#include "native/activity_provider.hpp"
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <iostream>
#include <mutex>
#include <stdexcept>
#include <thread>
namespace n=endfield::native;namespace m=endfield::modules;namespace a=endfield::app;
namespace {
unsigned checks{};void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(s);}
int names(std::string_view x,std::string_view y){return x.compare(y);}
struct Block {std::mutex mutex;std::condition_variable cv;bool entered{},released{};void wait(){std::unique_lock lock(mutex);entered=true;cv.notify_all();cv.wait(lock,[&]{return released;});}void await(){std::unique_lock lock(mutex);if(!cv.wait_for(lock,std::chrono::seconds(5),[&]{return entered;}))throw std::runtime_error("Fixture reader did not start");}void release(){std::lock_guard lock(mutex);released=true;cv.notify_all();}};
struct Release {std::shared_ptr<Block>b;~Release(){b->release();}};
void test(){std::atomic<unsigned>notifications{},systemReads{},appReads{};std::atomic<double>tick{100};const auto owner=std::this_thread::get_id();bool workerOnly=true,ownerOnly=true;a::UtilityExecutor executor([&]{++notifications;},1);m::ActivityState state(names);m::ActivitySamplingPlan plan;
 n::ActivityProbe::Readers readers;readers.system=[&]{workerOnly=workerOnly&&std::this_thread::get_id()!=owner;const auto num=++systemReads;m::ActivityRawSample raw;raw.uptime=tick;raw.timestamp=123;raw.cpu=m::ActivityCPU{num*10,num*10,num*80,0};raw.network=m::ActivityCounters{};raw.disk=m::ActivityCounters{};return raw;};readers.apps=[&]{workerOnly=workerOnly&&std::this_thread::get_id()!=owner;++appReads;m::ActivityAppsRaw raw;raw.uptime=tick;return raw;};
 unsigned systemPublications{},appPublications{};n::ActivityProbe probe(state,plan,executor,readers,[&](bool sys,bool apps){ownerOnly=ownerOnly&&std::this_thread::get_id()==owner;systemPublications+=sys;appPublications+=apps;});
 check(!probe.update(0)&&!executor.stats().started,"Construction/hidden idle starts no worker/provider");plan.start(100);check(probe.update(100),"Session start submits one baseline");executor.waitIdle();check(state.history().empty(),"Background worker cannot mutate owner model");executor.drain();check(state.history().size()==1&&!state.snapshot().cpuPercent,"First snapshot publishes unknown CPU baseline");const auto before=systemReads.load();for(unsigned k=0;k<1000;++k)check(!probe.update(100.5),"Idle animation frames never sample");check(systemReads==before&&notifications==1,"No idle polls/notifications");tick=105;probe.update(105);executor.waitIdle();executor.drain();check(state.snapshot().cpuPercent==20&&systemReads==2,"Five-second background sample derives complete counter delta");plan.setVisible(true,false,true,105.1);probe.update(105.1);executor.waitIdle();executor.drain();check(appReads==1&&systemReads==2,"Entering Apps immediately requests only its independent baseline");tick=106.1;probe.update(106.1);executor.waitIdle();executor.drain();check(systemReads==3&&appReads==2&&systemPublications==3&&appPublications==2,"Visible shared1Hz deadline coalesces system and app work");check(workerOnly&&ownerOnly,"Reader and publication thread boundaries preserved");
 auto unrelated=std::make_shared<Block>();Release free{unrelated};const auto route=executor.makeRoute();executor.submit(route,[unrelated]{unrelated->wait();},[](auto){});unrelated->await();tick=107.1;check(!probe.update(107.1)&&probe.stats().waiting,"Shared-queue backpressure retains one due request");unrelated->release();executor.waitIdle();executor.drain();check(probe.submitPending(),"Drain event retries without a new timer");executor.waitIdle();executor.drain();check(!probe.stats().waiting,"Completion clears retained due request");executor.invalidate(route);
 plan.setVisible(false,false,true,108);check(!probe.update(108)&&!plan.appsActive()&&plan.nextWakeTime()==113,"Hiding stops apps and retains only background system deadline");const auto priorApps=appReads.load();tick=113;probe.update(113);executor.waitIdle();executor.drain();check(appReads==priorApps,"Background never enumerates or samples apps");plan.stop();check(!probe.update(200)&&!plan.nextWakeTime(),"Shutdown stops all future sample work");
 auto blocked=std::make_shared<Block>();Release freeBlock{blocked};m::ActivityState isolated(names);m::ActivitySamplingPlan isolatedPlan;auto heldReaders=readers;heldReaders.system=[&,blocked]{blocked->wait();return readers.system();};unsigned late{};auto disposable=std::make_unique<n::ActivityProbe>(isolated,isolatedPlan,executor,heldReaders,[&](bool,bool){++late;});isolatedPlan.start(300);disposable->update(300);blocked->await();disposable.reset();blocked->release();executor.waitIdle();executor.drain();check(late==0&&isolated.history().empty(),"Destroyed probe suppresses late completion without waiting");
 auto restartBlock=std::make_shared<Block>();Release freeRestart{restartBlock};unsigned attempts{};heldReaders.system=[&,restartBlock]{if(++attempts==1)restartBlock->wait();return readers.system();};m::ActivitySamplingPlan restartPlan;m::ActivityState restartState(names);n::ActivityProbe restart(restartState,restartPlan,executor,heldReaders);restartPlan.start(400);restart.update(400);restartBlock->await();restartPlan.stop();restartPlan.start(401);check(!restart.update(401)&&restart.stats().waiting,"Restart while running retains exactly one fresh baseline request");restartBlock->release();executor.waitIdle();executor.drain();executor.waitIdle();executor.drain();check(restartState.history().size()==1&&!restartState.snapshot().cpuPercent&&restart.stats().discarded==1,"Stale generation is discarded and new baseline publishes once");
 m::ActivitySamplingPlan selfPlan;m::ActivityState selfState(names);std::unique_ptr<n::ActivityProbe>self;self=std::make_unique<n::ActivityProbe>(selfState,selfPlan,executor,readers,[&](bool,bool){self.reset();});selfPlan.start(500);self->update(500);executor.waitIdle();executor.drain();check(!self,"Callback can destroy its own probe without resubmission");
 #ifdef _WIN32
 check(n::compareWindowsActivityNames("Example2","Example10")<0,"Native natural comparator sorts digit runs numerically");check(n::compareWindowsActivityNames("활동","활동")==0,"Native comparator supports Korean identity");
 #endif
}
}
int main(){try{test();std::cout<<"PASS "<<checks<<" Activity shared-worker lifecycle checks (no live telemetry reads)\n";}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
