#include "native/activity_catalog.hpp"
#include "native/activity_disk.hpp"
#include <algorithm>
#include <cmath>
#include <iostream>
#include <limits>
#include <stdexcept>
namespace {namespace n=endfield::native;namespace m=endfield::modules;unsigned checks{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}template<class F>void rejects(F f){bool caught{};try{f();}catch(const std::invalid_argument&){caught=true;}check(caught,"Malformed catalog rejects");}
n::ActivityCatalogProcess p(unsigned pid,unsigned parent,unsigned start,std::string path,bool window=false,std::string app={}){return {pid,parent,start,path,app,"Synthetic "+std::to_string(pid),path,window};}
void catalog(){n::ActivityCatalogInventory data{{p(10,0,1,"c:/apps/a/a.exe",true),p(11,10,2,"c:/apps/a/helper.exe"),p(12,11,3,"c:/apps/a/deep/renderer.exe"),p(13,10,4,"c:/apps/another/tool.exe"),p(14,0,5,"c:/apps/a/a.exe"),p(15,10,6,"c:/apps/b/b.exe",true),p(20,0,7,"c:/package/main.exe",false,"package!App"),p(21,0,8,"c:/package/helper.exe",false,"package!App"),p(30,31,1,"c:/apps/z/helper.exe"),p(31,0,9,"c:/apps/z/z.exe",true)},true,{}};
    const auto got=n::buildActivityCatalog(data);check(got.apps.size()==4,"Package, desktop executable and exact app boundaries");check(got.apps[0].id=="app:package!App"&&got.apps[0].processIDs==std::vector<std::uint32_t>{20,21},"Exact AUMID groups packaged helpers");const auto&app=got.apps[1];check(app.processIDs==std::vector<std::uint32_t>{10,11,12,14},"Desktop root groups exact image and validated descendant helpers");check(!got.identities.contains(13)&&!got.identities.contains(30),"Directory neighbor and reused newer parent do not gain ownership");
    auto raced=data;raced.captureStartID=8;const auto captured=n::buildActivityCatalog(raced);check(captured.apps.size()==3&&!captured.identities.contains(31),"Process born after inventory began cannot inherit captured window/parent ownership");auto duplicate=data;duplicate.processes.push_back(data.processes[0]);rejects([&]{n::buildActivityCatalog(duplicate);});auto huge=data;huge.processes.resize(8193);rejects([&]{n::buildActivityCatalog(huge);});auto bad=data;bad.processes[0].imageKey="";rejects([&]{n::buildActivityCatalog(bad);});
    unsigned inventories{},processes{};bool failed{},unavailable{},reused{},protectedInventory{};n::ActivityCatalogSampler sampler({[&]{++inventories;auto value=data;value.complete=!failed;if(protectedInventory){std::erase_if(value.processes,[](const auto&p){return p.pid==10;});value.unreadablePIDs={10};}return value;},[&](std::uint32_t pid)->std::optional<n::ActivityCatalogReading>{++processes;if(unavailable&&pid==11)return {};auto identity=got.identities.at(pid);m::ActivityProcess reading;reading.pid=pid;reading.startID=identity.startID;reading.cpuTicks=processes*10;reading.memoryBytes=100;reading.startUptime=0;if(reused&&pid==11){++identity.startID;reading.startID=identity.startID;identity.imageKey="c:/unrelated.exe";}return n::ActivityCatalogReading{identity,reading};}});
    const auto first=sampler.sample(1,1);check(inventories==1&&first.processes.size()==8,"First serial sample discovers catalog and reads only members");sampler.sample(2,2);sampler.sample(5.99,5.99);check(inventories==1,"Catalog discovery never repeats inside source five seconds");unavailable=true;const auto protectedSample=sampler.sample(6,6);check(inventories==2&&protectedSample.members.at(app.id).size()==4&&!protectedSample.processes.contains(11),"Protected known process remains unknown in membership");unavailable=false;reused=true;const auto recycled=sampler.sample(7,7);check(!recycled.processes.contains(11)&&recycled.members.at(app.id).size()==4,"Reused PID cannot charge new process to cached app");failed=true;const auto missing=sampler.sample(11,11);check(!missing.inventoryComplete&&missing.apps.size()==4,"Failed inventory retains cards and marks metrics incomplete");failed=false;sampler.invalidate();check(inventories==3,"UI invalidation never performs IO");sampler.sample(12,12);check(inventories==4,"Apps reactivation resets five-second inventory immediately");protectedInventory=true;const auto preserved=sampler.sample(17,17);check(preserved.apps.size()==4&&preserved.members.at(app.id).size()==4,"Present-but-protected original app survives successful inventory refresh");rejects([&]{sampler.sample(11,11);});rejects([&]{sampler.sample(0,std::numeric_limits<double>::quiet_NaN());});
    auto rate=m::deriveActivityApps(protectedSample,&first);check(!rate.items[1].memoryBytes&&!rate.items[1].cpuPercent,"Source derivation propagates protected helper unknown without fake zeros");
}
void disk(){using D=n::ActivityDiskCounter;std::vector<D>reads{{"0 C:",100,true},{"1 D:",200,true},{"_Total",300,true}},writes{{"1 D:",20,true},{"_Total",30,true},{"0 C:",10,true}};auto got=n::activityDiskCounters(reads,writes);check(got&&got->size()==2&&got->at("0 C:")==m::ActivityBytes{100,10},"Pair raw physical-device bytes and exclude duplicate total");auto old=m::ActivityRawSample{};old.timestamp=old.uptime=1;old.disk=got;reads[0].bytes+=60;writes[2].bytes+=20;auto current=old;current.timestamp=current.uptime=2;current.disk=n::activityDiskCounters(reads,writes);auto rates=m::deriveActivity(current,&old);check(rates.diskRead==60&&rates.diskWrite==20,"Raw bytes derive original per-second rates once");auto reset=current;reset.uptime=3;reset.disk->at("0 C:").received=0;check(!m::deriveActivity(reset,&current).diskRead,"Counter reset produces baseline gap");auto topology=current;topology.uptime=3;topology.disk->erase("1 D:");check(!m::deriveActivity(topology,&current).diskRead,"Hotplug topology produces baseline gap");writes.pop_back();check(!n::activityDiskCounters(reads,writes),"Partial read/write instance set rejects");check(!n::activityDiskCounters({},{}),"No disks remains unknown");writes={{"0 C:",1,true},{"1 D:",2,true}};reads[0].valid=false;check(!n::activityDiskCounters(reads,writes),"Provider invalid data remains unknown");reads[0].valid=true;writes.push_back(writes[0]);check(!n::activityDiskCounters(reads,writes),"Duplicate instance rejects");std::vector<D>large(1026);check(!n::activityDiskCounters(large,{}),"Source1024disk bound enforced");large.clear();for(unsigned k=0;k<1025;++k)large.push_back({std::to_string(k),0,true});check(!n::activityDiskCounters(large,large),"1025 non-total disks cannot use the aggregate reserved slot");}
}
int main(){try{catalog();disk();std::cout<<"PASS "<<checks<<" injected Activity catalog/disk checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
