#include "native/activity_scene.hpp"
#include <atomic>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <filesystem>
#include <iostream>
#include <limits>
#include <new>
#include <set>
#ifdef _WIN32
#include <windows.h>
#include <objbase.h>
#include "native/activity_assets.hpp"
#include "native/layer_scene.hpp"
#include "native/layer_image_source.hpp"
#endif
namespace {std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {
namespace c=endfield::core;namespace m=endfield::modules;namespace n=endfield::native;using J=ehud::data::Json;unsigned checks{};double maximumError{};
void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(s);}template<class F>void rejects(F f,const char*s){bool rejected{};try{f();}catch(const std::exception&){rejected=true;}check(rejected,s);}
J read(const std::filesystem::path&p){std::ifstream file(p,std::ios::binary);check(bool(file),"Open explicit compact source oracle");std::string bytes{std::istreambuf_iterator<char>(file),{}};return J::parse(bytes,1024*1024);}
void closeEnough(double a,double b,double tolerance,const char*s){maximumError=std::max(maximumError,std::abs(a-b));check(std::abs(a-b)<=tolerance,s);}
m::ActivityState state(){m::ActivityState s([](auto a,auto b){return a.compare(b);});for(unsigned k=0;k<60;++k){m::ActivitySnapshot snapshot;snapshot.timestamp=k;snapshot.uptime=k;snapshot.cpuPercent=double(k%37);snapshot.memory=m::ActivityMemory{100+k,1000,20};snapshot.upload=double(k*10);snapshot.download=double(k*14);s.receive(std::move(snapshot));}m::ActivityAppsSnapshot apps;for(unsigned k=0;k<15;++k){m::ActivityApp app;app.identity={"app"+std::to_string(k),"Synthetic "+std::to_string(k),"icon"+std::to_string(k),{100+k}};app.cpuPercent=double(k*25);app.memoryBytes=1000000+k;apps.items.push_back(std::move(app));}s.receiveApps(std::move(apps));return s;}
const n::ActivitySurface&surface(const std::vector<n::ActivitySurface>&p,std::string_view id){for(const auto&v:p)if(v.id==id)return v;throw std::runtime_error("Missing Activity surface");}
void portable(const std::filesystem::path&path){auto s=state();m::ActivityAppearance a;auto art=m::prepareActivityArtwork(s,a);auto parts=n::prepareActivitySurfaces(art,a);check(parts.size()==17,"Overview retains four static cards, four graphs and nine chrome leaves");for(unsigned k=0;k<4;++k){const auto id="activity.graph."+std::to_string(k);auto original=art.overview["children"].array()[k]["children"].array()[3];check(original["id"].string()==id,"Original graph ordering");original["position"]=J::Array{0,0};check(surface(parts,id).content==original,"Independent graph raster keeps exact original descriptor paths/palette/gap masks");check(surface(parts,id).local==c::Matrix4::translation(97,69+k*60),"Exact graph placement within source row");check(surface(parts,"activity.row."+std::to_string(k)).content["children"].array().size()==6,"Static row glyph surface excludes animated graph");}
    const auto&tab=surface(parts,"activity:apps/tint");check(tab.content["shape"]["fillColor"]["sRGB"].array()[3].number()==.30&&tab.local==c::Matrix4::translation(100,25),"Original control tint and placement");
    s.setApps(true);s.scroll({30,100},27.5);art=m::prepareActivityArtwork(s,a);n::ActivityIcons icons{{"icon14",{"test.icon",7}}};parts=n::prepareActivitySurfaces(art,a,icons);check(art.rows.size()==6,"Six pooled source app cards");const auto&first=surface(parts,"activity.app.0");check(first.local==c::Matrix4::translation(12,56.5),"Fractional source row placement remains numeric");check(first.content["children"].array()[0]["contents"]["memoryImage"].string()=="test.icon","Only exact ready instance icon is inserted");check(first.content["children"].array()[0]["contentsGravity"].string()=="resizeAspect","Source app icon uses aspect fit without accent tint");
    std::set<std::string>ids;for(const auto&p:parts)check(ids.insert(p.id).second,"Unique stable retained plane identities");for(auto language:{c::Language::system,c::Language::english,c::Language::simplifiedChinese,c::Language::traditionalChinese,c::Language::japanese,c::Language::korean}){a.language=language;auto localized=n::prepareActivitySurfaces(m::prepareActivityArtwork(s,a),a);check(surface(localized,"activity.heading").content["text"]["font"]["familyName"].string()==".AppleSystemUIFont","Activity labels keep shared source font routing");}
    n::ActivityMotion motion;auto from=m::prepareActivityArtwork(state(),{}).graphs;motion.setGraphs(from,0,false);auto to=from;to[0].traces[0].points[0].y=3;to[0].traces[0].coverageCount=0;to[0].traces[0].marker={1,2};motion.setGraphs(to,1,true);auto sample=motion.graphs(1);check(sample[0].traces[0].points==from[0].traces[0].points&&sample[0].traces[0].coverageCount==0&&sample[0].traces[0].marker==c::Point{1,2},"Coverage and marker snap while path begins from old presentation");const auto interrupted=motion.graphs(1.1);motion.setGraphs(from,1.1,true);check(motion.graphs(1.1)[0].traces[0].points==interrupted[0].traces[0].points,"Interrupted graph retains current presentation origin");motion.settle();check(!motion.requiresFrames(2),"Settling removes finite graph demand");
    allocations=0;counting=true;for(unsigned k=0;k<2000;++k){const auto v=motion.graphs(2+k*.001);const auto p=motion.pages(2+k*.001);if(v[0].count!=1||!p.pages[0].visible)std::abort();}counting=false;check(allocations==0,"Retained graph/page sampling allocates no memory");
    rejects([&]{motion.graphs(std::numeric_limits<double>::quiet_NaN());},"Nonfinite Activity clock rejects");
    const auto oracle=read(path);for(const auto&row:oracle["handoffs"].array()){const auto phase=row["phase"].number();const bool incoming=row["direction"].integer()>0;n::ActivityMotion h;if(!incoming)h.select(true,0,false);h.select(incoming,1,true);const auto got=h.pages(1+phase*.26);for(unsigned page=0;page<2;++page){if(phase==1&&page!=unsigned(incoming))continue;const auto&expected=row["pages"].array()[page];closeEnough(got.pages[page].x,expected["x"].number(),.0001,"Actual CA handoff translation");const auto&b=expected["clip"].array();for(unsigned k=0;k<4;++k)closeEnough(std::array{got.pages[page].clip.x,got.pages[page].clip.y,got.pages[page].clip.width,got.pages[page].clip.height}[k],b[k].number(),.0001,"Actual CA complementary handoff clipping");}}
    for(const auto&row:oracle["graphs"].array()){std::array<m::ActivityGraphPlan,4>old{},next{};old[0].count=next[0].count=1;for(unsigned k=0;k<60;++k){const auto&a=row["from"].array()[k].array(),&b=row["to"].array()[k].array();old[0].traces[0].points[k]={a[0].number(),a[1].number()};next[0].traces[0].points[k]={b[0].number(),b[1].number()};}n::ActivityMotion graph;graph.setGraphs(old,0,false);graph.setGraphs(next,1,true);const auto got=graph.graphs(1+row["phase"].number()*.32);check(row["points"].array().size()==60,"Original graph morph keeps sixty points");for(unsigned k=0;k<60;++k){const auto&p=row["points"].array()[k].array();closeEnough(got[0].traces[0].points[k].x,p[0].number(),.0001,"Actual CA graph X");closeEnough(got[0].traces[0].points[k].y,p[1].number(),.0001,"Actual CA graph Y");}}
}
#ifdef _WIN32
struct Window{HWND hwnd{};Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"OwnedActivitySceneFixture";check(RegisterClassW(&c)!=0,"Register owned Activity fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,c.lpszClassName,L"Owned fixture",WS_POPUP,0,0,400,334,nullptr,nullptr,c.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Synthetic HWND remains hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);UnregisterClassW(L"OwnedActivitySceneFixture",GetModuleHandleW(nullptr));}};
void native(const std::filesystem::path&shader,const std::filesystem::path&assets){Window window;n::Renderer r;r.initialize(window.hwnd,400,334,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests});r.setCamera(n::layerViewportProjection(400,334));n::LayerRasterizer raster;n::LayerRasterOptions options;options.pixelsPerPoint=1;n::LayerImageSource images;options.memoryImages=&images;n::NativeActivityAssets source(assets);auto model=state();n::NativeActivityScene scene(model,raster,options,{},source.sortSamples());n::LayerComposition composition;bool done{};struct Cleanup{n::Renderer&r;n::LayerComposition&c;n::NativeActivityScene&s;bool&done;~Cleanup(){if(done)return;try{c.detach(r);s.releaseResources(r);}catch(...){r.reset();}}}cleanup{r,composition,scene,done};
    const auto frame=[&](double t,c::Matrix4 world=c::Matrix4{},bool animate=false){scene.syncContent(t,animate);scene.updatePose({world,1,t,{},{}});scene.uploadAnimations(r);composition.setEntries(r,scene.entries());composition.present(r);scene.collectRetired(r);};
    frame(0);r.draw(false);check(!r.readback().pixels.empty(),"Native Activity draws original isolated chart planes");for(const auto&e:scene.entries())check(e.scene->report().unsupported.empty(),"All Activity source effects are supported");
    scene.setFeedback(c::Point{100,25},false,false,.01);frame(.01);check(!scene.requiresFrames(.01),"Rounded source corner outside the control path does not hover");scene.setFeedback(c::Point{120,35},true,false,.1);frame(.16);const auto rs=raster.stats();const auto gs=r.stats();allocations=0;counting=true;try{for(unsigned k=0;k<120;++k){auto world=c::Matrix4::rotation(.01*k/120,.02,0);frame(1+k/60.,world);}}catch(...){counting=false;throw;}counting=false;check(allocations==0,"120 warm Activity pose/feedback frames allocate nothing");check(raster.stats().rasterizations==rs.rasterizations&&r.stats().textureUploads==gs.textureUploads,"Warm Activity frames reuse all text/graph textures");
    auto update=model.snapshot();update.timestamp=61;update.uptime=61;update.cpuPercent=88;update.memory=m::ActivityMemory{800,1000,50};model.receive(update);frame(4,{},true);const auto textLayouts=raster.stats().textLayoutsCreated;const auto before=scene.stats();for(unsigned k=1;k<=20;++k)frame(4+k*.016);const auto after=scene.stats();check(after.graphRasters>before.graphRasters&&after.graphRasters-before.graphRasters<=80,"Finite source graph morph touches at most four tiny surfaces per frame");check(raster.stats().textLayoutsCreated==textLayouts,"Graph morph never reshapes static labels");check(!scene.requiresFrames(4.4),"Graph motion stops after exact .32s");std::cout<<"Activity graph morph: rasters="<<after.graphRasters-before.graphRasters<<" bytes="<<after.graphPixelBytes-before.graphPixelBytes<<" total_ms="<<(after.graphRasterSeconds-before.graphRasterSeconds)*1000<<" max_ms="<<after.maximumGraphRasterSeconds*1000<<'\n';
    model.setApps(true);scene.syncContent(5);scene.selectPage(true,5,true);frame(5);frame(5.13);frame(5.26);check(!scene.requiresFrames(5.3),"Complementary source page handoff settles");
    std::array<std::uint8_t,32*32*4>icon{};for(std::size_t k=0;k<icon.size();k+=4){icon[k]=90;icon[k+1]=20;icon[k+2]=120;icon[k+3]=255;}images.publish("activity.fixture.icon",1,32,32,icon);scene.setIcons({{"icon14",{"activity.fixture.icon",1}}});frame(5.4);r.draw(false);const auto iconPixels=r.readback();const auto pixel=std::size_t(106)*iconPixels.rowBytes+28*4;check(std::abs(int(iconPixels.pixels[pixel])-120)<=2&&std::abs(int(iconPixels.pixels[pixel+1])-20)<=2&&std::abs(int(iconPixels.pixels[pixel+2])-90)<=2,"Ready original app icon paints at source18point slot without recoloring");const auto rowRaster=raster.stats();model.scroll({30,100},.25);frame(6);check(raster.stats().rasterizations==rowRaster.rasterizations,"Fractional row scroll changes placement only");
    const auto count=scene.stats().surfaces;for(unsigned k=0;k<15;++k){model.scroll({30,100},49);frame(6.1+k*.01);}check(scene.stats().surfaces==count&&count<=48,"App list retains six pooled row surfaces under scrolling");
    model.sort(m::ActivitySort::name);scene.syncContent(7);scene.revealSort(-1,7,true);for(unsigned k=0;k<17;++k)frame(7+k/60.);check(scene.stats().maskRasters>0&&!scene.requiresFrames(7.4),"Sort uses own original curved source mask and finite demand");frame(7.4);const auto settledRasters=raster.stats().rasterizations;for(unsigned k=0;k<60;++k)frame(8+k/60.);check(raster.stats().rasterizations==settledRasters,"Settled sort retires mask and performs no raster work");
    const auto offset=model.scrollOffset();m::ActivityAppearance light;light.dark=false;light.language=c::Language::korean;scene.setAppearance(light);frame(10);check(model.scrollOffset()==offset&&model.sortKey()==m::ActivitySort::name,"Preference event preserves source app state");composition.detach(r);check(scene.releaseResources(r)&&r.stats().textures==0&&r.stats().meshes==0,"Activity resources retire through shared composition");done=true;r.reset();
}
#endif
}
#ifdef _WIN32
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==4,"Pass HLSL, motion oracle and Activity resource root");portable(argv[2]);native(argv[1],std::filesystem::absolute(argv[3]));CoUninitialize();std::cout<<"PASS "<<checks<<" Activity scene checks, max source error "<<maximumError<<'\n';return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(int argc,char**argv){try{check(argc==2,"Pass compact Activity motion oracle");portable(argv[1]);std::cout<<"PASS "<<checks<<" Activity portable scene checks, max source error "<<maximumError<<'\n';return 0;}catch(const std::exception&e){counting=false;std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
