#include "modules/activity_state.hpp"
#include "modules/activity_presentation.hpp"
#include "core/data/json.hpp"
#include <atomic>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <limits>
#include <new>
#include <stdexcept>
namespace m=endfield::modules;using J=ehud::data::Json;
static std::atomic<std::size_t>allocations{};
void*operator new(std::size_t n){++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void operator delete(void*p)noexcept{std::free(p);}void operator delete(void*p,std::size_t)noexcept{std::free(p);}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete[](void*p)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
namespace {
unsigned checks{};void check(bool b,const char*m){++checks;if(!b)throw std::runtime_error(m);}void near(double a,double b,const char*m){check(std::abs(a-b)<1e-10,m);}
template<class F>void rejects(F f,const char*m){bool threw{};try{f();}catch(const std::invalid_argument&){threw=true;}check(threw,m);}
int names(std::string_view a,std::string_view b){return a.compare(b);}
std::optional<double>optional(const J&j){return j.isNull()?std::nullopt:std::optional<double>(j.number());}
void same(std::optional<double>a,const J&b){check(bool(a)==!b.isNull(),"Source optional state matches");if(a)near(*a,b.number(),"Source numeric value matches");}
m::ActivityCPU cpu(const J&v){const auto&a=v.array();return {std::uint64_t(a[0].integer()),std::uint64_t(a[1].integer()),std::uint64_t(a[2].integer()),std::uint64_t(a[3].integer())};}
const J&find(const J&root,std::string_view id){if(root["id"].isString()&&root["id"].string()==id)return root;for(const auto&child:root["children"].array()){const auto&found=find(child,id);if(!found.isNull())return found;}static const J empty;return empty;}
void oracle(const char*path){std::ifstream file(path);std::string bytes{std::istreambuf_iterator<char>(file),{}};const auto data=J::parse(bytes,1024*1024);for(const auto&c:data["cpu"].array()){m::ActivityRawSample previous;previous.uptime=10;previous.cpu=cpu(c["old"]);auto current=previous;current.uptime=11;current.cpu=cpu(c["now"]);same(m::deriveActivity(current,&previous).cpuPercent,c["percent"]);}
 for(const auto&c:data["memory"].array()){const auto&a=c["args"].array();const auto value=m::activityMacMemory(a[0].integer(),a[1].integer(),a[2].integer(),a[3].integer(),a[4].integer(),a[5].integer());check(bool(value)==!c["result"].isNull(),"Source memory availability");if(value){const auto&r=c["result"].array();check(value->used==std::uint64_t(r[0].integer())&&value->total==std::uint64_t(r[1].integer())&&value->compressed==std::uint64_t(r[2].integer()),"Source resident physical footprint excludes purgeable cache");}}
 for(const auto&c:data["graphs"].array()){std::vector<std::optional<double>>values;std::vector<double>times;for(const auto&v:c["values"].array())values.push_back(optional(v));for(const auto&v:c["times"].array())times.push_back(v.number());const auto trace=m::activityGraph(values,100,times);for(unsigned n=0;n<60;++n){near(trace.points[n].x,c["points"].array()[n].array()[0].number(),"Original CA graph x");near(trace.points[n].y,c["points"].array()[n].array()[1].number(),"Original CA graph y");}check(trace.coverageCount==c["coverage"].array().size(),"Original gap mask count");for(std::size_t n=0;n<trace.coverageCount;++n){const auto&r=trace.coverage[n];const auto&e=c["coverage"].array()[n].array();near(r.x,e[0].number(),"Coverage x");near(r.y,e[1].number(),"Coverage y");near(r.width,e[2].number(),"Coverage width");near(r.height,e[3].number(),"Coverage height");}check(trace.markerVisible!=c["hidden"].boolean(),"Original marker visibility");}
 for(const auto&c:data["rates"].array()){m::ActivityRawSample old;old.uptime=100;old.cpu=m::ActivityCPU{1,2,3,4};old.network=m::ActivityCounters{{"en0",{10,20}}};old.disk=m::ActivityCounters{};auto now=old;now.uptime+=c["elapsed"].number();now.cpu=m::ActivityCPU{2,4,6,8};now.network=m::ActivityCounters{{c["topology"].boolean()?"en1":"en0",{30,70}}};const auto got=m::deriveActivity(now,&old);const auto&e=c["result"];same(got.cpuPercent,e["cpu"]);same(got.upload,e["upload"]);same(got.download,e["download"]);same(got.diskRead,e["read"]);same(got.diskWrite,e["write"]);check(got.statusNotes.size()==e["notes"].array().size(),"Original status notes");for(std::size_t n=0;n<got.statusNotes.size();++n)check(got.statusNotes[n]==e["notes"].array()[n].string(),"Original note text/order");}
 for(const auto&c:data["formats"].array()){const auto value=optional(c["value"]);check(m::activityBytes(value)==c["bytes"].string(),"Source decimal byte formatter");check(m::activityRate(value)==c["rate"].string(),"Source rate formatter");check(m::activityPercent(value)==c["percent"].string(),"Source machine percent formatter");}
 for(const auto&c:data["apps"].array()){const auto mode=c["mode"].integer();m::ActivityAppsRaw old;old.uptime=10;old.secondsPerCPUTick=.01;old.apps.push_back({"app","Example","",{8,7,7}});old.members["app"]={7,8};old.processes[7]={7,1,100,1000,1,100,100};old.processes[8]={8,2,200,2000,1,200,200};auto now=old;now.uptime=mode==6?15:mode==7?15.0001:11;now.processes[7].cpuTicks=250;now.processes[7].diskRead=150;now.processes[8].cpuTicks=300;now.processes[8].diskWrite=300;if(mode==1)now.processes.erase(8);if(mode==2)now.processes[8].startID=3;if(mode==3)now.members["app"]={7};now.network=m::ActivityAppNetwork{mode==5?6:now.uptime,5,{{7,{10,20}}},mode==4?std::set<std::uint32_t>{8}:std::set<std::uint32_t>{}};const auto value=m::deriveActivityApps(now,&old).items[0];same(value.cpuPercent,c["cpu"]);same(value.memoryBytes?std::optional<double>(double(*value.memoryBytes)):std::nullopt,c["memory"]);same(value.diskRead,c["read"]);same(value.diskWrite,c["write"]);same(value.upload,c["upload"]);same(value.download,c["download"]);check(value.statusNotes.size()==c["notes"].array().size(),"Source app notes count");for(std::size_t n=0;n<value.statusNotes.size();++n)check(value.statusNotes[n]==c["notes"].array()[n].string(),"Source app note ordering");}}
void derivation(){const auto max=std::numeric_limits<std::uint64_t>::max();check(!m::activityMacMemory(100,4096,max,0,2,0),"Resident sum overflow is unavailable");check(!m::activityMacMemory(max,max,2,0,0,0),"Resident multiply overflow is unavailable");m::ActivityRawSample old;old.uptime=1;old.cpu=m::ActivityCPU{0,0,0,0};auto now=old;now.uptime=2;now.cpu=m::ActivityCPU{max,1,0,0};check(!m::deriveActivity(now,&old).cpuPercent,"CPU delta overflow is unavailable");old.network=m::ActivityCounters{{"a",{4,5}}};now.network=m::ActivityCounters{{"a",{3,9}}};check(!m::deriveActivity(now,&old).download,"Counter reset cannot cause spike");
 m::ActivityAppsRaw a;a.timestamp=1;a.uptime=10;a.secondsPerCPUTick=.01;a.apps.push_back({"app","Example","",{8,7,7}});a.members["app"]={7,8};a.processes[7]={7,1,100,1000,1,100,100};a.processes[8]={8,2,200,2000,1,200,200};auto b=a;b.uptime=11;b.processes[7].cpuTicks+=150;b.processes[8].cpuTicks+=100;b.processes[7].diskRead=150;b.processes[8].diskWrite=300;auto result=m::deriveActivityApps(b,&a);check(result.items[0].cpuPercent==250&&result.items[0].memoryBytes==3000&&result.items[0].diskRead==50&&result.items[0].diskWrite==100,"App sums complete membership;100% is one CPU");b.processes[8].startID=3;check(!m::deriveActivityApps(b,&a).items[0].cpuPercent,"Reused PID cannot inherit CPU baseline");b=a;b.uptime=16;check(!m::deriveActivityApps(b,&a).items[0].cpuPercent,"Delayed app samples over5s leave a gap");b=a;b.uptime=11;b.processes.erase(8);result=m::deriveActivityApps(b,&a);check(!result.items[0].memoryBytes&&!result.items[0].cpuPercent,"Protected missing member makes whole app unavailable");b=a;b.uptime=11;b.processes[7].diskRead.reset();result=m::deriveActivityApps(b,&a);check(result.items[0].cpuPercent==0&&!result.items[0].diskRead,"Unsupported Windows disk does not become fake0 or block known CPU");b.network=m::ActivityAppNetwork{11,5,{{7,{10,20}}},{}};result=m::deriveActivityApps(b,&a);check(result.items[0].download==10&&result.items[0].upload==20,"Complete absent network PID means source0");b.network->unknownPIDs.insert(8);check(!m::deriveActivityApps(b,&a).items[0].download,"Unknown network owner stays unknown");
 m::ActivityApp x,y,z;x.identity={"a","A","",{}};y.identity={"b","B","",{}};z.identity={"c","C","",{}};x.cpuPercent=1;z.cpuPercent=2;std::vector items{x,y,z};m::sortActivityApps(items,m::ActivitySort::cpu,false,names);check(items[0].identity.id=="a"&&items[2].identity.id=="b","Unknown sorts last ascending");m::sortActivityApps(items,m::ActivitySort::cpu,true,names);check(items[0].identity.id=="c"&&items[2].identity.id=="b","Unknown sorts last descending");}
void state(){m::ActivityState state(names);for(unsigned n=0;n<90;++n){m::ActivitySnapshot v;v.timestamp=n;v.uptime=n;v.cpuPercent=n;state.receive(v);}check(state.history().size()==60&&state.history().front().uptime==30,"History bounded60 and retained in session");m::ActivityAppsSnapshot apps;apps.uptime=100;for(unsigned n=0;n<256;++n){m::ActivityApp item;item.identity={std::to_string(n),"App "+std::to_string(n),"",{}};item.cpuPercent=n;apps.items.push_back(item);}state.receiveApps(apps);check(!state.scroll({20,100},1),"Overview doesn't consume Apps scroll");state.setApps(true);check(state.visibleRows().count==6,"Exactly six source pooled rows");state.scroll({20,100},49.25);auto rows=state.visibleRows();near(rows.rows[0].rect.y,-.25,"Fractional scroll retained");check(rows.rows[0].index==1&&rows.scrollbar.has_value(),"Scroll virtualizes by source49point pitch");const auto oldContent=state.appsContentRevision();state.scroll({20,100},.125);check(state.appsContentRevision()==oldContent,"Sub-row scroll updates placement without invalidating text content");const auto memory=allocations.load();for(unsigned n=0;n<10000;++n){state.visibleRows();state.maximumOffset();state.history();}check(allocations==memory,"Retained row/graph/history queries allocate nothing");state.sort(m::ActivitySort::name);check(!state.descending()&&state.scrollOffset()==0,"New name sort ascends and resets offset");state.sort(m::ActivitySort::name);check(state.descending(),"Same sort toggles direction");state.scroll({20,100},1e10);const auto revision=state.revision();check(state.scroll({20,100},1)&&state.revision()==revision,"At-boundary wheel consumed without rebuilding");auto bad=apps;bad.items[0].cpuPercent=std::numeric_limits<double>::quiet_NaN();rejects([&]{state.receiveApps(bad);},"NaN metrics rejected before sorting");check(state.revision()==revision,"Rejected app update preserves state");
 m::ActivityAppearance appearance;auto art=m::prepareActivityArtwork(state,appearance);check(art.rows.size()==5&&art.actions.size()==7,"End Apps page has bounded remaining rows and7actions");check(art.overview["children"].array().empty()&&art.graphs[0].count==0,"Apps updates never rebuild hidden overview paths");state.setApps(false);art=m::prepareActivityArtwork(state,appearance);check(find(art.overview,"activity.title.1")["text"]["string"].string()=="RAM","RAM label preserved");for(auto lang:{endfield::core::Language::english,endfield::core::Language::simplifiedChinese,endfield::core::Language::traditionalChinese,endfield::core::Language::japanese,endfield::core::Language::korean}){appearance.language=lang;appearance.dark=!appearance.dark;appearance.accent={.3,.8,.2,1};const auto localized=m::prepareActivityArtwork(state,appearance);check(find(localized.overview,"activity.title.1")["text"]["string"].string()=="RAM","Every locale retains RAM");const auto&color=find(localized.overview,"activity.tick.0")["backgroundColor"]["sRGB"].array();near(color[0].number(),.98,"Yellow graph independent of theme/accent");check(find(localized.overview,"activity.title.1")["text"]["font"]["familyName"].string()==".AppleSystemUIFont","Shared Noto resolver inherits original system descriptor");check(localized.rows.empty()&&localized.apps["children"].array().empty(),"Overview updates never rebuild hidden Apps rows");}
 m::ActivitySamplingPlan plan;check(!plan.nextWakeTime(),"No sampler until explicit session start");plan.start(10);auto demand=plan.takeDue(10);check(demand.system&&demand.resetSystem&&!demand.apps&&plan.nextWakeTime()==15,"Source background5s starts with baseline");plan.setVisible(true,false,false,11);check(plan.nextWakeTime()==12,"Activity visible changes same deadline to1Hz");plan.setVisible(false,true,false,11);check(plan.nextWakeTime()==12,"Charge alert shares same demand");plan.setVisible(true,false,true,12);demand=plan.takeDue(12);check(demand.system&&demand.apps&&demand.resetApps,"Apps first request uses independent baseline");plan.setVisible(false,false,true,12.1);check(!plan.appsActive()&&plan.nextWakeTime()==17.1,"Hidden Apps off while system history continues5s");plan.stop();check(!plan.nextWakeTime(),"Shutdown removes all deadlines");rejects([&]{plan.start(std::numeric_limits<double>::infinity());},"Nonfinite clock rejected");
 std::array<std::optional<double>,3>samples{1,{},2};std::array<double,3>times{100,101,102};const auto before=allocations.load();for(unsigned n=0;n<10000;++n){const auto g=m::activityGraph(samples,100,times);check(g.coverageCount==0&&g.markerVisible,"Absent graph samples never bridged");}check(allocations==before,"Fixed60vertex graph evaluator allocates nothing");}
}
int main(int argc,char**argv){try{derivation();state();if(argc==2)oracle(argv[1]);std::cout<<"PASS "<<checks<<" Activity source state/presentation checks\n";}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
