#include "modules/app_shortcut_motion.hpp"
#include "core/data/json.hpp"
#include "native/app_shortcut_assets.hpp"
#include <fstream>
#include <iostream>
#include <cmath>
#include <filesystem>
namespace {unsigned checks{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}void run(const std::filesystem::path&p,const std::filesystem::path&resource){using namespace endfield;std::ifstream f(p);const std::string bytes((std::istreambuf_iterator<char>(f)),{});const auto j=ehud::data::Json::parse(bytes,1024*1024);native::NativeAppShortcutAssets assets(resource);double error{},pathError{};for(const auto&r:j["rows"].array()){const double phase=r["phase"].number();const bool incoming=r["incoming"].boolean();modules::ShortcutScreenTransition t{1,0,int(r["direction"].integer()),true};const auto s=modules::shortcutScreenSample(t,phase*.26);const auto expected=r["matrix"].array();const auto path=(incoming?assets.arrival():assets.departure())->sample(t.direction,phase);const auto&commands=r["path"].array();check(commands.size()==path.opcodeCount,"Actual CA source mask topology");std::size_t at{};for(std::size_t k=0;k<commands.size();++k){const auto&command=commands[k];const auto op=command["op"].string();check(path.opcodes[k]==(op=="move"?0:op=="line"?1:op=="quadratic"?2:op=="cubic"?3:4),"Actual CA source mask opcode");for(const auto&point:command["points"].array())for(const auto&coordinate:point.array()){const auto d=std::abs(path.coordinates[at++]-coordinate.number());pathError=std::max(pathError,d);check(d<.02,"Independent original CA curve coordinates within measured band");}}check(at==path.coordinateCount,"Source mask coordinate shape");auto actual=incoming?s.incoming:s.outgoing;if(phase==1&&!incoming)actual=core::Matrix4::translation(-18*t.direction,0,-28);for(unsigned n=0;n<16;++n){error=std::max(error,std::abs(actual.values[n]-expected[n].number()));check(std::abs(actual.values[n]-expected[n].number())<1e-10,"Original detached CA component transform");}}modules::ShortcutScreenTransition t{1,4,-1,true};check(modules::shortcutScreenSample(t,4).active&&!modules::shortcutScreenSample(t,4.26).active,"Source screen duration is finite .26 seconds");bool rejected{};try{modules::shortcutScreenSample(t,NAN);}catch(const std::invalid_argument&){rejected=true;}check(rejected,"Invalid animation time is rejected");std::cout<<"PASS "<<checks<<" App Shortcut motion checks; max matrix error "<<error<<"; max control residual "<<pathError<<'\n';}}
int main(int argc,char**argv){try{check(argc==3,"Pass actual detached motion fixture and production assets");run(argv[1],std::filesystem::absolute(argv[2]));return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
