#include "native/app_notification_identity.hpp"
#include <array>
#include <iostream>
#include <stdexcept>

namespace {using namespace endfield::native;unsigned checks{};
void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(s);}
AppNotificationIdentity fixture(){return {"EndfieldHUD.Test.Calendar","{11111111-2222-4333-8444-555555555555}","C:\\Owned Fixture\\fixture.exe","C:\\Owned Fixture","C:\\Owned Fixture\\fixture.lnk"};}
void portable(){const auto i=fixture();check(validAppNotificationIdentity(i),"Explicit app identity uses a full stable CLSID and ordinary absolute paths");check(appNotificationServerCommand(i)=="\"C:\\Owned Fixture\\fixture.exe\" --notification-activation","Activation-only server command quotes its exact executable and fixed argument");
    for(const auto*id:{""," bad","a b","a/b",".a","a.","a\n"})check(!validAppNotificationID(id),"Malformed app IDs decline before platform IO");check(!validAppNotificationID(std::string(129,'a'))&&validAppNotificationID(std::string(128,'a')),"AUMID length bound is explicit without truncation");
    auto bad=i;bad.activatorCLSID="11111111-2222-4333-8444-555555555555";check(!validAppNotificationIdentity(bad),"Missing GUID braces decline rather than using another activator");bad=i;bad.executable="relative.exe";check(!validAppNotificationIdentity(bad),"Installer never resolves a relative executable against ambient working directory");bad=i;bad.shortcut="C:\\Owned Fixture\\fixture.url";check(!validAppNotificationIdentity(bad),"Registration requires an explicit Shell shortcut");bad=i;bad.shortcut="C:\\Owned Fixture\\..\\other.lnk";check(!validAppNotificationIdentity(bad),"Dot-component shortcut aliases are rejected");bad=i;bad.appUserModelID="invalid id";bool rejected{};try{(void)appNotificationServerCommand(bad);}catch(const std::invalid_argument&){rejected=true;}check(rejected,"No command is emitted for an invalid identity");
}
}
#ifdef _WIN32
#include <filesystem>
#include <fstream>
#include <thread>
#include <wrl/client.h>
#include <shobjidl.h>
namespace {using Microsoft::WRL::ComPtr;
void ok(HRESULT hr,const char*s){if(FAILED(hr)){std::cerr<<s<<" HRESULT="<<std::hex<<static_cast<unsigned long>(hr)<<std::dec<<'\n';throw std::runtime_error(s);}++checks;}
struct Apartment{Apartment(){ok(CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED),"Owned test STA initializes");}~Apartment(){CoUninitialize();}};
std::string utf8(const std::wstring&s){const auto n=WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,s.data(),static_cast<int>(s.size()),nullptr,0,nullptr,nullptr);if(!n)throw std::runtime_error("fixture UTF8");std::string out(static_cast<std::size_t>(n),'\0');check(WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,s.data(),static_cast<int>(s.size()),out.data(),n,nullptr,nullptr)==n,"Fixture paths preserve UTF8");return out;}
struct Owned{
    std::filesystem::path directory;std::wstring registryPath;HKEY classes{};HWND window{};
    Owned(){GUID id{};ok(CoCreateGuid(&id),"Fixture UUID creates no installed app identity");wchar_t value[40]{};check(StringFromGUID2(id,value,40)>0,"Fixture GUID formats");wchar_t temporary[32768]{};check(GetTempPathW(32768,temporary)>0,"Own temporary directory root exists");directory=std::filesystem::path(temporary)/(std::wstring(L"Endfield-notification-")+value);check(std::filesystem::create_directory(directory),"Unique owned fixture directory is created");registryPath=L"Software\\EndfieldHUD.Tests.NotificationIdentity."+std::wstring(value);DWORD disposition{};check(RegCreateKeyExW(HKEY_CURRENT_USER,registryPath.c_str(),0,nullptr,REG_OPTION_VOLATILE,KEY_ALL_ACCESS,nullptr,&classes,&disposition)==ERROR_SUCCESS&&disposition==REG_CREATED_NEW_KEY,"Tests create a private volatile Classes substitute, never HKCU Software Classes");window=CreateWindowExW(0,L"STATIC",L"owned hidden notification fixture",WS_POPUP,0,0,40,40,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);check(window&&!IsWindowVisible(window),"Activation route uses only an owned hidden HWND");}
    ~Owned(){if(window)DestroyWindow(window);if(classes)RegCloseKey(classes);if(!registryPath.empty())RegDeleteTreeW(HKEY_CURRENT_USER,registryPath.c_str());std::error_code e;std::filesystem::remove_all(directory,e);}
};
void registration(Owned&owned){const auto exe=owned.directory/L"fixture.exe",lnk=owned.directory/L"fixture.lnk";std::ofstream(exe,std::ios::binary)<<"synthetic, never executed";AppNotificationIdentity identity=fixture();identity.executable=utf8(exe.wstring());identity.workingDirectory=utf8(owned.directory.wstring());identity.shortcut=utf8(lnk.wstring());
    AppNotificationRegistration state{};ok(inspectAppNotificationRegistration(owned.classes,identity,&state),"Private registration inspection succeeds");check(state==AppNotificationRegistration::missing,"Fresh fixture has no shortcut or binding");ok(installAppNotificationIdentity(owned.classes,identity,AppNotificationRegistryLifetime::volatileFixture),"Explicit isolated installation creates matching shortcut metadata and private binding");ok(inspectAppNotificationRegistration(owned.classes,identity,&state),"Installed metadata inspection succeeds");check(state==AppNotificationRegistration::matching,"Full executable, argument, AUMID and activator properties match");
    {ComPtr<IShellLinkW>link;ok(CoCreateInstance(CLSID_ShellLink,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&link)),"Read only the temporary shortcut");ComPtr<IPersistFile>persist;ok(link.As(&persist),"Temporary shortcut supports persistence");ok(persist->Load(lnk.c_str(),STGM_READ),"Load owned shortcut metadata without executing it");std::array<wchar_t,256>arguments{};ok(link->GetArguments(arguments.data(),static_cast<int>(arguments.size())),"Read owned shortcut launch arguments");check(arguments[0]==L'\0',"Normal Start Menu launch never carries COM activation-only mode");}
    const auto stamp=std::filesystem::last_write_time(lnk);ok(installAppNotificationIdentity(owned.classes,identity,AppNotificationRegistryLifetime::volatileFixture),"Matching installation is idempotent");check(std::filesystem::last_write_time(lnk)==stamp,"Idempotent install never rewrites an existing shortcut");auto conflicting=identity;conflicting.appUserModelID="EndfieldHUD.Foreign";check(FAILED(installAppNotificationIdentity(owned.classes,conflicting,AppNotificationRegistryLifetime::volatileFixture))&&FAILED(removeAppNotificationIdentity(owned.classes,conflicting)),"An unrelated shortcut identity cannot be overwritten or removed");check(std::filesystem::exists(lnk),"Conflicting operations retain the installed shortcut");
    const auto child=L"CLSID\\"+std::wstring(identity.activatorCLSID.begin(),identity.activatorCLSID.end())+L"\\ForeignSibling";HKEY foreign{};check(RegCreateKeyExW(owned.classes,child.c_str(),0,nullptr,REG_OPTION_VOLATILE,KEY_ALL_ACCESS,nullptr,&foreign,nullptr)==ERROR_SUCCESS,"Independent test-owned sibling metadata is staged");RegCloseKey(foreign);
    {const auto reader=CreateFileW(lnk.c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);check(reader!=INVALID_HANDLE_VALUE,"Owned reader deliberately denies deletion");const auto removed=removeAppNotificationIdentity(owned.classes,identity);CloseHandle(reader);check(removed==HRESULT_FROM_WIN32(ERROR_SHARING_VIOLATION)&&std::filesystem::exists(lnk),"Busy matching shortcut preserves both identity components rather than deleting by pathname");ok(inspectAppNotificationRegistration(owned.classes,identity,&state),"Failed removal preserves exact metadata");check(state==AppNotificationRegistration::matching,"Blocked deletion keeps the matching server binding");}
    ok(removeAppNotificationIdentity(owned.classes,identity),"Matching uninstallation removes only exact shortcut and LocalServer32 default");check(!std::filesystem::exists(lnk),"Matched shortcut is removed by opened object handle");check(RegOpenKeyExW(owned.classes,child.c_str(),0,KEY_READ,&foreign)==ERROR_SUCCESS,"Unknown sibling registration is preserved");RegCloseKey(foreign);ok(inspectAppNotificationRegistration(owned.classes,identity,&state),"Removed registration inspection succeeds");check(state==AppNotificationRegistration::missing,"Uninstallation does not leave a default server binding");
    std::ofstream(lnk,std::ios::binary)<<"foreign shortcut bytes";check(FAILED(installAppNotificationIdentity(owned.classes,identity,AppNotificationRegistryLifetime::volatileFixture)),"A foreign existing shortcut is never overwritten to repair a missing binding");check(std::filesystem::file_size(lnk)==22,"Failed repair leaves foreign shortcut bytes unchanged");std::filesystem::remove(lnk);
    auto impossible=identity;impossible.shortcut=utf8((owned.directory/L"absent"/L"fixture.lnk").wstring());check(FAILED(installAppNotificationIdentity(owned.classes,impossible,AppNotificationRegistryLifetime::volatileFixture)),"A missing caller-owned shortcut parent declines rather than creating ambient folders");ok(inspectAppNotificationRegistration(owned.classes,identity,&state),"Failed fresh installation leaves original binding absent");check(state==AppNotificationRegistration::missing,"Failed installation does not create a runnable partial binding");
}
void activation(Owned&owned){const AppNotificationActivationRoute route{owned.window,WM_APP+0x31,42};auto server=std::make_unique<NativeAppNotificationActivation>("EndfieldHUD.Test.Calendar","{11111111-2222-4333-8444-555555555555}",route);check(!server->registered(),"Construction does not register a COM server or an installed app identity");ComPtr<INotificationActivationCallback>callback;ok(server->createCallback(&callback),"Hidden fixture obtains the actual activation callback without class registration");
    ok(callback->Activate(L"EndfieldHUD.Test.Calendar",L"{\"type\":\"calendar\",\"title\":\"中文😀\"}",nullptr,0),"Bounded Unicode activation queues metadata");ok(callback->Activate(L"EndfieldHUD.Test.Calendar",L"second",nullptr,0),"Second activation coalesces into the same owner notification");MSG msg{};unsigned messages{};while(PeekMessageW(&msg,owned.window,route.message,route.message,PM_REMOVE)){++messages;check(msg.wParam==42,"Private WM_APP carries exact caller generation");}check(messages==1,"Multiple activations post one owner message without polling");auto values=server->take();check(values.size()==2&&values[0].arguments.find("中文😀")!=std::string::npos&&values[1].arguments=="second","Owner drains exact order and UTF8 metadata");check(FAILED(callback->Activate(L"Foreign.App",L"x",nullptr,0))&&FAILED(callback->Activate(L"EndfieldHUD.Test.Calendar",L"x",nullptr,1)),"Foreign identities and unsupported text-input payloads never route to Calendar");
    std::wstring oversized(appNotificationMaximumArguments+1,L'x');check(FAILED(callback->Activate(L"EndfieldHUD.Test.Calendar",oversized.c_str(),nullptr,0)),"Oversized launch arguments reject without truncation");std::thread worker([&]{for(unsigned i=0;i<appNotificationMaximumQueuedActivations;++i)if(FAILED(callback->Activate(L"EndfieldHUD.Test.Calendar",L"worker",nullptr,0)))std::terminate();});worker.join();check(FAILED(callback->Activate(L"EndfieldHUD.Test.Calendar",L"overflow",nullptr,0)),"Bounded inbox rejects excess rather than growing while owner is busy");values=server->take();check(values.size()==appNotificationMaximumQueuedActivations,"A COM callback thread only queues bounded data, never executes view code");while(PeekMessageW(&msg,owned.window,route.message,route.message,PM_REMOVE)){}
    ok(server->stop(),"Explicit stop precedes HWND and apartment destruction");check(FAILED(callback->Activate(L"EndfieldHUD.Test.Calendar",L"late",nullptr,0))&&server->take().empty(),"Retained external callback is inert after owner stop");server.reset();check(FAILED(callback->Activate(L"EndfieldHUD.Test.Calendar",L"destroyed",nullptr,0)),"External callback survives facade destruction without retaining HWND/view ownership");ComPtr<IUnknown>identity;ok(callback.As(&identity),"Late COM identity and reference counting remain valid until final release");
}
}
#endif
int main(){try{portable();
#ifdef _WIN32
    Apartment apartment;Owned owned;registration(owned);activation(owned);
#endif
    std::cout<<"PASS "<<checks<<" isolated app notification identity/activation checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
