#include "modules/app_shortcut_presentation.hpp"
#include "native/app_shortcut_assets.hpp"
#include <fstream>
#include <iostream>
#include <cmath>
#include <set>
#include <limits>
namespace {namespace m=endfield::modules;namespace c=endfield::core;using J=m::ShortcutJson;unsigned checks{};
void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}
template<class F>void rejects(F f,const char*s){bool caught{};try{f();}catch(const std::exception&){caught=true;}check(caught,s);}
J read(const char*path){std::ifstream stream(path,std::ios::binary);check(bool(stream),"Explicit original fixture opens");return J::parse(std::string(std::istreambuf_iterator<char>(stream),{}),1024*1024);}
m::ShortcutFile items(){m::ShortcutFile f;for(unsigned n=0;n<10;++n){m::ShortcutRecord r;r.id="00000000-0000-4000-8000-"+std::string(11,'0')+char('1'+n);if(n==9)r.id="00000000-0000-4000-8000-000000000010";r.name="Fixture "+std::to_string(n);r.originalName="Original "+std::to_string(n);r.iconPreset=m::shortcutIconOrder[n];f.items.push_back(r);}return f;}
void same(const J&a,const J&b,const char*message){if(a.isNumber()&&b.isNumber()){check(std::abs(a.number()-b.number())<=2e-7,message);return;}if(a.isArray()&&b.isArray()){check(a.array().size()==b.array().size(),message);for(std::size_t n=0;n<a.array().size();++n)same(a.array()[n],b.array()[n],message);return;}if(a.isObject()&&b.isObject()){if(a.object().size()!=b.object().size())std::cerr<<"source="<<a.encode()<<" target="<<b.encode()<<'\n';check(a.object().size()==b.object().size(),message);for(const auto&[key,value]:a.object()){check(b.contains(key),message);same(value,b[key],message);}return;}if(a!=b)std::cerr<<"source="<<a.encode()<<" target="<<b.encode()<<'\n';check(a==b,message);}
J frame(const m::ShortcutSurface&p){const auto&b=p.content["bounds"].array();return J::Array{p.local.values[12],p.local.values[13],b[2],b[3]};}
void art(const J&source,const std::vector<m::ShortcutSurface>&parts){check(source.array().size()==parts.size(),"Original source drawing leaf count");for(std::size_t n=0;n<parts.size();++n){const auto&s=source.array()[n];const auto&p=parts[n];const auto&j=p.content;const auto kind=s["kind"].string();same(s["frame"],frame(p),"Original source drawing geometry");same(s["clip"],p.clip?J(J::Array{p.clip->x,p.clip->y,p.clip->width,p.clip->height}):J{},"Original row viewport clip");check(s["opacity"].number()==(p.role==m::ShortcutSurfaceRole::tint||p.role==m::ShortcutSurfaceRole::rim?0:1),"Source feedback remains an independent initially transparent leaf");if(kind=="text"){check(j["kind"].string()=="text","Original caption kind");for(const auto*k:{"string","fontSize","foregroundColor","alignment","wrapped"})same(s["text"][k],j["text"][k],"Original caption content/style");same(s["text"]["fontName"],j["text"]["font"]["postScriptName"],"Original inherited font descriptor");}else if(kind=="shape")same(s["shape"],j["shape"],"Actual original CGPath/style");else if(kind=="plate"){check(j["kind"].string()=="layer","Original retained plate kind");for(const auto*k:{"backgroundColor","cornerRadius","borderWidth"})same(s[k],j[k],"Original source plate palette/edge");if(s["borderWidth"].number()>0)same(s["borderColor"],j["borderColor"],"Original painted border color");}else check(!j["contents"].isNull()&&j["contents"]["sha256"].string().size()==64,"Original bundled glyph has an explicit pinned image, never a substitute");}}
void source(const J&fixture,const m::AppShortcutArtwork&catalog){for(bool dark:{true,false}){m::AppShortcutState empty,list(items());empty.setReducedMotion(true,0);list.setReducedMotion(true,0);empty.setActive(true,0);list.setActive(true,0);m::ShortcutAppearance appearance;appearance.dark=dark;for(const auto&row:fixture["cases"].array()){if(row["dark"].boolean()!=dark)continue;const auto name=row["name"].string();auto*state=&list;if(name=="empty")state=&empty;else if(name.starts_with("scroll"))list.scroll({50,100},std::stod(name.substr(6)));else if(name=="draft")list.beginDraft({"Fixture Application"},{},0);else if(name.starts_with("icon:"))list.selectIcon(name.substr(5),0);else if(name=="draft-error-drop"){list.setDraftName("Local Name");list.setDropTarget(true);list.showError("Synthetic error");}
 check(state->editing()==row["editing"].boolean()&&state->draftName()==row["draftName"].string()&&state->draftIcon()==row["draftIcon"].string()&&state->scrollOffset()==row["scroll"].number(),"Original canvas state at matching source event");const auto actions=state->actions();check(actions.size()==row["actions"].array().size(),"Original visible action count");for(std::size_t n=0;n<actions.size();++n){const auto&v=actions[n];const auto&o=row["actions"].array()[n];check(m::shortcutActionID(v)==o["id"].string()&&m::shortcutActionLabel(v,*state,c::Language::english)==o["label"].string(),"Original action identity/label/order");same(o["rect"],J(J::Array{v.rect.x,v.rect.y,v.rect.width,v.rect.height}),"Original clipped action hit region");}
 const auto prepared=m::prepareAppShortcutArtwork(*state,catalog,appearance);std::set<std::string>ids;for(const auto&p:prepared)check(ids.insert(p.id).second,"Unique source surface identities");if(row.contains("art"))art(row["art"],prepared);
 }} }
void lifecycle(){m::AppShortcutState s(items());s.setActive(true,0);check(s.scroll({50,100},500)&&s.scrollOffset()==262,"Scroll clamps to original content extent");const auto revision=s.revision();check(s.scroll({50,100},1)&&s.revision()==revision,"Consumed boundary wheel does no content work");check(!s.scroll({0,0},2)&&!s.scroll({50,100},NAN),"Nonlocal/nonfinite wheel is rejected");const auto file=s.file();rejects([&]{s.beginDraft({"bad"},{},NAN);},"Invalid transition time rejects atomically");check(!s.editing()&&s.file()==file,"Rejected draft leaves durable data and UI intact");s.beginDraft({"Neutral application"},{},1);check(s.transitioning()&&s.actions().empty()&&!s.takeNameRequest(),"Finite arrival gates input and name focus");s.advance(1.259);check(s.transitioning(),"Arrival remains finite until the source .26 endpoint");s.advance(1.26);check(!s.transitioning()&&s.takeNameRequest()&&!s.takeNameRequest(),"Arrival requests name editing exactly once");s.setDraftName("Custom");s.selectIcon("camera",1.3);check(s.requiresFrames(1.4)&&!s.requiresFrames(1.48),"Preset movement ends after source .18 seconds");s.showError("Injected save failure");check(s.editing()&&s.draftName()=="Custom"&&s.draftIcon()=="camera"&&s.file()==file,"Rejected injected save preserves candidate and durable file");s.setDropTarget(true);s.setActive(false,1.5);check(s.editing()&&!s.dropTarget()&&!s.requiresFrames(1.6)&&!s.takeNameRequest(),"Hide preserves draft but cancels drop/animation/focus completion");s.setActive(true,2);s.cancelDraft(2);check(s.transitioning()&&!s.editing()&&s.transition().direction==-1,"Cancel uses the original reverse transition");s.beginDraft({"Newer"},{},2.01);s.setActive(false,2.02);s.advance(3);check(!s.takeNameRequest()&&s.draftName()=="Newer","Stale arrival cannot activate a hidden field");s.setActive(true,4);s.setReducedMotion(true,4);s.cancelDraft(4);s.beginDraft({"Immediate"},{},4);check(!s.transitioning()&&s.takeNameRequest(),"Reduced motion completes directly without delayed focus");s.cancelDraft(4);s.replaceItems({});check(s.scrollOffset()==0,"Store replacement clamps session scroll without changing caller file semantics");}
}
int main(int argc,char**argv){try{check(argc==3,"Pass compact original canvas fixture and production artwork resource root");const auto fixture=read(argv[1]);endfield::native::NativeAppShortcutAssets assets(std::filesystem::absolute(argv[2]));source(fixture,assets.artwork());lifecycle();std::cout<<"PASS "<<checks<<" App Shortcut source presentation checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
