#include "native/app_shortcut_scene.hpp"
#include <iostream>
#ifdef _WIN32
#include <windows.h>
#include <objbase.h>
#include <cstdlib>
#include <new>
#include <cmath>
#include <algorithm>
static bool counting{};static std::size_t allocations{};
void*operator new(std::size_t size){if(counting)++allocations;if(auto*p=std::malloc(size?size:1))return p;throw std::bad_alloc();}void operator delete(void*p)noexcept{std::free(p);}void*operator new[](std::size_t size){return ::operator new(size);}void operator delete[](void*p)noexcept{::operator delete(p);}void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
namespace {namespace n=endfield::native;namespace m=endfield::modules;namespace c=endfield::core;unsigned checks{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}
struct Window{HWND hwnd{};Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"OwnedShortcutScene";check(RegisterClassW(&c)!=0,"Register synthetic Shortcut fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,c.lpszClassName,L"Isolated",WS_POPUP,0,0,400,334,nullptr,nullptr,c.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Fixture stays hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);UnregisterClassW(L"OwnedShortcutScene",GetModuleHandleW(nullptr));}};
m::ShortcutFile items(){m::ShortcutFile f;for(unsigned k=0;k<20;++k){m::ShortcutRecord v;char id[37];snprintf(id,sizeof(id),"00000000-0000-4000-8000-%012u",k+1);v.id=id;v.name="Neutral "+std::to_string(k);v.originalName="Original";v.iconPreset=m::shortcutIconOrder[k%14];f.items.push_back(std::move(v));}return f;}
void run(const std::filesystem::path&shader,const std::filesystem::path&root){Window window;n::Renderer renderer;renderer.initialize(window.hwnd,400,334,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests});renderer.setCamera(n::layerViewportProjection(400,334));n::LayerRasterizer raster;n::NativeAppShortcutAssets assets(root);n::LayerRasterOptions options;options.assetRoot=root;options.pixelsPerPoint=1;m::AppShortcutState state(items());state.setActive(true,0);n::NativeAppShortcutScene scene(state,assets,raster,options);n::LayerComposition composition;bool done{};struct Cleanup{n::Renderer&r;n::LayerComposition&c;n::NativeAppShortcutScene&s;bool&done;~Cleanup(){if(done)return;try{c.detach(r);s.releaseResources(r);}catch(...){r.reset();}}}cleanup{renderer,composition,scene,done};
 const auto frame=[&](double t,c::Matrix4 world=c::Matrix4{}){state.advance(t);scene.syncContent(t);scene.updatePose({world,1,t,{},{}});scene.uploadAnimations(renderer);composition.setEntries(renderer,scene.entries());composition.present(renderer);check(scene.collectRetired(renderer),"Retire only detached Shortcut generations");};
 frame(0);renderer.draw(false);check(scene.stats().surfaces<100,"List virtualizes seven original rows rather than full store");check(renderer.readback().width==400,"Original Shortcut artwork renders on existing device");for(const auto&e:scene.entries())check(e.scene->report().unsupported.empty(),"No silently unsupported source artwork");
 scene.setFeedback(c::Point{270,2},false,false,.01);frame(.01);check(!scene.requiresFrames(.01),"Source rounded control corner does not light up");scene.setFeedback(c::Point{295,17},true,false,.1);frame(.17);const auto rasters=raster.stats();const auto gpu=renderer.stats();allocations=0;counting=true;try{for(unsigned k=0;k<120;++k)frame(1+double(k)/60,c::Matrix4::rotation(.01,.02*k/120,0));}catch(...){counting=false;throw;}counting=false;check(allocations==0,"Warm Shortcut pose and uploads allocate no memory");check(raster.stats().rasterizations==rasters.rasterizations&&renderer.stats().textureUploads==gpu.textureUploads,"Warm Shortcut frames preserve all text and icons");
 state.scroll({80,110},13.25);frame(4);check(state.scrollOffset()==13.25,"Fractional source wheel is preserved");state.beginDraft({"Synthetic candidate"},{},5);frame(5);check(scene.entries().size()==2,"Source transition retains outgoing list under incoming draft");const auto incoming=scene.entries().back().scene->draws();const auto heading=std::find_if(incoming.begin(),incoming.end(),[](const auto&v){return v.sourceID.find("apps.heading")!=std::string::npos;});check(heading!=incoming.end(),"Retained source heading is independently addressable");const auto raw=m::shortcutScreenSample(state.transition(),5).incoming;const auto expected=c::Matrix4::translation(200,167)*raw*c::Matrix4::translation(-200,-167)*c::Matrix4::translation(12,7);for(unsigned k=0;k<16;++k)check(std::abs(heading->world.values[k]-expected.values[k])<1e-9,"Source artwork rotates about its default center anchor");const auto before=scene.stats();for(unsigned k=1;k<16;++k)frame(5+double(k)/60);frame(5.26);check(scene.entries().size()==1&&state.takeNameRequest(),"Arrival retires old list and requests editor exactly once");check(scene.stats().maskRasters>before.maskRasters&&scene.stats().maskRasters-before.maskRasters<=32,"Finite screen handoff updates at most two bounded source masks per frame");const auto settledRaster=raster.stats().rasterizations,settledUploads=renderer.stats().textureUploads;for(unsigned k=0;k<60;++k)frame(6+double(k)/60);check(raster.stats().rasterizations==settledRaster&&renderer.stats().textureUploads==settledUploads,"Settled Shortcut screens retire masks and do no pixel work");
 state.selectIcon("camera",7.1);frame(7.1);
 const auto trace=[&]()->const n::DrawObject*{const auto draws=scene.entries().back().scene->draws();const auto found=std::find_if(draws.begin(),draws.end(),[](const auto&v){return v.sourceID.find("apps:icon:camera/register")!=std::string::npos;});return found==draws.end()?nullptr:&*found;};
 check(trace()&&trace()->opacity==0,"New source preset outline starts with no visible ink");const auto presetRasters=raster.stats().rasterizations,presetUploads=renderer.stats().textureUploads;const auto presetBuilds=scene.stats().builds;
 frame(7.19);check(trace()&&trace()->opacity==1&&raster.stats().rasterizations==presetRasters+1&&renderer.stats().textureUploads==presetUploads+1,"Finite source trace repaints only its tiny independent leaf");frame(7.29);
 check(raster.stats().rasterizations==presetRasters+2&&renderer.stats().textureUploads==presetUploads+2&&scene.stats().builds==presetBuilds,"Trace endpoint preserves every sibling caption and icon");check(!scene.requiresFrames(7.4),"Source preview approach and outline end after .18 seconds");
 const auto tracedRaster=raster.stats().rasterizations,tracedUploads=renderer.stats().textureUploads;allocations=0;counting=true;try{for(unsigned k=0;k<20;++k)frame(7.4+double(k)/1000,c::Matrix4::rotation(.01,.01*k/20,0));}catch(...){counting=false;throw;}counting=false;check(allocations==0&&raster.stats().rasterizations==tracedRaster&&renderer.stats().textureUploads==tracedUploads,"Finished preset trace stays retained without allocation or upload");
 state.setDraftName("Updated name");frame(7.5);check(!trace(),"Source content rebuild removes completed trace without resurrecting its old generation");
 state.selectIcon("star",7.6);frame(7.6);state.selectIcon("camera",7.65);frame(7.65);check(trace()&&trace()->opacity==0,"Interrupted preset selection restarts only the newly selected face trace");frame(7.85);check(trace()&&trace()->opacity==1,"Interrupted preset trace reaches its own finite endpoint");state.cancelDraft(8);frame(8);frame(8.13);state.beginDraft({"Newer candidate"},{},8.14);frame(8.14);frame(8.4);check(state.draftName()=="Newer candidate"&&scene.entries().size()==1,"Interrupted handoff cannot resurrect an old draft");
 m::ShortcutAppearance light;light.dark=false;light.language=c::Language::korean;scene.setAppearance(light);frame(9);check(state.draftName()=="Newer candidate"&&state.scrollOffset()==13.25,"Appearance change preserves draft and session scroll");composition.detach(renderer);check(scene.releaseResources(renderer),"Explicit detach releases every Shortcut resource");check(renderer.stats().textures==0&&renderer.stats().meshes==0&&raster.stats().entries<150,"Shortcut resource lifetime remains bounded");frame(10);renderer.draw(false);check(renderer.readback().width==400,"Unchanged Shortcut content uploads again after release");composition.detach(renderer);check(scene.releaseResources(renderer)&&renderer.stats().textures==0&&renderer.stats().meshes==0,"Reuploaded Shortcut resources retire again");done=true;renderer.reset();}
}
int wmain(int argc,wchar_t**argv){auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==3,"Pass native HLSL and original Shortcut resource root");run(argv[1],std::filesystem::absolute(argv[2]));CoUninitialize();std::cout<<"PASS "<<checks<<" native Shortcut scene checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(){std::cout<<"Native Shortcut scene requires Windows; no GPU execution on this host\n";return 0;}
#endif
