#ifdef _WIN32
#include "tools/app_shortcut_preview.hpp"
#include "native/module_scene.hpp"
#include <windows.h>
#include <objbase.h>
#include <iostream>
#include <cmath>
namespace {
namespace c=endfield::core;namespace m=endfield::modules;namespace n=endfield::native;namespace a=endfield::app;namespace t=endfield::tools;using J=ehud::data::Json;
unsigned checks{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}
struct Window {HWND hwnd{};Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"OwnedShortcutPreviewFixture";check(RegisterClassW(&c)!=0,"Register owned isolated Shortcut fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,c.lpszClassName,L"Synthetic",WS_POPUP,0,0,1280,800,nullptr,nullptr,c.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Fixture stays hidden and never activates native input");}~Window(){DestroyWindow(hwnd);UnregisterClassW(L"OwnedShortcutPreviewFixture",GetModuleHandleW(nullptr));}};
m::ShortcutFile items(){m::ShortcutFile f;for(unsigned k=0;k<10;++k){m::ShortcutRecord v;char id[37];snprintf(id,sizeof(id),"00000000-0000-4000-8000-%012u",k+1);v.id=id;v.name="Neutral "+std::to_string(k);v.originalName="Original";v.iconPreset="terminal";f.items.push_back(std::move(v));}return f;}
void run(n::Renderer&r,n::LayerRasterizer&raster,HWND window,const n::NativeAppShortcutAssets&assets){t::AppShortcutPreviewOptions options;options.initial=items();options.raster.pixelsPerPoint=1;t::AppShortcutPreview owner(window,raster,assets,nullptr,TF_CLIENTID_NULL,options);owner.resize({1280,800,96,1,1280,800});n::LayerComposition composition;bool done{};struct Guard{n::Renderer&r;n::LayerComposition&c;t::AppShortcutPreview&o;bool&done;~Guard(){if(done)return;try{c.detach(r);o.release(r);}catch(...){r.reset();}}}guard{r,composition,owner,done};
 c::ModulePresentation modules(c::Module::power);c::source::DesktopChromeSettings settings{{0,0,1280,800},1,{},c::Module::power,true};auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;double time{};n::LayerScene geometry(raster);geometry.load(J::Object{{"bounds",J::Array{0,0,400,334}},{"children",J::Array{}}},options.raster);n::NativeModuleSurface plane(geometry,c::Module::addApp);
 const auto frame=[&](double dt=1./60){time+=dt;settings.module=modules.requested();const auto sample=modules.sample(time).presentation;owner.update(center,settings,sample,1,time);owner.upload(r);composition.setEntries(r,owner.entries());composition.present(r);owner.collected(r);};
 const auto point=[&](c::Point p){const auto sample=modules.sample(time).presentation;const auto*shown=sample.current.module==c::Module::addApp?&sample.current:&*sample.incoming;plane.update(center,settings,*shown);return *c::Projection::viewport(n::layerViewportProjection(1280,800)*plane.pose().contentWorld,1280,800).project(p);};
 const auto action=[&](m::ShortcutActionKind kind,std::string value={}){return owner.perform({kind,std::move(value),{}},time);};
 const auto choose=[&](std::string name){check(action(m::ShortcutActionKind::choose),"Original Add requests explicit chooser");auto request=owner.takeRequest();check(request&&request->kind==t::ShortcutRequestKind::choose&&owner.presentingPanel(),"One owned picker request locks only its native dialog");check(owner.completeCandidate(request->generation,{std::move(name)},time),"Injected selected candidate begins original draft");frame(.30);};
 frame();check(owner.entries().empty()&&!owner.requiresFrames(time),"Hidden initial owner has no visible native content or frame demand");modules.select(c::Module::addApp,time);frame(.03);check(!owner.covers({640,400}),"Incoming module rejects pointer until shared transition settles");frame(.4);check(owner.covers(point({10,10})),"Settled owner uses the actual source center projection");
 check(owner.scroll(point({100,100}),13.25,time)&&owner.state().scrollOffset()==13.25,"Fractional list scroll is preserved without a durable request");check(!owner.takeRequest(),"Scrolling never creates OS or persistence work");
 const auto firstID=owner.state().file().items[0].id;check(action(m::ShortcutActionKind::launch,firstID),"Launch action is explicit and selected-record based");auto launch=owner.takeRequest();check(launch&&launch->record&&launch->kind==t::ShortcutRequestKind::launch,"Host receives the exact launch record before close");owner.setOverlayVisible(false,time);frame();check(owner.busy()&&!owner.takeCancelledRequest(),"Accepted close-first launch survives its required HUD conceal");check(owner.completeRequest(launch->generation,{},time)&&!owner.busy(),"Launch completion clears only the accepted request");owner.setOverlayVisible(true,time);frame();
 check(action(m::ShortcutActionKind::choose),"Begin cancellable chooser");auto stale=owner.takeRequest();owner.setOverlayVisible(false,time);check(owner.takeCancelledRequest()==std::optional(stale->generation),"Conceal cancels the exact stale chooser generation");check(!owner.completeCandidate(stale->generation,{"Late"},time)&&!owner.state().editing(),"Late native dialog result cannot reopen hidden draft");owner.setOverlayVisible(true,time);frame();
 choose("A\r\nB");check(owner.editingName()&&owner.state().draftName()=="A\r\nB","Source arrival selects one borrowed plain name field");check(owner.finishEditing(true,time)&&!owner.editingName()&&owner.state().draftName()=="A  B","Finish normalizes unchanged candidate with original Foundation newline rule");frame();check(!owner.takeRequest(),"Applying name neither saves nor starts OS work");
 check(action(m::ShortcutActionKind::name)&&owner.editingName(),"Name reopens the shared projected editor");check(owner.key({a::KeyKind::unicodeCharacter,'Z'},false,time),"Plain field accepts a source Unicode character");check(owner.key({a::KeyKind::down,VK_RETURN},false,time)&&!owner.editingName()&&owner.state().draftName()=="Z","Initial select-all and Return replace draft only");frame();
 check(action(m::ShortcutActionKind::name),"Reopen name before cancel");owner.key({a::KeyKind::unicodeCharacter,'X'},false,time);check(owner.key({a::KeyKind::down,VK_ESCAPE},false,time)&&owner.state().draftName()=="Z"&&!owner.editingName(),"Unmarked Escape abandons name field before whole draft");frame();
 check(action(m::ShortcutActionKind::icon,"camera"),"Original source icon choice is retained");frame(.2);check(action(m::ShortcutActionKind::save),"Save enqueues one explicit repository operation");auto save=owner.takeRequest();check(save&&save->name=="Z"&&save->icon=="camera"&&save->candidate&&owner.busy(),"Save request freezes selected candidate and name/icon payload");check(owner.completeRequest(save->generation,"Synthetic write failure",time)&&owner.state().editing()&&owner.state().error().has_value(),"Failed durable write preserves editable source draft");frame();
 check(action(m::ShortcutActionKind::save),"Failed save can be retried explicitly");save=owner.takeRequest();owner.setOverlayVisible(false,time);check(owner.busy()&&!owner.takeCancelledRequest(),"Accepted write is retained while hidden");auto committed=owner.state().file();auto extra=committed.items.front();extra.id="00000000-0000-4000-8000-000000000099";extra.name="Z";extra.iconPreset="camera";committed.items.push_back(extra);check(owner.completeFile(save->generation,committed,time)&&!owner.state().editing()&&owner.state().file().items.size()==11,"Only committed file acknowledgement replaces durable UI data");frame();owner.setOverlayVisible(true,time);frame(.3);
 center=center*c::Matrix4::rotation(.03,-.06,0);frame();check(owner.covers(point({200,150})),"Tilted source paint and hits share one current plane");check(owner.scroll(point({100,100}),6.5,time)&&owner.state().scrollOffset()==19.75,"Tilt preserves fractional session list offset");
 m::ShortcutAppearance light;light.dark=false;light.language=c::Language::korean;owner.setAppearance(light,time);frame();check(owner.state().scrollOffset()==19.75&&owner.state().file()==committed,"Language/theme events retain file and scroll identity");
 choose("Preserved");owner.key({a::KeyKind::unicodeCharacter,'Q'},false,time);owner.setOverlayVisible(false,time);frame();check(!owner.editingName()&&owner.state().editing()&&owner.state().draftName()=="Q","Conceal commits final field text but preserves unsaved source draft");check(!owner.requiresFrames(time)&&!owner.pointerLocked(),"Closed owner has no animation or input lock");owner.setOverlayVisible(true,time);frame();check(!owner.editingName()&&owner.state().draftName()=="Q","Reopen never resurrects stale editor completion");
 modules.select(c::Module::power,time);frame(.03);check(!owner.entries().empty(),"Outgoing original artwork survives until shared module transition ends");frame(.4);check(owner.entries().empty()&&!owner.requiresFrames(time),"Departed module has no published content or frame demand");composition.detach(r);owner.release(r);check(r.stats().textures==0&&r.stats().meshes==0,"All Shortcut owner resources release after composition detach");done=true;
}
}
int wmain(int argc,wchar_t**argv){struct Apartment{HRESULT hr{CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED)};~Apartment(){if(SUCCEEDED(hr))CoUninitialize();}}apartment;try{check(SUCCEEDED(apartment.hr)&&argc==3,"Pass native HLSL and production Shortcut assets");Window window;n::Renderer renderer;renderer.initialize(window.hwnd,1280,800,{n::Driver::warpForTests,argv[1],n::RenderTarget::offscreenForTests});renderer.setCamera(n::layerViewportProjection(1280,800));n::LayerRasterizer raster;n::NativeAppShortcutAssets assets(std::filesystem::absolute(argv[2]));run(renderer,raster,window.hwnd,assets);renderer.reset();std::cout<<"PASS "<<checks<<" Shortcut owner checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
