#include "modules/archive_repository.hpp"
#include "native/archive_text_rules.hpp"
#include "core/data/file_io.hpp"
#ifdef _WIN32
#include <winsqlite/winsqlite3.h>
#else
#include <sqlite3.h>
#endif
#include <algorithm>
#include <cstdio>
#include <iostream>
#include <thread>

namespace {
namespace mod=endfield::modules;namespace data=ehud::data;using J=data::Json;
unsigned checks{};void check(bool v,const char*m){++checks;if(!v)throw std::runtime_error(m);}
template<class F>void rejects(F&&f,const char*m,std::optional<data::StoreErrorCode>code={}){bool failure{};try{f();}catch(const data::StoreError&e){failure=!code||*code==e.code();}catch(const std::exception&){failure=!code;}check(failure,m);}
std::string id(char prefix,unsigned n){char text[64];std::snprintf(text,sizeof(text),"%c0000000-0000-4000-8000-%012u",prefix,n);return text;}
struct Temporary {std::filesystem::path root=std::filesystem::canonical(std::filesystem::temp_directory_path())/("EndfieldHUD-Archive-Contracts-"+data::makeUUID());Temporary(){std::filesystem::create_directories(root);}~Temporary(){std::error_code e;std::filesystem::remove_all(root,e);}};
struct Database {
    sqlite3*db{};explicit Database(const std::filesystem::path&path){const auto u=path.u8string();const std::string s(reinterpret_cast<const char*>(u.data()),u.size());if(sqlite3_open_v2(s.c_str(),&db,SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|SQLITE_OPEN_FULLMUTEX,nullptr)!=SQLITE_OK)throw std::runtime_error("Synthetic SQLite open failed");}
    ~Database(){if(db)sqlite3_close(db);}Database(const Database&)=delete;
    void sql(const char*s){char*error{};const auto status=sqlite3_exec(db,s,nullptr,nullptr,&error);std::string text=error?error:"";sqlite3_free(error);if(status!=SQLITE_OK)throw std::runtime_error("Synthetic SQL failed: "+text);}
    struct Query {sqlite3_stmt*q{};explicit Query(sqlite3*d,const char*s){if(sqlite3_prepare_v2(d,s,-1,&q,nullptr)!=SQLITE_OK)throw std::runtime_error("Synthetic query failed");}~Query(){sqlite3_finalize(q);}void text(int n,std::string_view s){if(sqlite3_bind_text(q,n,s.data(),static_cast<int>(s.size()),SQLITE_TRANSIENT)!=SQLITE_OK)throw std::runtime_error("Synthetic text bind failed");}bool row(){return sqlite3_step(q)==SQLITE_ROW;}};
    std::int64_t number(const char*s){Query q(db,s);if(!q.row())throw std::runtime_error("Synthetic scalar missing");return sqlite3_column_int64(q.q,0);}
    std::string value(const char*s){Query q(db,s);if(!q.row())throw std::runtime_error("Synthetic string missing");const auto*bytes=sqlite3_column_blob(q.q,0);const auto count=sqlite3_column_bytes(q.q,0);return {static_cast<const char*>(bytes),static_cast<std::size_t>(count)};}
    void selection(std::string_view selected){Query q(db,"INSERT INTO state VALUES('selection',?)");q.text(1,selected);if(sqlite3_step(q.q)!=SQLITE_DONE)throw std::runtime_error("Synthetic selection insert failed");}
};
constexpr const char*v1Schema="CREATE TABLE entries(id TEXT PRIMARY KEY,template TEXT NOT NULL,title TEXT NOT NULL,date REAL NOT NULL,modified REAL NOT NULL,mediaCount INTEGER NOT NULL,payload BLOB NOT NULL);CREATE TABLE state(key TEXT PRIMARY KEY,value TEXT NOT NULL);PRAGMA user_version=1";
mod::ArchiveEntry document(unsigned n){mod::ArchiveEntry e;e.id=id('B',n);e.title="调查 中文 👩🏽‍💻";e.body="Body 中文\nDifferent style 👩🏽‍💻";e.date=-.25;e.modified=42.125;e.extra["futureDocument"]=J::Object{{"opaqueID","00000001234567890"}};e.bodyStyle.extra["futureStyle"]=42;endfield::core::notes::RichText rich;rich.extra["futureRich"]=true;rich.runs.push_back({0,4,{.fontSize=48,.bold=true},{{"futureRun","preserved"}}});e.bodyRichText=rich;return e;}
J macMedia(){return J::Object{{"version",1},{"kind","image"},{"bookmark","AQIDBA=="},{"isSecurityScoped",true},{"lastKnownPath","/Synthetic/Do not open/image.png"},{"displayName","图像.png"},{"pixelWidth",32},{"pixelHeight",24},{"frameCount",1},{"futureLocator",J::Object{{"opaque","000123"}}}};}
std::string originalPayload(const mod::ArchiveEntry&e,const mod::ArchiveTextRules&rules){return "\n "+mod::encodeArchiveEntry(e,rules).encode()+"\n";}
void legacy(Database&db,const mod::ArchiveEntry&e,std::string_view payload,bool mismatch=false){Database::Query q(db.db,"INSERT INTO entries VALUES(?,?,?,?,?,?,?)");q.text(1,e.id);q.text(2,e.type==mod::ArchiveTemplate::journal?"journal":"research");q.text(3,mismatch?"Different index title":e.title);sqlite3_bind_double(q.q,4,e.date+mod::archiveFoundationToUnix);sqlite3_bind_double(q.q,5,e.modified+mod::archiveFoundationToUnix);sqlite3_bind_int64(q.q,6,static_cast<std::int64_t>(e.media.size()));sqlite3_bind_blob(q.q,7,payload.data(),static_cast<int>(payload.size()),SQLITE_TRANSIENT);if(sqlite3_step(q.q)!=SQLITE_DONE)throw std::runtime_error("Synthetic v1 insert failed");}
void roundtrip(){Temporary t;const auto rules=endfield::native::nativeArchiveTextRules();const auto folder=t.root/"Archive";mod::ArchiveSQLiteRepository repo(folder,rules);check(!std::filesystem::exists(folder),"Construction creates no directory/database/worker");check(repo.categories().empty()&&repo.summaries().empty()&&!repo.selection(),"New source v2 archive defaults to no categories/documents/selection");
    {Database db(repo.path());check(db.number("PRAGMA user_version")==2&&db.number("SELECT count(*) FROM sqlite_master WHERE name NOT LIKE 'sqlite_%'")==3,"Source v2 has exactly three tables and version2");check(db.number("SELECT count(*) FROM pragma_table_info('entries')")==9,"Source entries has exact nine named columns");}
    mod::ArchiveCategory category{id('A',1),"自定义",-.5,{}};category.extra["futureCategory"]=J::Object{{"leadingZero","000123"}};repo.saveCategory(category);auto e=document(1);e.categoryID=category.id;e.media={macMedia()};repo.save(e);repo.select(e.id);
    check(repo.entry(e.id)==e&&repo.categories()==std::vector{category}&&repo.selection()==e.id,"Rich UTF16/default styles/unknown payloads/category/selection roundtrip exactly");check(repo.thumbnail(e.id)==e.media.front(),"First original Mac attachment stays opaque without opening its path/bookmark");
    {Database db(repo.path());Database::Query q(db.db,"SELECT date,modified,payload,typeof(payload),thumbnail FROM entries");check(q.row()&&sqlite3_column_double(q.q,0)==e.date+mod::archiveFoundationToUnix&&sqlite3_column_double(q.q,1)==e.modified+mod::archiveFoundationToUnix,"SQLite indices use Unix while document JSON uses Foundation epoch");auto bytes=static_cast<const char*>(sqlite3_column_blob(q.q,2));const auto payload=J::parse(std::string_view(bytes,static_cast<std::size_t>(sqlite3_column_bytes(q.q,2))));check(payload["date"].number()==e.date&&payload["modified"].number()==e.modified&&std::string(reinterpret_cast<const char*>(sqlite3_column_text(q.q,3)))=="blob","Payload encoded as source-compatible BLOB with unshifted Codable dates");check(db.number("SELECT count(*) FROM state WHERE key LIKE 'category.extra/%'")==1,"Additive category metadata uses unused state keys without schema changes");}
    e.body="Edited 🐱";e.bodyRichText.reset();e.modified=100.75;repo.save(e);repo.reopen();check(repo.entry(e.id)==e&&repo.selection()==e.id,"Explicit close/reopen retains changed document and source selection");auto summary=repo.summaries();check(summary.size()==1&&summary[0]==mod::archiveSummary(e),"Gallery summary contains only indexed small metadata/first-reference");repo.select({});check(!repo.selection(),"Explicit nil selection uses source empty-string state");repo.select(e.id);repo.remove(e.id);check(!repo.entry(e.id)&&!repo.thumbnail(e.id)&&!repo.selection()&&repo.summaries().empty(),"Delete removes reference and matching selection only");check(repo.categories()==std::vector{category},"Document removal keeps category and opaque media references untouched");
    bool wrongThreadRejected{};std::thread wrong([&]{try{(void)repo.categories();}catch(const std::exception&){wrongThreadRejected=true;}});wrong.join();check(wrongThreadRejected,"All store operations bind to one injected FIFO thread");
}
void migration(){Temporary t;const auto rules=endfield::native::nativeArchiveTextRules();auto e=document(1);e.media={macMedia()};auto research=document(2);research.type=mod::ArchiveTemplate::research;const auto raw=originalPayload(e,rules),other=originalPayload(research,rules);const auto folder=t.root/"v1";std::filesystem::create_directories(folder);{Database db(folder/"archive.sqlite");db.sql(v1Schema);legacy(db,e,raw);legacy(db,research,other);db.selection(e.id);}
    mod::ArchiveSQLiteRepository repo(folder,rules);const auto cats=repo.categories();check(cats.size()==2&&std::any_of(cats.begin(),cats.end(),[](const auto&c){return c.id==mod::archiveLegacyCategory(mod::ArchiveTemplate::journal).id&&c.created==-mod::archiveFoundationToUnix;}),"Validated v1 creates only used deterministic legacy categories at Unix0");e.categoryID=mod::archiveLegacyCategory(e.type).id;research.categoryID=mod::archiveLegacyCategory(research.type).id;check(repo.entry(e.id)==e&&repo.entry(research.id)==research&&repo.selection()==e.id,"Only permitted legacy additive category mismatch is recovered in memory");
    {Database db(repo.path());check(db.number("PRAGMA user_version")==2&&db.value("SELECT payload FROM entries WHERE template='journal'")==raw&&db.value("SELECT payload FROM entries WHERE template='research'")==other,"Migration preserves original payload bytes/whitespace and stamps v2 only after validation");check(db.value("SELECT value FROM state WHERE key='selection'")==e.id&&db.number("SELECT count(*) FROM entries WHERE thumbnail IS NOT NULL")==1,"Migration preserves selection and backfills first thumbnail only");}
    const auto bad=t.root/"invalid-v1";std::filesystem::create_directories(bad);auto badEntry=document(3);{Database db(bad/"archive.sqlite");db.sql(v1Schema);legacy(db,badEntry,originalPayload(badEntry,rules),true);db.selection(badEntry.id);}mod::ArchiveSQLiteRepository invalid(bad,rules);rejects([&]{(void)invalid.categories();},"Metadata mismatch rejects v1 before any category/schema writes",data::StoreErrorCode::invalid);{Database db(invalid.path());check(db.number("PRAGMA user_version")==1&&db.number("SELECT count(*) FROM sqlite_master WHERE name='categories'")==0&&db.number("SELECT count(*) FROM pragma_table_info('entries')")==7,"Failed migration transaction leaves source schema/version intact");}
    const auto empty=t.root/"empty-v1";std::filesystem::create_directories(empty);{Database db(empty/"archive.sqlite");db.sql(v1Schema);db.selection("");}mod::ArchiveSQLiteRepository emptyRepo(empty,rules);check(emptyRepo.categories().empty()&&!emptyRepo.selection(),"Empty v1 migrates without inventing legacy categories");
}
void categoryTransactions(){Temporary t;const auto rules=endfield::native::nativeArchiveTextRules();mod::ArchiveSQLiteRepository repo(t.root/"Archive",rules);mod::ArchiveCategory a{id('A',1),"Straße",1,{}},b{id('A',2),"Other",2,{}};repo.saveCategory(a);repo.saveCategory(b);auto duplicate=a;duplicate.id=id('A',3);duplicate.name="STRASSE";rejects([&]{repo.saveCategory(duplicate);},"Source Unicode category-name folding rejects duplicate identity");auto rename=a;rename.name="Renamed";rejects([&]{repo.saveCategory(rename);},"Existing source category identity/name/created are immutable");check(repo.categories().size()==2,"Rejected categories roll back entirely");
    auto first=document(1),second=document(2);first.categoryID=second.categoryID=a.id;first.media={macMedia()};second.media={J::parse(data::makeWindowsMediaReference("C:\\Synthetic\\never-open.mp4","never-open.mp4",10,20,"video",2.5,1))};repo.save(first);repo.save(second);repo.select(first.id);
    auto draft=second;draft.body="Newest selected draft with moved category";draft.bodyRichText.reset();draft.categoryID=b.id;repo.deleteCategory(a.id,std::span(&draft,1));first.categoryID.reset();check(repo.entry(first.id)==first&&repo.entry(second.id)==draft,"Category removal reassigns persisted docs and preserves latest draft's other category");check(repo.selection()==first.id&&repo.categories()==std::vector{b},"Category deletion keeps document selection/attachments and other categories");
    repo.saveCategory(a);auto third=document(3);third.categoryID=a.id;repo.save(third);auto invalid=third;invalid.categoryID=id('A',99);rejects([&]{repo.deleteCategory(a.id,std::span(&invalid,1));},"Unknown draft category rejects complete removal transaction");check(repo.entry(third.id)==third&&repo.categories().size()==2,"Failure restores category and all entry metadata/payloads");repo.deleteCategory(a.id,{});third.categoryID.reset();check(repo.entry(third.id)==third,"A failed transaction leaves connection usable for a later explicit removal");
}
void conflicts(){Temporary t;const auto rules=endfield::native::nativeArchiveTextRules();mod::ArchiveSQLiteRepository repo(t.root/"Archive",rules);auto e=document(1);repo.save(e);{Database db(repo.path());db.sql("INSERT INTO state VALUES('external','kept')");}e.title="Conflict draft";rejects([&]{repo.save(e);},"Changed-on-disk SQL version prevents overwriting external commit",data::StoreErrorCode::changedOnDisk);check(repo.entry(e.id)->title!=e.title,"Conflict does not write partial payload/index metadata");repo.reopen();repo.save(e);check(repo.entry(e.id)==e,"Only explicit reopen accepts a new optimistic-write baseline");
    {Database db(repo.path());db.sql("UPDATE entries SET title='Corrupt index'");}repo.reopen();rejects([&]{(void)repo.entry(e.id);},"Document/index mismatch is surfaced without decoding a false editable draft",data::StoreErrorCode::invalid);
    // A second path is the caller's own fixture, never another app's database.
    const auto folder=t.root/"replacement";mod::ArchiveSQLiteRepository second(folder,rules);second.save(document(2));const auto original=second.path();const auto moved=t.root/"kept-original.sqlite";std::error_code error;std::filesystem::rename(original,moved,error);
    if(error){
#ifdef _WIN32
        // System SQLite can withhold FILE_SHARE_DELETE for an open database.
        // This is stronger native protection; do not bypass its owned handle.
        check(error.value()==32||error==std::errc::permission_denied,"Windows SQLite explicitly prevents replacement while its connection owns the file");check(second.entry(id('B',2)).has_value()&&!std::filesystem::exists(moved),"Native sharing protection retains original fixture and usable connection");
#else
        throw std::system_error(error,"Synthetic path replacement failed");
#endif
    }else{{Database db(original);db.sql(v1Schema);}rejects([&]{second.select({});},"Replacement file identity prevents writing a now-unlinked original database",data::StoreErrorCode::changedOnDisk);second.reopen();check(second.categories().empty(),"Explicit recovery opens replacement fixture only after old connection retires");}
}
void invalidSchemas(){Temporary t;const auto rules=endfield::native::nativeArchiveTextRules();auto folder=t.root/"foreign";std::filesystem::create_directories(folder);{Database db(folder/"archive.sqlite");db.sql("CREATE TABLE foreignTable(value TEXT)");}mod::ArchiveSQLiteRepository foreign(folder,rules);rejects([&]{foreign.categories();},"Version0 foreign schema is never initialized/stamped",data::StoreErrorCode::invalid);{Database db(foreign.path());check(db.number("PRAGMA user_version")==0&&db.number("SELECT count(*) FROM sqlite_master WHERE name='categories'")==0,"Foreign database structure remains intact");}
    folder=t.root/"future";std::filesystem::create_directories(folder);{Database db(folder/"archive.sqlite");db.sql("PRAGMA user_version=3");}mod::ArchiveSQLiteRepository future(folder,rules);rejects([&]{future.summaries();},"Future version is not downgraded/replaced",data::StoreErrorCode::newerVersion);{Database db(future.path());check(db.number("PRAGMA user_version")==3,"Future version preserved");}
    folder=t.root/"triggers";mod::ArchiveSQLiteRepository seed(folder,rules);seed.save(document(1));{Database db(seed.path());db.sql("CREATE TRIGGER unexpected AFTER INSERT ON entries BEGIN UPDATE state SET value='modified'; END");}rejects([&]{seed.reopen();},"Unrecognized triggers cannot mutate archive rows during own transactions",data::StoreErrorCode::invalid);
    rejects([&]{mod::ArchiveSQLiteRepository relative("relative",rules);},"Repository cannot fall back to a real/default data path",data::StoreErrorCode::invalid);
}
void bounds(){Temporary t;const auto rules=endfield::native::nativeArchiveTextRules();mod::ArchiveSQLiteRepository repo(t.root/"Archive",rules);auto e=document(1);repo.save(e);{Database db(repo.path());db.sql("BEGIN IMMEDIATE");for(unsigned n=2;n<=mod::archiveMaximumEntries;++n){const auto row=document(n);Database::Query q(db.db,"INSERT INTO entries SELECT ?,template,title,date,modified,mediaCount,payload,categoryID,thumbnail FROM entries WHERE id=?");q.text(1,row.id);q.text(2,e.id);if(sqlite3_step(q.q)!=SQLITE_DONE)throw std::runtime_error("Synthetic count insert failed");}db.sql("COMMIT");}repo.reopen();check(repo.summaries().size()==mod::archiveMaximumEntries,"Exact source2000 summary limit remains usable without loading bodies");auto extra=document(2001);rejects([&]{repo.save(extra);},"Source document count rejects one additional entry");e.body="Edit at exact capacity";e.bodyRichText.reset();repo.save(e);check(repo.entry(e.id)==e,"Updating existing document at source count capacity remains permitted");
    {Database db(repo.path());db.sql("INSERT INTO entries SELECT 'B0000000-0000-4000-8000-000000003000',template,title,date,modified,mediaCount,payload,categoryID,thumbnail FROM entries LIMIT 1");}repo.reopen();rejects([&]{repo.summaries();},"Malformed count greater than source2000 never silently drops docs");rejects([&]{repo.save(e);},"Existing-record edit rejects malformed over-capacity database");
}
}
int main(){try{roundtrip();migration();categoryTransactions();conflicts();invalidSchemas();bounds();std::cout<<"PASS "<<checks<<" Archive SQLite repository contracts\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
