#include "native/archive_scene.hpp"
#include "native/archive_text_rules.hpp"
#include "core/data/file_io.hpp"
#include <iostream>
#include <stdexcept>
#ifdef _WIN32
#include <windows.h>
#include <objbase.h>
#include <atomic>
#include <cstdlib>
#include <new>
namespace {std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
#endif
namespace gpu=endfield::native;namespace mod=endfield::modules;namespace core=endfield::core;using J=ehud::data::Json;
namespace {unsigned checks{};void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}template<class F>void rejects(F&&f,const char*why){bool failed{};try{f();}catch(const std::exception&){failed=true;}check(failed,why);}
struct Repository:mod::ArchiveRepository{std::vector<mod::ArchiveCategory>cats;std::vector<mod::ArchiveEntry>docs;std::optional<std::string>selected;std::vector<mod::ArchiveCategory>categories()override{return cats;}std::vector<mod::ArchiveSummary>summaries()override{std::vector<mod::ArchiveSummary>s;for(const auto&e:docs)s.push_back(mod::archiveSummary(e));return s;}std::optional<mod::ArchiveEntry>entry(std::string_view id)override{for(const auto&e:docs)if(e.id==id)return e;return {};}std::optional<std::string>selection()override{return selected;}void select(const std::optional<std::string>&id)override{selected=id;}void save(const mod::ArchiveEntry&)override{}void saveCategory(const mod::ArchiveCategory&)override{}void deleteCategory(std::string_view,std::span<const mod::ArchiveEntry>)override{}void remove(std::string_view)override{}std::optional<J>thumbnail(std::string_view)override{return {};}};
mod::ArchiveExecutor inlineExecutor(){return {[](auto work,auto done){std::exception_ptr e;try{work();}catch(...){e=std::current_exception();}done(e);return true;}};}
mod::ArchiveViewInput input(const J&fixture){mod::ArchiveViewInput i;i.iconContents=J::Object{{"asset",fixture["rasterAssets"].array().front()["path"]},{"sha256",fixture["rasterAssets"].array().front()["sha256"]}};i.dateString=[](double){return "2026-09-21";};i.categoryCaptionWidth=[](auto){return 75.;};return i;}
void portable(const J&fixture){const auto rules=gpu::nativeArchiveTextRules();for(const auto&row:fixture["states"].array()){auto r=std::make_shared<Repository>();for(const auto&v:row["categories"].array())r->cats.push_back(mod::decodeArchiveCategory(v,rules));for(const auto&v:row["entries"].array())r->docs.push_back(mod::decodeArchiveEntry(v,rules));if(!row["selectedID"].isNull())r->selected=row["selectedID"].string();mod::ArchiveState state(r,inlineExecutor(),rules);state.activate();state.setFilter(row["categoryID"].isNull()?std::nullopt:std::optional(row["categoryID"].string()),row["filtersUncategorized"].boolean());state.scroll({30,150},row["categoryScrollOffset"].number());state.setGalleryScroll(row["scrollOffset"].number());mod::ArchiveArtwork art;
 if(row["kind"]==J("canvas")){auto i=input(fixture);i.appearance.dark=row["dark"].boolean();if(!row["formattingField"].isNull())i.formattingField=row["formattingField"].string();art=mod::prepareArchiveArtwork(state,i);}else{mod::ArchiveMenuInput i;i.categories=state.categories();i.scrollOffset=row["menuScrollOffset"].number();i.kind=row["kind"]==J("categoryMenu")?mod::ArchiveMenuKind::category:row["kind"]==J("deleteDocumentMenu")?mod::ArchiveMenuKind::deleteDocument:mod::ArchiveMenuKind::deleteCategory;i.editingName=row["state"]==J("category-menu-create");art=mod::prepareArchiveMenu(i);}
 const auto plan=gpu::prepareArchiveScene(art,row["kind"]==J("canvas"));check(plan.layers["bounds"]==J(J::Array{0,0,0,0}),"Module compiler cannot flatten the full canvas into a CPU bitmap");check(!plan.surfaces.empty()&&plan.surfaces.size()<100,"Original visible Archive rows remain bounded retained surfaces");check(plan.layers["children"].array().size()==plan.surfaces.size(),"Every compiled source leaf has one numeric binding");for(std::size_t n=0;n<plan.surfaces.size();++n){const auto&s=plan.surfaces[n];check(s.local.finite()&&s.id==plan.layers["children"].array()[n]["id"].string(),"Exact source ID/order resolves without fallback");check(s.clips.size()<=8,"Source ancestor clips stay bounded");for(const auto&clip:s.clips)check(clip.width>0&&clip.height>0,"Visible source clipping is retained in the module plane");if(s.feedback)check(plan.layers["children"].array()[n]["opacity"].number()==1,"Zero feedback target retains immutable local artwork");}
 if(!state.selected()&&row["kind"]==J("canvas")){for(const auto&s:plan.surfaces)if(s.id.starts_with("archive/card/")){check(s.clips.size()==1&&s.clips[0]==mod::ArchiveState::galleryRect(),"Gallery card/rim retain the original clipped viewport");}for(const auto&s:plan.surfaces)if(s.id.starts_with("archive/category/")){check(s.local.values[12]==14&&s.clips.size()==1&&s.clips[0]==core::Rect{11,46,81,244},"Expanded category clipping retains the unshifted source row origin");}}
 }
 mod::ArchiveMenuInput menu;const auto art=mod::prepareArchiveMenu(menu);auto bad=art;bad.root["transform"]=J::Array{1};rejects([&]{gpu::prepareArchiveScene(bad);},"Unsupported local transform rejects instead of generic raster approximation");
}
#ifdef _WIN32
void native(HWND hwnd,const wchar_t*shader,const J&fixture,const std::filesystem::path&assetRoot){gpu::Renderer renderer;renderer.initialize(hwnd,512,512,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});renderer.setCamera(gpu::layerViewportProjection(512,512));gpu::LayerRasterizer raster;gpu::LayerRasterOptions options;options.pixelsPerPoint=1;options.assetRoot=assetRoot;auto repo=std::make_shared<Repository>();mod::ArchiveEntry entry;entry.id="B0000000-0000-4000-8000-000000000001";entry.title="Source Archive";repo->docs.push_back(entry);mod::ArchiveState state(repo,inlineExecutor(),gpu::nativeArchiveTextRules());state.activate();gpu::NativeArchiveScene scene(raster,options);auto i=input(fixture);auto art=mod::prepareArchiveArtwork(state,i);check(scene.syncContent(art,1,0),"Actual Archive gallery stages retained source artwork and original icon");scene.uploadResources(renderer);scene.updatePose({core::Matrix4::translation(32,32),1,0});scene.uploadAnimations(renderer);gpu::LayerComposition composition;composition.setEntries(renderer,scene.entries());composition.present(renderer);renderer.draw(false);check(scene.entries().size()==2&&renderer.stats().nativeGroups==1,"Backdrop and one grouped source face share the existing publisher");const auto before=raster.stats();const auto gpuBefore=renderer.stats();allocations=0;counting=true;try{for(unsigned n=0;n<120;++n){core::Matrix4 world=core::Matrix4::translation(32+n*.01,32);world.values[3]=n*.000001;scene.updatePose({world,1,n/600.});scene.uploadAnimations(renderer);composition.present(renderer);renderer.draw(false);}}catch(...){counting=false;throw;}counting=false;check(allocations==0&&raster.stats().rasterizations==before.rasterizations,"Steady tilt allocates/rasterizes no Archive artwork");check(renderer.stats().nativeGroupRenders==gpuBefore.nativeGroupRenders&&renderer.stats().nativeGroupTargetAllocations==gpuBefore.nativeGroupTargetAllocations,"Root tilt preserves a single finished group target");scene.setFeedback(core::Point{20,310},false,.3);scene.updatePose({core::Matrix4::translation(32,32),1,.44});scene.uploadAnimations(renderer);composition.present(renderer);renderer.draw(false);check(raster.stats().rasterizations==before.rasterizations&&renderer.stats().nativeGroupRenders==gpuBefore.nativeGroupRenders+1,"Hover only updates retained numeric tint/rim then one GPU group pass");
 state.select(entry.id);art=mod::prepareArchiveArtwork(state,i);scene.syncContent(art,2,.5,true);scene.uploadResources(renderer);scene.updatePose({core::Matrix4::translation(32,32),1,.5});scene.uploadAnimations(renderer);composition.setEntries(renderer,scene.entries());composition.present(renderer);renderer.draw(false);check(scene.entries().size()==3&&scene.stats().outgoingSurfaces>0,"Source .18s face exchange retains outgoing paint above incoming");const auto entering=raster.stats();check(!scene.syncContent(art,3,.55)&&raster.stats().rasterizations==entering.rasterizations,"Body/save revisions with identical visible Canvas artwork perform no rebuild");scene.updatePose({core::Matrix4::translation(32,32),1,.71});scene.uploadAnimations(renderer);composition.setEntries(renderer,scene.entries());scene.collectRetired(renderer);composition.present(renderer);renderer.draw(false);check(scene.entries().size()==2&&scene.stats().retiredParts==0&&!scene.requiresFrames(.71),"Source .2s retirement removes only detached outgoing resources");
 auto invalid=art;invalid.root["children"]=J::Array{};const auto builds=scene.stats().builds;rejects([&]{scene.syncContent(invalid,4,.72);},"Invalid staged content cannot replace a published source face");check(scene.stats().builds==builds&&scene.entries().size()==2,"Failed content preserves retained publication and bindings");i.appearance.dark=false;art=mod::prepareArchiveArtwork(state,i);scene.syncContent(art,4,.73);scene.uploadResources(renderer);scene.updatePose({core::Matrix4::translation(32,32),1,.73});scene.uploadAnimations(renderer);composition.setEntries(renderer,scene.entries());check(scene.collectRetired(renderer),"Theme replacement retires old backdrop only after replacement publication");composition.present(renderer);renderer.draw(false);composition.detach(renderer);check(scene.releaseResources(renderer)&&renderer.stats().resourceBytes==0,"Archive teardown preserves no group/resource references");renderer.reset();}
#endif
}
int main(int argc,char**argv){try{
#ifdef _WIN32
 check(argc==4,"Supply shader, compact source fixture and original prepared raster root");const auto bytes=ehud::data::detail::readFile(argv[2],2*1024*1024);check(bytes.has_value(),"Compact original source metadata exists");const auto fixture=J::parse(*bytes,2*1024*1024);portable(fixture);const HRESULT initialized=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);check(SUCCEEDED(initialized),"Owned test COM apartment initialized");HWND hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,L"STATIC",L"Owned Archive scene contract",WS_OVERLAPPED,0,0,512,512,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);check(hwnd!=nullptr,"Owned hidden fixture HWND created");try{native(hwnd,std::filesystem::path(argv[1]).c_str(),fixture,argv[3]);}catch(...){DestroyWindow(hwnd);CoUninitialize();throw;}DestroyWindow(hwnd);CoUninitialize();
#else
 check(argc==2,"Supply compact actual source Archive fixture");const auto bytes=ehud::data::detail::readFile(argv[1],2*1024*1024);check(bytes.has_value(),"Actual source metadata exists");portable(J::parse(*bytes,2*1024*1024));
#endif
 std::cout<<"PASS "<<checks<<" Archive retained scene contracts\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
