#include "tools/archive_media_binding.hpp"
#ifdef _WIN32
#include "native/archive_text_rules.hpp"
#include "native/module_scene.hpp"
#include "core/data/file_io.hpp"
#include <objbase.h>
#include <atomic>
#include <cstdlib>
#include <iostream>
#include <new>
#include <stdexcept>
namespace {thread_local bool counting{};thread_local std::size_t allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {
namespace n=endfield::native;namespace m=endfield::modules;namespace a=endfield::app;namespace t=endfield::tools;namespace c=endfield::core;using J=ehud::data::Json;
unsigned checks{};void check(bool ok,const char*why){++checks;if(!ok)throw std::runtime_error(why);}
struct Window {HWND hwnd{};static constexpr UINT notice=WM_APP+249;Window(){hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,L"STATIC",L"Owned hidden Archive shared media fixture",WS_POPUP,0,0,1280,800,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Only explicit hidden fixture HWND is created");}~Window(){if(hwnd)DestroyWindow(hwnd);}};
struct Repository: m::ArchiveRepository {std::vector<m::ArchiveEntry>docs;std::optional<std::string>selectionID;std::vector<m::ArchiveCategory>categories()override{return {};}std::vector<m::ArchiveSummary>summaries()override{std::vector<m::ArchiveSummary>v;for(const auto&e:docs)v.push_back(m::archiveSummary(e));return v;}std::optional<m::ArchiveEntry>entry(std::string_view id)override{for(const auto&e:docs)if(e.id==id)return e;return {};}std::optional<std::string>selection()override{return selectionID;}void select(const std::optional<std::string>&id)override{selectionID=id;}void save(const m::ArchiveEntry&e)override{for(auto&v:docs)if(v.id==e.id){v=e;return;}docs.push_back(e);}void saveCategory(const m::ArchiveCategory&)override{}void deleteCategory(std::string_view,std::span<const m::ArchiveEntry>)override{}void remove(std::string_view)override{}std::optional<J>thumbnail(std::string_view id)override{const auto e=entry(id);return e&&!e->media.empty()?std::optional(e->media[0]):std::nullopt;}};
m::ArchiveExecutor immediate(){return {[](auto work,auto done){std::exception_ptr error;try{work();}catch(...){error=std::current_exception();}done(error);return true;}};}
class Sequence final:public n::NativeNotesImageDecoder::Sequence {n::NotesImageInfo info_;bool poster_{};public:explicit Sequence(const n::NotesImageRequest&r):poster_(r.videoPoster){const bool gif=r.path.ends_with(".gif")&&!r.firstFrameOnly&&!r.videoPoster;info_={2,2,gif?2u:1u,gif?m::NotesMediaKind::gif:m::NotesMediaKind::image,gif?std::vector<double>{600,.04}:std::vector<double>{},gif?600.04:0};}const n::NotesImageInfo&info()const override{return info_;}n::NotesImageFrame decode(unsigned index)override{n::NotesImageFrame f{2,2,index,std::vector<std::uint8_t>(16)};for(unsigned p=0;p<16;p+=4){f.straightRGBA[p+(poster_?2:index*2)]=255;f.straightRGBA[p+3]=255;}return f;}};
struct Probe {n::NativeNotesVideoPlayback::Notify notify;double position{};unsigned plays{},seeks{},stops{};};
class Engine final:public n::NativeNotesVideoPlayback::Engine {std::shared_ptr<Probe>p_;public:explicit Engine(std::shared_ptr<Probe>p):p_(std::move(p)){}HRESULT open(const n::NotesVideoRequest&)override{p_->notify(n::NativeNotesVideoPlayback::ready,S_OK);return S_OK;}HRESULT metadata(n::NotesVideoMetadata&out)override{out={2,2,10};return S_OK;}HRESULT play()override{++p_->plays;return S_OK;}HRESULT pause()override{return S_OK;}HRESULT seek(double value)override{p_->position=value;++p_->seeks;p_->notify(n::NativeNotesVideoPlayback::seeked,S_OK);return S_OK;}double currentTime()const override{return p_->position;}HRESULT tick(std::int64_t&)override{return S_FALSE;}HRESULT transfer(void*,unsigned,unsigned)override{return E_NOTIMPL;}void stop()noexcept override{++p_->stops;}};
J reference(std::string file,std::string kind="image"){return J::parse(ehud::data::makeWindowsMediaReference("C:\\Owned-fixture\\"+file,file,2,2,kind,kind=="image"?std::nullopt:std::optional(kind=="gif"?600.04:10.),kind=="gif"?2:1));}
void run(const std::filesystem::path&shader,const std::filesystem::path&fixturePath,const std::filesystem::path&assetRoot){
 const auto bytes=ehud::data::detail::readFile(fixturePath,2*1024*1024);check(bytes.has_value(),"Compact unchanged-source Archive fixture exists");const auto fixture=J::parse(*bytes);Window window;n::Renderer renderer;renderer.initialize(window.hwnd,1280,800,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests,true});renderer.setCamera(n::layerViewportProjection(1280,800));n::LayerImageSource images;n::LayerRasterizer raster;auto repository=std::make_shared<Repository>();for(unsigned k=0;k<24;++k){m::ArchiveEntry e;e.id="B0000000-0000-4000-8000-"+std::string(11,'0')+"0";e.id.replace(e.id.size()-2,2,k<10?"0"+std::to_string(k):std::to_string(k));e.title="Owned fixture "+std::to_string(k);e.date=e.modified=24-k;e.media={reference("image"+std::to_string(k)+".png")};if(!k)e.media={reference("image0.png"),reference("image.gif","gif"),reference("movie.mp4","video")};repository->docs.push_back(e);}repository->selectionID=repository->docs[0].id;m::ArchiveState state(repository,immediate(),n::nativeArchiveTextRules());
 t::ArchivePreviewOptions options;options.raster.assetRoot=assetRoot;options.raster.memoryImages=&images;options.raster.pixelsPerPoint=1;options.view.appearance.contentsScale=1;options.view.appearance.systemOrange=m::ArchiveColor{1,.6,0,1};options.view.iconContents=J::Object{{"asset",fixture["rasterAssets"].array()[0]["path"]},{"sha256",fixture["rasterAssets"].array()[0]["sha256"]}};options.view.dateString=[](double){return "2026-09-21";};options.view.categoryCaptionWidth=[](auto){return 75.;};options.newID=[]{return ehud::data::makeUUID();};options.foundationNow=[]{return 811692800.;};options.parseLocalDate=[](auto)->std::optional<double>{return 811692800.;};
 t::ArchivePreview preview(state,window.hwnd,raster,nullptr,TF_CLIENTID_NULL,options);preview.resize({1280,800,96,1,1280,800});preview.focus(true,0);n::NativeNotesImageDecoder decoder([](const auto&r){return n::NotesImageAccess{std::filesystem::u8path(r.path),r.accessLease};},{window.hwnd,Window::notice,83},[](const auto&r,n::NotesImageAccess){if(r.path.ends_with("bad.png"))throw std::runtime_error("Synthetic codec failure");return std::make_unique<Sequence>(r);});n::NativeNotesImagePlayback playback(decoder);auto probe=std::make_shared<Probe>();n::NativeNotesVideoPlayback video(renderer,{window.hwnd,Window::notice,83},[&](auto device,auto notify){check(device!=nullptr,"Movie shares the single existing renderer device");probe->notify=std::move(notify);return std::make_unique<Engine>(probe);});n::NativeMediaRequestBroker broker(decoder,playback,{window.hwnd,Window::notice,83},&video);const auto client=broker.attachClient(),notes=broker.attachClient();const std::array sibling{n::NotesImagePlaybackRequest{{"same","C:\\Owned-fixture\\pinned.png",1,512},m::NotesMediaKind::image}};broker.setImages(notes,1,sibling,0);
 t::ArchiveMediaBindingOptions media;media.resolve=[](const J&r){if(r["referencePlatform"]!=J("windows"))throw std::runtime_error("Explicit relink required");return n::NotesImageAccess{std::filesystem::u8path(r["windowsPath"].string()),{}};};media.errorText=[](HRESULT){return "Fixture media unavailable";};media.loadThumbnail=[&](std::string id,auto done){state.loadThumbnail(std::move(id),std::move(done));};auto binding=std::make_unique<t::ArchiveMediaBinding>(preview,broker,client,renderer,images,media);c::source::DesktopChromeSettings settings;settings.viewport={0,0,1280,800};settings.module=c::Module::archive;c::ModulePresentation modules(c::Module::archive);n::LayerComposition composition;double time{};
 n::LayerScene geometry(raster);geometry.load(J::Object{{"bounds",J::Array{0,0,400,440}},{"children",J::Array{}}},options.raster);n::NativeModuleSurface surface(geometry,c::Module::archive);c::Projection plane;
 struct Stamp{n::LayerScene*scene{};std::uint64_t content{},resources{};std::size_t after{};};std::vector<Stamp>stamps;stamps.reserve(64);
 const auto paint=[&](double advance=0.,double tilt=0.){time+=advance;auto center=c::Matrix4::translation(tilt,0);const auto sample=modules.sample(time).presentation;preview.update(center,settings,sample,1,time);surface.update(center,settings,sample.current,1);plane=c::Projection::viewport(n::layerViewportProjection(1280,800)*surface.pose().contentWorld,1280,800);binding->sync(time);broker.accept(83,time);broker.sample(time);binding->refresh(time);preview.upload(renderer);const auto entries=preview.entries();bool changed=stamps.size()!=entries.size();for(std::size_t k=0;!changed&&k<entries.size();++k)changed=stamps[k].scene!=entries[k].scene||stamps[k].content!=entries[k].scene->contentRevision()||stamps[k].resources!=entries[k].scene->resourceRevision()||stamps[k].after!=entries[k].after.size();if(changed){composition.setEntries(renderer,entries);stamps.clear();for(const auto&e:entries)stamps.push_back({e.scene,e.scene->contentRevision(),e.scene->resourceRevision(),e.after.size()});}composition.present(renderer);preview.collected(renderer);binding->collectRetired();renderer.draw(false);};
 std::array<unsigned,4>lastPixel{};
 const auto await=[&](const char*stage,auto ready){const auto end=GetTickCount64()+10000;for(;;){paint();if(ready())break;const auto now=GetTickCount64();if(now>=end){const auto decode=broker.decoderStats();const auto*r=broker.findImage(notes,"same");std::cerr<<"Media wait stage="<<stage<<" ownerTime="<<time<<" selectedIndex="<<preview.mediaIndex()<<" visible="<<preview.mediaVisible()<<" BGRA="<<lastPixel[0]<<','<<lastPixel[1]<<','<<lastPixel[2]<<','<<lastPixel[3]<<" sibling="<<(r&&r->frame)<<" decoder(requests,decodes,pending,completed,inflight)="<<decode.requests<<','<<decode.decodes<<','<<decode.pending<<','<<decode.completed<<','<<decode.inFlight<<" wake="<<broker.nextWakeTime().has_value()<<" targets="<<renderer.stats().mediaTargets<<'\n';}check(now<end,"Bounded same-worker completion");MsgWaitForMultipleObjectsEx(0,nullptr,static_cast<DWORD>(end-now),QS_POSTMESSAGE,MWMO_INPUTAVAILABLE);MSG message{};while(PeekMessageW(&message,window.hwnd,0,0,PM_REMOVE)){} }};
 const auto click=[&](double x,double y){const auto point=plane.project({x,y});check(point.has_value(),"Shared source module plane projects media controls");preview.pointer({a::PointerKind::down,a::PointerButton::left,point->x,point->y},time);preview.pointer({a::PointerKind::up,a::PointerButton::left,point->x,point->y},time);preview.cancelInteraction(time);paint(1);};
 paint();await("initial red still plus pinned sibling",[&]{const auto frame=renderer.readback();const auto point=plane.project({149,310});if(!point)return false;const auto offset=std::size_t(point->y)*frame.rowBytes+std::size_t(point->x)*4;for(unsigned c=0;c<4;++c)lastPixel[c]=frame.pixels[offset+c];return frame.pixels[offset+2]>240&&frame.pixels[offset+1]<20&&broker.findImage(notes,"same")&&broker.findImage(notes,"same")->frame;});check(probe->plays==0,"Opening a still or paused movie never starts real/synthetic audio");const auto siblingFrame=broker.findImage(notes,"same")->frame;const auto before=raster.stats();const auto gpuBefore=renderer.stats();allocations=0;counting=true;try{for(unsigned k=0;k<120;++k)paint(.001,k*.001);}catch(...){counting=false;throw;}counting=false;check(allocations==0&&raster.stats().rasterizations==before.rasterizations&&renderer.stats().nativeGroupRenders==gpuBefore.nativeGroupRenders,"120 still media/tilt frames allocate or rasterize no Archive content");
 paint(0);click(357,282);check(preview.mediaIndex()==1,"Original media-next action changes selected attachment");await("selected GIF deadline",[&]{return broker.nextWakeTime().has_value();});click(295,322);const auto pause=preview.takeMediaAction();check(pause&&binding->action(*pause,time),"Original GIF playback action reaches its scoped shared record");paint(1);check(broker.findImage(notes,"same")->frame==siblingFrame,"Archive playback leaves pinned Notes artwork intact");click(357,282);await("selected paused movie",[&]{const auto frame=renderer.readback();const auto point=plane.project({149,310});if(!point)return false;const auto offset=std::size_t(point->y)*frame.rowBytes+std::size_t(point->x)*4;for(unsigned c=0;c<4;++c)lastPixel[c]=frame.pixels[offset+c];return lastPixel[0]>240&&lastPixel[1]<20&&lastPixel[2]<20&&video.stats().visible==1&&video.stats().engines==1;});check(probe->plays==0&&renderer.stats().mediaTargets==0&&video.stats().ticks==0&&video.stats().transfers==0,"Movie first opens paused with a distinct same-worker poster and no live video target/ticks");click(295,322);const auto play=preview.takeMediaAction();check(play&&binding->action(*play,time)&&probe->plays>0&&renderer.stats().mediaTargets==1,"Original movie play allocates one live target on the existing shared video owner");t::ArchiveMediaAction seek=*play;seek.kind=t::ArchiveMediaAction::Kind::seek;seek.seconds=7;check(binding->action(seek,time)&&probe->seeks==1,"Source seek is passed once to the shared native engine");paint(1);const auto progressRaster=raster.stats().rasterizations;const auto layouts=raster.stats().textLayoutsCreated;probe->position=8;paint(1);check(raster.stats().rasterizations==progressRaster&&raster.stats().textLayoutsCreated==layouts,"Movie progress changes only retained local GPU fill");
 click(340,17);click(169,52);const auto import=preview.takeMediaAction();check(import&&import->kind==t::ArchiveMediaAction::Kind::chooseLocal,"Original chooser returns tagged picker request");const std::array files{t::ArchiveMediaImportFile{"C:\\Owned-fixture\\good.png","good.png",{}},t::ArchiveMediaImportFile{"C:\\Owned-fixture\\bad.png","bad.png",{}}};check(binding->beginImport(*import,files,time),"Picker results validate on the app's existing worker");await("mixed import completion",[&]{return state.selected()->media.size()==4;});check(state.selected()->media[3]["displayName"]==J("good.png")&&state.selected()->media[3]["referencePlatform"]==J("windows"),"Successful siblings append reference-only metadata despite another codec failure");
 state.select({});paint(1);await("gallery poster window",[&]{return binding->cachedThumbnails()==6;});check(broker.findImage(notes,"same")->visible&&broker.findImage(notes,"same")->frame==siblingFrame,"Selected media cancellation and gallery requests preserve pinned Notes client");for(double y:{300.,600.,850.}){state.setGalleryScroll(y);paint(1);await("gallery poster window",[&]{return binding->cachedThumbnails()>=8;});}check(binding->cachedThumbnails()<=12,"Gallery retains at most twelve source-sized static posters");preview.setOverlayVisible(false,time+=1);paint();check(binding->cachedThumbnails()==0,"Hidden Archive releases its own gallery cache");check(images.stats().cachedImages==0&&broker.findImage(notes,"same")->visible,"Gallery clear retires only Archive memory bindings and not shared Notes requests");
 composition.detach(renderer);preview.release(renderer);check(binding->releaseResources(time)&&broker.detachClient(client),"Borrowed Archive media retires after its panel group references detach");binding.reset();broker.hideImages(notes,time);check(broker.retireImage(notes,"same")&&broker.detachClient(notes),"Sibling client cleans up independently");const auto worker=decoder.duplicateWorkerHandle();decoder.stop();check(WaitForSingleObject(worker,10000)==WAIT_OBJECT_0,"One shared serial worker exits through root lifecycle");CloseHandle(worker);check(renderer.stats().resourceBytes==0&&!IsWindowVisible(window.hwnd),"Hidden synthetic module leaves no GPU/user data resources");renderer.reset();
}
}
int wmain(int argc,wchar_t**argv){const auto initialized=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(initialized)&&argc==4,"Pass shader, unchanged-source compact Archive fixture and prepared raster root");run(argv[1],argv[2],argv[3]);CoUninitialize();std::cout<<"PASS "<<checks<<" Archive shared media checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(initialized))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(){return 0;}
#endif
