#include "modules/archive_state.hpp"
#include "native/archive_text_rules.hpp"
#include "core/data/file_io.hpp"
#include <algorithm>
#include <deque>
#include <iostream>
#include <map>
#include <stdexcept>

namespace {
namespace mod=endfield::modules;namespace core=endfield::core;using J=ehud::data::Json;
unsigned checks{};void check(bool v,const char*m){++checks;if(!v)throw std::runtime_error(m);}template<class F>void rejects(F&&f,const char*m){bool failure{};try{f();}catch(const std::exception&){failure=true;}check(failure,m);}
std::string id(char prefix,unsigned value){char text[64];std::snprintf(text,sizeof(text),"%c0000000-0000-4000-8000-%012u",prefix,value);return text;}
struct Repository:mod::ArchiveRepository {
    std::vector<mod::ArchiveCategory>cats;std::vector<std::string>order;std::map<std::string,mod::ArchiveEntry,std::less<>>documents;std::optional<std::string>selected;
    unsigned reads{},saves{},categorySaves{},removals{},categoryRemovals{};bool failSave{},failRead{},failRemoveCategory{},failRemove{};
    std::vector<mod::ArchiveCategory>categories()override{return cats;}
    std::vector<mod::ArchiveSummary>summaries()override{std::vector<mod::ArchiveSummary>out;for(const auto&key:order)out.push_back(mod::archiveSummary(documents.at(key)));return out;}
    std::optional<mod::ArchiveEntry>entry(std::string_view key)override{++reads;if(failRead)throw std::runtime_error("Synthetic lazy read failure");const auto it=documents.find(key);return it==documents.end()?std::nullopt:std::optional(it->second);}
    std::optional<std::string>selection()override{return selected;}
    void select(const std::optional<std::string>&key)override{selected=key;}
    void save(const mod::ArchiveEntry&e)override{++saves;if(failSave)throw std::runtime_error("Synthetic save failure");documents[e.id]=e;order.erase(std::remove(order.begin(),order.end(),e.id),order.end());order.insert(order.begin(),e.id);}
    void saveCategory(const mod::ArchiveCategory&c)override{++categorySaves;if(std::none_of(cats.begin(),cats.end(),[&](const auto&v){return v.id==c.id;}))cats.push_back(c);}
    void deleteCategory(std::string_view key,std::span<const mod::ArchiveEntry>drafts)override{++categoryRemovals;if(failRemoveCategory)throw std::runtime_error("Synthetic atomic category failure");auto next=documents;for(auto&[document,e]:next){(void)document;if(e.categoryID==key)e.categoryID.reset();}for(const auto&e:drafts)next[e.id]=e;documents.swap(next);cats.erase(std::remove_if(cats.begin(),cats.end(),[&](const auto&c){return c.id==key;}),cats.end());}
    void remove(std::string_view key)override{++removals;if(failRemove)throw std::runtime_error("Synthetic deletion failure");documents.erase(std::string(key));order.erase(std::remove(order.begin(),order.end(),key),order.end());if(selected==key)selected.reset();}
    std::optional<J>thumbnail(std::string_view key)override{const auto e=entry(key);return e&& !e->media.empty()?std::optional(e->media.front()):std::nullopt;}
};
struct Queue {
    struct Job{std::function<void()>work;std::function<void(std::exception_ptr)>done;std::exception_ptr error;bool worked{};};
    std::deque<Job>jobs;std::size_t capacity{32};unsigned accepted{},rejected{};
    mod::ArchiveExecutor executor(){return {[this](auto work,auto done){if(jobs.size()>=capacity){++rejected;return false;}jobs.push_back({std::move(work),std::move(done),{},false});++accepted;return true;}};}
    void work(){check(!jobs.empty()&&!jobs.front().worked,"Synthetic FIFO work exists");auto&job=jobs.front();try{job.work();}catch(...){job.error=std::current_exception();}job.worked=true;}
    void done(){check(!jobs.empty()&&jobs.front().worked,"Synthetic owner completion exists");auto job=std::move(jobs.front());jobs.pop_front();job.done(job.error);}
    void one(){work();done();}
    void drain(){for(unsigned budget=0;!jobs.empty();++budget){check(budget<10000,"State has no retry loop");one();}}
};
std::shared_ptr<Repository>fixture(){auto repo=std::make_shared<Repository>();for(unsigned n=1;n<=14;++n)repo->cats.push_back({id('A',n),"Category "+std::to_string(n),double(n),{}});for(unsigned n=1;n<=20;++n){mod::ArchiveEntry e;e.id=id('B',n);e.title="Document "+std::to_string(n);e.body="Body 中文 👩🏽‍💻";e.date=e.modified=n;if(n%3)e.categoryID=repo->cats[n%14].id;repo->documents[e.id]=e;repo->order.push_back(e.id);}return repo;}
void model(){const auto rules=endfield::native::nativeArchiveTextRules();check(rules.characters("👩🏽‍💻é中文")==4,"Source Characters count grapheme clusters rather than bytes/UTF16");check(rules.trimmed("\xE2\x80\x8B\n  名字\t")=="名字","Pinned Foundation whitespace includes zero-width space/newlines");check(rules.categoryNameKey("  STRAẞE ")==rules.categoryNameKey("straße")&&rules.categoryNameKey("É")==rules.categoryNameKey("é"),"Source category equality is case-insensitive and canonically equivalent");
    mod::ArchiveEntry entry;entry.id=id('B',1);entry.title="中文 👩🏽‍💻";entry.body="ABC 🐱";entry.date=1.25;entry.modified=-10;entry.extra["futurePayload"]=J::Object{{"opaqueID","00000123456789"}};entry.bodyStyle.extra["futureStyle"]=5;core::notes::RichText rich;rich.extra["futureRich"]=true;rich.runs.push_back({4,2,{.fontSize=48,.bold=true},{{"futureRun",2}}});entry.bodyRichText=rich;
    auto encoded=mod::encodeArchiveEntry(entry,rules);const auto decoded=mod::decodeArchiveEntry(encoded,rules);check(decoded==entry,"Archive rich UTF16 runs and all additive payload/style fields survive roundtrip");check(mod::archiveUTF8(mod::archiveUTF16(entry.body))==entry.body,"CJK/emoji UTF8 and ACP conversion is lossless");
    encoded.erase("titleStyle");encoded.erase("bodyStyle");auto legacy=mod::decodeArchiveEntry(encoded,rules);check(legacy.titleStyle.fontSize==17&&legacy.bodyStyle.fontSize==12,"Older payload style defaults preserve source title17/body12");
    auto media=J::parse(ehud::data::makeWindowsMediaReference("C:\\Synthetic\\image.png","image.png",32,24));media["futureMedia"]=J::Object{{"number","0123456789"}};mod::validateArchiveMedia(media);entry.media.push_back(media);check(mod::decodeArchiveEntry(mod::encodeArchiveEntry(entry,rules),rules).media==entry.media,"Native media locator/unknown fields preserved without reading files");
    auto ambiguous=media;ambiguous["bookmark"]="AQ==";rejects([&]{mod::validateArchiveMedia(ambiguous);},"Mixed Mac/Windows references reject before persistence");entry.title=std::string(201,'a');rejects([&]{mod::validateArchiveEntry(entry,rules);},"Source title limit is200 graphemes");entry.title="";entry.body.resize(mod::archiveMaximumBodyBytes+1,'b');rejects([&]{mod::validateArchiveEntry(entry,rules);},"Source body2MiB limit rejects instead of truncating");
    check(mod::archiveLegacyCategory(mod::ArchiveTemplate::journal).id=="8A67BC44-25D4-4DC1-91EF-000000000001"&&mod::archiveLegacyCategory(mod::ArchiveTemplate::research).created==-mod::archiveFoundationToUnix,"Legacy category identities and Unix0/Foundation epoch match Mac migration");
}
void state(){const auto rules=endfield::native::nativeArchiveTextRules();auto repo=fixture();Queue queue;mod::ArchiveState state(repo,queue.executor(),rules);state.activate();check(state.busy()&&state.entries().empty(),"Activation schedules one shared-executor load");queue.drain();check(state.entries().size()==20&&state.categories().size()==14&&repo->reads==0,"Gallery loads summaries without document bodies");check(state.galleryMaximum()==854&&state.categoryMaximum()==299,"Source gallery/category scroll extents retained");check(state.galleryRows().size()==6&&state.categoryRows().size()==7,"Source gallery and categories virtualize visible rows");check(state.scroll({150,150},44.5)&&state.galleryRows().size()==8,"Fractional scrolling exposes touching cards without paging");check(state.scroll({30,150},45.25)&&state.categoryRows().front().hit.height==15.75,"Category hit geometry clips fractional rows");check(state.setFilter({},true)&&state.galleryScroll()==0,"Uncategorized is a protected synthetic filter with source scroll reset");check(!state.deleteCategory("all")&&!state.deleteCategory("uncategorized"),"Protected filters cannot delete real categories");
    state.select(repo->order.front());queue.drain();check(repo->reads==1&&state.selected()&&state.bodyRect()==endfield::core::Rect{24,111,352,264},"Selecting lazily reads one document and exposes source body viewport");const auto first=state.selected()->id;auto draft=*state.selected();draft.body="First revision";state.update(draft,100,1);check(state.saveDeadline()==1.35&&repo->saves==0&&!state.flushIfDue(1.34),"Typing exposes one .35s deadline and causes no immediate IO");state.flushIfDue(1.35);queue.work();draft=*state.selected();draft.body="Latest revision";state.update(draft,101,1.4);queue.done();check(state.hasUnsavedChanges()&&!queue.jobs.empty(),"Older write acknowledgment cannot drop a newer draft");queue.drain();check(repo->documents.at(first).body=="Latest revision"&&!state.hasUnsavedChanges(),"Latest revision retries after old accepted save completes");
    repo->failSave=true;draft=*state.selected();draft.body="Preserved failed draft";state.update(draft,102,2);state.flush();queue.drain();const auto failures=repo->saves;check(state.error()&&state.hasUnsavedChanges()&&state.selected()->body==draft.body,"Save failure retains editable text rather than flattening/discarding");check(queue.jobs.empty()&&repo->saves==failures,"Failed same revision does not install an automatic retry loop");repo->failSave=false;state.retryPendingSaves();queue.drain();check(!state.error()&&!state.hasUnsavedChanges(),"Explicit Retry commits retained latest document");
    queue.capacity=1;draft=*state.selected();draft.body="Saturated queue draft";state.update(draft,103,3);state.flush();auto second=*state.selected();second.body="Newer saturated draft";state.update(second,104,3.1);state.flush();queue.drain();check(repo->documents.at(first).body==second.body&&!state.hasUnsavedChanges(),"Bounded shared queue backpressure preserves newest immutable save");queue.capacity=32;
    const auto removed=repo->cats.front().id;state.setFilter(removed);state.moveSelected(removed,105,4);queue.drain();draft=*state.selected();draft.body="Draft inside removed category";state.update(draft,106,5);repo->failRemoveCategory=true;check(state.deleteCategory(removed),"Confirmed category deletion changes references only");queue.drain();check(state.categories().size()==13&&!state.selected()->categoryID&&state.selected()->body==draft.body&&state.filtersUncategorized(),"Failed atomic category deletion keeps latest draft owned and visible as Uncategorized");repo->failRemoveCategory=false;state.retryPendingSaves();queue.drain();check(!repo->documents.at(first).categoryID&&repo->documents.at(first).body==draft.body&&!state.hasUnsavedChanges(),"Retry atomically saves drafts and removes category without deleting documents");
    const auto duplicate=state.createCategory(id('C',1)," category 2 ",200);check(duplicate&&*duplicate==repo->cats.front().id,"Category names deduplicate by source case folding/trim");
    state.select(repo->order[1]);state.select(repo->order[2]);queue.drain();check(state.selected()->id==repo->order[2],"Late earlier selection completion cannot replace newer document");
    repo->failRemove=true;const auto deleting=state.selected()->id;check(state.deleteSelected(),"Document deletion requires caller confirmation then schedules durable delete");queue.drain();check(!state.selected()&&std::any_of(state.entries().begin(),state.entries().end(),[&](const auto&e){return e.id==deleting;}),"Failed delete restores gallery reference without resurrecting editor");repo->failRemove=false;state.select(deleting);queue.drain();check(state.deleteSelected(),"Restored document can be selected and explicitly deleted again");queue.drain();check(!repo->documents.contains(deleting),"Delete affects document reference, no media IO occurs");
    auto owned=std::make_unique<mod::ArchiveState>(repo,queue.executor(),rules);owned->activate();queue.drain();owned->select(first);queue.drain();draft=*owned->selected();draft.title="Pending durable shutdown";owned->update(draft,300,10);owned->flush();owned.reset();queue.drain();check(repo->documents.at(first).title==draft.title,"Accepted save survives facade teardown without a UI callback");
}
void races(){const auto rules=endfield::native::nativeArchiveTextRules();auto repo=fixture();Queue queue;mod::ArchiveState state(repo,queue.executor(),rules);state.activate();queue.drain();state.select(repo->order.front());queue.drain();const auto first=state.selected()->id;
    // Full shared capacity may be held entirely by unrelated modules. No Archive
    // completion will arrive in this case; its owner explicitly reports space.
    queue.capacity=1;const auto shared=queue.executor();check(shared.submit([]{},[](auto){}),"Unrelated synthetic utility work occupies shared queue");auto draft=*state.selected();draft.body="Retained across external saturation";state.update(draft,100,1);state.flush();check(queue.rejected>0&&state.hasUnsavedChanges()&&repo->saves==0,"Rejected whole job keeps exact editable draft and performs no partial IO");queue.one();state.queueCapacityAvailable();queue.drain();check(repo->documents.at(first).body==draft.body&&!state.hasUnsavedChanges(),"Explicit capacity notification retries only the rejected durable snapshot");
    check(state.create(id('C',5),101),"Create can retain document and selection with one queue slot");check(state.hasUnsavedChanges()&&queue.rejected>1,"Created selection remains pending when save occupies bounded queue");queue.drain();check(repo->selected==id('C',5)&&repo->documents.contains(id('C',5))&&!state.hasUnsavedChanges(),"Save completion retries created selection without timer or lost startup state");queue.capacity=32;
    state.select(first);queue.drain();repo->failRead=true;state.select(repo->order.back());queue.work();draft=*state.selected();draft.body="New outgoing edit while read fails";state.update(draft,102,2);queue.done();check(state.error()&&state.selected()->id==first&&state.selected()->body==draft.body,"Failed switch preserves newest outgoing editor draft rather than its stale pre-request copy");repo->failRead=false;state.flush();queue.drain();
    const auto category=repo->cats.front().id;state.moveSelected(category,103,3);queue.drain();check(state.deleteCategory(category),"Queue source category-reference transaction");queue.work();draft=*state.selected();draft.body="New draft during category transaction";state.update(draft,104,4);queue.done();check(!queue.jobs.empty(),"Successful category transaction queues a newer affected draft immediately");queue.drain();check(repo->documents.at(first).body==draft.body&&!repo->documents.at(first).categoryID&&!state.hasUnsavedChanges(),"Category acknowledgment cannot strand newer dirty text behind removed reference");
    // Inline injected executors are supported by the unchanged source; callbacks
    // can mutate dirty maps without invalidating a caller's traversal.
    auto inlineRepo=std::make_shared<Repository>();mod::ArchiveExecutor immediate{[](auto work,auto done){std::exception_ptr failure;try{work();}catch(...){failure=std::current_exception();}done(failure);return true;}};mod::ArchiveState inlineState(inlineRepo,immediate,rules);inlineState.activate();check(inlineState.create(id('D',1),105)&&!inlineState.hasUnsavedChanges()&&inlineRepo->selected==id('D',1),"Inline source-style executor drains create and selection without recursive retry loop");
}
void reference(const std::filesystem::path&root){const auto rules=endfield::native::nativeArchiveTextRules();const auto index=J::parse(*ehud::data::detail::readFile(root/"archive-reference.json",32*1024*1024),32*1024*1024);
    for(const auto&metadata:index["entries"].array()){if(metadata["kind"].string()!="canvas")continue;const auto row=J::parse(*ehud::data::detail::readFile(root/metadata["file"].string(),32*1024*1024),32*1024*1024);auto repo=std::make_shared<Repository>();for(const auto&value:row["categories"].array())repo->cats.push_back(mod::decodeArchiveCategory(value,rules));for(const auto&value:row["entries"].array()){auto entry=mod::decodeArchiveEntry(value,rules);repo->order.push_back(entry.id);repo->documents[entry.id]=std::move(entry);}if(!row["selectedID"].isNull())repo->selected=row["selectedID"].string();Queue queue;mod::ArchiveState state(repo,queue.executor(),rules);state.activate();queue.drain();state.setFilter(row["categoryID"].isNull()?std::nullopt:std::optional(row["categoryID"].string()),row["filtersUncategorized"].boolean());state.scroll({30,150},row["categoryScrollOffset"].number());state.setGalleryScroll(row["scrollOffset"].number());
        check(state.galleryMaximum()==row["galleryScrollMaximum"].number(),"Actual Mac gallery extent matches native state");check(state.bodyRect()==endfield::core::Rect{row["bodyRect"].array()[0].number(),row["bodyRect"].array()[1].number(),row["bodyRect"].array()[2].number(),row["bodyRect"].array()[3].number()},"Actual Mac attachment/body viewport matches");
        const auto rows=state.galleryRows();for(const auto&action:row["actions"].array())if(action["id"].string().starts_with("entry:")){const auto wanted=action["id"].string().substr(6);const auto found=std::find_if(rows.begin(),rows.end(),[&](const auto&r){return r.id==wanted;});const auto&rect=action["rect"].array();check(found!=rows.end()&&found->hit==endfield::core::Rect{rect[0].number(),rect[1].number(),rect[2].number(),rect[3].number()},"Actual Mac clipped gallery hit matches fractional native layout");}
    }
}
void textReference(const std::filesystem::path&root){const auto rules=endfield::native::nativeArchiveTextRules();const auto bytes=ehud::data::detail::readFile(root/"archive-text-reference.json",64*1024);check(bytes.has_value(),"Detached original text reference exists");const auto oracle=J::parse(*bytes,64*1024);
    for(const auto&row:oracle["text"].array()){const auto&text=row["text"].string();check(rules.characters(text)==std::size_t(row["characters"].integer())&&rules.trimmed(text)==row["trimmed"].string(),"Installed native Unicode rules match original Swift Characters/Foundation trimming fixture");}
    for(const auto&row:oracle["pairs"].array())check((rules.categoryNameKey(row["left"].string())==rules.categoryNameKey(row["right"].string()))==row["equal"].boolean(),"Installed native category equality matches unchanged ArchiveCategory.nameKey");
}
}
int main(int argc,char**argv){try{check(argc>=1&&argc<=3,"Optional arguments are actual-source Archive canvas and text reference roots");model();state();races();if(argc>=2)reference(argv[1]);if(argc==3)textReference(argv[2]);std::cout<<"PASS "<<checks<<" Archive state/model contracts\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
