#include "modules/archive_presentation.hpp"
#include "native/archive_text_rules.hpp"
#include "core/data/file_io.hpp"
#include <algorithm>
#include <cmath>
#include <iostream>
#include <map>
#include <stdexcept>

namespace {
namespace mod=endfield::modules;namespace core=endfield::core;using J=ehud::data::Json;
unsigned checks{};void check(bool value,const std::string&reason){++checks;if(!value)throw std::runtime_error(reason);}template<class F>void rejects(F&&f,const char*reason){bool failed{};try{f();}catch(const std::exception&){failed=true;}check(failed,reason);}
struct Repository:mod::ArchiveRepository {
 std::vector<mod::ArchiveCategory>cats;std::vector<mod::ArchiveEntry>docs;std::optional<std::string>selected;
 std::vector<mod::ArchiveCategory>categories()override{return cats;}
 std::vector<mod::ArchiveSummary>summaries()override{std::vector<mod::ArchiveSummary>out;for(const auto&e:docs)out.push_back(mod::archiveSummary(e));return out;}
 std::optional<mod::ArchiveEntry>entry(std::string_view id)override{for(const auto&e:docs)if(e.id==id)return e;return {};}
 std::optional<std::string>selection()override{return selected;}
 void select(const std::optional<std::string>&id)override{selected=id;}
 void save(const mod::ArchiveEntry&)override{}void saveCategory(const mod::ArchiveCategory&)override{}
 void deleteCategory(std::string_view,std::span<const mod::ArchiveEntry>)override{}void remove(std::string_view)override{}
 std::optional<J>thumbnail(std::string_view)override{return {};}
};
J expand(const J::Array&nodes,std::size_t index,unsigned depth=0){check(index<nodes.size()&&depth<64,"Bounded immutable source node reference");auto out=nodes[index];J::Array children;for(const auto&child:out["children"].array()){const auto next=std::size_t(child.integer());check(next<index,"Original fixture references are bottom-up and acyclic");children.push_back(expand(nodes,next,depth+1));}out["children"]=std::move(children);if(out["mask"].isNumber()){const auto next=std::size_t(out["mask"].integer());check(next<index,"Original mask reference is acyclic");out["mask"]=expand(nodes,next,depth+1);}return out;}
void values(const J&a,const J&b,std::string path){if(a.isNumber()&&b.isNumber()){check(std::isfinite(a.number())&&std::isfinite(b.number())&&std::abs(a.number()-b.number())<1e-6,path+" numeric source fact");return;}if(a.isArray()&&b.isArray()){check(a.array().size()==b.array().size(),path+" ordered array size");for(std::size_t n=0;n<a.array().size();++n)values(a.array()[n],b.array()[n],path+"/"+std::to_string(n));return;}if(a.isObject()&&b.isObject()){check(a.object().size()==b.object().size(),path+" source object fields");for(const auto&[key,value]:a.object())values(value,b[key],path+"/"+key);return;}check(a==b,path+" original source value");}
J defaulted(const J&node,std::string_view key,J fallback){return node[key].isNull()?std::move(fallback):node[key];}
J rgba(const J&value){return value.isNull()?J{}:value["sRGB"];}
void layers(const J&actual,const J&expected,std::string path,bool root=false){
 check(actual["kind"]==expected["kind"],path+" source layer kind");
 if(!root)values(actual["frame"],expected["frame"],path+"/frame");values(actual["bounds"],expected["bounds"],path+"/bounds");
 // Canvas root mounting is caller-owned. Source default anchor creates negative
 // outer frame; all of its local bounds and child geometry remain authoritative.
 for(const auto*key:{"opacity","cornerRadius","borderWidth","zPosition"})values(defaulted(actual,key,J(std::string_view(key)=="opacity"?1:0)),expected[key],path+"/"+key);
 for(const auto*key:{"hidden","masksToBounds","allowsGroupOpacity"})values(defaulted(actual,key,J(std::string_view(key)=="allowsGroupOpacity")),expected[key],path+"/"+key);
 values(defaulted(actual,"contentsScale",1),expected["contentsScale"],path+"/contentsScale");values(defaulted(actual,"contentsGravity","resize"),expected["contentsGravity"],path+"/contentsGravity");
 values(rgba(actual["backgroundColor"]),rgba(expected["backgroundColor"]),path+"/backgroundColor");if(expected["borderWidth"].number()>0)values(rgba(actual["borderColor"]),rgba(expected["borderColor"]),path+"/borderColor");
 values(actual["contents"],expected["contents"],path+"/contents");
 if(actual["text"].isObject()){const auto&a=actual["text"],&e=expected["text"];for(const auto*k:{"string","fontSize","alignment","wrapped","truncation","runs"})values(a[k],e[k],path+"/text/"+k);for(const auto*k:{"familyName","postScriptName","pointSize","symbolicTraits"})values(a["font"][k],e["font"][k],path+"/font/"+k);values(rgba(a["foregroundColor"]),rgba(e["foregroundColor"]),path+"/foregroundColor");}
 if(actual["shape"].isObject()){const auto&a=actual["shape"],&e=expected["shape"];for(const auto*k:{"lineWidth","lineCap","lineJoin","miterLimit","fillRule","path"})values(a[k],e[k],path+"/shape/"+k);values(rgba(a["fillColor"]),rgba(e["fillColor"]),path+"/fillColor");values(rgba(a["strokeColor"]),rgba(e["strokeColor"]),path+"/strokeColor");}
 std::vector<const J*>aChildren,eChildren;for(const auto&c:actual["children"].array())if(!c["hidden"].isBool()||!c["hidden"].boolean())aChildren.push_back(&c);for(const auto&c:expected["children"].array())if(!c["hidden"].boolean()&&c["name"]!=J("archive.outgoingFace"))eChildren.push_back(&c);
 check(aChildren.size()==eChildren.size(),path+" source paint-order child count: native="+std::to_string(aChildren.size())+" source="+std::to_string(eChildren.size()));for(std::size_t n=0;n<aChildren.size();++n)layers(*aChildren[n],*eChildren[n],path+"/"+std::to_string(n));
}
const J*find(const J&root,const std::function<bool(const J&)>&predicate){if(predicate(root))return &root;for(const auto&child:root["children"].array())if(const auto*result=find(child,predicate))return result;return nullptr;}
mod::ArchiveExecutor immediate(){return {[](auto work,auto done){std::exception_ptr failure;try{work();}catch(...){failure=std::current_exception();}done(failure);return true;}};}
void source(const J&fixture){check(fixture["schemaVersion"].integer()==1&&fixture["sourceAuthority"].string()=="ca04f142185c7de40acd8523bdb563195d90a1d1"&&!fixture["windowsCreated"].boolean()&&!fixture["mediaOpened"].boolean(),"Actual source fixture authority/detached constraints");const auto rules=endfield::native::nativeArchiveTextRules();std::map<std::string,double,std::less<>>widths;for(const auto&v:fixture["textReference"]["captionWidths"].array())widths[v["text"].string()]=v["width"].number();unsigned cases{};
 for(const auto&row:fixture["states"].array()){const auto expected=expand(fixture["nodes"].array(),std::size_t(row["root"].integer()));auto repo=std::make_shared<Repository>();for(const auto&v:row["categories"].array())repo->cats.push_back(mod::decodeArchiveCategory(v,rules));for(const auto&v:row["entries"].array())repo->docs.push_back(mod::decodeArchiveEntry(v,rules));if(!row["selectedID"].isNull())repo->selected=row["selectedID"].string();mod::ArchiveState state(repo,immediate(),rules);state.activate();state.setFilter(row["categoryID"].isNull()?std::nullopt:std::optional(row["categoryID"].string()),row["filtersUncategorized"].boolean());state.scroll({30,150},row["categoryScrollOffset"].number());state.setGalleryScroll(row["scrollOffset"].number());
  mod::ArchiveArtwork artwork;const auto kind=row["kind"].string();if(kind=="canvas"){mod::ArchiveViewInput input;input.appearance.dark=row["dark"].boolean();input.appearance.systemOrange=mod::ArchiveColor{1,159./255,10./255,1};input.dateString=[](double){return "2026-09-21";};input.categoryCaptionWidth=[&](std::string_view title){const auto it=widths.find(title);check(it!=widths.end(),"Independent original NSString measurement exists for category");return it->second;};input.iconContents=J::Object{{"asset",fixture["rasterAssets"].array().front()["path"]},{"sha256",fixture["rasterAssets"].array().front()["sha256"]}};if(!row["formattingField"].isNull())input.formattingField=row["formattingField"].string();input.mediaIndex=std::size_t(row["mediaIndex"].integer());if(const auto*swatch=find(expected,[](const J&n){return n["frame"]==J(J::Array{4,4,14,14});}))for(unsigned n=0;n<4;++n)input.formattingColor[n]=swatch->operator[]("backgroundColor")["sRGB"].array()[n].number();if(const auto*status=find(expected,[](const J&n){return n["kind"]==J("text")&&n["frame"].array()[1].number()==421;}))input.statusMessage=(*status)["text"]["string"].string();artwork=mod::prepareArchiveArtwork(state,input);
  }else{mod::ArchiveMenuInput input;input.categories=state.categories();input.appearance.dark=expected["children"].array()[1]["backgroundColor"]["sourceComponents"].array()[0].number()<.5;input.scrollOffset=row["menuScrollOffset"].number();input.kind=kind=="categoryMenu"?mod::ArchiveMenuKind::category:kind=="deleteDocumentMenu"?mod::ArchiveMenuKind::deleteDocument:mod::ArchiveMenuKind::deleteCategory;input.editingName=row["state"]==J("category-menu-create");artwork=mod::prepareArchiveMenu(input);}
  const auto label=row["state"].string();layers(artwork.root,expected,label,true);check(artwork.actions.size()==row["actions"].array().size(),label+" source action count");for(const auto&a:artwork.actions){const auto found=std::find_if(row["actions"].array().begin(),row["actions"].array().end(),[&](const auto&e){return e["id"]==J(a.id);});check(found!=row["actions"].array().end(),label+" original action identity");const auto&e=*found;check(a.title==e["title"].string()&&a.enabled==e["enabled"].boolean()&&a.selected==e["selected"].boolean(),label+" original action metadata");values(J::Array{a.rect.x,a.rect.y,a.rect.width,a.rect.height},e["rect"],label+" action rectangle");}++cases;
 }
 check(cases==21,"All21 original Archive canvas/menu cases compared");
}
void bounds(){auto repo=std::make_shared<Repository>();mod::ArchiveState state(repo,immediate(),endfield::native::nativeArchiveTextRules());state.activate();mod::ArchiveViewInput input;input.dateString=[](double){return "2001-01-01";};input.categoryCaptionWidth=[](auto){return 30.;};const auto artwork=mod::prepareArchiveArtwork(state,input);check(mod::archiveActionAt(artwork.actions,{20,310})==std::optional<std::string_view>("new"),"Source add action hit works");check(!mod::archiveActionAt(artwork.actions,{80,310})&&!mod::archiveActionAt(artwork.actions,{55,310}),"Disabled/remove and maximum edges cannot activate");input.appearance.contentsScale=9;rejects([&]{mod::prepareArchiveArtwork(state,input);},"Unsupported source scale rejects before content");input.appearance.contentsScale=2;input.categoryCaptionWidth=[](auto){return NAN;};rejects([&]{mod::prepareArchiveArtwork(state,input);},"Nonfinite caption metrics reject");check(mod::archiveCategoryMenuOrigin(false)==core::Point{100,49}&&mod::archiveCategoryMenuOrigin(true)==core::Point{126,38},"Source category menus retain exact button-relative anchors");check(mod::archiveMediaMenuOrigin({0,0,200,100})==core::Point{153,36},"Attachment chooser drops below add button");}
}
int main(int argc,char**argv){try{check(argc==2,"Supply compact actual-source Archive fixture JSON");const auto bytes=ehud::data::detail::readFile(argv[1],2*1024*1024);check(bytes.has_value(),"Actual source metadata available");source(J::parse(*bytes,2*1024*1024));bounds();std::cout<<"PASS "<<checks<<" Archive presentation/source contracts\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
