#include "tools/archive_preview.hpp"
#ifdef _WIN32
#include "modules/archive_repository.hpp"
#include "native/archive_text_rules.hpp"
#include "native/module_scene.hpp"
#include "core/data/file_io.hpp"
#include <objbase.h>
#include <atomic>
#include <cstdlib>
#include <filesystem>
#include <iostream>
#include <new>
#include <stdexcept>

namespace {std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};std::array<std::size_t,16>firstAllocationSizes{};}
void*operator new(std::size_t n){if(counting){const auto at=allocations.fetch_add(1);if(at<firstAllocationSizes.size())firstAllocationSizes[at]=n;}if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}
void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {
namespace gpu=endfield::native;namespace mod=endfield::modules;namespace app=endfield::app;namespace tools=endfield::tools;namespace core=endfield::core;namespace data=ehud::data;using J=data::Json;
unsigned checks{};void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}
struct Temporary {std::filesystem::path root=std::filesystem::canonical(std::filesystem::temp_directory_path())/("EndfieldHUD-Archive-Owner-"+data::makeUUID());Temporary(){check(!std::filesystem::exists(root),"New explicit fixture directory");std::filesystem::create_directory(root);}~Temporary(){std::error_code error;std::filesystem::remove_all(root,error);}};
struct Window {HWND hwnd{};Window(){hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,L"STATIC",L"Owned hidden Archive owner fixture",WS_OVERLAPPED,0,0,1280,800,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Owned no-redirection hidden fixture HWND");}~Window(){if(hwnd)DestroyWindow(hwnd);}};
mod::ArchiveExecutor immediate(){return {[](auto work,auto done){std::exception_ptr error;try{work();}catch(...){error=std::current_exception();}done(error);return true;}};}
void run(const wchar_t*shader,const std::filesystem::path&fixturePath,const std::filesystem::path&assetRoot){
 const auto bytes=data::detail::readFile(fixturePath,2*1024*1024);check(bytes.has_value(),"Original compact Archive fixture exists");const auto fixture=J::parse(*bytes,2*1024*1024);Window window;Temporary temporary;gpu::Renderer renderer;renderer.initialize(window.hwnd,1280,800,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});renderer.setCamera(gpu::layerViewportProjection(1280,800));gpu::LayerRasterizer raster;const auto rules=gpu::nativeArchiveTextRules();auto repository=std::make_shared<mod::ArchiveSQLiteRepository>(temporary.root/"Archive",rules);mod::ArchiveState state(repository,immediate(),rules);
 tools::ArchivePreviewOptions options;options.raster.assetRoot=assetRoot;options.raster.pixelsPerPoint=1;options.view.appearance.contentsScale=1;options.view.appearance.systemOrange=mod::ArchiveColor{1,159./255,10./255,1};options.view.iconContents=J::Object{{"asset",fixture["rasterAssets"].array().front()["path"]},{"sha256",fixture["rasterAssets"].array().front()["sha256"]}};options.view.dateString=[](double){return "2026-09-21";};options.view.categoryCaptionWidth=[](std::string_view){return 75.;};options.newID=[]{return data::makeUUID();};options.foundationNow=[]{return 811692800.;};options.parseLocalDate=[](std::string_view value)->std::optional<double>{return value=="2026-09-21"?std::optional(811692800.):std::nullopt;};options.fontFamilies=[]{return std::vector<std::string>{"Segoe UI","Consolas"};};
 tools::ArchivePreview preview(state,window.hwnd,raster,nullptr,TF_CLIENTID_NULL,options);preview.resize({1280,800,96,1,1280,800});preview.focus(true,0);core::source::DesktopChromeSettings settings;settings.viewport={0,0,1280,800};settings.module=core::Module::archive;core::ModulePresentation modules(core::Module::archive);double time{};gpu::LayerComposition composition;
 gpu::LayerScene geometry(raster);geometry.load(J::Object{{"bounds",J::Array{0,0,400,440}},{"children",J::Array{}}},options.raster);gpu::NativeModuleSurface surface(geometry,core::Module::archive);core::Projection plane;
 const auto paint=[&](double advance=1.){time+=advance;const auto sample=modules.sample(time).presentation;preview.update({},settings,sample,1,time);surface.update({},settings,sample.current,1);plane=core::Projection::viewport(gpu::layerViewportProjection(1280,800)*surface.pose().contentWorld,1280,800);preview.upload(renderer);composition.setEntries(renderer,preview.entries());preview.collected(renderer);composition.present(renderer);renderer.draw(false);};
 const auto point=[&](double x,double y){const auto projected=plane.project({x,y});check(projected.has_value(),"Original shared module plane projects fixture input");return *projected;};
 const auto click=[&](double x,double y){const auto p=point(x,y);check(preview.pointer({app::PointerKind::down,app::PointerButton::left,p.x,p.y},time),"Actual projected Archive input is consumed");preview.pointer({app::PointerKind::up,app::PointerButton::left,p.x,p.y},time);preview.pointer({app::PointerKind::captureLost},time);paint();};
 const auto type=[&](std::u16string_view value){for(auto c:value)check(preview.key({app::KeyKind::character,c},time),"Direct synthetic text input reaches shared projected field");paint();};
 paint();check(state.active()&&state.entries().empty()&&state.categories().empty(),"Archive opens source empty state with no invented default categories");click(25,314);check(!preview.activeField(),"Creation begins source category menu below add action");click(128,316);check(preview.activeField()==std::optional<std::string>("category"),"New category opens the projected inline name field");type(u"分类");click(333,315);check(state.categories().size()==1&&state.selected()&&state.selected()->categoryID==state.categories()[0].id,"Inline category creation selects the new document using injected SQLite callbacks");const auto documentID=state.selected()->id;
 click(42,62);check(preview.activeField()==std::optional<std::string>("title"),"Title uses its source viewport and shared editor");type(u"Archive");check(state.selected()->title=="Archive"&&preview.nextWakeTime().has_value(),"Typed title updates only retained draft and one source debounce deadline");check(preview.deadline(time+.35),"Existing owner scheduler flushes the .35 second save deadline");time+=.35;check(repository->entry(documentID)->title=="Archive","Title is persisted only in the explicit temporary Archive SQLite");
 click(114,390);check(preview.key({app::KeyKind::character,'Q'},time)&&state.selected()->title=="Archive","A modal formatting menu never forwards characters into the underlying field");click(40,344);check(state.selected()->titleStyle.bold,"Original formatting Special menu changes typed rich style");check(preview.key({app::KeyKind::down,VK_ESCAPE},time),"Escape closes the source formatting menu");paint();type(u"B");check(state.selected()->title=="ArchiveB"&&state.selected()->titleRichText.has_value()&&state.selected()->titleRichText->runs.back().style.bold,"Formatting persists rich runs and subsequent typing without plain flattening");
 click(42,125);type(u"正文");check(state.selected()->body=="正文","Body uses retained natural one-point paragraph layout");const auto currentEntries=preview.entries();check(currentEntries.size()>=9,"Main scene, all three real editor fields and registration share one composition");
 const auto before=raster.stats();const auto beforeGPU=renderer.stats();allocations=0;std::array<std::size_t,4>stageAllocations{};counting=true;try{for(unsigned n=0;n<120;++n){time+=1./60;auto center=core::Matrix4{};center.values[3]=n*.000001;auto count=allocations.load();preview.update(center,settings,modules.sample(time).presentation,1,time);stageAllocations[0]+=allocations.load()-count;count=allocations.load();preview.upload(renderer);stageAllocations[1]+=allocations.load()-count;count=allocations.load();preview.entries();stageAllocations[2]+=allocations.load()-count;count=allocations.load();composition.present(renderer);stageAllocations[3]+=allocations.load()-count;}}catch(...){counting=false;throw;}counting=false;
 if(allocations||raster.stats().rasterizations!=before.rasterizations||raster.stats().textLayoutsCreated!=before.textLayoutsCreated){std::cerr<<"warm allocations="<<allocations<<" stages(update,upload,entries,present)=";for(const auto n:stageAllocations)std::cerr<<n<<',';std::cerr<<" firstSizes=";for(const auto n:firstAllocationSizes)std::cerr<<n<<',';std::cerr<<" rasters="<<raster.stats().rasterizations-before.rasterizations<<" layouts="<<raster.stats().textLayoutsCreated-before.textLayoutsCreated<<'\n';}
 check(allocations==0&&raster.stats().rasterizations==before.rasterizations&&raster.stats().textLayoutsCreated==before.textLayoutsCreated,"120 steady tilt frames allocate, shape and raster no Archive content");check(renderer.stats().textureUploads==beforeGPU.textureUploads&&renderer.stats().nativeGroupTargetAllocations==beforeGPU.nativeGroupTargetAllocations,"Retained tilt performs no pixel uploads or GPU group allocation");
 // The numeric probe deliberately changes only the preview's projected plane.
 // Return both the retained scene and input helper to the same identity pose
 // before targeting source-local controls; this advances no owner time.
 paint(0);
 // Media selection is queued outside the synchronous repository callback.
 click(340,17);click(169,52);const auto import=preview.takeMediaAction();check(import&&import->kind==tools::ArchiveMediaAction::Kind::chooseLocal&&import->documentID==documentID&&import->remaining==16,"Source attachment chooser queues generation-tagged local selection");const auto image=J::parse(data::makeWindowsMediaReference("C:\\Synthetic\\never-open.png","never-open.png",32,24,"image",{},1));check(preview.receiveMedia(documentID,import->generation,{image},{},time),"Reference-only media completion appends current selected document");paint();check(state.selected()->media.size()==1&&state.bodyRect().height==147,"Attachment changes only source body viewport");click(350,125);type(u"Z");check(state.selected()->body=="正文Z","Resized viewport preserves prior body text and accepts subsequent editing");click(357,322);check(state.selected()->media.empty()&&state.bodyRect().height==264,"Source remove-media action restores text viewport without dropping its content");
 check(!preview.receiveMedia(documentID,import->generation+1,{image},{},time)&&state.selected()->media.empty(),"Late/stale media generation cannot mutate a different request");
 click(370,17);check(state.selected().has_value(),"Delete first opens source confirmation without mutating storage");click(254,210);check(!state.selected()&&state.entries().empty()&&!repository->entry(documentID),"Confirmed source deletion removes document from explicit temporary SQLite");
 settings.module=core::Module::power;modules.select(core::Module::power,time+=1);preview.update({},settings,modules.sample(time+.05).presentation,1,time+.05);check(!state.active()&&!preview.key({app::KeyKind::character,'X'},time+.05),"Module transition immediately disables editor/input while retaining outgoing artwork");preview.upload(renderer);composition.setEntries(renderer,preview.entries());composition.present(renderer);preview.update({},settings,modules.sample(time+1).presentation,1,time+1);check(preview.entries().empty()&&!preview.requiresFrames(time+1),"Completed section departure has no Archive frame demand");composition.setEntries(renderer,preview.entries());preview.collected(renderer);composition.detach(renderer);preview.release(renderer);check(renderer.stats().textures==0&&renderer.stats().meshes==0&&renderer.stats().nativeGroups==0&&!IsWindowVisible(window.hwnd),"Archive fixture tears down borrowed composition resources and never activates real TSF or UI");renderer.reset();
}
}
int wmain(int argc,wchar_t**argv){const auto initialized=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(initialized)&&argc==4,"Pass shader, original compact source fixture and prepared Archive asset root");run(argv[1],argv[2],argv[3]);CoUninitialize();std::cout<<"PASS "<<checks<<" Archive owner integration checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(initialized))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
