#include "modules/battery_presentation.hpp"
#include <cmath>
#include <fstream>
#include <iostream>
#include <sstream>
using namespace endfield;using namespace modules;using ehud::data::Json;
namespace {unsigned checks{};void check(bool v,const char*m){++checks;if(!v)throw std::runtime_error(m);}void near(double a,double b){check(std::abs(a-b)<2e-6,"Original numeric artwork");}
void numbers(const Json&a,const Json&b){check(a.isArray()&&b.isArray()&&a.array().size()==b.array().size(),"Original numeric shape");for(std::size_t n=0;n<a.array().size();++n)if(a.array()[n].isArray())numbers(a.array()[n],b.array()[n]);else near(a.array()[n].number(),b.array()[n].number());}
void color(const Json&a,const Json&b){if(a.isNull()||b.isNull())check(a.isNull()&&b.isNull(),"Original optional color");else numbers(a["sRGB"],b["sRGB"]);}
void compare(const Json&a,const Json&b,double dx=0,double dy=0){check(a["kind"]==b["kind"],"Original layer kind");numbers(a["bounds"],b["bounds"]);const auto&p=a["position"].array();const auto&f=b["frame"].array();near(p[0].number(),f[0].number()+dx);near(p[1].number(),f[1].number()+dy);
 if(a["kind"].string()=="text"){const auto&x=a["text"],&y=b["text"];for(auto k:{"string","fontSize","alignment","wrapped","truncation"}){if(x[k]!=y[k])std::cerr<<a["id"].string()<<" property "<<k<<'\n';check(x[k]==y[k],"Original text property");}for(auto k:{"postScriptName","familyName","pointSize","symbolicTraits"})check(x["font"][k]==y["font"][k],"Original font metadata");color(x["foregroundColor"],y["foregroundColor"]);}
 else {const auto&x=a["shape"],&y=b["shape"];for(auto k:{"lineCap","lineJoin","fillRule"})check(x[k]==y[k],"Original stroke style");near(x["lineWidth"].number(),y["lineWidth"].number());color(x["fillColor"],y["fillColor"]);color(x["strokeColor"],y["strokeColor"]);check(x["path"].array().size()==y["path"].array().size(),"Original path length");for(std::size_t n=0;n<x["path"].array().size();++n){const auto&u=x["path"].array()[n],&v=y["path"].array()[n];check(u["op"]==v["op"],"Original path operation");numbers(u["points"],v["points"]);}}
}
void oracle(const char*file){std::ifstream in(file);std::stringstream bytes;bytes<<in.rdbuf();const auto root=Json::parse(bytes.str());const auto&nodes=root["nodes"].array();auto node=[&](const Json&index)->const Json&{return nodes.at(static_cast<std::size_t>(index.number()));};
 for(const auto&c:root["cases"].array()){const int level=static_cast<int>(c["level"].number()),mode=static_cast<int>(c["mode"].number());BatteryReading r;r.percentage=level<0?std::nullopt:std::optional<unsigned>(level);r.present=mode>0;r.pluggedIn=mode>=2;r.charging=mode==3;r.fullyCharged=mode==4;BatteryAppearance a;a.dark=c["dark"].boolean();a.language=c["chinese"].boolean()?core::Language::simplifiedChinese:core::Language::english;BatteryPresentation p(r,a);check(p.chargeMode()==c["chargeMode"].boolean(),"Original charger connection mode");const auto art=prepareBatteryArtwork(p);const auto&source=node(c["root"])["children"].array(),&actual=art.layers["children"].array();check(source.size()==9&&actual.size()==10,"Original battery paint order");for(std::size_t n=0;n<7;++n)compare(actual[n],node(source[n]));const auto&feedback=node(source[7]);compare(actual[7],node(feedback["children"].array()[0]),111,314);compare(actual[8],node(feedback["children"].array()[1]),111,314);compare(actual[9],node(source[8]));}
}
void events(){BatteryPresentation p;const auto initial=p.revision();check(!p.receive({})&&p.revision()==initial,"Identical notifications do not rebuild");BatteryReading r;r.present=true;r.percentage=49;r.pluggedIn=true;check(p.receive(r)&&p.chargeMode()&&p.labels().state=="POWER CONNECTED","Charger negotiation enters charge mode immediately");r.charging=true;check(p.receive(r)&&p.labels().state=="CHARGING","Actual charge state remains separate");r.charging=false;r.fullyCharged=true;check(p.receive(r)&&p.labels().state=="FULLY CHARGED","Full source state");check(p.labels().capacity=="49 / 100 %","Percentage fallback is explicitly labelled");r.capacity=BatteryReading::Capacity{3100,5500,"mWh"};r.health="Reported condition";p.receive(r);check(p.labels().capacity=="3,100 / 5,500 mWh"&&p.labels().health=="Reported condition","Hardware units and category preserved");const auto previous=p.reading();r.percentage=101;bool rejected=false;try{p.receive(r);}catch(const std::invalid_argument&){rejected=true;}check(rejected&&p.reading()==previous,"Invalid provider update keeps prior reading");check(BatteryPresentation::hitsSettings({112,315})&&!BatteryPresentation::hitsSettings({290,315}),"Source settings hit region");
 for(auto language:{core::Language::english,core::Language::simplifiedChinese,core::Language::traditionalChinese,core::Language::japanese,core::Language::korean}){auto a=p.appearance();a.language=language;p.setAppearance(a);check(!p.labels().heading.empty()&&!p.labels().settings.empty(),"Existing five-language catalog");}
}
}
int main(int argc,char**argv){try{check(argc==2,"Pass source battery fixture");oracle(argv[1]);events();std::cout<<"Battery presentation: "<<checks<<" original-source and notification checks passed\n";}catch(const std::exception&e){std::cerr<<"Battery after "<<checks<<": "<<e.what()<<'\n';return 1;}}
