#ifdef _WIN32
#include "tools/battery_preview.hpp"
#include <objbase.h>
#include <algorithm>
#include <iostream>
namespace {namespace gpu=endfield::native;namespace c=endfield::core;namespace a=endfield::app;namespace t=endfield::tools;namespace m=endfield::modules;using Json=ehud::data::Json;
unsigned checks{};void check(bool v,const char*m){++checks;if(!v)throw std::runtime_error(m);}
struct Window{HWND h{};Window(){WNDCLASSW w{};w.lpfnWndProc=DefWindowProcW;w.hInstance=GetModuleHandleW(nullptr);w.lpszClassName=L"EndfieldBatteryOwnerFixture";check(RegisterClassW(&w)!=0,"Register own fixture");h=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,w.lpszClassName,L"Synthetic battery only",WS_POPUP,0,0,1280,800,nullptr,nullptr,w.hInstance,nullptr);check(h&&!IsWindowVisible(h),"Own battery fixture stays hidden");}~Window(){if(h)DestroyWindow(h);UnregisterClassW(L"EndfieldBatteryOwnerFixture",GetModuleHandleW(nullptr));}};
void run(const std::filesystem::path&shader){Window window;gpu::Renderer renderer;renderer.initialize(window.h,1280,800,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});const auto camera=gpu::layerViewportProjection(1280,800);renderer.setCamera(camera);gpu::LayerRasterizer raster;gpu::LayerComposition composition;gpu::LayerRasterOptions options;options.pixelsPerPoint=1;unsigned opened{};m::BatteryReading value;value.present=true;value.percentage=63;
 t::BatteryPreview owner(raster,options,value,{},[&]{++opened;});owner.resize({1280,800,96,1,1280,800});c::ModulePresentation modules{c::Module::power};c::source::DesktopChromeSettings settings{{0,0,1280,800},1,{},c::Module::power,true};auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;gpu::LayerScene geometry(raster);geometry.load(Json::Object{{"bounds",Json::Array{0,0,400,334}},{"children",Json::Array{}}},{});gpu::NativeModuleSurface plane(geometry,c::Module::power);double now{};bool done{};
 struct Cleanup{gpu::Renderer&r;gpu::LayerComposition&c;t::BatteryPreview&o;bool&done;~Cleanup(){if(done)return;try{c.detach(r);o.release(r);}catch(...){r.reset();}}}cleanup{renderer,composition,owner,done};
 auto frame=[&](double delta=.01){now+=delta;const auto sample=modules.sample(now).presentation;settings.module=sample.requested;owner.update(center,settings,sample,1,now);owner.upload(renderer);composition.setEntries(renderer,owner.entries());composition.present(renderer);owner.collected(renderer);};
 auto point=[&](c::Point p){const auto sample=modules.sample(now).presentation;plane.update(center,settings,sample.current,1);const auto q=c::Projection::viewport(camera*plane.pose().contentWorld,1280,800).project(p);check(q.has_value(),"Source plane projects battery control");return *q;};
 frame();check(owner.entries().size()==1&&!owner.requiresFrames(now),"Settled battery has one shared scene and no animation wake");renderer.draw(false);const auto pixels=renderer.readback();check(std::any_of(pixels.pixels.begin(),pixels.pixels.end(),[](auto v){return v!=0;}),"Original battery paints own target");const auto meshes=renderer.stats().meshes,textures=renderer.stats().textures;const auto resourceRevision=owner.entries()[0].scene->resourceRevision();
 auto q=point({200,324});check(owner.covers(q)&&owner.pointer({a::PointerKind::move,a::PointerButton::none,q.x,q.y},now)&&owner.requiresFrames(now),"Projected hover starts finite original feedback");frame(.2);check(!owner.requiresFrames(now),"Hover settles without periodic redraw");check(owner.pointer({a::PointerKind::down,a::PointerButton::left,q.x,q.y},now)&&opened==1,"Battery alert invokes injected Settings action");owner.pointer({a::PointerKind::up,a::PointerButton::left,q.x,q.y},now);frame(.2);
 for(unsigned n=0;n<120;++n){center=c::Matrix4::translation(.1*n,.05*n)*c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;frame();}check(owner.entries()[0].scene->resourceRevision()==resourceRevision&&renderer.stats().meshes==meshes&&renderer.stats().textures==textures,"Tilt updates reuse all battery artwork and GPU resources");
 gpu::BatterySnapshot source;source.available=true;source.present=true;source.ac_connected=true;source.charging=false;source.percent=63;check(owner.receive(source)&&owner.state().chargeMode()&&owner.state().labels().state=="POWER CONNECTED","Existing provider event displays connection immediately");frame();check(!owner.receive(source),"Repeated provider value cannot rerasterize");source.charging=true;check(owner.receive(source)&&owner.state().labels().state=="CHARGING","Actual charging is distinct");frame();source.ac_connected=false;source.charging=false;owner.receive(source);frame();check(!owner.state().chargeMode()&&owner.state().labels().state=="ON BATTERY","Unplug restores battery state");
 modules.select(c::Module::notes,now);frame(.5);frame(.5);check(owner.entries().empty()&&!owner.requiresFrames(now)&&!owner.covers(q),"Hidden battery submits nothing and consumes no input");composition.detach(renderer);owner.release(renderer);done=true;check(renderer.stats().meshes==0&&renderer.stats().textures==0&&!IsWindowVisible(window.h),"Battery detaches all own resources without live power reads");
}
}
int wmain(int argc,wchar_t**argv){const auto result=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(result)&&argc==2,"Pass HLSL to synthetic battery owner test");run(argv[1]);CoUninitialize();std::cout<<"Battery owner: "<<checks<<" checks passed\n";}catch(const std::exception&e){if(SUCCEEDED(result))CoUninitialize();std::cerr<<"Battery owner after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
