#include "modules/calendar_presentation.hpp"
#include "core/data/file_io.hpp"
#include <algorithm>
#include <cmath>
#include <iostream>
using namespace endfield::modules;
namespace {using J=CalendarJson;unsigned checks{};
void check(bool b,const char*m){++checks;if(!b)throw std::runtime_error(m);}
void equal(const J&a,const J&b){if(a.isNumber()&&b.isNumber()){if(std::abs(a.number()-b.number())>=1e-6)std::cerr<<"Expected number "<<a.encode()<<" actual "<<b.encode()<<'\n';check(std::abs(a.number()-b.number())<1e-6,"Original Calendar geometry/color/path number");return;}if(a.isArray()&&b.isArray()){check(a.array().size()==b.array().size(),"Original Calendar ordered tree/path count");for(std::size_t n=0;n<a.array().size();++n)equal(a.array()[n],b.array()[n]);return;}if(a.isObject()&&b.isObject()){for(const auto&[k,v]:a.object())try{equal(v,b[k]);}catch(...){std::cerr<<"Calendar field "<<k<<'\n';throw;}return;}if(a!=b)std::cerr<<"Expected "<<a.encode()<<" actual "<<b.encode()<<'\n';check(a==b,"Original Calendar text/control/state");}
J color(const J&j){return j.isNull()?J{}:J::Object{{"sRGB",j["sRGB"]}};}
J canonical(const J&n,bool root=false){J::Object out;const auto&b=n["bounds"].array();const auto&p=n["position"].array();const auto&a=n["anchorPoint"].array();if(!root)out.emplace("frame",J::Array{p[0].number()-a[0].number()*b[2].number(),p[1].number()-a[1].number()*b[3].number(),b[2],b[3]});for(const auto*k:{"kind","bounds","opacity","hidden","allowsGroupOpacity","masksToBounds","cornerRadius","borderWidth"}){auto v=n[k];if(v.isNull()){if(std::string_view(k)=="opacity")v=1;else if(std::string_view(k)=="allowsGroupOpacity")v=true;else if(std::string_view(k)=="cornerRadius"||std::string_view(k)=="borderWidth")v=0;else v=false;}out.emplace(k,std::move(v));}out.emplace("backgroundColor",color(n["backgroundColor"]));if(!n["borderWidth"].isNull()&&n["borderWidth"].number()>0)out.emplace("borderColor",color(n["borderColor"]));if(!n["text"].isNull()){J::Object t;for(const auto*k:{"string","fontSize","alignment","wrapped","truncation"})t.emplace(k,n["text"][k]);t.emplace("foregroundColor",color(n["text"]["foregroundColor"]));out.emplace("text",std::move(t));}if(!n["shape"].isNull()){J::Object s;for(const auto*k:{"path","lineWidth","lineCap","lineJoin","fillRule"})s.emplace(k,n["shape"][k]);s.emplace("fillColor",color(n["shape"]["fillColor"]));s.emplace("strokeColor",color(n["shape"]["strokeColor"]));out.emplace("shape",std::move(s));}J::Array children;for(const auto&c:n["children"].array())children.push_back(canonical(c));out.emplace("children",std::move(children));return out;}
CalendarDay day(const J&j){return{int(j["year"].integer()),int(j["month"].integer()),int(j["day"].integer())};}
CalendarEvent event(const J&j){CalendarEvent e;e.id=j["id"].string();e.title=j["title"].string();e.details=j["details"].string();e.day=day(j["day"]);e.created=j["created"].number();e.modified=j["modified"].number();return e;}
void original(const std::filesystem::path&p){auto bytes=ehud::data::detail::readFile(p,4*1024*1024);check(bool(bytes),"Original Calendar reference exists");const auto oracle=J::parse(*bytes,4*1024*1024);check(oracle["provenance"]["sourceAuthority"]==J("ca04f142185c7de40acd8523bdb563195d90a1d1"),"Calendar source authority is build18");for(const auto&row:oracle["cases"].array()){CalendarArtwork a;const auto name=row["state"].string();if(row["editing"].isBool()){CalendarMenuInput i;i.appearance.dark=row["dark"].boolean();i.editing=row["editing"].boolean();i.deleting=row["deleting"].boolean();i.busy=row["busy"].boolean();if(row["error"].isString())i.error=row["error"].string();a=prepareCalendarMenu(i);}else{CalendarCanvasInput i;i.today=day(row["today"]);i.month=day(row["month"]);i.selected=day(row["selected"]);i.appearance.dark=row["dark"].boolean();i.firstWeekday=unsigned(row["firstWeekday"].integer());i.firstEvent=std::size_t(row["firstEvent"].integer());i.busy=row["busy"].boolean();const auto permission=row["permission"].string();i.permission=permission=="denied"?CalendarPermission::denied:permission=="unavailable"?CalendarPermission::unavailable:CalendarPermission::authorized;if(row["error"].isString())i.error=row["error"].string();for(const auto&e:row["events"].array())i.events.push_back(event(e));const auto&sourceChildren=row["root"]["children"].array()[0]["children"].array();i.monthHeading=sourceChildren[5]["text"]["string"].string();a=prepareCalendarCanvas(i);if(name=="hover-today"){auto roots=a.root["children"].array();auto children=roots[0]["children"].array();auto highlight=children[3]["children"].array();highlight[0]["opacity"]=.62;highlight[1]["opacity"]=1;children[3]["children"]=std::move(highlight);roots[0]["children"]=std::move(children);a.root["children"]=std::move(roots);}const auto cells=calendarMonthCells(i.month,i.firstWeekday);check(cells.size()==row["monthCells"].array().size(),"Original month range");for(std::size_t n=0;n<cells.size();++n){check(cells[n].day==day(row["monthCells"].array()[n]["day"]),"Original grid Gregorian day identity");equal(J::Array{cells[n].rect.x,cells[n].rect.y,cells[n].rect.width,cells[n].rect.height},row["monthCells"].array()[n]["rect"]);}}
 try{equal(canonical(row["root"],true),canonical(a.root,true));}catch(...){std::cerr<<"Calendar source case "<<name<<'\n';throw;}check(a.actions.size()==row["actions"].array().size(),"Original Calendar ordered action count");for(std::size_t n=0;n<a.actions.size();++n){const auto&v=a.actions[n];const auto&r=row["actions"].array()[n];check(v.id==r["id"].string()&&v.label==r["label"].string()&&v.enabled==r["enabled"].boolean(),"Original Calendar action identity/text/enabled");equal(J::Array{v.rect.x,v.rect.y,v.rect.width,v.rect.height},r["rect"]);check(v.rect.y+v.rect.height<=413,"Calendar controls retain battery clearance");}}
}
}
int main(int argc,char**argv){try{check(argc==2,"Calendar source fixture argument required");original(std::filesystem::path(std::u8string(reinterpret_cast<const char8_t*>(argv[1]))));CalendarView view({2026,10,4});check(view.perform("previousMonth",{2026,10,4})&&view.month()==CalendarDay{2026,9,1},"Source month navigation");view.perform("today",{2026,10,4});check(view.month()==CalendarDay{2026,10,1}&&view.selected()==CalendarDay{2026,10,4},"Today resets selected day and month");check(view.scroll({50,320},31,6)&&view.firstEvent()==0&&view.scrollRemainder()==31,"Subrow Calendar wheel is retained");view.scroll({50,320},1,6);check(view.firstEvent()==1&&view.scrollRemainder()==0,"Source32 point row boundary");view.scroll({50,320},256,6);check(view.firstEvent()==3,"Calendar event rows clamp at last three");view.scroll({50,320},-256,6);check(view.firstEvent()==0,"Calendar wheel restores beginning");check(!view.scroll({400,320},32,6),"Source CGRect maximum edge excluded");view.perform("day:2026-10-05",{2026,10,4});check(view.selected()==CalendarDay{2026,10,5}&&view.firstEvent()==0,"Day selection resets list offset");std::cout<<"PASS "<<checks<<" Calendar presentation checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
