#ifdef _WIN32
#include "tools/calendar_preview.hpp"
#include "native/module_scene.hpp"
#include <objbase.h>
#include <array>
#include <atomic>
#include <cstdlib>
#include <deque>
#include <iostream>
#include <new>
namespace {std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {using namespace endfield;namespace gpu=native;namespace mod=modules;unsigned checks{};
void check(bool b,const char*m){++checks;if(!b)throw std::runtime_error(m);}
struct Window {HWND hwnd{};Window(){hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,L"STATIC",L"Owned hidden Calendar integration",WS_POPUP,0,0,1280,800,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Calendar integration owns a hidden window only");}~Window(){if(hwnd)DestroyWindow(hwnd);}};
struct Repository final:mod::CalendarRepository {mod::CalendarFile value;unsigned reads{},writes{};bool exists()override{return true;}mod::CalendarFile load()override{++reads;return value;}void save(const mod::CalendarFile&v)override{++writes;value=v;}};
struct Queue {struct Job{std::function<void()>work;std::function<void(std::exception_ptr)>complete;};std::deque<Job>jobs;mod::CalendarExecutor executor(){return {[this](auto work,auto complete){if(jobs.size()>=32)return false;jobs.push_back({std::move(work),std::move(complete)});return true;}};}void drain(){for(unsigned n=0;!jobs.empty();++n){check(n<128,"Injected Calendar FIFO settles without a timer or polling");auto j=std::move(jobs.front());jobs.pop_front();std::exception_ptr error;try{j.work();}catch(...){error=std::current_exception();}j.complete(error);}}};
void fields(const std::filesystem::path&shader){
 Window w;gpu::Renderer renderer;renderer.initialize(w.hwnd,1280,800,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});renderer.setCamera(gpu::layerViewportProjection(1280,800));gpu::LayerRasterizer raster;gpu::LayerRasterOptions options;options.pixelsPerPoint=1;const auto rules=gpu::nativeCalendarTextRules();gpu::LayerComposition composition;
 gpu::NativeCalendarEditorField title(w.hwnd,raster,options,mod::CalendarEditorField::title,"", "Title",{},WM_APP+240,1),date(w.hwnd,raster,options,mod::CalendarEditorField::date,"2026-10-04","Date",{},WM_APP+240,2),detail(w.hwnd,raster,options,mod::CalendarEditorField::details,"first\n第二行😀","Details",{},WM_APP+240,3);
 std::array<gpu::NativeCalendarEditorField*,3>all{&title,&date,&detail};std::array<gpu::LayerCompositionEntry,3>entries;
 const auto pose=[&](unsigned n,core::Matrix4 world){all[n]->updatePose({world,gpu::layerViewportProjection(1280,800),1280,800,1,true,n==0,{},{}});};
 for(unsigned n=0;n<3;++n){auto world=core::Matrix4::translation(100,100+n*100)*core::Matrix4::rotation(.13,.18,0);world.values[3]=.00004;pose(n,world);all[n]->upload(renderer);entries[n]=all[n]->entry();}
 composition.setEntries(renderer,entries);composition.present(renderer);renderer.draw(false);
 check(title.editor().layout().painted()->contentInset().x==3&&date.editor().layout().painted()->contentInset().x==3&&detail.editor().layout().painted()->contentInset().x==0,"Calendar title/date use source growing single-line fields while details wraps naturally");
 std::string repeated;for(unsigned n=0;n<121;++n)repeated+="e\xCC\x81";repeated+='\n';
 check(title.editor().replaceTextFromHost({0,0},mod::calendarEditorUTF16(repeated)).changed&&title.normalize(rules),"Calendar source Character limit normalizes through the same host TSF edit path");title.syncContent();check(rules.characters(mod::calendarEditorUTF8(title.document().text()))==120&&title.document().text().size()==240,"Title limit preserves complete combining clusters instead of truncating UTF16");
 title.editor().replaceTextFromHost({0,240},u"one\ntwo");check(title.normalize(rules)&&title.document().text()==u"one two","Only LF becomes a source single-line space");title.syncContent();title.editor().character('!');title.syncContent();title.editor().undo();title.syncContent();check(title.document().text()==u"one two","Calendar plain fields reuse the same document undo history");
 std::u16string longDetail;for(unsigned n=0;n<120;++n)longDetail+=u"中文😀 details\n";detail.editor().replaceTextFromHost({0,static_cast<std::uint32_t>(detail.document().text().size())},longDetail);detail.normalize(rules);detail.syncContent();check(detail.editor().maximumScrollOffset()>0&&detail.editor().scrollBy(35),"Details scrolls the full bounded document inside the original86pt viewport");detail.syncContent();
 for(auto*f:all)f->upload(renderer);composition.present(renderer);renderer.draw(false);
 title.editor().command(gpu::ProjectedEditorCommand::documentStart);title.syncContent();title.upload(renderer);composition.present(renderer);renderer.draw(false);const auto beforeCaret=renderer.readback();const auto caretRaster=raster.stats();const auto caretGroups=renderer.stats().nativeGroupRenders;
 title.editor().command(gpu::ProjectedEditorCommand::right);title.syncContent();title.upload(renderer);composition.present(renderer);renderer.draw(false);const auto afterCaret=renderer.readback();check(beforeCaret.pixels!=afterCaret.pixels&&renderer.stats().nativeGroupRenders==caretGroups+1&&raster.stats().rasterizations==caretRaster.rasterizations&&raster.stats().textLayoutsCreated==caretRaster.textLayoutsCreated,"Caret-only host selection moves within the same tilted field and repaints only its retained group");
 const auto rs=raster.stats();const auto gs=renderer.stats();allocations=0;counting=true;try{for(unsigned k=0;k<120;++k){for(unsigned n=0;n<3;++n){auto world=core::Matrix4::translation(100,100+n*100)*core::Matrix4::rotation(.000001*k,.000002*k,0);world.values[3]=k*.0000002;pose(n,world);all[n]->upload(renderer);}composition.present(renderer);renderer.draw(false);}}catch(...){counting=false;throw;}counting=false;
 check(allocations==0&&raster.stats().rasterizations==rs.rasterizations&&raster.stats().textLayoutsCreated==rs.textLayoutsCreated&&renderer.stats().textureUploads==gs.textureUploads&&renderer.stats().nativeGroupRenders==gs.nativeGroupRenders,"120 shared field tilt frames reuse text, placeholders, local group targets and resources without allocation");
 const auto capture=title.capturedLocalDraw(core::Matrix4::translation(14,49));check(capture.world==core::Matrix4::translation(14,49)&&capture.opacity==1&&capture.masks.empty(),"Closing capture borrows the completed field face in menu-local coordinates");
 composition.detach(renderer);for(auto*f:all){check(f->stopInput()&&f->releaseResources(renderer),"Field teardown preserves committed text and releases only detached resources");}check(renderer.stats().textures==0&&renderer.stats().meshes==0&&renderer.stats().nativeGroups==0,"All isolated field targets and borrowed glyph resources retire");renderer.reset();
}
void owner(const std::filesystem::path&shader){
 Window w;gpu::Renderer renderer;renderer.initialize(w.hwnd,1280,800,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});renderer.setCamera(gpu::layerViewportProjection(1280,800));gpu::LayerRasterizer raster;gpu::CalendarCivilContext civil(u"UTC","en_US","en_US");const auto text=gpu::nativeCalendarTextRules();Queue queue;auto repo=std::make_shared<Repository>();unsigned ids{},authorizationCalls{};double ownerTime{};const double dateTime=*mod::calendarUTC().timestamp({2026,10,4},10,0);
 mod::CalendarStateOptions stateOptions;stateOptions.text=text;stateOptions.now=[&]{return dateTime+ownerTime;};stateOptions.zone=[&]{return civil.timeZone();};stateOptions.newID=[&]{return std::string("C0000000-0000-4000-8000-")+(++ids==1?"000000000001":"000000000002");};stateOptions.scheduling.authorization=[&](bool,auto complete){++authorizationCalls;complete(mod::CalendarPermission::authorized);};stateOptions.scheduling.reconcile=[](auto,auto,auto complete){complete({});};stateOptions.scheduling.cancelObsolete=[](auto,auto complete){complete();};mod::CalendarState state(repo,queue.executor(),std::move(stateOptions));tools::CalendarPreviewOptions options;options.text=text;options.raster.pixelsPerPoint=1;
 tools::CalendarPreview preview(w.hwnd,state,civil,raster,options);check(repo->reads==0&&queue.jobs.empty(),"Constructing Calendar artwork owner performs no data IO or worker startup");preview.resize({1280,800,96,1,1280,800});core::source::DesktopChromeSettings settings;settings.viewport={0,0,1280,800};settings.module=core::Module::calendar;core::ModulePresentation modules(core::Module::calendar);gpu::LayerComposition composition;gpu::LayerScene helper(raster);helper.load(mod::CalendarJson::Object{{"bounds",mod::CalendarJson::Array{0,0,400,440}},{"children",mod::CalendarJson::Array{}}},{});gpu::NativeModuleSurface surface(helper,core::Module::calendar);core::Projection plane;
 struct Published{gpu::LayerScene*scene{};const gpu::DrawObject*after{};std::size_t count{};std::uint64_t content{},resource{};};std::array<Published,12>published;std::size_t publishedCount{};
 const auto frame=[&](double t,core::Matrix4 world=core::Matrix4{}){ownerTime=t;const auto sample=modules.sample(t).presentation;preview.update(world,settings,sample,1,t);preview.upload(renderer);const auto entries=preview.entries();bool changed=entries.size()!=publishedCount;for(std::size_t n=0;n<entries.size()&&!changed;++n)changed=entries[n].scene!=published[n].scene||entries[n].after.data()!=published[n].after||entries[n].after.size()!=published[n].count||entries[n].scene->contentRevision()!=published[n].content||entries[n].scene->resourceRevision()!=published[n].resource;if(changed){composition.setEntries(renderer,entries);publishedCount=entries.size();for(std::size_t n=0;n<entries.size();++n)published[n]={entries[n].scene,entries[n].after.data(),entries[n].after.size(),entries[n].scene->contentRevision(),entries[n].scene->resourceRevision()};}composition.present(renderer);renderer.draw(false);preview.collected(renderer);surface.update(world,settings,sample.current,1);plane=core::Projection::viewport(gpu::layerViewportProjection(1280,800)*surface.pose().contentWorld,1280,800);};
 frame(0);queue.drain();frame(.3);check(state.loaded()&&state.permission()==mod::CalendarPermission::unknown&&authorizationCalls==0&&repo->reads==1,"Empty source Calendar loads lazily through one injected FIFO without contacting notifications");
 const auto point=[&](double x,double y){const auto p=plane.project({x,y});check(bool(p),"Calendar input shares the exact drawn source module plane");return *p;};
 const auto click=[&](double x,double y){const auto p=point(x,y);ownerTime+=.01;check(preview.pointer({app::PointerKind::down,app::PointerButton::left,p.x,p.y},ownerTime),"Projected Calendar input consumes its original source action");preview.pointer({app::PointerKind::up,app::PointerButton::left,p.x,p.y},ownerTime);};
 const auto key=[&](unsigned v,tools::CalendarKeyModifiers mods=tools::CalendarKeyModifiers{}){check(preview.key({app::KeyKind::down,v},ownerTime,mods),"Calendar field receives isolated host key");};
 const auto character=[&](unsigned scalar){check(preview.key({app::KeyKind::unicodeCharacter,scalar},ownerTime,tools::CalendarKeyModifiers{}),"Calendar field receives synthetic UTF16 text through the shared editor");};
 const auto outside=point(470,100);check(!preview.pointer({app::PointerKind::down,app::PointerButton::left,outside.x,outside.y},ownerTime)&&!preview.pointer({app::PointerKind::up,app::PointerButton::left,outside.x,outside.y},ownerTime),"Outside Calendar down/up remains available to navigation without poisoning press state");
 click(373,289);frame(ownerTime+.2);check(preview.editing()&&preview.focusedField()==mod::CalendarEditorField::title&&preview.entries().size()>=5,"New event shows three actual projected fields above the original menu, focused title");
 character(0x4e2d);character(0x6587);character(0x1f600);frame(ownerTime+.01);check(!preview.message({w.hwnd,options.textMessage,999999,0},ownerTime),"Stale field generation cannot deliver changes into an open Calendar editor");
 click(100,190);key('A',{true,false,false,false});character('x');click(342,357);queue.drain();frame(ownerTime+.02);check(preview.editing()&&state.events().empty(),"Invalid source date keeps the real editor open without committing an event");
 click(100,190);key('A',{true,false,false,false});for(char c:std::string("2026-10-04"))character(static_cast<unsigned char>(c));click(100,255);character('d');character('\n');character(0x4e2d);frame(ownerTime+.01);
 const auto beforeSave=repo->writes;key(VK_RETURN,{true,false,false,false});check(state.events().empty()&&!queue.jobs.empty(),"Save queues a durable source transaction rather than mutating confirmed events in input");queue.drain();frame(ownerTime+.02);check(state.permission()==mod::CalendarPermission::authorized&&authorizationCalls>0&&state.events().size()==1&&state.events()[0].title=="中文😀"&&state.events()[0].details=="d\n中"&&repo->writes>beforeSave&&!preview.editing(),"Calendar save preserves plain Unicode title/details and dismisses only after injected persistence success");frame(ownerTime+.2);check(!preview.requiresFrames(ownerTime),"Finite captured menu and whole-face transitions stop without idle frames");
 click(60,320);frame(ownerTime+.2);check(preview.editing(),"Source event row reopens the original saved draft");const auto warmRaster=raster.stats();const auto warmGPU=renderer.stats();const auto jobs=queue.jobs.size();allocations=0;counting=true;try{for(unsigned n=0;n<120;++n)frame(ownerTime+1./60,core::Matrix4::rotation(.000001*n,.000002*n,0));}catch(...){counting=false;throw;}counting=false;
 check(allocations==0&&raster.stats().rasterizations==warmRaster.rasterizations&&raster.stats().textLayoutsCreated==warmRaster.textLayoutsCreated&&renderer.stats().textureUploads==warmGPU.textureUploads&&renderer.stats().nativeGroupRenders==warmGPU.nativeGroupRenders&&queue.jobs.size()==jobs,"120 real Calendar owner tilt frames allocate, shape, raster, upload and schedule no new content");
 frame(ownerTime+.01);click(56,355);check(state.events().size()==1,"Delete first shows source confirmation and preserves the event");frame(ownerTime+.01);click(97,355);check(state.events().size()==1,"Confirmed deletion remains durable-callback owned");queue.drain();frame(ownerTime+.2);check(state.events().empty()&&!preview.editing(),"Deletion confirmation removes only the selected event after persistence success");
 click(373,289);frame(ownerTime+.2);character('K');preview.setLanguage(core::Language::korean,ownerTime+.01);preview.setAppearance({false,{1,159./255,10./255,1}},ownerTime+.02);frame(ownerTime+.04);check(preview.editing()&&preview.focusedField()==mod::CalendarEditorField::title,"Language/theme updates preserve the active unsaved Calendar draft and focus owner");key(VK_ESCAPE);frame(ownerTime+.2);check(state.events().empty()&&!preview.editing(),"Escape disposes draft without inventing a save");
 click(373,289);frame(ownerTime+.2);const auto selection=modules.select(core::Module::reader,ownerTime+.01);settings.module=core::Module::reader;ownerTime+=.01;preview.update({},settings,selection.presentation,1,ownerTime);check(!preview.editing()&&!state.active(),"Selecting another module deactivates Calendar inputs and menu without stopping reminder ownership");composition.detach(renderer);publishedCount=0;preview.release(renderer);check(renderer.stats().textures==0&&renderer.stats().meshes==0&&renderer.stats().nativeGroups==0&&!IsWindowVisible(w.hwnd),"Shared publisher detaches Calendar resources fully; test never opens windows or reads real data");renderer.reset();
}
}
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==2,"Pass shared shader to hidden Calendar integration fixture");fields(argv[1]);owner(argv[1]);CoUninitialize();std::cout<<"PASS "<<checks<<" Calendar native owner/editor checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
