#include "native/calendar_notifications.hpp"
#include <algorithm>
#include <array>
#include <iostream>
#include <stdexcept>
#include <thread>
namespace {using namespace endfield;namespace n=native;namespace m=modules;unsigned checks{};
void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(s);}
template<class F>void rejects(F&&f,const char*s){bool bad{};try{f();}catch(const std::exception&){bad=true;}check(bad,s);}
constexpr const char*uuid="11111111-2222-4333-8444-555555555555";
m::CalendarReminder reminder(bool before=false){m::CalendarReminder r;r.eventID=uuid;r.identifier=std::string(m::calendarNotificationPrefix)+uuid+(before?".before":".day");r.title="中文😀 <&\" title";r.day={2026,10,8};r.date=*m::calendarUTC().timestamp(r.day,9,0);r.previousDay=before;return r;}
struct State {std::vector<n::CalendarScheduledNotification>pending;std::vector<std::string>removed;std::vector<n::CalendarScheduledNotification>added;unsigned permissionCalls{},factoryCalls{},pendingCalls{};bool failAdd{},failPermission{},failRemove{};m::CalendarPermission permission{m::CalendarPermission::authorized};std::thread::id callThread;};
struct Provider final:n::CalendarNotificationProvider {std::shared_ptr<State>s;explicit Provider(std::shared_ptr<State>v):s(std::move(v)){};m::CalendarPermission authorization(bool)override{s->callThread=std::this_thread::get_id();++s->permissionCalls;if(s->failPermission)throw std::runtime_error("injected permission failure");return s->permission;}
 std::vector<n::CalendarScheduledNotification>pending()override{++s->pendingCalls;s->callThread=std::this_thread::get_id();return s->pending;}
 void remove(std::string_view id)override{if(s->failRemove)throw std::runtime_error("injected removal failure");s->removed.push_back(std::string(id));std::erase_if(s->pending,[&](const auto&v){return v.identifier==id;});}
 void add(const n::CalendarScheduledNotification&v)override{if(s->failAdd)throw std::runtime_error("injected add failure");s->added.push_back(v);s->pending.push_back(v);}
};
void source(){auto s=std::make_shared<State>();Provider provider(s);n::CalendarNotificationOptions options;const auto r=reminder();const auto key=n::calendarNotificationKey(r.identifier);check(key&&key->group==std::string(m::calendarNotificationPrefix)+uuid&&key->tag=="day"&&key->group.size()<=64&&key->tag.size()<=16,"Native composite key preserves the whole source UUID within Windows bounds");check(!n::calendarNotificationKey("other."+r.identifier)&&!n::calendarNotificationKey(std::string(m::calendarNotificationPrefix)+uuid+".unknown"),"Other modules and unknown Calendar suffixes never enter owned notification scope");
 n::reconcileCalendarNotifications(provider,std::span(&r,1),options);check(s->added.size()==1&&s->added[0].title==r.title&&s->added[0].body=="Today · 2026-10-08"&&s->added[0].delivery==r.date,"Source reminder copies the exact date/Unicode title and localized today body");const auto accepted=s->added[0];n::reconcileCalendarNotifications(provider,std::span(&r,1),options);check(s->added.size()==1&&s->removed.empty(),"Matching source receipt signature schedules no duplicate");
 s->pending.push_back({"Activity.foreign","x",{},{},0});const auto before=reminder(true);n::reconcileCalendarNotifications(provider,std::span(&before,1),options);check(s->pending.size()==2&&s->pending[0].identifier=="Activity.foreign"&&s->added.back().body=="Tomorrow · 2026-10-08","Obsolete Calendar reminders are removed without touching sibling notifications");
 options.language=core::Language::korean;n::reconcileCalendarNotifications(provider,std::span(&before,1),options);check(s->added.back().body=="내일 · 2026-10-08"&&s->removed.size()==2,"Language event replaces the same composite key and localization signature exactly once");
 auto received=r;received.wasScheduled=true;s->pending.clear();s->added.clear();n::reconcileCalendarNotifications(provider,std::span(&received,1),options);check(s->added.empty(),"Missing previously-scheduled receipt means delivered/dismissed and is not replayed after clock changes");
 s->pending={accepted,{"Other.module",{}, {},{},0}};n::cancelObsoleteCalendarNotifications(provider,{});check(s->pending.size()==1&&s->pending[0].identifier=="Other.module","Permission-revocation cleanup removes only owned obsolete Calendar requests");
 auto catchUp=r;catchUp.catchUp=true;s->pending.clear();n::reconcileCalendarNotifications(provider,std::span(&catchUp,1),options);check(s->added.back().catchUp&&s->added.back().delivery==r.date,"Catch-up intent survives queueing so native delivery can preserve the source minimum-one-second trigger");auto invalidLanguage=options;invalidLanguage.language=static_cast<core::Language>(99);rejects([&]{n::reconcileCalendarNotifications(provider,std::span(&r,1),invalidLanguage);},"Unknown native language values cannot bypass resolved source localization");
 const auto calls=s->pendingCalls;auto bad=r;bad.eventID="broken";rejects([&]{n::reconcileCalendarNotifications(provider,std::span(&bad,1),options);},"Malformed event association declines before querying/mutating native schedule");check(s->pendingCalls==calls,"Complete plan validates before external provider callbacks");std::array duplicate{r,r};rejects([&]{n::reconcileCalendarNotifications(provider,duplicate,options);},"Duplicate plan key declines atomically");std::vector<m::CalendarReminder>tooMany(61,r);rejects([&]{n::reconcileCalendarNotifications(provider,tooMany,options);},"Source sixty-reminder bound is never weakened");
 const auto args=n::calendarNotificationArguments(uuid,r.signature());check(n::calendarNotificationEvent(args)==uuid,"Official launch metadata preserves source event identity through escaped Unicode JSON");check(!n::calendarNotificationEvent("{\"type\":\"other\",\"eventID\":\"11111111-2222-4333-8444-555555555555\",\"signature\":\"x\"}")&&!n::calendarNotificationEvent("bad"),"Untrusted foreign/corrupt activation cannot select a Calendar event");rejects([]{(void)n::calendarNotificationArguments("bad","x");},"Installer activation metadata never fabricates an event UUID");
}
void lifecycle(){auto s=std::make_shared<State>();unsigned callbacks{};app::UtilityExecutor executor([]{},1);const auto other=executor.makeRoute();const auto owner=std::this_thread::get_id();n::CalendarNotificationFactory factory=[s](const auto&){++s->factoryCalls;s->callThread=std::this_thread::get_id();return std::make_unique<Provider>(s);};n::NativeCalendarNotifications notifications(executor,{},factory);check(!executor.stats().started&&s->factoryCalls==0,"Constructing native adapter starts no service, thread or IO");auto scheduling=notifications.scheduling();
 check(executor.submit(other,[]{},[](auto){}),"Sibling fixture occupies one shared queue capacity");scheduling.authorization(true,[&](auto p){check(std::this_thread::get_id()==owner&&p==m::CalendarPermission::authorized,"Permission completes on borrowed UI owner");++callbacks;});check(notifications.status().pending==1&&!notifications.status().busy,"Rejected shared admission retains the exact pending permission operation");executor.waitIdle();executor.drain();notifications.queueCapacityAvailable();check(notifications.status().busy&&notifications.status().pending==0,"Existing queue completion admits retained operation without timer");executor.waitIdle();executor.drain();check(callbacks==1&&s->permissionCalls==1&&s->callThread!=owner,"Native provider runs only on one existing worker and callbacks only on owner");
 auto r=reminder();scheduling.reconcile({r},m::calendarUTC(),[&](auto error){check(!error&&std::this_thread::get_id()==owner,"Successful schedule callback remains owner-delivered");++callbacks;});executor.waitIdle();executor.drain();check(s->added.size()==1&&!notifications.status().busy,"Source reconciliation completes on same borrowed worker");s->failAdd=true;r.title="changed";scheduling.reconcile({r},m::calendarUTC(),[&](auto error){check(bool(error),"Partial native failure is reported instead of recording success receipt");++callbacks;});executor.waitIdle();executor.drain();check(notifications.status().error.has_value()&&callbacks==3,"Native error remains available after completion without auto retry");s->failAdd=false;notifications.setLanguage(core::Language::simplifiedChinese);scheduling.reconcile({r},m::calendarUTC(),[](auto error){if(error)std::rethrow_exception(error);});check(notifications.flush()&&s->added.back().body=="今天 · 2026-10-08","Explicit shutdown barrier flushes accepted scheduling and respects new language snapshot");
 unsigned recovered{};scheduling.authorization(false,[](auto){throw std::runtime_error("injected UI completion error");});scheduling.authorization(false,[&](auto){++recovered;});executor.waitIdle();rejects([&]{executor.drain();},"External completion exception is propagated without losing queued scheduling");executor.waitIdle();executor.drain();check(recovered==1&&!notifications.status().busy&&notifications.status().pending==0,"Existing FIFO continues after a client completion throws without a retry timer");
 auto dying=std::make_unique<n::NativeCalendarNotifications>(executor,n::CalendarNotificationOptions{},factory);auto route=dying->scheduling();route.authorization(false,[&](auto){++callbacks;dying.reset();});executor.waitIdle();executor.drain();check(!dying&&callbacks==4,"Owner may destroy adapter in its completion without stale resubmission");
 auto dropped=std::make_unique<n::NativeCalendarNotifications>(executor,n::CalendarNotificationOptions{},factory);auto deadRoute=dropped->scheduling();deadRoute.authorization(false,[&](auto){throw std::runtime_error("dead callback");});dropped.reset();executor.waitIdle();executor.drain();check(callbacks==4,"Accepted worker work finishes but destroyed owner receives no callbacks");executor.invalidate(other);executor.shutdown();
}
}
int main(){try{source();lifecycle();std::cout<<"PASS "<<checks<<" Calendar notification reconciliation/lifecycle checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
