#include "native/clipboard_scene.hpp"
#ifdef _WIN32
#include "native/clipboard_assets.hpp"
#endif
#include <atomic>
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <limits>
#include <new>
#include <stdexcept>
#ifdef _WIN32
#include <objbase.h>
#endif
namespace n=endfield::native;namespace c=endfield::core;using Json=ehud::data::Json;
namespace {std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};unsigned checks{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {
void check(bool v,const char*m){++checks;if(!v)throw std::runtime_error(m);}template<class F>void rejects(F f){bool failed{};try{f();}catch(const std::exception&){failed=true;}check(failed,"Invalid Clipboard input must reject");}
struct Fixture {
    n::ClipboardSnapshot snapshot;unsigned copies{},pins{},removed{},clears{};std::uint64_t copied{};bool failCopy{};
    Fixture(unsigned count=13){snapshot.capacity=32;for(unsigned k=0;k<count;++k)snapshot.rows.push_back({k+1,k==2,n::ClipboardKind::url,"https://example.invalid/"+std::to_string(k+1),{}});}
    n::ClipboardActions actions(){return {[this]{return snapshot;},[this](auto id){++copies;copied=id;return !failCopy;},[this](auto id){for(auto&r:snapshot.rows)if(r.id==id){r.pinned=!r.pinned;++pins;return true;}return false;},[this](auto id){const auto old=snapshot.rows.size();std::erase_if(snapshot.rows,[&](const auto&r){return r.id==id;});if(old==snapshot.rows.size())return false;++removed;return true;},[this]{const auto old=snapshot.rows.size();std::erase_if(snapshot.rows,[](const auto&r){return !r.pinned;});++clears;return old!=snapshot.rows.size();}};}
};
const Json*find(const Json&node,std::string_view id){if(node["id"].isString()&&node["id"].string()==id)return &node;if(node["children"].isArray())for(const auto&c:node["children"].array())if(auto*v=find(c,id))return v;return nullptr;}
void portable(){Fixture f;n::ClipboardState state(f.actions());check(state.rows().size()==13&&state.maximumOffset()==287,"Source bounded history geometry");check(state.visibleRange()==std::pair<std::size_t,std::size_t>{0,6},"Exactly six rows at settled top");check(state.rowRect(1)==c::Rect{12,43,376,37},"Original source row coordinates");state.activate();state.takeEvents();check(state.actionAt({12.2,43.2})&& !state.feedbackActionAt({12.2,43.2}),"Mouse action keeps source rectangle while cut-corner highlight excludes its corner");check(state.feedbackActionAt({345,55})=="clipboard:1:pin","Nested source feedback wins over full row");
    check(state.mouseDown({345,55})&&f.pins==1&&f.copies==0,"Nested pin wins over copy plate");check(state.rows()[0].pinned,"Provider mutation refreshes metadata only");state.mouseDown({370,55});check(f.removed==1&&f.copies==0,"Nested delete never copies");state.copyVisibleItem(0);check(f.copies==1&&f.copied==2&&state.selected()==2&&state.copiedFeedback(),"Visible shortcut uses current source row");state.copyVisibleItem(6);check(f.copies==1,"Only six source numeric shortcuts");
    f.failCopy=true;state.copySelection();check(!state.copiedFeedback()&&state.status()==state.strings().copyFailed,"Copy failure uses source feedback");f.failCopy=false;
    check(state.scroll({30,70},42.25)&&state.scrollOffset()==42.25,"Fractional wheel retained");const auto anchor=state.rows()[1].id;f.snapshot.rows.insert(f.snapshot.rows.begin(),{99,false,n::ClipboardKind::image,"图片 · 1 × 1",{}});state.refresh();check(state.scrollOffset()==83.25&&state.rows()[2].id==anchor,"Prepending capture retains scrolled item and fractional remainder");
    state.scrollBy(-10000);f.snapshot.rows.insert(f.snapshot.rows.begin(),{100,false,n::ClipboardKind::url,"new",{}});state.refresh();check(state.scrollOffset()==0,"At top captures appear immediately");state.selectNext(-1);check(state.selected().has_value(),"Up selects previous selected identity");for(unsigned n=0;n<20;++n)state.selectNext(1);check(state.selected()==13&&state.scrollOffset()==state.maximumOffset(),"Keyboard selection reveals final row");
    state.perform("clipboard:clear");check(state.confirmingClear()&&state.actions()[0].rect==c::Rect{218,299,67,27},"Original clear confirmation placement");state.scrollBy(-1);check(!state.confirmingClear(),"Changed scroll cancels clear confirmation");state.perform("clipboard:clear");state.perform("clipboard:confirmClear");check(f.clears==1&&state.rows().size()==1&&state.rows()[0].pinned,"Clear preserves pinned payload references");state.perform("clipboard:clear");check(!state.confirmingClear(),"All-pinned history has no clear action");
    const auto old=state.revision();const auto count=allocations.load();counting=true;for(unsigned k=0;k<100;++k){state.scrollBy(-1);state.visibleRange();state.maximumOffset();}counting=false;check(state.revision()==old&&allocations==count,"Clamped/idle metadata operations allocate nothing");
    const auto saved=state.rows();f.snapshot.rows.push_back(f.snapshot.rows[0]);rejects([&]{state.refresh();});check(state.rows()==saved,"Malformed incoming identity retains previous metadata");f.snapshot.rows.pop_back();
    Fixture art;n::ClipboardState view(art.actions());n::ClipboardAppearance appearance;const auto plan=n::prepareClipboardScene(view,appearance,{});check(plan.rows.size()==6,"Compiler virtualizes original visible range");check(plan.rows[0].surfaces.size()<=12,"Independent feedback and trace fit bounded retained surface budget");const auto*heading=find(plan.foreground.layers,"clipboard.heading");check(heading&&(*heading)["text"]["string"].string()=="// 剪贴板","Original section decoration retained");
    const auto*plate=find(plan.rows[0].layers,"clipboard.row.1/fill");check(plate&&(*plate)["shape"]["path"].array().size()==7&&(*plate)["shape"]["fillColor"]["sRGB"].array()[0].number()==.77,"Exact source cut corner and dark plate palette");const auto*preview=find(plan.rows[0].layers,"clipboard.row.1/preview");check(preview&&(*preview)["bounds"]==Json(Json::Array{0,0,243,17})&&(*preview)["position"]==Json(Json::Array{71,5}),"Original preview typography rectangle");
    view.scrollBy(.5);const auto scrolled=n::prepareClipboardScene(view,appearance,{});check(scrolled.rows.size()==7&&scrolled.rows[0].layers==plan.rows[0].layers&&scrolled.rows[0].full.y==42.5,"Fractional scroll retains exact local row artwork");
    art.snapshot.rows[0].kind=n::ClipboardKind::text;view.refresh();rejects([&]{n::prepareClipboardScene(view,appearance,{});});n::ClipboardImages images;images.text=n::ClipboardGameImage{Json::Object{{"memoryImage","synthetic-icon"},{"revision",1}},"Operational_Manual_icon",50};check(n::prepareClipboardScene(view,appearance,images).rows.size()==7,"Explicit prepared source image metadata accepted");images.text->tint[0]=.15;rejects([&]{n::prepareClipboardScene(view,appearance,images);});
    Fixture empty(0);n::ClipboardState emptyState(empty.actions());const auto emptyPlan=n::prepareClipboardScene(emptyState,appearance,{});check(find(emptyPlan.collection.layers,"clipboard.empty")&&emptyPlan.rows.empty(),"Source empty state belongs inside collection clip");
    for(unsigned n=0;n<512;++n){view.scrollBy(n%2?-.125:.125);const auto[first,end]=view.visibleRange();check(end-first<=7,"Viewport is always bounded to seven rows");}
    state.deactivate();check(!state.active()&&!state.confirmingClear(),"Leaving module settles interaction state");check(!state.scroll({50,10},1)&&!state.scroll({50,60},std::numeric_limits<double>::quiet_NaN()),"Only finite content-area wheel is consumed");
}
void dump(const char*path){Fixture f;n::ClipboardState state(f.actions());state.activate();n::ClipboardAppearance appearance;n::ClipboardImages images;
    images.text=n::ClipboardGameImage{Json::Object{{"asset","manual.png"},{"sha256",std::string(64,'a')}},"Operational_Manual_icon",50};images.files=n::ClipboardGameImage{Json::Object{{"asset","depot.png"},{"sha256",std::string(64,'a')}},"Depot_icon",50};Json::Array cases;
    const auto record=[&](const char*name){const auto plan=n::prepareClipboardScene(state,appearance,images);Json::Array parts,actions;const auto add=[&](const n::ClipboardPart&p){Json item=Json::Object{{"rowID",std::int64_t(p.rowID)},{"full",Json::Array{p.full.x,p.full.y,p.full.width,p.full.height}},{"layer",p.layers}};parts.push_back(std::move(item));};add(plan.collection);for(const auto&p:plan.rows)add(p);add(plan.scrollbar);add(plan.foreground);for(const auto&a:state.actions())actions.push_back(Json::Object{{"id",a.id},{"label",a.label},{"rect",Json::Array{a.rect.x,a.rect.y,a.rect.width,a.rect.height}}});cases.push_back(Json::Object{{"name",name},{"parts",std::move(parts)},{"actions",std::move(actions)},{"scroll",state.scrollOffset()}});};
    record("top");state.scrollBy(.5);record("fractional");state.perform("clipboard:2:copy");record("selected");state.perform("clipboard:1:pin");record("pinned");state.perform("clipboard:clear");record("confirm");appearance.dark=false;record("light");
    for(const auto kind:{n::ClipboardKind::text,n::ClipboardKind::files,n::ClipboardKind::image}){const char*name=kind==n::ClipboardKind::text?"text":kind==n::ClipboardKind::files?"files":"image";f.snapshot.rows={{1,false,kind,name,{}}};state.refresh();appearance.dark=true;record(name);}f.snapshot.rows.clear();state.refresh();record("empty");std::ofstream out(path);out<<Json(Json::Object{{"cases",std::move(cases)}}).encode();check(bool(out),"Write isolated comparison descriptors");
}
#ifdef _WIN32
struct Window {HWND hwnd{};Window(){WNDCLASSW wc{};wc.lpfnWndProc=DefWindowProcW;wc.hInstance=GetModuleHandleW(nullptr);wc.lpszClassName=L"OwnedClipboardSceneFixture";check(RegisterClassW(&wc)!=0,"Register isolated native fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,wc.lpszClassName,L"Owned fixture",WS_POPUP,0,0,400,334,nullptr,nullptr,wc.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Never show clipboard fixture");}~Window(){if(hwnd)DestroyWindow(hwnd);UnregisterClassW(L"OwnedClipboardSceneFixture",GetModuleHandleW(nullptr));}};
void native(const std::filesystem::path&shader,const std::filesystem::path&assetsRoot){n::NativeClipboardAssets assets(assetsRoot);Window window;n::Renderer renderer;renderer.initialize(window.hwnd,400,334,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests});renderer.setCamera(n::layerViewportProjection(400,334));n::LayerRasterizer raster;n::LayerComposition composition;Fixture fixture;n::ClipboardState state(fixture.actions());state.activate();n::NativeClipboardScene scene(state,raster,{}, {},{},assets.revealSamples());n::NativeClipboardPose pose;
    const auto frame=[&](double time){pose.time=time;scene.syncContent(time);scene.updatePose(pose);scene.uploadAnimations(renderer);composition.setEntries(renderer,scene.entries());composition.present(renderer);scene.collectRetired(renderer);};
    frame(0);renderer.draw(false);const auto baseline=renderer.readback();check(scene.stats().rows==6&&!baseline.pixels.empty(),"Real source rows render in isolated target");const auto r=raster.stats();const auto g=renderer.stats();allocations=0;counting=true;for(unsigned k=0;k<120;++k){pose.time=.001*k;pose.world=c::Matrix4::translation(double(k%3),0)*c::Matrix4::rotation(.0001*k,0,0);scene.updatePose(pose);composition.present(renderer);}counting=false;check(allocations==0&&raster.stats().rasterizations==r.rasterizations&&renderer.stats().textureUploads==g.textureUploads,"Warm module tilt allocates/rasterizes/uploads nothing");
    pose.world={};state.scrollBy(.5);frame(1);check(scene.stats().rows==7&&raster.stats().textLayoutsCreated-r.textLayoutsCreated<=4,"Wheel introduces only one row layout");const auto rowsRaster=raster.stats();state.scrollBy(.25);frame(1.1);check(raster.stats().textLayoutsCreated==rowsRaster.textLayoutsCreated,"Within visible range scroll never reshapes row text");
    scene.setFeedback("clipboard:1:pin",true,1.2);frame(1.27);const auto hoverRaster=raster.stats();frame(1.4);check(raster.stats().rasterizations==hoverRaster.rasterizations,"Control feedback remains numeric");
    state.perform("clipboard:2:copy");frame(2);check(scene.requiresFrames(2.01),"Original row engage has finite source demand");frame(2.09);renderer.draw(false);const auto middle=renderer.readback();frame(2.2);renderer.draw(false);check(middle.pixels!=renderer.readback().pixels&&scene.stats().outlineRasters>=2,"Row transform and border registration trace actually render");check(!scene.requiresFrames(2.3),"Settled rows stop requesting animation frames");
    state.perform("clipboard:2:remove");frame(3);check(scene.requiresFrames(3.01),"Delete retains original .20s row reflow");frame(3.3);check(fixture.removed==1,"Injected delete callback exactly once");
    state.perform("clipboard:clear");state.perform("clipboard:confirmClear");frame(4);frame(4.3);state.perform("clipboard:3:remove");frame(5);renderer.draw(false);const auto revealStart=renderer.readback();check(scene.requiresFrames(5.1)&&scene.stats().maskUploads==1,"No-row-reflow uses actual bounded Clipboard CA reveal");const auto activeTextures=renderer.stats().textures;const auto maskRasters=scene.stats().maskRasters;scene.uploadAnimations(renderer);check(scene.stats().maskRasters==maskRasters,"Equal source mask sample is a no-op");frame(5.13);renderer.draw(false);frame(5.3);renderer.draw(false);check(renderer.readback().pixels!=revealStart.pixels&&renderer.stats().textures+1==activeTextures,"Actual empty collection reveal finishes and retires one texture");check(!scene.requiresFrames(5.4),"Completed inner reveal has no idle demand");
    composition.detach(renderer);check(scene.releaseResources(renderer)&&renderer.stats().meshes==0&&renderer.stats().textures==0,"Detached module frees its resources without a second publisher");renderer.reset();
}
#endif
}
#ifdef _WIN32
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==3,"Pass HLSL and Clipboard asset root to hidden fixture");portable();native(argv[1],argv[2]);CoUninitialize();std::cout<<"PASS "<<checks<<" Clipboard scene checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(int argc,char**argv){try{portable();if(argc==2)dump(argv[1]);std::cout<<"PASS "<<checks<<" Clipboard source/state checks\n";return 0;}catch(const std::exception&e){counting=false;std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
