#ifdef _WIN32
#include "tools/clipboard_preview.hpp"
#include "native/module_scene.hpp"
#include "native/clipboard_assets.hpp"
#include <objbase.h>
#include <iostream>
namespace gpu=endfield::native;namespace c=endfield::core;namespace a=endfield::app;namespace t=endfield::tools;using Json=ehud::data::Json;
namespace {unsigned checks{};void check(bool v,const char*m){++checks;if(!v)throw std::runtime_error(m);}
struct Window{HWND h{};Window(){WNDCLASSW w{};w.lpfnWndProc=DefWindowProcW;w.hInstance=GetModuleHandleW(nullptr);w.lpszClassName=L"OwnedClipboardOwnerFixture";check(RegisterClassW(&w)!=0,"Register synthetic fixture HWND");h=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,w.lpszClassName,L"Owned fixture",WS_POPUP,0,0,1280,800,nullptr,nullptr,w.hInstance,nullptr);check(h&&!IsWindowVisible(h),"Hidden fixture never focuses a window");}~Window(){if(h)DestroyWindow(h);UnregisterClassW(L"OwnedClipboardOwnerFixture",GetModuleHandleW(nullptr));}};
Json blank(){return Json::Object{{"bounds",Json::Array{0,0,400,334}},{"position",Json::Array{0,0}},{"anchorPoint",Json::Array{0,0}},{"children",Json::Array{}}};}
void run(gpu::Renderer&r,const gpu::NativeClipboardAssets&assets){gpu::LayerRasterizer raster;gpu::LayerComposition composition;gpu::ClipboardSnapshot snapshot;snapshot.capacity=32;for(unsigned n=1;n<=13;++n)snapshot.rows.push_back({n,n==3,gpu::ClipboardKind::url,"https://fixture.invalid/"+std::to_string(n),{}});unsigned copies{},pins{},removes{},clears{};std::uint64_t copied{};
    gpu::ClipboardActions actions{[&]{return snapshot;},[&](auto id){++copies;copied=id;return true;},[&](auto id){for(auto&v:snapshot.rows)if(v.id==id){v.pinned=!v.pinned;++pins;return true;}return false;},[&](auto id){const auto size=snapshot.rows.size();std::erase_if(snapshot.rows,[&](const auto&v){return v.id==id;});if(size==snapshot.rows.size())return false;++removes;return true;},[&]{++clears;std::erase_if(snapshot.rows,[](const auto&v){return !v.pinned;});return true;}};
    t::ClipboardPreview owner(raster,{},std::move(actions),{}, {},{},assets.revealSamples());owner.resize({1280,800,96,1,1280,800});c::ModulePresentation modules{c::Module::clipboard};gpu::LayerScene empty(raster);empty.load(blank(),{});gpu::NativeModuleSurface plane(empty,c::Module::clipboard);c::source::DesktopChromeSettings settings{{0,0,1280,800},1,{},c::Module::clipboard,true};auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;const auto camera=gpu::layerViewportProjection(1280,800);double now{};bool done{};
    struct Cleanup{gpu::Renderer&r;gpu::LayerComposition&c;t::ClipboardPreview&o;bool&done;~Cleanup(){if(done)return;try{c.detach(r);o.release(r);}catch(...){r.reset();}}}cleanup{r,composition,owner,done};
    const auto frame=[&](double dt=.01){now+=dt;auto sample=modules.sample(now).presentation;settings.module=sample.requested;owner.update(center,settings,sample,1,now);owner.upload(r);composition.setEntries(r,owner.entries());composition.present(r);owner.collected(r);r.setCamera(camera);};
    const auto point=[&](c::Point p){auto sample=modules.sample(now).presentation;const auto*surface=sample.current.module==c::Module::clipboard?&sample.current:&*sample.incoming;plane.update(center,settings,*surface);return *c::Projection::viewport(camera*plane.pose().contentWorld,1280,800).project(p);};
    const auto click=[&](c::Point p,bool verifyPress=false){const auto q=point(p);const auto action=owner.state().feedbackActionAt(p);const auto tint=action?std::string(*action)+"/tint":std::string{};check(owner.pointer({a::PointerKind::down,a::PointerButton::left,q.x,q.y,0},now),"Projected source row press routed");check(owner.pointerLocked(),"Clipboard press locks shell tilt");frame(.07);if(verifyPress){bool found{};for(const auto&entry:owner.entries())if(auto index=entry.scene->surfaceIndex(tint)){entry.scene->prepareDraws();found=true;check(entry.scene->draws()[*index].opacity==1,"Stationary press reaches original pressed tint without a pointer move");}check(found,"Pressed action keeps its exact source highlight surface");}check(owner.pointer({a::PointerKind::up,a::PointerButton::left,q.x,q.y,0},now),"Owned release routed");frame(.3);check(!owner.pointerLocked(),"Release frees shell tilt lock");};
    frame();check(owner.state().rows().size()==13&&!owner.entries().empty()&&copies==0,"Shared owner renders injected metadata without reading/copying clipboard");click({80,55},true);check(copies==1&&copied==1,"Click copies exact injected item once");click({345,55});check(pins==1&&copies==1,"Nested pin does not invoke clipboard copy");click({371,55});check(removes==1&&copies==1,"Nested delete only mutates injected cache");
    check(owner.key({a::KeyKind::down,'6'},now),"Sixth visible shortcut routed");frame(.3);check(copied==7,"Shortcut follows remaining current visible items");const auto q=point({80,100});check(owner.wheel({q.x,q.y,-.5,false,0,3},now),"Fractional content wheel consumed");frame();check(owner.state().scrollOffset()==18,"Wheel preserves source line step and fractional value");
    snapshot.rows.insert(snapshot.rows.begin(),{99,false,gpu::ClipboardKind::url,"new",{}});owner.refresh();frame();check(owner.state().scrollOffset()==59,"Coalesced external refresh anchors scrolled history");
    center=center*c::Matrix4::rotation(.08,-.12,0);frame();const auto tilted=point({80,100});check(owner.covers(tilted),"Current tilted projection owns hit plane");check(owner.pointer({a::PointerKind::down,a::PointerButton::left,tilted.x,tilted.y,0},now),"Tilted item click remains mapped");owner.cancelInteraction();frame(.3);
    click({30,310});check(owner.state().confirmingClear(),"Source toolbar opens confirmation");click({330,310});check(clears==1&&owner.state().rows().size()==1&&owner.state().rows()[0].pinned,"Confirmation preserves pinned cache");
    modules.select(c::Module::power,now);frame(.4);frame(.4);check(!owner.covers({640,400})&&owner.entries().empty()&&!owner.requiresFrames(now),"Inactive Clipboard releases hit/frame demand");composition.detach(r);owner.release(r);done=true;check(r.stats().textures==0&&r.stats().meshes==0,"Borrowed renderer resources retire after owner detach");
}
}
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==3,"Pass HLSL and Clipboard assets to hidden owner test");Window window;gpu::Renderer renderer;renderer.initialize(window.h,1280,800,{gpu::Driver::warpForTests,argv[1],gpu::RenderTarget::offscreenForTests});gpu::NativeClipboardAssets assets(std::filesystem::absolute(argv[2]));run(renderer,assets);renderer.reset();CoUninitialize();std::cout<<"PASS "<<checks<<" Clipboard owner checks\n";return 0;}catch(const std::exception&e){if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
