#include "native/clipboard_image.hpp"
#include "native/system_services.hpp"
#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <iostream>
#include <mutex>
#include <stdexcept>
#include <thread>
namespace n=endfield::native;namespace a=endfield::app;
namespace {
unsigned checks{};void check(bool b,const char*m){++checks;if(!b)throw std::runtime_error(m);}
using Bytes=std::vector<std::uint8_t>;
void put16(Bytes&b,std::size_t p,std::uint16_t v){b[p]=static_cast<std::uint8_t>(v);b[p+1]=static_cast<std::uint8_t>(v>>8);}
void put32(Bytes&b,std::size_t p,std::uint32_t v){for(unsigned k=0;k<4;++k)b[p+k]=static_cast<std::uint8_t>(v>>(8*k));}
void big(Bytes&b,std::uint32_t v){for(int k=3;k>=0;--k)b.push_back(static_cast<std::uint8_t>(v>>(8*k)));}
std::uint32_t crc(std::span<const std::uint8_t>b){std::uint32_t value=0xffffffffu;for(const auto v:b){value^=v;for(unsigned k=0;k<8;++k)value=(value&1)?0xedb88320u^(value>>1):value>>1;}return value^0xffffffffu;}
void chunk(Bytes&b,const char*type,const Bytes&data){big(b,static_cast<std::uint32_t>(data.size()));const auto start=b.size();for(unsigned k=0;k<4;++k)b.push_back(static_cast<std::uint8_t>(type[k]));b.insert(b.end(),data.begin(),data.end());big(b,crc(std::span(b).subspan(start)));}
// Tiny owned codec fixtures only. Never inspect the operating-system clipboard.
Bytes png(unsigned w=2,unsigned h=1,bool invalidStream=false,bool badAdler=false){Bytes b{137,80,78,71,13,10,26,10},header;big(header,w);big(header,h);header.insert(header.end(),{8,6,0,0,0});chunk(b,"IHDR",header);Bytes raw;for(unsigned y=0;y<h;++y){raw.push_back(0);for(unsigned x=0;x<w;++x){raw.insert(raw.end(),{240,20,10,static_cast<std::uint8_t>(x%2?128:255)});}}check(raw.size()<65536,"Owned PNG fixture fits one small stored DEFLATE block");const auto size=static_cast<std::uint16_t>(raw.size());Bytes z{0x78,0x01,0x01,static_cast<std::uint8_t>(size),static_cast<std::uint8_t>(size>>8),static_cast<std::uint8_t>(~size),static_cast<std::uint8_t>((~size)>>8)};z.insert(z.end(),raw.begin(),raw.end());std::uint32_t s1=1,s2{};for(auto c:raw){s1=(s1+c)%65521;s2=(s2+s1)%65521;}big(z,(s2<<16)|s1);if(invalidStream)z[2]=0xff;if(badAdler)z.back()^=1;chunk(b,"IDAT",z);chunk(b,"IEND",{});return b;}
Bytes dib(bool v5=false,bool topDown=false){const unsigned header=v5?124u:40u;Bytes b(header+8);put32(b,0,header);put32(b,4,2);put32(b,8,topDown?0xffffffffu:1u);put16(b,12,1);put16(b,14,v5?32:24);put32(b,20,8);if(v5){put32(b,16,3);put32(b,40,0x00ff0000);put32(b,44,0x0000ff00);put32(b,48,0x000000ff);put32(b,52,0xff000000);put32(b,56,0x73524742);}b[header]=10;b[header+1]=20;b[header+2]=240;b[header+3]=v5?128:10;b[header+4]=v5?10:20;b[header+5]=v5?20:240;b[header+6]=v5?240:0;b[header+7]=v5?255:0;return b;}
Bytes tiff(unsigned orientation=1){constexpr unsigned entries=11;constexpr unsigned extras=8+2+entries*12+4;Bytes b(extras+6+6);b[0]='I';b[1]='I';put16(b,2,42);put32(b,4,8);put16(b,8,entries);unsigned index{};auto tag=[&](unsigned key,unsigned type,unsigned count,unsigned value){const auto p=10+index++*12;put16(b,p,static_cast<std::uint16_t>(key));put16(b,p+2,static_cast<std::uint16_t>(type));put32(b,p+4,count);put32(b,p+8,value);};tag(256,4,1,2);tag(257,4,1,1);tag(258,3,3,extras);tag(259,3,1,1);tag(262,3,1,2);tag(273,4,1,extras+6);tag(274,3,1,orientation);tag(277,3,1,3);tag(278,4,1,1);tag(279,4,1,6);tag(284,3,1,1);put16(b,extras,8);put16(b,extras+2,8);put16(b,extras+4,8);b[extras+6]=240;b[extras+7]=20;b[extras+8]=10;b[extras+9]=10;b[extras+10]=20;b[extras+11]=240;return b;}
#ifdef _WIN32
Bytes bigTIFF(){auto b=tiff(8);auto u16=[&](unsigned p){return unsigned(b[p])|(unsigned(b[p+1])<<8);};auto u32=[&](unsigned p){return std::uint32_t(b[p])|(std::uint32_t(b[p+1])<<8)|(std::uint32_t(b[p+2])<<16)|(std::uint32_t(b[p+3])<<24);};auto b16=[&](unsigned p,unsigned v){b[p]=static_cast<std::uint8_t>(v>>8);b[p+1]=static_cast<std::uint8_t>(v);};auto b32=[&](unsigned p,std::uint32_t v){for(unsigned k=0;k<4;++k)b[p+k]=static_cast<std::uint8_t>(v>>(8*(3-k)));};b[0]='M';b[1]='M';b16(2,42);b32(4,8);const auto count=u16(8);b16(8,count);for(unsigned k=0;k<count;++k){const auto p=10+k*12;const auto key=u16(p),type=u16(p+2);const auto size=u32(p+4),value=u32(p+8);b16(p,key);b16(p+2,type);b32(p+4,size);if(type==3&&size==1){b16(p+8,value);b16(p+10,0);}else b32(p+8,value);}const auto extras=8+2+count*12+4;for(unsigned k=0;k<3;++k)b16(extras+k*2,8);return b;}
#endif
n::ClipboardEncodedImage image(Bytes b,n::ClipboardEncodedFormat f=n::ClipboardEncodedFormat::png){return {f,std::make_shared<const Bytes>(std::move(b))};}
n::ClipboardImageResult fake(const n::ClipboardEncodedImage&i){auto t=std::make_shared<n::ClipboardImageThumbnail>();t->encoded=i;t->sourceWidth=2;t->sourceHeight=1;t->width=2;t->height=1;t->rgba={240,20,10,255,240,20,10,128};return {std::move(t),n::ClipboardImageError::none,0};}
struct Block {std::mutex mutex;std::condition_variable cv;bool entered{},released{};void wait(){std::unique_lock lock(mutex);entered=true;cv.notify_all();cv.wait(lock,[&]{return released;});}void await(){std::unique_lock lock(mutex);if(!cv.wait_for(lock,std::chrono::seconds(5),[&]{return entered;}))throw std::runtime_error("Owned decoder failed to enter");}void release(){std::lock_guard lock(mutex);released=true;cv.notify_all();}};
struct Release {std::shared_ptr<Block>block;~Release(){block->release();}};
void queueTests(){
    check(!n::validClipboardEncodedImage({}),"Empty encoded input rejected");const auto input=image(png());check(n::validClipboardEncodedImage(input),"Source valid PNG header accepted for worker validation");check(n::validClipboardEncodedImage(image(tiff(),n::ClipboardEncodedFormat::tiff)),"TIFF header supported alongside source PNG");check(n::validClipboardEncodedImage(image(dib(),n::ClipboardEncodedFormat::dib)),"Windows packed DIB header supported");check(n::validClipboardEncodedImage(image(dib(true,true),n::ClipboardEncodedFormat::dibV5)),"Windows top-down V5 supports explicit alpha");auto bad=*input.bytes;bad.resize(12);check(!n::validClipboardEncodedImage(image(std::move(bad))),"Truncated payload rejected before queue");auto largeHeader=*input.bytes;largeHeader[16]=0;largeHeader[17]=1;largeHeader[18]=0x86;largeHeader[19]=0xa1;check(!n::validClipboardEncodedImage(image(std::move(largeHeader))),"Source dimension above100000 rejected without decode");
    std::atomic<unsigned>wakes{},decodes{};const auto owner=std::this_thread::get_id();a::UtilityExecutor executor([&]{++wakes;},1);bool callbackOnOwner{},offOwner{};std::vector<std::uint64_t>sequences;std::shared_ptr<const n::ClipboardImageThumbnail>accepted;
    auto block=std::make_shared<Block>();Release release{block};n::NativeClipboardImageProbe probe(executor,[&](auto seq,auto result){callbackOnOwner=std::this_thread::get_id()==owner;sequences.push_back(seq);accepted=std::move(result.thumbnail);},[&](const auto&i){offOwner=std::this_thread::get_id()!=owner;if(++decodes==1)block->wait();return fake(i);});
    check(!probe.submitPending()&&!executor.stats().started,"Idle image helper starts no thread/codec");check(probe.request(1,input),"First immutable image submitted");block->await();for(unsigned k=2;k<=20;++k)check(probe.request(k,input),"Latest generation replaces a single pending record");check(probe.stats().inFlight&&probe.stats().waiting&&probe.stats().submitted==1,"Rapid clipboard changes cannot create unbounded work");block->release();executor.waitIdle();check(sequences.empty(),"Worker cannot invoke owner completion");executor.drain();check(sequences.empty()&&probe.stats().discarded==1,"Superseded in-flight thumbnail cannot be accepted");executor.waitIdle();executor.drain();check(sequences==std::vector<std::uint64_t>{20}&&decodes==2&&callbackOnOwner&&offOwner,"Only latest image accepted on owner thread");check(accepted&&accepted->encoded.bytes==input.bytes&&*accepted->encoded.bytes==*input.bytes,"Copyback keeps exactly the original immutable encoded bytes");const auto before=wakes.load();for(unsigned k=0;k<1000;++k)check(!probe.submitPending(),"Settled helper has no pending work");check(wakes==before&&decodes==2,"No idle polling, decode or notifications");
    check(probe.request(21,input),"New capture after completion");probe.cancel();executor.waitIdle();executor.drain();check(sequences.size()==1,"Cancel suppresses already completed or running result");check(probe.request(22,input),"Cancel remains reusable without another worker");executor.waitIdle();executor.drain();check(sequences.back()==22,"Reuse accepts next generation");
    auto hold=std::make_shared<Block>();Release releaseHold{hold};const auto route=executor.makeRoute();check(executor.submit(route,[hold]{hold->wait();},[](auto){}),"Unrelated shared work fills queue");hold->await();check(probe.request(23,input)&&probe.stats().waiting&&probe.stats().backpressure==1,"Shared queue backpressure keeps one immutable pending payload");hold->release();executor.waitIdle();executor.drain();check(probe.submitPending(),"Owner completion event retries without timer");executor.waitIdle();executor.drain();check(sequences.back()==23,"Backpressure result accepted once");executor.invalidate(route);
    auto blocked=std::make_shared<Block>();Release releaseBlocked{blocked};unsigned late{};auto disposable=std::make_unique<n::NativeClipboardImageProbe>(executor,[&](auto,auto){++late;},[blocked](const auto&i){blocked->wait();return fake(i);});disposable->request(1,input);blocked->await();disposable.reset();check(late==0,"Destroy does not block on running codec");blocked->release();executor.waitIdle();executor.drain();check(late==0,"Destroyed facade never receives late completion");
    std::unique_ptr<n::NativeClipboardImageProbe>selfDestroy;selfDestroy=std::make_unique<n::NativeClipboardImageProbe>(executor,[&](auto,auto){selfDestroy.reset();},fake);selfDestroy->request(1,input);executor.waitIdle();executor.drain();check(!selfDestroy,"Owner callback may safely destroy its own probe");
    n::ClipboardImageResult failed; n::NativeClipboardImageProbe invalid(executor,[&](auto,auto r){failed=std::move(r);},[](const auto&){return n::ClipboardImageResult{};});invalid.request(1,input);executor.waitIdle();executor.drain();check(!failed.thumbnail&&failed.error==n::ClipboardImageError::decode&&invalid.stats().failed==1,"Decoder failure/invalid injected result never enters history");
}
#ifdef _WIN32
void nativeTests(){
    const auto input=image(png());const auto result=n::decodeClipboardImage(input);check(result.thumbnail&&result.error==n::ClipboardImageError::none,"Microsoft WIC actually decodes owned PNG");const auto&t=*result.thumbnail;check(t.width==2&&t.height==1&&t.rgba[0]==240&&t.rgba[3]==255&&t.rgba[7]==128,"PNG color and straight alpha survive bounded decode");check(t.encoded.bytes==input.bytes,"WIC holds unchanged encoded copyback reference");
    const auto scaled=n::decodeClipboardImage(image(png(200,50)));check(scaled.thumbnail&&scaled.thumbnail->sourceWidth==200&&scaled.thumbnail->sourceHeight==50&&scaled.thumbnail->width==96&&scaled.thumbnail->height==24&&scaled.thumbnail->rgba.size()==96*24*4,"Original dimensions preserved while only96px pixels allocated");
    auto corrupt=*input.bytes;corrupt[corrupt.size()-1]^=1;check(!n::decodeClipboardImage(image(std::move(corrupt))).thumbnail,"PNG CRC corruption rejected, not just structurally accepted");// Original ClipboardStore ImageIO options recover these two malformed
    // streams as transparent2x1, rather than reject them. Codec acceptance is
    // distinct from complete DEFLATE integrity validation; do not decode twice.
    for(unsigned variant=0;variant<2;++variant){const auto encoded=image(png(2,1,variant==0,variant==1));const auto recovered=n::decodeClipboardImage(encoded);
        if(recovered.thumbnail){std::cout<<"PNG recovery "<<variant<<" RGBA=";for(auto value:recovered.thumbnail->rgba)std::cout<<unsigned(value)<<',';std::cout<<'\n';}
        check(recovered.thumbnail&&recovered.error==n::ClipboardImageError::none&&recovered.thumbnail->width==2&&recovered.thumbnail->height==1&&recovered.thumbnail->rgba==Bytes(8,0),"Malformed PNG recovery matches original ImageIO transparent2x1 pixels");
        check(recovered.thumbnail->encoded.bytes==encoded.bytes&&*recovered.thumbnail->encoded.bytes==*encoded.bytes,"Recovered PNG keeps identical original encoded copyback payload");
    }
    auto incomplete=*input.bytes;incomplete.resize(40);check(!n::decodeClipboardImage(image(std::move(incomplete))).thumbnail,"Truncated PNG cannot become a decoded history image");
    for(unsigned orient=1;orient<=8;++orient){const auto r=n::decodeClipboardImage(image(tiff(orient),n::ClipboardEncodedFormat::tiff));check(r.thumbnail&&r.thumbnail->sourceWidth==2&&r.thumbnail->sourceHeight==1,"Original TIFF first frame decoded");check(r.thumbnail->width==(orient>=5?1u:2u)&&r.thumbnail->height==(orient>=5?2u:1u),"TIFF source orientation applied to thumbnail geometry");const bool blueFirst=orient==2||orient==3||orient==7||orient==8;check(r.thumbnail->rgba[blueFirst?2:0]>200,"TIFF orientation preserves corner ordering");}
    const auto bigEndian=n::decodeClipboardImage(image(bigTIFF(),n::ClipboardEncodedFormat::tiff));check(bigEndian.thumbnail&&bigEndian.thumbnail->width==1&&bigEndian.thumbnail->height==2&&bigEndian.thumbnail->rgba[2]>200,"Big-endian TIFF preserves first-frame orientation and color");
    auto exifPNG=png();Bytes exifChunk;chunk(exifChunk,"eXIf",tiff(6));exifPNG.insert(exifPNG.begin()+33,exifChunk.begin(),exifChunk.end());const auto pngOriented=n::decodeClipboardImage(image(std::move(exifPNG)));check(pngOriented.thumbnail&&pngOriented.thumbnail->width==1&&pngOriented.thumbnail->height==2,"PNG eXIf orientation uses the source thumbnail transform too");
    auto truncated=tiff();truncated.resize(truncated.size()-4);const auto truncatedInput=image(std::move(truncated),n::ClipboardEncodedFormat::tiff);const auto recoveredTIFF=n::decodeClipboardImage(truncatedInput);
    if(recoveredTIFF.thumbnail){std::cout<<"TIFF recovery RGBA=";for(auto value:recoveredTIFF.thumbnail->rgba)std::cout<<unsigned(value)<<',';std::cout<<'\n';}
    check(recoveredTIFF.thumbnail&&recoveredTIFF.thumbnail->width==2&&recoveredTIFF.thumbnail->height==1&&recoveredTIFF.thumbnail->rgba==Bytes{0,0,0,255,0,0,0,255},"Truncated TIFF recovery matches original ImageIO opaque-black2x1 pixels");
    check(recoveredTIFF.thumbnail->encoded.bytes==truncatedInput.bytes&&*recoveredTIFF.thumbnail->encoded.bytes==*truncatedInput.bytes,"Recovered TIFF retains original encoded copyback bytes");
    Bytes palette(52);put32(palette,0,40);put32(palette,4,2);put32(palette,8,1);put16(palette,12,1);put16(palette,14,1);put32(palette,20,4);put32(palette,32,2);palette[46]=255;palette[48]=0x80;const auto indexed=n::decodeClipboardImage(image(std::move(palette),n::ClipboardEncodedFormat::dib));check(indexed.thumbnail&&indexed.thumbnail->rgba[0]==255&&indexed.thumbnail->rgba[4]==0,"Packed DIB palette and DWORD-aligned pixel offset are retained");
    const auto oldDIB=n::decodeClipboardImage(image(dib(),n::ClipboardEncodedFormat::dib));check(oldDIB.thumbnail&&oldDIB.thumbnail->rgba[0]==240&&oldDIB.thumbnail->rgba[3]==255,"Legacy24bit packed DIB converts without a temporary bitmap file");const auto v5=n::decodeClipboardImage(image(dib(true,true),n::ClipboardEncodedFormat::dibV5));check(v5.thumbnail&&v5.thumbnail->rgba[0]==240&&v5.thumbnail->rgba[3]==128,"V5 top-down explicit alpha preserved");auto linked=dib(true);put32(linked,56,0x4c494e4b);check(n::decodeClipboardImage(image(std::move(linked),n::ClipboardEncodedFormat::dibV5)).error==n::ClipboardImageError::unsupportedProfile,"Linked profile cannot open an external file");
    auto huge=tiff();put32(huge,18,100000);put32(huge,30,100000);const auto rejected=n::decodeClipboardImage(image(std::move(huge),n::ClipboardEncodedFormat::tiff));check(!rejected.thumbnail,"Dimensions rejected before any source-sized destination allocation");
}
#endif
}
int main(){try{queueTests();
#ifdef _WIN32
nativeTests();
#endif
std::cout<<"PASS "<<checks<<" clipboard image worker/thumbnail checks\n";}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
