#ifdef _WIN32
#include "native/event_log_scene.hpp"
#include "tools/event_log_preview.hpp"
#include "native/module_scene.hpp"
#include <objbase.h>
#include <atomic>
#include <cstdlib>
#include <cstdio>
#include <iostream>
#include <new>
#include <limits>
namespace n=endfield::native;namespace m=endfield::modules;namespace c=endfield::core;namespace a=endfield::app;namespace t=endfield::tools;using Json=ehud::data::Json;
namespace {unsigned checks{};std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t count){if(counting)++allocations;if(auto*p=std::malloc(count?count:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t count){return ::operator new(count);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {
void check(bool value,const char*message){++checks;if(!value)throw std::runtime_error(message);}template<class F>void rejects(F fn){bool failed{};try{fn();}catch(const std::exception&){failed=true;}check(failed,"Invalid Event Log operation must reject");}
std::string id(unsigned number){char buffer[64];std::snprintf(buffer,sizeof(buffer),"00000000-0000-0000-0000-%012u",number);return buffer;}
struct Fixture{m::EventLogSnapshot snapshot;unsigned clears{},snapshots{};Fixture(){for(unsigned k=1;k<=40;++k)snapshot.events.push_back({id(k),k%2?m::EventKind::clipboardCopied:m::EventKind::shelfAdded,1700000000.-k,k%2?m::EventMetadata{{"kind","text"}}:m::EventMetadata{{"filename","Synthetic.pdf"}}});}m::EventLogCallbacks callbacks(){return {[this]{++snapshots;return snapshot;},[this]{++clears;snapshot.events.clear();},[](double){return "11-14 22:13:19";}};}};
struct Window{HWND hwnd{};Window(){WNDCLASSW wc{};wc.lpfnWndProc=DefWindowProcW;wc.hInstance=GetModuleHandleW(nullptr);wc.lpszClassName=L"OwnedEventLogFixture";check(RegisterClassW(&wc)!=0,"Register isolated Event Log fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,wc.lpszClassName,L"Owned fixture",WS_POPUP,0,0,1280,800,nullptr,nullptr,wc.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Event Log tests remain hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);UnregisterClassW(L"OwnedEventLogFixture",GetModuleHandleW(nullptr));}};
void scene(n::Renderer&renderer){n::LayerRasterizer raster;n::LayerComposition composition;Fixture fixture;m::EventLogState state(fixture.callbacks());state.activate();n::NativeEventLogScene scene(state,raster,{});n::NativeEventLogPose pose;
    const auto frame=[&](double time){pose.time=time;scene.syncContent(time);scene.updatePose(pose);scene.uploadAnimations(renderer);composition.setEntries(renderer,scene.entries());composition.present(renderer);check(scene.collectRetired(renderer),"Published prior generation retires");};
    renderer.setCamera(n::layerViewportProjection(1280,800));frame(0);renderer.draw(false);const auto initial=renderer.readback();check(scene.stats().rows==4&&scene.stats().outgoingRows==0&&!initial.pixels.empty(),"Original bounded row page paints through shared renderer");const auto oldRaster=raster.stats();const auto oldGraphics=renderer.stats();allocations=0;counting=true;for(unsigned k=0;k<100;++k){pose.time=.001*k;pose.world=c::Matrix4::translation(double(k%3),0)*c::Matrix4::rotation(.0001*k,0,0);scene.updatePose(pose);composition.present(renderer);}counting=false;check(allocations==0&&raster.stats().rasterizations==oldRaster.rasterizations&&renderer.stats().textureUploads==oldGraphics.textureUploads,"Warm Event Log tilt allocates/rasterizes/uploads nothing");
    pose.world={};state.scrollBy(55);frame(1);state.perform("eventLog:category:files");frame(2);check(scene.stats().rows==4&&scene.stats().outgoingRows==4&&scene.requiresFrames(2.01),"Category exchange retains exactly two bounded pages");const auto handoffRaster=raster.stats();frame(2.13);renderer.draw(false);const auto middle=renderer.readback();frame(2.3);renderer.draw(false);check(middle.pixels!=renderer.readback().pixels&&scene.stats().outgoingRows==0&&!scene.requiresFrames(2.31),"Source rectangular handoff finishes and releases old text");check(raster.stats().rasterizations==handoffRaster.rasterizations,"Inner handoff uses only numeric masks/transforms");
    state.selectNext(1);frame(3);frame(3.09);check(scene.stats().outlineRasters>=2,"Selection traces original stroke path");const auto selected=state.selected();scene.setAppearance({false,2,{.4,.2,.8,1}});frame(3.09);check(state.selected()==selected&&scene.requiresFrames(3.09),"Event Log preference replacement retains active row selection trace");frame(3.2);state.perform("eventLog:clear");frame(4);state.perform("eventLog:confirmClear");frame(4.05);check(fixture.clears==1&&scene.stats().outgoingRows>0,"Clear keeps bounded exiting rows during source handoff");frame(4.4);check(scene.stats().rows==0&&scene.stats().outgoingRows==0,"Cleared event text released after finite handoff");
    auto invalid=pose;invalid.world.values[0]=std::numeric_limits<double>::quiet_NaN();rejects([&]{scene.updatePose(invalid);});composition.detach(renderer);check(scene.releaseResources(renderer)&&renderer.stats().textures==0&&renderer.stats().meshes==0,"Event Log resources detach without second publisher");
}
Json blank(){return Json::Object{{"bounds",Json::Array{0,0,400,334}},{"position",Json::Array{0,0}},{"anchorPoint",Json::Array{0,0}},{"children",Json::Array{}}};}
void owner(n::Renderer&renderer){n::LayerRasterizer raster;n::LayerComposition composition;Fixture fixture;t::EventLogPreview owner(raster,{},fixture.callbacks());owner.resize({1280,800,96,1,1280,800});c::ModulePresentation modules{c::Module::eventLog};n::LayerScene empty(raster);empty.load(blank(),{});n::NativeModuleSurface plane(empty,c::Module::eventLog);c::source::DesktopChromeSettings settings{{0,0,1280,800},1,{},c::Module::eventLog,true};auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;const auto camera=n::layerViewportProjection(1280,800);double time{};
    const auto frame=[&](double dt=.01){time+=dt;const auto sample=modules.sample(time).presentation;settings.module=sample.requested;owner.update(center,settings,sample,1,time);owner.upload(renderer);composition.setEntries(renderer,owner.entries());composition.present(renderer);owner.collected(renderer);renderer.setCamera(camera);};
    const auto point=[&](c::Point p){const auto sample=modules.sample(time).presentation;const auto*surface=sample.current.module==c::Module::eventLog?&sample.current:&*sample.incoming;plane.update(center,settings,*surface);return *c::Projection::viewport(camera*plane.pose().contentWorld,1280,800).project(p);};
    const auto click=[&](c::Point p,bool verifyPress=false){const auto q=point(p);const auto action=owner.state().feedbackActionAt(p);const auto tint=action?std::string(*action)+"/tint":std::string{};check(owner.pointer({a::PointerKind::down,a::PointerButton::left,q.x,q.y,0},time),"Projected Event Log action owns source hit");check(owner.pointerLocked(),"Press locks outer tilt");frame(.07);if(verifyPress){bool found{};for(const auto&entry:owner.entries())if(auto index=entry.scene->surfaceIndex(tint)){entry.scene->prepareDraws();found=true;check(entry.scene->draws()[*index].opacity==1,"Selection replacement retains stationary press origin");}check(found,"Original Event Log action tint exists");}check(owner.pointer({a::PointerKind::up,a::PointerButton::left,q.x,q.y,0},time),"Release consumed by owner");frame(.3);};
    frame();click({60,110},true);check(owner.state().selected()==id(1),"Projected row selection maps original source identity");const auto p=point({100,150});check(owner.wheel({p.x,p.y,-.5,false,0,3},time),"Fractional wheel routed to source viewport");frame();check(owner.state().scrollOffset()==18,"Source wheel distance retained");owner.key({a::KeyKind::down,VK_NEXT},time);frame();check(owner.state().scrollOffset()==186,"Page Down uses viewport minus 30");owner.key({a::KeyKind::down,VK_HOME},time);frame();check(owner.state().scrollOffset()==0,"Home reveals beginning");
    click({330,55});check(owner.state().category()==m::EventCategory::files,"Category chip changes only Event Log page");click({320,313});check(owner.state().confirmingClear(),"Clear uses confirmation");check(owner.key({a::KeyKind::down,VK_ESCAPE},time),"Escape cancels confirmation before shell dismissal");frame(.3);check(!owner.key({a::KeyKind::down,VK_ESCAPE},time),"No confirmation leaves Escape to host");
    {const auto selected=owner.state().selected();const auto category=owner.state().category();const auto offset=owner.state().scrollOffset();const auto snapshots=fixture.snapshots;owner.setLanguage(c::Language::korean);owner.setAppearance({false,2,{.5,.2,.8,1}});frame();check(owner.state().strings().heading=="이벤트 로그"&&owner.state().selected()==selected&&owner.state().category()==category&&owner.state().scrollOffset()==offset&&fixture.snapshots==snapshots,"Event Log preferences preserve filter/scroll and never refresh recorder");const auto old=raster.stats();owner.setLanguage(c::Language::korean);frame();check(raster.stats().rasterizations==old.rasterizations,"Equal Event Log language is raster-idle");}
    center=center*c::Matrix4::rotation(.08,-.12,0);frame();check(owner.covers(point({100,150})),"Tilt keeps event hit plane aligned");modules.select(c::Module::power,time);frame(.4);frame(.4);const auto snapshots=fixture.snapshots;owner.refresh();check(fixture.snapshots==snapshots&&owner.entries().empty()&&!owner.requiresFrames(time),"Hidden module suspends snapshot reads and frame demand");composition.detach(renderer);owner.release(renderer);check(renderer.stats().textures==0&&renderer.stats().meshes==0,"Event owner retires all shared resources");
}
}
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==2,"Pass HLSL to hidden Event Log fixture");Window window;n::Renderer renderer;renderer.initialize(window.hwnd,1280,800,{n::Driver::warpForTests,argv[1],n::RenderTarget::offscreenForTests});scene(renderer);owner(renderer);renderer.reset();CoUninitialize();std::cout<<"PASS "<<checks<<" Event Log native/owner checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
