#include "modules/event_log.hpp"
#include "modules/event_log_presentation.hpp"
#include <atomic>
#include <cstdlib>
#include <cstdio>
#include <ctime>
#include <fstream>
#include <iostream>
#include <limits>
#include <new>
#include <stdexcept>
namespace m=endfield::modules;namespace c=endfield::core;using Json=ehud::data::Json;
namespace {unsigned checks{};std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {
void check(bool value,const char*message){++checks;if(!value)throw std::runtime_error(message);}template<class F>void rejects(F fn){bool failed{};try{fn();}catch(const std::exception&){failed=true;}check(failed,"Malformed source event input must reject");}
std::string id(unsigned n){char buffer[64];std::snprintf(buffer,sizeof(buffer),"00000000-0000-0000-0000-%012u",n);return buffer;}
std::string timestamp(double time){const std::time_t seconds=static_cast<std::time_t>(time+978307200);const auto*tm=std::gmtime(&seconds);char buffer[32];std::strftime(buffer,sizeof(buffer),"%m-%d %H:%M:%S",tm);return buffer;}
struct Fixture{m::EventLogSnapshot snapshot;unsigned clears{};Fixture(){const std::array kinds{m::EventKind::clipboardCopied,m::EventKind::shelfAdded,m::EventKind::workStarted,m::EventKind::audioDeviceConnected};const std::array<m::EventMetadata,4>metadata{{{{"kind","text"}},{{"filename","Project.pdf"}},{{"kind","countdown"},{"seconds","1800"}},{{"device","Studio Headphones"}}}};for(unsigned n=1;n<=20;++n)snapshot.events.push_back({id(n),kinds[(n-1)%4],1700000000.-978307200-n,metadata[(n-1)%4]});snapshot.events.insert(snapshot.events.begin(),{id(21),m::EventKind::overlayOpened,1700000100,{}});snapshot.events.insert(snapshot.events.begin(),{id(22),m::EventKind::moduleOpened,1700000200,{{"module","notes"}}});}
    m::EventLogCallbacks callbacks(){return {[this]{return snapshot;},[this]{snapshot.events.clear();++clears;},timestamp};}};
void model(){m::EventLog log(3);check(log.capacity()==3&&log.events().empty(),"Isolated model starts empty without provider or file");for(unsigned n=1;n<=5;++n)log.record(id(n),m::EventKind::clipboardCopied,n,{{"kind","text"},{"text","PRIVATE_BODY"},{"path","/private/secret"}});check(log.events().size()==3&&log.events().front().id==id(5)&&log.events().back().id==id(3),"Source newest-first bounded capacity");check(log.events()[0].metadata==m::EventMetadata{{"kind","text"}},"Clipboard payload never enters allowlisted metadata");
    const auto revision=log.revision();rejects([&]{log.record(id(5),m::EventKind::overlayOpened,6);});rejects([&]{log.record(id(6),m::EventKind::overlayOpened,std::numeric_limits<double>::quiet_NaN());});check(log.revision()==revision&&log.events().size()==3,"Malformed record leaves bounded model unchanged");log.clear();auto cleared=log.revision();log.clear();check(log.events().empty()&&log.revision()==cleared+1,"Even empty clear is explicit but never records itself");
    auto app=m::sanitizedEventMetadata(m::EventKind::appShortcutOpened,{{"app","  Example\n\tTool  "}});check(app.at("app")=="Example Tool","Exact source ASCII whitespace compaction");check(m::sanitizedEventMetadata(m::EventKind::appShortcutOpened,{{"app","/private/App"}}).empty(),"App path never becomes an event name");check(m::sanitizedEventMetadata(m::EventKind::shelfAdded,{{"filename","C:\\private\\Project.pdf"}}).at("filename")=="Project.pdf","Only basename survives shelf metadata");check(m::sanitizedEventMetadata(m::EventKind::accountAction,{{"action","linked"},{"token","secret"},{"uid","hidden"}})==m::EventMetadata{{"action","linked"}},"Account secrets and identity are discarded");
    check(m::sanitizedEventMetadata(m::EventKind::appShortcutOpened,{{"app",std::string(200,'a')}}).at("app")==std::string(160,'a'),"Source ASCII byte bound exact");check(m::sanitizedEventMetadata(m::EventKind::audioDeviceConnected,{{"device","扬声器"}}).at("device")=="扬声器","Already-short Unicode names retain source UTF8");std::string longUnicode;for(unsigned n=0;n<70;++n)longUnicode+="字";rejects([&]{m::sanitizedEventMetadata(m::EventKind::audioDeviceConnected,{{"device",longUnicode}});});const auto compact=m::sanitizedEventMetadata(m::EventKind::audioDeviceConnected,{{"device",longUnicode}},[](auto){return "字";});check(compact.at("device")=="字","Explicit Unicode grapheme adapter is bounded and injected");
    for(unsigned kind=0;kind<32;++kind){const auto value=static_cast<m::EventKind>(kind);check(!m::eventKindKey(value).empty()&&!m::eventKindTitle(value).empty()&&!m::eventCategoryKey(m::eventCategory(value)).empty(),"Every source event kind has original category/title");const auto sanitized=m::sanitizedEventMetadata(value,{{"body","secret"},{"token","secret"},{"path","secret"}});check(sanitized.empty(),"Unknown metadata remains absent for every kind");}
    m::EventLog one(0),max(999);check(one.capacity()==1&&max.capacity()==500,"Capacity matches source clamp");
}
void state(){Fixture fixture;m::EventLogState state(fixture.callbacks());check(state.itemCount()==20&&state.filteredCount()==20,"Routine navigation remains invisible in every count");check(state.visibleRows().size()==4&&state.rowRect(id(1))==c::Rect{12,94,369,51},"Original 55pt row geometry and bounded viewport");state.activate();state.acknowledgeChanges();state.scrollBy(55.25);check(state.scrollOffset()==55.25,"Fractional source wheel offset retained");fixture.snapshot.events.insert(fixture.snapshot.events.begin(),{id(30),m::EventKind::shelfRemoved,1700000200,{{"filename","New.txt"}}});state.refresh();check(state.scrollOffset()==110.25,"New events preserve top visible identity and fraction");state.scrollBy(-9999);fixture.snapshot.events.insert(fixture.snapshot.events.begin(),{id(31),m::EventKind::shelfRemoved,1700000300,{{"filename","Newest.txt"}}});state.refresh();check(state.scrollOffset()==0,"At top new arrivals remain visible");
    state.perform("eventLog:clear");check(state.confirmingClear(),"Clear first requests confirmation");state.scrollBy(1);check(state.confirmingClear(),"Unlike Clipboard, scrolling preserves Event Log confirmation");check(state.cancelConfirmation()&&!state.cancelConfirmation(),"Escape only consumes active confirmation");state.selectNext(-1);check(state.selected()==id(20)&&state.scrollOffset()==state.maximumOffset(),"Up from no selection reveals source last row");
    state.perform("eventLog:category:work");check(state.category()==m::EventCategory::work&&state.filteredCount()==5&&state.scrollOffset()==0&&!state.selected(),"Category exchange resets selection and scroll");check(state.pendingChanges().size()==1&&state.pendingChanges()[0].kind==m::EventLogState::ChangeKind::exchange&&state.pendingChanges()[0].direction==1&&state.pendingChanges()[0].animated,"Original category order drives positive handoff");const auto revision=state.revision();state.perform("eventLog:category:work");check(state.revision()==revision,"Same category is a no-op");state.perform("eventLog:category:all");check(state.pendingChanges().size()==1&&state.pendingChanges()[0].direction==-1,"Rapid change settles prior destination and replaces one bounded exchange");
    state.perform("eventLog:clear");state.perform("eventLog:confirmClear");check(fixture.clears==1&&state.itemCount()==0&&!state.confirmingClear(),"Confirmed clear invokes injected callback once, logs nothing");check(state.pendingChanges().size()==2,"Clear exchanges content and animates only bottom confirmation");state.deactivate();check(!state.active()&&state.pendingChanges().size()==1&&state.pendingChanges()[0].kind==m::EventLogState::ChangeKind::settle,"Deactivate releases transition ownership");const auto emptyRevision=state.revision();allocations=0;counting=true;for(unsigned n=0;n<1000;++n){state.scrollBy(1);state.visibleRange();state.maximumOffset();}counting=false;check(allocations==0&&state.revision()==emptyRevision,"Idle and clamped scrolling allocate and mutate nothing");
    Fixture bad;m::EventLogState stable(bad.callbacks());const auto old=stable.revision();bad.snapshot.events.push_back(bad.snapshot.events[0]);rejects([&]{stable.refresh();});check(stable.itemCount()==20&&stable.revision()==old,"Malformed snapshot retains previous content");
}
void handoff(){for(double direction:{-1.,1.})for(unsigned n=0;n<=1000;++n){const auto s=m::sampleEventLogHandoff(direction,.26*n/1000);check(std::abs(s.incoming.width+s.outgoing.width-376)<1e-9,"Source masks cover one complete viewport");check(std::abs((direction>0?s.outgoing.x+s.outgoing.width:s.incoming.x+s.incoming.width)-(direction>0?s.incoming.x:s.outgoing.x))<1e-9,"Incoming/outgoing masks share exact moving edge");check(s.incomingX*direction>=0&&s.outgoingX*direction<=0,"Source pages translate in authored directions");}allocations=0;counting=true;for(unsigned n=0;n<1000;++n)(void)m::sampleEventLogHandoff(1,double(n)/1000);counting=false;check(allocations==0,"Pure handoff samples allocate no memory");rejects([]{m::sampleEventLogHandoff(1,std::numeric_limits<double>::quiet_NaN());});}
void dump(const char*path){Fixture fixture;m::EventLogState state(fixture.callbacks());state.activate();m::EventLogAppearance appearance;Json::Array cases;const auto record=[&](const char*name){const auto plan=m::prepareEventLogArtwork(state,appearance);Json::Array parts,actions;const auto add=[&](const m::EventLogPart&p){parts.push_back(Json::Object{{"rowID",p.rowID},{"full",Json::Array{p.full.x,p.full.y,p.full.width,p.full.height}},{"layer",p.layers}});};add(plan.header);add(plan.toolbar);add(plan.empty);add(plan.scrollbar);for(const auto&p:plan.rows)add(p);for(const auto&a:state.actions())actions.push_back(Json::Object{{"id",a.id},{"label",a.label},{"rect",Json::Array{a.rect.x,a.rect.y,a.rect.width,a.rect.height}}});cases.push_back(Json::Object{{"name",name},{"parts",std::move(parts)},{"actions",std::move(actions)},{"scroll",state.scrollOffset()},{"count",std::int64_t(state.filteredCount())}});};record("top");state.scrollBy(.5);record("fractional");state.perform("eventLog:row:"+id(2));record("selected");state.perform("eventLog:clear");record("confirm");appearance.dark=false;record("light");state.perform("eventLog:category:work");record("work");state.perform("eventLog:category:display");record("emptyCategory");state.perform("eventLog:clear");state.perform("eventLog:confirmClear");record("empty");std::ofstream out(path);out<<Json(Json::Object{{"cases",std::move(cases)}}).encode();check(bool(out),"Write isolated descriptor comparison");}
void privacyOracle(const char*path){std::ifstream input(path);const std::string text((std::istreambuf_iterator<char>(input)),{});const auto reference=Json::parse(text,8*1024*1024);for(const auto&sample:reference["metadata"].array()){std::optional<m::EventKind>kind;for(unsigned n=0;n<32;++n)if(m::eventKindKey(static_cast<m::EventKind>(n))==sample["kind"].string())kind=static_cast<m::EventKind>(n);check(kind.has_value(),"Original privacy kind known");m::EventMetadata raw,expected;for(const auto&[key,value]:sample["raw"].object())raw.emplace(key,value.string());for(const auto&[key,value]:sample["metadata"].object())expected.emplace(key,value.string());const auto actual=m::sanitizedEventMetadata(*kind,raw);check(actual==expected,"Original Swift allowlist and name normalization exact");check(m::eventDetail({id(1),*kind,0,actual})==sample["detail"].string(),"Original Swift detail labels and field order exact");}}
void handoffOracle(const char*path){std::ifstream input(path);const std::string text((std::istreambuf_iterator<char>(input)),{});const auto reference=Json::parse(text);check(reference["maximumRepeatDifference"].number()==0,"Actual source handoff is paused/deterministic");double maximum{};for(const auto&row:reference["samples"].array()){const auto s=m::sampleEventLogHandoff(row["direction"].number(),row["phase"].number()*.26);const bool incoming=row["incoming"].boolean();const auto rect=incoming?s.incoming:s.outgoing;const std::array actual{rect.x,rect.y,rect.width,rect.height};for(unsigned n=0;n<4;++n){const auto error=std::abs(actual[n]-row["bounds"].array()[n].number());maximum=std::max(maximum,error);check(error<.0001,"Original CA rectangular mask geometry matches sampled handoff");}const auto x=incoming?s.incomingX:s.outgoingX;maximum=std::max(maximum,std::abs(x-(row.contains("x")?row["x"].number():row["matrix"].array()[12].number())));check(std::abs(x-(row.contains("x")?row["x"].number():row["matrix"].array()[12].number()))<.0001,"Original CA page translation matches sampled handoff");}std::cout<<"Handoff maximum source difference "<<maximum<<" points\n";}

}
int main(int argc,char**argv){try{model();state();handoff();if(argc>1)dump(argv[1]);if(argc>2)privacyOracle(argv[2]);if(argc>3)handoffOracle(argv[3]);std::cout<<"PASS "<<checks<<" Event Log model/state/artwork checks\n";return 0;}catch(const std::exception&e){counting=false;std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
