#include "modules/map_presentation.hpp"
#include "core/data/json.hpp"
#include <algorithm>
#include <atomic>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <limits>
#include <new>
#include <stdexcept>
namespace {std::atomic<std::uint64_t>allocations{};}
void*operator new(std::size_t n){allocations.fetch_add(1,std::memory_order_relaxed);if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}
void operator delete(void*p)noexcept{std::free(p);}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete[](void*p)noexcept{::operator delete(p);}
#ifdef __cpp_sized_deallocation
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace m=endfield::modules;namespace c=endfield::core;using J=ehud::data::Json;
namespace {unsigned checks{};void check(bool v,const char*message){++checks;if(!v)throw std::runtime_error(message);}bool closeEnough(double a,double b){return std::abs(a-b)<=2e-12*std::max({1.,std::abs(a),std::abs(b)});}m::MapViewport viewport(const J&j){return {j.array()[0].number(),j.array()[1].number(),j.array()[2].number()};}void equal(c::Rect r,const J&j){check(closeEnough(r.x,j.array()[0].number())&&closeEnough(r.y,j.array()[1].number())&&closeEnough(r.width,j.array()[2].number())&&closeEnough(r.height,j.array()[3].number()),"Raster bounds equal original source geometry");}
void source(const char*path){std::ifstream f(path);check(bool(f),"Explicit original Map fixture exists");const auto root=J::parse(std::string((std::istreambuf_iterator<char>(f)),{}),256*1024);check(root["authority"].string()=="ca04f142185c7de40acd8523bdb563195d90a1d1","Map fixture authority pinned");for(const auto&row:root["raster"].array()){const auto camera=viewport(row["camera"]),target=viewport(row["target"]);m::MapRasterFrame frame{camera,{-128,-128,696,696},1.4};const auto p=m::mapRasterPlacement(frame,target);check(closeEnough(p.position.x,row["placement"].array()[0].number())&&closeEnough(p.position.y,row["placement"].array()[1].number())&&closeEnough(p.scale,row["placement"].array()[2].number()),"Retained image projection matches original including antimeridian");const auto geometry=m::mapRasterGeometry(camera,2.2);check(bool(geometry),"Valid source request has bounded allocation geometry");const auto&g=row["geometry"];equal(geometry->screenRect,g["screen"]);equal(geometry->worldRect,g["world"]);check(geometry->pixelDimension==g["pixels"].integer()&&closeEnough(geometry->pixelsPerPoint,g["pixelScale"].number())&&closeEnough(geometry->worldScale,g["factor"].number())&&closeEnough(geometry->tolerance,g["tolerance"].number()),"Pixel cap and octave simplification equal original worker");check(closeEnough(geometry->origin.x,g["origin"].array()[0].number())&&closeEnough(geometry->origin.y,g["origin"].array()[1].number()),"Original world raster origin");std::size_t n{};for(bool same:{false,true})for(bool interacting:{false,true})for(bool exact:{false,true})check(m::mapNeedsPaint(&frame,target,same,interacting,exact,2)==row["needsPaint"].array()[n++].boolean(),"Source paint eligibility, scale quality and exact request semantics");}}
void finitePlan(){const auto g=m::mapRasterGeometry({},100,500);check(g&&g->pixelDimension==1536&&g->screenRect==c::Rect{-128,-128,696,696},"Huge requested scale/padding still uses source1536-square cap");check(std::size_t(g->pixelDimension)*g->pixelDimension*4<=9437184,"One detail image stays at source9MiB bound");check(!m::mapRasterGeometry({},0)&&!m::mapRasterGeometry({},2,std::numeric_limits<double>::infinity()),"Malformed worker request rejected before image allocation");check(m::mapRenderScale(8,false)==2.2&&m::mapRenderScale(8,true)==1.4&&m::mapRenderScale(.1,true)==1,"Motion image and settled detail use distinct source scale limits");check(m::mapPaintCooldown(.001)==.125&&m::mapPaintCooldown(.1)==1.6,"Sustained painting remains at source one-seventeenth-core budget");const auto places=m::mapBackdropPlacements({.5,.5,3});check(places[1].position==c::Point{-440,-110}&&places[1].scale==1320./1024&&places[0].position.x==-1760&&places[2].position.x==880,"Three wraps reference one retained world image");
    m::MapRasterFrame frame{{},{-128,-128,696,696},2.2};check(!m::mapNeedsPaint(&frame,{},true,false,false,2.2),"Settled source frame performs no idle raster work");auto changed=frame.viewport;changed.centerX+=.001;check(!m::mapNeedsPaint(&frame,changed,true,true,false,2.2)&&m::mapNeedsPaint(&frame,changed,true,false,true,2.2),"Tiny gesture transforms retained detail immediately, requests exact detail only at end");const auto before=allocations.load();double checksum{};for(unsigned n=0;n<1000;++n){auto v=frame.viewport;v.centerX+=double(n)*.000001;const auto p=m::mapRasterPlacement(frame,v);checksum+=p.position.x;(void)m::mapNeedsPaint(&frame,v,true,true,false,2.2);(void)m::mapBackdropPlacements(v);}check(allocations.load()==before&&std::isfinite(checksum),"Warm image placement/cache decisions allocate nothing");}
void pinsAndChrome(){std::vector<m::MapPin>pins;for(unsigned n=0;n<30;++n)pins.push_back({std::to_string(n),m::MapViewport{}.centerX,m::MapViewport{}.centerY,double(n),n==0?m::MapPinStyle::player:m::MapPinStyle::yellow});auto visual=m::mapPinVisuals(pins,{},"0",true,false,true);check(visual.count==30&&visual.items[0].selected&&visual.items[0].pulses,"Selected player marker has pulse priority");unsigned count{};for(const auto&p:visual.items)count+=p.pulses;check(count==12&&!visual.items[1].pulses&&visual.items[29].pulses,"Only12 latest/selected visible pins pulse");auto hidden=m::mapPinVisuals(pins,{},"0",false,false,true);check(hidden.items[0].staticHaloOpacity==.65&&hidden.items[1].staticHaloOpacity==.25&&!hidden.items[0].pulses,"Hidden marker artwork stays static for closing scene");auto reduced=m::mapPinVisuals(pins,{},"0",true,true,true);check(!reduced.items[0].pulses,"Reduce motion disables ambient marker timing");check(m::mapPinColor(m::MapPinStyle::player)==m::mapPinColor(m::MapPinStyle::yellow)&&m::mapPinColor(m::MapPinStyle::green)==m::MapColor{.66,.95,.2,1},"Original game yellow and custom green colors retained");const auto assets=m::mapPlayerAssets();check(assets[0].rect==c::Rect{-24,-26,48,52}&&assets[0].opacity==.149&&assets[1].rect==c::Rect{-3,-106,6,102}&&assets[1].screenBlend&&assets[1].opacity==.72&&assets[2].path.ends_with("icon_char---2308601083109874541.png"),"Player glyph/halo/beam use original Domain resources and source aspect/layout");
    const auto pulse=m::mapPulse(0);check(pulse.scale==.65&&pulse.opacity==.05,"Pulse starts at authored scale/opacity");check(closeEnough(m::mapPulse(1.7).scale,.65),"Ambient cycle lasts1.7seconds");const auto change=m::mapStyleTransition(0);check(change.rotation==-.12&&change.opacity==.45&&m::mapStyleTransition(.16).opacity==1,"Pin style transition preserves authored finite endpoints");check(m::mapStyleTransition(0,true).opacity==1,"Reduced motion settles source style transition");const auto before=allocations.load();for(unsigned n=0;n<100;++n){const auto result=m::mapPinVisuals(pins,{},"0",true,false,true);check(result.count==30,"Retained visual count");}check(allocations.load()==before,"Visible pin selection allocates no artwork or metadata");
    check(m::mapDiameter==440&&m::mapRadius==216&&m::mapEdgeFeather==9,"Source circular footprint and compositor feather retained");const auto chrome=m::MapChromeGeometry{};check(chrome.heading==c::Rect{122,37,196,17}&&chrome.coordinates==c::Rect{100,301,211,26},"Fixed source chrome placement");check(m::mapZoomStatus({},3,true,true,{"MAP","LOADING TERRAIN","PINS"})=="3.00×  /  03 PINS","Source zoom status has exact separators/padding");check(m::mapZoomStatus({},3,false,true,{"地图","载入地形","标记"})=="载入地形","Locale strings injected without a second catalog");check(m::mapActionSymbol(m::MapAction::reset)=="⌖"&&m::mapActionSymbol(m::MapAction::addPin)=="⊙","Original reset/center action symbols retained");}
}
int main(int argc,char**argv){try{check(argc==2,"Pass original Swift map fixture");source(argv[1]);finitePlan();pinsAndChrome();std::cout<<"PASS "<<checks<<" Map presentation/source checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
