#include "native/map_painter.hpp"
#include "modules/map_geography.hpp"
#include "core/data/json.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <fstream>
#include <iostream>
#include <limits>
#include <thread>

namespace n=endfield::native;namespace m=endfield::modules;namespace c=endfield::core;using J=ehud::data::Json;
namespace {
unsigned checks{};
void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}
template<class F>void rejects(F&&fn,const char*why){bool rejected{};try{fn();}catch(const std::exception&){rejected=true;}check(rejected,why);}
std::vector<std::uint8_t>read(const char*path,std::size_t maximum){std::ifstream file(path,std::ios::binary|std::ios::ate);check(bool(file),"Open explicitly supplied source fixture");const auto end=file.tellg();check(end>=0&&std::uint64_t(end)<=maximum,"Fixture size respects source archive bound");std::vector<std::uint8_t>bytes(std::size_t(end),0);file.seekg(0);file.read(reinterpret_cast<char*>(bytes.data()),std::streamsize(bytes.size()));check(bool(file),"Read complete source fixture");return bytes;}
m::MapRing rectangle(c::Rect r){return {{{r.x,r.y},{r.x+r.width,r.y},{r.x+r.width,r.y+r.height},{r.x,r.y+r.height}},true,r};}
std::shared_ptr<m::MapGeography>synthetic(){auto g=std::make_shared<m::MapGeography>();m::MapCountries countries;
    const auto add=[&](const char*id,c::Rect bounds,bool hole){m::MapPath path{rectangle(bounds)};if(hole)path.push_back(rectangle({bounds.x+12,bounds.y+12,10,10}));countries.countries.push_back({id,id,path,bounds,{{path,bounds}}});countries.vertexCount+=hole?8:4;};
    add("A",{460,200,80,100},true);add("B",{600,200,80,100},false);g->countries=std::move(countries);
    m::MapTerrain t;t.bands.push_back({500,{{{{300,270},{700,270}},false,{300,270,400,0}}},{}});t.vertexCount=2;g->terrain=std::move(t);return g;
}
void image(const n::MapPaintResult&r,unsigned side,bool background){check(r.detail&&r.frame&&r.detail->width==side&&r.detail->height==side&&r.detail->straightRGBA.size()==std::size_t(side)*side*4,"Painter publishes exactly one bounded source detail bitmap");
    check(std::isfinite(r.workSeconds)&&r.workSeconds>=0,"Worker duration includes finite entire paint");bool opaque=true;for(std::size_t p=3;p<r.detail->straightRGBA.size();p+=4)opaque&=r.detail->straightRGBA[p]==255;check(opaque,"Original opaque map plate remains opaque in straight RGBA output");
    check(bool(r.backdrop)==background,"Backdrop generated only when requested");if(background)check(r.backdrop->width==1024&&r.backdrop->height==512&&r.backdrop->straightRGBA.size()==1024*512*4,"Original world fallback remains1024x512");
}
void lifecycle(){auto data=synthetic();n::NativeMapPainter painter;n::MapPaintRequest q{data,{.5,.5,3},true,{.98,.87,.13,1},1,true,1};const auto initial=painter.paint(q,[]{return false;});image(initial,696,true);check(initial.frame->screenRect==c::Rect{-128,-128,696,696}&&initial.frame->pixelsPerPoint==1,"Native pixels retain source128-point overscan and logical coverage");
    const auto cached=painter.stats();check(cached.countryIndexes==2&&cached.terrainIndexes==1&&cached.cachedLevels==2,"Backdrop creates no retained whole-world country duplicates");
    q.backdrop=false;const auto same=painter.paint(q,[]{return false;});image(same,696,false);check(same.detail->straightRGBA==initial.detail->straightRGBA,"Same camera/theme yields identical native pixels");const auto reuse=painter.stats();check(reuse.countryIndexes==cached.countryIndexes&&reuse.terrainIndexes==cached.terrainIndexes&&reuse.cachedLevels==cached.cachedLevels,"Repeated paint reuses indexed paths and simplification levels");
    q.dark=false;const auto light=painter.paint(q,[]{return false;});image(light,696,false);check(light.detail->straightRGBA!=initial.detail->straightRGBA,"Original dark/light raster palette changes pixels");
    q.contentsScale=8;const auto maximum=painter.paint(q,[]{return false;});image(maximum,1536,false);check(maximum.detail->straightRGBA.size()==1536*1536*4,"Oversized render scale is bounded by original1536-square budget");
    unsigned cancellationChecks{};const auto cancelled=painter.paint(q,[&]{return ++cancellationChecks>3;});check(!cancelled.detail&&!cancelled.backdrop&&!cancelled.frame,"Cancelled geometry/drawing never publishes a partial bitmap");check(painter.stats().countryIndexes==0&&painter.stats().terrainIndexes==0,"Cancelled paint clears worker-owned geographic working cache");
    q.contentsScale=1;q.backdrop=true;image(painter.paint(q,[]{return false;}),696,true);painter.clear();check(painter.stats().countryIndexes==0&&painter.stats().terrainIndexes==0&&initial.detail->straightRGBA==same.detail->straightRGBA,"Explicit worker cleanup retains caller-owned closing image");
    bool wrongThread{};std::thread other([&]{try{(void)painter.stats();}catch(const std::logic_error&){wrongThread=true;}});other.join();check(wrongThread,"Painter caches cannot move between utility workers");
    const auto empty=std::make_shared<m::MapGeography>();q.geography=empty;rejects([&]{painter.paint(q,[]{return false;});},"Absent geography rejects");q.geography=data;q.contentsScale=NAN;rejects([&]{painter.paint(q,[]{return false;});},"Nonfinite scale rejects before bitmap allocation");q.contentsScale=1;q.viewport.centerX=2;rejects([&]{painter.paint(q,[]{return false;});},"Unconstrained viewport rejects");q.viewport={.5,.5,3};q.accent[0]=2;rejects([&]{painter.paint(q,[]{return false;});},"Invalid accent rejects before bitmap allocation");
}
void fallback(){auto data=synthetic();data->countries.reset();auto coast=rectangle({460,200,80,100});data->terrain->bands.push_back({0,{coast},m::MapPath{coast}});n::NativeMapPainter painter;n::MapPaintRequest q{data,{.5,.5,3},true,{1,1,0,1},1,true,1};image(painter.paint(q,[]{return false;}),696,true);check(painter.stats().countryIndexes==0&&painter.stats().fillIndexes==1,"Terrain-only source fallback paints without country paths");
    auto countries=synthetic();countries->terrain.reset();q.geography=countries;image(painter.paint(q,[]{return false;}),696,true);check(painter.stats().terrainIndexes==0&&painter.stats().fillIndexes==0,"Data replacement releases old terrain/fill indexes independently");
}
void actual(const char*terrainPath,const char*countriesPath){auto data=std::make_shared<m::MapGeography>();data->terrain=m::MapTerrain::decode(read(terrainPath,m::MapTerrain::maximumBytes));data->countries=m::MapCountries::decode(read(countriesPath,m::MapCountries::maximumBytes));n::NativeMapPainter painter;n::MapPaintRequest q{data,m::MapViewport{},true,{.98,.87,.13,1},1,true,1};const auto first=painter.paint(q,[]{return false;});image(first,696,true);const auto stats=painter.stats();std::size_t components{};for(const auto&country:data->countries->countries)components+=country.components.size();check(stats.countryIndexes>0&&stats.countryIndexes<components,"Original Shenzhen camera retains only relevant source country indexes");q.backdrop=false;q.viewport=m::mapConstrained({.002,.5,3});image(painter.paint(q,[]{return false;}),696,false);check(painter.stats().cachedLevels<=painter.stats().countryIndexes*2,"Dateline wrapping preserves source two-level per-component LRU budget");std::cout<<"Native source map initial paint "<<first.workSeconds*1000<<"ms, cached components "<<stats.countryIndexes<<'/'<<components<<'\n';}
std::vector<std::uint8_t>hex(std::string_view s){check(s.size()%2==0&&s.size()<=16384,"Synthetic source archive hex is bounded");std::vector<std::uint8_t>b;const auto digit=[](char v){if(v>='0'&&v<='9')return v-'0';if(v>='a'&&v<='f')return v-'a'+10;throw std::invalid_argument("Invalid fixture hex");};for(std::size_t k=0;k<s.size();k+=2)b.push_back(std::uint8_t(digit(s[k])*16+digit(s[k+1])));return b;}
void sourcePixels(const char*path){const auto bytes=read(path,512*1024);const auto fixture=J::parse(std::string_view(reinterpret_cast<const char*>(bytes.data()),bytes.size()),512*1024);check(fixture["authority"].string()=="ca04f142185c7de40acd8523bdb563195d90a1d1"&&fixture["sourcePins"].object().size()==6,"Original painter authority/source hashes are retained");auto data=std::make_shared<m::MapGeography>();data->terrain=m::MapTerrain::decode(hex(fixture["terrainHex"].string()));data->countries=m::MapCountries::decode(hex(fixture["countriesHex"].string()));n::NativeMapPainter painter;unsigned maximum{},samples{},flat{};double maximumMeanDelta{};
    const auto compare=[&](const n::MapPaintImage&bitmap,const J&frame){
        check(bitmap.width==unsigned(frame["pixelWidth"].integer())&&bitmap.height==unsigned(frame["pixelHeight"].integer()),"Original CoreGraphics oracle image dimensions match");
        for(const auto&sample:frame["samples"].array()){const auto x=unsigned(sample["x"].integer()),y=unsigned(sample["y"].integer());check(x<bitmap.width&&y<bitmap.height,"Original sample lies inside bounded output");unsigned delta{};for(unsigned channel=0;channel<4;++channel){const auto actual=bitmap.straightRGBA[(std::size_t(y)*bitmap.width+x)*4+channel];delta=std::max(delta,unsigned(std::abs(int(actual)-int(sample["rgba"].array()[channel].integer()))));}maximum=std::max(maximum,delta);++samples;
            const auto&region=sample["meanRegion"];const auto rx=unsigned(region["x"].integer()),ry=unsigned(region["y"].integer()),rw=unsigned(region["width"].integer()),rh=unsigned(region["height"].integer());check(rw&&rh&&rw<=bitmap.width&&rh<=bitmap.height&&rx<=bitmap.width-rw&&ry<=bitmap.height-rh,"Original diagnostic region is bounded");for(unsigned channel=0;channel<4;++channel){double sum{};for(unsigned yy=0;yy<rh;++yy)for(unsigned xx=0;xx<rw;++xx)sum+=bitmap.straightRGBA[(std::size_t(ry+yy)*bitmap.width+rx+xx)*4+channel];maximumMeanDelta=std::max(maximumMeanDelta,std::abs(sum/(rw*rh)-region["rgba"].array()[channel].number()));}
            if(sample["flat3x3"].boolean()){++flat;check(delta<=2,"Original flat source palette remains within two byte levels");}}
    };
    for(const auto&frame:fixture["detailFrames"].array()){const auto&camera=frame["camera"].array();n::MapPaintRequest q{data,{camera[0].number(),camera[1].number(),camera[2].number()},frame["dark"].boolean(),{},frame["scale"].number(),false,1};for(unsigned k=0;k<4;++k)q.accent[k]=frame["accent"].array()[k].number();const auto result=painter.paint(q,[]{return false;});check(bool(result.detail),"Original fixture detail paints");compare(*result.detail,frame);}
    for(const auto&frame:fixture["backdropFrames"].array()){n::MapPaintRequest q{data,{.5,.5,3},frame["dark"].boolean(),{.98,.87,.13,1},1,true,1};const auto result=painter.paint(q,[]{return false;});check(bool(result.backdrop),"Original fixture backdrop paints");compare(*result.backdrop,frame);}
    check(samples>0&&flat>0,"Original source fixture includes real pixels and flat palette checks");std::cout<<"Original CoreGraphics sample comparison: "<<samples<<" points, "<<flat<<" flat points; maximum AA/color residual "<<maximum<<"/255; maximum7x7 mean residual "<<maximumMeanDelta<<"/255 (full raster parity unverified)\n";
}
}
int main(int argc,char**argv){try{check(argc==3||argc==4,"Pass original Terrain.bin Countries.bin [original-pixel-fixture.json]");lifecycle();fallback();actual(argv[1],argv[2]);if(argc==4)sourcePixels(argv[3]);std::cout<<"Native Map painter: "<<checks<<" checks passed (synthetic/source geography; no HWND or renderer)\n";return 0;}catch(const std::exception&e){std::cerr<<"Native Map painter failed after "<<checks<<": "<<e.what()<<'\n';return 1;}}
