#include "native/renderer.hpp"
#include "core/data/json.hpp"
#include <windows.h>
#include <objbase.h>
#include <algorithm>
#include <atomic>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <new>
namespace{std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace{namespace n=endfield::native;namespace c=endfield::core;using J=ehud::data::Json;unsigned checks{};
void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}template<class F>void rejects(F f,const char*s){bool rejected{};try{f();}catch(const std::exception&){rejected=true;}check(rejected,s);}
struct Window{HWND h{};Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"OwnedMapGroupFixture";check(RegisterClassW(&c)!=0,"Owned group class");h=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,c.lpszClassName,L"Synthetic group",WS_POPUP,0,0,8,8,nullptr,nullptr,c.hInstance,nullptr);check(h&&!IsWindowVisible(h),"Nested fixture remains hidden");}~Window(){if(h)DestroyWindow(h);UnregisterClassW(L"OwnedMapGroupFixture",GetModuleHandleW(nullptr));}};
constexpr std::array<std::uint32_t,6>indices{0,1,2,0,2,3};constexpr std::array<n::Vertex,4>quad{{{{0,0,0},{0,0}},{{8,0,0},{1,0}},{{8,8,0},{1,1}},{{0,8,0},{0,1}}}};
std::array<float,4>tint(const J&j){std::array<float,4>v{};for(unsigned k=0;k<3;++k){const double s=j.array()[k].number();v[k]=float(s<=.04045?s/12.92:std::pow((s+.055)/1.055,2.4));}v[3]=float(j.array()[3].number());return v;}
void test(n::Renderer&r,const std::filesystem::path&fixture){std::ifstream f(fixture,std::ios::binary);check(bool(f),"Open original nested CA fixture");std::string bytes{std::istreambuf_iterator<char>(f),{}};auto oracle=J::parse(bytes,128*1024);check(oracle["rows"].array().size()==60,"Sixty actual source-group cases");c::Matrix4 camera;camera.values={.25,0,0,0,0,-.25,0,0,0,0,0,0,-1,1,0,1};r.setCamera(camera);r.setMesh("quad",1,{quad,indices});const n::NativeGroupTarget target{{0,0,8,8},1,n::NativeGroupColorSpace::encodedSRGB};
    std::array<n::DrawObject,4>leaves;for(unsigned k=0;k<4;++k){leaves[k].sourceID="leaf"+std::to_string(k);leaves[k].meshID="quad";}
    n::DrawObject background;background.sourceID="background";background.meshID="quad";std::array<n::DrawObject,2>parent;parent[0]=background;
    unsigned maximum{};for(const auto&row:oracle["rows"].array()){const auto count=row["colors"].array().size();for(unsigned k=0;k<count;++k){leaves[k].linearTint=tint(row["colors"].array()[k]);leaves[k].blend=k==unsigned(row["screenIndex"].integer())?n::NativeBlend::screen:n::NativeBlend::sourceOver;}
        r.configureNativeGroup("z-marker",target,std::span(leaves.data(),count));parent[0].linearTint=tint(row["background"]);parent[1]=r.nativeGroupOutput("z-marker");parent[1].opacity=float(row["markerOpacity"].number());r.configureNativeGroup("a-map",target,parent);auto output=r.nativeGroupOutput("a-map");r.setDrawList(std::span(&output,1));r.draw(false);const auto pixels=r.readback();for(unsigned k=0;k<4;++k){const unsigned delta=unsigned(std::abs(int(pixels.pixels[4*pixels.rowBytes+4*4+k])-int(row["bgra"].array()[k].integer())));maximum=std::max(maximum,delta);check(delta<=2,"Original nested marker pixels match within two byte levels");}}
    parent[1].opacity=.45f;r.setNativeGroupDraws("a-map",parent);r.draw(false);const auto old=r.readback().pixels;const auto stable=r.stats();auto child=r.nativeGroupOutput("z-marker"),root=r.nativeGroupOutput("a-map");
    rejects([&]{r.setNativeGroupDraws("z-marker",std::span(&child,1));},"Self cycle rejects");rejects([&]{r.setNativeGroupDraws("z-marker",std::span(&root,1));},"Indirect cycle rejects");rejects([&]{r.configureNativeGroup("depth3",target,std::span(&root,1));},"Depth three rejects");auto bad=child;bad.meshID="quad";rejects([&]{r.setNativeGroupDraws("a-map",std::span(&bad,1));},"Mixed regular/group output pair rejects");bad=child;bad.blend=n::NativeBlend::screen;rejects([&]{r.setNativeGroupDraws("a-map",std::span(&bad,1));},"Parent screen on group output rejects");bad=leaves[0];bad.alphaMask=n::PlaneAlphaMask{{},{0,0,8,8},child.textureID};rejects([&]{r.setNativeGroupDraws("z-marker",std::span(&bad,1));},"Group output cannot become mask input");r.draw(false);check(r.readback().pixels==old&&r.stats().nativeGroupTargetAllocations==stable.nativeGroupTargetAllocations,"Malformed graph preserves pixels and allocations");
    allocations=0;counting=true;try{for(unsigned k=0;k<120;++k){parent[1].opacity=.45f+.55f*k/119;r.setNativeGroupDraws("a-map",parent);r.draw(false);}}catch(...){counting=false;throw;}counting=false;check(allocations==0&&r.stats().nativeGroupTargetAllocations==stable.nativeGroupTargetAllocations&&r.stats().textureUploads==stable.textureUploads,"Nested fade allocates and uploads no texture");
    const auto before=r.stats().nativeGroupRenders;leaves[0].opacity=.3f;r.setNativeGroupDraws("z-marker",std::span(leaves.data(),4));r.draw(false);check(r.stats().nativeGroupRenders==before+2,"Dirty leaf renders before lexically earlier parent and invalidates it once");r.draw(false);check(r.stats().nativeGroupRenders==before+2,"Settled nested graph adds no render work");
    root.opacity=0;r.setDrawList(std::span(&root,1));leaves[0].opacity=.7f;r.setNativeGroupDraws("z-marker",std::span(leaves.data(),4));r.draw(false);check(r.stats().nativeGroupRenders==before+2,"Hidden ancestor suppresses nested render work");root.opacity=1;r.setDrawList(std::span(&root,1));r.draw(false);check(r.stats().nativeGroupRenders==before+4,"Showing ancestor flushes retained leaf then parent");
    check(!r.removeNativeGroup("z-marker"),"Borrowed leaf cannot retire");r.clearDrawList();check(r.removeNativeGroup("a-map")&&r.removeNativeGroup("z-marker")&&r.removeMesh("quad"),"Parent then leaf retirement leaves no resources");check(r.stats().textures==0&&r.stats().meshes==0,"Nested group resources fully retire");r.setMesh("capacity-quad",1,{quad,indices});n::DrawObject leaf;leaf.sourceID="capacity-leaf";leaf.meshID="capacity-quad";std::vector<std::string>ids;std::vector<n::DrawObject>outputs;for(unsigned k=0;k<128;++k){ids.push_back("capacity"+std::to_string(k));r.configureNativeGroup(ids.back(),target,std::span(&leaf,1));outputs.push_back(r.nativeGroupOutput(ids.back()));}r.configureNativeGroup("capacity-parent",target,outputs);auto capacity=r.nativeGroupOutput("capacity-parent");r.setDrawList(std::span(&capacity,1));r.draw(false);check(r.stats().textures==129,"All128source markers fit the bounded group roster");r.clearDrawList();check(r.removeNativeGroup("capacity-parent"),"Capacity parent detaches first");for(const auto&id:ids)check(r.removeNativeGroup(id),"Capacity marker retires");check(r.removeMesh("capacity-quad")&&r.stats().textures==0&&r.stats().meshes==0,"Capacity exercise leaves no GPU resources");std::cout<<"Source nested marker maximum residual "<<maximum<<"/255\n";}
}
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==3,"Pass HLSL and actual source marker fixture");Window w;n::Renderer r;r.initialize(w.h,8,8,{n::Driver::warpForTests,argv[1],n::RenderTarget::offscreenForTests});test(r,argv[2]);r.reset();CoUninitialize();std::cout<<"PASS "<<checks<<" Map group checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
