#include "core/data/map_store.hpp"
#include "core/data/file_io.hpp"
#include <algorithm>
#include <fstream>
#include <iostream>
#include <limits>

namespace d=ehud::data;namespace m=endfield::modules;using J=d::Json;
namespace {
unsigned checks{};void check(bool value,const char*message){++checks;if(!value)throw std::runtime_error(message);}
template<class F>void rejects(F f,const char*message){bool rejected{};try{f();}catch(const std::exception&){rejected=true;}check(rejected,message);}
struct Temporary {std::filesystem::path root=std::filesystem::canonical(std::filesystem::temp_directory_path())/("Endfield-map-store-fixture-"+d::makeUUID());~Temporary(){std::error_code error;std::filesystem::remove_all(root,error);}std::filesystem::path file()const{return root/"WorldMap"/"map.json";}};
void write(const std::filesystem::path&p,std::string_view bytes){std::filesystem::create_directories(p.parent_path());std::ofstream stream(p,std::ios::binary|std::ios::trunc);stream.write(bytes.data(),static_cast<std::streamsize>(bytes.size()));check(bool(stream),"Write only explicit temporary fixture");}
std::string read(const std::filesystem::path&p){auto bytes=d::detail::readFile(p,2*d::MapStore::maximumArchiveBytes);check(bytes.has_value(),"Read only owned synthetic map");return *bytes;}
std::string id(unsigned value){const auto suffix=std::to_string(value);return "00000000-0000-0000-0000-"+std::string(12-suffix.size(),'0')+suffix;}
m::MapSnapshot snapshot(){m::MapSnapshot s;s.pins={{"AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE",.25,.75,-12345.125,m::MapPinStyle::player},{id(2),0,1,800000000.00001,m::MapPinStyle::green}};return s;}
void basic(){Temporary t;d::MapStore store(t.root);check(store.path()==t.file()&&store.value()==m::MapSnapshot{}&&!std::filesystem::exists(t.root),"Missing archive loads original3xShenzhen default without creating a file");check(!store.replace(store.value())&&!std::filesystem::exists(t.root),"Equal initial snapshot does no IO");auto s=snapshot();check(store.replace(s)&&store.value()==s,"Successful atomic replacement publishes full source snapshot");const auto bytes=read(t.file());const auto raw=J::parse(bytes);check(raw["version"].integer()==4&&raw["pins"].array().size()==2,"Version4 stores metadata only");check(raw["pins"].array()[0]["createdAt"].number()==-12345.125&&raw["pins"].array()[0]["style"].string()=="player","Foundation epoch and exact source style survive");check(d::MapStore(t.root).value()==s,"Saved source envelope reloads exactly");check(!store.replace(s)&&read(t.file())==bytes,"Equal saved value does not rewrite exact bytes");
    write(t.file(),"external fixture");auto changed=s;changed.viewport.zoom=4;rejects([&]{store.replace(changed);},"External byte changes reject instead of clobbering");check(store.value()==s&&read(t.file())=="external fixture","Failed transaction preserves model and external bytes");write(t.file(),bytes);check(store.replace(changed)&&store.value()==changed,"Explicit restored expectation permits later commit");
    auto invalid=changed;invalid.pins[0].x=std::numeric_limits<double>::quiet_NaN();const auto valid=read(t.file());rejects([&]{store.replace(invalid);},"Nonfinite metadata never reaches file writer");check(store.value()==changed&&read(t.file())==valid,"Invalid replacement retains published snapshot and bytes");rejects([&]{d::MapStore relative("relative");},"No implicit real application directory");}
void additive(){Temporary t;auto raw=J::parse(d::encodeMapArchive(snapshot()));raw["futureRoot"]=J::Object{{"exact",J::parse("9007199254740993")},{"nested",J::Array{true,"opaque"}}};raw["viewport"]["futureCamera"]="keep";auto rows=raw["pins"].array();rows[0]["id"]="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";rows[0]["futurePin"]=J::Object{{"token",J::parse("1.230000000000000000001")}};rows[0]["createdAt"]=J::parse("-12345.125000");raw["pins"]=std::move(rows);const auto original=raw.encode();write(t.file(),original);d::MapStore store(t.root);check(read(t.file())==original&&store.value().pins[0].id=="AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE","Version4 load canonicalizes UUID without rewriting original bytes");auto s=store.value();std::reverse(s.pins.begin(),s.pins.end());s.viewport.zoom=5;check(store.replace(s),"Reordered pins save through same transactional store");const auto saved=J::parse(read(t.file()));check(saved["futureRoot"]==raw["futureRoot"]&&saved["viewport"]["futureCamera"]==raw["viewport"]["futureCamera"],"Unknown root and viewport values survive exactly");check(saved["pins"].array()[1]["futurePin"]==raw["pins"].array()[0]["futurePin"],"Unknown pin payload follows stable UUID rather than row position");check(saved["pins"].array()[1]["createdAt"].encode()=="-12345.125000","Unchanged known Date token does not lose imported precision spelling");s.pins.erase(s.pins.begin()+1);store.replace(s);check(J::parse(read(t.file()))["pins"].array().size()==1,"Explicit removal deletes only that pin and its attached unknown payload");}
void migrations(){for(unsigned version=1;version<=4;++version){Temporary t;auto raw=J::parse(d::encodeMapArchive(snapshot()));raw["version"]=int(version);raw["viewport"]["zoom"]=version==1?16:version==2?24:72;raw["future"]="retained";auto rows=raw["pins"].array();rows[0].erase("style");raw["pins"]=std::move(rows);write(t.file(),raw.encode());d::MapStore store(t.root);const auto expectedZoom=version<4?3:72;check(store.value().viewport.zoom==expectedZoom&&store.value().pins[0].style==m::MapPinStyle::yellow,"Source old-default migration and additive missing-style fallback");const auto saved=J::parse(read(t.file()));check(saved["version"].integer()==4&&saved["future"].string()=="retained","Migration writes version4 once and preserves unknown fields");const auto bytes=read(t.file());d::MapStore again(t.root);check(read(t.file())==bytes&&again.value()==store.value(),"Second open performs no migration rewrite");}
    for(unsigned version:{2u,3u}){Temporary t;auto raw=J::parse(d::encodeMapArchive(snapshot()));raw["version"]=int(version);raw["viewport"]["centerX"]=.2;raw["viewport"]["zoom"]=version==2?24:72;write(t.file(),raw.encode());d::MapStore store(t.root);check(store.value().viewport.centerX==.2&&store.value().viewport.zoom==(version==2?24:72),"Customized older camera remains intact");}}
void invalid(){auto valid=J::parse(d::encodeMapArchive(snapshot()));std::vector<std::string>cases{"broken",std::string(d::MapStore::maximumArchiveBytes+1,' ')};auto add=[&](J j){cases.push_back(j.encode(2*d::MapStore::maximumArchiveBytes));};for(auto version:{0,5}){auto j=valid;j["version"]=version;add(j);}auto j=valid;j["viewport"]["centerX"]=1.;add(j);j=valid;j["viewport"]["zoom"]=2.;add(j);j=valid;j["version"]=1;j["viewport"]["zoom"]=17.;add(j);j=valid;j["version"]=3.5;add(j);
    for(const auto key:{"id","x","y","createdAt"}){j=valid;auto rows=j["pins"].array();rows[0].erase(key);j["pins"]=std::move(rows);add(j);}for(const auto key:{"unknown","YELLOW"}){j=valid;auto rows=j["pins"].array();rows[0]["style"]=key;j["pins"]=std::move(rows);add(j);}j=valid;auto rows=j["pins"].array();auto duplicate=rows[0];duplicate["id"]="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";rows.push_back(duplicate);j["pins"]=std::move(rows);add(j);
    j=valid;rows.clear();for(unsigned n=0;n<129;++n){auto row=valid["pins"].array()[0];row["id"]=id(n);rows.push_back(std::move(row));}j["pins"]=std::move(rows);add(j);
    for(const auto&bytes:cases){Temporary t;write(t.file(),bytes);rejects([&]{d::MapStore store(t.root);},"Malformed/newer/oversized archive cannot enable overwrite");check(read(t.file())==bytes,"Rejected source archive is preserved byte-for-byte");}
    Temporary folder;std::filesystem::create_directories(folder.file());rejects([&]{d::MapStore store(folder.root);},"A directory cannot be treated as a map archive");
    auto large=valid;large["opaque"]=std::string(d::MapStore::maximumArchiveBytes,'x');rejects([&]{d::encodeMapArchive(snapshot(),large);},"Unknown preservation cannot bypass original256KiB output cap");
}
void sourceOracle(const std::filesystem::path&p){const auto bytes=d::detail::readFile(p,128*1024);check(bytes.has_value(),"Read compact original Swift archive fixture");const auto rows=J::parse(*bytes,128*1024)["cases"].array();for(const auto&row:rows){bool accepted{};std::optional<d::MapArchive>actual;try{actual=d::decodeMapArchive(row["input"].string());accepted=true;}catch(const std::exception&){}check(accepted==row["accepted"].boolean(),"Original Foundation archive acceptance matches");if(actual){const auto expected=d::decodeMapArchive(row["snapshot"].string());check(actual->snapshot==expected.snapshot,"Original source migrations/pins/Foundation dates match exactly");}}}
}
int main(int argc,char**argv){try{basic();additive();migrations();invalid();if(argc==2)sourceOracle(std::filesystem::absolute(argv[1]));std::cout<<"PASS "<<checks<<" Map archive checks; temporary fixtures only\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
