#include "modules/map_geography.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iostream>
#include <limits>
#include <stdexcept>

namespace m=endfield::modules;using P=endfield::core::Point;using R=endfield::core::Rect;
namespace {
unsigned checks{};
void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}
template<class F>void rejects(F&&f,const char*why){bool failed{};try{f();}catch(const std::invalid_argument&){failed=true;}check(failed,why);}
bool closeEnough(double a,double b){return std::abs(a-b)<=1e-11*std::max({1.,std::abs(a),std::abs(b)});}
using Bytes=std::vector<std::uint8_t>;
void u16(Bytes&b,unsigned n){b.push_back(n&255);b.push_back((n>>8)&255);}
void u32(Bytes&b,std::uint32_t n){u16(b,n&65535);u16(b,n>>16);}
void write32(Bytes&b,std::size_t at,std::uint32_t n){for(unsigned i=0;i<4;++i)b.at(at+i)=std::uint8_t(n>>(8*i));}
Bytes header(const char*magic,unsigned count){Bytes b(magic,magic+8);u32(b,count);return b;}
Bytes terrain(){auto b=header("EHUDMAP1",1);u32(b,std::uint32_t(-4000));u32(b,1);u32(b,0);b.push_back(0);u32(b,2);u16(b,0);u16(b,0);u16(b,65535);u16(b,65535);return b;}
void country(Bytes&b,std::string_view id="SYN",std::string_view name="Synthetic"){b.push_back(std::uint8_t(id.size()));b.insert(b.end(),id.begin(),id.end());u16(b,unsigned(name.size()));b.insert(b.end(),name.begin(),name.end());u32(b,1);u32(b,1);u32(b,4);for(auto[x,y]:std::array<std::pair<unsigned,unsigned>,4>{{{0,0},{16777215,0},{16777215,16777215},{0,16777215}}}){u32(b,x);u32(b,y);}}
Bytes countries(std::string_view id="SYN",std::string_view name="Synthetic"){auto b=header("EHUDCTY1",1);country(b,id,name);return b;}
Bytes read(const char*path){std::ifstream f(path,std::ios::binary);check(bool(f),"Explicit bundled archive opens");return Bytes(std::istreambuf_iterator<char>(f),{});}
void decode(){const auto t=terrain();auto a=m::MapTerrain::decode(t);check(a.bands.size()==1&&a.vertexCount==2&&a.bands[0].elevation==-4000&&!a.bands[0].fillPath,"Terrain signed elevation and absent fill preserved");check(a.bands[0].contourPath[0].points==std::vector<P>{{0,0},{1024,512}}&&!a.bands[0].contourPath[0].closed,"Terrain quantization and open path preserved");
    const auto c=countries();auto b=m::MapCountries::decode(c);check(b.countries.size()==1&&b.vertexCount==4&&b.countries[0].id=="SYN"&&b.countries[0].name=="Synthetic","Country metadata preserved");check(b.countries[0].bounds==R{0,0,1024,512}&&b.countries[0].components.size()==1&&b.countries[0].path[0].closed,"Country closed ring and world bounds preserved");
    for(std::size_t n=0;n<t.size();++n)rejects([&]{m::MapTerrain::decode(std::span(t).first(n));},"Every truncated terrain prefix rejects");for(std::size_t n=0;n<c.size();++n)rejects([&]{m::MapCountries::decode(std::span(c).first(n));},"Every truncated country prefix rejects");
    for(const auto count:{0u,33u,UINT32_MAX}){auto bad=t;write32(bad,8,count);rejects([&]{m::MapTerrain::decode(bad);},"Terrain band bound rejects before allocation");}for(const auto count:{0u,513u,UINT32_MAX}){auto bad=c;write32(bad,8,count);rejects([&]{m::MapCountries::decode(bad);},"Country count bound rejects before allocation");}
    for(const auto elevation:{12001u,std::uint32_t(-12001)}){auto bad=t;write32(bad,12,elevation);rejects([&]{m::MapTerrain::decode(bad);},"Elevation source range enforced");}
    for(const auto at:{16u,20u}){auto bad=t;write32(bad,at,20001);rejects([&]{m::MapTerrain::decode(bad);},"Terrain per-band path cap enforced");}
    for(const auto points:{0u,1u,150001u,UINT32_MAX}){auto bad=t;write32(bad,25,points);rejects([&]{m::MapTerrain::decode(bad);},"Terrain point count rejects before reservation");}
    auto bad=t;bad[24]=2;rejects([&]{m::MapTerrain::decode(bad);},"Unknown terrain close flag rejects");bad=t;bad.push_back(0);rejects([&]{m::MapTerrain::decode(bad);},"Trailing terrain bytes reject");bad=c;bad.push_back(0);rejects([&]{m::MapCountries::decode(bad);},"Trailing country bytes reject");bad=c;bad[0]='X';rejects([&]{m::MapCountries::decode(bad);},"Wrong archive magic rejects");
    for(const auto id:{"","lower","A B","ABCDEFGHIJKLM"})rejects([&]{m::MapCountries::decode(countries(id));},"Invalid country identity rejected");auto duplicate=header("EHUDCTY1",2);country(duplicate);country(duplicate);rejects([&]{m::MapCountries::decode(duplicate);},"Duplicate country identity rejects");
    for(const std::string&name:{std::string{},std::string(129,'A'),std::string("  "),std::string("A\0B",3),std::string("A\nB"),std::string("\xc0\xaf"),std::string("\xed\xa0\x80"),std::string("\xf4\x90\x80\x80"),std::string("\xe2\x80\x8b"),std::string("\xc2\xa0"),std::string("A\xe2\x80\xae"),std::string("\xf3\xa0\x84\x81")})rejects([&]{m::MapCountries::decode(countries("SYN",name));},"Source UTF8/control/blank country string checks enforced");
    check(m::MapCountries::decode(countries("SYN","\xc3\x85land")).countries[0].name=="\xc3\x85land","Non-ASCII source country name is lossless");
    const std::size_t componentAt=12+1+3+2+9;for(const auto n:{0u,8193u,UINT32_MAX}){bad=c;write32(bad,componentAt,n);rejects([&]{m::MapCountries::decode(bad);},"Country component bounds enforced");}for(const auto n:{0u,1025u,UINT32_MAX}){bad=c;write32(bad,componentAt+4,n);rejects([&]{m::MapCountries::decode(bad);},"Country ring bounds enforced");}for(const auto n:{0u,2u,100001u,UINT32_MAX}){bad=c;write32(bad,componentAt+8,n);rejects([&]{m::MapCountries::decode(bad);},"Country vertex bounds enforced");}
    bad=c;write32(bad,componentAt+12,16777216);rejects([&]{m::MapCountries::decode(bad);},"Out-of-range24-bit coordinate rejects");bad=c;for(unsigned k=0;k<4;++k)write32(bad,componentAt+12+k*8,0);rejects([&]{m::MapCountries::decode(bad);},"Zero-width component rejects like source boundingBoxOfPath");
    bad.assign(m::MapTerrain::maximumBytes+1,0);rejects([&]{m::MapTerrain::decode(bad);},"Terrain maximum byte size checked");bad.assign(m::MapCountries::maximumBytes+1,0);rejects([&]{m::MapCountries::decode(bad);},"Country maximum byte size checked");
}
m::MapRing ring(std::initializer_list<P>points,bool closed=true){return {points,closed,{}};}
void geometry(){m::MapPath square{ring({{0,0},{10,0},{10,10},{0,10}})},hole=square;hole.push_back(ring({{3,3},{7,3},{7,7},{3,7}}));
    check(m::mapEvenOddContains(hole,{2,5})&&!m::mapEvenOddContains(hole,{5,5}),"Even-odd holes preserve interior exclusion");for(const auto p:{P{0,5},P{10,5},P{5,0},P{5,10},P{3,5},P{7,5}})check(m::mapEvenOddContains(hole,p),"Boundary inclusion matches original CoreGraphics probe");check(!m::mapEvenOddContains(hole,{NAN,5}),"Nonfinite hit rejects");
    m::MapPathGeometry indexed(hole);const auto clipped=indexed.clippedPolygon({1,1,8,8},0);check(clipped.fillPath.size()==2&&clipped.linePath.size()==1,"Clipped outer face invents fill sides but no coastline edges");check(clipped.fillPath[0].bounds==R{1,1,8,8}&&!m::mapEvenOddContains(clipped.fillPath,{5,5}),"Clipped outer geometry preserves hole");check(clipped.linePath[0].bounds==R{3,3,4,4}&&!clipped.linePath[0].closed,"Only original interior ring remains in line path");
    const auto narrow=indexed.clippedPolygon({4,-1,2,12},0);check(narrow.fillPath.size()==2&&narrow.linePath.size()==4,"Through-cut separates original edges from generated rectangle sides");for(const auto&r:narrow.linePath)check(r.points.size()==2&&r.points[0].y==r.points[1].y,"Through-cut strokes retain horizontal geographic segments only");
    m::MapPathGeometry line({ring({{-10,5},{20,5}},false)});const auto cut=line.clippedLines({0,0,10,10},0);check(cut.size()==1&&cut[0].points.size()==2&&closeEnough(cut[0].points[0].x,0)&&closeEnough(cut[0].points[1].x,10)&&closeEnough(cut[0].points[0].y,5)&&closeEnough(cut[0].points[1].y,5),"Horizontal zero-height chunk survives inclusive intersection and segment clipping");check(line.clippedPolygon({0,0,10,10},0).fillPath.empty(),"Open contours never become filled geography");
    m::MapRing longLine;for(unsigned k=0;k<200;++k)longLine.points.push_back({double(k),double(k%2)*.01});m::MapPathGeometry chunked({longLine});auto run=chunked.clippedLines({63,-1,3,3},0);check(run.size()==1&&run[0].points.front().x==63&&run[0].points.back().x==66,"Adjacent64-segment chunks keep contiguous geographic run");check(chunked.clippedLines({0,-1,199,3},.1)[0].points.size()==2,"Open run Douglas-Peucker removes only sub-tolerance vertices");
    for(auto&p:longLine.points)p.y*=5;m::MapPathGeometry ties({longLine});const auto tied=ties.clippedLines({-2,-2,15,15},.035);check(tied.size()==1&&tied[0].points.size()==12&&tied[0].points[8].x==8,"Original sequential CGFloat arithmetic preserves Douglas-Peucker tie winner");
    m::MapRing island;island.closed=true;for(unsigned k=0;k<64;++k){const double a=double(k)*6.283185307179586/64;island.points.push_back({5+4*std::cos(a),5+.02*std::sin(a)});}m::MapPathGeometry closed({island});const auto tiny=closed.clippedPolygon({0,0,10,10},100);check(tiny.fillPath.size()==1&&tiny.fillPath[0].points.size()==64,"Degenerate simplified narrow island falls back to original ring");
    closed.clippedPolygon({0,0,10,10},.1);check(closed.cachedLevels()==2,"Only two exact tolerance levels retained");closed.clippedPolygon({0,0,10,10},100);closed.clippedPolygon({0,0,10,10},.2);check(closed.cachedLevels()==2,"Third zoom bucket evicts least-recently-used level");
    rejects([&]{indexed.clippedLines({0,0,INFINITY,1},0);},"Invalid viewport cannot enter clipping arithmetic");rejects([&]{indexed.clippedPolygon({0,0,1,1},NAN);},"Invalid tolerance cannot populate cache");rejects([&]{m::MapPathGeometry invalid({ring({{0,0},{NAN,1}})});},"Nonfinite synthetic geometry rejects");
}
void actual(const char*terrainPath,const char*countryPath){const auto terrainBytes=read(terrainPath),countryBytes=read(countryPath);check(terrainBytes.size()==601709&&countryBytes.size()==821219,"Original bundled byte counts unchanged");const auto terrain=m::MapTerrain::decode(terrainBytes);const auto countries=m::MapCountries::decode(countryBytes);check(terrain.bands.size()==12&&terrain.vertexCount==142392,"Original terrain bands/vertices match source manifest");check(countries.countries.size()==255&&countries.vertexCount==97707,"Original countries/vertices match source manifest");
    const std::array<int,12>elevations{-4000,-2000,0,250,500,1000,1500,2000,3000,4000,5000,6000};const std::array<std::size_t,12>lines{1355,437,261,541,562,411,263,163,40,30,32,0},fills{0,0,261,541,561,411,263,163,40,30,32,0};std::size_t vertices{};bool coordinatesValid=true;
    for(std::size_t k=0;k<terrain.bands.size();++k){const auto&b=terrain.bands[k];check(b.elevation==elevations[k]&&b.contourPath.size()==lines[k]&&(b.fillPath?b.fillPath->size():0)==fills[k],"Every terrain source band/path count matches");for(const auto&path:{&b.contourPath,b.fillPath?&*b.fillPath:nullptr})if(path)for(const auto&r:*path){vertices+=r.points.size();for(auto p:r.points)coordinatesValid&=p.x>=0&&p.x<=1024&&p.y>=0&&p.y<=512;}}
    check(vertices==terrain.vertexCount&&coordinatesValid,"All terrain coordinates remain bounded and vertex count includes every contour/fill");vertices=0;bool hierarchyValid=true;const m::MapCountry*china{};for(const auto&country:countries.countries){if(country.id=="CHN")china=&country;for(const auto&component:country.components){hierarchyValid&=component.bounds.width>0&&component.bounds.height>0;for(const auto&r:component.path){hierarchyValid&=r.closed&&r.points.size()>=3;vertices+=r.points.size();}}}
    check(vertices==countries.vertexCount&&china&&hierarchyValid,"Original country hierarchy preserves every closed ring and component bounds");check(m::mapEvenOddContains(china->path,{(114.0579+180)/360*1024,(90-22.5431)/180*512}),"Original Shenzhen center lies in retained China geometry");
    m::MapPathGeometry coast(terrain.bands[2].contourPath);const auto local=coast.clippedLines({830,180,24,24},.035);bool clippedInside=true;for(const auto&r:local)for(auto p:r.points)clippedInside&=p.x>=830-1e-10&&p.x<=854+1e-10&&p.y>=180-1e-10&&p.y<=204+1e-10;check(clippedInside,"Every actual coast vertex stays bounded to requested viewport");
}
}
int main(int argc,char**argv){try{check(argc==3,"Pass original Terrain.bin and Countries.bin");decode();geometry();actual(argv[1],argv[2]);std::cout<<"PASS "<<checks<<" map geography checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
