#ifdef _WIN32
#include "tools/map_preview.hpp"
#include "modules/map_geography.hpp"
#include "native/module_scene.hpp"
#include <windows.h>
#include <objbase.h>
#include <atomic>
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <new>

namespace{std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}
void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {
namespace c=endfield::core;namespace m=endfield::modules;namespace n=endfield::native;namespace a=endfield::app;namespace t=endfield::tools;using J=ehud::data::Json;
unsigned checks{};void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(s);}
template<class F>void rejects(F f,const char*s){bool rejected{};try{f();}catch(const std::exception&){rejected=true;}check(rejected,s);}
struct Window{HWND hwnd{};Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"OwnedMapOwnerFixture";check(RegisterClassW(&c)!=0,"Register isolated Map fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,c.lpszClassName,L"Synthetic Map",WS_POPUP,0,0,1280,800,nullptr,nullptr,c.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Map fixture never shows or activates a window");}~Window(){if(hwnd)DestroyWindow(hwnd);UnregisterClassW(L"OwnedMapOwnerFixture",GetModuleHandleW(nullptr));}};
J blank(){return J::Object{{"bounds",J::Array{0,0,440,440}},{"position",J::Array{0,0}},{"anchorPoint",J::Array{0,0}},{"children",J::Array{}}};}
std::shared_ptr<const n::MapPaintImage>image(unsigned size){auto p=std::make_shared<n::MapPaintImage>();p->width=p->height=size;p->straightRGBA.assign(std::size_t(size)*size*4,255);return p;}
std::shared_ptr<const m::MapGeography>geography(){auto p=std::make_shared<m::MapGeography>();p->terrain=m::MapTerrain{};return p;}
n::MapPaintResult paint(const n::MapPaintRequest&q,const n::MapPaintCancelled&cancel){if(cancel())return {};const auto g=*m::mapRasterGeometry(q.viewport,q.contentsScale);auto pixels=std::make_shared<n::MapPaintImage>();pixels->width=pixels->height=g.pixelDimension;pixels->straightRGBA.assign(std::size_t(g.pixelDimension)*g.pixelDimension*4,127);n::MapPaintResult result{pixels,{},m::MapRasterFrame{g.viewport,g.screenRect,g.pixelsPerPoint},.001};if(q.backdrop){auto b=std::make_shared<n::MapPaintImage>();b->width=1024;b->height=512;b->straightRGBA.assign(1024*512*4,96);result.backdrop=b;}return result;}
void reentry(){
    n::LayerRasterizer raster;a::UtilityExecutor utility([]{});double now{};bool armed{},destroy{};std::unique_ptr<t::MapPreview>owner;
    const auto options=[&]{t::MapPreviewOptions o;o.geography=geography();o.clock=[&]{return now;};o.paint=paint;o.raster.pixelsPerPoint=1;o.player={image(2),image(2),image(2),image(880)};o.appearance.ambient=false;o.changed=[&]{if(!armed)return;armed=false;if(destroy)owner.reset();else owner->setOverlayVisible(false,now);};return o;};
    owner=std::make_unique<t::MapPreview>(raster,utility,options());owner->resize({1280,800,96,1,1280,800});c::ModulePresentation modules(c::Module::map);c::source::DesktopChromeSettings settings{{0,0,1280,800},1,{},c::Module::map,true};const auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;
    armed=true;owner->update(center,settings,modules.sample(now).presentation,1,now);check(!owner->state().active()&&!owner->rasterStats().active&&!owner->nextWakeTime()&&utility.stats().accepted==0,"Reentrant hide supersedes stale outer activation before any terrain task");
    now+=.1;owner->update(center,settings,modules.sample(now).presentation,1,now);check(!owner->state().active()&&!owner->rasterStats().active,"Following source presentation cannot reopen a caller-hidden owner");owner.reset();
    owner=std::make_unique<t::MapPreview>(raster,utility,options());auto appearance=n::MapAppearance{};appearance.dark=false;armed=true;destroy=true;check(owner->setAppearance(appearance,now)&&!owner,"Appearance invalidation may destroy owner without continuing on retired state");utility.waitIdle();utility.drain();utility.shutdown();
}
void run(n::Renderer&r){
    n::LayerRasterizer raster;a::UtilityExecutor utility([]{});double now{};unsigned saves{},changes{},styles{},recenters{},nextID{1};std::atomic<unsigned>paints{},clears{};m::MapSnapshot saved;
    t::MapPreviewOptions options;options.geography=geography();options.clock=[&]{return now;};options.changed=[&]{++changes;};options.pinStyleChanged=[&](auto){++styles;};options.recentered=[&]{++recenters;};options.paint=[&](const auto&q,const auto&cancel){++paints;return paint(q,cancel);};options.releaseWorkerCaches=[&]{++clears;};options.raster.pixelsPerPoint=1;options.appearance.ambient=false;options.player={image(2),image(2),image(2),image(880)};options.persistence={ [&](const auto&s){saved=s;++saves;},[&]{return std::string("00000000-0000-0000-0000-")+std::string(11,'0')+char('0'+nextID++);},[]{return 1.;}};
    t::MapPreview owner(raster,utility,std::move(options));owner.resize({1280,800,96,1,1280,800});n::LayerComposition composition;c::ModulePresentation modules{c::Module::power};n::LayerScene geometry(raster);geometry.load(blank(),{});n::NativeModuleSurface plane(geometry,c::Module::map);c::source::DesktopChromeSettings settings{{0,0,1280,800},1,{},c::Module::power,true};auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;const auto camera=n::layerViewportProjection(1280,800);bool released{};
    struct Cleanup{n::Renderer&r;n::LayerComposition&c;t::MapPreview&o;bool&done;~Cleanup(){if(done)return;try{c.detach(r);o.release(r);}catch(...){r.reset();}}}cleanup{r,composition,owner,released};
    const auto frame=[&](double dt=.01){now+=dt;const auto sample=modules.sample(now).presentation;settings.module=sample.requested;owner.update(center,settings,sample,1,now);owner.upload(r);composition.setEntries(r,owner.entries());composition.present(r);r.setCamera(camera);};
    const auto point=[&](c::Point p){const auto sample=modules.sample(now).presentation;const auto*shown=sample.current.module==c::Module::map?&sample.current:&*sample.incoming;plane.update(center,settings,*shown);return *c::Projection::viewport(camera*plane.pose().contentWorld,1280,800).project(p);};
    const auto drain=[&]{utility.waitIdle();utility.drain();owner.utilityCompleted(now);};
    const auto settle=[&]{for(unsigned k=0;k<16;++k){drain();if(const auto due=owner.nextWakeTime()){now=std::max(now,*due)+.000001;owner.deadline(now);continue;}if(!utility.stats().running&&!utility.stats().pending&&!utility.stats().completed)break;}frame(.21);};
    const auto press=[&](c::Point p,a::PointerButton b=a::PointerButton::left){const auto q=point(p);return owner.pointer({a::PointerKind::down,b,q.x,q.y},now);};
    const auto release=[&](c::Point p){const auto q=point(p);return owner.pointer({a::PointerKind::up,a::PointerButton::left,q.x,q.y},now);};
    frame();check(owner.entries().empty()&&utility.stats().accepted==0&&!owner.nextWakeTime(),"Hidden initial Map does no worker, raster or deadline work");
    modules.select(c::Module::map,now);frame(.02);check(owner.rasterStats().active&&!owner.state().active(),"Incoming Map prepares source terrain before input and pin pulses activate");check(!owner.covers(point({220,220}))&&!press({220,220}),"Mechanical module transition rejects Map input");drain();frame(1);settle();check(owner.state().active()&&owner.rasterStats().published==1,"Stable Map activates and retains one prepared geography frame");check(owner.covers(point({220,5}))&&!owner.covers(point({2,2})),"Map uses original440-point circle, not the standard334-point central clip");
    r.draw(false);check(!r.readback().pixels.empty(),"Shared composition renders synthetic Map without a new window or renderer");
    const auto accepted=utility.stats().accepted;const auto notices=changes;const auto text=raster.stats();const auto gpu=r.stats();allocations=0;counting=true;try{for(unsigned k=0;k<120;++k)frame(1./60.);}catch(...){counting=false;throw;}counting=false;
    check(allocations==0,"Warm Map owner frames allocate nothing");check(utility.stats().accepted==accepted&&changes==notices&&raster.stats().rasterizations==text.rasterizations&&r.stats().textureUploads==gpu.textureUploads,"Stable Map frames schedule, notify and repaint nothing");
    const auto firstZoom=owner.state().viewport().zoom;check(press({37,195})&&!owner.pointerLocked(),"Toolbar press reaches source control without freezing gyro as a drag");check(release({37,195}),"Toolbar release is owned");check(owner.state().viewport().zoom>firstZoom&&owner.requiresFrames(now),"Zoom action starts original finite camera motion");settle();
    const auto beforeDrag=saves;check(press({260,250})&&owner.pointerLocked(),"Terrain press begins exact Map drag lock");auto outside=point({490,270});check(owner.pointer({a::PointerKind::move,a::PointerButton::none,outside.x,outside.y},now),"An owned Map drag continues outside the circular hit boundary");check(saves==beforeDrag,"Pointer samples never persist camera");check(release({490,270})&&!owner.pointerLocked()&&saves==beforeDrag+1,"Mouse-up persists changed camera exactly once");settle();check(saved.viewport==owner.state().viewport(),"Committed camera matches final drag pose");
    const auto beforeCancel=owner.state().viewport();const auto savedBeforeCancel=saves;check(press({270,270}),"Synthetic cancellation begins inside Map");owner.cancelInteraction(now);check(owner.state().viewport()==beforeCancel&&saves==savedBeforeCancel&&!owner.pointerLocked(),"Cancelled untouched click does not recenter or persist");
    const auto zoom=owner.state().viewport().zoom;check(press({270,260})&&release({270,260}),"Clicking terrain is owned");check(recenters==1&&owner.state().viewport().zoom==zoom,"Source recenter preserves zoom and emits one event");settle();
    check(owner.perform(m::MapAction::addPin,{},now),"Source center-pin action is available");frame();check(owner.state().pins().size()==1&&owner.state().selection(),"Pin edit preserves retained state and selection");const auto id=owner.state().pins()[0].id;check(owner.perform(m::MapAction::pin,id,now),"Source pin cycles style");frame();check(styles==1&&owner.state().pins()[0].style==m::MapPinStyle::green,"Style event publishes only after successful injected persistence");frame(.17);
    const auto beforeWheel=owner.state().viewport();const auto wheelSaves=saves;const auto q=point({300,220});check(owner.wheel({q.x,q.y,.5,false,0,99},now)&&owner.pointerLocked(),"Fractional detent zoom uses source gesture lock, independent of OS text lines");const auto expected=m::mapZoomed(beforeWheel,{300,220},std::exp(.5*.12));check(std::abs(owner.state().viewport().zoom-expected.zoom)<1e-12&&saves==wheelSaves,"Wheel retains fractional source exponential sensitivity without per-sample saves");check(owner.nextWakeTime().has_value(),"Wheel end/refinement uses existing shared deadline");now+=.181;owner.deadline(now);check(!owner.pointerLocked()&&saves==wheelSaves+1,"Source180ms wheel completion saves once and releases lock");settle();
    center=center*c::Matrix4::rotation(.04,-.07,0);frame();check(owner.covers(point({220,5})),"Tilted Map uses its current exact source plane for hits");const auto v=owner.state().viewport();const auto selected=owner.state().selection();owner.setLanguage(c::Language::korean,now);frame();check(owner.state().viewport()==v&&owner.state().selection()==selected&&owner.state().pins().size()==1,"Locale replacement preserves camera, pins and selection");settle();const auto locale=raster.stats();owner.setLanguage(c::Language::korean,now);frame();check(raster.stats().rasterizations==locale.rasterizations,"Equal locale event shapes no text");
    auto appearance=n::MapAppearance{};appearance.dark=false;appearance.ambient=false;appearance.accent={.2,.5,.8,1};appearance.strings={"지도","지형 불러오는 중","핀"};check(owner.setAppearance(appearance,now),"Global theme/accent event is accepted");settle();check(owner.state().viewport()==v&&owner.state().selection()==selected,"Appearance keeps original durable Map identity");check(owner.key({a::KeyKind::down,VK_ESCAPE},now),"Map consumes first Escape to clear selection");check(!owner.key({a::KeyKind::down,VK_ESCAPE},now),"Unselected Map leaves Escape for the shared HUD");
    check(press({280,270}),"Begin source gesture before closing");const auto dragged=point({300,270});owner.pointer({a::PointerKind::move,a::PointerButton::none,dragged.x,dragged.y},now);const auto closeSaves=saves;owner.setOverlayVisible(false,now);check(saves==closeSaves+1&&!owner.pointerLocked()&&!owner.state().active()&&!owner.rasterStats().active&&!owner.nextWakeTime(),"Closing commits changed gesture, cancels refinement and disables interaction");frame();drain();check(!owner.requiresFrames(now)&&!owner.covers(point({220,220})),"Closed HUD retains outgoing pixels without Map frame demand or hits");const auto hiddenAccepted=utility.stats().accepted;for(unsigned k=0;k<20;++k)frame();check(utility.stats().accepted==hiddenAccepted,"Closed pose frames do not paint geography");
    owner.setOverlayVisible(true,now);frame();settle();check(owner.state().active()&&owner.covers(point({220,220})),"Reopen reuses one retained Map owner and current camera");modules.select(c::Module::power,now);frame(.02);check(!owner.state().active()&&!owner.rasterStats().active&&!owner.entries().empty(),"Outgoing module preserves artwork and immediately disables source interaction");frame(1);drain();check(owner.entries().empty()&&!owner.requiresFrames(now),"Departed Map detaches from combined composition");
    rejects([&]{owner.deadline(std::numeric_limits<double>::quiet_NaN());},"Nonfinite owner time is rejected");composition.detach(r);owner.release(r);released=true;check(r.stats().textures==0&&r.stats().meshes==0,"Map owner releases all local resources after shared detach");check(clears>0,"Hidden Map releases working caches on the existing utility worker");utility.shutdown();
}
}
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==2,"Pass original HUD shader");reentry();Window window;n::Renderer renderer;renderer.initialize(window.hwnd,1280,800,{n::Driver::warpForTests,argv[1],n::RenderTarget::offscreenForTests});run(renderer);renderer.reset();CoUninitialize();std::cout<<"PASS "<<checks<<" Map owner checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
