#include "modules/map_state.hpp"
#include "core/data/json.hpp"
#include <algorithm>
#include <atomic>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <limits>
#include <new>
#include <stdexcept>

namespace {std::atomic<std::uint64_t>allocations{};}
void*operator new(std::size_t n){allocations.fetch_add(1,std::memory_order_relaxed);if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}
void operator delete(void*p)noexcept{std::free(p);}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete[](void*p)noexcept{::operator delete(p);}
#ifdef __cpp_sized_deallocation
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace m=endfield::modules;namespace c=endfield::core;using J=ehud::data::Json;
namespace {
unsigned checks{};
void check(bool value,const char*message){++checks;if(!value)throw std::runtime_error(message);}
template<class F>void rejects(F&&f,const char*message){bool thrown{};try{f();}catch(const std::exception&){thrown=true;}check(thrown,message);}
bool closeEnough(double a,double b){return std::abs(a-b)<=2e-12*std::max({1.,std::abs(a),std::abs(b)});}
double number(const J&v){return v.isString()?std::numeric_limits<double>::quiet_NaN():v.number();}
c::Point point(const J&v){return {number(v.array()[0]),number(v.array()[1])};}
m::MapViewport viewport(const J&v){return {number(v.array()[0]),number(v.array()[1]),number(v.array()[2])};}
void equal(m::MapViewport a,m::MapViewport b){check(closeEnough(a.centerX,b.centerX)&&closeEnough(a.centerY,b.centerY)&&closeEnough(a.zoom,b.zoom),"Map camera matches unchanged original Swift");}
void equal(c::Point a,c::Point b){check(closeEnough(a.x,b.x)&&closeEnough(a.y,b.y),"Map projection matches unchanged original Swift");}
std::string id(unsigned n){char bytes[37];std::snprintf(bytes,sizeof bytes,"00000000-0000-4000-8000-%012u",n);return bytes;}
void source(const char*path){std::ifstream file(path);check(bool(file),"Explicit original map fixture exists");const std::string bytes((std::istreambuf_iterator<char>(file)),{});const auto json=J::parse(bytes,256*1024);check(json["authority"].string()=="ca04f142185c7de40acd8523bdb563195d90a1d1","Map source authority pinned");for(const auto&r:json["geometry"].array()){const auto v=m::mapConstrained(viewport(r["camera"]));const auto p=point(r["point"]);equal(v,viewport(r["constrained"]));check(m::mapContains(p)==r["contains"].boolean(),"Source circular edge hit");equal(m::mapPanned(v,point(r["delta"])),viewport(r["panned"]));equal(m::mapZoomed(v,p,number(r["factor"])),viewport(r["zoomed"]));equal(m::mapRecentered(v,p),viewport(r["recentered"]));if(r.contains("world")){const auto w=m::mapWorld(p,v);equal(w,point(r["world"]));equal(m::mapScreen(w.x,w.y,v),point(r["screen"]));}check(m::mapCoordinateDescription(v.centerX,v.centerY)==r["description"].string(),"Coordinates preserve source precision, hemispheres and spacing");}
    // The original CGRect edge observations also govern action hit/spacing.
    for(const auto&r:json["rectEdges"].array()){const auto p=point(r["point"]);m::MapState next;next.setActive(true);next.down(p);check((!next.dragging())==r["contains"].boolean(),"Toolbar hit preserves CGRect half-open edges");}
    m::MapSnapshot touching;touching.viewport={.5,.5,163./55.};touching.pins.push_back({id(1),.375,.5,1});m::MapState spaced(touching);check(spaced.actions().count==(json["pinBoundary"]["intersects"].boolean()?4:5),"Exact source pin/control edge keeps Swift operation boundaries");
}
struct Store {
    m::MapSnapshot data;unsigned writes{},serial{1};bool fails{};
    m::MapPersistence callbacks(){return {[this](const m::MapSnapshot&v){if(fails)throw std::runtime_error("Synthetic CAS failure");data=v;++writes;},[this]{return id(serial++);},[]{return 800000000.;}};}
};
void gestures(){Store store;m::MapState state(store.data,store.callbacks());check(state.viewport().zoom==3&&!state.active(),"Starts inactive at original Shenzhen 3x camera");check(closeEnough(state.viewport().centerX,(114.0579+180)/360)&&closeEnough(state.viewport().centerY,(90-22.5431)/180),"Initial camera does not use rejected preview defaults");check(!state.down({220,220}).handled,"Hidden map rejects input");state.setActive(true);
    state.down({220,220});check(state.dragging()&&state.pointerLocked(),"Only begun map gesture captures pointer");state.drag({223,220});check(state.viewport()==m::MapViewport{}&&store.writes==0,"Exact three-point drag threshold leaves camera untouched");const auto before=allocations.load();for(unsigned k=0;k<1000;++k)state.drag({224+double(k)*.01,221+double(k)*.02});check(allocations.load()==before,"Warm pointer drag copies no pin payload and allocates nothing");check(store.writes==0,"Drag never performs metadata persistence per frame");const auto dragged=state.viewport();state.up();check(store.writes==1&&store.data.viewport==dragged&&!state.pointerLocked(),"Release saves exactly one latest camera");state.endGesture();check(store.writes==1,"Identical gesture flush does not save");
    const auto current=state.viewport();state.down({270,210});auto click=state.up();check(click.recentered&&click.cameraAnimated&&store.writes==2,"Terrain click commits first then requests exact source camera animation");check(state.viewport().zoom==current.zoom,"Recenter preserves zoom");const auto moved=state.viewport();state.down({200,180});state.up(true);check(state.viewport()==moved,"Cancelled click does not recenter");
    store.fails=true;state.down({275,190});click=state.up();check(!click.recentered&&state.viewport()==moved&&state.error()=="Synthetic CAS failure","Failed recenter cannot visually claim success or emit event");state.down({220,220});state.drag({240,230});const auto unsaved=state.viewport();state.up();check(unsaved!=moved&&state.viewport()==unsaved&&store.data.viewport==moved,"Failed drag save preserves source visible camera and old durable record");store.fails=false;state.endGesture();check(store.data.viewport==unsaved,"Later explicit gesture completion retries unsaved camera");
    const auto saves=store.writes;state.wheel({260,210},1,false,false,1);check(state.pointerLocked()&&state.nextWakeTime()==1.18&&store.writes==saves,"Wheel uses one caller-owned 180ms deadline");state.wheel({260,210},.25,true,false,1.1);state.advance(1.2);check(state.pointerLocked()&&store.writes==saves,"Fractional samples extend one deadline without early save");state.advance(1.28);check(!state.pointerLocked()&&store.writes==saves+1,"Shared deadline commits final wheel viewport once");
    state.magnify({220,220},100,false,2);const auto zoom=state.viewport().zoom;state.magnify({220,220},std::numeric_limits<double>::quiet_NaN(),false,2.01);check(state.viewport().zoom==zoom,"Nonfinite magnify ignored");state.wheel({0,0},0,false,true,2.02);check(!state.pointerLocked(),"Ending wheel outside circular map releases gesture");state.wheel({220,220},.5,false,false,2.1);state.perform(m::MapAction::reset);check(!state.pointerLocked()&&!state.nextWakeTime(),"Direct accessible action first finishes any wheel gesture");const auto reset=state.viewport();check(reset.zoom==3&&reset.centerX!=m::MapViewport{}.centerX,"Reset changes only zoom, preserving source current-center semantics");
    state.down({220,220});state.drag({240,210});const auto atHide=state.viewport();state.setActive(false);check(!state.pointerLocked()&&store.data.viewport==atHide&&!state.nextWakeTime(),"Hide commits changed drag but cancels input/deadline");check(!state.wheel({220,220},1,false,false,3).handled,"Hidden wheel cannot create work");rejects([&]{state.advance(2.99);},"Owner clock rejects time reversal");
}
void pins(){Store store;m::MapState state({},store.callbacks());state.setActive(true);state.rightDown({220,220});check(state.pins().size()==1&&state.showsCoordinates()&&state.selection()==id(1)&&store.writes==1,"Right click adds and selects a persisted source pin");const auto original=state.pins()[0];state.down({220,220});check(state.pins()[0].style==m::MapPinStyle::green&&!state.showsCoordinates()&&!state.dragging(),"Left click cycles marker then hides coordinates, as source mouseDown");check(state.pins()[0].id==original.id&&state.pins()[0].createdAt==original.createdAt&&state.pins()[0].x==original.x,"Style edit retains geographic identity/time");auto change=state.perform(m::MapAction::pin,original.id);check(change.styleChanged==m::MapPinStyle::player&&state.showsCoordinates(),"Accessible pin action exposes exact player style event");check(m::mapMarkerHitRect(m::MapPinStyle::player,{220,220})==c::Rect{207,207,26,26},"Player marker has source larger hit rectangle");
    store.fails=true;state.rightDown({220,220});check(state.pins().size()==1&&state.selection()==original.id,"Failed deletion retains selected pin");store.fails=false;state.rightDown({220,220});check(state.pins().empty()&&!state.selection()&&!state.showsCoordinates(),"Right click removes existing marker before adding another");
    state.rightDown({26,184});check(state.pins().empty(),"Right-click toolbar consumes without placing pin");state.perform(m::MapAction::addPin);state.key(m::MapKey::escape);check(!state.selection()&&state.pins().size()==1,"Escape clears only selection");check(!state.key(m::MapKey::erase).handled,"Delete without selected marker is unhandled");state.perform(m::MapAction::pin,state.pins()[0].id);check(state.key(m::MapKey::erase).handled&&state.pins().empty(),"Keyboard deletion retains source selected-pin contract");
    for(unsigned i=0;i<128;++i)state.perform(m::MapAction::addPin);check(state.pins().size()==128,"Source pin capacity supported");const auto writes=store.writes;state.perform(m::MapAction::addPin);check(state.pins().size()==128&&store.writes==writes&&state.error().has_value(),"Capacity rejection preserves all previous metadata");check(!state.actions().items[3].enabled,"Add action disables at capacity");
    const auto savedPins=state.persisted().pins;state.down({280,280});const auto allocated=allocations.load();for(unsigned k=0;k<1000;++k)state.drag({284+double(k)*.01,285+double(k)*.02});check(allocations.load()==allocated&&store.writes==writes,"Dragging a full128-pin map neither copies metadata nor persists");state.up();check(store.writes==writes+1&&state.persisted().pins==savedPins,"Full-pin drag saves only final camera and retains exact pin metadata");const auto idleAllocations=allocations.load();for(unsigned k=0;k<100;++k)state.endGesture();check(allocations.load()==idleAllocations&&store.writes==writes+1,"Repeated exact gesture flushes allocate and save nothing");
    m::MapState readonly(store.data);readonly.setActive(true);check(!readonly.actions().items[3].enabled,"Read-only source fallback cannot add metadata");readonly.rightDown({320,200});check(std::equal(readonly.pins().begin(),readonly.pins().end(),state.pins().begin(),state.pins().end()),"Read-only input never changes existing data");
}
void archives(){m::MapSnapshot current;current.pins.push_back({id(1),.25,.75,42,m::MapPinStyle::player});auto old=current;old.viewport.zoom=16;check(m::migrateMapSnapshot(old,1).viewport==m::MapViewport{},"Version1 camera migrates exactly once");old.viewport=m::MapViewport{};old.viewport.zoom=24;check(m::migrateMapSnapshot(old,2).viewport.zoom==3,"Untouched version2 default migrates");old.viewport.zoom=72;check(m::migrateMapSnapshot(old,3).viewport.zoom==3,"Untouched version3 default migrates");old.viewport.centerX=.2;check(m::migrateMapSnapshot(old,3).viewport==old.viewport,"Custom version3 camera preserved");old.viewport=m::MapViewport{};old.viewport.zoom=72;check(m::migrateMapSnapshot(old,4)==old,"User-selected historical default in version4 is never reset");check(m::migrateMapSnapshot(current,4).pins==current.pins,"Migration retains pin styles, time and coordinates");rejects([&]{m::migrateMapSnapshot(current,5);},"Future archive rejected");auto malformed=current;malformed.pins.push_back(current.pins[0]);rejects([&]{m::validateMapSnapshot(malformed);},"Duplicate UUID rejected");malformed=current;malformed.pins[0].x=1;rejects([&]{m::validateMapSnapshot(malformed);},"Archive seam must use canonical wrapped coordinate");malformed=current;malformed.viewport.zoom=2;rejects([&]{m::validateMapSnapshot(malformed);},"Current archive does not accept legacy zoom range");check(m::mapWrappedX(-std::numeric_limits<double>::denorm_min())==0,"Tiny negative seam canonicalizes rounded one to zero");
}
}
int main(int argc,char**argv){try{check(argc==2,"Pass original Swift map fixture");source(argv[1]);gestures();pins();archives();std::cout<<"PASS "<<checks<<" Map source/state checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
