#include "native/map_scene.hpp"
#include <atomic>
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <limits>
#include <new>
#include <set>
#ifdef _WIN32
#include <windows.h>
#include <objbase.h>
#include "native/layer_scene.hpp"
#endif
namespace{std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace{namespace c=endfield::core;namespace m=endfield::modules;namespace n=endfield::native;unsigned checks{};
void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}template<class F>void rejects(F f,const char*s){bool rejected{};try{f();}catch(const std::exception&){rejected=true;}check(rejected,s);}
constexpr const char*pinID="00000000-0000-0000-0000-000000000001";
m::MapState state(){m::MapSnapshot initial;initial.pins.push_back({pinID,initial.viewport.centerX,initial.viewport.centerY,1,m::MapPinStyle::player});return m::MapState(std::move(initial),{[](const auto&){},[]{return "00000000-0000-0000-0000-000000000002";},[]{return 2.;}});}
const n::MapChromeSurface&part(const std::vector<n::MapChromeSurface>&parts,std::string_view id){for(const auto&p:parts)if(p.id==id)return p;throw std::runtime_error("Missing Map source layer");}
void portable(){auto s=state();s.setActive(true);n::MapAppearance a;auto parts=n::prepareMapChrome(s,a);check(parts.size()==18,"Map chrome uses two captions and four separate source controls");
    check(part(parts,"map.heading").local==c::Matrix4::translation(122,37),"Original heading placement");check(part(parts,"map.heading").content["text"]["font"]["fontName"].string()==".AppleSystemUIFontDemi","Source semibold uses shared font resolver");check(part(parts,"map.status").content["text"]["string"].string()=="LOADING TERRAIN","Unavailable terrain has original loading label");
    const auto&tint=part(parts,"map.control.zoomIn.tint");check(tint.role==n::MapChromeRole::tint&&tint.action==m::MapAction::zoomIn,"Feedback is a separate numeric source plane");check(tint.content["shape"]["fillColor"]["sRGB"].array()[3].number()==.3,"Original accent tint alpha");check(tint.content["shape"]["path"].array()[0]["points"].array()[0].array()[0].number()==4,"Original cut corner path");check(part(parts,"map.control.zoomIn.rim").content["shape"]["lineWidth"].number()==.9,"Original framed rim width");
    s.perform(m::MapAction::pin,pinID);parts=n::prepareMapChrome(s,a);check(parts.size()==24,"Selected pin adds coordinates and exact delete control");check(part(parts,"map.coordinates.plate").local==c::Matrix4::translation(100,301),"Original coordinate plate");check(part(parts,"map.control.deletePin.plate").local==c::Matrix4::translation(316,303),"Original nested delete placement");
    std::set<std::string>ids;for(const auto&p:parts)check(ids.insert(p.id).second,"Map local layer IDs are unique");a.dark=false;a.terrainReady=true;a.strings={"地图","载入地形","标记"};a.accent={.2,.4,.8,1};parts=n::prepareMapChrome(s,a);check(part(parts,"map.heading").content["text"]["string"].string()=="地图","Caller-owned locale changes source caption");check(part(parts,"map.control.zoomIn.plate").content["backgroundColor"]["sRGB"].array()[0].number()==.94,"Original light toolbar plate");check(s.selection()&&s.pins().size()==1,"Appearance never edits map state");a.accent[0]=NAN;rejects([&]{n::prepareMapChrome(s,a);},"Nonfinite color rejects");}
#ifdef _WIN32
struct Window{HWND hwnd{};Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"OwnedMapSceneFixture";check(RegisterClassW(&c)!=0,"Register own hidden Map fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,c.lpszClassName,L"Synthetic Map",WS_POPUP,0,0,440,440,nullptr,nullptr,c.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Map fixture remains hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);UnregisterClassW(L"OwnedMapSceneFixture",GetModuleHandleW(nullptr));}};
std::shared_ptr<const n::MapPaintImage>feather(){auto p=std::make_shared<n::MapPaintImage>();p->width=p->height=880;p->straightRGBA.assign(880*880*4,255);return p;}
std::shared_ptr<const n::MapPaintImage>image(){auto p=std::make_shared<n::MapPaintImage>();p->width=p->height=2;p->straightRGBA.assign(16,255);return p;}
void native(const std::filesystem::path&shader){Window window;n::Renderer renderer;renderer.initialize(window.hwnd,440,440,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests});renderer.setCamera(n::layerViewportProjection(440,440));n::LayerRasterizer raster;n::LayerRasterOptions options;options.pixelsPerPoint=1;endfield::app::UtilityExecutor utility([]{});double time{};n::NativeMapRaster terrain(utility,[&]{return time;},[]{},[](const auto&,const auto&){return n::MapPaintResult{};});auto model=state();model.setActive(true);n::MapAppearance appearance;appearance.ambient=false;n::NativeMapScene scene(model,terrain,raster,options,{image(),image(),image(),feather()},appearance);n::LayerComposition composition;bool released{};struct Cleanup{n::Renderer&r;n::LayerComposition&c;n::NativeMapScene&s;bool&done;~Cleanup(){if(done)return;try{c.detach(r);s.releaseResources(r);}catch(...){r.reset();}}}cleanup{renderer,composition,scene,released};
    const auto frame=[&](double t,c::Matrix4 world=c::Matrix4{},bool animate=false){time=t;scene.syncContent(t,animate);scene.updatePose({world,1,t,{},{}});scene.uploadResources(renderer);composition.setEntries(renderer,scene.entries());composition.present(renderer);};
    frame(0);check(raster.stats().entries==22,"Map retains 18 independent chrome leaves plus four reusable marker paths");renderer.draw(false);check(!renderer.readback().pixels.empty(),"Original retained Map draws in synthetic offscreen target");check(scene.stats().visiblePins==1&&scene.stats().pulsingPins==0,"Source player marker is visible without ambient demand");check(!scene.requiresFrames(0),"Stable nonambient Map has no frame demand");
    auto before=raster.stats();auto gpu=renderer.stats();allocations=0;counting=true;try{for(unsigned k=0;k<120;++k)frame(1+k/60.,c::Matrix4::rotation(.02,.01*k/120,0));}catch(...){counting=false;throw;}counting=false;check(allocations==0,"Warm retained Map tilt frames allocate nothing");check(raster.stats().rasterizations==before.rasterizations&&renderer.stats().textureUploads==gpu.textureUploads,"Tilt never rerasterizes Map geometry or captions");
    scene.setFeedback(c::Point{37,195},true,3);frame(3);check(scene.requiresFrames(3),"Stationary toolbar press starts original finite feedback");frame(3.07);check(!scene.requiresFrames(3.07),"Press endpoint settles without an extra pointer event");const auto finalFeedback=renderer.stats().objectUploads;frame(3.08);check(renderer.stats().objectUploads==finalFeedback,"Completed feedback does not keep uploading uniforms");
    appearance.dark=false;scene.setAppearance(appearance);frame(3.1);const auto beforeZoom=raster.stats().rasterizations;const auto beforeZoomChrome=scene.stats().chromeBuilds;
    model.perform(m::MapAction::zoomIn);frame(4,{},true);check(raster.stats().rasterizations==beforeZoom+1&&scene.stats().chromeBuilds==beforeZoomChrome,"Zoom after a full chrome rebuild updates only its retained status leaf");check(scene.requiresFrames(4),"Source zoom control starts finite camera motion");frame(4.09);const auto halfway=scene.stats().localUpdates;frame(4.25);check(scene.stats().localUpdates==halfway+1&&!scene.requiresFrames(4.25),"Late final frame writes exact camera endpoint once");frame(4.3);check(scene.stats().localUpdates==halfway+1,"Settled camera does no additional local work");
    scene.setFeedback({},false,4.4);model.perform(m::MapAction::pin,pinID);frame(4.5);check(raster.stats().entries==28,"Selection adds six independent delete/coordinate leaves without flattening existing controls");check(scene.requiresFrames(4.5),"Pin style uses original finite grouped rotation and opacity");const auto styleGPU=renderer.stats();const auto stylePaint=raster.stats();allocations=0;counting=true;try{for(unsigned k=1;k<=12;++k)frame(4.5+k/60.);}catch(...){counting=false;throw;}counting=false;check(allocations==0&&renderer.stats().textureUploads==styleGPU.textureUploads&&renderer.stats().nativeGroupTargetAllocations==styleGPU.nativeGroupTargetAllocations&&raster.stats().rasterizations==stylePaint.rasterizations,"Style animation retains marker target and performs numeric-only group updates");check(!scene.requiresFrames(4.7),"Grouped style fade terminates after .16seconds");
    appearance.ambient=true;scene.setAppearance(appearance);frame(5);const auto textures=renderer.stats().textureUploads;const auto textLayouts=raster.stats().textLayoutsCreated;check(scene.stats().pulsingPins==1&&scene.requiresFrames(5),"Original selected/latest marker pulse requests active frames");allocations=0;counting=true;try{for(unsigned k=0;k<120;++k)frame(5.01+k/60.);}catch(...){counting=false;throw;}counting=false;check(allocations==0,"Warm ambient Map animation allocates nothing");check(renderer.stats().textureUploads==textures&&raster.stats().textLayoutsCreated==textLayouts,"Ambient marker motion uploads no textures and shapes no text");
    model.setActive(false);frame(8);check(!scene.requiresFrames(8),"Closing/hiding removes marker ambient demand");const auto viewport=model.viewport();appearance.dark=false;appearance.strings={"지도","지형 불러오는 중","핀"};scene.setAppearance(appearance);frame(9);check(model.viewport()==viewport&&model.pins().size()==1,"Locale/theme replacement preserves camera and pin data");const auto old=scene.entries()[0].after[0].world;rejects([&]{scene.updatePose({{},NAN,10,{},{}});},"Malformed opacity rejects before publication");check(scene.entries()[0].after[0].world==old,"Rejected pose preserves published placement");
    check(!scene.releaseResources(renderer),"Published carrier cannot release live resources");composition.detach(renderer);check(scene.releaseResources(renderer),"Map resources release after composition detach");check(renderer.stats().textures==0&&renderer.stats().meshes==0,"Map retires source images, feather, shapes, group and chrome");released=true;renderer.reset();utility.shutdown();}
#endif
}
#ifdef _WIN32
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==2,"Pass original HUD shader");portable();native(argv[1]);CoUninitialize();std::cout<<"PASS "<<checks<<" Map retained scene checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(){try{portable();std::cout<<"PASS "<<checks<<" Map portable scene checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
