#include "native/media_assembly_scene.hpp"
#include <iostream>
#ifdef _WIN32
#include <windows.h>
#include <objbase.h>
#include <cstdlib>
#include <new>
#include <algorithm>
#include <cmath>
static bool counting{};static std::size_t allocations{};
void*operator new(std::size_t n){if(counting)++allocations;if(void*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void operator delete(void*p)noexcept{std::free(p);}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete[](void*p)noexcept{::operator delete(p);}void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
namespace {namespace n=endfield::native;namespace m=endfield::modules;namespace c=endfield::core;unsigned checks{};void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(s);}struct COM{HRESULT result{CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED)};~COM(){if(SUCCEEDED(result))CoUninitialize();}};
struct Window {HWND hwnd{};Window(){WNDCLASSW w{};w.lpfnWndProc=DefWindowProcW;w.hInstance=GetModuleHandleW(nullptr);w.lpszClassName=L"OwnedMediaAssemblyScene";check(RegisterClassW(&w)!=0,"Register owned Media Assembly fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,w.lpszClassName,L"Isolated",WS_POPUP,0,0,440,440,nullptr,nullptr,w.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Media fixture remains hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);UnregisterClassW(L"OwnedMediaAssemblyScene",GetModuleHandleW(nullptr));}};
void run(const std::filesystem::path&shader,const std::filesystem::path&root){Window window;n::Renderer renderer;renderer.initialize(window.hwnd,440,440,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests});renderer.setCamera(n::layerViewportProjection(440,440));n::LayerRasterizer raster;n::NativeMediaAssemblyAssets assets(root);n::LayerRasterOptions options;options.assetRoot=root;options.pixelsPerPoint=1;n::NativeMediaAssemblyScene scene(raster,options,assets);n::LayerComposition composition;
 struct Cleanup{n::LayerComposition&c;n::NativeMediaAssemblyScene&s;n::Renderer&r;~Cleanup(){try{c.detach(r);s.releaseResources(r);}catch(...){r.reset();}}}cleanup{composition,scene,renderer};
 m::MediaAssemblyPresentation presentation;m::MediaAssemblyAppearance appearance;m::MediaAssemblyAdjustments adjustments;std::optional<m::MediaAssemblyDocumentInfo>document;auto view=[&]{return m::MediaAssemblyView{document?&*document:nullptr,&adjustments,{},false,false,false,0};};
 const auto content=[&](double t,bool scroll=false){presentation.synchronize(view());return scene.syncContent(presentation,view(),appearance,{},0,t,scroll);};
 const auto frame=[&](double t,c::Matrix4 world=c::Matrix4{}){scene.updatePose({world,1,t,{},{}});scene.uploadResources(renderer);composition.setEntries(renderer,scene.entries());composition.present(renderer);check(scene.collectRetired(renderer),"Retire only detached Media Assembly resources");};
 const auto find=[&](std::string_view id)->const n::DrawObject*{for(const auto&e:scene.entries())for(const auto&d:e.scene->draws())if(d.sourceID.ends_with(id))return &d;return nullptr;};
 content(0);frame(0);renderer.draw(false);check(scene.stats().surfaces<70,"Empty original Media Assembly controls are bounded");check(renderer.readback().width==440,"Source artwork draws through the borrowed renderer");scene.setFeedback(c::Point{30,373},false,false,.1);frame(.3);const auto rasters=raster.stats().rasterizations;const auto uploads=renderer.stats().textureUploads;allocations=0;counting=true;try{for(unsigned k=0;k<120;++k)frame(1+double(k)/60,c::Matrix4::rotation(.001,.005*k/120,0));}catch(...){counting=false;throw;}counting=false;check(allocations==0,"Warm Media Assembly tilt/feedback/uploads allocate nothing");check(raster.stats().rasterizations==rasters&&renderer.stats().textureUploads==uploads,"Warm frames do not repaint source controls");
 const std::array<n::Vertex,4>vertices{{{{0,0,0},{0,0}},{{1,0,0},{1,0}},{{1,1,0},{1,1}},{{0,1,0},{0,1}}}};const std::array<std::uint32_t,6>indices{0,1,2,0,2,3};const std::array<std::uint8_t,16>pixels{255,64,32,255,255,64,32,255,255,64,32,255,255,64,32,255};renderer.setMesh("owned.media.quad",1,{vertices,indices});renderer.setTexture("owned.media.poster",1,{2,2,pixels});n::MediaAssemblyPreviewDraw preview;preview.sourceBounds={0,0,1,1};preview.draw.sourceID="owned.media.preview";preview.draw.meshID="owned.media.quad";preview.draw.textureID="owned.media.poster";
 document=m::MediaAssemblyDocumentInfo{"owned",false,{1920,1080},0};content(4);scene.setPreview(preview);frame(4);check(scene.entries().front().after.size()==1,"Borrowed preview appears directly above original stage");auto request=presentation.perform("sticker:sticker_1",view(),"owned-sticker");check(bool(request.adjustments),"Original sticker action produces model edit");adjustments=std::move(*request.adjustments);content(4.1);frame(4.1);const auto*sticker=find("media.sticker.owned-sticker");check(sticker&&sticker->masks.size()==2&&sticker->masks[0].cornerRadius==4,"Sticker retains original image and rounded-stage masks");const auto stickerTexture=sticker->textureID;const auto stickerWorld=sticker->world;const auto decoded=raster.stats().imageDecodes;const auto zoomRasters=raster.stats().rasterizations;presentation.zoom(1.25,{220,198},view());content(4.2);frame(4.2);sticker=find("media.sticker.owned-sticker");check(sticker&&sticker->textureID==stickerTexture&&sticker->world!=stickerWorld&&raster.stats().imageDecodes==decoded,"Zoom updates geometry while preserving original sticker pixels");check(raster.stats().rasterizations-zoomRasters<8,"Zoom does not rasterize the whole panel or sticker");
 presentation.perform("adjust",view());content(5);scene.revealDrawer(5,true);frame(5);const auto drawer=[&]()->const n::DrawObject*{for(const auto&e:scene.entries())if(!e.after.empty()&&e.after[0].sourceID.find("media.drawer")!=std::string::npos)return &e.after[0];return nullptr;};check(drawer()&&drawer()->opacity==0,"Drawer starts as one source group at zero opacity");const auto drawerRasters=raster.stats().rasterizations;frame(5.08);check(drawer()&&std::abs(drawer()->opacity-.5f)<1e-6&&raster.stats().rasterizations==drawerRasters,"Drawer fades once without per-child alpha or raster work");frame(5.16);presentation.scroll({80,200},0,47.25,false,view());content(5.2,true);frame(5.2);const auto scrollRasters=raster.stats().rasterizations;frame(5.24);frame(5.28);check(raster.stats().rasterizations==scrollRasters&&!scene.requiresFrames(5.4),"Inline list scroll uses finite local transforms and retained glyphs");const auto settled=raster.stats().rasterizations;const auto settledUploads=renderer.stats().textureUploads;allocations=0;counting=true;try{for(unsigned k=0;k<120;++k)frame(6+double(k)/120,c::Matrix4::rotation(.01,.01*k/120,0));}catch(...){counting=false;throw;}counting=false;check(allocations==0&&raster.stats().rasterizations==settled&&renderer.stats().textureUploads==settledUploads,"Settled grouped drawer/tilt allocate and repaint nothing");
 presentation.perform("toolBack",view());presentation.perform("tools",view());content(8);frame(8);for(unsigned k=1;k<16;++k){m::MediaAssemblySticker item;item.id="owned-"+std::to_string(k);item.kind=m::MediaAssemblyStickerKind(k%24);adjustments.stickers.push_back(std::move(item));}content(8.1);frame(8.1);check(adjustments.stickers.size()==16,"Closing fixture reaches original sticker capacity");const auto beforeClose=raster.stats().rasterizations;scene.beginClose(preview,8.2,true);document.reset();adjustments={};content(8.2);frame(8.2);check(scene.closingMedia(),"Finite close retains caller poster plus all sixteen sticker references");check(!renderer.removeTexture("owned.media.poster"),"Closing source group leases borrowed poster resource");const auto closeRasters=raster.stats().rasterizations;check(closeRasters-beforeClose<70,"Closing retains original sticker rasters rather than cloning them");frame(8.28);check(scene.closingMedia()&&raster.stats().rasterizations==closeRasters,"Closing midpoint does no CPU pixel work");frame(8.37);check(!scene.closingMedia()&&renderer.removeTexture("owned.media.poster")&&renderer.removeMesh("owned.media.quad"),"Finite close retires group before releasing caller media");
 appearance.dark=false;appearance.language=c::Language::korean;appearance.accent={.2,.6,1,1};content(9);frame(9);const auto oldFontRasters=raster.stats().rasterizations;raster.setDefaultFontLanguage(n::LayerFontLanguage::korean);check(content(9.1),"Equal Media content observes the shared default font revision");frame(9.1);check(raster.stats().rasterizations>oldFontRasters,"SC to KR refresh repaints retained text without replacing user media");const auto newFontRasters=raster.stats().rasterizations;frame(9.2);check(raster.stats().rasterizations==newFontRasters,"Font event creates no per-frame typography walk or repaint");for(const auto&e:scene.entries())check(e.scene->report().unsupported.empty(),"No source artwork silently omitted");composition.detach(renderer);check(scene.releaseResources(renderer)&&renderer.stats().textures==0&&renderer.stats().meshes==0,"Detach releases every owned layer and group resource");frame(10);renderer.draw(false);check(renderer.readback().width==440,"Existing retained art can upload after a complete release");composition.detach(renderer);check(scene.releaseResources(renderer)&&renderer.stats().textures==0&&renderer.stats().meshes==0,"Reuploaded source resources retire again");}
}
int wmain(int argc,wchar_t**argv){COM com;try{check(SUCCEEDED(com.result)&&argc==3,"Pass HLSL and packaged Media Assembly asset root");run(argv[1],std::filesystem::absolute(argv[2]));std::cout<<"PASS "<<checks<<" native Media Assembly scene checks\n";return 0;}catch(const std::exception&e){counting=false;std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(){std::cout<<"Native Media Assembly scene needs Windows; no GPU execution on this host\n";return 0;}
#endif
