#include "modules/media_assembly_artwork.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iostream>
#include <set>

namespace {namespace m=endfield::modules;namespace c=endfield::core;using J=ehud::data::Json;unsigned checks{},rowIndex{};std::string context;
void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(std::string(s)+" "+context);}
J read(const char*path){std::ifstream f(path);check(bool(f),"Open explicit original fixture");return J::parse(std::string(std::istreambuf_iterator<char>(f),{}),4*1024*1024);}
void same(const J&a,const J&b){++checks;if(a.isNumber()&&b.isNumber()){if(std::abs(a.number()-b.number())<=5e-7*std::max(1.,std::abs(b.number())))return;}else if(a.isArray()&&b.isArray()){check(a.array().size()==b.array().size(),"Original array shape");for(std::size_t n=0;n<a.array().size();++n)same(a.array()[n],b.array()[n]);return;}else if(a.isObject()&&b.isObject()){check(a.object().size()==b.object().size(),"Original object shape");for(const auto&[key,value]:a.object()){check(b.contains(key),"Original source property");same(value,b[key]);}return;}else if(a==b)return;throw std::runtime_error("Paint mismatch "+context+" actual="+a.encode()+" expected="+b.encode());}
J xy(const c::Matrix4&m,double x,double y){const auto&v=m.values;return J::Array{v[0]*x+v[4]*y+v[12],v[1]*x+v[5]*y+v[13]};}
J color(const J&j){return j.isNull()?J{}:j["sRGB"];}
J::Array canonical(const m::MediaAssemblyArtwork&art){J::Array result;for(const auto&s:art.surfaces){const auto&j=s.content;const auto&b=j["bounds"].array();const auto x=b[0].number(),y=b[1].number(),w=b[2].number(),h=b[3].number();const auto corners=J::Array{xy(s.local,x,y),xy(s.local,x+w,y),xy(s.local,x+w,y+h),xy(s.local,x,y+h)};const auto opacity=double(s.opacity);const auto border=j["borderWidth"].isNumber()?j["borderWidth"].number():0;
 if(!j["backgroundColor"].isNull()||border>0)result.push_back(J::Object{{"kind","plate"},{"corners",corners},{"opacity",opacity},{"color",color(j["backgroundColor"])},{"radius",j["cornerRadius"].isNumber()?j["cornerRadius"]:J(0)},{"borderWidth",border},{"border",border>0?color(j["borderColor"]):J{}}});
 if(j["kind"].string()=="shape"){const auto&v=j["shape"];J::Array commands;for(const auto&item:v["path"].array()){J::Array points;for(const auto&p:item["points"].array())points.push_back(xy(s.local,p.array()[0].number(),p.array()[1].number()));commands.push_back(J::Object{{"op",item["op"]},{"points",std::move(points)}});}result.push_back(J::Object{{"kind","shape"},{"path",std::move(commands)},{"opacity",opacity},{"fill",color(v["fillColor"])},{"stroke",color(v["strokeColor"])},{"width",v["lineWidth"]},{"rule",v["fillRule"]},{"cap",v["lineCap"]},{"join",v["lineJoin"]}});}
 else if(j["kind"].string()=="text"){const auto&t=j["text"];result.push_back(J::Object{{"kind","text"},{"corners",corners},{"opacity",opacity},{"string",t["string"]},{"size",t["fontSize"]},{"font",t["font"]["postScriptName"]},{"color",color(t["foregroundColor"])},{"alignment",t["alignment"]},{"wrapped",t["wrapped"]}});}
 else if(!j["contents"].isNull())result.push_back(J::Object{{"kind","image"},{"corners",corners},{"opacity",opacity},{"asset",j["contents"]["asset"]}});
 }return result;}
struct Owner {
 m::MediaAssemblyPresentation presentation;m::MediaAssemblyAdjustments adjustments;std::optional<m::MediaAssemblyDocumentInfo>document;bool playing{},visible{true};double time{};unsigned identity{};
 m::MediaAssemblyView view()const{return {document?&*document:nullptr,&adjustments,{},false,false,playing,time};}
 void apply(m::MediaAssemblyRequest r){if(r.adjustments)adjustments=std::move(*r.adjustments);if(r.command==m::MediaAssemblyCommand::trim||r.command==m::MediaAssemblyCommand::seek)time=std::min(std::max(adjustments.trimStart,r.time),std::max(adjustments.trimStart,adjustments.trimEnd.value_or(document?document->duration:0)-.001));if(r.command==m::MediaAssemblyCommand::play)playing=!playing;if(r.command==m::MediaAssemblyCommand::reset)adjustments={};if(r.command==m::MediaAssemblyCommand::closeMedia){adjustments={};document.reset();}if(visible)presentation.synchronize(view());}
 void operation(const J&o){const auto kind=o["op"].string();const auto n=[&](const char*k){return o[k].isNumber()?o[k].number():0.;};const c::Point p{n("x"),n("y")};if(kind=="photo"||kind=="video"){document=m::MediaAssemblyDocumentInfo{std::to_string(++identity),kind=="video",{1920,1080},120};adjustments={};time=0;presentation.synchronize(view());}
 else if(kind=="action")apply(presentation.perform(o["id"].string(),view(),"owned-sticker"));else if(kind=="parameter")apply(presentation.parameter(o["id"].string(),n("value"),view()));else if(kind=="trim")apply(presentation.trim(o["beginning"].boolean(),n("value"),view()));else if(kind=="scroll")presentation.scroll(p,n("dx"),n("dy"),false,view());else if(kind=="zoom")presentation.zoom(n("value"),p,view());else if(kind=="down")apply(presentation.pointerDown(p,view(),c::Language::english,"owned-sticker"));else if(kind=="drag")apply(presentation.pointerDrag(p,view()));else if(kind=="up")apply(presentation.pointerUp(view()));else if(kind=="stickerKey")apply(presentation.adjustSelected(n("dx"),n("dy"),n("size"),n("rotation"),view()));else if(kind=="hide"){visible=false;presentation.hide();}else if(kind=="show"){visible=true;presentation.synchronize(view());}}
};
void run(const J&fixture,const J&catalog){m::MediaAssemblyArtworkAssets assets;const auto&files=catalog["files"].array();check(files.size()==52,"Original asset catalog size");for(std::size_t n=1;n<15;++n)assets.filters[n]={files[13+n]["path"].string(),files[13+n]["sha256"].string()};for(std::size_t n=0;n<24;++n)assets.stickers[n]={files[28+n]["path"].string(),files[28+n]["sha256"].string()};
 check(fixture["buttonHeight"].number()==12,"Actual original 10pt semibold action measurement");Owner owner;bool previousDark=true;for(const auto&row:fixture["cases"].array()){const bool dark=row["dark"].boolean();if(dark!=previousDark){owner=Owner{};previousDark=dark;}owner.operation(row["operation"]);++rowIndex;if(!owner.visible)continue;m::MediaAssemblyAppearance appearance;appearance.dark=dark;appearance.accent={1,1,0,1};auto art=m::prepareMediaAssemblyArtwork(owner.presentation,owner.view(),appearance,assets);auto actual=canonical(art);const auto&expected=row["art"].array();context="row "+std::to_string(rowIndex)+" "+row["operation"].encode();if(actual.size()!=expected.size())std::cerr<<"actualLeaves="<<actual.size()<<" sourceLeaves="<<expected.size()<<'\n';check(actual.size()==expected.size(),"Original paint leaf count/order");for(std::size_t n=0;n<actual.size();++n){context="row "+std::to_string(rowIndex)+" leaf "+std::to_string(n);same(actual[n],fixture["paintLeaves"].array().at(static_cast<std::size_t>(expected[n].integer())));}
  std::set<std::string>ids;for(const auto&s:art.surfaces){check(ids.insert(s.id).second,"Unique retained source surface identity");check(s.local.finite()&&s.clipCount<=2,"Bounded finite source placements");}check(art.surfaces.size()<180,"Source control/parameter art remains bounded");
 }
 m::MediaAssemblyPresentation p;m::MediaAssemblyAdjustments a;m::MediaAssemblyDocumentInfo d{"geometry",false,{1920,1080},0};m::MediaAssemblyView v{&d,&a};p.synchronize(v);m::MediaAssemblyAppearance style;auto request=p.perform("sticker:sticker_1",v,"kept");a=std::move(*request.adjustments);auto first=m::prepareMediaAssemblyArtwork(p,v,style,assets);p.zoom(3,{220,198},v);auto second=m::prepareMediaAssemblyArtwork(p,v,style,assets);const auto find=[](const auto&art)->const auto&{return *std::find_if(art.surfaces.begin(),art.surfaces.end(),[](const auto&s){return s.role==m::MediaAssemblyPaintRole::sticker;});};check(find(first).content==find(second).content&&find(first).local!=find(second).local,"Zoom changes only sticker geometry; intrinsic source bitmap stays retained");check(find(second).clipCount==2&&find(second).clips[0].cornerRadius==4,"Sticker keeps both original image and rounded stage clipping");bool rejected{};try{(void)m::prepareMediaAssemblyArtwork(p,v,style,assets,"failure");}catch(const std::invalid_argument&){rejected=true;}check(rejected,"An error cannot silently invent a platform systemOrange");
}
}
int main(int argc,char**argv){try{check(argc==3,"Pass actual source artwork fixture and original asset catalog");run(read(argv[1]),read(argv[2]));std::cout<<"PASS "<<checks<<" Media Assembly artwork checks across "<<rowIndex<<" source states\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
