#include "core/media_request_catalog.hpp"
#include <array>
#include <iostream>
#include <stdexcept>
#include <utility>
namespace c=endfield::core;namespace m=endfield::modules;
namespace {unsigned checks{};void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}template<class F>void rejects(F&&fn,const char*why){bool failed{};try{fn();}catch(const std::exception&){failed=true;}check(failed,why);}
c::ScopedMediaRequest image(std::string key="shared"){return {std::move(key),"C:\\Owned-fixture\\not-opened.png",1};}
void run(){c::MediaRequestCatalog catalog;const auto notes=catalog.attach(),archive=catalog.attach();const std::array requests{image()};
 auto prepared=catalog.prepare(notes,c::MediaRequestChannel::image,1,requests);check(prepared.changed()&&prepared.aggregate().size()==1&&!catalog.find(notes,c::MediaRequestChannel::image,"shared"),"Prepare validates immutable union before owner/provider mutation");catalog.commit(std::move(prepared));const auto notesKey=catalog.find(notes,c::MediaRequestChannel::image,"shared")->globalKey;rejects([&]{catalog.commit(std::move(prepared));},"A consumed transaction cannot clear the live catalog");
 auto second=catalog.prepare(archive,c::MediaRequestChannel::image,7,requests);check(second.aggregate().size()==2&&second.aggregate()[0].globalKey!=second.aggregate()[1].globalKey,"Identical module-local names are scoped independently");catalog.commit(std::move(second));check(catalog.find(notes,c::MediaRequestChannel::image,"shared")->globalKey==notesKey,"Another module does not reset existing request identity");
 auto same=catalog.prepare(notes,c::MediaRequestChannel::image,1,requests);const auto revision=catalog.revision();check(!same.changed()&&!same.stale(),"Repeated unchanged metadata has no provider transaction");catalog.commit(std::move(same));check(catalog.revision()==revision,"Unchanged commit advances no owner revision");
 auto changed=requests;changed[0].path="C:\\Owned-fixture\\changed.png";rejects([&]{catalog.prepare(notes,c::MediaRequestChannel::image,1,changed);},"Changed reference cannot reuse same generation and revision");changed[0].revision=2;auto next=catalog.prepare(notes,c::MediaRequestChannel::image,1,changed);check(next.aggregate()[0].globalKey!=notesKey,"Reference revision changes native immutable identity");catalog.commit(std::move(next));
 auto stale=catalog.prepare(archive,c::MediaRequestChannel::image,6,requests);check(stale.stale()&&!stale.changed(),"Delayed module generation is recognized independently");rejects([&]{catalog.commit(std::move(stale));},"A stale owner completion cannot publish its union");
 auto empty=catalog.prepare(notes,c::MediaRequestChannel::image,1,{});check(empty.aggregate().size()==1&&empty.aggregate()[0].client==archive,"Hiding Notes preserves Archive media in aggregate");catalog.commit(std::move(empty));check(catalog.detach(notes)&&catalog.find(archive,c::MediaRequestChannel::image,"shared"),"Empty-client teardown cannot retire a sibling");check(!catalog.detach(archive),"Active client cannot detach and abandon references");
 auto before=catalog.prepare(archive,c::MediaRequestChannel::image,7,{});const auto other=catalog.attach();rejects([&]{catalog.commit(std::move(before));},"Catalog changes invalidate a prepared transaction");
 auto moveFrom=catalog.prepare(archive,c::MediaRequestChannel::image,7,{});auto moved=std::move(moveFrom);rejects([&]{catalog.commit(std::move(moveFrom));},"Moved-from transaction cannot mutate live state");catalog.commit(std::move(moved));
 c::MediaRequestCatalog foreign;const auto f=foreign.attach();auto foreignTx=foreign.prepare(f,c::MediaRequestChannel::image,1,requests);rejects([&]{catalog.commit(std::move(foreignTx));},"Matching revision numbers do not authorize a foreign catalog transaction");foreign.commit(std::move(foreignTx));
 auto lease=std::make_shared<unsigned>(1);std::weak_ptr<unsigned>weak=lease;auto leased=image("lease");leased.accessLease=lease;std::array leasedBatch{leased};auto txn=catalog.prepare(other,c::MediaRequestChannel::image,1,leasedBatch);catalog.commit(std::move(txn));lease.reset();leased.accessLease.reset();leasedBatch[0].accessLease.reset();check(!weak.expired(),"Accepted reference retains independent worker lease");auto clear=catalog.prepare(other,c::MediaRequestChannel::image,1,{});catalog.commit(std::move(clear));check(weak.expired(),"Cleared transaction releases old metadata lease once staging is retired");
 auto bad=image();bad.key=std::string("bad\0key",7);std::array invalid{bad};rejects([&]{catalog.prepare(archive,c::MediaRequestChannel::image,7,invalid);},"NUL identity rejects before provider use");bad=image();bad.path="relative.png";invalid[0]=bad;rejects([&]{catalog.prepare(archive,c::MediaRequestChannel::image,7,invalid);},"Reference path remains explicit and absolute without file IO");invalid[0]=image();invalid[0].kind=m::NotesMediaKind::video;rejects([&]{catalog.prepare(archive,c::MediaRequestChannel::image,7,invalid);},"Video cannot silently enter still/GIF channel");rejects([&]{catalog.prepare(archive,static_cast<c::MediaRequestChannel>(99),7,requests);},"Unknown channel cannot bypass scoped validation");
 c::MediaRequestCatalog limited;for(std::size_t n=0;n<c::MediaRequestCatalog::maximumClients;++n)limited.attach();rejects([&]{limited.attach();},"Clients share one bounded registry");
 c::MediaRequestCatalog counts;const auto a=counts.attach(),b=counts.attach();std::vector<c::ScopedMediaRequest>many;many.reserve(c::MediaRequestCatalog::maximumRequests);for(std::size_t n=0;n<c::MediaRequestCatalog::maximumRequests;++n)many.push_back(image(std::to_string(n)));auto all=counts.prepare(a,c::MediaRequestChannel::image,1,many);counts.commit(std::move(all));rejects([&]{counts.prepare(b,c::MediaRequestChannel::image,1,requests);},"Aggregate channel bound is shared, not renewed per owner");
 c::MediaRequestCatalog bytes;const auto byteA=bytes.attach(),byteB=bytes.attach();many.clear();const std::string path="C:\\"+std::string(32700,'a');for(unsigned n=0;n<520;++n){auto r=image(std::to_string(n));r.path=path;many.push_back(std::move(r));}auto first=bytes.prepare(byteA,c::MediaRequestChannel::image,1,many);bytes.commit(std::move(first));for(auto&r:many){r.kind=m::NotesMediaKind::video;r.workerPoster=true;}rejects([&]{bytes.prepare(byteB,c::MediaRequestChannel::video,1,many);},"Metadata-byte budget covers all channels, not only one provider");check(bytes.bindings(byteB,c::MediaRequestChannel::video).empty()&&bytes.bindings(byteA,c::MediaRequestChannel::image).size()==520,"Failed aggregate bound preserves accepted sibling state");
}
}
int main(){try{run();std::cout<<"PASS "<<checks<<" shared media metadata checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
