#include "native/media_request_broker.hpp"
#ifdef _WIN32
#include <objbase.h>
#include <array>
#include <atomic>
#include <cstdlib>
#include <iostream>
#include <new>
#include <stdexcept>
namespace {std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace n=endfield::native;namespace m=endfield::modules;
namespace {
unsigned checks{};void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}template<class F>void rejects(F&&fn,const char*why){bool failed{};try{fn();}catch(const std::exception&){failed=true;}check(failed,why);}
struct Window {HWND hwnd{};static constexpr UINT notice=WM_APP+247;Window(){hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,L"STATIC",L"Owned hidden shared media fixture",WS_POPUP,0,0,32,32,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);check(hwnd&&!IsWindowVisible(hwnd),"One explicit hidden HWND owns all module notices");}~Window(){if(hwnd)DestroyWindow(hwnd);}};
struct Gate {HANDLE entered=CreateEventW(nullptr,TRUE,FALSE,nullptr),release=CreateEventW(nullptr,TRUE,FALSE,nullptr);std::atomic<bool>blocked{};Gate(){check(entered&&release,"Owned worker fixture gate");}~Gate(){SetEvent(release);CloseHandle(entered);CloseHandle(release);}};
class Sequence final:public n::NativeNotesImageDecoder::Sequence {n::NotesImageInfo info_;public:explicit Sequence(bool gif):info_{2,2,gif?2u:1u,gif?m::NotesMediaKind::gif:m::NotesMediaKind::image,gif?std::vector<double>{600,.04}:std::vector<double>{},gif?600.04:0}{}const n::NotesImageInfo&info()const override{return info_;}n::NotesImageFrame decode(unsigned index)override{return {2,2,index,std::vector<std::uint8_t>(16,255)};}};
struct EngineProbe {n::NativeNotesVideoPlayback::Notify notify;bool stopped{},playing{};unsigned opens{},seeks{};double position{};};
class Engine final:public n::NativeNotesVideoPlayback::Engine {std::shared_ptr<EngineProbe>p_;public:explicit Engine(std::shared_ptr<EngineProbe>p):p_(std::move(p)){}~Engine()override{stop();}HRESULT open(const n::NotesVideoRequest&)override{++p_->opens;p_->notify(n::NativeNotesVideoPlayback::ready,S_OK);return S_OK;}HRESULT metadata(n::NotesVideoMetadata&out)override{out={2,2,10};return S_OK;}HRESULT play()override{p_->playing=true;return S_OK;}HRESULT pause()override{p_->playing=false;return S_OK;}HRESULT seek(double t)override{p_->position=t;++p_->seeks;p_->notify(n::NativeNotesVideoPlayback::seeked,S_OK);return S_OK;}double currentTime()const override{return p_->position;}HRESULT tick(std::int64_t&)override{return S_FALSE;}HRESULT transfer(void*,unsigned,unsigned)override{return E_NOTIMPL;}void stop()noexcept override{p_->stopped=true;p_->playing=false;}};
template<class F>void await(n::NativeMediaRequestBroker&broker,const Window&w,double time,F&&ready){const auto limit=GetTickCount64()+10000;for(;;){broker.accept(91,time);if(ready())break;const auto now=GetTickCount64();check(now<limit,"Bounded synthetic shared-worker completion");check(MsgWaitForMultipleObjectsEx(0,nullptr,static_cast<DWORD>(limit-now),QS_POSTMESSAGE,MWMO_INPUTAVAILABLE)==WAIT_OBJECT_0,"Only queued completion wakes the fixture owner");MSG message{};while(PeekMessageW(&message,w.hwnd,Window::notice,Window::notice,PM_REMOVE))check(message.lParam==0&&message.wParam==91,"Shared route carries only app generation");}MSG message{};while(PeekMessageW(&message,w.hwnd,Window::notice,Window::notice,PM_REMOVE)){} }
void run(const std::filesystem::path&shader){Window w;auto gate=std::make_shared<Gate>();n::Renderer renderer;renderer.initialize(w.hwnd,32,32,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests,true});n::NativeNotesImageDecoder decoder([](const auto&r){return n::NotesImageAccess{std::filesystem::u8path(r.path),r.accessLease};},{w.hwnd,Window::notice,91},[gate](const n::NotesImageRequest&r,n::NotesImageAccess){if(r.path.ends_with("blocked.png")&&!gate->blocked.exchange(true)){SetEvent(gate->entered);if(WaitForSingleObject(gate->release,10000)!=WAIT_OBJECT_0)throw std::runtime_error("Synthetic fixture gate timed out");}return std::make_unique<Sequence>(r.path.ends_with(".gif"));});n::NativeNotesImagePlayback images(decoder);std::vector<std::shared_ptr<EngineProbe>>engines;n::NativeNotesVideoPlayback video(renderer,{w.hwnd,Window::notice,91},[&](auto device,auto notify){check(device!=nullptr,"Native movies reuse the one renderer device");auto p=std::make_shared<EngineProbe>();p->notify=std::move(notify);engines.push_back(p);return std::make_unique<Engine>(p);});struct ReleaseGate{std::shared_ptr<Gate>gate;~ReleaseGate(){SetEvent(gate->release);}}releaseGate{gate};
 {
 n::NativeMediaRequestBroker broker(decoder,images,{w.hwnd,Window::notice,91},&video);rejects([&]{n::NativeMediaRequestBroker duplicate(decoder,images,{w.hwnd,Window::notice,92},&video);},"The same decoder cannot acquire a second request-union owner");const auto notes=broker.attachClient(),archive=broker.attachClient();std::array requests{n::NotesImagePlaybackRequest{{"same","C:\\Owned-fixture\\not-opened.gif",1,512},m::NotesMediaKind::gif}};
 check(broker.setImages(notes,1,requests,0)&&broker.setImages(archive,7,requests,0),"Notes and Archive submit independent visible unions");check(broker.findImage(notes,"same")&&broker.findImage(archive,"same")&&broker.findImage(notes,"same")!=broker.findImage(archive,"same"),"Local identity collision resolves to different retained records");await(broker,w,1,[&]{return broker.findImage(notes,"same")->frame&&broker.findImage(archive,"same")->frame;});const auto archiveFrame=broker.findImage(archive,"same")->frame;check(broker.pauseImage(notes,"same"),"Explicit Notes pause is scoped");check(broker.findImage(archive,"same")->state==m::NotesMediaState::playing,"Notes pause leaves Archive GIF playing");broker.hideImages(notes,1.1,true);check(!broker.findImage(notes,"same")->visible&&broker.findImage(notes,"same")->frame&&broker.findImage(archive,"same")->visible&&broker.findImage(archive,"same")->frame==archiveFrame,"Closing one module preserves sibling visibility/artwork");const auto closingFrame=broker.findImage(notes,"same")->frame;const auto closingFrameRevision=broker.findImage(notes,"same")->frameRevision;
 check(broker.setImages(notes,1,requests,2),"Reopening same generation restores its known identity");
 // Closing artwork remains available while the reopened reference is loading;
 // its non-null frame is not evidence that this new decode has completed.
 check(broker.findImage(notes,"same")->decodePending&&!broker.findImage(notes,"same")->wantsPlayback&&broker.findImage(notes,"same")->frame==closingFrame&&broker.findImage(archive,"same")->frame==archiveFrame,"Reopening preserves paused intent and both retained frames before decode completion");
 await(broker,w,2,[&]{return !broker.findImage(notes,"same")->decodePending;});
 check(broker.findImage(notes,"same")->frameRevision>closingFrameRevision&&broker.findImage(notes,"same")->frame&&broker.findImage(notes,"same")->state==m::NotesMediaState::paused&&!broker.findImage(notes,"same")->wantsPlayback&&!broker.findImage(notes,"same")->nextFrame&&broker.findImage(archive,"same")->frame==archiveFrame,"User-paused intent survives module reopen without resetting sibling frame");const auto requestCount=decoder.stats().requests;check(!broker.setImages(notes,1,requests,2)&&decoder.stats().requests==requestCount,"Unchanged owner metadata never resubmits decoder jobs");check(!broker.setImages(archive,6,requests,2)&&broker.findImage(archive,"same")->visible,"Stale Archive generation cannot hide current media");
 // Independent metadata imports share exactly that same serial worker. The
 // canceled codec call can finish, but its generation cannot publish to either
 // client, and the other client's still-pending validation remains requested.
 const std::array old{n::NotesImageRequest{"import","C:\\Owned-fixture\\blocked.png",1}};check(broker.setInspections(notes,2,old),"Source import enters shared worker");check(WaitForSingleObject(gate->entered,10000)==WAIT_OBJECT_0,"Injected codec gate entered without real file IO");const std::array other{n::NotesImageRequest{"import","C:\\Owned-fixture\\not-opened.png",1}};check(broker.setInspections(archive,3,other)&&broker.cancelInspections(notes,3),"Cancel only one client's import while sibling remains requested");SetEvent(gate->release);std::vector<n::NotesImageCompletion>complete;await(broker,w,3,[&]{auto batch=broker.drainInspections(archive,3);for(auto&result:batch)complete.push_back(std::move(result));return !complete.empty();});check(complete.size()==1&&complete[0].key=="import"&&complete[0].revision==1&&complete[0].info&&complete[0].info->kind==m::NotesMediaKind::image&&!complete[0].frame&&SUCCEEDED(complete[0].result),"Only current sibling receives complete metadata; validation pixels are released");check(broker.drainInspections(notes,2).empty()&&broker.drainInspections(notes,3).empty(),"Canceled/stale import cannot consume another client's completion");const auto decodes=decoder.stats().decodes;broker.setInspections(notes,4,other);std::vector<n::NotesImageCompletion>notesResult;await(broker,w,4,[&]{notesResult=broker.drainInspections(notes,4);return !notesResult.empty();});check(decoder.stats().decodes==decodes+1&&broker.drainInspections(archive,3).empty(),"Completed sibling import is excluded when another batch is added");broker.cancelInspections(notes,5);broker.cancelInspections(archive,4);
 std::array<n::NotesVideoRequest,5>movies;for(unsigned k=0;k<movies.size();++k)movies[k]={"movie"+std::to_string(k),"C:\\Owned-fixture\\not-opened.mp4",1,512,10,{},true};check(broker.setVideos(notes,1,movies,5)&&broker.setVideos(archive,1,movies,5),"Same-name movies union across both modules");check(broker.videoStats().visible==10&&broker.videoStats().engines==8,"Both modules share eight native engines rather than eight each");check(broker.findVideo(notes,"movie0")!=broker.findVideo(archive,"movie0"),"Movie records and texture identities remain separately scoped");n::NotesImageFrame poster{2,2,0,std::vector<std::uint8_t>(16,255)};for(unsigned pass=0;pass<3;++pass){broker.accept(91,5);for(const auto c:{notes,archive})for(const auto&r:movies)broker.setVideoPoster(c,r.key,1,1,&poster);check(broker.videoStats().engines<=8,"Poster scheduling never exceeds shared engine bound");}broker.accept(91,5);for(const auto c:{notes,archive})for(const auto&r:movies){const auto*record=broker.findVideo(c,r.key);check(record&&record->state==m::NotesMediaState::paused&&!record->textureID.empty(),"Every queued original movie gets a still without sound/playback");}check(!broker.requiresFrames(),"Paused shared movies schedule no permanent frames");const auto archivePoster=broker.findVideo(archive,"movie0")->textureID;const auto notesPoster=broker.findVideo(notes,"movie0")->textureID;check(archivePoster!=notesPoster,"Same-name original movies publish independent poster resources");
 const std::array<n::Vertex,4>vertices{{{{-1,1,0},{0,0}},{{1,1,0},{1,0}},{{1,-1,0},{1,1}},{{-1,-1,0},{0,1}}}};constexpr std::array<std::uint32_t,6>indices{0,1,2,0,2,3};renderer.setMesh("owned.broker.quad",1,{vertices,indices});n::DrawObject draw;draw.sourceID="owned.broker.draw";draw.meshID="owned.broker.quad";draw.textureID=notesPoster;renderer.setDrawList(std::span(&draw,1));broker.hideVideos(notes,6,true);check(broker.findVideo(archive,"movie0")->visible&&broker.findVideo(archive,"movie0")->textureID==archivePoster,"Hiding Notes movies leaves Archive poster and visible records intact");check(!broker.retireVideo(notes,"movie0"),"Borrowed poster cannot retire before composition detaches it");renderer.clearDrawList();check(broker.retireVideo(notes,"movie0"),"Retirement succeeds after caller replacement publication");renderer.removeMesh("owned.broker.quad");broker.pauseImage(archive,"same");const auto before=decoder.stats();const auto nativeBefore=video.stats();allocations=0;counting=true;try{for(unsigned k=0;k<120;++k){broker.sample(7+double(k)/60);broker.requiresFrames();broker.nextWakeTime();broker.findImage(archive,"same");broker.findVideo(archive,"movie0");}}catch(...){counting=false;throw;}counting=false;check(allocations==0&&decoder.stats().requests==before.requests&&video.stats().ticks==nativeBefore.ticks,"120 settled owner frames allocate, decode and query no new media");
 check(!broker.detachClient(archive),"Active module cannot detach published references");broker.hideImages(notes,10);broker.hideImages(archive,10);broker.hideVideos(archive,10);for(const auto&r:movies){if(r.key!="movie0")check(broker.retireVideo(notes,r.key),"Hidden Notes movie retires individually");check(broker.retireVideo(archive,r.key),"Hidden Archive movie retires independently");}check(broker.retireImage(notes,"same")&&broker.retireImage(archive,"same"),"Hidden image identities retire without sibling interference");check(broker.collectRetired()&&broker.detachClient(notes)&&broker.detachClient(archive),"Independent clear/retire/detach leaves no broker client references");check(renderer.stats().mediaLiveBytes==0,"Existing renderer releases all shared media outputs");
 }
 const auto done=decoder.duplicateWorkerHandle();decoder.stop();check(WaitForSingleObject(done,10000)==WAIT_OBJECT_0,"One existing serial decoder shuts down through its owner");CloseHandle(done);check(!IsWindowVisible(w.hwnd)&&renderer.stats().presents==0,"Synthetic broker never opens files, executes audio or shows UI");renderer.reset();}
}
int wmain(int argc,wchar_t**argv){const auto initialized=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(initialized)&&argc==2,"Pass retained native shader for hidden shared media fixture");run(argv[1]);CoUninitialize();std::cout<<"PASS "<<checks<<" shared media broker checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(initialized))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(){return 0;}
#endif
