#include "modules/module_strings.hpp"
#include <cstdio>
#include <iostream>
#include <stdexcept>
namespace c=endfield::core;namespace m=endfield::modules;namespace n=endfield::native;
namespace {
unsigned checks{};void check(bool v,const char*why){++checks;if(!v)throw std::runtime_error(why);}template<class F>void rejects(F f){bool failed{};try{f();}catch(const std::exception&){failed=true;}check(failed,"Malformed preference text rejects");}
std::string id(unsigned value){char s[64];std::snprintf(s,sizeof(s),"00000000-0000-0000-0000-%012u",value);return s;}
void catalog(){for(auto language:{c::Language::system,c::Language::english,c::Language::simplifiedChinese,c::Language::traditionalChinese,c::Language::japanese,c::Language::korean}){
    const auto shelf=m::fileShelfStrings(language);const auto style=m::shelfPresentationStyle(language);const auto clip=m::clipboardStrings(language);const auto events=m::eventLogStrings(language);const auto work=m::workModeStrings(language);
    check(style.heading==c::localized("Temporary File Shelf","文件暂存架",language),"Original Shelf module heading uses catalog");check(clip.heading==c::localized("Clipboard Cache","剪贴板",language),"Original Clipboard heading uses catalog");check(events.heading==c::localized("Event Log","事件日志",language),"Original Event Log heading uses catalog");check(work.heading==c::localized("Work Mode","工作模式",language),"Original Work Mode heading uses catalog");
    check(events.categories==m::EventLogStrings{}.categories&&events.cancel=="Cancel"&&events.confirm=="Clear all saved events?","Original non-localized Event Log literals stay source-authored");
    const std::array<std::string_view,1>count{"{count}"};check(shelf.selectedStatus==c::localized("{0} selected · Drag to copy","已选 {0} 项 · 拖出以复制",language,count),"Shelf keeps original argument placement");
    const std::array<std::string_view,2>values{"12","20"};check(c::renderTranslation(clip.countPattern,values)==c::localized("{0} / {1} items · Click to copy","{0} / {1} 项 · 点击复制",language,values),"Clipboard complete source format preserves Japanese/Korean spacing");
    const std::array<std::string_view,1>minutes{"30"};check(work.presets[1]==c::localized("{0} min","{0} 分",language,minutes),"Preset minute suffix uses original interpolation");
 }
 check(m::fileShelfStrings(c::Language::simplifiedChinese)==m::FileShelfStrings::simplifiedChinese(),"Original Chinese Shelf state fixture remains exact");check(m::workModeStrings(c::Language::simplifiedChinese)==m::WorkModeStrings{},"Original Chinese Work Mode oracle inputs remain exact");
 check(m::clipboardStrings(c::Language::japanese).countPattern=="{0} / {1}件 · クリックでコピー","Japanese source does not insert legacy suffix space");check(m::workModeStrings(c::Language::korean).presets[0]=="5분","Korean source minute placement exact");
}
void shelf(){unsigned reads{},mutations{};std::vector<m::FileShelfItem>rows;for(unsigned k=1;k<=20;++k)rows.push_back({id(k),"Original filename "+std::to_string(k),"C:\\synthetic\\file.png","Opaque platform type"});m::FileShelfState state(rows,{[&]{++reads;return rows;},[&]{++reads;},[&](auto){++mutations;return 0u;},[&](auto){++mutations;},[&]{++mutations;}},{},m::fileShelfStrings(c::Language::english));
 state.activate();state.selectItem(id(6),{});state.selectItem(id(9),{true,false});state.scrollBy(35.5);state.perform("shelf:clear");state.setDropTarget(true);state.takeEvents();const auto selected=state.selectedIDs();const auto offset=state.scrollOffset();const auto beforeReads=reads;
 for(auto lang:{c::Language::japanese,c::Language::korean,c::Language::traditionalChinese,c::Language::english}){check(state.setStrings(m::fileShelfStrings(lang)),"Shelf applies changed strings");check(state.selectedIDs()==selected&&state.scrollOffset()==offset&&state.confirmingClear()&&state.dropTarget()&&state.active(),"Shelf preference keeps selection/scroll/confirmation/drop");check(reads==beforeReads&&!mutations&&state.takeEvents().empty(),"Shelf language never reads files, persists, or starts animation");check(state.items()[0].name=="Original filename 1"&&state.items()[0].typeDescription=="Opaque platform type","Shelf metadata is opaque");const auto revision=state.revision();check(!state.setStrings(m::fileShelfStrings(lang))&&state.revision()==revision,"Unchanged Shelf preferences are a no-op");}
 auto invalid=state.strings();invalid.itemsStatus="no count";const auto revision=state.revision();rejects([&]{state.setStrings(invalid);});check(state.revision()==revision,"Invalid Shelf strings do not publish");
 m::ShelfPresentation presentation;auto style=m::shelfPresentationStyle(c::Language::english);style.errorColor=m::ShelfColor{1,0,0,1};presentation.update(state,style);const auto old=presentation.stats();style.dark=false;style.accent={.4,.2,.8,1};style.lightDropColor=m::ShelfColor{.1,.05,.2,1};presentation.update(state,style);check(presentation.stats().chromeBuilds>old.chromeBuilds&&state.scrollOffset()==offset&&state.selectedIDs()==selected,"Shelf theme rebuilds bounded artwork without resetting state");check(!presentation.update(state,style),"Warm Shelf theme update is idle");
}
void clipboard(){n::ClipboardSnapshot source;source.capacity=20;for(unsigned k=1;k<=12;++k)source.rows.push_back({k,k==1,n::ClipboardKind::text,"Opaque payload "+std::to_string(k),{}});unsigned reads{},copies{};n::ClipboardState state({[&]{++reads;return source;},[&](auto){++copies;return true;},{},{},{}},m::clipboardStrings(c::Language::english));state.activate();state.selectNext(-1);state.scrollBy(-12.5);state.copySelection();state.takeEvents();const auto selected=state.selected();const auto offset=state.scrollOffset();const auto beforeReads=reads;
 state.setStrings(m::clipboardStrings(c::Language::korean));check(state.selected()==selected&&state.scrollOffset()==offset&&state.active()&&state.copiedFeedback(),"Clipboard preference keeps selection, offset and copied semantic state");check(state.status()=="복사됨"&&state.rows()[0].preview=="Opaque payload 1","Only copied status translates, payload remains untouched");check(reads==beforeReads&&copies==1&&state.takeEvents().empty(),"Clipboard preference never reads/copies clipboard or adds motion");state.perform("clipboard:clear");state.takeEvents();state.setStrings(m::clipboardStrings(c::Language::japanese));check(state.confirmingClear()&&state.actions()[0].label=="キャンセル","Open Clipboard confirmation translates in place");const auto revision=state.revision();check(!state.setStrings(m::clipboardStrings(c::Language::japanese))&&state.revision()==revision,"Same Clipboard strings no-op");auto invalid=state.strings();invalid.countPattern="{0}";rejects([&]{state.setStrings(invalid);});check(state.revision()==revision,"Malformed Clipboard count leaves state unchanged");
}
void imageLabels(){n::ClipboardSnapshot input;input.capacity=10;input.rows={{1,false,n::ClipboardKind::image,"Image · 640 × 480",{}},{2,false,n::ClipboardKind::text,"Image · private text",{}},{3,false,n::ClipboardKind::image,"Opaque caption",{}}};n::ClipboardState state({[&]{return input;},[](auto){return false;},{},{},{}},m::clipboardStrings(c::Language::english));for(auto language:{c::Language::japanese,c::Language::korean,c::Language::traditionalChinese}){state.setStrings(m::clipboardStrings(language));check(state.displayPreview(state.rows()[0])==c::localized("Image · ","图片 · ",language)+"640 × 480","Original image-generated prefix alone translates");check(state.displayPreview(state.rows()[1])==input.rows[1].preview&&state.displayPreview(state.rows()[2])==input.rows[2].preview,"User text and arbitrary image captions stay opaque");}input.status=state.strings().copied;state.perform("clipboard:1:copy");const auto opaque=state.status();state.setStrings(m::clipboardStrings(c::Language::english));check(state.status()==opaque&&!state.copiedFeedback(),"Provider text coinciding with copied translation is never reclassified");}
void events(){m::EventLogSnapshot snapshot;for(unsigned k=1;k<=20;++k)snapshot.events.push_back({id(k),m::EventKind::workStarted,double(k),{{"kind","countdown"},{"seconds","300"}}});unsigned reads{},clears{};m::EventLogState state({[&]{++reads;return snapshot;},[&]{++clears;},[](double){return "01-02 03:04:05";}},m::eventLogStrings(c::Language::english));state.activate();state.perform("eventLog:category:work");state.selectNext(-1);state.scrollBy(-5.25);state.perform("eventLog:clear");state.acknowledgeChanges();const auto selected=state.selected();const auto offset=state.scrollOffset();const auto beforeReads=reads;const auto title=state.visibleRows()[0].title;const auto detail=state.visibleRows()[0].detail;
 state.setStrings(m::eventLogStrings(c::Language::korean));check(state.selected()==selected&&state.scrollOffset()==offset&&state.category()==m::EventCategory::work&&state.confirmingClear()&&state.active(),"Event Log language preserves filter, confirmation and scroll");check(reads==beforeReads&&!clears&&state.pendingChanges().empty(),"Event Log language neither refreshes recorder nor creates transition");check(state.visibleRows()[0].title==title&&state.visibleRows()[0].detail==detail,"Event payloads and literal titles remain source-authored");const auto revision=state.revision();check(!state.setStrings(m::eventLogStrings(c::Language::korean))&&revision==state.revision(),"Equal Event Log preferences idle");auto invalid=state.strings();invalid.heading=std::string(1,char(0xff));rejects([&]{state.setStrings(invalid);});check(state.revision()==revision,"Malformed Event label not published");
}
void work(){m::WorkModeController controller;m::WorkModePresentation state(controller,m::workModeStrings(c::Language::english));state.activate(2);state.perform("work:start",2);const auto before=state.layout(2.1);const auto feedback=state.feedback(2.1);const auto deadline=controller.completionDeadline();const auto revision=controller.revision();const auto clock=state.clockRevision();
 state.setStrings(m::workModeStrings(c::Language::japanese));const auto after=state.layout(2.1);check(before.clockY==after.clockY&&before.clockScale==after.clockScale&&before.configurationOpacity==after.configurationOpacity&&after.active,"Changing Work Mode language never settles/restarts expanding source layout");check(state.feedback(2.1).clock==feedback.clock&&state.feedback(2.1).scale==feedback.scale&&controller.completionDeadline()==deadline&&controller.revision()==revision&&state.clockRevision()==clock,"Clock, deadline and pressed timing retained");state.perform("work:reset",2.2);state.refresh(3);state.setCustomDuration("invalid",3);state.setFocusStatus("Opaque platform status",true,3);state.setStrings(m::workModeStrings(c::Language::korean));check(state.phaseText()==state.strings().invalidDuration&&state.focusStatus()=="Opaque platform status","Existing invalid duration translates, platform status stays opaque");const auto stable=state.revision();check(!state.setStrings(m::workModeStrings(c::Language::korean))&&state.revision()==stable,"Equal Work Mode strings idle");auto invalid=state.strings();invalid.ready=std::string(5000,'x');rejects([&]{state.setStrings(invalid);});check(state.revision()==stable,"Malformed Work Mode strings do not publish");
}
}
int main(){try{catalog();shelf();clipboard();imageLabels();events();work();std::cout<<"PASS "<<checks<<" retained module preference checks\n";}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
