#include "native/notes_image_playback.hpp"
#ifdef _WIN32
#include <array>
#include <iostream>
#include <stdexcept>
namespace n=endfield::native;namespace m=endfield::modules;
namespace {
unsigned checks{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}
struct Window {HWND hwnd{};ATOM atom{};static constexpr UINT message=WM_APP+249;Window(){WNDCLASSW w{};w.lpfnWndProc=DefWindowProcW;w.hInstance=GetModuleHandleW(nullptr);w.lpszClassName=L"EndfieldOwnedImagePlayback";atom=RegisterClassW(&w);check(atom!=0,"Register hidden owned playback fixture");hwnd=CreateWindowExW(WS_EX_TOOLWINDOW,w.lpszClassName,L"Synthetic media playback",WS_POPUP,0,0,1,1,nullptr,nullptr,w.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Playback test never opens visible UI");}~Window(){if(hwnd)DestroyWindow(hwnd);if(atom)UnregisterClassW(reinterpret_cast<LPCWSTR>(static_cast<ULONG_PTR>(atom)),GetModuleHandleW(nullptr));}};
class Sequence final:public n::NativeNotesImageDecoder::Sequence {n::NotesImageInfo info_{2,2,2,m::NotesMediaKind::gif,{600,.04},600.04};public:const n::NotesImageInfo&info()const override{return info_;}n::NotesImageFrame decode(unsigned index)override{return {2,2,index,std::vector<std::uint8_t>(16,static_cast<std::uint8_t>(index+1))};}};
void await(n::NativeNotesImagePlayback&owner,const Window&w,double time){const auto deadline=GetTickCount64()+10000;for(;;){if(owner.accept(7,time))break;const auto now=GetTickCount64();check(now<deadline,"Bounded synthetic playback completion");check(MsgWaitForMultipleObjectsEx(0,nullptr,static_cast<DWORD>(deadline-now),QS_POSTMESSAGE,MWMO_INPUTAVAILABLE)==WAIT_OBJECT_0,"Completion wakes existing owner event queue");MSG message{};while(PeekMessageW(&message,w.hwnd,Window::message,Window::message,PM_REMOVE))check(message.lParam==0,"Playback notice is generation-only");}MSG message{};while(PeekMessageW(&message,w.hwnd,Window::message,Window::message,PM_REMOVE)){} }
void run(){Window w;n::NativeNotesImageDecoder decoder([](const n::NotesImageRequest&r){return n::NotesImageAccess{std::filesystem::u8path(r.path),{}};},{w.hwnd,Window::message,7},[](const n::NotesImageRequest&,n::NotesImageAccess){return std::make_unique<Sequence>();});
    n::NativeNotesImagePlayback owner(decoder);std::array requests{n::NotesImagePlaybackRequest{{"gif","C:\\owned-synthetic\\tiny.gif",1,512},m::NotesMediaKind::gif}};check(owner.setVisible(requests,1),"First visible reference queues initial decode");const auto*record=owner.find("gif");check(record&&record->state==m::NotesMediaState::loading&&record->wantsPlayback&&!owner.nextWakeTime(),"GIF wants autoplay on first load without polling while decoding");
    owner.pause("gif");await(owner,w,2);check(record->state==m::NotesMediaState::paused&&record->frame->index==0&&!owner.nextWakeTime(),"Pausing during first load wins over initial GIF autoplay");check(owner.play("gif",10)&&owner.nextWakeTime()==610,"Source600second frame delay becomes one exact external deadline");
    const auto before=decoder.stats();for(unsigned i=0;i<120;++i)check(!owner.sample(10+double(i))&&record->frame->index==0,"Pointer/frame samples before GIF deadline do not decode");check(before.requests==decoder.stats().requests&&before.decodes==decoder.stats().decodes,"No60Hz codec work on long-delay GIF");
    check(!owner.sample(610)&&record->decodePending&&!owner.nextWakeTime(),"Due frame queues once and removes deadline until completion");await(owner,w,610.3);check(record->frame->index==1&&owner.nextWakeTime()&&std::abs(*owner.nextWakeTime()-610.34)<1e-9,"Next delay starts from accepted decode completion, matching source scheduler");
    owner.hide(611,true);const auto image=record->frame;check(record->state==m::NotesMediaState::hidden&&record->wantsPlayback&&record->frame==image&&owner.nextWakeTime()==611.6,"Hide cancels decoder/deadline but keeps bounded finite artwork and playback intent");check(!owner.sample(611.59)&&record->frame==image,"Closing artwork remains through source retention interval");check(owner.sample(611.6)&&!record->frame&&!owner.nextWakeTime(),"Artwork expires once after.6seconds and clock goes idle");
    owner.setVisible(requests,620);await(owner,w,621);check(record->state==m::NotesMediaState::playing&&record->frame->index==0&&owner.nextWakeTime()==1221,"Reopen starts source GIF frame0 and restores playback intent");owner.pause("gif");owner.hide(622);owner.setVisible(requests,623);await(owner,w,624);check(record->state==m::NotesMediaState::paused&&!owner.nextWakeTime(),"User-paused GIF remains paused after hide/show");
    check(!owner.setVisible(requests,625),"Repeated visible media does not reset native decoder");owner.hide(626);check(owner.retire("gif")&&!owner.find("gif")&&image->straightRGBA[0]==2,"Explicit retirement preserves already borrowed finite image snapshot");
    // Same decoder can paint an image reference using only its first frame,
    // even when the underlying file now happens to contain GIF metadata.
    requests[0].image.revision=2;requests[0].kind=m::NotesMediaKind::image;owner.setVisible(requests,630);await(owner,w,631);record=owner.find("gif");check(record->state==m::NotesMediaState::ready&&!record->wantsPlayback&&!owner.nextWakeTime()&&!owner.play("gif",632),"Persisted image kind stays still; no accidental animation after external file replacement");owner.hide(633);
    const auto done=decoder.duplicateWorkerHandle();decoder.stop();check(WaitForSingleObject(done,10000)==WAIT_OBJECT_0,"Playback owner uses shared worker teardown");CloseHandle(done);check(!IsWindowVisible(w.hwnd),"Playback test has no visible window or real file access");}
}
int main(){try{run();std::cout<<"PASS "<<checks<<" Notes image playback checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(){return 0;}
#endif
