#include "tools/notes_preview.hpp"
#include "native/module_scene.hpp"
#ifdef _WIN32
#include <objbase.h>
#include <array>
#include <cmath>
#include <fstream>
#include <iostream>
namespace n=endfield::native;namespace t=endfield::tools;namespace c=endfield::core;namespace a=endfield::app;namespace d=ehud::data;
namespace {
unsigned checks{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}
struct Window {HWND hwnd{};ATOM atom{};Window(){WNDCLASSW w{};w.lpfnWndProc=DefWindowProcW;w.hInstance=GetModuleHandleW(nullptr);w.lpszClassName=L"EndfieldOwnedNotesImport";atom=RegisterClassW(&w);check(atom!=0,"Register owned import fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,w.lpszClassName,L"Hidden synthetic Notes import",WS_POPUP,0,0,1280,800,nullptr,nullptr,w.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Import fixture remains hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);if(atom)UnregisterClassW(reinterpret_cast<LPCWSTR>(static_cast<ULONG_PTR>(atom)),GetModuleHandleW(nullptr));}};
struct Temp {std::filesystem::path path=std::filesystem::absolute(std::filesystem::temp_directory_path())/("endfield-owned-import-"+d::makeUUID());Temp(){check(std::filesystem::create_directory(path),"Create only a new owned fixture directory");}~Temp(){std::error_code e;std::filesystem::remove_all(path,e);}};
std::string utf8(const std::filesystem::path&p){const auto s=p.u8string();return {reinterpret_cast<const char*>(s.data()),s.size()};}
std::string ascii(const wchar_t*p){std::string s;for(;*p;++p){check(*p>0&&*p<128,"Build pins are ASCII");s.push_back(static_cast<char>(*p));}return s;}
void write(const std::filesystem::path&p,std::span<const std::uint8_t>b){std::ofstream f(p,std::ios::binary);f.write(reinterpret_cast<const char*>(b.data()),static_cast<std::streamsize>(b.size()));check(bool(f),"Write tiny image only beneath owned temporary fixture");}
std::vector<std::uint8_t>gif(){std::vector<std::uint8_t>b{'G','I','F','8','9','a',2,0,2,0,0x81,0,0,0,0,0,255,0,0,0,255,0,0,0,255};for(unsigned color:{1u,2u}){const std::array<std::uint8_t,18>header{0x21,0xf9,4,4,10,0,0,0,0x2c,0,0,0,0,2,0,2,0,0};b.insert(b.end(),header.begin(),header.end());b.push_back(2);std::vector<std::uint8_t>data;unsigned bits{},buffer{};auto code=[&](unsigned v){buffer|=v<<bits;bits+=3;while(bits>=8){data.push_back(static_cast<std::uint8_t>(buffer));buffer>>=8;bits-=8;}};for(unsigned i=0;i<4;++i){code(4);code(color);}code(5);if(bits)data.push_back(static_cast<std::uint8_t>(buffer));b.push_back(static_cast<std::uint8_t>(data.size()));b.insert(b.end(),data.begin(),data.end());b.push_back(0);}b.push_back(0x3b);return b;}
void run(const std::filesystem::path&shader,const n::NativeNotesControlsAssets&assets,bool shared=false){Window window;Temp temp;const auto dataRoot=temp.path/L"synthetic-store",pngPath=temp.path/L"owned.png",gifPath=temp.path/L"owned.gif";
    constexpr std::uint8_t png[]{137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,2,0,0,0,2,8,6,0,0,0,114,182,13,36,0,0,0,23,73,68,65,84,120,156,5,193,1,1,0,0,0,130,32,166,247,220,64,36,161,193,1,61,87,5,124,22,194,63,189,0,0,0,0,73,69,78,68,174,66,96,130};write(pngPath,png);write(gifPath,gif());
    n::Renderer renderer;renderer.initialize(window.hwnd,1280,800,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests});const auto camera=n::layerViewportProjection(1280,800);renderer.setCamera(camera);n::LayerRasterizer raster;n::LayerComposition composition;
    constexpr UINT sharedNotice=WM_APP+245;constexpr UINT_PTR sharedGeneration=99;
    std::unique_ptr<n::NativeNotesImageDecoder>decoder;std::unique_ptr<n::NativeNotesImagePlayback>images;std::unique_ptr<n::NativeMediaRequestBroker>broker;n::NativeMediaRequestBroker::Client client{},sibling{};
    if(shared){decoder=std::make_unique<n::NativeNotesImageDecoder>([](const n::NotesImageRequest&r){return n::NotesImageAccess{std::filesystem::u8path(r.path),r.accessLease};},n::NotesImageRoute{window.hwnd,sharedNotice,sharedGeneration});images=std::make_unique<n::NativeNotesImagePlayback>(*decoder);broker=std::make_unique<n::NativeMediaRequestBroker>(*decoder,*images,n::NotesImageRoute{window.hwnd,sharedNotice,sharedGeneration});client=broker->attachClient();sibling=broker->attachClient();const std::array requests{n::NotesImagePlaybackRequest{{"archive.poster",utf8(pngPath),1,64,true},endfield::modules::NotesMediaKind::image}};broker->setImages(sibling,1,requests,0);}
    auto notesOwner=std::make_unique<t::NotesPreview>(window.hwnd,raster,dataRoot,assets,false,std::filesystem::path{},std::span<const d::Note>{},t::NotesPreviewMediaOptions{broker.get(),client});auto&notes=*notesOwner;const a::ClientMetrics metrics{1280,800,96,1,1280,800};notes.resize(metrics);c::source::DesktopChromeSettings settings;settings.viewport={0,0,1280,800};settings.module=c::Module::notes;settings.sourceShell=true;const auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;double now{};
    auto frame=[&]{if(broker){broker->sample(now);notes.refreshSharedMedia(now);}notes.update(center,settings,1,now,false);notes.upload(renderer);composition.setEntries(renderer,notes.entries());notes.collected(renderer);composition.present(renderer);renderer.draw(false);};frame();
    n::LayerScene empty(raster);empty.load(d::Json::Object{{"bounds",d::Json::Array{0,0,400,334}},{"children",d::Json::Array{}}},{});n::NativeModuleSurface surface(empty,c::Module::notes);surface.update(center,settings,notes.modulePresentation().current,1);const auto projection=c::Projection::viewport(camera*surface.pose().contentWorld,1280,800);
    auto click=[&](c::Point local){const auto p=projection.project(local);check(p.has_value(),"Original module plane projects chooser point");check(notes.pointer({a::PointerKind::down,a::PointerButton::left,p->x,p->y},now),"Owned Notes pointer activates source media control");notes.pointer({a::PointerKind::up,a::PointerButton::left,p->x,p->y},now);};
    click({249,309});now=.2;frame();check(!notes.pointerLocked(),"Source media chooser preserves live mouse tilt while open");click({120,233});MSG actionMessage{};check(PeekMessageW(&actionMessage,window.hwnd,t::NotesPreview::mediaActionMessage,t::NotesPreview::mediaActionMessage,PM_REMOVE)!=FALSE,"Chooser requests owner native picker without opening external UI");const auto action=notes.takeMediaAction(actionMessage.wParam);check(action&&action->kind==t::NotesMediaAction::Kind::chooseLocal,"Correct source chooser action reaches owner route");
    const std::array paths{utf8(pngPath),utf8(gifPath)};check(notes.importMedia(paths,action->workspacePoint,now),"Owner feeds only two newly created fixture files into asynchronous import");
    auto loaded=[&]{std::size_t count{};for(const auto&e:notes.entries())if(e.after.size()==4&&!e.after[0].textureID.empty()&&e.after[0].sourceID.find("media")!=std::string::npos)++count;return count;};
    auto waitFor=[&](auto predicate){const auto deadline=GetTickCount64()+10000;while(!predicate()){const auto tick=GetTickCount64();check(tick<deadline,"Bounded full owner import/decode completion");check(MsgWaitForMultipleObjectsEx(0,nullptr,static_cast<DWORD>(deadline-tick),QS_POSTMESSAGE,MWMO_INPUTAVAILABLE)==WAIT_OBJECT_0,"Actual worker notices wake existing owned event queue");MSG message{};while(PeekMessageW(&message,window.hwnd,t::NotesPreview::mediaNoticeMessage,t::NotesPreview::mediaNoticeMessage,PM_REMOVE)){check(message.lParam==0,"Worker never posts raw owner pointer");notes.message({window.hwnd,message.message,message.wParam,message.lParam},now);}if(broker)while(PeekMessageW(&message,window.hwnd,sharedNotice,sharedNotice,PM_REMOVE)){check(message.wParam==sharedGeneration&&message.lParam==0,"Only one app-owned media route wakes shared modules");broker->accept(message.wParam,now);notes.refreshSharedMedia(now);}frame();check(!notes.mediaError(),"Original WIC import and owner persistence completed without fallback error");}};
    waitFor([&]{return loaded()==2&&(!broker||broker->findImage(sibling,"archive.poster")->frame);});if(broker)check(!notes.nextWakeTime(),"Borrowed Notes owns no second media deadline");auto nextWake=[&]{return broker?broker->nextWakeTime():notes.nextWakeTime();};check(nextWake().has_value(),"Imported GIF schedules one existing-clock deadline");{d::NotesStore saved(dataRoot);check(saved.notes().size()==3,"One original synthetic text note plus two media references persisted");unsigned image{},animation{};for(const auto&note:saved.notes())if(note.media){const auto meta=d::Json::parse(*note.media);check(meta["referencePlatform"].string()=="windows"&&meta["pixelWidth"].integer()==2&&meta["pixelHeight"].integer()==2,"Persisted metadata comes from real decoded tiny fixture");if(meta["kind"].string()=="gif"){++animation;check(meta["frameCount"].integer()==2&&std::abs(meta["duration"].number()-.2)<1e-9,"GIF frame count/duration survive full import path");}else ++image;}check(image==1&&animation==1,"PNG/GIF types are preserved without flattening");}
    const auto uploads=renderer.stats().textureUploads;now=*nextWake();if(broker)broker->sample(now);notes.deadline(now);waitFor([&]{return renderer.stats().textureUploads>uploads;});check(loaded()==2,"Next actual GIF frame reuses both retained card bindings");
    notes.setMediaActive(false,now,true);now+=.61;if(broker)broker->sample(now);notes.deadline(now);frame();if(broker)check(broker->findImage(sibling,"archive.poster")->visible&&broker->findImage(sibling,"archive.poster")->frame,"Notes import/hide leaves sibling module media untouched");check(!notes.nextWakeTime()&&loaded()==0,"Closing expires source artwork and leaves no hidden image deadline");composition.setEntries(renderer,{});notes.release(renderer);check(!IsWindowVisible(window.hwnd)&&renderer.stats().presents==0,"Complete import stayed offscreen with no real user data, file picker or desktop capture");notesOwner.reset();if(broker){broker->hideImages(sibling,now);check(broker->retireImage(sibling,"archive.poster")&&broker->collectRetired()&&broker->detachClient(client)&&broker->detachClient(sibling),"Explicit root detaches clients only after Notes resource release and destruction");const auto stopped=decoder->duplicateWorkerHandle();decoder->stop();check(WaitForSingleObject(stopped,10000)==WAIT_OBJECT_0,"Root alone shuts down the single shared import worker");CloseHandle(stopped);}
}
}
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);if(FAILED(hr))return 1;int result{};try{check(argc==5,"Pass shader, Notes assets, manifest SHA, source commit");n::NativeNotesControlsAssets assets(std::filesystem::absolute(argv[2]),{ascii(argv[3]),ascii(argv[4])});run(argv[1],assets);run(argv[1],assets,true);std::cout<<"PASS "<<checks<<" full Notes PNG/GIF import checks\n";}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';result=1;}CoUninitialize();return result;}
#else
int main(){return 0;}
#endif
