#include "native/notes_video_playback.hpp"
#ifdef _WIN32
#include <d3d11.h>
#include <dxgi.h>
#include <wrl/client.h>
#include <algorithm>
#include <array>
#include <atomic>
#include <cmath>
#include <fstream>
#include <iostream>
#include <thread>
namespace n=endfield::native;namespace m=endfield::modules;using Microsoft::WRL::ComPtr;
namespace {
unsigned checks{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}template<class F>void rejects(F f,const char*s){bool caught{};try{f();}catch(const std::exception&){caught=true;}check(caught,s);}
struct Window {HWND hwnd{};ATOM atom{};static constexpr UINT notice=WM_APP+250;Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"EndfieldOwnedNotesVideo";atom=RegisterClassW(&c);check(atom!=0,"Register owned video fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,c.lpszClassName,L"Hidden synthetic video",WS_POPUP,0,0,32,32,nullptr,nullptr,c.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Video fixture stays hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);if(atom)UnregisterClassW(reinterpret_cast<LPCWSTR>(static_cast<ULONG_PTR>(atom)),GetModuleHandleW(nullptr));}};
struct Probe {n::NativeNotesVideoPlayback::Notify notify;double position{};bool playing{},fresh{true},stopped{};unsigned frames{},opens{},seeks{};HRESULT transferError{S_OK};std::array<std::uint8_t,4>pixel{0,0,255,255};std::shared_ptr<void>lease;};
class Engine final:public n::NativeNotesVideoPlayback::Engine {
    std::shared_ptr<Probe>p_;
public:explicit Engine(std::shared_ptr<Probe>p):p_(std::move(p)){}~Engine()override{stop();}
    HRESULT open(const n::NotesVideoRequest&r)override{++p_->opens;p_->lease=r.accessLease;p_->notify(n::NativeNotesVideoPlayback::ready|n::NativeNotesVideoPlayback::firstFrame,S_OK);return S_OK;}
    HRESULT metadata(n::NotesVideoMetadata&out)override{out={4,4,10};return S_OK;}
    HRESULT play()override{p_->playing=true;return S_OK;}HRESULT pause()override{p_->playing=false;return S_OK;}
    HRESULT seek(double t)override{p_->position=t;++p_->seeks;p_->fresh=true;p_->notify(n::NativeNotesVideoPlayback::seeked,S_OK);return S_OK;}
    double currentTime()const override{return p_->position;}
    HRESULT tick(std::int64_t&pts)override{pts=static_cast<std::int64_t>(p_->position*10000000);if(!p_->fresh)return S_FALSE;p_->fresh=false;return S_OK;}
    HRESULT transfer(void*raw,unsigned width,unsigned height)override{if(FAILED(p_->transferError)){const auto error=p_->transferError;p_->transferError=S_OK;return error;}ComPtr<ID3D11Texture2D>texture;const auto hr=static_cast<IDXGISurface*>(raw)->QueryInterface(IID_PPV_ARGS(&texture));if(FAILED(hr))return hr;ComPtr<ID3D11Device>device;texture->GetDevice(&device);ComPtr<ID3D11DeviceContext>context;device->GetImmediateContext(&context);if(width!=4||height!=4)return E_INVALIDARG;std::array<std::uint8_t,64>pixels;for(unsigned i=0;i<pixels.size();i+=4)std::copy(p_->pixel.begin(),p_->pixel.end(),pixels.begin()+i);context->UpdateSubresource(texture.Get(),0,nullptr,pixels.data(),16,0);++p_->frames;return S_OK;}
    void stop()noexcept override{p_->playing=false;p_->stopped=true;p_->lease.reset();}
};
void run(const std::filesystem::path&shader){Window w;n::Renderer renderer;renderer.initialize(w.hwnd,32,32,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests,true});std::vector<std::shared_ptr<Probe>>probes;HRESULT nextTransferError=S_OK;n::NativeNotesVideoPlayback video(renderer,{w.hwnd,Window::notice,3},[&](auto device,auto callback){check(device!=nullptr,"Every engine borrows same renderer device");auto p=std::make_shared<Probe>();p->notify=std::move(callback);p->transferError=nextTransferError;nextTransferError=S_OK;probes.push_back(p);return std::make_unique<Engine>(std::move(p));});
    std::array request{n::NotesVideoRequest{"owned-video","C:\\owned-synthetic\\tiny.mp4",1,512,10,{}}};check(video.setVisible(request,0)&&!video.requiresFrames(),"Source video loads paused without a polling clock");check(!video.accept(2,0)&&video.accept(3,0),"Only current owner generation drains native notices");check(video.sample(0),"First frame becomes retained poster");const auto*r=video.find("owned-video");check(r&&r->nativeWidth==4&&r->nativeHeight==4&&r->state==m::NotesMediaState::paused&&r->textureID=="owned-video.poster"&&renderer.stats().mediaTargets==1&&!video.requiresFrames()&&!video.nextWakeTime(),"Initially paused video owns exactly one poster surface and no wakeups");
    const auto before=video.stats();for(unsigned i=0;i<120;++i)check(!video.sample(.1+double(i)/120),"Paused samples never transfer or query frames");check(video.stats().ticks==before.ticks&&video.stats().transfers==before.transfers,"Paused frame work stays zero");
    check(video.play("owned-video",2)&&video.requiresFrames()&&renderer.stats().mediaTargets==2,"First actual play lazily allocates independent live surface");const auto allocations=renderer.stats().mediaTargetAllocations,uploads=renderer.stats().textureUploads;probes.back()->pixel={255,0,0,255};check(video.sample(2)&&r->textureID=="owned-video.live","New video frame switches live output without overwriting poster");
    for(unsigned i=0;i<120;++i){probes.back()->fresh=true;probes.back()->position=double(i)/60;check(video.sample(2.01+double(i)/60),"Owner frame clock commits a newly supplied frame");}check(renderer.stats().mediaTargetAllocations==allocations&&renderer.stats().textureUploads==uploads,"120 video frames retain texture allocations and perform no CPU uploads");
    video.pause("owned-video");check(!video.requiresFrames()&&!video.nextWakeTime(),"Pause stops frame/progress demand");check(video.seek("owned-video",999)&&r->pendingSeek==10,"Source seek clamps to duration");video.accept(3,4.1);video.sample(4.1);check(r->currentTime==10&&!r->pendingSeek,"Seek completion publishes actual position");check(video.play("owned-video",4.2)&&probes.back()->position==0,"Playing within source .05-second end margin restarts at zero");
    video.accept(3,4.2);video.sample(4.2);probes.back()->position=3;video.hide(4.3,true);check(r->state==m::NotesMediaState::hidden&&r->textureID=="owned-video.poster"&&r->currentTime==3&&r->wantsPlayback&&!video.requiresFrames(),"Hide stops native engine but keeps source poster/time/play intent");check(video.collectRetired()&&renderer.stats().mediaTargets==1,"Detached live target retires independently of finite poster");check(video.sample(4.9)&&r->textureID.empty()&&video.collectRetired()&&renderer.stats().mediaTargets==0,"Finite source poster retention expires once then releases device target");
    const auto stale=probes.back()->notify;video.setVisible(request,5);stale(n::NativeNotesVideoPlayback::failure,E_FAIL);video.accept(3,5);video.sample(5);check(r->state==m::NotesMediaState::playing&&probes.back()->seeks==1&&r->pendingSeek==3,"Old engine callback cannot poison new generation; reopen restores seek/play intent");
    // Genuine off-thread notification only writes fixed mailbox state. The UI
    // drain alone samples engine state or touches retained GPU resources.
    const auto commits=renderer.stats().mediaFrameCommits;std::thread worker([callback=probes.back()->notify]{for(unsigned i=0;i<100;++i)callback(n::NativeNotesVideoPlayback::ended,S_OK);});worker.join();check(renderer.stats().mediaFrameCommits==commits,"Codec callback never calls renderer");video.accept(3,5.1);check(r->state==m::NotesMediaState::paused&&!r->wantsPlayback,"End notification pauses without looping or stale playback intent");
    std::array<n::NotesVideoRequest,9>tooMany;for(unsigned i=0;i<9;++i)tooMany[i]={"too-many-"+std::to_string(i),"C:\\owned-synthetic\\tiny.mp4",1,512,10,{}};const auto engineCount=probes.size();rejects([&]{video.setVisible(tooMany,5.2);},"Ninth visible engine rejects before any native allocation");check(probes.size()==engineCount,"Capacity validation leaves current engine alive");
    video.hide(6);video.collectRetired();check(video.retire("owned-video"),"Explicit retirement follows GPU detach");
    nextTransferError=E_FAIL;video.setVisible(request,7);video.accept(3,7);check(video.sample(7),"Best-effort poster failure publishes changed metadata");r=video.find("owned-video");check(r->state==m::NotesMediaState::paused&&FAILED(r->posterError)&&r->error==S_OK&&r->textureID.empty()&&!video.requiresFrames(),"A failed static poster does not reject a valid paused movie");
    check(video.play("owned-video",7.1),"A valid movie can play after poster extraction failed");check(video.sample(7.1)&&r->state==m::NotesMediaState::playing&&r->textureID=="owned-video.live","Live video remains available after isolated poster failure");
    video.pause("owned-video");probes.back()->fresh=false;video.play("owned-video",7.2);check(!video.sample(7.2)&&video.requiresFrames(),"Playing waits for actual native frame availability");video.pause("owned-video");check(!video.requiresFrames()&&!video.nextWakeTime(),"Pausing cancels outstanding play-frame demand even when no frame arrived");
    video.hide(8);video.collectRetired();check(video.retire("owned-video"),"Failed poster and played targets both retire");video.setRoute({});const auto notifications=video.stats().notices;probes.back()->notify(n::NativeNotesVideoPlayback::failure,E_FAIL);check(video.stats().notices==notifications,"Cleared owner route cannot receive teardown callbacks");check(renderer.stats().mediaLiveBytes==0&&!IsWindowVisible(w.hwnd)&&renderer.stats().presents==0,"All owned video resources released without visible UI/audio/capture");
}
void unsupported(const std::filesystem::path&shader){Window w;n::Renderer renderer;renderer.initialize(w.hwnd,32,32,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests,true});
    const auto path=std::filesystem::temp_directory_path()/(L"endfield-owned-invalid-video-"+std::to_wstring(GetCurrentProcessId())+L"-"+std::to_wstring(GetTickCount64())+L".mp4");check(!std::filesystem::exists(path),"Invalid-media fixture never overwrites an existing file");struct Cleanup{std::filesystem::path path;~Cleanup(){std::error_code error;std::filesystem::remove(path,error);}}cleanup{path};{std::ofstream file(path,std::ios::binary);file<<"Owned synthetic invalid container. No encoded image, video, or audio stream.";check(bool(file),"Write only bounded invalid fixture bytes");}
    {n::NativeNotesVideoPlayback video(renderer,{w.hwnd,Window::notice,9});const auto u=path.u8string();const std::array request{n::NotesVideoRequest{"invalid",std::string(reinterpret_cast<const char*>(u.data()),u.size()),1}};video.setVisible(request,0);const auto deadline=GetTickCount64()+10000;
        while(video.find("invalid")->state!=m::NotesMediaState::failed){video.accept(9,0);if(video.find("invalid")->state==m::NotesMediaState::failed)break;const auto now=GetTickCount64();check(now<deadline,"Actual Media Engine reports invalid container within bounded fixture wait");check(MsgWaitForMultipleObjectsEx(0,nullptr,static_cast<DWORD>(deadline-now),QS_POSTMESSAGE,MWMO_INPUTAVAILABLE)==WAIT_OBJECT_0,"Media Engine failure wakes existing owner queue");MSG message{};while(PeekMessageW(&message,w.hwnd,Window::notice,Window::notice,PM_REMOVE))check(message.lParam==0,"Native Media Engine notice carries no pointer");}
        check(!video.requiresFrames()&&!video.nextWakeTime()&&renderer.stats().mediaTargetAllocations==0,"Unsupported decode becomes explicit failure with no polling, surface allocation, or audio playback");video.hide(1);check(video.retire("invalid"),"Failed native pipeline can retire cleanly");video.setRoute({});}
    check(!IsWindowVisible(w.hwnd)&&renderer.stats().presents==0,"Actual invalid-container check never shows or captures desktop");
}
}
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);if(FAILED(hr))return 1;int result{};try{check(argc==2,"Pass native/hud.hlsl");run(argv[1]);unsupported(argv[1]);std::cout<<"PASS "<<checks<<" Notes video owner checks (injected video; actual invalid-container decode only, no audio)\n";}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';result=1;}CoUninitialize();return result;}
#else
int main(){return 0;}
#endif
