#include "native/notes_image_decoder.hpp"
#include <algorithm>
#include <array>
#include <atomic>
#include <fstream>
#include <iostream>
#include <stdexcept>
#ifdef _WIN32
namespace n=endfield::native;namespace m=endfield::modules;
namespace {
unsigned checks{};void check(bool value,const char*message){++checks;if(!value)throw std::runtime_error(message);}
template<class F>void rejects(F f,const char*message){bool rejected{};try{f();}catch(const std::exception&){rejected=true;}check(rejected,message);}
struct Handle {HANDLE value{};explicit Handle(HANDLE h):value(h){}~Handle(){if(value)CloseHandle(value);}Handle(const Handle&)=delete;};
struct Window {HWND hwnd{};ATOM atom{};static constexpr UINT notice=WM_APP+248;
    Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"EndfieldOwnedMediaDecodeFixture";atom=RegisterClassW(&c);check(atom!=0,"Register owned hidden media fixture");hwnd=CreateWindowExW(WS_EX_TOOLWINDOW,c.lpszClassName,L"Synthetic image decoder",WS_POPUP,0,0,1,1,nullptr,nullptr,c.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Media fixture never shows or focuses window");}
    ~Window(){if(hwnd)DestroyWindow(hwnd);if(atom)UnregisterClassW(reinterpret_cast<LPCWSTR>(static_cast<ULONG_PTR>(atom)),GetModuleHandleW(nullptr));}
    n::NotesImageRoute route(UINT_PTR generation)const{return {hwnd,notice,generation};}
};
std::vector<n::NotesImageCompletion>collect(n::NativeNotesImageDecoder&decoder,const Window&w,UINT_PTR generation,std::size_t count){std::vector<n::NotesImageCompletion>result;const auto deadline=GetTickCount64()+10000;
    while(result.size()<count){for(auto&c:decoder.drain(generation))result.push_back(std::move(c));if(result.size()>=count)break;const auto now=GetTickCount64();check(now<deadline,"Bounded image completion deadline");check(MsgWaitForMultipleObjectsEx(0,nullptr,static_cast<DWORD>(deadline-now),QS_POSTMESSAGE,MWMO_INPUTAVAILABLE)==WAIT_OBJECT_0,"Image worker wakes owner by completion event only");MSG message{};while(PeekMessageW(&message,w.hwnd,Window::notice,Window::notice,PM_REMOVE))check(message.lParam==0,"Media message never carries raw callback pointer");}
    MSG message{};while(PeekMessageW(&message,w.hwnd,Window::notice,Window::notice,PM_REMOVE))check(message.lParam==0,"Coalesced message is pointer-free");return result;}
void stop(n::NativeNotesImageDecoder&d){Handle done(d.duplicateWorkerHandle());d.stop();check(WaitForSingleObject(done.value,10000)==WAIT_OBJECT_0&&d.stats().stopped,"Worker stops and releases owned decoder/COM");}
n::NotesImageRequest request(unsigned index){return {"media."+std::to_string(index),"C:\\owned-synthetic\\image-"+std::to_string(index)+".png",1,512};}
struct Probe {std::atomic<unsigned>opens{},closes{},decodes{};std::atomic<DWORD>thread{};std::atomic<bool>block{};Handle entered{CreateEventW(nullptr,TRUE,FALSE,nullptr)},release{CreateEventW(nullptr,TRUE,FALSE,nullptr)};};
class Synthetic final:public n::NativeNotesImageDecoder::Sequence {
    std::shared_ptr<Probe>probe_;n::NotesImageAccess access_;n::NotesImageInfo info_{2,2,4,m::NotesMediaKind::gif,{.04,.1,.2,.3},.64};
public:Synthetic(std::shared_ptr<Probe>p,n::NotesImageAccess access):probe_(std::move(p)),access_(std::move(access)){info_.duration=0;for(auto d:info_.frameDelays)info_.duration+=d;}
    const n::NotesImageInfo&info()const override{return info_;}
    n::NotesImageFrame decode(unsigned index)override{++probe_->decodes;probe_->thread=GetCurrentThreadId();if(probe_->block.exchange(false)){SetEvent(probe_->entered.value);if(WaitForSingleObject(probe_->release.value,10000)!=WAIT_OBJECT_0)throw std::runtime_error("Synthetic block deadline");}return {2,2,index,std::vector<std::uint8_t>(16,static_cast<std::uint8_t>(index+1))};}
};
auto resolver(std::shared_ptr<Probe>probe){return [probe](const n::NotesImageRequest&r){++probe->opens;auto lease=std::shared_ptr<void>(new unsigned(1),[probe](void*p){delete static_cast<unsigned*>(p);++probe->closes;});return n::NotesImageAccess{std::filesystem::u8path(r.path),std::move(lease)};};}
auto factory(std::shared_ptr<Probe>probe){return [probe](const n::NotesImageRequest&,n::NotesImageAccess access){return std::make_unique<Synthetic>(probe,std::move(access));};}
void generations(){Window w;auto probe=std::make_shared<Probe>();probe->block=true;n::NativeNotesImageDecoder decoder(resolver(probe),w.route(4),factory(probe));std::array<n::NotesImageRequest,8>initial;for(unsigned i=0;i<8;++i)initial[i]=request(i);decoder.setVisible(initial);check(WaitForSingleObject(probe->entered.value,10000)==WAIT_OBJECT_0,"Synthetic initial decode blocks only its worker");
    auto invalid=initial;invalid[1].key=invalid[0].key;rejects([&]{decoder.setVisible(invalid);},"Malformed visible batch preserves previous generation");check(decoder.stats().queued==7,"Blocked worker retains bounded queue");
    decoder.hide();check(decoder.stats().queued==0&&decoder.stats().completed==0&&decoder.stats().inFlight,"Hide discards jobs/results without waiting for codec");std::array<n::NotesImageRequest,8>latest;for(unsigned i=0;i<8;++i)latest[i]=request(i+20);decoder.setVisible(latest);SetEvent(probe->release.value);auto results=collect(decoder,w,4,8);
    check(probe->thread!=GetCurrentThreadId()&&probe->decodes==9,"Only canceled in-flight plus latest eight execute off owner thread");for(const auto&r:results)check(SUCCEEDED(r.result)&&r.frame&&r.frame->width==2&&r.key.starts_with("media.2"),"No old visibility completion publishes");
    check(decoder.drain(3).empty(),"Old owner route cannot drain current results");check(!decoder.setVisible(latest),"Repeated visible state does not reopen codecs");
    const auto idle=decoder.stats();Handle never(CreateEventW(nullptr,FALSE,FALSE,nullptr));check(WaitForSingleObject(never.value,50)==WAIT_TIMEOUT,"Bounded idle observation");const auto after=decoder.stats();check(idle.wakeups==after.wakeups&&idle.decodes==after.decodes&&idle.notices==after.notices,"No idle polling, frame decoding, or notices");
    for(unsigned i=1;i<4;++i){decoder.requestFrame(latest[0].key,i);check(collect(decoder,w,4,1).front().frame->index==i,"Explicit next GIF frame published");}
    const auto decoded=decoder.stats().decodes;decoder.requestFrame(latest[0].key,2);auto cached=collect(decoder,w,4,1);check(decoder.stats().decodes==decoded&&cached.front().frame->index==2,"Three-frame LRU reuses immutable frame without WIC work");
    decoder.requestFrame(latest[0].key,0);collect(decoder,w,4,1);check(decoder.stats().decodes==decoded+1,"Fourth GIF frame evicts oldest rather than retaining unbounded movie");
    const auto borrowed=results.front().frame;decoder.hide();decoder.setRoute({});stop(decoder);check(probe->opens==probe->closes&&borrowed->straightRGBA[0]==1,"Hide/stop closes every access while borrowed finite artwork remains valid");}
void blockedStop(){Window w;auto probe=std::make_shared<Probe>();probe->block=true;auto decoder=std::make_unique<n::NativeNotesImageDecoder>(resolver(probe),w.route(5),factory(probe));const std::array one{request(90)};decoder->setVisible(one);check(WaitForSingleObject(probe->entered.value,10000)==WAIT_OBJECT_0,"Shutdown fixture enters bounded fake codec");Handle done(decoder->duplicateWorkerHandle());auto begin=GetTickCount64();decoder.reset();check(GetTickCount64()-begin<1000,"Facade destruction does not join blocked decoder");rejects([&]{n::NativeNotesImageDecoder another(resolver(probe),{},factory(probe));},"A blocked stopped codec cannot accumulate process workers");SetEvent(probe->release.value);check(WaitForSingleObject(done.value,10000)==WAIT_OBJECT_0&&probe->opens==probe->closes,"Worker cleanup remains safe after owner destruction");MSG msg{};check(!PeekMessageW(&msg,w.hwnd,Window::notice,Window::notice,PM_REMOVE),"No completion sent after owner route clears");}
std::string utf8(const std::filesystem::path&p){auto s=p.u8string();return {reinterpret_cast<const char*>(s.data()),s.size()};}
void write(const std::filesystem::path&path,std::span<const std::uint8_t>bytes){std::ofstream stream(path,std::ios::binary);stream.write(reinterpret_cast<const char*>(bytes.data()),static_cast<std::streamsize>(bytes.size()));check(bool(stream),"Write only newly owned tiny image fixture");}
std::vector<std::uint8_t>gif(){std::vector<std::uint8_t>b{'G','I','F','8','9','a',4,0,3,0,0x81,0,0,0,0,0,255,0,0,0,255,0,0,0,255};
    auto frame=[&](unsigned x,unsigned y,unsigned width,unsigned height,unsigned color,unsigned disposal,unsigned delay){const std::array<std::uint8_t,18>header{0x21,0xf9,4,static_cast<std::uint8_t>((disposal<<2)|1),static_cast<std::uint8_t>(delay),0,0,0,0x2c,static_cast<std::uint8_t>(x),0,static_cast<std::uint8_t>(y),0,static_cast<std::uint8_t>(width),0,static_cast<std::uint8_t>(height),0,0};b.insert(b.end(),header.begin(),header.end());b.push_back(2);std::vector<std::uint8_t>data;unsigned bits{},buffer{};auto code=[&](unsigned value){buffer|=value<<bits;bits+=3;while(bits>=8){data.push_back(static_cast<std::uint8_t>(buffer));buffer>>=8;bits-=8;}};for(unsigned i=0;i<width*height;++i){code(4);code(color);}code(5);if(bits)data.push_back(static_cast<std::uint8_t>(buffer));b.push_back(static_cast<std::uint8_t>(data.size()));b.insert(b.end(),data.begin(),data.end());b.push_back(0);};
    frame(0,0,4,3,1,1,0);frame(1,0,2,2,2,3,1);frame(0,1,1,2,3,2,20);frame(3,2,1,1,2,1,30);b.push_back(0x3b);return b;}
std::array<std::uint8_t,4>pixel(const n::NotesImageFrame&frame,unsigned x,unsigned y){std::array<std::uint8_t,4>p{};std::copy_n(frame.straightRGBA.data()+(std::size_t(y)*frame.width+x)*4,4,p.begin());return p;}
void wic(){Window w;const auto root=std::filesystem::temp_directory_path()/("endfield-owned-image-"+std::to_string(GetCurrentProcessId())+"-"+std::to_string(GetTickCount64()));check(std::filesystem::create_directory(root),"Create new synthetic media directory");struct Cleanup{std::filesystem::path path;~Cleanup(){std::error_code error;std::filesystem::remove_all(path,error);}}cleanup{root};
    constexpr std::uint8_t png[]{137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,2,0,0,0,2,8,6,0,0,0,114,182,13,36,0,0,0,23,73,68,65,84,120,156,5,193,1,1,0,0,0,130,32,166,247,220,64,36,161,193,1,61,87,5,124,22,194,63,189,0,0,0,0,73,69,78,68,174,66,96,130};
    const auto pngPath=root/"owned.png",gifPath=root/"owned.gif";write(pngPath,png);write(gifPath,gif());auto probe=std::make_shared<Probe>();n::NativeNotesImageDecoder decoder(resolver(probe),w.route(7));std::array requests{n::NotesImageRequest{"png",utf8(pngPath),1,512},n::NotesImageRequest{"gif",utf8(gifPath),1,512}};decoder.setVisible(requests);auto results=collect(decoder,w,7,2);for(const auto&r:results)check(SUCCEEDED(r.result)&&r.frame,"Native WIC decodes owned PNG/GIF");
    const auto pngResult=std::find_if(results.begin(),results.end(),[](const auto&r){return r.key=="png";});check(pngResult!=results.end()&&pngResult->info->kind==m::NotesMediaKind::image&&pngResult->frame->width==2&&pngResult->frame->height==2,"Still image preserves decoded dimensions and kind");check(pixel(*pngResult->frame,0,0)==std::array<std::uint8_t,4>{255,0,0,255}&&pixel(*pngResult->frame,0,1)==std::array<std::uint8_t,4>{0,0,255,128},"WIC still retains straight RGBA including half alpha");check(probe->closes>=1,"Still decoder releases original file lease immediately after pixels publish");
    for(unsigned index=1;index<4;++index){decoder.requestFrame("gif",index);auto row=collect(decoder,w,7,1).front();check(SUCCEEDED(row.result)&&row.frame&&row.frame->index==index,"Native WIC GIF subframe completion");const auto&f=*row.frame;check(row.info->frameDelays==std::vector<double>{.1,.04,.2,.3},"GIF source delay normalization, not browser90ms override");
        if(index==1)check(pixel(f,1,0)==std::array<std::uint8_t,4>{0,255,0,255}&&pixel(f,0,0)==std::array<std::uint8_t,4>{255,0,0,255},"GIF partial green frame retains red canvas outside subrect");
        if(index==2)check(pixel(f,1,0)==std::array<std::uint8_t,4>{255,0,0,255}&&pixel(f,0,1)==std::array<std::uint8_t,4>{0,0,255,255},"GIF restore-previous restores whole prior canvas before next frame");
        if(index==3)check(pixel(f,0,1)[3]==0&&pixel(f,3,2)==std::array<std::uint8_t,4>{0,255,0,255},"GIF restore-background clears exactly disposed subrect and draws next frame");}
    const auto old=results.front().frame;decoder.hide();stop(decoder);check(probe->opens==probe->closes&&old->straightRGBA.size()==16,"Media file access closed while immutable borrowed pixels survive decoder");check(!IsWindowVisible(w.hwnd),"No native decode fixture displays UI");}
}
int main(){try{generations();blockedStop();wic();std::cout<<"PASS "<<checks<<" native Notes image checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(){std::cout<<"Windows WIC/worker fixture requires Windows; not executed on this platform\n";return 0;}
#endif
