#include "modules/notes_state.hpp"
#include "modules/notes_drawing.hpp"
#include "modules/notes_presentation.hpp"
#include <algorithm>
#include <iostream>
#include <stdexcept>
namespace {unsigned checks{};void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}}
int main(){try{using namespace endfield::modules;using N=ehud::data::Note;constexpr auto id="DDDDDDDD-0000-4000-8000-000000000001";
    std::vector<N>writes;bool fail{};NotesState state({}, {[&](const N&n){if(fail)throw std::runtime_error("Synthetic full disk");writes.push_back(n);},[](std::string_view){} });
    state.setWorkspaceBounds({0,0,1000,800},endfield::core::Point{30,40});check(state.createDrawing(id,123)&&writes.size()==1,"Drawing creation makes one explicit save");const auto*n=state.note(id);check(n&&n->kind==ehud::data::NoteKind::drawing&&n->width==300&&n->height==240&&n->x==30&&n->y==40&&n->createdAt==123,"Source drawing default size/placement/date");check(!state.editing()&&state.selection()==id&&n->drawing&&NotesDrawing(*n->drawing).strokes().empty(),"Selected drawing creates no text editor");
    NotesPresentationInput input;input.palette=NotesPalette::source(true,{.98,.83,.12,1});input.drawingColor=NotesColor{.2,.8,.9,1};NotesCardPresentation presentation(id);presentation.updateContent(state,input);
    check(presentation.drawing()&&!presentation.editor()&&presentation.contentViewport()==endfield::core::Rect{5,29,290,184},"Drawing has source viewport without a text editor");
    const auto swatch=std::find_if(presentation.layers().begin(),presentation.layers().end(),[](const auto&l){return l.id.ends_with("format/formatColor/swatch");});check(swatch!=presentation.layers().end()&&swatch->background==input.drawingColor,"Drawing swatch uses caller's brush color");
    const auto color=std::find_if(presentation.actions().begin(),presentation.actions().end(),[](const auto&a){return a.verb=="formatColor";});check(color!=presentation.actions().end()&&color->localRect==endfield::core::Rect{6,216,20,20},"Drawing color button follows original square/footer position");check(std::none_of(presentation.actions().begin(),presentation.actions().end(),[](const auto&a){return a.verb=="edit";}),"Canvas does not open a text field on drawing click");
    presentation.setFeedback("formatColor",false,false);check(presentation.highlights().size()==3,"Drawing reuses original pin/delete/color highlight animations");
    state.select({});presentation.updateContent(state,input);check(std::none_of(presentation.actions().begin(),presentation.actions().end(),[](const auto&a){return a.verb=="formatColor";}),"Unselected drawing hides brush-color tool");state.select(id);
    NotesDrawing draft(*n->drawing);DrawingStroke stroke;sampleDrawingStroke(stroke,{4,8},{290,184});sampleDrawingStroke(stroke,{90,80},{290,184});check(writes.size()==1,"Sampling a gesture never persists or mutates canonical record");draft.append(stroke);check(state.commitDrawing(id,draft)&&writes.size()==2&&state.note(id)->drawing==draft.encode(),"Completed stroke has one atomic persistence boundary");check(!state.commitDrawing(id,draft)&&writes.size()==2,"Duplicate completed content adds no save");
    fail=true;draft.append(stroke);check(state.commitDrawing(id,draft)&&state.unsaved().contains(id)&&state.error(),"Persistence failure keeps visible unsaved strokes for recovery");check(NotesDrawing(*state.note(id)->drawing).strokes().size()==2,"Failed save never discards new user's drawing");fail=false;check(state.commitDrawing(id,draft)&&state.unsaved().empty()&&!state.error(),"Explicit retry saves same unsaved drawing");
    state.togglePin(id);state.setPresentation(false);check(state.visible(id)&&state.commitDrawing(id,NotesDrawing{}),"Pinned drawing remains editable across module selection");state.togglePin(id);check(!state.commitDrawing(id,draft),"Hidden unpinned drawing cannot receive accidental gesture commit");
    check(!state.createDrawing("DDDDDDDD-0000-4000-8000-000000000002",456),"Drawing tool inactive outside Notes");
    N legacy{.id="DDDDDDDD-0000-4000-8000-000000000003",.kind=ehud::data::NoteKind::drawing,.width=300,.height=240,.createdAt=0};std::size_t legacySaves{};NotesState legacyState({legacy},{[&](const auto&){++legacySaves;},[](auto){}});legacyState.setWorkspaceBounds({0,0,1000,800});NotesCardPresentation legacyCard(legacy.id);check(legacyCard.updateContent(legacyState,input)&&legacyCard.drawing(),"Missing optional drawing payload paints original empty-canvas fallback");check(!legacyState.note(legacy.id)->drawing&&legacySaves==0,"Presentation never rewrites a missing stored drawing payload");std::cout<<"PASS "<<checks<<" drawing state checks\n";return 0;
}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
