#include "tools/notes_preview.hpp"
#include "core/shell_packet.hpp"
#ifdef _WIN32
#include <algorithm>
#include <array>
#include <cmath>
#include <fstream>
#include <filesystem>
#include <iostream>
namespace n=endfield::native;namespace t=endfield::tools;namespace c=endfield::core;namespace a=endfield::app;namespace d=ehud::data;namespace m=endfield::modules;
namespace {
unsigned checks{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}void stage(const char*s){std::cerr<<"Movie fixture stage="<<s<<" checks="<<checks<<'\n';}
struct Window {HWND hwnd{};ATOM atom{};Window(){WNDCLASSW w{};w.lpfnWndProc=DefWindowProcW;w.hInstance=GetModuleHandleW(nullptr);w.lpszClassName=L"EndfieldOwnedMovieImport";atom=RegisterClassW(&w);check(atom!=0,"Register owned movie-import fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,w.lpszClassName,L"Hidden silent movie import",WS_POPUP,0,0,1280,800,nullptr,nullptr,w.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Movie fixture stays hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);if(atom)UnregisterClassW(reinterpret_cast<LPCWSTR>(static_cast<ULONG_PTR>(atom)),GetModuleHandleW(nullptr));}};
struct Temp {std::filesystem::path path=std::filesystem::temp_directory_path()/("endfield-owned-movie-import-"+d::makeUUID());Temp(){check(std::filesystem::create_directory(path),"Create new owned temporary data root");}~Temp(){std::error_code error;std::filesystem::remove_all(path,error);}};
std::string utf8(const std::filesystem::path&p){const auto bytes=p.u8string();return {reinterpret_cast<const char*>(bytes.data()),bytes.size()};}
std::string ascii(const wchar_t*p){std::string s;for(;*p;++p){check(*p>0&&*p<128,"Build pins are ASCII");s.push_back(static_cast<char>(*p));}return s;}
void run(const std::filesystem::path&shader,const n::NativeNotesControlsAssets&assets,const std::filesystem::path&fixture){
    std::ifstream input(fixture,std::ios::binary);std::array<std::uint8_t,1701>bytes{};input.read(reinterpret_cast<char*>(bytes.data()),static_cast<std::streamsize>(bytes.size()));check(input&&input.peek()==std::char_traits<char>::eof()&&c::packet::sha256(bytes)=="0de10d53a6946351f127b78b738c68658708cd91e932164d110ca6ec2f8579cf","Only pinned authored 64x64 silent red/blue H.264 fixture is accepted");
    Window window;Temp temp;const auto file=temp.path/L"owned-silent.mp4",store=temp.path/L"synthetic-notes";{std::ofstream output(file,std::ios::binary);output.write(reinterpret_cast<const char*>(bytes.data()),static_cast<std::streamsize>(bytes.size()));check(bool(output),"Write tiny movie only beneath owned temporary root");}
    n::Renderer renderer;renderer.initialize(window.hwnd,1280,800,{n::Driver::hardware,shader,n::RenderTarget::offscreenForTests,true});const auto camera=n::layerViewportProjection(1280,800);renderer.setCamera(camera);n::LayerRasterizer raster;n::LayerComposition composition;
    t::NotesPreview notes(window.hwnd,raster,store,assets,false);
    // Composition borrows scene pointers. Detach before NotesPreview destruction
    // on assertion/codec failures as well, otherwise teardown masks the failure
    // with a use-after-free in LayerComposition's destructor.
    struct Cleanup {n::LayerComposition&composition;t::NotesPreview&notes;n::Renderer&renderer;bool released{};void release(){composition.detach(renderer);notes.release(renderer);released=true;}~Cleanup(){if(!released)try{release();}catch(...){renderer.reset();}}}cleanup{composition,notes,renderer};
    notes.resize({1280,800,96,1,1280,800});c::source::DesktopChromeSettings settings;settings.viewport={0,0,1280,800};settings.module=c::Module::notes;settings.sourceShell=true;const auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;const auto workspaceWorld=center*c::source::inverseSourceMatrix(c::source::DesktopChromeLayout::make(settings,center,{}).designToScreen);const auto projection=c::Projection::viewport(camera*workspaceWorld,1280,800);
    const auto epoch=GetTickCount64();double offset{};auto now=[&]{return double(GetTickCount64()-epoch)/1000.+offset;};auto frame=[&]{const auto time=now();notes.update(center,settings,1,time,false);notes.upload(renderer);composition.setEntries(renderer,notes.entries());notes.collected(renderer);composition.present(renderer);renderer.draw(false);};frame();stage("initial-published");
    const std::array paths{utf8(file)};check(notes.importMedia(paths,{80,80},now()),"Actual owner starts movie inspection on existing import worker");
    auto mediaDraw=[&]()->const n::DrawObject*{for(const auto&e:notes.entries())if(e.after.size()==4&&!e.after[0].textureID.empty()&&e.after[0].sourceID.find("media")!=std::string::npos)return &e.after[0];return nullptr;};
    auto waitFor=[&](auto predicate,const char*why){const auto deadline=GetTickCount64()+10000;while(!predicate()){const auto tick=GetTickCount64();check(tick<deadline,why);const auto wait=notes.requiresFrames(now())?16u:static_cast<unsigned>(deadline-tick);MsgWaitForMultipleObjectsEx(0,nullptr,wait,QS_ALLINPUT,MWMO_INPUTAVAILABLE);MSG message{};while(PeekMessageW(&message,nullptr,0,0,PM_REMOVE)){if(message.hwnd==window.hwnd&&message.message==t::NotesPreview::mediaNoticeMessage){check(message.lParam==0,"Native completion posts no raw owner pointer");notes.message({window.hwnd,message.message,message.wParam,message.lParam},now());}else{TranslateMessage(&message);DispatchMessageW(&message);}}frame();check(!notes.mediaError(),"Movie owner import does not report a fallback error");}};
    waitFor([&]{return mediaDraw()!=nullptr;},"Actual movie inspection, persistence and paused poster complete");offset+=.3;frame();stage("poster-published");d::Note saved;{d::NotesStore disk(store);const auto found=std::find_if(disk.notes().begin(),disk.notes().end(),[](const auto&v){return v.media.has_value();});check(found!=disk.notes().end(),"Imported movie has a persisted reference");saved=*found;const auto metadata=d::Json::parse(*saved.media);check(metadata["kind"].string()=="video"&&metadata["pixelWidth"].integer()==64&&metadata["pixelHeight"].integer()==64&&std::abs(metadata["duration"].number()-1.2)<.02,"Actual movie type, dimensions and duration survive complete import path");}
    auto color=[&]{const auto*draw=mediaDraw();check(draw!=nullptr,"Movie retains an image draw");const auto point=c::Projection::viewport(camera*draw->world,1280,800).project({.5,.5});check(point.has_value(),"Actual card image center projects into owned target");const auto read=renderer.readback();const auto x=static_cast<unsigned>(std::clamp(std::floor(point->x),0.,1279.)),y=static_cast<unsigned>(std::clamp(std::floor(point->y),0.,799.));const auto at=(std::size_t(y)*read.width+x)*4;return std::array<unsigned,4>{read.pixels[at],read.pixels[at+1],read.pixels[at+2],read.pixels[at+3]};};const auto red=color();check(red[2]>220&&red[0]<40,"Source card displays actual red paused poster, not a synthetic placeholder");check(!notes.requiresFrames(now())&&!notes.nextWakeTime(),"Initially paused imported movie produces no permanent frame/deadline demand");
    m::NotesMediaLayout layout(saved.width,saved.height,m::NotesMediaKind::video,1.2);auto event=[&](a::PointerKind kind,c::Point local,a::PointerButton button){const auto point=projection.project({saved.x+local.x,saved.y+local.y});check(point.has_value(),"Source card action projects into owner coordinates");return notes.pointer({kind,button,point->x,point->y},now());};const auto seek=layout.geometry().seek;
    check(event(a::PointerKind::down,{seek.x+seek.width*.25,seek.y+10},a::PointerButton::left)&&notes.pointerLocked(),"Original video rail captures seek gesture");event(a::PointerKind::move,{seek.x+seek.width*.75,seek.y+10},a::PointerButton::none);check(event(a::PointerKind::up,{seek.x+seek.width*.75,seek.y+10},a::PointerButton::left)&&!notes.pointerLocked(),"Pointer release commits seek and unlocks source tilt");const auto commits=renderer.stats().mediaFrameCommits;
    waitFor([&]{return renderer.stats().mediaFrameCommits>commits;},"Actual paused seek produces a new frame");stage("seek-published");const auto blue=color();check(blue[0]>220&&blue[2]<40,"Owner seek reaches blue movie frames through retained shared composition");
    const auto playback=layout.geometry().playback;check(event(a::PointerKind::down,{playback.x+8,playback.y+8},a::PointerButton::left),"Original playback footer starts video");event(a::PointerKind::up,{playback.x+8,playback.y+8},a::PointerButton::left);const auto before=renderer.stats().mediaFrameCommits;waitFor([&]{return renderer.stats().mediaFrameCommits>before;},"Source footer delivers actual live frame");event(a::PointerKind::down,{playback.x+8,playback.y+8},a::PointerButton::left);event(a::PointerKind::up,{playback.x+8,playback.y+8},a::PointerButton::left);frame();
    notes.setMediaActive(false,now(),true);offset+=.61;notes.deadline(now());frame();check(!mediaDraw()&&!notes.nextWakeTime(),"Hide expires outgoing poster and shared deadline");{d::NotesStore disk(store);const auto found=std::find_if(disk.notes().begin(),disk.notes().end(),[&](const auto&v){return v.id==saved.id;});check(found!=disk.notes().end()&&found->media==saved.media,"Playback and seek do not rewrite or flatten the original movie reference");}
    cleanup.release();check(renderer.stats().mediaLiveBytes==0&&!IsWindowVisible(window.hwnd)&&renderer.stats().presents==0,"Full movie path tears down offscreen without user data, audio, native picker or capture");
}
}
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);if(FAILED(hr))return 1;int result{};try{check(argc==6,"Pass shader, Notes assets, manifest SHA, source commit, silent MP4");n::NativeNotesControlsAssets assets(std::filesystem::absolute(argv[2]),{ascii(argv[3]),ascii(argv[4])});run(argv[1],assets,argv[5]);std::cout<<"PASS "<<checks<<" full Notes silent movie import/seek/play checks\n";}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';result=1;}CoUninitialize();return result;}
#else
int main(){return 0;}
#endif
