#include "native/now_playing_service.hpp"
#include <iostream>
#include <stdexcept>
namespace n=endfield::native;namespace m=endfield::modules;using Q=endfield::app::UtilityExecutor;
namespace {
unsigned checks{};void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}
struct Provider:n::NowPlayingProvider {
 Changed changed;Ready startReady,commandReady;Read readReady;std::uint64_t target{};m::NowPlayingCommand sent;unsigned commands{},stops{};
 void start(Changed c,Ready r)override{changed=std::move(c);startReady=std::move(r);}void read(Read r)override{readReady=std::move(r);}
 void perform(std::uint64_t session,std::uint64_t,m::NowPlayingCommand c,Ready r)override{++commands;target=session;sent=c;commandReady=std::move(r);}void stop()noexcept override{++stops;}
};
n::NowPlayingReadResult media(unsigned session=1,std::string title="Source track"){n::NowPlayingReadResult r;auto&v=r.value;v.sessions={{1,"same.application","First"},{2,"same.application","Second"}};v.session=v.sessions[session-1];m::NowPlayingTrack track;track.title=std::move(title);track.duration=240;track.position=10;track.sampledAt=10;v.track=std::move(track);v.capabilities={true,true,true,true,true,true};v.metadataRevision=4;return r;}
void work(Q&q){q.waitIdle();q.drain();}void flush(Q&q,n::NativeNowPlayingService&s){work(q);s.drain();work(q);}
void ready(Q&q,n::NativeNowPlayingService&s,const std::shared_ptr<Provider>&p){s.setActive(true);flush(q,s);p->startReady({});flush(q,s);p->readReady(media());flush(q,s);check(s.snapshot().fresh,"Owned synthetic provider is ready");}
void completionTime(){Q q([]{});auto p=std::make_shared<Provider>();double now=10;n::NativeNowPlayingService s(q,[&]{return p;},[]{},[&]{return now;});ready(q,s,p);s.refresh();flush(q,s);now=11;check(s.perform({m::NowPlayingCommandKind::seek,120}),"Seek accepted while a read is in flight");const auto request=*s.snapshot().commandAccepted;check(request.token&&request.session==1&&request.metadataRevision==4&&request.command.seconds==120&&!request.replacedPending&&!s.snapshot().commandCompleted,"Accepted receipt carries exact current request without fabricated completion");now=12.5;p->readReady(media());flush(q,s);check(p->commands==1&&p->sent.seconds==120&&!s.snapshot().commandCompleted&&s.nextWakeTime()==15.5,"Queued seek starts only after the read, retaining its own timeout");now=14;p->commandReady({});flush(q,s);const auto result=*s.snapshot().commandCompleted;check(result.mediaReadRevision==2&&s.snapshot().mediaReadRevision==2,"Command completion preserves the last accepted read without claiming an acknowledgement");check(result.request.token==request.token&&result.completedAt==14&&result.failure==n::NowPlayingServiceFailure::none,"Source rollback begins at command completion, not acceptance");check(result.completedAt+2.5==16.5,"Original2.5second rollback can use the existing host deadline");p->readReady(media());flush(q,s);check(s.snapshot().mediaReadRevision==3&&s.snapshot().commandCompleted->mediaReadRevision==2,"Identical paused read with unchanged sample and metadata is still distinguishable after completion");s.refresh();flush(q,s);auto failed=media();failed.failure=n::NowPlayingServiceFailure::unavailable;p->readReady(std::move(failed));flush(q,s);check(s.snapshot().mediaReadRevision==3,"Failed read cannot acknowledge an optimistic seek");s.refresh();flush(q,s);p->changed();p->readReady(media());flush(q,s);check(s.snapshot().mediaReadRevision==3,"Read invalidated by a newer provider event does not advance accepted read evidence");p->readReady(media());flush(q,s);check(s.snapshot().mediaReadRevision==4,"Replacement current read advances evidence once");for(unsigned i=0;i<20;++i)s.drain();check(s.snapshot().commandCompleted->completedAt==14,"Idle drains never slide the completion timestamp");}
void replacing(){Q q([]{});auto p=std::make_shared<Provider>();double now=20;n::NativeNowPlayingService s(q,[&]{return p;},[]{},[&]{return now;});ready(q,s,p);s.refresh();flush(q,s);check(s.perform({m::NowPlayingCommandKind::seek,40}),"First pending seek accepted");const auto first=s.snapshot().commandAccepted->token;check(s.perform({m::NowPlayingCommandKind::seek,80}),"Latest pending seek accepted");const auto second=*s.snapshot().commandAccepted;check(second.token>first&&second.replacedPending==first,"New seek explicitly identifies only the replaced pending command");check(s.perform({m::NowPlayingCommandKind::playPause}),"Later transport may replace queued seek");const auto third=*s.snapshot().commandAccepted;check(third.replacedPending==second.token,"Source owner can clear optimism for an unsent replaced seek");p->readReady(media());flush(q,s);check(p->commands==1&&p->sent.kind==m::NowPlayingCommandKind::playPause,"Only latest pending request reaches provider");p->commandReady({});flush(q,s);check(s.snapshot().commandCompleted->request.token==third.token,"No fake success receipt is emitted for replaced queued seeks");}
void executingAndStale(){Q q([]{});auto p=std::make_shared<Provider>();double now=30;n::NativeNowPlayingService s(q,[&]{return p;},[]{},[&]{return now;});ready(q,s,p);s.perform({m::NowPlayingCommandKind::seek,90});work(q);const auto executing=s.snapshot().commandAccepted->token;const auto firstDone=p->commandReady;s.perform({m::NowPlayingCommandKind::next});const auto waiting=*s.snapshot().commandAccepted;check(!waiting.replacedPending&&waiting.token>executing,"In-flight seek is not misreported as a replaced pending request");now=31;firstDone({});flush(q,s);check(s.snapshot().commandCompleted->request.token==executing&&s.snapshot().commandAccepted->token==waiting.token&&p->commands==2,"Executing seek completion survives a newer accepted transport");firstDone({n::NowPlayingServiceFailure::accessDenied,-5});flush(q,s);check(s.snapshot().commandCompleted->request.token==executing&&s.snapshot().failure==n::NowPlayingServiceFailure::none,"Duplicate obsolete completion cannot change receipt or service failure");now=32;p->commandReady({n::NowPlayingServiceFailure::unsupported,-7});flush(q,s);check(s.snapshot().commandCompleted->request.token==waiting.token&&s.snapshot().commandCompleted->failure==n::NowPlayingServiceFailure::unsupported&&s.snapshot().commandCompleted->nativeError==-7,"Failure receipt preserves actual native command identity and error");s.setActive(false);check(!s.snapshot().commandAccepted&&!s.snapshot().commandCompleted,"Hide clears transient command evidence");firstDone({});flush(q,s);check(!s.snapshot().commandCompleted,"Late command after hide cannot resurrect a receipt");ready(q,s,p);s.perform({m::NowPlayingCommandKind::next});check(s.snapshot().commandAccepted->token>waiting.token,"Command identity does not recycle across activation");}
void changedSessionAndTimeout(){Q q([]{});auto p=std::make_shared<Provider>();double now=40;n::NativeNowPlayingService s(q,[&]{return p;},[]{},[&]{return now;});ready(q,s,p);s.refresh();flush(q,s);s.perform({m::NowPlayingCommandKind::seek,80});const auto token=s.snapshot().commandAccepted->token;p->readReady(media(1,"Other track"));flush(q,s);check(p->commands==0&&s.snapshot().commandCompleted->request.token==token&&s.snapshot().commandCompleted->failure==n::NowPlayingServiceFailure::stale,"Changed-track queued seek reports cancellation without OS action");s.refresh();flush(q,s);s.perform({m::NowPlayingCommandKind::next});const auto next=s.snapshot().commandAccepted->token;p->readReady(media(2));flush(q,s);check(p->commands==0&&s.snapshot().commandCompleted->request.token==next&&s.snapshot().commandCompleted->request.session==1,"Same-AUMID session replacement never transfers pending command ownership");now=41;s.perform({m::NowPlayingCommandKind::seek,50});work(q);const auto timed=s.snapshot().commandAccepted->token;const auto late=p->commandReady;now=44;s.drain();check(s.snapshot().commandCompleted->request.token==timed&&s.snapshot().commandCompleted->failure==n::NowPlayingServiceFailure::timedOut&&s.snapshot().commandCompleted->completedAt==44&&!s.nextWakeTime(),"Hung executing seek emits one timeout receipt and no extra clock");late({});flush(q,s);check(s.snapshot().commandCompleted->failure==n::NowPlayingServiceFailure::timedOut,"Late success cannot rewrite timed-out seek evidence");}
}
int main(){try{completionTime();replacing();executingAndStale();changedSessionAndTimeout();std::cout<<"Now Playing command receipts: "<<checks<<" checks passed (injected provider only)\n";return 0;}catch(const std::exception&e){std::cerr<<"Now Playing receipts failed after "<<checks<<": "<<e.what()<<'\n';return 1;}}
