#include "modules/now_playing_artwork.hpp"
#include <algorithm>
#include <atomic>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <new>
#include <stdexcept>
namespace {std::atomic<std::uint64_t>allocations{};}
void*operator new(std::size_t n){allocations.fetch_add(1,std::memory_order_relaxed);if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}
void operator delete(void*p)noexcept{std::free(p);}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete[](void*p)noexcept{::operator delete(p);}
#ifdef __cpp_sized_deallocation
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace m=endfield::modules;namespace c=endfield::core;using J=ehud::data::Json;
namespace {
unsigned checks{};void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}
bool closeEnough(double a,double b,double tolerance=2e-10){return std::abs(a-b)<=tolerance;}
const J&find(const J&values,std::string_view key,std::string_view wanted){for(const auto&v:values.array())if(v[key].isString()&&v[key].string()==wanted)return v;throw std::runtime_error("Missing immutable source fixture node: "+std::string(wanted));}
const J&node(const J&sample,std::string_view id){return find(sample["nodes"],"id",id);}
void rect(c::Rect value,const J&expected,double x=0,double y=0){const auto&e=expected.array();check(e.size()==4&&closeEnough(value.x,e[0].number()+x)&&closeEnough(value.y,e[1].number()+y)&&closeEnough(value.width,e[2].number())&&closeEnough(value.height,e[3].number()),"Original source rectangle");}
void rgba(const J&value,const J&expected){const auto&a=value["sRGB"].array();const auto&b=expected.array();check(a.size()==b.size(),"Original source color components");for(unsigned k=0;k<a.size();++k)check(closeEnough(a[k].number(),b[k].number(),3e-7),"Original calibrated color converted to sRGB");}
void path(const J&value,const J&expected,double dx=0,double dy=0){check(value.array().size()==expected.array().size(),"Original glyph path command count");for(std::size_t k=0;k<value.array().size();++k){const auto&a=value.array()[k];const auto&b=expected.array()[k];check(a["op"]==b["op"],"Original glyph command kind");check(a["points"].array().size()==b["points"].array().size(),"Original glyph control-point count");for(std::size_t p=0;p<a["points"].array().size();++p){const auto&ap=a["points"].array()[p].array();const auto&bp=b["points"].array()[p].array();check(closeEnough(ap[0].number()+dx,bp[0].number())&&closeEnough(ap[1].number()+dy,bp[1].number()),"Original CG glyph control points, including stroked round volume arc");}}}
m::NowPlayingViewInput input(){m::NowPlayingViewInput i;i.session=7;i.track=m::NowPlayingTrack{"中文 노래","Artist","Album",240,12.25,true,100,{},{},{},true};i.capabilities={true,true,true,true,true,true};i.lyrics=std::make_shared<m::NowPlayingLyrics>(*m::NowPlayingLyrics::parse("[00:00]First\n[00:20]Second\n[00:50]Third"));return i;}
const m::NowPlayingSurface&surface(const std::vector<m::NowPlayingSurface>&v,std::string_view id){for(const auto&s:v)if(s.id==id)return s;throw std::runtime_error("Missing prepared surface");}
void text(const m::NowPlayingSurface&s,const J&e,double dx=0,double dy=0){const auto&n=s.content;const auto&b=n["bounds"].array();rect({s.local.values[12],s.local.values[13],b[2].number(),b[3].number()},e["frame"],dx,dy);check(n["text"]["string"]==e["text"]&&n["text"]["fontSize"]==e["fontSize"]&&n["text"]["alignment"]==e["alignment"]&&n["text"]["truncation"]==e["truncation"],"Original caption/font size/alignment/truncation");rgba(n["text"]["foregroundColor"],e["foreground"]);}
void artwork(const m::NowPlayingPresentation&s,const J&e,bool volumePainted){const auto art=m::prepareNowPlayingArtwork(s);check(art.panel.size()==5&&art.lyrics.size()==3&&art.controls.size()==25&&art.volume.size()==6,"Fixed retained leaf count");
    for(const auto*list:{&art.panel,&art.lyrics,&art.controls,&art.volume})for(const auto&leaf:*list){check(leaf.content["children"].array().empty(),"No full-panel or nested positive-size raster surface");const auto&b=leaf.content["bounds"].array();check(b[2].number()>0&&b[3].number()>0,"Every raster leaf has valid nonzero bounds, including zero progress");}
    const auto&placeholder=surface(art.panel,"nowPlaying.placeholder");path(placeholder.content["shape"]["path"],node(e,"nowPlaying.panel/1")["path"],135,113);rgba(placeholder.content["shape"]["strokeColor"],node(e,"nowPlaying.panel/1")["stroke"]);check(placeholder.opacity==(node(e,"nowPlaying.panel/1")["hidden"].boolean()?0:1),"Source absent artwork stays a simple outlined placeholder");
    const auto&shade=surface(art.panel,"nowPlaying.metadataShade");const auto&originalShade=node(e,"nowPlaying.metadataShade");rect(m::NowPlayingGeometry::shade,originalShade["frame"],55);for(unsigned k=0;k<3;++k){rgba(shade.content["gradient"]["colors"].array()[k],originalShade["colors"].array()[k]);check(closeEnough(shade.content["gradient"]["locations"].array()[k].number(),originalShade["locations"].array()[k].number()),"Original metadata-only gradient stops");}
    text(surface(art.panel,"nowPlaying.title"),node(e,"nowPlaying.text.0"),55);text(surface(art.panel,"nowPlaying.artist"),node(e,"nowPlaying.text.1"),55);text(surface(art.panel,"nowPlaying.empty"),node(e,"nowPlaying.text.2"),55);
    for(unsigned k=0;k<3;++k){const auto&row=art.lyrics[k];const auto&expected=node(e,"nowPlaying.text."+std::to_string(6+k));text(row,expected,55,331);check(closeEnough(row.opacity,expected["opacity"].number(),2e-8),"Source lyric neighbor dimming");}
    text(surface(art.controls,"nowPlaying.elapsed"),node(e,"nowPlaying.text.3"));text(surface(art.controls,"nowPlaying.duration"),node(e,"nowPlaying.text.4"));
    for(const auto&action:s.actions()){const auto id="nowPlaying.control."+std::string(m::nowPlayingActionID(action.action));const auto&face=surface(art.controls,id+".face");const auto&glyph=surface(art.controls,id+".glyph");const auto&expected=node(e,id);check(closeEnough(face.opacity,expected["opacity"].number(),2e-8)&&glyph.opacity==face.opacity,"Source disabled control alpha is applied per leaf");rgba(face.content["backgroundColor"],node(e,id+"/0")["background"]);check(face.content["cornerRadius"]==node(e,id+"/0")["cornerRadius"]&&face.content["borderWidth"]==node(e,id+"/0")["borderWidth"],"Source circle/rounded faces have no visible border");path(glyph.content["shape"]["path"],node(e,id+"/1")["path"]);rgba(glyph.content["shape"]["fillColor"],node(e,id+"/1")["fill"]);}
    if(volumePainted){text(surface(art.volume,"nowPlaying.volume.label"),node(e,"nowPlaying.text.5"),357,218);const auto v=m::nowPlayingVolumeGeometry(s.input().volume.value_or(s.input().volumeAvailable?1:0),s.input().volumeAvailable);for(const auto&pair:std::array<std::pair<c::Rect,const char*>,5>{{{v.back,"/0"},{v.face,"/1"},{v.rail,"/2"},{v.fill,"/3"},{v.handle,"/4"}}})rect(pair.first,node(e,std::string("nowPlaying.volume.popover")+pair.second)["frame"],357,218);rgba(surface(art.volume,"nowPlaying.volume.face").content["backgroundColor"],node(e,"nowPlaying.volume.popover/1")["background"]);check(closeEnough(v.handleOpacity,node(e,"nowPlaying.volume.popover/4")["opacity"].number(),2e-8),"Unavailable volume keeps source dim thumb");}
}
void source(const char*filename){std::ifstream file(filename);check(bool(file),"Explicit immutable original-Canvas fixture");const auto fixture=J::parse(std::string((std::istreambuf_iterator<char>(file)),{}),1024*1024);check(fixture["sourceCommit"]==J("ca04f142185c7de40acd8523bdb563195d90a1d1"),"Original source authority pinned");m::NowPlayingPresentation s;auto i=input();double time=100;bool volumePainted{};
    for(const auto&e:fixture["cases"].array()){const auto name=e["name"].string();if(name=="playing-dark"){s.setActive(true,time);s.sync(i,time);}else if(name=="progress-interpolation")s.tick(time);else if(name=="seek-preview")s.pointerDown({220,388},time);else if(name=="lyric-forward"){const auto command=s.pointerUp(time);check(command&&command->kind==m::NowPlayingIntentKind::seek&&command->value==120,"Seek preview commits one source command");time=121;s.tick(time);}else if(name=="lyric-backward"){i.track->position=1;i.track->isPlaying=false;i.track->sampledAt=time;s.sync(i,time);}else if(name=="unavailable-volume"){s.perform(m::NowPlayingAction::volume,time);volumePainted=true;}else if(name=="available-volume"){i.volume=.42;i.volumeAvailable=true;i.capabilities.volume=true;s.sync(i,time);}else if(name=="lyrics-hidden")s.perform(m::NowPlayingAction::lyrics,time);else if(name=="metadata-change"){i.track->title="Changed song";s.sync(i,time);}else if(name=="failed-transport"){i.failed=true;s.sync(i,time);}else if(name=="light"){auto a=s.appearance();a.dark=false;s.setAppearance(a,time);}else if(name=="reduced-motion"){auto a=s.appearance();a.dark=true;a.reducedMotion=true;s.setAppearance(a,time);}else if(name=="deactivated")s.setActive(false,time);
        check(s.actions().size()==e["actions"].array().size(),"Source exact five actions");for(unsigned k=0;k<5;++k){const auto&a=s.actions()[k];const auto&expected=e["actions"].array()[k];rect(a.rect,expected["rect"]);check(m::nowPlayingActionID(a.action)==expected["id"].string()&&a.label==expected["label"].string()&&a.enabled==expected["enabled"].boolean(),"Source action identity/localization/availability");}
        check(s.sliderCount()==e["sliders"].array().size(),"Source only visible sliders");const auto sliders=s.sliders(time);for(unsigned k=0;k<s.sliderCount();++k){const auto&a=sliders[k];const auto&expected=e["sliders"].array()[k];rect(a.rect,expected["rect"]);check(a.enabled==expected["enabled"].boolean()&&a.minimum==expected["minimum"].number()&&a.maximum==expected["maximum"].number(),"Source slider bounds and availability");check(bool(a.value)==!expected["value"].isNull()&&(!a.value||closeEnough(*a.value,expected["value"].number())),"Source slider preview/value");}
        const auto pose=s.sample(time+1);check(closeEnough(pose.progressWidth,node(e,"nowPlaying.progress.fill")["bounds"].array()[2].number()),"Source retained progress destination");check(closeEnough(pose.progressHandleX,node(e,"nowPlaying.progress.handle")["frame"].array()[0].number()+2.5),"Source progress thumb centered on destination");
        if(name=="progress-interpolation"){const auto&anim=node(e,"nowPlaying.progress.fill")["animations"]["nowPlaying.progress"];check(anim["duration"].number()==1&&closeEnough(s.sample(time).progressWidth,anim["from"].number())&&closeEnough(s.sample(time+.5).progressWidth,(anim["from"].number()+anim["to"].number())/2),"Source one-second progress is linear and starts at sampled position");}
        if(name=="lyric-forward"||name=="lyric-backward"){const auto&anim=node(e,"nowPlaying.text.6")["animations"]["nowPlaying.lyrics.change"];check(anim["duration"].number()==m::NowPlayingPresentation::lyricChangeDuration&&s.sample(time).lyricTranslationY==anim["children"].array()[0]["from"].number(),"Source forward/backward cue motion");check(closeEnough(s.sample(time+.1).lyricOpacityFactor,.94),"Source cue fade independent of row base alpha");}
        artwork(s,e,volumePainted);
    }
    check(s.titleTransitionRevision()==1&&s.artistTransitionRevision()==0,"Only changed nonempty metadata starts source crossfade");check(!s.requiresFrames(time)&&!s.nextDisplayDeadline(time),"Hidden owner has no running animation or deadline");
    const auto&visible=node(find(fixture["cases"],"name","playing-dark"),"nowPlaying.lyrics")["animations"]["nowPlaying.lyrics.visibility"];check(visible["duration"].number()==m::NowPlayingPresentation::lyricsFadeDuration,"Original lyrics visibility duration");const auto&fade=node(find(fixture["cases"],"name","unavailable-volume"),"nowPlaying.volume.popover")["animations"]["nowPlaying.popover.visibility"];check(fade["duration"].number()==m::NowPlayingPresentation::volumeFadeDuration&&fade["timing"].isNull(),"Source volume animation has no explicit timing function");
    m::NowPlayingPresentation timing;timing.setActive(true,100);timing.sync(input(),100);timing.perform(m::NowPlayingAction::volume,100);for(const auto&row:fixture["opacityTiming"]["rows"].array())for(unsigned k=0;k<3;++k)check(std::abs(row["bgra"].array()[k].number()-255*timing.sample(100+row["phase"].number()*.16).volumeOpacity)<=.500001,"Actual detached Core Animation nil-timing volume fade is linear within8-bit rounding");
}
void lifecycle(){m::NowPlayingPresentation s;auto i=input();s.sync(i,100);check(!s.containsControl({220,388},100)&&!s.perform(m::NowPlayingAction::playPause,100),"Inactive controls cannot send commands");s.setActive(true,100);check(!s.containsControl({220,200},100)&&s.containsControl({368,410},100),"Transparent cover space leaves original HUD navigation exposed");
    check(s.nextDisplayDeadline(100)==100.75,"Single whole-second source display deadline");check(s.pointerDown({220,388},100).handled&&!s.pointerMove({385,388},100),"Seek dragging previews without repeated provider writes");check(s.nextDisplayDeadline(100)==100.75,"Drag preview does not alter actual playback deadline");i.track->position=13;i.track->sampledAt=100.75;s.sync(i,100.75);check(s.dragging(),"Same track refresh preserves source seek drag");i.track->title="Other";s.sync(i,100.75);check(!s.dragging()&&!s.pointerUp(100.75),"Changed track cancels pending seek");
    s.perform(m::NowPlayingAction::volume,101);check(s.capturesPointer()&&s.sliderCount()==2&&!s.sliders(101)[1].enabled&&s.volumeText()=="—","Unavailable source volume menu remains usable but sends no fabricated command");check(!s.setSlider(m::NowPlayingSliderKind::volume,.3,101),"Unsupported volume has no route");check(s.pointerDown({100,100},101).handled&&!s.capturesPointer(),"Outside click dismisses only original volume popover");
    i.volumeAvailable=true;i.capabilities.volume=true;i.volume=.8;s.sync(i,102);s.perform(m::NowPlayingAction::volume,102);const auto volume=s.pointerDown({383,300},102);check(volume.intent&&volume.intent->kind==m::NowPlayingIntentKind::volume&&s.dragging(),"Explicit volume route emits bounded slider intent");i.track.reset();s.sync(i,102);check(s.dragging(),"Same application losing track does not cancel a volume drag");i.session=9;s.sync(i,102);check(!s.dragging(),"Changed native session cancels any pending route interaction");
    i=input();i.track->duration=20;i.track->position=19;i.track->sampledAt=100;s.dismissVolume(103);s.sync(i,100);check(!s.tick(100)&&s.tick(101)&&!s.tick(101.1),"End refresh is requested exactly once at real playback end");s.pointerDown({55,388},101.2);s.sync(i,101.2);check(!s.tick(102),"Dragged preview cannot rearm end refresh");s.cancelDrag();i.track->position=1;i.track->sampledAt=102;s.sync(i,102);check(!s.tick(102)&&s.tick(121),"A genuine earlier playback position rearms source end refresh");
    i=input();i.playbackRate=2;s.sync(i,100);check(s.nextDisplayDeadline(100)==100.375,"Windows supplied positive playback rate preserves real timeline speed");s.tick(100);check(closeEnough(s.sample(101).progressWidth,330*14.25/240),"Numeric interpolation honors real native rate without changing source1x behavior");i.playbackRate=0;s.sync(i,100);check(!s.nextDisplayDeadline(100)&&s.sliders(110)[0].value==12.25,"Unknown native rate holds position and installs no guessed timer");
    i=input();i.lyrics.reset();s.sync(i,100);check(!s.lyricsVisible()&&s.lyricsSelected(),"Missing lyrics remain selected with hidden empty reserved viewport");s.perform(m::NowPlayingAction::lyrics,100);check(!s.lyricsVisible()&&!s.lyricsSelected(),"Lyrics control still toggles source preference without invented text");
    const auto revision=s.contentRevision();const auto before=allocations.load();double total{};for(unsigned n=0;n<10000;++n){const double time=100.+double(n)/1000;const auto p=s.sample(time);total+=p.progressWidth+s.nextDisplayDeadline(time).value_or(0);total+=s.requiresFrames(time)?1:0;total+=s.sliders(time)[0].value.value_or(0);total+=s.containsControl({220,388},time)?1:0;}check(total>0&&allocations.load()==before&&s.contentRevision()==revision,"Warm numeric frames/deadlines/input hit tests allocate nothing and do not rebuild content");
    s.setActive(false,110);check(!s.nextDisplayDeadline(110)&&!s.requiresFrames(110)&&!s.capturesPointer(),"Deactivate removes local work and pointer capture");
    for(auto language:{c::Language::english,c::Language::simplifiedChinese,c::Language::traditionalChinese,c::Language::japanese,c::Language::system,c::Language::korean}){auto a=s.appearance();a.language=language;s.setAppearance(a,110);check(s.actions()[0].label==c::localized("Lyrics","歌词",language),"All language settings use existing shared localization");}
}
}
int main(int argc,char**argv){try{check(argc==2,"Pass immutable original Canvas fixture");source(argv[1]);lifecycle();std::cout<<"Now Playing presentation: "<<checks<<" checks passed\n";return 0;}catch(const std::exception&e){std::cerr<<"Now Playing presentation failed after "<<checks<<": "<<e.what()<<'\n';return 1;}}
