#include "tools/now_playing_session.hpp"
#include <iostream>
#include "core/data/json.hpp"
#include <fstream>
#include <stdexcept>
namespace n=endfield::native;namespace m=endfield::modules;namespace t=endfield::tools;using Q=endfield::app::UtilityExecutor;
namespace {double sourceRollback{};unsigned checks{};void check(bool b,const char*w){++checks;if(!b)throw std::runtime_error(w);}
struct Provider:n::NowPlayingProvider{Changed changed;Ready startReady,commandReady;Read readReady;unsigned commands{},reads{},stops{};m::NowPlayingCommand command;
 void start(Changed c,Ready r)override{changed=std::move(c);startReady=std::move(r);}void read(Read r)override{++reads;readReady=std::move(r);}void perform(std::uint64_t,std::uint64_t,m::NowPlayingCommand c,Ready r)override{++commands;command=c;commandReady=std::move(r);}void stop()noexcept override{++stops;}};
n::NowPlayingReadResult media(double position=10,bool playing=false,unsigned session=1,std::string title="原曲 – Source track"){n::NowPlayingReadResult r;r.value.sessions={{1,"same.app","Player"},{2,"same.app","Player"}};r.value.session=r.value.sessions[session-1];m::NowPlayingTrack track;track.title=std::move(title);track.duration=240;track.position=position;track.isPlaying=playing;track.sampledAt=10;r.value.track=track;r.value.capabilities={true,true,true,true,true,true};r.value.metadataRevision=4;return r;}
struct Fixture{Q q{[]{}};std::shared_ptr<Provider>p=std::make_shared<Provider>();double now=10;unsigned notices{};n::NativeNowPlayingService service{q,[this]{return p;},[]{},[this]{return now;}};t::NowPlayingSession owner{service,q,{},[this]{++notices;}};
 void work(){q.waitIdle();q.drain();}void flush(){work();owner.utilityCompleted(now);work();}void ready(n::NowPlayingReadResult r=media()){owner.setActive(true,now);flush();p->startReady({});flush();p->readReady(std::move(r));flush();}
 bool seek(double value){return owner.dispatch({m::NowPlayingIntentKind::seek,1,value},now);}void read(n::NowPlayingReadResult r){service.refresh();flush();p->readReady(std::move(r));flush();}
};
void optimism(){Fixture f;f.ready();check(!f.owner.nextWakeTime(f.now)&&!f.owner.optimisticSeek(),"Paused source snapshot needs no display timer");check(f.seek(90),"Exact source seek is accepted");f.work();check(f.owner.optimisticSeek()&&f.owner.presentation().input().track->position==90,"Accepted seek updates only owner presentation immediately");check(f.service.snapshot().media.track->position==10,"Observed provider state stays independent of optimism");f.now=12;f.p->commandReady({});f.flush();check(f.owner.nextWakeTime(f.now)==12+sourceRollback,"Rollback begins2.5seconds after actual completion");f.p->readReady(media(10));f.flush();check(f.owner.optimisticSeek()&&f.owner.presentation().input().track->position==90,"First stale timestamp after success is not an acknowledgement");f.now=14.49;f.owner.deadline(f.now);check(f.owner.optimisticSeek(),"Seek remains until exact source rollback deadline");f.now=14.5;check(f.owner.deadline(f.now)&&!f.owner.optimisticSeek()&&f.owner.presentation().input().track->position==10,"Rollback restores latest actual observation at the exported deadline");check(!f.owner.nextWakeTime(f.now),"Completed rollback does not rearm a timer");
 f.now=15;f.seek(100);f.work();f.p->commandReady({});f.flush();f.p->readReady(media(101.25));f.flush();check(!f.owner.optimisticSeek()&&f.owner.presentation().input().track->position==101.25,"Original inclusive1.25second acknowledgement retires optimism");
 f.now=16;f.seek(120);f.work();f.p->commandReady({});f.flush();f.p->readReady(media(121.2501));f.flush();check(f.owner.optimisticSeek(),"Outside original acknowledgement tolerance remains optimistic");f.now=17;f.read(media(80,false,2));check(!f.owner.optimisticSeek()&&f.owner.presentation().input().session==2,"Same application distinct native session cannot inherit a seek");}
void queuedAndFailure(){Fixture f;f.ready();f.service.refresh();f.flush();f.seek(80);check(f.owner.optimisticSeek(),"Queued unsent seek is visible");f.owner.dispatch({m::NowPlayingIntentKind::next,1},f.now);check(!f.owner.optimisticSeek()&&f.owner.presentation().input().track->position==10,"Later transport replacing unsent seek rolls back immediately");f.p->readReady(media());f.flush();check(f.p->commands==1&&f.p->command.kind==m::NowPlayingCommandKind::next,"Replaced queued seek is never sent");f.p->commandReady({});f.flush();f.p->readReady(media());f.flush();f.seek(50);f.work();f.owner.dispatch({m::NowPlayingIntentKind::next,1},f.now);check(f.owner.optimisticSeek(),"Queued transport does not erase an already executing seek");f.p->commandReady({});f.flush();f.p->commandReady({n::NowPlayingServiceFailure::unavailable});f.flush();check(!f.owner.optimisticSeek(),"Source failure of later transport clears the same earlier optimistic seek");
 Fixture pending;pending.ready();pending.service.refresh();pending.flush();pending.seek(90);pending.now=13;pending.owner.deadline(pending.now);check(!pending.owner.optimisticSeek()&&pending.owner.presentation().input().failed,"Terminal read timeout cannot strand an unsent optimistic seek");
 Fixture changed;changed.ready();changed.service.refresh();changed.flush();changed.seek(90);changed.p->readReady(media(0,false,1,"Different song"));changed.flush();check(!changed.owner.optimisticSeek()&&changed.p->commands==0,"Track replacement clears and discards stale queued seek");}
void displayAndCapabilities(){Fixture f;auto r=media(10,true);r.value.track->duration=12;f.ready(std::move(r));check(f.owner.nextWakeTime(f.now)==11,"Source display clock exports next whole second");const auto reads=f.p->reads;f.now=10.5;check(!f.owner.deadline(f.now)&&f.p->reads==reads,"Early deadline call neither polls nor rebuilds");f.now=11;check(f.owner.deadline(f.now)&&f.owner.presentation().elapsedText()=="0:11"&&f.owner.nextWakeTime(f.now)==12,"Whole-second deadline updates visible time and rearms once");f.now=12;f.owner.deadline(f.now);f.work();check(f.p->reads==reads+1,"Track end triggers one actual metadata refresh");f.p->readReady(media(12,false));f.flush();f.now=20;for(unsigned k=0;k<100;++k){f.owner.deadline(f.now);f.owner.utilityCompleted(f.now);}check(f.p->reads==reads+1&&!f.owner.nextWakeTime(f.now),"Paused settled state has no repeated reads or timer");auto&view=f.owner.presentation();view.perform(m::NowPlayingAction::volume,f.now);f.owner.presentationChanged(f.now);check(view.capturesPointer()&&view.volumeText()=="—"&&!view.sliders(f.now)[1].enabled,"Unsupported volume preserves original unavailable submenu");check(!f.owner.dispatch({m::NowPlayingIntentKind::volume,1,.5},f.now)&&!view.lyricsVisible(),"No invented volume command or lyric content");f.owner.setActive(false,f.now);check(!f.service.snapshot().active&&!f.owner.nextWakeTime(f.now)&&!view.capturesPointer(),"Hide stops subscription and clears menu/deadlines");}
void staleLifecycle(){Fixture f;f.ready();f.seek(40);f.work();const auto late=f.p->commandReady;f.owner.setActive(false,f.now);late({});f.flush();check(!f.owner.optimisticSeek()&&!f.owner.active(),"Late completion cannot revive hidden seek");f.ready(media(20));check(f.owner.presentation().input().track->position==20&&!f.owner.optimisticSeek(),"New activation starts from actual fresh session snapshot");f.owner.setActive(false,f.now);
 Q q([]{});double now=0;std::unique_ptr<t::NowPlayingSession>owner;auto p=std::make_shared<Provider>();n::NativeNowPlayingService service(q,[&]{owner->setActive(false,now);return p;},[]{},[&]{return now;});owner=std::make_unique<t::NowPlayingSession>(service,q,m::NowPlayingAppearance{},[]{});owner->setActive(true,now);check(!owner->active()&&!service.snapshot().active&&p->stops==1,"Reentrant conceal during factory supersedes outer activation");
}
void source(const char*path){std::ifstream in(path,std::ios::binary);check(bool(in),"Read original seek rollback fixture");const auto j=ehud::data::Json::parse(std::string((std::istreambuf_iterator<char>(in)),{}),16384);check(j["sourceCommit"].string()=="ca04f142185c7de40acd8523bdb563195d90a1d1","Original controller rollback is pinned");for(const auto&row:j["rollback"].array()){sourceRollback=row["delay"].number();const bool same=row["mode"].string()=="same";check(row["hasSeek"].boolean()!=same&&row["changes"].integer()==(same?1:0)&&row["position"].integer()==(same?10:90),"Executed original callback rolls back only the still-current active seek");}check(sourceRollback>0,"Original scheduler supplied a real rollback delay");}
}
int main(int argc,char**argv){try{check(argc==2,"Pass immutable original owner source fixture");source(argv[1]);optimism();queuedAndFailure();displayAndCapabilities();staleLifecycle();std::cout<<"Now Playing session: "<<checks<<" checks passed (injected provider, original source seek/deadline rules)\n";return 0;}catch(const std::exception&e){std::cerr<<"Now Playing session failed after "<<checks<<": "<<e.what()<<'\n';return 1;}}
