#include "tools/now_playing_session.hpp"
#include "core/data/json.hpp"
#include <fstream>
#include <future>
#include <iostream>
namespace n=endfield::native;namespace m=endfield::modules;namespace t=endfield::tools;using Q=endfield::app::UtilityExecutor;
namespace {unsigned checks{};double sourceObserved{};void check(bool b,const char*w){++checks;if(!b)throw std::runtime_error(w);}
struct Provider:n::NowPlayingProvider{Changed changed;Ready ready,done;Read reading;unsigned commands{};bool stopped{};void start(Changed c,Ready r)override{changed=std::move(c);ready=std::move(r);}void read(Read r)override{reading=std::move(r);}void perform(std::uint64_t,std::uint64_t,m::NowPlayingCommand,Ready r)override{++commands;done=std::move(r);}void stop()noexcept override{stopped=true;}};
std::shared_ptr<const std::vector<std::uint8_t>>bytes(unsigned color){return std::make_shared<const std::vector<std::uint8_t>>(1,static_cast<std::uint8_t>(color));}
n::NowPlayingReadResult media(unsigned color=1,std::string title="Cached source song",std::uint64_t session=7){n::NowPlayingReadResult r;r.value.sessions={{session,"same.player","Owned fixture"}};r.value.session=r.value.sessions[0];r.value.track=m::NowPlayingTrack{std::move(title),"Artist","Album",240,12,false,10,{},{},{},true};r.value.artwork=bytes(color);r.value.capabilities={true,true,true,true,true,true};return r;}
auto image(unsigned color){auto p=std::make_shared<n::NotesImageFrame>();p->width=p->height=1;p->straightRGBA={static_cast<std::uint8_t>(color),0,0,255};return p;}
void source(const char*path){std::ifstream in(path,std::ios::binary);check(bool(in),"Read independently executed original warm lifecycle");const auto j=ehud::data::Json::parse(std::string((std::istreambuf_iterator<char>(in)),{}),8192);check(j["sourceCommit"].string()=="ca04f142185c7de40acd8523bdb563195d90a1d1","Original source warm fixture is pinned");for(const auto&row:j["rows"].array()){check(row["hiddenTrack"].isNull()&&!row["hiddenActive"].boolean()&&row["optimisticSeek"].isNull(),"Original source clears live controller and optimism on hide");check(!row["fresh"].boolean()&&row["refreshes"].integer()==1,"Original activate requests one fresh read after immediate restoration");if(row["alive"].boolean()){sourceObserved=row["visibleTrack"].number();check(sourceObserved==row["warmTrack"].number()&&sourceObserved==12&&row["changed"].integer()==1,"Original source restores observed12, not unacknowledged optimistic90");}else check(row["visibleTrack"].isNull()&&row["changed"].integer()==0,"Original Mac restoration depends on its actual app-alive check");}}
void warm(){Q q([]{});double now=10;unsigned decodes{};std::shared_ptr<Provider>p;std::promise<void>entered,release;auto gate=release.get_future().share();n::NativeNowPlayingService service(q,[&]{p=std::make_shared<Provider>();return p;},[]{},[&]{return now;});t::NowPlayingSession owner(service,q,{},[]{},[&](auto b){++decodes;if(b[0]==2){entered.set_value();gate.wait();}return n::NowPlayingImageResult{image(b[0])};});auto work=[&]{q.waitIdle();q.drain();};auto flush=[&]{work();owner.utilityCompleted(now);work();owner.utilityCompleted(now);};
 owner.setActive(true,now);work();p->ready({});flush();p->reading(media());flush();check(owner.artwork()&&owner.artwork()->straightRGBA[0]==1&&decodes==1,"Initial actual metadata/artwork decoded once");const auto cover=owner.artwork();const auto coverRevision=owner.presentation().input().coverRevision;
 check(owner.dispatch({m::NowPlayingIntentKind::seek,7,90},now),"Synthetic optimistic seek is active before conceal");work();const auto late=p->done;check(owner.presentation().input().track->position==90,"Outgoing source display currently contains optimistic90");owner.setActive(false,now);check(p->stopped&&!service.snapshot().active&&!owner.nextWakeTime(now)&&owner.artwork()==cover,"Hide stops service and retains actual decoded cover without clock");now=20;owner.setActive(true,now);
 check(owner.presentation().input().track&&owner.presentation().input().track->title=="Cached source song"&&owner.presentation().input().track->position==sourceObserved,"Reopen immediately restores original observed metadata before first provider callback");check(owner.artwork()==cover&&owner.presentation().input().coverRevision==coverRevision,"Cached thumbnail is immediately visible with unchanged retained identity");check(!service.snapshot().fresh&&owner.presentation().input().failed&&!owner.presentation().actions()[2].enabled,"Unconfirmed cached display never claims a current command-capable session");check(!owner.dispatch({m::NowPlayingIntentKind::playPause,7},now),"No native action may target the unconfirmed cached token");work();p->ready({});flush();const auto queued=q.stats().accepted;for(unsigned k=0;k<100;++k)owner.utilityCompleted(now);check(q.stats().accepted==queued&&decodes==1&&owner.artwork()==cover,"Pending read neither blanks cached content nor retries/polls artwork");
 p->reading(media(2,"Cached source song",11));owner.utilityCompleted(now);entered.get_future().wait();check(owner.presentation().input().session==11&&!owner.presentation().input().failed&&owner.presentation().actions()[2].enabled,"Fresh current session atomically replaces cached identity and enables its actual capabilities");check(owner.artwork()==cover&&owner.presentation().input().coverRevision==coverRevision,"Same-track fresh thumbnail decode keeps cached cover visible");late({});owner.utilityCompleted(now);check(owner.artwork()==cover&&!owner.optimisticSeek(),"Old activation seek completion cannot rewrite restored actual metadata");release.set_value();flush();check(owner.artwork()!=cover&&owner.artwork()->straightRGBA[0]==2,"Actual decoded replacement replaces cached cover once");
 const auto freshCover=owner.artwork();owner.setActive(false,now);now+=1;owner.setActive(true,now);check(owner.artwork()==freshCover&&owner.presentation().input().track->title=="Cached source song","Second reopen has no metadata or artwork waiting state");owner.setActive(false,now);owner.setActive(true,now);check(owner.artwork()==freshCover&&owner.presentation().input().track->position==12,"Hide/reopen before any fresh callback preserves only the same bounded warm slot");work();p->ready({});flush();p->reading(media(3,"Different actual song",12));owner.utilityCompleted(now);check(owner.presentation().input().track->title=="Different actual song"&&!owner.artwork(),"Actual changed track retires unrelated warm cover immediately");flush();check(owner.artwork()&&owner.artwork()->straightRGBA[0]==3,"New track publishes its own actual artwork");
 service.refresh();flush();p->reading({});flush();check(!owner.presentation().input().track&&!owner.artwork(),"Fresh confirmed empty session clears cached content");owner.setActive(false,now);owner.setActive(true,now);check(!owner.presentation().input().track&&!owner.artwork(),"Confirmed empty media never resurrects an old warm song");owner.setActive(false,now);
}
}
int main(int argc,char**argv){try{check(argc==2,"Pass original warm lifecycle fixture");source(argv[1]);warm();std::cout<<"Now Playing warm reopen: "<<checks<<" checks passed (owned source fixture/injected sessions)\n";return 0;}catch(const std::exception&e){std::cerr<<"Now Playing warm failed after "<<checks<<": "<<e.what()<<'\n';return 1;}}
