#ifdef _WIN32
#include "tools/now_playing_preview.hpp"
#include "native/module_scene.hpp"
#include <windows.h>
#include <objbase.h>
#include <atomic>
#include <cstdlib>
#include <iostream>
#include <new>
namespace {std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {namespace n=endfield::native;namespace m=endfield::modules;namespace c=endfield::core;namespace a=endfield::app;namespace t=endfield::tools;using J=ehud::data::Json;
unsigned checks{};void check(bool b,const char*w){++checks;if(!b)throw std::runtime_error(w);}struct Apartment{HRESULT hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);~Apartment(){if(SUCCEEDED(hr))CoUninitialize();}};
struct Window{HWND hwnd{};Window(){WNDCLASSW cls{};cls.lpfnWndProc=DefWindowProcW;cls.hInstance=GetModuleHandleW(nullptr);cls.lpszClassName=L"OwnedNowPlayingPreviewFixture";check(RegisterClassW(&cls),"Register isolated Now Playing owner fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,cls.lpszClassName,L"Synthetic media only",WS_POPUP,0,0,1280,800,nullptr,nullptr,cls.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Fixture stays hidden without touching a media player");}~Window(){DestroyWindow(hwnd);UnregisterClassW(L"OwnedNowPlayingPreviewFixture",GetModuleHandleW(nullptr));}};
struct Provider:n::NowPlayingProvider{Changed changed;Ready ready,done;Read reading;unsigned starts{},reads{},commands{},stops{};m::NowPlayingCommand command;
 void start(Changed c,Ready r)override{++starts;changed=std::move(c);ready=std::move(r);}void read(Read r)override{++reads;reading=std::move(r);}void perform(std::uint64_t,std::uint64_t,m::NowPlayingCommand c,Ready r)override{++commands;command=c;done=std::move(r);}void stop()noexcept override{++stops;}};
n::NowPlayingReadResult media(){n::NowPlayingReadResult r;r.value.sessions={{7,"synthetic.player","Owned fixture"}};r.value.session=r.value.sessions.front();r.value.track=m::NowPlayingTrack{"原曲 노래","Synthetic artist","Album",240,12,false,1,{},{},{},true};r.value.capabilities={true,true,true,true,true,true};return r;}
J blank(){return J::Object{{"bounds",J::Array{0,0,440,440}},{"position",J::Array{0,0}},{"anchorPoint",J::Array{0,0}},{"children",J::Array{}}};}
void run(n::Renderer&r){n::LayerRasterizer raster;a::UtilityExecutor utility([]{});auto provider=std::make_shared<Provider>();double now{};unsigned changes{},locks{};n::NativeNowPlayingService service(utility,[&]{return provider;},[]{},[&]{return now;});t::NowPlayingPreviewOptions options;options.raster.pixelsPerPoint=1;options.changed=[&]{++changes;};options.onLock=[&]{++locks;};t::NowPlayingPreview owner(service,raster,utility,std::move(options));owner.resize({1280,800,96,1,1280,800});n::LayerComposition composition;c::ModulePresentation modules(c::Module::power);n::LayerScene geometry(raster);geometry.load(blank(),{});n::NativeModuleSurface plane(geometry,c::Module::nowPlaying);c::source::DesktopChromeSettings settings{{0,0,1280,800},1,{},c::Module::power,true};auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;const auto camera=n::layerViewportProjection(1280,800);bool released{};struct Guard{n::Renderer&r;n::LayerComposition&c;t::NowPlayingPreview&o;bool&done;~Guard(){if(!done)try{c.detach(r);o.release(r);}catch(...){r.reset();}}}guard{r,composition,owner,released};
 auto frame=[&](double step=.01){now+=step;const auto sample=modules.sample(now).presentation;settings.module=sample.requested;owner.update(center,settings,sample,1,now);owner.upload(r);composition.setEntries(r,owner.entries());composition.present(r);r.setCamera(camera);};
 auto point=[&](c::Point p){const auto sample=modules.sample(now).presentation;const auto*shown=sample.current.module==c::Module::nowPlaying?&sample.current:&*sample.incoming;plane.update(center,settings,*shown);return *c::Projection::viewport(camera*plane.pose().contentWorld,1280,800).project(p);};
 auto work=[&]{utility.waitIdle();utility.drain();};auto flush=[&]{work();owner.utilityCompleted(now);work();};auto press=[&](c::Point p){auto q=point(p);return owner.pointer({a::PointerKind::down,a::PointerButton::left,q.x,q.y},now);};auto up=[&](c::Point p){auto q=point(p);return owner.pointer({a::PointerKind::up,a::PointerButton::left,q.x,q.y},now);};
 frame();check(owner.entries().empty()&&!service.snapshot().active&&utility.stats().accepted==0,"Unselected owner creates no provider task or scene publication");modules.select(c::Module::nowPlaying,now);frame(.02);work();check(service.snapshot().active&&provider->starts==1&&!owner.covers(point({220,220})),"Subscription begins during reveal while native input remains disabled");provider->ready({});flush();provider->reading(media());flush();frame(1);check(owner.covers(point({220,220}))&&!owner.containsControl(point({220,220}),now),"Transparent cover accepts fallback click without stealing priority from HUD navigation");check(owner.containsControl(point({50,420}),now),"Original play control is priority input");frame(.3);r.draw(false);
 const auto before=raster.stats();const auto gpu=r.stats();const auto queued=utility.stats().accepted;const auto notified=changes;allocations=0;counting=true;try{for(unsigned k=0;k<120;++k)frame(1./60.);}catch(...){counting=false;throw;}counting=false;check(allocations==0,"Warm retained owner frames allocate zero C++ objects");check(raster.stats().rasterizations==before.rasterizations&&r.stats().textureUploads==gpu.textureUploads&&utility.stats().accepted==queued&&changes==notified&&!owner.nextWakeTime(),"Paused warm frames schedule, notify and rerasterize nothing");
 check(press({220,220})&&up({220,220})&&locks==1&&provider->commands==0,"Source background canvas click locks gyro but fabricates no media action");check(owner.perform(m::NowPlayingAction::volume,now)&&owner.capturesPointer()&&!owner.pointerLocked(),"Unavailable volume opens original menu without drag lock");check(!owner.setSlider(m::NowPlayingSliderKind::volume,.5,now)&&owner.presentation().volumeText()=="—","Unsupported volume never dispatches guessed native commands");auto outside=point({500,500});check(owner.pointer({a::PointerKind::down,a::PointerButton::left,outside.x,outside.y},now)&&!owner.capturesPointer(),"Open menu consumes outside click and dismisses");check(!owner.key({a::KeyKind::down,VK_ESCAPE},false,now),"Closed menu leaves Escape to HUD");check(!owner.key({a::KeyKind::down,VK_SPACE},true,now),"Modified transport key is not consumed");check(owner.key({a::KeyKind::down,VK_RIGHT},false,now),"Unmodified source five-second seek is available");work();check(provider->command.kind==m::NowPlayingCommandKind::seek&&provider->command.seconds==17,"Keyboard seek uses actual current position plus5");provider->done({});flush();provider->reading(media());flush();now+=2.5;owner.deadline(now);check(owner.presentation().input().track->position==12,"Unacknowledged seek rolls back to actual provider metadata");
 check(press({200,387})&&owner.pointerLocked(),"Original seek rail starts drag lock");const auto drag=point({500,387});owner.pointer({a::PointerKind::move,a::PointerButton::none,drag.x,drag.y},now);check(up({500,387})&&!owner.pointerLocked(),"Owned drag finishes beyond canvas bounds");work();check(provider->command.seconds==240,"Original seek drag clamps to duration");
 owner.setLanguage(c::Language::korean,now);frame();check(owner.presentation().appearance().language==c::Language::korean,"Language event reaches shared source labels");const auto localized=raster.stats();owner.setLanguage(c::Language::korean,now);frame();check(raster.stats().rasterizations==localized.rasterizations,"Equal language update does not reshape text");raster.setDefaultFontLanguage(n::LayerFontLanguage::korean);frame();check(raster.stats().textLayoutsCreated>localized.textLayoutsCreated,"Shared font revision refreshes native text once");
 owner.setOverlayVisible(false,now);check(!service.snapshot().active&&!owner.pointerLocked()&&!owner.nextWakeTime()&&!owner.capturesPointer(),"Conceal stops provider and clears all input/deadline state");const auto retained=owner.presentation().input().track->title;frame();check(owner.presentation().input().track->title==retained&&!owner.requiresFrames(now),"Outgoing actual content remains retained after service deactivation");provider->done({});flush();check(!service.snapshot().active,"Late completion does not reopen hidden owner");modules.select(c::Module::power,now);frame(1);check(owner.entries().empty(),"Completed module departure removes its two composition entries");composition.detach(r);owner.release(r);released=true;check(r.stats().textures==0&&r.stats().meshes==0&&r.stats().nativeGroups==0,"Detached owner releases all retained local resources");utility.shutdown();
}
void reentry(){n::LayerRasterizer raster;a::UtilityExecutor queue([]{});double time{};auto p=std::make_shared<Provider>();std::unique_ptr<t::NowPlayingPreview>owner;bool hideInFactory=true;n::NativeNowPlayingService service(queue,[&]{if(hideInFactory)owner->setOverlayVisible(false,time);return p;},[]{},[&]{return time;});t::NowPlayingPreviewOptions options;options.raster.pixelsPerPoint=1;bool destroy{};options.onLock=[&]{owner.reset();};options.changed=[&]{if(destroy)owner.reset();};owner=std::make_unique<t::NowPlayingPreview>(service,raster,queue,options);owner->resize({1280,800,96,1,1280,800});c::ModulePresentation modules(c::Module::nowPlaying);c::source::DesktopChromeSettings settings{{0,0,1280,800},1,{},c::Module::nowPlaying,true};const auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;owner->update(center,settings,modules.sample(time).presentation,1,time);check(!service.snapshot().active&&!owner->nextWakeTime(),"Nested conceal supersedes outer provider activation");hideInFactory=false;owner->setOverlayVisible(true,time);owner->update(center,settings,modules.sample(time).presentation,1,time);check(owner->key({a::KeyKind::down,VK_SPACE},false,time)&&!owner&&!service.snapshot().active,"Source lock callback may destroy owner before a transport operation");owner=std::make_unique<t::NowPlayingPreview>(service,raster,queue,options);destroy=true;auto appearance=m::NowPlayingAppearance{};appearance.dark=false;check(owner->setAppearance(appearance,time)&&!owner,"Appearance invalidation may destroy owner safely");queue.waitIdle();queue.drain();}
}
int wmain(int argc,wchar_t**argv){Apartment apartment;try{check(SUCCEEDED(apartment.hr)&&argc==2,"Pass shared HUD shader");reentry();Window window;n::Renderer renderer;renderer.initialize(window.hwnd,1280,800,{n::Driver::warpForTests,argv[1],n::RenderTarget::offscreenForTests});run(renderer);renderer.reset();check(!IsWindowVisible(window.hwnd),"All native tests kept fixture hidden");std::cout<<"Now Playing owner: "<<checks<<" checks passed (synthetic provider only)\n";return 0;}catch(const std::exception&e){counting=false;std::cerr<<"Now Playing owner failed after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
