#include "native/now_playing_scene.hpp"
#include "core/data/json.hpp"
#include <cmath>
#include <fstream>
#include <iostream>
#include <filesystem>
#include <array>
namespace opacity_source {
using J=ehud::data::Json;unsigned checks{};
void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}
J load(const std::filesystem::path&path){std::ifstream input(path,std::ios::binary);check(bool(input),"Read immutable opacity source fixture");auto j=J::parse(std::string((std::istreambuf_iterator<char>(input)),{}),128*1024);check(j["sourceCommit"]==J("ca04f142185c7de40acd8523bdb563195d90a1d1")&&j["rows"].array().size()==28,"Original topology plus unchanged original fade block are pinned");return j;}
void run(const J&j){for(const auto&row:j["rows"].array()){const auto plan=endfield::native::nowPlayingGroupOpacity(row["inheritedOpacity"].number(),row["ownOpacity"].number());std::array<double,4>result{};for(const auto&leaf:row["leafRGBA"].array()){const auto&rgba=leaf.array();const auto alpha=rgba[3].number()*plan.leaf;for(unsigned k=0;k<3;++k)result[k]=rgba[2-k].number()*alpha+result[k]*(1-alpha);result[3]=alpha+result[3]*(1-alpha);}for(unsigned k=0;k<4;++k)check(std::abs(result[k]*plan.output*255-row["bgra"].array()[k].number())<=2,"Production opacity decision matches static and actual-source animated CA samples");}
 for(auto value:{-1.,2.,double(NAN)}){bool rejected{};try{endfield::native::nowPlayingGroupOpacity(value,1);}catch(const std::invalid_argument&){rejected=true;}check(rejected,"Malformed inherited opacity is rejected");}}
const J&volume(const J&j,double own){for(const auto&r:j["rows"].array())if(r["palette"]==J("volume")&&r["animated"].boolean()&&r["ownOpacity"].number()==own)return r["bgra"];throw std::runtime_error("Missing original volume opacity sample");}
}
#ifdef _WIN32
#include "native/now_playing_scene.hpp"
#include <windows.h>
#include <objbase.h>
#include <atomic>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <new>
namespace {std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {
namespace n=endfield::native;namespace m=endfield::modules;namespace c=endfield::core;using J=ehud::data::Json;
unsigned checks{};void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}
template<class F>void rejects(F&&f,const char*why){bool rejected{};try{f();}catch(const std::exception&){rejected=true;}check(rejected,why);}
struct Apartment {HRESULT hr{CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED)};~Apartment(){if(SUCCEEDED(hr))CoUninitialize();}};
struct Window {HWND hwnd{};Window(){WNDCLASSW cls{};cls.lpfnWndProc=DefWindowProcW;cls.hInstance=GetModuleHandleW(nullptr);cls.lpszClassName=L"OwnedNowPlayingSceneFixture";check(RegisterClassW(&cls),"Register owned hidden Now Playing fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,cls.lpszClassName,L"Synthetic music metadata",WS_POPUP,0,0,440,440,nullptr,nullptr,cls.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Fixture remains hidden and does not activate a player");}~Window(){DestroyWindow(hwnd);UnregisterClassW(L"OwnedNowPlayingSceneFixture",GetModuleHandleW(nullptr));}};
std::shared_ptr<const n::NotesImageFrame>image(std::array<std::uint8_t,4>color){auto value=std::make_shared<n::NotesImageFrame>();value->width=value->height=8;value->straightRGBA.resize(8*8*4);for(unsigned i=0;i<64;++i)std::copy(color.begin(),color.end(),value->straightRGBA.begin()+i*4);return value;}
m::NowPlayingViewInput input(){m::NowPlayingViewInput value;value.session=7;value.track=m::NowPlayingTrack{"中文 노래","Artist","Album",240,12.25,false,10,{},{},{},true};value.capabilities={true,true,true,true,true,true};value.coverAvailable=true;value.coverRevision=1;return value;}
void pixel(n::Renderer&r,unsigned x,unsigned y,const J&expected,const char*why){r.draw(false);const auto frame=r.readback();for(unsigned channel=0;channel<4;++channel)check(std::abs(int(frame.pixels[y*frame.rowBytes+x*4+channel])-int(expected.array()[channel].integer()))<=2,why);}
void native(n::Renderer&r,n::LayerRasterizer&raster,const J&reference,const J&opacityReference){
    const J*source{};for(const auto&row:reference["rows"].array())if(row["phase"].number()==.5&&row["oldRGBA"].array()[3].number()==.4&&row["newRGBA"].array()[3].number()==.4){source=&row;break;}check(source,"Measured original translucent CATransition fixture is present");
    m::NowPlayingPresentation presentation;auto in=input();presentation.sync(in,10);n::LayerRasterOptions options;options.pixelsPerPoint=1;n::NativeNowPlayingScene scene(presentation,raster,options);n::LayerComposition composition;bool released{};struct Guard {n::Renderer&r;n::LayerComposition&c;n::NativeNowPlayingScene&s;bool&done;~Guard(){if(!done)try{c.detach(r);s.releaseResources(r);}catch(...){r.reset();}}}guard{r,composition,scene,released};
    auto artwork=image({255,0,0,102});double time=10;scene.syncContent(artwork,time);
    const auto frame=[&](double now,c::Matrix4 world=c::Matrix4{},float alpha=1,std::span<const n::PlaneMask>masks={}){time=now;scene.syncContent(artwork,time);scene.updatePose({world,alpha,time,masks,{}});scene.uploadResources(r);const auto entry=scene.entry();composition.setEntries(r,std::span(&entry,1));composition.present(r);};
    frame(10);check(scene.stats().rasterSurfaces==38&&r.stats().nativeGroups==6,"Fixed bounded local leaves and six retained composition groups");pixel(r,220,100,(*source)["priorBGRA"],"Source cover retains encoded premultiplied pixels");pixel(r,10,100,J::Array{0,0,0,0},"Square-cover surrounding canvas stays transparent");pixel(r,55,1,(*source)["priorBGRA"],"Cover corner remains square without invented rounding");
    presentation.setActive(true,10);frame(10);artwork=image({0,0,255,102});in.coverRevision=2;in.track->title="Changed metadata";presentation.sync(in,11);frame(11);pixel(r,220,100,(*source)["priorBGRA"],"Source transition begins from the old model surface");frame(11.1);pixel(r,220,100,(*source)["bgra"],"Cover midpoint matches independently measured actual source blend");check(scene.requiresFrames(time),"Only finite source transitions request frames");
    artwork=image({0,255,0,102});in.coverRevision=3;presentation.sync(in,11.1);frame(11.1);pixel(r,220,100,(*source)["interruptedStartBGRA"],"Interrupted source transition starts with prior model rather than partial snapshot");frame(11.2);pixel(r,220,100,(*source)["interruptedHalfBGRA"],"Interrupted two-surface midpoint follows measured original source");frame(11.4);check(!scene.requiresFrames(time),"Paused scene settles with no clock demand");
    // These are owned synthetic decoded pixels, with no file/provider access.
    auto wide=std::make_shared<n::NotesImageFrame>();wide->width=16;wide->height=8;wide->straightRGBA.resize(16*8*4);for(unsigned y=0;y<8;++y)for(unsigned x=0;x<16;++x){const auto at=(y*16+x)*4;wide->straightRGBA[at]=x<4?255:0;wide->straightRGBA[at+1]=x>=12?255:0;wide->straightRGBA[at+2]=x>=4&&x<12?255:0;wide->straightRGBA[at+3]=255;}artwork=wide;in.coverRevision=4;presentation.sync(in,12);frame(12);frame(12.3);pixel(r,100,100,J::Array{255,0,0,255},"Aspect-fill crop uses original square coverage");pixel(r,340,100,J::Array{255,0,0,255},"Aspect-fill crop retains middle image, not letterbox artwork");pixel(r,54,100,J::Array{0,0,0,0},"Provider pixels cannot escape source panel bounds");
    scene.setFeedback(m::NowPlayingAction::playPause,true,12.3);check(!scene.setFeedback(m::NowPlayingAction::playPause,true,12.3),"Equal feedback is a no-op");frame(12.5);const auto rasterBefore=raster.stats();const auto gpuBefore=r.stats();const auto sceneBefore=scene.stats();const std::array<n::PlaneMask,1>mask{{{{},{0,0,440,440}}}};frame(12.6,{},1,mask);
    allocations=0;counting=true;try{for(unsigned k=0;k<120;++k){const double t=12.6+(k+1)/120.;scene.setFeedback(k%2?m::NowPlayingAction::playPause:m::NowPlayingAction::volume,k%3==0,t);frame(t,c::Matrix4::translation(double(k%7)*.01,0),1,mask);}}catch(...){counting=false;throw;}counting=false;
    check(allocations==0,"Warm content checks, feedback, tilt, groups and composition allocate zero C++ objects");check(raster.stats().rasterizations==rasterBefore.rasterizations&&scene.stats().contentEvents==sceneBefore.contentEvents&&r.stats().textureUploads==gpuBefore.textureUploads&&r.stats().meshUploads==gpuBefore.meshUploads&&r.stats().nativeGroupTargetAllocations==gpuBefore.nativeGroupTargetAllocations,"Warm numeric frames repaint no bitmap, text, mesh or target");
    scene.setFeedback({},false,14);frame(14.2);r.draw(false);const auto settled=r.stats();for(unsigned k=0;k<10;++k){frame(14.2);r.draw(false);}check(r.stats().nativeGroupRenders==settled.nativeGroupRenders&&!scene.requiresFrames(time),"Settled content does not repaint local targets or request frames");
    in.track->isPlaying=true;in.track->sampledAt=15;presentation.sync(in,15);presentation.tick(15);frame(15);const auto progressRaster=raster.stats().rasterizations;const auto progressGPU=r.stats();for(unsigned k=1;k<=30;++k)frame(15+k/30.);check(raster.stats().rasterizations==progressRaster&&r.stats().textureUploads==progressGPU.textureUploads,"Subsecond progress remains a numeric unit quad");presentation.tick(16);frame(16);check(raster.stats().rasterizations==progressRaster+1,"Whole-second event rerasterizes only the elapsed caption");
    presentation.perform(m::NowPlayingAction::volume,16);frame(16.08);check(!presentation.sliders(time)[1].enabled&&presentation.volumeText()=="—","Unsupported provider volume preserves exact unavailable source submenu");frame(16.2);pixel(r,400,270,J::Array{20,20,20,251},"Source volume face is retained once with its authored encoded color");frame(16.2,{},.5f);pixel(r,400,270,opacity_source::volume(opacityReference,1),"Settled volume inherits source wrapper alpha per overlapping leaf");presentation.dismissVolume(16.2);frame(16.28,{},.5f);pixel(r,400,270,opacity_source::volume(opacityReference,.5),"Own volume fade isolates the menu before inherited wrapper alpha");frame(16.4);
    in.lyrics=std::make_shared<m::NowPlayingLyrics>(*m::NowPlayingLyrics::parse("[00:00]First\n[00:20]Second\n[00:50]Third"));presentation.sync(in,16.4);frame(16.7);const auto layoutBefore=raster.stats().textLayoutsCreated;in.track->position=33;in.track->sampledAt=17;presentation.sync(in,17);frame(17);const auto lyricsRaster=raster.stats().rasterizations;for(unsigned k=1;k<=12;++k)frame(17+k/60.);check(raster.stats().rasterizations==lyricsRaster&&raster.stats().textLayoutsCreated>=layoutBefore,"Lyric cue movement/fade uses retained text and viewport clipping");
    const auto fontBefore=raster.stats();const auto coverBefore=scene.stats().coverUploads;raster.setDefaultFontLanguage(n::LayerFontLanguage::korean);frame(17.3);check(raster.stats().textLayoutsCreated>fontBefore.textLayoutsCreated&&scene.stats().coverUploads==coverBefore,"Shared SC/KR font event refreshes text without artwork upload");
    auto appearance=presentation.appearance();appearance.reducedMotion=true;presentation.setAppearance(appearance,18);scene.setFeedback(m::NowPlayingAction::volume,true,18);frame(18);check(!scene.requiresFrames(time),"Reduced motion settles all local finite animations");presentation.setActive(false,18);frame(18);check(!scene.requiresFrames(time)&&!presentation.nextDisplayDeadline(time),"Hide removes frame/deadline demand while retaining actual outgoing content");
    const auto saved=r.stats();rejects([&]{scene.releaseResources(r);},"Attached scene retirement fails before any resource mutation");check(r.stats().resourceBytes==saved.resourceBytes&&r.stats().nativeGroups==saved.nativeGroups,"Rejected release preserves published target and inputs");
    const auto borrowed=scene.entry().after[0];composition.detach(r);r.setDrawList(std::span(&borrowed,1));check(!scene.releaseResources(r)&&r.stats().resourceBytes==saved.resourceBytes,"Borrowed output prevents retirement of its whole retained dependency chain");r.clearDrawList();check(scene.releaseResources(r)&&r.stats().textures==0&&r.stats().meshes==0&&r.stats().nativeGroups==0,"Detached scene releases only its owned resources");frame(18);r.draw(false);check(r.stats().nativeGroups==6,"Unchanged model reuploads after complete release");
    frame(18,{},0);const auto hidden=r.stats().nativeGroupRenders;r.draw(false);check(r.stats().nativeGroupRenders==hidden,"Hidden output suppresses pending local group rendering");composition.detach(r);check(scene.releaseResources(r)&&r.stats().resourceBytes==0,"Reused scene has no resident retirement debt");released=true;
}
}
int wmain(int argc,wchar_t**argv){Apartment apartment;try{check(SUCCEEDED(apartment.hr)&&argc==4,"Pass shader and immutable transition/opacity source fixtures");std::ifstream input(std::filesystem::path(argv[2]),std::ios::binary);check(bool(input),"Read owned source fixture");const auto source=J::parse(std::string((std::istreambuf_iterator<char>(input)),{}),128*1024);check(source["sourceCommit"]==J("ca04f142185c7de40acd8523bdb563195d90a1d1"),"Original source fixture is pinned");const auto opacityFixture=opacity_source::load(std::filesystem::path(argv[3]));opacity_source::run(opacityFixture);Window window;n::Renderer renderer;renderer.initialize(window.hwnd,440,440,{n::Driver::warpForTests,argv[1],n::RenderTarget::offscreenForTests});renderer.setCamera(n::layerViewportProjection(440,440));n::LayerRasterizer raster;native(renderer,raster,source,opacityFixture);renderer.reset();check(!IsWindowVisible(window.hwnd),"Fixture never showed a window or invoked real media");std::cout<<"Now Playing native scene: "<<checks<<" checks passed\n";return 0;}catch(const std::exception&e){counting=false;std::cerr<<"Now Playing native scene failed after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(int argc,char**argv){try{opacity_source::check(argc==2,"Pass immutable source opacity fixture");opacity_source::run(opacity_source::load(std::filesystem::path(argv[1])));std::cout<<"Now Playing source opacity: "<<opacity_source::checks<<" checks passed; native scene pending Windows gate\n";return 0;}catch(const std::exception&e){std::cerr<<"Now Playing opacity failed: "<<e.what()<<'\n';return 1;}}
#endif
