#ifdef _WIN32
#include "tools/orbipom_preview.hpp"
#include "native/module_scene.hpp"
#include <windows.h>
#include <objbase.h>
#include <iostream>
#include <cstdio>
#include <cwchar>
#include <cmath>
namespace {
namespace c=endfield::core;namespace m=endfield::modules;namespace n=endfield::native;namespace a=endfield::app;namespace t=endfield::tools;using J=ehud::data::Json;unsigned checks{};bool diagnostic{};
LONG WINAPI fault(EXCEPTION_POINTERS*p){std::fprintf(stderr,"OrbiPom exception code=%08lx at=%p module=%p after=%u\n",static_cast<unsigned long>(p->ExceptionRecord->ExceptionCode),p->ExceptionRecord->ExceptionAddress,GetModuleHandleW(nullptr),checks);void*frames[24]{};const auto count=CaptureStackBackTrace(0,24,frames,nullptr);for(unsigned n=0;n<count;++n)std::fprintf(stderr," frame %u %p\n",n,frames[n]);std::fflush(stderr);return EXCEPTION_CONTINUE_SEARCH;}
void check(bool b,const char*s){++checks;if(diagnostic&&checks<=50){std::fprintf(stderr,"OrbiPom checkpoint %u %s\n",checks,s);std::fflush(stderr);}if(!b)throw std::runtime_error(s);}
struct Window{HWND hwnd{};Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"OwnedOrbiPomOwnerFixture";check(RegisterClassW(&c),"Register own hidden owner fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,c.lpszClassName,L"Synthetic",WS_POPUP,0,0,1280,800,nullptr,nullptr,c.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"No real app/game window");}~Window(){DestroyWindow(hwnd);UnregisterClassW(L"OwnedOrbiPomOwnerFixture",GetModuleHandleW(nullptr));}};
struct Fake:m::OrbiPomRuntimePort {m::OrbiPomSnapshot value;std::optional<std::string>failure;unsigned frames{},moves{},drops{},pauses{};double elapsed{};const m::OrbiPomSnapshot&snapshot()const noexcept override{return value;}const std::optional<std::string>&error()const noexcept override{return failure;}void start(std::optional<std::uint32_t>)override{value={};value.state="playing";value.bodies={{1,1,60,120,0,19.2,1,1}};}void advance(double t)override{++frames;elapsed+=t;}void move(c::Point p)override{++moves;value.previewX=p.x;}void pointerUp(c::Point)override{++drops;}bool drop()override{++drops;return true;}bool activate(m::OrbiPomSkill s)override{value.skill=s;if(s==m::OrbiPomSkill::swap){value.currentLevel=value.currentLevel%11+1;value.nextLevel=value.nextLevel%11+1;}return true;}void cancelSkill()override{value.skill.reset();}void pause(bool p)override{value.paused=p;++pauses;}void highScore(std::int64_t)override{}};
void run(n::Renderer&r,n::LayerRasterizer&raster,const std::filesystem::path&resources){Fake*fake{};unsigned saves{},creations{};std::function<void()>onSave;m::OrbiPomSession session(0,{[&]{++creations;auto p=std::make_unique<Fake>();fake=p.get();return p;},[&](auto){++saves;if(onSave){auto callback=onSave;callback();}},{}});t::OrbiPomPreviewOptions options;options.raster.assetRoot=resources;options.raster.pixelsPerPoint=1;t::OrbiPomPreview owner(session,raster,options);owner.resize({1280,800,96,1,1280,800});n::LayerComposition composition;bool released{};struct Guard{n::Renderer&r;n::LayerComposition&c;t::OrbiPomPreview&o;bool&done;~Guard(){if(!done)try{c.detach(r);o.release(r);}catch(...){r.reset();}}}guard{r,composition,owner,released};c::ModulePresentation modules(c::Module::power);c::source::DesktopChromeSettings settings{{0,0,1280,800},1,{},c::Module::power,true};auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;double time{};n::LayerScene geometry(raster);geometry.load(J::Object{{"bounds",J::Array{0,0,440,440}},{"position",J::Array{0,0}},{"anchorPoint",J::Array{0,0}},{"children",J::Array{}}},options.raster);n::NativeModuleSurface plane(geometry,c::Module::minigame);
struct Published{n::LayerScene*scene{};std::uint64_t content{},resources{};const n::DrawObject*after{};std::size_t count{};};std::array<Published,5>published{};std::size_t publishedCount{};unsigned bindingChanges{};
const auto publish=[&]{const auto entries=owner.entries();bool changed=entries.size()!=publishedCount;if(!changed)for(std::size_t k=0;k<entries.size();++k){const auto&e=entries[k];const auto&p=published[k];if(e.scene!=p.scene||e.scene->contentRevision()!=p.content||e.scene->resourceRevision()!=p.resources||e.after.data()!=p.after||e.after.size()!=p.count){changed=true;break;}}const bool bindings=composition.supplementalBindingsMatch(entries);if(!changed&&!bindings)++bindingChanges;if(changed||!bindings){composition.setEntries(r,entries);publishedCount=entries.size();for(std::size_t k=0;k<entries.size();++k){const auto&e=entries[k];published[k]={e.scene,e.scene->contentRevision(),e.scene->resourceRevision(),e.after.data(),e.after.size()};}}};
const auto frame=[&](double dt=1./60){time+=dt;settings.module=modules.requested();const auto sample=modules.sample(time).presentation;owner.update(center,settings,sample,1,time);owner.upload(r);publish();composition.present(r);owner.collected(r);};const auto point=[&](c::Point p){const auto sample=modules.sample(time).presentation;const auto*surface=sample.current.module==c::Module::minigame?&sample.current:&*sample.incoming;plane.update(center,settings,*surface);const auto camera=n::layerViewportProjection(1280,800);return *c::Projection::viewport(camera*plane.pose().contentWorld,1280,800).project(p);};
frame();check(owner.entries().empty()&&!session.hasRuntime()&&!owner.requiresFrames(time),"Initial hidden game has no VM/frame/artwork publication");modules.select(c::Module::minigame,time);frame(.03);check(!owner.state().active()&&!session.hasRuntime(),"Incoming game prepares source artwork while rejecting input");frame(.4);check(owner.state().active()&&owner.covers(point({10,420})),"Stable440-point game accepts current projected hits");check(owner.perform(m::OrbiPomAction::start,time)&&creations==1&&owner.requiresFrames(time),"Source Start creates one app-owned VM and frame demand");frame(.025);check(fake->frames==1&&std::abs(fake->elapsed-.025)<1e-10,"Shared clock advances exact new elapsed time after Start");
const auto q=point({200,200});owner.pointer({a::PointerKind::down,a::PointerButton::left,q.x,q.y},time);check(!owner.pointerLocked()&&fake->moves==1,"Aiming does not freeze gyro or drop on down");owner.pointer({a::PointerKind::up,a::PointerButton::left,q.x,q.y},time);check(fake->drops==1,"Projected release reaches original board once");center=center*c::Matrix4::rotation(.03,-.06,0);frame();check(owner.covers(point({200,200})),"Moving source plane is shared by glyphs and input");fake->value.energy=3;fake->value.swapCharge=6;frame();check(owner.perform(m::OrbiPomAction::clear,time),"Owner accepts the original clear skill with available energy");frame();const auto beforeSkill=bindingChanges;fake->value.hoverBodyID=1;frame();check(bindingChanges==beforeSkill+1&&owner.stats().ringRasters==1,"Skill target hover republishes its new ring binding through the retained host gate");check(owner.perform(m::OrbiPomAction::swap,time),"Owner accepts original swap action");frame();const auto beforeNext=bindingChanges;fake->value.currentLevel=3;fake->value.nextLevel=4;frame();check(bindingChanges==beforeNext+1,"Following swap preview/next texture update republishes unchanged-count owner entries");r.draw(false);check(!r.readback().pixels.empty(),"Skill target and swapped sprites render without host identity failure");check(owner.perform(m::OrbiPomAction::rules,time)&&!owner.state().requiresFrames(),"Rules modal pauses gameplay");frame(.2);const auto paused=fake->frames;for(unsigned n=0;n<10;++n)frame();check(fake->frames==paused&&owner.covers({-10,-10}),"Rules owns outside clicks and advances zero physics");check(owner.wheel({0,0,-.25,false,0,3},time),"Fractional rules wheel consumed without game input");check(owner.key({a::KeyKind::down,VK_ESCAPE},time),"Escape closes rules first");frame(.025);check(fake->frames==paused+1,"Closing rules starts a fresh elapsed baseline");
// Source pause commits the score produced by the last running step. A fake
// score mutation after pause would be impossible with the stopped engine.
fake->value.score=99;check(owner.perform(m::OrbiPomAction::pause,time),"Manual pause action");check(saves==1&&session.bestScore()==99,"Source manual pause saves the improved running score once");frame(.2);const auto before=fake->frames;owner.setOverlayVisible(false,time);frame(10);check(fake->frames==before&&!owner.requiresFrames(time)&&saves==1,"HUD hide retains the single paused best-score save and advances no catch-up");owner.setOverlayVisible(true,time);frame(.02);check(session.manuallyPaused()&&fake->frames==before,"Reopen preserves user pause");owner.perform(m::OrbiPomAction::pause,time);frame(.01);const auto active=fake->frames;owner.setForeground(false,time);frame(40);check(fake->frames==active,"Foreground loss never advances original game");owner.setForeground(true,time);frame(.012);check(fake->frames==active+1&&creations==1,"Focus resume uses only new interval and same VM");owner.setLanguage(c::Language::korean,time);frame();check(creations==1&&session.bestScore()==99,"Language replacement retains game and best score");
// Mac willSleep/didWake: an hour asleep never reaches virtual timers. Activation
// changes while asleep are tracked but cannot restart the clock.
{const auto before=fake->frames;const auto elapsed=fake->elapsed;owner.setSystemSuspended(true,time);check(!owner.state().requiresFrames()&&!owner.requiresFrames(time)&&fake->value.paused,"System suspend pauses the original VM and drops frame demand");frame(3600);check(fake->frames==before,"No simulation step while the system sleeps");owner.setForeground(false,time);owner.setForeground(true,time);check(!owner.state().requiresFrames()&&fake->value.paused,"Activation while suspended keeps the game asleep");frame(1./60);owner.setSystemSuspended(false,time);check(owner.requiresFrames(time)&&!fake->value.paused,"Wake restores the current activation and frame demand");frame(1./60);check(fake->frames==before+1&&std::abs(fake->elapsed-elapsed-1./60)<1e-9,"Resume after an hour asleep advances only one new frame interval");}
// Low-power visual mode: the source 1/30 s timer is the only simulation tick.
{owner.setLowPowerVisualMode(true,time);frame(1./60);const auto before=fake->frames;const auto elapsed=fake->elapsed;for(unsigned n=0;n<12;++n)frame(1./60);check(fake->frames==before+6&&std::abs(fake->elapsed-elapsed-12./60)<1e-9,"Low power advances on 1/30 s ticks only, carrying the full elapsed time");const auto paced=fake->frames;for(unsigned n=0;n<6;++n)frame(1./30-.004);check(fake->frames==paced+6,"A slightly early 30 Hz shared-clock frame still counts as its tick");owner.setLowPowerVisualMode(false,time);frame(1./60);const auto normal=fake->frames;frame(1./60);check(fake->frames==normal+1,"Normal visual mode advances on every shared frame again");}// Persistence can synchronously deliver a newer owner lifecycle event. The
// older departure must not overwrite its active/input/elapsed baseline.
const auto currentSample=modules.sample(time).presentation;c::ModulePresentation departing(c::Module::minigame);departing.select(c::Module::power,time);fake->value.score=100;const auto beforeReentry=fake->frames;
onSave=[&]{if(diagnostic)std::fputs("reentry save begin\n",stderr);onSave={};owner.setOverlayVisible(false,time+.002);if(diagnostic)std::fputs("reentry concealed\n",stderr);owner.setOverlayVisible(true,time+.003);if(diagnostic)std::fputs("reentry shown\n",stderr);owner.update(center,settings,currentSample,1,time+.004);if(diagnostic)std::fputs("reentry updated\n",stderr);time+=.004;};
owner.update(center,settings,departing.sample(time+.001).presentation,1,time+.001);
check(owner.state().active()&&owner.covers(point({200,200}))&&saves==2,"A newer reentrant visibility/update event wins over stale departure");frame(.01);
check(fake->frames==beforeReentry+1,"Reentrant resume keeps the newer elapsed baseline");
modules.select(c::Module::power,time);frame(.03);check(!owner.state().active()&&!owner.entries().empty(),"Outgoing artwork retained while simulation pauses");const auto leaving=fake->frames;frame(.4);check(owner.entries().empty()&&!owner.requiresFrames(time)&&fake->frames==leaving,"Departed Minigame has no shared frame demand");composition.detach(r);owner.release(r);released=true;check(r.stats().textures==0&&r.stats().meshes==0,"All game-owned resources detach without sibling mutation");}
}
int wmain(int argc,wchar_t**argv){
// The apartment outlives every DWrite/WIC/D3D fixture owner on success AND
// exception paths. Uninitializing inside try leaves raster COM owners alive.
struct Apartment{HRESULT result{CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED)};~Apartment(){if(SUCCEEDED(result))CoUninitialize();}} apartment;const auto hr=apartment.result;try{diagnostic=argc==4&&std::wcscmp(argv[3],L"--diagnostic")==0;if(diagnostic)SetUnhandledExceptionFilter(fault);check(SUCCEEDED(hr)&&(argc==3||diagnostic),"Pass HLSL and original Resources root");Window window;n::Renderer renderer;renderer.initialize(window.hwnd,1280,800,{n::Driver::warpForTests,argv[1],n::RenderTarget::offscreenForTests});renderer.setCamera(n::layerViewportProjection(1280,800));n::LayerRasterizer raster;run(renderer,raster,std::filesystem::absolute(argv[2]));renderer.reset();std::cout<<"PASS "<<checks<<" OrbiPom owner checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
