#ifdef _WIN32
#include "native/orbipom_scene.hpp"
#include "modules/orbipom_runtime.hpp"
#include <windows.h>
#include <objbase.h>
#include <atomic>
#include <cstdlib>
#include <new>
#include <iostream>
#include <cstdio>
#include <cwchar>
#include <chrono>
namespace{std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {
namespace m=endfield::modules;namespace n=endfield::native;namespace c=endfield::core;unsigned checks{};bool diagnostic{};
LONG WINAPI fault(EXCEPTION_POINTERS*p){std::fprintf(stderr,"OrbiPom exception code=%08lx at=%p module=%p after=%u\n",static_cast<unsigned long>(p->ExceptionRecord->ExceptionCode),p->ExceptionRecord->ExceptionAddress,GetModuleHandleW(nullptr),checks);void*frames[24]{};const auto count=CaptureStackBackTrace(0,24,frames,nullptr);for(unsigned n=0;n<count;++n)std::fprintf(stderr," frame %u %p\n",n,frames[n]);std::fflush(stderr);return EXCEPTION_CONTINUE_SEARCH;}
void check(bool b,const char*s){++checks;if(diagnostic&&checks<=50){std::fprintf(stderr,"OrbiPom checkpoint %u %s\n",checks,s);std::fflush(stderr);}if(!b)throw std::runtime_error(s);}
struct Window{HWND hwnd{};Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"OwnedOrbiPomSceneFixture";check(RegisterClassW(&c),"Register isolated Minigame fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,c.lpszClassName,L"Synthetic",WS_POPUP,0,0,440,440,nullptr,nullptr,c.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"No game window shown or activated");}~Window(){DestroyWindow(hwnd);UnregisterClassW(L"OwnedOrbiPomSceneFixture",GetModuleHandleW(nullptr));}};
struct Fake:m::OrbiPomRuntimePort{m::OrbiPomSnapshot value;std::optional<std::string>error_;const m::OrbiPomSnapshot&snapshot()const noexcept override{return value;}const std::optional<std::string>&error()const noexcept override{return error_;}void start(std::optional<std::uint32_t>)override{value.state="playing";value.bodies={{1,1,60,120,0,19.2,1,1},{2,11,120,220,.2,96,1,1}};}void advance(double)override{}void move(c::Point)override{}void pointerUp(c::Point)override{}bool drop()override{return true;}bool activate(m::OrbiPomSkill)override{return true;}void cancelSkill()override{}void pause(bool b)override{value.paused=b;}void highScore(std::int64_t)override{}};
void synthetic(n::Renderer&r,n::LayerRasterizer&raster,const std::filesystem::path&resources){Fake*f{};m::OrbiPomSession session(0,{[&]{auto p=std::make_unique<Fake>();f=p.get();return p;},{},{}});m::OrbiPomState state(session);state.setActive(true);n::LayerRasterOptions o;o.assetRoot=resources;o.pixelsPerPoint=1;n::NativeOrbiPomScene scene(session,state,raster,o);n::LayerComposition composition;bool released{};struct Guard{n::Renderer&r;n::LayerComposition&c;n::NativeOrbiPomScene&s;bool&done;~Guard(){if(!done)try{c.detach(r);s.releaseResources(r);}catch(...){r.reset();}}}guard{r,composition,scene,released};double time{};struct Published{n::LayerScene*scene{};std::uint64_t content{},resources{};const n::DrawObject*after{};std::size_t count{};};std::array<Published,4>published{};std::size_t publishedCount{};unsigned bindingChanges{};
const auto legacyMatches=[&](std::span<const n::LayerCompositionEntry>entries){if(entries.size()!=publishedCount)return false;for(std::size_t k=0;k<entries.size();++k){const auto&e=entries[k];const auto&p=published[k];if(e.scene!=p.scene||e.scene->contentRevision()!=p.content||e.scene->resourceRevision()!=p.resources||e.after.data()!=p.after||e.after.size()!=p.count)return false;}return true;};
const auto publish=[&]{const auto entries=scene.entries();const bool legacy=legacyMatches(entries),bindings=composition.supplementalBindingsMatch(entries);if(legacy&&!bindings)++bindingChanges;if(!legacy||!bindings){composition.setEntries(r,entries);publishedCount=entries.size();for(std::size_t k=0;k<entries.size();++k){const auto&e=entries[k];published[k]={e.scene,e.scene->contentRevision(),e.scene->resourceRevision(),e.after.data(),e.after.size()};}}};
std::array<std::size_t,6>stageAllocations{};const auto frame=[&](double dt=1./60){time+=dt;const auto stage=[&](std::size_t index,auto&&call){const auto before=allocations.load();call();if(counting)stageAllocations[index]+=allocations.load()-before;};stage(0,[&]{scene.syncContent(time);});stage(1,[&]{scene.updatePose({c::Matrix4::rotation(.01,.02,0),1,time,{},{}});});stage(2,[&]{scene.uploadResources(r);});stage(3,[&]{publish();});stage(4,[&]{composition.present(r);});stage(5,[&]{scene.collectRetired(r);});};
frame();check(!session.hasRuntime(),"Idle original art does not start a VM");r.draw(false);check(!r.readback().pixels.empty(),"Original detached canvas renders");state.perform(m::OrbiPomAction::start);frame();check(scene.stats().bodies==2&&scene.stats().spriteUploads==11,"Two bodies share exactly eleven retained source level textures");// Reproduce the live host's old pointer/count-only publication gate. The
// existing body acquires a ring texture while every cached legacy key stays equal.
f->value.hoverBodyID=1;scene.syncContent(time);scene.updatePose({c::Matrix4::rotation(.01,.02,0),1,time,{},{}});scene.uploadResources(r);
check(legacyMatches(scene.entries()),"Skill hover changes a binding inside the same supplemental buffer/count and scene revisions");check(!composition.supplementalBindingsMatch(scene.entries()),"Exact binding query detects the first selected-ring texture");bool staleRejected{};try{composition.present(r);}catch(const std::exception&e){staleRejected=std::string_view(e.what()).find("Supplemental draw identity changed")!=std::string_view::npos;}check(staleRejected,"Legacy host gate reproduces the live skill failure without weakening present validation");
frame();check(bindingChanges==1&&scene.stats().ringRasters==1,"Binding-aware host republishes the selected source circle once");scene.setFeedback(c::Point{365,115},true,time);frame(.2);const auto a=raster.stats();const auto gpu=r.stats();allocations=0;counting=true;try{for(unsigned k=0;k<120;++k){f->value.bodies[0].x=60+k*.05;f->value.bodies[1].angle=.2+k*.002;frame();}}catch(...){counting=false;throw;}counting=false;if(allocations!=0)std::cerr<<"OrbiPom warm allocations total="<<allocations.load()<<" sync="<<stageAllocations[0]<<" pose="<<stageAllocations[1]<<" upload="<<stageAllocations[2]<<" entries="<<stageAllocations[3]<<" present="<<stageAllocations[4]<<" retire="<<stageAllocations[5]<<'\n';check(allocations==0,"Warm moving bodies, selected border and tilt allocate nothing");check(raster.stats().rasterizations==a.rasterizations&&r.stats().textureUploads==gpu.textureUploads&&r.stats().meshUploads==gpu.meshUploads,"Body motion never rebuilds captions, artwork or image resources");
const auto beforeSwap=bindingChanges;std::swap(f->value.currentLevel,f->value.nextLevel);if(f->value.currentLevel==f->value.nextLevel)f->value.currentLevel=f->value.currentLevel%11+1;frame();check(bindingChanges==beforeSwap+1,"Current/next sprite texture changes republish with stable source IDs and counts");const auto beforeReplace=bindingChanges;f->value.bodies[0].id=777;f->value.hoverBodyID=777;frame();check(bindingChanges==beforeReplace+1&&scene.stats().bodies==2,"Same-count body replacement detects new supplemental source identities");r.draw(false);check(!r.readback().pixels.empty(),"Skill binding replacements render after exact republication");
f->value.score=234;frame();check(scene.stats().localUpdates>0&&scene.stats().spriteUploads==11,"Score event updates retained text without sprite uploads");state.perform(m::OrbiPomAction::rules);frame();check(!state.requiresFrames()&&scene.rulesBounds().width==322&&scene.entries().size()==4,"Rules use one source retained group and pause the original simulation");frame(.2);const auto menuRaster=raster.stats();check(scene.scrollRules(24,time),"Original rules paragraph scroll is available");for(unsigned n=0;n<10;++n)frame();check(raster.stats().rasterizations==menuRaster.rasterizations,"Rules scroll uses only local numeric placement and retained group redraw");state.setRulesPresented(false);frame();check(scene.entries().size()==4,"Closing rules retains the outgoing face");frame(.19);check(scene.entries().size()==3&&!scene.requiresFrames(time),"Source .18s retirement detaches the finite menu output");
f->value.bodies.erase(f->value.bodies.begin());frame();check(scene.stats().bodies==1,"Removed original body and selected border retire after publication");// A pointer callback can create a selection ring and remove its body before
// the next host upload. Missing GPU resources must never become retired debt.
f->value.bodies.push_back({3,1,100,140,0,19.2,1,1});f->value.hoverBodyID=3;scene.syncContent(time);f->value.bodies.pop_back();f->value.hoverBodyID.reset();scene.syncContent(time);frame();check(scene.collectRetired(r)&&scene.stats().bodies==1,"Unpublished selected-body removal has no phantom GPU retirement");state.perform(m::OrbiPomAction::pause);frame();frame(.2);check(!state.requiresFrames()&&!scene.requiresFrames(time),"User pause settles without frame demand");m::OrbiPomAppearance appearance;appearance.dark=false;appearance.language=c::Language::korean;scene.setAppearance(appearance);frame();check(session.manuallyPaused()&&scene.stats().bodies==1,"Locale/theme changes preserve paused game and original bodies");// Hold exactly one source body through a different explicit publication.
// A failed partial retirement must leave a reusable retained scene, not an
// uploaded-revision token that skips resources already successfully removed.
const auto borrowed=scene.entries()[1].after[8];composition.detach(r);r.setDrawList(std::span(&borrowed,1));check(!scene.releaseResources(r),"Borrowed body prevents only its own partial resource retirement");r.clearDrawList();publishedCount=0;frame();r.draw(false);check(!r.readback().pixels.empty()&&scene.stats().bodies==1,"Reuse after partial release restores every removed scene resource");composition.detach(r);check(scene.releaseResources(r),"Owner releases only its detached resources");check(r.stats().textures==0&&r.stats().meshes==0&&r.stats().nativeGroups==0,"Body textures, menu group and retired border all released");publishedCount=0;frame();r.draw(false);check(!r.readback().pixels.empty(),"Unchanged source artwork uploads again after complete release");composition.detach(r);check(scene.releaseResources(r)&&r.stats().textures==0&&r.stats().meshes==0,"Reuploaded scene releases completely again");released=true;}
void actual(n::Renderer&r,n::LayerRasterizer&raster,const std::filesystem::path&resources){m::OrbiPomRuntime*runtime{};m::OrbiPomSession session(0,{[&]{auto p=std::make_unique<m::OrbiPomRuntime>(m::OrbiPomRuntimeOptions{resources});runtime=p.get();return p;},{},{}});m::OrbiPomState state(session);state.setActive(true);check(session.start(12345),"Actual unchanged Matter and OrbiPom start through one QuickJS VM");n::LayerRasterOptions o;o.assetRoot=resources;o.pixelsPerPoint=1;n::NativeOrbiPomScene scene(session,state,raster,o);n::LayerComposition composition;bool released{};struct Guard{n::Renderer&r;n::LayerComposition&c;n::NativeOrbiPomScene&s;bool&done;~Guard(){if(!done)try{c.detach(r);s.releaseResources(r);}catch(...){r.reset();}}}guard{r,composition,scene,released};double total{},maximum{};std::size_t peak{};const auto start=std::chrono::steady_clock::now();
for(unsigned frame=0;frame<600;++frame){if(frame%60==0){state.move({120+double(frame%160),140});session.drop();}const auto a=std::chrono::steady_clock::now();state.advance(1./60);const auto b=std::chrono::steady_clock::now();total+=std::chrono::duration<double>(b-a).count();maximum=std::max(maximum,std::chrono::duration<double>(b-a).count());peak=std::max(peak,session.snapshot().bodies.size());const double t=frame/60.;scene.syncContent(t);scene.updatePose({{},1,t,{},{}});scene.uploadResources(r);composition.setEntries(r,scene.entries());composition.present(r);scene.collectRetired(r);if(frame%60==0)r.draw(false);check(!session.error(),"Populated original runtime remains healthy");}
check(peak>=4&&runtime->stats().boots==1&&runtime->stats().advances==600,"Representative ten-second seeded game uses one VM and all600 source fixed-step calls");const auto before=runtime->stats().advances;state.setForeground(false);for(unsigned n=0;n<100;++n)state.advance(1);state.setForeground(true);state.setPresented(false);for(unsigned n=0;n<100;++n)state.advance(1);check(runtime->stats().advances==before,"Foreground loss and hidden game advance zero simulation steps");const auto wall=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();std::cout<<"OrbiPom observational WARP+QuickJS: frames=600 peak_bodies="<<peak<<" advance_total_ms="<<total*1000<<" advance_max_ms="<<maximum*1000<<" preparation_and_periodic_render_ms="<<wall*1000<<" heap_bytes="<<runtime->stats().heapBytes<<" texture_uploads="<<r.stats().textureUploads<<'\n';composition.detach(r);check(scene.releaseResources(r),"Actual game retires all scene resources");released=true;}
}
int wmain(int argc,wchar_t**argv){
// The apartment outlives every DWrite/WIC/D3D fixture owner on success AND
// exception paths. Uninitializing inside try leaves raster COM owners alive.
struct Apartment{HRESULT result{CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED)};~Apartment(){if(SUCCEEDED(result))CoUninitialize();}} apartment;const auto hr=apartment.result;try{diagnostic=argc==4&&std::wcscmp(argv[3],L"--diagnostic")==0;if(diagnostic)SetUnhandledExceptionFilter(fault);check(SUCCEEDED(hr)&&(argc==3||diagnostic),"Pass HLSL and original Resources root");Window window;n::Renderer renderer;renderer.initialize(window.hwnd,440,440,{n::Driver::warpForTests,argv[1],n::RenderTarget::offscreenForTests});renderer.setCamera(n::layerViewportProjection(440,440));n::LayerRasterizer raster;synthetic(renderer,raster,std::filesystem::absolute(argv[2]));actual(renderer,raster,std::filesystem::absolute(argv[2]));renderer.reset();std::cout<<"PASS "<<checks<<" OrbiPom native scene checks\n";return 0;}catch(const std::exception&e){counting=false;std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
