#include "modules/orbipom_presentation.hpp"
#include "native/orbipom_assets.hpp"
#include <fstream>
#include <iostream>
#include <cmath>
#include <set>
namespace {namespace m=endfield::modules;using J=ehud::data::Json;unsigned checks{};void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(s);}struct Runtime:m::OrbiPomRuntimePort {m::OrbiPomSnapshot value;std::optional<std::string>failure;const m::OrbiPomSnapshot&snapshot()const noexcept override{return value;}const std::optional<std::string>&error()const noexcept override{return failure;}void start(std::optional<std::uint32_t>)override{value.state="playing";}void advance(double)override{}void move(endfield::core::Point)override{}void pointerUp(endfield::core::Point)override{}bool drop()override{return true;}bool activate(m::OrbiPomSkill)override{return true;}void cancelSkill()override{}void pause(bool b)override{value.paused=b;}void highScore(std::int64_t v)override{value.highScore=v;}};
const m::OrbiPomSurface&part(const std::vector<m::OrbiPomSurface>&p,std::string_view id){for(const auto&s:p)if(s.id==id)return s;throw std::runtime_error("Missing OrbiPom source surface");}
void compareText(const J&source,const m::OrbiPomSurface&target){check(source["text"]==target.content["text"]["string"],"Source caption text");check(source["fontSize"]==target.content["text"]["fontSize"],"Source caption size");const auto&b=source["frame"].array();check(target.local.values[12]==b[0].number()&&target.local.values[13]==b[1].number()&&target.content["bounds"].array()[2]==b[2]&&target.content["bounds"].array()[3]==b[3],"Source text geometry");for(unsigned k=0;k<4;++k)check(std::abs(source["ink"].array()[k].number()-target.content["text"]["foregroundColor"]["sRGB"].array()[k].number())<1e-6,"Original sRGB caption palette");}
void run(const char*fixture,const char*assets){std::ifstream file(fixture);const std::string bytes(std::istreambuf_iterator<char>(file),{});const auto source=J::parse(bytes,512*1024);endfield::native::validateOrbiPomAssets(std::filesystem::absolute(assets));
for(const auto&row:source["opacityTiming"]["rows"].array())for(unsigned k=0;k<3;++k)check(std::abs(row["bgra"].array()[k].number()-row["phase"].number()*255)<=.500001,"Actual detached CA nil-timing opacity is linear, not default easing");
for(bool dark:{true,false}){Runtime*runtime{};m::OrbiPomSession session(0,{[&]{auto p=std::make_unique<Runtime>();runtime=p.get();return p;},{},{}});m::OrbiPomState state(session);state.setActive(true);m::OrbiPomAppearance a;a.dark=dark;
for(unsigned phase=0;phase<4;++phase){if(phase==1)state.perform(m::OrbiPomAction::start);if(phase==2)state.perform(m::OrbiPomAction::pause);if(phase==3)state.perform(m::OrbiPomAction::restart);const auto art=m::prepareOrbiPomArtwork(session,state,a);const auto&original=source["cases"].array()[(dark?0:4)+phase];check(!original["timer"].boolean(),"Original fixture created no frame timer");const auto&face=original["layer"]["children"].array()[0]["children"].array();const std::array<std::pair<unsigned,const char*>,8>text{{{0,"orbipom.heading"},{3,"orbipom.score-label"},{4,"orbipom.best-label"},{5,"orbipom.score"},{6,"orbipom.best"},{7,"orbipom.next-label"},{8,"orbipom.energy"},{9,"orbipom.sp"}}};for(auto [index,id]:text)compareText(face[index],part(art.face,id));const auto&children=original["layer"]["children"].array();compareText(children[children.size()-3],part(art.overlay,"orbipom.status"));compareText(children[children.size()-2],part(art.overlay,"orbipom.danger"));const auto actions=state.actions();check(actions.count==original["actions"].array().size(),"Source action count");for(std::size_t k=0;k<actions.count;++k){const auto&v=actions.items[k];const auto&o=original["actions"].array()[k];check(v.enabled==o["enabled"].boolean(),"Source action availability");const auto&b=o["rect"].array();check(v.rect==endfield::core::Rect{b[0].number(),b[1].number(),b[2].number(),b[3].number()},"Source control bounds");const auto&p=part(art.overlay,"orbipom.control."+std::to_string(static_cast<unsigned>(v.action)));check(p.content["children"].array()[0]["children"].array().back()["text"]["string"]==o["title"],"Source control labels/costs");}std::set<std::string>ids;for(const auto*list:{&art.face,&art.overlay})for(const auto&p:*list)check(ids.insert(p.id).second,"Stable unique retained surface identities");}
(void)runtime;}
std::array<double,9>heights{14.1,22.2,45,30,11,56.2,45,30,20};auto rules=m::prepareOrbiPomRules({},heights);check(rules.bounds==endfield::core::Rect{0,0,322,348}&&rules.origin==endfield::core::Point{104,43}&&rules.viewport==endfield::core::Rect{12,40,298,299},"Source rules menu clamp and clipping plane");double sum=72;for(auto h:heights)sum+=std::max(18.,std::ceil(h)+3);check(rules.contentHeight==sum&&rules.maximumScroll==sum-299,"Measured paragraphs preserve source ceil18/+3/9px gap");for(auto language:{endfield::core::Language::english,endfield::core::Language::simplifiedChinese,endfield::core::Language::traditionalChinese,endfield::core::Language::japanese,endfield::core::Language::korean}){const auto strings=m::orbiPomRuleParagraphs(language);for(const auto&s:strings)check(!s.empty()&&J::validUtf8(s),"All source locale paragraphs preserve valid text");}
check(m::orbiPomAssets().size()==15,"Exactly eleven original levels and four skill images");try{heights[0]=NAN;(void)m::prepareOrbiPomRules({},heights);check(false,"Malformed measure rejected");}catch(const std::invalid_argument&){++checks;}
}
}
int main(int argc,char**argv){try{check(argc==3,"Pass source fixture and original Resources root");run(argv[1],argv[2]);std::cout<<"PASS "<<checks<<" OrbiPom original canvas checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
