#include "modules/orbipom_state.hpp"
#include "core/data/json.hpp"
#include <algorithm>
#include <atomic>
#include <cstdlib>
#include <new>
#include <cmath>
#include <fstream>
#include <iostream>
#include <limits>
#include <stdexcept>

namespace {std::atomic<std::uint64_t>allocations{};}
void*operator new(std::size_t n){allocations.fetch_add(1,std::memory_order_relaxed);if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}
void operator delete(void*p)noexcept{std::free(p);}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete[](void*p)noexcept{::operator delete(p);}
#ifdef __cpp_sized_deallocation
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace m=endfield::modules;using P=endfield::core::Point;using J=ehud::data::Json;
namespace {
unsigned checks{};
void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}
bool closeEnough(double a,double b){return std::abs(a-b)<=1e-12*std::max({1.,std::abs(a),std::abs(b)});}
struct Port final:m::OrbiPomRuntimePort {
    m::OrbiPomSnapshot value;std::optional<std::string>failure;unsigned starts{},advances{},moves{},ups{},drops{},activations{},cancels{},pauses{},hydrates{};P last{};bool finish{},failStart{};
    const m::OrbiPomSnapshot&snapshot()const noexcept override{return value;}
    const std::optional<std::string>&error()const noexcept override{return failure;}
    void start(std::optional<std::uint32_t>)override{++starts;const auto high=value.highScore;value={};value.state="playing";value.highScore=high;if(failStart)failure="Synthetic original-runtime error";}
    void advance(double seconds)override{++advances;value.simulationTime+=seconds;if(finish)value.state="over";}
    void move(P p)override{++moves;last=p;value.previewX=p.x;}
    void pointerUp(P p)override{++ups;last=p;}
    bool drop()override{++drops;return value.canAdvance();}
    bool activate(m::OrbiPomSkill s)override{++activations;value.skill=s;value.skillPhase="selecting";return true;}
    void cancelSkill()override{++cancels;value.skill.reset();value.skillPhase.reset();}
    void pause(bool valueIn)override{++pauses;value.paused=valueIn;}
    void highScore(std::int64_t high)override{++hydrates;value.highScore=high;}
};
struct Fixture {
    Port*port{};unsigned creations{};std::vector<std::int64_t>saves;std::vector<m::OrbiPomEvent>events;
    m::OrbiPomSessionCallbacks callbacks(){return {[this]{++creations;auto p=std::make_unique<Port>();port=p.get();return p;},[this](auto score){saves.push_back(score);},[this](auto event){events.push_back(event);}};}
};
void source(const char*path){
    std::ifstream file(path);check(bool(file),"Explicit original-source fixture opens");const std::string bytes(std::istreambuf_iterator<char>(file),{});const auto root=J::parse(bytes,128*1024);
    check(root["originalRuntimeChecks"].integer()==108,"Fixture was generated by all original physics/skill tests");
    constexpr std::array states{"idle","playing","over"};const std::array<std::optional<std::string>,4>phases{std::nullopt,"armed","selecting","casting"};
    for(const auto&row:root["availability"].array()){
        const auto&a=row.array();m::OrbiPomSnapshot s;s.state=states.at(a[0].integer());s.paused=a[1].integer()!=0;s.skillPhase=phases.at(a[2].integer());s.energy=int(a[3].integer());s.swapCharge=int(a[4].integer());int mask{};
        for(int i=0;i<4;++i)if(s.canUse(static_cast<m::OrbiPomSkill>(i)))mask|=1<<i;
        check(mask==a[5].integer(),"Availability exactly matches original Swift snapshot predicate");
    }
    for(const auto&row:root["worlds"].array()){const auto&a=row.array();const auto p=m::orbiPomWorld({a[0].number(),a[1].number()});check(closeEnough(p.x,a[2].number())&&closeEnough(p.y,a[3].number()),"Board conversion matches extracted original Swift expression");}
    std::size_t total{};for(const auto&frame:root["frames"].array())for(const auto&body:frame["snapshot"]["bodies"].array()){
        m::OrbiPomBody b{body["id"].integer(),int(body["level"].integer()),body["x"].number(),body["y"].number(),body["angle"].number(),body["size"].number(),body["opacity"].number(),body["scale"].number()};const auto place=m::orbiPomPlacement(b);const auto world=m::orbiPomWorld(place.center);
        check(closeEnough(world.x,b.x)&&closeEnough(world.y,b.y)&&place.angle==b.angle&&place.opacity==b.opacity,"Actual original-engine bodies retain render offset coordinates, angle and opacity");++total;
    }
    check(root["frames"].array().size()==11&&total>30,"Seeded actual engine transcript includes ten seconds of moving/merged bodies");
}
void session(){
    Fixture f;m::OrbiPomSession session(51,f.callbacks());check(!session.hasRuntime()&&session.snapshot().state=="idle"&&session.bestScore()==51,"Idle state keeps runtime lazy and local score");session.advance(1);session.move({1,2});check(f.creations==0,"Hidden/no-runtime calls do not instantiate engine");
    check(session.start(123)&&f.creations==1&&f.port->hydrates==1&&session.snapshot().highScore==51&&f.events==std::vector{m::OrbiPomEvent::started},"First start hydrates only injected best and emits one event");
    f.port->value.score=73;session.pause(true);check(session.bestScore()==73&&f.saves==std::vector<std::int64_t>{73},"Pause commits improved local best once");session.pause(true);check(f.saves.size()==1,"Repeated hidden pause does not rewrite best");
    const auto calls=f.port->advances;session.advance(300);check(f.port->advances==calls,"Paused runtime receives no simulation call");session.setManuallyPaused(true);session.pause(false);check(session.snapshot().paused,"Visibility resume cannot override user pause");session.setManuallyPaused(false);check(session.snapshot().paused,"Clearing manual intent alone waits for visibility reconciliation");session.pause(false);
    session.advance(std::numeric_limits<double>::quiet_NaN());session.advance(-1);session.advance(0);check(f.port->advances==calls,"Invalid elapsed time never reaches engine");session.move({NAN,1});session.pointerUp({1,INFINITY});check(f.port->moves==0&&f.port->ups==0,"Nonfinite pointer cannot reach original runtime");
    f.port->value.score=94;f.port->finish=true;session.advance(1./60);session.advance(1./60);check(f.events==std::vector{m::OrbiPomEvent::started,m::OrbiPomEvent::finished}&&f.saves.back()==94,"Finished transition commits once and only once");
    check(session.start(456)&&f.creations==1&&f.port->starts==2&&f.events.back()==m::OrbiPomEvent::restarted,"Restart reuses one VM and session best");
    m::OrbiPomSession unavailable(-1);check(!unavailable.start()&&!unavailable.hasRuntime()&&unavailable.error()&&unavailable.bestScore()==0,"Missing actual physics runtime stays explicitly unavailable");
    Fixture failing;m::OrbiPomSession failure(0,{[&]{auto p=std::make_unique<Port>();p->failStart=true;failing.port=p.get();return p;},{},[&](auto event){failing.events.push_back(event);}});check(!failure.start()&&failure.hasRuntime()&&failure.error()&&failing.events.empty(),"Original runtime failure publishes no successful Start event");
}
void retirement(){Fixture f;m::OrbiPomSession session(0,f.callbacks());{m::OrbiPomState state(session);state.setActive(true);state.perform(m::OrbiPomAction::start);f.port->value.score=144;}check(session.snapshot().paused&&session.bestScore()==144&&f.saves==std::vector<std::int64_t>{144},"Retiring a canvas pauses retained VM and saves local best");}
void input(){
    Fixture f;m::OrbiPomSession session(0,f.callbacks());m::OrbiPomState state(session);
    check(!state.requiresFrames()&&!state.perform(m::OrbiPomAction::start)&&!state.down({100,100})&&!session.hasRuntime(),"Inactive controls cannot start a VM");state.setActive(true);check(state.presented()&&!state.requiresFrames()&&!session.hasRuntime(),"Visible Start screen still has no clock or VM");state.down({170,280});check(session.hasRuntime()&&state.requiresFrames(),"Enabled source Start rectangle starts visible frame demand");
    check(!state.down({440,200})&&!state.down({200,440}),"Source CGRect maximum boundaries stay outside");state.down({87,88});check(f.port->moves==1&&f.port->ups==0&&f.port->last==P{0,0},"Board down only aims");state.up(P{197,198});check(f.port->ups==1&&closeEnough(f.port->last.x,100)&&closeEnough(f.port->last.y,100),"Held release maps original1.1 world scale");state.up(P{197,198});check(f.port->ups==1,"Orphan release cannot drop");state.down({180,180});state.up(P{-1,180});state.up(P{180,180});check(f.port->ups==1,"Outside release clears the held gesture");
    const auto before=f.port->drops;check(state.key(m::OrbiPomKey::space,true)&&f.port->drops==before,"Space repeat is consumed without dropping");check(!state.key(m::OrbiPomKey::space,false,true)&&f.port->drops==before,"Application modifiers are not consumed");state.key(m::OrbiPomKey::space);check(f.port->drops==before+1,"Fresh Space delegates exact drop logic to runtime");
    f.port->value.previewX=228;state.key(m::OrbiPomKey::right);check(state.keyboardPoint().x==230&&f.port->last.x==230,"Keyboard aim clamps original230world width");state.key(m::OrbiPomKey::left);check(state.keyboardPoint().x==224,"Arrow moves exactly6world points");
    state.perform(m::OrbiPomAction::pause);check(session.manuallyPaused()&&!state.requiresFrames()&&state.boardDimmed(),"Manual pause dims board and removes frame demand");const auto advances=f.port->advances;for(int i=0;i<100;++i)state.advance(10);check(f.port->advances==advances,"Paused host calls never advance simulation");state.setPresented(false);state.setActive(true);check(session.manuallyPaused()&&session.snapshot().paused&&!state.requiresFrames(),"Hide/reopen retains manual pause intent");state.key(m::OrbiPomKey::pause,true);check(session.manuallyPaused(),"P repeat cannot toggle pause");state.key(m::OrbiPomKey::pause);check(state.requiresFrames(),"Fresh P resumes visible session");
    state.setForeground(false);state.advance(20);check(!state.requiresFrames()&&session.snapshot().paused&&f.port->advances==advances,"Focus loss pauses without hidden catch-up");state.setForeground(true);state.advance(1./60);check(f.port->advances==advances+1,"Foreground restoration accepts only new host elapsed time");
    state.perform(m::OrbiPomAction::rules);check(state.rulesPresented()&&!state.requiresFrames()&&session.snapshot().paused,"Rules suspend gameplay");const auto moves=f.port->moves;state.down({180,180});state.up(P{180,180});state.move({200,200});check(f.port->moves==moves&&!state.key(m::OrbiPomKey::space),"Rules retain ownership of game input");state.setRulesPresented(false);check(state.requiresFrames(),"Closing rules resumes only eligible session");
    f.port->value.energy=3;state.perform(m::OrbiPomAction::clear);check(session.snapshot().skill==m::OrbiPomSkill::clear&&state.actions().count==8,"Skill selection adds one source cancel control");check(state.key(m::OrbiPomKey::escape)&&!session.snapshot().skill,"Escape delegates selected-skill cancellation");
    f.port->value.score=123;state.perform(m::OrbiPomAction::restart);check(state.restartConfirmation()&&state.boardDimmed()&&!state.requiresFrames()&&session.bestScore()==123,"Restart confirmation pauses and saves the current score");auto actions=state.actions();check(actions.count==7&&!actions.items[6].enabled&&actions.items[0].rect==endfield::core::Rect{160,256,48,32},"Confirmation exposes exact source geometry and disables other actions");check(state.key(m::OrbiPomKey::escape)&&!state.restartConfirmation()&&state.requiresFrames(),"Escape cancels confirmation preserving runtime");state.perform(m::OrbiPomAction::restart);state.perform(m::OrbiPomAction::confirmRestart);check(f.creations==1&&f.port->starts==2&&session.snapshot().highScore==123&&!state.restartConfirmation(),"Confirm restart reuses VM and retained best");
    const auto allocated=allocations.load();for(int i=0;i<500;++i){state.move({180+double(i%50),180});state.advance(1./60);const auto current=state.actions();if(current.count>8)throw std::runtime_error("Action storage overrun");}check(allocations.load()==allocated,"Warm portable input/frame/actions allocate nothing; actual engine allocations remain outside this check");
    state.down({100,100});state.setActive(false);state.setActive(true);state.up(P{100,100});check(f.port->ups==1,"Deactivation clears pending pointer release");state.setPresented(false);check(!state.requiresFrames()&&!state.active()&&!state.rulesPresented()&&!state.restartConfirmation(),"Hidden module owns no active frame or modal work");
}
}
int main(int argc,char**argv){try{check(argc==2,"Pass immutable original OrbiPom fixture");source(argv[1]);session();input();retirement();std::cout<<"PASS "<<checks<<" OrbiPom source/session/input checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
