#ifdef _WIN32
#include "tools/projection_preview.hpp"
#include "core/data/data_store.hpp"
#include <windows.h>
#include <objbase.h>
#include <iostream>
namespace {
namespace c=endfield::core;namespace a=endfield::app;namespace m=endfield::modules;namespace n=endfield::native;namespace t=endfield::tools;namespace d=ehud::data;using J=d::Json;
unsigned checks{};void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(s);}
struct Window{HWND h{};Window(){WNDCLASSW cl{};cl.lpfnWndProc=DefWindowProcW;cl.hInstance=GetModuleHandleW(nullptr);cl.lpszClassName=L"OwnedProjectionOwnerFixture";check(RegisterClassW(&cl)!=0,"Register isolated Projection owner");h=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,cl.lpszClassName,L"Hidden synthetic Projection",WS_POPUP,0,0,1280,800,nullptr,nullptr,cl.hInstance,nullptr);check(h&&!IsWindowVisible(h),"Projection fixture never shows or activates a window");}~Window(){if(h)DestroyWindow(h);UnregisterClassW(L"OwnedProjectionOwnerFixture",GetModuleHandleW(nullptr));}};
void run(n::Renderer&renderer,const std::filesystem::path&resources){n::LayerRasterizer raster;m::ProjectionModel model({.98,.83,.12,1},.5,.5);m::ProjectionInteraction interaction(model,{1280,800});t::ProjectionPreviewOptions options;options.raster.assetRoot=resources/"notes-format";options.raster.pixelsPerPoint=2;options.raster.paddingPoints=1;constexpr std::string_view wheel="244c34ad474b15c242f9bd62cbf195272cbf7b880acbeaf0021e237d6a22abd2";options.colorWheel=n::NativeNotesControlsImage{{"notes.menu/wheel","source-generated:NotesColorWheelView.wheel",{8,8,166,166},{1,1,1,1},192,false,false},J::Object{{"asset","raster/"+std::string(wheel)+".png"},{"sha256",std::string(wheel)}}};options.shelfChoices=[](){std::vector<m::NotesShelfChoice> choices;for(unsigned k=0;k<8;++k)choices.push_back({"shelf"+std::to_string(k),"Synthetic "+std::to_string(k),"PNG",true,true});return choices;};std::vector<t::ProjectionPreviewEvent>events;options.event=[&](const auto&e){events.push_back(e);};t::ProjectionPreview owner(model,interaction,raster,std::move(options));owner.resize({1280,800,96,1,1280,800});n::LayerComposition composition;double now{};bool released{};struct Cleanup{n::Renderer&r;n::LayerComposition&c;t::ProjectionPreview&o;bool&released;~Cleanup(){if(released)return;try{c.detach(r);o.release(r);}catch(...){r.reset();}}}cleanup{renderer,composition,owner,released};
    auto frame=[&](double dt=.02){now+=dt;owner.update(now);owner.upload(renderer);composition.setEntries(renderer,owner.entries());composition.present(renderer);owner.collected(renderer);renderer.setCamera(n::layerViewportProjection(1280,800));};
    auto down=[&](double x,double y){check(owner.pointer({a::PointerKind::down,a::PointerButton::left,x,y,0},now),"Source pointer down is consumed");};auto up=[&](double x,double y){check(owner.pointer({a::PointerKind::up,a::PointerButton::left,x,y,0},now),"Source pointer up is consumed");};auto click=[&](double x,double y){down(x,y);up(x,y);frame(.2);};auto escape=[&]{check(owner.key({a::KeyKind::down,27},now),"Source Escape consumed by owner");frame(.2);};
    owner.setActive(true,now);frame();check(owner.active()&&!owner.menuOpen()&&!owner.requiresFrames(now),"Source blank Projection settles with no background timer");const auto before=raster.stats();for(unsigned k=0;k<30;++k)frame();check(raster.stats().rasterizations==before.rasterizations,"Steady workspace does no CPU raster work");
    down(100,300);check(owner.pointerLocked(),"Canvas drawing owns capture");check(owner.pointer({a::PointerKind::move,a::PointerButton::none,200,350,0},now),"Source live segment accepts event");frame();up(200,350);frame();check(model.drawing().strokes().size()==1&&!owner.pointerLocked()&&events.back().kind==t::ProjectionPreviewEvent::Kind::strokeCompleted,"Mouse-up commits one stroke and one source event");down(300,300);owner.cancelInteraction(now);frame();check(model.drawing().strokes().size()==1&&!interaction.liveStroke(),"Capture loss discards only uncommitted live ink");
    click(525,80);check(owner.menuOpen(),"Original thickness menu opens");const auto width=model.brushWidth();click(744,189);check(model.brushWidth()==width+1&&owner.menuOpen(),"Exact source plus item changes brush while retaining menu");const auto eventsBefore=events.size();escape();check(!owner.menuOpen()&&events.size()==eventsBefore+1&&events.back().kind==t::ProjectionPreviewEvent::Kind::brushChanged,"Adjustment coalesces its event until source menu close");
    click(490,80);check(owner.menuOpen(),"Original pinned color wheel opens");click(545,160);check(owner.menuOpen(),"Wheel event retains color chooser");check(owner.key({a::KeyKind::down,39},now),"Wheel accepts original four-point arrow adjustment");escape();check(events.back().kind==t::ProjectionPreviewEvent::Kind::brushChanged,"Wheel commits its source event on close");
    click(680,80);check(owner.menuOpen(),"Original background appearance menu opens");down(600,191);check(owner.pointerLocked(),"Only actual slider drag locks pointer");owner.pointer({a::PointerKind::move,a::PointerButton::none,1200,191,0},now);up(1200,191);frame();check(model.darkness()==1&&!owner.pointerLocked(),"Source slider drag clamps beyond the rail without persistent capture");escape();
    click(660,80);check(!model.backgroundEnabled()&&owner.backgroundOpacity()==0,"Source background disabled after finite .18-second fade");click(660,80);check(model.backgroundEnabled()&&owner.backgroundOpacity()==1,"Source background restored without full-window raster replacement");
    click(720,80);check(owner.menuOpen(),"Original media chooser opens");click(550,171);check(owner.menuOpen(),"Shelf picker replaces chooser");check(owner.wheel({550,220,-4,false,0,3},now),"Shelf consumes source scroll");frame();click(500,190);click(720,357);auto action=owner.takeAction();check(action&&action->kind==t::ProjectionPreviewAction::Kind::useShelf&&!action->shelfID.empty(),"Shelf returns original selected reference ID, no file read");
    check(owner.beginImport(action->generation,1,{},now),"Injected validated import begins");const auto raw=d::makeWindowsMediaReference("C:\\owned\\not-opened.png","Synthetic.png",640,480,"image",{},1);auto lease=std::make_shared<int>(7);auto ref=m::ProjectionMediaReference::fromWindowsReference(raw,lease);const std::array refs{ref};check(owner.receiveImport(action->generation,refs,now)&&model.media().size()==1&&events.back().kind==t::ProjectionPreviewEvent::Kind::mediaAdded,"Generation-bound import retains metadata/lease and source event");frame();const auto id=model.media()[0].id;const auto oldFrame=model.media()[0].frame;down(oldFrame.x+40,oldFrame.y+10);owner.pointer({a::PointerKind::move,a::PointerButton::none,oldFrame.x+80,oldFrame.y+30,0},now);up(oldFrame.x+80,oldFrame.y+30);frame();check(model.find(id)->frame.x==oldFrame.x+40,"Media header moves actual model geometry without copying content");
    click(720,80);click(550,137);action=owner.takeAction();check(action&&action->kind==t::ProjectionPreviewAction::Kind::chooseLocal,"Native picker is an explicit queued action");check(owner.beginImport(action->generation,1,{},now),"Second synthetic import starts");owner.setActive(false,now);check(!owner.receiveImport(action->generation,refs,now)&&model.media().size()==1,"Hide invalidates import and retains existing media");owner.setActive(true,now);frame();check(model.drawing().strokes().size()==1&&model.media().size()==1,"Projection session survives return/reopen");
    owner.setPreferences(c::Language::korean,{.2,.7,1,1},{},false,now);frame();check(model.drawing().strokes().size()==1&&model.media().size()==1,"Language/accent event preserves session data");click(610,80);check(owner.menuOpen(),"Source clear confirmation opens");click(700,180);check(model.drawing().strokes().empty()&&model.media().empty()&&events.back().kind==t::ProjectionPreviewEvent::Kind::cleared,"Confirmed clear removes owned drawing/media only");check(*lease==7&&ref->encoded()==raw,"Clear never mutates external reference or lease");frame();escape();action=owner.takeAction();check(action&&action->kind==t::ProjectionPreviewAction::Kind::returnToHUD,"Canvas Escape delegates HUD handoff");composition.detach(renderer);owner.release(renderer);released=true;check(renderer.stats().textures==0&&renderer.stats().meshes==0,"Projection owner releases every local resource after detach");
}
}
int wmain(int argc,wchar_t**argv){auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==3,"Pass HLSL and original resources root");Window window;n::Renderer renderer;renderer.initialize(window.h,1280,800,{n::Driver::warpForTests,argv[1],n::RenderTarget::offscreenForTests});run(renderer,std::filesystem::absolute(argv[2]));renderer.reset();CoUninitialize();std::cout<<"PASS "<<checks<<" Projection owner checks\n";return 0;}catch(const std::exception&e){if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
