#include "modules/projection_model.hpp"
#include "core/data/data_store.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iostream>
#include <limits>
#include <stdexcept>
namespace m=endfield::modules;namespace c=endfield::core;using J=ehud::data::Json;
namespace {unsigned checks{};void check(bool v,const char*message){++checks;if(!v)throw std::runtime_error(message);}double number(const J&v){if(v.isString())return v.string()=="nan"?std::numeric_limits<double>::quiet_NaN():std::numeric_limits<double>::infinity();return v.number();}c::Rect rect(const J&v){return {number(v.array()[0]),number(v.array()[1]),number(v.array()[2]),number(v.array()[3])};}void equal(c::Rect a,c::Rect b){check(std::abs(a.x-b.x)<1e-8&&std::abs(a.y-b.y)<1e-8&&std::abs(a.width-b.width)<1e-8&&std::abs(a.height-b.height)<1e-8,"Projection constrain differs from unchanged original AppKit");}
void source(const char*path){std::ifstream file(path);check(bool(file),"Explicit owned geometry fixture exists");const std::string bytes((std::istreambuf_iterator<char>(file)),{});const auto json=J::parse(bytes,1024*1024);check(json["authority"].string()=="ca04f142185c7de40acd8523bdb563195d90a1d1","Projection source authority pinned");for(const auto&r:json["constrain"].array())equal(m::ProjectionModel::constrain(rect(r["frame"]),rect(r["bounds"])),rect(r["expected"]));for(const auto&r:json["insets"].array()){const auto g=m::projectionWorkspaceGeometry({1920,1080},number(r["input"].array()[0]),number(r["input"].array()[1]));check(std::abs(g.toolbar.y-r["expected"].number())<1e-8,"Toolbar inset matches source for finite/nonfinite screen values");}}
void session(){m::ProjectionModel model({.9,.7,.1,1},.37,.75);check(model.brushWidth()==5&&model.backgroundEnabled()&&!model.erasing(),"Session source defaults preserved");check(model.setBrushWidth(200)&&model.brushWidth()==80,"Brush upper limit");check(model.setBrushWidth(-1)&&model.brushWidth()==1,"Brush lower limit");check(!model.setBrushWidth(std::numeric_limits<double>::quiet_NaN())&&model.brushWidth()==1,"Nonfinite brush event ignored");check(model.setDarkness(2)&&model.darkness()==1&&model.setBlur(-2)&&model.blur()==0,"Background adjustments clamp independently");check(model.setErasing(true)&&model.setBackgroundEnabled(false),"Session toggles mutate without persistence");
    m::DrawingStroke stroke;stroke.points={{.1,.1},{.2,.2}};stroke.width=5;check(model.append(stroke)&&model.drawing().strokes().size()==1,"Projection reuses validated Notes vector storage");check(model.erase({150,150},{1000,1000})&&model.drawing().strokes().empty(),"Source eraser removes intersecting complete stroke");check(!model.append({}),"Empty vector stroke never enters session");
    const auto original=ehud::data::makeWindowsMediaReference("C:\\owned\\not-opened.png","Sample.png",640,480,"image",{},1);auto lease=std::make_shared<int>(7);auto ref=m::ProjectionMediaReference::fromWindowsReference(original,lease);check(ref->encoded()==original&&ref->accessLease()==lease,"Media retains exact existing reference and access lease without copying a file");std::vector<std::uint64_t>ids;for(unsigned i=0;i<16;++i){const auto id=model.addMedia(ref,{500,350},{0,0,1000,700});check(id.has_value(),"Session accepts bounded source media count");ids.push_back(*id);}check(!model.addMedia(ref,{0,0},{0,0,1000,700})&&model.media().size()==16,"Media limit rejects new work without removing existing entries");check(model.bringForward(ids[0])&&model.media().back().id==ids[0]&&!model.bringForward(ids[0]),"Z-order preserves identities and skips equal order");check(model.setFrame({-200,-300,700,600},ids[0],{0,0,400,300}),"Explicit media move/resize accepted");equal(model.find(ids[0])->frame,{0,0,400,300});check(model.removeMedia(ids[4])&&!model.find(ids[4]),"Remove releases only session identity");check(model.clearContent()&&model.media().empty()&&!model.clearContent(),"Clear affects owned media/vectors only");check(!model.backgroundEnabled()&&model.erasing()&&model.brushWidth()==1&&model.darkness()==1&&model.blur()==0,"Clear keeps brush and background preferences");check(ref->encoded()==original&&*lease==7,"Clear cannot mutate external reference or lease");
    const auto geometry=m::projectionWorkspaceGeometry({1280,800});check(geometry.toolbar==c::Rect{472,64,336,42},"Compact toolbar uses existing source dimensions");const auto menu=m::projectionMenuFrame(geometry,{260,92});check(menu==c::Rect{510,118,260,92},"Secondary menu belongs directly below toolbar");
}}
int main(int argc,char**argv){try{check(argc==2,"Pass original AppKit geometry fixture");source(argv[1]);session();std::cout<<"PASS "<<checks<<" Projection source/model checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
