#include "tools/projection_media_binding.hpp"
#ifdef _WIN32
#include "core/data/data_store.hpp"
#include <objbase.h>
#include <atomic>
#include <iostream>
namespace {
namespace n=endfield::native;namespace m=endfield::modules;namespace t=endfield::tools;namespace a=endfield::app;namespace c=endfield::core;namespace d=ehud::data;
unsigned checks{};void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}
struct Window {HWND h{};static constexpr UINT notice=WM_APP+261;Window(){h=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,L"STATIC",L"Owned synthetic Projection media",WS_POPUP,0,0,1280,800,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);check(h&&!IsWindowVisible(h),"Synthetic media fixture remains hidden");}~Window(){if(h)DestroyWindow(h);}};
class Sequence:public n::NativeNotesImageDecoder::Sequence {
 n::NotesImageInfo info_;bool poster_{};
public:explicit Sequence(const n::NotesImageRequest&r):poster_(r.videoPoster){const bool gif=r.path.ends_with(".gif")&&!r.firstFrameOnly&&!r.videoPoster;info_={2,2,gif?2u:1u,gif?m::NotesMediaKind::gif:m::NotesMediaKind::image,gif?std::vector<double>{600,.04}:std::vector<double>{},gif?600.04:0};}
 const n::NotesImageInfo&info()const override{return info_;}
 n::NotesImageFrame decode(unsigned index)override{n::NotesImageFrame f{2,2,index,std::vector<std::uint8_t>(16)};for(unsigned p=0;p<16;p+=4){f.straightRGBA[p+(poster_?2:index*2)]=255;f.straightRGBA[p+3]=255;}return f;}
};
struct EngineState {n::NativeNotesVideoPlayback::Notify notify;std::string key,path;double position{};unsigned plays{},seeks{},stops{};};
class Engine:public n::NativeNotesVideoPlayback::Engine {std::shared_ptr<EngineState>s_;public:explicit Engine(std::shared_ptr<EngineState>s):s_(std::move(s)){}HRESULT open(const n::NotesVideoRequest&r)override{s_->key=r.key;s_->path=r.path;s_->notify(n::NativeNotesVideoPlayback::ready,S_OK);return S_OK;}HRESULT metadata(n::NotesVideoMetadata&o)override{o={2,2,10};return S_OK;}HRESULT play()override{++s_->plays;return S_OK;}HRESULT pause()override{return S_OK;}HRESULT seek(double t)override{s_->position=t;++s_->seeks;s_->notify(n::NativeNotesVideoPlayback::seeked,S_OK);return S_OK;}double currentTime()const override{return s_->position;}HRESULT tick(std::int64_t&)override{return S_FALSE;}HRESULT transfer(void*,unsigned,unsigned)override{return E_NOTIMPL;}void stop()noexcept override{++s_->stops;}};
std::shared_ptr<const m::ProjectionMediaReference>reference(std::string file,std::string kind="image"){return m::ProjectionMediaReference::fromWindowsReference(d::makeWindowsMediaReference("C:\\Projection-fixture\\"+file,file,2,2,kind,kind=="image"?std::nullopt:std::optional(kind=="gif"?600.04:10.),kind=="gif"?2:1));}
void run(const std::filesystem::path&shader){Window window;n::Renderer renderer;renderer.initialize(window.h,1280,800,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests,true});n::LayerRasterizer raster;m::ProjectionModel model({.98,.83,.12,1},.5,.5);m::ProjectionInteraction interaction(model,{1280,800});t::ProjectionPreviewOptions options;options.raster.pixelsPerPoint=1;options.reduceMotion=true;t::ProjectionPreview preview(model,interaction,raster,options);preview.resize({1280,800,96,1,1280,800});preview.setActive(true,0);
 const auto still=*model.addMedia(reference("red.png"),{190,400},{0,0,1280,800});const auto gif=*model.addMedia(reference("animation.gif","gif"),{580,400},{0,0,1280,800});const auto movie=*model.addMedia(reference("movie.mp4","video"),{980,400},{0,0,1280,800});
 std::atomic<unsigned>opens{};n::NativeNotesImageDecoder decoder([](const auto&r){return n::NotesImageAccess{std::filesystem::u8path(r.path),r.accessLease};},{window.h,Window::notice,97},[&](const auto&r,n::NotesImageAccess){++opens;if(r.path.ends_with("bad.png")||r.path.ends_with("bad.mp4"))throw std::runtime_error("Synthetic codec error");return std::make_unique<Sequence>(r);});n::NativeNotesImagePlayback playback(decoder);std::vector<std::shared_ptr<EngineState>>engines;n::NativeNotesVideoPlayback video(renderer,{window.h,Window::notice,97},[&](auto device,auto notify){check(bool(device),"Synthetic video borrows same renderer device");auto state=std::make_shared<EngineState>();state->notify=std::move(notify);engines.push_back(state);return std::make_unique<Engine>(state);});n::NativeMediaRequestBroker broker(decoder,playback,{window.h,Window::notice,97},&video);const auto client=broker.attachClient(),sibling=broker.attachClient();const std::array siblingRequests{n::NotesImagePlaybackRequest{{"unrelated","C:\\Projection-fixture\\sibling.png",1,64,false,{},false,false},m::NotesMediaKind::image}};broker.setImages(sibling,1,siblingRequests,0);
 t::ProjectionMediaBindingOptions bindingOptions;bindingOptions.resolve=[](const auto&r){return n::NotesImageAccess{std::filesystem::u8path(r.path()),r.accessLease()};};bindingOptions.errorText=[](HRESULT){return "Synthetic media unavailable";};t::ProjectionMediaBinding binding(preview,model,broker,client,renderer,bindingOptions);n::LayerComposition composition;double now{};bool released{};struct Cleanup{n::LayerComposition&c;n::Renderer&r;t::ProjectionPreview&p;t::ProjectionMediaBinding&b;double&t;bool&done;~Cleanup(){if(done)return;try{c.detach(r);p.release(r);b.releaseResources(t);}catch(...){r.reset();}}}cleanup{composition,renderer,preview,binding,now,released};
 auto frame=[&]{preview.update(now);binding.sync(now);broker.accept(97,now);broker.sample(now);binding.refresh(now);preview.upload(renderer);composition.setEntries(renderer,preview.entries());composition.present(renderer);preview.collected(renderer);binding.collectRetired();renderer.setCamera(n::layerViewportProjection(1280,800));renderer.draw(false);};
 auto await=[&](auto ready,const char*message){const auto end=GetTickCount64()+10000;for(;;){frame();if(ready())break;const auto current=GetTickCount64();check(current<end,message);MsgWaitForMultipleObjectsEx(0,nullptr,static_cast<DWORD>(end-current),QS_POSTMESSAGE,MWMO_INPUTAVAILABLE);MSG m{};while(PeekMessageW(&m,window.h,0,0,PM_REMOVE)){} }};
 auto draw=[&](std::uint64_t id)->const n::DrawObject*{const auto wanted="projection.media.borrowed:"+std::to_string(id);for(const auto&e:preview.entries())for(const auto&d:e.after)if(d.sourceID==wanted)return &d;return nullptr;};
 await([&]{return draw(still)&&draw(gif)&&draw(movie)&&broker.findImage(sibling,"unrelated")&&broker.findImage(sibling,"unrelated")->frame;},"Bounded shared worker prepares all source media kinds");const auto siblingFrame=broker.findImage(sibling,"unrelated")->frame;check(opens>=4&&video.stats().visible==1&&engines[0]->plays==0,"Still/GIF and paused video share existing providers without automatic movie playback");check(renderer.stats().mediaTargets==0,"Opening a paused movie retains only original worker poster");
 const auto rasterBefore=raster.stats();const auto uploads=renderer.stats().textureUploads,requests=broker.decoderStats().requests;for(unsigned k=0;k<120;++k){binding.sync(now);binding.refresh(now);}check(raster.stats().rasterizations==rasterBefore.rasterizations&&renderer.stats().textureUploads==uploads&&broker.decoderStats().requests==requests,"Unchanged shared-media frames perform no decode, raster or upload");
 auto moved=model.find(still)->frame;moved.x+=20;model.setFrame(moved,still,{0,0,1280,800});frame();check(broker.decoderStats().requests==requests&&draw(still),"Media move only changes source placement, never resubmits provider data");const auto content=m::projectionMediaGeometry({moved.width,moved.height},m::NotesMediaKind::image).content;check(draw(still)->masks.size()==1&&draw(still)->masks[0].bounds==content,"Borrowed image retains actual source content clip");
 const auto token=*preview.prepareImportRequest();t::ProjectionPreviewAction play{t::ProjectionPreviewAction::Kind::togglePlayback,token,movie,{},0};check(binding.action(play,now)&&engines[0]->plays==1,"Explicit movie action alone starts shared playback");auto seek=play;seek.kind=t::ProjectionPreviewAction::Kind::seek;seek.seconds=7;check(binding.action(seek,now)&&engines[0]->seeks==1,"Source seek reaches one existing engine");t::ProjectionPreviewAction gifAction{t::ProjectionPreviewAction::Kind::togglePlayback,token,gif,{},0};check(binding.action(gifAction,now),"GIF toggle reaches its own shared record");check(broker.findImage(sibling,"unrelated")->frame==siblingFrame,"Projection actions preserve unrelated Notes/Archive client data");
 const std::array mixed{t::ProjectionImportFile{"C:\\Projection-fixture\\good.png","good.png",{}},t::ProjectionImportFile{"C:\\Projection-fixture\\bad.png","bad.png",{}}};const auto import=*preview.prepareImportRequest();check(binding.beginImport(import,mixed,{},now),"Explicit import uses existing shared inspection worker");std::optional<std::uint64_t>next;await([&]{next=preview.prepareImportRequest();return next.has_value();},"Failed batch settles without keeping input locked");check(model.media().size()==3,"Projection all-or-nothing import never keeps successful siblings of a failed batch");const auto lease=std::make_shared<int>(42);const std::array good{t::ProjectionImportFile{"C:\\Projection-fixture\\good.png","good.png",lease}};check(binding.beginImport(*next,good,c::Point{700,200},now),"Next complete batch starts after failure");await([&]{return model.media().size()==4;},"Validated full batch appends one source reference");check(model.media().back().reference->accessLease()==lease&&model.media().back().reference->encoded().find("windows")!=std::string::npos,"Imported media remains reference-only and retains independent access lease");
 const auto bad=*model.addMedia(reference("bad.mp4","video"),{600,600},{0,0,1280,800});await([&]{for(const auto&e:engines)if(e->path.ends_with("bad.mp4")){const auto*r=video.find(e->key);if(r&&FAILED(r->posterError)&&r->state==m::NotesMediaState::paused)return true;}return false;},"Poster failure is forwarded so shared engine does not remain loading");check(model.removeMedia(bad),"Failed poster does not destroy valid source metadata");frame();
 const auto old=model.media().size();const auto stale=*preview.prepareImportRequest();check(binding.beginImport(stale,good,{},now),"Cancelable import begins on shared worker");preview.setActive(false,now);frame();check(!preview.importRequestCurrent(stale)&&model.media().size()==old&&broker.findImage(sibling,"unrelated")->visible,"Hide invalidates import and stops only this module's provider demand");composition.detach(renderer);preview.release(renderer);check(binding.releaseResources(now),"Post-fade detach retires borrowed Projection GPU resources");preview.setActive(true,now);frame();await([&]{return draw(still)&&draw(movie);},"Reopen reacquires source media with fresh resource identities");check(model.media().size()==old,"Close/reopen preserves the session model");
 composition.detach(renderer);preview.release(renderer);check(binding.releaseResources(now)&&broker.detachClient(client),"Projection client fully retires after detaching owner");broker.hideImages(sibling,now);check(broker.retireImage(sibling,"unrelated")&&broker.detachClient(sibling),"Other client can retire independently");const auto worker=decoder.duplicateWorkerHandle();decoder.stop();check(WaitForSingleObject(worker,10000)==WAIT_OBJECT_0,"Root stops the one existing worker");CloseHandle(worker);released=true;check(renderer.stats().resourceBytes==0&&!IsWindowVisible(window.h),"No GPU resources or visible/user-data side effects remain");renderer.reset();
}
}
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==2,"Pass original HUD shader");run(argv[1]);CoUninitialize();std::cout<<"PASS "<<checks<<" Projection shared-media checks\n";return 0;}catch(const std::exception&e){if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
