#include "native/projection_plane.hpp"
#include <cmath>
#include <iostream>
#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#endif
namespace n=endfield::native;namespace c=endfield::core;
namespace {unsigned checks{};void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(s);}
void portable(){const auto grid=n::projectionGridMesh({100,75});check(grid.vertices.size()==36&&grid.indices.size()==54,"Source36-point cells allocate only screen coverage");check(grid.vertices[0].position==std::array<float,3>{0,0,0}&&grid.vertices[0].uv==std::array<float,2>{0,0},"Grid starts at source origin");check(grid.vertices[34].position==std::array<float,3>{100,75,0}&&std::abs(grid.vertices[34].uv[0]-28.f/36)<1e-7&&std::abs(grid.vertices[34].uv[1]-3.f/36)<1e-7,"Final cell crops original UVs without stretching dots");const auto cell=n::projectionDotCell();const auto&dot=cell["children"].array()[0];check(dot["position"].array()[0].number()==12&&dot["position"].array()[1].number()==12&&dot["bounds"].array()[2].number()==2&&dot["backgroundColor"]["sRGB"].array()[3].number()==.14,"Exact source2x2 white dots at12+36n and alpha.14");const auto ring=n::projectionCursor(12,{1,0,0,1},false);check(ring["shape"]["lineWidth"].number()==1&&ring["shape"]["lineDashPattern"].isNull()&&ring["shape"]["path"].array().size()==6,"Source brush ring uses one-point elliptical outline");const auto eraser=n::projectionCursor(12,{1,0,0,1},true);check(eraser["shape"]["lineDashPattern"].array().size()==2&&eraser["shape"]["lineDashPattern"].array()[0].number()==3&&eraser["shape"]["strokeColor"]["sRGB"].array()[1].number()==1,"Eraser uses source white and3/2 dash pattern");bool rejected{};try{n::projectionGridMesh({1e9,1e9});}catch(const std::invalid_argument&){rejected=true;}check(rejected,"Grid validates existing renderer vertex budget before allocating");}
#ifdef _WIN32
struct Window{HWND h{};ATOM a{};Window(){WNDCLASSW cl{};cl.lpfnWndProc=DefWindowProcW;cl.hInstance=GetModuleHandleW(nullptr);cl.lpszClassName=L"OwnedProjectionPlaneFixture";a=RegisterClassW(&cl);check(a!=0,"Register own Projection plane fixture");h=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,cl.lpszClassName,L"Hidden source plane",WS_POPUP,0,0,384,256,nullptr,nullptr,cl.hInstance,nullptr);check(h&&!IsWindowVisible(h),"Projection plane test stays hidden");}~Window(){if(h)DestroyWindow(h);if(a)UnregisterClassW(reinterpret_cast<LPCWSTR>(static_cast<ULONG_PTR>(a)),GetModuleHandleW(nullptr));}};
void native(const std::filesystem::path&shader){Window w;n::Renderer renderer;renderer.initialize(w.h,384,256,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests});n::LayerRasterizer raster;n::LayerRasterOptions options;options.paddingPoints=0;n::NativeProjectionPlane plane(raster,options);check(plane.resize({256,256./1.5},1.5),"Create actual fractional-DPI source plane");plane.setBackground(.4,1);plane.setCursor({},12,{1,0,0,1},false);plane.upload(renderer);n::LayerComposition composition;const std::array<n::LayerCompositionEntry,2>entries{plane.backgroundEntry(),plane.cursorEntry()};composition.setEntries(renderer,entries);composition.present(renderer);renderer.setCamera(n::layerViewportProjection(384,256));renderer.draw(false);auto image=renderer.readback();const auto alpha=[&](unsigned x,unsigned y){return image.pixels[y*image.rowBytes+x*4+3];};check(alpha(2,2)>=101&&alpha(2,2)<=103,"Only source black darkness plate is drawn");check(alpha(19,19)>alpha(2,2)&&alpha(73,19)==alpha(19,19),"Retained dot cell repeats at exact54physical-pixel period");check(raster.stats().resourceBytes<128*128*4,"Background uses one36-point cell and small cursor, no full-screen raster");const auto gpu=renderer.stats();const auto paint=raster.stats();for(unsigned i=0;i<120;++i){plane.setBackground(.4,double(i%19)/18);plane.setCursor(c::Point{80+double(i),100},12,{1,0,0,1},false);plane.upload(renderer);composition.setEntries(renderer,entries);composition.present(renderer);}check(renderer.stats().textureUploads==gpu.textureUploads&&renderer.stats().meshUploads==gpu.meshUploads&&raster.stats().rasterizations==paint.rasterizations,"Background fades and brush motion reuse all resources");plane.setBackground(.4,0);plane.setCursor({},12,{1,0,0,1},false);composition.present(renderer);renderer.draw(false);image=renderer.readback();check(alpha(2,2)==0&&alpha(19,19)==0,"Background toggle hides both source plate and dots");composition.detach(renderer);check(plane.releaseResources(renderer)&&renderer.stats().resourceBytes==0,"Plane resources retire after shared composition detach");check(!IsWindowVisible(w.h)&&renderer.stats().presents==0,"No actual screen or user data read");}
#endif
}
#ifdef _WIN32
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);if(FAILED(hr))return 1;int result{};try{portable();check(argc==2,"Pass hud.hlsl");native(argv[1]);std::cout<<"PASS "<<checks<<" Projection plane checks\n";}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';result=1;}CoUninitialize();return result;}
#else
int main(){try{portable();std::cout<<"PASS "<<checks<<" Projection plane checks\n";}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
