#ifdef _WIN32
#include "tools/reader_preview.hpp"
#include "native/module_scene.hpp"
#include <windows.h>
#include <objbase.h>
#include <algorithm>
#include <array>
#include <atomic>
#include <cstdio>
#include <cstdlib>
#include <deque>
#include <iostream>
#include <new>
namespace {std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {
using namespace endfield;namespace gpu=native;namespace mod=modules;using J=mod::ReaderJson;unsigned checks{};
void check(bool value,const char*message){++checks;if(!value)throw std::runtime_error(message);}
std::string uuid(unsigned n){char s[64];std::snprintf(s,sizeof(s),"B0000000-0000-4000-8000-%012u",n);return s;}
mod::ReaderBook book(unsigned n){return mod::windowsReaderReference(uuid(n),"C:\\Owned-unopened-reader-fixture\\book"+std::to_string(n)+".txt","Synthetic book "+std::to_string(n));}
struct Repository:mod::ReaderRepository {mod::ReaderLibrary saved;unsigned reads{},writes{};mod::ReaderLibrary load()override{++reads;return saved;}void save(const mod::ReaderLibrary&next)override{++writes;saved=next;}};
struct Queue {struct Job{std::function<void()>work;std::function<void(std::exception_ptr)>done;};std::deque<Job>jobs;mod::ReaderExecutor executor(){return {[this](auto work,auto done){if(jobs.size()>=32)return false;jobs.push_back({std::move(work),std::move(done)});return true;}};}void drain(){for(unsigned n=0;!jobs.empty();++n){check(n<100,"Injected FIFO does not spin or install a retry timer");auto job=std::move(jobs.front());jobs.pop_front();std::exception_ptr error;try{job.work();}catch(...){error=std::current_exception();}job.done(error);}}};
struct Source:mod::ReaderDocumentSource {
    unsigned opens{},renders{},details{},releases{};bool illustration{};std::shared_ptr<const mod::ReaderPagePixels>detailPixels;std::string opened;std::array<std::shared_ptr<const mod::ReaderPagePixels>,3>pixels;
    Source(){for(unsigned k=0;k<3;++k){auto p=std::make_shared<mod::ReaderPagePixels>();p->width=p->height=200;p->format=mod::ReaderPagePixels::Format::bgra8Premultiplied;for(unsigned n=0;n<200*200;++n)p->bytes.insert(p->bytes.end(),{0,static_cast<std::uint8_t>(k==1?255:0),static_cast<std::uint8_t>(k==0?255:0),255});pixels[k]=p;}auto crop=std::make_shared<mod::ReaderPagePixels>();crop->width=crop->height=200;crop->format=mod::ReaderPagePixels::Format::bgra8Premultiplied;for(unsigned n=0;n<200*200;++n)crop->bytes.insert(crop->bytes.end(),{255,0,0,255});detailPixels=crop;}
    void open(const mod::ReaderBook&b,const std::function<bool()>&cancel)override{if(!cancel()){++opens;opened=b.id;}}
    mod::ReaderPage page(int n){mod::ReaderPage p;p.location.section=n;p.progress=n/2.;p.summary="Injected page";p.illustration=illustration;p.pixels=pixels[static_cast<std::size_t>(n)];if(n<2)p.next=mod::ReaderLocation{n+1};if(n>0)p.previous=mod::ReaderLocation{n-1};return p;}
    std::vector<mod::ReaderPage>render(std::optional<mod::ReaderLocation>where,std::optional<double>progress,const mod::ReaderPreferences&,core::Point,bool,const std::function<bool()>&cancel)override{if(cancel())return {};check(!opened.empty(),"Only injected provider's retained synthetic document renders");++renders;const auto n=progress?static_cast<int>(*progress*2):static_cast<int>(where.value_or(mod::ReaderLocation{}).section);auto current=page(std::clamp(n,0,2));std::vector<mod::ReaderPage>p{current};if(current.next)p.push_back(page(static_cast<int>(current.next->section)));if(current.previous)p.push_back(page(static_cast<int>(current.previous->section)));return p;}
    mod::ReaderPage detail(mod::ReaderLocation l,const mod::ReaderPreferences&,core::Point,bool,mod::ReaderImageView,const std::function<bool()>&cancel)override{if(cancel())return {};++details;auto result=page(static_cast<int>(l.section));if(illustration)result.pixels=detailPixels;return result;}
    void release()override{++releases;opened.clear();}
};
struct Window{HWND hwnd{};Window(){hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,L"STATIC",L"Owned Reader integration fixture",WS_POPUP,0,0,1280,800,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Reader fixture creates only a hidden owned window");}~Window(){if(hwnd)DestroyWindow(hwnd);}};
void run(const std::filesystem::path&shader){Window w;gpu::Renderer renderer;renderer.initialize(w.hwnd,1280,800,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});renderer.setCamera(gpu::layerViewportProjection(1280,800));gpu::LayerRasterizer raster;Queue queue;auto repository=std::make_shared<Repository>();for(unsigned n=1;n<=9;++n)repository->saved.books.push_back(book(n));repository->saved.selected=uuid(1);repository->saved.preferences=mod::ReaderPreferences::defaults("System");auto provider=std::make_shared<Source>();mod::ReaderState state(repository,queue.executor(),provider);tools::ReaderPreviewOptions options;options.raster.pixelsPerPoint=1;options.strings=mod::ReaderStrings{};unsigned marks=100;options.newID=[&]{return uuid(++marks);};options.fontFamilies=[] {return std::vector<std::string>{"Noto Sans SC","Noto Sans KR","Georgia"};};options.shelfChoices=[] {return std::vector<mod::ReaderMenuChoice>{{"owned-shelf","Shelf fixture.txt"}};};tools::ReaderPreview preview(state,raster,std::move(options));preview.resize({1280,800,96,1,1280,800});core::source::DesktopChromeSettings settings;settings.viewport={0,0,1280,800};settings.module=core::Module::reader;core::ModulePresentation modules(core::Module::reader);double time{};gpu::LayerComposition composition;
    const auto frame=[&](double t){time=t;preview.update({},settings,modules.sample(time).presentation,1,time);preview.upload(renderer);composition.setEntries(renderer,preview.entries());composition.present(renderer);renderer.draw(false);preview.collected(renderer);};
    frame(0);queue.drain();frame(1);check(state.current()&&provider->opens==1&&provider->renders==1&&repository->reads==1,"Reader opens/renders once through the borrowed FIFO without touching locator files");check(state.library().preferences.fontName=="System","Fresh automatic font sentinel is retained rather than persisted as an SC override");
    gpu::LayerScene geometry(raster);geometry.load(J::Object{{"bounds",J::Array{0,0,400,440}},{"children",J::Array{}}},{});gpu::NativeModuleSurface surface(geometry,core::Module::reader);surface.update({},settings,modules.sample(time).presentation.current,1);const auto plane=core::Projection::viewport(gpu::layerViewportProjection(1280,800)*surface.pose().contentWorld,1280,800);
    const auto point=[&](double x,double y){auto p=plane.project({x,y});check(bool(p),"Existing shared source projection maps Reader fixture input");return *p;};
    const auto click=[&](double x,double y){const auto p=point(x,y);check(preview.pointer({app::PointerKind::down,app::PointerButton::left,p.x,p.y},time+=.2),"Source Reader action receives projected pointer down");preview.pointer({app::PointerKind::up,app::PointerButton::left,p.x,p.y},time+=.01);};
    const auto outside=point(470,120);check(!preview.pointer({app::PointerKind::down,app::PointerButton::left,outside.x,outside.y},time+=.01),"Reader leaves sidebar/outside pointer down to the shared navigation owner");check(!preview.pointer({app::PointerKind::up,app::PointerButton::left,outside.x,outside.y},time+=.01)&&!preview.capturesPointer(),"Outside down never poisons Reader press ownership or steals navigation pointer up");
    click(100,20);check(preview.capturesPointer(),"Library establishes only its explicit local modal routing");check(preview.pointer({app::PointerKind::down,app::PointerButton::left,outside.x,outside.y},time+=.01)&&!preview.capturesPointer(),"Outside click dismisses an open Reader menu and consumes its own down");check(preview.pointer({app::PointerKind::up,app::PointerButton::left,outside.x,outside.y},time+=.01),"Menu dismissal owns the matching pointer up");check(!preview.pointer({app::PointerKind::down,app::PointerButton::left,outside.x,outside.y},time+=.01)&&!preview.pointer({app::PointerKind::up,app::PointerButton::left,outside.x,outside.y},time+=.01),"Subsequent outside navigation remains unconsumed after menu dismissal");frame(time+.2);
    click(268,20);check(state.book()->bookmarks.empty(),"Bookmark remains unconfirmed until injected durable callback");queue.drain();frame(time+.2);check(state.book()->bookmarks.size()==1&&repository->saved.books[0].bookmarks.size()==1,"Original star captures current location and commits only through injected repository");
    const auto scrollPoint=point(200,200);const auto renders=provider->renders;check(preview.wheel({scrollPoint.x,scrollPoint.y,-1,false,0,3},time+=.2),"Inner Reader wheel consumes original viewport input");frame(time+.2);check(provider->renders==renders,"Small text scroll repositions bounded cached page pixels without decode work");
    click(100,20);check(preview.pointerLocked(),"Original Library menu retains local input routing");mod::ReaderMenuInput library;library.type=mod::ReaderMenuType::library;for(const auto&b:state.library().books)library.choices.push_back({b.id,b.title});const auto sourceLibrary=mod::prepareReaderMenu(library);const auto closeAction=std::find_if(sourceLibrary.actions.begin(),sourceLibrary.actions.end(),[](const auto&a){return a.id=="close";});check(closeAction!=sourceLibrary.actions.end(),"Original list has its close action");click(42+closeAction->rect.x+10,44+closeAction->rect.y+10);frame(time+.3);check(!preview.pointerLocked(),"Closing Library relinquishes menu input after its finite fade");
    click(40,20);click(30,60);auto action=preview.takeImportAction();check(action&&action->kind==tools::ReaderImportAction::Kind::chooseLocal&&preview.importRequestCurrent(action->generation),"Original Open menu queues one tagged request for the app's shared native picker");check(preview.receiveImportError(action->generation,{},time+=.2),"Native picker cancellation acknowledges only the current generation");frame(time+.3);check(state.book()->id==uuid(1)&&state.current(),"Dialog cancellation keeps the existing document and pixels intact");
    click(40,20);click(30,60);action=preview.takeImportAction();check(action&&preview.beginImport(action->generation,time+=.2),"Selected native reference starts source loading only after actual dialog selection");check(preview.receiveImportError(action->generation,std::string("Synthetic invalid book"),time+=.2),"Import validation failure is a tagged source error, never a blank success");frame(time+.3);check(state.book()->id==uuid(1)&&state.current()&&!preview.importRequestCurrent(action->generation),"Failed import preserves confirmed recent-book data while replacing only the visible status");
    click(100,20);click(60,95);queue.drain();frame(time+.3);check(state.book()->id==uuid(1)&&state.current(),"Selecting confirmed Library book clears validation status and reopens the original reference");
    click(40,20);click(30,60);action=preview.takeImportAction();check(action&&preview.beginImport(action->generation,time+=.2)&&preview.receiveImport(action->generation,book(20),time+=.2),"Validated native import submits a source structural transaction");queue.drain();frame(time+.3);check(state.book()->id==uuid(20)&&state.current()&&repository->saved.selected==std::optional(uuid(20)),"Only durable import selects and opens a new synthetic document");const auto importedPixel=point(200,200);const auto importedRaster=renderer.readback();const auto importedOffset=static_cast<std::size_t>(importedPixel.y)*importedRaster.rowBytes+static_cast<std::size_t>(importedPixel.x)*4;check(importedRaster.pixels[importedOffset+2]>250&&importedRaster.pixels[importedOffset]<5,"Fast durable save/open/render completed before paint still publishes imported page pixels instead of permanent loading");
    // Test the source list's deletion confirmation using the actual action tree,
    // not guessed screen coordinates or default-app/filesystem operations.
    click(100,20);library.choices.clear();for(const auto&b:state.library().books)library.choices.push_back({b.id,b.title});auto artwork=mod::prepareReaderMenu(library);const auto erase=std::find_if(artwork.actions.begin(),artwork.actions.end(),[](const auto&a){return a.id.starts_with("delete:");});check(erase!=artwork.actions.end(),"Actual Reader list exposes a per-book delete control");const auto erasedID=std::string(erase->id.substr(7));click(42+erase->rect.x+10,44+erase->rect.y+10);check(repository->saved.books.size()==10,"Delete click only enters original confirmation artwork");library.deletion=erasedID;artwork=mod::prepareReaderMenu(library);const auto confirm=std::find_if(artwork.actions.begin(),artwork.actions.end(),[](const auto&a){return a.id=="confirmDelete";});check(confirm!=artwork.actions.end(),"Original deletion confirmation has explicit confirm action");click(42+confirm->rect.x+10,44+confirm->rect.y+10);queue.drain();frame(time+.3);check(repository->saved.books.size()==9&&std::none_of(repository->saved.books.begin(),repository->saved.books.end(),[&](const auto&b){return b.id==erasedID;}),"Deletion removes only the confirmed reference from injected recent-book storage");
    check(!preview.key({app::KeyKind::down,VK_DOWN},true,time+=.2),"Modified keys remain available to the existing host shortcuts");check(preview.key({app::KeyKind::down,VK_DOWN},false,time+=.2),"Unmodified source Reader down key scrolls inner cached text");frame(time+.3);frame(time+.2);const auto beforeRaster=raster.stats();const auto beforeGPU=renderer.stats();const auto beforeRenders=provider->renders;allocations=0;std::array<std::size_t,4>allocationPhases{};counting=true;try{for(unsigned n=0;n<120;++n){time+=1./60;auto before=allocations.load();preview.update(core::Matrix4::rotation(0,n*.00001,0),settings,modules.sample(time).presentation,.8f,time);allocationPhases[0]+=allocations.load()-before;before=allocations.load();preview.upload(renderer);allocationPhases[1]+=allocations.load()-before;before=allocations.load();composition.present(renderer);allocationPhases[2]+=allocations.load()-before;before=allocations.load();renderer.draw(false);allocationPhases[3]+=allocations.load()-before;}}catch(...){counting=false;throw;}counting=false;if(allocations)std::cerr<<"Reader retained frame allocations update/upload/present/draw="<<allocationPhases[0]<<'/'<<allocationPhases[1]<<'/'<<allocationPhases[2]<<'/'<<allocationPhases[3]<<'\n';check(allocations==0,"120 steady changing Reader tilt frames allocate no owner storage");check(raster.stats().rasterizations==beforeRaster.rasterizations&&raster.stats().textLayoutsCreated==beforeRaster.textLayoutsCreated&&renderer.stats().textureUploads==beforeGPU.textureUploads&&renderer.stats().meshUploads==beforeGPU.meshUploads&&renderer.stats().nativeGroupRenders==beforeGPU.nativeGroupRenders&&provider->renders==beforeRenders,"Root tilt/opacity never shapes, repaints, decodes, uploads mesh/pixel resources or recomposites Reader content");
    // Use actual toolbar button dispatch after a cropped detail has arrived;
    // direct Scene zoom alone would miss a stale-detail bug in perform().
    frame(time+.2);provider->illustration=true;state.setLayout({376,334},false);queue.drain();frame(time+.2);click(234,400);check(preview.nextWakeTime().has_value(),"Actual zoom button schedules the one shared detail deadline");preview.deadline(time+=.13);queue.drain();frame(time+.01);const auto sampleBlue=[&]{const auto p=point(200,200);const auto image=renderer.readback();const auto offset=static_cast<std::size_t>(p.y)*image.rowBytes+static_cast<std::size_t>(p.x)*4;return std::array{image.pixels[offset],image.pixels[offset+1],image.pixels[offset+2]};};check(sampleBlue()[0]>250&&sampleBlue()[2]<5,"Actual button detail completion publishes the synthetic cropped image");const auto buttonUploads=renderer.stats().textureUploads;const auto buttonRasters=raster.stats();const auto buttonDetails=provider->details;click(234,400);frame(time+.01);check(sampleBlue()[2]>250&&provider->details==buttonDetails&&renderer.stats().textureUploads==buttonUploads&&raster.stats().rasterizations==buttonRasters.rasterizations&&raster.stats().textLayoutsCreated==buttonRasters.textLayoutsCreated,"Plus button changes zoom immediately before any new detail completion without reuploading full pixels or rebuilding controls");preview.deadline(time+=.13);queue.drain();frame(time+.01);check(sampleBlue()[0]>250,"Latest higher zoom accepts only its tagged detail");click(165,400);frame(time+.01);check(sampleBlue()[2]>250,"Minus button also discards an obsolete crop immediately");preview.deadline(time+=.13);queue.drain();frame(time+.01);check(sampleBlue()[0]>250,"Lower zoom can install its own current detail");click(200,400);frame(time+.01);check(sampleBlue()[2]>250&&!preview.nextWakeTime(),"Reset button immediately restores the full page and clears detail scheduling");
    // Return to the same projection before input; a stale-plane test would
    // otherwise blame correctly transformed controls for fixture coordinates.
    frame(time+.2);click(40,20);click(30,60);action=preview.takeImportAction();check(action&&preview.importRequestCurrent(action->generation),"Second tagged import exists before leaving module");settings.module=core::Module::power;modules.select(core::Module::power,time+=.2);preview.update({},settings,modules.sample(time+.03).presentation,1,time+.03);time+=.03;check(!state.active()&&!preview.covers(scrollPoint)&&!preview.receiveImport(action->generation,book(30),time),"Leaving Reader disables input and rejects stale picker completion immediately");preview.upload(renderer);composition.present(renderer);queue.drain();check(preview.nextWakeTime()&&*preview.nextWakeTime()>=time,"Outgoing pixel release uses the shared scheduler's bounded deadline");
    preview.update({},settings,modules.sample(time+.2).presentation,1,time+.2);preview.upload(renderer);composition.setEntries(renderer,preview.entries());composition.present(renderer);check(preview.deadline(time+.4),"Source .35 second departure deadline releases cached page artwork");preview.update({},settings,modules.sample(time+.5).presentation,1,time+.5);preview.upload(renderer);composition.setEntries(renderer,preview.entries());composition.present(renderer);check(preview.entries().empty()&&!preview.requiresFrames(time+.5)&&provider->opened.empty(),"Settled departure leaves no module entries, decode document or frame demand");preview.collected(renderer);preview.release(renderer);composition.detach(renderer);check(renderer.stats().textures==0&&renderer.stats().meshes==0&&!IsWindowVisible(w.hwnd),"One composition safely retires all Reader resources and the fixture remains hidden");renderer.reset();
}
}
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==2,"Pass shared shader to hidden Reader owner fixture");run(argv[1]);CoUninitialize();std::cout<<"PASS "<<checks<<" Reader preview checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
