#ifdef _WIN32
#include "tools/reader_preview.hpp"
#include "native/reader_owner.hpp"
#include "native/module_scene.hpp"
#include "core/data/file_io.hpp"
#include <windows.h>
#include <objbase.h>
#include <winrt/base.h>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <condition_variable>
#include <mutex>
#include <chrono>
namespace {
using namespace endfield;namespace gpu=native;namespace mod=modules;namespace fs=std::filesystem;unsigned checks{};
void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(s);}
struct Temp{fs::path root=fs::temp_directory_path()/("endfield-reader-continuity-"+ehud::data::makeUUID());Temp(){fs::create_directory(root);}~Temp(){std::error_code e;fs::remove_all(root,e);}};
struct Window{HWND hwnd{};Window(){hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,L"STATIC",L"Owned real Reader continuity fixture",WS_POPUP,0,0,1280,800,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Only hidden fixture HWND exists");}~Window(){if(hwnd)DestroyWindow(hwnd);}};
mod::ReaderBook reference(const fs::path&p){const auto s=p.u8string();return mod::windowsReaderReference(ehud::data::makeUUID(),std::string(reinterpret_cast<const char*>(s.data()),s.size()),"Unvalidated fixture");}
void settle(app::UtilityExecutor&e,gpu::ReaderOwner&o){for(unsigned n=0;n<100;++n){e.waitIdle();e.drain();o.queueCapacityAvailable();if(!o.state().busy()&&!o.importBusy())return;}throw std::runtime_error("Real Reader FIFO did not settle");}
struct Movement{int shift{};double mean{};};
Movement compare(const gpu::Readback&a,const gpu::Readback&b,core::Point origin){Movement best{0,std::numeric_limits<double>::infinity()};for(int shift=-80;shift<=80;++shift){double error{};std::size_t count{};for(int y=85;y<295;y+=3)for(int x=26;x<348;x+=8){const auto ax=static_cast<int>(std::lround(origin.x+x)),ay=static_cast<int>(std::lround(origin.y+y+shift)),by=static_cast<int>(std::lround(origin.y+y));if(ay<0||by<0||ax<0||ay>=static_cast<int>(a.height)||by>=static_cast<int>(b.height)||ax>=static_cast<int>(a.width))continue;const auto first=std::size_t(ay)*a.rowBytes+std::size_t(ax)*4,second=std::size_t(by)*b.rowBytes+std::size_t(ax)*4;for(unsigned k=0;k<3;++k){error+=std::abs(int(a.pixels[first+k])-int(b.pixels[second+k]));++count;}}const double score=count?error/double(count):1e30;if(score<best.mean-.000001||(std::abs(score-best.mean)<=.000001&&std::abs(shift)<std::abs(best.shift))){best={shift,score};}}return best;}
struct PixelDifference{unsigned maximum{};double mean{};};
PixelDifference sameViewport(const gpu::Readback&a,const gpu::Readback&b,core::Point origin){PixelDifference out;std::size_t count{};for(int y=4;y<330;++y)for(int x=8;x<368;++x){const auto px=static_cast<int>(std::lround(origin.x+x)),py=static_cast<int>(std::lround(origin.y+y));const auto first=std::size_t(py)*a.rowBytes+std::size_t(px)*4,second=std::size_t(py)*b.rowBytes+std::size_t(px)*4;for(unsigned k=0;k<3;++k){const unsigned error=static_cast<unsigned>(std::abs(int(a.pixels[first+k])-int(b.pixels[second+k])));out.maximum=std::max(out.maximum,error);out.mean+=error;++count;}}out.mean/=double(count);return out;}
// A fixture-owned job delays this shared FIFO, as a long paragraph/persistence
// job can. It never changes the provider or waits for an owner callback. Its
// RAII release runs before executor shutdown even when an assertion fails.
struct QueueHold {
 struct Gate{std::mutex mutex;std::condition_variable wake;bool entered{},released{};};
 std::shared_ptr<Gate>gate=std::make_shared<Gate>();app::UtilityExecutor*executor;app::UtilityExecutor::Route route;
 explicit QueueHold(app::UtilityExecutor&e):executor(&e),route(e.makeRoute()){auto state=gate;check(e.submit(route,[state]{std::unique_lock lock(state->mutex);state->entered=true;state->wake.notify_all();state->wake.wait(lock,[&]{return state->released;});},[](auto error){if(error)std::rethrow_exception(error);}),"Owned shared FIFO delay is accepted");std::unique_lock lock(gate->mutex);const bool entered=gate->wake.wait_for(lock,std::chrono::seconds(5),[&]{return gate->entered;});if(!entered){gate->released=true;gate->wake.notify_all();}check(entered,"Owned FIFO delay starts with a bounded fixture wait");}
 void release(){std::lock_guard lock(gate->mutex);gate->released=true;gate->wake.notify_all();}
 ~QueueHold(){release();executor->invalidate(route,false);}
};
void run(const fs::path&shader,const fs::path&fonts){Temp temp;Window window;gpu::Renderer renderer;renderer.initialize(window.hwnd,1280,800,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});renderer.setCamera(gpu::layerViewportProjection(1280,800));gpu::LayerRasterizer raster(fonts);app::UtilityExecutor utility([]{});gpu::ReaderOwner*pointer{};
 const auto path=temp.root/"owned-long.txt";{std::ofstream file(path,std::ios::binary);for(unsigned n=0;n<2200;++n){char row[256];std::snprintf(row,sizeof(row),"ROW %06u  %08x  original native layout follows this retained line.\n",n,n*2654435761u);file<<row;}check(bool(file),"Owned TXT fixture writes only its temporary directory");}
 gpu::ReaderOwner owner(temp.root/"Reader",utility,raster.retainedFontResources(),[&](auto,auto book,std::exception_ptr e){if(e)std::rethrow_exception(e);check(book.has_value()&&pointer->state().addValidated(std::move(*book)),"Native import validates only the owned reference");});pointer=&owner;
 tools::ReaderPreviewOptions options;options.raster.pixelsPerPoint=1;options.newID=[] {return ehud::data::makeUUID();};tools::ReaderPreview preview(owner.state(),raster,std::move(options));preview.resize({1280,800,96,1,1280,800});core::source::DesktopChromeSettings settings;settings.viewport={0,0,1280,800};settings.module=core::Module::reader;core::ModulePresentation modules(core::Module::reader);gpu::LayerComposition composition;double time{};
 const auto frame=[&](double t){time=t;preview.update({},settings,modules.sample(t).presentation,1,t);preview.upload(renderer);composition.setEntries(renderer,preview.entries());composition.present(renderer);renderer.draw(false);preview.collected(renderer);};
 frame(0);settle(utility,owner);auto prefs=owner.state().library().preferences;prefs.fontSize=10;prefs.lineSpacing=2;prefs.margin=16;owner.state().setPreferences(prefs);settle(utility,owner);owner.import(1,reference(path));settle(utility,owner);frame(1);check(owner.state().current()&&owner.state().current()->next&&!owner.state().current()->illustration,"Real long TXT opens through native owner/provider");
 gpu::LayerScene geometry(raster);geometry.load(mod::ReaderJson::Object{{"bounds",mod::ReaderJson::Array{0,0,400,440}},{"children",mod::ReaderJson::Array{}}},{});gpu::NativeModuleSurface surface(geometry,core::Module::reader);surface.update({},settings,modules.sample(time).presentation.current,1);const auto plane=core::Projection::viewport(gpu::layerViewportProjection(1280,800)*surface.pose().contentWorld,1280,800);const auto origin=plane.project({12,48}),wheelPoint=plane.project({200,200});check(origin&&wheelPoint,"Real fixture uses source module projection");
 std::int64_t previousCharacter=owner.state().current()->location.character;unsigned crossings{};auto previous=renderer.readback();int largest{},sameTimeLargest{};double largestError{};
 for(unsigned tick=0;tick<36;++tick){const double input=time+.02;check(preview.wheel({wheelPoint->x,wheelPoint->y,-1,false,0,3},input),"Normal three-line wheel input is owned");for(unsigned step=0;step<=8;++step){const double t=input+step*.016;frame(t);const auto before=renderer.readback();const auto motion=compare(previous,before,*origin);largest=std::max(largest,std::abs(motion.shift));largestError=std::max(largestError,motion.mean);if(std::abs(motion.shift)>40)std::cerr<<"Unexpected TXT movement tick="<<tick<<" step="<<step<<" shift="<<motion.shift<<" mean="<<motion.mean<<" character="<<owner.state().current()->location.character<<'\n';previous=before;
 // Real accepted save/render completions can coalesce between paints. The
 // same presentation time must not reposition already-visible native text.
 settle(utility,owner);frame(t);auto after=renderer.readback();const auto completion=compare(before,after,*origin);sameTimeLargest=std::max(sameTimeLargest,std::abs(completion.shift));if(completion.shift||completion.mean>.1)std::cerr<<"Native completion movement tick="<<tick<<" step="<<step<<" shift="<<completion.shift<<" mean="<<completion.mean<<" character="<<owner.state().current()->location.character<<'\n';previous=std::move(after);const auto character=owner.state().current()->location.character;if(character!=previousCharacter){++crossings;previousCharacter=character;}}
 }
 std::cout<<"Native TXT ordinary-wheel continuity: crossings="<<crossings<<" maximum16msShift="<<largest<<" sameTimeCompletionShift="<<sameTimeLargest<<" maximumCorrelationError="<<largestError<<'\n';check(crossings>=3,"Ordinary wheel stress crosses multiple actual TXT pagination boundaries");check(largest<=40,"Native text never jumps a page during one normal-wheel animation frame");check(sameTimeLargest==0,"Same-time native completion never jumps already-visible retained text");
 // Unlike short Latin rows, this paragraph forces native line breaking and
 // fallback shaping across several pages. All content is synthetic and owned.
 const auto chinese=temp.root/"owned-chinese-paragraphs.txt";{std::ofstream file(chinese,std::ios::binary);const auto phrase=u8"这是用于连续滚动测试的中文段落，保留原始行距与字形。中文输入与分页不应让内容突然跳动。🌙 ";for(unsigned section=0;section<100;++section){file<<"SECTION "<<section<<" ";for(unsigned n=0;n<48;++n)file<<reinterpret_cast<const char*>(phrase);file<<"\n";}check(bool(file),"Long CJK paragraphs stay inside the owned temporary fixture");}
 owner.import(2,reference(chinese));settle(utility,owner);frame(time+.2);check(owner.state().current()&&owner.state().current()->location.character==0,"Dense native CJK test starts at its own first page");
 int burstLargest{};unsigned burstCrossings{},backwardCrossings{};double completionMean{};unsigned completionMax{};std::int64_t burstCharacter=owner.state().current()->location.character;previous=renderer.readback();
 const auto observeAnchor=[&]{const auto character=owner.state().current()->location.character;if(character!=burstCharacter){++burstCrossings;if(character<burstCharacter)++backwardCrossings;burstCharacter=character;}};
 const auto completeTrajectory=[&]{for(unsigned step=0;step<300&&(preview.requiresFrames(time)||owner.state().busy());++step){frame(time+.016);if(step%6==0){const auto before=renderer.readback();settle(utility,owner);frame(time);const auto difference=sameViewport(before,renderer.readback(),*origin);completionMean=std::max(completionMean,difference.mean);completionMax=std::max(completionMax,difference.maximum);}observeAnchor();}frame(time+.016);previous=renderer.readback();if(preview.requiresFrames(time)||owner.state().busy()){const auto stalled=preview.scrollSnapshot();std::cerr<<"Unsettled CJK trajectory time="<<time<<" character="<<owner.state().current()->location.character<<" pending="<<stalled.pendingDirection<<" deferred="<<stalled.deferred<<" targetOffset="<<stalled.targetOffset<<" displayedY="<<stalled.scene.displayed[0].y<<" origin="<<stalled.scene.pageOrigin<<" duration="<<stalled.scene.animationDuration<<" start="<<stalled.scene.animationStart<<" ready="<<stalled.scene.ready[0]<<stalled.scene.ready[1]<<stalled.scene.ready[2]<<" busy="<<owner.state().busy()<<'\n';}check(!preview.requiresFrames(time)&&!owner.state().busy(),"Finite real CJK trajectory settles before reversing direction");};
 for(unsigned tick=0;tick<40;++tick){if(tick==20){completeTrajectory();for(unsigned n=0;n<100&&burstCrossings<5;++n){check(preview.wheel({wheelPoint->x,wheelPoint->y,-1,false,0,3},time+.02),"Ordinary native setup reaches enough pages for a multi-page reverse");frame(time+.12);settle(utility,owner);frame(time);observeAnchor();}completeTrajectory();check(burstCrossings>=5,"Reverse stress begins after at least five real forward page crossings");}const double input=time+.016;const unsigned burst=2+tick%4;const double direction=tick<20?-1:1;for(unsigned event=0;event<burst;++event)check(preview.wheel({wheelPoint->x,wheelPoint->y,direction,false,0,3},input),"Coalesced ordinary wheel bursts remain owned");for(unsigned step=0;step<6;++step){const double t=input+step*.016;frame(t);auto before=renderer.readback();const auto motion=compare(previous,before,*origin);burstLargest=std::max(burstLargest,std::abs(motion.shift));previous=before;if(step==5){settle(utility,owner);frame(t);auto after=renderer.readback();const auto difference=sameViewport(before,after,*origin);completionMean=std::max(completionMean,difference.mean);completionMax=std::max(completionMax,difference.maximum);if(difference.mean>.05)std::cerr<<"Dense completion changed viewport tick="<<tick<<" mean="<<difference.mean<<" max="<<difference.maximum<<" target="<<preview.scrollSnapshot().targetOffset<<" deferred="<<preview.scrollSnapshot().deferred<<'\n';previous=std::move(after);}observeAnchor();}}
 completeTrajectory();
 std::cout<<"Native CJK bursts: crossings="<<burstCrossings<<" backwardCrossings="<<backwardCrossings<<" maximum16msShift="<<burstLargest<<" sameTimeMax="<<completionMax<<" sameTimeMean="<<completionMean<<'\n';check(burstCrossings>=3&&backwardCrossings>=4,"Dense forward/reverse inputs cross more than three actual long-paragraph pages backward");check(completionMean<=.05,"Coalesced provider completion preserves the same-time visible text crop");
 // One ordinary wheel event per 16 ms, with an unavailable second neighbor.
 // Missing work is a content boundary, never a future scrolling debt. Once
 // the last actual .10s input curve ends, completion cannot restart motion.
 owner.state().jump(mod::ReaderLocation{});settle(utility,owner);frame(time+.2);previous=renderer.readback();int heldLargest{};double largestDeferred{};bool held{};
 {QueueHold queue(utility);for(unsigned tick=0;tick<42;++tick){const double t=time+.016;check(preview.wheel({wheelPoint->x,wheelPoint->y,-1,false,0,3},t),"Normal wheel during owned FIFO work stays responsive");frame(t);auto next=renderer.readback();heldLargest=std::max(heldLargest,std::abs(compare(previous,next,*origin).shift));previous=std::move(next);const auto snapshot=preview.scrollSnapshot();largestDeferred=std::max(largestDeferred,std::abs(snapshot.deferred));held=held||snapshot.deferred!=0;}
 // Let the latest real wheel curve finish while the FIFO is still blocked.
 // This separates a late content publication from valid ongoing input motion.
 for(unsigned step=0;step<8;++step)frame(time+.016);
 const auto stopped=renderer.readback();const auto stoppedSnapshot=preview.scrollSnapshot();const double stoppedAbsolute=stoppedSnapshot.scene.pageOrigin-stoppedSnapshot.scene.displayed[0].y;
 check(!preview.requiresFrames(time)&&stoppedSnapshot.scene.animationDuration<=.100001,"Stopped wheel releases animation demand even before the unavailable page finishes");
 queue.release();settle(utility,owner);frame(time);const auto difference=sameViewport(stopped,renderer.readback(),*origin);check(difference.mean<=.05,"Delayed real provider publication keeps the stopped viewport pixels");
 for(unsigned step=0;step<12;++step){frame(time+.016);const auto still=preview.scrollSnapshot();check(std::abs(still.scene.pageOrigin-still.scene.displayed[0].y-stoppedAbsolute)<.000001,"Late provider completion with no new wheel cannot start any new movement");check(sameViewport(stopped,renderer.readback(),*origin).mean<=.05,"Stopped document retains the full same-time native text crop");}
 check(!preview.requiresFrames(time)&&preview.scrollSnapshot().deferred==0&&preview.scrollSnapshot().pendingDirection==0,"Late content clears the unavailable-input marker without replay or frame demand");
 // A fresh small wheel input responds immediately and finishes on the original
 // .10s curve, regardless of how many old events arrived during unavailable IO.
 const auto freshStart=time+.016;check(preview.wheel({wheelPoint->x,wheelPoint->y,-1,false,0,3},freshStart),"Fresh input after late content is accepted");frame(freshStart);check(sameViewport(stopped,renderer.readback(),*origin).mean<=.05,"Fresh ordinary wheel begins at the same presentation pixels");frame(freshStart+.016);auto fresh=preview.scrollSnapshot();const double freshAbsolute=fresh.scene.pageOrigin-fresh.scene.displayed[0].y;check(freshAbsolute>stoppedAbsolute&&freshAbsolute-stoppedAbsolute<=36.000001,"Fresh ordinary wheel responds within one frame without old queued excess");check(fresh.scene.animationDuration<=.100001,"Fresh ordinary wheel keeps the source .10s duration");frame(freshStart+.112);check(!preview.requiresFrames(time),"Fresh wheel stops promptly after the last input");
 const auto forwardSnapshot=preview.scrollSnapshot();const double forwardAbsolute=forwardSnapshot.scene.pageOrigin-forwardSnapshot.scene.displayed[0].y;const auto forwardImage=renderer.readback();const auto reverseStart=time+.016;check(preview.wheel({wheelPoint->x,wheelPoint->y,1,false,0,3},reverseStart),"Opposite ordinary wheel is accepted without old backlog");frame(reverseStart);check(sameViewport(forwardImage,renderer.readback(),*origin).mean<=.05,"Opposite wheel starts from the visible document crop");frame(reverseStart+.016);const auto reversed=preview.scrollSnapshot();const double reverseAbsolute=reversed.scene.pageOrigin-reversed.scene.displayed[0].y;check(reverseAbsolute<forwardAbsolute&&forwardAbsolute-reverseAbsolute<=36.000001,"Opposite input reverses visible geometry on its next frame");frame(reverseStart+.112);check(!preview.requiresFrames(time),"Opposite input also settles without automatic scrolling");
 }
 std::cout<<"Native CJK FIFO direct response: latestUnavailableStep="<<largestDeferred<<" ordinaryMaximum16msShift="<<heldLargest<<'\n';check(held&&largestDeferred>0&&largestDeferred<=36.000001,"Owned long-paragraph delay retains only the latest ordinary step, never an accumulated page backlog");
 composition.detach(renderer);preview.release(renderer);check(owner.shutdown(),"Real provider saves/retires on its borrowed MTA before renderer/COM");renderer.reset();
}
}
int wmain(int argc,wchar_t**argv){const auto h=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(h)&&argc==3,"Pass shader and bundled fonts to owned Reader continuity fixture");run(argv[1],argv[2]);winrt::clear_factory_cache();CoFreeUnusedLibrariesEx(INFINITE,0);CoUninitialize();std::cout<<"PASS "<<checks<<" real Reader continuity checks\n";return 0;}catch(const std::exception&e){if(SUCCEEDED(h)){winrt::clear_factory_cache();CoFreeUnusedLibrariesEx(INFINITE,0);CoUninitialize();}std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(){return 0;}
#endif
