#include "modules/reader_text.hpp"
#include "third_party/zlib/zlib.h"
#include <algorithm>
#include <array>
#include <iostream>
#include <cstring>
using namespace endfield::modules;
namespace {
int checks{};void check(bool b,const char*m){++checks;if(!b)throw std::runtime_error(m);}template<class F>void rejects(F f,const char*m){bool failed=false;try{f();}catch(const ReaderError&){failed=true;}check(failed,m);}
class Bytes:public ReaderBytes {public:std::vector<std::uint8_t>value;explicit Bytes(std::vector<std::uint8_t>b):value(std::move(b)){}std::uint64_t size()const override{return value.size();}void read(std::uint64_t offset,std::span<std::uint8_t>b)override{check(offset<=value.size()&&b.size()<=value.size()-offset,"Read is confined opened bytes");std::copy_n(value.data()+offset,b.size(),b.data());}};
void u16(std::vector<std::uint8_t>&out,unsigned n){out.push_back(static_cast<std::uint8_t>(n));out.push_back(static_cast<std::uint8_t>(n>>8));}void u32(std::vector<std::uint8_t>&out,std::uint32_t n){u16(out,n);u16(out,n>>16);}void put(std::vector<std::uint8_t>&out,std::string_view text){out.insert(out.end(),text.begin(),text.end());}
struct Entry {std::string name;std::vector<std::uint8_t>text;bool deflated{};std::optional<std::vector<std::uint8_t>>compressed{};};
std::vector<std::uint8_t>storedDeflate(std::span<const std::uint8_t>text){std::vector<std::uint8_t>out;std::size_t n{};do{const auto count=std::min<std::size_t>(65535,text.size()-n);const bool final=n+count==text.size();out.push_back(final?1:0);u16(out,static_cast<unsigned>(count));u16(out,static_cast<unsigned>(count)^0xffff);out.insert(out.end(),text.begin()+static_cast<std::ptrdiff_t>(n),text.begin()+static_cast<std::ptrdiff_t>(n+count));n+=count;}while(n<text.size());return out;}
std::vector<std::uint8_t>archive(const std::vector<Entry>&entries){std::vector<std::uint8_t>out,central;for(const auto&e:entries){const auto offset=out.size();const auto body=e.compressed?*e.compressed:e.deflated?storedDeflate(e.text):e.text;const auto crc=static_cast<std::uint32_t>(crc32(0,e.text.data(),static_cast<uInt>(e.text.size())));u32(out,0x04034b50);u16(out,20);u16(out,0);u16(out,e.deflated?8:0);u32(out,0);u32(out,crc);u32(out,static_cast<std::uint32_t>(body.size()));u32(out,static_cast<std::uint32_t>(e.text.size()));u16(out,static_cast<unsigned>(e.name.size()));u16(out,0);put(out,e.name);out.insert(out.end(),body.begin(),body.end());u32(central,0x02014b50);u16(central,20);u16(central,20);u16(central,0);u16(central,e.deflated?8:0);u32(central,0);u32(central,crc);u32(central,static_cast<std::uint32_t>(body.size()));u32(central,static_cast<std::uint32_t>(e.text.size()));u16(central,static_cast<unsigned>(e.name.size()));u16(central,0);u16(central,0);u16(central,0);u16(central,0);u32(central,0);u32(central,static_cast<std::uint32_t>(offset));put(central,e.name);}const auto offset=out.size();out.insert(out.end(),central.begin(),central.end());u32(out,0x06054b50);u32(out,0);u16(out,static_cast<unsigned>(entries.size()));u16(out,static_cast<unsigned>(entries.size()));u32(out,static_cast<std::uint32_t>(central.size()));u32(out,static_cast<std::uint32_t>(offset));u16(out,0);return out;}
std::vector<std::uint8_t>bytes(std::string_view text){return {text.begin(),text.end()};}
void zip(){
    // Immutable synthetic raw streams exercise the two Huffman modes too;
    // production ships inflate/CRC only, not the encoder used to author them.
    auto unhex=[](std::string_view h){std::vector<std::uint8_t>b;for(std::size_t n=0;n<h.size();n+=2){auto d=[](char c){return unsigned(c<='9'?c-'0':c-'a'+10);};b.push_back(static_cast<std::uint8_t>(d(h[n])*16+d(h[n+1])));}return b;};
    std::string fixed;for(unsigned n=0;n<40;++n)fixed+="Original Reader raw Huffman test. ";const auto fixedBytes=unhex("f32fca4ccfcc4bcc51084a4d4c492d52284a2c57f0284d4bcb4dcc5328492d2ed153f01f5531aa6254c5a88a511544a80000");ReaderZIP fixedZip(std::make_shared<Bytes>(archive({{"fixed",bytes(fixed),true,fixedBytes}})));check(fixedZip.data("fixed")==bytes(fixed),"Fixed-Huffman stream decodes exact original bytes");
    std::string dynamic;for(unsigned n=0;n<80;++n){dynamic+=std::string(100,'A');for(unsigned k=0;k<10;++k)dynamic+="BC";for(unsigned k=0;k<5;++k)dynamic+="DEFG";}const auto dynamicBytes=unhex("edce311600100c44c1b385e0fe37d24b8d66f6bfed27e2fe5aafe598ebfc030a0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0bcb57cb06");ReaderZIP dynamicZip(std::make_shared<Bytes>(archive({{"dynamic",bytes(dynamic),true,dynamicBytes}})));check(dynamicZip.data("dynamic")==bytes(dynamic),"Dynamic-Huffman stream decodes exact original bytes");
    for(const auto size:{0u,1u,65535u,65536u,131072u}){std::vector<std::uint8_t>content(size);for(std::size_t n=0;n<size;++n)content[n]=static_cast<std::uint8_t>((n*31)%256);ReaderZIP zip(std::make_shared<Bytes>(archive({{"chapter",content,true}})));check(zip.data("chapter")==content,"Exact raw-deflate output including64KiB boundaries");}
    auto data=archive({{"chapter",bytes("text"),false}});ReaderZIP good(std::make_shared<Bytes>(data));check(good.data("chapter")==bytes("text"),"Stored CRC verified");rejects([&]{good.data("chapter",3);},"Per-entry caller bound");
    auto damaged=data;damaged[30+7]^=1;ReaderZIP damagedZip(std::make_shared<Bytes>(damaged));rejects([&]{damagedZip.data("chapter");},"Actual content CRC mismatch rejected");
    damaged=data;damaged[30]='X';ReaderZIP badName(std::make_shared<Bytes>(damaged));rejects([&]{badName.data("chapter");},"Local and central names agree");
    damaged=data;damaged.push_back(0);rejects([&]{ReaderZIP z(std::make_shared<Bytes>(damaged));},"Trailing bytes fail exact EOCD");
    rejects([&]{ReaderZIP z(std::make_shared<Bytes>(archive({{"../bad",{},false}})));},"Traversal rejected");rejects([&]{ReaderZIP z(std::make_shared<Bytes>(archive({{"a",{},false},{"a",{},false}})));},"Duplicate archive entries rejected");
    damaged=data;const auto central=30+7+4;damaged[central+8]=1;rejects([&]{ReaderZIP z(std::make_shared<Bytes>(damaged));},"Encrypted central flag rejected");
    damaged=data;damaged[central+40]=0;damaged[central+41]=0xa0;rejects([&]{ReaderZIP z(std::make_shared<Bytes>(damaged));},"Unix symlink entry rejected without extraction");
    damaged=data;const std::uint32_t excessive=1000000;for(unsigned n=0;n<4;++n)damaged[central+24+n]=static_cast<std::uint8_t>(excessive>>(8*n));rejects([&]{ReaderZIP z(std::make_shared<Bytes>(damaged));},"Declared compression expansion ratio rejected before allocation");
    bool cancelled=false;try{ReaderZIP z(std::make_shared<Bytes>(data),[]{return true;});}catch(const ReaderCancelled&){cancelled=true;}check(cancelled,"Explicit cooperative cancellation");
    for(auto name:{"../a","/a","a/./b","a\\b","a:b"})check(!ReaderZIP::safePath(name),"Unsafe path rejected");check(!ReaderZIP::safePath(std::string("a\0b",3)),"NUL path rejected");check(ReaderZIP::safePath("images//book.png"),"Original harmless empty path segments retained");
    check(ReaderZIP::resolve("../images/a%20b.png#anchor","OPS/Text/chapter.xhtml")=="OPS/images/a b.png","Decoded path confinement and fragment");for(auto href:{"../../../bad","http://example.org/a","//remote/a","a%00b","a?query","a%ZZ"})rejects([&]{ReaderZIP::resolve(href,"OPS/Text/chapter");},"Unsafe resolution rejected");
}
void text(){const std::u16string value=u"Latin 中文 한국어 \U0001F642 e\u0301";check(readerUTF8(readerUTF8(value))==value,"Unicode scalar roundtrip");rejects([]{readerUTF8(std::string("\xc0\x80",2));},"Overlong UTF8 rejected");rejects([]{readerUTF8(std::u16string(1,0xd800));},"Unpaired UTF16 rejected");check(readerUTF16(std::array<std::uint8_t,6>{0xff,0xfe,'A',0,0x2d,0x4e})==u"A中","BOM little endian");check(readerUTF16(std::array<std::uint8_t,6>{0xfe,0xff,0,'A',0x4e,0x2d})==u"A中","BOM big endian");rejects([]{readerUTF16(std::array<std::uint8_t,3>{0xff,0xfe,0});},"Odd UTF16 byte rejected");check(readerTrim(u"\u2003\u2028 text \u00a0")==u"text","Foundation whitespace/newlines trim");
    std::u16string longText(16383,u'A');longText+=u"\U0001F642Z";check(readerChunk(longText,0).size()==16383,"Page chunk never splits surrogate pair");
    auto first=std::make_shared<const std::vector<ReaderBlock>>(std::vector<ReaderBlock>{{ReaderBlock::Kind::text,u"abc\nparagraph \U0001F642 tail",{}},{ReaderBlock::Kind::image,{},"a.png"}});auto second=std::make_shared<const std::vector<ReaderBlock>>(std::vector<ReaderBlock>{{ReaderBlock::Kind::text,u"second chapter",{}}});ReaderBlocks blocks=[&](std::size_t index){return index?second:first;};
    check(readerNormalized({0,0,15,{ReaderJson::Object{}}},2,blocks).character==14,"Location backs away from low surrogate");check(readerNormalized({10,10,900,{ReaderJson::Object{}}},2,blocks).section==1,"Section/block/text clamped");check(readerLocationAt(.2,2,blocks).character==4,"Progress seek nearby paragraph boundary");check(readerAdvance({0,1,0,{ReaderJson::Object{}}},2,2)==ReaderLocation{1,0,0,{ReaderJson::Object{}}},"Advance across chapter");check(!readerAdvance({1,0,0,{ReaderJson::Object{}}},1,2),"No next after final block");check(readerPrevious({1,0,0,{ReaderJson::Object{}}},2,blocks,4,[](auto s){return double(s.size());})==ReaderLocation{0,1,0,{ReaderJson::Object{}}},"Previous illustration across chapter");check(!readerPrevious({0,0,0,{ReaderJson::Object{}}},2,blocks,4,[](auto s){return double(s.size());}),"No predecessor before start");auto prev=readerPrevious({0,0,10,{ReaderJson::Object{}}},2,blocks,4,[](auto s){return double(s.size());});check(prev&&prev->character==6,"Original predecessor suffix binary search");
}
void epub(){auto file=std::make_shared<Bytes>(archive({{"mimetype",bytes(" application/epub+zip\n"),false},{"META-INF/container.xml",bytes("container"),false},{"OPS/book.opf",bytes("package"),false},{"OPS/a.xhtml",bytes("a"),false},{"OPS/b.xhtml",bytes("b"),false},{"OPS/c.xhtml",bytes("c"),false}}));unsigned parses{};ReaderXMLParser parser=[&](auto b,const ReaderCancel&){++parses;const std::string text(reinterpret_cast<const char*>(b.data()),b.size());ReaderXMLDocument result;if(text=="container")result.rootFile="OPS/book.opf";else if(text=="package"){result.title=u" \u3000 Title \n";for(auto name:{"a","b","c"}){result.spine.push_back(name);result.manifest.emplace(name,ReaderXMLDocument::Item{std::string(name)+".xhtml","application/xhtml+xml"});}}else{result.blocks.push_back({ReaderBlock::Kind::text,readerUTF8(text),{}});result.blocks.push_back({ReaderBlock::Kind::image,{},"../cover.png"});}return result;};ReaderEPUB epub(file,parser);check(epub.title()==u"Title"&&epub.spine().size()==3,"Original package title/spine");auto a=epub.blocks(0);check((*a)[1].image=="cover.png","Image href resolved relative chapter");const auto before=parses;check(epub.blocks(0)==a&&parses==before,"Retained two chapter FIFO cache hit");epub.blocks(1);epub.blocks(2);check(epub.blocks(0)!=a&&parses==before+3,"Original two chapter FIFO eviction");check((*a)[0].text==u"a","Borrowed chapter survives cache replacement");}
}
int main(){try{zip();text();epub();std::cout<<"Reader format core passed "<<checks<<" checks\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<" after "<<checks<<" checks\n";return 1;}}
