#ifdef _WIN32
#include "native/reader_scene.hpp"
#include <windows.h>
#include <objbase.h>
#include <atomic>
#include <cstdlib>
#include <iostream>
#include <new>
#include <chrono>
#include <cmath>
namespace {std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {using namespace endfield;namespace gpu=native;namespace mod=modules;unsigned checks{};void check(bool b,const char*m){++checks;if(!b)throw std::runtime_error(m);}struct Window{HWND hwnd{};Window(){hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,L"STATIC",L"Owned Reader scene fixture",WS_POPUP,0,0,400,440,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Reader fixture stays hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);}};
std::shared_ptr<const mod::ReaderPagePixels>pixels(std::array<unsigned char,4>c){auto p=std::make_shared<mod::ReaderPagePixels>();p->width=p->height=2;p->format=mod::ReaderPagePixels::Format::bgra8Premultiplied;for(unsigned n=0;n<4;++n)p->bytes.insert(p->bytes.end(),c.begin(),c.end());return p;}
std::shared_ptr<const mod::ReaderPagePixels>striped(unsigned channel){auto p=std::make_shared<mod::ReaderPagePixels>();p->width=8;p->height=334;p->format=mod::ReaderPagePixels::Format::bgra8Premultiplied;p->bytes.reserve(8*334*4);for(unsigned y=0;y<334;++y)for(unsigned x=0;x<8;++x){std::array<unsigned char,4>c{0,0,0,255};c[channel]=255;c[(channel+1)%3]=static_cast<unsigned char>((y*17+x*23)%200);p->bytes.insert(p->bytes.end(),c.begin(),c.end());}return p;}
std::array<unsigned char,4>pixel(const gpu::Readback&r,unsigned x,unsigned y){const auto n=std::size_t(y)*r.rowBytes+x*4;return {r.pixels[n],r.pixels[n+1],r.pixels[n+2],r.pixels[n+3]};}
void run(const std::filesystem::path&shader){Window w;gpu::Renderer renderer;renderer.initialize(w.hwnd,400,440,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});renderer.setCamera(gpu::layerViewportProjection(400,440));gpu::LayerRasterizer raster;gpu::LayerRasterOptions o;o.pixelsPerPoint=1;gpu::NativeReaderScene scene(raster,o);gpu::LayerComposition composition;mod::ReaderViewport viewport;viewport.setActive(true,0);mod::ReaderCanvasInput input;input.hasPage=true;input.next=true;input.progress=.2;input.bookTitle="Reader fixture";mod::ReaderLocation a{},b{0,0,10,{mod::ReaderJson::Object{}}};std::vector<mod::ReaderPage>pages{{a,b,{},.2,"First",false,pixels({0,0,255,255})},{b,{},a,.5,"Next",false,pixels({0,255,0,255})}};
    viewport.setPage(mod::ReaderPageAnchor{"fixture",a,true,false,false,.2},0);scene.syncContent(input,pages,&pages[0],{},viewport,0);scene.updatePose({},1,viewport,0,false);scene.upload(renderer);std::array entries{scene.entry()};composition.setEntries(renderer,entries);composition.present(renderer);renderer.draw(false);check(pixel(renderer.readback(),200,150)==std::array<unsigned char,4>{0,0,255,255},"Current immutable BGRA page is correctly converted and inserted before controls");
    viewport.scroll({200,200},0,100,1,mod::ReaderGesturePhase::none,false,true);scene.updatePose({},1,viewport,1,false);scene.upload(renderer);composition.present(renderer);renderer.draw(false);const auto r=renderer.readback();check(pixel(r,200,100)==std::array<unsigned char,4>{0,0,255,255}&&pixel(r,200,350)==std::array<unsigned char,4>{0,255,0,255},"Vertical cached neighbors move inside original rounded viewport without decoding");check(pixel(r,200,400)!=std::array<unsigned char,4>{0,255,0,255},"Page quad never escapes viewport into controls");
    const auto beforeR=raster.stats();const auto beforeG=renderer.stats();allocations=0;counting=true;try{for(unsigned n=0;n<120;++n){scene.updatePose(core::Matrix4::rotation(0,n*.00001,0),.7f,viewport,2+n/60.,false);scene.upload(renderer);composition.present(renderer);renderer.draw(false);}}catch(...){counting=false;throw;}counting=false;check(allocations==0,"120 retained Reader pose/pixel-binding updates allocate no CPU storage");check(raster.stats().rasterizations==beforeR.rasterizations&&raster.stats().textLayoutsCreated==beforeR.textLayoutsCreated&&renderer.stats().textureUploads==beforeG.textureUploads&&renderer.stats().meshUploads==beforeG.meshUploads&&renderer.stats().nativeGroupRenders==beforeG.nativeGroupRenders,"Tilt/root alpha reuses page pixels, glyphs, meshes and completed local group");
    viewport.pointerDown({200,400});viewport.pointerDragged({55,400},5);scene.updatePose({},1,viewport,5,false);scene.upload(renderer);composition.present(renderer);renderer.draw(false);check(viewport.displayedProgress()==0&&scene.stats().pixelUploads==2,"Zero progress uses a retained bounded numeric mask, no zero-area upload");viewport.cancelInteraction();
    auto bad=pages[0];auto malformed=std::make_shared<mod::ReaderPagePixels>(*bad.pixels);malformed->bytes.pop_back();bad.pixels=malformed;const auto stats=scene.stats();bool rejected{};try{scene.syncContent(input,{},&bad,{},viewport,6);}catch(const std::invalid_argument&){rejected=true;}check(rejected&&scene.stats().contentUpdates==stats.contentUpdates,"Malformed external pixels reject before replacing previous artwork");
    scene.clearArtwork();scene.updatePose({},1,viewport,7,false);scene.upload(renderer);composition.present(renderer);renderer.draw(false);check(scene.stats().pixelUploads==2&&renderer.stats().textures<beforeG.textures,"Original artwork release clears resident page textures after group references retire");composition.detach(renderer);check(scene.release(renderer)&&renderer.stats().textures==0&&renderer.stats().meshes==0,"Reader releases only its detached grouped resources");renderer.reset();
}
void motion(const std::filesystem::path&shader){Window w;gpu::Renderer renderer;renderer.initialize(w.hwnd,400,440,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});renderer.setCamera(gpu::layerViewportProjection(400,440));gpu::LayerRasterizer raster;gpu::LayerRasterOptions o;o.pixelsPerPoint=1;gpu::NativeReaderScene scene(raster,o);gpu::LayerComposition composition;mod::ReaderViewport viewport;viewport.setActive(true,0);mod::ReaderCanvasInput input;input.hasPage=true;input.next=true;input.bookTitle="Retained motion";mod::ReaderLocation a{},b{0,0,10,{mod::ReaderJson::Object{}}};std::vector<mod::ReaderPage>pages{{a,b,{},.2,"First",false,pixels({0,0,255,255})},{b,{},a,.5,"Next",false,pixels({0,255,0,255})}};viewport.setPage(mod::ReaderPageAnchor{"motion",a,true,false,false,.2},0);scene.syncContent(input,pages,&pages[0],{},viewport,0);
    const auto frame=[&](double t){scene.updatePose({},1,viewport,t,false);scene.upload(renderer);composition.present(renderer);renderer.draw(false);};scene.updatePose({},1,viewport,0,false);scene.upload(renderer);std::array entries{scene.entry()};composition.setEntries(renderer,entries);composition.present(renderer);renderer.draw(false);
    viewport.scroll({200,200},0,100,1,mod::ReaderGesturePhase::none,false,false);frame(1);frame(1.04);const auto before=renderer.readback();viewport.scroll({200,200},0,50,1.04,mod::ReaderGesturePhase::none,false,false);frame(1.04);check(renderer.readback().pixels==before.pixels,"Repeated wheel easing retargets from the sampled presentation without a one-frame jump");frame(1.08);const auto middle=renderer.readback();unsigned beforeBoundary=382,middleBoundary=382;for(unsigned y=49;y<381;++y){if(pixel(before,200,y)[1]>250&&beforeBoundary==382)beforeBoundary=y;if(pixel(middle,200,y)[1]>250&&middleBoundary==382)middleBoundary=y;}check(middleBoundary<beforeBoundary&&middleBoundary>200,"Repeated wheel progresses smoothly toward its newer target");frame(1.2);
    viewport.scroll({200,200},0,200,2,mod::ReaderGesturePhase::none,false,false);check(viewport.takeNavigation()->step==1,"Stress wheel crosses one retained neighbor boundary");viewport.setPage(mod::ReaderPageAnchor{"motion",b,false,true,false,.5},2);input.progress=.5;input.next=false;input.previous=true;scene.syncContent(input,pages,&pages[1],{},viewport,2);frame(2);check(pixel(renderer.readback(),200,80)[2]>250&&scene.requiresFrames(2),"Recycled next page retains the outgoing visible portion and continues the existing wheel trajectory");frame(2.11);check(pixel(renderer.readback(),200,80)[1]>250&&!scene.requiresFrames(2.11),"Continuous vertical crossing settles without a horizontal page transition or reverse bounce");
    viewport.setPage(mod::ReaderPageAnchor{"image",a,true,false,true,.2},3);input.illustration=true;input.next=true;input.previous=false;pages[0].illustration=true;scene.syncContent(input,pages,&pages[0],{},viewport,3);viewport.zoomBy(2,{200,215},3.1);scene.syncPages(pages,&pages[0],{},viewport,3.1);frame(3.1);mod::ReaderPage detailed=pages[0];detailed.pixels=pixels({255,0,0,255});std::optional<mod::ReaderDetail>detail=mod::ReaderDetail{viewport.imageView(),detailed};scene.syncPages(pages,&pages[0],detail,viewport,3.3);frame(3.3);check(pixel(renderer.readback(),200,200)[0]>250,"Matching detail uses its fixed viewport-sized crop");const auto uploaded=scene.stats().pixelUploads;const auto fonts=raster.stats();viewport.zoomBy(1.3,{200,215},3.4);scene.syncPages(pages,&pages[0],detail,viewport,3.4);frame(3.4);check(pixel(renderer.readback(),200,200)[2]>250&&scene.stats().pixelUploads==uploaded,"A new zoom immediately restores the retained full page without stale detail or another base texture upload");
    const auto warmGPU=renderer.stats();const auto started=std::chrono::steady_clock::now();allocations=0;counting=true;try{for(unsigned n=0;n<120;++n){const double t=4+n/240.;viewport.zoomBy(n%2?1/1.02:1.02,{120,130},t);viewport.pointerDown({200,200});viewport.pointerDragged({200+double(n%5),200-double(n%7)},t);viewport.pointerUp(t);scene.syncPages(pages,&pages[0],{},viewport,t);frame(t);}}catch(...){counting=false;throw;}counting=false;const auto elapsed=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-started).count();check(allocations==0&&scene.stats().pixelUploads==uploaded&&raster.stats().rasterizations==fonts.rasterizations&&raster.stats().textLayoutsCreated==fonts.textLayoutsCreated&&renderer.stats().textureUploads==warmGPU.textureUploads&&renderer.stats().meshUploads==warmGPU.meshUploads,"120 zoom/pan input frames reuse full-page pixels and controls with no CPU allocation, shaping, raster or texture uploads");check(!viewport.takeDetailRequest(4.49)&&viewport.takeDetailRequest(4+119./240+.12).has_value(),"Continuous zoom/pan leaves one newest debounced detail, never one per frame");std::cout<<"Reader synthetic WARP zoom/pan 120frames ms="<<elapsed<<" (includes offscreen draws, no live PDF/EPUB timing)\n";composition.detach(renderer);check(scene.release(renderer)&&renderer.stats().textures==0&&renderer.stats().meshes==0,"Motion/detail resources retire completely after one shared publication detaches");renderer.reset();
}
void continuity(const std::filesystem::path&shader){
 Window w;gpu::Renderer renderer;renderer.initialize(w.hwnd,400,440,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});renderer.setCamera(gpu::layerViewportProjection(400,440));gpu::LayerRasterizer raster;gpu::LayerRasterOptions o;o.pixelsPerPoint=1;gpu::NativeReaderScene scene(raster,o);gpu::LayerComposition composition;mod::ReaderViewport v;v.setActive(true,0);mod::ReaderCanvasInput input;input.hasPage=true;input.next=input.previous=true;input.bookTitle="Continuous seam";
 mod::ReaderLocation a{1},b{2},c{3};std::vector<mod::ReaderPage>pages{{a,b,{},.2,"A",true,striped(2)},{b,c,a,.4,"B",true,striped(1)},{c,{},b,.6,"C",true,striped(0)}};
 const auto bind=[&](unsigned n,double t,bool ready=true){auto&p=pages[n];v.setPage(mod::ReaderPageAnchor{"seam",p.location,bool(p.next),bool(p.previous),p.illustration,p.progress,ready,true},t);input.progress=p.progress;input.next=bool(p.next);input.previous=bool(p.previous);input.illustration=true;scene.syncContent(input,pages,&p,{},v,t);};
 const auto frame=[&](double t){scene.updatePose({},1,v,t,false);scene.upload(renderer);composition.present(renderer);renderer.draw(false);};
 const auto sameViewport=[&](const gpu::Readback&x,const gpu::Readback&y){for(unsigned row=50;row<380;++row)for(unsigned col=16;col<384;++col){const auto p=pixel(x,col,row),q=pixel(y,col,row);for(unsigned k=0;k<4;++k)if(std::abs(int(p[k])-int(q[k]))>2)return false;}return true;};
 const auto boundary=[&](const gpu::Readback&image){for(unsigned y=49;y<381;++y)if(pixel(image,200,y)[1]>250)return y;return 382u;};
 bind(0,0);scene.updatePose({},1,v,0,false);scene.upload(renderer);std::array entries{scene.entry()};composition.setEntries(renderer,entries);composition.present(renderer);renderer.draw(false);
 v.scroll({200,200},0,300,1,mod::ReaderGesturePhase::none,false,false);frame(1);frame(1.04);auto old=renderer.readback();const auto uploaded=scene.stats().pixelUploads;v.scroll({200,200},0,40,1.04,mod::ReaderGesturePhase::none,false,false);check(v.takeNavigation()->step==1,"Ordinary wheel queues one continuous next-page seam");bind(1,1.04);frame(1.04);check(sameViewport(old,renderer.readback()),"Forward anchor rebase keeps every sampled viewport pixel at the same timestamp");check(scene.stats().pixelUploads==uploaded+1,"Crossing reuses current/neighbor GPU pixels and uploads only the newly added third page");frame(1.08);check(boundary(renderer.readback())<boundary(old),"Forward crossing keeps the same monotonic visual direction");old=renderer.readback();v.scroll({200,200},0,-40,1.08,mod::ReaderGesturePhase::none,false,false);check(v.takeNavigation()->step==-1,"Reverse wheel queues the same continuous seam in reverse");bind(0,1.08);frame(1.08);check(sameViewport(old,renderer.readback()),"Reverse anchor rebase also keeps actual viewport pixels continuous mid-animation");frame(1.2);check(!scene.requiresFrames(1.2),"Continuous forward/reverse wheel settles without an idle frame loop");
 // A cropped detail and the full page have the same red image here; crossing
 // must restore the existing full-page texture without changing the feature
 // at the outgoing/neighbor boundary.
 pages[0].pixels=pixels({0,0,255,255});pages[1].pixels=pixels({0,255,0,255});pages[2].pixels=pixels({255,0,0,255});
 v.setPage(mod::ReaderPageAnchor{"zoom-seam",a,true,false,true,.2},2);v.zoomBy(2,{200,215},2);scene.syncContent(input,pages,&pages[0],{},v,2);frame(2);v.scroll({200,200},0,480,2.1);scene.syncPages(pages,&pages[0],{},v,2.1);frame(2.1);auto detailPage=pages[0];detailPage.pixels=pixels({0,0,255,255});std::optional<mod::ReaderDetail>detail=mod::ReaderDetail{v.imageView(),detailPage};scene.syncPages(pages,&pages[0],detail,v,2.2);frame(2.2);old=renderer.readback();const auto zoomUploads=scene.stats().pixelUploads;v.scroll({200,200},0,40,2.2,mod::ReaderGesturePhase::none,false,false);check(v.takeNavigation()->step==1,"Zoomed ordinary wheel crosses the full zoomed height");v.setPage(mod::ReaderPageAnchor{"zoom-seam",b,true,true,true,.4},2.2);scene.syncContent(input,pages,&pages[1],{},v,2.2);frame(2.2);check(sameViewport(old,renderer.readback()),"Zoomed cropped-detail to full-page crossing preserves the actual feature boundary");check(scene.stats().pixelUploads==zoomUploads+1,"Zoomed crossing preserves both existing full-page GPU textures too");frame(2.31);check(!scene.requiresFrames(2.31),"Zoomed seamless scroll has finite demand only");
 // Delayed provider result: availability cannot replay input after the wheel
 // stops. A subsequent actual event reveals it on the original .10s curve.
 v.setPage(mod::ReaderPageAnchor{"waiting-seam",b,true,true,false,.4,false,true},3);std::array onlyCurrent{pages[1]};input.illustration=false;scene.syncContent(input,onlyCurrent,&onlyCurrent[0],{},v,3);frame(3);old=renderer.readback();v.scroll({200,200},0,80,3.1,mod::ReaderGesturePhase::none,false,false);scene.syncPages(onlyCurrent,&onlyCurrent[0],{},v,3.1);frame(3.1);check(sameViewport(old,renderer.readback())&&!scene.requiresFrames(3.1),"Unready next page holds opaque current pixels without moving into a blank slot or polling");v.setPage(mod::ReaderPageAnchor{"waiting-seam",b,true,true,false,.4,true,true},3.2);scene.syncPages(pages,&pages[1],{},v,3.2);frame(3.2);check(sameViewport(old,renderer.readback()),"Deferred neighbor completion retains the exact stopped pixel position");frame(3.25);check(sameViewport(old,renderer.readback())&&!scene.requiresFrames(3.25),"Availability alone never starts automatic scrolling after stopped input");v.scroll({200,200},0,80,3.3,mod::ReaderGesturePhase::none,false,false);frame(3.3);check(sameViewport(old,renderer.readback()),"Fresh ordinary input starts from the unchanged visible crop");frame(3.35);check(pixel(renderer.readback(),200,360)[0]>250&&pixel(renderer.readback(),200,70)[1]>250,"Only fresh input reveals the ready page naturally below the current page");frame(3.41);check(!scene.requiresFrames(3.41)&&scene.stats().pixelUploads<=zoomUploads+6,"Fresh input settles promptly with a fixed bounded page texture set");
 // Reverse navigation targets the current top edge while the previous page is
 // cached. The gate must allow y=0: its clamped target can never become positive.
 v.scroll({200,200},0,-100,3.5,mod::ReaderGesturePhase::none,false,false);check(v.takeNavigation()->step==-1,"Actual reverse input stages one cached previous-page navigation");frame(3.5);check(!scene.canAdvanceVertical(-1,3.5),"Reverse rebase retains the next page while it is still visible below the current page");frame(3.61);old=renderer.readback();check(scene.canAdvanceVertical(-1,3.61),"Cached reverse rebase becomes ready at the reachable current top edge");v.setPage(mod::ReaderPageAnchor{"waiting-seam",a,true,false,false,.2,true,true},3.61);scene.syncPages(pages,&pages[0],{},v,3.61);frame(3.61);check(sameViewport(old,renderer.readback()),"Top-edge reverse anchor replacement retains the same actual viewport pixels");composition.detach(renderer);check(scene.release(renderer)&&renderer.stats().textures==0&&renderer.stats().meshes==0,"Seam/remainder resources retire completely through the existing shared publisher");renderer.reset();
}

}
int wmain(int argc,wchar_t**argv){auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==2,"Reader scene fixture requires shader");run(argv[1]);motion(argv[1]);continuity(argv[1]);CoUninitialize();std::cout<<"Reader scene passed "<<checks<<" checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(hr))CoUninitialize();std::cerr<<e.what()<<" after "<<checks<<" checks\n";return 1;}}
#endif
