#ifdef _WIN32
#include "native/reader_scene.hpp"
#include <windows.h>
#include <objbase.h>
#include <atomic>
#include <cstdlib>
#include <iostream>
#include <new>
#include <chrono>
#include <cmath>
namespace {std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};}
void*operator new(std::size_t n){if(counting)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace {using namespace endfield;namespace gpu=native;namespace mod=modules;unsigned checks{};void check(bool b,const char*m){++checks;if(!b)throw std::runtime_error(m);}struct Window{HWND hwnd{};Window(){hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,L"STATIC",L"Owned Reader scene fixture",WS_POPUP,0,0,400,440,nullptr,nullptr,GetModuleHandleW(nullptr),nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Reader fixture stays hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);}};
std::shared_ptr<const mod::ReaderPagePixels>pixels(std::array<unsigned char,4>c){auto p=std::make_shared<mod::ReaderPagePixels>();p->width=p->height=2;p->format=mod::ReaderPagePixels::Format::bgra8Premultiplied;for(unsigned n=0;n<4;++n)p->bytes.insert(p->bytes.end(),c.begin(),c.end());return p;}
std::array<unsigned char,4>pixel(const gpu::Readback&r,unsigned x,unsigned y){const auto n=std::size_t(y)*r.rowBytes+x*4;return {r.pixels[n],r.pixels[n+1],r.pixels[n+2],r.pixels[n+3]};}
void run(const std::filesystem::path&shader){Window w;gpu::Renderer renderer;renderer.initialize(w.hwnd,400,440,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});renderer.setCamera(gpu::layerViewportProjection(400,440));gpu::LayerRasterizer raster;gpu::LayerRasterOptions o;o.pixelsPerPoint=1;gpu::NativeReaderScene scene(raster,o);gpu::LayerComposition composition;mod::ReaderViewport viewport;viewport.setActive(true,0);mod::ReaderCanvasInput input;input.hasPage=true;input.next=true;input.progress=.2;input.bookTitle="Reader fixture";mod::ReaderLocation a{},b{0,0,10,{mod::ReaderJson::Object{}}};std::vector<mod::ReaderPage>pages{{a,b,{},.2,"First",false,pixels({0,0,255,255})},{b,{},a,.5,"Next",false,pixels({0,255,0,255})}};
    viewport.setPage(mod::ReaderPageAnchor{"fixture",a,true,false,false,.2},0);scene.syncContent(input,pages,&pages[0],{},viewport,0);scene.updatePose({},1,viewport,0,false);scene.upload(renderer);std::array entries{scene.entry()};composition.setEntries(renderer,entries);composition.present(renderer);renderer.draw(false);check(pixel(renderer.readback(),200,150)==std::array<unsigned char,4>{0,0,255,255},"Current immutable BGRA page is correctly converted and inserted before controls");
    viewport.scroll({200,200},0,100,1,mod::ReaderGesturePhase::none,false,true);scene.updatePose({},1,viewport,1,false);scene.upload(renderer);composition.present(renderer);renderer.draw(false);const auto r=renderer.readback();check(pixel(r,200,100)==std::array<unsigned char,4>{0,0,255,255}&&pixel(r,200,350)==std::array<unsigned char,4>{0,255,0,255},"Vertical cached neighbors move inside original rounded viewport without decoding");check(pixel(r,200,400)!=std::array<unsigned char,4>{0,255,0,255},"Page quad never escapes viewport into controls");
    const auto beforeR=raster.stats();const auto beforeG=renderer.stats();allocations=0;counting=true;try{for(unsigned n=0;n<120;++n){scene.updatePose(core::Matrix4::rotation(0,n*.00001,0),.7f,viewport,2+n/60.,false);scene.upload(renderer);composition.present(renderer);renderer.draw(false);}}catch(...){counting=false;throw;}counting=false;check(allocations==0,"120 retained Reader pose/pixel-binding updates allocate no CPU storage");check(raster.stats().rasterizations==beforeR.rasterizations&&raster.stats().textLayoutsCreated==beforeR.textLayoutsCreated&&renderer.stats().textureUploads==beforeG.textureUploads&&renderer.stats().meshUploads==beforeG.meshUploads&&renderer.stats().nativeGroupRenders==beforeG.nativeGroupRenders,"Tilt/root alpha reuses page pixels, glyphs, meshes and completed local group");
    viewport.pointerDown({200,400});viewport.pointerDragged({55,400},5);scene.updatePose({},1,viewport,5,false);scene.upload(renderer);composition.present(renderer);renderer.draw(false);check(viewport.displayedProgress()==0&&scene.stats().pixelUploads==2,"Zero progress uses a retained bounded numeric mask, no zero-area upload");viewport.cancelInteraction();
    auto bad=pages[0];auto malformed=std::make_shared<mod::ReaderPagePixels>(*bad.pixels);malformed->bytes.pop_back();bad.pixels=malformed;const auto stats=scene.stats();bool rejected{};try{scene.syncContent(input,{},&bad,{},viewport,6);}catch(const std::invalid_argument&){rejected=true;}check(rejected&&scene.stats().contentUpdates==stats.contentUpdates,"Malformed external pixels reject before replacing previous artwork");
    scene.clearArtwork();scene.updatePose({},1,viewport,7,false);scene.upload(renderer);composition.present(renderer);renderer.draw(false);check(scene.stats().pixelUploads==2&&renderer.stats().textures<beforeG.textures,"Original artwork release clears resident page textures after group references retire");composition.detach(renderer);check(scene.release(renderer)&&renderer.stats().textures==0&&renderer.stats().meshes==0,"Reader releases only its detached grouped resources");renderer.reset();
}
void motion(const std::filesystem::path&shader){Window w;gpu::Renderer renderer;renderer.initialize(w.hwnd,400,440,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});renderer.setCamera(gpu::layerViewportProjection(400,440));gpu::LayerRasterizer raster;gpu::LayerRasterOptions o;o.pixelsPerPoint=1;gpu::NativeReaderScene scene(raster,o);gpu::LayerComposition composition;mod::ReaderViewport viewport;viewport.setActive(true,0);mod::ReaderCanvasInput input;input.hasPage=true;input.next=true;input.bookTitle="Retained motion";mod::ReaderLocation a{},b{0,0,10,{mod::ReaderJson::Object{}}};std::vector<mod::ReaderPage>pages{{a,b,{},.2,"First",false,pixels({0,0,255,255})},{b,{},a,.5,"Next",false,pixels({0,255,0,255})}};viewport.setPage(mod::ReaderPageAnchor{"motion",a,true,false,false,.2},0);scene.syncContent(input,pages,&pages[0],{},viewport,0);
    const auto frame=[&](double t){scene.updatePose({},1,viewport,t,false);scene.upload(renderer);composition.present(renderer);renderer.draw(false);};scene.updatePose({},1,viewport,0,false);scene.upload(renderer);std::array entries{scene.entry()};composition.setEntries(renderer,entries);composition.present(renderer);renderer.draw(false);
    viewport.scroll({200,200},0,100,1,mod::ReaderGesturePhase::none,false,false);frame(1);frame(1.04);const auto before=renderer.readback();viewport.scroll({200,200},0,50,1.04,mod::ReaderGesturePhase::none,false,false);frame(1.04);check(renderer.readback().pixels==before.pixels,"Repeated wheel easing retargets from the sampled presentation without a one-frame jump");frame(1.08);const auto middle=renderer.readback();unsigned beforeBoundary=382,middleBoundary=382;for(unsigned y=49;y<381;++y){if(pixel(before,200,y)[1]>250&&beforeBoundary==382)beforeBoundary=y;if(pixel(middle,200,y)[1]>250&&middleBoundary==382)middleBoundary=y;}check(middleBoundary<beforeBoundary&&middleBoundary>200,"Repeated wheel progresses smoothly toward its newer target");frame(1.2);
    viewport.scroll({200,200},0,200,2,mod::ReaderGesturePhase::none,false,false);check(viewport.takeNavigation()->step==1,"Stress wheel crosses one retained neighbor boundary");viewport.setPage(mod::ReaderPageAnchor{"motion",b,false,true,false,.5},2);input.progress=.5;input.next=false;input.previous=true;scene.syncContent(input,pages,&pages[1],{},viewport,2);frame(2);check(pixel(renderer.readback(),200,80)[1]>250&&!scene.requiresFrames(2),"Recycled next page publishes its residual offset directly without a page-switch bounce");
    viewport.setPage(mod::ReaderPageAnchor{"image",a,true,false,true,.2},3);input.illustration=true;input.next=true;input.previous=false;pages[0].illustration=true;scene.syncContent(input,pages,&pages[0],{},viewport,3);viewport.zoomBy(2,{200,215},3.1);scene.syncPages(pages,&pages[0],{},viewport,3.1);frame(3.1);mod::ReaderPage detailed=pages[0];detailed.pixels=pixels({255,0,0,255});std::optional<mod::ReaderDetail>detail=mod::ReaderDetail{viewport.imageView(),detailed};scene.syncPages(pages,&pages[0],detail,viewport,3.3);frame(3.3);check(pixel(renderer.readback(),200,200)[0]>250,"Matching detail uses its fixed viewport-sized crop");const auto uploaded=scene.stats().pixelUploads;const auto fonts=raster.stats();viewport.zoomBy(1.3,{200,215},3.4);scene.syncPages(pages,&pages[0],detail,viewport,3.4);frame(3.4);check(pixel(renderer.readback(),200,200)[2]>250&&scene.stats().pixelUploads==uploaded,"A new zoom immediately restores the retained full page without stale detail or another base texture upload");
    const auto warmGPU=renderer.stats();const auto started=std::chrono::steady_clock::now();allocations=0;counting=true;try{for(unsigned n=0;n<120;++n){const double t=4+n/240.;viewport.zoomBy(n%2?1/1.02:1.02,{120,130},t);viewport.pointerDown({200,200});viewport.pointerDragged({200+double(n%5),200-double(n%7)},t);viewport.pointerUp(t);scene.syncPages(pages,&pages[0],{},viewport,t);frame(t);}}catch(...){counting=false;throw;}counting=false;const auto elapsed=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-started).count();check(allocations==0&&scene.stats().pixelUploads==uploaded&&raster.stats().rasterizations==fonts.rasterizations&&raster.stats().textLayoutsCreated==fonts.textLayoutsCreated&&renderer.stats().textureUploads==warmGPU.textureUploads&&renderer.stats().meshUploads==warmGPU.meshUploads,"120 zoom/pan input frames reuse full-page pixels and controls with no CPU allocation, shaping, raster or texture uploads");check(!viewport.takeDetailRequest(4.49)&&viewport.takeDetailRequest(4+119./240+.12).has_value(),"Continuous zoom/pan leaves one newest debounced detail, never one per frame");std::cout<<"Reader synthetic WARP zoom/pan 120frames ms="<<elapsed<<" (includes offscreen draws, no live PDF/EPUB timing)\n";composition.detach(renderer);check(scene.release(renderer)&&renderer.stats().textures==0&&renderer.stats().meshes==0,"Motion/detail resources retire completely after one shared publication detaches");renderer.reset();
}
}
int wmain(int argc,wchar_t**argv){auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==2,"Reader scene fixture requires shader");run(argv[1]);motion(argv[1]);CoUninitialize();std::cout<<"Reader scene passed "<<checks<<" checks\n";return 0;}catch(const std::exception&e){counting=false;if(SUCCEEDED(hr))CoUninitialize();std::cerr<<e.what()<<" after "<<checks<<" checks\n";return 1;}}
#endif
