#ifdef _WIN32
#include "native/reader_owner.hpp"
#include "native/layer_raster.hpp"
#include "core/data/file_io.hpp"
#include <windows.h>
#include <objbase.h>
#include <filesystem>
#include <fstream>
#include <iostream>
namespace {
using namespace endfield;namespace gpu=native;namespace mod=modules;namespace fs=std::filesystem;unsigned checks{};
void check(bool value,const char*message){++checks;if(!value)throw std::runtime_error(message);}
struct Temp{fs::path root=fs::temp_directory_path()/("endfield-reader-owner-"+ehud::data::makeUUID());Temp(){fs::create_directory(root);}~Temp(){std::error_code e;fs::remove_all(root,e);}};
void write(const fs::path&p,std::string_view s){std::ofstream out(p,std::ios::binary);out.write(s.data(),static_cast<std::streamsize>(s.size()));check(bool(out),"Write only a newly owned fixture file");}
mod::ReaderBook reference(const fs::path&p){const auto raw=p.u8string();return mod::windowsReaderReference(ehud::data::makeUUID(),std::string(reinterpret_cast<const char*>(raw.data()),raw.size()),"Unvalidated filename");}
void settle(app::UtilityExecutor&e,gpu::ReaderOwner&o){for(unsigned n=0;n<100;++n){e.waitIdle();e.drain();o.queueCapacityAvailable();if(!o.state().busy()&&!o.importBusy())return;}throw std::runtime_error("Reader owned queue failed to settle");}
bool writable(const fs::path&p){const auto h=CreateFileW(p.c_str(),GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_DELETE,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if(h==INVALID_HANDLE_VALUE)return false;CloseHandle(h);return true;}
void run(const gpu::LayerFontResources&sc,const gpu::LayerFontResources&kr){Temp fixture;const auto directory=fixture.root/"Reader",path=fixture.root/L"合成 Reader.txt";std::string body;for(unsigned n=0;n<200;++n)body+="Synthetic paragraph 中文 한글 🙂.\n";write(path,body);app::UtilityExecutor executor([]{});{gpu::ReaderOwner unused(fixture.root/"Unused",executor,sc);}check(!executor.stats().started&&!fs::exists(fixture.root/"Unused"),"Destroying never-active owner does not start an unnecessary release worker or create data");unsigned changes{},imports{};gpu::ReaderOwner*target{};std::optional<mod::ReaderBook>validated;
    auto owner=std::make_unique<gpu::ReaderOwner>(directory,executor,sc,[&](auto generation,auto book,std::exception_ptr error){check(generation==10&&!error&&book.has_value(),"Tagged validation completes on owner without substituting an invalid document");++imports;validated=book;check(target&&target->state().addValidated(std::move(*book)),"Caller selects validated book only through the source structural transaction");},[&]{++changes;});target=owner.get();
    check(!fs::exists(directory)&&!executor.stats().started,"Reader owner construction creates no directory, reads no book and starts no worker");owner->state().setActive(true);settle(executor,*owner);check(owner->state().loaded()&&owner->state().library().preferences.fontName=="System"&&!fs::exists(directory),"Fresh library keeps automatic SC/KR sentinel without an empty write");
    auto lease=std::make_shared<int>(1);std::weak_ptr<int>weak=lease;owner->import(10,reference(path),lease);lease.reset();executor.waitIdle();check(!weak.expired(),"Shelf lease survives accepted validation until owner completion drains");settle(executor,*owner);check(imports==1&&validated&&validated->title=="合成 Reader"&&weak.expired()&&owner->state().current()&&changes>0,"Actual temporary TXT validation/open/raster uses one borrowed worker and releases its lease");owner->import(11,reference(path));owner->cancelImport();settle(executor,*owner);check(imports==1&&!owner->importBusy(),"Canceled same-worker validation cannot deliver a stale reference or generation");check(!writable(path),"Real provider retains only its owned read-only fixture handle while open");check(*ehud::data::detail::readFile(path,65536)==body,"Reader never rewrites or copies the referenced fixture book");
    const auto first=owner->state().current()->pixels;owner->setFonts(kr);settle(executor,*owner);check(owner->state().library().preferences.fontName=="System"&&owner->state().current()->pixels!=first,"Automatic font-language event replaces pages without persisting a face override");const auto accepted=executor.stats().accepted;owner->setFonts(kr);check(executor.stats().accepted==accepted,"Identical retained font generation queues no duplicate render");auto prefs=owner->state().library().preferences;prefs.fontName="Noto Sans SC";check(owner->state().setPreferences(prefs),"Explicit user Reader family remains a source preference transaction");settle(executor,*owner);owner->setFonts(sc);settle(executor,*owner);owner->setFonts(kr);settle(executor,*owner);check(owner->state().library().preferences.fontName=="Noto Sans SC","Language events preserve explicitly selected Reader typography");
    check(owner->state().toggleBookmark(ehud::data::makeUUID()),"Bookmark submits only through confirmed source state");check(owner->flush()&&!owner->state().hasUnsavedChanges()&&owner->state().book()->bookmarks.size()==1,"Explicit flush drains accepted writes and preserves original bookmarks");
    const auto libraryPath=directory/"library.json";const auto durable=*ehud::data::detail::readFile(libraryPath,mod::readerMaximumLibraryBytes);auto external=mod::ReaderJson::parse(durable);external["syntheticExternalEdit"]=true;write(libraryPath,external.encode());check(owner->state().toggleBookmark(ehud::data::makeUUID()),"A conflicting storage writer leaves the full latest transaction available");check(!owner->shutdown()&&!owner->closed()&&owner->state().hasUnsavedChanges()&&owner->state().active(),"Failed quit preserves Reader state/data for visible retry instead of closing or guessing success");check(mod::ReaderJson::parse(*ehud::data::detail::readFile(libraryPath,mod::readerMaximumLibraryBytes))["syntheticExternalEdit"].boolean(),"Conflict leaves external owned bytes untouched");write(libraryPath,durable);check(owner->flush()&&!owner->state().hasUnsavedChanges(),"Explicit retry commits retained latest bookmark after fixture conflict is resolved");check(owner->shutdown()&&owner->closed()&&writable(path),"Shutdown releases real native document on the same MTA before UI-side destruction");owner.reset();target=nullptr;
    const auto other=executor.makeRoute();unsigned unrelated{};check(executor.submit(other,[]{},[&](auto error){check(!error,"Sibling shared task remains usable");++unrelated;}),"Reader shutdown never stops the app-owned utility executor");executor.waitIdle();executor.drain();check(unrelated==1,"Sibling route still delivers after Reader shutdown");executor.invalidate(other);
    {gpu::ReaderOwner reopened(directory,executor,sc);reopened.state().setActive(true);settle(executor,reopened);check(reopened.state().current()&&reopened.state().book()->bookmarks.empty()&&reopened.state().library().preferences.fontName=="Noto Sans SC","Reopen preserves committed bookmark toggle and explicit font after failed-save retry");check(reopened.shutdown(),"Reopened actual provider shuts down safely");}
    // No explicit shutdown: terminal teardown must still preserve already
    // accepted immutable writes, invalidate UI callbacks and release the MTA
    // document. An unrelated completed result forces bounded queue backpressure.
    app::UtilityExecutor bounded([]{},1);bool destroyOnChange{};unsigned callbacks{};std::unique_ptr<gpu::ReaderOwner>dying;
    dying=std::make_unique<gpu::ReaderOwner>(directory,bounded,sc,gpu::ReaderImportQueue::Completion{},[&]{++callbacks;if(destroyOnChange)dying.reset();});dying->state().setActive(true);settle(bounded,*dying);const auto route=bounded.makeRoute();bool delivered{};check(bounded.submit(route,[]{},[&](auto){delivered=true;}),"Owned sibling completion fills the same bounded queue");bounded.waitIdle();dying.reset();check(delivered&&writable(path)&&bounded.stats().pending==0&&bounded.stats().running==0,"Destructor makes release capacity by draining owned queue results and leaves no MTA handle");bounded.invalidate(route);
    dying=std::make_unique<gpu::ReaderOwner>(directory,bounded,sc,gpu::ReaderImportQueue::Completion{},[&]{++callbacks;if(destroyOnChange)dying.reset();});dying->state().setActive(true);settle(bounded,*dying);destroyOnChange=true;dying->state().toggleBookmark(ehud::data::makeUUID());check(!dying&&writable(path)&&bounded.stats().pending==0&&bounded.stats().running==0,"Changed callback may destroy the facade while accepted write survives and native resources release");destroyOnChange=false;
    {gpu::ReaderOwner verify(directory,bounded,sc);verify.state().setActive(true);settle(bounded,verify);check(verify.state().book()->bookmarks.size()==1,"Terminal callback teardown retains accepted immutable save even though UI acknowledgment is invalidated");check(verify.shutdown(),"Final provider release precedes shared queue teardown");}
    dying=std::make_unique<gpu::ReaderOwner>(directory,bounded,sc,gpu::ReaderImportQueue::Completion{},[&]{if(destroyOnChange&&dying&&!dying->state().busy())dying.reset();});dying->state().setActive(true);settle(bounded,*dying);destroyOnChange=true;dying->state().toggleBookmark(ehud::data::makeUUID());check(dying!=nullptr,"Busy synchronous save notice cannot prematurely destroy callback fixture");const bool survivedFlush=dying->flush();check(!survivedFlush&&!dying&&writable(path),"Destruction during flushed acknowledgment safely stops the outer barrier after accepted save and same-MTA release");destroyOnChange=false;
    check(callbacks>0&&!fs::exists(fixture.root/"unrequested"),"Synthetic lifecycle never creates unrelated app data or a second worker service");
}
}
int main(int argc,char**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==2,"Pass existing bundled font directory to isolated Reader owner fixture");gpu::LayerFontResources sc,kr;{gpu::LayerRasterizer raster(fs::path(std::u8string(reinterpret_cast<const char8_t*>(argv[1]))));sc=raster.retainedFontResources();raster.setDefaultFontLanguage(gpu::LayerFontLanguage::korean);kr=raster.retainedFontResources();}run(sc,kr);CoUninitialize();std::cout<<"PASS "<<checks<<" Reader owner checks\n";return 0;}catch(const std::exception&e){if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(){return 0;}
#endif
