#include "native/reader_document.hpp"
#include "native/reader_formats.hpp"
#include "native/layer_raster.hpp"
#include "core/data/file_io.hpp"
#include "third_party/zlib/zlib.h"
#ifdef _WIN32
#include <windows.h>
#include <fstream>
#include <iostream>
#include <thread>
#include <cstdio>
#include <algorithm>
#include <array>
namespace {
using namespace endfield::modules;using namespace endfield::native;using J=ReaderJson;namespace fs=std::filesystem;unsigned checks{};
void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}template<class F>void rejects(F f,const char*why){bool failed{};try{f();}catch(const std::exception&){failed=true;}check(failed,why);}void hr(HRESULT code){if(FAILED(code))throw std::runtime_error("Native Reader fixture COM HRESULT");}
std::vector<std::uint8_t>base64(std::string_view text){std::vector<std::uint8_t>out;unsigned bits{},value{};for(const auto c:text){if(c=='=')break;const auto i=std::string_view("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/").find(c);check(i!=std::string_view::npos,"Fixture base64 remains exact");value=(value<<6)|static_cast<unsigned>(i);bits+=6;if(bits>=8){bits-=8;out.push_back(static_cast<std::uint8_t>(value>>bits));}}return out;}
void u16(std::vector<std::uint8_t>&out,unsigned n){out.push_back(static_cast<std::uint8_t>(n));out.push_back(static_cast<std::uint8_t>(n>>8));}void u32(std::vector<std::uint8_t>&out,std::uint32_t n){u16(out,n);u16(out,n>>16);}void append(std::vector<std::uint8_t>&out,std::string_view s){out.insert(out.end(),s.begin(),s.end());}
std::vector<std::uint8_t>zip(const std::vector<std::pair<std::string,std::vector<std::uint8_t>>>&entries){std::vector<std::uint8_t>out,central;for(const auto&[name,data]:entries){const auto offset=out.size();const auto crc=crc32(0,data.data(),static_cast<uInt>(data.size()));u32(out,0x04034b50);u16(out,20);u16(out,0);u16(out,0);u32(out,0);u32(out,static_cast<std::uint32_t>(crc));u32(out,static_cast<std::uint32_t>(data.size()));u32(out,static_cast<std::uint32_t>(data.size()));u16(out,static_cast<unsigned>(name.size()));u16(out,0);append(out,name);out.insert(out.end(),data.begin(),data.end());u32(central,0x02014b50);u16(central,20);u16(central,20);u16(central,0);u16(central,0);u32(central,0);u32(central,static_cast<std::uint32_t>(crc));u32(central,static_cast<std::uint32_t>(data.size()));u32(central,static_cast<std::uint32_t>(data.size()));u16(central,static_cast<unsigned>(name.size()));u16(central,0);u16(central,0);u16(central,0);u16(central,0);u32(central,0);u32(central,static_cast<std::uint32_t>(offset));append(central,name);}const auto start=out.size();out.insert(out.end(),central.begin(),central.end());u32(out,0x06054b50);u32(out,0);u16(out,static_cast<unsigned>(entries.size()));u16(out,static_cast<unsigned>(entries.size()));u32(out,static_cast<std::uint32_t>(central.size()));u32(out,static_cast<std::uint32_t>(start));u16(out,0);return out;}
std::vector<std::uint8_t>bytes(std::string_view s){return {s.begin(),s.end()};}
std::string pdf(){std::string out="%PDF-1.4\n";const std::vector<std::string>objects={"<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R 5 0 R] /Count 2 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 300] /CropBox [0 0 200 300] /Resources << >> /Contents 4 0 R >>","<< /Length 26 >>\nstream\n1 0 0 rg 0 0 200 300 re f\nendstream","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 200] /Resources << >> /Contents 6 0 R >>","<< /Length 26 >>\nstream\n0 0 1 rg 0 0 300 200 re f\nendstream"};std::vector<std::size_t>offsets{0};for(std::size_t n=0;n<objects.size();++n){offsets.push_back(out.size());out+=std::to_string(n+1)+" 0 obj\n"+objects[n]+"\nendobj\n";}const auto xref=out.size();out+="xref\n0 7\n0000000000 65535 f \n";for(std::size_t n=1;n<offsets.size();++n){char row[32];std::snprintf(row,sizeof(row),"%010llu 00000 n \n",static_cast<unsigned long long>(offsets[n]));out+=row;}out+="trailer\n<< /Size 7 /Root 1 0 R >>\nstartxref\n"+std::to_string(xref)+"\n%%EOF\n";return out;}
struct Temp {fs::path path=fs::temp_directory_path()/("endfield-reader-native-"+ehud::data::makeUUID());Temp(){fs::create_directory(path);}~Temp(){std::error_code e;fs::remove_all(path,e);}};
void write(const fs::path&path,std::span<const std::uint8_t>b){std::ofstream file(path,std::ios::binary);file.write(reinterpret_cast<const char*>(b.data()),static_cast<std::streamsize>(b.size()));check(bool(file),"Owned fixture file write");}
ReaderBook reference(const fs::path&path){const auto raw=path.u8string();return windowsReaderReference(ehud::data::makeUUID(),std::string(reinterpret_cast<const char*>(raw.data()),raw.size()),"Fixture");}
J xmlJSON(const ReaderXMLDocument&doc){J::Object manifest;for(const auto&[id,item]:doc.manifest)manifest.emplace(id,J::Object{{"href",item.href},{"type",item.type}});J::Array spine,blocks;for(const auto&s:doc.spine)spine.emplace_back(s);for(const auto&b:doc.blocks)blocks.emplace_back(b.kind==ReaderBlock::Kind::text?J(J::Object{{"text",readerUTF8(b.text)}}):J(J::Object{{"image",b.image}}));return J::Object{{"rootFile",doc.rootFile?J(*doc.rootFile):J{}},{"title",readerUTF8(doc.title)},{"manifest",std::move(manifest)},{"spine",std::move(spine)},{"blocks",std::move(blocks)}};}
void originalXML(const fs::path&path){auto raw=ehud::data::detail::readFile(path,1024*1024);check(bool(raw),"Original parser fixture present");const auto source=J::parse(*raw,1024*1024);check(source["sourceAuthority"].string()=="ca04f142185c7de40acd8523bdb563195d90a1d1","Original Reader source authority pinned");for(const auto&row:source["cases"].array()){const auto data=base64(row["base64"].string());if(row["success"].boolean()){const auto actual=xmlJSON(parseReaderXML(data,{}));if(actual!=row["result"])std::cerr<<"XML oracle mismatch "<<row["name"].string()<<" actual="<<actual.encode()<<'\n';check(actual==row["result"],"Native bounded XML matches unchanged original parser facts");}else rejects([&]{parseReaderXML(data,{});},"Original rejected XML remains rejected");}for(const auto&row:source["txtCases"].array()){const auto data=base64(row["base64"].string());if(row["success"].boolean()){const auto actual=readerUTF8(decodeReaderTXT(data));if(actual!=row["result"]["text"].string())std::cerr<<"TXT oracle mismatch "<<row["name"].string()<<" expected="<<row["result"]["text"].encode()<<" actual="<<J(actual).encode()<<'\n';check(actual==row["result"]["text"].string(),"Native TXT scalar decoding matches unchanged original document, including GB18030 compatibility mappings");}else rejects([&]{decodeReaderTXT(data);},"Original rejected TXT remains rejected");}for(const auto&row:source["whitespace"].array())check(readerWhitespace(static_cast<char16_t>(row["scalar"].integer()))==row["trimmed"].boolean(),"Foundation whitespace set matches original scalars");}
void native(const LayerFontResources&fonts,const LayerFontResources&korean,const fs::path&oracle){check(fonts.locale()=="zh-cn"&&korean.locale()=="ko-kr"&&fonts.fallbackFamily()=="Noto Sans SC"&&korean.fallbackFamily()=="Noto Sans KR","Retained Reader configuration preserves SC/KR families and native locales");originalXML(oracle);check(decodeReaderTXT(bytes("UTF8 中文🙂"))==u"UTF8 中文🙂","TXT strict UTF8");check(decodeReaderTXT(std::array<std::uint8_t,4>{0xd6,0xd0,0xce,0xc4})==u"中文","TXT GB18030 native fallback");check(decodeReaderTXT(std::array<std::uint8_t,4>{0xff,0xfe,'A',0})==u"A","TXT BOM UTF16");rejects([]{decodeReaderTXT(bytes(""));},"Empty TXT rejected");rejects([]{decodeReaderTXT(std::array<std::uint8_t,1>{0x81});},"Truncated GB18030 rejected");rejects([]{decodeReaderTXT(std::array<std::uint8_t,2>{'A',0});},"Embedded NUL rejected");check(readerGraphemePrefix(u"e\u0301\U0001F642Z",2)=="é🙂","Original grapheme prefix keeps complete Unicode clusters");
    Temp fixture;const auto textPath=fixture.path/L"中文 book.txt",epubPath=fixture.path/L"fixture.epub",pdfPath=fixture.path/L"fixture.pdf";std::string body;for(unsigned n=0;n<2000;++n)body+="Reader paragraph 中文🙂 \n";write(textPath,bytes(body));const std::vector<std::uint8_t>image{137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,2,0,0,0,2,8,6,0,0,0,114,182,13,36,0,0,0,23,73,68,65,84,120,156,5,193,1,1,0,0,0,130,32,166,247,220,64,36,161,193,1,61,87,5,124,22,194,63,189,0,0,0,0,73,69,78,68,174,66,96,130};write(epubPath,zip({{"mimetype",bytes("application/epub+zip")},{"META-INF/container.xml",bytes("<container><rootfile full-path='OPS/book.opf'/></container>")},{"OPS/book.opf",bytes("<package><title>EPUB 中文🙂</title><manifest><item id='a' href='a.xhtml' media-type='application/xhtml+xml'/><item id='b' href='b.png' media-type='image/png'/></manifest><spine><itemref idref='a'/><itemref idref='b'/></spine></package>")},{"OPS/a.xhtml",bytes("<html><body><p>Actual XML text.</p></body></html>")},{"OPS/b.png",image}}));write(pdfPath,bytes(pdf()));
    NativeReaderDocument provider(fonts);ReaderPreferences prefs=ReaderPreferences::defaults("Noto Sans SC");provider.open(reference(textPath),{});check(provider.info().sections==1&&provider.info().title=="中文 book","Opened native TXT source title");auto pages=provider.render({}, {},prefs,{376,334},true,{});check(!pages.empty()&&pages.size()<=3&&!pages[0].illustration&&pages[0].next&&pages[0].next->character>0,"Real text pagination returns current and bounded neighbors");check(pages[0].pixels->width==752&&pages[0].pixels->height==668&&pages[0].pixels->bytes.size()==752*668*4,"Original fixed viewport raster budget");const auto cached=provider.render({}, {},prefs,{376,334},true,{});check(cached[0].pixels==pages[0].pixels&&provider.stats().cacheHits>=2&&provider.stats().cachedPages<=3,"Original three-page cache reuses exact bounded pixels");auto automatic=ReaderPreferences::defaults("System");auto autoSC=provider.render({}, {},automatic,{376,334},true,{});check(provider.info().requestedFont=="System"&&provider.info().selectedFont=="Noto Sans SC"&&automatic.fontName=="System","Automatic Reader family uses current SC snapshot without persisting a face override");provider.setFontResources(korean);auto autoKR=provider.render({}, {},automatic,{376,334},true,{});check(provider.info().selectedFont=="Noto Sans KR"&&autoKR[0].pixels!=autoSC[0].pixels&&automatic.fontName=="System","Automatic Reader sentinel follows KR configuration without changing saved choice");provider.render({}, {},prefs,{376,334},true,{});check(provider.info().selectedFont=="Noto Sans SC"&&prefs.fontName=="Noto Sans SC","Explicit Reader family remains selected across app-language change");provider.setFontResources(fonts);auto fallback=prefs;fallback.fontName="Endfield Fixture Missing Family";auto sc=provider.render({}, {},fallback,{376,334},true,{});check(provider.info().requestedFont==fallback.fontName&&provider.info().selectedFont=="Noto Sans SC"&&fallback.fontName=="Endfield Fixture Missing Family","Missing saved face uses bundled default without replacing saved preference");provider.setFontResources(korean);auto kr=provider.render({}, {},fallback,{376,334},true,{});check(provider.info().selectedFont=="Noto Sans KR"&&kr[0].pixels!=sc[0].pixels,"KR configuration event invalidates cached pages and selects the retained private family");provider.setFontResources(fonts);auto next=provider.render(pages[0].next,{},prefs,{376,334},false,{});check(next[0].previous&&next[0].location.character>0&&next[0].progress>0,"Real predecessor and saved UTF16 character progress");rejects([&]{provider.render({}, {},prefs,{376,334},true,[]{return true;});},"Cancelled request never publishes stale pixels");provider.release();
    provider.open(reference(epubPath),{});check(provider.info().sections==2&&provider.info().title=="EPUB 中文🙂","Real native EPUB package/spine/title");auto first=provider.render({}, {},prefs,{376,334},false,{});check(first[0].next&&first[0].next->section==1&&!first[0].illustration,"EPUB text advances to original image chapter");auto picture=provider.detail({1},prefs,{376,334},false,{12,{200,-300}},{});check(picture.illustration&&picture.progress==1&&picture.previous&&picture.pixels->bytes.size()==752*668*4,"EPUB image detail remains viewport-bounded at12x zoom");provider.release();
    provider.open(reference(pdfPath),{});check(provider.info().sections==2&&provider.info().title=="fixture"&&!provider.info().pdfMetadataTitleAvailable,"Built-in PDF source reports filename title capability explicitly");auto pdfPages=provider.render({}, {},prefs,{376,334},true,{});check(pdfPages.size()==2&&pdfPages[0].illustration&&pdfPages[0].summary=="1 / 2"&&pdfPages[1].progress==1,"Actual Windows PDF pages and progress");const auto&pixels=*pdfPages[0].pixels;const auto center=(std::size_t(pixels.height/2)*pixels.width+pixels.width/2)*4;check(pixels.bytes[center+2]>220&&pixels.bytes[center]<30,"Actual PDF red artwork rendered instead of placeholder");auto pdfZoom=provider.detail({},prefs,{376,334},false,{12,{}},{});check(pdfZoom.pixels->bytes.size()==pixels.bytes.size(),"PDF12x zoom crops source into original fixed bitmap budget");provider.release();
    auto imported=reference(textPath);imported.platform=ReaderReferencePlatform::macOS;rejects([&]{provider.open(imported,{});},"Opaque Mac reference needs explicit relink");provider.release();
}
}
int main(int argc,char**argv){try{check(argc==3,"Arguments are bundledfont directory and original format oracle");hr(CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED));struct End{~End(){CoUninitialize();}}end;LayerFontResources fonts,korean;{LayerRasterizer raster(fs::u8path(argv[1]));fonts=raster.retainedFontResources();check(raster.setDefaultFontLanguage(LayerFontLanguage::korean),"Native fixture changes only owned raster font configuration");korean=raster.retainedFontResources();}std::exception_ptr error;std::thread worker([&]{try{hr(CoInitializeEx(nullptr,COINIT_MULTITHREADED));End workerEnd;native(fonts,korean,fs::u8path(argv[2]));}catch(...){error=std::current_exception();}});worker.join();if(error)std::rethrow_exception(error);std::cout<<"Native Reader formats passed "<<checks<<" checks\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<" after "<<checks<<" checks\n";return 1;}}
#else
int main(){return 0;}
#endif
