#include "modules/reader_presentation.hpp"
#include "core/data/file_io.hpp"
#include <algorithm>
#include <cmath>
#include <iostream>
using namespace endfield::modules;
namespace {using J=ReaderJson;unsigned checks{};
void check(bool b,const char*m){++checks;if(!b)throw std::runtime_error(m);}void equal(const J&a,const J&b){if(a.isNumber()&&b.isNumber()){check(std::abs(a.number()-b.number())<1e-6,"Source Reader numeric geometry/style");return;}if(a.isArray()&&b.isArray()){check(a.array().size()==b.array().size(),"Source Reader ordered children/path/geometry count");for(std::size_t n=0;n<a.array().size();++n)equal(a.array()[n],b.array()[n]);return;}if(a.isObject()&&b.isObject()){for(const auto&[key,value]:a.object())equal(value,b[key]);return;}if(a!=b)std::cerr<<"Expected "<<a.encode()<<" actual "<<b.encode()<<'\n';check(a==b,"Source Reader exact text/path/state");}
J canonical(const J&n,bool root=false){J::Object o;if(!root){const auto&b=n["bounds"].array();const auto&p=n["position"].array();const auto&a=n["anchorPoint"].array();o.emplace("frame",J::Array{p[0].number()-a[0].number()*b[2].number(),p[1].number()-a[1].number()*b[3].number(),b[2],b[3]});}for(auto k:{"kind","bounds","position","anchorPoint","opacity","hidden","masksToBounds","cornerRadius","borderWidth","backgroundColor","borderColor"}){if(std::string_view(k)=="position"||std::string_view(k)=="anchorPoint"||(std::string_view(k)=="borderColor"&&(n["borderWidth"].isNull()||n["borderWidth"].number()==0)))continue;auto value=n[k];if(value.isNull()){if(std::string_view(k)=="opacity")value=1;else if(std::string_view(k)=="hidden"||std::string_view(k)=="masksToBounds")value=false;else if(std::string_view(k)=="cornerRadius"||std::string_view(k)=="borderWidth")value=0;else if(std::string_view(k)=="anchorPoint")value=J::Array{0,0};}o.emplace(k,std::move(value));}if(!n["text"].isNull()){J::Object t;for(auto k:{"string","fontSize","foregroundColor","alignment","truncation","wrapped"})t.emplace(k,n["text"][k]);o.emplace("text",std::move(t));}if(!n["shape"].isNull()){J::Object s;for(auto k:{"path","fillColor","strokeColor","lineWidth","lineCap","lineJoin","fillRule"})s.emplace(k,n["shape"][k]);o.emplace("shape",std::move(s));}J::Array children;for(const auto&c:n["children"].array())children.push_back(canonical(c));o.emplace("children",std::move(children));return o;}
void original(const std::filesystem::path&p){auto b=ehud::data::detail::readFile(p,4*1024*1024);check(bool(b),"Original Reader artwork fixture present");auto source=J::parse(*b,4*1024*1024);check(source["sourceAuthority"].string()=="ca04f142185c7de40acd8523bdb563195d90a1d1","Reader original authority pinned");for(const auto&row:source["cases"].array()){const auto name=row["state"].string();ReaderArtwork actual;if(!row["kind"].isNull()){ReaderCanvasInput i;i.bookTitle="Synthetic book";i.appearance.dark=row["dark"].boolean();i.loading=row["loading"].boolean();if(!row["error"].isNull())i.error=row["error"].string();i.hasPage=row["kind"].string()!="none";i.illustration=row["kind"].string()=="image";i.next=i.previous=i.bookmarked=i.hasPage;i.progress=i.hasPage?1./3:0;actual=prepareReaderCanvas(i);if(name=="hover-open"){auto children=actual.root["children"].array();auto controls=children[1]["children"].array();auto highlight=controls[1]["children"].array();highlight[0]["opacity"]=.62;highlight[1]["opacity"]=1;controls[1]["children"]=highlight;children[1]["children"]=controls;actual.root["children"]=children;}}
 else{ReaderMenuInput i;i.type=name=="open"?ReaderMenuType::open:name.starts_with("settings")?ReaderMenuType::settings:name=="bookmarks"?ReaderMenuType::bookmarks:ReaderMenuType::library;if(i.type==ReaderMenuType::library||i.type==ReaderMenuType::bookmarks)for(unsigned n=0;n<9;++n)i.choices.push_back({"id"+std::to_string(n),i.type==ReaderMenuType::bookmarks?std::to_string(n*10)+"%":"Synthetic book "+std::to_string(n)+" · "+std::to_string(n*10)+"%"});if(name=="library-bottom")i.firstRow=3;if(name=="library-delete")i.deletion="id0";if(name=="settings-horizontal"){i.preferences.setVertical(false);i.preferences.fontSize=32;i.preferences.lineSpacing=18;i.preferences.margin=48;}actual=prepareReaderMenu(i);}
 try{equal(canonical(row["root"],true),canonical(actual.root,true));}catch(...){std::cerr<<"Reader original case "<<name<<'\n';throw;}check(actual.actions.size()==row["actions"].array().size(),"Source Reader action count");for(std::size_t n=0;n<actual.actions.size();++n){const auto&a=actual.actions[n];const auto&r=row["actions"].array()[n];check(a.id==r["id"].string()&&a.label==r["label"].string()&&a.enabled==r["enabled"].boolean(),"Source Reader action identity/title/enabled");equal(J::Array{a.rect.x,a.rect.y,a.rect.width,a.rect.height},r["rect"]);}}
}
}
int main(int argc,char**argv){try{check(argc==2,"Original Reader artwork fixture argument required");original(std::filesystem::path(std::u8string(reinterpret_cast<const char8_t*>(argv[1]))));auto p=ReaderPreferences{};p.fontSize=32;p.margin=48;p.lineSpacing=18;check(changeReaderSetting(p,"size+").fontSize==32&&changeReaderSetting(p,"margin+").margin==48&&changeReaderSetting(p,"spacing+").lineSpacing==18,"Source settings upper clamps");p.fontSize=10;p.margin=6;p.lineSpacing=0;check(changeReaderSetting(p,"size-").fontSize==10&&changeReaderSetting(p,"margin-").margin==6&&changeReaderSetting(p,"spacing-").lineSpacing==0,"Source settings lower clamps");auto a=prepareReaderCanvas({});check(!readerActionAt(a.actions,{76,20}),"Source action maximum edge excluded");check(readerActionAt(a.actions,{13,9})=="open","Source top control hit");ReaderMenuInput automatic;automatic.type=ReaderMenuType::settings;automatic.preferences=ReaderPreferences::defaults("System");automatic.selectedFont="Noto Sans SC";auto sc=prepareReaderMenu(automatic);automatic.selectedFont="Noto Sans KR";auto kr=prepareReaderMenu(automatic);const auto fontTitle=[](const ReaderArtwork&v){const auto i=std::find_if(v.actions.begin(),v.actions.end(),[](const auto&a){return a.id=="font";});return i==v.actions.end()?std::string{}:i->label;};check(fontTitle(sc)=="Font · Noto Sans SC"&&fontTitle(kr)=="Font · Noto Sans KR"&&automatic.preferences.fontName=="System","Automatic language family is displayed without turning it into a persisted explicit font override");std::cout<<"Reader presentation passed "<<checks<<" checks\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<" after "<<checks<<" checks\n";return 1;}}
