#include "modules/reader_viewport.hpp"
#include "core/data/file_io.hpp"
#include <algorithm>
#include <array>
#include <cstdio>
#include <cmath>
#include <deque>
#include <fstream>
#include <iostream>
#include <limits>
#include <thread>

namespace {
namespace m=endfield::modules;namespace c=endfield::core;using J=m::ReaderJson;namespace fs=std::filesystem;
unsigned checks{};void check(bool b,const char*why){++checks;if(!b)throw std::runtime_error(why);}template<class F>void rejects(F&&f,const char*why){bool rejected{};try{f();}catch(const std::exception&){rejected=true;}check(rejected,why);}
std::string id(unsigned n){char s[64];std::snprintf(s,sizeof(s),"A0000000-0000-4000-8000-%012u",n);return s;}
m::ReaderBook book(unsigned n){return m::windowsReaderReference(id(n),"C:\\Owned-reader-fixture\\book"+std::to_string(n)+".pdf","Book "+std::to_string(n));}
void write(const fs::path&p,std::string_view value){fs::create_directories(p.parent_path());std::ofstream file(p,std::ios::binary);file.write(value.data(),std::streamsize(value.size()));if(!file)throw std::runtime_error("Cannot write isolated fixture");}
struct Temp {fs::path root=fs::canonical(fs::temp_directory_path())/("endfield-reader-"+ehud::data::makeUUID());~Temp(){std::error_code e;fs::remove_all(root,e);}};
struct Repository:m::ReaderRepository {m::ReaderLibrary value;unsigned reads{},saves{};bool fail{};m::ReaderLibrary load()override{++reads;return value;}void save(const m::ReaderLibrary&v)override{++saves;if(fail)throw std::runtime_error("Synthetic reader save failure");value=v;}};
struct Queue {
 struct Job {std::function<void()>work;std::function<void(std::exception_ptr)>done;std::exception_ptr error;};std::deque<Job>jobs;std::size_t capacity{32};unsigned rejected{},accepted{};
 m::ReaderExecutor executor(){return {[this](auto w,auto d){if(jobs.size()>=capacity){++rejected;return false;}jobs.push_back({std::move(w),std::move(d),{}});++accepted;return true;}};}
 void one(){check(!jobs.empty(),"Synthetic borrowed FIFO job exists");auto job=std::move(jobs.front());jobs.pop_front();try{job.work();}catch(...){job.error=std::current_exception();}job.done(job.error);}
 void drain(){for(unsigned n=0;!jobs.empty();++n){check(n<1000,"Reader installs no automatic retry loop");one();}}
};
struct Source:m::ReaderDocumentSource {
 unsigned opens{},renders{},details{},releases{};std::string opened;bool fail{},missingPixels{};c::Point renderedSize{};bool renderedDark{};double renderedFont{};std::string summary="Synthetic page";std::shared_ptr<m::ReaderPagePixels>pixels=std::make_shared<m::ReaderPagePixels>();
 Source(){pixels->width=pixels->height=200;pixels->bytes.resize(200*200*4);}
 void open(const m::ReaderBook&b,const std::function<bool()>&cancel)override{if(cancel())return;++opens;opened=b.id;}
 m::ReaderPage page(int index){m::ReaderPage p;p.location.section=index;p.progress=index/5.;p.summary=summary;p.illustration=true;p.pixels=missingPixels?nullptr:pixels;if(index<5)p.next=m::ReaderLocation{index+1};if(index>0)p.previous=m::ReaderLocation{index-1};return p;}
 std::vector<m::ReaderPage>render(std::optional<m::ReaderLocation>location,std::optional<double>progress,const m::ReaderPreferences&prefs,c::Point size,bool dark,const std::function<bool()>&cancel)override{if(cancel())return {};renderedSize=size;renderedDark=dark;renderedFont=prefs.fontSize;if(opened.empty())throw std::runtime_error("Render attempted before retained open");if(fail)throw std::runtime_error("Synthetic decode failure");++renders;const int index=progress?int(*progress*5):int(location.value_or(m::ReaderLocation{}).section);auto first=page(std::clamp(index,0,5));std::vector<m::ReaderPage>p{first};if(first.next)p.push_back(page(int(first.next->section)));if(first.previous)p.push_back(page(int(first.previous->section)));return p;}
 m::ReaderPage detail(m::ReaderLocation l,const m::ReaderPreferences&,c::Point,bool,m::ReaderImageView,const std::function<bool()>&cancel)override{if(cancel())return {}; ++details;return page(int(l.section));}
 void release()override{++releases;opened.clear();}
};
void model(){m::ReaderLibrary l;l.books={book(1),book(2)};l.selected=id(1);l.originalFields["future"]="000001234567890123456789";l.preferences.originalFields["futurePreference"]=J::Array{1,2};l.books[0].originalFields["futureBook"]="opaque";l.books[0].location.originalFields["futureLocation"]=true;l.books[0].bookmarks.push_back({id(3),{1,2,3},.4,J::Object{{"futureMark",42}}});const auto j=m::encodeReaderLibrary(l);const auto round=m::decodeReaderLibrary(j);check(m::encodeReaderLibrary(round)==j,"All unknown root/preference/book/bookmark/location JSON survives exactly");check(!j["books"].array()[0].contains("bookmark")&&j["books"].array()[0]["referencePlatform"]==J("windows"),"Native references never fabricate Mac bookmark bytes");
 auto mac=j;auto macBooks=mac["books"].array();auto&b=macBooks[0];b.erase("referencePlatform");b.erase("windowsPath");b["bookmark"]="AQIDBA==";b["path"]="/owned-unopened/中文.epub";b["scoped"]=true;mac["books"]=macBooks;check(m::encodeReaderLibrary(m::decodeReaderLibrary(mac))==mac,"Mac v1 security bookmark bytes/path/scoped remain opaque and lossless");b["windowsPath"]="C:\\unsafe.txt";mac["books"]=macBooks;rejects([&]{m::decodeReaderLibrary(mac);},"Mixed platform locators reject instead of guessing access");
 l.selected.reset();check(!m::encodeReaderLibrary(l).contains("selected"),"Nil selected key follows Swift optional encoding");auto prefs=m::ReaderPreferences{};check(prefs.fontName=="Georgia"&&prefs.fontSize==10&&prefs.lineSpacing==2&&prefs.margin==16&&prefs.vertical(),"Exact original v1 defaults retained");check(m::ReaderPreferences::defaults("Noto Sans KR").fontName=="Noto Sans KR","Fresh shipping default is explicitly injectable without replacing saved choices");prefs.rightToLeft=true;prefs.setVertical(false);check(!prefs.continuous&&!prefs.rightToLeft,"Turning-axis setter clears only the source legacy direction flag");
 check(m::readerSupportedExtension(".PDF")&&m::readerSupportedExtension("epub")&&m::readerSupportedExtension("TXT")&&!m::readerSupportedExtension("zip"),"Actual original PDF/EPUB/TXT supported set is preserved");for(const auto path:{"book.pdf","C:book.pdf","\\relative.pdf"})rejects([&]{m::windowsReaderReference(id(8),path,"Title");},"Relative/drive-relative native references reject without file IO");
 auto invalid=j;auto badBooks=j["books"].array();badBooks[0]["location"]["character"]=64000001;invalid["books"]=badBooks;rejects([&]{m::decodeReaderLibrary(invalid);},"Source location bound is not silently clamped on import");invalid=j;badBooks=j["books"].array();badBooks[1]["id"]=id(1);invalid["books"]=badBooks;rejects([&]{m::decodeReaderLibrary(invalid);},"UUID duplicates reject before changing the library");invalid=j;invalid["version"]=2;rejects([&]{m::decodeReaderLibrary(invalid);},"Newer schema rejects without rewriting user payloads");
}
void repository(){Temp t;m::ReaderJSONRepository repo(t.root,m::ReaderPreferences::defaults("Noto Sans SC"));check(!fs::exists(t.root),"Injected repository construction creates and reads nothing");auto l=repo.load();check(l.books.empty()&&l.preferences.fontName=="Noto Sans SC"&&!fs::exists(t.root),"Fresh lazy load creates no empty file");l.books={book(1)};l.selected=id(1);repo.save(l);const auto original=*ehud::data::detail::readFile(t.root/"library.json",m::readerMaximumLibraryBytes);check(m::decodeReaderLibrary(J::parse(original))==l,"Actual atomic JSON file persists the source v1 model");repo.save(l);check(*ehud::data::detail::readFile(t.root/"library.json",m::readerMaximumLibraryBytes)==original,"Unchanged save leaves exact durable bytes untouched");m::ReaderJSONRepository alternateDefaults(t.root,m::ReaderPreferences::defaults("Noto Sans KR"));check(alternateDefaults.load().preferences.fontName=="Noto Sans SC","A newly supplied KR default never overrides a saved SC font choice");
 auto changed=J::parse(original);changed["unknownExternalEdit"]=true;const auto edited=changed.encode();write(t.root/"library.json",edited);l.preferences.fontSize=11;rejects([&]{repo.save(l);},"Changed-on-disk detection rejects a stale writer");check(*ehud::data::detail::readFile(t.root/"library.json",m::readerMaximumLibraryBytes)==edited,"Conflict preserves external bytes instead of truncating them");
 Temp corrupt;write(corrupt.root/"library.json","{ damaged");m::ReaderJSONRepository bad(corrupt.root);rejects([&]{bad.load();},"Corrupt library load is explicit");check(*ehud::data::detail::readFile(corrupt.root/"library.json",100)=="{ damaged","Corrupt file never resets itself to empty");
 bool wrongThread{};std::thread other([&]{try{repo.load();}catch(...){wrongThread=true;}});other.join();check(wrongThread,"One worker repository refuses another thread without touching data");
}
void state(){auto repo=std::make_shared<Repository>();repo->value.books={book(1),book(2)};repo->value.selected=id(1);Queue q;auto source=std::make_shared<Source>();m::ReaderState state(repo,q.executor(),source);check(repo->reads==0&&q.jobs.empty(),"Reader owner has no eager IO/service/timer");state.setActive(true);q.drain();check(state.loaded()&&source->opens==1&&source->renders==1&&state.current()&&state.pages().size()==2,"Activation loads once and renders only current/two-neighbor bounded cache");check(state.next()&&state.current()->location.section==1,"Neighbor navigation uses the retained page immediately");q.drain();check(state.pages().size()==3&&state.book()->location.section==1,"Background refill commits progress independently of UI raster cache");check(state.previous()&&state.current()->location.section==0,"Previous uses source bounded visit history");q.drain();
 repo->fail=true;check(state.select(id(2))&&state.book()->id==id(1),"Select remains the confirmed snapshot until durable callback");q.drain();check(state.error()&&state.hasUnsavedChanges()&&state.book()->id==id(1)&&q.jobs.empty(),"Failed select retains pending command without pretending it persisted or retry polling");repo->fail=false;state.retryPendingWrites();q.drain();check(state.book()->id==id(2)&&source->opened==id(2)&&!state.hasUnsavedChanges(),"Explicit retry selects and opens only the confirmed book");
 repo->fail=true;auto prefs=state.library().preferences;prefs.fontSize=20;check(state.setPreferences(prefs)&&state.library().preferences.fontSize==20,"Preferences preview immediately while the write stays off-thread");q.drain();check(state.library().preferences.fontSize==10&&state.hasUnsavedChanges(),"Failed preference write restores confirmed rendering and retains explicit retry data");repo->fail=false;state.retryPendingWrites();q.drain();check(state.library().preferences.fontSize==20,"Explicit preference retry installs confirmed choices");
 check(state.toggleBookmark(id(7))&&state.book()->bookmarks.empty(),"Bookmark transaction waits for durable acknowledgment");q.drain();check(state.book()->bookmarks.size()==1,"Bookmark captures current location/progress atomically");check(state.toggleBookmark(id(8)),"Toggle removes by current location rather than supplied new UUID");q.drain();check(state.book()->bookmarks.empty(),"Original bookmark toggle removal retained");
 const auto beforeCanceledDetails=source->details;state.requestImageDetail({2,{}});state.cancelImageDetail();q.drain();check(source->details==beforeCanceledDetails,"Canceled queued zoom detail skips the actual provider raster work, not just publication");check(!state.imageDetail(),"Canceled detail callback cannot install stale zoom artwork");state.requestImageDetail({3,{}});q.drain();check(state.imageDetail()&&state.imageDetail()->view.zoom==3,"Detail uses same provider/executor and viewport-sized raster");const auto beforeSuperseded=source->details;state.requestImageDetail({4,{}});state.requestImageDetail({5,{}});q.drain();check(source->details==beforeSuperseded+1&&state.imageDetail()&&state.imageDetail()->view.zoom==5,"Superseded queued detail renders only newest view on the existing worker");state.setActive(false);q.drain();check(!state.current()&&state.pages().empty()&&!state.imageDetail()&&source->opened.empty(),"Hidden Reader releases decode/cache/detail on the borrowed executor");
 q.capacity=1;check(q.executor().submit([]{},[](auto){}),"Unrelated module occupies shared queue");state.setActive(true);check(q.rejected>0,"Rejected reopen is explicitly retained");state.jump(m::ReaderLocation{2});q.one();state.queueCapacityAvailable();q.drain();check(source->opened==id(2)&&state.current()->location.section==2,"Newest request preserves rejected initial open, never rendering without its book");
 auto refreshed=book(99);refreshed.windowsPath=book(2).windowsPath;refreshed.title="Refreshed duplicate reference";const auto opens=source->opens;repo->fail=true;check(state.addValidated(refreshed)&&state.book()->title=="Book 2","Duplicate locator refresh retains original ID until durable save");q.drain();repo->fail=false;state.retryPendingWrites();q.drain();check(state.book()->id==id(2)&&state.book()->title==refreshed.title&&source->opens==opens+1,"Failed duplicate import retains reopen intent and never changes reference identity");
 repo->fail=true;state.saveProgress({3},.6,id(2));q.drain();const auto failed=repo->saves;state.flush();state.queueCapacityAvailable();check(q.jobs.empty()&&repo->saves==failed&&state.book()->location.section==3,"Failed progress remains responsive without retrying on idle/capacity events");repo->fail=false;state.retryPendingWrites();q.drain();check(repo->value.books[1].location.section==3&&!state.hasUnsavedChanges(),"Failed progress survives until explicit flush retry");
 auto invalidRepo=std::make_shared<Repository>();invalidRepo->value.books={book(1)};invalidRepo->value.selected=id(1);auto invalidSource=std::make_shared<Source>();invalidSource->missingPixels=true;m::ReaderState invalid(invalidRepo,q.executor(),invalidSource);invalid.setActive(true);q.drain();check(invalid.error()&&!invalid.current(),"A decoder cannot publish a blank page as a successful bounded raster");invalid.setActive(false);q.drain();
 q.capacity=32;auto firstRepo=std::make_shared<Repository>();firstRepo->value.books={book(1)};firstRepo->value.selected=id(1);auto firstSource=std::make_shared<Source>();m::ReaderState first(firstRepo,q.executor(),firstSource);first.setActive(true);q.one();check(first.loaded()&&!first.current()&&q.jobs.size()==1,"Accepted first document render remains queued without a published page");auto newer=first.library().preferences;newer.fontSize=22;first.setPreferences(newer);first.setLayout({300,310},false);q.one();check(!first.current(),"Old captured first page never publishes after preferences/theme/viewport change");q.drain();check(first.current()&&firstSource->opens==1&&firstSource->renders==2&&firstSource->renderedSize==c::Point{300,310}&&!firstSource->renderedDark&&firstSource->renderedFont==22,"Latest first-page replacement uses one accepted open and the latest settings");first.setActive(false);q.drain();
 auto rollbackRepo=std::make_shared<Repository>();rollbackRepo->value.books={book(1)};rollbackRepo->value.selected=id(1);rollbackRepo->fail=true;auto rollbackSource=std::make_shared<Source>();m::ReaderState rollback(rollbackRepo,q.executor(),rollbackSource);rollback.setActive(true);q.one();auto failing=rollback.library().preferences;failing.fontSize=25;rollback.setPreferences(failing);q.drain();check(rollback.current()&&rollback.library().preferences.fontSize==10&&rollbackSource->renderedFont==10&&rollback.hasUnsavedChanges(),"Failed preferences before first paint re-render with confirmed metrics and retain retry intent");rollback.setActive(false);q.drain();
 auto combiningRepo=std::make_shared<Repository>();combiningRepo->value.books={book(1)};combiningRepo->value.selected=id(1);auto combiningSource=std::make_shared<Source>();combiningSource->summary="a";for(unsigned n=0;n<6000;++n)combiningSource->summary+="\xCC\x81";m::ReaderState combining(combiningRepo,q.executor(),combiningSource);combining.setActive(true);q.drain();check(combining.current()&&combining.current()->summary==combiningSource->summary,"Source summary grapheme contract preserves long combining sequences without a 4096-byte truncation");combining.setActive(false);q.drain();
 auto deathRepo=std::make_shared<Repository>();deathRepo->value.books={book(1)};deathRepo->value.selected=id(1);bool destroyOnChange{};std::unique_ptr<m::ReaderState> death;death=std::make_unique<m::ReaderState>(deathRepo,q.executor(),nullptr,[&]{if(destroyOnChange)death.reset();});death->setActive(true);q.drain();death->saveProgress({1},.2,id(1));death->saveProgress({2},.4,id(1));destroyOnChange=true;q.one();check(!death&&q.jobs.empty()&&deathRepo->saves==1&&deathRepo->value.books[0].location.section==1,"Destroying facade from acknowledgment cannot submit a newer pending write afterward");
 auto dying=std::make_unique<m::ReaderState>(repo,q.executor());dying->setActive(true);q.drain();dying->remove(id(1));dying.reset();q.drain();check(repo->value.books.size()==1,"Accepted immutable library write survives owner teardown with no dead callback");
}
void viewport(){m::ReaderViewport v;v.setActive(true,0);v.setPage(m::ReaderPageAnchor{id(1),{3},true,true,true,1./3},0);v.zoomBy(2,{200,215},1);check(v.imageView().zoom==2&&v.nextWakeTime()==1.12&&!v.takeDetailRequest(1.119),"Zoom exposes one .12s shared deadline with no render per pointer event");check(v.takeDetailRequest(1.12)->zoom==2&&!v.nextWakeTime(),"Zoom detail deadline is consumed exactly once");v.pointerDown({200,215});v.pointerDragged({250,195},2);v.pointerUp(2);check(v.imageView().pan==c::Point{50,-20},"Drag pans retained geometry directly");v.turnPage(1);check(v.takeNavigation()->step==1,"Explicit page turn emits one owner intent");v.setPage(m::ReaderPageAnchor{id(1),{4},true,true,true,4./9},3);check(v.imageView().zoom==2&&v.imageView().pan.y==167,"Vertical turn preserves zoom while opening at source page edge");auto p=v.placements();check(p[0].rect.width==752&&p[1].rect.y-p[0].rect.y==668,"Zoomed neighbor spacing uses page height, not viewport height");v.resetZoom(4);v.scroll({200,215},0,100,4.5,m::ReaderGesturePhase::none,false,false);check(v.nonPrecisionScrollDuration()==.10,"Ordinary wheel keeps source .10 second easing");v.scroll({200,215},0,234,5);check(v.takeNavigation()->step==1,"Continuous scrolling crosses a page without a horizontal flip");v.setPage(m::ReaderPageAnchor{id(1),{5},true,true,true,.5},5);check(v.scrollOffset()==0&&v.imageView().zoom==1&&v.nonPrecisionScrollDuration()==0,"Cached continuous next page recycles immediately without an unwanted scroll bounce");
 auto prefs=m::ReaderPreferences{};prefs.setVertical(false);v.setPreferences(prefs);v.zoomBy(3,{200,215},6);v.scroll({200,215},0,120,7);check(!v.takeNavigation()&&v.imageView().pan.y==-120,"Horizontal zoomed pages remain scrollable to their lower area");v.scroll({200,215},60,0,8,m::ReaderGesturePhase::began);check(v.takeNavigation()->step==1,"Horizontal precision gesture turns after exact60 threshold");v.scroll({200,215},100,0,8.1,m::ReaderGesturePhase::changed);check(!v.takeNavigation(),"One gesture never repeatedly flips pages");v.setPage(m::ReaderPageAnchor{id(1),{6},true,true,true,.6},8.1);check(v.imageView().zoom==3&&v.imageView().pan.y==-120&&v.pageTurnSequence()==1,"Horizontal flip preserves zoom/pan and one original .26s transition");v.scroll({200,215},100,0,8.2,m::ReaderGesturePhase::none,true);check(!v.takeNavigation(),"Horizontal momentum never triggers a second turn");
 const auto r=v.progressRect();v.pointerDown({r.x+r.width*.72,r.y+5});check(v.displayedProgress()==.72,"Progress drag previews its fraction before seeking");v.pointerUp(9);check(v.takeNavigation()->progress==.72&&v.imageView().zoom==1,"Committed seek resets zoom, retaining source behavior");v.setActive(false,10);check(!v.takeDetailRequest(11)&&v.nextWakeTime()==10.35&&!v.artworkReleaseDue(10.349)&&v.artworkReleaseDue(10.35),"Close cancels detail and shares the source .35s retained-artwork deadline");
 m::ReaderViewport switching;switching.setActive(true,0);switching.setPage(m::ReaderPageAnchor{id(1),{0},true,false,true,0},0);switching.zoomBy(4,{80,70},1);switching.setPage({},2);switching.setPage(m::ReaderPageAnchor{id(2),{0},true,false,true,0},3);check(switching.imageView()==m::ReaderImageView{}&&switching.scrollOffset()==0,"Actual source nil/current book-open sequence resets equal-location book zoom");switching.zoomBy(3,{80,70},4);switching.turnPage(1);switching.setPage(m::ReaderPageAnchor{id(3),{0},true,false,true,0},5);check(switching.imageView()==m::ReaderImageView{}&&switching.lastAnimatedTurnDirection()==0&&switching.scrollOffset()==0,"Coalesced different-book notification produces the same clear/open state, never a stale cross-book flip");
 check(m::readerMenuRect(m::ReaderMenuKind::settings,c::Rect{158,8,84,30})==c::Rect{144,44,248,222},"Reading settings stays compact directly below its source control");check(m::readerMenuRect(m::ReaderMenuKind::bookmarks,c::Rect{296,8,92,30})==c::Rect{152,44,240,294},"Bookmarks stays compact beneath its source control");m::ReaderListScroll list;list.setCount(20);check(list.scroll(34.5)&&list.offset()==0,"List keeps smooth wheel remainder without early row jumps");list.scroll(.5);check(list.offset()==1&&list.scrollbar(350)->width==2,"Six visible rows and source-width scrollbar retained");list.setDeleteConfirmation(true);check(!list.scroll(350)&&list.offset()==1,"Delete confirmation blocks changing the target beneath it");list.setDeleteConfirmation(false);list.setCount(5000);for(unsigned n=0;n<500;++n)list.scroll(350);check(list.offset()==4994&&list.scrollbar(350)->height==12,"Source Shelf-choice list remains six-row virtualized beyond the bookmark count");list.setCount(std::numeric_limits<std::size_t>::max());list.scroll(350);check(list.offset()==5004&&std::isfinite(list.scrollbar(350)->y),"Scalar list count and bounded wheel arithmetic never allocate or overflow");list.setCount(1);check(list.scroll(35)&&list.offset()==0&&!list.scrollbar(350),"Short source list consumes wheel remainder while retaining its sole row");check(!m::ReaderImageView{0,{}}.valid()&&m::ReaderImageView{0,{}}.clamped({376,334})==m::ReaderImageView{},"Malformed zero zoom clamps to source minimum before any division");
}
bool close(double a,double b){return std::abs(a-b)<1e-9;}
void oracle(const fs::path&path){const auto raw=ehud::data::detail::readFile(path,1024*1024);check(raw.has_value(),"Compact original Reader oracle exists");const auto root=J::parse(*raw,1024*1024);for(const auto&row:root["cases"].array()){m::ReaderViewport v;m::ReaderPreferences prefs;prefs.setVertical(row["vertical"].boolean());v.setPreferences(prefs);v.setActive(true,0);m::ReaderPageAnchor anchor{id(1),{3},true,true,row["illustration"].boolean(),1./3};v.setPage(anchor,0);if(row["initialZoom"].boolean())v.magnify({200,215},1,1);const auto&e=row["event"];const auto&kind=e["kind"].string();if(kind=="zoom")v.zoomBy(e["factor"].number(),{e["x"].number(),e["y"].number()},10);else if(kind=="scroll")v.scroll({200,215},e["dx"].number(),e["dy"].number(),10);else if(kind=="turn")v.turnPage(int(e["direction"].integer()));else if(kind=="magnify")v.magnify({e["x"].number(),e["y"].number()},e["amount"].number(),10);else if(kind=="seek"){const auto r=v.progressRect();v.pointerDown({r.x+r.width*e["fraction"].number(),r.y+r.height/2});v.pointerUp(10);}else{v.pointerDown({200,215});v.pointerDragged({200+e["dx"].number(),215+e["dy"].number()},10);v.pointerUp(10);}if(auto navigation=v.takeNavigation();navigation&&navigation->step){anchor.location.section+=navigation->step;anchor.progress=anchor.location.section/9.;v.setPage(anchor,10);}const auto&after=row["after"];const auto&pan=after["pan"].array();if(!close(v.imageView().zoom,after["zoom"].number())||!close(v.imageView().pan.x,pan[0].number())||!close(v.imageView().pan.y,pan[1].number())||!close(v.scrollOffset(),after["offset"].number()))std::cerr<<"Oracle mismatch: "<<row["name"].string()<<'\n';check(close(v.imageView().zoom,after["zoom"].number())&&close(v.imageView().pan.x,pan[0].number())&&close(v.imageView().pan.y,pan[1].number())&&close(v.scrollOffset(),after["offset"].number()),"Unchanged actual ReaderCanvas pan/zoom/scroll equals portable state");const auto pages=v.placements();for(unsigned n=0;n<3;++n){const auto&b=after["pictures"].array()[n].array();check(close(pages[n].rect.x,b[0].number())&&close(pages[n].rect.y,b[1].number())&&close(pages[n].rect.width,b[2].number())&&close(pages[n].rect.height,b[3].number())&&pages[n].hidden==after["hidden"].array()[n].boolean(),"All three original cached page frames/visibility match exactly");}check(v.pageTurnSequence()==std::uint64_t(after["turnSequence"].integer()),"Source horizontal transition sequence retained");}
 for(const auto&row:root["storeCases"].array()){const auto&library=row["library"];const auto encoded=m::encodeReaderLibrary(m::decodeReaderLibrary(library));if(encoded!=library)std::cerr<<"Store snapshot mismatch: "<<row["name"].string()<<"\noriginal="<<library.encode()<<"\nencoded="<<encoded.encode()<<'\n';check(encoded==library,"Actual original ReaderStore encoded snapshots roundtrip exactly");}
}
}
int main(int argc,char**argv){try{check(argc<=2,"Optional argument is compact original Reader JSON oracle");model();repository();state();viewport();if(argc==2)oracle(argv[1]);std::cout<<"PASS "<<checks<<" Reader foundation checks\n";return 0;}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
