#include "modules/settings.hpp"
#include <fstream>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <vector>
namespace {
using namespace endfield;using namespace modules;using ehud::data::Json;using ehud::data::Settings;
unsigned checks{};void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}
template<class F>void rejects(F f,const char*why){bool failed{};try{f();}catch(const std::exception&){failed=true;}check(failed,why);}
Json view(const Settings&s){Json result{Json::Object{}};for(const auto*key:{"hudScale","hudOffsetX","hudOffsetY","theme","accentHex","launchAtLogin","ambientAnimation"})result[key]=s.fields[key];return result;}
void run(const Json&oracle){
    auto initial=Settings::defaults();initial.set("language","english");initial.set("theme","dark");initial.set("launchAtLogin",false);initial.set("reduceMotion",true);
    std::vector<Settings>saved;std::vector<bool>capture;unsigned registered{},notifications{},configurations{};bool rejectShortcut{};
    SettingsCallbacks callbacks;callbacks.persist=[&](const auto&v){saved.push_back(v);};callbacks.launchAtLogin=[](bool)->std::optional<std::string>{return "Synthetic login failure";};callbacks.registerShortcut=[&](auto)->std::optional<std::string>{++registered;return rejectShortcut?std::optional<std::string>("Synthetic conflict"):std::nullopt;};callbacks.shortcutCapture=[&](bool b){capture.push_back(b);};callbacks.changed=[&]{++notifications;};callbacks.configurationChanged=[&](const auto&){++configurations;};
    SettingsController controller(initial,callbacks);double now{};std::size_t index{};
    const auto record=[&](const char*name){const auto&expected=oracle["controller"].array().at(index++);check(expected["name"].string()==name&&expected["time"].number()==now,"Original checkpoint name/time");check(view(controller.configuration())==expected["current"],"Effective configuration equals original controller");check(view(controller.committed())==expected["committed"],"Committed configuration equals original controller");const auto remaining=controller.confirmationRemaining(now);check(remaining?(expected["remaining"].isNumber()&&expected["remaining"].integer()==*remaining):expected["remaining"].isNull(),"Exact source preview remaining seconds");check(controller.scalePending()==expected["scalePending"].boolean()&&controller.positionPending()==expected["positionPending"].boolean(),"Source pending layout components");check(controller.status()==(expected["status"].isNull()?"":expected["status"].string())&&controller.capturingShortcut()==expected["capturing"].boolean(),"Original source status and capture lifecycle");};
    record("initial");controller.previewScale(1.35,now);record("scale");check(saved.empty()&&controller.nextWakeTime(now)==1,"Preview never saves unconfirmed geometry and uses caller deadline");auto config=controller.configuration();config.set("theme","light");controller.update(config,now);record("themeDuringPreview");check(saved.size()==1&&saved.back().number("hudScale")==1&&saved.back().string("theme")=="light","Unrelated preference saves with confirmed geometry only");
    now=1;controller.previewPosition(-.17,.1,now);record("position");now=2.1;controller.wake(now);record("tick");check(controller.nextWakeTime(now)==3,"Finite shared deadline follows source remaining-label boundary");now=12.9;check(controller.confirmLayout(now),"Unexpired preview accepts");record("confirm");controller.previewScale(9,now);record("clamped");now=24.9;check(!controller.confirmLayout(now),"Expired click cannot commit unsafe layout");record("expiredConfirm");
    now=30;controller.previewPosition(.3,-.2,now);controller.close();record("closed");config=controller.configuration();config.set("launchAtLogin",true);config.set("ambientAnimation",false);controller.update(config,now);record("platformFailure");controller.beginShortcutCapture();record("capture");controller.close();record("captureClosed");check(index==oracle["controller"].array().size(),"All actual original controller checkpoints consumed");
    check(capture==std::vector<bool>({true,false})&&!controller.nextWakeTime(now),"Capture closes once and settled controller has no wake");const auto before=notifications;controller.wake(now+1000);check(notifications==before,"Idle wake publishes nothing");
    const auto macShortcut=controller.committed().fields["summonShortcut"];check(settingsShortcutTitle({})=="Ctrl + `","Native default is explicit Windows chord equivalent");check(!controller.setShortcut({0x77,3})&&registered==1,"Two-modifier chord registers once");check(settingsShortcut(controller.committed())==SettingsShortcut{0x77,3}&&controller.committed().fields["summonShortcut"]==macShortcut,"Windows chord uses additive identity and preserves imported Mac key code");
    rejectShortcut=true;const auto prior=controller.committed();check(controller.setShortcut({0x78,2})==std::optional<std::string>("Synthetic conflict")&&controller.committed()==prior,"Registration failure preserves prior binding/preferences");const auto registrations=registered;check(controller.setShortcut({'C',2}).has_value()&&registered==registrations,"Reserved common Windows editor chord rejects before platform mutation");
    check(validateSettingsShortcut({'A',0},core::Language::english).has_value()&&validateSettingsShortcut({'A',7},core::Language::english).has_value()&&validateSettingsShortcut({0x10,2},core::Language::english).has_value(),"Capture requires one ordinary key plus one/two supported modifiers");
    rejectShortcut=false;controller.previewScale(.2,100);controller.beginShortcutCapture();controller.restoreDefaults();check(!controller.capturingShortcut()&&!controller.confirmationRemaining(100)&&settingsShortcut(controller.committed())==SettingsShortcut{},"Restore clears preview/capture and reapplies native default binding");check(registered==registrations+1,"Explicit restore retries registration even if binding would be unchanged");
    SettingsCallbacks absent;SettingsController unsupported(initial,absent);check(unsupported.setShortcut({0x77,2}).has_value()&&settingsShortcut(unsupported.configuration())==SettingsShortcut{},"Absent platform registration reports unavailable rather than pretending success");
    const auto unchanged=unsupported.configuration();rejects([&]{unsupported.previewScale(1.2,std::numeric_limits<double>::infinity());},"Nonfinite caller time rejects");check(unsupported.configuration()==unchanged&&!unsupported.confirmationRemaining(0),"Malformed time leaves preview untouched");
    std::cout<<"Settings controller: "<<checks<<" source and transaction checks passed\n";
}
}
int main(int argc,char**argv){try{check(argc==2,"Pass actual original Settings oracle JSON");std::ifstream input(argv[1],std::ios::binary);check(input.good(),"Open explicit oracle");std::string text{std::istreambuf_iterator<char>(input),{}};run(Json::parse(text,32*1024*1024));return 0;}catch(const std::exception&e){std::cerr<<"Settings after "<<checks<<": "<<e.what()<<'\n';return 1;}}
