#include "native/settings_safety.hpp"
#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#include <objbase.h>
#include <algorithm>
#include <cmath>
#include <iostream>
#include <atomic>
#include <cstdlib>
#include <new>
using namespace endfield;using namespace native;using ehud::data::Json;
namespace {unsigned checks{};std::atomic<std::size_t>allocations{};bool countAllocations{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}Json blank(){return Json::Object{{"bounds",Json::Array{0,0,0,0}},{"children",Json::Array{}}};}
struct Window{HWND hwnd{};Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"EndfieldSafetyHidden";check(RegisterClassW(&c)!=0,"Register owned fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,c.lpszClassName,L"Synthetic",WS_POPUP,0,0,640,480,nullptr,nullptr,c.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Owned hidden window");}~Window(){if(hwnd)DestroyWindow(hwnd);UnregisterClassW(L"EndfieldSafetyHidden",GetModuleHandleW(nullptr));}};
void run(const std::filesystem::path&shader){Window window;Renderer renderer;renderer.initialize(window.hwnd,640,480,{Driver::warpForTests,shader,RenderTarget::offscreenForTests});renderer.setCamera(layerViewportProjection(640,480));LayerRasterizer raster;LayerRasterOptions options;options.pixelsPerPoint=1;modules::SettingsController controller(ehud::data::Settings::defaults());modules::SettingsSafety state(controller);controller.previewScale(1.8,0);state.refresh(0);NativeSettingsSafety scene(state,raster,options);LayerComposition composition;LayerScene reference(raster),carrier(raster);carrier.load(blank(),options);constexpr core::Rect viewport{0,0,640,480};const auto artwork=modules::prepareSettingsSafetyArtwork(state,viewport,{});reference.load(artwork.layers,options);std::vector<LayerPlacement>placements;for(const auto&s:artwork.surfaces)placements.push_back({*reference.surfaceIndex(s.id),s.local,1,{}});const std::array<Vertex,4>vertices{{{{0,0,0},{0,0},{1,1,1,1}},{{640,0,0},{1,0},{1,1,1,1}},{{640,480,0},{1,1},{1,1,1,1}},{{0,480,0},{0,1},{1,1,1,1}}}};constexpr std::array<std::uint32_t,6>indices{0,1,2,0,2,3};renderer.setMesh("safety-oracle-dim",1,{vertices,indices});DrawObject dim;dim.sourceID="safety-oracle-dim";dim.meshID=dim.sourceID;dim.linearTint={0,0,0,1};dim.opacity=.30f;std::vector<DrawObject>local;DrawObject full;bool done{};
 struct Cleanup{Renderer&r;LayerComposition&c;NativeSettingsSafety&s;bool&done;~Cleanup(){if(!done)try{c.detach(r);r.removeNativeGroup("safety-full-oracle");s.releaseResources(r);}catch(...){r.reset();}}}cleanup{renderer,composition,scene,done};
 for(double time:{0.,.04,.08,.13,.19,.25}){auto tilt=core::Matrix4::rotation(.04,-.06,0);tilt.values[11]=-.0004;scene.syncContent(viewport,time);scene.updatePose(viewport,tilt,time);scene.upload(renderer);auto entry=scene.entry();composition.setEntries(renderer,std::span(&entry,1));composition.present(renderer);renderer.draw(false);const auto actual=renderer.readback();check(scene.coverage().width*scene.coverage().height<viewport.width*viewport.height,"Production modal target stays card-sized");
  const auto phase=state.pose(time);tilt.values[13]=phase.travel;const auto card=modules::SettingsSafety::geometry(viewport).card;const auto world=core::Matrix4::translation(card.x+card.width*.5,card.y+95)*tilt*core::Matrix4::translation(-card.width*.5,-95);for(std::size_t n=0;n<placements.size();++n)placements[n].world=world*artwork.surfaces[n].local;reference.setPlacements(placements);reference.uploadResources(renderer);local.clear();local.push_back(dim);const auto draws=reference.prepareDraws();local.insert(local.end(),draws.begin(),draws.end());renderer.configureNativeGroup("safety-full-oracle",{viewport,1},local);full=renderer.nativeGroupOutput("safety-full-oracle");full.opacity=float(phase.opacity);LayerCompositionEntry oracle{&carrier,std::span(&full,1)};composition.setEntries(renderer,std::span(&oracle,1));composition.present(renderer);renderer.draw(false);const auto expected=renderer.readback();check(actual.pixels.size()==expected.pixels.size(),"Same owned target dimensions");unsigned maximum{};for(std::size_t n=0;n<actual.pixels.size();++n)maximum=std::max(maximum,static_cast<unsigned>(std::abs(int(actual.pixels[n])-int(expected.pixels[n]))));if(maximum>1)std::cerr<<"phase="<<time<<" maximum="<<maximum<<'\n';check(maximum<=1,"Card-sized decomposition equals actual full-root group fade within one storage level");}
 composition.detach(renderer);check(renderer.removeNativeGroup("safety-full-oracle"),"Detached oracle target retires");reference.releaseResources(renderer);renderer.removeMesh("safety-oracle-dim");state.setReduceMotion(true,.3);scene.syncContent(viewport,.3);scene.updatePose(viewport,{},.3);scene.upload(renderer);const auto geometry=modules::SettingsSafety::geometry(viewport);check(scene.actionAt({geometry.card.x+geometry.confirm.x+20,geometry.card.y+geometry.confirm.y+15})==1,"Hit routing uses actual projected card buttons");const auto count=scene.rasterizations();allocations=0;std::array<std::size_t,4>stageAllocations{};countAllocations=true;try{for(unsigned n=0;n<100;++n){auto before=allocations.load();state.refresh(.31+n*.001);stageAllocations[0]+=allocations.load()-before;before=allocations.load();scene.syncContent(viewport,.31+n*.001);stageAllocations[1]+=allocations.load()-before;before=allocations.load();scene.updatePose(viewport,core::Matrix4::rotation(0,n*.0001,0),.31+n*.001);stageAllocations[2]+=allocations.load()-before;before=allocations.load();scene.upload(renderer);stageAllocations[3]+=allocations.load()-before;}}catch(...){countAllocations=false;throw;}countAllocations=false;if(allocations)std::cerr<<"safety warm allocations refresh="<<stageAllocations[0]<<" content="<<stageAllocations[1]<<" pose="<<stageAllocations[2]<<" upload="<<stageAllocations[3]<<"\n";check(allocations==0,"Warm modal tilt/countdown checks allocate no heap");check(scene.rasterizations()==count,"Pointer-only card projection keeps glyphs and plate rasters");state.setReduceMotion(false,.5);state.pointerMove(0,.5);scene.syncContent(viewport,.5);scene.updatePose(viewport,{},.5);scene.upload(renderer);const auto feedbackStart=scene.rasterizations();for(unsigned n=1;n<=8;++n){const double t=.5+n*.02;scene.syncContent(viewport,t);scene.updatePose(viewport,{},t);scene.upload(renderer);}check(scene.rasterizations()>feedbackStart&&scene.rasterizations()<=feedbackStart+16,"Finite feedback updates only the two small source plates");const auto settled=scene.rasterizations();for(unsigned n=0;n<100;++n){scene.syncContent(viewport,.7+n*.001);scene.updatePose(viewport,{},.7+n*.001);scene.upload(renderer);}check(scene.rasterizations()==settled&&!state.feedbackAnimating(.7),"Completed source button animation has zero idle raster work");check(scene.releaseResources(renderer)&&renderer.stats().nativeGroups==0,"All isolated modal resources retire");done=true;check(!IsWindowVisible(window.hwnd)&&renderer.stats().presents==0,"No visible/modal UI or real settings touched");}
}
void*operator new(std::size_t n){if(countAllocations)++allocations;if(void*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void operator delete(void*p)noexcept{std::free(p);}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete[](void*p)noexcept{std::free(p);}void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
int wmain(int argc,wchar_t**argv){const auto com=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(com)&&argc==2,"Pass HLSL");run(argv[1]);CoUninitialize();std::cout<<"Settings safety scene: "<<checks<<" checks passed\n";return 0;}catch(const std::exception&e){countAllocations=false;if(SUCCEEDED(com))CoUninitialize();std::cerr<<"Settings safety scene after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
