#include "native/settings_scene.hpp"
#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#include <objbase.h>
#include <fstream>
#include <algorithm>
#include <cmath>
#include <iostream>
#include <atomic>
#include <cstdlib>
#include <new>
using namespace endfield;using namespace native;using ehud::data::Json;
namespace {unsigned checks{};std::atomic<std::size_t>allocations{};bool countAllocations{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}template<class F>void rejects(F f,const char*s){bool failed{};try{f();}catch(const std::exception&){failed=true;}check(failed,s);}
struct Window{HWND hwnd{};Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"EndfieldSettingsSceneHidden";check(RegisterClassW(&c)!=0,"Register owned fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,c.lpszClassName,L"Synthetic",WS_POPUP,0,0,400,334,nullptr,nullptr,c.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Synthetic window hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);UnregisterClassW(L"EndfieldSettingsSceneHidden",GetModuleHandleW(nullptr));}};
void run(const std::filesystem::path&shader,const std::filesystem::path&root){std::ifstream in(root/"manifest.json");check(in.good(),"Explicit original icon roster");const auto manifest=Json::parse(std::string{std::istreambuf_iterator<char>(in),{}});std::vector<modules::SettingsIcon>icons;SettingsImages images;for(const auto&icon:manifest["icons"].array())if(icon["offered"].boolean()){icons.push_back({icon["id"].string(),icon["title"].string()});images.emplace(icon["id"].string(),Json::Object{{"asset",icon["app"]["file"]},{"sha256",icon["app"]["sha256"]}});}
 Window window;Renderer renderer;renderer.initialize(window.hwnd,400,334,{Driver::warpForTests,shader,RenderTarget::offscreenForTests});renderer.setCamera(layerViewportProjection(400,334));LayerRasterizer raster;LayerRasterOptions options;options.pixelsPerPoint=1;options.assetRoot=root;auto initial=ehud::data::Settings::defaults();initial.set("launchAtLogin",false);modules::SettingsController controller(initial);modules::SettingsPresentation state(core::Module::display,controller,icons);state.activate(0);NativeSettingsScene scene(state,raster,options,images);LayerComposition composition;bool finished{};
 struct Cleanup{Renderer&r;LayerComposition&c;NativeSettingsScene&s;bool&done;~Cleanup(){if(!done)try{c.detach(r);s.releaseResources(r);}catch(...){r.reset();}}}cleanup{renderer,composition,scene,finished};double time{};
 const auto publish=[&](double t){time=t;state.refresh(t);scene.syncContent(t);scene.updatePose({{},1,t,{},{}});scene.uploadAnimations(renderer);composition.setEntries(renderer,scene.entries());composition.present(renderer);renderer.draw(false);check(scene.collectRetired(renderer),"Old generation retires after publication");};publish(0);check(renderer.stats().nativeGroups==7,"Seven visible source slider rows use retained groups");const auto image=renderer.readback();check(std::any_of(image.pixels.begin(),image.pixels.end(),[](auto b){return b!=0;}),"Original source artwork paints owned target");
 const auto baseline=raster.stats();const auto resources=renderer.stats();scene.updatePose({{},1,.01,{},{}});scene.uploadAnimations(renderer);composition.setEntries(renderer,scene.entries());composition.present(renderer);allocations=0;countAllocations=true;try{for(unsigned n=0;n<100;++n){const double t=.02+n*.001;scene.updatePose({core::Matrix4::rotation(0,.0001*n,0),1,t,{},{}});scene.uploadAnimations(renderer);composition.setEntries(renderer,scene.entries());composition.present(renderer);}}catch(...){countAllocations=false;throw;}countAllocations=false;check(allocations==0,"Warm Settings tilt and feedback allocate no heap");check(raster.stats().rasterizations==baseline.rasterizations&&renderer.stats().textureUploads==resources.textureUploads,"Numeric Settings frames retain all pixels");
 state.scroll({200,100},444,.2);publish(.2);check(state.perform("battery",.3),"Visible original battery submenu");publish(.3);check(scene.entries().size()>7&&state.pagePose(.3).active,"Source outgoing/incoming pages coexist");bool collapsed{};for(const auto&e:scene.entries())for(const auto&d:e.after){collapsed|=d.opacity==0;for(const auto&m:d.masks)check(m.bounds.width>0&&m.bounds.height>0,"Collapsed endpoint never submits an invalid zero-area mask");}check(collapsed,"Collapsed incoming source page is fully clipped by zero output alpha");publish(.43);bool clipped{};for(const auto&e:scene.entries())for(const auto&d:e.after){for(const auto&m:d.masks)clipped|=m.bounds.width>0&&m.bounds.width<400;}check(clipped,"Shared hand-off boundary clips actual grouped output");publish(.6);check(!state.outgoing(),"Finite source page completes and releases outgoing content");check(state.perform("method",.7),"Source choice triggers row feedback");publish(.7);bool faded{};for(const auto&e:scene.entries())for(const auto&d:e.after)faded|=std::abs(d.opacity-.68f)<1e-6;check(faded,"Engage applies source opacity once to composed row");publish(.9);
 state.escape(1);publish(1);publish(1.3);state.perform("appIcon",1.4);publish(1.4);publish(1.7);check(state.view().page==modules::SettingsPage::icons,"Original icon page uses explicit prepared source pictures");const auto beforeBurst=raster.stats().rasterizations;for(unsigned n=0;n<32;++n)state.scroll({200,100},7,1.8);check(raster.stats().rasterizations==beforeBurst,"Burst input only changes portable page before one frame");publish(1.8);scene.setFeedback("appIcon:rhineLab",true,1.9);publish(1.97);check(scene.stats().retiredParts==0&&raster.stats().entries<LayerRasterizer::maximumEntries,"Recycled page and icon controls stay bounded");
 auto invalid=modules::SettingsAppearance{};invalid.scale=100;scene.setAppearance(invalid);const auto oldObjects=renderer.stats().objects;rejects([&]{scene.syncContent(2);},"Invalid candidate rejects before replacing current scene");check(renderer.stats().objects==oldObjects,"Invalid content preserves published siblings");scene.setAppearance({});publish(2);composition.detach(renderer);check(scene.releaseResources(renderer),"Detached Settings releases retained local/output resources");finished=true;check(renderer.stats().nativeGroups==0&&renderer.stats().textures==0&&!IsWindowVisible(window.hwnd)&&renderer.stats().presents==0,"No real UI/provider or resident resource leak");}
}
void*operator new(std::size_t n){if(countAllocations)++allocations;if(void*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void operator delete(void*p)noexcept{std::free(p);}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete[](void*p)noexcept{std::free(p);}void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
int wmain(int argc,wchar_t**argv){const auto com=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(com)&&argc==3,"Pass shader and original icon root");run(argv[1],argv[2]);CoUninitialize();std::cout<<"Settings scene: "<<checks<<" checks passed\n";return 0;}catch(const std::exception&e){countAllocations=false;if(SUCCEEDED(com))CoUninitialize();std::cerr<<"Settings scene after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
