#include "modules/settings_safety.hpp"
#include <fstream>
#include <iostream>
#include <cmath>
using namespace endfield;using namespace modules;using ehud::data::Json;
namespace {unsigned checks{};double maximum{};void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(s);}void close(double a,double b,double tolerance,const char*s){const auto delta=std::abs(a-b);maximum=std::max(maximum,delta);check(delta<=tolerance,s);}void color(const SettingsSafetyColor&a,const Json&b){for(unsigned n=0;n<4;++n)close(a[n],b.array()[n].number(),n<3?1.3e-7:2e-12,"Actual CA color interpolation");}
void run(const Json&fixture){const SettingsSafetyColor identical{250./255,212./255,31./255,.9};for(double phase:{-.1,0.,.01,.3,.99,1.,2.})check(settingsSafetyInterpolateColor(identical,identical,phase)==identical,"Unanimated source color remains bit-identical without a phantom repaint");check(fixture["actualSource"].boolean()&&fixture["ownOffscreenNonactivatingPanel"].boolean()&&!fixture["screenCaptured"].boolean(),"Actual isolated source feedback oracle");for(const auto&record:fixture["records"].array()){SettingsController controller(ehud::data::Settings::defaults());SettingsSafety state(controller);SettingsAppearance appearance;appearance.dark=record["dark"].boolean();state.setAppearance(appearance);controller.previewScale(1.2,0);state.refresh(0);const bool press=record["action"].string()=="press";if(press)state.pointerMove(0,1);else state.key(37,false,1);check(state.feedbackAnimating(1)&&state.requiresFrames(1),"Source button state starts finite feedback demand");for(const auto&animation:record["animations"].array()){close(animation["duration"].number(),.12,0,"Actual implicit transaction duration");const auto&t=animation["timing"].array();close(t[0].array()[0].number(),.25,0,"Actual default timing x1");close(t[0].array()[1].number(),float(.1),0,"Actual default timing y1 Float boundary");close(t[1].array()[0].number(),.25,0,"Actual default timing x2");close(t[1].array()[1].number(),1,0,"Actual default timing y2");}
for(const auto&row:record["samples"].array()){const auto phase=row["phase"].number();const auto paint=state.buttonPaint(0,1+.12*phase);color(paint.fill,row["fill"]);color(paint.stroke,row["stroke"]);close(paint.width,row["width"].number(),2e-12,"Actual CA scalar line-width interpolation");}check(!state.feedbackAnimating(1.121)&&!state.requiresFrames(1.121),"Feedback has no steady timer/frame work");if(press){const auto&interrupt=record["interruption"];const auto time=1+.12*interrupt["phase"].number();state.pointerMove({},time);const auto paint=state.buttonPaint(0,time);color(paint.fill,interrupt["from"]["fillColor"]);color(paint.stroke,interrupt["from"]["strokeColor"]);check(state.feedbackAnimating(time)&&!state.feedbackAnimating(time+.121),"Interrupted feedback starts from the displayed state and remains finite");}
state.setReduceMotion(true,2);state.pointerMove(1,2);check(!state.feedbackAnimating(2)&&state.buttonPaint(1,2).fill[3]==.2,"Reduce motion applies exact final button colors immediately");}
}
}
int main(int argc,char**argv){try{check(argc==2,"Pass original Settings feedback fixture");std::ifstream in(argv[1]);check(in.good(),"Read fixture");run(Json::parse(std::string{std::istreambuf_iterator<char>(in),{}}));std::cout<<"Settings safety feedback: "<<checks<<" original CA checks; max component error "<<maximum<<'\n';}catch(const std::exception&e){std::cerr<<"Settings safety feedback after "<<checks<<": "<<e.what()<<'\n';return 1;}}
