#include "modules/settings_safety.hpp"
#include <fstream>
#include <iostream>
#include <cmath>
using namespace endfield;using namespace modules;using ehud::data::Json;
namespace {unsigned checks{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}void close(double a,double b,const char*s){check(std::abs(a-b)<2e-6,s);}void box(core::Rect r,const Json&v){const auto&a=v.array();close(r.x,a[0].number(),"Original rect x");close(r.y,a[1].number(),"Original rect y");close(r.width,a[2].number(),"Original rect width");close(r.height,a[3].number(),"Original rect height");}
void run(const Json&oracle){SettingsController controller(ehud::data::Settings::defaults());SettingsSafety state(controller);controller.previewScale(1.2,0);state.refresh(0);check(state.modal()&&state.focused()==1&&state.pose(0).opacity==0,"Source preview starts modal, confirm-focused and transparent");const auto unchangedRevision=state.revision();const auto*unchangedText=state.strings().message.data();for(unsigned n=0;n<100;++n)state.refresh(n*.001);check(state.revision()==unchangedRevision&&state.strings().message.data()==unchangedText,"Warm pointer-clock checks retain the unchanged source countdown text");check(state.pose(.08).opacity>0&&state.pose(.08).opacity<1&&state.requiresFrames(.08)&&!state.requiresFrames(.21),"Finite source opacity/depth demand");for(const auto&row:oracle["cases"].array()){const core::Rect viewport{0,0,row["width"].number(),800};const auto geometry=SettingsSafety::geometry(viewport);box(geometry.card,row["card"]);check(row["rootGroupOpacity"].boolean()&&row["cardGroupOpacity"].boolean(),"Actual source requires modal group alpha");SettingsAppearance appearance;appearance.dark=row["dark"].boolean();const auto art=prepareSettingsSafetyArtwork(state,viewport,appearance);const auto&children=art.layers["children"].array();check(children.size()==9,"Four artwork leaves plus five source native text cells");const auto&controls=row["controls"].array();for(unsigned n=0;n<5;++n){const auto&text=children[n+4];const auto&control=controls[n];const auto&p=text["position"].array();const auto&b=text["bounds"].array();auto expected=control["frame"].array();if(n>=3){expected[1]=expected[1].number()+control["titleRect"].array()[1].number();expected[3]=control["titleRect"].array()[3];}box({p[0].number(),p[1].number(),b[2].number(),b[3].number()},expected);check(text["text"]["string"]==control["value"]&&text["text"]["font"]["postScriptName"]==control["font"]["name"],"Actual native source label/font");close(text["text"]["fontSize"].number(),control["font"]["size"].number(),"Actual source text size");}
 const auto&source=row["artwork"].array()[0];const auto&plate=children[0];check(plate["shape"]["path"].array().size()==source["path"].array().size(),"Source card cut-corner topology");for(std::size_t n=0;n<source["path"].array().size();++n){const auto&a=plate["shape"]["path"].array()[n];const auto&b=source["path"].array()[n];check(a["op"]==b["op"],"Source card path op");for(std::size_t k=0;k<a["points"].array().size();++k){close(a["points"].array()[k].array()[0].number()+.5,b["points"].array()[k].array()[0].number(),"Source card path x");close(a["points"].array()[k].array()[1].number()+.5,b["points"].array()[k].array()[1].number(),"Source card path y");}}for(unsigned n=0;n<4;++n)close(plate["shape"]["fillColor"]["sRGB"].array()[n].number(),source["fill"].array()[n].number(),"Source card fill");}
 state.key(37,false,.25);check(state.focused()==0,"Left selects revert");check(state.key(32,false,.3)&&!controller.scalePending()&&state.modal()&&state.pose(.3).dismissing,"Space executes focused action and modal input persists through fade");check(state.key(13,false,.31)&&!controller.scalePending(),"Dismissing modal consumes repeated underlying shortcuts");state.refresh(.45);check(!state.modal(),"Finite retract releases modal state");controller.previewPosition(.2,-.1,.5);state.refresh(.5);check(state.strings().title=="Keep this position?"&&state.focused()==1,"Position preview uses source message and resets confirm focus");state.pointerDown(1,.6);state.pointerUp(0,.6);check(controller.positionPending(),"Press/release across different actions never confirms");state.pointerDown(1,.7);state.pointerUp(1,.7);check(!controller.positionPending()&&controller.committed().number("hudOffsetX")==.2,"Same projected control confirms source layout");state.refresh(.9);controller.previewScale(2,1);state.refresh(1);controller.wake(13);state.refresh(13);check(!controller.scalePending()&&state.pose(13).dismissing,"Shared owner timeout dismisses safe overlay");state.setReduceMotion(true,13);check(!state.modal()&&!state.requiresFrames(13),"Reduced motion settles dismissal immediately");
 auto transform=core::Matrix4::translation(600,400)*core::Matrix4::scale(2,2);const auto centered=SettingsSafety::centeredSourceTransform(transform,2);for(unsigned n=0;n<16;++n)close(centered.values[n],core::Matrix4{}.values[n],"Source centered projection removes unsafe scale/position");}
}
int main(int argc,char**argv){try{check(argc==2,"Pass detached original safety fixture");std::ifstream in(argv[1]);check(in.good(),"Read source fixture");run(Json::parse(std::string{std::istreambuf_iterator<char>(in),{}}));std::cout<<"Settings safety: "<<checks<<" source checks passed\n";}catch(const std::exception&e){std::cerr<<"Settings safety after "<<checks<<": "<<e.what()<<'\n';return 1;}}
