#ifdef _WIN32
#include "tools/settings_preview.hpp"
#include "native/module_scene.hpp"
#include <windows.h>
#include <objbase.h>
#include <iostream>
namespace {namespace c=endfield::core;namespace gpu=endfield::native;namespace a=endfield::app;namespace t=endfield::tools;namespace m=endfield::modules;using Json=ehud::data::Json;unsigned checks{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}
struct Window{HWND hwnd{};Window(){WNDCLASSW c{};c.lpfnWndProc=DefWindowProcW;c.hInstance=GetModuleHandleW(nullptr);c.lpszClassName=L"EndfieldSettingsOwnerHidden";check(RegisterClassW(&c)!=0,"Register owned hidden fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,c.lpszClassName,L"Synthetic",WS_POPUP,0,0,1280,800,nullptr,nullptr,c.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Fixture remains hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);UnregisterClassW(L"EndfieldSettingsOwnerHidden",GetModuleHandleW(nullptr));}};
void run(const std::filesystem::path&shader){Window window;gpu::Renderer renderer;renderer.initialize(window.hwnd,1280,800,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});const auto camera=gpu::layerViewportProjection(1280,800);renderer.setCamera(camera);gpu::LayerRasterizer raster;gpu::LayerComposition composition;std::vector<ehud::data::Settings>saves;std::vector<bool>captures;unsigned registrations{};t::SettingsPreviewOptions options;options.raster.pixelsPerPoint=1;options.initial.set("launchAtLogin",false);options.callbacks.persist=[&](const auto&s){saves.push_back(s);};options.callbacks.shortcutCapture=[&](bool b){captures.push_back(b);};options.callbacks.registerShortcut=[&](auto)->std::optional<std::string>{++registrations;return {};};options.callbacks.launchAtLogin=[](bool)->std::optional<std::string>{return "Injected unavailable startup integration";};options.viewHooks.displays=[](){return std::vector<m::SettingsDisplay>{{"fixture-display","Synthetic Display","1920 × 1080"}};};t::SettingsPreview owner(raster,options);owner.resize({1280,800,96,1,1280,800});owner.setReduceMotion(true,0);c::ModulePresentation modules{c::Module::system};c::source::DesktopChromeSettings settings{{0,0,1280,800},1,{},c::Module::system,true};auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;gpu::LayerScene geometry(raster);geometry.load(Json::Object{{"bounds",Json::Array{0,0,400,334}},{"children",Json::Array{}}},{});double now{};bool finished{};
 struct Cleanup{gpu::Renderer&r;gpu::LayerComposition&c;t::SettingsPreview&o;bool&done;~Cleanup(){if(!done)try{c.detach(r);o.release(r);}catch(...){r.reset();}}}cleanup{renderer,composition,owner,finished};
 const auto frame=[&]{now+=.01;const auto sample=modules.sample(now).presentation;settings.module=sample.requested;owner.update(center,settings,sample,1,now);owner.upload(renderer);composition.setEntries(renderer,owner.entries());composition.present(renderer);owner.collected(renderer);};
 const auto point=[&](c::Point p){auto sample=modules.sample(now).presentation;gpu::NativeModuleSurface plane(geometry,sample.current.module);plane.update(center,settings,sample.current,1);const auto q=c::Projection::viewport(camera*plane.pose().contentWorld,1280,800).project(p);check(bool(q),"Exact current Settings plane projects");return *q;};
 const auto click=[&](c::Point p){const auto q=point(p);check(owner.covers(q)&&owner.pointer({a::PointerKind::down,a::PointerButton::left,q.x,q.y},now),"Original Settings action receives projected press");owner.pointer({a::PointerKind::up,a::PointerButton::left,q.x,q.y},now);frame();};frame();check(!owner.entries().empty()&&saves.empty()&&!owner.nextWakeTime(now),"First Settings screen has no service/IO/deadline");click({300,95});check(!owner.controller().configuration().boolean("launchAtLogin")&&owner.controller().status()=="Injected unavailable startup integration"&&saves.empty(),"Unavailable platform leaves checkbox and committed preferences unchanged");click({300,135});check(!saves.empty(),"Source preference reaches injected save callback");click({300,175});click({100,143});check(owner.controller().configuration().fields["windowsDisplayID"].string()=="fixture-display","Selected Windows display keeps native identity separately from Mac UUID");
 modules.select(c::Module::hotkeys,now,false,true);frame();click({270,60});check(owner.pointerLocked()&&captures==std::vector<bool>{true},"Shortcut recording gates the host native chord service");check(owner.key({a::KeyKind::down,0x77},3,now),"Injected two-modifier F8 capture");frame();check(!owner.pointerLocked()&&registrations==1&&captures==std::vector<bool>({true,false})&&m::settingsShortcut(owner.controller().configuration())==m::SettingsShortcut{0x77,3},"Successful hotkey record commits once and restores host registration");
 modules.select(c::Module::display,now,false,true);frame();auto q=point({300,55});check(owner.pointer({a::PointerKind::down,a::PointerButton::left,q.x,q.y},now)&&owner.pointerLocked(),"Actual slider drag alone locks gyro");const auto count=saves.size();q=point({350,55});owner.pointer({a::PointerKind::move,a::PointerButton::none,q.x,q.y},now);frame();check(!owner.controller().scalePending()&&saves.size()==count,"Slider keeps staged geometry until mouse up");owner.pointer({a::PointerKind::up,a::PointerButton::left,q.x,q.y},now);frame();check(owner.controller().scalePending()&&owner.nextWakeTime(now)&&saves.size()==count,"Source confirmation starts without persisting unsafe scale");check(owner.covers({2,2})&&!owner.pointerLocked()&&owner.wheel({2,2,1},now)&&owner.key({a::KeyKind::down,0x41},0,now)&&saves.size()==count,"Scale safety consumes background input without locking tilt or saving");owner.wake(now+12.1);now+=12.1;frame();check(!owner.controller().scalePending()&&!owner.nextWakeTime(now)&&saves.size()==count,"Shared host deadline restores unconfirmed geometry");owner.controller().previewScale(1.6,now);frame();check(owner.key({a::KeyKind::down,VK_RETURN},0,now),"Modal Enter reaches the initially focused Keep action");frame();check(!owner.controller().scalePending()&&owner.controller().committed().number("hudScale")==1.6&&saves.size()==count+1,"Keyboard Keep commits unsafe layout exactly once");owner.controller().previewPosition(.2,-.1,now);frame();check(owner.key({a::KeyKind::down,VK_ESCAPE},0,now),"Modal Escape reaches Revert before the HUD close route");frame();check(!owner.controller().positionPending()&&saves.size()==count+1,"Modal Revert never saves pending coordinates");owner.controller().previewPosition(.2,-.1,now);owner.setOverlayVisible(false,now);frame();check(!owner.controller().positionPending()&&!owner.requiresFrames(now),"Closing reverts pending layout and cancels Settings demand");owner.setOverlayVisible(true,now);modules.select(c::Module::power,now,false,true);frame();check(owner.entries().empty()&&renderer.stats().nativeGroups==0,"Inactive Settings drops raster/group resources after publication");composition.detach(renderer);owner.release(renderer);finished=true;check(!IsWindowVisible(window.hwnd)&&renderer.stats().presents==0,"Fixture never opens real UI or activates native services");}
}
int wmain(int argc,wchar_t**argv){const auto com=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(com)&&argc==2,"Pass HLSL shader");run(argv[1]);CoUninitialize();std::cout<<"Settings owner: "<<checks<<" checks passed\n";return 0;}catch(const std::exception&e){if(SUCCEEDED(com))CoUninitialize();std::cerr<<"Settings owner after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
