#include "modules/settings_presentation.hpp"
#include <fstream>
#include <iostream>
#include <cmath>
using namespace endfield;using namespace modules;using ehud::data::Json;
namespace {unsigned checks{};std::string context;void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(context+": "+s);}void close(double a,double b,const char*s){if(std::abs(a-b)>2e-6)std::cerr<<"actual "<<a<<" expected "<<b<<'\n';check(std::abs(a-b)<=2e-6,s);}Json read(const char*file){std::ifstream in(file);check(in.good(),"Explicit fixture opened");return Json::parse(std::string{std::istreambuf_iterator<char>(in),{}},32*1024*1024);}
struct Leaf{Json node;double x{},y{};};void flatten(const Json&n,std::vector<Leaf>&out,double x=0,double y=0){const auto&b=n["bounds"].array();const auto&p=n["position"].array();const auto&a=n["anchorPoint"].array();x+=p[0].number()-a[0].number()*b[2].number()-b[0].number();y+=p[1].number()-a[1].number()*b[3].number()-b[1].number();const auto k=n["kind"].string();if(k=="text"||k=="shape"||!n["backgroundColor"].isNull()||!n["contents"].isNull()||!n["requiredSourceImage"].isNull())out.push_back({n,x,y});for(const auto&c:n["children"].array())flatten(c,out,x,y);}
void color(const Json&a,const Json&b){if(a.isNull()||b.isNull()){check(a.isNull()&&b.isNull(),"Optional color");return;}for(unsigned k=0;k<4;++k)close(a["sRGB"].array()[k].number(),b["sRGB"].array()[k].number(),"Source sRGB color");}
void compare(const Leaf&a,const Leaf&b){const auto&n=a.node;const auto&o=b.node;context+=" / "+n["id"].string();check(n["kind"]==o["kind"],"Source layer kind");if(n["kind"].string()=="shape"){const auto&s=n["shape"];const auto&t=o["shape"];color(s["fillColor"],t["fillColor"]);color(s["strokeColor"],t["strokeColor"]);close(s["lineWidth"].number(),t["lineWidth"].number(),"Source line width");check(s["path"].array().size()==t["path"].array().size(),"Source path command count");for(std::size_t i=0;i<s["path"].array().size();++i){const auto&u=s["path"].array()[i];const auto&v=t["path"].array()[i];check(u["op"]==v["op"],"Original path command");check(u["points"].array().size()==v["points"].array().size(),"Original path arity");for(std::size_t k=0;k<u["points"].array().size();++k){close(a.x+u["points"].array()[k].array()[0].number(),b.x+v["points"].array()[k].array()[0].number(),"Source path x");close(a.y+u["points"].array()[k].array()[1].number(),b.y+v["points"].array()[k].array()[1].number(),"Source path y");}}}
 else{close(a.x,b.x,"Source surface x");close(a.y,b.y,"Source surface y");for(unsigned k=2;k<4;++k)close(n["bounds"].array()[k].number(),o["bounds"].array()[k].number(),"Source leaf dimensions");color(n["backgroundColor"],o["backgroundColor"]);}
 if(n["kind"].string()=="text"){for(auto key:{"string","fontSize","wrapped","truncation","alignment"})if(n["text"][key]!=o["text"][key]){std::cerr<<"text key "<<key<<" actual "<<n["text"][key].encode()<<" expected "<<o["text"][key].encode()<<'\n';check(false,"Original text descriptor");}for(auto key:{"postScriptName","familyName","symbolicTraits"})check(n["text"]["font"][key]==o["text"]["font"][key],"Original font descriptor");color(n["text"]["foregroundColor"],o["text"]["foregroundColor"]);close(n["contentsScale"].number(),o["contentsScale"].number(),"Original text density");}
 if(!n["requiredSourceImage"].isNull())check(!o["contents"].isNull()&&n["contentsGravity"]==o["contentsGravity"],"Original icon remains explicit supplied artwork dependency");}
void oracle(const Json&fixture,const Json&manifest){auto initial=ehud::data::Settings::defaults();initial.set("language","english");initial.set("theme","dark");initial.set("launchAtLogin",false);initial.set("reduceMotion",true);SettingsCallbacks cb;cb.registerShortcut=[](auto){return std::optional<std::string>{};};SettingsController c(initial,cb);SettingsUpdateStatus status;status.automaticallyInstalls=status.canCheck=status.canSetAutomatic=true;c.setUpdateStatus(status);std::vector<SettingsIcon>icons;for(const auto&i:manifest["icons"].array())if(i["offered"].boolean())icons.push_back({i["id"].string(),i["title"].string()});SettingsViewHooks hooks;hooks.displays=[](){return std::vector<SettingsDisplay>{{"00000000-0000-4000-8000-000000000010","Fixture Display","1920 × 1080"}};};std::size_t checkpoint{};
 for(auto module:{core::Module::system,core::Module::display,core::Module::hotkeys,core::Module::about}){SettingsPresentation s(module,c,icons,{},hooks);s.setReduceMotion(true,0);s.activate(0);SettingsAppearance appearance;
 const auto verify=[&](const char*name){const auto&expected=fixture["artwork"].array().at(checkpoint++);context=expected["module"].string()+"/"+name;check(expected["name"].string()==name,"Original checkpoint sequence");const auto&v=s.view();close(v.scroll,expected["scroll"].number(),"Source scroll");check(v.accessibilityStatus==expected["status"].string(),"Original accessibility status");check(v.actions.size()==expected["actions"].array().size(),"Original action count");for(std::size_t n=0;n<v.actions.size();++n){const auto&a=v.actions[n];const auto&b=expected["actions"].array()[n];if(a.label!=b["label"].string())std::cerr<<a.label<<" != "<<b["label"].string()<<'\n';check(a.id==b["id"].string()&&a.label==b["label"].string()&&a.enabled==b["enabled"].boolean(),"Original action identity/label/state");const auto&r=b["rect"].array();close(a.rect.x,r[0].number(),"Hit x");close(a.rect.y,r[1].number(),"Hit y");close(a.rect.width,r[2].number(),"Hit w");close(a.rect.height,r[3].number(),"Hit h");}
 check(v.sliders.size()==expected["sliders"].array().size(),"Original slider count");for(std::size_t n=0;n<v.sliders.size();++n){const auto&a=v.sliders[n];const auto&b=expected["sliders"].array()[n];check(a.id==b["id"].string()&&a.label==b["label"].string()&&a.formatted==b["formatted"].string(),"Original slider labels");close(a.value,b["value"].number(),"Slider value");close(a.minimum,b["minimum"].number(),"Slider min");close(a.maximum,b["maximum"].number(),"Slider max");}
 auto art=prepareSettingsArtwork(v,appearance);std::vector<Leaf>actual,original;for(const auto&r:art.rows)flatten(r.layers,actual);flatten(art.chrome.layers,actual);flatten(expected["layer"],original);check(actual.size()==original.size(),"Original painted leaf count");const auto prefix=context;for(std::size_t n=0;n<actual.size();++n){context=prefix+" leaf"+std::to_string(n);compare(actual[n],original[n]);}
 };
 const auto find=[&](std::string_view id){s.scroll({200,100},-10000,0);for(unsigned n=0;n<20;++n){for(const auto&a:s.view().actions)if(a.id==id){check(s.perform(id,0),"Original action executes");return;}s.scroll({200,100},100,0);}check(false,"Original action discoverable through scrolling");};verify("main");s.scroll({200,100},10000,0);verify("bottom");if(module==core::Module::system){for(const auto id:{"language","screen","restore"}){find(id);verify(id);s.escape(0);}}else if(module==core::Module::display){for(const auto id:{"battery","centerLogo","appIcon"}){find(id);verify(id);if(std::string_view(id)=="battery"){find("metric");verify("metric");s.escape(0);}if(std::string_view(id)=="appIcon"){s.scroll({200,100},10000,0);verify("iconsBottom");}s.escape(0);}s.scroll({200,100},-10000,0);appearance.dark=false;verify("light");s.mouseDown({300,55},0);s.mouseDragged({350,55},0);verify("stagedScale");s.mouseUp(0);c.revertLayout();}else if(module==core::Module::hotkeys){find("capture");verify("capture");s.escape(0);}s.deactivate(0);}
 check(checkpoint==fixture["artwork"].array().size(),"All original artwork states checked");}
}
int main(int argc,char**argv){try{check(argc==3,"Pass actual source oracle and original icon roster");oracle(read(argv[1]),read(argv[2]));std::cout<<"Settings presentation: "<<checks<<" original artwork checks passed\n";}catch(const std::exception&e){std::cerr<<"Settings presentation after "<<checks<<": "<<e.what()<<'\n';return 1;}}
