#include "core/source_desktop_content.hpp"
#include "core/source_color.hpp"
#include "core/data/json.hpp"
#include <cmath>
#include <fstream>
#include <iostream>
#include <limits>
#include <set>
using namespace endfield::core;using namespace source;using ehud::data::Json;
namespace {unsigned checks{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}template<class F>void rejects(F f){bool yes{};try{f();}catch(const std::exception&){yes=true;}check(yes,"Invalid source content must reject");}
Language language(std::string_view s){if(s=="english")return Language::english;if(s=="simplifiedChinese")return Language::simplifiedChinese;if(s=="traditionalChinese")return Language::traditionalChinese;if(s=="japanese")return Language::japanese;if(s=="korean")return Language::korean;throw std::runtime_error("Unknown fixture language");}
void run(const Json&j){double error{};for(const auto&sample:j["colors"].array()){SourceRGB rgb{};for(unsigned n=0;n<3;++n)rgb[n]=sample["input"].array()[n].number();const auto output=selectedCaptionColor(rgb);const auto light=sourceBlackBlend(rgb,.35);for(unsigned n=0;n<3;++n)check(std::abs(light[n]-sample["lightOutput"].array()[n].number())<.006,"Light source chrome blend stays within measured ColorSync bound");for(unsigned n=0;n<3;++n){error=std::max(error,std::abs(output[n]-sample["output"].array()[n].number()));check(std::abs(output[n]-sample["output"].array()[n].number())<.006,"Source selected-caption profile conversion stays within measured ColorSync bound");}}
 double whiteError{},lightWhiteError{};std::size_t whiteSamples{};
 for(const auto&sample:j["colors"].array())if(sample.contains("whiteOutput")){
  ++whiteSamples;SourceRGB rgb{};for(unsigned n=0;n<3;++n)rgb[n]=sample["input"].array()[n].number();const auto white=sourceWhiteBlend(rgb,.42),lightWhite=sourceWhiteBlend(sourceBlackBlend(rgb,.35),.42);
  for(unsigned n=0;n<3;++n){whiteError=std::max(whiteError,std::abs(white[n]-sample["whiteOutput"].array()[n].number()));lightWhiteError=std::max(lightWhiteError,std::abs(lightWhite[n]-sample["lightWhiteOutput"].array()[n].number()));check(std::abs(white[n]-sample["whiteOutput"].array()[n].number())<.004,"Storage source white blend stays within original AppKit bound");check(std::abs(lightWhite[n]-sample["lightWhiteOutput"].array()[n].number())<.004,"Light Storage compound source blend stays within original AppKit bound");}
 }
 check(!whiteSamples||whiteSamples==j["colors"].array().size(),"Original white blend samples cover every measured accent");
 rejects([&]{sourceWhiteBlend({0,0,0},-1);});rejects([&]{sourceWhiteBlend({0,0,0},std::numeric_limits<double>::infinity());});rejects([&]{sourceWhiteBlend({0,std::numeric_limits<double>::quiet_NaN(),0},.42);});check(sourceWhiteBlend({.2,.3,.4},0)==SourceRGB{.2,.3,.4}&&sourceWhiteBlend({.2,.3,.4},1)==SourceRGB{1,1,1},"White-blend endpoints remain exact");
 std::cout<<"white samples="<<whiteSamples<<" profile max="<<whiteError<<" light compound max="<<lightWhiteError<<'\n';
 for(const auto&f:j["fonts"].array()){const auto size=f["size"].number();check(size*.966796875==f["ascender"].number()&&size*-.2109375==f["descender"].number()&&f["leading"].number()==0,"All original medium/bold baseline metrics remain exact");}
 std::set<std::string>slots;std::size_t requests{};for(const auto&c:j["cases"].array()){slots.insert(c["button"].string());const auto&expected=c["expected"];const auto&r=j["measurements"].array()[static_cast<std::size_t>(c["measurement"].integer())];
  const auto measure=[&](std::string_view text,double size,bool bold,double width,bool wrapped){++requests;if(text!=r["text"].string()||width!=r["width"].number()||bold!=r["bold"].boolean()||wrapped!=r["wrapped"].boolean())std::cerr<<"case="<<c.encode()<<" actualText="<<text<<" width="<<width<<" bold="<<bold<<" wrap="<<wrapped<<" expected="<<r.encode()<<"\n";check(text==r["text"].string()&&width==r["width"].number()&&bold==r["bold"].boolean()&&wrapped==r["wrapped"].boolean(),"Caption fitting asks for exact original string/area/weight/wrap");const auto&pair=r["sizes"].array()[static_cast<std::size_t>(size*2-20)].array();return DesktopTextSize{pair[0].number(),pair[1].number()};};
  DesktopCaptionRequest request;const auto target=c["target"].string(),title=c["title"].string();request.target=target;request.title=title;request.authoredSize={c["authoredSize"].array()[0].number(),c["authoredSize"].array()[1].number()};request.language=language(c["language"].string());request.module=c["module"].boolean();request.rightSlot=c["right"].boolean();request.selected=c["selected"].boolean();request.dark=c["dark"].boolean();const auto plan=sourceDesktopCaption(request,measure);
  check(plan.text==expected["text"].string()&&plan.fontSize==expected["fontSize"].number(),"Caption text/font fitting matches original desktop export");check(plan.bold==expected["bold"].boolean()&&plan.wrapped==expected["wrapped"].boolean()&&plan.ellipsis==expected["ellipsis"].boolean(),"Caption wrap/weight/truncation matches original desktop export");
  // Local rectangle uses evaluated geometry during runtime. The fit uses its
  // source authored dimensions; these export variants retain the same size.
  check(plan.size.width==expected["bounds"].array()[2].number()&&plan.size.height==expected["bounds"].array()[3].number(),"Source caption expanded bounds match export");for(unsigned n=0;n<4;++n)check(std::abs(plan.color[n]-expected["color"].array()[n].number())<2e-6,"Default accent and palette match source caption colors");
 }
 check(slots.size()==24&&j["cases"].array().size()==1000,"All original recycled/fixed slots, languages, selections and custom examples were compared");
 const DesktopCaptionMeasure empty=[](auto,double,bool,double,bool){return DesktopTextSize{};};DesktopCaptionRequest request{"custom","Arbitrary caller title",{100,40}};request.module=false;const auto custom=sourceDesktopCaption(request,empty);check(custom.text==request.title&&!custom.wrapped&&custom.ellipsis,"Arbitrary custom strings are not replaced with finite presets");request.title="\xff";rejects([&]{sourceDesktopCaption(request,empty);});rejects([&]{selectedCaptionColor({0,0,std::numeric_limits<double>::quiet_NaN()});});rejects([&]{colorAtWheel({std::numeric_limits<double>::infinity(),0});});rejects([&]{sourceBlackBlend({0,0,0},-1);});check(sourceBlackBlend({.2,.3,.4},0)==SourceRGB{.2,.3,.4}&&sourceBlackBlend({.2,.3,.4},1)==SourceRGB{},"Black-blend endpoints remain exact");
 struct Probe{double h,r,g,b;};for(auto p:{Probe{0,1,.3983038663864136,.3702169358730316},Probe{.08,1,.6964329481124878,.369477242231369},Probe{1./6,.9994924664497375,.9872058033943176,.3682177662849426},Probe{.25,.69842129945755,.9825108647346497,.3697151839733124},Probe{.5,.33565735816955566,.9924101233482361,1},Probe{.75,.7155163884162903,.4236825108528137,1}}){const auto c=colorAtWheel({(.7*std::cos(p.h*6.283185307179586)+1)*.5,(.7*std::sin(p.h*6.283185307179586)+1)*.5});check(std::abs(c[0]-p.r)<1./255&&std::abs(c[1]-p.g)<1./255&&std::abs(c[2]-p.b)<1./255&&c[3]==1,"Shared source wheel retains original AppKit color bound");}
 check(colorWheelPoint({0,0,0,1})==Point{.5,.5}&&colorWheelPoint({1,0,0,1})==Point{1,.5},"Source wheel marker retains calibrated control convention");std::cout<<"caption samples="<<j["cases"].array().size()<<" measure requests="<<requests<<" selected profile max="<<error<<'\n';
}
}
int main(int argc,char**argv){try{check(argc==2,"Pass original desktop content source fixture");std::ifstream input(argv[1]);const std::string bytes((std::istreambuf_iterator<char>(input)),{});run(Json::parse(bytes,8*1024*1024));std::cout<<"Desktop content: "<<checks<<" checks passed\n";}catch(const std::exception&e){std::cerr<<"Desktop content after "<<checks<<": "<<e.what()<<'\n';return 1;}}
