#include "native/storage_files.hpp"
#include "native/storage_details_probe.hpp"
#include "core/data/json.hpp"
#include <fstream>
#include <limits>
#include <atomic>
#include <condition_variable>
#include <iostream>
#include <map>
#include <mutex>
#include <stdexcept>
#include <thread>
#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#include <objbase.h>
#include <filesystem>
#include <fstream>
#endif
namespace n=endfield::native;namespace m=endfield::modules;namespace a=endfield::app;
namespace {unsigned checks{};void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}template<class F>void rejects(F&&f,const char*s){bool rejected{};try{f();}catch(const std::invalid_argument&){rejected=true;}check(rejected,s);}
n::StorageFileMetadata meta(unsigned id,n::StorageFileKind kind=n::StorageFileKind::regular,std::int64_t bytes=10,std::uint64_t volume=7){n::StorageFileMetadata m;m.kind=kind;m.allocatedBytes=bytes;m.identity.volume=volume;for(unsigned i=0;i<4;++i)m.identity.file[i]=static_cast<std::uint8_t>(id>>(i*8));return m;}
struct Node {n::StorageFileMetadata value;std::vector<std::pair<std::u16string,std::shared_ptr<Node>>>children;bool deny{},failRead{};std::optional<n::StorageFileMetadata>openedOverride;};
struct Fake: n::StorageFileSystem {std::map<std::string,std::shared_ptr<Node>,std::less<>>roots;std::size_t opens{},reads{},live{},peak{};std::function<void()>onRead;
    struct Cursor:n::StorageDirectory {Fake&fs;std::shared_ptr<Node>node;std::size_t index{};Cursor(Fake&f,std::shared_ptr<Node>n):fs(f),node(std::move(n)){fs.peak=std::max(fs.peak,++fs.live);}~Cursor(){--fs.live;}const n::StorageFileMetadata&metadata()const noexcept override{return node->openedOverride?*node->openedOverride:node->value;}n::StorageDirectoryRead next(n::StorageDirectoryEntry&out)override{++fs.reads;if(fs.onRead)fs.onRead();if(node->failRead)return n::StorageDirectoryRead::error;if(index==node->children.size())return n::StorageDirectoryRead::end;const auto&entry=node->children[index++];out={entry.first,entry.second->value};return n::StorageDirectoryRead::entry;}std::unique_ptr<n::StorageDirectory>openChild(std::u16string_view name)override{++fs.opens;for(const auto&entry:node->children)if(entry.first==name){if(entry.second->deny)return {};return std::make_unique<Cursor>(fs,entry.second);}return {};}};
    std::unique_ptr<n::StorageDirectory>openRoot(std::string_view path)override{++opens;const auto i=roots.find(path);return i==roots.end()||i->second->deny?nullptr:std::make_unique<Cursor>(*this,i->second);}
};
std::shared_ptr<Node>node(unsigned id,n::StorageFileKind kind=n::StorageFileKind::regular,std::int64_t bytes=10){auto p=std::make_shared<Node>();p->value=meta(id,kind,bytes);return p;}
void accounting(){Fake fs;auto root=node(1,n::StorageFileKind::directory),second=node(2,n::StorageFileKind::directory),child=node(3,n::StorageFileKind::directory);auto shared=node(11),large=node(12,n::StorageFileKind::regular,4096),link=node(13,n::StorageFileKind::symbolicLink,10000),cloud=node(14,n::StorageFileKind::directory);cloud->value.unavailable=true;auto junction=node(15,n::StorageFileKind::reparse);auto mounted=node(16,n::StorageFileKind::directory);mounted->value.identity.volume=8;auto denied=node(17,n::StorageFileKind::directory);denied->deny=true;auto replaced=node(18,n::StorageFileKind::directory);replaced->openedOverride=meta(99,n::StorageFileKind::directory);root->children={{u".",node(1,n::StorageFileKind::directory)},{u"a",shared},{u"dir",child},{u"link",link},{u"cloud",cloud},{u"mount",mounted},{u"junction",junction},{u"denied",denied},{u"replaced",replaced}};child->children={{u"data",large}};second->children={{u"hardlink",shared},{u"empty",node(19,n::StorageFileKind::regular,0)}};fs.roots={{"one",root},{"two",second}};
    const std::array scopes{n::StorageFolderScope{"first","First",{"one"}},n::StorageFolderScope{"second","Second",{"two"}},n::StorageFolderScope{"missing","Missing",{"absent"}}};m::StorageScanCancellation cancel;const auto result=n::scanStorageFolders(scopes,cancel,123,fs,7,[]{return 0.;});check(result.updatedAt==123&&!result.isLoading&&result.categories.size()==3,"Source scan preserves ordered explicit scopes and request date");check(result.categories[0].bytes==4106&&result.categories[0].isPartial,"Source counts allocated bytes while rejecting denied/cloud/mount/replacement paths");check(result.categories[1].bytes==0&&!result.categories[1].isPartial,"Cross-scope hardlink identity is counted once, zero remains available");check(!result.categories[2].bytes&&result.categories[2].isPartial&&result.isPartial&&!result.error,"Mixed availability preserves valid partial categories");check(fs.opens==6&&fs.peak<=2&&fs.live==0,"Excluded entries never open, and bounded directory handles retire");
    Fake symlinks;auto s=node(1,n::StorageFileKind::directory);s->children={{u"link",link}};symlinks.roots["s"]=s;const std::array only{n::StorageFolderScope{"s","S",{"s"}}};const auto skipped=n::scanStorageFolders(only,cancel,0,symlinks,7,[]{return 0.;});check(skipped.categories[0].bytes==0&&!skipped.isPartial,"Source symlinks are excluded without reporting a partial category");
    m::StorageScanCancellation cancelled;cancelled.cancel();const auto before=fs.opens;const auto noWork=n::scanStorageFolders(scopes,cancelled,0,fs,7,[]{return 0.;});check(fs.opens==before&&noWork.error&&noWork.categories.size()==3,"Already cancelled scan never opens a filesystem scope");
    n::StorageFileIdentity other=shared->value.identity;other.file[15]=1;auto extended=node(11);extended->value.identity=other;s->children={{u"a",shared},{u"b",extended}};const auto wide=n::scanStorageFolders(only,cancel,0,symlinks,7,[]{return 0.;});check(wide.categories[0].bytes==20,"All128 identity bits participate in hardlink deduplication");
    auto huge=node(20,n::StorageFileKind::regular,std::numeric_limits<std::int64_t>::max());s->children={{u"huge",huge},{u"overflow",shared},{u"again",shared}};const auto overflow=n::scanStorageFolders(only,cancel,0,symlinks,7,[]{return 0.;});check(overflow.categories[0].bytes==std::numeric_limits<std::int64_t>::max()&&overflow.isPartial,"Overflow never wraps and the rejected identity remains deduplicated");
}
void bounds(){Fake fs;auto root=node(1,n::StorageFileKind::directory);for(unsigned i=0;i<12;++i)root->children.push_back({u"file"+std::u16string(i,u'x'),node(i+2)});fs.roots["r"]=root;const std::array scopes{n::StorageFolderScope{"r","R",{"r"}},n::StorageFolderScope{"again","Again",{"r"}}};m::StorageScanCancellation cancel;auto limits=m::StorageScanLimits{};limits.maximumEntries=3;auto result=n::scanStorageFolders(scopes,cancel,0,fs,7,[]{return 0.;},limits);check(result.categories[0].bytes==30&&!result.categories[1].bytes&&result.isPartial,"Global entry budget stops before another scope opens");limits={};limits.entriesPerFolder=2;result=n::scanStorageFolders(scopes,cancel,0,fs,7,[]{return 0.;},limits);check(result.categories[0].bytes==20&&result.categories[1].bytes==0&&result.categories[1].isPartial,"Per-category entry budget resets while hardlink set remains shared");
    auto child=node(100,n::StorageFileKind::directory);child->children={{u"nested",node(101)}};root->children={{u"dir",child}};limits={};limits.maximumDepth=0;const auto before=fs.opens;result=n::scanStorageFolders(scopes,cancel,0,fs,7,[]{return 0.;},limits);check(result.categories[0].bytes==0&&result.isPartial&&fs.opens==before+2,"Depth zero never opens a child directory");
    limits={};double time{};fs.onRead=[&]{time+=3;};root->children={{u"first",node(2)},{u"second",node(3)}};result=n::scanStorageFolders(scopes,cancel,0,fs,7,[&]{return time;},limits);check(result.categories[0].bytes==10&&result.categories[1].bytes==0&&result.isPartial,"Two-second category deadline checked between metadata calls");fs.onRead={};time=0;limits.maximumSeconds=0;const auto untouched=fs.opens;result=n::scanStorageFolders(scopes,cancel,0,fs,7,[&]{return time;},limits);check(fs.opens==untouched&&result.error,"Expired total deadline does not touch the filesystem");
    limits={};m::StorageScanCancellation during;fs.onRead=[&]{during.cancel();};result=n::scanStorageFolders(scopes,during,0,fs,7,[]{return 0.;},limits);check(result.categories[0].bytes==10&&!result.categories[1].bytes&&result.isPartial,"Cancellation matches source boundary after the in-progress metadata item");fs.onRead={};
    limits.maximumEntries=40001;rejects([&]{n::scanStorageFolders(scopes,cancel,0,fs,7,[]{return 0.;},limits);},"Caller cannot raise the original scanner resource ceiling");
}
void original(const char*path){using J=ehud::data::Json;std::ifstream f(path,std::ios::binary);std::string bytes((std::istreambuf_iterator<char>(f)),{});const auto doc=J::parse(bytes,2*1024*1024);check(doc["schemaVersion"].integer()==1&&doc["ownedTemporaryFilesOnly"].boolean(),"Original scanner oracle used only owned temporary data");
    const auto tree=[&](auto&&self,const J&j)->std::shared_ptr<Node>{auto out=std::make_shared<Node>();const auto kind=j["kind"].string();out->value.kind=kind=="directory"?n::StorageFileKind::directory:kind=="regular"?n::StorageFileKind::regular:kind=="symbolicLink"?n::StorageFileKind::symbolicLink:n::StorageFileKind::other;out->value.identity.volume=std::stoull(j["volume"].string());auto id=std::stoull(j["file"].string());for(unsigned i=0;i<8;++i)out->value.identity.file[i]=static_cast<std::uint8_t>(id>>(i*8));out->value.allocatedBytes=j["bytes"].integer();for(const auto&entry:j["children"].array()){const auto name=entry["name"].string();out->children.push_back({std::u16string(name.begin(),name.end()),self(self,entry["node"])});}return out;};
    for(const auto&row:doc["cases"].array()){Fake fs;for(const auto&[key,value]:doc["graph"].object())fs.roots[key]=tree(tree,value);std::vector<n::StorageFolderScope>scopes;for(const auto&key:doc["scopes"].array())scopes.push_back({key.string(),key.string(),{key.string()}});const auto&v=row["limits"];m::StorageScanLimits limits{v["maximumEntries"].integer(),v["entriesPerFolder"].integer(),v["maximumSeconds"].number(),v["secondsPerFolder"].number(),static_cast<int>(v["maximumDepth"].integer())};m::StorageScanCancellation cancel;if(row["cancelled"].boolean())cancel.cancel();const auto actual=n::scanStorageFolders(scopes,cancel,123,fs,{},[]{return 0.;},limits);check(actual.categories.size()==row["categories"].array().size(),"Original scanner category count");for(std::size_t i=0;i<actual.categories.size();++i){const auto&a=actual.categories[i];const auto&e=row["categories"].array()[i];const J actualBytes=a.bytes?J(*a.bytes):J{};if(a.id!=e["id"].string()||a.title!=e["title"].string()||actualBytes!=e["bytes"]||a.isPartial!=e["partial"].boolean())throw std::runtime_error("Original scan mismatch "+row["name"].string()+" / "+a.id);++checks;}check(actual.isPartial==row["partial"].boolean()&&(actual.error?J(*actual.error):J{})==row["error"],"Original scanner partial/error semantics match");check(actual.updatedAt==123&&!actual.isLoading&&fs.live==0,"Original scanner date and handle retirement match");}
}
struct Block {std::mutex mutex;std::condition_variable cv;bool entered{},release{};void run(){std::unique_lock l(mutex);entered=true;cv.notify_all();cv.wait(l,[&]{return release;});}void wait(){std::unique_lock l(mutex);if(!cv.wait_for(l,std::chrono::seconds(5),[&]{return entered;}))throw std::runtime_error("Synthetic scan did not start");}void finish(){std::lock_guard l(mutex);release=true;cv.notify_all();}};
struct Release {std::shared_ptr<Block>b;~Release(){b->finish();}};
void queue(){std::atomic<unsigned>wakes{},calls{};a::UtilityExecutor executor([&]{++wakes;});m::StorageController state;double time{};const auto owner=std::this_thread::get_id();bool worker{};auto blocked=std::make_shared<Block>();Release release{blocked};
    n::StorageDetailsProbe probe(state,executor,[&](const m::StorageScanCancellation&cancel){worker=std::this_thread::get_id()!=owner;if(++calls==1)blocked->run();return m::StorageDetailsSnapshot{{{"owned","Owned",cancel.cancelled()?0:512,false}},false,time,false,{}};},[&]{return time;});
    state.activate(time);check(!probe.submitPending()&&calls==0,"Activation alone never starts a details walk");state.requestDetails(time);check(probe.submitPending(),"Explicit details request borrows shared executor");blocked->wait();state.deactivate();state.activate(time=1);state.requestDetails(time);check(!probe.submitPending()&&calls==1,"Reopen waits for cancelled serial walk, never overlaps it");blocked->finish();executor.waitIdle();executor.drain();check(state.details().isLoading&&state.details().categories.empty(),"Cancelled result never replaces cached details and queues one replacement");check(probe.submitPending(),"Shared completion event can submit the single replacement");executor.waitIdle();executor.drain();check(calls==2&&worker&&state.details().categories[0].bytes==512,"Accepted metadata reaches controller only on owner drain");state.requestDetails(time=899);check(!probe.submitPending(),"Original fifteen-minute cache prevents another details scan");state.requestDetails(time=902);check(probe.submitPending(),"Expired details cache allows one explicit new request");executor.waitIdle();executor.drain();const auto done=wakes.load();for(unsigned i=0;i<1000;++i)check(!probe.submitPending(),"Idle details adapter submits no work");check(wakes==done,"No idle wakeups, private timer or polling");
    auto late=std::make_shared<Block>();Release finish{late};m::StorageController discarded;auto temporary=std::make_unique<n::StorageDetailsProbe>(discarded,executor,[late](const m::StorageScanCancellation&){late->run();return m::StorageDetailsSnapshot{{},false,0,false,{}};},[]{return 0.;});discarded.activate(0);discarded.requestDetails(0);temporary->submitPending();late->wait();const auto rev=discarded.revision();temporary.reset();late->finish();executor.waitIdle();executor.drain();check(discarded.revision()==rev&&executor.stats().discarded>0,"Destroyed route cancels and discards callback without accessing expired owner");
}
#ifdef _WIN32
std::string pathText(const std::filesystem::path&p){const auto u=p.u8string();return {reinterpret_cast<const char*>(u.data()),u.size()};}
void native(){const auto base=std::filesystem::temp_directory_path()/(L"EndfieldStorageFixture-"+std::to_wstring(GetCurrentProcessId())+L"-"+std::to_wstring(GetTickCount64()));check(!std::filesystem::exists(base),"Native Storage owns a new explicit temporary root");std::filesystem::create_directories(base/L"one"/L"child");std::filesystem::create_directories(base/L"two");struct Remove{std::filesystem::path p;~Remove(){std::error_code e;std::filesystem::remove_all(p,e);}}remove{base};{std::ofstream f(base/L"one"/L"a",std::ios::binary);f<<std::string(1234,'a');}{std::ofstream f(base/L"one"/L"child"/L"b",std::ios::binary);f<<std::string(5678,'b');}{std::ofstream f(base/L"one"/L"\u4e2d\u6587\U0001f600",std::ios::binary);f<<"owned UTF16 path";}check(CreateHardLinkW((base/L"two"/L"alias").c_str(),(base/L"one"/L"a").c_str(),nullptr)!=FALSE,"Owned hardlink fixture creates without privileges");
    auto fs=n::makeWindowsStorageFileSystem();auto parent=fs->openRoot(pathText(base));check(bool(parent),"Handle-relative native root opens own directory");const auto volume=parent->metadata().identity.volume;parent.reset();m::StorageScanCancellation cancel;const std::array scopes{n::StorageFolderScope{"one","One",{pathText(base/L"one")}},n::StorageFolderScope{"two","Two",{pathText(base/L"two")}}};const auto read=n::scanStorageFolders(scopes,cancel,100,*fs,volume,[]{return 0.;});
    auto allocated=[](const std::filesystem::path&p){HANDLE h=CreateFileW(p.c_str(),FILE_READ_ATTRIBUTES,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,nullptr,OPEN_EXISTING,FILE_FLAG_OPEN_REPARSE_POINT|FILE_FLAG_OPEN_NO_RECALL,nullptr);check(h!=INVALID_HANDLE_VALUE,"Owned metadata-only validation handle");FILE_STANDARD_INFO value{};const bool ok=GetFileInformationByHandleEx(h,FileStandardInfo,&value,sizeof(value))!=FALSE;CloseHandle(h);check(ok,"Owned allocation metadata reads");return value.AllocationSize.QuadPart;};const auto expected=allocated(base/L"one"/L"a")+allocated(base/L"one"/L"child"/L"b")+allocated(base/L"one"/L"\u4e2d\u6587\U0001f600");check(read.categories[0].bytes==expected&&read.categories[1].bytes==0&&!read.isPartial&&!read.error,"Actual native scanner measures only owned allocation metadata and deduplicates hardlinks");
    const auto capacity=n::readWindowsCapacityAt(pathText(base),123);check(capacity&&capacity->totalBytes>0&&capacity->availableBytes>=0&&capacity->availableBytes<=capacity->totalBytes&&capacity->updatedAt==123,"One capacity query uses only the explicitly owned fixture volume");check(!fs->openRoot("\\\\server\\share")&&!fs->openRoot(pathText(base)+"\\..")&&!fs->openRoot(pathText(base)+":stream"),"Scanner rejects network, parent traversal and ADS paths before enumeration");
    check(!fs->openRoot(pathText(base/L"one"/L"a")),"Metadata validation rejects an ordinary file as a scan root before enumeration");
    const auto nested=base/L"one"/L"child";auto opened=fs->openRoot(pathText(nested));check(bool(opened),"Owned directory captured before replacement");std::filesystem::rename(nested,base/L"detached");std::filesystem::create_directories(nested);{std::ofstream f(nested/L"replacement");f<<"do not enumerate this replacement";}n::StorageDirectoryEntry entry;bool sawOriginal{},sawReplacement{};while(opened->next(entry)==n::StorageDirectoryRead::entry){sawOriginal|=entry.name==u"b";sawReplacement|=entry.name==u"replacement";}check(sawOriginal&&!sawReplacement,"Enumeration stays bound to the original handle after path replacement");opened.reset();
}
#endif
}
int main(int argc,char**argv){try{accounting();bounds();queue();if(argc==2)original(argv[1]);else check(argc==1,"Pass optional original storage-files.json");
#ifdef _WIN32
native();
#endif
std::cout<<"PASS "<<checks<<" Storage files/details checks\n";}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
