#include "native/storage_probe.hpp"
#include <atomic>
#include <condition_variable>
#include <iostream>
#include <mutex>
#include <stdexcept>
#include <thread>
namespace n=endfield::native;namespace m=endfield::modules;namespace a=endfield::app;
namespace {unsigned checks{};void check(bool b,const char*s){++checks;if(!b)throw std::runtime_error(s);}
struct Block {std::mutex mutex;std::condition_variable cv;bool entered{},released{};void wait(){std::unique_lock lock(mutex);entered=true;cv.notify_all();cv.wait(lock,[&]{return released;});}void await(){std::unique_lock lock(mutex);if(!cv.wait_for(lock,std::chrono::seconds(5),[&]{return entered;}))throw std::runtime_error("Owned synthetic provider did not enter");}void release(){std::lock_guard lock(mutex);released=true;cv.notify_all();}};
struct ReleaseBlock {std::shared_ptr<Block>block;~ReleaseBlock(){block->release();}};
void tests(){std::atomic<unsigned>wakes{},reads{};const auto owner=std::this_thread::get_id();a::UtilityExecutor executor([&]{++wakes;},1);m::StorageController controller;
    bool offThread{};n::StorageCapacityProbe probe(controller,executor,[&]()->std::optional<m::StorageCapacity>{offThread=std::this_thread::get_id()!=owner;++reads;return m::StorageCapacity{"Owned synthetic volume",1000,420,100};});
    check(!probe.submitPending()&&!executor.stats().started,"Hidden Storage starts no utility thread, read, or deadline");controller.activate(0);check(probe.submitPending(),"Initial active capacity enters existing utility executor");controller.refresh(1);check(!probe.submitPending(),"In-flight repeated refresh never adds work");executor.waitIdle();check(controller.snapshot().isLoading&&reads==1&&offThread,"Provider runs off owner thread, and cannot directly mutate its controller");controller.deactivate();executor.drain();check(!controller.snapshot().isLoading&&controller.snapshot().capacity&&!controller.nextWakeTime(),"Accepted hidden capacity completion caches without a hidden timer");
    const auto notices=wakes.load();for(unsigned i=0;i<1000;++i)check(!probe.submitPending(),"Idle submit has no request");check(wakes==notices&&reads==1,"No idle utility work or notifications");controller.activate(59);check(!probe.submitPending(),"Original capacity cache avoids fresh read at59seconds");controller.wake(119);check(probe.submitPending(),"Caller-owned source60second deadline submits exactly one read");executor.waitIdle();executor.drain();check(reads==2&&probe.stats().completed==2,"No module-owned timer required");controller.deactivate();
    auto block=std::make_shared<Block>();ReleaseBlock releaseBlock{block};const auto unrelated=executor.makeRoute();check(executor.submit(unrelated,[block]{block->wait();},[](auto){}),"Owned synthetic shared queue is occupied");block->await();controller.activate(200);check(!probe.submitPending()&&probe.stats().waiting&&probe.stats().backpressure==1,"Full shared queue retains one latest capacity request");block->release();executor.waitIdle();executor.drain();check(probe.submitPending()&&!probe.stats().waiting,"Completion event retries retained request without another clock");executor.waitIdle();executor.drain();check(reads==3,"Backpressure never duplicated the source read");executor.invalidate(unrelated);controller.deactivate();
    auto blocked=std::make_shared<Block>();ReleaseBlock releaseBlocked{blocked};m::StorageController disposable;auto doomed=std::make_unique<n::StorageCapacityProbe>(disposable,executor,[blocked]()->std::optional<m::StorageCapacity>{blocked->wait();return m::StorageCapacity{"owned",5,2,0};});disposable.activate(0);doomed->submitPending();blocked->await();const auto revision=disposable.revision();doomed.reset();check(disposable.revision()==revision,"Destroying provider route does not wait for blocked work or mutate state");blocked->release();executor.waitIdle();executor.drain();check(disposable.revision()==revision&&executor.stats().discarded>=1,"Late result has no callback into destroyed probe");
    m::StorageController failed;n::StorageCapacityProbe invalid(failed,executor,[]()->std::optional<m::StorageCapacity>{return m::StorageCapacity{"invalid",1,2,0};});failed.activate(0);invalid.submitPending();executor.waitIdle();executor.drain();check(!failed.snapshot().isLoading&&failed.snapshot().error&&invalid.stats().failed==1,"Invalid provider result becomes recoverable source capacity error");
    m::StorageController invalidName;n::StorageCapacityProbe invalidUTF8(invalidName,executor,[]()->std::optional<m::StorageCapacity>{return m::StorageCapacity{std::string(1,static_cast<char>(0xff)),2,1,0};});invalidName.activate(0);invalidUTF8.submitPending();executor.waitIdle();executor.drain();check(!invalidName.snapshot().capacity&&invalidName.snapshot().error&&invalidUTF8.stats().failed==1,"Invalid native volume name becomes recoverable error before text rendering");
}
}
int main(){try{tests();std::cout<<"PASS "<<checks<<" Storage utility capacity probe checks\n";}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
