#ifdef _WIN32
#include "tools/storage_preview.hpp"
#include <objbase.h>
#include <atomic>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <new>
#include <stdexcept>
namespace {std::atomic<bool>counting{};std::atomic<std::size_t>allocations{};unsigned checks{};}
void*operator new(std::size_t n){if(counting)++allocations;if(void*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}
void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}
#if defined(__cpp_sized_deallocation)
void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#endif
namespace c=endfield::core;namespace m=endfield::modules;namespace n=endfield::native;namespace t=endfield::tools;namespace a=endfield::app;using J=ehud::data::Json;
namespace {
void check(bool v,const char*s){++checks;if(!v)throw std::runtime_error(s);}
void checkNear(double a,double b,const char*s){check(std::isfinite(a)&&std::abs(a-b)<1e-6,s);}
struct Window {HWND hwnd{};ATOM atom{};Window(){WNDCLASSW w{};w.lpfnWndProc=DefWindowProcW;w.hInstance=GetModuleHandleW(nullptr);w.lpszClassName=L"EndfieldStorageOwnedFixture";atom=RegisterClassW(&w);check(atom!=0,"Register owned Storage fixture");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,w.lpszClassName,L"Hidden Storage fixture",WS_POPUP,0,0,1280,800,nullptr,nullptr,w.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Storage fixture stays hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);if(atom)UnregisterClassW(reinterpret_cast<LPCWSTR>(static_cast<ULONG_PTR>(atom)),GetModuleHandleW(nullptr));}};
const J&named(const J&node,std::string_view name){if(node["name"].isString()&&node["name"].string()==name)return node;for(const auto&child:node["children"].array())try{return named(child,name);}catch(const std::out_of_range&){}throw std::out_of_range("Missing original Storage artwork");}
m::StorageSourcePaths paths(const std::filesystem::path&file){std::ifstream f(file,std::ios::binary|std::ios::ate);check(bool(f)&&f.tellg()>0&&f.tellg()<4*1024*1024,"Explicit bounded Storage source fixture");std::string text(static_cast<std::size_t>(f.tellg()),'\0');f.seekg(0);f.read(text.data(),static_cast<std::streamsize>(text.size()));check(bool(f),"Complete Storage fixture read");const auto source=J::parse(text);const auto&root=source["cases"].array()[0]["root"];return {named(root,"storage.refresh.arrow")["shape"]["path"],named(root,"storage.settings.button")["children"].array()[1]["children"].array()[0]["shape"]["path"],named(root,"storage.refresh.button")["children"].array()[1]["children"].array()[0]["shape"]["path"]};}
const n::DrawObject&draw(n::LayerComposition&composition,std::string_view suffix){for(const auto&d:composition.draws())if(d.sourceID.ends_with(suffix))return d;throw std::runtime_error("Missing retained Storage draw");}
void run(const std::filesystem::path&shader,m::StorageSourcePaths source){Window window;n::Renderer renderer;renderer.initialize(window.hwnd,1280,800,{n::Driver::warpForTests,shader,n::RenderTarget::offscreenForTests});renderer.setCamera(n::layerViewportProjection(1280,800));n::LayerRasterizer raster;
    std::atomic<unsigned>reads{},notices{},detailReads{};a::UtilityExecutor executor([&]{++notices;});unsigned settingsCalls{};double time{};t::StoragePreviewOptions options;options.utility=&executor;options.paths=std::move(source);options.rasterDensity=1;options.openSettings=[&]{++settingsCalls;};options.readCapacity=[&]()->std::optional<m::StorageCapacity>{const auto count=++reads;if(count==2)return {};return m::StorageCapacity{"Owned fixture volume",1000000000000,420000000000,100};};
    options.scanDetails=[&](const m::StorageScanCancellation&){++detailReads;return m::StorageDetailsSnapshot{{{"owned","Owned",512,false}},false,0,false,{}};};options.completionClock=[&]{return time;};t::StoragePreview preview(raster,std::move(options));preview.resize({1280,800,96,1,1280,800});c::ModulePresentation modules(c::Module::storage);c::source::DesktopChromeSettings settings;settings.viewport={0,0,1280,800};settings.module=c::Module::storage;n::LayerComposition composition;
    // Declared after preview: cleanup always detaches borrowed scenes first.
    struct Cleanup {n::LayerComposition&composition;t::StoragePreview&preview;n::Renderer&renderer;~Cleanup(){try{composition.detach(renderer);preview.release(renderer);}catch(...){renderer.reset();}}}cleanup{composition,preview,renderer};
    auto frame=[&](c::Matrix4 center=c::Matrix4{}){preview.update(center,settings,modules.sample(time).presentation,1,time);preview.upload(renderer);composition.setEntries(renderer,preview.entries());preview.collected(renderer);composition.present(renderer);};frame();
    check(preview.state().snapshot().isLoading&&preview.nextWakeTime()==60&&preview.requiresFrames(time),"Incoming Storage activates one source read, deadline and finite arrow turn");executor.waitIdle();executor.drain();preview.utilityCompleted(time);frame();check(reads==1&&!preview.state().snapshot().isLoading&&preview.requiresFrames(time),"Fast injected capacity completes but preserves current refresh turn");
    const auto camera=n::layerViewportProjection(1280,800);const auto arrow=draw(composition,"storage.refresh.arrow").world;const auto center=c::Projection::viewport(camera*arrow,1280,800).project({11,11});check(center.has_value(),"Original arrow center projects");time=.36;frame();const auto rotated=draw(composition,"storage.refresh.arrow").world;const auto center2=c::Projection::viewport(camera*rotated,1280,800).project({11,11});check(center2.has_value(),"Rotated arrow center projects");checkNear(center->x,center2->x,"Source arrow does not orbit in X");checkNear(center->y,center2->y,"Source arrow does not orbit in Y");check(rotated!=arrow,"Finite refresh actually rotates retained geometry");time=.73;frame();check(!preview.requiresFrames(time),"Fast source read settles after complete0.72second turn");
    check(detailReads==0,"Activation and refresh never run implicit category scans");const auto detailRaster=raster.stats().rasterizations;check(preview.requestDetails(false,time),"Explicit model details request is accepted without inventing canvas UI");executor.waitIdle();executor.drain();preview.utilityCompleted(time);frame();check(detailReads==1&&preview.state().details().categories[0].bytes==512&&raster.stats().rasterizations==detailRaster,"Details completion shares utility worker and adds no capacity-artwork work");check(preview.requestDetails(false,time)&&detailReads==1,"Source details cache prevents another explicit scan");
    const auto point=[&](std::string_view surface,c::Point local){const auto p=c::Projection::viewport(camera*draw(composition,surface).world,1280,800).project(local);check(p.has_value(),"Projected original control fixture");return *p;};
    auto p=point("storage.settings.button",{30,14});preview.pointer({a::PointerKind::move,a::PointerButton::none,p.x,p.y},time);time+=.15;frame();checkNear(draw(composition,"storage.settings.tint").opacity,.62,"Source rounded hover tint fades to.62");
    check(preview.pointer({a::PointerKind::down,a::PointerButton::left,p.x,p.y},time)&&preview.pointerLocked()&&settingsCalls==1,"Storage settings uses original projected action and source press lock");preview.pointer({a::PointerKind::up,a::PointerButton::left,p.x,p.y},time);check(!preview.pointerLocked(),"Pointer up releases Storage press lock");
    p=point("storage.refresh.button",{18,14});check(preview.pointer({a::PointerKind::down,a::PointerButton::left,p.x,p.y},time),"Original refresh control submits explicit query");check(preview.presentation().actions().size()==1&&!preview.perform("storage:refresh",time),"Loading suppresses repeated refresh action without adding a second job");preview.pointer({a::PointerKind::up,a::PointerButton::left,p.x,p.y},time);executor.waitIdle();executor.drain();preview.utilityCompleted(time);frame();check(reads==2&&preview.presentation().labels().caption=="Storage capacity is unavailable."&&preview.presentation().labels().values[0]=="1.0 TB","Capacity failure displays original status while preserving cached values");
    time+=1;preview.cancelInteraction(time);frame();const auto before=raster.stats();const auto gpu=renderer.stats();allocations=0;counting=true;
    for(unsigned i=0;i<120;++i){auto tilted=c::Matrix4{};tilted.values[3]=double(i)*.000001;time+=1./60;preview.update(tilted,settings,modules.sample(time).presentation,1,time);composition.present(renderer);}counting=false;
    check(allocations==0&&raster.stats().rasterizations==before.rasterizations&&raster.stats().textLayoutsCreated==before.textLayoutsCreated&&renderer.stats().textureUploads==gpu.textureUploads,"120 changing tilt frames retain all CPU/GPU content without allocations");
    preview.setVisible(false,time);check(!preview.nextWakeTime()&&!preview.requiresFrames(time)&&!preview.pointerLocked(),"Closing stops Storage deadline and local animation immediately");check(!preview.requestDetails(true,time),"Concealed model declines explicit details request");const auto hiddenReads=reads.load();preview.deadline(time+120);executor.waitIdle();executor.drain();check(reads==hiddenReads,"Hidden Storage never polls injected provider");
    time+=120;preview.setVisible(true,time);frame();executor.waitIdle();executor.drain();preview.utilityCompleted(time);frame();check(reads==hiddenReads+1,"Reopen outside cache age refreshes once");
    settings.module=c::Module::power;modules.select(c::Module::power,time);time+=.05;frame();check(!preview.state().active()&&!preview.entries().empty()&&!preview.nextWakeTime(),"Source departure retains artwork while stopping provider demand");time+=1;frame();check(preview.entries().empty()&&!preview.requiresFrames(time),"Settled other module retains no Storage drawing or wake demand");composition.detach(renderer);preview.release(renderer);renderer.draw(false);check(renderer.stats().textures==0&&renderer.stats().meshes==0&&!IsWindowVisible(window.hwnd)&&renderer.stats().presents==0,"Storage fixture retires all resources without showing UI or reading any disk capacity");
}
}
int wmain(int argc,wchar_t**argv){const auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(hr)&&argc==3,"Pass shader and detached storage.json");run(argv[1],paths(argv[2]));CoUninitialize();std::cout<<"PASS "<<checks<<" retained Storage owner checks\n";}catch(const std::exception&e){counting=false;if(SUCCEEDED(hr))CoUninitialize();std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#else
int main(){return 0;}
#endif
