#include "modules/storage_state.hpp"
#include "core/data/json.hpp"
#include <cmath>
#include <deque>
#include <fstream>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <variant>
using namespace endfield::modules;using J=ehud::data::Json;
namespace {
unsigned checks{};void check(bool value,const char*why){++checks;if(!value)throw std::runtime_error(why);}
template<class F>void rejects(F action,const char*why){bool caught{};try{action();}catch(const std::invalid_argument&){caught=true;}check(caught,why);}
J opt(const std::optional<std::string>&v){return v?J(*v):J{};}
J snapshot(const StorageController&c){const auto&s=c.snapshot();const auto&d=c.details();J capacity;if(s.capacity){const auto&v=*s.capacity;capacity=J::Object{{"name",v.volumeName},{"total",v.totalBytes},{"available",v.availableBytes},{"date",v.updatedAt}};}J::Array categories;for(const auto&v:d.categories)categories.push_back(J::Object{{"id",v.id},{"title",v.title},{"bytes",v.bytes?J(*v.bytes):J{}},{"partial",v.isPartial}});
    return J::Object{{"capacity",capacity},{"loading",s.isLoading},{"error",opt(s.error)},{"details",J::Object{{"categories",std::move(categories)},{"loading",d.isLoading},{"date",d.updatedAt?J(*d.updatedAt):J{}},{"partial",d.isPartial},{"error",opt(d.error)}}}};}
void original(const char*path){std::ifstream file(path,std::ios::binary);std::string bytes((std::istreambuf_iterator<char>(file)),{});const auto doc=J::parse(bytes,2*1024*1024);check(doc["schemaVersion"].integer()==1&&!doc["filesystemReads"].boolean(),"Original oracle identifies isolated unchanged source");
    StorageController c;std::deque<std::variant<StorageCapacityRequest,StorageDetailsRequest>>queue;unsigned reads{},scans{};
    auto collect=[&]{if(auto r=c.takeCapacityRequest())queue.emplace_back(*r);if(auto r=c.takeDetailsRequest())queue.emplace_back(*r);};
    for(const auto&row:doc["steps"].array()){const auto action=row["action"].string();const auto now=row["now"].number();
        if(action=="activate")c.activate(now);else if(action=="deactivate")c.deactivate();else if(action=="refresh")c.refresh(now);else if(action=="details"||action=="details-force")c.requestDetails(now,action=="details-force");else if(action=="wake")c.wake(now);else if(action=="work"&&!queue.empty()){
            const auto job=queue.front();queue.pop_front();if(const auto*r=std::get_if<StorageCapacityRequest>(&job)){++reads;check(c.completeCapacity(r->token,reads==2?std::nullopt:std::optional(StorageCapacity{"Owned startup fixture",1000000,400000+reads,now})),"Current capacity worker completion accepted");}
            else{++scans;const auto&detail=std::get<StorageDetailsRequest>(job);check(c.completeDetails(detail.token,{{{"documents","Documents",12345,detail.cancellation->cancelled()}},false,now,detail.cancellation->cancelled(),{}},now),"Current detail worker completion accepted");}}
        collect();const auto value=snapshot(c);for(const auto*key:{"capacity","loading","error","details"})if(value[key]!=row[key])throw std::runtime_error("Original Storage state mismatch at "+action+" time="+std::to_string(now)+" field="+key+" actual="+value[key].encode());
        check(c.active()==row["active"].boolean()&&c.revision()==static_cast<std::uint64_t>(row["revision"].integer()),"Original activity/publication count matches");check(queue.size()==static_cast<std::size_t>(row["workers"].integer())&&c.nextWakeTime().has_value()==(row["timers"].integer()!=0),"Original worker coalescing and active-only wake match");
    }check(reads&&scans,"Oracle exercised capacity and explicit detail providers");
}
void contracts(){StorageController c;c.refresh(0);c.requestDetails(0);check(!c.takeCapacityRequest()&&!c.takeDetailsRequest()&&!c.nextWakeTime(),"Concealed controller starts no work or deadline");c.activate(0);const auto read=*c.takeCapacityRequest();c.refresh(1);check(!c.takeCapacityRequest(),"Repeated refresh coalesces while in flight");rejects([&]{c.completeCapacity(read.token,StorageCapacity{"disk",4,5,0});},"Invalid provider capacity rejected before state mutation");check(c.snapshot().isLoading,"Bad completion preserves current request");c.deactivate();check(c.completeCapacity(read.token,StorageCapacity{"disk",10,4,2})&&c.snapshot().capacity->usedBytes()==6&&!c.nextWakeTime(),"Hidden capacity completion is cached without restarting timer");check(!c.completeCapacity(read.token,{}),"Old capacity completion ignored");c.activate(59);check(!c.takeCapacityRequest(),"Capacity cache measures last request time");c.refresh(59);check(c.takeCapacityRequest().has_value(),"Explicit refresh bypasses60s cache");
    c.requestDetails(59);auto detail=*c.takeDetailsRequest();c.deactivate();check(detail.cancellation->cancelled()&&!c.details().isLoading,"Hide signals cancellation and immediately clears loading");c.activate(60);c.requestDetails(60);check(!c.takeDetailsRequest(),"Reopen cannot overlap still-running cancelled scan");c.completeDetails(detail.token,{},61);auto replacement=c.takeDetailsRequest();check(replacement&&replacement->token!=detail.token&&!replacement->cancellation->cancelled(),"Cancelled completion starts exactly one latest replacement");check(!c.completeDetails(detail.token,{},62),"Stale detail token cannot publish over new scan");c.deactivate();
    StorageScanBudget b(0);b.beginScope(0);for(int n=0;n<8000;++n){check(!b.limitReached(0),"Scope entry limit permits exactly8000 metadata records");b.examinedEntry();}check(b.limitReached(0),"Per-scope entry bound reached");for(int scope=1;scope<5;++scope){b.beginScope(0);for(int n=0;n<8000;++n)b.examinedEntry();}b.beginScope(0);check(b.limitReached(0)&&b.totalEntries()==40000,"Total bound carries across scopes");StorageScanBudget t(0);t.beginScope(9);check(!t.limitReached(9.99)&&t.limitReached(10),"10s global bound precedes2s scope bound");t.beginScope(0);check(t.limitReached(2)&&t.limitReached(0,true),"2s scope and cancellation independently stop walk");check(t.mayDescend(31)&&!t.mayDescend(32),"Source depth32 traversal guard is exact");
    StorageScanBudget allocation(0);check(allocation.addSourceBlocks(1,10,3)&&allocation.scopeBytes()==1536,"POSIX oracle allocated blocks convert at512bytes");allocation.beginScope(0);check(allocation.addSourceBlocks(1,10,3)&&allocation.scopeBytes()==0,"Hard links deduplicate across category scopes");check(allocation.addAllocated(2,10,12)&&allocation.scopeBytes()==12,"Identity includes source volume");check(!allocation.addSourceBlocks(1,11,std::numeric_limits<std::int64_t>::max())&&allocation.scopeBytes()==12,"Overflow marks partial without wrapping byte count");check(allocation.addSourceBlocks(1,11,1)&&allocation.scopeBytes()==12,"Overflowing identity remains deduplicated like original");
    StorageScanBudget negative(0,{-1,-1,-1,-1,-1});check(negative.limitReached(0)&&!negative.mayDescend(0),"Negative source limits normalize tozero");rejects([&]{c.activate(std::numeric_limits<double>::quiet_NaN());},"Invalid clock cannot alter controller");
}
}
int main(int argc,char**argv){try{contracts();if(argc==2)original(argv[1]);else check(argc==1,"Pass optional original storage-state.json");std::cout<<"PASS "<<checks<<" Storage state checks\n";}catch(const std::exception&e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<'\n';return 1;}}
