#include "native/work_mode_scene.hpp"
#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#include <objbase.h>
#include <algorithm>
#include <atomic>
#include <cstdlib>
#include <iostream>
#include <new>
using namespace endfield;using namespace native;
namespace{std::atomic<std::size_t>allocations{};bool counting{};unsigned checks{};void check(bool v,const char*m){++checks;if(!v)throw std::runtime_error(m);}template<class F>void rejects(F f,const char*m){bool failed{};try{f();}catch(const std::exception&){failed=true;}check(failed,m);}
struct Window{HWND hwnd{};ATOM atom{};Window(){WNDCLASSW type{};type.lpfnWndProc=DefWindowProcW;type.hInstance=GetModuleHandleW(nullptr);type.lpszClassName=L"EndfieldWorkModeSynthetic";atom=RegisterClassW(&type);check(atom!=0,"Owned class registers");hwnd=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP|WS_EX_TOOLWINDOW,type.lpszClassName,L"Synthetic",WS_POPUP,0,0,440,440,nullptr,nullptr,type.hInstance,nullptr);check(hwnd&&!IsWindowVisible(hwnd),"Fixture remains hidden");}~Window(){if(hwnd)DestroyWindow(hwnd);if(atom)UnregisterClassW(reinterpret_cast<LPCWSTR>(static_cast<ULONG_PTR>(atom)),GetModuleHandleW(nullptr));}};
void run(const std::filesystem::path&shader){Window window;Renderer renderer;renderer.initialize(window.hwnd,440,440,{Driver::warpForTests,shader,RenderTarget::offscreenForTests});renderer.setCamera(layerViewportProjection(440,440));LayerRasterizer raster;LayerRasterOptions options;options.pixelsPerPoint=1;modules::WorkModeController controller;modules::WorkModePresentation state(controller);state.activate(0);NativeWorkModeScene scene(state,raster,options);LayerComposition composition;
 auto publish=[&](double time){state.refresh(time);scene.syncContent(time);scene.updatePose({{},1,time,{},{}});scene.uploadAnimations(renderer);composition.setEntries(renderer,scene.entries());composition.present(renderer);renderer.draw(false);check(scene.collectRetired(renderer),"Unpublished old source surfaces retire");};
 publish(0);check(scene.entries().size()==8,"Source paint order contains8 independent parts");const auto idle=renderer.readback();check(std::any_of(idle.pixels.begin(),idle.pixels.end(),[](auto value){return value!=0;}),"Original Work Mode artwork paints owned target");
 check(state.perform("work:start",0),"Start uses source controller");publish(0);const auto resources=renderer.stats();const auto local=raster.stats();
 for(unsigned n=1;n<=120;++n){const double now=n*.001;state.refresh(now);check(!scene.syncContent(now),"Subsecond ring frames do not regenerate artwork");scene.updatePose({core::Matrix4::rotation(0,.001*n,0),1,now,{},{}});scene.uploadAnimations(renderer);composition.setEntries(renderer,scene.entries());composition.present(renderer);}
 const auto after=renderer.stats();check(after.textureUploads==resources.textureUploads&&after.meshUploads==resources.meshUploads&&after.objectBufferAllocations==resources.objectBufferAllocations&&raster.stats().rasterizations==local.rasterizations,"Continuous ring/layout use only retained numeric state");
 publish(.5);const auto beforeTick=raster.stats();const auto beforeGPU=renderer.stats();publish(1.1);check(raster.stats().rasterizations==beforeTick.rasterizations+1&&renderer.stats().textureUploads==beforeGPU.textureUploads+1,"One-second label changes rasterize/upload exactly one clock leaf");
 // Warm all numeric buffers before measuring allocation-free settled motion.
 scene.updatePose({{},1,1.2,{},{}});scene.uploadAnimations(renderer);composition.setEntries(renderer,scene.entries());composition.present(renderer);allocations=0;counting=true;
 std::array<std::size_t,4>stageAllocations{};try{for(unsigned n=0;n<100;++n){auto before=allocations.load();scene.updatePose({core::Matrix4::rotation(0,.001*n,0),1,1.21+n*.001,{},{}});stageAllocations[0]+=allocations.load()-before;before=allocations.load();scene.uploadAnimations(renderer);stageAllocations[1]+=allocations.load()-before;before=allocations.load();composition.setEntries(renderer,scene.entries());stageAllocations[2]+=allocations.load()-before;before=allocations.load();composition.present(renderer);stageAllocations[3]+=allocations.load()-before;}}catch(...){counting=false;throw;}counting=false;if(allocations!=0)std::cerr<<"Warm allocations pose/upload/entries/present="<<stageAllocations[0]<<'/'<<stageAllocations[1]<<'/'<<stageAllocations[2]<<'/'<<stageAllocations[3]<<'\n';check(allocations==0,"Warm ring/tilt frames allocate no heap objects");
 state.perform("work:pause",1.4);publish(1.4);check(!scene.requiresFrames(2),"Paused settled Work Mode stops compositor demand");state.perform("work:reset",2);publish(2);publish(2.5);scene.setFeedback("work:stopwatch",true,2.5);publish(2.57);check(scene.requiresFrames(2.57)==false,"Stationary pressed feedback settles after source duration");
 state.perform("work:stopwatch",3);publish(3);state.perform("work:start",3.3);publish(3.3);const auto active=composition.draws();const auto ring=std::find_if(active.begin(),active.end(),[](const auto&d){return d.angularMask.has_value();});check(ring!=active.end()&&ring->angularMask->endPlane.has_value(),"Resident source ring uses exact cubic endpoint plane");check(std::abs(ring->angularMask->sweepAngle-.2900428318115755)<1e-10,"Stopwatch source .045 stroke is not approximated by linear angle");
 state.setFocusStatus("Permission requested by injected platform",true,3.4);publish(3.4);check(renderer.stats().nativeGroups==2,"Permission plate owns a second retained source-opacity group");state.perform("work:focusAccess",3.5);publish(3.5);bool permissionGroup{},caption{};for(const auto&entry:scene.entries()){for(const auto&draw:entry.after)if(draw.sourceID.find("workMode.focusAccess")!=std::string::npos){permissionGroup=true;check(std::abs(draw.opacity-.55f)<1e-6,"Permission feedback multiplies group opacity once");}if(const auto index=entry.scene->surfaceIndex("workMode.focusStatus")){caption=true;entry.scene->prepareDraws();check(entry.scene->draws()[*index].opacity==1,"Separate permission caption never fades with plate");}}check(permissionGroup&&caption,"Original plate and caption retain separate source ancestry");publish(3.8);
 state.setReduceMotion(true,4);publish(4);check(!scene.requiresFrames(4),"Reduced motion does not keep source ring alive");state.deactivate(4);composition.detach(renderer);check(scene.releaseResources(renderer)&&renderer.stats().objects==0&&renderer.stats().nativeGroups==0,"Shared group/ring resources retire after detach");check(!IsWindowVisible(window.hwnd)&&renderer.stats().presents==0,"No visible window or real provider was used");}
}
void*operator new(std::size_t size){if(counting)++allocations;if(void*p=std::malloc(size?size:1))return p;throw std::bad_alloc();}void operator delete(void*p)noexcept{std::free(p);}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete[](void*p)noexcept{std::free(p);}void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
int wmain(int argc,wchar_t**argv){const auto com=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);if(FAILED(com))return 1;int code{};try{check(argc==2,"Pass native shader");run(argv[1]);std::cout<<"Work Mode scene: "<<checks<<" checks passed\n";}catch(const std::exception&e){counting=false;std::cerr<<"Work Mode scene after "<<checks<<": "<<e.what()<<'\n';code=1;}CoUninitialize();return code;}
#else
int main(){return 0;}
#endif
