#ifdef _WIN32
#include "tools/work_mode_preview.hpp"
#include "native/module_scene.hpp"
#include <objbase.h>
#include <algorithm>
#include <cmath>
#include <iostream>
namespace {
namespace gpu=endfield::native;namespace c=endfield::core;namespace a=endfield::app;namespace t=endfield::tools;namespace m=endfield::modules;using Json=ehud::data::Json;
unsigned checks{};void check(bool v,const char*message){++checks;if(!v)throw std::runtime_error(message);}
struct Window{HWND window{};Window(){WNDCLASSW w{};w.lpfnWndProc=DefWindowProcW;w.hInstance=GetModuleHandleW(nullptr);w.lpszClassName=L"EndfieldWorkOwnerHidden";check(RegisterClassW(&w)!=0,"Register owned fixture");window=CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP,w.lpszClassName,L"Synthetic",WS_POPUP,0,0,1280,800,nullptr,nullptr,w.hInstance,nullptr);check(window&&!IsWindowVisible(window),"Synthetic Work Mode stays hidden");}~Window(){if(window)DestroyWindow(window);UnregisterClassW(L"EndfieldWorkOwnerHidden",GetModuleHandleW(nullptr));}};
void run(const std::filesystem::path&shader){Window window;gpu::Renderer renderer;renderer.initialize(window.window,1280,800,{gpu::Driver::warpForTests,shader,gpu::RenderTarget::offscreenForTests});const auto camera=gpu::layerViewportProjection(1280,800);renderer.setCamera(camera);gpu::LayerRasterizer raster;gpu::LayerComposition composition;
    std::vector<double>saves;std::vector<bool>focus;unsigned permissions{};t::WorkModePreviewOptions options;options.raster.pixelsPerPoint=1;options.restoredWorkSeconds=100;options.saveWorkSeconds=[&](double total){saves.push_back(total);};options.focusDesired=[&](bool desired){focus.push_back(desired);};options.requestFocusAccess=[&]{++permissions;};
    t::WorkModePreview owner(window.window,raster,nullptr,TF_CLIENTID_NULL,options);owner.resize({1280,800,96,1,1280,800});owner.focus(true,0);c::ModulePresentation modules{c::Module::workMode};c::source::DesktopChromeSettings settings{{0,0,1280,800},1,{},c::Module::workMode,true};auto center=c::source::DesktopChromeLayout::make(settings,{},{}).designToScreen;
    gpu::LayerScene geometry(raster);geometry.load(Json::Object{{"bounds",Json::Array{0,0,440,440}},{"children",Json::Array{}}},{});gpu::NativeModuleSurface plane(geometry,c::Module::workMode);double now{};bool done{};
    struct Cleanup{gpu::Renderer&r;gpu::LayerComposition&c;t::WorkModePreview&o;bool&done;~Cleanup(){if(done)return;try{c.detach(r);o.release(r);}catch(...){r.reset();}}}cleanup{renderer,composition,owner,done};
    const auto frame=[&](double delta=.01){now+=delta;const auto sample=modules.sample(now).presentation;settings.module=sample.requested;owner.update(center,settings,sample,1,now);owner.upload(renderer);composition.setEntries(renderer,owner.entries());composition.present(renderer);owner.collected(renderer);};
    const auto point=[&](c::Point p){const auto sample=modules.sample(now).presentation;const auto*surface=sample.current.module==c::Module::workMode?&sample.current:&*sample.incoming;plane.update(center,settings,*surface,1);const auto result=c::Projection::viewport(camera*plane.pose().contentWorld,1280,800).project(p);check(result.has_value(),"Actual current source module plane projects");return *result;};
    const auto click=[&](c::Point p){const auto q=point(p);check(owner.covers(q)&&owner.pointer({a::PointerKind::down,a::PointerButton::left,q.x,q.y},now),"Original source control receives projected press");check(!owner.pointerLocked(),"User-requested button press preserves gyro motion");owner.pointer({a::PointerKind::up,a::PointerButton::left,q.x,q.y},now);frame();};
    const auto type=[&](std::string_view value){for(unsigned char ch:value)check(owner.key({a::KeyKind::character,ch},false,now),"Short field consumes caller characters");frame();};
    frame();check(owner.entries().size()==9&&!owner.nextWakeTime()&&saves.empty()&&focus.empty(),"Idle owner paints eight source parts plus registration without services/deadlines");renderer.draw(false);const auto image=renderer.readback();check(std::any_of(image.pixels.begin(),image.pixels.end(),[](auto v){return v!=0;}),"Original Work Mode paints hidden shared target");
    click({315,139});check(owner.editing(),"Source custom control creates borrowed-service field");frame();check(owner.entries().size()==12,"Field backing/glyphs/border share one composition");std::shared_ptr<const gpu::PaintedTextLayout>fieldLayout;for(const auto&entry:owner.entries())if(auto found=entry.scene->paintedTextLayout("projected-editor-glyphs"))fieldLayout=std::move(found);check(fieldLayout&&fieldLayout->contentInset().x==3&&fieldLayout->documentWidth()==312&&fieldLayout->documentHeight()==68,"Duration uses original centered inset and finite single-line document");type("invalid");check(owner.key({a::KeyKind::down,VK_RETURN},false,now)&&owner.editing()&&owner.state().phaseText()==options.strings.invalidDuration,"Invalid committed text remains editable and selected");type("0:02");check(owner.key({a::KeyKind::down,VK_RETURN},false,now)&&!owner.editing()&&owner.controller().snapshot(now).duration==2,"Selected invalid draft replaces and commits source min:sec");frame();
    check(owner.key({a::KeyKind::down,VK_SPACE},false,now),"Space starts countdown");frame(.1);check(owner.controller().snapshot(now).phase==m::WorkModePhase::running&&focus==std::vector<bool>{true}&&owner.nextWakeTime(),"Running owner exposes shared deadline and explicit Focus desire");
    check(owner.key({a::KeyKind::down,VK_RETURN},false,now),"Return pauses source timer");frame(.5);check(owner.controller().snapshot(now).phase==m::WorkModePhase::paused&&!owner.nextWakeTime()&&focus==std::vector<bool>{true},"Paused Work Mode keeps Focus desire but no deadline");
    check(owner.key({a::KeyKind::down,VK_SPACE},false,now),"Space resumes source timer");frame(.1);const auto hiddenStart=now;const auto completion=owner.controller().completionDeadline();owner.setOverlayVisible(false,now);frame(.1);check(!owner.controller().visible()&&!owner.controller().displayDeadline()&&owner.nextWakeTime()==completion&&!owner.requiresFrames(now),"Closed HUD with still-selected Work Mode keeps completion only");owner.setOverlayVisible(true,now);frame(.1);check(owner.controller().visible()&&owner.controller().displayDeadline(),"Reopening uses source visible label deadline");modules.select(c::Module::power,now);frame(.5);frame(.4);check(owner.entries().empty()&&!owner.requiresFrames(now)&&owner.nextWakeTime()&&owner.controller().snapshot(now).phase==m::WorkModePhase::running,"Hidden countdown retains completion only, no UI frames");
    now=hiddenStart+4;owner.wake(now);check(owner.controller().snapshot(now).phase==m::WorkModePhase::completed&&!owner.nextWakeTime()&&focus==std::vector<bool>({true,false}),"Delayed shared wake completes countdown and requests Focus release once");check(!saves.empty()&&std::abs(saves.back()-102)<1e-9,"Absolute source work checkpoint counts exactly two active seconds");
    modules.select(c::Module::workMode,now);frame(.6);frame(.5);click({270,310});frame(.5);click({315,139});type("1:23");check(owner.key({a::KeyKind::down,VK_ESCAPE},false,now)&&!owner.editing()&&owner.controller().snapshot(now).duration==2,"Escape discards duration draft without changing controller");frame();
    click({315,139});type("2:34");modules.select(c::Module::power,now);frame(.5);frame(.5);check(!owner.editing()&&owner.controller().snapshot(now).duration==2,"Leaving Work Mode cancels unsaved custom input");
    modules.select(c::Module::workMode,now);frame(.5);frame(.5);owner.setFocusStatus("Explicit unsupported platform",false,now);frame();check(std::none_of(owner.state().actions().begin(),owner.state().actions().end(),[](const auto&v){return v.id=="work:focusAccess";}),"Unsupported Focus does not invent a permission action");owner.setFocusStatus("Injected permission needed",true,now);frame();click({220,37});check(permissions==1,"Permission control reaches injected callback only");frame(.3);
    click({280,99});frame(.3);owner.key({a::KeyKind::down,VK_SPACE},false,now);frame(.4);modules.select(c::Module::power,now);frame(.5);frame(.5);check(!owner.nextWakeTime()&&owner.controller().snapshot(now).phase==m::WorkModePhase::running,"Hidden stopwatch has no periodic wake");const auto beforeSleep=owner.controller().snapshot(now).elapsed;owner.setSuspended(true,now);now+=3600;owner.setSuspended(false,now);check(owner.controller().snapshot(now).elapsed>=beforeSleep+3600&&!owner.nextWakeTime(),"Caller continuous clock includes sleep without a second ticker");
    check(owner.message({window.window,options.textMessage,123456,0},now)&&!owner.editing(),"Stale private field notice cannot reopen/edit a retired document");composition.detach(renderer);owner.shutdown(now);owner.release(renderer);done=true;check(renderer.stats().textures==0&&renderer.stats().meshes==0&&renderer.stats().nativeGroups==0&&!IsWindowVisible(window.window),"Detached owner retires all resources and never activates TSF, Focus or real UI");
}
}
int wmain(int argc,wchar_t**argv){const auto result=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);try{check(SUCCEEDED(result)&&argc==2,"Pass HLSL to hidden Work Mode owner test");run(argv[1]);CoUninitialize();std::cout<<"Work Mode owner: "<<checks<<" checks passed\n";return 0;}catch(const std::exception&e){if(SUCCEEDED(result))CoUninitialize();std::cerr<<"Work Mode owner after "<<checks<<": "<<e.what()<<'\n';return 1;}}
#endif
