#include "modules/work_mode_presentation.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iostream>
#include <sstream>
using namespace endfield;using namespace modules;using ehud::data::Json;
namespace{unsigned checks{};void check(bool v,const char*m){++checks;if(!v)throw std::runtime_error(m);}void close(double a,double b,const char*m,double tolerance=2e-6){check(std::abs(a-b)<=tolerance,m);}template<class F>void rejects(F f){bool hit=false;try{f();}catch(const std::exception&){hit=true;}check(hit,"Invalid source input rejects");}
const Json*find(const Json&node,std::string_view key,std::string_view value){if(node[key].isString()&&node[key].string()==value)return &node;if(node["children"].isArray())for(const auto&c:node["children"].array())if(const auto*p=find(c,key,value))return p;return nullptr;}
void numbers(const Json&a,const Json&b){check(a.isArray()&&b.isArray()&&a.array().size()==b.array().size(),"Source numeric shape matches");for(std::size_t n=0;n<a.array().size();++n){if(a.array()[n].isArray())numbers(a.array()[n],b.array()[n]);else close(a.array()[n].number(),b.array()[n].number(),"Original numeric descriptor");}}
void color(const Json&a,const Json&b){if(a.isNull()||b.isNull()){check(a.isNull()&&b.isNull(),"Original optional color");return;}numbers(a["sRGB"],b["sRGB"]);}
void shape(const Json&a,const Json&b){const auto&sa=a["shape"],&sb=b["shape"];close(sa["lineWidth"].number(),sb["lineWidth"].number(),"Source shape width");check(sa["lineCap"]==sb["lineCap"]&&sa["lineJoin"]==sb["lineJoin"],"Source cap and join");color(sa["fillColor"],sb["fillColor"]);color(sa["strokeColor"],sb["strokeColor"]);check(sa["path"].array().size()==sb["path"].array().size(),"Source path command count");for(std::size_t n=0;n<sa["path"].array().size();++n){const auto&ca=sa["path"].array()[n],&cb=sb["path"].array()[n];check(ca["op"]==cb["op"],"Source path command");numbers(ca["points"],cb["points"]);}}
void text(const Json&a,const Json&b){numbers(a["bounds"],b["bounds"]);const auto&ta=a["text"],&tb=b["text"];for(auto key:{"string","fontSize","alignment","wrapped","truncation"})check(ta[key]==tb[key],"Original text property");for(auto key:{"postScriptName","familyName","symbolicTraits"})check(ta["font"][key]==tb["font"][key],"Original font descriptor");color(ta["foregroundColor"],tb["foregroundColor"]);close(a["contentsScale"].number(),b["contentsScale"].number(),"Original text backing scale");}
void oracle(const char*file){std::ifstream in(file);std::stringstream bytes;bytes<<in.rdbuf();const auto root=Json::parse(bytes.str());WorkModeController c;WorkModePresentation s(c);s.setReduceMotion(true,0);s.activate(0);double now=0;WorkModeAppearance appearance;std::size_t index{};
 auto verify=[&](const char*name){const auto&item=root["cases"].array().at(index++);check(item["name"].string()==name,"Original operation checkpoint order");const auto&source=item["layer"];check(s.accessibilityStatus()==item["status"].string(),"Original accessible status");check(s.actions().size()==item["actions"].array().size(),"Original accessible action count");for(std::size_t n=0;n<s.actions().size();++n){const auto&a=s.actions()[n];const auto&b=item["actions"].array()[n];check(a.id==b["id"].string()&&a.label==b["label"].string(),"Original action identity and label");const auto&r=b["rect"].array();close(a.rect.x,r[0].number(),"Action x");close(a.rect.y,r[1].number(),"Action y");close(a.rect.width,r[2].number(),"Action width");close(a.rect.height,r[3].number(),"Action height");}
  const auto art=prepareWorkModeArtwork(s,appearance);for(const auto&part:{&art.header,&art.clock,&art.phase,&art.focus})for(const auto&node:part->layers["children"].array())if(node["kind"].string()=="text"){const auto*original=find(source,"name",node["id"].string());check(original,"Named source text exists");text(node,*original);}
  const auto*originalRing=find(source,"name","workMode.ring"),*base=find(source,"name","workMode.ringBase");shape(art.ring.layers["children"].array()[0],*originalRing);shape(art.ringBase.layers["children"].array()[0],*base);
  close(s.ring(now).fraction,(*originalRing)["shape"]["strokeEnd"].number(),"Original model strokeEnd");const auto layout=s.layout(now);const auto*clock=find(source,"name","workMode.clockViewport"),*phaseNode=find(source,"name","workMode.phase"),*config=find(source,"name","workMode.configuration");close(layout.clockY,(*clock)["position"].array()[1].number(),"Original clock center");close(layout.clockScale,(*clock)["transform"].array()[0].array()[0].number(),"Original clock scale");close(layout.phaseY,(*phaseNode)["position"].array()[1].number(),"Original phase center");close(layout.configurationOpacity,(*config)["opacity"].number(),"Original configuration opacity");
  for(const auto&part:{&art.controls,&art.configuration})for(const auto&node:part->layers["children"].array()){const auto id=node["id"].string();if(id.ends_with("/plate")){const auto action=id.substr(0,id.size()-6);const auto*original=find(source,"name","workMode.button."+action);check(original,"Original button exists");shape(node,(*original)["children"].array()[0]);}else if(id.ends_with("/label")){const auto action=id.substr(0,id.size()-6);const auto*original=find(source,"name","workMode.control."+action);check(original,"Original caption exists");text(node,*original);}}
 };
 verify("idle");s.perform("work:preset:5",now);verify("preset5");s.setCustomDuration("1:07",now);verify("custom67");s.setCustomDuration("bad",now);verify("invalid");s.cancelCustomEditing(now);s.perform("work:start",now);verify("running");now=12.25;c.refresh(now);s.refresh(now);verify("running12");s.perform("work:pause",now);verify("paused");s.perform("work:reset",now);s.perform("work:stopwatch",now);verify("stopwatch");s.perform("work:start",now);now=41.75;c.refresh(now);s.refresh(now);verify("stopwatchRunning");s.perform("work:pause",now);appearance.dark=false;verify("lightPaused");s.setFocusStatus("Unavailable on this platform",false,now);verify("focusUnavailable");s.setFocusStatus("Permission required",true,now);verify("focusAccess");s.deactivate(now);
}
void timing(const char*file){std::ifstream in(file);std::stringstream bytes;bytes<<in.rdbuf();const auto source=Json::parse(bytes.str());check(source["maximumRepeatDifference"].number()==0,"Original paused CA clock repeats exactly");
 for(const auto&row:source["rows"].array()){WorkModeController c;WorkModePresentation state(c);state.activate(0);state.perform("work:start",0);const auto name=row["name"].string();const auto now=row["phase"].number()*row["duration"].number();std::vector<double>actual;
  if(name=="layoutPosition")actual={220,state.layout(now).clockY};else if(name=="layoutTransform")actual={state.layout(now).clockScale,state.layout(now).clockScale,0,0,0};else if(name=="layoutOpacity")actual={state.layout(now).configurationOpacity};else if(name=="button"){const auto feedback=state.feedback(now);actual={feedback.scale,feedback.scale,0,0,0};}else if(name=="clock"){const auto m=state.feedback(now).clock;actual={m.values[0],m.values[5],m.values[12],m.values[13],m.values[14]};}else{state.setFocusStatus("Synthetic",true,0);state.perform("work:focusAccess",0);actual={state.feedback(now).focusOpacity};}
  const auto&expected=row["value"].array();check(actual.size()==expected.size(),"Source CA sample shape");for(std::size_t n=0;n<actual.size();++n){if(std::abs(actual[n]-expected[n].number())>2e-6)std::cerr<<name<<" phase="<<row["phase"].number()<<" channel="<<n<<" actual="<<actual[n]<<" expected="<<expected[n].number()<<" delta="<<actual[n]-expected[n].number()<<"\n";close(actual[n],expected[n].number(),"Genuine original CA presentation sample",2e-6);}
 }
}
void lifecycle(){WorkModeController c;unsigned edits{},requests{};WorkModePresentation s(c,{},{{[&](core::Rect r){++edits;check(r==core::Rect{64,184,312,68},"Exact source editor viewport");}},{[&]{++requests;}}});s.activate(10);check(s.perform("work:custom",10)&&edits==1,"Custom editor callback");s.perform("work:start",10);check(s.actions().size()==2&&s.requiresFrames(10),"Running session hides configuration and requests compositor frames");const auto half=s.layout(10.1);s.perform("work:reset",10.1);close(s.layout(10.1).clockY,half.clockY,"Interrupted expansion starts from current presentation");check(s.actions().size()==2,"Collapsing configuration remains input-disabled");s.refresh(10.55);check(s.actions().size()==8,"Configuration becomes interactive at exact finite completion");check(!s.requiresFrames(11),"Settled ready module requests no frames");s.perform("work:start",11);check(!s.setCustomDuration("bad",12)&&c.snapshot(12).phase==WorkModePhase::running,"Obsolete duration editor cannot reset running session");check(s.setCustomDuration("30",12),"Obsolete editor may harmlessly reenter unchanged countdown");s.setReduceMotion(true,12);check(!s.requiresFrames(12),"Reduced motion leaves label deadlines and no ring frames");s.setFocusStatus("Unsupported",false,12);check(!s.perform("work:focusAccess",12),"Unavailable platform does not invent permission action");s.setFocusStatus("Permission required",true,12);check(s.perform("work:focusAccess",12)&&requests==1,"Owner-injected permission action only");s.deactivate(12);check(!s.requiresFrames(13),"Hidden module retains running controller with no visual frames");
 for(double f:{0.,.01,.045,.1,.25,.5,.75,1.}){const auto cut=workModeRingCut(f);close(std::hypot(cut.endPlane[0],cut.endPlane[1]),1,"Source butt normal is unit");check(std::isfinite(cut.endAngle),"Source arc endpoint finite");}close(workModeRingCut(.045).endAngle+.5*3.14159265358979323846,.2900428318115755,"Original cubic parameter differs from naive polar fraction",1e-12);rejects([]{workModeRingCut(-.1);});rejects([]{workModeRingCut(1.1);});
}
}
int main(int argc,char**argv){try{check(argc==3,"Pass original artwork and actual CA timing fixtures");oracle(argv[1]);timing(argv[2]);lifecycle();std::cout<<"Work Mode presentation: "<<checks<<" checks passed\n";}catch(const std::exception&e){std::cerr<<"Work Mode presentation after "<<checks<<": "<<e.what()<<'\n';return 1;}}
