#include "modules/activity_state.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <stdexcept>

namespace endfield::modules {
namespace {
using U=std::uint64_t;
bool add(U&a,U b)noexcept{if(b>std::numeric_limits<U>::max()-a)return false;a+=b;return true;}
std::optional<U>product(U a,U b)noexcept{if(b&&a>std::numeric_limits<U>::max()/b)return {};return a*b;}
void time(double n){if(!std::isfinite(n)||n<0)throw std::invalid_argument("Invalid Activity clock");}
bool validInterval(double elapsed,double maximum){return std::isfinite(elapsed)&&elapsed>0&&elapsed<=maximum;}
std::optional<double>cpu(const std::optional<ActivityCPU>&a,const std::optional<ActivityCPU>&b){if(!a||!b)return {};const std::array<U,4>x{a->user,a->system,a->idle,a->nice},y{b->user,b->system,b->idle,b->nice};U total{};for(unsigned k=0;k<4;++k)if(x[k]<y[k]||!add(total,x[k]-y[k]))return {};if(!total)return {};return std::clamp(double(total-(a->idle-b->idle))/double(total)*100,0.,100.);}
std::optional<std::array<double,2>>rates(const std::optional<ActivityCounters>&a,const std::optional<ActivityCounters>&b,double elapsed){if(!a||!b||a->size()!=b->size()||!validInterval(elapsed,std::numeric_limits<double>::max()))return {};U received{},sent{};auto old=b->begin();for(const auto&[key,value]:*a){if(key!=old->first||value.received<old->second.received||value.sent<old->second.sent||!add(received,value.received-old->second.received)||!add(sent,value.sent-old->second.sent))return {};++old;}const std::array<double,2>out{double(received)/elapsed,double(sent)/elapsed};if(!std::isfinite(out[0])||!std::isfinite(out[1]))return {};return out;}
std::vector<std::uint32_t>pids(std::vector<std::uint32_t>p){std::sort(p.begin(),p.end());p.erase(std::unique(p.begin(),p.end()),p.end());return p;}
std::optional<double>combined(std::optional<double>a,std::optional<double>b){if(!a||!b||!std::isfinite(*a)||!std::isfinite(*b)||*a<0||*b<0||!std::isfinite(*a+*b))return {};return *a+*b;}
void increment(U&v){if(v==std::numeric_limits<U>::max())throw std::overflow_error("Activity generation exhausted");++v;}
void metric(std::optional<double>value){if(value&&(!std::isfinite(*value)||*value<0))throw std::invalid_argument("Invalid Activity metric");}
void validateSnapshot(const ActivitySnapshot&v){time(v.uptime);if(!std::isfinite(v.timestamp))throw std::invalid_argument("Invalid Activity timestamp");metric(v.cpuPercent);metric(v.upload);metric(v.download);metric(v.diskRead);metric(v.diskWrite);if(v.memory&&(!v.memory->total||v.memory->used>v.memory->total||(v.memory->compressed&&*v.memory->compressed>v.memory->total)))throw std::invalid_argument("Invalid Activity memory");}
}
std::optional<ActivityMemory>activityMacMemory(U physical,U pageSize,U internal,U purgeable,U wired,U compressed)noexcept{if(!physical||!pageSize)return {};U pages=internal-std::min(internal,purgeable);if(!add(pages,wired)||!add(pages,compressed))return {};const auto used=product(pages,pageSize),compression=product(compressed,pageSize);if(!used||!compression)return {};return ActivityMemory{std::min(physical,*used),physical,std::min(physical,*compression)};}
ActivitySnapshot deriveActivity(const ActivityRawSample&value,const ActivityRawSample*previous){ActivitySnapshot out;out.timestamp=value.timestamp;out.uptime=value.uptime;out.memory=value.memory;const double elapsed=previous?value.uptime-previous->uptime:0;std::optional<std::array<double,2>>network,disk;if(validInterval(elapsed,15)){out.cpuPercent=cpu(value.cpu,previous->cpu);network=rates(value.network,previous->network,elapsed);disk=rates(value.disk,previous->disk,elapsed);}if(network){out.download=(*network)[0];out.upload=(*network)[1];}if(disk){out.diskRead=(*disk)[0];out.diskWrite=(*disk)[1];}if(!out.cpuPercent)out.statusNotes.push_back(value.cpu?"Collecting CPU baseline":"CPU unavailable");if(!out.memory)out.statusNotes.push_back("RAM unavailable");if(!network)out.statusNotes.push_back(value.network?"Collecting network baseline":"Network unavailable");if(!disk)out.statusNotes.push_back(value.disk?"Collecting disk baseline":"Disk activity unavailable");return out;}
ActivityAppsSnapshot deriveActivityApps(const ActivityAppsRaw&value,const ActivityAppsRaw*previous){if(value.apps.size()>ActivityState::maximumApps)throw std::invalid_argument("Activity catalog exceeds source256 limit");ActivityAppsSnapshot out;out.timestamp=value.timestamp;out.uptime=value.uptime;out.statusNotes=value.statusNotes;out.items.reserve(value.apps.size());const double elapsed=previous?value.uptime-previous->uptime:0;
    for(const auto&identity:value.apps){ActivityApp item;item.identity=identity;const auto member=value.members.find(identity.id);item.identity.processIDs=pids(member==value.members.end()?identity.processIDs:member->second);const auto&ids=item.identity.processIDs;
        bool complete=value.inventoryComplete&&!ids.empty();for(auto id:ids)if(!value.processes.contains(id))complete=false;
        bool same=false;if(previous){const auto prior=previous->members.find(identity.id);same=prior!=previous->members.end()&&pids(prior->second)==ids;}
        if(complete){U memory{};bool validMemory=true;for(auto id:ids)validMemory=add(memory,value.processes.at(id).memoryBytes)&&validMemory;if(validMemory)item.memoryBytes=memory;
            if(validInterval(elapsed,5)&&same&&std::isfinite(value.secondsPerCPUTick)&&value.secondsPerCPUTick>0){U ticks{},reads{},writes{};bool valid=true,validTicks=true,hasDisk=true,validReads=true,validWrites=true;
                for(auto id:ids){const auto&v=value.processes.at(id);const auto old=previous->processes.find(id);if(old==previous->processes.end()||old->second.startID!=v.startID||v.cpuTicks<old->second.cpuTicks){valid=false;break;}const auto&o=old->second;if(v.diskRead&&v.diskWrite&&o.diskRead&&o.diskWrite){if(*v.diskRead<*o.diskRead||*v.diskWrite<*o.diskWrite){valid=false;break;}validReads=add(reads,*v.diskRead-*o.diskRead)&&validReads;validWrites=add(writes,*v.diskWrite-*o.diskWrite)&&validWrites;}else hasDisk=false;validTicks=add(ticks,v.cpuTicks-o.cpuTicks)&&validTicks;}
                if(valid){if(validTicks){const double percent=double(ticks)*value.secondsPerCPUTick/elapsed*100;if(std::isfinite(percent))item.cpuPercent=std::max(0.,percent);}if(hasDisk&&validReads)item.diskRead=double(reads)/elapsed;if(hasDisk&&validWrites)item.diskWrite=double(writes)/elapsed;}}
            if(value.network&&value.uptime-value.network->uptime>=0&&value.uptime-value.network->uptime<=4){const auto&net=*value.network;bool valid=true;double received{},sent{};for(auto id:ids){if(!(value.processes.at(id).startUptime<=net.intervalStart)||net.unknownPIDs.contains(id)){valid=false;break;}const auto found=net.rates.find(id);if(found!=net.rates.end()){received+=found->second[0];sent+=found->second[1];}}if(valid&&std::isfinite(received)&&std::isfinite(sent)){item.download=received;item.upload=sent;}}}
        if(!complete)item.statusNotes.push_back("Some app processes are unavailable or protected");else if(!item.cpuPercent)item.statusNotes.push_back("Collecting app baseline");if(!item.memoryBytes)item.statusNotes.push_back("RAM unavailable");if(!item.download)item.statusNotes.push_back("Network unavailable or collecting baseline");out.items.push_back(std::move(item));}
    return out;
}
std::string_view activitySortKey(ActivitySort key)noexcept{static constexpr std::array<std::string_view,9>keys{"name","cpu","memory","network","disk","upload","download","diskRead","diskWrite"};const auto i=static_cast<unsigned>(key);return i<keys.size()?keys[i]:std::string_view{};}
void sortActivityApps(std::vector<ActivityApp>&items,ActivitySort key,bool descending,const ActivityNameCompare&compare){if(!compare||activitySortKey(key).empty())throw std::invalid_argument("Activity requires source-compatible name comparison");auto number=[key](const ActivityApp&i)->std::optional<double>{switch(key){case ActivitySort::name:return {};case ActivitySort::cpu:return i.cpuPercent;case ActivitySort::memory:return i.memoryBytes?std::optional<double>(double(*i.memoryBytes)):std::nullopt;case ActivitySort::network:return combined(i.upload,i.download);case ActivitySort::disk:return combined(i.diskRead,i.diskWrite);case ActivitySort::upload:return i.upload;case ActivitySort::download:return i.download;case ActivitySort::diskRead:return i.diskRead;case ActivitySort::diskWrite:return i.diskWrite;}return {};};
    std::sort(items.begin(),items.end(),[&](const auto&a,const auto&b){if(key!=ActivitySort::name){const auto x=number(a),y=number(b);if(x&&y&&*x!=*y)return descending?*x>*y:*x<*y;if(bool(x)!=bool(y))return bool(x);}const int names=compare(a.identity.name,b.identity.name);if(names)return key==ActivitySort::name&&descending?names>0:names<0;return a.identity.id<b.identity.id;});}
ActivityGraphTrace activityGraph(std::span<const std::optional<double>>input,double ceiling,std::span<const double>times,double width,double height){if(!std::isfinite(width)||!std::isfinite(height)||width<=0||height<=0)throw std::invalid_argument("Invalid Activity graph bounds");const auto raw=input.last(std::min<std::size_t>(60,input.size()));std::array<std::optional<double>,60>values{};std::array<double,60>positions{};const auto padding=60-raw.size();for(std::size_t n=0;n<60;++n)positions[n]=double(n)*width/59.;for(std::size_t n=0;n<raw.size();++n)if(raw[n]&&std::isfinite(*raw[n])&&*raw[n]>=0)values[padding+n]=raw[n];
    if(!raw.empty()&&times.size()>=raw.size()){const auto used=times.last(raw.size());bool valid=true;for(std::size_t n=0;n<used.size();++n)if(!std::isfinite(used[n])||used[n]<0||(n&&used[n]<=used[n-1]))valid=false;if(valid){const auto window=std::max(59.,used.back()-used.front());for(std::size_t n=0;n<used.size();++n)positions[padding+n]=width*(1-(used.back()-used[n])/window);for(std::size_t n=0;n<padding;++n)positions[n]=double(n)*positions[padding]/double(padding);}}
    ActivityGraphTrace out;const auto limit=std::isfinite(ceiling)&&ceiling>0?ceiling:1;for(std::size_t n=0;n<60;++n){out.points[n]={positions[n],height-std::clamp(values[n].value_or(0)/limit,0.,1.)*height};if(n&&values[n-1]&&values[n]&&positions[n]>positions[n-1])out.coverage[out.coverageCount++]={positions[n-1],-1,positions[n]-positions[n-1],height+2};}out.markerVisible=values.back().has_value();out.marker=out.points.back();return out;
}
ActivityState::ActivityState(ActivityNameCompare compare):compare_(std::move(compare)){if(!compare_)throw std::invalid_argument("Activity requires name ordering");}
void ActivityState::receive(ActivitySnapshot value){validateSnapshot(value);latest_=value;if(count_==60){std::move(history_.begin()+1,history_.end(),history_.begin());history_.back()=std::move(value);}else history_[count_++]=std::move(value);++revision_;++overviewRevision_;}
void ActivityState::receiveApps(ActivityAppsSnapshot value){time(value.uptime);if(!std::isfinite(value.timestamp)||value.items.size()>maximumApps)throw std::invalid_argument("Invalid Activity app snapshot");std::set<std::string>identities;for(const auto&i:value.items){if(i.identity.id.empty()||i.identity.id.size()>4096||i.identity.name.size()>4096||i.identity.iconKey.size()>4096||!identities.insert(i.identity.id).second)throw std::invalid_argument("Invalid Activity app identity");metric(i.cpuPercent);metric(i.upload);metric(i.download);metric(i.diskRead);metric(i.diskWrite);}sortActivityApps(value.items,sort_,descending_,compare_);appSnapshot_=std::move(value);offset_=std::min(offset_,maximumOffset());++revision_;++appsRevision_;++placementRevision_;}
bool ActivityState::setApps(bool value){if(apps_==value)return false;apps_=value;++revision_;return true;}
bool ActivityState::sort(ActivitySort value){if(activitySortKey(value).empty())throw std::invalid_argument("Invalid Activity sort");const bool next=value==sort_?!descending_:value!=ActivitySort::name;auto copy=appSnapshot_.items;sortActivityApps(copy,value,next,compare_);appSnapshot_.items=std::move(copy);sort_=value;descending_=next;offset_=0;++revision_;++appsRevision_;++placementRevision_;return true;}
double ActivityState::maximumOffset()const noexcept{return std::max(0.,double(appSnapshot_.items.size())*49-226);}
bool ActivityState::scroll(core::Point p,double delta){if(!apps_||!appsViewport().contains(p)||!std::isfinite(delta))return false;const auto next=std::clamp(offset_+delta,0.,maximumOffset());if(next!=offset_){if(std::floor(next/49)!=std::floor(offset_/49))++appsRevision_;offset_=next;++revision_;++placementRevision_;}return true;}
ActivityRows ActivityState::visibleRows()const noexcept{ActivityRows out;const auto first=static_cast<std::size_t>(std::floor(offset_/49));for(std::size_t n=0;n<6&&first+n<appSnapshot_.items.size();++n)out.rows[out.count++]={first+n,{0,double(first+n)*49-offset_,374,45}};const auto max=maximumOffset();if(max>0){const auto height=std::max(20.,226.*226/(double(appSnapshot_.items.size())*49));out.scrollbar=core::Rect{374,(226-height)*offset_/max,2,height};}return out;}
void ActivitySamplingPlan::start(double now){time(now);if(running_)return;increment(generation_);running_=true;resetSystem_=true;systemDue_=now;if(visible_&&apps_){increment(appGeneration_);resetApps_=true;appsDue_=now;}}
void ActivitySamplingPlan::stop(){if(!running_)return;increment(generation_);increment(appGeneration_);running_=visible_=alert_=apps_=false;systemDue_.reset();appsDue_.reset();resetSystem_=resetApps_=false;}
void ActivitySamplingPlan::setVisible(bool visible,bool alert,bool apps,double now){time(now);const auto before=interval();const bool wasApps=appsActive();visible_=visible;alert_=alert;apps_=apps;if(!running_&&(visible||alert)){start(now);return;}if(!running_)return;if(before!=interval())systemDue_=now+interval();if(wasApps!=appsActive()){increment(appGeneration_);resetApps_=appsActive();if(appsActive())appsDue_=now;else appsDue_.reset();}}
ActivityDemand ActivitySamplingPlan::takeDue(double now){time(now);ActivityDemand out;out.generation=generation_;out.appGeneration=appGeneration_;if(!running_)return out;if(systemDue_&&now>=*systemDue_){out.system=true;out.resetSystem=resetSystem_;resetSystem_=false;systemDue_=now+interval();}if(appsDue_&&now>=*appsDue_){out.apps=true;out.resetApps=resetApps_;resetApps_=false;appsDue_=now+1;}return out;}
std::optional<double>ActivitySamplingPlan::nextWakeTime()const noexcept{if(systemDue_&&appsDue_)return std::min(*systemDue_,*appsDue_);return systemDue_?systemDue_:appsDue_;}
} // namespace endfield::modules
