#include "modules/activity_presentation.hpp"
#include "core/source_color.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <stdexcept>

namespace endfield::modules {
namespace {
using Json=ehud::data::Json;using Rect=core::Rect;using Point=core::Point;using Color=std::array<double,4>;
Color gray(double w,double a=1){return {w,w,w,a};}Color alpha(Color c,double a){c[3]=a;return c;}
Json color(Color c){return Json::Object{{"sRGB",Json::Array{c[0],c[1],c[2],c[3]}}};}
Json box(Rect r){return Json::Array{r.x,r.y,r.width,r.height};}
Json layer(std::string id,Rect r,const char*kind="layer"){return Json::Object{{"id",std::move(id)},{"kind",kind},{"bounds",box({0,0,r.width,r.height})},{"position",Json::Array{r.x,r.y}},{"anchorPoint",Json::Array{0,0}},{"allowsGroupOpacity",false},{"children",Json::Array{}}};}
// parent is owned, mutable JSON created by layer(), never borrowed cache data.
void append(Json&parent,Json child){const_cast<Json::Array&>(parent["children"].array()).push_back(std::move(child));}
Json text(std::string id,Rect r,std::string value,double size,Color ink,double scale,const char*weight="regular",const char*align="left",bool wrapped=false){if(value.size()>4096||!Json::validUtf8(value))throw std::invalid_argument("Invalid Activity text");auto out=layer(std::move(id),r,"text");out["contentsScale"]=std::min(4.,std::ceil(std::clamp(scale,1.,4.)*1.35));out["text"]=Json::Object{{"string",std::move(value)},{"fontSize",size},{"font",Json::Object{{"postScriptName",std::string_view(weight)=="semibold"?".AppleSystemUIFontDemi":std::string_view(weight)=="medium"?".AppleSystemUIFontMedium":".AppleSystemUIFont"},{"familyName",".AppleSystemUIFont"},{"pointSize",size},{"symbolicTraits",std::string_view(weight)=="semibold"?2:0}}},{"foregroundColor",color(ink)},{"alignment",align},{"wrapped",wrapped},{"truncation","end"}};return out;}
Json plate(std::string id,Rect r,bool dark){auto out=layer(std::move(id),r);out["cornerRadius"]=3;out["backgroundColor"]=color(gray(dark?.12:.19));out["borderColor"]=color(gray(dark?.48:.30,.38));out["borderWidth"]=.5;return out;}
Json command(const char*op,std::initializer_list<Point>points={}){Json::Array a;for(auto p:points)a.push_back(Json::Array{p.x,p.y});return Json::Object{{"op",op},{"points",std::move(a)}};}
Json path(std::string id,Rect bounds,Json::Array commands,std::optional<Color>fill,std::optional<Color>stroke,double width=1){auto out=layer(std::move(id),bounds,"shape");out["shape"]=Json::Object{{"path",std::move(commands)},{"fillColor",fill?color(*fill):Json{}},{"strokeColor",stroke?color(*stroke):Json{}},{"lineWidth",width},{"lineCap","butt"},{"lineJoin","round"},{"fillRule","non-zero"},{"miterLimit",10}};return out;}
Json graph(std::string id,const ActivityGraphPlan&plan){auto out=layer(id,{85,9,165,36});out["masksToBounds"]=true;Json::Array grid;for(unsigned n=0;n<=6;++n){const double x=165.*n/6;grid.push_back(command("move",{{x,0}}));grid.push_back(command("line",{{x,36}}));}for(unsigned n=0;n<=2;++n){const double y=36.*n/2;grid.push_back(command("move",{{0,y}}));grid.push_back(command("line",{{165,y}}));}append(out,path(id+".grid",{0,0,165,36},std::move(grid),{},gray(.8,.14),.5));
    for(unsigned n=0;n<plan.count;++n){const auto&t=plan.traces[n];const auto ink=plan.count==1&&id=="activity.graph.1"?ActivityArtwork::blue:n==0?ActivityArtwork::yellow:ActivityArtwork::blue;Json::Array line{command("move",{t.points[0]})},area{command("move",{{0,36}}),command("line",{t.points[0]})},coverage;for(unsigned k=1;k<60;++k){line.push_back(command("line",{t.points[k]}));area.push_back(command("line",{t.points[k]}));}area.push_back(command("line",{{165,36}}));area.push_back(command("close"));for(std::size_t k=0;k<t.coverageCount;++k){const auto&r=t.coverage[k];coverage.push_back(command("move",{{r.x,r.y}}));coverage.push_back(command("line",{{r.x+r.width,r.y}}));coverage.push_back(command("line",{{r.x+r.width,r.y+r.height}}));coverage.push_back(command("line",{{r.x,r.y+r.height}}));coverage.push_back(command("close"));}auto fill=path(id+".area."+std::to_string(n),{0,0,165,36},std::move(area),alpha(ink,.38),{});auto trace=path(id+".line."+std::to_string(n),{0,0,165,36},std::move(line),{},ink);fill["mask"]=path(id+".fillCoverage."+std::to_string(n),{0,0,165,36},coverage,gray(0),{});trace["mask"]=path(id+".lineCoverage."+std::to_string(n),{0,0,165,36},std::move(coverage),gray(0),{});append(out,std::move(fill));append(out,std::move(trace));auto marker=layer(id+".latest."+std::to_string(n),{t.marker.x-1.5,t.marker.y-1.5,3,3});marker["cornerRadius"]=1.5;marker["backgroundColor"]=color(ink);marker["hidden"]=!t.markerVisible;append(out,std::move(marker));}return out;
}
}
std::string activityBytes(std::optional<double>bytes){if(!bytes||!std::isfinite(*bytes)||*bytes<0)return "—";static constexpr std::array<const char*,6>units{"B","KB","MB","GB","TB","PB"};double value=*bytes;std::size_t index{};while(value>=1000&&index+1<units.size()){value/=1000;++index;}char out[400];std::snprintf(out,sizeof(out),value>=100||index==0?"%.0f %s":"%.1f %s",value,units[index]);return out;}
std::string activityRate(std::optional<double>value){if(!value||!std::isfinite(*value)||*value<0)return "—";return activityBytes(value)+"/s";}
std::string activityPercent(std::optional<double>value,bool whole){if(!value||!std::isfinite(*value)||*value<0)return "—";char out[400];std::snprintf(out,sizeof(out),"%.1f%%",whole?std::min(100.,*value):*value);return out;}
ActivityArtwork prepareActivityArtwork(const ActivityState&state,const ActivityAppearance&a){if(!std::isfinite(a.scale)||a.scale<1||a.scale>8)throw std::invalid_argument("Invalid Activity scale");for(double c:a.accent)if(!std::isfinite(c)||c<0||c>1)throw std::invalid_argument("Invalid Activity accent");auto tr=[&](std::string_view en,std::string_view zh){return core::localized(en,zh,a.language);};const auto primary=gray(a.dark?.93:.12),muted=gray(a.dark?.65:.40);ActivityArtwork out;out.chrome=layer("activity.chrome",{0,0,400,334});out.overview=layer("activity.overview",{0,0,400,334});out.apps=layer("activity.apps",{0,0,400,334});append(out.chrome,text("activity.heading",{12,0,376,20},"// "+tr("Activity Monitor","活动监视器"),15,primary,a.scale,"semibold"));
    out.actions={{"activity:overview",tr("Overview","概览"),{12,25,82,23}},{"activity:apps",tr("Apps","应用"),{100,25,82,23}}};for(unsigned n=0;n<2;++n){const auto&action=out.actions[n];auto tab=layer("activity.control."+std::to_string(n),action.rect);tab["cornerRadius"]=3;const bool selected=state.showingApps()==bool(n);tab["backgroundColor"]=color(selected?a.accent:gray(a.dark?.23:.85));append(tab,text("activity.control.label."+std::to_string(n),{3,5,76,13},action.label,9.5,selected||!a.dark?gray(.1):gray(.94),a.scale,"medium","center"));append(out.chrome,std::move(tab));out.feedback.push_back({action.id,action.rect});}
    out.showingApps=state.showingApps();if(!out.showingApps){
    const auto history=state.history();std::array<double,60>timestamps{};std::array<std::array<std::optional<double>,60>,6>values{};for(std::size_t n=0;n<history.size();++n){const auto&s=history[n];timestamps[n]=s.uptime;values[0][n]=s.cpuPercent;if(s.memory&&s.memory->total)values[1][n]=double(s.memory->used)/double(s.memory->total)*100;values[2][n]=s.upload;values[3][n]=s.download;values[4][n]=s.diskRead;values[5][n]=s.diskWrite;}
    for(unsigned n=0;n<4;++n){auto&g=out.graphs[n];g.count=n<2?1:2;const auto first=n<2?n:2+(n-2)*2;g.ceiling=n<2?100:1;if(n>=2){double peak{};for(unsigned channel=0;channel<2;++channel)for(std::size_t k=0;k<history.size();++k)if(values[first+channel][k]&&std::isfinite(*values[first+channel][k])&&*values[first+channel][k]>=0)peak=std::max(peak,*values[first+channel][k]);g.ceiling=std::max(1.,peak*1.12);}for(unsigned k=0;k<g.count;++k)g.traces[k]=activityGraph({values[first+k].data(),history.size()},g.ceiling,{timestamps.data(),history.size()});}
    const auto&snapshot=state.snapshot();const auto memory=snapshot.memory;const std::array<std::string,4>titles{"CPU","RAM",tr("Network","网络"),tr("Disk I/O","磁盘 I/O")},subtitles{tr("TOTAL LOAD","总负载"),tr("USED / TOTAL","已用 / 总计"),tr("UP / DOWN","上传 / 下载"),tr("READ / WRITE","读取 / 写入")},mainValues{activityPercent(snapshot.cpuPercent),activityBytes(memory?std::optional<double>(double(memory->used)):std::nullopt),"↑ "+activityRate(snapshot.upload),tr("R ","读 ")+activityRate(snapshot.diskRead)},secondary{"0–100%","/ "+activityBytes(memory?std::optional<double>(double(memory->total)):std::nullopt),"↓ "+activityRate(snapshot.download),tr("W ","写 ")+activityRate(snapshot.diskWrite)};
    for(unsigned n=0;n<4;++n){const auto suffix=std::to_string(n);auto row=plate("activity.row."+suffix,{12,60+60.*n,376,54},a.dark);auto tick=layer("activity.tick."+suffix,{0,12,2,30});tick["backgroundColor"]=color(n==1?ActivityArtwork::blue:ActivityArtwork::yellow);append(row,std::move(tick));append(row,text("activity.title."+suffix,{9,10,70,16},titles[n],11,gray(.94),a.scale,"semibold"));append(row,text("activity.subtitle."+suffix,{9,31,70,12},subtitles[n],8.5,gray(.65),a.scale));append(row,graph("activity.graph."+suffix,out.graphs[n]));append(row,text("activity.value."+suffix,{262,6,104,19},mainValues[n],n<2?14:11.5,n==1?ActivityArtwork::blue:ActivityArtwork::yellow,a.scale,"medium","right"));append(row,text("activity.secondary."+suffix,{259,27,107,14},secondary[n],10,n>=2?ActivityArtwork::blue:gray(.65),a.scale,"regular","right"));append(row,text("activity.tertiary."+suffix,{257,41,109,11},n==1?tr("Compressed ","压缩 ")+activityBytes(memory&&memory->compressed?std::optional<double>(double(*memory->compressed)):std::nullopt):"",8,gray(.65),a.scale,"regular","right"));append(out.overview,std::move(row));}
    return out;}
    const std::array<ActivitySort,5>keys{ActivitySort::name,ActivitySort::cpu,ActivitySort::memory,ActivitySort::network,ActivitySort::disk};const std::array<std::string,5>names{tr("App","应用"),"CPU","RAM",tr("Network","网络"),tr("Disk","磁盘")};const std::array<Rect,5>frames{{{12,61,128,15},{146,61,45,15},{195,61,52,15},{251,61,65,15},{317,61,65,15}}};for(unsigned n=0;n<5;++n){const bool selected=state.sortKey()==keys[n];append(out.apps,text("activity.apps.header."+std::to_string(n),frames[n],names[n]+(selected?(state.descending()?" ↓":" ↑"):""),9,selected?primary:muted,a.scale,"medium",n?"right":"left"));const auto&r=frames[n];out.actions.push_back({"activity:sort:"+std::string(activitySortKey(keys[n])),tr("Sort by ","排序：")+names[n]+(selected?state.descending()?tr(", descending","，降序"):tr(", ascending","，升序"):""),{r.x,r.y-5,r.width,r.height+10}});out.feedback.push_back({out.actions.back().id,out.actions.back().rect});}
    auto rule=layer("activity.apps.header.rule",{12,80,376,.5});rule["backgroundColor"]=color(alpha(muted,.35));append(out.apps,std::move(rule));if(state.appSnapshot().items.empty())append(out.apps,text("activity.apps.empty",{20,172,360,42},tr("No app readings available","暂无应用读数"),12,muted,a.scale,"regular","center",true));
    const auto slots=state.visibleRows();const auto cyan=core::source::sourceWhiteBlend({a.accent[0],a.accent[1],a.accent[2]},.42);const Color secondaryInk{cyan[0],cyan[1],cyan[2],a.accent[3]};out.rows.reserve(slots.count);for(std::size_t n=0;n<slots.count;++n){const auto&slot=slots.rows[n];const auto&item=state.appSnapshot().items[slot.index];const auto suffix=std::to_string(n);auto row=plate("activity.app."+suffix,{0,0,374,45},a.dark);append(row,text("activity.app.name."+suffix,{31,12,100,28},item.identity.name,10,gray(.94),a.scale,"medium","left",true));append(row,text("activity.app.cpu."+suffix,{134,14,45,18},activityPercent(item.cpuPercent,false),10,a.accent,a.scale,"regular","right"));append(row,text("activity.app.memory."+suffix,{183,14,52,18},activityBytes(item.memoryBytes?std::optional<double>(double(*item.memoryBytes)):std::nullopt),10,secondaryInk,a.scale,"regular","right"));append(row,text("activity.app.upload."+suffix,{239,7,65,15},"↑ "+activityRate(item.upload),8.5,a.accent,a.scale,"regular","right"));append(row,text("activity.app.download."+suffix,{239,26,65,15},"↓ "+activityRate(item.download),8.5,secondaryInk,a.scale,"regular","right"));append(row,text("activity.app.read."+suffix,{305,7,65,15},tr("R ","读 ")+activityRate(item.diskRead),8.5,a.accent,a.scale,"regular","right"));append(row,text("activity.app.write."+suffix,{305,26,65,15},tr("W ","写 ")+activityRate(item.diskWrite),8.5,secondaryInk,a.scale,"regular","right"));out.rows.push_back({n,slot.index,item.identity.id,item.identity.iconKey,slot.rect,std::move(row)});}
    if(slots.scrollbar){auto scroll=layer("activity.apps.scrollbar",{slots.scrollbar->x+12,slots.scrollbar->y+84,2,slots.scrollbar->height});scroll["backgroundColor"]=color(a.accent);append(out.apps,std::move(scroll));}return out;
}
}
