#include "modules/app_shortcut_presentation.hpp"
#include <algorithm>
#include <cmath>

namespace endfield::modules {
namespace {
using J=ShortcutJson;using R=core::Rect;using C=ShortcutColor;
void need(bool v,const char*m){if(!v)throw std::invalid_argument(m);}
J color(C c){for(auto x:c)need(std::isfinite(x)&&x>=0&&x<=1,"Invalid shortcut source color");return J::Object{{"sRGB",J::Array{c[0],c[1],c[2],c[3]}}};}
C gray(double w,double a=1){return {w,w,w,a};}C alpha(C c,double a){c[3]=a;return c;}
J box(R r){return J::Array{r.x,r.y,r.width,r.height};}
J node(R r,const char*kind="layer"){return J::Object{{"kind",kind},{"bounds",box({0,0,r.width,r.height})},{"position",J::Array{r.x,r.y}},{"anchorPoint",J::Array{0,0}},{"children",J::Array{}}};}
J shape(R r,J path,std::optional<C>fill,std::optional<C>stroke,double width=1){auto out=node(r,"shape");out["shape"]=J::Object{{"path",std::move(path)},{"fillColor",fill?color(*fill):J{}},{"strokeColor",stroke?color(*stroke):J{}},{"lineWidth",width},{"lineCap","butt"},{"lineJoin","miter"}};return out;}
J plate(R r,C fill,double radius=3,std::optional<C>border={},double width=0){auto out=node(r);out["backgroundColor"]=color(fill);out["cornerRadius"]=radius;if(border)out["borderColor"]=color(*border);out["borderWidth"]=width;return out;}
J text(std::string value,R r,double size,C ink,const char*weight="regular",bool center=false,bool wrap=false){auto out=node(r,"text");const bool regular=std::string_view(weight)=="regular",bold=std::string_view(weight)=="bold";out["text"]=J::Object{{"string",std::move(value)},{"fontSize",size},{"font",J::Object{{"familyName",".AppleSystemUIFont"},{"postScriptName",regular?".AppleSystemUIFont":bold?".AppleSystemUIFontBold":".AppleSystemUIFontDemi"},{"pointSize",size},{"symbolicTraits",regular?0:2}}},{"foregroundColor",color(ink)},{"alignment",center?"center":"left"},{"wrapped",wrap},{"truncation","end"}};return out;}
J scaled(const J&path,double x,double y){J::Array result;result.reserve(path.array().size());for(const auto&command:path.array()){J::Array points;for(const auto&p:command["points"].array())points.push_back(J::Array{p.array()[0].number()*x,p.array()[1].number()*y});result.push_back(J::Object{{"op",command["op"]},{"points",std::move(points)}});}return result;}
void validPath(const J&p){need(p.isArray()&&p.array().size()<=128,"Invalid source shortcut path");for(const auto&v:p.array()){const auto op=v["op"].string();const std::size_t count=op=="move"||op=="line"?1:op=="quadratic"?2:op=="cubic"?3:op=="close"?0:999;need(v["points"].isArray()&&v["points"].array().size()==count,"Invalid source shortcut command");for(const auto&q:v["points"].array())need(q.isArray()&&q.array().size()==2&&std::isfinite(q.array()[0].number())&&std::isfinite(q.array()[1].number()),"Invalid source shortcut point");}}
std::string L(core::Language l,std::string_view e,std::string_view z){return core::localized(e,z,l);}
}
AppShortcutArtwork::AppShortcutArtwork(const J&source){need(source["version"].integer()==1&&source["glyphs"].isArray()&&source["glyphs"].array().size()==14,"Invalid shortcut artwork catalog");for(const auto&v:source["glyphs"].array()){auto id=v["id"].string();need(validShortcutIcon(id)&&!glyphs_.contains(id),"Duplicate shortcut artwork");validPath(v["path"]);if(v.contains("sourceAsset")){need(v["sourceAsset"].string().starts_with("AppIconSources/EndfieldWiki/")&&v["sourceAsset"].string().ends_with(".png")&&v["sourceAsset"].string().find("..") ==std::string::npos&&v["sha256"].string().size()==64,"Invalid original shortcut image");}glyphs_.emplace(std::move(id),v);}pencil_=source["pencil"];validPath(pencil_);for(const auto&[id,p]:source["rounded"].object()){validPath(p);rounded_.emplace(id,p);}}
const J&AppShortcutArtwork::roundedPath(double width,double height)const{const auto key=std::to_string(static_cast<unsigned>(width))+"x"+std::to_string(static_cast<unsigned>(height));const auto found=rounded_.find(key);need(found!=rounded_.end()&&width==std::floor(width)&&height==std::floor(height),"Missing exact shortcut control path");return found->second;}
J AppShortcutArtwork::glyph(std::string_view id,R r,C ink)const{const auto found=glyphs_.find(id);need(found!=glyphs_.end(),"Unknown shortcut glyph");const auto&v=found->second;if(v.contains("sourceAsset")){auto out=node(r);out["contents"]=J::Object{{"asset",v["sourceAsset"]},{"sha256",v["sha256"]}};out["contentsGravity"]="resizeAspect";out["contentsSourceInTint"]=color(ink);return out;}auto out=shape(r,scaled(v["path"],r.width/28,r.height/28),{},ink,std::max(1.,r.width/17));out["shape"]["lineCap"]="round";out["shape"]["lineJoin"]="round";return out;}
J AppShortcutArtwork::pencil(R r,C ink)const{return shape(r,scaled(pencil_,r.width/16,r.height/16),{},ink,1.1);}
std::string shortcutActionID(const ShortcutAction&a){switch(a.kind){case ShortcutActionKind::choose:return "apps:choose";case ShortcutActionKind::name:return "apps:name";case ShortcutActionKind::icon:return "apps:icon:"+a.value;case ShortcutActionKind::cancel:return "apps:cancel";case ShortcutActionKind::save:return "apps:save";case ShortcutActionKind::launch:return "apps:"+a.value+":launch";case ShortcutActionKind::edit:return "apps:"+a.value+":edit";case ShortcutActionKind::remove:return "apps:"+a.value+":remove";}throw std::invalid_argument("Unknown shortcut action");}
std::string shortcutActionLabel(const ShortcutAction&a,const AppShortcutState&s,core::Language language){const auto local=[&](auto e,auto z){return L(language,e,z);};switch(a.kind){case ShortcutActionKind::choose:return local("Choose application","选择应用");case ShortcutActionKind::name:return local("Rename: ","重命名：")+s.draftName();case ShortcutActionKind::cancel:return local("Cancel","取消");case ShortcutActionKind::save:return local("Save shortcut","保存快捷方式");case ShortcutActionKind::icon:{constexpr std::array en{"App icon","Bolt","Star","Terminal","Globe","Folder","Music","Play","Brush","Code","Game","Camera","Grid","Text bubble"};constexpr std::array zh{"原始图标","闪电","星形","终端","地球","文件夹","音乐","播放","画笔","代码","游戏","相机","网格","文字气泡"};const auto found=std::find(shortcutIconOrder.begin(),shortcutIconOrder.end(),a.value);need(found!=shortcutIconOrder.end(),"Unknown shortcut icon action");const auto n=found-shortcutIconOrder.begin();return local(en[n],zh[n])+(a.value==s.draftIcon()?local(", selected","，已选择"):"");}default:break;}const auto found=std::find_if(s.file().items.begin(),s.file().items.end(),[&](const auto&v){return v.id==a.value;});need(found!=s.file().items.end(),"Missing shortcut action record");return (a.kind==ShortcutActionKind::launch?local("Open ","打开 "):a.kind==ShortcutActionKind::edit?local("Edit ","编辑 "):local("Remove shortcut: ","移除快捷方式："))+found->name;}
std::vector<ShortcutSurface>prepareAppShortcutArtwork(const AppShortcutState&s,const AppShortcutArtwork&art,const ShortcutAppearance&a,const ShortcutOriginalImages&images){std::vector<ShortcutSurface>out;const auto ink=gray(a.dark?.94:.12),muted=gray(a.dark?.65:.35);(void)color(a.accent);const auto local=[&](auto e,auto z){return L(a.language,e,z);};
    auto add=[&](std::string id,J content,std::optional<R>clip={},ShortcutSurfaceRole role=ShortcutSurfaceRole::artwork,std::string action={}){const auto&p=content["position"].array();const auto matrix=core::Matrix4::translation(p[0].number(),p[1].number());content["position"]=J::Array{0,0};content["id"]=id;out.push_back({std::move(id),std::move(action),std::move(content),matrix,clip,role});};
    auto feedback=[&](const std::string&id,R r,std::optional<R>clip){add(id+"/tint",shape(r,art.roundedPath(r.width,r.height),alpha(a.accent,.30),{}),clip,ShortcutSurfaceRole::tint,id);add(id+"/rim",shape(r,art.roundedPath(r.width,r.height),{},a.accent,.9),clip,ShortcutSurfaceRole::rim,id);};
    auto control=[&](std::string id,std::string title,R r,std::optional<R>clip={},bool highlighted=false,bool left=false,bool pencil=false){add(id+"/plate",plate(r,highlighted?a.accent:gray(a.dark?.95:.16,.12)),clip);feedback(id,r,clip);if(pencil)add(id+"/pencil",art.pencil({r.x+r.width/2-7,r.y+r.height/2-7,14,14},ink),clip);else add(id+"/label",text(std::move(title),{r.x+6,r.y+6,r.width-12,r.height-8},11,highlighted?gray(.1):ink,"semibold",!left),clip);};
    auto image=[&](std::string id,std::string_view key,R r,std::optional<R>clip={}){if(key.empty())add(std::move(id),art.glyph("grid",{r.x+3,r.y+3,r.width-6,r.height-6},muted),clip);else{auto n=node(r);n["contents"]=J::Object{{"asset",std::string(key)}};n["contentsGravity"]="resizeAspect";add(std::move(id),std::move(n),clip);}};
    if(!s.editing()){
        if(s.file().items.empty())add("apps.empty",art.glyph("grid",{183,135,58,58},muted),shortcutListRect);
        const auto first=static_cast<std::size_t>(s.scrollOffset()/52),end=std::min(s.file().items.size(),first+7);for(auto n=first;n<end;++n){const auto&v=s.file().items[n];const R r{12,44+double(n)*52-s.scrollOffset(),376,46};if(r.y+r.height<=44||r.y>=296)continue;const auto id="apps:"+v.id;add(id+"/plate",plate(r,gray(a.dark?.95:.15,a.dark?.09:.07)),shortcutListRect);feedback(id+":launch",{r.x,r.y,306,46},shortcutListRect);if(v.iconPreset=="original"){const auto found=images.items.find(v.id);image(id+"/icon",found==images.items.end()?std::string_view{}:found->second,{r.x+9,r.y+7,32,32},shortcutListRect);}else add(id+"/icon",art.glyph(v.iconPreset,{r.x+12,r.y+10,26,26},a.accent),shortcutListRect);
            add(id+"/name",text(v.name,{r.x+50,r.y+7,251,17},12,ink,"semibold"),shortcutListRect);add(id+"/original",text(v.originalName,{r.x+50,r.y+26,251,14},9,muted),shortcutListRect);control(id+":edit","",{r.x+312,r.y+10,26,26},shortcutListRect,false,false,true);control(id+":remove","×",{r.x+344,r.y+10,26,26},shortcutListRect);}
    }
    add("apps.heading",text("// "+local("APPLICATIONS","应用快捷方式"),{12,7,248,22},15,ink,"bold"));control("apps:choose",local("+ Choose app","+ 选择应用"),{270,2,118,28});
    if(s.editing()){
        if(s.draftIcon()=="original")image("apps.preview",images.draft,{19,55,45,45});else add("apps.preview",art.glyph(s.draftIcon(),{23,59,37,37},ink));out.back().role=ShortcutSurfaceRole::preview;
        add("apps.candidate",text(s.candidate()->name,{78,48,304,21},14,ink,"semibold"));control("apps:name",s.draftName().empty()?local("Shortcut name","快捷方式名称"):s.draftName(),shortcutNameRect,{},false,true);add("apps.icon-label",text(local("ICON","图标"),{12,116,180,18},10,muted,"bold"));
        for(std::size_t n=0;n<14;++n){const auto key=shortcutIconOrder[n];const auto r=shortcutIconRect(n);const auto id="apps:icon:"+std::string(key);const bool selected=key==s.draftIcon();add(id+"/plate",plate(r,selected?alpha(a.accent,.22):gray(a.dark?1:0,.07),3,selected?a.accent:alpha(muted,.3),selected?1.5:.5));feedback(id,r,{});if(key=="original")image(id+"/glyph",images.draft,{r.x+10,r.y+10,28,28});else add(id+"/glyph",art.glyph(key,{r.x+12,r.y+12,24,24},ink));}
        control("apps:cancel",local("Cancel","取消"),{134,274,108,28});control("apps:save",local("Save shortcut","保存快捷方式"),{252,274,136,28},{},true);
    }
    if(s.error())add("apps.error",text(*s.error(),{12,309,376,24},10,a.dark?C{1,214./255,10./255,1}:C{1,69./255,58./255,1},"regular",false,true));
    if(s.dropTarget())add("apps.drop",shape({5,36,390,266},art.roundedPath(390,266),alpha(a.accent,.06),a.accent,2));
    return out;
}
}
