#include "modules/archive_presentation.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <stdexcept>

namespace endfield::modules {
namespace {
using J=ArchiveJson;using Rect=core::Rect;using Point=core::Point;using Color=ArchiveColor;
void need(bool v,const char*m){if(!v)throw std::invalid_argument(m);}
bool contains(Rect r,Point p){return p.x>=r.x&&p.y>=r.y&&p.x<r.x+r.width&&p.y<r.y+r.height;}
Color gray(double w,double a=1){return {w,w,w,a};}Color alpha(Color c,double a){c[3]=a;return c;}
J color(Color c){return J::Object{{"sRGB",J::Array{c[0],c[1],c[2],c[3]}}};}J box(Rect r){return J::Array{r.x,r.y,r.width,r.height};}
void string(std::string_view s){need(J::validUtf8(s)&&s.size()<=archiveMaximumPayloadBytes&&s.find('\0')==std::string_view::npos,"Invalid Archive localized/display text");}
void validate(const ArchiveAppearance&a,const ArchiveStrings&s){need(std::isfinite(a.contentsScale)&&a.contentsScale>=1&&a.contentsScale<=8,"Invalid source Archive scale");for(const auto*c:{&a.accent,a.systemOrange?&*a.systemOrange:nullptr})if(c)for(double v:*c)need(std::isfinite(v)&&v>=0&&v<=1,"Invalid source Archive color");
    for(const auto*p:{&s.heading,&s.all,&s.uncategorized,&s.untitled,&s.documents,&s.createDocument,&s.title,&s.content,&s.category,&s.newCategory,&s.deleteDocument,&s.deleteCategory,&s.categoryRemovalDetail,&s.cancel,&s.remove})string(*p);}
J layer(std::string id,Rect r,const char*kind="layer"){return J::Object{{"id",std::move(id)},{"kind",kind},{"frame",box(r)},{"bounds",box({0,0,r.width,r.height})},{"position",J::Array{r.x,r.y}},{"anchorPoint",J::Array{0,0}},{"opacity",1},{"children",J::Array{}}};}
void add(J&parent,J child){auto children=parent["children"].array();children.push_back(std::move(child));parent["children"]=std::move(children);}
J plate(std::string id,Rect r,Color c){auto out=layer(std::move(id),r);out["backgroundColor"]=color(c);return out;}
J text(std::string id,Rect r,std::string value,double size,Color c,double scale,const char*role="medium",const char*align="natural",bool truncate=true){string(value);auto out=layer(std::move(id),r,"text");out["contentsScale"]=scale;const bool semi=std::string_view(role)=="semibold",regular=std::string_view(role)=="regular";
    out["contentsGravity"]="topLeft";out["text"]=J::Object{{"string",std::move(value)},{"fontSize",size},{"font",J::Object{{"familyName",".AppleSystemUIFont"},{"postScriptName",semi?".AppleSystemUIFontDemi":regular?".AppleSystemUIFont":".AppleSystemUIFontMedium"},{"pointSize",size},{"symbolicTraits",semi?2:0}}},{"foregroundColor",color(c)},{"alignment",align},{"wrapped",false},{"truncation",truncate?"end":"none"},{"runs",J::Array{}}};return out;}
J cmd(const char*op,std::initializer_list<Point>points={}){J::Array out;for(auto p:points)out.push_back(J::Array{p.x,p.y});return J::Object{{"op",op},{"points",std::move(out)}};}
J::Array cut(Rect r){const double c=std::min(4.,std::min(r.width,r.height)/3);return {cmd("move",{{r.x+c,r.y}}),cmd("line",{{r.x+r.width,r.y}}),cmd("line",{{r.x+r.width,r.y+r.height-c}}),cmd("line",{{r.x+r.width-c,r.y+r.height}}),cmd("line",{{r.x,r.y+r.height}}),cmd("line",{{r.x,r.y+c}}),cmd("close")};}
J::Array rounded(Rect r){const auto x=r.x,y=r.y,w=r.width,h=r.height,c=std::min({3.,w/2,h/2}),k=c*.5522847498;return {cmd("move",{{x+w,y+h/2}}),cmd("line",{{x+w,y+h-c}}),cmd("cubic",{{x+w,y+h-c+k},{x+w-c+k,y+h},{x+w-c,y+h}}),cmd("line",{{x+c,y+h}}),cmd("cubic",{{x+c-k,y+h},{x,y+h-c+k},{x,y+h-c}}),cmd("line",{{x,y+c}}),cmd("cubic",{{x,y+c-k},{x+c-k,y},{x+c,y}}),cmd("line",{{x+w-c,y}}),cmd("cubic",{{x+w-c+k,y},{x+w,y+c-k},{x+w,y+c}}),cmd("close")};}
J shape(std::string id,Rect r,J::Array path,std::optional<Color>fill={},std::optional<Color>stroke={},double width=1){auto out=layer(std::move(id),r,"shape");out["shape"]=J::Object{{"path",std::move(path)},{"fillColor",fill?color(*fill):J{}},{"strokeColor",stroke?color(*stroke):J{}},{"lineWidth",width},{"lineCap","butt"},{"lineJoin","miter"},{"miterLimit",10},{"fillRule","non-zero"}};return out;}
struct Build {
    ArchiveArtwork result;const ArchiveAppearance&a;Color ink;bool menu{};
    void highlight(J&parent,std::string action,Rect local,Rect world,bool cutCorner,bool framed,bool enabled=true,std::optional<Rect>clip={}){
        const auto id=parent["id"].string()+"/highlight/"+action;auto root=layer(id,local);root["name"]="hud.control.highlight";root["allowsGroupOpacity"]=false;const Rect b{0,0,local.width,local.height},rim=framed?Rect{-2,-2,b.width+4,b.height+4}:b;
        auto tint=shape(id+"/tint",b,cutCorner?cut(b):rounded(b),alpha(a.accent,.30));tint["opacity"]=0;auto edge=shape(id+"/rim",b,cutCorner?cut(rim):rounded(rim),{},a.accent,.9);edge["opacity"]=enabled&&framed?.28:0;add(root,std::move(tint));add(root,std::move(edge));add(parent,std::move(root));result.feedback.push_back({std::move(action),id+"/tint",id+"/rim",world,clip,cutCorner,framed,enabled});
    }
    void action(J&face,std::string id,std::string title,Rect r,bool selected=false,bool enabled=true){result.actions.push_back({id,title,r,enabled,selected});add(face,plate("archive/action/"+id+"/plate",r,selected?alpha(a.accent,.28):alpha(ink,.07)));add(face,text("archive/action/"+id+"/label",{r.x+4,r.y+5,r.width-8,r.height-10},std::move(title),10,enabled?ink:alpha(ink,.3),a.contentsScale,"medium","center"));highlight(face,std::move(id),r,r,true,true,enabled);}
    void menuItem(J&face,const ArchiveAction&item,bool transparent=false){const auto&r=item.rect;auto p=plate("archive/menu/item/"+item.id,r,transparent?gray(0,0):item.selected?alpha(a.accent,.22):alpha(ink,.07));p["opacity"]=item.enabled||transparent?1:.4;add(face,std::move(p));if(!transparent){if(item.enabled)highlight(face,item.id,r,r,true,true);add(face,text("archive/menu/item/"+item.id+"/label",{r.x+6,r.y+5,r.width-12,r.height-10},item.title,10,ink,2,"semibold"));}}
};
void contents(const J&j){need(j.isObject()&&((j["asset"].isString()&&j["sha256"].isString())||(j["memoryImage"].isString()&&j["revision"].isNumber())),"Archive artwork needs an exact original/prepared image binding");}
Rect inset(Rect r,double dx,double dy){return {r.x+dx,r.y+dy,r.width-2*dx,r.height-2*dy};}
}
ArchiveArtwork prepareArchiveArtwork(const ArchiveState&state,const ArchiveViewInput&i){validate(i.appearance,i.strings);need(i.dateString&&i.categoryCaptionWidth,"Archive requires source date and native caption metrics");need(std::isfinite(i.mediaTime)&&i.mediaTime>=0,"Invalid Archive media time");for(double c:i.formattingColor)need(std::isfinite(c)&&c>=0&&c<=1,"Invalid Archive formatting color");if(i.formattingField)need(*i.formattingField=="title"||*i.formattingField=="body","Unknown Archive formatting field");
    const auto&a=i.appearance;const auto ink=gray(a.dark?.94:.12);Build b{{},a,ink};auto root=layer("archive.canvas",ArchiveState::bounds());root["name"]="archive.canvas";auto backdrop=plate("archive.backdrop",ArchiveState::bounds(),gray(a.dark?.065:.94,.96));backdrop["name"]="archive.backdrop";backdrop["cornerRadius"]=4;add(root,std::move(backdrop));auto face=layer("archive.face",ArchiveState::bounds());face["name"]="archive.face";
    add(face,text("archive/heading",{14,10,239,22},"// "+i.strings.heading,14,ink,a.contentsScale));add(face,plate("archive/headerLine",{14,35,372,1},alpha(ink,.24)));add(face,plate("archive/headerAccent",{14,35,58,2},a.accent));
    if(state.selected()){
        const auto&e=*state.selected();need(e.media.empty()||i.mediaIndex<e.media.size(),"Archive media index exceeds selected document");b.action(face,"back","‹",{265,5,26,25});b.action(face,"moveCategory","▾",{296,5,26,25});b.action(face,"addMedia","+",{327,5,26,25});b.action(face,"delete","×",{358,5,26,25});
        add(face,text("archive/title",ArchiveState::titleRect(),e.title.empty()?i.strings.title:e.title,17,e.title.empty()?alpha(ink,.4):ink,a.contentsScale));add(face,text("archive/date",ArchiveState::dateRect(),i.dateString(e.date),10,alpha(ink,.55),a.contentsScale));if(e.body.empty())add(face,text("archive/bodyPlaceholder",state.bodyRect(),i.strings.content,12,alpha(ink,.4),a.contentsScale));
        if(!e.media.empty()){b.action(face,"mediaPrevious","‹",{284,270,28,26});b.action(face,"mediaNext","›",{345,270,28,26});auto counter=text("archive/mediaCounter",{312,276,33,16},std::to_string(i.mediaIndex+1)+"/"+std::to_string(e.media.size()),9,ink,a.contentsScale,"medium","center");counter["name"]="archive.media.counter";add(face,std::move(counter));b.action(face,"removeMedia","×",{345,310,28,26});const auto&media=e.media[i.mediaIndex];if(media["kind"].string()!="image"){b.action(face,"mediaPlay",i.mediaPlaying?"Ⅱ":"▷",{284,310,28,26});add(face,plate("archive/mediaRail",{24,372,250,2},alpha(ink,.2)));const auto duration=media["duration"].isNull()?1:media["duration"].number();add(face,plate("archive/mediaProgress",{24,372,250*std::min(1.,i.mediaTime/std::max(.01,duration)),2},a.accent));}if(i.mediaError)add(face,text("archive/mediaError",{24,347,245,22},*i.mediaError,9,ink,a.contentsScale));}
    }else{
        auto gallery=layer("archive.gallery",ArchiveState::galleryRect());gallery["name"]="archive.gallery";gallery["masksToBounds"]=true;
        for(const auto&row:state.galleryRows()){const auto&e=state.entries()[row.index];const auto id="archive/card/"+e.id;auto card=plate(id,row.local,gray(a.dark?.86:1,.93));card["name"]="archive.card."+e.id;add(card,plate(id+"/bracketX",{5,5,18,3},gray(0)));add(card,plate(id+"/bracketY",{5,5,3,17},gray(0)));auto fallback=layer(id+"/fallback",{4,4,124,52});auto icon=layer(id+"/icon",{43,8,39,39});icon["name"]="endfield.icon.Archive_Icon";icon["contentsScale"]=a.contentsScale;icon["contentsGravity"]="resizeAspect";contents(i.iconContents);icon["contents"]=i.iconContents;add(fallback,std::move(icon));const auto poster=i.posterContents.find(e.id);fallback["hidden"]=poster!=i.posterContents.end();add(card,std::move(fallback));auto image=layer(id+"/poster",{4,4,124,52});image["contentsGravity"]="resizeAspectFill";image["masksToBounds"]=true;if(poster!=i.posterContents.end()){contents(poster->second);image["contents"]=poster->second;}add(card,std::move(image));add(card,plate(id+"/titleBar",{4,58,124,23},gray(0,.85)));add(card,text(id+"/title",{10,63,112,18},e.title.empty()?i.strings.untitled:e.title,10,gray(1),a.contentsScale));add(card,text(id+"/date",{9,89,115,18},i.dateString(e.date),9,gray(1./3),a.contentsScale));const std::string action="entry:"+e.id;b.highlight(card,action,{0,0,132,113},{101+row.local.x,49+row.local.y,132,113},true,true,true,ArchiveState::galleryRect());add(gallery,std::move(card));b.result.actions.push_back({action,e.title.empty()?i.strings.untitled:e.title,row.hit});}
        add(face,std::move(gallery));auto categories=layer("archive.categories",{11,46,81,244});categories["name"]="archive.categories";categories["bounds"]=box({-3,-3,81,244});categories["masksToBounds"]=true;
        for(const auto&row:state.categoryRows()){const auto id=row.index<2?std::string(row.id):"category:"+std::string(row.id);const auto title=row.index==0?i.strings.all:row.index==1?i.strings.uncategorized:state.categories()[row.index-2].name;const auto width=i.categoryCaptionWidth(title);need(std::isfinite(width)&&width>=0,"Invalid native Archive caption width");const auto fontSize=std::clamp(10*67/std::max(1.,width),8.,10.);auto node=plate("archive/category/"+id,row.local,row.selected?alpha(a.accent,.28):alpha(ink,.07));node["name"]="archive.category."+id;add(node,text(node["id"].string()+"/label",{4,5,67,17},title,fontSize,ink,a.contentsScale,"medium","center"));b.highlight(node,id,{0,0,75,27},{14,49+row.local.y,75,27},true,true,true,Rect{11,46,81,244});add(categories,std::move(node));b.result.actions.push_back({id,title,row.hit,true,row.selected});}
        add(face,std::move(categories));auto track=plate("archive/galleryTrack",{383,49,2,357},alpha(ink,.14));track["name"]="archive.gallery.scrollTrack";track["hidden"]=!state.galleryThumb();add(face,std::move(track));auto knob=plate("archive/galleryKnob",state.galleryThumb()?inset(*state.galleryThumb(),2,0):Rect{},alpha(ink,.65));knob["name"]="archive.gallery.scrollThumb";knob["cornerRadius"]=2;knob["hidden"]=!state.galleryThumb();add(face,std::move(knob));b.action(face,"new","+",{14,302,30,29});b.action(face,"deleteCategory","−",{50,302,30,29},false,state.categoryID().has_value());char count[32];std::snprintf(count,sizeof(count),"%03zu",state.filteredIndices().size());add(face,text("archive/count",{14,344,80,43},count,27,a.accent,a.contentsScale));add(face,text("archive/documents",{14,380,80,20},i.strings.documents,10,ink,a.contentsScale));if(state.filteredIndices().empty())add(face,text("archive/empty",{130,189,235,30},i.strings.createDocument,15,ink,a.contentsScale));
    }
    if(state.selected()&&i.formattingField){constexpr std::array<const char*,4>ids{"formatSize","formatFont","formatColor","formatSpecial"},titles{"A↕","Aa","","B"};for(unsigned n=0;n<4;++n){const Rect r{24+double(n)*26,382,22,22};b.result.actions.push_back({ids[n],titles[n],r});auto p=plate("archive/format/"+std::string(ids[n]),r,gray(a.dark?.18:.82));p["borderWidth"]=.5;p["borderColor"]=color(alpha(a.accent,.6));if(n==2)add(p,plate(p["id"].string()+"/swatch",{4,4,14,14},i.formattingColor));else add(p,text(p["id"].string()+"/label",{2,3,18,15},titles[n],10,ink,a.contentsScale,"regular","natural",false));add(face,std::move(p));b.highlight(face,ids[n],r,r,false,false);}}
    const auto error=i.statusMessage?i.statusMessage:state.error();if(error){need(a.systemOrange.has_value(),"Archive error requires caller's source system orange");add(face,text("archive/error",{14,421,state.error()?332.:372.,18},*error,9,*a.systemOrange,a.contentsScale));if(state.error())b.action(face,"retry","↻",{354,416,32,22});}else if(!i.formattingField)add(face,text("archive/footer",{14,425,230,13},"ENDFIELD  /  ARCHIVE",7,alpha(ink,.3),a.contentsScale));add(root,std::move(face));b.result.root=std::move(root);return std::move(b.result);
}
ArchiveArtwork prepareArchiveMenu(const ArchiveMenuInput&i){validate(i.appearance,i.strings);need(i.categories.size()<=archiveMaximumCategories&&std::isfinite(i.scrollOffset)&&i.scrollOffset>=0,"Invalid Archive category menu input");const auto&a=i.appearance;const auto ink=gray(a.dark?.96:.1);Build b{{},a,ink,true};const bool category=i.kind==ArchiveMenuKind::category,removeCategory=i.kind==ArchiveMenuKind::deleteCategory;need(category||i.kind==ArchiveMenuKind::deleteDocument||removeCategory,"Unknown Archive menu");const Rect bounds{0,0,category?260.:240.,category?294.:removeCategory?111.:83.};auto root=layer("archive.menu",bounds);root["name"]="notes.secondaryMenu";root["zPosition"]=2000000;add(root,plate("archive/menu/shadow",{-3,4,bounds.width,bounds.height},gray(0,.30)));auto face=plate("archive/menu/face",bounds,gray(a.dark?.08:.92,.98));face["borderWidth"]=.7;face["borderColor"]=color(alpha(a.accent,.7));
    if(category){const double maximum=std::max(0.,double(i.categories.size()+1)*32-4-188);need(i.scrollOffset<=maximum,"Archive category menu scroll exceeds source maximum");b.result.actions.push_back({"close","×",{229,8,23,23}});b.menuItem(face,b.result.actions.back());const auto first=std::min(i.categories.size()+1,std::size_t(std::floor(i.scrollOffset/32))),last=std::min(i.categories.size()+1,std::size_t(std::ceil((i.scrollOffset+188)/32)));std::vector<ArchiveAction>rows;for(std::size_t n=first;n<last;++n){const Rect r{12,43+double(n)*32-i.scrollOffset,236,28};const double top=std::max(43.,r.y),bottom=std::min(231.,r.y+28);if(bottom-top<2)continue;const auto id=n==0?"uncategorized":i.categories[n-1].id,title=n==0?i.strings.uncategorized:i.categories[n-1].name;string(title);need(n==0||ehud::data::validUUID(id),"Invalid Archive category menu identity");rows.push_back({id,title,r});b.result.actions.push_back({id,title,{12,top,236,bottom-top}});b.menuItem(face,b.result.actions.back(),true);}
        b.result.actions.push_back(i.editingName?ArchiveAction{"create","✓",{218,252,30,28}}:ArchiveAction{"newCategory","+ "+i.strings.newCategory,{12,252,236,28}});b.menuItem(face,b.result.actions.back());add(face,text("archive/menu/heading",{12,12,209,22},"// "+i.strings.category,12,ink,2,"semibold"));auto clip=layer("archive/menu/rows",{9,40,242,194});clip["bounds"]=box({-3,-3,242,194});clip["name"]="archive.categoryMenu.rows";clip["masksToBounds"]=true;for(const auto&row:rows){const Rect r{0,row.rect.y-43,236,28};auto p=plate("archive/menu/row/"+row.id,r,alpha(ink,.07));add(p,text(p["id"].string()+"/label",{6,5,224,18},row.title,10,ink,2,"semibold"));b.highlight(p,row.id,{0,0,236,28},row.rect,true,true,true,Rect{9,40,242,194});add(clip,std::move(p));}add(face,std::move(clip));
    }else{const double y=removeCategory?72:44;b.result.actions={{"cancel",i.strings.cancel,{10,y,105,28}},{"delete",i.strings.remove,{125,y,105,28}}};for(const auto&item:b.result.actions)b.menuItem(face,item);add(face,text("archive/menu/heading",{10,12,220,25},"// "+(removeCategory?i.strings.deleteCategory:i.strings.deleteDocument),12,ink,2,"semibold"));if(removeCategory)add(face,text("archive/menu/detail",{10,40,220,25},i.strings.categoryRemovalDetail,10,ink,2,"semibold"));}
    add(root,std::move(face));b.result.root=std::move(root);return std::move(b.result);
}
std::optional<std::string_view>archiveActionAt(std::span<const ArchiveAction>actions,Point p)noexcept{if(!std::isfinite(p.x)||!std::isfinite(p.y))return {};for(auto it=actions.rbegin();it!=actions.rend();++it)if(it->enabled&&contains(it->rect,p))return it->id;return {};}
bool archiveFeedbackContains(const ArchiveFeedback&f,Point p)noexcept{if(!f.enabled||!std::isfinite(p.x)||!std::isfinite(p.y)||!contains(f.rect,p)||(f.clip&&!contains(*f.clip,p)))return false;const auto&r=f.rect;if(f.cutCorner){const auto c=std::min(4.,std::min(r.width,r.height)/3);const std::array<Point,6>path{{{r.x+c,r.y},{r.x+r.width,r.y},{r.x+r.width,r.y+r.height-c},{r.x+r.width-c,r.y+r.height},{r.x,r.y+r.height},{r.x,r.y+c}}};return core::polygonContains(path,p);}const auto radius=std::min({3.,r.width/2,r.height/2}),x=std::clamp(p.x,r.x+radius,r.x+r.width-radius),y=std::clamp(p.y,r.y+radius,r.y+r.height-radius);return (p.x-x)*(p.x-x)+(p.y-y)*(p.y-y)<=radius*radius;}
Point archiveCategoryMenuOrigin(bool moving)noexcept{return moving?Point{126,38}:Point{100,49};}
Point archiveMediaMenuOrigin(Rect bounds)noexcept{return {std::min(392-bounds.width,std::max(8.,353-bounds.width)),36};}
} // namespace endfield::modules
