#include "modules/calendar_presentation.hpp"
#include <algorithm>
#include <cmath>
#include <set>
namespace endfield::modules {
namespace {using J=CalendarJson;using R=core::Rect;using P=core::Point;using C=CalendarColor;
#include "modules/calendar_refresh_path.inc"
void need(bool b){if(!b)throw std::invalid_argument("Invalid Calendar presentation");}J box(R r){return J::Array{r.x,r.y,r.width,r.height};}J color(C c){return J::Object{{"sRGB",J::Array{c[0],c[1],c[2],c[3]}}};}C gray(double v,double a=1){return{v,v,v,a};}C alpha(C c,double a){c[3]=a;return c;}void valid(C c){for(auto v:c)need(std::isfinite(v)&&v>=0&&v<=1);}
J layer(std::string id,R r){return J::Object{{"id",std::move(id)},{"kind","layer"},{"bounds",box({0,0,r.width,r.height})},{"position",J::Array{r.x,r.y}},{"anchorPoint",J::Array{0,0}},{"opacity",1},{"children",J::Array{}}};}
J fill(std::string id,R r,C c){auto j=layer(std::move(id),r);j["backgroundColor"]=color(c);return j;}
J text(std::string id,std::string value,R r,double size,C c,std::string alignment="left"){auto j=layer(std::move(id),r);j["kind"]="text";j["text"]=J::Object{{"string",std::move(value)},{"fontSize",size},{"font",J::Object{{"familyName",".AppleSystemUIFont"},{"postScriptName",".AppleSystemUIFontDemi"},{"pointSize",size}}},{"foregroundColor",color(c)},{"alignment",std::move(alignment)},{"wrapped",false},{"truncation","end"},{"runs",J::Array{}}};return j;}
J command(const char*kind,std::initializer_list<P>p){J::Array v;for(auto q:p)v.emplace_back(J::Array{q.x,q.y});return J::Object{{"op",kind},{"points",std::move(v)}};}
J cut(R r){const double c=4;return J::Array{command("move",{{r.x+c,r.y}}),command("line",{{r.x+r.width,r.y}}),command("line",{{r.x+r.width,r.y+r.height-c}}),command("line",{{r.x+r.width-c,r.y+r.height}}),command("line",{{r.x,r.y+r.height}}),command("line",{{r.x,r.y+c}}),command("close",{})};}
J shape(std::string id,R r,J path,C c,bool rim=false,double opacity=1){auto j=layer(std::move(id),r);j["kind"]="shape";j["opacity"]=opacity;j["shape"]=J::Object{{"path",std::move(path)},{"fillColor",rim?J{}:color(c)},{"strokeColor",rim?color(c):J{}},{"lineWidth",rim?.9:1},{"lineCap","butt"},{"lineJoin","miter"},{"fillRule","non-zero"}};return j;}
void feedback(CalendarArtwork&out,J::Array&parent,const CalendarAction&a,C accent,std::string prefix,bool menu){if(menu&&!a.enabled)return;auto j=layer(prefix,a.rect);j["name"]="hud.control.highlight";j["allowsGroupOpacity"]=false;const auto tint=prefix+"/tint",rim=prefix+"/rim";j["children"]=J::Array{shape(tint,{0,0,a.rect.width,a.rect.height},cut({0,0,a.rect.width,a.rect.height}),alpha(accent,.30),false,0),shape(rim,{0,0,a.rect.width,a.rect.height},cut({-2,-2,a.rect.width+4,a.rect.height+4}),accent,true,a.enabled?.28f:0.f)};parent.push_back(std::move(j));out.feedback.push_back({a.id,tint,rim,a.rect,a.enabled,a.enabled?.28f:0.f});}
void canvasButton(CalendarArtwork&out,J::Array&parent,CalendarAction a,C ink,C accent,bool selected=false,bool centered=true,bool opaque=false,bool light=false,double lightGray=.82){const auto prefix="calendar/button/"+a.id;auto plate=shape(prefix+"/plate",a.rect,cut({0,0,a.rect.width,a.rect.height}),light?gray(lightGray):opaque?alpha(accent,1):selected?alpha(accent,.23):alpha(ink,.07));plate["name"]="calendar.button."+a.id;parent.push_back(std::move(plate));parent.push_back(text(prefix+"/label",a.label,{a.rect.x+(centered?3:8),a.rect.y+a.rect.height/2-7,a.rect.width-(centered?6:16),15},11,alpha(light||opaque?gray(.13):ink,a.enabled?1:.35),centered?"center":"left"));feedback(out,parent,a,accent,prefix+"/highlight",false);out.actions.push_back(std::move(a));}
void menuButton(CalendarArtwork&out,J::Array&parent,CalendarAction a,C ink,C accent){const auto prefix="calendar/menu/button/"+a.id;auto plate=fill(prefix+"/plate",a.rect,alpha(ink,.07));plate["opacity"]=a.enabled?1:.4;parent.push_back(std::move(plate));feedback(out,parent,a,accent,prefix+"/highlight",true);parent.push_back(text(prefix+"/label",a.label,{a.rect.x+6,a.rect.y+5,a.rect.width-12,a.rect.height-10},10,ink,"center"));out.actions.push_back(std::move(a));}
bool contains(R r,P p){return std::isfinite(p.x)&&std::isfinite(p.y)&&p.x>=r.x&&p.y>=r.y&&p.x<r.x+r.width&&p.y<r.y+r.height;}
}
CalendarStrings CalendarStrings::simplifiedChinese(){CalendarStrings s;s.calendar="日历";s.today="今天";s.noEvents="暂无事项";s.addEvent="添加事项";s.editEvent="编辑事项";s.title="标题";s.date="日期";s.details="详情";s.save="保存";s.cancel="取消";s.erase="删除";s.deleteQuestion="删除此事项？";s.previousMonth="上个月";s.nextMonth="下个月";s.refreshReminders="刷新提醒";s.denied="通知已在系统设置中关闭";s.unavailable="通知暂不可用";return s;}
std::vector<CalendarCell>calendarMonthCells(CalendarDay month,unsigned first){need(month.valid()&&first>=1&&first<=7);month.day=1;const auto padding=(month.weekday()+7-first)%7;std::vector<CalendarCell>cells;cells.reserve(month.daysInMonth());for(unsigned day=1;day<=month.daysInMonth();++day){const auto position=day-1+padding;cells.push_back({{month.year,month.month,int(day)},{12.+(position%7)*54,100.+(position/7)*30,50,26}});}return cells;}
CalendarArtwork prepareCalendarCanvas(const CalendarCanvasInput&i){valid(i.appearance.accent);need(i.today.valid()&&i.selected.valid()&&i.month.valid()&&i.firstWeekday>=1&&i.firstWeekday<=7&&i.events.size()<=calendarMaximumEvents);const auto ink=gray(i.appearance.dark?.95:.10),accent=i.appearance.accent;CalendarArtwork out;out.bounds={0,0,400,440};out.root=layer("calendar",out.bounds);out.root["name"]="calendar";auto face=layer("calendar/face",out.bounds);J::Array children;
    children.push_back(text("calendar/heading","// "+i.strings.calendar,{12,9,226,24},17,ink));canvasButton(out,children,{"today",i.strings.today,{305,8,80,27}},ink,accent,false,true,true);children.push_back(fill("calendar/rule",{12,41,376,1},alpha(ink,.2)));children.push_back(text("calendar/month",i.monthHeading.empty()?i.month.string():i.monthHeading,{53,54,294,22},15,ink,"center"));canvasButton(out,children,{"previousMonth","‹",{12,49,28,28},i.month.year>1900||i.month.month>1},ink,accent);canvasButton(out,children,{"nextMonth","›",{360,49,28,28},i.month.year<9999||i.month.month<12},ink,accent);
    for(unsigned n=0;n<7;++n)children.push_back(text("calendar/weekday/"+std::to_string(n),i.weekdays[(n+i.firstWeekday-1)%7],{12.+n*54,82,50,14},9,alpha(ink,.5),"center"));std::set<CalendarDay>occupied;for(const auto&e:i.events)occupied.insert(e.day);
    for(const auto&c:calendarMonthCells(i.month,i.firstWeekday)){const auto id=c.day.string();canvasButton(out,children,{"day:"+id,std::to_string(c.day.day),c.rect},ink,accent,c.day==i.selected);if(c.day==i.today){auto border=layer("calendar/today-border",{c.rect.x+1,c.rect.y+1,c.rect.width-2,c.rect.height-2});border["cornerRadius"]=2;border["borderWidth"]=.8;border["borderColor"]=color(alpha(accent,.75));children.push_back(std::move(border));}if(occupied.contains(c.day))children.push_back(fill("calendar/dot/"+id,{c.rect.x+c.rect.width/2-1.5,c.rect.y+c.rect.height-4,3,2},accent));}
    children.push_back(text("calendar/selected",i.selected.string(),{12,281,308,22},14,ink));canvasButton(out,children,{"new","+",{359,275,29,29},!i.busy},ink,accent,false,true,false,true,i.appearance.dark?.82:.9);std::vector<const CalendarEvent*>list;for(const auto&e:i.events)if(e.day==i.selected)list.push_back(&e);std::sort(list.begin(),list.end(),[](const auto*a,const auto*b){return a->created==b->created?a->id<b->id:a->created<b->created;});const auto first=std::min(i.firstEvent,list.size()>3?list.size()-3:0);for(auto n=first;n<std::min(list.size(),first+3);++n)canvasButton(out,children,{"event:"+list[n]->id,list[n]->title,{12,312+double(n-first)*29,376,25}},ink,accent,false,false);
    if(list.empty())children.push_back(text("calendar/empty",i.strings.noEvents,{12,336,376,25},12,alpha(ink,.4),"center"));std::optional<std::string>warning=i.error;if(!warning&&i.permission==CalendarPermission::denied)warning=i.strings.denied;if(!warning&&i.permission==CalendarPermission::unavailable)warning=i.strings.unavailable;if(warning)children.push_back(text("calendar/warning",*warning,{12,398,332,15},8,{1,159./255,10./255,1}));canvasButton(out,children,{"reminders","",{352,384,36,29},!i.busy},ink,accent,false,true,false,true,i.appearance.dark?.82:.9);
    static const J refresh=J::parse(calendarRefreshPath);auto arrow=shape("calendar/refresh",{359,387.5,22,22},refresh,gray(.13,i.busy?.35:1));arrow["name"]="calendar.refresh.arrow";children.push_back(std::move(arrow));face["children"]=std::move(children);out.root["children"]=J::Array{std::move(face)};return out;}
CalendarArtwork prepareCalendarMenu(const CalendarMenuInput&i){valid(i.appearance.accent);CalendarArtwork out;out.bounds={0,0,340,310};out.root=layer("calendar/menu",out.bounds);out.root["name"]="notes.secondaryMenu";const auto ink=gray(i.appearance.dark?.96:.10),accent=i.appearance.accent;auto face=fill("calendar/menu/face",out.bounds,gray(i.appearance.dark?.08:.92,.98));face["borderWidth"]=.7;face["borderColor"]=color(alpha(accent,.7));J::Array children;menuButton(out,children,{"close","×",{308,8,23,23}},ink,accent);menuButton(out,children,{"save","✓",{297,265,30,30},!i.busy},ink,accent);if(i.editing){menuButton(out,children,{i.deleting?"cancelDelete":"delete","×",{14,265,30,30},!i.busy},ink,accent);if(i.deleting)menuButton(out,children,{"confirmDelete","✓",{52,265,30,30},!i.busy},ink,accent);}children.push_back(text("calendar/menu/heading","// "+(i.editing?i.strings.editEvent:i.strings.addEvent),{14,10,280,22},13,ink,"natural"));const std::array<std::string,3>labels{i.strings.title,i.strings.date,i.strings.details};for(unsigned n=0;n<3;++n)children.push_back(text("calendar/menu/field/"+std::to_string(n),labels[n],{14,32.+n*50,312,14},9,alpha(ink,.55),"natural"));children.push_back(text("calendar/menu/status",i.error.value_or(i.deleting?i.strings.deleteQuestion:""),{14,243,312,17},9,i.error?C{1,159./255,10./255,1}:alpha(ink,.5),"natural"));face["children"]=std::move(children);out.root["children"]=J::Array{fill("calendar/menu/shadow",{-3,4,340,310},gray(0,.30)),std::move(face)};return out;}
std::optional<std::string_view>calendarActionAt(std::span<const CalendarAction>a,P p)noexcept{std::optional<std::string_view>found;for(const auto&v:a)if(v.enabled&&contains(v.rect,p))found=v.id;return found;}
CalendarView::CalendarView(CalendarDay today):selected_(today),month_{today.year,today.month,1}{need(today.valid());}
bool CalendarView::perform(std::string_view id,CalendarDay today){need(today.valid());if(id=="previousMonth"||id=="nextMonth"){if(auto next=month_.advancedMonth(id=="nextMonth"?1:-1)){month_=*next;++revision_;return true;}return false;}if(id=="today"){selected_=today;month_={today.year,today.month,1};first_=0;++revision_;return true;}if(id.starts_with("day:"))if(const auto day=CalendarDay::parse(id.substr(4))){selected_=*day;first_=0;++revision_;return true;}return false;}
bool CalendarView::scroll(P p,double delta,std::size_t count){if(!contains({0,0,400,440},p)||!std::isfinite(delta))return false;if(p.y>=308){remainder_+=std::clamp(delta,-256.,256.);const auto rows=static_cast<int>(remainder_/32);if(rows){remainder_-=rows*32.;const auto next=static_cast<std::size_t>(std::clamp(static_cast<std::int64_t>(first_)+rows,std::int64_t(0),static_cast<std::int64_t>(count>3?count-3:0)));if(next!=first_){first_=next;++revision_;}}}return true;}
void CalendarView::clampEvents(std::size_t count)noexcept{first_=std::min(first_,count>3?count-3:0);}
}
