#include "modules/calendar_model.hpp"
#include <algorithm>
#include <charconv>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <limits>
#include <set>
#include <tuple>
namespace endfield::modules {
namespace {using J=CalendarJson;using namespace std::chrono;
void need(bool b){if(!b)throw CalendarError(CalendarErrorCode::invalidData);}
year_month_day civil(CalendarDay d){return {year(d.year),month(static_cast<unsigned>(d.month)),day(static_cast<unsigned>(d.day))};}
CalendarDay parts(year_month_day d){return {int(d.year()),int(unsigned(d.month())),int(unsigned(d.day()))};}
std::string uuid(std::string v){need(ehud::data::validUUID(v));for(auto&c:v)if(c>='a'&&c<='f')c=char(c-'a'+'A');return v;}
J extras(J j,std::initializer_list<const char*>keys){for(const auto*k:keys)j.erase(k);return j;}
void numeric(J&out,const char*k,double value,const J&original){const auto&v=original[k];out[k]=v.isNumber()&&v.number()==value?v:J(value);}
std::optional<std::string>optionalString(const J&j,const char*k){return j[k].isNull()?std::optional<std::string>{}:j[k].string();}
CalendarEvent decodeEvent(const J&j){need(j.isObject()&&j["day"].isObject());CalendarEvent e;e.id=uuid(j["id"].string());e.title=j["title"].string();e.details=j["details"].string();
    const auto integer=[&](const char*k){const auto n=j["day"][k].integer();need(n>=std::numeric_limits<int>::min()&&n<=std::numeric_limits<int>::max());return int(n);};e.day={integer("year"),integer("month"),integer("day")};e.created=j["created"].number();e.modified=j["modified"].number();e.catchUpPending=j["catchUpPending"].boolean();if(!j["catchUpDate"].isNull())e.catchUpDate=j["catchUpDate"].number();e.beforeScheduledFor=optionalString(j,"beforeScheduledFor");e.dayScheduledFor=optionalString(j,"dayScheduledFor");
    e.originalFields=extras(j,{"id","title","details","day","created","modified","catchUpPending","catchUpDate","beforeScheduledFor","dayScheduledFor"});e.dayFields=extras(j["day"],{"year","month","day"});for(const auto*k:{"created","modified","catchUpDate"})if(j[k].isNumber())e.originalNumbers[k]=j[k];return e;}
J encodeEvent(const CalendarEvent&e){auto j=e.originalFields;j["id"]=uuid(e.id);j["title"]=e.title;j["details"]=e.details;auto day=e.dayFields;day["year"]=e.day.year;day["month"]=e.day.month;day["day"]=e.day.day;j["day"]=std::move(day);numeric(j,"created",e.created,e.originalNumbers);numeric(j,"modified",e.modified,e.originalNumbers);j["catchUpPending"]=e.catchUpPending;
    if(e.catchUpDate)numeric(j,"catchUpDate",*e.catchUpDate,e.originalNumbers);else j.erase("catchUpDate");if(e.beforeScheduledFor)j["beforeScheduledFor"]=*e.beforeScheduledFor;else j.erase("beforeScheduledFor");if(e.dayScheduledFor)j["dayScheduledFor"]=*e.dayScheduledFor;else j.erase("dayScheduledFor");return j;}
}
CalendarError::CalendarError(CalendarErrorCode c):std::runtime_error(c==CalendarErrorCode::changedOnDisk?"Calendar changed outside this app. Restart before saving.":c==CalendarErrorCode::capacity?"The calendar can keep up to 256 events.":c==CalendarErrorCode::upcomingCapacity?"Keep up to 30 upcoming events so every reminder can be scheduled.":c==CalendarErrorCode::invalidDate?"Enter a valid date as YYYY-MM-DD.":c==CalendarErrorCode::missing?"This event is no longer available.":c==CalendarErrorCode::notifications?"Reminders could not be scheduled. Try again.":"Calendar data could not be read. Your file was preserved."),code_(c){}
bool CalendarDay::valid()const noexcept{return year>=1900&&year<=9999&&month>=1&&month<=12&&day>=1&&day<=31&&civil(*this).ok();}
std::string CalendarDay::string()const{char v[24];std::snprintf(v,sizeof(v),"%04d-%02d-%02d",year,month,day);return v;}
std::optional<CalendarDay>CalendarDay::parse(std::string_view s)noexcept{CalendarDay d;int*fields[]{&d.year,&d.month,&d.day};std::size_t at{};for(unsigned n=0;n<3;++n){const auto end=n==2?s.size():s.find('-',at);if(end==s.npos||end<=at)return {};auto p=s.substr(at,end-at);if(p.front()=='+')p.remove_prefix(1);if(p.empty())return {};auto r=std::from_chars(p.data(),p.data()+p.size(),*fields[n]);if(r.ec!=std::errc{}||r.ptr!=p.data()+p.size())return {};at=end+1;}return d.valid()?std::optional(d):std::nullopt;}
std::optional<CalendarDay>CalendarDay::advanced(int n)const noexcept{if(!valid())return {};const auto count=std::int64_t(std::chrono::sys_days(civil(*this)).time_since_epoch().count())+std::int64_t(n);const auto first=std::chrono::sys_days(civil({1900,1,1})).time_since_epoch().count(),last=std::chrono::sys_days(civil({9999,12,31})).time_since_epoch().count();if(count<first||count>last)return {};const auto at=std::chrono::sys_days(std::chrono::days(static_cast<std::chrono::days::rep>(count)));const auto value=parts(std::chrono::year_month_day(at));return value.valid()?std::optional(value):std::nullopt;}
std::optional<CalendarDay>CalendarDay::advancedMonth(int n)const noexcept{if(!valid())return {};const auto index=std::int64_t(year)*12+month-1+n;if(index<1900*12||index>9999*12+11)return {};const auto value=CalendarDay{int(index/12),int(index%12)+1,1};return value.valid()?std::optional(value):std::nullopt;}
unsigned CalendarDay::weekday()const{need(valid());return std::chrono::weekday(std::chrono::sys_days(civil(*this))).c_encoding()+1;}
unsigned CalendarDay::daysInMonth()const{need(valid());return unsigned(std::chrono::year_month_day_last{std::chrono::year(year),std::chrono::month_day_last{std::chrono::month(static_cast<unsigned>(month))}}.day());}
bool CalendarEvent::operator==(const CalendarEvent&v)const{return std::tie(id,title,details,day,created,modified,catchUpPending,catchUpDate,beforeScheduledFor,dayScheduledFor,originalFields,dayFields)==std::tie(v.id,v.title,v.details,v.day,v.created,v.modified,v.catchUpPending,v.catchUpDate,v.beforeScheduledFor,v.dayScheduledFor,v.originalFields,v.dayFields);}
void validateCalendarEvent(const CalendarEvent&e,const CalendarTextRules&r){need(bool(r.characters)&&bool(r.trimmed)&&bool(r.prefix)&&ehud::data::validUUID(e.id)&&J::validUtf8(e.title)&&J::validUtf8(e.details)&&!r.trimmed(e.title).empty()&&r.characters(e.title)<=120&&r.characters(e.details)<=2000&&e.title.find('\0')==e.title.npos&&e.details.find('\0')==e.details.npos&&e.day.valid()&&std::isfinite(e.created)&&std::isfinite(e.modified)&&(!e.catchUpDate||std::isfinite(*e.catchUpDate))&&(!e.beforeScheduledFor||CalendarDay::parse(*e.beforeScheduledFor).has_value())&&(!e.dayScheduledFor||CalendarDay::parse(*e.dayScheduledFor).has_value())&&e.originalFields.isObject()&&e.dayFields.isObject()&&e.originalNumbers.isObject());}
void validateCalendarFile(const CalendarFile&f,const CalendarTextRules&r){need(f.events.size()<=calendarMaximumEvents&&f.originalFields.isObject());std::set<std::string,std::less<>>ids;for(const auto&e:f.events){validateCalendarEvent(e,r);need(ids.insert(uuid(e.id)).second);}}
CalendarFile decodeCalendarFile(const J&j,const CalendarTextRules&r){try{need(j.isObject()&&j["version"].integer()==1&&j["events"].array().size()<=calendarMaximumEvents);CalendarFile f;f.originalFields=extras(j,{"version","events"});for(const auto&e:j["events"].array())f.events.push_back(decodeEvent(e));validateCalendarFile(f,r);return f;}catch(const CalendarError&){throw;}catch(...){throw CalendarError(CalendarErrorCode::invalidData);}}
J encodeCalendarFile(const CalendarFile&f,const CalendarTextRules&r){validateCalendarFile(f,r);auto j=f.originalFields;j["version"]=1;J::Array events;events.reserve(f.events.size());for(const auto&e:f.events)events.push_back(encodeEvent(e));j["events"]=std::move(events);return j;}
CalendarTimeZone calendarUTC(){return {"UTC",[](CalendarDay d,unsigned h,unsigned m)->std::optional<double>{if(!d.valid()||h>23||m>59)return {};return double(std::chrono::sys_days(civil(d)).time_since_epoch().count())*86400+h*3600+m*60-calendarFoundationToUnix;},[](double t){need(std::isfinite(t));const auto days=std::floor((t+calendarFoundationToUnix)/86400);need(days>=-25567&&days<=2932896);return parts(std::chrono::year_month_day(std::chrono::sys_days(std::chrono::days(static_cast<std::int64_t>(days)))));}};}
std::string CalendarReminder::signature()const{need(std::isfinite(date)&&date+calendarFoundationToUnix>=double(std::numeric_limits<std::int64_t>::min())&&date+calendarFoundationToUnix<double(std::numeric_limits<std::int64_t>::max()));return std::to_string(static_cast<std::int64_t>(date+calendarFoundationToUnix))+"|"+(previousDay?"true":"false")+"|"+title;}
std::vector<CalendarReminder>calendarReminderPlan(std::span<const CalendarEvent>events,double now,const CalendarTimeZone&zone){need(std::isfinite(now)&&zone.timestamp&&zone.day);std::vector<CalendarReminder>out;out.reserve(events.size()*2);for(const auto&e:events){const auto on=zone.timestamp(e.day,9,0);if(!on||!std::isfinite(*on)||zone.day(*on)!=e.day)continue;const auto previous=e.day.advanced(-1);if(previous)if(const auto at=zone.timestamp(*previous,9,0);at&&std::isfinite(*at)&&*at>now)out.push_back({std::string(calendarNotificationPrefix)+e.id+".before",e.id,e.title,e.day,*at,true,false,e.beforeScheduledFor==std::optional(e.day.string())});const auto date=e.catchUpDate.value_or(*on);if(date>now)out.push_back({std::string(calendarNotificationPrefix)+e.id+".day",e.id,e.title,e.day,date,false,e.catchUpDate.has_value(),e.dayScheduledFor==std::optional(e.day.string())});}std::sort(out.begin(),out.end(),[](const auto&a,const auto&b){return a.date==b.date?a.identifier<b.identifier:a.date<b.date;});return out;}
void calendarUpsert(CalendarFile&f,CalendarEvent e,CalendarDay today,const CalendarTextRules&r){validateCalendarEvent(e,r);need(today.valid());auto next=f;const auto found=std::find_if(next.events.begin(),next.events.end(),[&](const auto&v){return uuid(v.id)==uuid(e.id);});e.id=uuid(std::move(e.id));if(found!=next.events.end())*found=std::move(e);else{if(next.events.size()>=calendarMaximumEvents)throw CalendarError(CalendarErrorCode::capacity);next.events.push_back(std::move(e));}if(std::count_if(next.events.begin(),next.events.end(),[&](const auto&v){return v.day>=today;})>static_cast<std::ptrdiff_t>(calendarMaximumUpcoming))throw CalendarError(CalendarErrorCode::upcomingCapacity);f=std::move(next);}
void calendarRemove(CalendarFile&f,std::string_view id){const auto normalized=uuid(std::string(id));std::erase_if(f.events,[&](const auto&e){return uuid(e.id)==normalized;});}
bool calendarClaimCatchUps(CalendarFile&f,double now,CalendarDay today){need(std::isfinite(now)&&today.valid());bool changed{};for(auto&e:f.events)if(e.catchUpPending&&e.day<=today){e.catchUpPending=false;if(e.day==today)e.catchUpDate=now+3;changed=true;}return changed;}
bool calendarRecordScheduled(CalendarFile&f,std::span<const CalendarReminder>plan){bool changed{};for(const auto&r:plan)for(auto&e:f.events)if(e.id==r.eventID&&e.day==r.day){auto&receipt=r.previousDay?e.beforeScheduledFor:e.dayScheduledFor;auto date=r.day.string();if(receipt!=std::optional(date)){receipt=std::move(date);changed=true;}break;}return changed;}
}
