#include "modules/calendar_repository.hpp"
#include "core/data/file_io.hpp"
namespace endfield::modules {
CalendarJSONRepository::CalendarJSONRepository(std::filesystem::path d,CalendarTextRules r):directory_(std::move(d)),path_(directory_/"calendar.json"),rules_(std::move(r)){if(!directory_.is_absolute()||!rules_.characters||!rules_.trimmed||!rules_.prefix)throw CalendarError(CalendarErrorCode::invalidData);}
void CalendarJSONRepository::onOwner(){if(!owner_)owner_=std::this_thread::get_id();else if(*owner_!=std::this_thread::get_id())throw std::logic_error("Calendar repository belongs to one FIFO executor");}
bool CalendarJSONRepository::exists(){onOwner();ehud::data::detail::validateRoot(directory_);std::error_code failure;const auto status=std::filesystem::symlink_status(path_,failure);if(failure&&failure!=std::errc::no_such_file_or_directory)throw ehud::data::StoreError(ehud::data::StoreErrorCode::unavailable,"Cannot inspect Calendar file");return std::filesystem::exists(status);}
CalendarFile CalendarJSONRepository::load(){onOwner();if(loaded_)return value_;try{ehud::data::detail::validateRoot(directory_);auto bytes=ehud::data::detail::readFile(path_,calendarMaximumBytes);CalendarFile f;if(bytes)f=decodeCalendarFile(CalendarJson::parse(*bytes,calendarMaximumBytes),rules_);value_=std::move(f);persisted_=std::move(bytes);loaded_=true;return value_;}catch(const CalendarError&){throw;}catch(const ehud::data::StoreError&e){throw CalendarError(e.code()==ehud::data::StoreErrorCode::tooLarge?CalendarErrorCode::capacity:CalendarErrorCode::invalidData);}catch(...){throw CalendarError(CalendarErrorCode::invalidData);}}
void CalendarJSONRepository::save(const CalendarFile&f){onOwner();if(!loaded_)(void)load();auto next=f;std::string bytes;try{bytes=encodeCalendarFile(next,rules_).encode(calendarMaximumBytes);}catch(const CalendarError&){throw;}catch(...){throw CalendarError(CalendarErrorCode::capacity);}if(next==value_)return;std::optional<std::string>baseline(bytes);try{ehud::data::detail::replaceFile(path_,persisted_,bytes,calendarMaximumBytes);}catch(const ehud::data::StoreError&e){if(e.code()==ehud::data::StoreErrorCode::changedOnDisk)throw CalendarError(CalendarErrorCode::changedOnDisk);throw;}value_=std::move(next);persisted_=std::move(baseline);}
}
