#include "modules/calendar_state.hpp"
#include <algorithm>
#include <cmath>
#include <deque>
#include <thread>
#include <utility>
namespace endfield::modules {
namespace {void need(bool b,const char*m){if(!b)throw std::invalid_argument(m);}std::string message(std::exception_ptr p){try{if(p)std::rethrow_exception(p);}catch(const std::exception&e){return e.what();}catch(...){return CalendarError(CalendarErrorCode::invalidData).what();}return {};}
// Typed source error for display-time localization; other failures (OS/IO
// text) are shown as reported, like the Mac localizedDescription.
std::optional<CalendarErrorCode>code(std::exception_ptr p){try{if(p)std::rethrow_exception(p);}catch(const CalendarError&e){return e.code();}catch(const std::exception&){return {};}catch(...){return CalendarErrorCode::invalidData;}return {};}}
struct CalendarState::Impl:std::enable_shared_from_this<Impl> {
    std::shared_ptr<CalendarRepository>repository;CalendarExecutor executor;CalendarStateOptions options;
    std::thread::id owner{std::this_thread::get_id()};CalendarFile value;
    bool alive{true},active{},loaded{},job{},checking{},checkPending{},schedule{},needsSchedule{},requestPermissionPending{};CalendarPermission permission{CalendarPermission::unknown};
    std::optional<std::string>error;std::optional<CalendarErrorCode>errorCode;std::exception_ptr persistenceError;std::uint64_t revision{};
    struct Mutation {std::function<void(CalendarFile&)>apply;std::function<void(bool)>complete;};std::deque<std::shared_ptr<Mutation>>pending;
    Impl(std::shared_ptr<CalendarRepository>r,CalendarExecutor e,CalendarStateOptions o):repository(std::move(r)),executor(std::move(e)),options(std::move(o)){need(repository&&executor.submit&&options.text.characters&&options.text.trimmed&&options.text.prefix&&options.now&&options.zone&&options.newID,"Calendar requires borrowed file/clock/Unicode/identity callbacks");need(options.scheduling.authorization&&options.scheduling.reconcile&&options.scheduling.cancelObsolete,"Calendar requires an explicit notification capability adapter");}
    void onOwner()const{need(owner==std::this_thread::get_id(),"Calendar state belongs to its creating thread");}
    void notify(){++revision;if(alive&&options.changed)options.changed();}
    void fail(std::exception_ptr p){error=message(p);errorCode=code(p);}
    double now()const{const auto t=options.now();need(std::isfinite(t),"Calendar requires finite owner time");return t;}
    CalendarDay today()const{const auto z=options.zone();need(z.day&&z.timestamp,"Calendar requires civil time conversion");const auto d=z.day(now());need(d.valid(),"Calendar clock is outside supported civil dates");return d;}
    bool busy()const{return job||checking||!pending.empty();}
    void mutate(std::function<void(CalendarFile&)>apply,std::function<void(bool)>complete={}){need(pending.size()<8,"Calendar mutation queue exceeds its source control bound");pending.push_back(std::make_shared<Mutation>(Mutation{std::move(apply),std::move(complete)}));error.reset();errorCode.reset();notify();if(alive)pump();}
    void pump(){if(!alive||job||checking||pending.empty())return;auto operation=pending.front();auto result=std::make_shared<std::optional<CalendarFile>>();auto repo=repository;std::weak_ptr<Impl>weak=shared_from_this();
        const bool accepted=executor.submit([repo,operation,result]{auto f=repo->load();operation->apply(f);repo->save(f);*result=std::move(f);},[weak,operation,result](std::exception_ptr failure){auto i=weak.lock();if(!i||!i->alive)return;i->onOwner();i->job=false;need(!i->pending.empty()&&i->pending.front()==operation,"Calendar FIFO completion order changed");i->pending.pop_front();if(failure){i->persistenceError=failure;i->fail(failure);}else{i->persistenceError={};i->value=std::move(**result);}if(operation->complete)operation->complete(!failure);if(!i->alive)return;i->notify();if(i->alive)i->pump();});if(accepted)job=true;
    }
    void checkExisting(){if(!alive||loaded||job||checking||!pending.empty())return;auto found=std::make_shared<bool>();auto repo=repository;auto weak=weak_from_this();const bool accepted=executor.submit([repo,found]{*found=repo->exists();},[weak,found](std::exception_ptr failure){auto i=weak.lock();if(!i||!i->alive)return;i->checking=false;if(failure){i->persistenceError=failure;i->fail(failure);i->notify();}else if(*found||i->active)i->load();else i->notify();});checking=accepted;checkPending=!accepted;}
    void load(){if(loaded||busy())return;checkPending=false;auto weak=weak_from_this();mutate([](auto&){},[weak](bool success){auto i=weak.lock();if(!i||!i->alive||!success)return;i->loaded=true;if(!i->value.events.empty())i->reschedule(false);});}
    void finishSchedule(){if(!alive)return;schedule=false;if(needsSchedule){const auto request=requestPermissionPending;needsSchedule=false;requestPermissionPending=false;reschedule(request);}else notify();}
    void reschedule(bool request){if(!alive||!loaded)return;if(schedule){needsSchedule=true;requestPermissionPending|=request;return;}schedule=true;auto weak=weak_from_this();try{options.scheduling.authorization(request&&!value.events.empty(),[weak](CalendarPermission p){auto i=weak.lock();if(!i||!i->alive)return;i->onOwner();i->permission=p;i->notify();if(!i->alive)return;
            if(p!=CalendarPermission::authorized){std::vector<std::string>keep;for(const auto&r:calendarReminderPlan(i->value.events,i->now(),i->options.zone()))keep.push_back(r.identifier);try{i->options.scheduling.cancelObsolete(std::move(keep),[weak]{if(auto i=weak.lock();i&&i->alive){i->onOwner();i->finishSchedule();}});}catch(...){i->fail(std::current_exception());i->finishSchedule();}return;}
            const auto t=i->now();const auto z=i->options.zone();const auto today=z.day(t);i->mutate([t,today](auto&f){calendarClaimCatchUps(f,t,today);},[weak,z](bool ok){auto i=weak.lock();if(!i||!i->alive)return;if(!ok){i->finishSchedule();return;}auto plan=calendarReminderPlan(i->value.events,i->now(),z);auto receipts=plan;try{i->options.scheduling.reconcile(std::move(plan),z,[weak,receipts=std::move(receipts)](std::exception_ptr failure){auto i=weak.lock();if(!i||!i->alive)return;i->onOwner();if(failure){i->fail(failure);i->finishSchedule();return;}i->mutate([receipts](auto&f){calendarRecordScheduled(f,receipts);},[weak](bool){if(auto i=weak.lock();i&&i->alive)i->finishSchedule();});});}catch(...){i->fail(std::current_exception());i->finishSchedule();}});
        });}catch(...){fail(std::current_exception());finishSchedule();}}
};
CalendarState::CalendarState(std::shared_ptr<CalendarRepository>r,CalendarExecutor e,CalendarStateOptions o):impl_(std::make_shared<Impl>(std::move(r),std::move(e),std::move(o))){}
CalendarState::~CalendarState(){impl_->alive=false;impl_->pending.clear();impl_->options.changed={};impl_->options.event={};}
void CalendarState::startIfExisting(){auto i=impl_;i->onOwner();if(i->loaded||i->busy())return;i->checkExisting();}
void CalendarState::setActive(bool v){auto i=impl_;i->onOwner();i->active=v;if(v){if(!i->loaded)i->load();else{i->reschedule(false);if(i->alive)i->notify();}}}
void CalendarState::refreshReminders(){auto i=impl_;i->onOwner();if(i->loaded)i->reschedule(true);else i->load();}
void CalendarState::refreshForSystemChange(){auto i=impl_;i->onOwner();if(!i->loaded)return;i->reschedule(false);if(i->alive)i->notify();}
bool CalendarState::save(std::string title,std::string details,CalendarDay day,std::optional<std::string>id,std::function<void(bool)>completion){auto i=impl_;i->onOwner();if(!i->loaded||i->busy())return false;auto z=i->options.zone();const auto nine=z.timestamp(day,9,0);if(!day.valid()||!nine||z.day(*nine)!=day){report(CalendarErrorCode::invalidDate);return false;}title=i->options.text.prefix(i->options.text.trimmed(title),120);if(title.empty())return false;const auto timestamp=i->now();const auto today=z.day(timestamp);const CalendarEvent*old{};if(id){for(auto&c:*id)if(c>='a'&&c<='f')c=char(c-'a'+'A');for(const auto&e:i->value.events)if(e.id==*id){old=&e;break;}if(!old){report(CalendarErrorCode::missing);return false;}}
    CalendarEvent e=old?*old:CalendarEvent{};if(!old){e.id=i->options.newID();e.created=timestamp;}e.title=std::move(title);e.details=i->options.text.prefix(details,2000);e.modified=timestamp;if(!old||e.day!=day){e.catchUpPending=day==today&&timestamp>=*nine;e.catchUpDate.reset();}e.day=day;const auto rules=i->options.text;std::weak_ptr<Impl>weak=i;const bool creating=!old;i->mutate([e=std::move(e),today,rules](auto&f){calendarUpsert(f,e,today,rules);},[weak,creating,completion=std::move(completion)](bool ok){auto i=weak.lock();if(!i||!i->alive)return;if(ok){if(i->options.event)i->options.event(creating?"created":"edited");if(!i->alive)return;i->reschedule(true);}if(i->alive&&completion)completion(ok);});return true;}
bool CalendarState::remove(std::string id,std::function<void(bool)>completion){auto i=impl_;i->onOwner();if(!i->loaded||i->busy())return false;std::weak_ptr<Impl>weak=i;i->mutate([id=std::move(id)](auto&f){calendarRemove(f,id);},[weak,completion=std::move(completion)](bool ok){auto i=weak.lock();if(!i||!i->alive)return;if(ok){if(i->options.event)i->options.event("deleted");if(!i->alive)return;i->reschedule(false);}if(i->alive&&completion)completion(ok);});return true;}
void CalendarState::report(std::string error){auto i=impl_;i->onOwner();i->error=std::move(error);i->errorCode.reset();i->notify();}
void CalendarState::report(CalendarErrorCode code){auto i=impl_;i->onOwner();i->error=CalendarError(code).what();i->errorCode=code;i->notify();}
void CalendarState::queueCapacityAvailable(){auto i=impl_;i->onOwner();if(i->checkPending)i->checkExisting();if(i->alive)i->pump();}
bool CalendarState::active()const noexcept{return impl_->active;}bool CalendarState::loaded()const noexcept{return impl_->loaded;}bool CalendarState::busy()const noexcept{return impl_->busy();}bool CalendarState::scheduling()const noexcept{return impl_->schedule;}bool CalendarState::hasPendingWork()const noexcept{return impl_->busy()||impl_->checkPending||impl_->schedule||impl_->needsSchedule;}bool CalendarState::hasPersistenceFailure()const noexcept{return bool(impl_->persistenceError);}
CalendarDay CalendarState::today()const{impl_->onOwner();return impl_->today();}CalendarTimeZone CalendarState::zone()const{impl_->onOwner();return impl_->options.zone();}CalendarPermission CalendarState::permission()const noexcept{return impl_->permission;}const std::optional<std::string>&CalendarState::error()const noexcept{return impl_->error;}std::optional<CalendarErrorCode>CalendarState::errorCode()const noexcept{return impl_->errorCode;}std::span<const CalendarEvent>CalendarState::events()const noexcept{return impl_->value.events;}std::uint64_t CalendarState::revision()const noexcept{return impl_->revision;}
}
