#include "modules/media_assembly_artwork.hpp"
#include <algorithm>
#include <cmath>
#include <iomanip>
#include <locale>
#include <numbers>
#include <sstream>

namespace endfield::modules {namespace {
using J=ehud::data::Json;using R=core::Rect;using P=core::Point;using C=MediaAssemblyColor;using G=MediaAssemblyPaintGroup;using Role=MediaAssemblyPaintRole;using M=core::Matrix4;
void need(bool v,const char*s){if(!v)throw std::invalid_argument(s);}
C gray(double v,double a=1){return {v,v,v,a};}C alpha(C v,double a){v[3]=a;return v;}
J color(C v){for(double x:v)need(std::isfinite(x)&&x>=0&&x<=1,"Invalid Media Assembly source color");return J::Object{{"sRGB",J::Array{v[0],v[1],v[2],v[3]}}};}
J box(R v){return J::Array{v.x,v.y,v.width,v.height};}
J node(R r,const char*kind="layer"){return J::Object{{"kind",kind},{"bounds",box({0,0,r.width,r.height})},{"position",J::Array{r.x,r.y}},{"anchorPoint",J::Array{0,0}}};}
J plate(R r,C c,double radius=0,std::optional<C>border={},double width=0){auto j=node(r);j["backgroundColor"]=color(c);j["cornerRadius"]=radius;j["borderWidth"]=width;if(border)j["borderColor"]=color(*border);return j;}
J text(std::string value,R r,double size,C c,bool center=false,bool wrapped=false){auto j=node(r,"text");j["text"]=J::Object{{"string",std::move(value)},{"fontSize",size},{"font",J::Object{{"familyName",".AppleSystemUIFont"},{"postScriptName",".AppleSystemUIFontMedium"},{"pointSize",size},{"symbolicTraits",0}}},{"foregroundColor",color(c)},{"alignment",center?"center":"natural"},{"wrapped",wrapped},{"truncation","end"}};return j;}
J cmd(const char*op,std::initializer_list<P>points={}){J::Array out;for(auto p:points)out.push_back(J::Array{p.x,p.y});return J::Object{{"op",op},{"points",std::move(out)}};}
void rectangle(J::Array&path,R r){path.push_back(cmd("move",{{r.x,r.y}}));path.push_back(cmd("line",{{r.x+r.width,r.y}}));path.push_back(cmd("line",{{r.x+r.width,r.y+r.height}}));path.push_back(cmd("line",{{r.x,r.y+r.height}}));path.push_back(cmd("close"));}
J cut(R r){const auto k=std::min(4.,std::min(r.width,r.height)/3);return J::Array{cmd("move",{{r.x+k,r.y}}),cmd("line",{{r.x+r.width,r.y}}),cmd("line",{{r.x+r.width,r.y+r.height-k}}),cmd("line",{{r.x+r.width-k,r.y+r.height}}),cmd("line",{{r.x,r.y+r.height}}),cmd("line",{{r.x,r.y+k}}),cmd("close")};}
J shape(R r,J path,std::optional<C>fill={},std::optional<C>stroke={},double width=1,bool evenOdd=false){auto j=node(r,"shape");j["shape"]=J::Object{{"path",std::move(path)},{"fillColor",fill?color(*fill):J{}},{"strokeColor",stroke?color(*stroke):J{}},{"lineWidth",width},{"fillRule",evenOdd?"even-odd":"non-zero"},{"lineCap","butt"},{"lineJoin","miter"}};return j;}
J image(R r,const MediaAssemblyImageReference&asset){need(!asset.path.empty()&&asset.sha256.size()==64,"Missing original Media Assembly image");auto j=node(r);j["contents"]=J::Object{{"asset",asset.path},{"sha256",asset.sha256}};j["contentsGravity"]="resizeAspect";return j;}
std::string fixed(double x,unsigned digits){std::ostringstream s;s.imbue(std::locale::classic());s<<std::fixed<<std::setprecision(int(digits))<<x;return s.str();}
}
MediaAssemblyArtwork prepareMediaAssemblyArtwork(const MediaAssemblyPresentation&p,const MediaAssemblyView&v,const MediaAssemblyAppearance&a,const MediaAssemblyArtworkAssets&assets,std::string_view error,double progress){
 need(std::isfinite(progress)&&progress>=0&&progress<=1&&std::isfinite(v.currentTime)&&v.currentTime>=0,"Invalid Media Assembly artwork state");if(v.adjustments)need(v.adjustments->valid(),"Invalid Media Assembly adjustments");if(v.document)need(v.adjustments&&std::isfinite(v.document->duration)&&v.document->duration>=0&&std::isfinite(v.document->pixels.x)&&std::isfinite(v.document->pixels.y)&&v.document->pixels.x>0&&v.document->pixels.y>0,"Invalid Media Assembly document");
 (void)color(a.accent);const auto ink=gray(a.dark?.94:.1),white=gray(1);const auto preview=MediaAssemblyPresentation::previewRect;MediaAssemblyArtwork out;out.surfaces.reserve(160);out.actions=p.actions(v,a.language);out.imageRect=p.imageRect(v);out.drawerVisible=p.drawer().has_value();
 const auto L=[&](auto en,auto zh){return core::localized(en,zh,a.language);};
 auto add=[&](std::string id,J content,G group,Role role=Role::artwork,std::initializer_list<MediaAssemblyClip>clips={},float opacity=1,std::string action={},bool enabled=false,bool framed=false){const auto&position=content["position"].array();const auto local=M::translation(position[0].number(),position[1].number());content["position"]=J::Array{0,0};content["id"]=id;MediaAssemblySurface s{std::move(id),std::move(action),std::move(content),local,{},clips.size(),group,role,opacity,enabled,framed};need(clips.size()<=s.clips.size(),"Too many source Media Assembly clips");std::copy(clips.begin(),clips.end(),s.clips.begin());out.surfaces.push_back(std::move(s));};
 auto feedback=[&](const std::string&id,R r,G group,bool enabled,bool framed,std::initializer_list<MediaAssemblyClip>clips={}){add(id+"/tint",shape(r,cut({0,0,r.width,r.height}),alpha(a.accent,.3)),group,Role::tint,clips,0,id,enabled,framed);const auto d=framed?2.:0.;add(id+"/rim",shape(r,cut({-d,-d,r.width+2*d,r.height+2*d}),{},a.accent,.9),group,Role::rim,clips,enabled&&framed?.28f:0.f,id,enabled,framed);};
 auto action=[&](const MediaAssemblyAction&b,G group){if(!b.draw)return;const auto id="media.action."+b.id;add(id+"/plate",plate(b.rect,b.selected?a.accent:gray(.12,.95),2),group);feedback(id,b.rect,group,b.enabled,true);
  // Original action() measures the source 10pt semibold ascender/descender,
  // then label() paints with source medium. Detached source oracle pins 12pt.
  constexpr double h=12;add(id+"/title",text(b.title,{b.rect.x+3,b.rect.y+b.rect.height/2-h/2,b.rect.width-6,h},10,alpha(b.selected?gray(0):white,b.enabled?1:.35),true),group);};
 add("media.stage",plate(preview,gray(a.dark?.03:.92,.6),4),G::stage);
 if(v.adjustments)for(const auto&s:v.adjustments->stickers){const auto index=std::size_t(s.kind);need(index<assets.stickers.size(),"Unknown source sticker");const auto source=mediaAssemblyStickerPixelSize(s.kind);auto base=out.imageRect;if(p.tool()==MediaAssemblyTool::crop){const auto c=p.cropRect(v);base={base.x+c.x*base.width,base.y+c.y*base.height,c.width*base.width,c.height*base.height};}const auto r=MediaAssemblyViewport::stickerRect(s,base);add("media.sticker."+s.id,image({0,0,source.x,source.y},assets.stickers[index]),G::stickers,Role::sticker,{{preview,4},{out.imageRect,0}});out.surfaces.back().local=M::translation(r.x+r.width/2,r.y+r.height/2)*M::rotation(0,0,s.rotation*std::numbers::pi/180)*M::scale(r.width/source.x,r.height/source.y)*M::translation(-source.x/2,-source.y/2);}
 if(p.tool()==MediaAssemblyTool::crop){const auto c=p.cropRect(v),i=out.imageRect;const R r{i.x+c.x*i.width-preview.x,i.y+c.y*i.height-preview.y,c.width*i.width,c.height*i.height};J::Array shade;rectangle(shade,{0,0,preview.width,preview.height});rectangle(shade,r);add("media.crop.shade",shape(preview,std::move(shade),gray(0,.48),{},1,true),G::overlay,Role::artwork,{{preview,0}});J::Array border;rectangle(border,r);for(double f:{1./3,2./3}){border.push_back(cmd("move",{{r.x+r.width*f,r.y}}));border.push_back(cmd("line",{{r.x+r.width*f,r.y+r.height}}));border.push_back(cmd("move",{{r.x,r.y+r.height*f}}));border.push_back(cmd("line",{{r.x+r.width,r.y+r.height*f}}));}add("media.crop.border",shape(preview,std::move(border),{},a.accent),G::overlay,Role::artwork,{{preview,0}});const auto handles=p.cropHandles(v);for(std::size_t n=0;n<handles.size();++n)add("media.crop.handle."+std::to_string(n),plate({handles[n].x-4,handles[n].y-4,8,8},white,0,gray(0),1),G::overlay,Role::artwork,{{preview,0}});}
 add("media.heading",text("// "+L("Media Assembly","影像加工"),{12,9,328,22},14,ink),G::overlay);add("media.empty",text(v.busy?L("Loading…","正在载入…"):!v.document?L("Open an image or video","打开图片或视频"):"",{35,174,370,42},14,ink,true,true),G::overlay);
 const auto baseCount=std::size_t(v.document&&v.document->video?10:9);need(out.actions.size()>=baseCount,"Missing source Media Assembly controls");for(std::size_t n=0;n<baseCount;++n)action(out.actions[n],G::overlay);
 if(p.drawer()){const auto b=p.drawerBounds();add("media.drawer.back",plate({b.x-3,b.y-3,b.width+6,b.height+6},gray(.08,.92),3),G::drawer);
  if(p.tool()){
   action(out.actions[baseCount],G::drawer);constexpr std::array en{"Crop","Adjust","Curves","Levels","Trim"},zh{"裁剪","调整","曲线","色阶","剪辑"};const auto tool=std::size_t(*p.tool());add("media.drawer.title",text(L(en[tool],zh[tool]),{59,95,121,18},11,white),G::drawer);
   if(p.tool()==MediaAssemblyTool::crop)action(out.actions[baseCount+1],G::drawer);
   else if(p.tool()==MediaAssemblyTool::trim){const auto&r=MediaAssemblyPresentation::trimRect;const auto&adjust=*v.adjustments;const auto duration=std::max(.05,v.document?v.document->duration:0),start=r.x+r.width*adjust.trimStart/duration,end=r.x+r.width*adjust.trimEnd.value_or(duration)/duration;
    add("media.trim.rail",plate({r.x,r.y+r.height/2-2,r.width,4},gray(1,.25)),G::drawer);if(end>start)add("media.trim.fill",plate({start,r.y+r.height/2-2,end-start,4},a.accent),G::drawer);add("media.trim.start",plate({start-4,r.y+r.height/2-9,8,18},white),G::drawer);add("media.trim.end",plate({end-4,r.y+r.height/2-9,8,18},white),G::drawer);add("media.trim.text",text(fixed(adjust.trimStart,2)+"s  —  "+fixed(adjust.trimEnd.value_or(duration),2)+"s",{27,136,157,20},10,white,true),G::drawer);action(out.actions[baseCount+1],G::drawer);
   }else{const auto ps=p.parameters(v);const auto clip=MediaAssemblyPresentation::inlineRect;for(std::size_t n=0;n<ps.count;++n){const auto&item=ps.values[n];const auto id="media.parameter."+std::string(item.id);const auto y=clip.y+double(n)*52-p.drawerOffset(),width=151*(item.value-item.low)/(item.high-item.low);const auto value=item.step>=1?fixed(std::round(item.value),0):fixed(item.value,2);add(id+"/text",text(L(item.english,item.chinese)+"  "+value,{clip.x+5,y+2,151,19},10,white),G::drawer,Role::inlineItem,{{clip,0}});add(id+"/rail",plate({clip.x+5,y+32,151,2},gray(1,.25)),G::drawer,Role::inlineItem,{{clip,0}});if(width>0)add(id+"/fill",plate({clip.x+5,y+32,width,2},a.accent),G::drawer,Role::inlineItem,{{clip,0}});add(id+"/knob",plate({clip.x+5+width-3,y+27,6,12},white),G::drawer,Role::inlineItem,{{clip,0}});}
    const auto maximum=p.maximumDrawerOffset(v);if(maximum>0){const auto h=std::max(20.,clip.height*clip.height/(clip.height+maximum));add("media.drawer.thumb",plate({MediaAssemblyPresentation::presetRect.x+MediaAssemblyPresentation::presetRect.width-2,clip.y+(clip.height-h)*p.drawerOffset()/maximum,2,h},gray(1,.4),1),G::drawer);}
   }
  }else if(p.drawer()==MediaAssemblyDrawer::tools){for(std::size_t n=baseCount;n<out.actions.size();++n)action(out.actions[n],G::drawer);}
  else{const bool filters=p.drawer()==MediaAssemblyDrawer::filters;const auto count=filters?mediaAssemblyFilters().size():mediaAssemblyStickers().size();const auto clip=MediaAssemblyPresentation::presetRect;
   for(std::size_t n=0;n<count;++n){const R r{clip.x+double(n%3)*57+3,clip.y+double(n/3)*57+3-p.drawerOffset(),49,49};if(r.y+r.height<=clip.y||r.y>=clip.y+clip.height)continue;const auto key=std::string(filters?"filter:":"sticker:")+std::string((filters?mediaAssemblyFilters():mediaAssemblyStickers())[n].id);const auto id="media.action."+key;const bool selected=filters&&v.adjustments&&std::size_t(v.adjustments->filter)==n;add(id+"/plate",plate(r,gray(1,selected?.18:.07),3,a.accent,selected?1.5:0),G::drawer,Role::artwork,{{clip,0}});
    if(filters&&n==0)add(id+"/empty",text("∅",{r.x+5,r.y+9,r.width-10,r.height-18},22,white,true),G::drawer,Role::artwork,{{clip,0}});else add(id+"/image",image({r.x+5,r.y+5,r.width-10,r.height-10},filters?assets.filters[n]:assets.stickers[n]),G::drawer,Role::artwork,{{clip,0}});
    // Original feedback remains enabled on a full sticker sheet even when
    // adding item17 is disabled by the separate action capacity check.
    feedback(id,r,G::drawer,v.editable(),false,{{clip,0}});
   }const auto maximum=p.maximumDrawerOffset(v);if(maximum>0){const auto h=std::max(24.,clip.height*clip.height/(clip.height+maximum));add("media.drawer.thumb",plate({clip.x+clip.width-1,clip.y+(clip.height-h)*p.drawerOffset()/maximum,2,h},gray(1,.4),1),G::drawer);}
  }
 }
 if(v.adjustments&&!p.drawer())for(const auto&s:v.adjustments->stickers)if(s.id==p.selectedSticker()){const auto r=MediaAssemblyViewport::stickerRect(s,out.imageRect);const P center{r.x+r.width/2,r.y+r.height/2};J::Array path;const std::array<P,4>points{{{r.x,r.y},{r.x+r.width,r.y},{r.x+r.width,r.y+r.height},{r.x,r.y+r.height}}};for(std::size_t n=0;n<points.size();++n){const auto q=MediaAssemblyViewport::unrotate(points[n],center,-s.rotation);path.push_back(cmd(n?"line":"move",{{q.x-preview.x,q.y-preview.y}}));}path.push_back(cmd("close"));add("media.selection.border",shape(preview,std::move(path),{},a.accent),G::selection,Role::artwork,{{preview,0}});const auto handles=p.stickerHandles(s,v);for(std::size_t n=0;n<handles.size();++n){const auto h=handles[n];if(n<2){auto j=text(n?"×":"↻",{h.x-8,h.y-8,16,16},13,white,true);j["backgroundColor"]=color(gray(0,.85));j["cornerRadius"]=8;add("media.selection.handle."+std::to_string(n),std::move(j),G::selection,Role::artwork,{{preview,0}});}else add("media.selection.handle."+std::to_string(n),plate({h.x-3,h.y-3,6,6},white),G::selection,Role::artwork,{{preview,0}});}}
 const bool video=v.document&&v.document->video&&p.tool()!=MediaAssemblyTool::trim;const double duration=v.document?v.document->duration:0,time=p.seekFraction()?*p.seekFraction()*duration:v.currentTime;
 if(video){const auto seek=MediaAssemblyPresentation::seekRect;const auto width=seek.width*std::clamp(time/std::max(.01,duration),0.,1.);add("media.seek.rail",plate({seek.x,seek.y+seek.height/2,seek.width,2},gray(.5,.6)),G::transport);if(width>0)add("media.seek.fill",plate({seek.x,seek.y+seek.height/2,width,2},a.accent),G::transport);}
 const auto seconds=std::floor(std::max(0.,time)),minutes=std::floor(seconds/60),remaining=seconds-minutes*60;const auto elapsed=video?fixed(minutes,0)+":"+(remaining<10?"0":"")+fixed(remaining,0):"";
 add("media.elapsed",text(elapsed,{364,337,55,15},9,white),G::transport);add("media.zoom",text(fixed(p.viewport().zoom(),1)+"×",{137,378,68,16},11,ink,true),G::transport);const auto status=!error.empty()?std::string(error):v.exporting?L("Exporting","正在导出")+" "+fixed(std::floor(progress*100),0)+"%":"";need(error.empty()||a.systemOrange.has_value(),"Media Assembly error requires original systemOrange");add("media.status",text(status,{18,405,410,31},9,error.empty()?ink:*a.systemOrange,false,true),G::transport);
 return out;
}
}
