#include "modules/reader_text.hpp"
#include <algorithm>
#include <cmath>
namespace endfield::modules {
namespace {void need(bool b){if(!b)throw ReaderError(ReaderErrorCode::invalidBook);}bool high(char16_t c){return c>=0xd800&&c<=0xdbff;}bool low(char16_t c){return c>=0xdc00&&c<=0xdfff;}}
bool readerValidUTF16(std::u16string_view s)noexcept{for(std::size_t i=0;i<s.size();++i){if(high(s[i])){if(++i==s.size()||!low(s[i]))return false;}else if(low(s[i]))return false;}return true;}
std::u16string readerUTF8(std::string_view s){need(ReaderJson::validUtf8(s));std::u16string out;out.reserve(s.size());for(std::size_t i=0;i<s.size();){auto c=static_cast<unsigned char>(s[i++]);std::uint32_t point=c;if(c>=0xc0){unsigned count=c<0xe0?1:c<0xf0?2:3;point=c&((1u<<(6-count))-1);while(count--){point=(point<<6)|(static_cast<unsigned char>(s[i++])&63);}}if(point<=0xffff)out+=char16_t(point);else{point-=0x10000;out+=char16_t(0xd800+(point>>10));out+=char16_t(0xdc00+(point&1023));}}return out;}
std::string readerUTF8(std::u16string_view s){need(readerValidUTF16(s));std::string out;out.reserve(s.size());for(std::size_t i=0;i<s.size();++i){std::uint32_t c=s[i];if(high(s[i])){c=0x10000+((c-0xd800)<<10)+(s[++i]-0xdc00);}if(c<0x80)out+=char(c);else if(c<0x800){out+=char(0xc0|(c>>6));out+=char(0x80|(c&63));}else if(c<0x10000){out+=char(0xe0|(c>>12));out+=char(0x80|((c>>6)&63));out+=char(0x80|(c&63));}else{out+=char(0xf0|(c>>18));out+=char(0x80|((c>>12)&63));out+=char(0x80|((c>>6)&63));out+=char(0x80|(c&63));}}return out;}
std::u16string readerUTF16(std::span<const std::uint8_t>b){need(b.size()>=2&&b.size()%2==0);const bool le=b[0]==0xff&&b[1]==0xfe;need(le||(b[0]==0xfe&&b[1]==0xff));std::u16string out;out.reserve(b.size()/2-1);for(std::size_t i=2;i<b.size();i+=2)out+=char16_t(le?std::uint16_t(b[i])|(std::uint16_t(b[i+1])<<8):std::uint16_t(b[i+1])|(std::uint16_t(b[i])<<8));need(readerValidUTF16(out));return out;}
std::u16string_view readerChunk(std::u16string_view s,std::size_t from){need(from<s.size());auto count=std::min<std::size_t>(16384,s.size()-from);if(from+count<s.size()&&high(s[from+count-1]))--count;return s.substr(from,count);}
ReaderLocation readerNormalized(ReaderLocation location,std::size_t count,const ReaderBlocks&blocks){need(count>0&&count<100000&&bool(blocks));location.section=std::clamp<std::int64_t>(location.section,0,static_cast<std::int64_t>(count-1));const auto values=blocks(static_cast<std::size_t>(location.section));need(values&&!values->empty());location.block=std::clamp<std::int64_t>(location.block,0,static_cast<std::int64_t>(values->size()-1));const auto&value=(*values)[static_cast<std::size_t>(location.block)];if(value.kind==ReaderBlock::Kind::text){need(!value.text.empty());location.character=std::clamp<std::int64_t>(location.character,0,static_cast<std::int64_t>(value.text.size()-1));if(location.character>0&&low(value.text[static_cast<std::size_t>(location.character)]))--location.character;}else location.character=0;location.originalFields=ReaderJson::Object{};return location;}
ReaderLocation readerLocationAt(double progress,std::size_t count,const ReaderBlocks&blocks){need(std::isfinite(progress)&&count>0&&count<100000);const auto amount=std::clamp(progress,0.,.999999);ReaderLocation location;location.section=static_cast<std::int64_t>(amount*static_cast<double>(count));const auto values=blocks(static_cast<std::size_t>(location.section));need(values&&!values->empty());const auto fraction=amount*static_cast<double>(count)-static_cast<double>(location.section);location.block=std::min<std::int64_t>(static_cast<std::int64_t>(values->size()-1),static_cast<std::int64_t>(fraction*static_cast<double>(values->size())));const auto&value=(*values)[static_cast<std::size_t>(location.block)];if(value.kind==ReaderBlock::Kind::text){location.character=static_cast<std::int64_t>((fraction*static_cast<double>(values->size())-static_cast<double>(location.block))*static_cast<double>(value.text.size()));if(location.character>0){const auto begin=static_cast<std::size_t>(std::max<std::int64_t>(0,location.character-200));const auto end=static_cast<std::size_t>(location.character);const auto found=value.text.substr(begin,end-begin).rfind(u'\n');if(found!=std::u16string::npos)location.character=static_cast<std::int64_t>(begin+found+1);}}return readerNormalized(location,count,blocks);}
std::optional<ReaderLocation>readerAdvance(ReaderLocation l,std::size_t blocks,std::size_t count){if(l.block+1<static_cast<std::int64_t>(blocks))return ReaderLocation{l.section,l.block+1,0,{ReaderJson::Object{}}};if(l.section+1<static_cast<std::int64_t>(count))return ReaderLocation{l.section+1,0,0,{ReaderJson::Object{}}};return {};}
std::optional<ReaderLocation>readerPrevious(ReaderLocation l,std::size_t count,const ReaderBlocks&blocks,double height,const std::function<double(std::u16string_view)>&measure){need(count>0&&bool(measure)&&std::isfinite(height));auto end=l.character;if(end==0){if(l.block>0)--l.block;else if(l.section>0){--l.section;l.block=static_cast<std::int64_t>(blocks(static_cast<std::size_t>(l.section))->size()-1);}else return {};const auto values=blocks(static_cast<std::size_t>(l.section));const auto&block=(*values)[static_cast<std::size_t>(l.block)];if(block.kind==ReaderBlock::Kind::text)end=static_cast<std::int64_t>(block.text.size());}const auto values=blocks(static_cast<std::size_t>(l.section));const auto&block=(*values)[static_cast<std::size_t>(l.block)];l.character=0;if(block.kind!=ReaderBlock::Kind::text||end<=0)return l;std::int64_t lo=std::max<std::int64_t>(0,end-16384),hi=end-1;while(lo<hi){const auto mid=(lo+hi)/2;const auto h=measure(std::u16string_view(block.text).substr(static_cast<std::size_t>(mid),static_cast<std::size_t>(end-mid)));need(std::isfinite(h)&&h>=0);if(h<=std::max(1.,height))hi=mid;else lo=mid+1;}if(lo>0&&low(block.text[static_cast<std::size_t>(lo)]))--lo;l.character=lo;return l;}
} // namespace endfield::modules
