#include "modules/reader_presentation.hpp"
#include "modules/notes_controls.hpp"
#include <algorithm>
#include <cmath>
namespace endfield::modules {
namespace {
using J=ReaderJson;using R=core::Rect;using P=core::Point;
void need(bool b){if(!b)throw std::invalid_argument("Invalid Reader presentation");}
bool contains(R r,P p){return std::isfinite(p.x)&&std::isfinite(p.y)&&p.x>=r.x&&p.y>=r.y&&p.x<r.x+r.width&&p.y<r.y+r.height;}
J box(R r){return J::Array{r.x,r.y,r.width,r.height};}J color(ReaderColor c){return J::Object{{"sRGB",J::Array{c[0],c[1],c[2],c[3]}}};}ReaderColor white(double w,double a=1){return {w,w,w,a};}ReaderColor alpha(ReaderColor c,double a){c[3]=a;return c;}
void validColor(ReaderColor c){for(const auto n:c)need(std::isfinite(n)&&n>=0&&n<=1);}
J layer(std::string id,R r){return J::Object{{"id",std::move(id)},{"kind","layer"},{"bounds",box({0,0,r.width,r.height})},{"position",J::Array{r.x,r.y}},{"anchorPoint",J::Array{0,0}},{"opacity",1},{"children",J::Array{}}};}
J fill(std::string id,R r,ReaderColor c){auto j=layer(std::move(id),r);j["backgroundColor"]=color(c);return j;}
J text(std::string id,std::string value,R r,double size,ReaderColor c,std::string align="natural",bool wrapped=false){auto j=layer(std::move(id),r);j["kind"]="text";j["text"]=J::Object{{"string",std::move(value)},{"fontSize",size},{"font",J::Object{{"familyName",".AppleSystemUIFont"},{"postScriptName",".AppleSystemUIFontDemi"},{"pointSize",size}}},{"foregroundColor",color(c)},{"alignment",std::move(align)},{"wrapped",wrapped},{"truncation","end"},{"runs",J::Array{}}};return j;}
J command(const char*op,std::initializer_list<P>p){J::Array a;for(auto q:p)a.emplace_back(J::Array{q.x,q.y});return J::Object{{"op",op},{"points",std::move(a)}};}
J cut(R r){const auto c=std::min(4.,std::min(r.width,r.height)/3);return J::Array{command("move",{{r.x+c,r.y}}),command("line",{{r.x+r.width,r.y}}),command("line",{{r.x+r.width,r.y+r.height-c}}),command("line",{{r.x+r.width-c,r.y+r.height}}),command("line",{{r.x,r.y+r.height}}),command("line",{{r.x,r.y+c}}),command("close",{})};}
J shape(std::string id,R r,J path,ReaderColor c,bool rim,float opacity){auto j=layer(std::move(id),r);j["kind"]="shape";j["opacity"]=opacity;j["shape"]=J::Object{{"path",std::move(path)},{"fillColor",rim?J{}:color(c)},{"strokeColor",rim?color(c):J{}},{"lineWidth",rim?.9:1},{"lineCap","butt"},{"lineJoin","miter"},{"fillRule","non-zero"}};return j;}
void feedback(ReaderArtwork&out,J::Array&parent,const ReaderAction&a,ReaderColor accent,std::string prefix){auto group=layer(prefix,a.rect);group["allowsGroupOpacity"]=false;group["name"]="hud.control.highlight";const auto tint=prefix+"/tint",rim=prefix+"/rim";group["children"]=J::Array{shape(tint,{0,0,a.rect.width,a.rect.height},cut({0,0,a.rect.width,a.rect.height}),alpha(accent,.30),false,0),shape(rim,{0,0,a.rect.width,a.rect.height},cut({-2,-2,a.rect.width+4,a.rect.height+4}),accent,true,a.enabled?.28f:0.f)};parent.push_back(std::move(group));out.feedback.push_back({a.id,tint,rim,a.rect,a.enabled,a.enabled?.28f:0.f});}
void action(ReaderArtwork&out,J::Array&parent,const ReaderAction&a,ReaderColor ink,ReaderColor accent,std::string prefix,bool menu){parent.push_back(fill(prefix+"/plate",a.rect,a.selected?alpha(accent,.22):alpha(ink,.07)));if(menu&&!a.enabled)parent.back()["opacity"]=.4;
    // Canvas has disabled feedback artwork too; retained menus omit it.
    if(a.enabled||!menu)feedback(out,parent,a,accent,prefix+"/highlight");const auto r=menu?R{a.rect.x+6,a.rect.y+5,a.rect.width-12,a.rect.height-10}:R{a.rect.x+3,a.rect.y+a.rect.height/2-7,a.rect.width-6,14};parent.push_back(text(prefix+"/label",a.label,r,menu?10:11,alpha(ink,a.enabled?1:.3),menu?"natural":"center"));
    // ReaderCanvas's plate is always opaque as a layer; its color alpha alone
    // is .07 even for a disabled action.

}
}
ReaderStrings ReaderStrings::simplifiedChinese(){ReaderStrings s;s.open="打开";s.library="书库";s.reading="阅读设置";s.bookmarks="书签";s.title="阅读器";s.empty="打开书籍开始阅读。";s.loading="正在载入书籍…";s.chooseFile="从 Finder 选择";s.chooseShelf="从暂存架选择";s.shelfTitle="从暂存架选择";s.font="字体";s.fontSize="字号";s.lineSpacing="行间距";s.margin="页边距";s.horizontal="从左到右";s.vertical="从上到下";return s;}
ReaderArtwork prepareReaderCanvas(const ReaderCanvasInput&i){validColor(i.appearance.accent);need(std::isfinite(i.progress)&&i.progress>=0&&i.progress<=1);ReaderArtwork out;out.bounds={0,0,400,440};out.root=layer("reader",out.bounds);out.root["name"]="reader";out.progressRect=i.illustration?R{165,416,171,22}:R{55,389,290,22};J::Array children;auto page=fill("reader/viewport",ReaderViewport::viewport,white(i.appearance.dark?.07:.95,.85));page["masksToBounds"]=true;page["cornerRadius"]=3;J::Array pictures;for(int n=0;n<3;++n){const double neighbor=n==0?0:n==1?1:-1;pictures.push_back(layer("reader/picture/"+std::to_string(n),{0,neighbor*334,376,334}));}page["children"]=std::move(pictures);children.push_back(std::move(page));J::Array controlChildren;auto controls=layer("reader/controls",{});
    out.actions={{"open",i.strings.open,{12,8,64,30}},{"library",i.strings.library,{85,8,64,30}},{"settings",i.strings.reading,{158,8,84,30}},{"bookmark",i.bookmarked?"★":"☆",{251,8,36,30},i.hasPage},{"bookmarks",i.strings.bookmarks,{296,8,92,30},i.hasPage},{"previous","‹",{12,389,30,24},i.previous},{"next","›",{358,389,30,24},i.next}};
    if(i.illustration){out.actions.push_back({"zoomOut","−",{154,389,25,24}});out.actions.push_back({"zoomReset","1:1",{183,389,35,24}});out.actions.push_back({"zoomIn","+",{222,389,25,24}});}const auto ink=white(i.appearance.dark?.93:.08);for(std::size_t n=0;n<out.actions.size();++n)action(out,controlChildren,out.actions[n],ink,i.appearance.accent,"reader/control/"+std::to_string(n),false);controls["children"]=std::move(controlChildren);children.push_back(std::move(controls));
    children.push_back(text("reader/title",i.bookTitle.value_or(i.strings.title),{12,421,i.illustration?142.:304.,16},10,alpha(ink,.7)));const auto info=i.error.value_or(i.loading?i.strings.loading:!i.hasPage?i.strings.empty:"");auto status=text("reader/status",info,{27,185,346,70},12,ink,"center",true);status["hidden"]=info.empty();children.push_back(std::move(status));children.push_back(text("reader/percent",std::to_string(static_cast<int>(i.progress*100))+"%",{347,421,41,16},10,alpha(ink,.7),"right"));
    const auto r=out.progressRect;children.push_back(fill("reader/rail",{r.x,r.y+r.height/2,r.width,2},white(.5,.4)));children.push_back(fill("reader/fill",{r.x,r.y+r.height/2,r.width*i.progress,2},i.appearance.accent));auto thumb=fill("reader/thumb",{r.x+r.width*i.progress-2.5,r.y+r.height/2-3,5,8},white(1));thumb["hidden"]=!i.hasPage;children.push_back(std::move(thumb));out.root["children"]=std::move(children);return out;
}
ReaderArtwork prepareReaderMenu(const ReaderMenuInput&i){validColor(i.accent);need(i.preferences.valid()&&i.firstRow<=i.choices.size());ReaderArtwork out;
    if(i.type==ReaderMenuType::font){NotesControlsInput input;input.kind=NotesControlsKind::font;input.dark=true;input.accent=i.accent;input.firstRow=i.firstRow;input.selectedValue=i.selectedFont.value_or(i.preferences.fontName);for(const auto&choice:i.choices)input.values.push_back(choice.title);NotesControls controls;controls.update(input);out.root=controls.artwork();out.bounds=controls.bounds();for(const auto&a:controls.actions())out.actions.push_back({a.id,a.label,a.rect,a.enabled,a.selected});for(const auto&f:controls.feedback()){const auto action=std::find_if(out.actions.begin(),out.actions.end(),[&](const auto&a){return a.id==f.actionID;});need(action!=out.actions.end());out.feedback.push_back({f.actionID,f.tintLayerID,f.rimLayerID,action->rect,true,static_cast<float>(f.rimOpacity)});}return out;}
const bool open=i.type==ReaderMenuType::open,settings=i.type==ReaderMenuType::settings,font=i.type==ReaderMenuType::font;const double w=open?208:settings?248:font?242:i.type==ReaderMenuType::bookmarks?240:350,h=open?75:settings?222:font?184:294;out.bounds={0,0,w,h};out.root=layer("reader/menu",out.bounds);out.root["name"]="notes.secondaryMenu";auto face=fill("reader/menu/face",out.bounds,white(.08,.98));face["borderWidth"]=.7;face["borderColor"]=color(alpha(i.accent,.7));J::Array items;
    if(open)out.actions={{"finder",i.strings.chooseFile,{8,8,166,25}},{"shelf",i.strings.chooseShelf,{8,40,166,25}},{"close","×",{178,8,23,23}}};
    else if(settings){out.actions={{"close","×",{215,8,23,23}},{"font",i.strings.font+" · "+i.selectedFont.value_or(i.preferences.fontName),{8,8,198,26}}};for(std::size_t n=0;n<3;++n){const auto id=n==0?"size":n==1?"spacing":"margin";out.actions.push_back({std::string(id)+"-","−",{174,47+double(n)*40,30,30}});out.actions.push_back({std::string(id)+"+","+",{208,47+double(n)*40,30,30}});}out.actions.push_back({"horizontal",i.strings.horizontal,{8,176,112,32},true,!i.preferences.vertical()});out.actions.push_back({"vertical",i.strings.vertical,{128,176,112,32},true,i.preferences.vertical()});}

    else{out.actions.push_back({"close","×",{w-32,8,23,23}});const bool deleting=i.type==ReaderMenuType::library;for(auto n=i.firstRow;n<std::min(i.choices.size(),i.firstRow+6);++n){const auto y=39+double(n-i.firstRow)*35;out.actions.push_back({i.choices[n].id,i.choices[n].title,{8,y,w-(deleting?54:16),29}});if(deleting)out.actions.push_back({"delete:"+i.choices[n].id,"×",{w-33,y+3,23,23}});}if(i.deletion){out.actions.push_back({"cancelDelete","×",{w-128,258,52,27}});out.actions.push_back({"confirmDelete","✓",{w-64,258,56,27}});}}
    const auto ink=white(.96);for(std::size_t n=0;n<out.actions.size();++n)action(out,items,out.actions[n],ink,i.accent,"reader/menu/item/"+std::to_string(n),true);
    if(settings){const std::array<std::pair<std::string,double>,3>values{{{i.strings.fontSize,i.preferences.fontSize},{i.strings.lineSpacing,i.preferences.lineSpacing},{i.strings.margin,i.preferences.margin}}};for(std::size_t n=0;n<3;++n)items.push_back(text("reader/menu/value/"+std::to_string(n),values[n].first+"  "+std::to_string(static_cast<int>(values[n].second)),{10,53+double(n)*40,158,24},10,ink));}
    else if(!open&&!font){items.push_back(text("reader/menu/heading",i.type==ReaderMenuType::library?i.strings.library:i.type==ReaderMenuType::bookmarks?i.strings.bookmarks:i.strings.shelfTitle,{10,12,w-50,20},12,ink));if(i.choices.size()>6){const auto height=std::max(12.,204*6/double(i.choices.size()));items.push_back(fill("reader/menu/track",{w-6,39,2,204},alpha(ink,.12)));items.push_back(fill("reader/menu/thumb",{w-6,39+double(i.firstRow)/double(i.choices.size()-6)*(204-height),2,height},alpha(ink,.55)));}}
    face["children"]=std::move(items);out.root["children"]=J::Array{fill("reader/menu/shadow",{-3,4,w,h},white(0,.30)),std::move(face)};return out;
}
std::optional<std::string_view>readerActionAt(std::span<const ReaderAction>a,P p,bool last)noexcept{std::optional<std::string_view>found;for(const auto&x:a)if(x.enabled&&contains(x.rect,p)){found=x.id;if(!last)return found;}return found;}
ReaderPreferences changeReaderSetting(ReaderPreferences p,std::string_view id){need(p.valid());const double amount=id.ends_with('+')?1:-1;if(id.starts_with("size"))p.fontSize=std::clamp(p.fontSize+amount,10.,32.);else if(id.starts_with("spacing"))p.lineSpacing=std::clamp(p.lineSpacing+amount,0.,18.);else if(id.starts_with("margin"))p.margin=std::clamp(p.margin+amount,6.,48.);else if(id=="horizontal")p.setVertical(false);else if(id=="vertical")p.setVertical(true);return p;}
}
