#include "modules/reader_state.hpp"
#include <algorithm>
#include <atomic>
#include <cmath>
#include <limits>
#include <thread>

namespace endfield::modules {
namespace {
void need(bool value,const char*reason){if(!value)throw std::invalid_argument(reason);}
std::string message(std::exception_ptr e){try{std::rethrow_exception(e);}catch(const std::exception&v){return v.what();}catch(...){return "This book could not be read.";}}
bool finiteSize(core::Point p){return std::isfinite(p.x)&&std::isfinite(p.y)&&p.x>0&&p.y>0&&p.x<=4096&&p.y<=4096;}
void validPage(const ReaderPage&p){need(p.location.valid()&&(!p.next||p.next->valid())&&(!p.previous||p.previous->valid())&&std::isfinite(p.progress)&&p.progress>=0&&p.progress<=1&&ReaderJson::validUtf8(p.summary)&&p.summary.size()<=readerMaximumPageSummaryBytes,"Invalid Reader page metadata");need(bool(p.pixels),"Reader provider returned no page raster");{need(p.pixels->width>=200&&p.pixels->width<=900&&p.pixels->height>=200&&p.pixels->height<=1000&&p.pixels->bytes.size()==std::size_t(p.pixels->width)*p.pixels->height*4,"Reader raster exceeds the original fixed viewport budget");need(p.pixels->format==ReaderPagePixels::Format::rgba8Premultiplied||p.pixels->format==ReaderPagePixels::Format::bgra8Premultiplied,"Unknown Reader raster format");}}
}
bool ReaderImageView::valid()const noexcept{return std::isfinite(zoom)&&zoom>=1&&zoom<=12&&std::isfinite(pan.x)&&std::isfinite(pan.y);}
ReaderImageView ReaderImageView::clamped(core::Point size)const{need(finiteSize(size),"Invalid Reader viewport");const auto z=std::isfinite(zoom)?std::clamp(zoom,1.,12.):1.;const auto x=size.x*(z-1)/2,y=size.y*(z-1)/2;return {z,{std::clamp(std::isfinite(pan.x)?pan.x:0.,-x,x),std::clamp(std::isfinite(pan.y)?pan.y:0.,-y,y)}};}
struct ReaderState::Impl:std::enable_shared_from_this<Impl> {
    struct Request {std::optional<ReaderLocation>location;std::optional<double>progress;std::optional<ReaderBook>open;};
    std::shared_ptr<ReaderRepository>repository;ReaderExecutor executor;std::shared_ptr<ReaderDocumentSource>source;std::function<void()>changed;
    const std::thread::id owner=std::this_thread::get_id();bool alive{true},active{},loaded{},loadRunning{},loadRejected{},writing{},failedWrite{},rendering{},renderRejected{},releaseRejected{},loading{};
    ReaderLibrary library,draft,confirmed;std::optional<ReaderPreferences>preferencePreview;bool pendingOpen{};std::optional<std::string>error;std::uint64_t revision{},mutation{},writeVersion{},generation{},renderSerial{},detailSerial{};
    std::shared_ptr<std::atomic<std::uint64_t>>gate=std::make_shared<std::atomic<std::uint64_t>>(0),detailGate=std::make_shared<std::atomic<std::uint64_t>>(0);
    std::optional<ReaderLibrary>pendingSave;std::optional<Request>pending;std::vector<ReaderPage>pages;std::optional<ReaderPage>current;std::vector<ReaderLocation>history;
    core::Point size{376,334};bool dark{true};std::optional<ReaderDetail>detail;std::optional<ReaderImageView>pendingDetail;bool detailRunning{},detailRejected{};
    Impl(std::shared_ptr<ReaderRepository>r,ReaderExecutor e,std::shared_ptr<ReaderDocumentSource>s,std::function<void()>notify):repository(std::move(r)),executor(std::move(e)),source(std::move(s)),changed(std::move(notify)){need(repository&&executor.submit,"Reader requires an injected repository and FIFO executor");history.reserve(256);pages.reserve(3);}
    void check()const{need(std::this_thread::get_id()==owner,"Reader state belongs to one owner thread");}
    void notify(){++revision;if(alive&&changed)changed();}
    const ReaderBook*book()const{if(!library.selected)return nullptr;const auto it=std::find_if(library.books.begin(),library.books.end(),[&](const auto&b){return b.id==*library.selected;});return it==library.books.end()?nullptr:&*it;}
    void newGeneration(){need(generation<std::numeric_limits<std::uint64_t>::max(),"Reader generation exhausted");gate->store(++generation);pending.reset();rendering=false;renderRejected=false;pendingDetail.reset();detail.reset();detailRunning=false;detailRejected=false;detailGate->store(++detailSerial);pages.clear();current.reset();history.clear();loading=false;}
    void pumpLoad(){if(!alive||loaded||loadRunning||!active)return;const auto weak=weak_from_this();auto result=std::make_shared<std::optional<ReaderLibrary>>();auto repo=repository;
        const auto accepted=executor.submit([repo,result]{*result=repo->load();},[weak,result](std::exception_ptr e){const auto i=weak.lock();if(!i||!i->alive)return;i->check();i->loadRunning=false;if(e){i->error=message(e);i->loading=false;}else{need(result->has_value(),"Reader library callback has no result");validateReaderLibrary(**result);i->library=std::move(**result);i->draft=i->confirmed=i->library;i->loaded=true;i->error.reset();i->loading=false;if(i->active)i->openSelected();}i->notify();});
        loadRejected=!accepted;loadRunning=accepted;loading=true;
    }
    void save(bool reopen=false){if(!alive)return;validateReaderLibrary(draft);pendingSave=draft;pendingOpen=pendingOpen||reopen;++mutation;failedWrite=false;pumpSave();notify();}
    void pumpSave(){if(!alive||writing||!pendingSave||failedWrite)return;auto value=std::make_shared<ReaderLibrary>(*pendingSave);const auto version=mutation;const bool reopen=pendingOpen;const auto weak=weak_from_this();auto repo=repository;
        const auto accepted=executor.submit([repo,value]{repo->save(*value);},[weak,version,reopen,value](std::exception_ptr e){const auto i=weak.lock();if(!i||!i->alive)return;i->check();i->writing=false;if(e){i->pendingOpen=i->pendingOpen||reopen;i->error=message(e);i->failedWrite=i->mutation==version;if(i->preferencePreview&&*i->preferencePreview==value->preferences){i->preferencePreview.reset();i->library.preferences=i->confirmed.preferences;i->refresh();}}else{const auto selected=i->library.selected;const auto oldPreferences=i->library.preferences;i->confirmed=*value;i->library=*value;for(auto&book:i->library.books){const auto latest=std::find_if(i->draft.books.begin(),i->draft.books.end(),[&](const auto&b){return b.id==book.id;});if(latest!=i->draft.books.end()){book.location=latest->location;book.progress=latest->progress;}}if(i->preferencePreview&&*i->preferencePreview==value->preferences)i->preferencePreview.reset();if(i->preferencePreview)i->library.preferences=*i->preferencePreview;if(i->mutation==version){i->pendingSave.reset();i->pendingOpen=false;}i->error.reset();if(i->active&&(reopen||selected!=i->library.selected))i->openSelected();else if(i->active&&oldPreferences!=i->library.preferences)i->refresh();}i->notify();if(i->alive&&i->pendingSave&&!i->failedWrite)i->pumpSave();});
        if(accepted){writing=true;writeVersion=version;pendingOpen=false;}
    }
    void progress(const ReaderPage&p){const auto*b=book();if(!b)return;auto it=std::find_if(library.books.begin(),library.books.end(),[&](const auto&v){return v.id==b->id;});if(it->location==p.location&&it->progress==p.progress)return;it->location=p.location;it->progress=p.progress;const auto target=std::find_if(draft.books.begin(),draft.books.end(),[&](const auto&v){return v.id==b->id;});if(target!=draft.books.end()){target->location=p.location;target->progress=p.progress;save();}}
    void openSelected(){if(!alive||!active||!source)return;newGeneration();if(const auto*b=book()){pending=Request{b->location,{},*b};loading=true;error.reset();pumpRender();}}
    void refresh(){const auto*b=book();if(!alive||!active||!b)return;request(current?current->location:b->location);}
    void request(std::optional<ReaderLocation>location,std::optional<double>fraction={}){if(!alive||!active||!source||!book())return;const auto token=generation;cancelDetail();if(location&&(!current||*location!=current->location)){const auto it=std::find_if(pages.begin(),pages.end(),[&](const auto&p){return p.location==*location;});if(it!=pages.end()){current=*it;progress(*current);notify();}}if(!alive||!active||generation!=token)return;auto opening=pending?std::move(pending->open):std::optional<ReaderBook>{};pending=Request{location,fraction,std::move(opening)};pumpRender();}
    void pumpRender(){if(!alive||!active||rendering||!pending||!source)return;auto request=std::make_shared<Request>(*pending);const auto token=generation,serial=renderSerial+1;auto result=std::make_shared<std::vector<ReaderPage>>();const auto prefs=library.preferences;const auto viewport=size;const auto theme=dark;const auto sharedGate=gate;const auto decoder=source;const auto weak=weak_from_this();
        const auto accepted=executor.submit([request,result,prefs,viewport,theme,sharedGate,token,decoder]{const auto canceled=[sharedGate,token]{return sharedGate->load()!=token;};if(canceled())return;if(request->open){decoder->release();decoder->open(*request->open,canceled);}if(canceled())return;*result=decoder->render(request->location,request->progress,prefs,viewport,theme,canceled);if(!canceled()){need(!result->empty()&&result->size()<=3,"Reader provider must return current and at most two neighbors");for(const auto&p:*result)validPage(p);}},[weak,result,token,serial](std::exception_ptr e){const auto i=weak.lock();if(!i||!i->alive||!i->active||i->generation!=token||i->renderSerial!=serial)return;i->check();i->rendering=false;if(i->pending){i->pumpRender();return;}i->loading=false;if(e)i->error=message(e);else{need(!result->empty(),"Reader page callback has no current page");i->pages=std::move(*result);i->current=i->pages.front();i->progress(*i->current);if(!i->alive||!i->active||i->generation!=token)return;i->error.reset();}i->notify();});
        renderRejected=!accepted;if(accepted){renderSerial=serial;rendering=true;pending.reset();loading=!current;error.reset();}
    }
    void cancelDetail(){detailGate->store(++detailSerial);pendingDetail.reset();detail.reset();detailRejected=false;}
    void pumpDetail(){if(!alive||!active||detailRunning||!pendingDetail||!current||!source)return;const auto view=*pendingDetail;const auto location=current->location;const auto token=generation,serial=detailSerial;const auto prefs=library.preferences;const auto viewport=size;const auto theme=dark;const auto decoder=source;const auto sharedGate=gate,sharedDetailGate=detailGate;auto result=std::make_shared<std::optional<ReaderPage>>();const auto weak=weak_from_this();
        const bool accepted=executor.submit([decoder,sharedGate,sharedDetailGate,token,serial,prefs,viewport,theme,view,location,result]{const auto canceled=[sharedGate,sharedDetailGate,token,serial]{return sharedGate->load()!=token||sharedDetailGate->load()!=serial;};if(canceled())return;*result=decoder->detail(location,prefs,viewport,theme,view,canceled);if(!canceled())validPage(**result);},[weak,result,token,serial,view,location](std::exception_ptr e){const auto i=weak.lock();if(!i||!i->alive||!i->active||i->generation!=token)return;i->check();i->detailRunning=false;if(!e&&i->detailSerial==serial&&i->current&&i->current->location==location&&*result){i->detail=ReaderDetail{view,std::move(**result)};i->notify();}if(i->alive&&i->pendingDetail)i->pumpDetail();});
        detailRejected=!accepted;if(accepted){detailRunning=true;pendingDetail.reset();}
    }
    void release(){if(!alive||!source)return;const auto decoder=source;const auto sharedGate=gate;const auto token=generation;releaseRejected=!executor.submit([decoder,sharedGate,token]{if(sharedGate->load()==token)decoder->release();},[](std::exception_ptr){});}
};
ReaderState::ReaderState(std::shared_ptr<ReaderRepository>r,ReaderExecutor e,std::shared_ptr<ReaderDocumentSource>s,std::function<void()>changed):impl_(std::make_shared<Impl>(std::move(r),std::move(e),std::move(s),std::move(changed))){}
ReaderState::~ReaderState(){impl_->alive=false;impl_->gate->fetch_add(1);impl_->detailGate->fetch_add(1);}
void ReaderState::setActive(bool value){auto i=impl_;i->check();if(i->active==value)return;i->active=value;if(value){i->releaseRejected=false;if(!i->loaded)i->pumpLoad();else i->openSelected();}else{i->newGeneration();i->release();}i->notify();}
bool ReaderState::active()const noexcept{return impl_->active;}bool ReaderState::loaded()const noexcept{return impl_->loaded;}bool ReaderState::busy()const noexcept{return impl_->loadRunning||impl_->writing||impl_->rendering||impl_->detailRunning;}bool ReaderState::loading()const noexcept{return impl_->loading;}bool ReaderState::hasUnsavedChanges()const noexcept{return impl_->pendingSave.has_value();}bool ReaderState::documentProviderAvailable()const noexcept{return bool(impl_->source);}
const ReaderLibrary&ReaderState::library()const noexcept{return impl_->library;}const ReaderBook*ReaderState::book()const noexcept{return impl_->book();}const ReaderPage*ReaderState::current()const noexcept{return impl_->current?&*impl_->current:nullptr;}std::span<const ReaderPage>ReaderState::pages()const noexcept{return impl_->pages;}const std::optional<ReaderDetail>&ReaderState::imageDetail()const noexcept{return impl_->detail;}const std::optional<std::string>&ReaderState::error()const noexcept{return impl_->error;}std::uint64_t ReaderState::revision()const noexcept{return impl_->revision;}
bool ReaderState::addValidated(ReaderBook book){auto i=impl_;i->check();if(!i->loaded)return false;ReaderLibrary probe;probe.books={book};validateReaderLibrary(probe);auto next=i->draft;auto found=std::find_if(next.books.begin(),next.books.end(),[&](const auto&b){return b.platform==book.platform&&readerReferencePath(b)==readerReferencePath(book);});if(found!=next.books.end()){auto original=*found;original.title=std::move(book.title);original.bookmarkBase64=std::move(book.bookmarkBase64);original.scoped=book.scoped;original.path=std::move(book.path);original.windowsPath=std::move(book.windowsPath);book=std::move(original);*found=book;}else{if(next.books.size()>=readerMaximumBooks)throw ReaderError(ReaderErrorCode::tooLarge);next.books.push_back(book);}next.selected=book.id;validateReaderLibrary(next);if(next==i->draft)return false;i->draft=std::move(next);i->save(true);return true;}
bool ReaderState::select(std::string_view id){auto i=impl_;i->check();if(!i->loaded)return false;const auto found=std::find_if(i->draft.books.begin(),i->draft.books.end(),[&](const auto&b){return b.id==id;});if(found==i->draft.books.end())throw ReaderError(ReaderErrorCode::unavailable);if(i->draft.selected==std::optional(found->id)){if(!i->pendingSave&&i->active)i->openSelected();return false;}i->draft.selected=found->id;i->save(true);return true;}
bool ReaderState::remove(std::string_view id){auto i=impl_;i->check();if(!i->loaded)return false;const std::string owned(id);const bool selected=i->draft.selected==std::optional(owned);if(!std::erase_if(i->draft.books,[&](const auto&b){return b.id==owned;}))return false;if(selected)i->draft.selected=i->draft.books.empty()?std::nullopt:std::optional(i->draft.books.front().id);i->save(selected);return true;}
bool ReaderState::saveProgress(ReaderLocation location,double fraction,std::string_view id){auto i=impl_;i->check();if(!location.valid()||!std::isfinite(fraction))return false;auto it=std::find_if(i->draft.books.begin(),i->draft.books.end(),[&](const auto&b){return b.id==id;});if(it==i->draft.books.end())return false;fraction=std::clamp(fraction,0.,1.);if(it->location==location&&it->progress==fraction)return false;it->location=location;it->progress=fraction;for(auto&b:i->library.books)if(b.id==id){b.location=location;b.progress=fraction;}i->save();return true;}
bool ReaderState::toggleBookmark(std::string id){auto i=impl_;i->check();if(!i->book()||!i->current)return false;auto next=i->draft;const auto activeID=i->book()->id;auto it=std::find_if(next.books.begin(),next.books.end(),[&](const auto&b){return b.id==activeID;});if(it==next.books.end())return false;it->location=i->current->location;it->progress=i->current->progress;const auto mark=std::find_if(it->bookmarks.begin(),it->bookmarks.end(),[&](const auto&m){return m.location==it->location;});if(mark!=it->bookmarks.end())it->bookmarks.erase(mark);else{if(it->bookmarks.size()>=readerMaximumBookmarks)throw ReaderError(ReaderErrorCode::tooLarge);it->bookmarks.push_back({std::move(id),it->location,it->progress});}validateReaderLibrary(next);i->draft=std::move(next);i->save();return true;}
bool ReaderState::setPreferences(ReaderPreferences value){auto i=impl_;i->check();if(!i->loaded||!value.valid())return false;value.originalFields=i->draft.preferences.originalFields;value.originalNumbers=i->draft.preferences.originalNumbers;if(value==i->library.preferences)return false;i->draft.preferences=value;i->preferencePreview=value;i->library.preferences=std::move(value);i->history.clear();i->save();i->refresh();return true;}
void ReaderState::setLayout(core::Point size,bool dark){auto i=impl_;i->check();need(finiteSize(size),"Invalid Reader layout");if(i->size==size&&i->dark==dark)return;i->size=size;i->dark=dark;i->refresh();}
bool ReaderState::next(){auto i=impl_;i->check();if(!i->current||!i->current->next)return false;if(i->history.size()==256)i->history.erase(i->history.begin());i->history.push_back(i->current->location);i->request(i->current->next);return true;}
bool ReaderState::previous(){auto i=impl_;i->check();std::optional<ReaderLocation>location;if(!i->history.empty()){location=i->history.back();i->history.pop_back();}else if(i->current)location=i->current->previous;if(!location)return false;i->request(location);return true;}
void ReaderState::jump(ReaderLocation location){auto i=impl_;i->check();need(location.valid(),"Invalid Reader jump location");i->history.clear();i->request(std::move(location));}
void ReaderState::jump(double progress){auto i=impl_;i->check();if(!std::isfinite(progress))return;i->history.clear();i->request({},std::clamp(progress,0.,1.));}
void ReaderState::requestImageDetail(ReaderImageView view){auto i=impl_;i->check();if(!i->active||!i->current||!i->current->illustration||!view.valid())return;view=view.clamped(i->size);if(view.zoom<=1){i->cancelDetail();return;}if(i->detail&&i->detail->view==view&&i->detail->page.location==i->current->location)return;i->detailGate->store(++i->detailSerial);i->pendingDetail=view;i->pumpDetail();}
void ReaderState::cancelImageDetail(){auto i=impl_;i->check();i->cancelDetail();}
void ReaderState::queueCapacityAvailable(){auto i=impl_;i->check();if(i->loadRejected)i->pumpLoad();if(i->releaseRejected&&!i->active)i->release();i->pumpSave();if(i->renderRejected)i->pumpRender();if(i->detailRejected)i->pumpDetail();}
void ReaderState::retryPendingWrites(){auto i=impl_;i->check();i->failedWrite=false;i->pumpSave();}
void ReaderState::flush(){auto i=impl_;i->check();i->pumpSave();}
} // namespace endfield::modules
