#include "modules/settings_safety.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace endfield::modules {namespace {using Json=ehud::data::Json;using Rect=core::Rect;using Color=std::array<double,4>;
void need(bool v,const char*s){if(!v)throw std::invalid_argument(s);}void finite(double t){need(std::isfinite(t),"Settings safety needs finite caller time");}
double curve(double t,double cx1,double cy1,double cx2,double cy2){finite(t);if(t<=0)return 0;if(t>=1)return 1;const double x=static_cast<float>(t),x1=static_cast<float>(cx1),x2=static_cast<float>(cx2),y1=static_cast<float>(cy1),y2=static_cast<float>(cy2);const double ax=1-3*x2+3*x1,bx=3*x2-6*x1,cx=3*x1,ay=1-3*y2+3*y1,by=3*y2-6*y1,cy=3*y1;double p=x;for(unsigned n=0;n<8;++n){const double e=((ax*p+bx)*p+cx)*p-x;if(std::abs(e)<1e-5)break;p-=e/((3*ax*p+2*bx)*p+cx);}return static_cast<float>(((ay*p+by)*p+cy)*p);}
double timing(double t){return curve(t,.2,.7,.3,1);}
Color gray(double w,double a=1){return{w,w,w,a};}Color alpha(Color c,double a){c[3]=a;return c;}Json color(Color c){return Json::Object{{"sRGB",Json::Array{c[0],c[1],c[2],c[3]}}};}
Json layer(std::string id,Rect r,const char*kind="layer"){return Json::Object{{"id",std::move(id)},{"kind",kind},{"bounds",Json::Array{0,0,r.width,r.height}},{"position",Json::Array{r.x,r.y}},{"anchorPoint",Json::Array{0,0}},{"children",Json::Array{}}};}
Json command(const char*name,double x,double y){Json::Array points;points.push_back(Json::Array{x,y});return Json::Object{{"op",name},{"points",std::move(points)}};}
Json shape(std::string id,Rect r,double corner,Color fill,Color stroke,double width){auto node=layer(std::move(id),r,"shape");Json::Array path{command("move",corner,0),command("line",r.width,0),command("line",r.width,r.height-corner),command("line",r.width-corner,r.height),command("line",0,r.height),command("line",0,corner),Json::Object{{"op","close"},{"points",Json::Array{}}}};node["shape"]=Json::Object{{"path",std::move(path)},{"fillColor",color(fill)},{"strokeColor",color(stroke)},{"lineWidth",width},{"lineCap","butt"},{"lineJoin","miter"},{"miterLimit",10}};return node;}
Json text(std::string id,Rect r,std::string value,double size,Color ink,double density,const char*face,const char*alignment="left",bool wrapped=false){auto node=layer(std::move(id),r,"text");const auto name=std::string_view(face);node["contentsScale"]=density;node["text"]=Json::Object{{"string",std::move(value)},{"fontSize",size},{"font",Json::Object{{"postScriptName",face},{"familyName",name.find("Monospaced")!=std::string_view::npos?".AppleSystemUIFontMonospaced":".AppleSystemUIFont"},{"pointSize",size},{"symbolicTraits",name.find("Monospaced")!=std::string_view::npos?1026:name.ends_with("Demi")||name.ends_with("Bold")?2:0}}},{"foregroundColor",color(ink)},{"alignment",alignment},{"wrapped",wrapped},{"truncation",wrapped?"none":"end"}};return node;}
}
double settingsSafetyFeedbackProgress(double phase){return curve(phase,.25,.1,.25,1);}
SettingsSafetyColor settingsSafetyInterpolateColor(const SettingsSafetyColor&from,const SettingsSafetyColor&to,double phase){finite(phase);if(from==to)return to;if(phase<=0)return from;if(phase>=1)return to;const auto p=settingsSafetyFeedbackProgress(phase);auto out=from;for(unsigned n=0;n<4;++n)out[n]=n<3?static_cast<float>(from[n]+(to[n]-from[n])*p):from[n]+(to[n]-from[n])*p;return out;}
SettingsSafety::SettingsSafety(SettingsController&c):controller_(&c){updateButtons(0,false);}
void SettingsSafety::setAppearance(SettingsAppearance a){for(double c:a.accent)need(std::isfinite(c)&&c>=0&&c<=1,"Invalid safety accent");if(a==appearance_)return;appearance_=a;updateButtons(0,false);changed();}
SettingsSafetyButtonPaint SettingsSafety::buttonPaint(unsigned n,double now)const{finite(now);need(n<2,"Invalid source safety button");const auto&b=buttons_[n];return{settingsSafetyInterpolateColor(b.fill.from,b.fill.to,(now-b.fill.start)/.12),settingsSafetyInterpolateColor(b.stroke.from,b.stroke.to,(now-b.stroke.start)/.12),b.width.from+(b.width.to-b.width.from)*settingsSafetyFeedbackProgress((now-b.width.start)/.12)};}
bool SettingsSafety::feedbackAnimating(double now)const{finite(now);if(!shown_||reduced_)return false;for(const auto&b:buttons_)if((b.fill.from!=b.fill.to&&now<b.fill.start+.12)||(b.stroke.from!=b.stroke.to&&now<b.stroke.start+.12)||(b.width.from!=b.width.to&&now<b.width.start+.12))return true;return false;}
void SettingsSafety::updateButtons(double now,bool animated){animated=animated&&!reduced_&&shown_&&buttonsReady_;for(unsigned n=0;n<2;++n){const auto previous=buttonPaint(n,now);const bool engaged=hovered_==int(n)||pressed_==int(n),focus=focused_==int(n);const auto targetFill=engaged?alpha(appearance_.accent,.20):gray(static_cast<float>(appearance_.dark?.9:.1),.065);const auto targetStroke=focus||engaged?alpha(appearance_.accent,.90):gray(static_cast<float>(appearance_.dark?.7:.3),.44);const auto width=focus?1.25:.7;auto&b=buttons_[n];const auto color=[&](ColorTrack&t,const Color&target,const Color&prior){if(t.to==target&&animated)return;t.from=animated?prior:target;t.to=target;t.start=now;};color(b.fill,targetFill,previous.fill);color(b.stroke,targetStroke,previous.stroke);if(b.width.to!=width||!animated)b.width={animated?previous.width:width,width,now};}buttonsReady_=true;}

bool SettingsSafety::refresh(double now){finite(now);const auto old=revision_;const auto remaining=controller_->confirmationRemaining(now);if(!remaining){remaining_.reset();if(shown_&&!dismissing_){submitted_=true;pressed_.reset();if(reduced_){shown_=false;}else{dismissing_=true;start_=now;}changed();}if(dismissing_&&now>=start_+.14){shown_=dismissing_=false;hovered_.reset();changed();}return old!=revision_;}
 const bool position=controller_->positionPending();const auto language=controller_->language();if(remaining_!=remaining||language_!=language||position_!=position||strings_.title.empty()){const auto n=std::to_string(*remaining);const std::array<std::string_view,1>arguments{n};SettingsSafetyStrings strings{core::localized(position?"Keep this position?":"Keep this UI scale?",position?"保留此位置？":"保留此缩放？",language),core::localized(position?"Keep this position? Reverts in {0}s":"Keep this UI scale? Reverts in {0}s",position?"保留此位置？{0} 秒后自动恢复":"保留此缩放？{0} 秒后自动恢复",language,arguments),core::localized("Revert ⎋","恢复 ⎋",language),core::localized("Keep ↵","保留 ↵",language)};if(strings!=strings_){strings_=std::move(strings);changed();}remaining_=remaining;language_=language;position_=position;updateButtons(now,false);}if(!shown_||dismissing_){const bool wasShown=shown_;shown_=true;dismissing_=submitted_=false;focused_=1;pressed_.reset();if(!wasShown)start_=now;else start_=now-.2;updateButtons(now,false);changed();}return old!=revision_;}
void SettingsSafety::setReduceMotion(bool v,double now){finite(now);if(reduced_==v)return;reduced_=v;if(v&&dismissing_)shown_=dismissing_=false;updateButtons(now,false);changed();}
void SettingsSafety::hideImmediately(double now){finite(now);shown_=dismissing_=submitted_=false;hovered_.reset();pressed_.reset();changed();}
SettingsSafetyPose SettingsSafety::pose(double now)const{finite(now);if(!shown_)return{};if(reduced_)return{1,0,true,false,false};const double elapsed=std::max(0.,now-start_);if(dismissing_){const double p=timing(elapsed/.14);return{1-p,8*p,true,true,elapsed<.14};}return{timing(elapsed/.16),12*(1-timing(elapsed/.2)),true,false,elapsed<.2};}
bool SettingsSafety::requiresFrames(double now)const{return pose(now).animated||feedbackAnimating(now);}
void SettingsSafety::action(bool confirm,double now){if(!shown_||submitted_||dismissing_)return;submitted_=true;if(confirm)controller_->confirmLayout(now);else controller_->revertLayout();refresh(now);}
bool SettingsSafety::pointerDown(std::optional<int>a,double now){finite(now);if(!shown_)return false;if(dismissing_||submitted_)return true;need(!a||*a==0||*a==1,"Invalid safety action");pressed_=a;if(a)focused_=*a;updateButtons(now,true);changed();return true;}
bool SettingsSafety::pointerUp(std::optional<int>a,double now){finite(now);if(!shown_)return false;const auto pressed=pressed_;pressed_.reset();updateButtons(now,true);changed();if(pressed&&pressed==a)action(*a==1,now);return true;}
void SettingsSafety::pointerMove(std::optional<int>a,double now){finite(now);need(!a||*a==0||*a==1,"Invalid safety hover");if(hovered_==a)return;hovered_=a;updateButtons(now,true);changed();}
bool SettingsSafety::key(unsigned key,bool repeat,double now){finite(now);if(!shown_)return false;if(dismissing_||submitted_||repeat)return true;if(key==27)action(false,now);else if(key==9){focused_=1-focused_;updateButtons(now,true);changed();}else if(key==37||key==39){focused_=key==39;updateButtons(now,true);changed();}else if(key==13||key==32)action(focused_==1,now);return true;}
SettingsSafetyGeometry SettingsSafety::geometry(Rect v){need(std::isfinite(v.x)&&std::isfinite(v.y)&&std::isfinite(v.width)&&std::isfinite(v.height)&&v.width>0&&v.height>0,"Invalid safety viewport");const double width=std::min(390.,std::max(220.,v.width-40)),button=(width-58)/2;return{{v.x+(v.width-width)/2,v.y+(v.height-190)/2,width,190},{23,137,button,32},{35+button,137,button,32}};}
core::Matrix4 SettingsSafety::centeredSourceTransform(const core::Matrix4&p,double scale){need(p.finite()&&std::isfinite(scale)&&scale>0,"Invalid source confirmation tilt");const auto&m=p.values;const double w=m[3]*500+m[7]*320+m[15];need(std::isfinite(w)&&std::abs(w)>.0001,"Invalid confirmation projection divisor");const double x=(m[0]*500+m[4]*320+m[12])/w,y=(m[1]*500+m[5]*320+m[13])/w;return core::Matrix4::translation(-x,-y)*p*core::Matrix4::translation(500,320)*core::Matrix4::scale(1/scale,1/scale);}
SettingsArtworkPart prepareSettingsSafetyArtwork(const SettingsSafety&s,Rect viewport,const SettingsAppearance&a,std::optional<double>feedbackTime){need(std::isfinite(a.scale)&&a.scale>=1&&a.scale<=8,"Invalid source safety density");for(double c:a.accent)need(std::isfinite(c)&&c>=0&&c<=1,"Invalid safety accent");const auto geometry=SettingsSafety::geometry(viewport);const double width=geometry.card.width;const auto primary=gray(a.dark?.95:.10);SettingsArtworkPart part;part.layers=layer("settings.safety",{});Json::Array children;const auto add=[&](Json node){const auto&p=node["position"].array();part.surfaces.push_back({node["id"].string(),{},core::Matrix4::translation(p[0].number(),p[1].number()),false,false,1});children.push_back(std::move(node));};add(shape("settings.safety.plate",{.5,.5,width-1,189},10,gray(a.dark?.095:.90,.98),alpha(a.accent,.58),.8));auto line=layer("settings.safety.line",{23,0,62,2});line["backgroundColor"]=color(alpha(a.accent,.82));add(std::move(line));
 for(int n=0;n<2;++n){const auto r=n==0?geometry.cancel:geometry.confirm;const bool engaged=s.hovered()==n||s.pressed()==n,focused=s.focused()==n;const auto paint=feedbackTime?s.buttonPaint(unsigned(n),*feedbackTime):SettingsSafetyButtonPaint{engaged?alpha(a.accent,.20):gray(a.dark?.9:.1,.065),focused||engaged?alpha(a.accent,.90):gray(a.dark?.7:.3,.44),focused?1.25:.7};add(shape(n?"settings.safety.confirmPlate":"settings.safety.cancelPlate",{r.x-2,r.y-2,r.width+4,r.height+4},4,paint.fill,paint.stroke,paint.width));}
 add(text("settings.safety.title",{23,42,width-46,28},s.strings().title,18,primary,a.scale,".AppleSystemUIFontBold"));add(text("settings.safety.message",{23,78,width-46,42},s.strings().message,12,gray(a.dark?.73:.32),a.scale,".AppleSystemUIFontMedium","left",true));add(text("settings.safety.caption",{23,18,width-46,13},"ENDFIELDHUD / SYSTEM",8,gray(a.dark?.53:.44),a.scale,".AppleSystemUIFontMonospaced-Semibold"));for(int n=0;n<2;++n){const auto r=n==0?geometry.cancel:geometry.confirm;add(text(n?"settings.safety.confirm":"settings.safety.cancel",{r.x,r.y+8.5,r.width,15},n?s.strings().confirm:s.strings().cancel,12,primary,a.scale,".AppleSystemUIFontDemi","center"));}part.layers["children"]=std::move(children);return part;}
}
