#include "modules/settings_presentation.hpp"
#include <algorithm>
#include <charconv>
#include <cmath>
#include <stdexcept>
#include <utility>
namespace endfield::modules {namespace {
using Kind=SettingsRowKind;using Row=SettingsRow;using Rect=core::Rect;using Point=core::Point;using Json=ehud::data::Json;
void need(bool v,const char*s){if(!v)throw std::invalid_argument(s);}void finite(double t){need(std::isfinite(t),"Settings requires finite presentation time");}
bool contains(Rect r,Point p){return p.x>=r.x&&p.y>=r.y&&p.x<r.x+r.width&&p.y<r.y+r.height;}
bool contains(Rect a,Rect b){return b.x>=a.x&&b.y>=a.y&&b.x+b.width<=a.x+a.width&&b.y+b.height<=a.y+a.height;}
Rect intersection(Rect a,Rect b){const auto x=std::max(a.x,b.x),y=std::max(a.y,b.y),right=std::min(a.x+a.width,b.x+b.width),bottom=std::min(a.y+a.height,b.y+b.height);return{x,y,std::max(0.,right-x),std::max(0.,bottom-y)};}
std::string fixed(double n,int digits){char chars[96];const auto r=std::to_chars(chars,chars+sizeof(chars),n,std::chars_format::fixed,digits);need(r.ec==std::errc(),"Settings value formatting failed");return{chars,r.ptr};}
std::string formatted(double value,std::string_view id,core::Language language){if(id=="duration")return fixed(std::round(value),0)+" "+core::localized("seconds","秒",language);if(id=="uiScale"||id=="batterySize")return fixed(value,2)+"×";if(id=="positionX"||id=="positionY")return(value>=0?"+":"")+fixed(std::round(value*100),0)+"%";return fixed(std::round(value*100),0)+"%";}
Row row(std::string id,std::string title,Kind kind,std::string value={},double height=40){Row r;r.id=std::move(id);r.title=std::move(title);r.kind=kind;r.value=std::move(value);r.height=height;return r;}
Row toggle(std::string id,std::string title,bool value){auto r=row(std::move(id),std::move(title),Kind::toggle);r.selected=value;return r;}
Row slider(std::string id,std::string title,double value,double low,double high){auto r=row(std::move(id),std::move(title),Kind::slider);r.number=value;r.minimum=low;r.maximum=high;return r;}
Row selection(std::string id,std::string title,bool selected,std::string detail={},bool available=true,double height=40){auto r=row(std::move(id),std::move(title),Kind::selection,{},height);r.selected=selected;r.detail=std::move(detail);r.available=available;return r;}
constexpr std::array<std::string_view,5>accents{"FAD41F","6EDFE8","A8E58B","C9A2FF","FF8F78"};
constexpr std::array<std::string_view,6>languages{"system","english","simplifiedChinese","traditionalChinese","japanese","korean"};
constexpr std::array<std::string_view,5>logos{"endfield","rhodesIsland","babel","rhineLab","custom"},metrics{"battery","ram","cpu","network","disk"},clocks{"digital","split","dial","rail","stacked"};
std::string cycle(std::string_view current,std::span<const std::string_view> values){const auto found=std::find(values.begin(),values.end(),current);return std::string(values[(found==values.end()?0:static_cast<std::size_t>(found-values.begin())+1)%values.size()]);}
Rect iconRect(std::size_t i,Rect r){return{23+double(i)*90,r.y+5,82,66};}Rect paletteRect(std::size_t i,Rect r){return{198+double(i)*30,r.y+17,25,25};}
}
SettingsPresentation::SettingsPresentation(core::Module module,SettingsController&controller,std::vector<SettingsIcon>icons,SettingsAbout about,SettingsViewHooks hooks):module_(module),controller_(&controller),icons_(std::move(icons)),about_(std::move(about)),hooks_(std::move(hooks)){
    need(module==core::Module::system||module==core::Module::display||module==core::Module::hotkeys||module==core::Module::about,"Invalid Settings module");need(icons_.size()<=256&&about_.credits.size()<=64,"Settings metadata exceeds source UI bound");
    for(std::size_t n=0;n<icons_.size();++n){need(!icons_[n].id.empty()&&icons_[n].id.size()<256&&Json::validUtf8(icons_[n].title),"Invalid explicit icon roster");for(std::size_t k=0;k<n;++k)need(icons_[n].id!=icons_[k].id,"Duplicate Settings icon identity");}
    if(module==core::Module::system&&hooks_.displays)displays_=hooks_.displays();rebuild();
}
std::string SettingsPresentation::text(std::string_view en,std::string_view zh)const{return core::localized(en,zh,controller_->language());}
std::vector<Row>SettingsPresentation::rows()const{
    const auto&c=controller_->configuration();std::vector<Row>out;
    const auto languageTitle=[&](std::string_view id){if(id=="system")return text("System","跟随系统");if(id=="english")return std::string("English");if(id=="simplifiedChinese")return std::string("简体中文");if(id=="traditionalChinese")return std::string("繁體中文");if(id=="japanese")return std::string("日本語");return std::string("한국어");};
    const auto metricTitle=[&](std::string_view id){if(id=="battery")return text("Battery","电池");if(id=="ram")return std::string("RAM");if(id=="cpu")return std::string("CPU");if(id=="network")return text("Network","网络");return text("Disk","磁盘");};
    if(module_==core::Module::system){
        if(page_==SettingsPage::languages){for(auto id:languages)out.push_back(selection("language:"+std::string(id),languageTitle(id),c.string("language")==id));return out;}
        const auto&displayID=c.fields["windowsDisplayID"];const auto selectedDisplay=displayID.isString()?displayID.string():std::string{};
        if(page_==SettingsPage::screens){out.push_back(selection("screen:pointer",text("Pointer display","鼠标所在显示器"),selectedDisplay.empty()&&c.boolean("openOnActiveDisplay")));out.push_back(selection("screen:main",text("Main display","主显示器"),selectedDisplay.empty()&&!c.boolean("openOnActiveDisplay")));
            bool found{};for(std::size_t n=0;n<displays_.size();++n){const auto&d=displays_[n];const auto copies=std::count_if(displays_.begin(),displays_.end(),[&](const auto&v){return v.name==d.name;});out.push_back(selection("screen:"+d.id,d.name+(copies>1?" · "+std::to_string(n+1):""),d.id==selectedDisplay,d.dimensions,true,48));found|=d.id==selectedDisplay;}
            if(!selectedDisplay.empty()&&!found){const auto&name=c.fields["windowsDisplayName"];out.push_back(selection("screen:disconnected",name.isString()?name.string():text("Saved display","已选显示器"),true,text("Disconnected · using pointer display","未连接 · 暂用鼠标所在显示器"),false,48));}return out;}
        auto displayTitle=c.boolean("openOnActiveDisplay")?text("Pointer display","鼠标所在显示器"):text("Main display","主显示器");if(!selectedDisplay.empty()){const auto found=std::find_if(displays_.begin(),displays_.end(),[&](const auto&d){return d.id==selectedDisplay;});const auto&name=c.fields["windowsDisplayName"];displayTitle=found!=displays_.end()?found->name:name.isString()?name.string():text("Saved display","已选显示器");if(found==displays_.end())displayTitle+=text(" (disconnected)","（未连接）");}
        return{row("language",text("Language","语言"),Kind::choice,languageTitle(c.string("language"))),toggle("login",text("Launch at login","登录时启动"),c.boolean("launchAtLogin")),toggle("focus",text("Close when focus lost","失去焦点时关闭"),c.boolean("closeOnFocusLost")),row("screen",text("Display","显示器"),Kind::choice,displayTitle),toggle("batteryEnabled",text("Battery alerts","电池提醒"),c.boolean("batteryAlertsEnabled")),row("restore",text("Restore default settings","恢复默认设置"),Kind::choice,"↺")};
    }
    if(module_==core::Module::display){
        if(page_==SettingsPage::logos){for(auto id:logos){auto title=id=="custom"?text("Custom","自定"):std::string(id);for(const auto&icon:icons_)if(icon.id==id){title=icon.title;break;}out.push_back(selection("logo:"+std::string(id),title,c.string("centerLogo")==id));}return out;}
        if(page_==SettingsPage::metrics){for(auto id:metrics)out.push_back(selection("metric:"+std::string(id),metricTitle(id),c.string("alertMetric")==id));return out;}
        if(page_==SettingsPage::icons){for(std::size_t n=0;n<icons_.size();n+=4){auto r=row("icons:"+std::to_string(n),{},Kind::icons,c.string("applicationIcon"),78);r.icons.assign(icons_.begin()+static_cast<std::ptrdiff_t>(n),icons_.begin()+static_cast<std::ptrdiff_t>(std::min(n+4,icons_.size())));out.push_back(std::move(r));}return out;}
        if(page_==SettingsPage::battery)return{row("metric",text("Reading","显示数据"),Kind::choice,metricTitle(c.string("alertMetric"))),row("method",text("Display method","显示方式"),Kind::choice,c.string("displayMode")=="always"?text("Always","始终显示"):text("Power changes","充电状态变化")),slider("duration",text("Display duration","显示时长"),c.number("displayDuration"),1,60),row("placement",text("Display position","显示位置"),Kind::choice,c.string("placement")=="topCenter"?text("Top center","顶部居中"):text("Custom","自定")),row("editPosition",text("Edit position","编辑位置"),Kind::choice,"↗"),slider("batterySize",text("Size","大小"),c.number("scale"),.65,1.6)};
        const auto clock=c.string("clockStyle");const auto found=std::find(clocks.begin(),clocks.end(),clock);const auto clockNumber=found==clocks.end()?0:found-clocks.begin();const auto theme=c.string("theme");
        out={slider("uiScale",text("UI scale","界面缩放"),stagedScale_.value_or(c.number("hudScale")),.2,2),slider("positionX",text("HUD position X","界面位置 X"),stagedPosition_?(*stagedPosition_)[0]:c.number("hudOffsetX"),-.5,.5),slider("positionY",text("HUD position Y","界面位置 Y"),stagedPosition_?(*stagedPosition_)[1]:c.number("hudOffsetY"),-.5,.5),slider("parallax",text("Parallax intensity","视差强度"),c.number("parallaxIntensity"),0,2),slider("perspective",text("Perspective intensity","透视强度"),c.number("perspectiveIntensity"),0,2),slider("darkness",text("Background brightness","背景亮度"),1-c.number("backgroundDarkness"),0,1),slider("blur",text("Blur amount","模糊程度"),c.number("blurAmount"),0,1),row("theme",text("Theme","主题"),Kind::choice,theme=="dark"?text("Dark","深色"):theme=="light"?text("Light","浅色"):text("System","跟随系统")),row("clockFormat",text("Time format","时间格式"),Kind::choice,c.string("clockFormat")=="twentyFourHour"?text("24-hour","24 小时制"):text("12-hour AM/PM","12 小时制 AM/PM")),row("clockStyle",text("Clock style","时钟样式"),Kind::choice,"0"+std::to_string(clockNumber+1)+" / 05"),row("centerLogo",text("Center logo","中心标志"),Kind::choice,"›"),row("appIcon",text("App / menu bar icon","应用 / 菜单栏图标"),Kind::choice,"›"),row("palette",text("Theme color","主题颜色"),Kind::palette,c.string("accentHex"),54),row("battery",text("Battery alert","电池提醒"),Kind::choice,"›"),toggle("ambient",text("Ambient animation","持续环境动画"),c.boolean("ambientAnimation")),toggle("motion",text("Reduce Motion","减少动态效果"),c.boolean("reduceMotion")),toggle("lowPower",text("Low Power visual mode","低功耗视觉模式"),c.boolean("lowPowerVisualMode"))};return out;
    }
    if(module_==core::Module::hotkeys)return{row("capture",text("Summon HUD","呼出界面"),Kind::choice,controller_->capturingShortcut()?text("Press shortcut…","请按快捷键…"):settingsShortcutTitle(settingsShortcut(c)),54),row("keyReset",text("Restore default hotkey","恢复默认快捷键"),Kind::choice,settingsShortcutTitle({}))};
    const auto&updates=controller_->updateStatus();out={row("app",about_.name,Kind::info,about_.version,46),row("updates",text("Check for updates","检查更新"),Kind::choice,updates.title.empty()?text("Not checked yet","尚未检查"):updates.title),row("latestRelease",text("Latest GitHub release","GitHub 最新版本"),Kind::link,updates.latestVersion.empty()?"—":updates.latestVersion),toggle("automaticUpdates",text("Install updates automatically","自动安装更新"),updates.automaticallyInstalls),row("author",text("Author","作者"),Kind::info,about_.author),row("github","GitHub",Kind::link,about_.repository.empty()?text("Not configured","尚未设置"):"↗"),row("license",text("License","许可证"),Kind::info,about_.license),row("credits","Credits:",Kind::heading,{},30)};out[1].available=updates.canCheck;out[2].url=updates.releaseURL;out[3].available=updates.canSetAutomatic;out[5].url=about_.repository;
    auto credits=about_.credits;if(credits.empty())credits={{"Arknights: Endfield",text("Unofficial fan project","非官方同人项目"),{}},{"llynxxx",text("Inspiration","灵感来源"),"https://www.bilibili.com/video/BV1DBaP6yEHs/"},{"QinAnze / 氰氨锗",text("Inspiration","灵感来源"),"https://github.com/QinAnze/zmd-charge"},{"Ronit Singh · FineTune",text("Audio architecture reference","音频架构参考"),"https://github.com/ronitsingh10/FineTune"}};
    for(std::size_t n=0;n<credits.size();++n){auto r=row("credit:"+std::to_string(n),credits[n].name,Kind::link,credits[n].role,48);r.url=credits[n].url;out.push_back(std::move(r));}return out;
}
void SettingsPresentation::rebuild(){
    SettingsPageView next;next.page=page_;next.rows=rows();for(auto&r:next.rows)if(r.kind==Kind::slider)r.value=formatted(r.number,r.id,controller_->language());for(const auto&r:next.rows)next.maximumScroll+=r.height;next.maximumScroll=std::max(0.,next.maximumScroll-viewport().height);scroll_=std::min(scroll_,next.maximumScroll);next.scroll=scroll_;next.restore=restore_;next.capturing=module_==core::Module::hotkeys&&controller_->capturingShortcut();
    next.heading=page_==SettingsPage::battery||page_==SettingsPage::metrics?text("Battery alert","电池提醒"):page_==SettingsPage::logos?text("Center logo","中心标志"):page_==SettingsPage::icons?text("App / menu bar icon","应用 / 菜单栏图标"):page_==SettingsPage::screens?text("Display","显示器"):page_==SettingsPage::languages?text("Language","语言"):module_==core::Module::system?text("System","系统"):module_==core::Module::display?text("Display","显示"):module_==core::Module::hotkeys?text("Hotkeys","快捷键"):text("About","关于");
    next.back=text("‹ Back","‹ 返回");next.cancel=text("Cancel","取消");next.restoreTitle=text("Restore all preferences?","恢复所有设置？");next.restoreMessage=text("Notes, files and shortcuts are kept.","保留便笺、文件与应用快捷方式。");next.restoreAccept=text("Restore","恢复");next.status=!localStatus_.empty()?localStatus_:module_==core::Module::about?controller_->updateStatus().detail:!controller_->shortcutStatus().empty()?controller_->shortcutStatus():controller_->status();next.accessibilityStatus=next.status;if(next.status.empty()&&module_==core::Module::system)next.status=controller_->loginStatus();if(next.status.empty()&&next.capturing)next.status=text("Press up to 3 keys · Esc to cancel","最多同时按 3 个键 · Esc 取消");
    if(restore_)next.actions={{"restore:cancel",text("Cancel restore","取消恢复"),{46,197,144,32},true},{"restore:confirm",text("Restore defaults","恢复默认设置"),{206,197,144,32},true}};
    else{
        if(page_!=SettingsPage::main)next.actions.push_back({"back",text("Back","返回"),{323,2,65,25},true});double y=40-scroll_;
        for(const auto&r:next.rows){const Rect rect{16,y,366,r.height-2};y+=r.height;const auto visible=intersection(rect,viewport());if(visible.height<std::min(25.,rect.height)||visible.width<=0)continue;
            if(r.kind==Kind::slider){const Rect sliderRect{192,rect.y+8,184,25};if(contains(viewport(),sliderRect))next.sliders.push_back({r.id,r.title,formatted(r.number,r.id,controller_->language()),sliderRect,r.number,r.minimum,r.maximum});}
            else if(r.kind==Kind::toggle)next.actions.push_back({r.id,r.title+", "+(r.selected?text("On","开"):text("Off","关")),visible,r.available});
            else if(r.kind==Kind::choice)next.actions.push_back({r.id,r.title+", "+r.value,visible,r.available});
            else if(r.kind==Kind::selection){auto label=r.title;if(!r.detail.empty())label+=", "+r.detail;if(r.selected)label+=", "+text("Selected","已选择");next.actions.push_back({r.id,label,visible,r.available});}
            else if(r.kind==Kind::link&&!r.url.empty())next.actions.push_back({r.id,r.title+", "+r.value,visible,true});
            else if(r.kind==Kind::icons){for(std::size_t n=0;n<r.icons.size();++n){const auto bounds=iconRect(n,rect);if(contains(viewport(),bounds))next.actions.push_back({"appIcon:"+r.icons[n].id,r.icons[n].title,bounds,true});}}
            else if(r.kind==Kind::palette){for(std::size_t n=0;n<accents.size();++n){const auto bounds=paletteRect(n,rect);if(contains(viewport(),bounds))next.actions.push_back({"accent:"+std::string(accents[n]),text("Theme color","主题颜色")+" #"+std::string(accents[n]),bounds,true});}const auto custom=paletteRect(5,rect);if(contains(viewport(),custom))next.actions.push_back({"customColor",text("Custom color wheel","自定义色轮"),custom,true});}
        }
        if(next.capturing)next.actions.push_back({"capture:cancel",text("Cancel shortcut recording","取消快捷键录制"),{297,296,90,27},true});
    }
    view_=std::move(next);dirty_=false;seenController_=controller_->revision();++revision_;
}
void SettingsPresentation::settle(){if(outgoing_){outgoing_.reset();++revision_;}rowAction_.clear();}
void SettingsPresentation::activate(double now){finite(now);active_=true;refresh(now);}
void SettingsPresentation::deactivate(double now){finite(now);active_=false;dragged_.reset();stagedScale_.reset();stagedPosition_.reset();if(module_==core::Module::hotkeys)controller_->endShortcutCapture();settle();restore_=false;localStatus_.clear();dirty_=true;}
void SettingsPresentation::setReduceMotion(bool value,double now){finite(now);if(reduced_==value)return;reduced_=value;if(value)settle();}
bool SettingsPresentation::refresh(double now){finite(now);if(outgoing_&&(reduced_||now>=pageStart_+.26))settle();if(!dirty_&&seenController_==controller_->revision())return false;rowAction_.clear();rebuild();return true;}
void SettingsPresentation::reveal(int direction,double now,const std::function<void()>&change){finite(now);settle();auto previous=view_;change();dirty_=true;rebuild();if(active_&&!reduced_){outgoing_=std::move(previous);pageStart_=now;direction_=direction<0?-1:1;}}
void SettingsPresentation::changePage(SettingsPage page,int direction,double now){reveal(direction,now,[&]{page_=page;scroll_=0;});}
SettingsPagePose SettingsPresentation::pagePose(double now)const{finite(now);if(!outgoing_||now>=pageStart_+.26)return{};const auto p=core::CubicTiming{.2,.7,.3,1}.value((now-pageStart_)/.26);return{18*direction_*(1-p),-18*direction_*p,direction_>0?Rect{400*(1-p),0,400*p,334}:Rect{0,0,400*p,334},direction_>0?Rect{0,0,400*(1-p),334}:Rect{400*p,0,400*(1-p),334},true};}
SettingsRowPose SettingsPresentation::rowPose(std::string_view id,double now)const{finite(now);if(!active_||reduced_||rowAction_!=id||now>=rowStart_+.16)return{};const auto t=std::clamp((now-rowStart_)/.16,0.,1.);return{3*(1-core::CubicTiming{0,0,.58,1}.value(t)),.68+.32*t};}
bool SettingsPresentation::requiresFrames(double now)const{finite(now);return active_&&!reduced_&&((outgoing_&&now<pageStart_+.26)||(!rowAction_.empty()&&now<rowStart_+.16));}
void SettingsPresentation::animateRow(std::string_view id,double now){finite(now);if(!active_||reduced_)return;rowAction_=id;rowStart_=now;if(id.starts_with("appIcon:")){const auto selected=controller_->configuration().string("applicationIcon");const auto found=std::find_if(icons_.begin(),icons_.end(),[&](const auto&i){return i.id==selected;});rowAction_="icons:"+std::to_string((found==icons_.end()?0:static_cast<std::size_t>(found-icons_.begin())/4)*4);}else if(id.starts_with("accent:")||id=="customColor")rowAction_="palette";else if(id=="capture:cancel")rowAction_="capture";}
std::optional<std::string_view>SettingsPresentation::actionAt(Point point)const{for(const auto&a:view_.actions)if(a.enabled&&contains(a.rect,point))return a.id;return {};}
bool SettingsPresentation::mouseDown(Point point,double now){finite(now);if(!contains(bounds(),point))return false;for(const auto&s:view_.sliders)if(contains(s.rect,point)){dragged_=selectedSlider_=s.id;moveSlider(point,now);return true;}if(const auto id=actionAt(point))perform(*id,now);return true;}
void SettingsPresentation::mouseDragged(Point point,double now){if(dragged_)moveSlider(point,now);}
void SettingsPresentation::mouseUp(double now){finite(now);const auto scale=stagedScale_;const auto position=stagedPosition_;const auto id=dragged_;dragged_.reset();stagedScale_.reset();stagedPosition_.reset();if(scale){controller_->previewScale(*scale,now);refresh(now);animateRow("uiScale",now);}if(position){controller_->previewPosition((*position)[0],(*position)[1],now);refresh(now);animateRow(id.value_or("positionX"),now);}}
void SettingsPresentation::moveSlider(Point point,double now){finite(now);if(!std::isfinite(point.x)||!dragged_)return;for(const auto&s:view_.sliders)if(s.id==*dragged_){const auto fraction=std::clamp((point.x-s.rect.x-6)/(s.rect.width-12),0.,1.);setSlider(s.id,s.minimum+fraction*(s.maximum-s.minimum),now);return;}}
bool SettingsPresentation::setSlider(std::string_view key,double value,double now){finite(now);if(!std::isfinite(value))return false;const auto found=std::find_if(view_.sliders.begin(),view_.sliders.end(),[&](const auto&s){return s.id==key;});if(found==view_.sliders.end())return false;const auto id=found->id;value=std::clamp(value,found->minimum,found->maximum);selectedSlider_=id;auto config=controller_->configuration();
    if(id=="uiScale"){value=std::round(value*20)/20;if(dragged_==id){stagedScale_=value;dirty_=true;}else controller_->previewScale(value,now);}
    else if(id=="positionX"||id=="positionY"){value=std::round(value*100)/100;auto p=stagedPosition_.value_or(std::array{config.number("hudOffsetX"),config.number("hudOffsetY")});p[id=="positionX"?0:1]=value;if(dragged_==id){stagedPosition_=p;dirty_=true;}else controller_->previewPosition(p[0],p[1],now);}
    else{const auto field=id=="parallax"?"parallaxIntensity":id=="perspective"?"perspectiveIntensity":id=="darkness"?"backgroundDarkness":id=="blur"?"blurAmount":id=="duration"?"displayDuration":"scale";config.set(field,id=="darkness"?1-value:id=="duration"?std::round(value):value);controller_->update(std::move(config),now);}refresh(now);if(!dragged_)animateRow(id,now);return true;}
void SettingsPresentation::nudgeSlider(double direction,double now){finite(direction);finite(now);if(!selectedSlider_)return;for(const auto&s:view_.sliders)if(s.id==*selectedSlider_){const auto step=s.id=="duration"?1:s.id=="uiScale"?.05:s.id.starts_with("position")?.01:(s.maximum-s.minimum)*.02;setSlider(s.id,s.value+step*direction,now);return;}}
bool SettingsPresentation::scroll(Point point,double delta,double now){finite(now);if(!contains(viewport(),point)||!std::isfinite(delta)||restore_||view_.capturing)return false;const auto next=std::clamp(scroll_+delta,0.,view_.maximumScroll);if(next!=scroll_){mouseUp(now);scroll_=next;dirty_=true;refresh(now);}return true;}
bool SettingsPresentation::perform(std::string_view action,double now){finite(now);const auto found=std::find_if(view_.actions.begin(),view_.actions.end(),[&](const auto&a){return a.id==action&&a.enabled;});if(found==view_.actions.end())return false;const std::string id(action);localStatus_.clear();auto config=controller_->configuration();
    if(id=="back"){reveal(-1,now,[&]{if(page_==SettingsPage::metrics){page_=SettingsPage::battery;scroll_=0;}else{page_=SettingsPage::main;scroll_=mainScroll_;}});return true;}
    if(id=="language"||id=="screen"||id=="appIcon"||id=="battery"||id=="centerLogo"||id=="metric"){if(id!="metric")mainScroll_=scroll_;if(id=="screen"&&hooks_.displays)displays_=hooks_.displays();changePage(id=="language"?SettingsPage::languages:id=="screen"?SettingsPage::screens:id=="appIcon"?SettingsPage::icons:id=="battery"?SettingsPage::battery:id=="centerLogo"?SettingsPage::logos:SettingsPage::metrics,1,now);return true;}
    if(id=="restore"||id=="restore:cancel"||id=="restore:confirm"){reveal(id=="restore"?1:-1,now,[&]{restore_=id=="restore";if(id=="restore:confirm")controller_->restoreDefaults();});return true;}
    if(id=="customColor"){if(hooks_.chooseColor)hooks_.chooseColor();}
    else if(id=="logo:custom"){if(hooks_.chooseLogo)hooks_.chooseLogo();return true;}
    else if(id=="capture"||id=="capture:cancel"){if(controller_->capturingShortcut())controller_->endShortcutCapture();else controller_->beginShortcutCapture();}
    else if(id=="keyReset")controller_->setShortcut({});else if(id=="editPosition")controller_->editBatteryPosition();else if(id=="updates")controller_->checkUpdates();else if(id=="automaticUpdates")controller_->toggleAutomaticUpdates();
    else if(id.starts_with("language:")){reveal(-1,now,[&]{page_=SettingsPage::main;scroll_=mainScroll_;config.set("language",id.substr(9));controller_->update(config,now);});return true;}
    else if(id.starts_with("screen:")){const auto value=id.substr(7);reveal(-1,now,[&]{page_=SettingsPage::main;scroll_=mainScroll_;if(value=="pointer"||value=="main"){config.set("windowsDisplayID",nullptr);config.set("windowsDisplayName",nullptr);}else{const auto d=std::find_if(displays_.begin(),displays_.end(),[&](const auto&v){return v.id==value;});need(d!=displays_.end(),"Missing selected display");config.set("windowsDisplayID",d->id);config.set("windowsDisplayName",d->name);}config.set("openOnActiveDisplay",value!="main");controller_->update(config,now);});return true;}
    else if(id.starts_with("metric:")){reveal(-1,now,[&]{config.set("alertMetric",id.substr(7));controller_->update(config,now);page_=SettingsPage::battery;scroll_=0;});return true;}
    else if(id=="github"||id=="latestRelease"||id.starts_with("credit:")){for(const auto&r:view_.rows)if(r.id==id&&!r.url.empty()){controller_->openLink(r.url);break;}}
    else{if(id.starts_with("appIcon:"))config.set("applicationIcon",id.substr(8));else if(id.starts_with("accent:"))config.set("accentHex",id.substr(7));else if(id.starts_with("logo:")){if(hooks_.logoSelection)hooks_.logoSelection();config.set("centerLogo",id.substr(5));}else if(id=="theme"){constexpr std::array<std::string_view,3>values{"dark","light","system"};config.set("theme",cycle(config.string("theme"),values));}else if(id=="clockFormat"){constexpr std::array<std::string_view,2>values{"twentyFourHour","twelveHour"};config.set("clockFormat",cycle(config.string("clockFormat"),values));}else if(id=="clockStyle")config.set("clockStyle",cycle(config.string("clockStyle"),clocks));else if(id=="method"){constexpr std::array<std::string_view,2>values{"whenChargingStarts","always"};config.set("displayMode",cycle(config.string("displayMode"),values));}else if(id=="placement"){constexpr std::array<std::string_view,2>values{"topCenter","custom"};config.set("placement",cycle(config.string("placement"),values));}else{const auto field=id=="login"?"launchAtLogin":id=="focus"?"closeOnFocusLost":id=="ambient"?"ambientAnimation":id=="batteryEnabled"?"batteryAlertsEnabled":id=="motion"?"reduceMotion":id=="lowPower"?"lowPowerVisualMode":nullptr;if(field)config.set(field,!config.boolean(field));}controller_->update(std::move(config),now);}
    dirty_=true;refresh(now);animateRow(id,now);return true;
}
bool SettingsPresentation::escape(double now){finite(now);if(view_.capturing){controller_->endShortcutCapture();refresh(now);animateRow("capture",now);return true;}if(restore_)return perform("restore:cancel",now);if(page_!=SettingsPage::main)return perform("back",now);return false;}
bool SettingsPresentation::capture(SettingsShortcut key,bool repeated,bool isEscape,double now){finite(now);if(!view_.capturing)return false;if(isEscape)return escape(now);if(repeated)return true;if(const auto error=controller_->setShortcut(key)){localStatus_=*error;dirty_=true;refresh(now);animateRow("capture",now);return true;}controller_->endShortcutCapture();refresh(now);animateRow("capture",now);return true;}
void SettingsPresentation::setCustomColor(std::array<double,3>color,double now){constexpr char digits[]="0123456789ABCDEF";std::string hex;hex.reserve(6);for(double c:color){need(std::isfinite(c)&&c>=0&&c<=1,"Invalid source color picker result");const auto value=static_cast<unsigned>(std::round(c*255));hex+=digits[value>>4];hex+=digits[value&15];}auto config=controller_->configuration();config.set("accentHex",hex);controller_->update(std::move(config),now);refresh(now);animateRow("palette",now);}
void SettingsPresentation::setCustomLogo(std::string revision,double now){need(ehud::data::validUUID(revision),"Invalid explicit logo import revision");auto config=controller_->configuration();config.set("centerLogo","custom");config.set("centerLogoRevision",std::move(revision));controller_->update(std::move(config),now);refresh(now);animateRow("logo:custom",now);}
void SettingsPresentation::showImportError(std::string error,double now){need(error.size()<=16*1024&&Json::validUtf8(error),"Invalid Settings import error");localStatus_=std::move(error);dirty_=true;refresh(now);}
void SettingsPresentation::showBatterySettings(double now){if(module_!=core::Module::display)return;if(page_==SettingsPage::main)mainScroll_=scroll_;settle();page_=SettingsPage::battery;scroll_=0;localStatus_.clear();dirty_=true;refresh(now);}
}
namespace endfield::modules { namespace {
using Color=std::array<double,4>;
Color gray(double v,double a=1){return{v,v,v,a};}Color alpha(Color c,double a){c[3]=a;return c;}Json color(Color c){return Json::Object{{"sRGB",Json::Array{c[0],c[1],c[2],c[3]}}};}Json box(Rect r){return Json::Array{r.x,r.y,r.width,r.height};}
Json layer(std::string id,Rect r,const char*kind="layer"){return Json::Object{{"id",std::move(id)},{"kind",kind},{"bounds",box({0,0,r.width,r.height})},{"position",Json::Array{r.x,r.y}},{"anchorPoint",Json::Array{0,0}},{"children",Json::Array{}}};}
Json command(const char*op,std::initializer_list<Point>points={}){Json::Array p;for(auto v:points)p.push_back(Json::Array{v.x,v.y});return Json::Object{{"op",op},{"points",std::move(p)}};}
Json::Array cut(Rect r,double corner){return{command("move",{{r.x+corner,r.y}}),command("line",{{r.x+r.width,r.y}}),command("line",{{r.x+r.width,r.y+r.height-corner}}),command("line",{{r.x+r.width-corner,r.y+r.height}}),command("line",{{r.x,r.y+r.height}}),command("line",{{r.x,r.y+corner}}),command("close")};}
Json shape(std::string id,Rect r,double corner,std::optional<Color>fill={},std::optional<Color>stroke={},double width=1){auto n=layer(std::move(id),r,"shape");n["shape"]=Json::Object{{"path",cut({0,0,r.width,r.height},corner)},{"fillColor",fill?color(*fill):Json{}},{"strokeColor",stroke?color(*stroke):Json{}},{"lineWidth",width},{"lineCap","butt"},{"lineJoin","miter"},{"miterLimit",10},{"fillRule","non-zero"}};return n;}
Json solid(std::string id,Rect r,Color c){auto n=layer(std::move(id),r);n["backgroundColor"]=color(c);return n;}
Json label(std::string id,Rect r,std::string value,double size,Color c,double scale,const char*weight="regular",const char*alignment="left",bool wrapped=false){need(value.size()<=16384&&Json::validUtf8(value),"Invalid bounded Settings label");auto n=layer(std::move(id),r,"text");n["contentsScale"]=std::min(4.,std::ceil(std::clamp(scale,1.,4.)*1.35));const auto w=std::string_view(weight);n["text"]=Json::Object{{"string",std::move(value)},{"fontSize",size},{"font",Json::Object{{"postScriptName",w=="semibold"?".AppleSystemUIFontDemi":w=="medium"?".AppleSystemUIFontMedium":".AppleSystemUIFont"},{"familyName",".AppleSystemUIFont"},{"pointSize",size},{"symbolicTraits",w=="semibold"?2:0}}},{"foregroundColor",color(c)},{"alignment",alignment},{"wrapped",wrapped},{"truncation",wrapped?"none":"end"}};return n;}
Rect inset(Rect r,double x,double y){return{r.x+x,r.y+y,r.width-2*x,r.height-2*y};}
struct SettingsBuild {SettingsArtworkPart part;Json::Array children;
 void add(Json node,std::string action={},bool tint=false,bool rim=false,float opacity=1){const auto&p=node["position"].array();part.surfaces.push_back({node["id"].string(),std::move(action),core::Matrix4::translation(p[0].number(),p[1].number()),tint,rim,opacity});children.push_back(std::move(node));}
 void feedback(std::string id,Rect r,Color accent){add(shape(id+"/tint",r,4,alpha(accent,.30)),id,true,false,0);add(shape(id+"/rim",inset(r,-2,-2),4,{},accent,.9),id,false,true,.28f);}
 void button(std::string id,std::string text,Rect r,bool selected,Color accent,Color primary,Color muted,double scale){add(shape(id+"/plate",r,3,alpha(selected?accent:muted,selected?.22:.12),alpha(selected?accent:muted,selected?1:.48),.7));feedback(id,r,accent);add(label(id+"/label",{r.x+6,r.y+r.height*.5-7,r.width-12,18},std::move(text),10.5,selected?accent:primary,scale,"medium","center"));}
 SettingsArtworkPart finish(std::string row={}){part.row=std::move(row);part.layers=layer("settings.part",{});part.layers["allowsGroupOpacity"]=false;part.layers["children"]=std::move(children);return std::move(part);}
};
}
SettingsArtwork prepareSettingsArtwork(const SettingsPageView&view,const SettingsAppearance&a){need(std::isfinite(a.scale)&&a.scale>=1&&a.scale<=8,"Invalid Settings scale");for(double c:a.accent)need(std::isfinite(c)&&c>=0&&c<=1,"Invalid Settings accent");need(view.rows.size()<=256&&std::isfinite(view.scroll)&&view.scroll>=0&&std::isfinite(view.maximumScroll)&&view.maximumScroll>=view.scroll,"Invalid Settings page model");const auto primary=gray(a.dark?.94:.12),muted=gray(a.dark?.64:.40);SettingsArtwork out;SettingsBuild chrome;
 chrome.add(label("settings.heading",{12,1,306,23},view.heading,16,primary,a.scale,"semibold"));chrome.add(solid("settings.headerLine",{12,29,376,1},alpha(a.accent,.5)));if(view.page!=SettingsPage::main)chrome.button("back",view.back,{323,2,65,25},false,a.accent,primary,muted,a.scale);
 if(view.restore){SettingsBuild content;content.add(label("settings.restore.title",{35,114,330,25},view.restoreTitle,17,primary,a.scale,"medium","center"));content.add(label("settings.restore.message",{35,151,330,34},view.restoreMessage,11,muted,a.scale,"regular","center"));content.button("restore:cancel",view.cancel,{46,197,144,32},false,a.accent,primary,muted,a.scale);content.button("restore:confirm",view.restoreAccept,{206,197,144,32},true,a.accent,primary,muted,a.scale);out.rows.push_back(content.finish());out.chrome=chrome.finish();return out;}
 double y=40-view.scroll;for(const auto&r:view.rows){need(std::isfinite(r.height)&&r.height>=2&&r.height<=512,"Invalid Settings row height");const Rect rect{16,y,366,r.height-2};y+=r.height;if(intersection(rect,SettingsPresentation::viewport()).height<=0)continue;SettingsBuild b;const std::string id="settings.row."+r.id;b.add(solid(id+"/divider",{rect.x,rect.y+rect.height-1,rect.width,.5},alpha(muted,.19)));
  if(r.kind!=Kind::selection)b.add(label(id+"/title",{20,rect.y+(r.height>45?8:11),175,18},r.title,11.5,r.id=="credits"?a.accent:primary,a.scale,r.id=="credits"?"semibold":"medium"));
  switch(r.kind){case Kind::selection:{b.add(shape(id+"/plate",inset(rect,1,3),3,alpha(r.selected?a.accent:muted,r.selected?.13:.07),alpha(r.selected?a.accent:muted,r.selected?.7:.2),.7));if(r.available)b.feedback(r.id,inset(rect,1,3),a.accent);b.add(label(id+"/title",{26,rect.y+(r.detail.empty()?11:7),305,18},r.title,11.5,r.available?primary:muted,a.scale,"medium"));if(!r.detail.empty())b.add(label(id+"/detail",{26,rect.y+27,305,13},r.detail,8.5,muted,a.scale));if(r.selected)b.add(label(id+"/selected",{346,rect.y+rect.height*.5-9,24,18},"✓",12,a.accent,a.scale,"semibold"));break;}
   case Kind::toggle:b.add(shape(id+"/track",{324,rect.y+10,50,20},3,alpha(r.selected?a.accent:muted,r.selected?.24:.12),r.selected?a.accent:alpha(muted,.5),.7));b.feedback(r.id,{321,rect.y+7,56,26},a.accent);b.add(solid(id+"/marker",{r.selected?350.:328.,rect.y+14,20,12},r.selected?a.accent:muted));b.add(label(id+"/value",{270,rect.y+13,42,15},r.selected?"ON":"OFF",9,r.selected?a.accent:muted,a.scale,"regular","right"));break;
   case Kind::choice:b.button(r.id,r.value,{196,rect.y+6,179,r.height>45?34.:27.},r.id=="capture"&&view.capturing,a.accent,primary,muted,a.scale);break;
   case Kind::slider:{need(std::isfinite(r.number)&&std::isfinite(r.minimum)&&std::isfinite(r.maximum)&&r.maximum>r.minimum,"Invalid Settings slider");std::string value;for(const auto&s:view.sliders)if(s.id==r.id)value=s.formatted;if(value.empty())value=r.value;need(!value.empty(),"Settings slider requires preformatted caller value");b.add(label(id+"/value",{20,rect.y+26,167,13},value,8.5,muted,a.scale));const auto fraction=std::clamp((r.number-r.minimum)/(r.maximum-r.minimum),0.,1.);b.add(solid(id+"/track",{198,rect.y+20.5,172,2},alpha(muted,.3)));b.add(solid(id+"/fill",{198,rect.y+20.5,172*fraction,2},a.accent));b.add(shape(id+"/handle",{194+172*fraction,rect.y+14.5,8,14},2,a.accent));break;}
   case Kind::icons:{need(r.icons.size()<=4,"Source icon row holds four icons");for(std::size_t n=0;n<r.icons.size();++n){const auto&i=r.icons[n];const std::string key="appIcon:"+i.id;const auto box=iconRect(n,rect);const bool selected=r.value==i.id;b.add(shape(key+"/plate",inset(box,2,2),4,alpha(selected?a.accent:muted,selected?.16:.09)));b.add(shape(key+"/frame",box,5,{},selected?a.accent:alpha(muted,.42),.8));b.feedback(key,box,a.accent);auto glyph=layer(key+"/image",{box.x+box.width*.5-26,box.y+box.height*.5-26,52,52});glyph["contentsGravity"]="resizeAspect";glyph["requiredSourceImage"]=i.id;out.icons.push_back({i.id,glyph["id"].string()});b.add(std::move(glyph));}break;}
   case Kind::palette:{for(std::size_t n=0;n<accents.size();++n){const auto hex=accents[n];const auto byte=[&](unsigned at){unsigned value{};const auto parsed=std::from_chars(hex.data()+at,hex.data()+at+2,value,16);need(parsed.ec==std::errc(),"Invalid original palette");return double(value)/255;};const auto box=paletteRect(n,rect);const auto key="accent:"+std::string(hex);b.add(shape(key+"/swatch",inset(box,2,2),3,Color{byte(0),byte(2),byte(4),1}));b.feedback(key,box,a.accent);if(r.value==hex)b.add(shape(key+"/selected",box,4,{},primary,1));}b.button("customColor","◉",paletteRect(5,rect),false,a.accent,primary,muted,a.scale);break;}
   case Kind::info:case Kind::link:if(r.kind==Kind::link&&!r.url.empty())b.feedback(r.id,inset(rect,0,2),a.accent);b.add(label(id+"/value",{201,rect.y+10,175,r.height-13},r.value,10,muted,a.scale,"regular","right",true));break;
   case Kind::heading:break;
  }out.rows.push_back(b.finish(r.id));
 }
 if(view.maximumScroll>0){const auto height=std::max(22.,250.*250/(view.maximumScroll+250));chrome.add(solid("settings.scrollThumb",{387,40+(250-height)*view.scroll/view.maximumScroll,1.5,height},alpha(muted,.55)));}chrome.add(label("settings.status",{14,299,view.capturing?276.:372.,31},view.status,9.5,muted,a.scale,"regular","left",true));if(view.capturing)chrome.button("capture:cancel",view.cancel,{297,296,90,27},false,a.accent,primary,muted,a.scale);out.chrome=chrome.finish();return out;
}
}
