#include "modules/storage_presentation.hpp"
#include <algorithm>
#include <charconv>
#include <cmath>
#include <numbers>
#include <stdexcept>
namespace endfield::modules {
namespace {
using J=ehud::data::Json;using Color=std::array<double,4>;using Rect=core::Rect;using Point=core::Point;
void need(bool b,const char*m){if(!b)throw std::invalid_argument(m);}Color gray(double v,double a=1){return{v,v,v,a};}
std::string fixed(double v,int precision){std::array<char,128>text{};const auto r=std::to_chars(text.data(),text.data()+text.size(),v,std::chars_format::fixed,precision);need(r.ec==std::errc{},"Storage numeric label overflow");return {text.data(),r.ptr};}
void valid(const StorageSnapshot&s){if(s.capacity){const auto&v=*s.capacity;need(v.totalBytes>0&&v.availableBytes>=0&&v.availableBytes<=v.totalBytes&&std::isfinite(v.updatedAt),"Invalid display capacity");need(v.volumeName.size()<=4096&&J::validUtf8(v.volumeName),"Invalid storage volume label");}if(s.error)need(s.error->size()<=4096&&J::validUtf8(*s.error),"Invalid storage error label");}
void valid(const StorageAppearance&a){need(std::isfinite(a.scale)&&a.scale>=1&&a.scale<=8,"Invalid Storage content scale");for(auto v:a.accent)need(std::isfinite(v)&&v>=0&&v<=1,"Invalid Storage accent");if(a.availableColor)for(auto v:*a.availableColor)need(std::isfinite(v)&&v>=0&&v<=1,"Invalid Storage available color");}
J color(Color c){return J::Object{{"sRGB",J::Array{c[0],c[1],c[2],c[3]}}};}J rect(Rect r){return J::Array{r.x,r.y,r.width,r.height};}
J layer(std::string id,Rect r,const char*kind="layer"){return J::Object{{"id",std::move(id)},{"kind",kind},{"bounds",rect({0,0,r.width,r.height})},{"position",J::Array{r.x,r.y}},{"anchorPoint",J::Array{0,0}},{"children",J::Array{}}};}
J label(std::string id,Rect r,std::string value,double size,Color ink,const char*weight="Regular",const char*alignment="left"){auto out=layer(std::move(id),r,"text");out["text"]=J::Object{{"string",std::move(value)},{"fontSize",size},{"font",J::Object{{"postScriptName",std::string(".AppleSystemUIFont")+(std::string_view(weight)=="Semibold"?"Demi":std::string_view(weight)=="Regular"?"":weight)},{"familyName",".AppleSystemUIFont"},{"pointSize",size},{"symbolicTraits",std::string_view(weight)=="Semibold"?2:0}}},{"foregroundColor",color(ink)},{"alignment",alignment},{"wrapped",false},{"truncation","end"}};return out;}
J command(const char*op,std::initializer_list<Point>points={}){J::Array values;for(auto p:points)values.push_back(J::Array{p.x,p.y});return J::Object{{"op",op},{"points",std::move(values)}};}
J::Array rectanglePath(Rect r){return {command("move",{{r.x,r.y}}),command("line",{{r.x+r.width,r.y}}),command("line",{{r.x+r.width,r.y+r.height}}),command("line",{{r.x,r.y+r.height}}),command("close")};}
J shape(std::string id,Rect r,J path,std::optional<Color>fill,std::optional<Color>stroke={},double width=1){auto out=layer(std::move(id),r,"shape");out["shape"]=J::Object{{"path",std::move(path)},{"fillColor",fill?color(*fill):J{}},{"strokeColor",stroke?color(*stroke):J{}},{"lineWidth",width},{"lineCap","butt"},{"lineJoin","miter"},{"miterLimit",10},{"fillRule","non-zero"}};return out;}

}
std::string storageBytes(std::optional<double>bytes){if(!bytes||!std::isfinite(*bytes)||*bytes<0)return "—";constexpr std::array units{"B","KB","MB","GB","TB","PB"};auto value=*bytes;std::size_t index{};while(value>=1000&&index+1<units.size()){value/=1000;++index;}return fixed(value,value>=100||index==0?0:1)+" "+units[index];}
std::array<Rect,32>storageMeter(double fraction)noexcept{std::array<Rect,32>result{};const double width=(376.-3.*31.)/32.,filled=std::clamp(fraction,0.,1.)*32;for(unsigned i=0;i<32;++i)result[i]={double(i)*(width+3),0,width*std::clamp(filled-i,0.,1.),17};return result;}
StoragePresentation::StoragePresentation(StorageSnapshot s,StorageAppearance a):snapshot_(std::move(s)),appearance_(a){valid(snapshot_);valid(appearance_);update();}
bool StoragePresentation::receive(StorageSnapshot s){valid(s);if(snapshot_==s)return false;const auto old=labels_;const bool wasLoading=snapshot_.isLoading;const auto oldCapacity=snapshot_.capacity;snapshot_=std::move(s);update();const bool meterChanged=oldCapacity.has_value()!=snapshot_.capacity.has_value()||(oldCapacity&&snapshot_.capacity&&(oldCapacity->totalBytes!=snapshot_.capacity->totalBytes||oldCapacity->availableBytes!=snapshot_.capacity->availableBytes));if(labels_==old&&wasLoading==snapshot_.isLoading&&!meterChanged)return false;++revision_;return true;}
bool StoragePresentation::setAppearance(StorageAppearance a){valid(a);if(a==appearance_)return false;appearance_=a;update();++revision_;return true;}
void StoragePresentation::update(){const auto l=appearance_.language;auto text=[&](std::string_view en,std::string_view zh){return core::localized(en,zh,l);};auto error=snapshot_.error;if(error=="Storage capacity is unavailable.")error=text("Storage capacity is unavailable.","无法读取存储容量。");else if(error=="The startup filesystem is unavailable.")error=text("The startup filesystem is unavailable.","启动文件系统不可用。");
    labels_.heading="// "+text("Storage","存储");labels_.caption=!snapshot_.isLoading&&error?*error:snapshot_.capacity?snapshot_.capacity->volumeName:text("Startup disk","启动磁盘");labels_.titles={text("Total","总计"),text("Used","已用"),text("Available","可用")};labels_.values={"—","—","—"};labels_.meter=text("Capacity unavailable","容量不可用");
    if(const auto&v=snapshot_.capacity){labels_.values={storageBytes(double(v->totalBytes)),storageBytes(double(v->usedBytes())),storageBytes(double(v->availableBytes))};labels_.meter=fixed(std::clamp(double(v->usedBytes())/double(v->totalBytes)*100.,0.,100.),1)+"%"+text(" used"," 已用");labels_.status=v->volumeName+"; "+text("Total ","总计 ")+labels_.values[0]+"; "+text("Used ","已用 ")+labels_.values[1]+"; "+text("Available ","可用 ")+labels_.values[2];if(snapshot_.isLoading)labels_.status+="; "+text("Refreshing","正在刷新");else if(error)labels_.status+="; "+*error;}
    else labels_.status=snapshot_.isLoading?text("Reading storage…","正在读取存储…"):error.value_or(text("Storage unavailable","存储不可用"));
    labels_.settings=text("Storage Settings","存储设置");labels_.refresh=text("Refresh storage","刷新存储");actions_={StorageAction{"storage:settings",labels_.settings,settingsRect()},StorageAction{"storage:refresh",labels_.refresh,refreshRect()}};}
std::optional<std::string_view>StoragePresentation::actionAt(Point p)const noexcept{if(!std::isfinite(p.x)||!std::isfinite(p.y))return{};for(const auto&a:actions())if(p.x>=a.rect.x&&p.x<a.rect.x+a.rect.width&&p.y>=a.rect.y&&p.y<a.rect.y+a.rect.height)return a.id;return{};}
StorageArtwork prepareStorageArtwork(const StoragePresentation&p,const StorageSourcePaths&paths){for(const auto*path:{&paths.refreshArrow,&paths.settingsFeedback,&paths.refreshFeedback})need(path->isArray()&&!path->array().empty()&&path->array().size()<=128,"Storage requires exact bounded source control paths");const auto&a=p.appearance();const auto&v=p.labels();const auto primary=gray(a.dark?.93:.12),muted=gray(a.dark?.65:.40),ink=gray(.13);need(a.availableColor.has_value()||a.accent==StorageAppearance{}.accent,"Custom Storage accent requires original blended available color");const Color cyan=a.availableColor.value_or(Color{.9886131882667542,.9012837409973145,.5504170060157776,1});StorageArtwork result;J::Array nodes;
    auto add=[&](J node,std::string action={},bool rim=false,bool rotates=false,float opacity=1){node["contentsScale"]=node["kind"].string()=="text"?std::min(4.,std::ceil(std::clamp(a.scale,1.,4.)*1.35)):std::clamp(a.scale,1.,4.);const auto&position=node["position"].array();result.surfaces.push_back({node["id"].string(),core::Matrix4::translation(position[0].number(),position[1].number()),std::move(action),rim,rotates,opacity});nodes.push_back(std::move(node));};
    add(label("storage.heading",{12,0,376,20},v.heading,15,primary,"Semibold"));add(label("storage.caption",{12,24,376,13},v.caption,9,muted));add(label("storage.meterCaption",{12,224,376,15},v.meter,10,muted));
    for(unsigned i=0;i<3;++i){const auto suffix=std::to_string(i);auto plate=layer("storage.metric."+suffix,{12,49+double(i)*47,376,40});plate["cornerRadius"]=3;plate["backgroundColor"]=color(gray(a.dark?.12:.19));plate["borderColor"]=color(gray(a.dark?.48:.30,.38));plate["borderWidth"]=.5;add(std::move(plate));add(label("storage.metricTitle."+suffix,{22,62+double(i)*47,116,15},v.titles[i],11,gray(.94),"Medium"));add(label("storage.metricValue."+suffix,{145,58+double(i)*47,231,25},v.values[i],18,i==0?gray(.94):i==1?a.accent:cyan,"Medium","right"));}
    for(unsigned i=0;i<2;++i){J::Array path;const auto fraction=i?(p.snapshot().capacity?double(p.snapshot().capacity->usedBytes())/double(p.snapshot().capacity->totalBytes):0.):1.;for(const auto&r:storageMeter(fraction))if(r.width>0){auto cell=rectanglePath(r);path.insert(path.end(),cell.begin(),cell.end());}auto node=shape(i?"storage.capacity.used":"storage.capacity.segments",{12,201,376,17},std::move(path),i?a.accent:gray(a.dark?.65:.40,.22));add(std::move(node),{},false,false,i&&!p.snapshot().capacity?0.f:1.f);}
    for(unsigned i=0;i<2;++i){const auto r=i?StoragePresentation::refreshRect():StoragePresentation::settingsRect();const auto prefix=i?"storage.refresh":"storage.settings";auto plate=layer(std::string(prefix)+".button",r);plate["cornerRadius"]=3;plate["backgroundColor"]=color(i?gray(a.dark?.81:.90):a.accent);add(std::move(plate));
        if(!i)add(label("storage.settings.title",{r.x+5,r.y+6,156,17},v.settings,11,ink,"Semibold","center"));else add(shape("storage.refresh.arrow",{r.x+7,r.y+3.5,22,22},paths.refreshArrow,ink,{},0),{},false,true);
        auto tint=a.accent;tint[3]=.30;const auto action=i?"storage:refresh":"storage:settings";add(shape(std::string(prefix)+".tint",r,i?paths.refreshFeedback:paths.settingsFeedback,tint),action,false,false,0);add(shape(std::string(prefix)+".rim",r,i?paths.refreshFeedback:paths.settingsFeedback,{},a.accent,.9),action,true,false,0);
    }
    result.layers=layer("storage.root",StoragePresentation::bounds());result.layers["contentsScale"]=std::clamp(a.scale,1.,4.);result.layers["allowsGroupOpacity"]=false;result.layers["children"]=std::move(nodes);return result;
}
void StorageRefreshMotion::begin(double now){if(!active_||reduce_||running_)return;++generation_;running_=true;began_=now;}
void StorageRefreshMotion::cancel(){++generation_;running_=queued_=false;}
void StorageRefreshMotion::update(bool active,bool loading,bool reduced,double now){need(std::isfinite(now),"Invalid Storage animation clock");active_=active;loading_=loading;reduce_=reduced;if(!active_||reduce_)cancel();else if(loading_&&!running_)begin(now);}
void StorageRefreshMotion::manualTurn(double now){need(std::isfinite(now),"Invalid Storage animation clock");if(!active_||reduce_)return;if(running_)queued_=true;else begin(now);}
bool StorageRefreshMotion::complete(std::uint64_t token,bool finished,double now){need(std::isfinite(now),"Invalid Storage animation clock");if(!running_||token!=generation_)return false;running_=false;++generation_;if(!finished||!active_||reduce_){queued_=false;return true;}const bool again=loading_||queued_;queued_=false;if(again)begin(now);return true;}
StorageRefreshSample StorageRefreshMotion::sample(double now){need(std::isfinite(now),"Invalid Storage animation clock");if(running_&&now-began_>=duration)complete(generation_,true,now);return {running_?std::clamp((now-began_)/duration,0.,1.)*2*std::numbers::pi:0,running_,generation_};}
}
