import AppKit
import ImageIO

enum ClipboardKind: String, CaseIterable { case text, url, image, files }

struct ClipboardItem: Identifiable {
    let id: UUID
    var isPinned: Bool
    let createdAt: Date
    var kind: ClipboardKind
    var preview: String
    var thumbnail: CGImage?
    fileprivate let payload: ClipboardPayload
}

fileprivate final class ClipboardFileReferences {
    let urls: [URL]
    private let accessed: [URL]
    init(_ urls: [URL]) {
        self.urls = urls
        accessed = urls.filter { $0.startAccessingSecurityScopedResource() }
    }
    deinit { accessed.forEach { $0.stopAccessingSecurityScopedResource() } }
}

fileprivate enum ClipboardPayload {
    case text(String)
    case url(URL, String)
    case image(NSPasteboard.PasteboardType, Data)
    case files(ClipboardFileReferences)

    var byteCount: Int {
        switch self {
        case .text(let value), .url(_, let value): return value.utf8.count
        case .image(_, let data): return data.count
        case .files(let files): return files.urls.reduce(0) { $0 + $1.absoluteString.utf8.count }
        }
    }

    func matches(_ other: ClipboardPayload) -> Bool {
        switch (self, other) {
        case (.text(let first), .text(let second)): return first == second
        case (.url(let first, let text), .url(let second, let otherText)): return first == second && text == otherText
        case (.image(let type, let first), .image(let otherType, let second)): return type == otherType && first == second
        case (.files(let first), .files(let second)):
            return first.urls.map(\.standardizedFileURL) == second.urls.map(\.standardizedFileURL)
        default: return false
        }
    }
}

/// A session-only, main-thread clipboard cache. Raw contents are never written
/// to disk, logged, sent to a server, or represented by copied source files.
final class ClipboardStore {
    private(set) var items: [ClipboardItem] = []
    private(set) var capacity: Int
    private(set) var statusMessage: String?
    private var observers: [UUID: () -> Void] = [:]
    private static let maximumTextBytes = 1_048_576
    private static let maximumImageBytes = 64 * 1_048_576
    private static let maximumRetainedBytes = 128 * 1_048_576
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping"
    ]

    init(capacity: Int = 10) { self.capacity = max(1, capacity) }

    @discardableResult func observe(_ callback: @escaping () -> Void) -> UUID {
        requireMainThread()
        let id = UUID(); observers[id] = callback; return id
    }

    func removeObserver(_ id: UUID) { requireMainThread(); observers.removeValue(forKey: id) }

    @discardableResult func setCapacity(_ value: Int) -> Bool {
        requireMainThread()
        guard value > 0 else {
            setStatus(L10n.text("Keep at least one clipboard item.", "请至少保留一个剪贴板项目。")); return false
        }
        guard items.filter(\.isPinned).count <= value else {
            setStatus(L10n.text("Unpin some items before reducing the cache size.", "请先取消固定部分项目，再缩小缓存容量。")); return false
        }
        guard value != capacity else { return true }
        capacity = value
        while items.count > capacity, let index = items.lastIndex(where: { !$0.isPinned }) { items.remove(at: index) }
        statusMessage = nil; notify(); return true
    }

    @discardableResult func togglePin(id: UUID) -> Bool {
        requireMainThread()
        guard let index = items.firstIndex(where: { $0.id == id }) else { return false }
        items[index].isPinned.toggle(); statusMessage = nil; notify(); return true
    }

    @discardableResult func remove(id: UUID) -> Bool {
        requireMainThread()
        guard let index = items.firstIndex(where: { $0.id == id }) else { return false }
        items.remove(at: index); statusMessage = nil; notify(); return true
    }

    @discardableResult func clearUnpinned() -> Bool {
        requireMainThread()
        let before = items.count
        items.removeAll { !$0.isPinned }
        let changed = before != items.count || statusMessage != nil
        statusMessage = nil
        if changed { notify() }
        return before != items.count
    }

    @discardableResult func capture(from pasteboard: NSPasteboard) -> Bool {
        requireMainThread()
        // Check markers before requesting a payload, including per-item types.
        let declared = Set((pasteboard.types ?? []).map(\.rawValue))
            .union(pasteboard.pasteboardItems?.flatMap { $0.types.map(\.rawValue) } ?? [])
        guard Self.ignoredTypes.isDisjoint(with: declared) else { return false }
        do {
            guard let item = try read(from: pasteboard) else { return false }
            if let index = items.firstIndex(where: { $0.payload.matches(item.payload) }) {
                let existing = items.remove(at: index)
                items.insert(existing, at: 0)
                let changed = index != 0 || statusMessage != nil
                statusMessage = nil
                if changed { notify() }
                return true
            }
            var next = items
            var bytes = next.reduce(item.payload.byteCount) { $0 + $1.payload.byteCount }
            while next.count >= capacity || bytes > Self.maximumRetainedBytes {
                guard let index = next.lastIndex(where: { !$0.isPinned }) else {
                    setStatus(L10n.text("The cache is full of pinned items. Unpin or remove an item to capture more.",
                                        "缓存已被固定项目占满，请取消固定或移除项目后继续记录。"))
                    return false
                }
                bytes -= next[index].payload.byteCount
                next.remove(at: index)
            }
            next.insert(item, at: 0)
            items = next; statusMessage = nil; notify(); return true
        } catch {
            setStatus(error.localizedDescription); return false
        }
    }

    @discardableResult func copy(id: UUID, to pasteboard: NSPasteboard) -> Bool {
        requireMainThread()
        guard let item = items.first(where: { $0.id == id }) else { return false }
        let success: Bool
        switch item.payload {
        case .files(let files):
            pasteboard.clearContents()
            success = pasteboard.writeObjects(files.urls.map { $0 as NSURL })
        case .text(let value):
            pasteboard.clearContents()
            success = pasteboard.setString(value, forType: .string)
        case .url(let url, let original):
            let writer = NSPasteboardItem()
            guard writer.setString(url.absoluteString, forType: .URL), writer.setString(original, forType: .string) else { return false }
            pasteboard.clearContents()
            success = pasteboard.writeObjects([writer])
        case .image(let type, let data):
            pasteboard.clearContents()
            success = pasteboard.setData(data, forType: type)
        }
        setStatus(success ? nil : L10n.text("This item could not be copied. Try again.", "无法复制此项目，请重试。"))
        return success
    }

    private func read(from pasteboard: NSPasteboard) throws -> ClipboardItem? {
        if pasteboard.canReadObject(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            guard urls.count <= 512, urls.reduce(0, { $0 + $1.absoluteString.utf8.count }) <= Self.maximumTextBytes else {
                throw CaptureError.tooManyFiles
            }
            let names = urls.prefix(3).map(\.lastPathComponent).joined(separator: ", ")
            let preview = urls.count > 3 ? names + " (+\(urls.count - 3))" : names
            return make(.files, preview: preview, payload: .files(ClipboardFileReferences(urls)))
        }
        for type: NSPasteboard.PasteboardType in [.png, .tiff] {
            guard pasteboard.types?.contains(type) == true, let data = pasteboard.data(forType: type) else { continue }
            guard data.count <= Self.maximumImageBytes else { throw CaptureError.imageTooLarge }
            guard let source = CGImageSourceCreateWithData(data as CFData, [kCGImageSourceShouldCache: false] as CFDictionary),
                  CGImageSourceGetCount(source) > 0,
                  let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
                  let width = properties[kCGImagePropertyPixelWidth] as? Int,
                  let height = properties[kCGImagePropertyPixelHeight] as? Int,
                  width > 0, height > 0 else { continue }
            guard width <= 100_000, height <= 100_000,
                  Int64(width) * Int64(height) <= 100_000_000 else { throw CaptureError.imageDimensionsTooLarge }
            let options: [CFString: Any] = [kCGImageSourceCreateThumbnailFromImageAlways: true,
                kCGImageSourceCreateThumbnailWithTransform: true, kCGImageSourceThumbnailMaxPixelSize: 96,
                kCGImageSourceShouldCacheImmediately: true]
            guard let thumbnail = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { continue }
            return make(.image, preview: L10n.text("Image", "图像") + " · \(width) × \(height)",
                        thumbnail: thumbnail, payload: .image(type, data))
        }
        if let explicit = pasteboard.string(forType: .URL), let url = Self.parsedURL(explicit, explicit: true) {
            let original = pasteboard.string(forType: .string) ?? explicit
            guard original.utf8.count <= Self.maximumTextBytes, explicit.utf8.count <= Self.maximumTextBytes else { throw CaptureError.textTooLarge }
            return make(.url, preview: original, payload: .url(url, original))
        }
        guard let text = pasteboard.string(forType: .string), !text.isEmpty else { return nil }
        guard text.utf8.count <= Self.maximumTextBytes else { throw CaptureError.textTooLarge }
        if text.utf8.count <= 2048, let url = Self.parsedURL(text, explicit: false) {
            return make(.url, preview: text, payload: .url(url, text))
        }
        return make(.text, preview: text, payload: .text(text))
    }

    private static func parsedURL(_ text: String, explicit: Bool) -> URL? {
        let candidate = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !candidate.contains(where: \.isWhitespace), let url = URL(string: candidate),
              let scheme = url.scheme?.lowercased(), !scheme.isEmpty else { return nil }
        if ["http", "https", "ftp"].contains(scheme) { return url.host?.isEmpty == false ? url : nil }
        if explicit { return url }
        if ["mailto", "tel", "sms"].contains(scheme), !candidate.dropFirst(scheme.count + 1).isEmpty { return url }
        if scheme == "file", !url.path.isEmpty { return url }
        return nil
    }

    private func make(_ kind: ClipboardKind, preview: String, thumbnail: CGImage? = nil, payload: ClipboardPayload) -> ClipboardItem {
        let flattened = preview.split(whereSeparator: \.isWhitespace).joined(separator: " ")
        let compact = flattened.count > 90 ? String(flattened.prefix(89)) + "…" : flattened
        return ClipboardItem(id: UUID(), isPinned: false, createdAt: Date(), kind: kind,
                             preview: compact, thumbnail: thumbnail, payload: payload)
    }

    private func setStatus(_ value: String?) {
        guard statusMessage != value else { return }
        statusMessage = value; notify()
    }

    private func notify() { Array(observers.values).forEach { $0() } }
    private func requireMainThread() { precondition(Thread.isMainThread, "ClipboardStore must be used on the main thread") }

    private enum CaptureError: LocalizedError {
        case textTooLarge, imageTooLarge, imageDimensionsTooLarge, tooManyFiles
        var errorDescription: String? {
            switch self {
            case .textTooLarge: return L10n.text("Text over 1 MB was skipped.", "已跳过超过 1 MB 的文本。")
            case .imageTooLarge: return L10n.text("An image over 64 MB was skipped.", "已跳过超过 64 MB 的图像。")
            case .imageDimensionsTooLarge: return L10n.text("An image over 100 megapixels was skipped.", "已跳过超过 1 亿像素的图像。")
            case .tooManyFiles: return L10n.text("This file selection is too large to cache.", "此文件选择过大，无法缓存。")
            }
        }
    }
}
