import Foundation

/// These are community-scoped credentials, never a Hypergryph/Gryphline passport token.
/// Persistence belongs exclusively to the account credential vault (Keychain in production).
struct HypergryphCredentials: Codable, Equatable {
    let cred: String
    let signingToken: String
    /// The community website's already-issued request context, not a device
    /// fingerprint generated by EndfieldHUD. Older Keychain records omit it.
    let deviceID: String?

    init(cred: String, signingToken: String, deviceID: String? = nil) {
        self.cred = cred; self.signingToken = signingToken; self.deviceID = deviceID
    }
}

enum HypergryphAccountRegion: String, Codable, CaseIterable {
    case mainland, global
    var apiHost: String { self == .mainland ? "zonai.skland.com" : "zonai.skport.com" }
    var communityURL: URL { URL(string: self == .mainland ? "https://www.skland.com" : "https://www.skport.com")! }
    var gameOrigin: String { self == .mainland ? "https://game.skland.com" : "https://game.skport.com" }
}

enum HypergryphGame: String, Codable, CaseIterable { case arknights, endfield }

struct HypergryphRole: Codable, Equatable, Identifiable {
    let region: HypergryphAccountRegion
    let game: HypergryphGame
    let bindingUID: String
    let roleID: String
    var serverID: String? = nil
    var name: String? = nil
    var serverName: String? = nil
    var isDefault: Bool = false
    var isAvailable: Bool = true
    /// Community target for explicit web/card diagnostics, distinct from the game UID.
    /// The authenticated self-profile route identifies the account from its credential.
    var communityUserID: String? = nil
    var id: String { [region.rawValue, game.rawValue, bindingUID, roleID, serverID ?? ""].map { "\($0.utf8.count):\($0)" }.joined(separator: "|") }
}

struct HypergryphStamina: Codable, Equatable {
    let current: Int
    let maximum: Int
    var fullRecoveryAt: Date? = nil
    var serverObservedAt: Date? = nil
    // Missing/sentinel deadlines remain unknown; projection never lowers a
    // reported value or clamps purchased sanity above its natural cap.
}

/// A local projection for the existing HUD clock. Recovery dates use the local
/// clock; no additional persistence or scheduling owner is needed.
struct HypergryphSanityPresentation: Equatable {
    let game: HypergryphGame
    let current: Int
    let maximum: Int
    let observedAt: Date
    let nextRecoveryAt: Date?
    let fullRecoveryAt: Date?
    let isRefreshing: Bool
    let refreshAvailable: Bool
}

struct HypergryphProfileSnapshot: Codable, Equatable {
    let role: HypergryphRole
    let observedAt: Date
    var name: String? = nil
    var avatarURL: URL? = nil
    var level: Int? = nil
    var worldLevel: Int? = nil
    var experience: Int? = nil
    var createdAt: Date? = nil
    var operatorCount: Int? = nil
    var weaponCount: Int? = nil
    var documentCount: Int? = nil
    var stamina: HypergryphStamina? = nil

    /// Endfield publishes the discriminator as a suffix of its display name.
    /// Older cached cards may contain that combined name, so split it only when
    /// applying a profile rather than introducing another persisted identity.
    var personalProfileIdentity: (name: String?, tag: String?) {
        let card = Self.splitDisplayName(name)
        let binding = Self.splitDisplayName(role.name)
        return (card.name ?? binding.name, card.tag ?? binding.tag)
    }

    private static func splitDisplayName(_ raw: String?) -> (name: String?, tag: String?) {
        guard let raw else { return (nil, nil) }
        let name = raw.replacingOccurrences(of: "\n", with: " ").replacingOccurrences(of: "\r", with: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !name.isEmpty else { return (nil, nil) }
        if let separator = name.lastIndex(of: "#") {
            let tag = name[name.index(after: separator)...]
            let prefix = name[..<separator].trimmingCharacters(in: .whitespaces)
            if !prefix.isEmpty, !tag.isEmpty, tag.count <= 10,
               tag.utf8.allSatisfy({ (48...57).contains($0) }) {
                return (prefix, String(tag))
            }
        }
        return (name, nil)
    }

    func sanityPresentation(at date: Date, isRefreshing: Bool = false,
                            refreshAvailable: Bool = false) -> HypergryphSanityPresentation? {
        guard let stamina, stamina.current >= 0, stamina.maximum > 0 else { return nil }
        var current = stamina.current
        var nextLocal: Date?, fullLocal: Date?
        // Endfield's game DungeonConst uses 432 seconds per point; the official
        // Arknights card codec uses 360. Neither requires another network read.
        let interval: TimeInterval = role.game == .endfield ? 432 : 360
        let elapsed = date.timeIntervalSince(observedAt)
        let reference = stamina.serverObservedAt ?? observedAt
        if current < stamina.maximum, elapsed.isFinite, elapsed >= 0,
           reference.timeIntervalSince1970.isFinite,
           let full = stamina.fullRecoveryAt, full.timeIntervalSince1970.isFinite,
           full.timeIntervalSince1970 > 0 {
            let serverNow = reference.addingTimeInterval(elapsed)
            let remaining = full.timeIntervalSince(serverNow)
            if remaining <= 0 { current = stamina.maximum }
            else if remaining.isFinite {
                let missing = ceil(remaining / interval)
                let estimate = missing >= Double(stamina.maximum) ? 0 : stamina.maximum - Int(missing)
                current = max(current, estimate)
                fullLocal = observedAt.addingTimeInterval(full.timeIntervalSince(reference))
                let untilNext = remaining - Double(stamina.maximum - current - 1) * interval
                if untilNext.isFinite, untilNext > 0 { nextLocal = date.addingTimeInterval(untilNext) }
            }
        }
        return HypergryphSanityPresentation(game: role.game, current: current, maximum: stamina.maximum,
            observedAt: observedAt, nextRecoveryAt: nextLocal, fullRecoveryAt: fullLocal,
            isRefreshing: isRefreshing, refreshAvailable: refreshAvailable)
    }
}

enum HypergryphAPIError: Error, Equatable {
    case invalidCredentials
    case invalidRole
    case authenticationExpired
    case service(code: Int)
    case http(status: Int)
    case transport
    case cancelled
    case responseTooLarge
    case invalidResponse
    case unsafeRedirect
}

/// Opt-in diagnostics contain only fixed categories and a provider code. Raw
/// messages can contain account details and must never leave the API adapter.
struct HypergryphAPIDiagnostic: Equatable {
    enum Endpoint: String {
        case refresh, bindings, communityUser = "community_user"
        case endfieldProfile = "endfield_profile", arknightsProfile = "arknights_profile"
    }
    enum Reason: String {
        case device, parameters, role, permission, identity, authentication, signature, other

        static func classify(_ value: Any?) -> Self {
            guard let message = value as? String, message.utf8.count <= 1_024 else { return .other }
            let text = message.lowercased()
            if ["设备", "設備", "device"].contains(where: text.contains) { return .device }
            if ["签名", "簽名", "signature", "invalid sign"].contains(where: text.contains) { return .signature }
            if ["参数", "參數", "parameter"].contains(where: text.contains) { return .parameters }
            if ["实名", "實名", "real-name", "real name"].contains(where: text.contains) { return .identity }
            if ["权限", "權限", "授权", "授權", "permission", "forbidden", "private", "unauthorized"].contains(where: text.contains) { return .permission }
            if ["角色", "role", "绑定", "綁定"].contains(where: text.contains) { return .role }
            if ["登录", "登入", "登錄", "login", "credential"].contains(where: text.contains) { return .authentication }
            return .other
        }
    }
    let endpoint: Endpoint
    let code: Int
    let reason: Reason
}

protocol HypergryphAccountRequest: AnyObject { func cancel() }

protocol HypergryphAccountServing: AnyObject {
    @discardableResult func refreshCredentials(cred: String, region: HypergryphAccountRegion,
        completion: @escaping (Result<HypergryphCredentials, HypergryphAPIError>) -> Void) -> HypergryphAccountRequest?
    @discardableResult func refreshCredentials(credentials: HypergryphCredentials, region: HypergryphAccountRegion,
        completion: @escaping (Result<HypergryphCredentials, HypergryphAPIError>) -> Void) -> HypergryphAccountRequest?
    @discardableResult func bindings(credentials: HypergryphCredentials, region: HypergryphAccountRegion,
        completion: @escaping (Result<[HypergryphRole], HypergryphAPIError>) -> Void) -> HypergryphAccountRequest?
    @discardableResult func profile(role: HypergryphRole, credentials: HypergryphCredentials,
        completion: @escaping (Result<HypergryphProfileSnapshot, HypergryphAPIError>) -> Void) -> HypergryphAccountRequest?
}

extension HypergryphAccountServing {
    /// Compatibility for adapters that have no separate signing/device context.
    @discardableResult func refreshCredentials(credentials: HypergryphCredentials, region: HypergryphAccountRegion,
        completion: @escaping (Result<HypergryphCredentials, HypergryphAPIError>) -> Void) -> HypergryphAccountRequest? {
        refreshCredentials(cred: credentials.cred, region: region, completion: completion)
    }
}
