import Foundation

/// Full UI translations keyed by both source strings, including context where
/// identical English labels have different meanings. {0}, {1}, … refer to the
/// English interpolation arguments; renderers insert their values only once.
enum LocalizationCatalog {
    struct Entry {
        let english: String
        let simplifiedChinese: String
        let traditionalChinese: String
        let japanese: String
        var korean: String {
            LocalizationCatalog.koreanTranslations[english + "\u{1F}" + simplifiedChinese] ?? english
        }

        init(_ english: String, _ simplifiedChinese: String, _ traditionalChinese: String, _ japanese: String) {
            self.english = english; self.simplifiedChinese = simplifiedChinese
            self.traditionalChinese = traditionalChinese; self.japanese = japanese
        }
    }

    static func entry(english: String, simplifiedChinese: String) -> Entry? {
        byEnglish[english]?.first { $0.simplifiedChinese == simplifiedChinese }
    }

    private static let byEnglish = Dictionary(grouping: entries, by: \.english)

    // Keep source pairs intact: identical English labels can have different
    // meanings. This additive map preserves the existing four-language catalog.
    static let koreanTranslations: [String: String] = [
        "Overview\u{1F}概览": "개요",
        "Apps\u{1F}应用": "앱",
        ", descending\u{1F}，降序": ", 내림차순",
        ", ascending\u{1F}，升序": ", 오름차순",
        "Sort by \u{1F}排序：": "정렬 기준: ",
        "Read \u{1F}读取 ": "읽기 ",
        "Write \u{1F}写入 ": "쓰기 ",
        "RAM \u{1F}RAM ": "RAM ",
        "Upload \u{1F}上传 ": "업로드 ",
        "Download \u{1F}下载 ": "다운로드 ",
        "Disk read \u{1F}磁盘读取 ": "디스크 읽기 ",
        "Disk write \u{1F}磁盘写入 ": "디스크 쓰기 ",
        "App\u{1F}应用": "앱",
        "RAM\u{1F}RAM": "RAM",
        "Network\u{1F}网络": "네트워크",
        "Disk\u{1F}磁盘": "디스크",
        "No app readings available\u{1F}暂无应用读数": "앱 사용량을 확인할 수 없습니다",
        "R \u{1F}读 ": "읽기 ",
        "W \u{1F}写 ": "쓰기 ",
        "Disk I/O\u{1F}磁盘 I/O": "디스크 I/O",
        "TOTAL LOAD\u{1F}总负载": "총 부하",
        "USED / TOTAL\u{1F}已用 / 总计": "사용 중 / 전체",
        "UP / DOWN\u{1F}上传 / 下载": "업로드 / 다운로드",
        "READ / WRITE\u{1F}读取 / 写入": "읽기 / 쓰기",
        "Compressed \u{1F}压缩 ": "압축됨 ",
        "Settings\u{1F}设置": "설정",
        "Open overlay\u{1F}打开浮层": "HUD 열기",
        "Settings…\u{1F}设置…": "설정…",
        "Preview charging effect\u{1F}预览充电效果": "충전 효과 미리 보기",
        "About EndfieldHUD\u{1F}关于 EndfieldHUD": "EndfieldHUD 정보",
        "Check for Updates…\u{1F}检查更新…": "업데이트 확인…",
        "Quit EndfieldHUD\u{1F}退出 EndfieldHUD": "EndfieldHUD 종료",
        "Edit\u{1F}编辑": "편집",
        "Cut\u{1F}剪切": "잘라내기",
        "Copy\u{1F}复制": "복사",
        "Paste\u{1F}粘贴": "붙여넣기",
        "Select All\u{1F}全选": "모두 선택",
        "Update available\u{1F}发现新版本": "업데이트 있음",
        "Checking for updates…\u{1F}正在检查更新…": "업데이트 확인 중…",
        "Active\u{1F}进行中": "진행 중",
        "Paused\u{1F}已暂停": "일시 정지됨",
        "Stopped\u{1F}已停止": "중지됨",
        "Countdown complete\u{1F}倒计时结束": "카운트다운 완료",
        "Work Mode\u{1F}工作模式": "작업 모드",
        "Unknown charge\u{1F}电量未知": "배터리 잔량 알 수 없음",
        "Charging\u{1F}正在充电": "충전 중",
        "Power connected\u{1F}已连接电源": "전원 연결됨",
        "On battery\u{1F}使用电池": "배터리 사용 중",
        "No internal battery · Preview available\u{1F}无内置电池 · 可预览效果": "내장 배터리 없음 · 미리 보기 가능",
        "Edit app shortcut\u{1F}编辑应用快捷方式": "앱 바로가기 편집",
        "Application shortcuts\u{1F}应用快捷方式": "앱 바로가기",
        "Shortcut storage is unavailable.\u{1F}快捷方式存储不可用。": "바로가기 저장소를 사용할 수 없습니다.",
        "Choose one application to customize.\u{1F}请选择一个应用进行设置。": "설정할 앱을 하나 선택하세요.",
        "Choose application\u{1F}选择应用": "앱 선택",
        "Rename: \u{1F}重命名：": "이름 변경: ",
        ", selected\u{1F}，已选择": ", 선택됨",
        "Cancel\u{1F}取消": "취소",
        "Save shortcut\u{1F}保存快捷方式": "바로가기 저장",
        "Open \u{1F}打开 ": "열기: ",
        "Edit \u{1F}编辑 ": "편집: ",
        "Remove shortcut: \u{1F}移除快捷方式：": "바로가기 제거: ",
        "APPLICATIONS\u{1F}应用快捷方式": "앱 바로가기",
        "+ Choose app\u{1F}+ 选择应用": "+ 앱 선택",
        "Shortcut name\u{1F}快捷方式名称": "바로가기 이름",
        "ICON\u{1F}图标": "아이콘",
        "macOS did not return an application.\u{1F}macOS 未返回应用。": "macOS에서 앱을 반환하지 않았습니다.",
        "App icon\u{1F}原始图标": "앱 아이콘",
        "Bolt\u{1F}闪电": "번개",
        "Star\u{1F}星形": "별",
        "Terminal\u{1F}终端": "터미널",
        "Globe\u{1F}地球": "지구본",
        "Folder\u{1F}文件夹": "폴더",
        "Music\u{1F}音乐": "음악",
        "Play\u{1F}播放": "재생",
        "Brush\u{1F}画笔": "브러시",
        "Code\u{1F}代码": "코드",
        "Game\u{1F}游戏": "게임",
        "Camera\u{1F}相机": "카메라",
        "Grid\u{1F}网格": "격자",
        "Text bubble\u{1F}文字气泡": "말풍선",
        "Choose a macOS application (.app) with an available executable.\u{1F}请选择包含可用执行文件的 macOS 应用程序（.app）。": "실행 가능한 파일이 포함된 macOS 앱(.app)을 선택하세요.",
        "Enter a name of 1–128 characters without line breaks.\u{1F}请输入 1–128 个字符的名称，不含换行。": "줄바꿈 없이 1~128자의 이름을 입력하세요.",
        "This application is already saved. Edit its existing shortcut instead.\u{1F}此应用已添加，请编辑现有快捷方式。": "이미 저장된 앱입니다. 기존 바로가기를 편집하세요.",
        "This app shortcut is no longer available.\u{1F}此应用快捷方式已不存在。": "이 앱 바로가기는 더 이상 사용할 수 없습니다.",
        "A different application now occupies this location. Choose the application again.\u{1F}此位置的应用已更改，请重新选择应用。": "이 위치의 앱이 변경되었습니다. 앱을 다시 선택하세요.",
        "The saved app shortcuts could not be read. The original data has been preserved.\u{1F}无法读取应用快捷方式，原始数据已保留。": "저장된 앱 바로가기를 읽을 수 없습니다. 원본 데이터는 보존되었습니다.",
        "These app shortcuts were saved by a newer version of EndfieldCharge.\u{1F}这些快捷方式由较新版本的 EndfieldCharge 保存。": "이 앱 바로가기는 더 최신 버전의 EndfieldCharge에서 저장되었습니다.",
        "App shortcuts changed outside this window. Restart EndfieldCharge before editing.\u{1F}应用快捷方式已在外部更改，请重启 EndfieldCharge 后再编辑。": "다른 창이나 앱에서 바로가기가 변경되었습니다. EndfieldCharge를 재시작한 후 편집하세요.",
        "The application is unavailable: \u{1F}应用不可用：": "앱을 사용할 수 없습니다: ",
        "App shortcuts could not be saved or opened: \u{1F}无法保存或打开应用快捷方式：": "앱 바로가기를 저장하거나 열 수 없습니다: ",
        "Audio device information is unavailable.\u{1F}音频设备信息不可用。": "오디오 기기 정보를 확인할 수 없습니다.",
        "This device does not support this control.\u{1F}此设备不支持该控制。": "이 기기는 해당 조작을 지원하지 않습니다.",
        "The audio device changed. Try the control again.\u{1F}音频设备已更改，请重试。": "오디오 기기가 변경되었습니다. 다시 시도하세요.",
        "The audio control value is invalid.\u{1F}音频控制值无效。": "오디오 설정값이 올바르지 않습니다.",
        "The device could not confirm the audio change.\u{1F}无法确认设备的音频更改。": "기기에서 오디오 변경 사항을 확인하지 못했습니다.",
        "macOS could not complete the audio operation\u{1F}macOS 无法完成音频操作": "macOS에서 오디오 작업을 완료하지 못했습니다",
        "The audio change failed and could not be fully restored. Check the current device levels.\u{1F}音频更改失败且未能完全恢复，请检查当前设备音量。": "오디오 변경에 실패했으며 완전히 복원하지 못했습니다. 현재 기기 음량을 확인하세요.",
        "Audio device\u{1F}音频设备": "오디오 기기",
        "Active audio apps require macOS 14.2 or later and compatible Core Audio support.\u{1F}活跃音频应用需要 macOS 14.2 或更新版本及兼容的 Core Audio 支持。": "오디오 재생 중인 앱을 감지하려면 macOS 14.2 이상 및 호환되는 Core Audio 지원이 필요합니다.",
        "Active audio app information is unavailable.\u{1F}活跃音频应用信息不可用。": "오디오 재생 중인 앱 정보를 확인할 수 없습니다.",
        "Some audio changes could not be observed. Reopen Volume to refresh.\u{1F}无法监听部分音频更改，请重新打开音量模块刷新。": "일부 오디오 변경 사항을 감지하지 못했습니다. 음량 모듈을 다시 열어 새로 고치세요.",
        "CHARGE MODE\u{1F}超充模式": "충전 모드",
        "BATTERY MODE\u{1F}电池模式": "배터리 모드",
        "Battery unavailable\u{1F}电量不可用": "배터리 잔량 확인 불가",
        ", Preview\u{1F}，预览": ", 미리 보기",
        "Image · \u{1F}图片 · ": "이미지 · ",
        "Copy: \u{1F}复制：": "복사: ",
        "{0} / {1} items · Click to copy\u{1F}{0} / {1} 项 · 点击复制": "{0} / {1}개 항목 · 클릭하여 복사",
        "Copied\u{1F}已复制": "복사됨",
        "Could not restore this item\u{1F}无法恢复此项目": "이 항목을 복원할 수 없습니다",
        "Unpin: \u{1F}取消固定：": "고정 해제: ",
        "Pin: \u{1F}固定：": "고정: ",
        "Delete: \u{1F}删除：": "삭제: ",
        "Clear\u{1F}清空": "비우기",
        "Clear unpinned\u{1F}清空未固定项": "고정되지 않은 항목 비우기",
        "Previous page\u{1F}上一页": "이전 페이지",
        "Next page\u{1F}下一页": "다음 페이지",
        "Your clipboard history appears here\u{1F}剪贴板历史将在此显示": "클립보드 기록이 여기에 표시됩니다",
        "Copy text, links, images or files\u{1F}复制文字、链接、图片或文件": "텍스트, 링크, 이미지 또는 파일을 복사하세요",
        "Text\u{1F}文字": "텍스트",
        "Link\u{1F}链接": "링크",
        "Image\u{1F}图片": "이미지",
        "Files\u{1F}文件": "파일",
        " · Pinned\u{1F} · 已固定": " · 고정됨",
        "Pinned items will stay\u{1F}保留已固定项目": "고정된 항목은 유지됩니다",
        "Keep at least one clipboard item.\u{1F}请至少保留一个剪贴板项目。": "클립보드 항목을 하나 이상 유지해야 합니다.",
        "Unpin some items before reducing the cache size.\u{1F}请先取消固定部分项目，再缩小缓存容量。": "캐시 크기를 줄이기 전에 일부 항목의 고정을 해제하세요.",
        "The cache is full of pinned items. Unpin or remove an item to capture more.\u{1F}缓存已被固定项目占满，请取消固定或移除项目后继续记录。": "고정된 항목으로 캐시가 가득 찼습니다. 더 기록하려면 항목을 고정 해제하거나 제거하세요.",
        "This item could not be copied. Try again.\u{1F}无法复制此项目，请重试。": "이 항목을 복사하지 못했습니다. 다시 시도하세요.",
        "Image\u{1F}图像": "이미지",
        "Text over 1 MB was skipped.\u{1F}已跳过超过 1 MB 的文本。": "1 MB를 초과하는 텍스트를 건너뛰었습니다.",
        "An image over 64 MB was skipped.\u{1F}已跳过超过 64 MB 的图像。": "64 MB를 초과하는 이미지를 건너뛰었습니다.",
        "An image over 100 megapixels was skipped.\u{1F}已跳过超过 1 亿像素的图像。": "1억 픽셀을 초과하는 이미지를 건너뛰었습니다.",
        "This file selection is too large to cache.\u{1F}此文件选择过大，无法缓存。": "선택한 파일이 너무 커서 캐시할 수 없습니다.",
        "Clear log\u{1F}清空日志": "로그 비우기",
        "Unavailable\u{1F}不可用": "사용 불가",
        "Clear shelf\u{1F}清空暂存架": "보관함 비우기",
        "Add files\u{1F}添加文件": "파일 추가",
        "Clear all\u{1F}清空": "모두 비우기",
        "Quick Look: \u{1F}快速查看：": "훑어보기: ",
        "Reveal in Finder: \u{1F}在访达中显示：": "Finder에서 보기: ",
        "Remove from shelf: \u{1F}从暂存架移除：": "보관함에서 제거: ",
        "Video\u{1F}视频": "비디오",
        "Archive\u{1F}压缩文件": "압축 파일",
        "File\u{1F}文件": "파일",
        "Drop files or folders here\u{1F}将文件或文件夹拖放到此处": "여기에 파일이나 폴더를 놓으세요",
        "Keep references. Drag them out whenever you need.\u{1F}仅保留引用，可随时拖出使用。": "파일 참조를 보관하고 필요할 때 드래그하여 꺼내세요.",
        "Release to keep file references\u{1F}松开以暂存文件引用": "놓아서 파일 참조 보관",
        "Files stay in their original locations\u{1F}文件保留在原位置": "파일은 원래 위치에 유지됩니다",
        "{0} selected · Drag to copy\u{1F}已选 {0} 项 · 拖出以复制": "{0}개 선택됨 · 드래그하여 복사",
        "{0} items · Shift-click to select\u{1F}{0} 项 · Shift 点击多选": "{0}개 항목 · Shift-클릭하여 선택",
        "Clear references only?\u{1F}仅清空文件引用？": "파일 참조만 비울까요?",
        "File shelf storage is unavailable.\u{1F}文件暂存架存储不可用。": "파일 보관함 저장소를 사용할 수 없습니다.",
        "The saved file shelf could not be read. Its original data has been preserved.\u{1F}无法读取暂存架数据，原始数据已保留。": "저장된 파일 보관함을 읽을 수 없습니다. 원본 데이터는 보존되었습니다.",
        "This file shelf was saved by a newer version of EndfieldCharge.\u{1F}此暂存架由较新版本的 EndfieldCharge 保存。": "이 파일 보관함은 더 최신 버전의 EndfieldCharge에서 저장되었습니다.",
        "The saved shelf changed outside this window. Restart EndfieldCharge before making changes.\u{1F}暂存架数据已在外部更改，请重新启动 EndfieldCharge 后再编辑。": "다른 창이나 앱에서 보관함이 변경되었습니다. EndfieldCharge를 재시작한 후 변경하세요.",
        "Choose a file or folder that is available on this Mac.\u{1F}请选择此 Mac 上可访问的文件或文件夹。": "이 Mac에서 사용할 수 있는 파일이나 폴더를 선택하세요.",
        "This item is no longer on the shelf.\u{1F}此项目已不在暂存架中。": "이 항목은 더 이상 보관함에 없습니다.",
        "The original item is unavailable. A different item now occupies its old location.\u{1F}原始项目不可用，其他项目已占用了原来的位置。": "원본 항목을 사용할 수 없습니다. 이전 위치에 다른 항목이 있습니다.",
        "This item is unavailable: \u{1F}此项目不可用：": "이 항목을 사용할 수 없습니다: ",
        "The file shelf could not be saved or opened: \u{1F}无法保存或打开暂存架：": "파일 보관함을 저장하거나 열 수 없습니다: ",
        "Press your new shortcut. Escape cancels.\u{1F}请按新的快捷键，Escape 取消。": "새 단축키를 누르세요. Escape를 누르면 취소됩니다.",
        "{0} is stopped.\u{1F}{0} 已停用。": "{0} 사용이 중지되었습니다.",
        "{0} is ready, including in text fields.\u{1F}{0} 已就绪，在文本框中也可使用。": "{0} 사용 가능. 텍스트 입력란에서도 사용할 수 있습니다.",
        "{0} is unavailable or in use. Open from the menu bar.\u{1F}{0} 不可用或已被占用，请从菜单栏打开浮层。": "{0} 사용 불가 또는 이미 사용 중입니다. 메뉴 막대에서 여세요.",
        "Could not register the shortcut. Your previous shortcut is unchanged.\u{1F}无法注册快捷键，原快捷键保持不变。": "단축키를 등록하지 못했습니다. 기존 단축키가 유지됩니다.",
        "That shortcut is already in use or unavailable. Choose another combination.\u{1F}该快捷键已被占用或不可用，请选择其他组合。": "이미 사용 중이거나 사용할 수 없는 단축키입니다. 다른 조합을 선택하세요.",
        "macOS shortcut conflicts could not be checked. Try again.\u{1F}暂时无法检查 macOS 快捷键冲突，请重试。": "macOS 단축키 충돌을 확인하지 못했습니다. 다시 시도하세요.",
        "That shortcut is enabled in macOS Keyboard Shortcuts. Choose another combination.\u{1F}该快捷键已在 macOS 键盘快捷键中启用，请选择其他组合。": "macOS 키보드 단축키에서 사용 중인 조합입니다. 다른 조합을 선택하세요.",
        "Choose an application\u{1F}选择应用": "앱 선택",
        "Choose\u{1F}选择": "선택",
        "Return applies the name. Save shortcut stores your changes.\u{1F}回车应用名称，点击保存快捷方式以保存修改。": "Return을 누르면 이름이 적용됩니다. 바로가기 저장을 누르면 변경 사항이 저장됩니다.",
        "Battery\u{1F}电池": "배터리",
        "Originium\u{1F}源石": "오리지늄",
        "Orundum\u{1F}合成玉": "합성옥",
        "Perlica\u{1F}佩丽卡": "페리카",
        "Rhodes Island\u{1F}罗德岛": "로도스 아일랜드",
        "Babel\u{1F}巴别塔": "바벨",
        "Rhine Lab\u{1F}莱茵生命": "라인 랩",
        "Blacksteel\u{1F}黑钢国际": "블랙스틸",
        "Penguin Logistics\u{1F}企鹅物流": "펭귄 로지스틱스",
        "Elite Operators\u{1F}精英干员": "엘리트 오퍼레이터",
        "Reserve Team A4\u{1F}预备行动组 A4": "예비작전팀 A4",
        "Reserve Team A6\u{1F}预备行动组 A6": "예비작전팀 A6",
        "Human Resources\u{1F}人力资源部": "인사부",
        "Rim Billiton\u{1F}雷姆必拓": "림 빌리턴",
        "Kjerag\u{1F}谢拉格": "쉐라그",
        "Ursus Student Group\u{1F}乌萨斯学生自治团": "우르수스 학생 자치단",
        "Obsidian Festival\u{1F}黑曜石音乐节": "흑요석 축제",
        "Dossoles\u{1F}多索雷斯": "도솔레스",
        "Contingency Contract\u{1F}危机合约": "위기협약",
        "Ambience Synesthesia\u{1F}音律联觉": "앰비언스 시네스티시아",
        "Coral Coast\u{1F}珊瑚海岸": "코랄 코스트",
        "Vitafield\u{1F}生命之地": "비타필드",
        "Contingency Contract: Barrenland\u{1F}危机合约：荒芜行动": "위기협약: 황무지",
        "Contingency Contract: Pyrite\u{1F}危机合约：黄铁行动": "위기협약: 파이라이트",
        "Contingency Contract: Cinder\u{1F}危机合约：燃灰行动": "위기협약: 잿불",
        "Contingency Contract: Lead Seal\u{1F}危机合约：铅封行动": "위기협약: 리드씰",
        "Contingency Contract: Spectrum\u{1F}危机合约：光谱行动": "위기협약: 스펙트럼",
        "Contingency Contract: Pine Soot\u{1F}危机合约：松烟行动": "위기협약: 와일드 스케일",
        "Rhodes Kitchen\u{1F}罗德厨房": "로도스 키친",
        "Cambrian\u{1F}寒武纪": "캄브리안",
        "Marthe\u{1F}玛尔特": "마르트",
        "Icefield Messenger\u{1F}冰原信使": "아이스필드 메신저",
        "Power / Device Battery\u{1F}电量 / 设备电池": "전원 / 기기 배터리",
        ". Arrow keys select; Return copies; Delete removes the cached item.\u{1F}。方向键选择，回车复制，Delete 删除缓存项目。": ". 방향키로 선택, Return으로 복사, Delete로 캐시 항목을 삭제합니다.",
        "Pointer display\u{1F}鼠标所在显示器": "포인터가 있는 디스플레이",
        "Main display\u{1F}主显示器": "주 디스플레이",
        "Saved display\u{1F}已选显示器": "저장된 디스플레이",
        " (disconnected)\u{1F}（未连接）": " (연결 해제됨)",
        "Add to Temporary File Shelf\u{1F}添加到文件暂存架": "임시 파일 보관함에 추가",
        "Add references\u{1F}添加引用": "파일 참조 추가",
        "Quick Look could not open. Select the file and try again.\u{1F}无法打开快速查看，请选中文件后重试。": "훑어보기를 열지 못했습니다. 파일을 선택하고 다시 시도하세요.",
        "Shift-click selects a range to drag together. Space previews the selected file. Command-R reveals it in Finder. Delete removes only selected shelf references.\u{1F}Shift 点击多选并一同拖出。空格键预览所选文件，Command-R 在访达中显示，Delete 仅移除所选暂存架引用。": "Shift-클릭으로 범위를 선택하여 함께 드래그할 수 있습니다. Space로 선택한 파일을 미리 보고, Command-R로 Finder에서 확인하세요. Delete는 선택한 보관함의 파일 참조만 제거합니다.",
        "Selected\u{1F}已选择": "선택됨",
        "Authority\u{1F}权限等级": "권한",
        "MAX\u{1F}满级": "최대",
        "Notes\u{1F}便笺": "메모",
        "Temporary File Shelf\u{1F}文件暂存架": "임시 파일 보관함",
        "Clipboard Cache\u{1F}剪贴板": "클립보드 캐시",
        "Volume\u{1F}音量": "음량",
        "Event Log\u{1F}事件日志": "이벤트 로그",
        "Map\u{1F}地图": "지도",
        "+ Add App\u{1F}+ 添加应用": "+ 앱 추가",
        "System\u{1F}系统": "시스템",
        "Display\u{1F}显示": "화면",
        "Hotkeys\u{1F}快捷键": "단축키",
        "About\u{1F}关于": "정보",
        "Storage\u{1F}存储": "저장 공간",
        "Activity Monitor\u{1F}活动监视器": "활성 상태 보기",
        "Power\u{1F}电源": "전원",
        "Personal Profile\u{1F}个人名片": "개인 프로필",
        "Power / Device Battery\u{1F}电源 / 设备电量": "전원 / 기기 배터리",
        "Not configured yet\u{1F}尚未配置": "아직 설정되지 않음",
        "Device Battery\u{1F}设备电量": "기기 배터리",
        "Edit text note\u{1F}编辑文字便笺": "텍스트 메모 편집",
        "Edit checklist item\u{1F}编辑待办事项": "체크리스트 항목 편집",
        "Escape or Command-Return saves. Text notes support multiple lines.\u{1F}按 Esc 或 Command-Return 保存。文字便笺支持多行。": "Escape 또는 Command-Return으로 저장합니다. 텍스트 메모는 여러 줄을 지원합니다.",
        "Add image notes\u{1F}添加图片便笺": "이미지 메모 추가",
        "Add images\u{1F}添加图片": "이미지 추가",
        "Choose profile picture\u{1F}选择头像": "프로필 사진 선택",
        "Choose profile background\u{1F}选择名片背景": "프로필 배경 선택",
        "Card color\u{1F}名片颜色": "카드 색상",
        "Return saves. Escape cancels.\u{1F}回车保存，Esc 取消。": "Return으로 저장하고 Escape로 취소합니다.",
        "Quit EndfieldHUD?\u{1F}退出 EndfieldHUD？": "EndfieldHUD를 종료할까요?",
        "The application will quit after the HUD closes.\u{1F}界面收起后，将退出应用。": "HUD가 닫힌 후 앱이 종료됩니다.",
        "Quit\u{1F}退出": "종료",
        "Cancel quitting EndfieldHUD\u{1F}取消退出 EndfieldHUD": "EndfieldHUD 종료 취소",
        "Quit EndfieldHUD application\u{1F}退出 EndfieldHUD 应用": "EndfieldHUD 앱 종료",
        "Keep this position?\u{1F}保留此位置？": "이 위치를 유지할까요?",
        "Keep this UI scale?\u{1F}保留此缩放？": "이 UI 배율을 유지할까요?",
        "Keep this position? Reverts in {0}s\u{1F}保留此位置？{0} 秒后自动恢复": "이 위치를 유지할까요? {0}초 후 복원됩니다",
        "Keep this UI scale? Reverts in {0}s\u{1F}保留此缩放？{0} 秒后自动恢复": "이 UI 배율을 유지할까요? {0}초 후 복원됩니다",
        "Keep ↵\u{1F}保留 ↵": "유지 ↵",
        "Revert ⎋\u{1F}恢复 ⎋": "복원 ⎋",
        "Disconnected · using pointer display\u{1F}未连接 · 暂用鼠标所在显示器": "연결 해제됨 · 포인터가 있는 디스플레이 사용 중",
        "Language\u{1F}语言": "언어",
        "Launch at login\u{1F}登录时启动": "로그인 시 실행",
        "Close when focus lost\u{1F}失去焦点时关闭": "포커스를 잃으면 닫기",
        "Display\u{1F}显示器": "디스플레이",
        "Ambient animation\u{1F}持续环境动画": "배경 애니메이션",
        "Battery alerts\u{1F}电池提醒": "배터리 알림",
        "Restore default settings\u{1F}恢复默认设置": "기본 설정 복원",
        "Display method\u{1F}显示方式": "표시 방식",
        "Always\u{1F}始终显示": "항상",
        "Power changes\u{1F}充电状态变化": "전원 상태 변경 시",
        "Display duration\u{1F}显示时长": "표시 시간",
        "Display position\u{1F}显示位置": "표시 위치",
        "Top center\u{1F}顶部居中": "상단 중앙",
        "Custom\u{1F}自定": "사용자 지정",
        "Edit position\u{1F}编辑位置": "위치 편집",
        "Size\u{1F}大小": "크기",
        "UI scale\u{1F}界面缩放": "UI 배율",
        "HUD position X\u{1F}界面位置 X": "HUD X 위치",
        "HUD position Y\u{1F}界面位置 Y": "HUD Y 위치",
        "Parallax intensity\u{1F}视差强度": "시차 효과 강도",
        "Perspective intensity\u{1F}透视强度": "원근 효과 강도",
        "Background brightness\u{1F}背景亮度": "배경 밝기",
        "Blur amount\u{1F}模糊程度": "흐림 정도",
        "Reduce Motion\u{1F}减少动态效果": "동작 줄이기",
        "Theme\u{1F}主题": "테마",
        "Time format\u{1F}时间格式": "시간 형식",
        "24-hour\u{1F}24 小时制": "24시간제",
        "12-hour AM/PM\u{1F}12 小时制 AM/PM": "12시간제 오전/오후",
        "App / menu bar icon\u{1F}应用 / 菜单栏图标": "앱 / 메뉴 막대 아이콘",
        "Theme color\u{1F}主题颜色": "테마 색상",
        "Battery alert\u{1F}电池提醒": "배터리 알림",
        "Low Power visual mode\u{1F}低功耗视觉模式": "저전력 시각 효과 모드",
        "Summon HUD\u{1F}呼出界面": "HUD 열기",
        "Press shortcut…\u{1F}请按快捷键…": "단축키를 누르세요…",
        "Restore default hotkey\u{1F}恢复默认快捷键": "기본 단축키 복원",
        "Check for updates\u{1F}检查更新": "업데이트 확인",
        "Latest GitHub release\u{1F}GitHub 最新版本": "최신 GitHub 릴리스",
        "Install updates automatically\u{1F}自动安装更新": "업데이트 자동 설치",
        "Author\u{1F}作者": "제작자",
        "Not configured\u{1F}尚未设置": "설정되지 않음",
        "License\u{1F}许可证": "라이선스",
        "Cancel restore\u{1F}取消恢复": "복원 취소",
        "Restore defaults\u{1F}恢复默认设置": "기본값 복원",
        "Back\u{1F}返回": "뒤로",
        "On\u{1F}开": "켬",
        "Off\u{1F}关": "끔",
        "Custom color wheel\u{1F}自定义色轮": "사용자 지정 색상환",
        "Cancel shortcut recording\u{1F}取消快捷键录制": "단축키 기록 취소",
        "‹ Back\u{1F}‹ 返回": "‹ 뒤로",
        "Press up to 3 keys · Esc to cancel\u{1F}最多同时按 3 个键 · Esc 取消": "최대 3개의 키를 누르세요 · Esc로 취소",
        "Restore all preferences?\u{1F}恢复所有设置？": "모든 설정을 복원할까요?",
        "Notes, files and shortcuts are kept.\u{1F}保留便笺、文件与应用快捷方式。": "메모, 파일 및 바로가기는 유지됩니다.",
        "Restore\u{1F}恢复": "복원",
        "seconds\u{1F}秒": "초",
        "System\u{1F}跟随系统": "시스템 설정 따르기",
        "Dark\u{1F}深色": "다크",
        "Light\u{1F}浅色": "라이트",
        "Unofficial fan project\u{1F}非官方同人项目": "비공식 팬 프로젝트",
        "Inspiration\u{1F}灵感来源": "영감",
        "Audio architecture reference\u{1F}音频架构参考": "오디오 구조 참고",
        "UI layout restored\u{1F}已恢复界面布局": "UI 배치가 복원되었습니다",
        "UI scale restored\u{1F}已恢复界面缩放": "UI 배율이 복원되었습니다",
        "The signed updater could not start.\u{1F}签名更新服务无法启动。": "서명된 업데이터를 시작하지 못했습니다.",
        "Installs after 30 idle seconds, or when you quit.\u{1F}空闲 30 秒后或退出时自动安装。": "30초간 사용하지 않거나 앱을 종료하면 설치됩니다.",
        "Already downloaded; installs on next quit. Automatic restarts are off.\u{1F}更新已下载，将在下次退出时安装。已关闭自动重启。": "다운로드 완료. 다음 종료 시 설치됩니다. 자동 재시작은 꺼져 있습니다.",
        "EndfieldHUD update available\u{1F}EndfieldHUD 发现新版本": "EndfieldHUD 업데이트 있음",
        "{0} is available. Signed updates install automatically when the HUD, Work Mode and audio controls are idle.\u{1F}{0} 已发布。签名更新将在浮层、工作模式和音量控制空闲时自动安装。": "{0} 버전을 사용할 수 있습니다. HUD, 작업 모드 및 오디오 제어를 사용하지 않을 때 서명된 업데이트가 자동으로 설치됩니다.",
        "{0} is available. Open About to see the release.\u{1F}{0} 已发布。打开关于页面查看。": "{0} 버전을 사용할 수 있습니다. 정보에서 릴리스를 확인하세요.",
        "GitHub is limiting requests. Try again later.\u{1F}GitHub 暂时限制请求，请稍后重试。": "GitHub 요청 제한에 도달했습니다. 나중에 다시 시도하세요.",
        "No published release found on GitHub.\u{1F}GitHub 上暂无已发布版本。": "GitHub에서 공개된 릴리스를 찾지 못했습니다.",
        "No release is available for this update channel.\u{1F}此更新通道暂无已发布版本。": "이 업데이트 채널에 사용 가능한 릴리스가 없습니다.",
        "This build has no valid release version.\u{1F}此构建没有有效的版本号。": "이 빌드에는 유효한 릴리스 버전이 없습니다.",
        "Could not check GitHub. Check your connection and retry.\u{1F}无法检查 GitHub。请检查网络后重试。": "GitHub를 확인하지 못했습니다. 인터넷 연결을 확인하고 다시 시도하세요.",
        "Signed update unavailable. Retry or view the GitHub release.\u{1F}签名更新暂不可用。请重试或查看 GitHub 版本。": "서명된 업데이트를 사용할 수 없습니다. 다시 시도하거나 GitHub 릴리스를 확인하세요.",
        "Waiting for a compatible signed update package.\u{1F}正在等待兼容的签名更新包。": "호환되는 서명된 업데이트 패키지를 기다리는 중입니다.",
        "Not checked yet\u{1F}尚未检查": "아직 확인하지 않음",
        "Checking…\u{1F}正在检查…": "확인 중…",
        "Up to date\u{1F}已是最新版本": "최신 버전입니다",
        "Downloading…\u{1F}正在下载…": "다운로드 중…",
        "Ready to update\u{1F}更新已就绪": "업데이트 준비됨",
        "Restarting…\u{1F}正在重启…": "재시작 중…",
        "Check failed — retry\u{1F}检查失败 · 重试": "확인 실패 — 다시 시도",
        "Centered\u{1F}居中": "중앙",
        " · Not adjustable on this device\u{1F} · 此设备不支持调整": " · 이 기기에서 조절 불가",
        "Custom countdown: minutes and seconds\u{1F}自定义倒计时：分和秒": "사용자 지정 카운트다운: 분과 초",
        "Enter minutes or min:sec, between 0:01 and 1440:00. Return saves; Escape cancels.\u{1F}输入分钟数或分:秒，范围为 0:01 至 1440:00。回车保存，Esc 取消。": "0:01~1440:00 범위에서 분 또는 분:초 형식으로 입력하세요. Return으로 저장하고 Escape로 취소합니다.",
        ". Space starts, pauses or resumes.\u{1F}。空格键开始、暂停或继续。": ". Space로 시작, 일시 정지 또는 재개합니다.",
        ". Drag to pan. Scroll or pinch to zoom. Right-click to place or remove a pin. Left-click to hide coordinates. Arrow keys move the map.\u{1F}。拖动平移，滚动或捏合缩放，右键放置或移除标记，左键隐藏坐标，方向键移动地图。": ". 드래그하여 이동하고 스크롤하거나 두 손가락을 오므리거나 벌려 확대 및 축소합니다. 오른쪽 클릭으로 핀을 놓거나 제거하고 왼쪽 클릭으로 좌표를 숨깁니다. 방향키로 지도를 이동합니다.",
        "Approval needed in System Settings → Login Items.\u{1F}请在系统设置 → 登录项中允许启动。": "시스템 설정 → 로그인 항목에서 승인이 필요합니다.",
        "Enabled\u{1F}已启用": "활성화됨",
        "Disabled\u{1F}已停用": "비활성화됨",
        "Move EndfieldHUD.app into Applications (or your home Applications folder), open it from there, then enable Launch at login.\u{1F}请将 EndfieldHUD.app 移到“应用程序”文件夹（或个人目录中的“应用程序”文件夹），从那里打开后再启用“登录时启动”。": "EndfieldHUD.app을 응용 프로그램 폴더 또는 홈 폴더의 응용 프로그램 폴더로 옮긴 후 그곳에서 열고 로그인 시 실행을 켜세요.",
        "The app’s executable could not be found. Build or reinstall EndfieldHUD.app, then try again.\u{1F}找不到应用程序的可执行文件。请重新构建或安装 EndfieldHUD.app 后再试。": "앱의 실행 파일을 찾지 못했습니다. EndfieldHUD.app을 빌드하거나 다시 설치한 후 다시 시도하세요.",
        "Enlarge note\u{1F}放大便笺": "메모 확대",
        "Reduce note size\u{1F}缩小便笺": "메모 축소",
        "Checklist\u{1F}待办": "체크리스트",
        "TODO\u{1F}待办": "할 일",
        "Unpin note\u{1F}取消固定": "메모 고정 해제",
        "Pin note\u{1F}固定便笺": "메모 고정",
        "Delete note\u{1F}删除便笺": "메모 삭제",
        "Edit text\u{1F}编辑文字": "텍스트 편집",
        "Uncheck\u{1F}取消勾选": "선택 해제",
        "Check\u{1F}勾选": "선택",
        "Edit item\u{1F}编辑事项": "항목 편집",
        "Move up\u{1F}上移": "위로 이동",
        "Move down\u{1F}下移": "아래로 이동",
        "Delete item\u{1F}删除事项": "항목 삭제",
        "Add item\u{1F}添加事项": "항목 추가",
        "NOTES\u{1F}便笺": "메모",
        "Could not save: \u{1F}无法保存：": "저장할 수 없습니다: ",
        "Notes storage unavailable\u{1F}便笺存储不可用": "메모 저장소 사용 불가",
        "TEXT\u{1F}文字": "텍스트",
        "IMAGE\u{1F}图片": "이미지",
        "Double-click to write…\u{1F}双击输入…": "두 번 클릭하여 작성…",
        "Image unavailable\u{1F}图片不可用": "이미지 사용 불가",
        "New item…\u{1F}新事项…": "새 항목…",
        "+ Add item\u{1F}+ 添加事项": "+ 항목 추가",
        "Cancel deletion\u{1F}取消删除": "삭제 취소",
        "Confirm deletion\u{1F}确认删除": "삭제 확인",
        "Notes storage is unavailable.\u{1F}便笺存储不可用。": "메모 저장소를 사용할 수 없습니다.",
        "Notes could not be saved or opened: \u{1F}无法保存或打开便笺：": "메모를 저장하거나 열 수 없습니다: ",
        "A saved note could not be read. The original database has been preserved.\u{1F}无法读取已保存的便笺，原始数据库已保留。": "저장된 메모를 읽을 수 없습니다. 원본 데이터베이스는 보존되었습니다.",
        "These notes were saved by a newer version of EndfieldCharge.\u{1F}这些便笺由较新版本的 EndfieldCharge 保存。": "이 메모는 더 최신 버전의 EndfieldCharge에서 저장되었습니다.",
        "This file could not be opened as an image.\u{1F}无法将此文件作为图片打开。": "이 파일을 이미지로 열 수 없습니다.",
        "Choose an image smaller than 128 MB.\u{1F}请选择小于 128 MB 的图片。": "128 MB 미만의 이미지를 선택하세요.",
        "The note contains an invalid image reference.\u{1F}便笺中的图片引用无效。": "메모에 올바르지 않은 이미지 참조가 포함되어 있습니다.",
        "Discard position\u{1F}取消位置更改": "위치 변경 취소",
        "Confirm position\u{1F}确认位置": "위치 확인",
        "Discard (Esc)\u{1F}取消（Esc）": "취소 (Esc)",
        "Confirm (Return)\u{1F}确认（回车）": "확인 (Return)",
        "Experimental app volume requires macOS 14.2 or later.\u{1F}实验性应用音量需要 macOS 14.2 或更新版本。": "실험적 앱 음량 기능을 사용하려면 macOS 14.2 이상이 필요합니다.",
        "Choose another process with active audio output.\u{1F}请选择正在输出音频的其他进程。": "오디오를 재생 중인 다른 프로세스를 선택하세요.",
        "This experimental route supports stereo output-only built-in or USB devices. Bluetooth and devices with input channels are not supported.\u{1F}此实验性路由支持仅具备双声道输出的内建或 USB 设备，暂不支持蓝牙或带输入声道的设备。": "이 실험적 경로는 입력 채널이 없는 내장 또는 USB 스테레오 출력 기기를 지원합니다. Bluetooth 및 입력 채널이 있는 기기는 지원하지 않습니다.",
        "This output device does not support app volume routing.\u{1F}此输出设备暂不支持应用音量路由。": "이 출력 기기는 앱 음량 라우팅을 지원하지 않습니다.",
        "This app uses a different output route.\u{1F}此应用使用其他输出路由。": "이 앱은 다른 출력 경로를 사용합니다.",
        "Choose a finite app volume between 0% and 100%.\u{1F}请选择 0% 至 100% 之间的有效应用音量。": "앱 음량을 0%~100% 사이의 유한한 값으로 설정하세요.",
        "Stop the existing route before starting another for this process.\u{1F}请先停止此进程的现有路由，再重新开始。": "이 프로세스에 새 경로를 시작하려면 기존 경로를 먼저 중지하세요.",
        "Allow System Audio Recording if asked, then play audio in the selected app to activate.\u{1F}如有提示，请允许系统音频录制，然后在所选应用中播放音频以激活。": "시스템 오디오 녹음 권한 요청을 허용한 후 선택한 앱에서 오디오를 재생하여 활성화하세요.",
        "App audio routing requires macOS 14.2 or later.\u{1F}应用音频路由需要 macOS 14.2 或更新版本。": "앱 오디오 라우팅을 사용하려면 macOS 14.2 이상이 필요합니다.",
        "This route has already been started.\u{1F}此路由已经启动过。": "이 경로는 이미 시작되었습니다.",
        "macOS did not finish starting audio processing. Cancellation is pending; the original app was not muted. Quit EndfieldCharge if macOS remains unresponsive.\u{1F}macOS 未能完成音频处理启动，正在等待取消；应用原始输出未被静音。若系统持续无响应，请退出 EndfieldCharge。": "macOS에서 오디오 처리 시작을 완료하지 못했습니다. 취소를 기다리는 중이며 원래 앱은 음소거되지 않았습니다. macOS가 계속 응답하지 않으면 EndfieldCharge를 종료하세요.",
        "Waiting for macOS to release the audio route. The app remains responsive; quit EndfieldCharge if audio is affected. No replacement route will start while cleanup is pending.\u{1F}正在等待 macOS 释放音频路由。界面仍可操作；若声音受影响，请退出 EndfieldCharge。清理完成前不会启动替代路由。": "macOS에서 오디오 경로를 해제하기를 기다리는 중입니다. 앱은 계속 응답합니다. 오디오에 문제가 있으면 EndfieldCharge를 종료하세요. 정리가 끝날 때까지 새 경로는 시작되지 않습니다.",
        "This route is already running.\u{1F}此路由已在运行。": "이 경로는 이미 실행 중입니다.",
        "Could not create this app's audio tap. Check System Audio Recording permission in Privacy & Security, then retry.\u{1F}无法创建此应用的音频 Tap，请检查“隐私与安全性”中的“系统音频录制”权限后重试。": "이 앱의 오디오 탭을 생성하지 못했습니다. 개인정보 보호 및 보안에서 시스템 오디오 녹음 권한을 확인한 후 다시 시도하세요.",
        "This macOS audio tap cannot safely switch its mute behavior.\u{1F}此 macOS 音频 Tap 无法安全切换静音行为。": "이 macOS 오디오 탭의 음소거 동작을 안전하게 변경할 수 없습니다.",
        "The route could not be fully removed. Retry Stop; quit EndfieldCharge if audio remains affected.\u{1F}未能完全移除音频路由，请重试停止；若音频仍受影响，请退出 EndfieldCharge。": "경로를 완전히 제거하지 못했습니다. 중지를 다시 시도하세요. 오디오 문제가 계속되면 EndfieldCharge를 종료하세요.",
        "The route was removed, but macOS reported a cleanup error.\u{1F}音频路由已移除，但 macOS 报告了清理错误。": "경로가 제거되었지만 macOS에서 정리 오류가 보고되었습니다.",
        "This experimental route requires the current built-in or USB stereo output, with no input channels. The device may have changed.\u{1F}此实验性路由需要当前内建或 USB 双声道输出设备，且该设备不能带输入声道。设备可能已更改。": "이 실험적 경로는 입력 채널이 없는 현재의 내장 또는 USB 스테레오 출력 기기가 필요합니다. 기기가 변경되었을 수 있습니다.",
        "This experimental route requires the device's standard left/right stereo channel mapping.\u{1F}此实验性路由需要设备使用标准左右双声道映射。": "이 실험적 경로는 기기의 표준 좌우 스테레오 채널 매핑이 필요합니다.",
        "The private audio device did not become ready. Its route was cancelled; try again after the audio device settles.\u{1F}私有音频设备未能就绪，路由已取消。请等待音频设备稳定后重试。": "비공개 오디오 기기가 준비되지 않았습니다. 경로가 취소되었습니다. 오디오 기기가 안정된 후 다시 시도하세요.",
        "This process must output only to the selected device. Processes using another or several devices are not supported.\u{1F}此进程必须仅向所选设备输出，暂不支持使用其他或多个设备的进程。": "이 프로세스는 선택한 기기로만 출력해야 합니다. 다른 기기나 여러 기기를 사용하는 프로세스는 지원하지 않습니다.",
        "The selected audio process changed. Select the app again.\u{1F}所选音频进程已更改，请重新选择应用。": "선택한 오디오 프로세스가 변경되었습니다. 앱을 다시 선택하세요.",
        "The audio device format changed. Start this route again if needed.\u{1F}音频设备格式已更改，如有需要请重新启动此路由。": "오디오 기기 형식이 변경되었습니다. 필요하면 이 경로를 다시 시작하세요.",
        "The audio callback format changed. Stopping processing and restoring direct playback.\u{1F}音频回调格式已更改，正在停止处理并恢复原始播放。": "오디오 콜백 형식이 변경되었습니다. 처리를 중지하고 직접 재생을 복원합니다.",
        "Audio processing stopped responding. Stopping this route.\u{1F}音频处理停止响应，正在停止此路由。": "오디오 처리가 응답하지 않습니다. 이 경로를 중지합니다.",
        "No usable app audio arrived. Allow System Audio Recording, play audio, and try again. The app's original output was not muted.\u{1F}未收到可用的应用音频。请允许系统音频录制、播放音频后重试，应用原始输出未被静音。": "사용 가능한 앱 오디오가 수신되지 않았습니다. 시스템 오디오 녹음을 허용하고 오디오를 재생한 후 다시 시도하세요. 앱의 원래 출력은 음소거되지 않았습니다.",
        "The audio streams changed during startup. Start this route again.\u{1F}音频流在启动过程中发生更改，请重新启动此路由。": "시작 중 오디오 스트림이 변경되었습니다. 이 경로를 다시 시작하세요.",
        "This experimental route requires matching Float32 stereo streams and sample rates. This audio device or format is not supported.\u{1F}此实验性路由需要格式和采样率匹配的 Float32 双声道音频流，暂不支持此音频设备或格式。": "이 실험적 경로는 Float32 스테레오 스트림과 샘플률이 일치해야 합니다. 이 오디오 기기 또는 형식은 지원하지 않습니다.",
        "macOS could not read the audio device ({0}).\u{1F}macOS 无法读取音频设备（{0}）。": "macOS에서 오디오 기기를 읽지 못했습니다({0}).",
        "The audio device changed or could not provide valid route information.\u{1F}音频设备已更改或无法提供有效的路由信息。": "오디오 기기가 변경되었거나 유효한 경로 정보를 제공하지 못했습니다.",
        "macOS could not complete the audio route ({0}).\u{1F}macOS 无法完成音频路由（{0}）。": "macOS에서 오디오 경로를 완료하지 못했습니다({0}).",
        "Audio routing was cancelled.\u{1F}音频路由已取消。": "오디오 라우팅이 취소되었습니다.",
        "Name\u{1F}名称": "이름",
        "Introduction\u{1F}个人介绍": "소개",
        "Awakening day\u{1F}苏醒日": "각성일",
        "Birthday\u{1F}生日": "생일",
        "Authority level\u{1F}权限等级": "권한 레벨",
        "Exploration level\u{1F}探索等级": "탐색 레벨",
        "Operators\u{1F}干员": "오퍼레이터",
        "Weapons\u{1F}武器": "무기",
        "Archives\u{1F}档案": "기록",
        "Background width\u{1F}背景宽度": "배경 너비",
        "Background X\u{1F}背景 X": "배경 X",
        "Background Y\u{1F}背景 Y": "배경 Y",
        "Thumbnail X\u{1F}缩略图 X": "썸네일 X",
        "Thumbnail Y\u{1F}缩略图 Y": "썸네일 Y",
        "Zoom\u{1F}缩放": "확대/축소",
        "Portrait X\u{1F}头像 X": "인물 사진 X",
        "Portrait Y\u{1F}头像 Y": "인물 사진 Y",
        "Personal profile\u{1F}个人名片": "개인 프로필",
        "Change card theme\u{1F}更换名片主题": "카드 테마 변경",
        "Show profile text\u{1F}显示名片文字": "프로필 텍스트 표시",
        "Hide profile text\u{1F}隐藏名片文字": "프로필 텍스트 숨기기",
        "Show awakening day\u{1F}切换为苏醒日": "각성일 표시",
        "Show birthday\u{1F}切换为生日": "생일 표시",
        "Edit personal profile\u{1F}编辑个人名片": "개인 프로필 편집",
        "Edit introduction\u{1F}编辑个人介绍": "소개 편집",
        "Profile storage is unavailable.\u{1F}个人名片存储不可用。": "프로필 저장소를 사용할 수 없습니다.",
        "Use YYYY/MM/DD for awakening day.\u{1F}苏醒日格式为 YYYY/MM/DD。": "각성일을 YYYY/MM/DD 형식으로 입력하세요.",
        "Use MM/DD for birthday.\u{1F}生日格式为 MM/DD。": "생일을 MM/DD 형식으로 입력하세요.",
        "PERSONAL PROFILE\u{1F}个人名片": "개인 프로필",
        "Awakening\u{1F}苏醒日": "각성",
        "REGION CONSTRUCTION\u{1F}地区建设概况": "지역 건설",
        "h\u{1F}小时": "시간",
        "Edit name\u{1F}修改名称": "이름 편집",
        "Edit #\u{1F}修改 #": "# 편집",
        "Change profile picture\u{1F}更换头像": "프로필 사진 변경",
        "Adjust portrait\u{1F}调整头像": "인물 사진 조정",
        "Restore default picture\u{1F}恢复默认头像": "기본 사진 복원",
        "Close\u{1F}关闭": "닫기",
        "Back to card theme\u{1F}返回名片主题": "카드 테마로 돌아가기",
        "Follow HUD theme\u{1F}跟随浮层主题": "HUD 테마 따르기",
        "Card color \u{1F}名片颜色 ": "카드 색상 ",
        "Custom card color\u{1F}自定名片颜色": "사용자 지정 카드 색상",
        "Back to profile menu\u{1F}返回名片菜单": "프로필 메뉴로 돌아가기",
        "Choose background\u{1F}选择背景": "배경 선택",
        "Restore default\u{1F}恢复默认": "기본값 복원",
        "PORTRAIT\u{1F}调整头像": "인물 사진",
        "CARD THEME\u{1F}名片主题": "카드 테마",
        "CARD COLOR\u{1F}名片颜色": "카드 색상",
        "Card theme\u{1F}更换名片主题": "카드 테마",
        "That modifier is not supported.\u{1F}不支持该修饰键。": "이 보조 키는 지원하지 않습니다.",
        "Use one key with one or two modifiers (up to three keys).\u{1F}请使用一个普通键加一至两个修饰键（最多三个键）。": "일반 키 하나와 보조 키 한두 개를 사용하세요(최대 3개 키).",
        "Choose a letter, number, punctuation, arrow, or function key.\u{1F}请选择字母、数字、标点、方向键或功能键。": "문자, 숫자, 문장 부호, 방향키 또는 기능 키를 선택하세요.",
        "That combination is reserved for common macOS or editing commands.\u{1F}该组合用于常见的 macOS 或编辑命令，请选择其他快捷键。": "일반적인 macOS 또는 편집 명령에 예약된 조합입니다.",
        "System interface\u{1F}系统界面": "시스템 인터페이스",
        "The original menu could not be rendered. Please check the log.\u{1F}原始菜单无法渲染，请查看日志。": "원래 메뉴를 렌더링하지 못했습니다. 로그를 확인하세요.",
        "Open battery menu\u{1F}打开电池菜单": "배터리 메뉴 열기",
        "Not selected\u{1F}未选择": "선택되지 않음",
        "Scroll modules up\u{1F}向上滚动模块": "모듈 위로 스크롤",
        "Scroll modules down\u{1F}向下滚动模块": "모듈 아래로 스크롤",
        "No internal battery\u{1F}无内置电池": "내장 배터리 없음",
        "CHARGING\u{1F}正在充电": "충전 중",
        "FULLY CHARGED\u{1F}已充满": "충전 완료",
        "POWER CONNECTED\u{1F}已连接电源": "전원 연결됨",
        "ON BATTERY\u{1F}电池供电": "배터리 사용 중",
        "External power\u{1F}外接电源": "외부 전원",
        "Battery power\u{1F}电池供电": "배터리 전원",
        "Unavailable\u{1F}暂无数据": "데이터 없음",
        "SOURCE  /  \u{1F}电源  /  ": "전원 / ",
        "// BATTERY STATUS\u{1F}// 电池状态": "// 배터리 상태",
        "CLICK OUTSIDE TO CLOSE\u{1F}点击外侧关闭": "바깥쪽을 클릭하여 닫기",
        "Reading storage…\u{1F}正在读取存储…": "저장 공간 읽는 중…",
        "Storage unavailable\u{1F}存储不可用": "저장 공간 확인 불가",
        "Total \u{1F}总计 ": "전체 ",
        "Used \u{1F}已用 ": "사용 중 ",
        "Available \u{1F}可用 ": "사용 가능 ",
        "Refreshing\u{1F}正在刷新": "새로 고치는 중",
        "Storage Settings\u{1F}存储设置": "저장 공간 설정",
        "Refresh storage\u{1F}刷新存储": "저장 공간 새로 고침",
        "Startup disk\u{1F}启动磁盘": "시동 디스크",
        "Total\u{1F}总计": "전체",
        "Used\u{1F}已用": "사용 중",
        "Available\u{1F}可用": "사용 가능",
        " used\u{1F} 已用": " 사용 중",
        "Capacity unavailable\u{1F}容量不可用": "용량 확인 불가",
        "The startup filesystem is unavailable.\u{1F}启动文件系统不可用。": "시동 파일 시스템을 사용할 수 없습니다.",
        "Storage capacity is unavailable.\u{1F}无法读取存储容量。": "저장 공간 용량을 확인할 수 없습니다.",
        "Enter a name of 1–20 characters without line breaks.\u{1F}请输入 1–20 个字符的名称，不含换行。": "줄바꿈 없이 1~20자의 이름을 입력하세요.",
        "Enter a tag of 1–10 characters without spaces or #.\u{1F}请输入 1–10 个字符的编号，不含空格或 #。": "공백이나 # 없이 1~10자의 태그를 입력하세요.",
        "Enter a number within the allowed range.\u{1F}请输入允许范围内的数字。": "허용 범위 내의 숫자를 입력하세요.",
        "Choose a readable image file.\u{1F}请选择可读取的图片文件。": "읽을 수 있는 이미지 파일을 선택하세요.",
        "Choose a portrait no larger than 128 megapixels or 32,768 pixels on either side.\u{1F}请选择不超过 1.28 亿像素、且单边不超过 32,768 像素的头像。": "1억 2,800만 픽셀 이하이며 가로와 세로가 각각 32,768픽셀 이하인 인물 사진을 선택하세요.",
        "The personal card could not be read. The saved data has been preserved.\u{1F}无法读取个人名片，已保留原始数据。": "개인 카드를 읽을 수 없습니다. 저장된 데이터는 보존되었습니다.",
        "This personal card was saved by a newer version of EndfieldHUD.\u{1F}此个人名片由较新版本的 EndfieldHUD 保存。": "이 개인 카드는 더 최신 버전의 EndfieldHUD에서 저장되었습니다.",
        "The personal card changed in another app instance. Restart before editing.\u{1F}个人名片已由另一个应用实例更改，请重启后编辑。": "다른 앱 인스턴스에서 개인 카드가 변경되었습니다. 재시작한 후 편집하세요.",
        "The personal card could not be saved: \u{1F}无法保存个人名片：": "개인 카드를 저장할 수 없습니다: ",
        "Adjust each audio process independently. 100% is full volume and keeps an enabled route running.\u{1F}独立调整每个音频进程。100% 为原始音量，已启用的路由会继续运行。": "각 오디오 프로세스의 음량을 개별적으로 조절합니다. 100%는 최대 음량이며 활성화된 경로를 계속 실행합니다.",
        "Output volume\u{1F}输出音量": "출력 음량",
        "Left/right balance\u{1F}左右声道平衡": "좌우 밸런스",
        " volume\u{1F} 音量": " 음량",
        " Return to 100% to retry cleanup.\u{1F} 回到 100% 可重试清理。": " 100%로 되돌려 정리를 다시 시도하세요.",
        "Adjusts only this audio process; 100% keeps its route running at full volume\u{1F}仅调整此音频进程；100% 保持路由运行并恢复原始音量": "이 오디오 프로세스만 조절합니다. 100%에서는 경로가 최대 음량으로 계속 실행됩니다",
        "Requested volume; waiting for audio processing to start\u{1F}目标音量；正在等待音频处理启动": "요청한 음량입니다. 오디오 처리 시작을 기다리는 중입니다",
        "Waiting for macOS to release this route\u{1F}正在等待 macOS 释放此路由": "macOS에서 이 경로를 해제하기를 기다리는 중입니다",
        "Return to 100% to retry restoring normal playback\u{1F}回到 100% 可重试恢复正常播放": "100%로 되돌려 일반 재생 복원을 다시 시도하세요",
        "No output device\u{1F}无输出设备": "출력 기기 없음",
        "Adjust to enable a temporary audio route; macOS may request System Audio Recording access\u{1F}调整即可启用临时音频路由；macOS 可能请求系统音频录制权限": "음량을 조절하면 임시 오디오 경로가 활성화됩니다. macOS에서 시스템 오디오 녹음 권한을 요청할 수 있습니다",
        "App routing stopped because the output device changed.\u{1F}输出设备已更改，应用混音已停止。": "출력 기기가 변경되어 앱 라우팅이 중지되었습니다.",
        "Choose output device\u{1F}选择输出设备": "출력 기기 선택",
        "Choose input device\u{1F}选择输入设备": "입력 기기 선택",
        "Unmute\u{1F}取消静音": "음소거 해제",
        "Mute\u{1F}静音": "음소거",
        "Headphones / Bluetooth\u{1F}耳机 / 蓝牙": "헤드폰 / Bluetooth",
        "App volume\u{1F}应用音量": "앱 음량",
        ", Selected\u{1F}，已选择": ", 선택됨",
        "Output device\u{1F}输出设备": "출력 기기",
        "Input device\u{1F}输入设备": "입력 기기",
        "Device and app volume\u{1F}设备与应用音量": "기기 및 앱 음량",
        "Choose a connected device\u{1F}选择已连接的设备": "연결된 기기 선택",
        "Output\u{1F}输出": "출력",
        "Input\u{1F}输入": "입력",
        "No device\u{1F}无设备": "기기 없음",
        "Balance\u{1F}平衡": "밸런스",
        "Balance is unavailable for this device\u{1F}此设备不支持声道平衡": "이 기기에서는 밸런스를 조절할 수 없습니다",
        "Balance unavailable\u{1F}声道平衡不可用": "밸런스 조절 불가",
        "Use this device's controls\u{1F}请使用设备自身的音量控制": "기기 자체의 제어 기능을 사용하세요",
        "No headphones or Bluetooth audio devices\u{1F}未连接耳机或蓝牙音频设备": "헤드폰 또는 Bluetooth 오디오 기기 없음",
        "Headphones\u{1F}耳机": "헤드폰",
        " · Output\u{1F} · 输出": " · 출력",
        "Audio app detection requires macOS 14.2 or later\u{1F}音频应用检测需要 macOS 14.2 或更高版本": "오디오 앱을 감지하려면 macOS 14.2 이상이 필요합니다",
        "No adjustable audio apps\u{1F}暂无可调节音量的应用": "조절 가능한 오디오 앱 없음",
        "Starting…\u{1F}正在启动…": "시작 중…",
        "Stopping…\u{1F}正在停止…": "중지 중…",
        "100% to restore\u{1F}回到 100% 恢复": "100%로 복원",
        "Unsupported route\u{1F}暂不支持此路由": "지원하지 않는 경로",
        "No connected devices\u{1F}无已连接设备": "연결된 기기 없음",
        "Countdown\u{1F}倒计时": "카운트다운",
        "Stopwatch\u{1F}秒表": "스톱워치",
        "Pause\u{1F}暂停": "일시 정지",
        "Reset\u{1F}重置": "초기화",
        "Resume\u{1F}继续": "재개",
        "Start\u{1F}开始": "시작",
        "{0} min\u{1F}{0} 分": "{0}분",
        "Use 0:01–1440:00 (min:sec)\u{1F}输入 0:01–1440:00（分:秒）": "0:01~1440:00 형식을 사용하세요(분:초)",
        "Ready\u{1F}就绪": "준비됨",
        "Stopped\u{1F}已结束": "종료됨",
        "Completed\u{1F}已完成": "완료됨",
        "Automatic Focus was interrupted.\u{1F}自动专注模式操作已中断。": "집중 모드 자동 전환이 중단되었습니다.",
        "Open Accessibility Settings\u{1F}打开辅助功能设置": "손쉬운 사용 설정 열기",
        "Automatic Focus requires macOS 11 or later.\u{1F}自动专注模式需要 macOS 11 或更新版本。": "집중 모드 자동 전환을 사용하려면 macOS 11 이상이 필요합니다.",
        "Allow Accessibility to control Focus.\u{1F}允许辅助功能访问以控制专注模式。": "집중 모드를 제어하려면 손쉬운 사용 권한을 허용하세요.",
        "macOS Focus controls are unavailable.\u{1F}无法访问 macOS 专注模式控制。": "macOS 집중 모드 제어 기능을 사용할 수 없습니다.",
        "Automatic Focus could not be confirmed. Check the current Focus.\u{1F}无法确认自动专注模式，请检查当前专注状态。": "집중 모드 자동 전환을 확인하지 못했습니다. 현재 집중 모드를 확인하세요.",
        "Automatic Focus requires macOS 13 or later and Shortcuts.\u{1F}自动专注模式需要 macOS 13 或更新版本及快捷指令。": "집중 모드 자동 전환을 사용하려면 macOS 13 이상 및 단축어 앱이 필요합니다.",
        "Add EndfieldCharge Focus Start and End shortcuts to enable automatic Focus.\u{1F}请添加 EndfieldCharge Focus Start 和 End 快捷指令以启用自动专注模式。": "자동 집중 모드를 활성화하려면 EndfieldCharge Focus Start 및 End 단축어를 추가하세요.",
        "Waiting for Shortcuts; the Focus change is not confirmed yet.\u{1F}正在等待快捷指令，尚未确认专注模式更改。": "단축어를 기다리는 중입니다. 집중 모드 변경이 아직 확인되지 않았습니다.",
        "Shortcuts could not open. Automatic Focus was not started.\u{1F}无法启动快捷指令，自动专注模式未启动。": "단축어를 열지 못했습니다. 집중 모드 자동 전환이 시작되지 않았습니다.",
        "Automatic Focus could not be confirmed. Check the Focus shortcuts and current Focus.\u{1F}无法确认自动专注模式，请检查专注模式快捷指令及当前状态。": "집중 모드 자동 전환을 확인하지 못했습니다. 집중 모드 단축어 및 현재 집중 모드를 확인하세요.",
        "Terrain data could not be loaded.\u{1F}无法载入地形数据。": "지형 데이터를 불러오지 못했습니다.",
        "Country shapes could not be loaded.\u{1F}无法载入地图轮廓。": "국가 경계 데이터를 불러오지 못했습니다.",
        "Zoom in\u{1F}放大": "확대",
        "Zoom out\u{1F}缩小": "축소",
        "Reset zoom to 3×\u{1F}重置缩放至3×": "3배 배율로 초기화",
        "Place pin at map center\u{1F}在地图中心放置标记": "지도 중앙에 핀 놓기",
        "Remove selected pin\u{1F}移除选中标记": "선택한 핀 제거",
        "Pin \u{1F}标记 ": "핀 ",
        "MAP\u{1F}地图": "지도",
        "LOADING TERRAIN\u{1F}载入地形": "지형 불러오는 중",
        "PINS\u{1F}标记": "핀",
    ]

    static let entries: [Entry] = [
        // ActivityMonitorCanvas.swift
        Entry("Overview", "概览", "概覽", "概要"),
        Entry("Apps", "应用", "應用程式", "アプリ"),
        Entry(", descending", "，降序", "，降序", "、降順"),
        Entry(", ascending", "，升序", "，升序", "、昇順"),
        Entry("Sort by ", "排序：", "排序：", "並べ替え："),
        Entry("Read ", "读取 ", "讀取 ", "読み込み "),
        Entry("Write ", "写入 ", "寫入 ", "書き込み "),
        Entry("RAM ", "RAM ", "RAM ", "RAM "),
        Entry("Upload ", "上传 ", "上傳 ", "送信 "),
        Entry("Download ", "下载 ", "下載 ", "受信 "),
        Entry("Disk read ", "磁盘读取 ", "磁碟讀取 ", "ディスク読み込み "),
        Entry("Disk write ", "磁盘写入 ", "磁碟寫入 ", "ディスク書き込み "),
        Entry("App", "应用", "應用程式", "アプリ"),
        Entry("RAM", "RAM", "RAM", "RAM"),
        Entry("Network", "网络", "網路", "ネットワーク"),
        Entry("Disk", "磁盘", "磁碟", "ディスク"),
        Entry("No app readings available", "暂无应用读数", "暫無應用程式讀值", "アプリの使用状況を取得できません"),
        Entry("R ", "读 ", "讀 ", "読込 "),
        Entry("W ", "写 ", "寫 ", "書込 "),
        Entry("Disk I/O", "磁盘 I/O", "磁碟 I/O", "ディスク I/O"),
        Entry("TOTAL LOAD", "总负载", "總負載", "合計負荷"),
        Entry("USED / TOTAL", "已用 / 总计", "已用 / 總計", "使用中 / 合計"),
        Entry("UP / DOWN", "上传 / 下载", "上傳 / 下載", "送信 / 受信"),
        Entry("READ / WRITE", "读取 / 写入", "讀取 / 寫入", "読み込み / 書き込み"),
        Entry("Compressed ", "压缩 ", "壓縮 ", "圧縮済み "),
        // AppDelegate.swift
        Entry("Settings", "设置", "設定", "設定"),
        Entry("Open overlay", "打开浮层", "開啟浮層", "HUDを開く"),
        Entry("Settings…", "设置…", "設定…", "設定…"),
        Entry("Preview charging effect", "预览充电效果", "預覽充電效果", "充電エフェクトをプレビュー"),
        Entry("About EndfieldHUD", "关于 EndfieldHUD", "關於 EndfieldHUD", "EndfieldHUDについて"),
        Entry("Check for Updates…", "检查更新…", "檢查更新…", "アップデートを確認…"),
        Entry("Quit EndfieldHUD", "退出 EndfieldHUD", "結束 EndfieldHUD", "EndfieldHUDを終了"),
        Entry("Edit", "编辑", "編輯", "編集"),
        Entry("Cut", "剪切", "剪下", "切り取り"),
        Entry("Copy", "复制", "複製", "コピー"),
        Entry("Paste", "粘贴", "貼上", "ペースト"),
        Entry("Select All", "全选", "全選", "すべてを選択"),
        Entry("Update available", "发现新版本", "發現新版本", "アップデートがあります"),
        Entry("Checking for updates…", "正在检查更新…", "正在檢查更新…", "アップデートを確認中…"),
        Entry("Active", "进行中", "進行中", "実行中"),
        Entry("Paused", "已暂停", "已暫停", "一時停止中"),
        Entry("Stopped", "已停止", "已停止", "停止済み"),
        Entry("Countdown complete", "倒计时结束", "倒計時結束", "カウントダウン終了"),
        Entry("Work Mode", "工作模式", "工作模式", "作業モード"),
        Entry("Unknown charge", "电量未知", "電量未知", "バッテリー残量不明"),
        Entry("Charging", "正在充电", "正在充電", "充電中"),
        Entry("Power connected", "已连接电源", "已連接電源", "電源に接続済み"),
        Entry("On battery", "使用电池", "使用電池", "バッテリー使用中"),
        Entry("No internal battery · Preview available", "无内置电池 · 可预览效果", "無內建電池 · 可預覽效果", "内蔵バッテリーなし · プレビュー可能"),
        // AppShortcutCanvas.swift
        Entry("Edit app shortcut", "编辑应用快捷方式", "編輯應用程式捷徑", "アプリのショートカットを編集"),
        Entry("Application shortcuts", "应用快捷方式", "應用程式捷徑", "アプリのショートカット"),
        Entry("Shortcut storage is unavailable.", "快捷方式存储不可用。", "捷徑儲存不可用。", "ショートカットの保存領域を利用できません。"),
        Entry("Choose one application to customize.", "请选择一个应用进行设置。", "請選擇一個應用程式進行設定。", "カスタマイズするアプリを1つ選択してください。"),
        Entry("Choose application", "选择应用", "選擇應用程式", "アプリを選択"),
        Entry("Rename: ", "重命名：", "重命名：", "名前を変更："),
        Entry(", selected", "，已选择", "，已選擇", "、選択済み"),
        Entry("Cancel", "取消", "取消", "キャンセル"),
        Entry("Save shortcut", "保存快捷方式", "儲存捷徑", "ショートカットを保存"),
        Entry("Open ", "打开 ", "開啟 ", "開く："),
        Entry("Edit ", "编辑 ", "編輯 ", "編集："),
        Entry("Remove shortcut: ", "移除快捷方式：", "移除捷徑：", "ショートカットを削除："),
        Entry("APPLICATIONS", "应用快捷方式", "應用程式捷徑", "アプリのショートカット"),
        Entry("+ Choose app", "+ 选择应用", "+ 選擇應用程式", "+ アプリを選択"),
        Entry("Shortcut name", "快捷方式名称", "捷徑名稱", "ショートカット名"),
        Entry("ICON", "图标", "圖示", "アイコン"),
        // AppShortcutLauncher.swift
        Entry("macOS did not return an application.", "macOS 未返回应用。", "macOS 未返回應用程式。", "macOSからアプリが返されませんでした。"),
        // AppShortcutStore.swift
        Entry("App icon", "原始图标", "原始圖示", "アプリのアイコン"),
        Entry("Bolt", "闪电", "閃電", "稲妻"),
        Entry("Star", "星形", "星形", "星"),
        Entry("Terminal", "终端", "終端", "ターミナル"),
        Entry("Globe", "地球", "地球", "地球"),
        Entry("Folder", "文件夹", "資料夾", "フォルダ"),
        Entry("Music", "音乐", "音樂", "音楽"),
        Entry("Play", "播放", "播放", "再生"),
        Entry("Brush", "画笔", "畫筆", "ブラシ"),
        Entry("Code", "代码", "代碼", "コード"),
        Entry("Game", "游戏", "遊戲", "ゲーム"),
        Entry("Camera", "相机", "相機", "カメラ"),
        Entry("Grid", "网格", "網格", "グリッド"),
        Entry("Text bubble", "文字气泡", "文字氣泡", "吹き出し"),
        Entry("Choose a macOS application (.app) with an available executable.", "请选择包含可用执行文件的 macOS 应用程序（.app）。", "請選擇包含可用執行檔的 macOS 應用程式（.app）。", "実行可能ファイルを含むmacOSアプリ（.app）を選択してください。"),
        Entry("Enter a name of 1–128 characters without line breaks.", "请输入 1–128 个字符的名称，不含换行。", "請輸入 1–128 個字符的名稱，不含換行。", "改行を含まない1〜128文字の名前を入力してください。"),
        Entry("This application is already saved. Edit its existing shortcut instead.", "此应用已添加，请编辑现有快捷方式。", "此應用程式已新增，請編輯現有捷徑。", "このアプリは追加済みです。既存のショートカットを編集してください。"),
        Entry("This app shortcut is no longer available.", "此应用快捷方式已不存在。", "此應用程式捷徑已不存在。", "このアプリのショートカットは存在しません。"),
        Entry("A different application now occupies this location. Choose the application again.", "此位置的应用已更改，请重新选择应用。", "此位置的應用程式已更改，請重新選擇應用程式。", "この場所のアプリが変更されました。アプリを選択し直してください。"),
        Entry("The saved app shortcuts could not be read. The original data has been preserved.", "无法读取应用快捷方式，原始数据已保留。", "無法讀取應用程式捷徑，原始資料已保留。", "保存済みのアプリのショートカットを読み込めませんでした。元のデータは保持されています。"),
        Entry("These app shortcuts were saved by a newer version of EndfieldCharge.", "这些快捷方式由较新版本的 EndfieldCharge 保存。", "這些捷徑由較新版本的 EndfieldCharge 儲存。", "これらのショートカットは新しいバージョンのEndfieldChargeで保存されています。"),
        Entry("App shortcuts changed outside this window. Restart EndfieldCharge before editing.", "应用快捷方式已在外部更改，请重启 EndfieldCharge 后再编辑。", "應用程式捷徑已在外部更改，請重啟 EndfieldCharge 後再編輯。", "アプリのショートカットが外部で変更されました。EndfieldChargeを再起動してから編集してください。"),
        Entry("The application is unavailable: ", "应用不可用：", "應用程式不可用：", "アプリを利用できません："),
        Entry("App shortcuts could not be saved or opened: ", "无法保存或打开应用快捷方式：", "無法儲存或開啟應用程式捷徑：", "アプリのショートカットを保存または開くことができません："),
        // AudioDeviceController.swift
        Entry("Audio device information is unavailable.", "音频设备信息不可用。", "音訊裝置資訊不可用。", "オーディオデバイスの情報を取得できません。"),
        Entry("This device does not support this control.", "此设备不支持该控制。", "此裝置不支援該控制。", "このデバイスはこの操作に対応していません。"),
        Entry("The audio device changed. Try the control again.", "音频设备已更改，请重试。", "音訊裝置已更改，請重試。", "オーディオデバイスが変更されました。もう一度操作してください。"),
        Entry("The audio control value is invalid.", "音频控制值无效。", "音訊控制值無效。", "オーディオ設定値が無効です。"),
        Entry("The device could not confirm the audio change.", "无法确认设备的音频更改。", "無法確認裝置的音訊更改。", "デバイスのオーディオ設定の変更を確認できませんでした。"),
        Entry("macOS could not complete the audio operation", "macOS 无法完成音频操作", "macOS 無法完成音訊操作", "macOSでオーディオ操作を完了できませんでした"),
        Entry("The audio change failed and could not be fully restored. Check the current device levels.", "音频更改失败且未能完全恢复，请检查当前设备音量。", "音訊更改失敗且未能完全恢復，請檢查當前裝置音量。", "オーディオ設定の変更に失敗し、完全に復元できませんでした。現在のデバイスの音量を確認してください。"),
        Entry("Audio device", "音频设备", "音訊裝置", "オーディオデバイス"),
        Entry("Active audio apps require macOS 14.2 or later and compatible Core Audio support.", "活跃音频应用需要 macOS 14.2 或更新版本及兼容的 Core Audio 支持。", "活躍音訊應用程式需要 macOS 14.2 或更新版本及相容的 Core Audio 支援。", "音声を再生中のアプリの検出にはmacOS 14.2以降と対応するCore Audio機能が必要です。"),
        Entry("Active audio app information is unavailable.", "活跃音频应用信息不可用。", "活躍音訊應用程式資訊不可用。", "音声を再生中のアプリの情報を取得できません。"),
        Entry("Some audio changes could not be observed. Reopen Volume to refresh.", "无法监听部分音频更改，请重新打开音量模块刷新。", "無法監聽部分音訊更改，請重新開啟音量模組重新整理。", "一部のオーディオ設定の変更を検出できませんでした。音量を開き直して更新してください。"),
        // ChargeIndicatorView.swift
        Entry("CHARGE MODE", "超充模式", "超充模式", "充電モード"),
        Entry("BATTERY MODE", "电池模式", "電池模式", "バッテリーモード"),
        Entry("Battery unavailable", "电量不可用", "電量不可用", "バッテリー残量を取得できません"),
        Entry(", Preview", "，预览", "，預覽", "、プレビュー"),
        // ClipboardCanvas.swift
        Entry("Image · ", "图片 · ", "圖片 · ", "画像 · "),
        Entry("Copy: ", "复制：", "複製：", "コピー："),
        Entry("{0} / {1} items · Click to copy", "{0} / {1} 项 · 点击复制", "{0} / {1} 項 · 點擊複製", "{0} / {1}件 · クリックでコピー"),
        Entry("Copied", "已复制", "已複製", "コピー済み"),
        Entry("Could not restore this item", "无法恢复此项目", "無法恢復此項目", "この項目を復元できませんでした"),
        Entry("Unpin: ", "取消固定：", "取消固定：", "固定を解除："),
        Entry("Pin: ", "固定：", "固定：", "固定："),
        Entry("Delete: ", "删除：", "刪除：", "削除："),
        Entry("Clear", "清空", "清空", "消去"),
        Entry("Clear unpinned", "清空未固定项", "清空未固定項", "固定していない項目を消去"),
        Entry("Previous page", "上一页", "上一頁", "前のページ"),
        Entry("Next page", "下一页", "下一頁", "次のページ"),
        Entry("Your clipboard history appears here", "剪贴板历史将在此显示", "剪貼簿歷史將在此顯示", "クリップボードの履歴がここに表示されます"),
        Entry("Copy text, links, images or files", "复制文字、链接、图片或文件", "複製文字、連結、圖片或檔案", "テキスト、リンク、画像、ファイルをコピー"),
        Entry("Text", "文字", "文字", "テキスト"),
        Entry("Link", "链接", "連結", "リンク"),
        Entry("Image", "图片", "圖片", "画像"),
        Entry("Files", "文件", "檔案", "ファイル"),
        Entry(" · Pinned", " · 已固定", " · 已固定", " · 固定済み"),
        Entry("Pinned items will stay", "保留已固定项目", "保留已固定項目", "固定済みの項目は保持されます"),
        // ClipboardStore.swift
        Entry("Keep at least one clipboard item.", "请至少保留一个剪贴板项目。", "請至少保留一個剪貼簿項目。", "クリップボードの項目は1件以上保持してください。"),
        Entry("Unpin some items before reducing the cache size.", "请先取消固定部分项目，再缩小缓存容量。", "請先取消固定部分項目，再縮小快取容量。", "キャッシュ容量を減らす前に、一部の項目の固定を解除してください。"),
        Entry("The cache is full of pinned items. Unpin or remove an item to capture more.", "缓存已被固定项目占满，请取消固定或移除项目后继续记录。", "快取已被固定項目佔滿，請取消固定或移除項目後繼續記錄。", "固定済みの項目でキャッシュがいっぱいです。固定を解除するか項目を削除してください。"),
        Entry("This item could not be copied. Try again.", "无法复制此项目，请重试。", "無法複製此項目，請重試。", "この項目をコピーできませんでした。もう一度お試しください。"),
        Entry("Image", "图像", "圖像", "画像"),
        Entry("Text over 1 MB was skipped.", "已跳过超过 1 MB 的文本。", "已跳過超過 1 MB 的文字。", "1 MBを超えるテキストはスキップしました。"),
        Entry("An image over 64 MB was skipped.", "已跳过超过 64 MB 的图像。", "已跳過超過 64 MB 的圖像。", "64 MBを超える画像はスキップしました。"),
        Entry("An image over 100 megapixels was skipped.", "已跳过超过 1 亿像素的图像。", "已跳過超過 1 億像素的圖像。", "1億画素を超える画像はスキップしました。"),
        Entry("This file selection is too large to cache.", "此文件选择过大，无法缓存。", "此檔案選擇過大，無法快取。", "選択したファイルが大きすぎるためキャッシュできません。"),
        // EventLogCanvas.swift
        Entry("Clear log", "清空日志", "清空記錄", "ログを消去"),
        // FileShelfCanvas.swift
        Entry("Unavailable", "不可用", "不可用", "利用不可"),
        Entry("Clear shelf", "清空暂存架", "清空暫存架", "シェルフを消去"),
        Entry("Add files", "添加文件", "新增檔案", "ファイルを追加"),
        Entry("Clear all", "清空", "清空", "すべてを消去"),
        Entry("Quick Look: ", "快速查看：", "快速查看：", "クイックルック："),
        Entry("Reveal in Finder: ", "在访达中显示：", "在Finder中顯示：", "Finderで表示："),
        Entry("Remove from shelf: ", "从暂存架移除：", "從暫存架移除：", "シェルフから削除："),
        Entry("Video", "视频", "影片", "動画"),
        Entry("Archive", "压缩文件", "壓縮檔案", "圧縮ファイル"),
        Entry("File", "文件", "檔案", "ファイル"),
        Entry("Drop files or folders here", "将文件或文件夹拖放到此处", "將檔案或資料夾拖放到此處", "ファイルやフォルダをここにドロップ"),
        Entry("Keep references. Drag them out whenever you need.", "仅保留引用，可随时拖出使用。", "僅保留引用，可隨時拖出使用。", "参照を保存し、必要なときにドラッグして取り出せます。"),
        Entry("Release to keep file references", "松开以暂存文件引用", "松開以暫存檔案引用", "ドロップしてファイルの参照を保存"),
        Entry("Files stay in their original locations", "文件保留在原位置", "檔案保留在原位置", "ファイルは元の場所に保持されます"),
        Entry("{0} selected · Drag to copy", "已选 {0} 项 · 拖出以复制", "已選 {0} 項 · 拖出以複製", "{0}件を選択 · ドラッグでコピー"),
        Entry("{0} items · Shift-click to select", "{0} 项 · Shift 点击多选", "{0} 項 · Shift 點擊多選", "{0}件 · Shiftクリックで複数選択"),
        Entry("Clear references only?", "仅清空文件引用？", "僅清空檔案引用？", "ファイルの参照を消去しますか？"),
        Entry("File shelf storage is unavailable.", "文件暂存架存储不可用。", "檔案暫存架儲存不可用。", "ファイルシェルフの保存領域を利用できません。"),
        // FileShelfStore.swift
        Entry("The saved file shelf could not be read. Its original data has been preserved.", "无法读取暂存架数据，原始数据已保留。", "無法讀取暫存架資料，原始資料已保留。", "保存済みのファイルシェルフを読み込めませんでした。元のデータは保持されています。"),
        Entry("This file shelf was saved by a newer version of EndfieldCharge.", "此暂存架由较新版本的 EndfieldCharge 保存。", "此暫存架由較新版本的 EndfieldCharge 儲存。", "このファイルシェルフは新しいバージョンのEndfieldChargeで保存されています。"),
        Entry("The saved shelf changed outside this window. Restart EndfieldCharge before making changes.", "暂存架数据已在外部更改，请重新启动 EndfieldCharge 后再编辑。", "暫存架資料已在外部更改，請重新啟動 EndfieldCharge 後再編輯。", "保存済みのシェルフが外部で変更されました。EndfieldChargeを再起動してから編集してください。"),
        Entry("Choose a file or folder that is available on this Mac.", "请选择此 Mac 上可访问的文件或文件夹。", "請選擇此 Mac 上可訪問的檔案或資料夾。", "このMacでアクセスできるファイルまたはフォルダを選択してください。"),
        Entry("This item is no longer on the shelf.", "此项目已不在暂存架中。", "此項目已不在暫存架中。", "この項目はシェルフに存在しません。"),
        Entry("The original item is unavailable. A different item now occupies its old location.", "原始项目不可用，其他项目已占用了原来的位置。", "原始項目不可用，其他項目已佔用了原來的位置。", "元の項目を利用できません。元の場所に別の項目が存在します。"),
        Entry("This item is unavailable: ", "此项目不可用：", "此項目不可用：", "この項目を利用できません："),
        Entry("The file shelf could not be saved or opened: ", "无法保存或打开暂存架：", "無法儲存或開啟暫存架：", "ファイルシェルフを保存または開くことができません："),
        // GlobalShortcutController.swift
        Entry("Press your new shortcut. Escape cancels.", "请按新的快捷键，Escape 取消。", "請按新的快速鍵，Escape 取消。", "新しいショートカットキーを押してください。Escでキャンセルします。"),
        Entry("{0} is stopped.", "{0} 已停用。", "{0} 已停用。", "{0}は無効です。"),
        Entry("{0} is ready, including in text fields.", "{0} 已就绪，在文本框中也可使用。", "{0} 已就緒，在文字框中也可使用。", "{0}はテキスト欄でも使用できます。"),
        Entry("{0} is unavailable or in use. Open from the menu bar.", "{0} 不可用或已被占用，请从菜单栏打开浮层。", "{0} 不可用或已被佔用，請從選單欄開啟浮層。", "{0}は利用できないか使用中です。メニューバーから開いてください。"),
        Entry("Could not register the shortcut. Your previous shortcut is unchanged.", "无法注册快捷键，原快捷键保持不变。", "無法註冊快速鍵，原快速鍵保持不變。", "ショートカットを登録できませんでした。以前のショートカットは保持されています。"),
        Entry("That shortcut is already in use or unavailable. Choose another combination.", "该快捷键已被占用或不可用，请选择其他组合。", "該快速鍵已被佔用或不可用，請選擇其他組合。", "このショートカットは使用中か利用できません。別の組み合わせを選択してください。"),
        Entry("macOS shortcut conflicts could not be checked. Try again.", "暂时无法检查 macOS 快捷键冲突，请重试。", "暫時無法檢查 macOS 快速鍵衝突，請重試。", "macOSのショートカットの競合を確認できませんでした。もう一度お試しください。"),
        Entry("That shortcut is enabled in macOS Keyboard Shortcuts. Choose another combination.", "该快捷键已在 macOS 键盘快捷键中启用，请选择其他组合。", "該快速鍵已在 macOS 鍵盤快速鍵中啟用，請選擇其他組合。", "このショートカットはmacOSのキーボードショートカットで有効です。別の組み合わせを選択してください。"),
        // HUDAppShortcutInteraction.swift
        Entry("Choose an application", "选择应用", "選擇應用程式", "アプリを選択"),
        Entry("Choose", "选择", "選擇", "選択"),
        Entry("Return applies the name. Save shortcut stores your changes.", "回车应用名称，点击保存快捷方式以保存修改。", "按 Return 套用名稱，按一下「儲存捷徑」以儲存變更。", "Returnで名前を適用します。「ショートカットを保存」で変更を保存します。"),
        // HUDApplicationIcon.swift
        Entry("Battery", "电池", "電池", "バッテリー"),
        Entry("Originium", "源石", "源石", "源石"),
        Entry("Orundum", "合成玉", "合成玉", "合成玉"),
        Entry("Perlica", "佩丽卡", "佩麗卡", "ペリカ"),
        Entry("Rhodes Island", "罗德岛", "羅德島", "ロドス・アイランド"),
        Entry("Babel", "巴别塔", "巴別塔", "バベル"),
        Entry("Rhine Lab", "莱茵生命", "萊茵生命", "ライン生命"),
        Entry("Blacksteel", "黑钢国际", "黑鋼國際", "ブラックスチール"),
        Entry("Penguin Logistics", "企鹅物流", "企鵝物流", "ペンギン急便"),
        Entry("Elite Operators", "精英干员", "精英乾員", "エリートオペレーター"),
        Entry("Reserve Team A4", "预备行动组 A4", "預備行動組 A4", "予備隊A4"),
        Entry("Reserve Team A6", "预备行动组 A6", "預備行動組 A6", "予備隊A6"),
        Entry("Human Resources", "人力资源部", "人力資源部", "人事部"),
        Entry("Rim Billiton", "雷姆必拓", "雷姆必拓", "レム・ビリトン"),
        Entry("Kjerag", "谢拉格", "謝拉格", "イェラグ"),
        Entry("Ursus Student Group", "乌萨斯学生自治团", "烏薩斯學生自治團", "ウルサス学生自治団"),
        Entry("Obsidian Festival", "黑曜石音乐节", "黑曜石音樂節", "オブシディアンフェスティバル"),
        Entry("Dossoles", "多索雷斯", "多索雷斯", "ドッソレス"),
        Entry("Contingency Contract", "危机合约", "危機合約", "危機契約"),
        Entry("Ambience Synesthesia", "音律联觉", "音律聯覺", "音律聯覚"),
        Entry("Coral Coast", "珊瑚海岸", "珊瑚海岸", "コーラルコースト"),
        Entry("Vitafield", "生命之地", "生命之地", "ヴィータフィールド"),
        Entry("Contingency Contract: Barrenland", "危机合约：荒芜行动", "危機合約：荒蕪行動", "危機契約：荒廃"),
        Entry("Contingency Contract: Pyrite", "危机合约：黄铁行动", "危機合約：黃鐵行動", "危機契約：黄鉄"),
        Entry("Contingency Contract: Cinder", "危机合约：燃灰行动", "危機合約：燃灰行動", "危機契約：燃灰"),
        Entry("Contingency Contract: Lead Seal", "危机合约：铅封行动", "危機合約：鉛封行動", "危機契約：鉛封"),
        Entry("Contingency Contract: Spectrum", "危机合约：光谱行动", "危機合約：光譜行動", "危機契約：分光"),
        Entry("Contingency Contract: Pine Soot", "危机合约：松烟行动", "危機合約：松煙行動", "危機契約：松煙"),
        Entry("Rhodes Kitchen", "罗德厨房", "羅德廚房", "ロドスキッチン"),
        Entry("Cambrian", "寒武纪", "寒武紀", "カンブリアン"),
        Entry("Marthe", "玛尔特", "瑪爾特", "マルト"),
        Entry("Icefield Messenger", "冰原信使", "冰原信使", "アイスフィールドメッセンジャー"),
        // HUDChargeBadge.swift
        Entry("Power / Device Battery", "电量 / 设备电池", "電量 / 裝置電池", "電源 / デバイスのバッテリー"),
        // HUDClipboardInteraction.swift
        Entry(". Arrow keys select; Return copies; Delete removes the cached item.", "。方向键选择，回车复制，Delete 删除缓存项目。", "。方向鍵選擇，Return複製，Delete 刪除快取項目。", "。矢印キーで選択、Returnでコピー、Deleteでキャッシュから削除します。"),
        // HUDDisplayPolicy.swift
        Entry("Pointer display", "鼠标所在显示器", "滑鼠所在顯示器", "ポインタのあるディスプレイ"),
        Entry("Main display", "主显示器", "主顯示器", "メインディスプレイ"),
        Entry("Saved display", "已选显示器", "已選顯示器", "保存済みのディスプレイ"),
        Entry(" (disconnected)", "（未连接）", "（未連接）", "（未接続）"),
        // HUDFileShelfInteraction.swift
        Entry("Add to Temporary File Shelf", "添加到文件暂存架", "新增到檔案暫存架", "一時ファイルシェルフに追加"),
        Entry("Add references", "添加引用", "新增引用", "参照を追加"),
        Entry("Quick Look could not open. Select the file and try again.", "无法打开快速查看，请选中文件后重试。", "無法開啟快速查看，請選中檔案後重試。", "クイックルックを開けませんでした。ファイルを選択してもう一度お試しください。"),
        Entry("Shift-click selects a range to drag together. Space previews the selected file. Command-R reveals it in Finder. Delete removes only selected shelf references.", "Shift 点击多选并一同拖出。空格键预览所选文件，Command-R 在访达中显示，Delete 仅移除所选暂存架引用。", "Shift 點擊多選並一同拖出。空白鍵預覽所選檔案，Command-R 在Finder中顯示，Delete 僅移除所選暫存架引用。", "Shiftクリックで範囲を選択し、まとめてドラッグできます。Spaceでプレビュー、Command-RでFinderに表示、Deleteで選択したシェルフの参照だけを削除します。"),
        Entry("Selected", "已选择", "已選擇", "選択済み"),
        // HUDIdentityCard.swift
        Entry("Authority", "权限等级", "權限等級", "権限レベル"),
        Entry("MAX", "满级", "滿級", "最大"),
        // HUDModule.swift
        Entry("Notes", "便笺", "便箋", "メモ"),
        Entry("Temporary File Shelf", "文件暂存架", "檔案暫存架", "一時ファイルシェルフ"),
        Entry("Clipboard Cache", "剪贴板", "剪貼簿", "クリップボード"),
        Entry("Volume", "音量", "音量", "音量"),
        Entry("Event Log", "事件日志", "事件記錄", "イベントログ"),
        Entry("Map", "地图", "地圖", "マップ"),
        Entry("+ Add App", "+ 添加应用", "+ 新增程式", "+ アプリを追加"),
        Entry("System", "系统", "系統", "システム"),
        Entry("Display", "显示", "顯示", "表示"),
        Entry("Hotkeys", "快捷键", "快速鍵", "ショートカット"),
        Entry("About", "关于", "關於", "このアプリについて"),
        Entry("Storage", "存储", "儲存", "ストレージ"),
        Entry("Activity Monitor", "活动监视器", "活動監視器", "アクティビティモニタ"),
        Entry("Power", "电源", "電源", "電源"),
        Entry("Personal Profile", "个人名片", "個人名片", "プロフィール"),
        Entry("Power / Device Battery", "电源 / 设备电量", "電源 / 裝置電量", "電源 / デバイスのバッテリー"),
        // HUDModuleContent.swift
        Entry("Not configured yet", "尚未配置", "尚未配置", "未設定"),
        // HUDNavigation.swift
        Entry("Device Battery", "设备电量", "裝置電量", "デバイスのバッテリー"),
        // HUDNotesInteraction.swift
        Entry("Edit text note", "编辑文字便笺", "編輯文字便箋", "テキストメモを編集"),
        Entry("Edit checklist item", "编辑待办事项", "編輯待辦事項", "チェックリストの項目を編集"),
        Entry("Escape or Command-Return saves. Text notes support multiple lines.", "按 Esc 或 Command-Return 保存。文字便笺支持多行。", "按 Esc 或 Command-Return 儲存。文字便箋支援多行。", "EscまたはCommand-Returnで保存します。テキストメモは複数行に対応しています。"),
        Entry("Add image notes", "添加图片便笺", "新增圖片便箋", "画像メモを追加"),
        Entry("Add images", "添加图片", "新增圖片", "画像を追加"),
        // HUDPersonalProfileInteraction.swift
        Entry("Choose profile picture", "选择头像", "選擇頭像", "プロフィール画像を選択"),
        Entry("Choose profile background", "选择名片背景", "選擇名片背景", "プロフィールの背景を選択"),
        Entry("Card color", "名片颜色", "名片顏色", "カードの色"),
        Entry("Return saves. Escape cancels.", "回车保存，Esc 取消。", "Return儲存，Esc 取消。", "Returnで保存、Escでキャンセルします。"),
        // HUDQuitConfirmationView.swift
        Entry("Quit EndfieldHUD?", "退出 EndfieldHUD？", "結束 EndfieldHUD？", "EndfieldHUDを終了しますか？"),
        Entry("The application will quit after the HUD closes.", "界面收起后，将退出应用。", "介面收起後，將結束應用程式。", "HUDが閉じた後にアプリを終了します。"),
        Entry("Quit", "退出", "結束", "終了"),
        Entry("Cancel quitting EndfieldHUD", "取消退出 EndfieldHUD", "取消結束 EndfieldHUD", "EndfieldHUDの終了をキャンセル"),
        Entry("Quit EndfieldHUD application", "退出 EndfieldHUD 应用", "結束 EndfieldHUD 應用程式", "EndfieldHUDアプリを終了"),
        // HUDScaleSafetyView.swift
        Entry("Keep this position?", "保留此位置？", "保留此位置？", "この位置を保持しますか？"),
        Entry("Keep this UI scale?", "保留此缩放？", "保留此縮放？", "この表示倍率を保持しますか？"),
        Entry("Keep this position? Reverts in {0}s", "保留此位置？{0} 秒后自动恢复", "保留此位置？{0} 秒後自動恢復", "この位置を保持しますか？{0}秒後に元に戻ります"),
        Entry("Keep this UI scale? Reverts in {0}s", "保留此缩放？{0} 秒后自动恢复", "保留此縮放？{0} 秒後自動恢復", "この表示倍率を保持しますか？{0}秒後に元に戻ります"),
        Entry("Keep ↵", "保留 ↵", "保留 ↵", "保持 ↵"),
        Entry("Revert ⎋", "恢复 ⎋", "恢復 ⎋", "元に戻す ⎋"),
        // HUDSettingsCanvas.swift
        Entry("Disconnected · using pointer display", "未连接 · 暂用鼠标所在显示器", "未連接 · 暫用滑鼠所在顯示器", "未接続 · ポインタのある画面を使用中"),
        Entry("Language", "语言", "語言", "言語"),
        Entry("Launch at login", "登录时启动", "登入時啟動", "ログイン時に起動"),
        Entry("Close when focus lost", "失去焦点时关闭", "失去焦點時關閉", "フォーカスを失ったら閉じる"),
        Entry("Display", "显示器", "顯示器", "ディスプレイ"),
        Entry("Ambient animation", "持续环境动画", "持續環境動畫", "環境アニメーション"),
        Entry("Battery alerts", "电池提醒", "電池提醒", "バッテリー通知"),
        Entry("Restore default settings", "恢复默认设置", "恢復預設設定", "設定を初期状態に戻す"),
        Entry("Display method", "显示方式", "顯示方式", "表示方法"),
        Entry("Always", "始终显示", "始終顯示", "常に表示"),
        Entry("Power changes", "充电状态变化", "充電狀態變化", "電源状態の変化時"),
        Entry("Display duration", "显示时长", "顯示時長", "表示時間"),
        Entry("Display position", "显示位置", "顯示位置", "表示位置"),
        Entry("Top center", "顶部居中", "頂部居中", "上部中央"),
        Entry("Custom", "自定", "自定", "カスタム"),
        Entry("Edit position", "编辑位置", "編輯位置", "位置を編集"),
        Entry("Size", "大小", "大小", "サイズ"),
        Entry("UI scale", "界面缩放", "介面縮放", "表示倍率"),
        Entry("HUD position X", "界面位置 X", "介面位置 X", "HUDの位置 X"),
        Entry("HUD position Y", "界面位置 Y", "介面位置 Y", "HUDの位置 Y"),
        Entry("Parallax intensity", "视差强度", "視差強度", "視差の強さ"),
        Entry("Perspective intensity", "透视强度", "透視強度", "遠近感の強さ"),
        Entry("Background brightness", "背景亮度", "背景亮度", "背景の明るさ"),
        Entry("Blur amount", "模糊程度", "模糊程度", "ぼかしの強さ"),
        Entry("Reduce Motion", "减少动态效果", "減少動態效果", "視差効果を減らす"),
        Entry("Theme", "主题", "主題", "テーマ"),
        Entry("Time format", "时间格式", "時間格式", "時刻表示"),
        Entry("24-hour", "24 小时制", "24 小時制", "24時間表示"),
        Entry("12-hour AM/PM", "12 小时制 AM/PM", "12 小時制 AM/PM", "12時間表示 AM/PM"),
        Entry("App / menu bar icon", "应用 / 菜单栏图标", "應用程式 / 選單欄圖示", "アプリ / メニューバーアイコン"),
        Entry("Theme color", "主题颜色", "主題顏色", "テーマカラー"),
        Entry("Battery alert", "电池提醒", "電池提醒", "バッテリー通知"),
        Entry("Low Power visual mode", "低功耗视觉模式", "低功耗視覺模式", "省電力表示モード"),
        Entry("Summon HUD", "呼出界面", "呼出介面", "HUDを呼び出す"),
        Entry("Press shortcut…", "请按快捷键…", "請按快速鍵…", "キーを押してください…"),
        Entry("Restore default hotkey", "恢复默认快捷键", "恢復預設快速鍵", "ショートカットを初期状態に戻す"),
        Entry("Check for updates", "检查更新", "檢查更新", "アップデートを確認"),
        Entry("Latest GitHub release", "GitHub 最新版本", "GitHub 最新版本", "GitHubの最新リリース"),
        Entry("Install updates automatically", "自动安装更新", "自動安裝更新", "更新を自動インストール"),
        Entry("Author", "作者", "作者", "作者"),
        Entry("Not configured", "尚未设置", "尚未設定", "未設定"),
        Entry("License", "许可证", "授權條款", "ライセンス"),
        Entry("Cancel restore", "取消恢复", "取消恢復", "リセットをキャンセル"),
        Entry("Restore defaults", "恢复默认设置", "恢復預設設定", "初期設定に戻す"),
        Entry("Back", "返回", "返回", "戻る"),
        Entry("On", "开", "開", "オン"),
        Entry("Off", "关", "關", "オフ"),
        Entry("Custom color wheel", "自定义色轮", "自定義色輪", "カスタムカラーホイール"),
        Entry("Cancel shortcut recording", "取消快捷键录制", "取消快速鍵錄製", "ショートカットの記録をキャンセル"),
        Entry("‹ Back", "‹ 返回", "‹ 返回", "‹ 戻る"),
        Entry("Press up to 3 keys · Esc to cancel", "最多同时按 3 个键 · Esc 取消", "最多同時按 3 個鍵 · Esc 取消", "最大3キーを同時に押す · Escでキャンセル"),
        Entry("Restore all preferences?", "恢复所有设置？", "恢復所有設定？", "すべての設定を初期状態に戻しますか？"),
        Entry("Notes, files and shortcuts are kept.", "保留便笺、文件与应用快捷方式。", "保留便箋、檔案與應用程式捷徑。", "メモ、ファイル、ショートカットは保持されます。"),
        Entry("Restore", "恢复", "恢復", "元に戻す"),
        Entry("seconds", "秒", "秒", "秒"),
        Entry("System", "跟随系统", "跟隨系統", "システムに合わせる"),
        Entry("Dark", "深色", "深色", "ダーク"),
        Entry("Light", "浅色", "淺色", "ライト"),
        // HUDSettingsController.swift
        Entry("Unofficial fan project", "非官方同人项目", "非官方同人項目", "非公式ファンプロジェクト"),
        Entry("Inspiration", "灵感来源", "靈感來源", "着想元"),
        Entry("Audio architecture reference", "音频架构参考", "音訊架構參考", "オーディオ設計の参考"),
        Entry("UI layout restored", "已恢复界面布局", "已恢復介面佈局", "表示位置を元に戻しました"),
        Entry("UI scale restored", "已恢复界面缩放", "已恢復介面縮放", "表示倍率を元に戻しました"),
        // HUDUpdateController.swift
        Entry("The signed updater could not start.", "签名更新服务无法启动。", "簽名更新服務無法啟動。", "署名付きアップデーターを起動できませんでした。"),
        Entry("Installs after 30 idle seconds, or when you quit.", "空闲 30 秒后或退出时自动安装。", "空閒 30 秒後或結束時自動安裝。", "30秒間操作がない場合、または終了時にインストールします。"),
        Entry("Already downloaded; installs on next quit. Automatic restarts are off.", "更新已下载，将在下次退出时安装。已关闭自动重启。", "更新已下載，將在下次結束時安裝。已關閉自動重啟。", "ダウンロード済みです。次回終了時にインストールします。自動再起動は無効です。"),
        Entry("EndfieldHUD update available", "EndfieldHUD 发现新版本", "EndfieldHUD 發現新版本", "EndfieldHUDのアップデートがあります"),
        Entry("{0} is available. Signed updates install automatically when the HUD, Work Mode and audio controls are idle.", "{0} 已发布。签名更新将在浮层、工作模式和音量控制空闲时自动安装。", "{0} 已發佈。簽名更新將在浮層、工作模式和音量控制空閒時自動安裝。", "{0}が利用可能です。HUD、作業モード、音量操作の待機中に署名付きアップデートを自動インストールします。"),
        Entry("{0} is available. Open About to see the release.", "{0} 已发布。打开关于页面查看。", "{0} 已發佈。開啟關於頁面查看。", "{0}が利用可能です。「このアプリについて」でリリースを確認できます。"),
        Entry("GitHub is limiting requests. Try again later.", "GitHub 暂时限制请求，请稍后重试。", "GitHub 暫時限制請求，請稍後重試。", "GitHubでリクエストが制限されています。しばらくしてからお試しください。"),
        Entry("No published release found on GitHub.", "GitHub 上暂无已发布版本。", "GitHub 上暫無已發佈版本。", "GitHubに公開済みのリリースがありません。"),
        Entry("No release is available for this update channel.", "此更新通道暂无已发布版本。", "此更新通道暫無已發佈版本。", "このアップデートチャンネルに利用可能なリリースがありません。"),
        Entry("This build has no valid release version.", "此构建没有有效的版本号。", "此建置沒有有效的版本號。", "このビルドには有効なバージョン番号がありません。"),
        Entry("Could not check GitHub. Check your connection and retry.", "无法检查 GitHub。请检查网络后重试。", "無法檢查 GitHub。請檢查網路後重試。", "GitHubを確認できませんでした。接続を確認してもう一度お試しください。"),
        Entry("Signed update unavailable. Retry or view the GitHub release.", "签名更新暂不可用。请重试或查看 GitHub 版本。", "簽名更新暫不可用。請重試或查看 GitHub 版本。", "署名付きアップデートを利用できません。再試行するかGitHubのリリースを確認してください。"),
        Entry("Waiting for a compatible signed update package.", "正在等待兼容的签名更新包。", "正在等待相容的簽名更新包。", "互換性のある署名付き更新パッケージを待っています。"),
        // HUDUpdateState.swift
        Entry("Not checked yet", "尚未检查", "尚未檢查", "未確認"),
        Entry("Checking…", "正在检查…", "正在檢查…", "確認中…"),
        Entry("Up to date", "已是最新版本", "已是最新版本", "最新バージョンです"),
        Entry("Downloading…", "正在下载…", "正在下載…", "ダウンロード中…"),
        Entry("Ready to update", "更新已就绪", "更新已就緒", "更新準備完了"),
        Entry("Restarting…", "正在重启…", "正在重啟…", "再起動中…"),
        Entry("Check failed — retry", "检查失败 · 重试", "檢查失敗 · 重試", "確認失敗 · 再試行"),
        // HUDVolumeInteraction.swift
        Entry("Centered", "居中", "居中", "中央"),
        Entry(" · Not adjustable on this device", " · 此设备不支持调整", " · 此裝置不支援調整", " · このデバイスでは調整できません"),
        // HUDWorkModeInteraction.swift
        Entry("Custom countdown: minutes and seconds", "自定义倒计时：分和秒", "自定義倒計時：分和秒", "カスタムカウントダウン：分と秒"),
        Entry("Enter minutes or min:sec, between 0:01 and 1440:00. Return saves; Escape cancels.", "输入分钟数或分:秒，范围为 0:01 至 1440:00。回车保存，Esc 取消。", "輸入分鐘數或分:秒，範圍為 0:01 至 1440:00。Return儲存，Esc 取消。", "分数または分:秒を0:01〜1440:00の範囲で入力してください。Returnで保存、Escでキャンセルします。"),
        Entry(". Space starts, pauses or resumes.", "。空格键开始、暂停或继续。", "。空白鍵開始、暫停或繼續。", "。Spaceで開始、一時停止、再開します。"),
        // HUDWorldMapInteraction.swift
        Entry(". Drag to pan. Scroll or pinch to zoom. Right-click to place or remove a pin. Left-click to hide coordinates. Arrow keys move the map.", "。拖动平移，滚动或捏合缩放，右键放置或移除标记，左键隐藏坐标，方向键移动地图。", "。拖動平移，滾動或捏合縮放，右鍵放置或移除標記，左鍵隱藏座標，方向鍵移動地圖。", "。ドラッグで移動、スクロールまたはピンチで拡大縮小、右クリックでピンを配置または削除、左クリックで座標を非表示、矢印キーでマップを移動します。"),
        // LoginItemManager.swift
        Entry("Approval needed in System Settings → Login Items.", "请在系统设置 → 登录项中允许启动。", "請在系統設定 → 登入項中允許啟動。", "システム設定 → ログイン項目で許可してください。"),
        Entry("Enabled", "已启用", "已啟用", "有効"),
        Entry("Disabled", "已停用", "已停用", "無効"),
        Entry("Move EndfieldHUD.app into Applications (or your home Applications folder), open it from there, then enable Launch at login.", "请将 EndfieldHUD.app 移到“应用程序”文件夹（或个人目录中的“应用程序”文件夹），从那里打开后再启用“登录时启动”。", "請將 EndfieldHUD.app 移到“應用程式”資料夾（或個人目錄中的“應用程式”資料夾），從那裡開啟後再啟用“登入時啟動”。", "EndfieldHUD.appを「アプリケーション」フォルダ（またはホーム内の同フォルダ）に移動し、そこから起動して「ログイン時に起動」を有効にしてください。"),
        Entry("The app’s executable could not be found. Build or reinstall EndfieldHUD.app, then try again.", "找不到应用程序的可执行文件。请重新构建或安装 EndfieldHUD.app 后再试。", "找不到應用程式的可執行檔。請重新建置或安裝 EndfieldHUD.app 後再試。", "アプリの実行可能ファイルが見つかりません。EndfieldHUD.appをビルドまたは再インストールしてお試しください。"),
        // NotesCanvas.swift
        Entry("Enlarge note", "放大便笺", "放大便箋", "メモを拡大"),
        Entry("Reduce note size", "缩小便笺", "縮小便箋", "メモを縮小"),
        Entry("Checklist", "待办", "待辦", "チェックリスト"),
        Entry("TODO", "待办", "待辦", "チェックリスト"),
        Entry("Unpin note", "取消固定", "取消固定", "メモの固定を解除"),
        Entry("Pin note", "固定便笺", "固定便箋", "メモを固定"),
        Entry("Delete note", "删除便笺", "刪除便箋", "メモを削除"),
        Entry("Edit text", "编辑文字", "編輯文字", "テキストを編集"),
        Entry("Uncheck", "取消勾选", "取消勾選", "チェックを外す"),
        Entry("Check", "勾选", "勾選", "チェックする"),
        Entry("Edit item", "编辑事项", "編輯事項", "項目を編集"),
        Entry("Move up", "上移", "上移", "上に移動"),
        Entry("Move down", "下移", "下移", "下に移動"),
        Entry("Delete item", "删除事项", "刪除事項", "項目を削除"),
        Entry("Add item", "添加事项", "新增事項", "項目を追加"),
        Entry("NOTES", "便笺", "便箋", "メモ"),
        Entry("Could not save: ", "无法保存：", "無法儲存：", "保存できませんでした："),
        Entry("Notes storage unavailable", "便笺存储不可用", "便箋儲存不可用", "メモの保存領域を利用できません"),
        Entry("TEXT", "文字", "文字", "テキスト"),
        Entry("IMAGE", "图片", "圖片", "画像"),
        Entry("Double-click to write…", "双击输入…", "雙擊輸入…", "ダブルクリックして入力…"),
        Entry("Image unavailable", "图片不可用", "圖片不可用", "画像を利用できません"),
        Entry("New item…", "新事项…", "新事項…", "新しい項目…"),
        Entry("+ Add item", "+ 添加事项", "+ 新增事項", "+ 項目を追加"),
        Entry("Cancel deletion", "取消删除", "取消刪除", "削除をキャンセル"),
        Entry("Confirm deletion", "确认删除", "確認刪除", "削除を確定"),
        Entry("Notes storage is unavailable.", "便笺存储不可用。", "便箋儲存不可用。", "メモの保存領域を利用できません。"),
        // NotesStore.swift
        Entry("Notes could not be saved or opened: ", "无法保存或打开便笺：", "無法儲存或開啟便箋：", "メモを保存または開くことができません："),
        Entry("A saved note could not be read. The original database has been preserved.", "无法读取已保存的便笺，原始数据库已保留。", "無法讀取已儲存的便箋，原始資料庫已保留。", "保存済みのメモを読み込めませんでした。元のデータベースは保持されています。"),
        Entry("These notes were saved by a newer version of EndfieldCharge.", "这些便笺由较新版本的 EndfieldCharge 保存。", "這些便箋由較新版本的 EndfieldCharge 儲存。", "これらのメモは新しいバージョンのEndfieldChargeで保存されています。"),
        Entry("This file could not be opened as an image.", "无法将此文件作为图片打开。", "無法將此檔案作為圖片開啟。", "このファイルを画像として開けませんでした。"),
        Entry("Choose an image smaller than 128 MB.", "请选择小于 128 MB 的图片。", "請選擇小於 128 MB 的圖片。", "128 MB未満の画像を選択してください。"),
        Entry("The note contains an invalid image reference.", "便笺中的图片引用无效。", "便箋中的圖片引用無效。", "メモ内の画像の参照が無効です。"),
        // OverlayController.swift
        Entry("Discard position", "取消位置更改", "取消位置更改", "位置の変更を破棄"),
        Entry("Confirm position", "确认位置", "確認位置", "位置を確定"),
        Entry("Discard (Esc)", "取消（Esc）", "取消（Esc）", "破棄（Esc）"),
        Entry("Confirm (Return)", "确认（回车）", "確認（Return）", "確定（Return）"),
        // PerAppAudioController.swift
        Entry("Experimental app volume requires macOS 14.2 or later.", "实验性应用音量需要 macOS 14.2 或更新版本。", "實驗性應用程式音量需要 macOS 14.2 或更新版本。", "実験的なアプリ音量機能にはmacOS 14.2以降が必要です。"),
        Entry("Choose another process with active audio output.", "请选择正在输出音频的其他进程。", "請選擇正在輸出音訊的其他程序。", "音声を出力中の別のプロセスを選択してください。"),
        Entry("This experimental route supports stereo output-only built-in or USB devices. Bluetooth and devices with input channels are not supported.", "此实验性路由支持仅具备双声道输出的内建或 USB 设备，暂不支持蓝牙或带输入声道的设备。", "此實驗性路由支援僅具備雙聲道輸出的內建或 USB 裝置，暫不支援藍牙或帶輸入聲道的裝置。", "この実験的なルートは入力チャンネルのない内蔵またはUSBのステレオ出力デバイスに対応します。Bluetoothと入力チャンネルのあるデバイスには対応していません。"),
        Entry("This output device does not support app volume routing.", "此输出设备暂不支持应用音量路由。", "此輸出裝置暫不支援應用程式音量路由。", "この出力デバイスはアプリ音量のルーティングに対応していません。"),
        Entry("This app uses a different output route.", "此应用使用其他输出路由。", "此應用程式使用其他輸出路由。", "このアプリは別の出力ルートを使用しています。"),
        Entry("Choose a finite app volume between 0% and 100%.", "请选择 0% 至 100% 之间的有效应用音量。", "請選擇 0% 至 100% 之間的有效應用程式音量。", "0%〜100%の範囲で有効なアプリ音量を選択してください。"),
        Entry("Stop the existing route before starting another for this process.", "请先停止此进程的现有路由，再重新开始。", "請先停止此程序的現有路由，再重新開始。", "このプロセスの既存のルートを停止してから、新しいルートを開始してください。"),
        Entry("Allow System Audio Recording if asked, then play audio in the selected app to activate.", "如有提示，请允许系统音频录制，然后在所选应用中播放音频以激活。", "如有提示，請允許系統音訊錄製，然後在所選應用程式中播放音訊以啟用。", "要求されたらシステムオーディオの録音を許可し、選択したアプリで音声を再生して有効にしてください。"),
        // PerAppAudioEngine.swift
        Entry("App audio routing requires macOS 14.2 or later.", "应用音频路由需要 macOS 14.2 或更新版本。", "應用程式音訊路由需要 macOS 14.2 或更新版本。", "アプリのオーディオルーティングにはmacOS 14.2以降が必要です。"),
        Entry("This route has already been started.", "此路由已经启动过。", "此路由已經啟動過。", "このルートはすでに開始されています。"),
        Entry("macOS did not finish starting audio processing. Cancellation is pending; the original app was not muted. Quit EndfieldCharge if macOS remains unresponsive.", "macOS 未能完成音频处理启动，正在等待取消；应用原始输出未被静音。若系统持续无响应，请退出 EndfieldCharge。", "macOS 未能完成音訊處理啟動，正在等待取消；應用程式原始輸出未被靜音。若系統持續無回應，請結束 EndfieldCharge。", "macOSで音声処理の開始が完了せず、キャンセルを待機中です。アプリの元の出力は消音されていません。応答が戻らない場合はEndfieldChargeを終了してください。"),
        Entry("Waiting for macOS to release the audio route. The app remains responsive; quit EndfieldCharge if audio is affected. No replacement route will start while cleanup is pending.", "正在等待 macOS 释放音频路由。界面仍可操作；若声音受影响，请退出 EndfieldCharge。清理完成前不会启动替代路由。", "正在等待 macOS 釋放音訊路由。介面仍可操作；若聲音受影響，請結束 EndfieldCharge。清理完成前不會啟動替代路由。", "macOSがオーディオルートを解放するのを待っています。画面は操作できます。音声に影響がある場合はEndfieldChargeを終了してください。後処理が完了するまで代わりのルートは開始しません。"),
        Entry("This route is already running.", "此路由已在运行。", "此路由已在執行。", "このルートはすでに実行中です。"),
        Entry("Could not create this app's audio tap. Check System Audio Recording permission in Privacy & Security, then retry.", "无法创建此应用的音频 Tap，请检查“隐私与安全性”中的“系统音频录制”权限后重试。", "無法建立此應用程式的音訊 Tap，請檢查“隱私與安全性”中的“系統音訊錄製”權限後重試。", "このアプリのオーディオタップを作成できませんでした。「プライバシーとセキュリティ」でシステムオーディオの録音権限を確認し、もう一度お試しください。"),
        Entry("This macOS audio tap cannot safely switch its mute behavior.", "此 macOS 音频 Tap 无法安全切换静音行为。", "此 macOS 音訊 Tap 無法安全切換靜音行為。", "このmacOSオーディオタップの消音動作を安全に切り替えることができません。"),
        Entry("The route could not be fully removed. Retry Stop; quit EndfieldCharge if audio remains affected.", "未能完全移除音频路由，请重试停止；若音频仍受影响，请退出 EndfieldCharge。", "未能完全移除音訊路由，請重試停止；若音訊仍受影響，請結束 EndfieldCharge。", "オーディオルートを完全に削除できませんでした。停止を再試行し、音声に影響が残る場合はEndfieldChargeを終了してください。"),
        Entry("The route was removed, but macOS reported a cleanup error.", "音频路由已移除，但 macOS 报告了清理错误。", "音訊路由已移除，但 macOS 報告了清理錯誤。", "オーディオルートは削除されましたが、macOSで後処理のエラーが報告されました。"),
        Entry("This experimental route requires the current built-in or USB stereo output, with no input channels. The device may have changed.", "此实验性路由需要当前内建或 USB 双声道输出设备，且该设备不能带输入声道。设备可能已更改。", "此實驗性路由需要當前內建或 USB 雙聲道輸出裝置，且該裝置不能帶輸入聲道。裝置可能已更改。", "この実験的なルートには、現在選択中の入力チャンネルのない内蔵またはUSBのステレオ出力が必要です。デバイスが変更された可能性があります。"),
        Entry("This experimental route requires the device's standard left/right stereo channel mapping.", "此实验性路由需要设备使用标准左右双声道映射。", "此實驗性路由需要裝置使用標準左右雙聲道映射。", "この実験的なルートには標準の左右ステレオチャンネル配置が必要です。"),
        Entry("The private audio device did not become ready. Its route was cancelled; try again after the audio device settles.", "私有音频设备未能就绪，路由已取消。请等待音频设备稳定后重试。", "私有音訊裝置未能就緒，路由已取消。請等待音訊裝置穩定後重試。", "専用のオーディオデバイスの準備が整わず、ルートをキャンセルしました。デバイスが安定してから再試行してください。"),
        Entry("This process must output only to the selected device. Processes using another or several devices are not supported.", "此进程必须仅向所选设备输出，暂不支持使用其他或多个设备的进程。", "此程序必須僅向所選裝置輸出，暫不支援使用其他或多個裝置的程序。", "このプロセスは選択したデバイスだけに出力する必要があります。別のデバイスや複数のデバイスへの出力には対応していません。"),
        Entry("The selected audio process changed. Select the app again.", "所选音频进程已更改，请重新选择应用。", "所選音訊程序已更改，請重新選擇應用程式。", "選択したオーディオプロセスが変更されました。アプリを選択し直してください。"),
        Entry("The audio device format changed. Start this route again if needed.", "音频设备格式已更改，如有需要请重新启动此路由。", "音訊裝置格式已更改，如有需要請重新啟動此路由。", "オーディオデバイスの形式が変更されました。必要に応じてルートを開始し直してください。"),
        Entry("The audio callback format changed. Stopping processing and restoring direct playback.", "音频回调格式已更改，正在停止处理并恢复原始播放。", "音訊回調格式已更改，正在停止處理並恢復原始播放。", "オーディオコールバックの形式が変更されました。処理を停止し、直接再生に戻します。"),
        Entry("Audio processing stopped responding. Stopping this route.", "音频处理停止响应，正在停止此路由。", "音訊處理停止響應，正在停止此路由。", "音声処理が応答しなくなったため、ルートを停止します。"),
        Entry("No usable app audio arrived. Allow System Audio Recording, play audio, and try again. The app's original output was not muted.", "未收到可用的应用音频。请允许系统音频录制、播放音频后重试，应用原始输出未被静音。", "未收到可用的應用程式音訊。請允許系統音訊錄製、播放音訊後重試，應用程式原始輸出未被靜音。", "利用可能なアプリ音声を受信できませんでした。システムオーディオの録音を許可し、音声を再生して再試行してください。元の出力は消音されていません。"),
        Entry("The audio streams changed during startup. Start this route again.", "音频流在启动过程中发生更改，请重新启动此路由。", "音訊流在啟動過程中發生更改，請重新啟動此路由。", "開始中に音声ストリームが変更されました。ルートを開始し直してください。"),
        Entry("This experimental route requires matching Float32 stereo streams and sample rates. This audio device or format is not supported.", "此实验性路由需要格式和采样率匹配的 Float32 双声道音频流，暂不支持此音频设备或格式。", "此實驗性路由需要格式和採樣率匹配的 Float32 雙聲道音訊流，暫不支援此音訊裝置或格式。", "この実験的なルートには形式とサンプルレートが一致するFloat32のステレオストリームが必要です。このデバイスまたは形式には対応していません。"),
        Entry("macOS could not read the audio device ({0}).", "macOS 无法读取音频设备（{0}）。", "macOS 無法讀取音訊裝置（{0}）。", "macOSでオーディオデバイスを読み取れませんでした（{0}）。"),
        Entry("The audio device changed or could not provide valid route information.", "音频设备已更改或无法提供有效的路由信息。", "音訊裝置已更改或無法提供有效的路由資訊。", "オーディオデバイスが変更されたか、有効なルート情報を取得できませんでした。"),
        Entry("macOS could not complete the audio route ({0}).", "macOS 无法完成音频路由（{0}）。", "macOS 無法完成音訊路由（{0}）。", "macOSでオーディオルートを完了できませんでした（{0}）。"),
        Entry("Audio routing was cancelled.", "音频路由已取消。", "音訊路由已取消。", "オーディオルーティングをキャンセルしました。"),
        // PersonalProfileCanvas.swift
        Entry("Name", "名称", "名稱", "名前"),
        Entry("Introduction", "个人介绍", "個人介紹", "自己紹介"),
        Entry("Awakening day", "苏醒日", "蘇醒日", "覚醒日"),
        Entry("Birthday", "生日", "生日", "誕生日"),
        Entry("Authority level", "权限等级", "權限等級", "権限レベル"),
        Entry("Exploration level", "探索等级", "探索等級", "探索レベル"),
        Entry("Operators", "干员", "乾員", "オペレーター"),
        Entry("Weapons", "武器", "武器", "武器"),
        Entry("Archives", "档案", "檔案", "アーカイブ"),
        Entry("Background width", "背景宽度", "背景寬度", "背景の幅"),
        Entry("Background X", "背景 X", "背景 X", "背景 X"),
        Entry("Background Y", "背景 Y", "背景 Y", "背景 Y"),
        Entry("Thumbnail X", "缩略图 X", "縮略圖 X", "サムネイル X"),
        Entry("Thumbnail Y", "缩略图 Y", "縮略圖 Y", "サムネイル Y"),
        Entry("Zoom", "缩放", "縮放", "ズーム"),
        Entry("Portrait X", "头像 X", "頭像 X", "ポートレート X"),
        Entry("Portrait Y", "头像 Y", "頭像 Y", "ポートレート Y"),
        Entry("Personal profile", "个人名片", "個人名片", "プロフィール"),
        Entry("Change card theme", "更换名片主题", "更換名片主題", "カードのテーマを変更"),
        Entry("Show profile text", "显示名片文字", "顯示名片文字", "プロフィールの文字を表示"),
        Entry("Hide profile text", "隐藏名片文字", "隱藏名片文字", "プロフィールの文字を非表示"),
        Entry("Show awakening day", "切换为苏醒日", "切換為蘇醒日", "覚醒日に切り替え"),
        Entry("Show birthday", "切换为生日", "切換為生日", "誕生日に切り替え"),
        Entry("Edit personal profile", "编辑个人名片", "編輯個人名片", "プロフィールを編集"),
        Entry("Edit introduction", "编辑个人介绍", "編輯個人介紹", "自己紹介を編集"),
        Entry("Profile storage is unavailable.", "个人名片存储不可用。", "個人名片儲存不可用。", "プロフィールの保存領域を利用できません。"),
        Entry("Use YYYY/MM/DD for awakening day.", "苏醒日格式为 YYYY/MM/DD。", "蘇醒日格式為 YYYY/MM/DD。", "覚醒日はYYYY/MM/DD形式で入力してください。"),
        Entry("Use MM/DD for birthday.", "生日格式为 MM/DD。", "生日格式為 MM/DD。", "誕生日はMM/DD形式で入力してください。"),
        Entry("PERSONAL PROFILE", "个人名片", "個人名片", "プロフィール"),
        Entry("Awakening", "苏醒日", "蘇醒日", "覚醒日"),
        Entry("REGION CONSTRUCTION", "地区建设概况", "地區建設概況", "地域建設状況"),
        Entry("h", "小时", "小時", "時間"),
        Entry("Edit name", "修改名称", "修改名稱", "名前を編集"),
        Entry("Edit #", "修改 #", "修改 #", "#を編集"),
        Entry("Change profile picture", "更换头像", "更換頭像", "プロフィール画像を変更"),
        Entry("Adjust portrait", "调整头像", "調整頭像", "ポートレートを調整"),
        Entry("Restore default picture", "恢复默认头像", "恢復預設頭像", "既定の画像に戻す"),
        Entry("Close", "关闭", "關閉", "閉じる"),
        Entry("Back to card theme", "返回名片主题", "返回名片主題", "カードのテーマに戻る"),
        Entry("Follow HUD theme", "跟随浮层主题", "跟隨浮層主題", "HUDのテーマに合わせる"),
        Entry("Card color ", "名片颜色 ", "名片顏色 ", "カードの色 "),
        Entry("Custom card color", "自定名片颜色", "自定名片顏色", "カードの色をカスタマイズ"),
        Entry("Back to profile menu", "返回名片菜单", "返回名片選單", "プロフィールメニューに戻る"),
        Entry("Choose background", "选择背景", "選擇背景", "背景を選択"),
        Entry("Restore default", "恢复默认", "恢復預設", "初期状態に戻す"),
        Entry("PORTRAIT", "调整头像", "調整頭像", "ポートレート"),
        Entry("CARD THEME", "名片主题", "名片主題", "カードのテーマ"),
        Entry("CARD COLOR", "名片颜色", "名片顏色", "カードの色"),
        Entry("Card theme", "更换名片主题", "更換名片主題", "カードのテーマ"),
        // SummonShortcut.swift
        Entry("That modifier is not supported.", "不支持该修饰键。", "不支援該修飾鍵。", "この修飾キーには対応していません。"),
        Entry("Use one key with one or two modifiers (up to three keys).", "请使用一个普通键加一至两个修饰键（最多三个键）。", "請使用一個普通鍵加一至兩個修飾鍵（最多三個鍵）。", "通常のキー1つに修飾キーを1〜2つ組み合わせてください（合計3キーまで）。"),
        Entry("Choose a letter, number, punctuation, arrow, or function key.", "请选择字母、数字、标点、方向键或功能键。", "請選擇字母、數字、標點、方向鍵或功能鍵。", "文字、数字、句読点、矢印、ファンクションキーから選択してください。"),
        Entry("That combination is reserved for common macOS or editing commands.", "该组合用于常见的 macOS 或编辑命令，请选择其他快捷键。", "該組合用於常見的 macOS 或編輯命令，請選擇其他快速鍵。", "この組み合わせはmacOSや編集操作で使われます。別のショートカットを選択してください。"),
        // SystemHUDView.swift
        Entry("System interface", "系统界面", "系統介面", "システムインターフェース"),
        Entry("The original menu could not be rendered. Please check the log.", "原始菜单无法渲染，请查看日志。", "原始選單無法繪製，請查看日誌。", "元のメニューを描画できませんでした。ログを確認してください。"),
        Entry("Open battery menu", "打开电池菜单", "開啟電池選單", "バッテリーメニューを開く"),
        Entry("Not selected", "未选择", "未選擇", "未選択"),
        Entry("Scroll modules up", "向上滚动模块", "向上滾動模組", "モジュールを上にスクロール"),
        Entry("Scroll modules down", "向下滚动模块", "向下滾動模組", "モジュールを下にスクロール"),
        Entry("No internal battery", "无内置电池", "無內建電池", "内蔵バッテリーなし"),
        Entry("CHARGING", "正在充电", "正在充電", "充電中"),
        Entry("FULLY CHARGED", "已充满", "已充滿", "充電完了"),
        Entry("POWER CONNECTED", "已连接电源", "已連接電源", "電源に接続済み"),
        Entry("ON BATTERY", "电池供电", "電池供電", "バッテリー使用中"),
        Entry("External power", "外接电源", "外接電源", "外部電源"),
        Entry("Battery power", "电池供电", "電池供電", "バッテリー電源"),
        Entry("Unavailable", "暂无数据", "暫無資料", "データなし"),
        Entry("SOURCE  /  ", "电源  /  ", "電源  /  ", "電源  /  "),
        Entry("// BATTERY STATUS", "// 电池状态", "// 電池狀態", "// バッテリー状態"),
        Entry("CLICK OUTSIDE TO CLOSE", "点击外侧关闭", "點擊外側關閉", "外側をクリックして閉じる"),
        // TelemetryCanvases.swift
        Entry("Reading storage…", "正在读取存储…", "正在讀取儲存…", "ストレージを読み込み中…"),
        Entry("Storage unavailable", "存储不可用", "儲存不可用", "ストレージを利用できません"),
        Entry("Total ", "总计 ", "總計 ", "合計 "),
        Entry("Used ", "已用 ", "已用 ", "使用中 "),
        Entry("Available ", "可用 ", "可用 ", "利用可能 "),
        Entry("Refreshing", "正在刷新", "正在重新整理", "更新中"),
        Entry("Storage Settings", "存储设置", "儲存設定", "ストレージ設定"),
        Entry("Refresh storage", "刷新存储", "重新整理儲存", "ストレージを更新"),
        Entry("Startup disk", "启动磁盘", "啟動磁碟", "起動ディスク"),
        Entry("Total", "总计", "總計", "合計"),
        Entry("Used", "已用", "已用", "使用中"),
        Entry("Available", "可用", "可用", "利用可能"),
        Entry(" used", " 已用", " 已用", " 使用中"),
        Entry("Capacity unavailable", "容量不可用", "容量不可用", "容量を取得できません"),
        Entry("The startup filesystem is unavailable.", "启动文件系统不可用。", "啟動檔案系統不可用。", "起動ファイルシステムを利用できません。"),
        Entry("Storage capacity is unavailable.", "无法读取存储容量。", "無法讀取儲存容量。", "ストレージ容量を取得できません。"),
        // UserProfileStore.swift
        Entry("Enter a name of 1–20 characters without line breaks.", "请输入 1–20 个字符的名称，不含换行。", "請輸入 1–20 個字符的名稱，不含換行。", "改行を含まない1〜20文字の名前を入力してください。"),
        Entry("Enter a tag of 1–10 characters without spaces or #.", "请输入 1–10 个字符的编号，不含空格或 #。", "請輸入 1–10 個字符的編號，不含空格或 #。", "スペースや#を含まない1〜10文字のタグを入力してください。"),
        Entry("Enter a number within the allowed range.", "请输入允许范围内的数字。", "請輸入允許範圍內的數字。", "許容範囲内の数値を入力してください。"),
        Entry("Choose a readable image file.", "请选择可读取的图片文件。", "請選擇可讀取的圖片檔案。", "読み取り可能な画像ファイルを選択してください。"),
        Entry("Choose a portrait no larger than 128 megapixels or 32,768 pixels on either side.", "请选择不超过 1.28 亿像素、且单边不超过 32,768 像素的头像。", "請選擇不超過 1.28 億像素、且單邊不超過 32,768 像素的頭像。", "1億2800万画素以下で、縦横とも32,768ピクセル以下のポートレートを選択してください。"),
        Entry("The personal card could not be read. The saved data has been preserved.", "无法读取个人名片，已保留原始数据。", "無法讀取個人名片，已保留原始資料。", "プロフィールカードを読み込めませんでした。保存データは保持されています。"),
        Entry("This personal card was saved by a newer version of EndfieldHUD.", "此个人名片由较新版本的 EndfieldHUD 保存。", "此個人名片由較新版本的 EndfieldHUD 儲存。", "このプロフィールカードは新しいバージョンのEndfieldHUDで保存されています。"),
        Entry("The personal card changed in another app instance. Restart before editing.", "个人名片已由另一个应用实例更改，请重启后编辑。", "個人名片已由另一個應用程式實例更改，請重啟後編輯。", "プロフィールカードが別のアプリインスタンスで変更されました。再起動してから編集してください。"),
        Entry("The personal card could not be saved: ", "无法保存个人名片：", "無法儲存個人名片：", "プロフィールカードを保存できませんでした："),
        // VolumeCanvas.swift
        Entry("Adjust each audio process independently. 100% is full volume and keeps an enabled route running.", "独立调整每个音频进程。100% 为原始音量，已启用的路由会继续运行。", "獨立調整每個音訊程序。100% 為原始音量，已啟用的路由會繼續執行。", "各オーディオプロセスを個別に調整します。100%は元の音量で、有効なルートは動作を継続します。"),
        Entry("Output volume", "输出音量", "輸出音量", "出力音量"),
        Entry("Left/right balance", "左右声道平衡", "左右聲道平衡", "左右のバランス"),
        Entry(" volume", " 音量", " 音量", " の音量"),
        Entry(" Return to 100% to retry cleanup.", " 回到 100% 可重试清理。", " 回到 100% 可重試清理。", " 100%に戻すと後処理を再試行します。"),
        Entry("Adjusts only this audio process; 100% keeps its route running at full volume", "仅调整此音频进程；100% 保持路由运行并恢复原始音量", "僅調整此音訊程序；100% 保持路由執行並恢復原始音量", "このオーディオプロセスのみ調整します。100%ではルートを維持し、元の音量に戻します"),
        Entry("Requested volume; waiting for audio processing to start", "目标音量；正在等待音频处理启动", "目標音量；正在等待音訊處理啟動", "指定音量：音声処理の開始を待機中"),
        Entry("Waiting for macOS to release this route", "正在等待 macOS 释放此路由", "正在等待 macOS 釋放此路由", "macOSによるルートの解放を待機中"),
        Entry("Return to 100% to retry restoring normal playback", "回到 100% 可重试恢复正常播放", "回到 100% 可重試恢復正常播放", "100%に戻すと通常再生への復帰を再試行します"),
        Entry("No output device", "无输出设备", "無輸出裝置", "出力デバイスなし"),
        Entry("Adjust to enable a temporary audio route; macOS may request System Audio Recording access", "调整即可启用临时音频路由；macOS 可能请求系统音频录制权限", "調整即可啟用臨時音訊路由；macOS 可能請求系統音訊錄製權限", "調整すると一時的な音声ルートが有効になります。macOSがシステムオーディオの録音権限を求める場合があります"),
        Entry("App routing stopped because the output device changed.", "输出设备已更改，应用混音已停止。", "輸出裝置已更改，應用程式混音已停止。", "出力デバイスが変更されたため、アプリの音声ルートを停止しました。"),
        Entry("Choose output device", "选择输出设备", "選擇輸出裝置", "出力デバイスを選択"),
        Entry("Choose input device", "选择输入设备", "選擇輸入裝置", "入力デバイスを選択"),
        Entry("Unmute", "取消静音", "取消靜音", "消音を解除"),
        Entry("Mute", "静音", "靜音", "消音"),
        Entry("Headphones / Bluetooth", "耳机 / 蓝牙", "耳機 / 藍牙", "ヘッドフォン / Bluetooth"),
        Entry("App volume", "应用音量", "應用程式音量", "アプリ音量"),
        Entry(", Selected", "，已选择", "，已選擇", "、選択済み"),
        Entry("Output device", "输出设备", "輸出裝置", "出力デバイス"),
        Entry("Input device", "输入设备", "輸入裝置", "入力デバイス"),
        Entry("Device and app volume", "设备与应用音量", "裝置與應用程式音量", "デバイスとアプリの音量"),
        Entry("Choose a connected device", "选择已连接的设备", "選擇已連接的裝置", "接続済みのデバイスを選択"),
        Entry("Output", "输出", "輸出", "出力"),
        Entry("Input", "输入", "輸入", "入力"),
        Entry("No device", "无设备", "無裝置", "デバイスなし"),
        Entry("Balance", "平衡", "平衡", "バランス"),
        Entry("Balance is unavailable for this device", "此设备不支持声道平衡", "此裝置不支援聲道平衡", "このデバイスでは左右のバランスを調整できません"),
        Entry("Balance unavailable", "声道平衡不可用", "聲道平衡不可用", "バランス調整不可"),
        Entry("Use this device's controls", "请使用设备自身的音量控制", "請使用裝置自身的音量控制", "デバイス本体で音量を調整してください"),
        Entry("No headphones or Bluetooth audio devices", "未连接耳机或蓝牙音频设备", "未連接耳機或藍牙音訊裝置", "ヘッドフォンやBluetoothオーディオデバイスは接続されていません"),
        Entry("Headphones", "耳机", "耳機", "ヘッドフォン"),
        Entry(" · Output", " · 输出", " · 輸出", " · 出力"),
        Entry("Audio app detection requires macOS 14.2 or later", "音频应用检测需要 macOS 14.2 或更高版本", "音訊應用程式檢測需要 macOS 14.2 或更高版本", "音声を再生中のアプリの検出にはmacOS 14.2以降が必要です"),
        Entry("No adjustable audio apps", "暂无可调节音量的应用", "暫無可調節音量的應用程式", "音量を調整できるアプリはありません"),
        Entry("Starting…", "正在启动…", "正在啟動…", "開始中…"),
        Entry("Stopping…", "正在停止…", "正在停止…", "停止中…"),
        Entry("100% to restore", "回到 100% 恢复", "回到 100% 恢復", "100%で復元"),
        Entry("Unsupported route", "暂不支持此路由", "暫不支援此路由", "未対応のルート"),
        Entry("No connected devices", "无已连接设备", "無已連接裝置", "接続済みデバイスなし"),
        // WorkModeCanvas.swift
        Entry("Countdown", "倒计时", "倒計時", "カウントダウン"),
        Entry("Stopwatch", "秒表", "碼錶", "ストップウォッチ"),
        Entry("Pause", "暂停", "暫停", "一時停止"),
        Entry("Reset", "重置", "重設", "リセット"),
        Entry("Resume", "继续", "繼續", "再開"),
        Entry("Start", "开始", "開始", "開始"),
        Entry("{0} min", "{0} 分", "{0} 分", "{0}分"),
        Entry("Use 0:01–1440:00 (min:sec)", "输入 0:01–1440:00（分:秒）", "輸入 0:01–1440:00（分:秒）", "0:01〜1440:00（分:秒）で入力"),
        Entry("Ready", "就绪", "就緒", "準備完了"),
        Entry("Stopped", "已结束", "已結束", "終了済み"),
        Entry("Completed", "已完成", "已完成", "完了"),
        // WorkModeFocusController.swift
        Entry("Automatic Focus was interrupted.", "自动专注模式操作已中断。", "自動專注模式操作已中斷。", "集中モードの自動操作が中断されました。"),
        Entry("Open Accessibility Settings", "打开辅助功能设置", "開啟輔助使用設定", "アクセシビリティ設定を開く"),
        Entry("Automatic Focus requires macOS 11 or later.", "自动专注模式需要 macOS 11 或更新版本。", "自動專注模式需要 macOS 11 或更新版本。", "集中モードの自動切り替えにはmacOS 11以降が必要です。"),
        Entry("Allow Accessibility to control Focus.", "允许辅助功能访问以控制专注模式。", "允許輔助使用存取以控制專注模式。", "集中モードを操作するにはアクセシビリティを許可してください。"),
        Entry("macOS Focus controls are unavailable.", "无法访问 macOS 专注模式控制。", "無法存取 macOS 專注模式控制。", "macOSの集中モードを操作できません。"),
        Entry("Automatic Focus could not be confirmed. Check the current Focus.", "无法确认自动专注模式，请检查当前专注状态。", "無法確認自動專注模式，請檢查目前專注狀態。", "自動切り替えを確認できませんでした。現在の集中モードを確認してください。"),
        Entry("Automatic Focus requires macOS 13 or later and Shortcuts.", "自动专注模式需要 macOS 13 或更新版本及快捷指令。", "自動專注模式需要 macOS 13 或更新版本及捷徑。", "集中モードの自動切り替えにはmacOS 13以降とショートカットが必要です。"),
        Entry("Add EndfieldCharge Focus Start and End shortcuts to enable automatic Focus.", "请添加 EndfieldCharge Focus Start 和 End 快捷指令以启用自动专注模式。", "請新增 EndfieldCharge Focus Start 和 EndfieldCharge Focus End 捷徑以啟用自動專注模式。", "集中モードの自動切り替えにはEndfieldCharge Focus StartとEndfieldCharge Focus Endのショートカットを追加してください。"),
        Entry("Waiting for Shortcuts; the Focus change is not confirmed yet.", "正在等待快捷指令，尚未确认专注模式更改。", "正在等待捷徑，尚未確認專注模式更改。", "ショートカットを待機中です。集中モードの変更はまだ確認されていません。"),
        Entry("Shortcuts could not open. Automatic Focus was not started.", "无法启动快捷指令，自动专注模式未启动。", "無法啟動捷徑，自動專注模式未啟動。", "ショートカットを開けませんでした。集中モードの自動切り替えは開始されていません。"),
        Entry("Automatic Focus could not be confirmed. Check the Focus shortcuts and current Focus.", "无法确认自动专注模式，请检查专注模式快捷指令及当前状态。", "無法確認自動專注模式，請檢查專注模式捷徑及當前狀態。", "集中モードの自動切り替えを確認できませんでした。ショートカットと現在の集中モードを確認してください。"),
        // WorldMapCanvas.swift
        Entry("Terrain data could not be loaded.", "无法载入地形数据。", "無法載入地形資料。", "地形データを読み込めませんでした。"),
        Entry("Country shapes could not be loaded.", "无法载入地图轮廓。", "無法載入地圖輪廓。", "国の輪郭を読み込めませんでした。"),
        Entry("Zoom in", "放大", "放大", "拡大"),
        Entry("Zoom out", "缩小", "縮小", "縮小"),
        Entry("Reset zoom to 3×", "重置缩放至3×", "重設縮放至3×", "ズームを3倍に戻す"),
        Entry("Place pin at map center", "在地图中心放置标记", "在地圖中心放置標記", "マップの中央にピンを配置"),
        Entry("Remove selected pin", "移除选中标记", "移除選中標記", "選択したピンを削除"),
        Entry("Pin ", "标记 ", "標記 ", "ピン "),
        Entry("MAP", "地图", "地圖", "マップ"),
        Entry("LOADING TERRAIN", "载入地形", "載入地形", "地形を読み込み中"),
        Entry("PINS", "标记", "標記", "ピン"),
    ]
}
