# Installs only the EndfieldHUD runtime component into a NEW owned prefix and
# verifies the installed package: every resource matches its SHA-256 pin and
# nothing but the executable, fonts and resources is installed.
cmake_minimum_required(VERSION 3.25)
foreach(required BUILD CONFIG PREFIX)
  if(NOT ${required})
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()
file(REMOVE_RECURSE "${PREFIX}")
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD}" --config "${CONFIG}" --prefix "${PREFIX}" --component EndfieldHUD
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Install failed:\n${output}\n${errors}")
endif()
file(GLOB entries RELATIVE "${PREFIX}" "${PREFIX}/*")
list(SORT entries)
if(NOT entries STREQUAL "EndfieldHUD.exe;fonts;resources")
  message(FATAL_ERROR "Unexpected installed entries: ${entries}")
endif()
file(GLOB_RECURSE forbidden "${PREFIX}/*.pdb" "${PREFIX}/*.ilk" "${PREFIX}/*_tests.exe" "${PREFIX}/*.tar.gz" "${PREFIX}/*.mp4")
if(forbidden)
  message(FATAL_ERROR "Development artifacts were installed: ${forbidden}")
endif()
execute_process(COMMAND "${PREFIX}/EndfieldHUD.exe" --verify-package RESULT_VARIABLE verified OUTPUT_VARIABLE report ERROR_VARIABLE verifyErrors)
if(NOT verified EQUAL 0)
  message(FATAL_ERROR "Installed package does not verify (${verified}):\n${report}\n${verifyErrors}")
endif()
file(GLOB_RECURSE installed "${PREFIX}/*")
set(bytes 0)
foreach(file IN LISTS installed)
  file(SIZE "${file}" size)
  math(EXPR bytes "${bytes}+${size}")
endforeach()
message(STATUS "Installed EndfieldHUD package verifies: ${bytes} bytes")
file(REMOVE_RECURSE "${PREFIX}")
