# Stages EndfieldHUD.exe runtime resources and writes resources/resources.json
# with an exact byte count and SHA-256 pin for every file
# (core/resource_locator.hpp). Run as:
#   cmake -DSTAGE_DIR=<exe dir>/resources -DSOURCE_COMMIT=<pin>
#         -DRESOURCE_SPECS_FILE=<file with one id|kind|source|dest line per resource> -P stage_resources.cmake
# kind is "file" or "directory". Only runtime inputs are staged: no recordings,
# reference exports, packets, test fixtures, symbols or user data. A missing
# optional input is left out of the manifest, and the application disables
# only the module that needs it. Files left in STAGE_DIR by an earlier package
# layout are removed, so the staged tree is exactly the manifest.
cmake_minimum_required(VERSION 3.25)
if(NOT STAGE_DIR OR NOT RESOURCE_SPECS_FILE)
  message(FATAL_ERROR "STAGE_DIR and RESOURCE_SPECS_FILE are required")
endif()
file(STRINGS "${RESOURCE_SPECS_FILE}" specs)
file(MAKE_DIRECTORY "${STAGE_DIR}")
set(entries "")
set(staged 0)
set(staged_files "resources.json")
set(ids "")
foreach(spec IN LISTS specs)
  string(REPLACE "|" ";" parts "${spec}")
  list(LENGTH parts count)
  if(NOT count EQUAL 4)
    message(FATAL_ERROR "Invalid resource spec: ${spec}")
  endif()
  list(GET parts 0 id)
  list(GET parts 1 kind)
  list(GET parts 2 source)
  list(GET parts 3 dest)
  if(id IN_LIST ids)
    message(FATAL_ERROR "Resource ${id} is declared twice")
  endif()
  list(APPEND ids "${id}")
  if(NOT EXISTS "${source}")
    message(STATUS "EndfieldHUD resource ${id} is unavailable at build time; its module stays disabled")
    continue()
  endif()
  set(target "${STAGE_DIR}/${dest}")
  set(files_json "")
  if(kind STREQUAL "directory")
    file(GLOB_RECURSE files LIST_DIRECTORIES false RELATIVE "${source}" "${source}/*")
    list(SORT files)
    foreach(relative IN LISTS files)
      get_filename_component(name "${relative}" NAME)
      if(name STREQUAL ".DS_Store" OR name STREQUAL "Thumbs.db" OR name MATCHES "\\.(pdb|ilk|tar|gz|zip)$")
        continue()
      endif()
      if(relative MATCHES "[\"\\\\;]")
        message(FATAL_ERROR "Resource ${id} contains an unsupported file name: ${relative}")
      endif()
      list(APPEND staged_files "${dest}/${relative}")
      get_filename_component(parent "${target}/${relative}" DIRECTORY)
      file(MAKE_DIRECTORY "${parent}")
      file(COPY_FILE "${source}/${relative}" "${target}/${relative}" ONLY_IF_DIFFERENT)
      file(SIZE "${target}/${relative}" bytes)
      file(SHA256 "${target}/${relative}" sha)
      if(files_json)
        string(APPEND files_json ",")
      endif()
      string(APPEND files_json "{\"path\":\"${relative}\",\"bytes\":${bytes},\"sha256\":\"${sha}\"}")
    endforeach()
  elseif(kind STREQUAL "file")
    get_filename_component(parent "${target}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    file(COPY_FILE "${source}" "${target}" ONLY_IF_DIFFERENT)
    file(SIZE "${target}" bytes)
    file(SHA256 "${target}" sha)
    set(files_json "{\"path\":\"\",\"bytes\":${bytes},\"sha256\":\"${sha}\"}")
    list(APPEND staged_files "${dest}")
  else()
    message(FATAL_ERROR "Unknown resource kind ${kind} for ${id}")
  endif()
  if(NOT files_json)
    message(STATUS "EndfieldHUD resource ${id} is empty; its module stays disabled")
    continue()
  endif()
  if(entries)
    string(APPEND entries ",")
  endif()
  string(APPEND entries "\n    \"${id}\":{\"path\":\"${dest}\",\"kind\":\"${kind}\",\"files\":[${files_json}]}")
  math(EXPR staged "${staged}+1")
endforeach()
# Prune what the manifest does not list (an earlier layout or a removed input).
file(GLOB_RECURSE existing LIST_DIRECTORIES false RELATIVE "${STAGE_DIR}" "${STAGE_DIR}/*")
foreach(relative IN LISTS existing)
  if(NOT relative IN_LIST staged_files AND NOT relative STREQUAL "resources.json.staging")
    file(REMOVE "${STAGE_DIR}/${relative}")
  endif()
endforeach()
file(GLOB_RECURSE folders LIST_DIRECTORIES true RELATIVE "${STAGE_DIR}" "${STAGE_DIR}/*")
list(SORT folders ORDER DESCENDING)
foreach(relative IN LISTS folders)
  if(IS_DIRECTORY "${STAGE_DIR}/${relative}")
    file(GLOB children "${STAGE_DIR}/${relative}/*")
    if(NOT children)
      file(REMOVE_RECURSE "${STAGE_DIR}/${relative}")
    endif()
  endif()
endforeach()
set(manifest "{\"format\":\"EndfieldHUD.Windows.Resources\",\"schema\":1,\"sourceCommit\":\"${SOURCE_COMMIT}\",\"resources\":{${entries}\n}}\n")
file(WRITE "${STAGE_DIR}/resources.json.staging" "${manifest}")
file(RENAME "${STAGE_DIR}/resources.json.staging" "${STAGE_DIR}/resources.json")
message(STATUS "EndfieldHUD staged ${staged} runtime resources into ${STAGE_DIR}")
