#include "native/archive_scene.hpp"
#include "core/motion.hpp"
#include <algorithm>
#include <cmath>
#include <set>
#include <stdexcept>

namespace endfield::native {
namespace {
using J=ehud::data::Json;using Matrix=core::Matrix4;using Rect=core::Rect;
void need(bool value,const char*message){if(!value)throw std::invalid_argument(message);}
double number(const J&j,double fallback=0){if(j.isNull())return fallback;need(j.isNumber()&&std::isfinite(j.number()),"Invalid Archive artwork number");return j.number();}
bool flag(const J&j,bool fallback=false){return j.isNull()?fallback:j.boolean();}
std::string string(const J&j){return j.isNull()?std::string{}:j.string();}
Rect rect(const J&j){need(j.isArray()&&j.array().size()==4,"Invalid Archive artwork rectangle");const auto&a=j.array();Rect r{number(a[0]),number(a[1]),number(a[2]),number(a[3])};need(r.width>=0&&r.height>=0&&r.width<=8192&&r.height<=8192,"Archive artwork exceeds geometry bounds");return r;}
const J::Array&children(const J&j){static const J::Array empty;return j["children"].isNull()?empty:j["children"].array();}
bool drawing(const J&j){const auto kind=string(j["kind"]);return !j["backgroundColor"].isNull()||!j["contents"].isNull()||number(j["borderWidth"])>0||kind=="shape"||kind=="text";}
struct Compiler {
 const modules::ArchiveArtwork&artwork;ArchiveScenePlan result;J::Array leaves;std::set<std::string,std::less<>>ids;std::size_t visited{};
 explicit Compiler(const modules::ArchiveArtwork&a):artwork(a){result.feedback=a.feedback;result.bounds=rect(a.root["bounds"]);}
 void emit(J node,const Matrix&world,double opacity,const std::vector<Rect>&clips,bool grouped){
  const auto id=string(node["id"]);need(!id.empty()&&id.size()<=450&&J::validUtf8(id)&&ids.insert(id).second,"Invalid or repeated Archive surface identity");const auto b=rect(node["bounds"]);node["position"]=J::Array{world.values[12]+b.x,world.values[13]+b.y};node["anchorPoint"]=J::Array{0,0};node["opacity"]=1;node["zPosition"]=0;node["transform"]=nullptr;if(!grouped)node["children"]=J::Array{};
  ArchiveSurface surface{id,world,static_cast<float>(opacity),clips};for(std::size_t n=0;n<artwork.feedback.size();++n){const auto&f=artwork.feedback[n];if(id==f.tintID||id==f.rimID){need(!surface.feedback,"Ambiguous Archive feedback surface");surface.feedback=n;surface.rim=id==f.rimID;}}
  leaves.push_back(std::move(node));result.surfaces.push_back(std::move(surface));
 }
 void visit(J node,const Matrix&parent,double alpha,std::vector<Rect>clips,unsigned depth){
  need(depth<=32&&++visited<=LayerRasterizer::maximumNodes,"Archive artwork hierarchy exceeds bounds");need(node.isObject()&&node["transform"].isNull()&&node["sublayerTransform"].isNull()&&node["mask"].isNull(),"Archive original local artwork requires translation-only geometry");if(flag(node["hidden"]))return;const auto b=rect(node["bounds"]);const auto&p=node["position"].array(),&anchor=node["anchorPoint"].array();need(p.size()==2&&anchor.size()==2&&number(anchor[0])==0&&number(anchor[1])==0,"Archive artwork requires its explicit source-local anchoring");const auto world=parent*Matrix::translation(number(p[0])-b.x,number(p[1])-b.y);const auto opacity=number(node["opacity"],1);need(opacity>=0&&opacity<=1,"Invalid Archive surface opacity");need(depth==0||number(node["zPosition"])==0,"Archive child z-order requires explicit source paint order");
  if(flag(node["masksToBounds"])){need(clips.size()<8&&number(node["cornerRadius"])==0,"Unsupported nested Archive rounded clip");clips.push_back({world.values[12]+b.x,world.values[13]+b.y,b.width,b.height});}
  const auto id=string(node["id"]);const bool card=id.starts_with("archive/card/")&&string(node["name"]).starts_with("archive.card."),category=id.starts_with("archive/category/")&&string(node["name"]).starts_with("archive.category.");
  if(card||category){J::Array ordinary,feedback;for(const auto&child:children(node))(string(child["name"])=="hud.control.highlight"?feedback:ordinary).push_back(child);node["children"]=std::move(ordinary);emit(std::move(node),world,alpha*opacity,clips,true);for(const auto&child:feedback)visit(child,world,alpha*opacity,clips,depth+1);return;}
  const auto saved=children(node);const bool border=number(node["borderWidth"])>0&&!saved.empty();auto own=node;if(border)own["borderWidth"]=0;if(drawing(own))emit(std::move(own),world,alpha*opacity,clips,false);for(const auto&child:saved)visit(child,world,alpha*opacity,clips,depth+1);
  if(border){auto edge=node;edge["id"]=id+"/native-border";edge["kind"]="layer";edge["backgroundColor"]=nullptr;edge["contents"]=nullptr;edge.erase("shape");edge.erase("text");emit(std::move(edge),world,alpha*opacity,clips,false);}
 }
};
}
ArchiveScenePlan prepareArchiveScene(const modules::ArchiveArtwork&artwork,bool faceOnly){need(artwork.root.isObject()&&artwork.feedback.size()<=64,"Invalid bounded Archive artwork");Compiler c(artwork);if(faceOnly){const auto face=std::find_if(children(artwork.root).begin(),children(artwork.root).end(),[](const J&v){return v["name"]==J("archive.face");});need(face!=children(artwork.root).end(),"Archive main canvas has no original face");c.visit(*face,{},1,{},0);}else c.visit(artwork.root,{},1,{},0);need(!c.result.surfaces.empty()&&c.result.surfaces.size()<=LayerRasterizer::maximumEntries,"Archive artwork exceeds retained raster capacity");for(std::size_t n=0;n<artwork.feedback.size();++n)for(bool rim:{false,true})need(std::count_if(c.result.surfaces.begin(),c.result.surfaces.end(),[&](const auto&s){return s.feedback==n&&s.rim==rim;})==1,"Archive feedback must resolve exactly once");c.result.layers=J::Object{{"bounds",J::Array{0,0,0,0}},{"position",J::Array{0,0}},{"anchorPoint",J::Array{0,0}},{"allowsGroupOpacity",false},{"children",std::move(c.leaves)}};return std::move(c.result);}
#ifdef _WIN32
struct NativeArchiveScene::Impl {
 struct Track{double from{},target{},start{},duration{};};
 struct Part {
  ArchiveScenePlan plan;LayerScene local;std::unique_ptr<NativeLayerGroup>group;std::vector<LayerPlacement>placements;std::vector<std::array<PlaneMask,8>>masks;std::vector<std::array<Track,2>>tracks;bool uploaded{};
  std::array<DrawObject,1>media;bool hasMedia{};std::optional<std::size_t>mediaSlot,progressSlot;double progress{1};
  std::optional<NativeGroupInsertion>insertion()const{return hasMedia?std::optional(NativeGroupInsertion{*mediaSlot,media,modules::ArchiveState::mediaRect()}):std::nullopt;}
  Part(LayerRasterizer&r,ArchiveScenePlan p,const LayerRasterOptions&o):plan(std::move(p)),local(r),placements(plan.surfaces.size()),masks(plan.surfaces.size()),tracks(plan.feedback.size()){
   local.load(plan.layers,o);need(local.report().unsupported.empty()&&local.draws().size()==plan.surfaces.size(),"Unsupported original Archive local artwork");for(std::size_t n=0;n<plan.surfaces.size();++n){const auto&s=plan.surfaces[n];need(local.surfaceIndex(s.id)==n,"Archive cached surface order changed");auto&p=placements[n];p={n,s.local,s.opacity,{}};for(std::size_t k=0;k<s.clips.size();++k)masks[n][k]={Matrix{},s.clips[k]};p.masks={masks[n].data(),s.clips.size()};if(s.feedback)tracks[*s.feedback][s.rim?1:0].from=tracks[*s.feedback][s.rim?1:0].target=s.opacity;}
   for(std::size_t n=0;n<plan.surfaces.size();++n){if(plan.surfaces[n].id=="archive/action/mediaPrevious/plate")mediaSlot=n;if(plan.surfaces[n].id=="archive/mediaProgress")progressSlot=n;}
   local.setPlacements(placements);local.prepareDraws();group=std::make_unique<NativeLayerGroup>(local,"archive.face",o.pixelsPerPoint);
  }
 };
 LayerRasterizer&raster;LayerRasterOptions options;modules::ArchiveArtwork artwork;std::unique_ptr<LayerScene>backdrop;J backdropPayload;std::unique_ptr<Part>current,outgoing;std::vector<std::unique_ptr<Part>>retired;std::vector<std::unique_ptr<LayerScene>>retiredBackdrops;std::vector<LayerCompositionEntry>entries;
 std::uint64_t revision{},backdropUploadedRevision{};Renderer*resourceRenderer{};std::optional<double>lastTime,transitionStart;bool reduced{},main{},posed{};float opacity{1};NativeArchiveSceneStats stats;
 Impl(LayerRasterizer&r,LayerRasterOptions o):raster(r),options(std::move(o)){retired.reserve(4);retiredBackdrops.reserve(2);entries.reserve(3);}
 void time(double t)const{need(std::isfinite(t)&&(!lastTime||t>=*lastTime),"Archive requires a finite monotonic owner clock");}
 static double sample(const Track&t,double now){return t.duration>0?t.from+(t.target-t.from)*core::CubicTiming{0,0,.58,1}.value((now-t.start)/t.duration):t.target;}
 void retire(std::unique_ptr<Part>&p){if(p){need(retired.size()<4,"Publish/collect retired Archive resources before another replacement");retired.push_back(std::move(p));}}
 void rebuild(){entries.clear();if(backdrop)entries.push_back({backdrop.get(),{}});if(current&&current->uploaded)entries.push_back(current->group->entry());if(outgoing&&outgoing->uploaded)entries.push_back(outgoing->group->entry());}
};
NativeArchiveScene::NativeArchiveScene(LayerRasterizer&r,LayerRasterOptions o):impl_(std::make_unique<Impl>(r,std::move(o))){}
NativeArchiveScene::~NativeArchiveScene()=default;
bool NativeArchiveScene::syncContent(modules::ArchiveArtwork artwork,std::uint64_t revision,double time,bool animated,bool reduced){auto&i=*impl_;i.time(time);need(revision>0,"Archive content needs an explicit source revision");if(i.revision&&i.artwork.root==artwork.root){i.artwork=std::move(artwork);i.revision=revision;i.lastTime=time;return false;}need(i.retired.size()+(i.outgoing?1:0)+(i.current&&!animated?1:0)<=4,"Publish/collect old Archive resources before replacement");const bool main=artwork.root["name"]==J("archive.canvas");need(!i.revision||i.main==main,"Archive scene cannot change canvas/menu ownership");auto plan=prepareArchiveScene(artwork,main);need(plan.surfaces.size()<=LayerRasterizer::maximumEntries-i.raster.stats().entries,"Archive replacement exceeds shared raster cache capacity");auto next=std::make_unique<Impl::Part>(i.raster,std::move(plan),i.options);std::unique_ptr<LayerScene>backdrop;J backdropPayload;
 if(main){const auto found=std::find_if(children(artwork.root).begin(),children(artwork.root).end(),[](const J&j){return j["name"]==J("archive.backdrop");});need(found!=children(artwork.root).end(),"Missing original Archive backdrop");backdropPayload=*found;if(!i.backdrop||i.backdropPayload!=backdropPayload){backdrop=std::make_unique<LayerScene>(i.raster);backdrop->load(backdropPayload,i.options);need(backdrop->report().unsupported.empty()&&backdrop->draws().size()==1,"Unsupported Archive backdrop");}}
 // All content parsing/raster staging finished before live scene ownership moves.
 need(!backdrop||!i.backdrop||i.retiredBackdrops.size()<2,"Publish/collect old Archive appearance resources before replacement");i.retire(i.outgoing);if(animated&&!reduced&&i.current){i.outgoing=std::move(i.current);i.transitionStart=time;}else{i.retire(i.current);i.transitionStart.reset();}i.current=std::move(next);if(backdrop){if(i.backdrop)i.retiredBackdrops.push_back(std::move(i.backdrop));i.backdrop=std::move(backdrop);i.backdropUploadedRevision=0;}i.backdropPayload=std::move(backdropPayload);i.artwork=std::move(artwork);i.main=main;i.revision=revision;i.reduced=reduced;i.posed=false;i.lastTime=time;++i.stats.builds;i.rebuild();return true;}
bool NativeArchiveScene::setFeedback(std::optional<core::Point>point,bool pressed,double time,bool reduced){auto&i=*impl_;i.time(time);need(bool(i.current),"Initialize Archive before feedback");std::optional<std::size_t>hit;double area=INFINITY;if(point)for(std::size_t n=0;n<i.current->plan.feedback.size();++n){const auto&f=i.current->plan.feedback[n];if(modules::archiveFeedbackContains(f,*point)&&f.rect.width*f.rect.height<=area){hit=n;area=f.rect.width*f.rect.height;}}
 bool changed{};for(std::size_t n=0;n<i.current->tracks.size();++n){const auto&f=i.current->plan.feedback[n];for(unsigned k=0;k<2;++k){auto&t=i.current->tracks[n][k];const bool selected=hit==n;const double target=k?(selected?1:f.enabled&&f.framed?.28:0):(selected?pressed?1:.62:0);if(t.target==target&&!reduced)continue;t={Impl::sample(t,time),target,time,reduced?0:pressed&&selected?.06:.14};changed=true;}}
 if(changed){++i.stats.feedbackChanges;i.posed=false;}i.lastTime=time;return changed;}
bool NativeArchiveScene::setMediaDraw(std::optional<DrawObject>draw){auto&i=*impl_;need(bool(i.current),"Initialize Archive before media binding");auto&p=*i.current;
 if(draw){need(p.mediaSlot.has_value(),"Archive media requires selected-document footer slot");validateDrawObject(*draw);need(draw->masks.size()==1&&draw->masks[0].worldToLocal==Matrix{}&&draw->masks[0].bounds==modules::ArchiveState::mediaRect()&&draw->masks[0].cornerRadius==0&&!draw->shutter&&!draw->alphaMask&&!draw->angularMask,"Archive media must preserve its exact local media clip");}
 if(!draw&&!p.hasMedia)return false;if(draw&&p.hasMedia){const auto&old=p.media[0];if(old.sourceID==draw->sourceID&&old.meshID==draw->meshID&&old.textureID==draw->textureID&&old.world==draw->world&&old.linearTint==draw->linearTint&&old.opacity==draw->opacity&&old.masks.size()==draw->masks.size()&&std::equal(old.masks.begin(),old.masks.end(),draw->masks.begin(),[](const auto&a,const auto&b){return a.worldToLocal==b.worldToLocal&&a.bounds==b.bounds&&a.cornerRadius==b.cornerRadius;}))return false;}
 if(draw)p.media[0]=std::move(*draw);p.hasMedia=draw.has_value();p.uploaded=false;i.posed=false;return true;
}
void NativeArchiveScene::setMediaProgress(double fraction){auto&i=*impl_;need(std::isfinite(fraction)&&fraction>=0&&fraction<=1,"Invalid Archive progress fraction");if(i.current)i.current->progress=fraction;}
bool NativeArchiveScene::uploadResources(Renderer&r){auto&i=*impl_;need(bool(i.current),"Initialize Archive before upload");need(!i.resourceRenderer||i.resourceRenderer==&r,"Archive resources belong to another renderer");need(r.stats().initialized,"Archive resources require an initialized renderer");i.resourceRenderer=&r;bool changed{};
 // Resource IDs are owned strings at the Renderer boundary. Do not copy them
 // again on numeric tilt/fade frames when the local artwork is still resident.
 if(i.backdrop&&i.backdropUploadedRevision!=i.backdrop->resourceRevision()){i.backdrop->uploadResources(r);i.backdropUploadedRevision=i.backdrop->resourceRevision();changed=true;}
 for(auto*p:{i.current.get(),i.outgoing.get()})if(p&&!p->uploaded){changed=p->group->uploadResources(r,{},p->insertion())||changed;p->uploaded=true;}i.rebuild();return changed;}
void NativeArchiveScene::updatePose(const NativeArchivePose&pose){auto&i=*impl_;i.time(pose.time);need(i.current&&i.current->uploaded&&pose.world.finite()&&std::isfinite(pose.opacity)&&pose.opacity>=0&&pose.opacity<=1&&pose.ownerMasks.size()<=8,"Upload Archive resources before a valid pose");if(pose.shutter)validatePlaneShutter(*pose.shutter);double fraction=1;if(i.transitionStart)fraction=std::clamp((pose.time-*i.transitionStart)/.18,0.,1.);const auto place=[&](Impl::Part&p,float alpha){for(std::size_t n=0;n<p.placements.size();++n){const auto&s=p.plan.surfaces[n];p.placements[n].world=s.local;if(p.progressSlot==n)p.placements[n].world=s.local*Matrix::scale(p.progress,1);p.placements[n].opacity=s.feedback?static_cast<float>(Impl::sample(p.tracks[*s.feedback][s.rim?1:0],pose.time)):s.opacity;}p.local.setPlacements(p.placements);p.group->setPose(pose.world,alpha,pose.ownerMasks,pose.shutter);};place(*i.current,pose.opacity*static_cast<float>(fraction));if(i.outgoing)place(*i.outgoing,pose.opacity*static_cast<float>(1-fraction));if(i.backdrop){const std::array<LayerPlacement,1>placement{{{0,pose.world,pose.opacity,pose.ownerMasks}}};i.backdrop->setPlacements(placement);i.backdrop->setGroupShutter(pose.shutter);}
 if(i.transitionStart&&pose.time-*i.transitionStart>=.2){i.retire(i.outgoing);i.transitionStart.reset();i.rebuild();}i.opacity=pose.opacity;i.lastTime=pose.time;i.posed=true;++i.stats.poses;}
bool NativeArchiveScene::uploadAnimations(Renderer&r){auto&i=*impl_;need(i.posed,"Place Archive before updating local group content");bool changed{};for(auto*p:{i.current.get(),i.outgoing.get()})if(p)changed=p->group->updateLocal(r,p->insertion())||changed;return changed;}
bool NativeArchiveScene::requiresFrames(double time)const{auto&i=*impl_;i.time(time);if(i.opacity==0)return false;if(i.transitionStart&&time-*i.transitionStart<.2)return true;if(i.current)for(const auto&pair:i.current->tracks)for(const auto&t:pair)if(t.from!=t.target&&time<t.start+t.duration)return true;return false;}
std::span<const LayerCompositionEntry>NativeArchiveScene::entries()const noexcept{return impl_->entries;}
bool NativeArchiveScene::collectRetired(Renderer&r){auto&i=*impl_;for(auto it=i.retired.begin();it!=i.retired.end();){if(!(*it)->group->releaseResources(r))return false;it=i.retired.erase(it);}for(auto it=i.retiredBackdrops.begin();it!=i.retiredBackdrops.end();){if(!(*it)->releaseResources(r))return false;it=i.retiredBackdrops.erase(it);}if(i.backdrop)i.backdrop->collectRetiredResources(r);return true;}
bool NativeArchiveScene::releaseResources(Renderer&r){auto&i=*impl_;need(!i.resourceRenderer||i.resourceRenderer==&r,"Archive resources belong to another renderer");bool okay=collectRetired(r);for(auto*p:{i.current.get(),i.outgoing.get()})if(p)okay=p->group->releaseResources(r)&&okay;if(i.backdrop)okay=i.backdrop->releaseResources(r)&&okay;if(okay){i.resourceRenderer=nullptr;i.backdropUploadedRevision=0;for(auto*p:{i.current.get(),i.outgoing.get()})if(p)p->uploaded=false;}return okay;}
const modules::ArchiveArtwork&NativeArchiveScene::artwork()const noexcept{return impl_->artwork;}
NativeArchiveSceneStats NativeArchiveScene::stats()const noexcept{auto s=impl_->stats;s.surfaces=impl_->current?impl_->current->plan.surfaces.size():0;s.outgoingSurfaces=impl_->outgoing?impl_->outgoing->plan.surfaces.size():0;s.retiredParts=impl_->retired.size()+impl_->retiredBackdrops.size();return s;}
#endif
} // namespace endfield::native
