#include "native/media_assembly_scene.hpp"
#include "core/motion.hpp"
#include <algorithm>
#include <cmath>
#if defined(__clang__)
#pragma clang fp contract(off)
#elif defined(_MSC_VER)
#pragma float_control(precise,on,push)
#pragma fp_contract(off)
#endif
namespace endfield::native {namespace {
void need(bool v,const char*s){if(!v)throw std::invalid_argument(s);}
void finite(double v){need(std::isfinite(v),"Nonfinite Media Assembly animation time");}
// Observed source CA easeOut: bounded Float clock/control/result conversion.
double easeOut(double value){finite(value);if(value<=0)return 0;if(value>=1)return 1;const double x=float(value),x2=float(.58),a=1-3*x2,b=3*x2;double t=x;for(unsigned n=0;n<8;++n){const auto e=(a*t+b)*t*t-x;if(std::abs(e)<1e-5)break;t-=e/((3*a*t+2*b)*t);}return float((3-2*t)*t*t);}
}
modules::MediaAssemblyArtworkAssets mediaAssemblyArtworkAssets(const NativeMediaAssemblyAssets&a){modules::MediaAssemblyArtworkAssets result;for(std::size_t n=1;n<result.filters.size();++n){const auto&v=a.filterThumbnail(modules::MediaAssemblyFilter(n));result.filters[n]={v.path,v.sha256};}for(std::size_t n=0;n<result.stickers.size();++n){const auto&v=a.sticker(modules::MediaAssemblyStickerKind(n));result.stickers[n]={v.path,v.sha256};}return result;}
}
#ifdef _WIN32
#include "native/layer_group.hpp"
#include "core/source_camera.hpp"
#include <atomic>
namespace endfield::native {namespace {
namespace m=modules;using J=ehud::data::Json;using M=core::Matrix4;using R=core::Rect;using G=m::MediaAssemblyPaintGroup;using Role=m::MediaAssemblyPaintRole;
constexpr std::size_t groups=6;
J root(const std::vector<m::MediaAssemblySurface>&plan){J::Array children;children.reserve(plan.size());for(const auto&s:plan)children.push_back(s.content);return J::Object{{"bounds",J::Array{0,0,440,440}},{"position",J::Array{0,0}},{"anchorPoint",J::Array{0,0}},{"children",std::move(children)}};}
bool valid(R r){return std::isfinite(r.x)&&std::isfinite(r.y)&&std::isfinite(r.width)&&std::isfinite(r.height)&&r.width>0&&r.height>0&&std::isfinite(r.x+r.width)&&std::isfinite(r.y+r.height);}
bool cutContains(R r,core::Point p){if(!r.contains(p))return false;const auto x=p.x-r.x,y=p.y-r.y,k=std::min(4.,std::min(r.width,r.height)/3);return x+y>=k&&x+y<=r.width+r.height-k;}
struct Track{double from{},target{},start{},duration{};double value(double time)const{return duration?from+(target-from)*easeOut((time-start)/duration):target;}bool active(double time)const noexcept{return duration&&from!=target&&time<start+duration;}};
M fit(const MediaAssemblyPreviewDraw&v,R rect){need(valid(v.sourceBounds)&&valid(rect),"Invalid borrowed Media Assembly image plane");return M::translation(rect.x,rect.y)*M::scale(rect.width/v.sourceBounds.width,rect.height/v.sourceBounds.height)*M::translation(-v.sourceBounds.x,-v.sourceBounds.y)*v.draw.world;}
void checkPreview(const MediaAssemblyPreviewDraw&v){validateDrawObject(v.draw);need(valid(v.sourceBounds)&&v.draw.masks.empty()&&!v.draw.shutter&&!v.draw.alphaMask&&!v.draw.angularMask,"Media Assembly preview must be an unclipped local provider image");const auto&a=v.draw.world.values;need(a[2]==0&&a[3]==0&&a[6]==0&&a[7]==0&&a[8]==0&&a[9]==0&&a[11]==0&&a[14]==0&&a[15]==1,"Media Assembly preview must remain in its local plane");}
}
struct NativeMediaAssemblyScene::Impl {
 struct Part {
  std::vector<m::MediaAssemblySurface>plan;LayerScene scene;std::unique_ptr<NativeLayerGroup>group;std::vector<LayerPlacement>placements;std::vector<std::array<PlaneMask,8>>masks;std::vector<Track>tracks;std::vector<std::uint64_t>localRevisions;std::uint64_t uploadedRevision{};bool uploaded{},residentAttempted{};
  Part(LayerRasterizer&r,std::vector<m::MediaAssemblySurface>p,const LayerRasterOptions&o,G kind):plan(std::move(p)),scene(r),placements(plan.size()),masks(plan.size()),tracks(plan.size()),localRevisions(plan.size(),1){scene.load(root(plan),o);need(scene.report().unsupported.empty(),"Unsupported original Media Assembly artwork");for(std::size_t n=0;n<plan.size();++n){const auto index=scene.surfaceIndex(plan[n].id);need(index&&*index==n,"Media Assembly source leaves must remain independent");tracks[n].target=plan[n].opacity;placements[n]={n,plan[n].local,plan[n].opacity,{}};}scene.setPlacements(placements);scene.prepareDraws();if(kind==G::drawer)group=std::make_unique<NativeLayerGroup>(scene,"media.drawer",o.pixelsPerPoint,NativeGroupColorSpace::encodedSRGB);}
  bool sameShape(const std::vector<m::MediaAssemblySurface>&v)const{if(v.size()!=plan.size())return false;for(std::size_t n=0;n<v.size();++n)if(v[n].id!=plan[n].id)return false;return true;}
 };
 struct Closing {
  LayerScene carrier;std::unique_ptr<Part>stickers;MediaAssemblyPreviewDraw poster;R image;std::string id;std::vector<DrawObject>children;std::array<DrawObject,1>output;bool registered{},ready{},built{};
  Closing(LayerRasterizer&r,MediaAssemblyPreviewDraw p,R box):carrier(r),poster(std::move(p)),image(box){static std::atomic<std::uint64_t>sequence{};id="media.close."+std::to_string(++sequence);output[0].masks.reserve(8);children.reserve(17);}
 };
 LayerRasterizer&raster;LayerRasterOptions options;m::MediaAssemblyArtworkAssets assets;std::array<std::unique_ptr<Part>,groups>parts;std::vector<std::unique_ptr<Part>>retired;std::unique_ptr<Closing>closing;std::vector<std::unique_ptr<Closing>>oldClosing;MediaAssemblyMotion motion;std::optional<MediaAssemblyPreviewDraw>preview;std::array<DrawObject,1>previewOutput;std::array<LayerCompositionEntry,7>entryStorage;std::size_t count{};R image{};M world;float opacity{1};double time{},targetOffset{};std::array<PlaneMask,6>ownerMasks;std::size_t ownerMaskCount{};std::optional<PlaneShutter>shutter;std::optional<core::Point>pointer;bool pressed{},reduced{},posed{},feedbackDirty{true};Renderer*renderer{};MediaAssemblySceneStats statistics;
 Impl(LayerRasterizer&r,LayerRasterOptions o,const NativeMediaAssemblyAssets&a):raster(r),options(std::move(o)),assets(mediaAssemblyArtworkAssets(a)){need(options.assetRoot==a.root(),"Media Assembly scene must use its pinned original asset root");retired.reserve(12);oldClosing.reserve(2);previewOutput[0].masks.reserve(8);}
 void clock(double t)const{need(std::isfinite(t)&&t>=time,"Media Assembly scene requires monotonic time");}
 void retire(std::unique_ptr<Part>p){if(p&&p->residentAttempted)retired.push_back(std::move(p));}
 void retireClosing(){if(closing){if(closing->registered||(closing->stickers&&closing->stickers->residentAttempted))oldClosing.push_back(std::move(closing));else closing.reset();}}
 void refresh(){count=0;for(std::size_t k=0;k<groups;++k){if(parts[k]){auto&p=*parts[k];if(p.group){if(p.uploaded)entryStorage[count++]=p.group->entry();}else entryStorage[count++]={&p.scene,k==std::size_t(G::stage)&&preview?std::span<const DrawObject>(previewOutput):std::span<const DrawObject>{}};}if(k==std::size_t(G::stage)&&closing&&closing->ready)entryStorage[count++]={&closing->carrier,closing->output};}}
 bool releasePart(Part&p,Renderer&r){p.uploadedRevision=0;const bool done=p.group?p.group->releaseResources(r):p.scene.releaseResources(r);if(done){p.uploaded=false;p.residentAttempted=false;}return done;}
 bool releaseClose(Closing&p,Renderer&r){if(p.registered&&r.stats().initialized&&!r.removeNativeGroup(p.id))return false;p.registered=false;p.ready=false;return !p.stickers||releasePart(*p.stickers,r);}
 void posePart(Part&p,bool local){const M base=local?M{}:world;const auto inverse=local?M{}:core::source::inverseSourceMatrix(world);for(std::size_t n=0;n<p.plan.size();++n){const auto&s=p.plan[n];auto&v=p.placements[n];const auto delta=s.role==Role::inlineItem?targetOffset-motion.inlineOffset(time):0;v.world=base*M::translation(0,delta)*s.local;v.opacity=(local?1:opacity)*float(s.role==Role::tint||s.role==Role::rim?p.tracks[n].value(time):s.opacity);std::size_t maskCount=local?0:ownerMaskCount;if(!local)std::copy_n(ownerMasks.begin(),maskCount,p.masks[n].begin());for(std::size_t k=0;k<s.clipCount;++k)p.masks[n][maskCount++]={inverse,s.clips[k].bounds,s.clips[k].cornerRadius};v.masks=std::span(p.masks[n]).first(maskCount);}p.scene.setPlacements(p.placements);p.scene.setGroupShutter(local?std::nullopt:shutter);p.scene.prepareDraws();}
 void posePreview(){if(!preview)return;auto&d=previewOutput[0];d.world=world*fit(*preview,image);d.opacity=opacity*preview->draw.opacity;d.masks.assign(ownerMasks.begin(),ownerMasks.begin()+ownerMaskCount);const auto inverse=core::source::inverseSourceMatrix(world);d.masks.push_back({inverse,m::MediaAssemblyPresentation::previewRect,4});d.masks.push_back({inverse,image});d.shutter=shutter;}
 void poseGroups(){const auto mask=std::span(ownerMasks).first(ownerMaskCount);if(parts[std::size_t(G::drawer)]){auto&p=*parts[std::size_t(G::drawer)];if(p.uploaded)p.group->setPose(world,opacity*float(motion.drawerOpacity(time)),mask,shutter);}if(closing&&closing->ready){auto&d=closing->output[0];d.world=world;d.opacity=opacity*float(motion.closeOpacity(time));d.masks.assign(mask.begin(),mask.end());d.shutter=shutter;}}
};
NativeMediaAssemblyScene::NativeMediaAssemblyScene(LayerRasterizer&r,LayerRasterOptions o,const NativeMediaAssemblyAssets&a):impl_(std::make_unique<Impl>(r,std::move(o),a)){}
NativeMediaAssemblyScene::~NativeMediaAssemblyScene()=default;
bool NativeMediaAssemblyScene::syncContent(const m::MediaAssemblyPresentation&p,const m::MediaAssemblyView&v,const m::MediaAssemblyAppearance&a,std::string_view error,double progress,double time,bool animateInline,bool reduced){auto&i=*impl_;i.clock(time);auto art=m::prepareMediaAssemblyArtwork(p,v,a,i.assets,error,progress);std::array<std::vector<m::MediaAssemblySurface>,groups>plans;for(auto&s:art.surfaces)plans[std::size_t(s.group)].push_back(std::move(s));std::array<std::unique_ptr<Impl::Part>,groups>replacements;for(std::size_t k=0;k<groups;++k)if(!plans[k].empty()&&(!i.parts[k]||!i.parts[k]->sameShape(plans[k])))replacements[k]=std::make_unique<Impl::Part>(i.raster,std::move(plans[k]),i.options,G(k));bool changed=i.image!=art.imageRect;for(std::size_t k=0;k<groups;++k){auto&old=i.parts[k];if(replacements[k]||plans[k].empty()){if(replacements[k]||old){i.retire(std::move(old));old=std::move(replacements[k]);changed=true;++i.statistics.builds;}continue;}auto&part=*old;if(part.scene.fontRevision()!=i.raster.fontRevision()){changed=part.scene.refreshTypography()||changed;}for(std::size_t n=0;n<plans[k].size();++n){auto&next=plans[k][n];auto&before=part.plan[n];if(before.content!=next.content){need(part.localRevisions[n]!=UINT64_MAX,"Media Assembly local revision exhausted");part.scene.updateLocalContent(before.id,++part.localRevisions[n],next.content,i.options);++i.statistics.localUpdates;changed=true;}if(before.local!=next.local||before.clips!=next.clips||before.opacity!=next.opacity||before.feedbackEnabled!=next.feedbackEnabled)changed=true;before=std::move(next);}}
 i.image=art.imageRect;if(i.targetOffset!=p.drawerOffset()){i.motion.scrollInline(p.drawerOffset(),time,animateInline&&!reduced);i.targetOffset=p.drawerOffset();changed=true;}i.time=time;i.feedbackDirty|=changed;i.reduced=reduced;setFeedback(i.pointer,i.pressed,reduced,time);return changed;}
void NativeMediaAssemblyScene::setPreview(std::optional<MediaAssemblyPreviewDraw>draw){auto&i=*impl_;if(draw){checkPreview(*draw);auto next=draw->draw;next.masks.reserve(8);i.previewOutput[0]=std::move(next);}i.preview=std::move(draw);if(i.posed)i.posePreview();i.refresh();}
void NativeMediaAssemblyScene::revealDrawer(double time,bool animated){auto&i=*impl_;i.clock(time);i.motion.revealDrawer(time,animated);i.time=time;}
void NativeMediaAssemblyScene::beginClose(std::optional<MediaAssemblyPreviewDraw>poster,double time,bool animated){auto&i=*impl_;i.clock(time);if(poster)checkPreview(*poster);std::unique_ptr<Impl::Closing>next;if(poster&&animated){need(valid(i.image),"Synchronize Media Assembly image before closing");next=std::make_unique<Impl::Closing>(i.raster,std::move(*poster),i.image);}i.retireClosing();if(next){next->stickers=std::move(i.parts[std::size_t(G::stickers)]);i.closing=std::move(next);}i.preview.reset();i.motion.closeMedia(time,bool(i.closing));i.time=time;i.refresh();}
bool NativeMediaAssemblyScene::closingMedia()const noexcept{return bool(impl_->closing);}
void NativeMediaAssemblyScene::settle()noexcept{auto&i=*impl_;i.motion.settle();for(auto&p:i.parts)if(p)for(auto&t:p->tracks)t={t.target,t.target,0,0};}
bool NativeMediaAssemblyScene::setFeedback(std::optional<core::Point>point,bool pressed,bool reduced,double time){auto&i=*impl_;i.clock(time);if(point)need(std::isfinite(point->x)&&std::isfinite(point->y),"Invalid Media Assembly pointer");if(!i.feedbackDirty&&i.pointer==point&&i.pressed==pressed&&i.reduced==reduced)return false;std::string_view action;double area=INFINITY;if(point)for(auto&p:i.parts)if(p)for(const auto&s:p->plan)if(s.role==Role::tint&&s.feedbackEnabled){const auto&b=s.content["bounds"].array();R rect{s.local.values[12],s.local.values[13],b[2].number(),b[3].number()};bool inside=cutContains(rect,*point);for(std::size_t k=0;k<s.clipCount;++k)inside&=s.clips[k].bounds.contains(*point);if(inside&&rect.width*rect.height<=area){action=s.action;area=rect.width*rect.height;}}
 for(auto&p:i.parts)if(p)for(std::size_t n=0;n<p->plan.size();++n){const auto&s=p->plan[n];if(s.role!=Role::tint&&s.role!=Role::rim)continue;const bool match=s.feedbackEnabled&&s.action==action;const double target=match?(s.role==Role::rim?1:pressed?1:.62):(s.role==Role::rim&&s.feedbackEnabled&&s.framed?.28:0);auto&t=p->tracks[n];if(t.target!=target||(reduced&&t.duration))t={t.value(time),target,time,reduced?0:pressed&&match?.06:.14};}i.pointer=point;i.pressed=pressed;i.reduced=reduced;i.feedbackDirty=false;i.time=time;return true;}
void NativeMediaAssemblyScene::updatePose(const MediaAssemblyScenePose&p){auto&i=*impl_;i.clock(p.time);need(p.world.finite()&&std::isfinite(p.opacity)&&p.opacity>=0&&p.opacity<=1&&p.ownerMasks.size()<=6,"Invalid Media Assembly pose");(void)core::source::inverseSourceMatrix(p.world);if(p.shutter)validatePlaneShutter(*p.shutter);for(const auto&mask:p.ownerMasks)need(mask.worldToLocal.finite()&&valid(mask.bounds)&&std::isfinite(mask.cornerRadius)&&mask.cornerRadius>=0&&mask.cornerRadius<=std::min(mask.bounds.width,mask.bounds.height)*.5,"Invalid Media Assembly owner mask");i.world=p.world;i.opacity=p.opacity;i.time=p.time;i.ownerMaskCount=p.ownerMasks.size();std::copy(p.ownerMasks.begin(),p.ownerMasks.end(),i.ownerMasks.begin());i.shutter=p.shutter?std::optional(*p.shutter):std::nullopt;for(std::size_t k=0;k<groups;++k)if(i.parts[k])i.posePart(*i.parts[k],k==std::size_t(G::drawer));i.posePreview();if(i.closing&&i.motion.closeOpacity(p.time)==0)i.retireClosing();i.poseGroups();i.posed=true;i.refresh();++i.statistics.poses;}
void NativeMediaAssemblyScene::uploadResources(Renderer&r){auto&i=*impl_;need(i.posed&&r.stats().initialized&&(!i.renderer||i.renderer==&r),"Invalid Media Assembly resource owner");for(auto&p:i.parts)if(p){if(p->uploadedRevision!=p->scene.resourceRevision()||!p->uploaded){p->residentAttempted=true;if(p->group)p->group->uploadResources(r);else p->scene.uploadResources(r);p->uploadedRevision=p->scene.resourceRevision();p->uploaded=true;++i.statistics.uploads;}else if(p->group)p->group->updateLocal(r);}
 if(i.closing&&!i.closing->ready){auto&close=*i.closing;if(close.stickers){auto&p=*close.stickers;if(p.uploadedRevision!=p.scene.resourceRevision()||!p.uploaded){p.residentAttempted=true;p.scene.uploadResources(r);p.uploaded=true;p.uploadedRevision=p.scene.resourceRevision();}}if(!close.built){auto poster=close.poster.draw;poster.world=fit(close.poster,close.image);poster.masks={{M{},m::MediaAssemblyPresentation::previewRect,4},{M{},close.image}};close.children.push_back(std::move(poster));if(close.stickers){const auto draws=close.stickers->scene.draws();for(std::size_t n=0;n<draws.size();++n){auto draw=draws[n];draw.world=close.stickers->plan[n].local;draw.opacity=close.stickers->plan[n].opacity;draw.shutter.reset();draw.masks={{M{},m::MediaAssemblyPresentation::previewRect,4},{M{},close.image}};close.children.push_back(std::move(draw));}}close.built=true;}
 if(!close.registered){r.configureNativeGroup(close.id,{m::MediaAssemblyPresentation::previewRect,i.options.pixelsPerPoint,NativeGroupColorSpace::encodedSRGB},close.children);close.registered=true;}auto prepared=r.nativeGroupOutput(close.id);prepared.masks.reserve(8);close.output[0]=std::move(prepared);close.ready=true;++i.statistics.uploads;}
 i.renderer=&r;i.poseGroups();i.refresh();}
std::span<const LayerCompositionEntry>NativeMediaAssemblyScene::entries()const noexcept{return std::span(impl_->entryStorage).first(impl_->count);}
bool NativeMediaAssemblyScene::requiresFrames(double time)const{const auto&i=*impl_;i.clock(time);if(i.motion.requiresFrames(time))return true;for(const auto&p:i.parts)if(p)for(const auto&t:p->tracks)if(t.active(time))return true;return false;}
bool NativeMediaAssemblyScene::collectRetired(Renderer&r){auto&i=*impl_;for(auto&p:i.oldClosing)if(!i.releaseClose(*p,r))return false;i.oldClosing.clear();for(auto&p:i.retired)if(!i.releasePart(*p,r))return false;i.retired.clear();for(auto&p:i.parts)if(p&&!p->group)p->scene.collectRetiredResources(r);return true;}
bool NativeMediaAssemblyScene::releaseResources(Renderer&r){auto&i=*impl_;bool done=collectRetired(r);if(i.closing)done=i.releaseClose(*i.closing,r)&&done;for(auto&p:i.parts)if(p)done=i.releasePart(*p,r)&&done;if(done)i.renderer=nullptr;return done;}
MediaAssemblySceneStats NativeMediaAssemblyScene::stats()const noexcept{auto out=impl_->statistics;out.retired=impl_->retired.size()+impl_->oldClosing.size();for(const auto&p:impl_->parts)if(p)out.surfaces+=p->plan.size();return out;}
}
#endif
#if defined(_MSC_VER)&&!defined(__clang__)
#pragma float_control(pop)
#endif
