#include "native/projection_plane.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace endfield::native {
namespace {
using J=ehud::data::Json;using P=core::Point;using R=core::Rect;
void need(bool b,const char*s){if(!b)throw std::invalid_argument(s);}
J base(const char*id,R r,const char*kind="layer"){return J::Object{{"id",id},{"kind",kind},{"bounds",J::Array{r.x,r.y,r.width,r.height}},{"position",J::Array{r.x,r.y}},{"anchorPoint",J::Array{0,0}},{"children",J::Array{}}};}
J color(std::array<double,4>c){return J::Object{{"sRGB",J::Array{c[0],c[1],c[2],c[3]}}};}
J command(const char*op,std::initializer_list<P>points={}){J::Array values;for(auto p:points)values.push_back(J::Array{p.x,p.y});return J::Object{{"op",op},{"points",std::move(values)}};}
void quad(ProjectionGridMesh&out,R r,double u,double v){const auto first=std::uint32_t(out.vertices.size());for(const auto&xy:std::array<P,4>{{{0,0},{1,0},{1,1},{0,1}}}){Vertex vertex;vertex.position={float(r.x+xy.x*r.width),float(r.y+xy.y*r.height),0};vertex.uv={float(xy.x*u),float(xy.y*v)};out.vertices.push_back(vertex);}for(auto index:std::array<unsigned,6>{0,1,2,0,2,3})out.indices.push_back(first+index);}
}
ProjectionGridMesh projectionGridMesh(P size){need(std::isfinite(size.x)&&std::isfinite(size.y)&&size.x>0&&size.y>0,"Invalid Projection grid dimensions");const auto columns=std::ceil(size.x/36),rows=std::ceil(size.y/36);need(columns*rows<=250000,"Projection grid exceeds renderer mesh capacity");ProjectionGridMesh out;out.vertices.reserve(std::size_t(columns*rows)*4);out.indices.reserve(std::size_t(columns*rows)*6);for(unsigned y=0;y<rows;++y)for(unsigned x=0;x<columns;++x){const R r{x*36.,y*36.,std::min(36.,size.x-x*36),std::min(36.,size.y-y*36)};quad(out,r,r.width/36,r.height/36);}return out;}
J projectionDotCell(){auto root=base("projection.dot-cell",{0,0,36,36});root["masksToBounds"]=true;auto dot=base("projection.dot",{12,12,2,2});dot["backgroundColor"]=color({1,1,1,.14});root["children"]=J::Array{dot};return root;}
J projectionCursor(double width,std::array<double,4>c,bool erasing){need(std::isfinite(width)&&width>=1&&width<=80,"Invalid Projection cursor width");for(auto v:c)need(std::isfinite(v)&&v>=0&&v<=1,"Invalid Projection cursor color");if(erasing)c={1,1,1,1};const auto radius=width*.5,k=radius*.5522847498307936;auto root=base("projection.cursor",{-radius-1,-radius-1,width+2,width+2},"shape");root["shape"]=J::Object{{"path",J::Array{command("move",{{radius,0}}),command("cubic",{{radius,k},{k,radius},{0,radius}}),command("cubic",{{-k,radius},{-radius,k},{-radius,0}}),command("cubic",{{-radius,-k},{-k,-radius},{0,-radius}}),command("cubic",{{k,-radius},{radius,-k},{radius,0}}),command("close")}}, {"fillColor",J{}},{"strokeColor",color(c)},{"lineWidth",1},{"lineCap","butt"},{"lineJoin","miter"},{"lineDashPattern",erasing?J(J::Array{3,2}):J{}}};return root;}
#ifdef _WIN32
struct NativeProjectionPlane::Impl {
    LayerScene carrier,cell,cursor;LayerRasterOptions options;ProjectionGridMesh grid,plate;std::array<DrawObject,2>draws;P size{};double scale{},darkness{.5},backgroundOpacity{1};std::optional<P>pointer;double width{5};std::array<double,4>color{.98,.83,.12,1};bool erasing{},ready{},cursorReady{};std::uint64_t geometryRevision{},uploadedGeometry{},uploadedCell{},uploadedCursor{},cellRevision{1},cursorRevision{1};core::Matrix4 world;float opacity{1};Renderer*renderer{};ProjectionPlaneStats stats;
    Impl(LayerRasterizer&r,LayerRasterOptions o):carrier(r),cell(r),cursor(r),options(std::move(o)){options.paddingPoints=0;}
    void pose(){if(!ready)return;draws[0].world=draws[1].world=world;draws[0].opacity=opacity*float(backgroundOpacity);draws[1].opacity=draws[0].opacity;draws[0].linearTint={0,0,0,float(darkness)};const auto p=pointer.value_or(P{});const LayerPlacement value{0,world*core::Matrix4::translation(p.x,p.y),pointer?opacity:0,{}};cursor.setPlacements(std::span(&value,1));}
};
NativeProjectionPlane::NativeProjectionPlane(LayerRasterizer&r,LayerRasterOptions o):impl_(std::make_unique<Impl>(r,std::move(o))){}NativeProjectionPlane::~NativeProjectionPlane()=default;
bool NativeProjectionPlane::resize(P size,double scale){auto&i=*impl_;need(std::isfinite(scale)&&scale>=.25&&scale<=4&&std::isfinite(size.x)&&std::isfinite(size.y)&&size.x>0&&size.y>0,"Invalid Projection plane dimensions");const auto w=std::ceil(size.x*scale),h=std::ceil(size.y*scale);need(w>=1&&h>=1&&w<=8192&&h<=8192&&w*h<=Renderer::maximumRenderPixels,"Projection plane exceeds renderer viewport bound");if(i.ready&&i.size==size&&i.scale==scale)return false;auto grid=projectionGridMesh(size);ProjectionGridMesh plate;quad(plate,{0,0,size.x,size.y},1,1);auto options=i.options;options.pixelsPerPoint=scale;
    if(!i.ready){i.carrier.load(base("projection.background-carrier",{0,0,0,0}),options);i.cell.load(projectionDotCell(),options);i.cursor.load(projectionCursor(i.width,i.color,i.erasing),options);need(i.cell.draws().size()==1&&i.cursor.draws().size()==1&&i.cell.report().unsupported.empty()&&i.cursor.report().unsupported.empty(),"Unsupported Projection plane artwork");const auto&dot=i.cell.draws()[0];i.draws[0].sourceID=dot.sourceID+".plate";i.draws[0].meshID=i.draws[0].sourceID;i.draws[1]=dot;i.draws[1].sourceID=dot.sourceID+".grid";i.draws[1].meshID=i.draws[1].sourceID;}else if(i.scale!=scale){i.cell.updateLocalContent("projection.dot-cell",++i.cellRevision,projectionDotCell(),options);i.cursor.updateLocalContent("projection.cursor",++i.cursorRevision,projectionCursor(i.width,i.color,i.erasing),options);++i.stats.cursorRasters;}
    i.options=std::move(options);i.grid=std::move(grid);i.plate=std::move(plate);i.size=size;i.scale=scale;i.ready=true;i.world.values[0]=i.world.values[5]=scale;++i.geometryRevision;++i.stats.geometryUpdates;i.pose();return true;
}
bool NativeProjectionPlane::setBackground(double darkness,double opacity){auto&i=*impl_;need(std::isfinite(darkness)&&darkness>=0&&darkness<=1&&std::isfinite(opacity)&&opacity>=0&&opacity<=1,"Invalid source Projection background");if(i.darkness==darkness&&i.backgroundOpacity==opacity)return false;i.darkness=darkness;i.backgroundOpacity=opacity;i.pose();return true;}
bool NativeProjectionPlane::setCursor(std::optional<P>p,double width,std::array<double,4>c,bool erasing){auto&i=*impl_;need(i.ready,"Resize Projection plane before cursor updates");if(p)need(std::isfinite(p->x)&&std::isfinite(p->y),"Invalid Projection pointer");const bool content=!i.cursorReady||i.width!=width||i.color!=c||i.erasing!=erasing;bool changed=i.pointer!=p;if(content){auto art=projectionCursor(width,c,erasing);i.cursor.updateLocalContent("projection.cursor",++i.cursorRevision,art,i.options);i.width=width;i.color=c;i.erasing=erasing;i.cursorReady=true;++i.stats.cursorRasters;changed=true;}i.pointer=p;if(changed)i.pose();return changed;}
bool NativeProjectionPlane::setPose(const core::Matrix4&w,float opacity){auto&i=*impl_;need(i.ready&&w.finite()&&std::isfinite(opacity)&&opacity>=0&&opacity<=1,"Invalid Projection plane pose");auto expected=core::Matrix4{};expected.values[0]=expected.values[5]=i.scale;expected.values[12]=w.values[12];expected.values[13]=w.values[13];need(w==expected&&std::floor(w.values[12])==w.values[12]&&std::floor(w.values[13])==w.values[13],"Projection plane requires original flat DPI placement");if(i.world==w&&i.opacity==opacity)return false;i.world=w;i.opacity=opacity;i.pose();++i.stats.poseUpdates;return true;}
bool NativeProjectionPlane::upload(Renderer&r){auto&i=*impl_;need(i.ready&&(!i.renderer||i.renderer==&r),"Projection plane requires one initialized renderer");bool changed=!i.renderer||i.uploadedCell!=i.cell.resourceRevision()||i.uploadedCursor!=i.cursor.resourceRevision();i.renderer=&r;i.cell.uploadResources(r);i.cursor.uploadResources(r);i.uploadedCell=i.cell.resourceRevision();i.uploadedCursor=i.cursor.resourceRevision();if(i.uploadedGeometry!=i.geometryRevision){changed=r.setMesh(i.draws[0].meshID,i.geometryRevision,{i.plate.vertices,i.plate.indices})||changed;changed=r.setMesh(i.draws[1].meshID,i.geometryRevision,{i.grid.vertices,i.grid.indices})||changed;i.uploadedGeometry=i.geometryRevision;}i.renderer=&r;return changed;}
LayerCompositionEntry NativeProjectionPlane::backgroundEntry(){auto&i=*impl_;need(i.ready,"Initialize Projection background before publication");return {&i.carrier,i.draws};}LayerCompositionEntry NativeProjectionPlane::cursorEntry(){auto&i=*impl_;need(i.ready,"Initialize Projection cursor before publication");return {&i.cursor,{}};}
bool NativeProjectionPlane::releaseResources(Renderer&r){auto&i=*impl_;need(!i.renderer||i.renderer==&r,"Projection plane belongs to another renderer");bool okay=true;if(i.renderer&&r.stats().initialized)for(const auto&draw:i.draws)okay=r.removeMesh(draw.meshID)&&okay;okay=i.cell.releaseResources(r)&&okay;okay=i.cursor.releaseResources(r)&&okay;if(okay){i.renderer=nullptr;i.uploadedGeometry=i.uploadedCell=i.uploadedCursor=0;}return okay;}
ProjectionPlaneStats NativeProjectionPlane::stats()const noexcept{return impl_->stats;}
#endif
}
