#include "native/reader_document.hpp"
#include "native/reader_formats.hpp"
#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#include <d2d1.h>
#include <dwrite.h>
#include <wincodec.h>
#include <shcore.h>
#include <roapi.h>
#include <wrl.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Data.Pdf.h>
#include <winrt/Windows.Storage.Streams.h>
#include <winrt/Windows.Graphics.Imaging.h>
#include <winrt/Windows.UI.h>
#include <icu.h>
#include <algorithm>
#include <atomic>
#include <cmath>
#include <cstring>
#include <filesystem>
#include <mutex>
#include <numeric>
namespace endfield::native {
namespace {
using namespace modules;using Microsoft::WRL::ComPtr;using Microsoft::WRL::Make;
void need(bool value,ReaderErrorCode code=ReaderErrorCode::invalidBook){if(!value)throw ReaderError(code);}void hr(HRESULT value){if(FAILED(value))throw std::runtime_error("Reader native HRESULT="+std::to_string(static_cast<unsigned long>(value)));}
std::wstring wide(std::string_view value){auto u=readerUTF8(value);return std::wstring(reinterpret_cast<const wchar_t*>(u.data()),u.size());}
class FileBytes final:public ReaderBytes {
    HANDLE handle_{INVALID_HANDLE_VALUE};std::uint64_t length_{};std::mutex mutex_;
public:
    explicit FileBytes(const ReaderBook&book){need(book.platform==ReaderReferencePlatform::windows,ReaderErrorCode::unavailable);auto path=wide(book.windowsPath);need(!path.empty()&&path.find(L'\0')==path.npos,ReaderErrorCode::unavailable);std::replace(path.begin(),path.end(),L'/',L'\\');path=path.starts_with(L"\\\\")?L"\\\\?\\UNC\\"+path.substr(2):L"\\\\?\\"+path;need(path.size()<32767,ReaderErrorCode::tooLarge);
        handle_=CreateFileW(path.c_str(),GENERIC_READ,FILE_SHARE_READ|FILE_SHARE_DELETE,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL|FILE_FLAG_RANDOM_ACCESS,nullptr);
        need(handle_!=INVALID_HANDLE_VALUE,ReaderErrorCode::unavailable);try{BY_HANDLE_FILE_INFORMATION stat{};LARGE_INTEGER size{};need(GetFileInformationByHandle(handle_,&stat)&&!(stat.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY)&&GetFileSizeEx(handle_,&size)&&size.QuadPart>=0,ReaderErrorCode::unavailable);length_=static_cast<std::uint64_t>(size.QuadPart);}catch(...){CloseHandle(handle_);handle_=INVALID_HANDLE_VALUE;throw;}}
    ~FileBytes(){if(handle_!=INVALID_HANDLE_VALUE)CloseHandle(handle_);}
    std::uint64_t size()const override{return length_;}
    void read(std::uint64_t offset,std::span<std::uint8_t>out)override{need(offset<=length_&&out.size()<=length_-offset,ReaderErrorCode::unavailable);std::lock_guard guard(mutex_);LARGE_INTEGER begin{};begin.QuadPart=static_cast<LONGLONG>(offset);need(SetFilePointerEx(handle_,begin,nullptr,FILE_BEGIN)!=FALSE,ReaderErrorCode::unavailable);while(!out.empty()){DWORD actual{};const auto bytes=static_cast<DWORD>(std::min<std::size_t>(out.size(),65536));need(ReadFile(handle_,out.data(),bytes,&actual,nullptr)!=FALSE&&actual==bytes,ReaderErrorCode::unavailable);out=out.subspan(actual);}}
};
class ByteStream final:public Microsoft::WRL::RuntimeClass<Microsoft::WRL::RuntimeClassFlags<Microsoft::WRL::ClassicCom>,IStream,Microsoft::WRL::FtmBase> {
    std::shared_ptr<ReaderBytes>bytes_;std::uint64_t position_{};std::mutex mutex_;
public:
    explicit ByteStream(std::shared_ptr<ReaderBytes>bytes,std::uint64_t position=0):bytes_(std::move(bytes)),position_(position){}
    HRESULT STDMETHODCALLTYPE Read(void*target,ULONG bytes,ULONG*actual)override{if(actual)*actual=0;if(bytes&&!target)return STG_E_INVALIDPOINTER;try{std::lock_guard guard(mutex_);const auto count=static_cast<ULONG>(std::min<std::uint64_t>(bytes,position_<bytes_->size()?bytes_->size()-position_:0));if(count)bytes_->read(position_,{static_cast<std::uint8_t*>(target),count});position_+=count;if(actual)*actual=count;return count==bytes?S_OK:S_FALSE;}catch(...){return STG_E_READFAULT;}}
    HRESULT STDMETHODCALLTYPE Write(const void*,ULONG,ULONG*)override{return STG_E_ACCESSDENIED;}
    HRESULT STDMETHODCALLTYPE Seek(LARGE_INTEGER offset,DWORD origin,ULARGE_INTEGER*position)override{std::lock_guard guard(mutex_);if(origin>STREAM_SEEK_END)return STG_E_INVALIDFUNCTION;const auto base=origin==STREAM_SEEK_SET?0:origin==STREAM_SEEK_CUR?position_:bytes_->size();if(offset.QuadPart<0){const auto minus=std::uint64_t(-(offset.QuadPart+1))+1;if(minus>base)return STG_E_INVALIDFUNCTION;position_=base-minus;}else{if(std::uint64_t(offset.QuadPart)>UINT64_MAX-base)return STG_E_INVALIDFUNCTION;position_=base+std::uint64_t(offset.QuadPart);}if(position)position->QuadPart=position_;return S_OK;}
    HRESULT STDMETHODCALLTYPE SetSize(ULARGE_INTEGER)override{return STG_E_ACCESSDENIED;}
    HRESULT STDMETHODCALLTYPE CopyTo(IStream*,ULARGE_INTEGER,ULARGE_INTEGER*,ULARGE_INTEGER*)override{return E_NOTIMPL;}
    HRESULT STDMETHODCALLTYPE Commit(DWORD)override{return S_OK;}HRESULT STDMETHODCALLTYPE Revert()override{return STG_E_INVALIDFUNCTION;}
    HRESULT STDMETHODCALLTYPE LockRegion(ULARGE_INTEGER,ULARGE_INTEGER,DWORD)override{return STG_E_INVALIDFUNCTION;}HRESULT STDMETHODCALLTYPE UnlockRegion(ULARGE_INTEGER,ULARGE_INTEGER,DWORD)override{return STG_E_INVALIDFUNCTION;}
    HRESULT STDMETHODCALLTYPE Stat(STATSTG*out,DWORD flags)override{if(!out)return STG_E_INVALIDPOINTER;if(flags!=STATFLAG_DEFAULT&&flags!=STATFLAG_NONAME&&flags!=STATFLAG_NOOPEN)return STG_E_INVALIDFLAG;*out={};out->type=STGTY_STREAM;out->cbSize.QuadPart=bytes_->size();out->grfMode=STGM_READ;return S_OK;}
    HRESULT STDMETHODCALLTYPE Clone(IStream**out)override{if(!out)return E_POINTER;*out=nullptr;try{std::lock_guard guard(mutex_);auto value=Make<ByteStream>(bytes_,position_);return value?value.CopyTo(out):E_OUTOFMEMORY;}catch(...){return E_OUTOFMEMORY;}}
};
std::vector<std::uint8_t>readAll(const std::shared_ptr<ReaderBytes>&file,std::size_t limit,const ReaderCancel&cancelled){need(file->size()<=limit,ReaderErrorCode::tooLarge);std::vector<std::uint8_t>out(static_cast<std::size_t>(file->size()));for(std::size_t n=0;n<out.size();){checkReaderCancelled(cancelled);const auto size=std::min<std::size_t>(65536,out.size()-n);file->read(n,std::span(out).subspan(n,size));n+=size;}return out;}
core::Rect fit(core::Point dimensions,core::Rect rect){const auto scale=std::min(rect.width/std::max(1.,dimensions.x),rect.height/std::max(1.,dimensions.y));return {rect.x+(rect.width-dimensions.x*scale)/2,rect.y+(rect.height-dimensions.y*scale)/2,dimensions.x*scale,dimensions.y*scale};}
core::Rect viewRect(core::Rect rect,core::Point size,ReaderImageView view){return {(rect.x-size.x/2)*view.zoom+size.x/2+view.pan.x,(rect.y-size.y/2)*view.zoom+size.y/2+view.pan.y,rect.width*view.zoom,rect.height*view.zoom};}
core::Rect intersection(core::Rect a,core::Rect b){const auto x=std::max(a.x,b.x),y=std::max(a.y,b.y);return {x,y,std::max(0.,std::min(a.x+a.width,b.x+b.width)-x),std::max(0.,std::min(a.y+a.height,b.y+b.height)-y)};}
struct Font {std::wstring name;IDWriteFontCollection*collection{};DWRITE_FONT_WEIGHT weight{DWRITE_FONT_WEIGHT_NORMAL};DWRITE_FONT_STYLE style{DWRITE_FONT_STYLE_NORMAL};};
Font resolve(const LayerFontResources&resources,std::string_view requested){
    // Automatic Reader typography follows the immutable app language snapshot,
    // not an installed family named System or a full PostScript catalog scan.
    if(requested=="System")return {wide(resources.fallbackFamily()),resources.bundledCollection()};
    auto name=wide(requested);UINT32 index{};BOOL exists{};for(auto*collection:{resources.bundledCollection(),resources.systemCollection()}){hr(collection->FindFamilyName(name.c_str(),&index,&exists));if(exists)return {std::move(name),collection};}
    // Saved NSFont names may be a face/PostScript name rather than a family.
    // Enumerate only on an explicit format change, never on a pointer/page frame.
    for(auto*collection:{resources.bundledCollection(),resources.systemCollection()})for(UINT32 familyIndex=0;familyIndex<collection->GetFontFamilyCount();++familyIndex){ComPtr<IDWriteFontFamily>family;hr(collection->GetFontFamily(familyIndex,&family));for(UINT32 i=0;i<family->GetFontCount();++i){ComPtr<IDWriteFont>font;hr(family->GetFont(i,&font));for(auto kind:{DWRITE_INFORMATIONAL_STRING_POSTSCRIPT_NAME,DWRITE_INFORMATIONAL_STRING_FULL_NAME}){ComPtr<IDWriteLocalizedStrings>names;hr(font->GetInformationalStrings(kind,&names,&exists));if(!exists)continue;for(UINT32 n=0;n<names->GetCount();++n){UINT32 length{};hr(names->GetStringLength(n,&length));std::wstring candidate(std::size_t(length)+1,L'\0');hr(names->GetString(n,candidate.data(),length+1));candidate.resize(length);if(candidate==name){ComPtr<IDWriteLocalizedStrings>families;hr(family->GetFamilyNames(&families));hr(families->GetStringLength(0,&length));std::wstring selected(std::size_t(length)+1,L'\0');hr(families->GetString(0,selected.data(),length+1));selected.resize(length);return {std::move(selected),collection,font->GetWeight(),font->GetStyle()};}}}}}
    return {wide(resources.fallbackFamily()),resources.bundledCollection()};
}
struct TextLayout {
    struct Paragraph {std::size_t start{},length{};double top{};ComPtr<IDWriteTextLayout>layout;std::vector<DWRITE_LINE_METRICS>lines;};
    std::vector<Paragraph>paragraphs;std::size_t visible{};double height{},spacing{};
};
// Draw each already-shaped native glyph run once. Extra paragraph lineSpacing
// is applied between successive source lines; no fixed-height font approximation
// or duplicate per-line shaping/layout is used.
class TextPainter final:public Microsoft::WRL::RuntimeClass<Microsoft::WRL::RuntimeClassFlags<Microsoft::WRL::ClassicCom>,IDWriteTextRenderer> {
public:ID2D1RenderTarget*target{};ID2D1Brush*brush{};const TextLayout::Paragraph*paragraph{};double spacing{},originY{};std::size_t precedingLines{},visibleLines{};
    HRESULT STDMETHODCALLTYPE IsPixelSnappingDisabled(void*,BOOL*out)override{if(!out)return E_POINTER;*out=FALSE;return S_OK;}
    HRESULT STDMETHODCALLTYPE GetCurrentTransform(void*,DWRITE_MATRIX*out)override{if(!out)return E_POINTER;D2D1_MATRIX_3X2_F transform{};target->GetTransform(&transform);static_assert(sizeof(transform)==sizeof(*out));std::memcpy(out,&transform,sizeof(transform));return S_OK;}
    HRESULT STDMETHODCALLTYPE GetPixelsPerDip(void*,FLOAT*out)override{if(!out)return E_POINTER;FLOAT x{},y{};target->GetDpi(&x,&y);*out=x/96;return S_OK;}
    HRESULT STDMETHODCALLTYPE DrawGlyphRun(void*,FLOAT x,FLOAT y,DWRITE_MEASURING_MODE mode,const DWRITE_GLYPH_RUN*run,const DWRITE_GLYPH_RUN_DESCRIPTION*,IUnknown*)override{double lineTop{};std::size_t index{};double best=1e30;for(std::size_t n=0;n<paragraph->lines.size();++n){const auto delta=std::abs(double(y)-(originY+paragraph->top+lineTop+paragraph->lines[n].baseline));if(delta<best){best=delta;index=n;}lineTop+=paragraph->lines[n].height;}if(precedingLines+index>=visibleLines)return S_OK;target->DrawGlyphRun({x,static_cast<FLOAT>(y+(precedingLines+index)*spacing)},run,brush,mode);return S_OK;}
    HRESULT STDMETHODCALLTYPE DrawUnderline(void*,FLOAT,FLOAT,const DWRITE_UNDERLINE*,IUnknown*)override{return S_OK;}HRESULT STDMETHODCALLTYPE DrawStrikethrough(void*,FLOAT,FLOAT,const DWRITE_STRIKETHROUGH*,IUnknown*)override{return S_OK;}HRESULT STDMETHODCALLTYPE DrawInlineObject(void*,FLOAT,FLOAT,IDWriteInlineObject*,BOOL,BOOL,IUnknown*)override{return E_NOTIMPL;}
};
}
struct NativeReaderDocument::Impl {
    std::atomic<std::shared_ptr<const LayerFontResources>>resources;DWORD worker{};bool initialized{},roInitialized{};
    ComPtr<ID2D1Factory>d2d;ComPtr<IWICImagingFactory>wic;std::shared_ptr<ReaderBytes>file;
    winrt::Windows::Data::Pdf::PdfDocument pdf{nullptr};winrt::Windows::Storage::Streams::IRandomAccessStream pdfInput{nullptr};std::unique_ptr<ReaderEPUB>epub;std::shared_ptr<const std::vector<ReaderBlock>>plain;
    NativeReaderInfo metadata;LayerFontResources formatResources,requestFonts,cacheFonts;ReaderPreferences formatPreferences;ComPtr<IDWriteTextFormat>format;
    ComPtr<IWICBitmapSource>cachedImage;std::string cachedImagePath;unsigned cachedImageMaximum{};std::size_t cachedImageBytes{};
    std::vector<ReaderPage>cache;std::optional<ReaderPreferences>cachePreferences;core::Point cacheSize{};bool cacheDark{};std::uint64_t cacheFontRevision{};NativeReaderStats counters;
    explicit Impl(LayerFontResources fonts){need(bool(fonts));resources.store(std::make_shared<const LayerFontResources>(std::move(fonts)));}
    void onWorker(){if(!worker)worker=GetCurrentThreadId();need(worker==GetCurrentThreadId());if(!initialized){hr(RoInitialize(RO_INIT_MULTITHREADED));try{ComPtr<ID2D1Factory>factory;ComPtr<IWICImagingFactory>images;hr(D2D1CreateFactory(D2D1_FACTORY_TYPE_SINGLE_THREADED,__uuidof(ID2D1Factory),nullptr,reinterpret_cast<void**>(factory.GetAddressOf())));hr(CoCreateInstance(CLSID_WICImagingFactory,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&images)));d2d=std::move(factory);wic=std::move(images);roInitialized=true;initialized=true;}catch(...){RoUninitialize();worker=0;throw;}}}
    void clear(){pdf=nullptr;pdfInput=nullptr;epub.reset();plain.reset();file.reset();cachedImage.Reset();cachedImagePath.clear();cachedImageMaximum=0;cachedImageBytes=0;metadata={};format.Reset();formatResources={};cache.clear();cachePreferences.reset();cacheFontRevision=0;requestFonts={};cacheFonts={};}
    ReaderBlocks blocks(const ReaderCancel&cancelled){return [this,&cancelled](std::size_t section){checkReaderCancelled(cancelled);return plain?plain:epub->blocks(section,cancelled);};}
    std::size_t count()const{return metadata.sections;}
    ReaderLocation normalized(ReaderLocation location,const ReaderCancel&cancelled){if(pdf){location={std::clamp<std::int64_t>(location.section,0,static_cast<std::int64_t>(count()-1)),0,0,{ReaderJson::Object{}}};return location;}return readerNormalized(location,count(),blocks(cancelled));}
    void configureFormat(const ReaderPreferences&p){const auto fonts=requestFonts?requestFonts:*resources.load();need(bool(fonts)&&p.valid());if(format&&formatPreferences==p&&formatResources.revision()==fonts.revision()&&formatResources.factory()==fonts.factory()&&formatResources.bundledCollection()==fonts.bundledCollection()&&formatResources.systemCollection()==fonts.systemCollection()&&formatResources.fallbackFamily()==fonts.fallbackFamily()&&formatResources.locale()==fonts.locale())return;const auto face=resolve(fonts,p.fontName);ComPtr<IDWriteTextFormat>prepared;const auto locale=wide(fonts.locale());hr(fonts.factory()->CreateTextFormat(face.name.c_str(),face.collection,face.weight,face.style,DWRITE_FONT_STRETCH_NORMAL,static_cast<FLOAT>(p.fontSize),locale.c_str(),&prepared));hr(prepared->SetWordWrapping(DWRITE_WORD_WRAPPING_WRAP));format=std::move(prepared);formatResources=fonts;formatPreferences=p;metadata.requestedFont=p.fontName;metadata.selectedFont=readerUTF8(std::u16string_view(reinterpret_cast<const char16_t*>(face.name.data()),face.name.size()));}
    TextLayout shape(std::u16string_view value,double width,double available,const ReaderCancel&cancelled){TextLayout result;result.spacing=formatPreferences.lineSpacing;std::size_t begin{},globalLines{};bool filling=true;double top{};
        while(begin<value.size()){checkReaderCancelled(cancelled);std::size_t end=begin;while(end<value.size()&&value[end]!=u'\r'&&value[end]!=u'\n'&&value[end]!=0x2029)++end;if(end<value.size()){const auto newline=value[end++];if(newline==u'\r'&&end<value.size()&&value[end]==u'\n')++end;}
            const auto text=value.substr(begin,end-begin);const auto direction=ubidi_getBaseDirection(reinterpret_cast<const UChar*>(text.data()),static_cast<int32_t>(text.size()));hr(format->SetReadingDirection(direction==UBIDI_RTL?DWRITE_READING_DIRECTION_RIGHT_TO_LEFT:DWRITE_READING_DIRECTION_LEFT_TO_RIGHT));TextLayout::Paragraph paragraph;paragraph.start=begin;paragraph.length=text.size();paragraph.top=top;++counters.textLayouts;hr(formatResources.factory()->CreateTextLayout(reinterpret_cast<const wchar_t*>(text.data()),static_cast<UINT32>(text.size()),format.Get(),static_cast<FLOAT>(std::max(1.,width)),1e7f,&paragraph.layout));UINT32 count{};const auto measured=paragraph.layout->GetLineMetrics(nullptr,0,&count);need(measured==E_NOT_SUFFICIENT_BUFFER||SUCCEEDED(measured));need(count>0&&count<=16385);paragraph.lines.resize(count);hr(paragraph.layout->GetLineMetrics(paragraph.lines.data(),count,&count));paragraph.lines.resize(count);
            for(const auto&line:paragraph.lines){need(std::isfinite(line.height)&&line.height>0&&line.length<=value.size()-begin);if(line.length==0)continue;const auto bottom=top+line.height+static_cast<double>(globalLines)*result.spacing;if(filling&&bottom<=available+1e-5)result.visible+=line.length;else filling=false;top+=line.height;++globalLines;}result.paragraphs.push_back(std::move(paragraph));begin=end;if(!filling)break;
        }result.height=top+static_cast<double>(globalLines?globalLines-1:0)*result.spacing;return result;
    }
    ComPtr<IWICBitmapSource>decodeImage(std::span<const std::uint8_t>bytes,unsigned maximum,bool orient,const ReaderCancel&cancelled){checkReaderCancelled(cancelled);need(bytes.size()<=32*1024*1024);ComPtr<IWICStream>stream;hr(wic->CreateStream(&stream));hr(stream->InitializeFromMemory(const_cast<BYTE*>(bytes.data()),static_cast<DWORD>(bytes.size())));ComPtr<IWICBitmapDecoder>decoder;hr(wic->CreateDecoderFromStream(stream.Get(),nullptr,WICDecodeMetadataCacheOnDemand,&decoder));ComPtr<IWICBitmapFrameDecode>frame;hr(decoder->GetFrame(0,&frame));UINT width{},height{};hr(frame->GetSize(&width,&height));need(width&&height&&width<=65536&&height<=65536&&std::uint64_t(width)*height<=64000000);ComPtr<IWICBitmapSource>source;hr(frame.As(&source));
        UINT colorContexts{};if(SUCCEEDED(frame->GetColorContexts(0,nullptr,&colorContexts))&&colorContexts){need(colorContexts<=16);ComPtr<IWICColorContext>input,output;hr(wic->CreateColorContext(&input));hr(wic->CreateColorContext(&output));IWICColorContext*raw=input.Get();UINT actual{};if(SUCCEEDED(frame->GetColorContexts(1,&raw,&actual))&&actual){hr(output->InitializeFromExifColorSpace(1));ComPtr<IWICColorTransform>transform;hr(wic->CreateColorTransformer(&transform));hr(transform->Initialize(source.Get(),input.Get(),output.Get(),GUID_WICPixelFormat32bppRGBA));source=transform;}}
        const auto ratio=std::min(1.,double(maximum)/std::max(width,height));if(ratio<1){ComPtr<IWICBitmapScaler>scaled;hr(wic->CreateBitmapScaler(&scaled));hr(scaled->Initialize(source.Get(),std::max(1u,static_cast<unsigned>(std::round(width*ratio))),std::max(1u,static_cast<unsigned>(std::round(height*ratio))),WICBitmapInterpolationModeFant));source=scaled;}
        if(orient){ComPtr<IWICMetadataQueryReader>metadata;if(SUCCEEDED(frame->GetMetadataQueryReader(&metadata))){PROPVARIANT value{};unsigned orientation=1;auto query=metadata->GetMetadataByName(L"/app1/ifd/{ushort=274}",&value);if(FAILED(query)){PropVariantClear(&value);query=metadata->GetMetadataByName(L"/ifd/{ushort=274}",&value);}if(SUCCEEDED(query)){if(value.vt==VT_UI2)orientation=value.uiVal;else if(value.vt==VT_UI4)orientation=value.ulVal;}PropVariantClear(&value);const WICBitmapTransformOptions rotations[]={WICBitmapTransformRotate0,WICBitmapTransformFlipHorizontal,WICBitmapTransformRotate180,WICBitmapTransformFlipVertical,static_cast<WICBitmapTransformOptions>(WICBitmapTransformRotate90|WICBitmapTransformFlipHorizontal),WICBitmapTransformRotate90,static_cast<WICBitmapTransformOptions>(WICBitmapTransformRotate270|WICBitmapTransformFlipHorizontal),WICBitmapTransformRotate270};if(orientation>1&&orientation<=8){ComPtr<IWICBitmapFlipRotator>rotator;hr(wic->CreateBitmapFlipRotator(&rotator));hr(rotator->Initialize(source.Get(),rotations[orientation-1]));source=rotator;}}}
        ComPtr<IWICFormatConverter>converted;hr(wic->CreateFormatConverter(&converted));hr(converted->Initialize(source.Get(),GUID_WICPixelFormat32bppPBGRA,WICBitmapDitherTypeNone,nullptr,0,WICBitmapPaletteTypeCustom));
        // Decoded frame depends on its stream. Materialize only the bounded
        // thumbnail before releasing the injected bytes/decoder.
        ComPtr<IWICBitmap>owned;hr(wic->CreateBitmapFromSource(converted.Get(),WICBitmapCacheOnLoad,&owned));ComPtr<IWICBitmapSource>result;hr(owned.As(&result));checkReaderCancelled(cancelled);return result;
    }
    ReaderPage page(ReaderLocation location,const ReaderPreferences&p,core::Point size,bool dark,ReaderImageView view,const ReaderCancel&cancelled,const ReaderPage*known=nullptr){checkReaderCancelled(cancelled);need(p.valid()&&std::isfinite(size.x)&&std::isfinite(size.y)&&size.x>0&&size.y>0&&size.x<=100000&&size.y<=100000);location=normalized(location,cancelled);view=view.clamped(size);const auto rasterWidth=std::clamp(size.x*2,200.,900.),rasterHeight=std::clamp(size.y*2,200.,1000.);const auto width=static_cast<unsigned>(rasterWidth),height=static_cast<unsigned>(rasterHeight);ComPtr<IWICBitmap>bitmap;hr(wic->CreateBitmap(width,height,GUID_WICPixelFormat32bppPBGRA,WICBitmapCacheOnLoad,&bitmap));ComPtr<ID2D1RenderTarget>target;const auto properties=D2D1::RenderTargetProperties(D2D1_RENDER_TARGET_TYPE_SOFTWARE,D2D1::PixelFormat(DXGI_FORMAT_B8G8R8A8_UNORM,D2D1_ALPHA_MODE_PREMULTIPLIED),96,96);hr(d2d->CreateWicBitmapRenderTarget(bitmap.Get(),properties,&target));target->BeginDraw();target->Clear(D2D1::ColorF(dark?.07f:.95f,dark?.07f:.95f,dark?.07f:.95f,1));target->SetTransform(D2D1::Matrix3x2F::Scale(static_cast<FLOAT>(rasterWidth/size.x),static_cast<FLOAT>(rasterHeight/size.y)));
        ++counters.pagesRendered;ReaderPage result;result.location=location;const core::Rect inner{p.margin,p.margin,size.x-2*p.margin,size.y-2*p.margin};need(inner.width>0&&inner.height>0);double portion{};
        if(pdf){result.illustration=true;auto pdfPage=pdf.GetPage(static_cast<std::uint32_t>(location.section));struct ClosePage{winrt::Windows::Data::Pdf::PdfPage*p;~ClosePage(){try{p->Close();}catch(...){}}}close{&pdfPage};const auto native=pdfPage.Size();need(std::isfinite(native.Width)&&std::isfinite(native.Height)&&native.Width>0&&native.Height>0);const auto destination=viewRect(fit({native.Width,native.Height},inner),size,view);const auto visible=intersection(destination,{0,0,size.x,size.y});if(visible.width>0&&visible.height>0){winrt::Windows::Data::Pdf::PdfPageRenderOptions options;options.SourceRect({static_cast<FLOAT>((visible.x-destination.x)/destination.width*native.Width),static_cast<FLOAT>((visible.y-destination.y)/destination.height*native.Height),static_cast<FLOAT>(visible.width/destination.width*native.Width),static_cast<FLOAT>(visible.height/destination.height*native.Height)});options.DestinationWidth(std::max(1u,static_cast<unsigned>(std::ceil(visible.width*rasterWidth/size.x))));options.DestinationHeight(std::max(1u,static_cast<unsigned>(std::ceil(visible.height*rasterHeight/size.y))));options.BackgroundColor(winrt::Windows::UI::Colors::White());options.IsIgnoringHighContrast(true);options.BitmapEncoderId(winrt::Windows::Graphics::Imaging::BitmapEncoder::BmpEncoderId());winrt::Windows::Storage::Streams::InMemoryRandomAccessStream encoded;++counters.pdfRenders;pdfPage.RenderToStreamAsync(encoded,options).get();checkReaderCancelled(cancelled);need(encoded.Size()>0&&encoded.Size()<=8*1024*1024);winrt::Windows::Storage::Streams::DataReader reader(encoded.GetInputStreamAt(0));need(reader.LoadAsync(static_cast<std::uint32_t>(encoded.Size())).get()==encoded.Size());std::vector<std::uint8_t>bytes(static_cast<std::size_t>(encoded.Size()));reader.ReadBytes(bytes);auto decoded=decodeImage(bytes,1000,false,cancelled);ComPtr<ID2D1Bitmap>image;hr(target->CreateBitmapFromWicBitmap(decoded.Get(),nullptr,&image));target->DrawBitmap(image.Get(),D2D1::RectF(static_cast<FLOAT>(visible.x),static_cast<FLOAT>(visible.y),static_cast<FLOAT>(visible.x+visible.width),static_cast<FLOAT>(visible.y+visible.height)));}result.next=location.section+1<static_cast<std::int64_t>(count())?std::optional<ReaderLocation>{ReaderLocation{location.section+1,0,0,{ReaderJson::Object{}}}}:std::nullopt;result.previous=location.section>0?std::optional<ReaderLocation>{ReaderLocation{location.section-1,0,0,{ReaderJson::Object{}}}}:std::nullopt;result.progress=double(location.section)/double(std::max<std::size_t>(1,count()-1));result.summary=std::to_string(location.section+1)+" / "+std::to_string(count());}
        else{const auto values=blocks(cancelled)(static_cast<std::size_t>(location.section));const auto&value=(*values)[static_cast<std::size_t>(location.block)];if(value.kind==ReaderBlock::Kind::image){result.illustration=true;const auto maximum=std::min(2048u,static_cast<unsigned>(1200*view.zoom));ComPtr<IWICBitmapSource>decoded;if(cachedImage&&cachedImagePath==value.image&&cachedImageMaximum==maximum){decoded=cachedImage;++counters.imageDecodeCacheHits;}else{auto bytes=epub->zip().data(value.image,ReaderZIP::maximumEntryBytes,cancelled);++counters.imageDecodes;decoded=decodeImage(bytes,maximum,true,cancelled);UINT cachedWidth{},cachedHeight{};hr(decoded->GetSize(&cachedWidth,&cachedHeight));need(cachedWidth<=2048&&cachedHeight<=2048);checkReaderCancelled(cancelled);auto acceptedPath=value.image;cachedImage=decoded;cachedImagePath=std::move(acceptedPath);cachedImageMaximum=maximum;cachedImageBytes=std::size_t(cachedWidth)*cachedHeight*4;}UINT w{},h{};hr(decoded->GetSize(&w,&h));const auto dest=viewRect(fit({double(w),double(h)},inner),size,view);ComPtr<ID2D1Bitmap>image;hr(target->CreateBitmapFromWicBitmap(decoded.Get(),nullptr,&image));target->DrawBitmap(image.Get(),D2D1::RectF(static_cast<FLOAT>(dest.x),static_cast<FLOAT>(dest.y),static_cast<FLOAT>(dest.x+dest.width),static_cast<FLOAT>(dest.y+dest.height)));result.next=readerAdvance(location,values->size(),count());}
            else{configureFormat(p);const auto chunk=readerChunk(value.text,static_cast<std::size_t>(location.character));auto layout=shape(chunk,inner.width,inner.height,cancelled);need(layout.visible>0&&layout.visible<=chunk.size());std::size_t visibleLines{},characters{};for(const auto&paragraph:layout.paragraphs)for(const auto&line:paragraph.lines)if(line.length&&characters<layout.visible){characters+=line.length;++visibleLines;}ComPtr<ID2D1SolidColorBrush>ink;hr(target->CreateSolidColorBrush(D2D1::ColorF(dark?.92f:.08f,dark?.92f:.08f,dark?.92f:.08f,1),&ink));auto painter=Make<TextPainter>();need(bool(painter));painter->target=target.Get();painter->brush=ink.Get();painter->spacing=p.lineSpacing;painter->originY=inner.y;painter->visibleLines=visibleLines;target->PushAxisAlignedClip(D2D1::RectF(static_cast<FLOAT>(inner.x),static_cast<FLOAT>(inner.y),static_cast<FLOAT>(inner.x+inner.width),static_cast<FLOAT>(inner.y+inner.height)),D2D1_ANTIALIAS_MODE_PER_PRIMITIVE);std::size_t preceding{};for(const auto&paragraph:layout.paragraphs){painter->paragraph=&paragraph;painter->precedingLines=preceding;hr(paragraph.layout->Draw(nullptr,painter.Get(),static_cast<FLOAT>(inner.x),static_cast<FLOAT>(inner.y+paragraph.top)));for(const auto&line:paragraph.lines)if(line.length)++preceding;}target->PopAxisAlignedClip();const auto end=location.character+static_cast<std::int64_t>(layout.visible);result.next=end<static_cast<std::int64_t>(value.text.size())?std::optional<ReaderLocation>{ReaderLocation{location.section,location.block,end,{ReaderJson::Object{}}}}:readerAdvance(location,values->size(),count());portion=double(location.character)/double(std::max<std::size_t>(1,value.text.size()));result.summary=readerGraphemePrefix(chunk,80);std::replace(result.summary.begin(),result.summary.end(),'\n',' ');}
            result.progress=result.next?(double(location.section)+(double(location.block)+portion)/double(values->size()))/double(count()):1;if(known){result.previous=known->previous;++counters.detailMetadataCacheHits;}else{configureFormat(p);result.previous=readerPrevious(location,count(),blocks(cancelled),std::max(1.,size.y-p.margin*2),[&](std::u16string_view text){return shape(text,std::max(1.,size.x-p.margin*2),std::max(1.,size.y-p.margin*2),cancelled).height;});}}
        hr(target->EndDraw());checkReaderCancelled(cancelled);auto pixels=std::make_shared<ReaderPagePixels>();pixels->width=width;pixels->height=height;pixels->format=ReaderPagePixels::Format::bgra8Premultiplied;pixels->bytes.resize(std::size_t(width)*height*4);hr(bitmap->CopyPixels(nullptr,width*4,static_cast<UINT>(pixels->bytes.size()),pixels->bytes.data()));result.pixels=std::move(pixels);return result;
    }
};
NativeReaderDocument::NativeReaderDocument(LayerFontResources fonts):impl_(std::make_unique<Impl>(std::move(fonts))){}
NativeReaderDocument::~NativeReaderDocument(){if(impl_->worker&&impl_->worker!=GetCurrentThreadId())std::terminate();impl_->clear();if(impl_->roInitialized)RoUninitialize();}
void NativeReaderDocument::setFontResources(LayerFontResources fonts){need(bool(fonts));impl_->resources.store(std::make_shared<const LayerFontResources>(std::move(fonts)));}
void NativeReaderDocument::open(const ReaderBook&book,const ReaderCancel&cancelled){auto&i=*impl_;i.onWorker();checkReaderCancelled(cancelled);i.clear();need(book.platform==ReaderReferencePlatform::windows,ReaderErrorCode::unavailable);ReaderLibrary validation;validation.books={book};validation.selected=book.id;validateReaderLibrary(validation);try{auto file=std::make_shared<FileBytes>(book);const auto path=std::filesystem::path(wide(book.windowsPath));auto ext=path.extension().wstring();std::transform(ext.begin(),ext.end(),ext.begin(),[](wchar_t c){return c>=L'A'&&c<=L'Z'?static_cast<wchar_t>(c+32):c;});std::u16string title(reinterpret_cast<const char16_t*>(path.stem().c_str()));
        if(ext==L".txt"){auto text=decodeReaderTXT(readAll(file,32*1024*1024,cancelled));i.plain=std::make_shared<const std::vector<ReaderBlock>>(std::vector<ReaderBlock>{{ReaderBlock::Kind::text,std::move(text),{}}});i.metadata.sections=1;}
        else if(ext==L".epub"){i.epub=std::make_unique<ReaderEPUB>(file,parseReaderXML,cancelled);i.metadata.sections=i.epub->spine().size();if(!i.epub->title().empty())title=i.epub->title();}
        else if(ext==L".pdf"){need(file->size()<=1024ull*1024*1024,ReaderErrorCode::tooLarge);auto stream=Make<ByteStream>(file);need(bool(stream));winrt::Windows::Storage::Streams::IRandomAccessStream input{nullptr};hr(CreateRandomAccessStreamOverStream(stream.Get(),BSOS_DEFAULT,winrt::guid_of<winrt::Windows::Storage::Streams::IRandomAccessStream>(),winrt::put_abi(input)));try{i.pdf=winrt::Windows::Data::Pdf::PdfDocument::LoadFromStreamAsync(input).get();}catch(const winrt::hresult_error&e){if(e.code()==HRESULT_FROM_WIN32(ERROR_WRONG_PASSWORD))throw ReaderError(ReaderErrorCode::encrypted);throw;}checkReaderCancelled(cancelled);need(i.pdf&&i.pdf.PageCount()>0&&i.pdf.PageCount()<100000,ReaderErrorCode::tooLarge);i.metadata.sections=i.pdf.PageCount();i.pdfInput=std::move(input);}
        else throw ReaderError(ReaderErrorCode::unsupported);i.metadata.title=readerGraphemePrefix(title,200);need(!i.metadata.title.empty()&&i.metadata.title.size()<=4096);i.file=std::move(file);
    }catch(...){i.clear();throw;}}
NativeReaderInfo NativeReaderDocument::info()const{need(impl_->worker==GetCurrentThreadId()&&impl_->count()>0);return impl_->metadata;}
NativeReaderStats NativeReaderDocument::stats()const{need(!impl_->worker||impl_->worker==GetCurrentThreadId());auto counters=impl_->counters;counters.cachedPages=impl_->cache.size();counters.cachedImageBytes=impl_->cachedImageBytes;return counters;}
std::vector<ReaderPage>NativeReaderDocument::render(std::optional<ReaderLocation>location,std::optional<double>progress,const ReaderPreferences&p,core::Point size,bool dark,const ReaderCancel&cancelled){auto&i=*impl_;i.onWorker();need(i.file&&i.count()>0);if(progress){need(std::isfinite(*progress));if(i.pdf)location=ReaderLocation{static_cast<std::int64_t>(std::clamp(*progress,0.,.999999)*double(i.count())),0,0,{ReaderJson::Object{}}};else location=readerLocationAt(*progress,i.count(),i.blocks(cancelled));}i.requestFonts=*i.resources.load();const auto fontRevision=i.requestFonts.revision();if(!i.cachePreferences||*i.cachePreferences!=p||i.cacheSize.x!=size.x||i.cacheSize.y!=size.y||i.cacheDark!=dark||i.cacheFontRevision!=fontRevision||i.cacheFonts.bundledCollection()!=i.requestFonts.bundledCollection()||i.cacheFonts.fallbackFamily()!=i.requestFonts.fallbackFamily()||i.cacheFonts.locale()!=i.requestFonts.locale())i.cache.clear();i.cachePreferences=p;i.cacheSize=size;i.cacheDark=dark;i.cacheFontRevision=fontRevision;i.cacheFonts=i.requestFonts;auto at=[&](ReaderLocation anchor){checkReaderCancelled(cancelled);anchor=i.normalized(anchor,cancelled);for(const auto&cached:i.cache)if(cached.location==anchor){++i.counters.cacheHits;return cached;}return i.page(anchor,p,size,dark,{},cancelled);};auto current=at(location.value_or(ReaderLocation{}));std::vector<ReaderPage>pages;pages.reserve(3);pages.push_back(current);if(current.next){try{pages.push_back(at(*current.next));}catch(const ReaderCancelled&){throw;}catch(const std::exception&){}}if(current.previous&&current.previous!=current.next){try{pages.push_back(at(*current.previous));}catch(const ReaderCancelled&){throw;}catch(const std::exception&){}}checkReaderCancelled(cancelled);i.cache=pages;return pages;}
ReaderPage NativeReaderDocument::detail(ReaderLocation location,const ReaderPreferences&p,core::Point size,bool dark,ReaderImageView view,const ReaderCancel&cancelled){auto&i=*impl_;i.onWorker();need(i.file&&view.valid());i.requestFonts=*i.resources.load();const ReaderPage*known{};if(i.cachePreferences&&*i.cachePreferences==p&&i.cacheSize==size&&i.cacheDark==dark&&i.cacheFonts.factory()==i.requestFonts.factory()&&i.cacheFonts.bundledCollection()==i.requestFonts.bundledCollection()&&i.cacheFonts.systemCollection()==i.requestFonts.systemCollection()&&i.cacheFonts.revision()==i.requestFonts.revision()&&i.cacheFonts.fallbackFamily()==i.requestFonts.fallbackFamily()&&i.cacheFonts.locale()==i.requestFonts.locale())for(const auto&cached:i.cache)if(cached.location==location){known=&cached;break;}return i.page(location,p,size,dark,view,cancelled,known);}
void NativeReaderDocument::release(){auto&i=*impl_;need(!i.worker||i.worker==GetCurrentThreadId());i.clear();i.wic.Reset();i.d2d.Reset();i.initialized=false;if(i.roInitialized){RoUninitialize();i.roInitialized=false;}i.worker=0;}
} // namespace endfield::native
#endif
