#include "native/settings_safety.hpp"
#ifdef _WIN32
#include <algorithm>
#include <atomic>
#include <cmath>
namespace endfield::native {namespace {
namespace m=modules;using Json=ehud::data::Json;using Matrix=core::Matrix4;using Rect=core::Rect;
void need(bool b,const char*s){if(!b)throw std::invalid_argument(s);}Json blank(){return Json::Object{{"bounds",Json::Array{0,0,0,0}},{"children",Json::Array{}}};}bool contains(Rect a,Rect b){return a.x<=b.x&&a.y<=b.y&&a.x+a.width>=b.x+b.width&&a.y+a.height>=b.y+b.height;}Rect intersection(Rect a,Rect b){const auto x=std::max(a.x,b.x),y=std::max(a.y,b.y);return{x,y,std::max(0.,std::min(a.x+a.width,b.x+b.width)-x),std::max(0.,std::min(a.y+a.height,b.y+b.height)-y)};}
}
struct NativeSettingsSafety::Impl {
 m::SettingsSafety&state;LayerRasterizer&raster;LayerRasterOptions options;m::SettingsAppearance appearance;LayerScene card,carrier;m::SettingsArtworkPart artwork;std::array<Json,2>buttonLeaves;std::array<m::SettingsSafetyButtonPaint,2>painted{};std::vector<LayerPlacement>placements;std::vector<DrawObject>local;std::array<DrawObject,5>published;std::string groupID,quadID;std::uint64_t seen{},contentEpoch{},uploadedCardRevision{};std::optional<Rect>viewport,uploadedCoverage;Rect cover{};Matrix cardWorld;core::Projection hit;bool dirty{true},posed{},uploaded{},groupOwned{},quadUploaded{};std::size_t rasterizations{};
 Impl(m::SettingsSafety&s,LayerRasterizer&r,LayerRasterOptions o,m::SettingsAppearance a):state(s),raster(r),options(std::move(o)),appearance(a),card(r),carrier(r){state.setAppearance(a);carrier.load(blank(),options);static std::atomic<std::uint64_t>next{};groupID="settings.safety."+std::to_string(next.fetch_add(1));quadID=groupID+".dim";local.reserve(10);for(unsigned n=0;n<4;++n){published[n].sourceID=groupID+".surround."+std::to_string(n);published[n].meshID=quadID;published[n].linearTint={0,0,0,1};} }
 bool updateFeedback(double now){bool changed=false;for(unsigned n=0;n<2;++n){const auto paint=state.buttonPaint(n,now);if(paint==painted[n])continue;auto next=buttonLeaves[n];const auto color=[](const m::SettingsSafetyColor&c){return Json::Object{{"sRGB",Json::Array{c[0],c[1],c[2],c[3]}}};};next["shape"]["fillColor"]=color(paint.fill);next["shape"]["strokeColor"]=color(paint.stroke);next["shape"]["lineWidth"]=paint.width;card.updateLocalContent(artwork.surfaces[n+2].id,++contentEpoch,next,options);buttonLeaves[n]=std::move(next);painted[n]=paint;++rasterizations;changed=true;}return changed;}
};
NativeSettingsSafety::NativeSettingsSafety(m::SettingsSafety&s,LayerRasterizer&r,LayerRasterOptions o,m::SettingsAppearance a):impl_(std::make_unique<Impl>(s,r,std::move(o),a)){}
NativeSettingsSafety::~NativeSettingsSafety()=default;
void NativeSettingsSafety::setAppearance(m::SettingsAppearance a){if(a==impl_->appearance)return;impl_->appearance=a;impl_->state.setAppearance(a);impl_->dirty=true;}
bool NativeSettingsSafety::syncContent(Rect viewport,double now){need(std::isfinite(now),"Invalid confirmation animation time");auto&i=*impl_;if(!i.dirty&&i.seen==i.state.revision()&&i.viewport==viewport)return i.updateFeedback(now);auto art=m::prepareSettingsSafetyArtwork(i.state,viewport,i.appearance,now);if(i.viewport!=viewport)i.cover={};if(i.artwork.surfaces.empty()){i.card.load(art.layers,i.options);need(i.card.report().unsupported.empty(),"Unsupported source Settings confirmation artwork");i.placements.resize(art.surfaces.size());for(std::size_t n=0;n<art.surfaces.size();++n){const auto index=i.card.surfaceIndex(art.surfaces[n].id);need(index.has_value(),"Missing source confirmation leaf");i.placements[n]={*index,art.surfaces[n].local,1,{}};}i.rasterizations+=art.surfaces.size();i.contentEpoch=i.card.contentRevision();}else{
  // Stable leaf identities preserve unrelated labels and native layout handles.
  // Only the two small plate bitmaps change on focus/hover events; the 1Hz
  // remaining label is the sole glyph surface changing during a countdown.
  const auto&before=i.artwork.layers["children"].array();const auto&after=art.layers["children"].array();need(before.size()==after.size(),"Unexpected source confirmation shape");for(std::size_t n=0;n<after.size();++n)if((n==2||n==3?i.buttonLeaves[n-2]:before[n])!=after[n]){i.card.updateLocalContent(art.surfaces[n].id,++i.contentEpoch,after[n],i.options);++i.rasterizations;}}
 for(unsigned n=0;n<2;++n){i.buttonLeaves[n]=art.layers["children"].array()[n+2];i.painted[n]=i.state.buttonPaint(n,now);}i.artwork=std::move(art);i.seen=i.state.revision();i.viewport=viewport;i.dirty=false;return true;
}
void NativeSettingsSafety::updatePose(Rect viewport,const Matrix&tilt,double now){auto&i=*impl_;need(i.viewport==viewport&&!i.dirty&&i.seen==i.state.revision()&&tilt.finite(),"Synchronize source confirmation before placement");const auto geometry=m::SettingsSafety::geometry(viewport);const auto phase=i.state.pose(now);Matrix transformed=tilt;transformed.values[13]=phase.travel; // Source CABasicAnimation targets transform.translation.y.
 i.cardWorld=Matrix::translation(geometry.card.x+geometry.card.width*.5,geometry.card.y+95)*transformed*Matrix::translation(-geometry.card.width*.5,-95);i.hit=core::Projection{{i.cardWorld.values[0],i.cardWorld.values[4],i.cardWorld.values[12],i.cardWorld.values[1],i.cardWorld.values[5],i.cardWorld.values[13],i.cardWorld.values[3],i.cardWorld.values[7],i.cardWorld.values[15]}};
 std::optional<Rect>bounds;const auto include=[&](core::Point p){const auto q=i.hit.project(p);need(bool(q),"Invalid source confirmation projection");if(!bounds)bounds=Rect{q->x,q->y,0,0};else{const auto x=std::min(bounds->x,q->x),y=std::min(bounds->y,q->y),right=std::max(bounds->x+bounds->width,q->x),bottom=std::max(bounds->y+bounds->height,q->y);*bounds={x,y,right-x,bottom-y};}};
 // Four projected corners cover the convex source card and all its ink; the
 // source line/button rectangles sit inside. Add AA/raster padding before
 // choosing the retained pixel-aligned coverage grid.
 for(auto p:std::array<core::Point,4>{{{-2,-2},{geometry.card.width+2,-2},{geometry.card.width+2,192},{-2,192}}})include(p);const auto visible=intersection(*bounds,viewport);need(visible.width>0&&visible.height>0,"Confirmation has no visible coverage");if(!contains(i.cover,visible)){constexpr double grid=64;const double left=std::floor(visible.x/grid)*grid,top=std::floor(visible.y/grid)*grid,right=std::ceil((visible.x+visible.width)/grid)*grid,bottom=std::ceil((visible.y+visible.height)/grid)*grid;i.cover=intersection({left,top,right-left,bottom-top},viewport);}
 for(std::size_t n=0;n<i.placements.size();++n)i.placements[n].world=i.cardWorld*i.artwork.surfaces[n].local;i.card.setPlacements(i.placements);const auto&r=i.cover;const std::array<Rect,4>surround{{{viewport.x,viewport.y,viewport.width,r.y-viewport.y},{viewport.x,r.y,r.x-viewport.x,r.height},{r.x+r.width,r.y,viewport.x+viewport.width-r.x-r.width,r.height},{viewport.x,r.y+r.height,viewport.width,viewport.y+viewport.height-r.y-r.height}}};for(unsigned n=0;n<4;++n){const auto b=surround[n];i.published[n].world=Matrix::translation(b.x,b.y)*Matrix::scale(b.width,b.height);i.published[n].opacity=float(phase.opacity*(i.appearance.dark?.30:.22));}i.published[4].opacity=float(phase.opacity);i.published[4].world={};i.posed=true;
}
std::optional<int>NativeSettingsSafety::actionAt(core::Point p)const{const auto&i=*impl_;if(!i.posed||!i.state.modal())return{};const auto q=i.hit.unproject(p);if(!q)return{};const auto g=m::SettingsSafety::geometry(*i.viewport);if(g.cancel.contains(*q))return 0;if(g.confirm.contains(*q))return 1;return{};}
void NativeSettingsSafety::upload(Renderer&r){auto&i=*impl_;need(i.posed,"Place confirmation before uploading");if(!i.quadUploaded){const std::array<Vertex,4>vertices{{{{0,0,0},{0,0},{1,1,1,1}},{{1,0,0},{1,0},{1,1,1,1}},{{1,1,0},{1,1},{1,1,1,1}},{{0,1,0},{0,1},{1,1,1,1}}}};constexpr std::array<std::uint32_t,6>indices{0,1,2,0,2,3};r.setMesh(i.quadID,1,{vertices,indices});i.quadUploaded=true;}if(i.uploadedCardRevision!=i.card.resourceRevision()){i.card.uploadResources(r);i.uploadedCardRevision=i.card.resourceRevision();}const auto draws=i.card.prepareDraws();if(i.local.empty()){i.local.resize(draws.size()+1);auto&background=i.local[0];background.sourceID=i.groupID+".localDim";background.meshID=i.quadID;background.linearTint={0,0,0,1};for(std::size_t n=0;n<draws.size();++n){i.local[n+1]=draws[n];i.local[n+1].masks.reserve(8);}}auto&background=i.local[0];background.opacity=i.appearance.dark?.30f:.22f;background.world=Matrix::translation(i.cover.x,i.cover.y)*Matrix::scale(i.cover.width,i.cover.height);for(std::size_t n=0;n<draws.size();++n){auto&target=i.local[n+1];const auto&source=draws[n];need(target.sourceID==source.sourceID&&target.meshID==source.meshID&&target.textureID==source.textureID,"Source confirmation identities changed");target.world=source.world;target.opacity=source.opacity;target.masks.assign(source.masks.begin(),source.masks.end());}if(!i.uploaded||i.uploadedCoverage!=i.cover){r.configureNativeGroup(i.groupID,{i.cover,i.options.pixelsPerPoint},i.local);i.groupOwned=true;i.uploadedCoverage=i.cover;}else r.setNativeGroupDraws(i.groupID,i.local);const auto&output=r.nativeGroupOutput(i.groupID);if(!i.uploaded){i.published[4].sourceID=output.sourceID;i.published[4].meshID=output.meshID;i.published[4].textureID=output.textureID;i.uploaded=true;}i.card.collectRetiredResources(r);}
LayerCompositionEntry NativeSettingsSafety::entry(){need(impl_->uploaded,"Upload confirmation before publishing");return{&impl_->carrier,impl_->published};}
bool NativeSettingsSafety::releaseResources(Renderer&r){auto&i=*impl_;if(i.groupOwned&&!r.removeNativeGroup(i.groupID))return false;i.uploaded=i.groupOwned=false;i.uploadedCardRevision=0;bool ok=i.card.releaseResources(r)&&i.carrier.releaseResources(r);if(i.quadUploaded){if(r.removeMesh(i.quadID))i.quadUploaded=false;else ok=false;}return ok;}
Rect NativeSettingsSafety::coverage()const noexcept{return impl_->cover;}
std::size_t NativeSettingsSafety::rasterizations()const noexcept{return impl_->rasterizations;}
}
#endif
