#include "native/settings_scene.hpp"
#ifdef _WIN32
#include "core/source_camera.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace endfield::native {namespace {
using Json=ehud::data::Json;using Matrix=core::Matrix4;namespace m=modules;
void need(bool v,const char*s){if(!v)throw std::invalid_argument(s);}
Json group(std::string id,Json::Array children){double left=1e100,top=1e100,right=-1e100,bottom=-1e100;for(const auto&n:children){const auto&p=n["position"].array();const auto&b=n["bounds"].array();left=std::min(left,p[0].number());top=std::min(top,p[1].number());right=std::max(right,p[0].number()+b[2].number());bottom=std::max(bottom,p[1].number()+b[3].number());}need(right>left&&bottom>top,"Settings static group needs finite positive bounds");return Json::Object{{"id",std::move(id)},{"bounds",Json::Array{left,top,right-left,bottom-top}},{"position",Json::Array{left,top}},{"anchorPoint",Json::Array{0,0}},{"allowsGroupOpacity",false},{"children",std::move(children)}};}
m::SettingsArtworkPart compact(m::SettingsArtworkPart p,const SettingsImages&images){auto children=p.layers["children"].array();Json::Array result,pending;std::vector<m::SettingsSurface>surfaces;std::size_t serial{};const auto flush=[&]{if(pending.empty())return;const auto id="settings.static."+std::to_string(serial++);result.push_back(group(id,std::move(pending)));pending={};surfaces.push_back({id,{},{},false,false,1});};
 for(std::size_t n=0;n<children.size();++n){auto&node=children[n];if(!node["requiredSourceImage"].isNull()){const auto key=node["requiredSourceImage"].string();const auto it=images.find(key);need(it!=images.end()&&it->second.isObject(),"Missing original Settings icon artwork");const auto&asset=it->second;need(asset["asset"].isString()&&asset["sha256"].isString()&&asset["sha256"].string().size()==64,"Invalid pinned Settings icon");node["contents"]=asset;node.erase("requiredSourceImage");}
  if(p.surfaces[n].tint||p.surfaces[n].rim){flush();result.push_back(std::move(node));surfaces.push_back(std::move(p.surfaces[n]));}else pending.push_back(std::move(node));}
 flush();p.layers["children"]=std::move(result);p.surfaces=std::move(surfaces);return p;
}
}
struct NativeSettingsScene::Impl {
 struct Track{double from{},target{},start{},duration{};};static double value(Track t,double now){return t.duration>0?t.from+(t.target-t.from)*core::CubicTiming{0,0,.58,1}.value((now-t.start)/t.duration):t.target;}
 struct Part{m::SettingsArtworkPart plan;LayerScene scene;std::unique_ptr<NativeLayerGroup>group;std::vector<LayerPlacement>placements,active;std::vector<Track>feedback;std::array<PlaneMask,8>masks{},outerMasks{};Matrix outerWorld;float outerOpacity{};std::size_t outerCount{};std::optional<PlaneShutter>shutter;bool uploaded{};
  Part(LayerRasterizer&r,m::SettingsArtworkPart p,const LayerRasterOptions&o,bool row):plan(std::move(p)),scene(r),placements(plan.surfaces.size()),feedback(plan.surfaces.size()){scene.load(plan.layers,o);need(scene.report().unsupported.empty(),"Unsupported original Settings artwork");active.reserve(placements.size());for(std::size_t n=0;n<placements.size();++n){const auto&s=plan.surfaces[n];placements[n]={scene.surfaceIndex(s.id).value_or(std::size_t(-1)),s.local,s.opacity,{}};feedback[n].from=feedback[n].target=s.rim?.28:0;if(placements[n].surface!=std::size_t(-1))active.push_back(placements[n]);}scene.setPlacements(active);scene.prepareDraws();if(row)group=std::make_unique<NativeLayerGroup>(scene,"settings.row."+plan.row,o.pixelsPerPoint);}
  bool release(Renderer&r){return group?group->releaseResources(r):scene.releaseResources(r);}
 };
 struct Page{std::vector<std::shared_ptr<Part>>rows;std::shared_ptr<Part>chrome;};
 m::SettingsPresentation&state;LayerRasterizer&raster;LayerRasterOptions options;SettingsImages images;m::SettingsAppearance appearance;Page current;std::optional<Page>outgoing;std::vector<std::shared_ptr<Part>>retired;std::vector<LayerCompositionEntry>entries;bool dirty{true},posed{},pressed{};std::optional<std::string>hover;std::uint64_t revision{};double lastTime{};SettingsSceneStats stats;DrawObject validator;
 Impl(m::SettingsPresentation&s,LayerRasterizer&r,LayerRasterOptions o,SettingsImages im,m::SettingsAppearance a):state(s),raster(r),options(std::move(o)),images(std::move(im)),appearance(a){entries.reserve(20);retired.reserve(20);validator.sourceID="settings.pose";validator.masks.reserve(8);}
 void time(double now)const{need(std::isfinite(now)&&now>=lastTime,"Settings needs monotonic owner time");}
 template<class F>void each(Page&p,F&&f){for(auto&r:p.rows)f(*r,true);if(p.chrome)f(*p.chrome,false);}
 template<class F>void all(F&&f){if(outgoing)each(*outgoing,f);each(current,f);}
 void refreshEntries(){entries.clear();all([&](Part&p,bool){if(p.group){if(p.uploaded)entries.push_back(p.group->entry());}else entries.push_back({&p.scene,{}});});}
};
NativeSettingsScene::NativeSettingsScene(m::SettingsPresentation&s,LayerRasterizer&r,LayerRasterOptions o,SettingsImages images,m::SettingsAppearance a):impl_(std::make_unique<Impl>(s,r,std::move(o),std::move(images),a)){}
NativeSettingsScene::~NativeSettingsScene()=default;
void NativeSettingsScene::setAppearance(m::SettingsAppearance a){if(a==impl_->appearance)return;impl_->appearance=a;impl_->dirty=true;}
bool NativeSettingsScene::syncContent(double now){auto&i=*impl_;i.time(now);if(!i.dirty&&i.revision==i.state.revision())return false;need(i.retired.empty(),"Publish prior Settings generation before new content");std::vector<std::shared_ptr<Impl::Part>>old;const auto save=[&](Impl::Page&p){for(auto&v:p.rows)old.push_back(v);if(p.chrome)old.push_back(p.chrome);};if(i.outgoing)save(*i.outgoing);save(i.current);std::vector<bool>used(old.size());std::size_t needed{};
 struct Pending{m::SettingsArtwork art;std::vector<std::optional<std::size_t>>matches;};
 const auto plan=[&](const m::SettingsPageView&v){Pending p{m::prepareSettingsArtwork(v,i.appearance),{}};for(auto&r:p.art.rows)r=compact(std::move(r),i.images);p.art.chrome=compact(std::move(p.art.chrome),i.images);const auto match=[&](const m::SettingsArtworkPart&part,bool grouped){std::optional<std::size_t>found;for(std::size_t n=0;n<old.size();++n)if(!used[n]&&bool(old[n]->group)==grouped&&old[n]->plan.row==part.row&&old[n]->plan.layers==part.layers){found=n;used[n]=true;break;}if(!found)needed+=part.surfaces.size();p.matches.push_back(found);};for(const auto&r:p.art.rows)match(r,true);match(p.art.chrome,false);return p;};
 // Match outgoing first so the old source page remains intact during hand-off.
 std::optional<Pending>outPlan;if(i.state.outgoing())outPlan=plan(*i.state.outgoing());auto nextPlan=plan(i.state.view());need(i.raster.stats().entries<=LayerRasterizer::maximumEntries&&needed<=LayerRasterizer::maximumEntries-i.raster.stats().entries,"Settings generation exceeds shared raster budget");
 const auto build=[&](Pending&p){Impl::Page page;page.rows.reserve(p.art.rows.size());for(std::size_t n=0;n<=p.art.rows.size();++n){const bool row=n<p.art.rows.size();auto&part=row?p.art.rows[n]:p.art.chrome;auto created=p.matches[n]?old[*p.matches[n]]:std::make_shared<Impl::Part>(i.raster,std::move(part),i.options,row);if(row)page.rows.push_back(std::move(created));else page.chrome=std::move(created);}return page;};std::optional<Impl::Page>nextOut;if(outPlan)nextOut=build(*outPlan);auto next=build(nextPlan);
 for(std::size_t n=0;n<old.size();++n)if(!used[n])i.retired.push_back(old[n]);i.outgoing=std::move(nextOut);i.current=std::move(next);i.revision=i.state.revision();i.dirty=false;i.lastTime=now;++i.stats.builds;i.refreshEntries();
 // Content replacement gets the existing pointer state immediately. No fake
 // move event is required to restore stationary pressed/hover feedback.
 const auto hover=i.hover;const bool pressed=i.pressed;i.hover.reset();i.pressed=!pressed;setFeedback(hover?std::optional<std::string_view>(*hover):std::nullopt,pressed,now);return true;
}
bool NativeSettingsScene::setFeedback(std::optional<std::string_view>action,bool pressed,double now){auto&i=*impl_;i.time(now);if(i.hover.has_value()==action.has_value()&&(!action||*i.hover==*action)&&i.pressed==pressed&&!i.state.reduceMotion())return false;i.all([&](Impl::Part&p,bool){for(std::size_t n=0;n<p.plan.surfaces.size();++n){const auto&s=p.plan.surfaces[n];if(!s.tint&&!s.rim)continue;const bool hit=action&&*action==s.action;const double target=s.rim?(hit?1:.28):(hit?(pressed?1:.62):0);auto&t=p.feedback[n];if(t.target!=target||(i.state.reduceMotion()&&t.duration))t={Impl::value(t,now),target,now,i.state.reduceMotion()?0:pressed&&hit?.06:.14};}});i.hover=action?std::optional(std::string(*action)):std::nullopt;i.pressed=pressed;i.lastTime=now;return true;}
void NativeSettingsScene::updatePose(const NativeSettingsPose&pose){auto&i=*impl_;i.time(pose.time);need(!i.dirty&&i.revision==i.state.revision(),"Synchronize Settings before pose");need(pose.world.finite()&&std::isfinite(pose.opacity)&&pose.opacity>=0&&pose.opacity<=1&&pose.ownerMasks.size()<=6,"Invalid Settings pose");if(pose.shutter)validatePlaneShutter(*pose.shutter);const auto inverse=core::source::inverseSourceMatrix(pose.world);const auto page=i.state.pagePose(pose.time);
 const auto prepare=[&](Impl::Page&p,bool outgoing){const auto travel=outgoing?page.outgoingX:page.incomingX;const auto mask=outgoing?page.outgoingMask:page.incomingMask;i.each(p,[&](Impl::Part&part,bool row){const auto rowPose=outgoing?m::SettingsRowPose{}:i.state.rowPose(part.plan.row,pose.time);const auto world=pose.world*Matrix::translation(travel+rowPose.x,0);std::size_t count=pose.ownerMasks.size();std::copy(pose.ownerMasks.begin(),pose.ownerMasks.end(),part.outerMasks.begin());const bool empty=mask.width<=0||mask.height<=0;if(!empty)part.outerMasks[count++]={inverse,mask};if(row)part.outerMasks[count++]={core::source::inverseSourceMatrix(pose.world*Matrix::translation(travel,0)),m::SettingsPresentation::viewport()};part.outerWorld=world;part.outerOpacity=empty?0:pose.opacity*float(row?rowPose.opacity:1);part.outerCount=count;part.shutter=pose.shutter;
  for(std::size_t n=0;n<part.placements.size();++n){const auto&s=part.plan.surfaces[n];auto&v=part.placements[n];v.world=(part.group?Matrix{}:world)*s.local;v.opacity=(part.group?1:part.outerOpacity)*((s.tint||s.rim)?float(Impl::value(part.feedback[n],pose.time)):s.opacity);v.masks=part.group?std::span<const PlaneMask>{}:std::span(part.outerMasks.data(),count);i.validator.world=v.world;i.validator.opacity=v.opacity;i.validator.masks.assign(v.masks.begin(),v.masks.end());i.validator.shutter=part.group?std::nullopt:pose.shutter;validateDrawObject(i.validator);}
 });};if(i.outgoing)prepare(*i.outgoing,true);prepare(i.current,false);
 i.all([&](Impl::Part&p,bool){p.active.clear();for(const auto&v:p.placements)if(v.surface!=std::size_t(-1))p.active.push_back(v);p.scene.setPlacements(p.active);p.scene.setGroupShutter(p.group?std::nullopt:pose.shutter);if(p.group&&p.uploaded)p.group->setPose(p.outerWorld,p.outerOpacity,std::span(p.outerMasks.data(),p.outerCount),p.shutter);});i.posed=true;i.lastTime=pose.time;++i.stats.poses;
}
bool NativeSettingsScene::uploadAnimations(Renderer&r){auto&i=*impl_;need(i.posed,"Place Settings before upload");bool changed{},entriesChanged{};i.all([&](Impl::Part&p,bool){if(!p.group)return;if(!p.uploaded){changed|=p.group->uploadResources(r);p.uploaded=true;entriesChanged=true;}else changed|=p.group->updateLocal(r);p.group->setPose(p.outerWorld,p.outerOpacity,std::span(p.outerMasks.data(),p.outerCount),p.shutter);});if(entriesChanged)i.refreshEntries();return changed;}
bool NativeSettingsScene::requiresFrames(double now)const{const auto&i=*impl_;i.time(now);if(i.state.requiresFrames(now))return true;if(!i.state.active()||i.state.reduceMotion())return false;bool pending{};const auto check=[&](const Impl::Page&p){for(const auto&part:p.rows)for(const auto&t:part->feedback)pending|=t.duration>0&&t.from!=t.target&&now<t.start+t.duration;if(p.chrome)for(const auto&t:p.chrome->feedback)pending|=t.duration>0&&t.from!=t.target&&now<t.start+t.duration;};check(i.current);if(i.outgoing)check(*i.outgoing);return pending;}
std::span<const LayerCompositionEntry>NativeSettingsScene::entries()const noexcept{return impl_->entries;}
bool NativeSettingsScene::collectRetired(Renderer&r){for(auto&p:impl_->retired)if(!p->release(r))return false;impl_->retired.clear();return true;}
bool NativeSettingsScene::releaseResources(Renderer&r){auto&i=*impl_;bool ok=collectRetired(r);i.all([&](Impl::Part&p,bool){ok=p.release(r)&&ok;});return ok;}
SettingsSceneStats NativeSettingsScene::stats()const noexcept{auto s=impl_->stats;s.parts=impl_->current.rows.size()+(impl_->current.chrome?1:0)+(impl_->outgoing?impl_->outgoing->rows.size()+1:0);s.retiredParts=impl_->retired.size();return s;}
}
#endif
