# Personal Profile, bottom-left ID card binding and Work Mode lifetime hours.
# Included at the end of windows/CMakeLists.txt, after every existing target.
# Portable targets build on Windows (system ICU) or wherever a local ICU exists.
if(NOT WIN32 AND NOT ICU_FOUND)
  find_package(ICU QUIET COMPONENTS uc i18n)
endif()
if(WIN32 OR ICU_FOUND)
  add_library(hud_profile modules/profile_state.cpp native/profile_text.cpp modules/profile_service.cpp modules/work_mode_profile_hours.cpp modules/id_card_binding.cpp modules/profile_events.cpp modules/profile_presentation.cpp modules/profile_artwork.cpp modules/id_card_artwork.cpp)
  target_include_directories(hud_profile PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
  target_link_libraries(hud_profile PUBLIC hud_data hud_scene hud_localization hud_utility hud_work_mode hud_source_motion hud_packet)
  if(WIN32)
    target_compile_definitions(hud_profile PRIVATE _WIN32_WINNT=0x0A00 UNICODE _UNICODE NOMINMAX)
    target_link_libraries(hud_profile PRIVATE icu)
  else()
    target_link_libraries(hud_profile PRIVATE ICU::uc ICU::i18n)
  endif()
  if(MSVC)
    target_compile_options(hud_profile PRIVATE /W4 /permissive- /EHsc)
  else()
    target_compile_options(hud_profile PRIVATE -Wall -Wextra -Wpedantic)
  endif()
  if(BUILD_TESTING)
    add_executable(profile_state_tests tests/profile_state_tests.cpp)
    target_link_libraries(profile_state_tests PRIVATE hud_profile)
    add_test(NAME profile_state_contracts COMMAND profile_state_tests ${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/profile-state-source.json)
    add_executable(profile_service_tests tests/profile_service_tests.cpp)
    target_link_libraries(profile_service_tests PRIVATE hud_profile)
    add_test(NAME profile_service_contracts COMMAND profile_service_tests)
    add_executable(profile_presentation_tests tests/profile_presentation_tests.cpp)
    target_link_libraries(profile_presentation_tests PRIVATE hud_profile)
    add_test(NAME profile_presentation_contracts COMMAND profile_presentation_tests ${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/profile-presentation-source.json)
    add_executable(id_card_artwork_tests tests/id_card_artwork_tests.cpp)
    target_link_libraries(id_card_artwork_tests PRIVATE hud_profile)
    add_test(NAME id_card_artwork_contracts COMMAND id_card_artwork_tests ${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/id_card-artwork-source.json ${CMAKE_CURRENT_SOURCE_DIR}/resources/profile)
    add_executable(id_card_binding_tests tests/id_card_binding_tests.cpp)
    target_link_libraries(id_card_binding_tests PRIVATE hud_profile)
    add_test(NAME id_card_binding_contracts COMMAND id_card_binding_tests ${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/id_card-source.json)
  endif()
endif()

# Native Win32 page: retained scene, projected editors and the module owner.
if(WIN32 AND TARGET hud_profile)
  add_library(hud_profile_native native/profile_scene.cpp native/profile_editor_field.cpp native/profile_image.cpp native/id_card_captions.cpp native/profile_pickers.cpp tools/profile_preview.cpp tools/profile_owner.cpp)
  target_include_directories(hud_profile_native PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
  target_compile_definitions(hud_profile_native PRIVATE _WIN32_WINNT=0x0A00 WINVER=0x0A00 UNICODE _UNICODE NOMINMAX)
  target_link_libraries(hud_profile_native PUBLIC hud_profile hud_native hud_overlay_host PRIVATE windowscodecs ole32 comdlg32)
  if(MSVC)
    target_compile_options(hud_profile_native PRIVATE /W4 /permissive- /EHsc)
  endif()
  if(BUILD_TESTING)
    add_executable(profile_scene_tests tests/profile_scene_tests.cpp)
    target_compile_definitions(profile_scene_tests PRIVATE UNICODE _UNICODE NOMINMAX)
    target_link_libraries(profile_scene_tests PRIVATE hud_profile_native ole32)
    add_test(NAME profile_scene_contracts COMMAND profile_scene_tests ${CMAKE_CURRENT_SOURCE_DIR}/native/hud.hlsl)
    add_executable(profile_image_tests tests/profile_image_tests.cpp)
    target_compile_definitions(profile_image_tests PRIVATE UNICODE _UNICODE NOMINMAX)
    target_link_libraries(profile_image_tests PRIVATE hud_profile_native windowscodecs ole32)
    add_test(NAME profile_image_contracts COMMAND profile_image_tests)
    add_executable(profile_preview_tests tests/profile_preview_tests.cpp)
    target_compile_definitions(profile_preview_tests PRIVATE UNICODE _UNICODE NOMINMAX)
    target_link_libraries(profile_preview_tests PRIVATE hud_profile_native ole32)
    add_test(NAME profile_preview_contracts COMMAND profile_preview_tests ${CMAKE_CURRENT_SOURCE_DIR}/native/hud.hlsl ${CMAKE_CURRENT_SOURCE_DIR}/resources/profile)
    add_executable(profile_owner_tests tests/profile_owner_tests.cpp)
    target_compile_definitions(profile_owner_tests PRIVATE UNICODE _UNICODE NOMINMAX)
    target_link_libraries(profile_owner_tests PRIVATE hud_profile_native windowscodecs ole32)
    add_test(NAME profile_owner_contracts COMMAND profile_owner_tests ${CMAKE_CURRENT_SOURCE_DIR}/native/hud.hlsl ${CMAKE_CURRENT_SOURCE_DIR}/resources/profile)
    add_executable(profile_pickers_tests tests/profile_pickers_tests.cpp)
    target_compile_definitions(profile_pickers_tests PRIVATE UNICODE _UNICODE NOMINMAX)
    target_link_libraries(profile_pickers_tests PRIVATE hud_profile_native ole32)
    add_test(NAME profile_pickers_contracts COMMAND profile_pickers_tests)
    add_executable(id_card_captions_tests tests/id_card_captions_tests.cpp)
    target_compile_definitions(id_card_captions_tests PRIVATE UNICODE _UNICODE NOMINMAX)
    target_link_libraries(id_card_captions_tests PRIVATE hud_profile_native ole32)
    add_test(NAME id_card_captions_contracts COMMAND id_card_captions_tests ${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/id_card-native-captions.json ${CMAKE_CURRENT_SOURCE_DIR}/resources/profile)
  endif()
endif()
