#!/bin/bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-$PROJECT_DIR/build}"
SELECTED_SDK="$("$PROJECT_DIR/scripts/build.sh" --print-sdk)"
mkdir -p "$BUILD_DIR/tests" "$BUILD_DIR/module-cache"

xcrun swiftc -swift-version 5 -parse-as-library \
    -sdk "$SELECTED_SDK" -module-cache-path "$BUILD_DIR/module-cache" \
    -framework Cocoa -framework IOKit -framework CoreAudio -framework Quartz -framework Carbon -lsqlite3 \
    "$PROJECT_DIR/Sources/Models.swift" \
    "$PROJECT_DIR/Sources/HUDResources.swift" \
    "$PROJECT_DIR/Sources/HUDGitHubRelease.swift" \
    "$PROJECT_DIR/Sources/HUDUpdateState.swift" \
    "$PROJECT_DIR/Sources/HUDDisplayPolicy.swift" \
    "$PROJECT_DIR/Sources/HUDClock.swift" \
    "$PROJECT_DIR/Sources/HUDApplicationIcon.swift" \
    "$PROJECT_DIR/Sources/EndfieldGameIcon.swift" \
    "$PROJECT_DIR/Sources/HUDSettingsController.swift" \
    "$PROJECT_DIR/Sources/HUDSettingsCanvas.swift" \
    "$PROJECT_DIR/Sources/HUDQuitConfirmationView.swift" \
    "$PROJECT_DIR/Sources/HUDSettingsInteraction.swift" \
    "$PROJECT_DIR/Sources/HUDRuntimeAppearance.swift" \
    "$PROJECT_DIR/Sources/HUDControlHighlightLayer.swift" \
    "$PROJECT_DIR/Sources/Localization.swift" \
    "$PROJECT_DIR/Sources/OverlayGeometry.swift" \
    "$PROJECT_DIR/Sources/BatteryCapacity.swift" \
    "$PROJECT_DIR/Sources/BatteryMonitor.swift" \
    "$PROJECT_DIR/Sources/DisplayPolicy.swift" \
    "$PROJECT_DIR/Sources/DeviceBatteryProvider.swift" \
    "$PROJECT_DIR/Sources/SystemOverlayState.swift" \
    "$PROJECT_DIR/Sources/ShelfDragPresentationState.swift" \
    "$PROJECT_DIR/Sources/SummonShortcut.swift" \
    "$PROJECT_DIR/Sources/ShortcutPolicy.swift" \
    "$PROJECT_DIR/Sources/HUDMotionController.swift" \
    "$PROJECT_DIR/Sources/HUDDeploymentFlicker.swift" \
    "$PROJECT_DIR/Sources/HUDMechanicalArtwork.swift" \
    "$PROJECT_DIR/Sources/ChargeIndicatorView.swift" \
    "$PROJECT_DIR/Sources/HUDChargeBadge.swift" \
    "$PROJECT_DIR/Sources/HUDIdentityCard.swift" \
    "$PROJECT_DIR/Sources/HUDPortraitArtwork.swift" \
    "$PROJECT_DIR/Sources/UserProfileStore.swift" \
    "$PROJECT_DIR/Sources/PersonalProfileCanvas.swift" \
    "$PROJECT_DIR/Sources/HUDPersonalProfileInteraction.swift" \
    "$PROJECT_DIR/Sources/HUDRenderScale.swift" \
    "$PROJECT_DIR/Sources/HUDModule.swift" \
    "$PROJECT_DIR/Sources/HUDSubsectionTransition.swift" \
    "$PROJECT_DIR/Sources/HUDModuleContent.swift" \
    "$PROJECT_DIR/Sources/HUDNavigationTarget.swift" \
    "$PROJECT_DIR/Sources/HUDNavigation.swift" \
    "$PROJECT_DIR/Sources/NotesStore.swift" \
    "$PROJECT_DIR/Sources/NotesCanvas.swift" \
    "$PROJECT_DIR/Sources/HUDNotesInteraction.swift" \
    "$PROJECT_DIR/Sources/FileShelfStore.swift" \
    "$PROJECT_DIR/Sources/FileShelfCanvas.swift" \
    "$PROJECT_DIR/Sources/HUDFileShelfInteraction.swift" \
    "$PROJECT_DIR/Sources/AppShortcutStore.swift" \
    "$PROJECT_DIR/Sources/AppShortcutLauncher.swift" \
    "$PROJECT_DIR/Sources/AppShortcutArtwork.swift" \
    "$PROJECT_DIR/Sources/AppShortcutCanvas.swift" \
    "$PROJECT_DIR/Sources/HUDAppShortcutInteraction.swift" \
    "$PROJECT_DIR/Sources/ClipboardStore.swift" \
    "$PROJECT_DIR/Sources/ClipboardWatcher.swift" \
    "$PROJECT_DIR/Sources/ClipboardCanvas.swift" \
    "$PROJECT_DIR/Sources/HUDClipboardInteraction.swift" \
    "$PROJECT_DIR/Sources/AudioDeviceController.swift" \
    "$PROJECT_DIR/Sources/PerAppAudioController.swift" \
    "$PROJECT_DIR/Sources/PerAppAudioEngine.swift" \
    "$PROJECT_DIR/Sources/PerAppAudioPCM.swift" \
    "$PROJECT_DIR/Sources/VolumeCanvas.swift" \
    "$PROJECT_DIR/Sources/HUDVolumeInteraction.swift" \
    "$PROJECT_DIR/Sources/SystemActivityMonitor.swift" \
    "$PROJECT_DIR/Sources/AppActivityMonitor.swift" \
    "$PROJECT_DIR/Sources/ActivityMonitorCanvas.swift" \
    "$PROJECT_DIR/Sources/SystemStorageSettings.swift" \
    "$PROJECT_DIR/Sources/StorageController.swift" \
    "$PROJECT_DIR/Sources/TelemetryCanvases.swift" \
    "$PROJECT_DIR/Sources/HUDTelemetryInteraction.swift" \
    "$PROJECT_DIR/Sources/WorkModeController.swift" \
    "$PROJECT_DIR/Sources/WorkModeFocusController.swift" \
    "$PROJECT_DIR/Sources/WorkModeCanvas.swift" \
    "$PROJECT_DIR/Sources/HUDWorkModeInteraction.swift" \
    "$PROJECT_DIR/Sources/SystemEventLog.swift" \
    "$PROJECT_DIR/Sources/SystemEventRecorder.swift" \
    "$PROJECT_DIR/Sources/AudioTopologyWatcher.swift" \
    "$PROJECT_DIR/Sources/EventLogCanvas.swift" \
    "$PROJECT_DIR/Sources/HUDEventLogInteraction.swift" \
    "$PROJECT_DIR/Sources/WorldMapStore.swift" \
    "$PROJECT_DIR/Sources/WorldMapGeometry.swift" \
    "$PROJECT_DIR/Sources/WorldMapTerrain.swift" \
    "$PROJECT_DIR/Sources/WorldMapCountries.swift" \
    "$PROJECT_DIR/Sources/WorldMapPathGeometry.swift" \
    "$PROJECT_DIR/Sources/WorldMapLayerCoordinates.swift" \
    "$PROJECT_DIR/Sources/WorldMapRasterController.swift" \
    "$PROJECT_DIR/Sources/WorldMapRasterPainter.swift" \
    "$PROJECT_DIR/Sources/WorldMapCanvas.swift" \
    "$PROJECT_DIR/Sources/HUDWorldMapInteraction.swift" \
    "$PROJECT_DIR/Tests/HUDMotionTests.swift" \
    "$PROJECT_DIR/Tests/HUDCanvasLifecycleTests.swift" \
    "$PROJECT_DIR/Tests/HUDDeploymentFlickerTests.swift" \
    "$PROJECT_DIR/Tests/HUDControlHighlightTests.swift" \
    "$PROJECT_DIR/Tests/HUDApplicationIconTests.swift" \
    "$PROJECT_DIR/Tests/HUDMechanicalArtworkTests.swift" \
    "$PROJECT_DIR/Tests/HUDChargeBadgeTests.swift" \
    "$PROJECT_DIR/Tests/HUDModuleTests.swift" \
    "$PROJECT_DIR/Tests/HUDNavigationTests.swift" \
    "$PROJECT_DIR/Tests/NotesStoreTests.swift" \
    "$PROJECT_DIR/Tests/NotesCanvasTests.swift" \
    "$PROJECT_DIR/Tests/HUDNotesInteractionTests.swift" \
    "$PROJECT_DIR/Tests/FileShelfStoreTests.swift" \
    "$PROJECT_DIR/Tests/FileShelfCanvasTests.swift" \
    "$PROJECT_DIR/Tests/HUDFileShelfInteractionTests.swift" \
    "$PROJECT_DIR/Tests/AppShortcutStoreTests.swift" \
    "$PROJECT_DIR/Tests/AppShortcutCanvasTests.swift" \
    "$PROJECT_DIR/Tests/ClipboardStoreTests.swift" \
    "$PROJECT_DIR/Tests/ClipboardWatcherTests.swift" \
    "$PROJECT_DIR/Tests/ClipboardCanvasTests.swift" \
    "$PROJECT_DIR/Tests/AudioDeviceControllerTests.swift" \
    "$PROJECT_DIR/Tests/PerAppAudioTests.swift" \
    "$PROJECT_DIR/Tests/VolumeCanvasTests.swift" \
    "$PROJECT_DIR/Tests/SystemActivityMonitorTests.swift" \
    "$PROJECT_DIR/Tests/AppActivityMonitorTests.swift" \
    "$PROJECT_DIR/Tests/SystemStorageSettingsTests.swift" \
    "$PROJECT_DIR/Tests/StorageControllerTests.swift" \
    "$PROJECT_DIR/Tests/HUDSubsectionTransitionTests.swift" \
    "$PROJECT_DIR/Tests/TelemetryCanvasTests.swift" \
    "$PROJECT_DIR/Tests/TelemetryGraphTimeTests.swift" \
    "$PROJECT_DIR/Tests/WorkModeTests.swift" \
    "$PROJECT_DIR/Tests/UserProfileStoreTests.swift" \
    "$PROJECT_DIR/Tests/PersonalProfileCanvasTests.swift" \
    "$PROJECT_DIR/Tests/WorkModeFocusTests.swift" \
    "$PROJECT_DIR/Tests/SystemEventLogTests.swift" \
    "$PROJECT_DIR/Tests/SystemEventRecorderTests.swift" \
    "$PROJECT_DIR/Tests/AudioTopologyWatcherTests.swift" \
    "$PROJECT_DIR/Tests/EventLogCanvasTests.swift" \
    "$PROJECT_DIR/Tests/WorldMapStoreTests.swift" \
    "$PROJECT_DIR/Tests/WorldMapGeometryTests.swift" \
    "$PROJECT_DIR/Tests/WorldMapTerrainTests.swift" \
    "$PROJECT_DIR/Tests/WorldMapCountriesTests.swift" \
    "$PROJECT_DIR/Tests/WorldMapPathGeometryTests.swift" \
    "$PROJECT_DIR/Tests/WorldMapLayerCoordinatesTests.swift" \
    "$PROJECT_DIR/Tests/WorldMapRasterControllerTests.swift" \
    "$PROJECT_DIR/Tests/WorldMapRasterPainterTests.swift" \
    "$PROJECT_DIR/Tests/WorldMapCanvasTests.swift" \
    "$PROJECT_DIR/Tests/PowerDataTests.swift" \
    "$PROJECT_DIR/Tests/SystemOverlayStateTests.swift" \
    "$PROJECT_DIR/Tests/ShelfDragPresentationStateTests.swift" \
    "$PROJECT_DIR/Tests/ShortcutPolicyTests.swift" \
    "$PROJECT_DIR/Tests/SummonShortcutTests.swift" \
    "$PROJECT_DIR/Tests/SettingsTests.swift" \
    "$PROJECT_DIR/Tests/HUDDisplayPolicyTests.swift" \
    "$PROJECT_DIR/Tests/HUDClockTests.swift" \
    "$PROJECT_DIR/Tests/HUDSettingsCanvasTests.swift" \
    "$PROJECT_DIR/Tests/HUDQuitConfirmationTests.swift" \
    "$PROJECT_DIR/Tests/HUDGitHubReleaseTests.swift" \
    "$PROJECT_DIR/Tests/HUDUpdateStateTests.swift" \
    "$PROJECT_DIR/Tests/CoreTests.swift" \
    -o "$BUILD_DIR/tests/CoreTests"
"$BUILD_DIR/tests/CoreTests"
