# MSBuild FileTracker drops every file read under the per-user/common
# application-data and TEMP folders (LocalAppData, LocalLow, AppData, TEMP,
# ProgramData) from CL.read.1.tlog. With a Visual Studio generator and the
# source or build tree in such a folder, a header-only edit therefore never
# rebuilds its includers: their stale objects keep the old struct layouts and
# link against newer implementations (checkpoint 120: watch_session_preview.obj
# kept the pre-119 WatchAppearanceEntry layout, so setEntries read garbage).
#
# MSBuild still compares every source's command line with CL.command.1.tlog,
# which is keyed by the source alone and is not path-filtered. So each C/C++
# source gets one definition derived from the contents of every project file it
# can reach through quoted #include directives. A changed reachable header
# changes exactly those sources' command lines and recompiles only them. The
# scan is conservative: preprocessor conditions are ignored and every include
# root that holds a name contributes, so it may over-approximate but never
# drops a quoted project include. Angle-bracket SDK/MSVC headers stay tracked
# by MSBuild itself. Fingerprints are content hashes, so re-stamped but
# unchanged files never recompile anything.
include_guard(GLOBAL)

set(EHUD_INCLUDE_FINGERPRINTS AUTO CACHE STRING
  "Per-source project include fingerprints: AUTO (Visual Studio generator with the source or build tree in a folder MSBuild FileTracker ignores), ON or OFF")
set_property(CACHE EHUD_INCLUDE_FINGERPRINTS PROPERTY STRINGS AUTO ON OFF)

# Sets <out> to "<VARIABLE> (<tree>)" for the first source/build tree inside a
# FileTracker-ignored folder, or to "" when neither tree is inside one.
function(ehud_tracker_excluded_tree out)
  set(found "")
  string(REPLACE "\\" "/" trees "${CMAKE_SOURCE_DIR};${CMAKE_BINARY_DIR}")
  string(TOLOWER "${trees}" trees)
  foreach(variable IN ITEMS LOCALAPPDATA APPDATA TEMP TMP ProgramData USERPROFILE)
    set(root "$ENV{${variable}}")
    if(root STREQUAL "")
      continue()
    endif()
    set(label "${variable}")
    if(variable STREQUAL "USERPROFILE")
      set(root "${root}/AppData/LocalLow")
      set(label "USERPROFILE/AppData/LocalLow")
    endif()
    string(REPLACE "\\" "/" root "${root}")
    string(TOLOWER "${root}" root)
    foreach(tree IN LISTS trees)
      cmake_path(IS_PREFIX root "${tree}" NORMALIZE under)
      if(under AND found STREQUAL "")
        set(found "${label} (${tree})")
      endif()
    endforeach()
  endforeach()
  set(${out} "${found}" PARENT_SCOPE)
endfunction()

# Deferred to the end of the calling directory, after every target exists.
function(ehud_apply_include_fingerprints)
  string(TOUPPER "${EHUD_INCLUDE_FINGERPRINTS}" mode)
  if(NOT mode MATCHES "^(AUTO|ON|OFF)$")
    message(FATAL_ERROR "EHUD_INCLUDE_FINGERPRINTS must be AUTO, ON or OFF, not '${EHUD_INCLUDE_FINGERPRINTS}'")
  endif()
  set(reason "EHUD_INCLUDE_FINGERPRINTS=ON")
  if(NOT mode STREQUAL "ON")
    if(NOT CMAKE_GENERATOR MATCHES "^Visual Studio")
      return()
    endif()
    ehud_tracker_excluded_tree(reason)
    if(reason STREQUAL "")
      return()
    endif()
    if(mode STREQUAL "OFF")
      message(WARNING "MSBuild does not track header dependencies under ${reason}, and EHUD_INCLUDE_FINGERPRINTS=OFF: header-only edits will not rebuild their includers. Use AUTO, build with Ninja, or place the source/build tree elsewhere.")
      return()
    endif()
  endif()

  get_property(targets DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" PROPERTY BUILDSYSTEM_TARGETS)
  set(roots "")
  set(sources "")
  foreach(target IN LISTS targets)
    foreach(property IN ITEMS INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES)
      get_target_property(directories ${target} ${property})
      if(NOT directories)
        continue()
      endif()
      foreach(directory IN LISTS directories)
        if(NOT directory MATCHES "\\$<" AND IS_ABSOLUTE "${directory}" AND IS_DIRECTORY "${directory}")
          cmake_path(SET directory NORMALIZE "${directory}")
          list(APPEND roots "${directory}")
        endif()
      endforeach()
    endforeach()
    get_target_property(type ${target} TYPE)
    if(type STREQUAL "UTILITY")
      continue()
    endif()
    get_target_property(target_directory ${target} SOURCE_DIR)
    get_target_property(files ${target} SOURCES)
    if(NOT files)
      continue()
    endif()
    foreach(file IN LISTS files)
      if(file MATCHES "\\$<" OR NOT file MATCHES "\\.([cC]|[cC][cC]|[cC][pP][pP]|[cC][xX][xX])$")
        continue()
      endif()
      if(NOT IS_ABSOLUTE "${file}")
        set(file "${target_directory}/${file}")
      endif()
      cmake_path(SET file NORMALIZE "${file}")
      if(EXISTS "${file}")
        list(APPEND sources "${file}")
      endif()
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES roots)
  list(REMOVE_DUPLICATES sources)

  # Per file id (MD5 of its normalized path): _ehud_path_<id>, the resolved
  # direct quoted includes _ehud_deps_<id>, and for reached files
  # _ehud_entry_<id> = "<path relative to this directory>=<SHA-256>".
  set(generation 0)
  set(fingerprinted 0)
  set(reached_files "")
  foreach(source IN LISTS sources)
    string(MD5 source_id "${source}")
    set(_ehud_path_${source_id} "${source}")
    math(EXPR generation "${generation} + 1")
    set(_ehud_seen_${source_id} ${generation})
    set(queue ${source_id})
    set(entries "")
    while(queue)
      list(POP_FRONT queue current)
      if(NOT DEFINED _ehud_deps_${current})
        set(file "${_ehud_path_${current}}")
        cmake_path(GET file PARENT_PATH file_directory)
        file(STRINGS "${file}" lines REGEX "^[ \t]*#[ \t]*include[ \t]*\"[^\"]+\"")
        set(dependencies "")
        foreach(line IN LISTS lines)
          if(NOT line MATCHES "^[ \t]*#[ \t]*include[ \t]*\"([^\"]+)\"")
            continue()
          endif()
          set(name "${CMAKE_MATCH_1}")
          if(IS_ABSOLUTE "${name}")
            set(candidates "${name}")
          else()
            set(candidates "${file_directory}/${name}")
            foreach(root IN LISTS roots)
              list(APPEND candidates "${root}/${name}")
            endforeach()
          endif()
          foreach(candidate IN LISTS candidates)
            if(EXISTS "${candidate}" AND NOT IS_DIRECTORY "${candidate}")
              cmake_path(SET candidate NORMALIZE "${candidate}")
              string(MD5 dependency "${candidate}")
              set(_ehud_path_${dependency} "${candidate}")
              list(APPEND dependencies ${dependency})
            endif()
          endforeach()
        endforeach()
        list(REMOVE_DUPLICATES dependencies)
        set(_ehud_deps_${current} "${dependencies}")
      endif()
      foreach(dependency IN LISTS _ehud_deps_${current})
        if("${_ehud_seen_${dependency}}" STREQUAL "${generation}")
          continue()
        endif()
        set(_ehud_seen_${dependency} ${generation})
        list(APPEND queue ${dependency})
        if(NOT DEFINED _ehud_entry_${dependency})
          file(SHA256 "${_ehud_path_${dependency}}" hash)
          file(RELATIVE_PATH relative "${CMAKE_CURRENT_SOURCE_DIR}" "${_ehud_path_${dependency}}")
          set(_ehud_entry_${dependency} "${relative}=${hash}")
          list(APPEND reached_files "${_ehud_path_${dependency}}")
        endif()
        list(APPEND entries "${_ehud_entry_${dependency}}")
      endforeach()
    endwhile()
    if(entries)
      list(SORT entries)
      string(SHA256 fingerprint "${entries}")
      string(SUBSTRING "${fingerprint}" 0 16 fingerprint)
      set_property(SOURCE "${source}" APPEND PROPERTY COMPILE_DEFINITIONS "EHUD_INCLUDE_FINGERPRINT=${fingerprint}")
      math(EXPR fingerprinted "${fingerprinted} + 1")
    endif()
  endforeach()
  # Regenerate when a reached file changes, for builds that skip an explicit
  # configure step.
  if(reached_files)
    set_property(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${reached_files})
  endif()
  list(LENGTH reached_files reached_count)
  message(STATUS "Project include fingerprints: ${fingerprinted} sources over ${reached_count} reachable project files (${reason})")
endfunction()
