#include "tools/archive_media_binding.hpp"
#ifdef _WIN32
#include <algorithm>
#include <array>
#include <atomic>
#include <cmath>
#include <set>
#include <stdexcept>
namespace endfield::tools {
namespace {
namespace n=native;namespace m=modules;using J=m::ArchiveJson;using Matrix=core::Matrix4;
void need(bool ok,const char*why){if(!ok)throw std::invalid_argument(why);}
m::NotesMediaKind kind(const J&j){m::validateArchiveMedia(j);const auto&s=j["kind"].string();return s=="image"?m::NotesMediaKind::image:s=="gif"?m::NotesMediaKind::gif:m::NotesMediaKind::video;}
std::optional<double>duration(const J&j){return j["duration"].isNull()?std::nullopt:std::optional(j["duration"].number());}
std::string key(){static std::atomic<std::uint64_t>serial{1};return "archive.media."+std::to_string(serial.fetch_add(1,std::memory_order_relaxed));}
std::string path(const std::filesystem::path&p){const auto bytes=p.u8string();return std::string(reinterpret_cast<const char*>(bytes.data()),bytes.size());}
const std::array<n::Vertex,4>vertices{{{{0,0,0},{0,0}},{{1,0,0},{1,0}},{{1,1,0},{1,1}},{{0,1,0},{0,1}}}};
constexpr std::array<std::uint32_t,6>indices{0,1,2,0,2,3};
core::Rect fitted(unsigned w,unsigned h){need(w&&h,"Archive decoded dimensions must be positive");const auto b=m::ArchiveState::mediaRect();const double scale=std::min(b.width/w,b.height/h);return {b.x+(b.width-w*scale)/2,b.y+(b.height-h*scale)/2,w*scale,h*scale};}
}
struct ArchiveMediaBinding::Impl:std::enable_shared_from_this<Impl> {
 struct Asset {J reference;std::string key{tools::key()}; n::NotesImageAccess access;m::NotesMediaKind kind{};std::shared_ptr<const n::NotesImageFrame>frame;std::uint64_t observedFrame{},uploadedFrame{},appliedPoster{};HRESULT observedError{S_OK};bool uploaded{},imageSubmitted{},videoSubmitted{},failed{};std::optional<std::string>error;};
 struct Thumb {std::string id;J reference;std::shared_ptr<Asset>asset;std::shared_ptr<const n::LayerMemoryImage>image;std::uint64_t used{};bool wanted{},settled{};};
 struct Import {ArchiveMediaAction action;std::uint64_t serial{};std::vector<ArchiveMediaImportFile>files;std::vector<std::optional<n::NotesImageCompletion>>results;};
 ArchivePreview&preview;n::NativeMediaRequestBroker&broker;n::NativeMediaRequestBroker::Client client;n::Renderer&renderer;n::LayerImageSource&images;ArchiveMediaBindingOptions options;
 std::string mesh{key()+".quad"};bool meshUploaded{},alive{true},visible{},requestsDirty{true},postersDirty{true},metadataDirty{};double time{};unsigned depth{};std::uint64_t sourceRevision{},collectionRevision{},used{},importSerial{1},galleryGeneration{};double scroll{-1};std::size_t selectedIndex{};
 std::optional<std::string>selectedID;std::shared_ptr<Asset>selected;std::vector<std::shared_ptr<Asset>>assets;std::vector<Thumb>thumbs;std::map<std::string,J,std::less<>>metadata,posters;std::map<std::string,std::uint64_t,std::less<>>loading;
 std::optional<Import>import;std::string boundTexture,boundDocument;unsigned boundWidth{},boundHeight{};std::size_t boundIndex{};bool bound{},publishedPlaying{};double publishedTime{};std::optional<std::string>publishedError;
 Impl(ArchivePreview&p,n::NativeMediaRequestBroker&b,n::NativeMediaRequestBroker::Client c,n::Renderer&r,n::LayerImageSource&i,ArchiveMediaBindingOptions o):preview(p),broker(b),client(c),renderer(r),images(i),options(std::move(o)){need(client&&renderer.stats().initialized&&options.resolve&&options.errorText,"Archive media requires existing root providers and explicit access/error contracts");assets.reserve(32);thumbs.reserve(18);}
 struct Event {Impl&i;Event(Impl&v,double t):i(v){need(std::isfinite(t),"Archive media requires a finite owner clock");if(!i.depth)i.time=std::max(i.time,t);++i.depth;}~Event(){--i.depth;}};
 std::shared_ptr<Asset>asset(const J&reference){need(assets.size()<32,"Publish/collect Archive media before further replacements");auto a=std::make_shared<Asset>();a->reference=reference;a->kind=kind(reference);try{a->access=options.resolve(reference);need(ehud::data::validWindowsFilePath(path(a->access.path)),"Archive media access must use a validated absolute Windows locator");}catch(...){a->failed=true;a->error=options.errorText(E_ACCESSDENIED);}assets.push_back(a);return a;}
 Thumb*thumb(std::string_view id){for(auto&t:thumbs)if(t.id==id)return &t;return nullptr;}
 bool wanted(std::string_view id)const{for(const auto&t:thumbs)if(t.id==id&&t.wanted)return true;return false;}
 void requestThumbnail(std::string id){if(!options.loadThumbnail||loading.contains(id))return;need(loading.size()<6,"Archive lazy thumbnail requests exceed six visible rows");const auto epoch=galleryGeneration;loading[id]=epoch;const auto weak=weak_from_this();options.loadThumbnail(id,[weak,id,epoch](std::optional<J>result){if(auto self=weak.lock();self&&self->alive){const auto pending=self->loading.find(id);if(pending==self->loading.end()||pending->second!=epoch)return;self->loading.erase(pending);if(!self->visible||self->selectedID||self->galleryGeneration!=epoch||!self->wanted(id))return;if(result){m::validateArchiveMedia(*result);self->metadata[id]=std::move(*result);self->metadataDirty=true;}if(self->options.changed)self->options.changed();}});}
 void submit(){if(!requestsDirty)return;std::vector<n::NotesImagePlaybackRequest>still;std::vector<n::NotesVideoRequest>movie;still.reserve(7);movie.reserve(1);
  const auto add=[&](const std::shared_ptr<Asset>&a,int dimension,bool gallery){if(!a||a->failed)return;auto locator=path(a->access.path);n::NotesImageRequest image{a->key,std::move(locator),1,dimension,gallery||a->kind==m::NotesMediaKind::image,a->access.lease,false,a->kind==m::NotesMediaKind::video};still.push_back({image,gallery||a->kind==m::NotesMediaKind::video?m::NotesMediaKind::image:a->kind});if(!gallery&&a->kind==m::NotesMediaKind::video&&broker.hasVideoPlayback())movie.push_back({a->key,image.path,1,512,duration(a->reference),a->access.lease,true});};
  if(visible){add(selected,512,false);for(auto&t:thumbs)if(t.wanted&&!t.settled)add(t.asset,256,true);}
  broker.setImages(client,1,still,time,!visible);for(const auto&r:still)for(auto&a:assets)if(a->key==r.image.key)a->imageSubmitted=true;
  broker.setVideos(client,1,movie,time,!visible);for(const auto&r:movie)for(auto&a:assets)if(a->key==r.key)a->videoSubmitted=true;requestsDirty=false;
  // Static gallery snapshots no longer need a bookmark/file/decoder lease once
  // they have entered the shared immutable image cache.
  for(auto&t:thumbs)if(t.settled&&t.asset->imageSubmitted){const auto*r=broker.findImage(client,t.asset->key);if(r&&!r->visible&&broker.retireImage(client,t.asset->key)){t.asset->imageSubmitted=false;t.asset->access.lease.reset();}}
 }
 void evict(){while(std::count_if(thumbs.begin(),thumbs.end(),[](const auto&t){return t.settled;})>12){auto it=thumbs.end();for(auto p=thumbs.begin();p!=thumbs.end();++p)if(p->settled&&!p->wanted&&(it==thumbs.end()||p->used<it->used))it=p;need(it!=thumbs.end(),"Archive thumbnail cache bound exceeded by visible rows");images.retire(it->asset->key);it=thumbs.erase(it);postersDirty=true;}}
 bool sync(){bool changed{};const auto&state=preview.state();const bool show=preview.mediaVisible();const std::string*id=state.selected()?&state.selected()->id:nullptr;const bool differentID=bool(selectedID)!=bool(id)||(id&&*selectedID!=*id);const auto index=preview.mediaIndex();const bool content=sourceRevision!=state.revision()||differentID||selectedIndex!=index;
  if(visible!=show){visible=show;requestsDirty=true;changed=true;if(show&&selected&&!selected->failed){selected->error.reset();selected->observedError=S_OK;}if(!show){cancelImport();loading.clear();metadata.clear();for(auto&t:thumbs)if(t.asset)images.retire(t.asset->key);thumbs.clear();posters.clear();postersDirty=true;collectionRevision=0;}}
  if(content){sourceRevision=state.revision();bool replace=differentID||selectedIndex!=index;const J*reference=state.selected()&&index<state.selected()->media.size()?&state.selected()->media[index]:nullptr;if(!replace)replace=bool(reference)!=bool(selected)||(reference&&selected->reference!=*reference);
   if(replace){if(differentID)collectionRevision=0;selectedID=id?std::optional(*id):std::nullopt;selectedIndex=index;selected=reference?asset(*reference):nullptr;requestsDirty=true;bound=false;changed=true;}}
  const bool gallery=visible&&!id;if(gallery&&(metadataDirty||collectionRevision!=state.collectionRevision()||scroll!=state.galleryScroll())){if(collectionRevision!=state.collectionRevision()||scroll!=state.galleryScroll()){++galleryGeneration;loading.clear();}metadataDirty=false;collectionRevision=state.collectionRevision();scroll=state.galleryScroll();for(auto&t:thumbs)t.wanted=false;auto rows=state.galleryRows();std::erase_if(rows,[&](const auto&row){return !state.entries()[row.index].mediaCount;});std::sort(rows.begin(),rows.end(),[](const auto&a,const auto&b){return a.hit.height!=b.hit.height?a.hit.height>b.hit.height:a.id<b.id;});if(rows.size()>6)rows.resize(6);std::set<std::string,std::less<>>pendingWanted;for(const auto&r:rows)pendingWanted.emplace(r.id);for(auto it=loading.begin();it!=loading.end();)if(!pendingWanted.contains(it->first))it=loading.erase(it);else ++it;for(auto it=metadata.begin();it!=metadata.end();)if(!pendingWanted.contains(it->first))it=metadata.erase(it);else ++it;
   std::erase_if(thumbs,[&](const auto&t){return !pendingWanted.contains(t.id)&&!t.settled;});
   for(const auto&r:rows){const auto&e=state.entries()[r.index];auto*t=thumb(e.id);if(!t){need(thumbs.size()<18,"Archive thumbnail metadata exceeds twelve posters plus six requests");thumbs.push_back({e.id});t=&thumbs.back();}t->wanted=true;t->used=++used;const J*reference=e.thumbnail?&*e.thumbnail:metadata.contains(e.id)?&metadata.at(e.id):nullptr;if(reference){if(!t->asset||t->reference!=*reference){if(t->image)images.retire(t->asset->key);t->reference=*reference;t->asset=asset(*reference);t->image.reset();t->settled=t->asset->failed;postersDirty=true;}}else requestThumbnail(e.id);
   }requestsDirty=true;postersDirty=true;changed=true;evict();
  }else if(!gallery){for(auto&t:thumbs)if(t.wanted){t.wanted=false;requestsDirty=true;}loading.clear();}
  submit();return changed;
 }
 bool cancelImport(){if(!import)return false;broker.cancelInspections(client,++importSerial);import.reset();return true;}
 bool inspect(){if(!import)return false;auto batch=broker.drainInspections(client,import->serial);if(batch.empty())return false;for(auto&result:batch){for(std::size_t k=0;k<import->files.size();++k)if(result.key=="import."+std::to_string(import->serial)+"."+std::to_string(k))import->results[k]=std::move(result);}if(std::any_of(import->results.begin(),import->results.end(),[](const auto&r){return !r;}))return false;
  auto complete=std::move(*import);import.reset();broker.cancelInspections(client,++importSerial);std::vector<J>references;std::optional<std::string>error;for(std::size_t k=0;k<complete.files.size();++k){const auto&r=*complete.results[k];try{if(FAILED(r.result)||!r.info)throw std::runtime_error("Media validation failed");const auto&i=*r.info;const auto type=i.kind==m::NotesMediaKind::image?"image":i.kind==m::NotesMediaKind::gif?"gif":"video";auto encoded=ehud::data::makeWindowsMediaReference(complete.files[k].path,complete.files[k].displayName,static_cast<int>(i.pixelWidth),static_cast<int>(i.pixelHeight),type,i.kind==m::NotesMediaKind::image?std::nullopt:std::optional(i.duration),static_cast<int>(i.frameCount));references.push_back(J::parse(encoded));}catch(...){error=options.errorText(FAILED(r.result)?r.result:E_INVALIDARG);}}
  return preview.receiveMedia(complete.action.documentID,complete.action.generation,std::move(references),std::move(error),time);
 }
 bool refresh(){bool changed=inspect();for(auto&t:thumbs)if(t.wanted&&t.asset&&!t.image&&!t.asset->failed){const auto*record=broker.findImage(client,t.asset->key);if(record&&record->frame){const auto&f=*record->frame;t.image=images.publish(t.asset->key,record->frameRevision,f.width,f.height,f.straightRGBA);t.asset->observedFrame=record->frameRevision;t.settled=true;postersDirty=requestsDirty=changed=true;}else if(record&&FAILED(record->error)){t.asset->failed=true;t.settled=true;requestsDirty=true;}}
  evict();bool playing{};double progress{};const std::optional<std::string>emptyError;const std::optional<std::string>*error=&emptyError;std::string_view texture;unsigned width{},height{};
  if(selected){auto&a=*selected;error=&a.error;if(const auto*record=broker.findImage(client,a.key)){if(record->frame){a.frame=record->frame;a.observedFrame=record->frameRevision;if(a.kind==m::NotesMediaKind::video&&a.appliedPoster!=record->frameRevision){if(broker.setVideoPoster(client,a.key,1,record->frameRevision,record->frame.get(),record->error))a.appliedPoster=record->frameRevision;}}if(FAILED(record->error)&&a.kind!=m::NotesMediaKind::video&&a.observedError!=record->error){a.error=options.errorText(record->error);a.observedError=record->error;}if(a.kind==m::NotesMediaKind::gif)playing=record->state==m::NotesMediaState::playing;
    if(!visible&&!record->frame){a.frame.reset();}}
   if(a.kind==m::NotesMediaKind::video){if(const auto*v=broker.findVideo(client,a.key)){texture=v->textureID;width=v->width;height=v->height;playing=v->state==m::NotesMediaState::playing;progress=v->pendingSeek.value_or(v->currentTime);if(FAILED(v->error)&&a.observedError!=v->error){a.error=options.errorText(v->error);a.observedError=v->error;}}else if(!broker.hasVideoPlayback()&&a.observedError!=E_NOTIMPL){a.error=options.errorText(E_NOTIMPL);a.observedError=E_NOTIMPL;}}
   else if(a.frame){if(!a.uploaded||a.uploadedFrame!=a.observedFrame){renderer.setTexture(a.key,a.observedFrame,{a.frame->width,a.frame->height,a.frame->straightRGBA});a.uploadedFrame=a.observedFrame;a.uploaded=true;changed=true;}texture=a.key;width=a.frame->width;height=a.frame->height;}
   if(a.kind==m::NotesMediaKind::video&&texture.empty()&&a.frame){if(!a.uploaded||a.uploadedFrame!=a.observedFrame){renderer.setTexture(a.key,a.observedFrame,{a.frame->width,a.frame->height,a.frame->straightRGBA});a.uploadedFrame=a.observedFrame;a.uploaded=true;}texture=a.key;width=a.frame->width;height=a.frame->height;}
  }
  const bool postersChanged=postersDirty;if(postersDirty){posters.clear();for(const auto&t:thumbs)if(t.wanted&&t.image)posters[t.id]=J::Object{{"memoryImage",t.asset->key},{"revision",double(t.image->revision())}};postersDirty=false;changed=true;}
  if(changed||playing!=publishedPlaying||progress!=publishedTime||*error!=publishedError){if(postersChanged)preview.setMediaPresentation(selectedIndex,playing,progress,posters,*error,time);else preview.setMediaPlayback(selectedIndex,playing,progress,*error,time);publishedPlaying=playing;publishedTime=progress;publishedError=*error;changed=true;}
  if(selectedID&&(!bound||boundDocument!=*selectedID||boundIndex!=selectedIndex||boundTexture!=texture||boundWidth!=width||boundHeight!=height)){
   std::optional<n::DrawObject>draw;if(!texture.empty()&&width&&height){if(!meshUploaded){renderer.setMesh(mesh,1,{vertices,indices});meshUploaded=true;}const auto r=fitted(width,height);n::DrawObject d;d.sourceID=selected->key+".draw";d.meshID=mesh;d.textureID=texture;d.world=Matrix::translation(r.x,r.y)*Matrix::scale(r.width,r.height);d.masks.push_back({Matrix{},m::ArchiveState::mediaRect()});draw=std::move(d);}preview.setMediaDraw(*selectedID,selectedIndex,std::move(draw),time);bound=true;boundDocument=*selectedID;boundIndex=selectedIndex;boundTexture=texture;boundWidth=width;boundHeight=height;changed=true;
  }submit();return changed;
 }
};
ArchiveMediaBinding::ArchiveMediaBinding(ArchivePreview&p,n::NativeMediaRequestBroker&b,n::NativeMediaRequestBroker::Client c,n::Renderer&r,n::LayerImageSource&i,ArchiveMediaBindingOptions o):impl_(std::make_shared<Impl>(p,b,c,r,i,std::move(o))){}
ArchiveMediaBinding::~ArchiveMediaBinding(){auto i=impl_;i->alive=false;try{(void)releaseResources(i->time);}catch(...){} }
bool ArchiveMediaBinding::sync(double t){auto i=impl_;Impl::Event event(*i,t);return i->sync();}
bool ArchiveMediaBinding::refresh(double t){auto i=impl_;Impl::Event event(*i,t);return i->refresh();}
bool ArchiveMediaBinding::action(const ArchiveMediaAction&a,double t){auto i=impl_;Impl::Event event(*i,t);if(!i->preview.mediaRequestCurrent(a.documentID,a.generation)||!i->visible||!i->selected||!i->selectedID||a.documentID!=*i->selectedID||a.mediaIndex!=i->selectedIndex)return false;bool result{};if(a.kind==ArchiveMediaAction::Kind::playPause)result=i->selected->kind==m::NotesMediaKind::video?i->broker.toggleVideo(i->client,i->selected->key,i->time):i->selected->kind==m::NotesMediaKind::gif?i->broker.toggleImage(i->client,i->selected->key,i->time):false;else if(a.kind==ArchiveMediaAction::Kind::seek&&i->selected->kind==m::NotesMediaKind::video)result=i->broker.seekVideo(i->client,i->selected->key,a.seconds);if(result)i->refresh();return result;}
bool ArchiveMediaBinding::beginImport(const ArchiveMediaAction&a,std::span<const ArchiveMediaImportFile>files,double t){auto i=impl_;Impl::Event event(*i,t);if(!i->preview.mediaRequestCurrent(a.documentID,a.generation)||(a.kind!=ArchiveMediaAction::Kind::chooseLocal&&a.kind!=ArchiveMediaAction::Kind::useShelf)||!a.remaining||files.empty())return false;const auto count=std::min({std::size_t{16},a.remaining,files.size()});Impl::Import next;next.action=a;next.serial=i->importSerial+1;next.files.assign(files.begin(),files.begin()+count);next.results.resize(count);std::vector<n::NotesImageRequest>requests;requests.reserve(count);for(std::size_t k=0;k<count;++k){const auto&f=next.files[k];need(ehud::data::validWindowsFilePath(f.path)&&!f.displayName.empty()&&f.displayName.size()<=4096&&J::validUtf8(f.displayName),"Invalid explicit Archive import file");requests.push_back({"import."+std::to_string(next.serial)+"."+std::to_string(k),f.path,1,64,false,f.accessLease,true});}i->broker.setInspections(i->client,next.serial,requests);i->importSerial=next.serial;i->import=std::move(next);return true;}
bool ArchiveMediaBinding::cancelImport(){auto i=impl_;return i->cancelImport();}
bool ArchiveMediaBinding::collectRetired(){auto&i=*impl_;bool okay=true;for(auto it=i.assets.begin();it!=i.assets.end();){auto&a=**it;if(it->use_count()>1){++it;continue;}if(a.uploaded&&!i.renderer.removeTexture(a.key)){okay=false;++it;continue;}a.uploaded=false;if(a.imageSubmitted&&!i.broker.retireImage(i.client,a.key)){okay=false;++it;continue;}a.imageSubmitted=false;if(a.videoSubmitted&&!i.broker.retireVideo(i.client,a.key)){okay=false;++it;continue;}it=i.assets.erase(it);}return okay;}
bool ArchiveMediaBinding::releaseResources(double t){auto i=impl_;Impl::Event event(*i,t);i->cancelImport();i->visible=false;i->selected.reset();i->selectedID.reset();for(auto&t:i->thumbs)if(t.asset)i->images.retire(t.asset->key);i->thumbs.clear();i->posters.clear();i->broker.hideImages(i->client,i->time);i->broker.hideVideos(i->client,i->time);bool okay=collectRetired();if(i->meshUploaded){if(i->renderer.removeMesh(i->mesh))i->meshUploaded=false;else okay=false;}return okay;}
std::size_t ArchiveMediaBinding::cachedThumbnails()const noexcept{return std::count_if(impl_->thumbs.begin(),impl_->thumbs.end(),[](const auto&t){return t.settled;});}
} // namespace endfield::tools
#endif
