#include "tools/archive_preview.hpp"
#ifdef _WIN32
#include "native/archive_editor_text.hpp"
#include "native/archive_text_rules.hpp"
#include "native/module_scene.hpp"
#include "native/module_registration.hpp"
#include "core/source_camera.hpp"
#include <algorithm>
#include <atomic>
#include <cmath>
#include <limits>
#include <stdexcept>

namespace endfield::tools {
namespace {
namespace gpu=native;namespace m=modules;namespace text=core::text;namespace rich=core::notes;
using Matrix=core::Matrix4;using J=ehud::data::Json;using Rect=core::Rect;using Point=core::Point;
void need(bool value,const char*message){if(!value)throw std::invalid_argument(message);}
bool contains(Rect r,Point p){return p.x>=r.x&&p.y>=r.y&&p.x<r.x+r.width&&p.y<r.y+r.height;}
J blank(){return J::Object{{"bounds",J::Array{0,0,400,440}},{"position",J::Array{0,0}},{"anchorPoint",J::Array{0,0}},{"children",J::Array{}}};}
J rgba(std::array<double,4>c){return J::Object{{"sRGB",J::Array{c[0],c[1],c[2],c[3]}}};}
UINT_PTR nextGeneration(){static std::atomic<UINT_PTR>value{1};const auto result=value.fetch_add(1);need(result&&result!=std::numeric_limits<UINT_PTR>::max(),"Archive editor generation exhausted");return result;}
enum class FieldKind:unsigned {title,date,body,category};
const char*fieldName(FieldKind kind){switch(kind){case FieldKind::title:return "title";case FieldKind::date:return "date";case FieldKind::body:return "body";case FieldKind::category:return "category";}return "";}
gpu::ArchiveEditorTextKind clampKind(FieldKind k){return k==FieldKind::title?gpu::ArchiveEditorTextKind::title:k==FieldKind::category?gpu::ArchiveEditorTextKind::category:gpu::ArchiveEditorTextKind::body;}
J backing(Rect size,FieldKind kind,const ArchivePreviewOptions&o,Point inset,const rich::TextStyle*typing=nullptr){auto root=blank();J box=J::Object{{"id","archive.editor.background"},{"kind","layer"},{"bounds",J::Array{0,0,size.width,size.height}},{"position",J::Array{0,0}},{"anchorPoint",J::Array{0,0}},{"children",J::Array{}},{"backgroundColor",rgba({o.view.appearance.dark?.065:.94,o.view.appearance.dark?.065:.94,o.view.appearance.dark?.065:.94,1})}};
 if(kind==FieldKind::category){const auto gray=o.view.appearance.dark?.12:.92;box["backgroundColor"]=rgba({gray,gray,gray,1});box["borderWidth"]=1;box["borderColor"]=rgba(o.view.appearance.accent);box["cornerRadius"]=3;}
 const auto placeholder=kind==FieldKind::title?o.view.strings.title:kind==FieldKind::body?o.view.strings.content:kind==FieldKind::category?o.categoryNamePlaceholder:std::string{};
 J::Array children;children.push_back(std::move(box));if(!placeholder.empty()){
 const double font=typing?typing->fontSize:kind==FieldKind::title?17:kind==FieldKind::date?10:12;const double gray=o.view.appearance.dark?.55:.45;const auto family=typing&&typing->fontName?*typing->fontName:std::string(".AppleSystemUIFont");
 children.emplace_back(J::Object{{"id","archive.editor.placeholder"},{"kind","text"},{"bounds",J::Array{0,0,std::max(0.,size.width-inset.x*2),std::max(0.,size.height-inset.y*2)}},{"position",J::Array{inset.x,inset.y}},{"anchorPoint",J::Array{0,0}},{"children",J::Array{}},{"text",J::Object{{"string",placeholder},{"fontSize",font},{"font",J::Object{{"familyName",family},{"postScriptName",family},{"pointSize",font}}},{"foregroundColor",rgba({gray,gray,gray,1})},{"wrapped",true},{"alignment","left"},{"truncation","end"}}}});}
 root["children"]=std::move(children);return root;
}
gpu::ProjectedEditorStyle fieldStyle(Rect rect,FieldKind kind,const ArchivePreviewOptions&o){gpu::ProjectedEditorStyle s;s.width=rect.width;s.height=rect.height;s.fontSize=kind==FieldKind::title?17:kind==FieldKind::date?10:12;s.fontFamily=".AppleSystemUIFont";s.fontFace=".AppleSystemUIFont";const auto ink=o.view.appearance.dark?1.:0.;s.textColor=s.caretColor=s.compositionColor={ink,ink,ink,1};s.naturalParagraphSpacingOne=true;s.wrapped=kind==FieldKind::body;
 // The plain-only single-line flag currently cannot coexist with Archive's
 // natural +1 spacing/rich title. Do not silently discard either source input.
 if(kind==FieldKind::category){s.naturalParagraphSpacingOne=false;s.sourceSingleLineField=true;s.cornerRadius=3;}return s;
}
std::optional<rich::RichText>initialRich(std::u16string_view value,std::optional<rich::RichText>payload,const rich::TextStyle&style){if(payload)return payload;if(value.empty())return {};rich::RichText result;if(style!=rich::TextStyle{})result.runs.push_back({0,static_cast<std::uint32_t>(value.size()),style,{}});if(result.runs.empty())return {};return result;}
void setTyping(rich::RichDocument&document,const rich::TextStyle&style){if(style.fontName)document.applyFormat({rich::FormatKind::font,*style.fontName});document.applyFormat({.kind=rich::FormatKind::size,.fontSize=style.fontSize});if(style.color)document.applyFormat({.kind=rich::FormatKind::color,.color=*style.color});for(const auto[k,on]:{std::pair{rich::FormatKind::bold,style.bold},std::pair{rich::FormatKind::italic,style.italic},std::pair{rich::FormatKind::underline,style.underline},std::pair{rich::FormatKind::strikethrough,style.strikethrough}}){const auto st=document.typingStyle();const bool current=k==rich::FormatKind::bold?st.bold:k==rich::FormatKind::italic?st.italic:k==rich::FormatKind::underline?st.underline:st.strikethrough;if(current!=on)document.applyFormat({.kind=k});}}
std::array<double,4>inkColor(const rich::TextStyle&s,bool dark){return s.color?std::array<double,4>{s.color->red,s.color->green,s.color->blue,s.color->alpha}:std::array<double,4>{dark?1.:0.,dark?1.:0.,dark?1.:0.,1};}
void bindImage(J&node,std::string_view id,const J&contents){if(node["id"]==J(std::string(id))){node.erase("requiredSourceImage");node["contents"]=contents;}if(node["children"].isArray()){auto children=node["children"].array();for(auto&child:children)bindImage(child,id,contents);node["children"]=std::move(children);}}
m::ArchiveArtwork controlsArtwork(const m::NotesControls&controls,const J&wheel){m::ArchiveArtwork art;art.root=controls.artwork();for(const auto&a:controls.actions())art.actions.push_back({a.id,a.label,a.rect,a.enabled,a.selected});for(const auto&f:controls.feedback()){const auto found=std::find_if(controls.actions().begin(),controls.actions().end(),[&](const auto&a){return a.id==f.actionID;});need(found!=controls.actions().end(),"Missing original formatting action");art.feedback.push_back({f.actionID,f.tintLayerID,f.rimLayerID,found->rect,{},true,true,found->enabled});}for(const auto&dependency:controls.images()){need(dependency.sourceResource=="source-generated:NotesColorWheelView.wheel"&&!wheel.isNull(),"Original source color wheel is required for Archive color formatting");bindImage(art.root,dependency.layerID,wheel);}return art;}
}

struct ArchivePreview::Impl {
 struct Field {
  FieldKind kind;Rect rect;std::shared_ptr<rich::RichDocument>richDocument;std::shared_ptr<text::Buffer>plainDocument;gpu::LayerScene back,glyphs;std::unique_ptr<gpu::NativeProjectedEditor>editor;UINT_PTR generation{nextGeneration()};std::uint64_t capturedRevision{};bool forceCapture{},published{};
  std::array<gpu::LayerPlacement,4>glyphPlacement;std::array<gpu::PlaneMask,2>masks;std::array<gpu::LayerPlacement,2>backPlacement;std::array<Matrix,4>localGlyphs;std::array<Matrix,2>localBack;std::array<float,4>leafOpacity{};
  Field(HWND window,gpu::LayerRasterizer&r,FieldKind k,Rect bounds,std::string_view value,const std::optional<rich::RichText>&payload,const rich::TextStyle&typing,const ArchivePreviewOptions&o,std::shared_ptr<rich::RichDocument>retainedRich={},std::shared_ptr<text::Buffer>retainedPlain={}):kind(k),rect(bounds),richDocument(std::move(retainedRich)),plainDocument(std::move(retainedPlain)),back(r),glyphs(r){auto content=m::archiveUTF16(value);need(content.size()<=o.editorCapacity,"Stored Archive field exceeds the current native editor leaf; full data is preserved");
   if(!richDocument&&!plainDocument){if(kind==FieldKind::title||kind==FieldKind::body){richDocument=std::make_shared<rich::RichDocument>(content,initialRich(content,payload,typing),o.editorCapacity);setTyping(*richDocument,typing);}else plainDocument=std::make_shared<text::Buffer>(std::move(content),o.editorCapacity);}
   auto style=fieldStyle(bounds,kind,o);if(richDocument)editor=std::make_unique<gpu::NativeProjectedEditor>(window,*richDocument,glyphs,style,o.raster,gpu::PlainEditorFixtureCapacity{o.editorCapacity},o.textMessage,generation);else editor=std::make_unique<gpu::NativeProjectedEditor>(window,*plainDocument,glyphs,style,o.raster,gpu::PlainEditorFixtureCapacity{o.editorCapacity},o.textMessage,generation);loadBacking(o);capturedRevision=document().revision();
  }
  void loadBacking(const ArchivePreviewOptions&o){const auto typing=richDocument?std::optional(richDocument->typingStyle()):std::nullopt;const auto inset=editor?editor->layout().painted()->contentInset():Point{};back.load(backing(rect,kind,o,inset,typing?&*typing:nullptr),o.raster);need(back.report().unsupported.empty()&&!back.draws().empty()&&back.draws().size()<=2,"Unsupported Archive editor backing");const auto draws=back.prepareDraws();for(std::size_t n=0;n<draws.size();++n)localBack[n]=draws[n].world;}
  text::Document&document(){return richDocument?static_cast<text::Document&>(*richDocument):static_cast<text::Document&>(*plainDocument);}
  bool release(gpu::Renderer&r){return back.releaseResources(r)&&glyphs.releaseResources(r);}
 };
 struct Fields {std::array<std::unique_ptr<Field>,3>values;std::string id;double reveal{},retire{};bool fading{};};
 struct Menu {
  enum class Kind {category,deleteDocument,deleteCategory,format,mediaSource,shelf};
  Kind kind;Point origin;gpu::NativeArchiveScene scene;std::unique_ptr<m::NotesControls>controls;std::optional<m::NotesControlsInput>controlInput;std::unique_ptr<Field>categoryField;std::optional<std::string>target;bool moving{},editingName{},closing{},published{};double scroll{},start{},closeAt{};std::size_t keyboardIndex{};std::uint64_t revision{1};
  Menu(Kind k,Point p,gpu::LayerRasterizer&r,const ArchivePreviewOptions&o,double t):kind(k),origin(p),scene(r,o.raster),start(t){}
 };
 HWND window;gpu::LayerRasterizer&raster;ITfThreadMgr*manager;TfClientId client;ArchivePreviewOptions options;m::ArchiveState&state;gpu::NativeArchiveScene scene;gpu::LayerScene geometry;gpu::NativeModuleSurface surface;gpu::NativeModuleRegistration registration{"archive.registration"};
 app::ClientMetrics metrics;core::Projection projection;std::optional<gpu::ModuleSurfacePose>pose;std::unique_ptr<Fields>fields;std::vector<std::unique_ptr<Fields>>retiredFields;std::vector<std::unique_ptr<Field>>retiredViewportFields;std::unique_ptr<Menu>menu;std::vector<std::unique_ptr<Menu>>retiredMenus;std::vector<gpu::LayerCompositionEntry>composed;
 bool active{},requested{},input{},focused{},overlayVisible{true},reduceMotion{},pressed{},dragging{},seeking{},wheelDrag{},alive{true},contentDirty{true},pendingDeactivate{};double time{};unsigned depth{};std::optional<Point>pointerPoint;std::optional<std::string>focusedField,pendingAction,displayedID;std::optional<std::optional<std::string>>pendingFocus;std::optional<double>scrollGrab;std::uint64_t stateRevision{},viewRevision{1},mediaGeneration{1},registrationUploadedRevision{};gpu::Renderer*registrationRenderer{};UINT_PTR mediaRoute{nextGeneration()};bool mediaPosted{};std::optional<ArchiveMediaAction>mediaAction;
 std::optional<gpu::DrawObject>mediaDraw;std::string mediaDrawDocument;std::size_t mediaDrawIndex{};
 struct Event {Impl&i;Event(Impl&v,double t):i(v){need(std::isfinite(t),"Archive needs finite owner time");if(!i.depth)i.time=std::max(i.time,t);++i.depth;}~Event(){--i.depth;}};
 Impl(m::ArchiveState&s,HWND w,gpu::LayerRasterizer&r,ITfThreadMgr*tm,TfClientId tc,ArchivePreviewOptions value):window(w),raster(r),manager(tm),client(tc),options(std::move(value)),state(s),scene(r,options.raster),geometry(r),surface(prepareGeometry(),core::Module::archive){need(window&&IsWindow(window),"Archive requires caller HWND");need((manager==nullptr)==(client==TF_CLIENTID_NULL),"Borrowed TSF manager/client must be supplied together");need(options.newID&&options.foundationNow&&options.parseLocalDate&&options.view.dateString&&options.view.categoryCaptionWidth&&options.view.appearance.systemOrange,"Archive requires explicit ID/date/font/error-color contracts");need(options.editorCapacity>0&&options.editorCapacity<=65536&&options.textMessage>=WM_APP&&options.textMessage<=0xbfff&&options.mediaMessage>=WM_APP&&options.mediaMessage<=0xbfff&&options.mediaMessage!=options.textMessage,"Invalid Archive editor capacity or message");retiredFields.reserve(3);retiredViewportFields.reserve(3);retiredMenus.reserve(3);composed.reserve(64);}
 gpu::LayerScene&prepareGeometry(){geometry.load(blank(),options.raster);return geometry;}
 std::optional<Point>local(Point p,bool gated=true)const{return (!gated||input)&&pose?projection.unproject({p.x*metrics.scale,p.y*metrics.scale}):std::nullopt;}
 double dateNow(){const auto result=options.foundationNow();need(std::isfinite(result),"Archive requires finite Foundation date");return result;}
 Field*field(std::string_view name){if(name=="category")return menu?menu->categoryField.get():nullptr;if(fields)for(auto&f:fields->values)if(f&&fieldName(f->kind)==name)return f.get();return nullptr;}
 Field*focusedEditor(){return focusedField?field(*focusedField):nullptr;}
 bool focusField(std::optional<std::string>name){if(focusedField==name)return true;auto*old=focusedEditor();if(old&&manager){const auto hr=old->editor->focus(false);if(hr==TS_E_NOLOCK){pendingFocus=name;return false;}need(SUCCEEDED(hr),"Cannot blur Archive editor");if(!alive)return false;}if(name){auto*next=field(*name);if(!next)return false;if(manager&&focused){const auto hr=next->editor->focus(true);if(hr==TS_E_NOLOCK){pendingFocus=name;return false;}need(SUCCEEDED(hr),"Cannot focus Archive editor");if(!alive)return false;}}
  pendingFocus.reset();focusedField=std::move(name);if(focusedField&&*focusedField!="date"&&*focusedField!="category"){options.view.formattingField=focusedField;if(auto*f=focusedEditor();f&&f->richDocument)options.view.formattingColor=inkColor(f->richDocument->selectionStyle(),options.view.appearance.dark);}else if(!menu||menu->kind!=Menu::Kind::format)options.view.formattingField.reset();contentDirty=true;return true;
 }
 bool capture(Field&f,bool force=false){if(f.document().composition())return false;if(f.document().revision()==f.capturedRevision&&!f.forceCapture&&!force)return true;auto clamped=f.kind==FieldKind::date?gpu::ArchiveEditorTextClamp{std::u16string(f.document().text()),{}}:gpu::clampArchiveEditorText(f.document().text(),clampKind(f.kind));if(!clamped.removed.empty()){for(const auto r:clamped.removed)f.document().replace(r,{});f.editor->syncContent();}
  if(f.kind==FieldKind::category){f.capturedRevision=f.document().revision();f.forceCapture=false;return true;}if(!state.selected()||!fields||state.selected()->id!=fields->id)return false;auto entry=*state.selected();const auto value=m::archiveUTF8(f.document().text());if(f.kind==FieldKind::date){const auto parsed=options.parseLocalDate(value);if(!parsed){f.capturedRevision=f.document().revision();f.forceCapture=false;return true;}need(std::isfinite(*parsed),"Invalid parsed Archive date");entry.date=*parsed;}else if(f.kind==FieldKind::title){entry.title=value;entry.titleRichText=f.richDocument->richText();entry.titleStyle=f.richDocument->typingStyle();}else{entry.body=value;entry.bodyRichText=f.richDocument->richText();entry.bodyStyle=f.richDocument->typingStyle();}state.update(std::move(entry),dateNow(),time);f.capturedRevision=f.document().revision();f.forceCapture=false;contentDirty=true;return true;
 }
 void selectionFeedback(){if(auto*f=focusedEditor();f&&f->richDocument){const auto color=inkColor(f->richDocument->selectionStyle(),options.view.appearance.dark);if(options.view.formattingColor!=color){options.view.formattingColor=color;contentDirty=true;}}}
 bool captureAll(){if(fields)for(auto&f:fields->values)if(f&&!capture(*f))return false;if(menu&&menu->categoryField&&!capture(*menu->categoryField))return false;return true;}
 void stopFields(Fields&set){for(auto&f:set.values)if(f&&f->editor){const auto hr=f->editor->stop();need(hr!=TS_E_NOLOCK&&SUCCEEDED(hr),"Archive editor transaction must end before field retirement");f->editor.reset();}}
 bool finish(){if(!captureAll())return false;if(!focusField({}))return false;if(fields)if(auto*f=fields->values[1].get();f&&state.selected()){const auto value=m::archiveUTF16(options.view.dateString(state.selected()->date));if(f->document().text()!=value){f->document().replace({0,static_cast<std::uint32_t>(f->document().text().size())},value);f->capturedRevision=f->document().revision();f->editor->syncContent();}}state.flush();return true;}
 void retireCurrent(bool fading){if(!fields)return;stopFields(*fields);need(retiredFields.size()<3,"Publish retired Archive fields before another replacement");fields->fading=fading&&!reduceMotion;fields->retire=time+(fields->fading?.2:.6);fields->reveal=time;retiredFields.push_back(std::move(fields));focusedField.reset();options.view.formattingField.reset();dragging=false;}
 void installFields(){if(!active||!state.selected()){if(fields&&finish())retireCurrent(active);return;}if(fields&&fields->id==state.selected()->id){const auto rect=state.bodyRect();if(auto*f=fields->values[2].get();f&&f->rect!=rect){
    // Only the painted viewport is replaced; the same rich Document retains
    // selection, undo, runs and draft. Marked/locked input defers this boundary.
    if(f->document().composition())return;need(retiredViewportFields.size()<3,"Publish old Archive viewport resources before replacement");auto next=std::make_unique<Field>(window,raster,f->kind,rect,m::archiveUTF8(f->document().text()),std::nullopt,rich::TextStyle{},options,f->richDocument,f->plainDocument);if(manager)need(SUCCEEDED(next->editor->connect(*manager,client)),"Cannot reconnect Archive body viewport");const auto oldScroll=f->editor->scrollOffset();const auto stopped=f->editor->stop();if(stopped==TS_E_NOLOCK)return;need(SUCCEEDED(stopped),"Cannot resize locked Archive body viewport");f->editor.reset();next->capturedRevision=f->capturedRevision;next->forceCapture=f->forceCapture;next->editor->setScrollOffset(oldScroll);if(manager&&focusedField==std::optional<std::string>{"body"}&&focused)need(SUCCEEDED(next->editor->focus(true)),"Cannot restore Archive body focus");retiredViewportFields.push_back(std::move(fields->values[2]));fields->values[2]=std::move(next);
   }return;}
  if(fields&&!finish())return;const auto entry=*state.selected();auto next=std::make_unique<Fields>();next->id=entry.id;next->reveal=time;for(unsigned n=0;n<3;++n){const auto kind=static_cast<FieldKind>(n);const auto rect=n==0?m::ArchiveState::titleRect():n==1?m::ArchiveState::dateRect():state.bodyRect();const auto value=n==0?entry.title:n==1?options.view.dateString(entry.date):entry.body;const auto payload=n==0?entry.titleRichText:n==2?entry.bodyRichText:std::optional<rich::RichText>{};const auto style=n==0?entry.titleStyle:n==2?entry.bodyStyle:rich::TextStyle{.fontSize=10};
   if(m::archiveUTF16(value).size()>options.editorCapacity){options.view.statusMessage="This document exceeds the current native editor viewport limit. Its full text is preserved.";contentDirty=true;continue;}next->values[n]=std::make_unique<Field>(window,raster,kind,rect,value,payload,style,options);if(manager)need(SUCCEEDED(next->values[n]->editor->connect(*manager,client)),"Cannot connect Archive field to shared text manager");if(!alive)return;}
  retireCurrent(true);fields=std::move(next);++mediaGeneration;mediaAction.reset();options.view.mediaIndex=0;contentDirty=true;
 }
 void refresh(){installFields();if(stateRevision==state.revision()&&!contentDirty)return;const auto selectedID=state.selected()?std::optional(state.selected()->id):std::nullopt;const bool changedSelection=stateRevision&&displayedID!=selectedID;auto prepared=options.view;
  // Cache one full-width progress leaf, then shrink its local GPU transform.
  // Progress events never recreate the entire source canvas or editor artwork.
  if(state.selected()&&!state.selected()->media.empty()){const auto&ref=state.selected()->media[prepared.mediaIndex];prepared.mediaTime=ref["duration"].isNumber()?ref["duration"].number():1.;}
  auto art=m::prepareArchiveArtwork(state,prepared);scene.syncContent(std::move(art),++viewRevision,time,changedSelection,reduceMotion);
  if(selectedID&&mediaDrawDocument==*selectedID&&mediaDrawIndex==options.view.mediaIndex)scene.setMediaDraw(mediaDraw);
  double fraction{};if(state.selected()&&!state.selected()->media.empty()){const auto&ref=state.selected()->media[options.view.mediaIndex];fraction=std::clamp(options.view.mediaTime/std::max(.01,ref["duration"].isNumber()?ref["duration"].number():1.),0.,1.);}scene.setMediaProgress(fraction);stateRevision=state.revision();displayedID=selectedID;contentDirty=false;}
 void poseField(Field&f,float alpha,bool current){if(!pose)return;const auto world=pose->contentWorld*Matrix::translation(f.rect.x,f.rect.y);const auto camera=gpu::layerViewportProjection(metrics.pixelWidth,metrics.pixelHeight)*Matrix::scale(metrics.scale,metrics.scale);bool nativePose{};if(f.editor){f.editor->syncContent();nativePose=f.editor->setPose({world,camera,metrics.pixelWidth,metrics.pixelHeight,1,current&&pose->opacity>0,focused&&input&&focusedField&&*focusedField==fieldName(f.kind),true});}f.masks={gpu::PlaneMask{core::source::inverseSourceMatrix(world),{0,0,f.rect.width,f.rect.height},f.kind==FieldKind::category?3.:0.},pose->hostClip};
  const auto draws=f.glyphs.prepareDraws();need(draws.size()==4,"Archive editor must retain the shared four leaves");const auto inverse=core::source::inverseSourceMatrix(world);for(std::size_t n=0;n<4;++n){if(nativePose){f.localGlyphs[n]=inverse*draws[n].world;f.leafOpacity[n]=draws[n].opacity;}f.glyphPlacement[n]={n,world*f.localGlyphs[n],alpha*f.leafOpacity[n],f.masks};}f.glyphs.setPlacements(f.glyphPlacement);f.glyphs.setGroupShutter(pose->shutter);
  f.backPlacement={gpu::LayerPlacement{0,world*f.localBack[0],alpha,f.masks},gpu::LayerPlacement{1,world*f.localBack[1],f.document().text().empty()?alpha:0,f.masks}};f.back.setPlacements({f.backPlacement.data(),f.back.draws().size()});f.back.setGroupShutter(pose->shutter);
 }
 void poseFields(){if(!pose)return;if(fields){const auto fade=reduceMotion?1.:std::clamp((time-fields->reveal)/.18,0.,1.);for(auto&f:fields->values)if(f)poseField(*f,pose->opacity*static_cast<float>(fade),true);}for(auto&set:retiredFields){const auto fade=set->fading?1-std::clamp((time-set->reveal)/.18,0.,1.):1.;for(auto&f:set->values)if(f)poseField(*f,pose->opacity*static_cast<float>(fade),false);}}
 m::ArchiveArtwork menuArtwork(Menu&v){if(v.kind==Menu::Kind::category)return m::prepareArchiveMenu({m::ArchiveMenuKind::category,options.view.appearance,options.view.strings,state.categories(),v.scroll,v.editingName});if(v.kind==Menu::Kind::deleteDocument||v.kind==Menu::Kind::deleteCategory)return m::prepareArchiveMenu({v.kind==Menu::Kind::deleteDocument?m::ArchiveMenuKind::deleteDocument:m::ArchiveMenuKind::deleteCategory,options.view.appearance,options.view.strings});need(bool(v.controls),"Archive formatting controls are missing");v.controls->update(*v.controlInput);return controlsArtwork(*v.controls,options.colorWheelContents);}
 void redrawMenu(Menu&v){v.scene.syncContent(menuArtwork(v),++v.revision,time,false,reduceMotion);}
 bool closeMenu(bool animated=true){if(!menu)return true;if(menu->categoryField){if(menu->categoryField->document().composition())return false;if(manager){const auto hr=menu->categoryField->editor->focus(false);if(hr==TS_E_NOLOCK)return false;need(SUCCEEDED(hr),"Cannot blur category editor");}const auto hr=menu->categoryField->editor->stop();if(hr==TS_E_NOLOCK)return false;need(SUCCEEDED(hr),"Cannot close category editor");menu->categoryField->editor.reset();if(focusedField==std::optional<std::string>{"category"})focusedField.reset();}
  need(retiredMenus.size()<3,"Publish retired Archive menus before another replacement");const auto returnField=menu->kind==Menu::Kind::format?menu->target:std::optional<std::string>{};menu->closing=animated&&!reduceMotion&&active;menu->closeAt=time+(menu->closing?.16:0);menu->start=time;retiredMenus.push_back(std::move(menu));if(returnField)focusField(returnField);return true;
 }
 bool showMenu(Menu::Kind kind,Point origin,bool moving=false){if(!closeMenu(false))return false;auto next=std::make_unique<Menu>(kind,origin,raster,options,time);next->moving=moving;next->target=kind==Menu::Kind::deleteCategory?state.categoryID():state.selected()?std::optional(state.selected()->id):std::nullopt;redrawMenu(*next);menu=std::move(next);return true;}
 bool showControls(m::NotesControlsKind kind,std::optional<std::string>target={}){if(!closeMenu(false))return false;const auto menuKind=kind==m::NotesControlsKind::mediaSource?Menu::Kind::mediaSource:kind==m::NotesControlsKind::shelfMedia?Menu::Kind::shelf:Menu::Kind::format;auto next=std::make_unique<Menu>(menuKind,Point{},raster,options,time);next->target=std::move(target);next->controls=std::make_unique<m::NotesControls>();m::NotesControlsInput ci;ci.kind=kind;ci.dark=options.view.appearance.dark;ci.accent=options.view.appearance.accent;ci.contentsScale=options.view.appearance.contentsScale;ci.strings=options.menuStrings;
  if(menuKind==Menu::Kind::format){auto*f=next->target?field(*next->target):nullptr;if(!f||!f->richDocument)return false;const auto style=f->richDocument->selectionStyle();ci.currentColor=inkColor(style,ci.dark);ci.traits={style.bold,style.italic,style.underline,style.strikethrough};if(kind==m::NotesControlsKind::font){need(bool(options.fontFamilies),"Archive font list provider is required");ci.values=options.fontFamilies();ci.selectedValue=style.fontName.value_or(std::string(raster.defaultFontFamily()));}else if(kind==m::NotesControlsKind::size){ci.values=m::NotesControls::sizeValues(style.fontSize);ci.selectedValue=std::to_string(static_cast<int>(std::round(style.fontSize)));}if(kind==m::NotesControlsKind::color){need(options.colorAtWheel&&options.colorWheelPoint,"Shared source color-wheel conversions are required");const rich::RGBA color{ci.currentColor[0],ci.currentColor[1],ci.currentColor[2],ci.currentColor[3]};ci.colorWheelSelection=options.colorWheelPoint(color);need(std::isfinite(ci.colorWheelSelection.x)&&std::isfinite(ci.colorWheelSelection.y)&&ci.colorWheelSelection.x>=0&&ci.colorWheelSelection.x<=1&&ci.colorWheelSelection.y>=0&&ci.colorWheelSelection.y<=1,"Invalid source color-wheel point");}ci.firstRow=m::NotesControls::initialFirstRow(ci.values,ci.selectedValue);}
  next->controlInput=std::move(ci);redrawMenu(*next);const auto bounds=next->controls->bounds();next->origin=menuKind==Menu::Kind::mediaSource?m::archiveMediaMenuOrigin(bounds):menuKind==Menu::Kind::shelf?Point{(400-bounds.width)/2,150}:Point{24,376-bounds.height};if(menuKind==Menu::Kind::format&&!focusField({}))return false;options.view.formattingField=next->target;menu=std::move(next);return true;
 }
 bool perform(std::string_view action){if(!active)return false;if(action.starts_with("format")){const auto field=options.view.formattingField.value_or("body");auto*f=this->field(field);if(!f||!f->richDocument)return false;if(f->document().composition()){pendingAction=action;return false;}const auto kind=action=="formatFont"?m::NotesControlsKind::font:action=="formatSize"?m::NotesControlsKind::size:action=="formatSpecial"?m::NotesControlsKind::special:m::NotesControlsKind::color;return showControls(kind,field);}
  if(!finish()){pendingAction=action;return false;}pendingAction.reset();if(action=="new")return showMenu(Menu::Kind::category,m::archiveCategoryMenuOrigin(false));if(action=="moveCategory")return showMenu(Menu::Kind::category,m::archiveCategoryMenuOrigin(true),true);if(action=="delete")return showMenu(Menu::Kind::deleteDocument,{80,150});if(action=="deleteCategory")return showMenu(Menu::Kind::deleteCategory,{14,177});if(action=="addMedia")return showControls(m::NotesControlsKind::mediaSource);
  if(action=="back")state.select({});else if(action=="retry"){state.retryPendingSaves();state.activate();}else if(action=="all")state.setFilter({});else if(action=="uncategorized")state.setFilter({},true);else if(action.starts_with("category:"))state.setFilter(std::string(action.substr(9)));else if(action.starts_with("entry:"))state.select(std::string(action.substr(6)));else if(action=="removeMedia"&&state.selected()){auto entry=*state.selected();if(options.view.mediaIndex<entry.media.size()){entry.media.erase(entry.media.begin()+static_cast<std::ptrdiff_t>(options.view.mediaIndex));options.view.mediaIndex=entry.media.empty()?0:std::min(options.view.mediaIndex,entry.media.size()-1);state.update(std::move(entry),dateNow(),time);}}else if(action=="mediaPrevious"||action=="mediaNext"){if(state.selected()&&!state.selected()->media.empty()){const auto count=state.selected()->media.size();options.view.mediaIndex=(options.view.mediaIndex+(action=="mediaNext"?1:count-1))%count;options.view.mediaTime=0;}}
  else if(action=="mediaPlay"&&state.selected())queueMedia(ArchiveMediaAction::Kind::playPause);else return false;contentDirty=true;return true;
 }
 void queueMedia(ArchiveMediaAction::Kind kind,std::string item={},double seconds=0){if(!state.selected())return;if(kind==ArchiveMediaAction::Kind::chooseLocal||kind==ArchiveMediaAction::Kind::chooseShelf||kind==ArchiveMediaAction::Kind::useShelf)++mediaGeneration;mediaAction=ArchiveMediaAction{kind,state.selected()->id,std::move(item),options.view.mediaIndex,16-state.selected()->media.size(),mediaGeneration,seconds};if(!mediaPosted&&PostMessageW(window,options.mediaMessage,mediaRoute,0))mediaPosted=true;}
 bool categoryChoice(std::optional<std::string>id){if(!menu||menu->kind!=Menu::Kind::category)return false;const bool moving=menu->moving;const auto selected=menu->target;if(!closeMenu())return false;if(moving){if(state.selected()&&selected==std::optional(state.selected()->id))state.moveSelected(std::move(id),dateNow(),time);}else state.create(options.newID(),dateNow(),std::move(id));contentDirty=true;return true;}
 bool finishCategory(){if(!menu||!menu->categoryField||!capture(*menu->categoryField))return false;const auto name=gpu::nativeArchiveTextRules().trimmed(m::archiveUTF8(menu->categoryField->document().text()));if(name.empty())return false;const auto id=state.createCategory(options.newID(),name,dateNow());if(!id)return false;return categoryChoice(id);}
 bool menuAction(std::string_view action){if(!menu)return false;if(action=="close"||action=="cancel")return closeMenu();if(menu->kind==Menu::Kind::category){if(action=="newCategory"){menu->editingName=true;redrawMenu(*menu);const Rect r{menu->origin.x+12,menu->origin.y+252,194,28};menu->categoryField=std::make_unique<Field>(window,raster,FieldKind::category,r,"",std::nullopt,rich::TextStyle{},options);if(manager)need(SUCCEEDED(menu->categoryField->editor->connect(*manager,client)),"Cannot connect category field");return focusField("category");}if(action=="create")return finishCategory();if(action=="uncategorized")return categoryChoice({});return categoryChoice(std::string(action));}
  if(menu->kind==Menu::Kind::deleteDocument||menu->kind==Menu::Kind::deleteCategory){const auto kind=menu->kind;const auto selected=menu->target;const auto category=menu->target;if(!closeMenu())return false;if(action=="delete"){if(kind==Menu::Kind::deleteDocument&&state.selected()&&selected==std::optional(state.selected()->id))state.deleteSelected();else if(kind==Menu::Kind::deleteCategory&&category)state.deleteCategory(*category);}contentDirty=true;return true;}
  if(menu->kind==Menu::Kind::mediaSource){if(action=="finder"){closeMenu();queueMedia(ArchiveMediaAction::Kind::chooseLocal);return true;}if(action=="shelf"){closeMenu();queueMedia(ArchiveMediaAction::Kind::chooseShelf);return true;}}
  if(menu->kind==Menu::Kind::shelf){auto&ci=*menu->controlInput;if(action=="filter"){ci.mediaOnly=!ci.mediaOnly;ci.firstRow=0;ci.selectedID.reset();redrawMenu(*menu);return true;}if(action=="use"&&ci.selectedID){const auto id=*ci.selectedID;closeMenu();queueMedia(ArchiveMediaAction::Kind::useShelf,id);return true;}if(action.starts_with("row:")){const auto index=static_cast<std::size_t>(std::stoull(std::string(action.substr(4))));std::size_t row{};for(const auto&choice:ci.choices)if(!ci.mediaOnly||choice.supported){if(row++==index&&choice.supported&&choice.available){ci.selectedID=choice.id;redrawMenu(*menu);return true;}}return false;}}
  if(menu->kind==Menu::Kind::format){auto*f=menu->target?field(*menu->target):nullptr;if(!f||!f->editor||!f->richDocument)return false;rich::FormatChange change;auto&ci=*menu->controlInput;if(action.starts_with("value:")){const auto n=static_cast<std::size_t>(std::stoull(std::string(action.substr(6))));if(n>=ci.values.size())return false;if(ci.kind==m::NotesControlsKind::font){change.kind=rich::FormatKind::font;change.fontName=ci.values[n];}else{change.kind=rich::FormatKind::size;change.fontSize=std::stod(ci.values[n]);}}else if(action.starts_with("trait:")){const auto n=static_cast<unsigned>(std::stoul(std::string(action.substr(6))));if(n>=4)return false;change.kind=n==0?rich::FormatKind::bold:n==1?rich::FormatKind::italic:n==2?rich::FormatKind::underline:rich::FormatKind::strikethrough;}else return false;const auto applied=f->editor->applyFormat(change);if(!applied.handled)return false;f->forceCapture=true;capture(*f);f->editor->syncContent();const auto style=f->richDocument->selectionStyle();ci.traits={style.bold,style.italic,style.underline,style.strikethrough};ci.currentColor=inkColor(style,ci.dark);if(change.kind==rich::FormatKind::font)ci.selectedValue=change.fontName;else if(change.kind==rich::FormatKind::size)ci.selectedValue=std::to_string(static_cast<int>(std::round(change.fontSize)));redrawMenu(*menu);return true;}
  return false;
 }
 bool chooseWheel(Point p){if(!menu||menu->kind!=Menu::Kind::format||!menu->controlInput||menu->controlInput->kind!=m::NotesControlsKind::color)return false;auto&v=*menu;auto*f=v.target?field(*v.target):nullptr;if(!f||!f->editor)return false;need(bool(options.colorAtWheel),"Shared source color-wheel conversion is required");const Point normalized{(p.x-8)/166,(p.y-8)/166};const auto color=options.colorAtWheel(normalized);need(color.valid(),"Invalid source color-wheel color");const auto applied=f->editor->applyFormat({.kind=rich::FormatKind::color,.color=color});if(applied.handled){f->forceCapture=true;capture(*f);const double x=normalized.x*2-1,y=normalized.y*2-1,radius=std::max(1.,std::hypot(x,y));v.controlInput->currentColor={color.red,color.green,color.blue,color.alpha};v.controlInput->colorWheelSelection={(x/radius+1)*.5,(y/radius+1)*.5};redrawMenu(v);}return applied.handled;}
 bool menuKey(std::uint32_t key){if(!menu)return false;auto&v=*menu;if(v.controlInput&&v.controlInput->kind==m::NotesControlsKind::color&&(key==VK_LEFT||key==VK_RIGHT||key==VK_UP||key==VK_DOWN)){auto p=Point{8+v.controlInput->colorWheelSelection.x*166,8+v.controlInput->colorWheelSelection.y*166};if(key==VK_LEFT)p.x-=4;else if(key==VK_RIGHT)p.x+=4;else if(key==VK_UP)p.y-=4;else p.y+=4;chooseWheel(p);return true;}const auto&actions=v.scene.artwork().actions;std::size_t enabled{};for(const auto&a:actions)enabled+=a.enabled;if(!enabled)return true;v.keyboardIndex=std::min(v.keyboardIndex,enabled-1);if(key==VK_DOWN||key==VK_RIGHT){v.keyboardIndex=std::min(enabled-1,v.keyboardIndex+1);return true;}if(key==VK_UP||key==VK_LEFT){if(v.keyboardIndex)--v.keyboardIndex;return true;}if(key==VK_RETURN||key==VK_SPACE){std::size_t n{};for(const auto&a:actions)if(a.enabled&&n++==v.keyboardIndex){const auto action=a.id;menuAction(action);return true;}}return false;}
 bool seekAt(Point point){if(!state.selected()||options.view.mediaIndex>=state.selected()->media.size())return false;const auto&reference=state.selected()->media[options.view.mediaIndex];if(reference["kind"]!=J("video")||reference["duration"].isNull())return false;const double seconds=reference["duration"].number()*std::clamp((point.x-24)/250,0.,1.);queueMedia(ArchiveMediaAction::Kind::seek,{},seconds);return true;}
 void poseMenu(Menu&v,bool current){if(!pose)return;const auto a=reduceMotion?1.:v.closing?1-std::clamp((time-v.start)/.16,0.,1.):std::clamp((time-v.start)/.16,0.,1.);const auto world=pose->contentWorld*Matrix::translation(v.origin.x,v.origin.y);v.scene.updatePose({world,pose->opacity*static_cast<float>(a),time,std::span(&pose->hostClip,1),pose->shutter});if(v.categoryField)poseField(*v.categoryField,pose->opacity*static_cast<float>(a),current);}
 void poseAll(){if(!pose)return;scene.updatePose({pose->contentWorld,pose->opacity,time,std::span(&pose->hostClip,1),pose->shutter});poseFields();if(menu)poseMenu(*menu,true);for(auto&v:retiredMenus)poseMenu(*v,false);}
 bool changeActive(bool value){if(active==value)return true;if(!value&&!finish()){pendingDeactivate=true;input=false;return false;}pendingDeactivate=false;active=value;input=false;pressed=dragging=false;scrollGrab.reset();if(value){for(auto&f:retiredFields)f->retire=time;for(auto&v:retiredMenus)v->closeAt=time;state.activate();}else{closeMenu(false);retireCurrent(false);state.deactivate();++mediaGeneration;mediaAction.reset();}contentDirty=true;return true;}
};

ArchivePreview::ArchivePreview(m::ArchiveState&s,HWND w,gpu::LayerRasterizer&r,ITfThreadMgr*manager,TfClientId client,ArchivePreviewOptions options):impl_(std::make_shared<Impl>(s,w,r,manager,client,std::move(options))){}
ArchivePreview::~ArchivePreview(){auto i=std::move(impl_);i->alive=false;if(i->fields)for(auto&f:i->fields->values)if(f)f->editor.reset();if(i->menu&&i->menu->categoryField)i->menu->categoryField->editor.reset();}
void ArchivePreview::resize(const app::ClientMetrics&m){need(m.pixelWidth&&m.pixelHeight&&std::isfinite(m.scale)&&m.scale>0,"Invalid Archive viewport");impl_->metrics=m;}
void ArchivePreview::setAppearance(m::ArchiveAppearance value){auto i=impl_;i->options.view.appearance=value;i->contentDirty=true;if(i->fields)for(auto&f:i->fields->values)if(f){f->editor->setStyle(fieldStyle(f->rect,f->kind,i->options));f->editor->syncContent();f->loadBacking(i->options);}if(i->menu){if(i->menu->controlInput){i->menu->controlInput->dark=value.dark;i->menu->controlInput->accent=value.accent;i->menu->controlInput->contentsScale=value.contentsScale;}i->redrawMenu(*i->menu);}}
bool ArchivePreview::setStrings(m::ArchiveStrings strings,m::NotesControlsStrings menuStrings,std::string placeholder,double t){auto i=impl_;const Impl::Event event(*i,t);if(strings==i->options.view.strings&&menuStrings==i->options.menuStrings&&placeholder==i->options.categoryNamePlaceholder)return false;need(J::validUtf8(placeholder)&&placeholder.find('\0')==std::string::npos&&placeholder.size()<=4096,"Invalid localized Archive category placeholder");auto candidate=i->options.view;candidate.strings=strings;candidate.mediaIndex=0;(void)m::prepareArchiveArtwork(i->state,candidate);i->options.view.strings=std::move(strings);i->options.menuStrings=std::move(menuStrings);i->options.categoryNamePlaceholder=std::move(placeholder);i->contentDirty=true;
 // Only label/backing content changes. Documents, selection, scroll, undo,
 // composition, focus and source face transition ownership remain untouched.
 if(i->fields)for(auto&f:i->fields->values)if(f)f->loadBacking(i->options);if(i->menu){if(i->menu->controlInput)i->menu->controlInput->strings=i->options.menuStrings;if(i->menu->categoryField)i->menu->categoryField->loadBacking(i->options);i->redrawMenu(*i->menu);}return true;}
void ArchivePreview::setReduceMotion(bool value,double t){auto i=impl_;const Impl::Event event(*i,t);i->reduceMotion=value;}
void ArchivePreview::setOverlayVisible(bool value,double t){auto i=impl_;const Impl::Event event(*i,t);i->overlayVisible=value;if(!value)i->changeActive(false);}
void ArchivePreview::update(const Matrix&center,const core::source::DesktopChromeSettings&settings,const core::ModulePresentationSample&sample,float opacity,double t){auto i=impl_;const Impl::Event event(*i,t);const auto*shown=sample.current.module==core::Module::archive?&sample.current:sample.incoming&&sample.incoming->module==core::Module::archive?&*sample.incoming:nullptr;i->requested=shown&&sample.requested==core::Module::archive;i->changeActive(i->overlayVisible&&i->requested);i->input=i->active&&i->requested&&sample.acceptsModuleInput&&!i->pendingDeactivate;i->captureAll();i->refresh();if(!shown){i->pose.reset();i->registration.update({});return;}i->surface.update(center,settings,*shown,opacity);i->pose=i->surface.pose();const auto&p=*i->pose;const auto camera=gpu::layerViewportProjection(i->metrics.pixelWidth,i->metrics.pixelHeight)*Matrix::scale(i->metrics.scale,i->metrics.scale);i->projection=core::Projection::viewport(camera*p.contentWorld,i->metrics.pixelWidth,i->metrics.pixelHeight);if(i->pointerPoint)i->scene.setFeedback(i->local(*i->pointerPoint),i->pressed,i->time,i->reduceMotion);i->registration.update(p.registration);}
bool ArchivePreview::requiresFrames(double t)const{const auto&i=*impl_;const auto now=std::max(t,i.time);if(!i.pose||i.pose->opacity==0)return false;if(i.scene.requiresFrames(now))return true;if(i.fields&&!i.reduceMotion&&now<i.fields->reveal+.18)return true;for(const auto&f:i.retiredFields)if(now<f->retire)return true;if(i.menu&&(now<i.menu->start+.16||i.menu->scene.requiresFrames(now)))return true;for(const auto&v:i.retiredMenus)if(now<v->closeAt)return true;return false;}
std::optional<double>ArchivePreview::nextWakeTime()const noexcept{return impl_->state.saveDeadline();}
bool ArchivePreview::deadline(double t){auto i=impl_;const Impl::Event event(*i,t);return i->state.flushIfDue(i->time);}
void ArchivePreview::queueCapacityAvailable(){impl_->state.queueCapacityAvailable();}
bool ArchivePreview::covers(Point p)const{const auto&i=*impl_;const auto q=i.local(p);if(!q)return false;if(i.menu&&contains({i.menu->origin.x,i.menu->origin.y,i.menu->scene.artwork().root["bounds"].array()[2].number(),i.menu->scene.artwork().root["bounds"].array()[3].number()},*q))return true;return contains(m::ArchiveState::bounds(),*q);}
bool ArchivePreview::pointer(const app::PointerEvent&e,double t){auto i=impl_;const Impl::Event event(*i,t);i->pointerPoint=Point{e.x,e.y};const auto q=i->local(*i->pointerPoint);const Point physical{e.x*i->metrics.scale,e.y*i->metrics.scale};if(e.kind==app::PointerKind::leave||e.kind==app::PointerKind::captureLost){const bool owned=i->pressed||i->dragging||i->seeking||i->wheelDrag||i->scrollGrab.has_value();i->pressed=i->dragging=i->seeking=i->wheelDrag=false;i->scrollGrab.reset();if(auto*f=i->focusedEditor())f->editor->pointerUp();i->pointerPoint.reset();return owned;}if(e.kind==app::PointerKind::up&&e.button==app::PointerButton::left){const bool owned=i->pressed||i->dragging||i->seeking||i->wheelDrag||i->scrollGrab.has_value();i->pressed=i->dragging=i->seeking=i->wheelDrag=false;i->scrollGrab.reset();if(auto*f=i->focusedEditor())f->editor->pointerUp();return owned;}if(!i->input)return false;
 if(e.kind==app::PointerKind::move){if(i->wheelDrag){if(q&&i->menu)i->chooseWheel({q->x-i->menu->origin.x,q->y-i->menu->origin.y});return true;}if(i->seeking){if(q)i->seekAt(*q);return true;}if(i->dragging){if(auto*f=i->focusedEditor()){f->editor->pointerDrag(physical);i->selectionFeedback();return true;}}if(i->scrollGrab&&q){if(const auto thumb=i->state.galleryThumb()){const auto travel=357-thumb->height;if(travel>0)i->state.setGalleryScroll((q->y-49-*i->scrollGrab)/travel*i->state.galleryMaximum());}return true;}if(i->menu){if(q)i->menu->scene.setFeedback(Point{q->x-i->menu->origin.x,q->y-i->menu->origin.y},i->pressed,i->time,i->reduceMotion);return true;}i->scene.setFeedback(q,i->pressed,i->time,i->reduceMotion);return q&&contains(m::ArchiveState::bounds(),*q);}
 if((e.kind!=app::PointerKind::down&&e.kind!=app::PointerKind::doubleClick)||e.button!=app::PointerButton::left||!q)return false;if(i->menu){auto&v=*i->menu;const Point p{q->x-v.origin.x,q->y-v.origin.y};const auto&b=v.scene.artwork().root["bounds"].array();if(v.categoryField&&contains(v.categoryField->rect,*q)){i->focusField("category");v.categoryField->editor->syncContent();i->dragging=v.categoryField->editor->pointerDown(physical,(e.modifiers&MK_SHIFT)!=0).handled;return true;}if(!contains({0,0,b[2].number(),b[3].number()},p)){i->closeMenu();return true;}if(v.kind==Impl::Menu::Kind::format&&v.controlInput->kind==m::NotesControlsKind::color&&contains({8,8,166,166},p)){i->wheelDrag=true;i->chooseWheel(p);return true;}
  const auto action=m::archiveActionAt(v.scene.artwork().actions,p);if(action){const auto id=std::string(*action);i->pressed=true;v.scene.setFeedback(p,true,i->time,i->reduceMotion);i->menuAction(id);}return true;}
 if(!contains(m::ArchiveState::bounds(),*q))return false;if(i->fields)for(auto&f:i->fields->values)if(f&&contains(f->rect,*q)){if(!i->focusField(fieldName(f->kind)))return true;f->editor->syncContent();i->dragging=f->editor->pointerDown(physical,(e.modifiers&MK_SHIFT)!=0).handled;i->selectionFeedback();return true;}if(contains({24,364,250,18},*q)&&i->seekAt(*q)){i->seeking=true;return true;}if(const auto thumb=i->state.galleryThumb();thumb&&contains({377,49,14,357},*q)){i->scrollGrab=contains(*thumb,*q)?q->y-thumb->y:thumb->height/2;const auto travel=357-thumb->height;if(travel>0)i->state.setGalleryScroll((q->y-49-*i->scrollGrab)/travel*i->state.galleryMaximum());return true;}const auto action=m::archiveActionAt(i->scene.artwork().actions,*q);if(action){const auto id=std::string(*action);i->pressed=true;i->scene.setFeedback(q,true,i->time,i->reduceMotion);i->perform(id);}else i->finish();return true;
}
bool ArchivePreview::wheel(const app::WheelEvent&e,double t){auto i=impl_;const Impl::Event event(*i,t);const auto q=i->local({e.x,e.y});if(!q)return false;if(!i->menu&&!contains(m::ArchiveState::bounds(),*q))return false;if(i->dragging||i->scrollGrab||i->seeking||i->wheelDrag||e.horizontal||!std::isfinite(e.steps)||!e.linesPerStep)return true;const auto delta=-e.steps*(e.linesPerStep==UINT32_MAX?188:12.*e.linesPerStep);if(i->menu){auto&v=*i->menu;if(v.kind==Impl::Menu::Kind::category){v.scroll=std::clamp(v.scroll+delta,0.,std::max(0.,(i->state.categories().size()+1)*32.-4-188));i->redrawMenu(v);}else if(v.controlInput&&(v.controlInput->kind==m::NotesControlsKind::font||v.controlInput->kind==m::NotesControlsKind::size||v.controlInput->kind==m::NotesControlsKind::shelfMedia)){auto&ci=*v.controlInput;const auto visible=ci.kind==m::NotesControlsKind::shelfMedia?4u:7u;std::size_t count=ci.values.size();if(ci.kind==m::NotesControlsKind::shelfMedia){count=0;for(const auto&choice:ci.choices)if(!ci.mediaOnly||choice.supported)++count;}ci.firstRow=static_cast<std::size_t>(std::clamp<double>(ci.firstRow+(delta>0?1:delta<0?-1:0),0,std::max<std::size_t>(visible,count)-visible));i->redrawMenu(v);}return true;}if(auto*f=i->field("body");f&&contains(f->rect,*q)){f->editor->syncContent();f->editor->scrollBy(delta);return true;}i->state.scroll(*q,delta);return true;}
bool ArchivePreview::key(const app::KeyEvent&e,double t){auto i=impl_;const Impl::Event event(*i,t);if(!i->input)return false;const bool control=(GetKeyState(VK_CONTROL)&0x8000)!=0,shift=(GetKeyState(VK_SHIFT)&0x8000)!=0,system=e.alt||GetKeyState(VK_MENU)<0||GetKeyState(VK_LWIN)<0||GetKeyState(VK_RWIN)<0;auto*f=i->focusedEditor();if(e.kind==app::KeyKind::down&&e.value==VK_ESCAPE&&!control&&!system){if(i->menu){i->closeMenu();return true;}if(f&&!f->document().composition()){i->finish();return true;}return false;}if(e.kind==app::KeyKind::down&&control&&!system&&e.value=='N'){i->perform("new");return true;}if(i->menu&&(!f||f->kind!=FieldKind::category)){if(e.kind==app::KeyKind::down&&!control&&!system)return i->menuKey(e.value);return e.kind==app::KeyKind::character||e.kind==app::KeyKind::unicodeCharacter;}if(!f)return false;if(e.kind==app::KeyKind::character||e.kind==app::KeyKind::unicodeCharacter){if(e.value==27||e.value=='\t'||(f->kind!=FieldKind::body&&(e.value=='\r'||e.value=='\n')))return true;if(!control&&!system){f->editor->character(e.value,e.kind==app::KeyKind::unicodeCharacter);i->capture(*f);return true;}return false;}if(e.kind!=app::KeyKind::down||system)return false;if(e.value==VK_RETURN&&f->kind!=FieldKind::body&&!f->document().composition()){if(f->kind==FieldKind::category)i->finishCategory();else i->finish();return true;}using C=gpu::ProjectedEditorCommand;if(control){if(e.value=='A')f->editor->command(C::selectAll);else if(e.value=='Z')f->editor->undo();else if(e.value=='Y')f->editor->redo();else return false;i->capture(*f);return true;}std::optional<C>command;switch(e.value){case VK_LEFT:command=C::left;break;case VK_RIGHT:command=C::right;break;case VK_UP:command=C::up;break;case VK_DOWN:command=C::down;break;case VK_HOME:command=C::documentStart;break;case VK_END:command=C::documentEnd;break;case VK_BACK:command=C::backspace;break;case VK_DELETE:command=C::deleteForward;break;default:return false;}f->editor->command(*command,shift);i->capture(*f);return true;}
bool ArchivePreview::filterKey(const app::NativeMessage&m){auto i=impl_;auto*f=i->focusedEditor();return i->input&&f&&(!i->menu||f->kind==FieldKind::category)&&m.window==i->window&&f->editor->filterKeyMessage(m.message,m.wParam,m.lParam);}
bool ArchivePreview::message(const app::NativeMessage&m,double t){auto i=impl_;if(m.window!=i->window||m.message!=i->options.textMessage)return false;const Impl::Event event(*i,t);auto apply=[&](Impl::Field&f){if(f.generation!=m.wParam)return;f.editor->takeChanges(m.wParam);i->capture(f);f.editor->syncContent();i->selectionFeedback();};if(i->fields)for(auto&f:i->fields->values)if(f&&f->editor)apply(*f);if(i->menu&&i->menu->categoryField&&i->menu->categoryField->editor)apply(*i->menu->categoryField);if(i->pendingFocus){const auto desired=*i->pendingFocus;i->focusField(desired);}if(i->pendingDeactivate)i->changeActive(false);if(i->pendingAction){const auto action=*i->pendingAction;i->perform(action);}return true;}
void ArchivePreview::focus(bool value,double t){auto i=impl_;const Impl::Event event(*i,t);i->focused=value;if(auto*f=i->focusedEditor();f&&i->manager){const auto hr=f->editor->focus(value);need(SUCCEEDED(hr)||hr==TS_E_NOLOCK,"Cannot update Archive field focus");}if(!value){i->dragging=i->pressed=false;i->scrollGrab.reset();}}
void ArchivePreview::cancelInteraction(double t){auto i=impl_;const Impl::Event event(*i,t);i->pressed=i->dragging=i->seeking=i->wheelDrag=false;i->scrollGrab.reset();i->pointerPoint.reset();if(auto*f=i->focusedEditor())f->editor->pointerUp();}
bool ArchivePreview::pointerLocked()const noexcept{return impl_->dragging||impl_->scrollGrab.has_value()||impl_->seeking||impl_->wheelDrag;}
bool ArchivePreview::finishEditing(double t){auto i=impl_;const Impl::Event event(*i,t);return i->finish();}
std::optional<ArchiveMediaAction>ArchivePreview::takeMediaAction(){auto result=std::move(impl_->mediaAction);impl_->mediaAction.reset();impl_->mediaPosted=false;return result;}
UINT_PTR ArchivePreview::mediaRouteGeneration()const noexcept{return impl_->mediaRoute;}
void ArchivePreview::presentShelfMedia(std::vector<m::NotesShelfChoice>choices,double t){auto i=impl_;const Impl::Event event(*i,t);if(!i->active||!i->state.selected())return;if(i->showControls(m::NotesControlsKind::shelfMedia)){i->menu->controlInput->choices=std::move(choices);i->redrawMenu(*i->menu);}}
bool ArchivePreview::receiveMedia(std::string_view document,std::uint64_t generation,std::vector<m::ArchiveJson>references,std::optional<std::string>error,double t){auto i=impl_;const Impl::Event event(*i,t);if(!i->active||generation!=i->mediaGeneration||!i->state.selected()||i->state.selected()->id!=document)return false;for(const auto&r:references)m::validateArchiveMedia(r);auto entry=*i->state.selected();const auto count=std::min<std::size_t>(16-entry.media.size(),references.size());for(std::size_t n=0;n<count;++n)entry.media.push_back(std::move(references[n]));i->options.view.statusMessage=std::move(error);if(count)i->state.update(std::move(entry),i->dateNow(),i->time);i->contentDirty=true;return true;}
void ArchivePreview::setMediaPlayback(std::size_t index,bool playing,double mediaTime,std::optional<std::string>error,double t){auto i=impl_;const Impl::Event event(*i,t);need(std::isfinite(mediaTime)&&mediaTime>=0,"Invalid Archive media progress");const bool changed=i->options.view.mediaIndex!=index||i->options.view.mediaPlaying!=playing||i->options.view.mediaError!=error;i->options.view.mediaIndex=index;i->options.view.mediaPlaying=playing;i->options.view.mediaTime=mediaTime;i->options.view.mediaError=std::move(error);i->contentDirty=i->contentDirty||changed;double fraction{};if(i->state.selected()&&index<i->state.selected()->media.size()){const auto&ref=i->state.selected()->media[index];fraction=std::clamp(mediaTime/std::max(.01,ref["duration"].isNumber()?ref["duration"].number():1.),0.,1.);}i->scene.setMediaProgress(fraction);}
void ArchivePreview::setMediaPresentation(std::size_t index,bool playing,double mediaTime,std::map<std::string,m::ArchiveJson,std::less<>>posters,std::optional<std::string>error,double t){auto i=impl_;const Impl::Event event(*i,t);need(std::isfinite(mediaTime)&&mediaTime>=0&&posters.size()<=12,"Invalid bounded Archive media presentation");const bool changed=i->options.view.mediaIndex!=index||i->options.view.mediaPlaying!=playing||i->options.view.posterContents!=posters||i->options.view.mediaError!=error;i->options.view.mediaIndex=index;i->options.view.mediaPlaying=playing;i->options.view.mediaTime=mediaTime;i->options.view.posterContents=std::move(posters);i->options.view.mediaError=std::move(error);i->contentDirty=i->contentDirty||changed;
 double fraction{};if(i->state.selected()&&index<i->state.selected()->media.size()){const auto&ref=i->state.selected()->media[index];fraction=std::clamp(mediaTime/std::max(.01,ref["duration"].isNumber()?ref["duration"].number():1.),0.,1.);}i->scene.setMediaProgress(fraction);}
bool ArchivePreview::setMediaDraw(std::string_view document,std::size_t index,std::optional<gpu::DrawObject>draw,double t){auto i=impl_;const Impl::Event event(*i,t);if(!i->state.selected()||i->state.selected()->id!=document||i->options.view.mediaIndex!=index)return false;i->refresh();i->mediaDrawDocument=std::string(document);i->mediaDrawIndex=index;i->mediaDraw=std::move(draw);return i->scene.setMediaDraw(i->mediaDraw);}
std::size_t ArchivePreview::mediaIndex()const noexcept{return impl_->options.view.mediaIndex;}
bool ArchivePreview::mediaVisible()const noexcept{return impl_->active&&impl_->overlayVisible;}
bool ArchivePreview::mediaRequestCurrent(std::string_view document,std::uint64_t generation)const noexcept{return impl_->active&&impl_->overlayVisible&&impl_->mediaGeneration==generation&&impl_->state.selected()&&impl_->state.selected()->id==document;}
void ArchivePreview::upload(gpu::Renderer&r){auto i=impl_;if(!i->pose)return;need(!i->registrationRenderer||i->registrationRenderer==&r,"Archive registration belongs to another renderer");i->scene.uploadResources(r);if(i->menu)i->menu->scene.uploadResources(r);for(auto&v:i->retiredMenus)v->scene.uploadResources(r);i->poseAll();i->scene.uploadAnimations(r);if(i->menu)i->menu->scene.uploadAnimations(r);for(auto&v:i->retiredMenus)v->scene.uploadAnimations(r);const auto revision=i->registration.stats().geometryRevision;if(i->registrationUploadedRevision!=revision){i->registration.uploadGeometry(r);i->registrationRenderer=&r;i->registrationUploadedRevision=revision;}}
std::span<const gpu::LayerCompositionEntry>ArchivePreview::entries(){auto i=impl_;i->composed.clear();if(!i->pose)return i->composed;for(const auto&e:i->scene.entries())i->composed.push_back(e);const auto appendField=[&](Impl::Field&f){f.published=true;i->composed.push_back({&f.back,{}});i->composed.push_back({&f.glyphs,{}});};if(i->fields)for(auto&f:i->fields->values)if(f)appendField(*f);for(auto&set:i->retiredFields)if(i->time<set->retire)for(auto&f:set->values)if(f)appendField(*f);auto appendMenu=[&](Impl::Menu&v){v.published=true;for(const auto&e:v.scene.entries())i->composed.push_back(e);if(v.categoryField)appendField(*v.categoryField);};if(i->menu)appendMenu(*i->menu);for(auto&v:i->retiredMenus)if(i->time<v->closeAt)appendMenu(*v);i->composed.push_back({&i->geometry,i->registration.draws()});return i->composed;}
void ArchivePreview::collected(gpu::Renderer&r){auto i=impl_;need(i->scene.collectRetired(r),"Old Archive face remains published");for(auto&f:i->retiredViewportFields)need(f->release(r),"Old Archive viewport remains published");i->retiredViewportFields.clear();if(i->menu)need(i->menu->scene.collectRetired(r),"Old Archive menu content remains published");for(auto it=i->retiredFields.begin();it!=i->retiredFields.end();)if(i->time>=(*it)->retire){for(auto&f:(*it)->values)if(f)need(f->release(r),"Old Archive field remains published");it=i->retiredFields.erase(it);}else++it;for(auto it=i->retiredMenus.begin();it!=i->retiredMenus.end();)if(i->time>=(*it)->closeAt){need((*it)->scene.releaseResources(r),"Old Archive menu remains published");if((*it)->categoryField)need((*it)->categoryField->release(r),"Old category editor remains published");it=i->retiredMenus.erase(it);}else{need((*it)->scene.collectRetired(r),"Old menu face remains published");++it;}}
void ArchivePreview::release(gpu::Renderer&r){auto i=impl_;need(i->finish(),"Archive text transaction must finish before release");for(auto&f:i->retiredViewportFields)need(f->release(r),"Old Archive viewport remains published");if(i->fields){i->stopFields(*i->fields);for(auto&f:i->fields->values)if(f)need(f->release(r),"Archive field remains published");}if(i->menu){i->closeMenu(false);}for(auto&set:i->retiredFields)for(auto&f:set->values)if(f)need(f->release(r),"Archive outgoing field remains published");for(auto&v:i->retiredMenus){need(v->scene.releaseResources(r),"Archive outgoing menu remains published");if(v->categoryField)need(v->categoryField->release(r),"Archive category field remains published");}need(i->scene.releaseResources(r)&&i->registration.releaseResources(r)&&i->geometry.releaseResources(r),"Archive resources remain published");i->registrationRenderer=nullptr;i->registrationUploadedRevision=0;i->state.deactivate();}
const m::ArchiveState&ArchivePreview::state()const noexcept{return impl_->state;}
std::optional<std::string>ArchivePreview::activeField()const{return impl_->focusedField;}
}
#endif
