#include "tools/calendar_preview.hpp"
#ifdef _WIN32
#include "native/module_scene.hpp"
#include "native/module_registration.hpp"
#include <algorithm>
#include <cmath>
#include <utility>
namespace endfield::tools {
namespace {namespace gpu=native;namespace mod=modules;using M=core::Matrix4;using P=core::Point;using R=core::Rect;using J=mod::CalendarJson;
void need(bool b,const char*m){if(!b)throw std::invalid_argument(m);}
bool inside(R r,P p){return p.x>=r.x&&p.y>=r.y&&p.x<r.x+r.width&&p.y<r.y+r.height;}
bool locked(HRESULT r){return r==TS_E_NOLOCK||r==TF_E_NOLOCK;}
constexpr std::array<R,3>fieldRects{{{14,49,312,30},{14,99,312,28},{14,149,312,86}}};
std::string locale(core::Language l){switch(l){case core::Language::english:return "en_US";case core::Language::simplifiedChinese:return "zh_CN";case core::Language::traditionalChinese:return "zh_TW";case core::Language::japanese:return "ja_JP";case core::Language::korean:return "ko_KR";default:throw std::invalid_argument("Resolve Calendar language at the app preference boundary");}}
mod::CalendarStrings strings(core::Language l){mod::CalendarStrings s;const auto cn=mod::CalendarStrings::simplifiedChinese();
#define CALENDAR_STRING(n) s.n=core::localized(s.n,cn.n,l)
 CALENDAR_STRING(calendar);CALENDAR_STRING(today);CALENDAR_STRING(noEvents);CALENDAR_STRING(addEvent);CALENDAR_STRING(editEvent);CALENDAR_STRING(title);CALENDAR_STRING(date);CALENDAR_STRING(details);CALENDAR_STRING(save);CALENDAR_STRING(cancel);CALENDAR_STRING(erase);CALENDAR_STRING(deleteQuestion);CALENDAR_STRING(previousMonth);CALENDAR_STRING(nextMonth);CALENDAR_STRING(refreshReminders);CALENDAR_STRING(denied);CALENDAR_STRING(unavailable);
#undef CALENDAR_STRING
 return s;
}
J empty(){return J::Object{{"bounds",J::Array{0,0,400,440}},{"position",J::Array{0,0}},{"anchorPoint",J::Array{0,0}},{"children",J::Array{}}};}
}
struct CalendarPreview::Impl:std::enable_shared_from_this<Impl> {
    HWND hwnd;mod::CalendarState&state;gpu::CalendarCivilContext&civil;gpu::LayerRasterizer&raster;CalendarPreviewOptions options;ITfThreadMgr*manager;TfClientId client;
    mod::CalendarView view;mod::CalendarDay today;gpu::NativeCalendarScene canvas;gpu::LayerScene geometry;gpu::NativeModuleSurface surface;gpu::NativeModuleRegistration registration{"calendar.registration"};
    app::ClientMetrics metrics;const gpu::ModuleSurfacePose*pose{};core::Projection projection;gpu::Renderer*renderer{};
    bool alive{true},overlay{true},active{},input{},ownerFocused{true},pressed{},dragging{},dirty{true},seen{};double time{};unsigned eventDepth{};std::uint64_t stateRevision{},viewRevision{},fontRevision{},artRevision{},generation{},registrationRevision{};
    std::optional<P>point;
    struct Menu {
        gpu::NativeCalendarScene scene;std::array<std::unique_ptr<gpu::NativeCalendarEditorField>,3>fields;std::array<bool,3>stopped{};mod::CalendarMenuInput input;std::optional<std::string>eventID;std::uint64_t generation{},revision{};unsigned focused{};std::optional<unsigned>pendingFocus;bool pendingSelectAll{},pendingBlur{},pendingDismiss{},pendingSave{},animateDismiss{},closing{},captured{};double opened{},closed{};std::optional<std::string>localError;
        Menu(gpu::LayerRasterizer&r,gpu::LayerRasterOptions o):scene(r,std::move(o)){}
    };
    std::unique_ptr<Menu>menu,closing;std::vector<std::unique_ptr<Menu>>retired;std::array<gpu::LayerCompositionEntry,12>composed;std::size_t count{};
    struct Event {Impl&i;Event(Impl&v,double t):i(v){need(std::isfinite(t),"Calendar owner requires a finite clock");if(!i.eventDepth)i.time=std::max(i.time,t);++i.eventDepth;}~Event(){--i.eventDepth;}};
    Impl(HWND h,mod::CalendarState&s,gpu::CalendarCivilContext&c,gpu::LayerRasterizer&r,CalendarPreviewOptions o,ITfThreadMgr*m,TfClientId id):hwnd(h),state(s),civil(c),raster(r),options(std::move(o)),manager(m),client(id),view(s.today()),today(view.selected()),canvas(r,options.raster),geometry(r),surface(geometry,core::Module::calendar){
        need(IsWindow(h)&&options.text.characters&&options.text.trimmed&&options.text.prefix,"Calendar owner requires borrowed HWND and installed text rules");need((manager&&client!=TF_CLIENTID_NULL)||(!manager&&client==TF_CLIENTID_NULL),"Calendar requires the caller's already-activated TSF manager/client pair");need(options.textMessage>=WM_APP&&options.textMessage<0xbfff,"Calendar text notice must use an owned WM_APP message");geometry.load(empty(),options.raster);surface.rebindLocalContent();retired.reserve(3);
    }
    std::optional<P>local(P p)const{return input&&pose?projection.unproject({p.x*metrics.scale,p.y*metrics.scale}):std::nullopt;}
    std::size_t eventCount()const{std::size_t n{};for(const auto&e:state.events())n+=e.day==view.selected();return n;}
    void content(){
        if(!dirty&&stateRevision==state.revision()&&viewRevision==view.revision()&&fontRevision==raster.fontRevision())return;
        if(!active&&!dirty)return;view.clampEvents(eventCount());mod::CalendarCanvasInput i;i.appearance=options.appearance;i.strings=options.strings;i.today=today;i.selected=view.selected();i.month=view.month();i.firstWeekday=civil.firstWeekday();i.weekdays=civil.weekdays();i.monthHeading=civil.monthHeading(i.month);i.events.assign(state.events().begin(),state.events().end());i.firstEvent=view.firstEvent();i.busy=state.busy();i.permission=state.permission();i.error=state.error();
        canvas.syncContent(mod::prepareCalendarCanvas(i),++artRevision,time,seen,options.reduceMotion);stateRevision=state.revision();viewRevision=view.revision();fontRevision=raster.fontRevision();dirty=false;
        if(menu&&!menu->pendingDismiss&&!menu->captured){const auto error=menu->localError?menu->localError:state.error();if(menu->input.busy!=state.busy()||menu->input.error!=error){menu->input.busy=state.busy();menu->input.error=error;menu->scene.syncContent(mod::prepareCalendarMenu(menu->input),++menu->revision,time,false,options.reduceMotion);}}
    }
    void dispose(std::unique_ptr<Menu>v){if(!v)return;bool released=!renderer;if(renderer){released=v->scene.releaseResources(*renderer);if(released)for(auto&f:v->fields)released=f->releaseResources(*renderer)&&released;}if(!released){need(retired.size()<3,"Publish and collect old Calendar menus before opening another");retired.push_back(std::move(v));}}
    bool focusField(unsigned n,bool selectAll){
        if(!menu||menu->pendingDismiss||menu->captured)return false;need(n<3,"Unknown Calendar field focus");auto*current=menu.get();
        if(manager&&menu->focused!=n){const auto result=menu->fields[menu->focused]->editor().commitComposition();if(!alive||menu.get()!=current)return false;if(locked(result)){menu->pendingFocus=n;menu->pendingSelectAll=selectAll;return false;}need(SUCCEEDED(result),"Cannot commit previous Calendar field composition");const auto blurred=menu->fields[menu->focused]->editor().focus(false);if(!alive||menu.get()!=current)return false;if(locked(blurred)){menu->pendingFocus=n;menu->pendingSelectAll=selectAll;return false;}need(SUCCEEDED(blurred),"Cannot leave Calendar text field");}
        menu->focused=n;menu->pendingFocus.reset();if(manager&&ownerFocused){const auto result=menu->fields[n]->editor().focus(true);if(!alive||menu.get()!=current)return false;if(locked(result)){menu->pendingFocus=n;menu->pendingSelectAll=selectAll;return false;}need(SUCCEEDED(result),"Cannot focus Calendar text field");}
        auto&f=*menu->fields[n];f.normalize(options.text);f.syncContent();if(selectAll){f.editor().command(gpu::ProjectedEditorCommand::selectAll);f.syncContent();}return true;
    }
    void show(const mod::CalendarEvent*event){
        if(!close(false))return;dispose(std::move(closing));auto next=std::make_unique<Menu>(raster,options.raster);next->generation=++generation;next->opened=time;next->input.appearance=options.appearance;next->input.strings=options.strings;next->input.editing=event!=nullptr;next->input.busy=state.busy();next->input.error=state.error();if(event)next->eventID=event->id;
        const std::array<std::string,3>values{event?event->title:std::string{},(event?event->day:view.selected()).string(),event?event->details:std::string{}};const std::array<std::string,3>placeholders{options.strings.title,options.strings.date,options.strings.details};
        for(unsigned n=0;n<3;++n){next->fields[n]=std::make_unique<gpu::NativeCalendarEditorField>(hwnd,raster,options.raster,static_cast<mod::CalendarEditorField>(n),values[n],placeholders[n],options.appearance,options.textMessage,++generation);if(manager){const auto result=next->fields[n]->editor().connect(*manager,client);if(!alive)return;need(SUCCEEDED(result),"Cannot connect Calendar field to shared TSF manager");}}
        next->scene.syncContent(mod::prepareCalendarMenu(next->input),++next->revision,time,false,options.reduceMotion);menu=std::move(next);focusField(0,false);dragging=false;
    }
    bool close(bool animated){
        if(!menu)return true;auto*old=menu.get();for(unsigned n=0;n<3;++n)if(!menu->stopped[n]){const auto hr=menu->fields[n]->editor().commitComposition();if(!alive||menu.get()!=old)return false;if(locked(hr)){menu->pendingDismiss=true;menu->animateDismiss=animated;return false;}need(SUCCEEDED(hr),"Cannot finish Calendar marked text before closing");}
        const bool fade=animated&&active&&!options.reduceMotion&&renderer&&pose;
        // Capture first, while the field still displays its source glyphs/caret.
        // The outgoing menu owns these borrowed GPU references until detachment.
        if(fade&&!menu->captured){std::array<gpu::DrawObject,3>captures;for(unsigned n=0;n<3;++n){menu->fields[n]->normalize(options.text);menu->fields[n]->syncContent();menu->fields[n]->upload(*renderer);captures[n]=menu->fields[n]->capturedLocalDraw(M::translation(fieldRects[n].x,fieldRects[n].y));}menu->scene.appendCapturedFields(captures);menu->scene.uploadResources(*renderer);menu->captured=true;}
        for(unsigned n=0;n<3;++n)if(!menu->stopped[n]){if(!menu->fields[n]->stopInput()){menu->pendingDismiss=true;menu->animateDismiss=animated;return false;}if(!alive||menu.get()!=old)return false;menu->stopped[n]=true;}
        dispose(std::move(closing));menu->pendingDismiss=false;menu->pendingSave=false;menu->pendingFocus.reset();pressed=dragging=false;
        if(fade){closing=std::move(menu);closing->closing=true;closing->closed=time;}else dispose(std::move(menu));return true;
    }
    void save(){
        if(!menu||menu->pendingDismiss||menu->captured||state.busy())return;const auto rawDate=mod::calendarEditorUTF8(menu->fields[1]->document().text());const auto day=mod::CalendarDay::parse(options.text.trimmed(rawDate));
        if(!day){menu->localError=mod::CalendarError(mod::CalendarErrorCode::invalidDate).what();menu->input.error=menu->localError;menu->scene.syncContent(mod::prepareCalendarMenu(menu->input),++menu->revision,time,false,options.reduceMotion);return;}
        auto*current=menu.get();for(auto&f:menu->fields){const auto hr=f->editor().commitComposition();if(!alive||menu.get()!=current)return;if(locked(hr)){menu->pendingSave=true;return;}need(SUCCEEDED(hr),"Cannot commit Calendar marked text before save");}
        for(auto&f:menu->fields){f->normalize(options.text);f->syncContent();}menu->pendingSave=false;menu->localError.reset();const auto id=menu->eventID;const auto tag=menu->generation;std::weak_ptr<Impl>weak=shared_from_this();
        state.save(mod::calendarEditorUTF8(menu->fields[0]->document().text()),mod::calendarEditorUTF8(menu->fields[2]->document().text()),*day,id,[weak,tag](bool saved){auto i=weak.lock();if(!i||!i->alive)return;i->dirty=true;if(saved&&i->menu&&i->menu->generation==tag)i->close(true);});
        if(alive)content();
    }
    void menuAction(std::string_view action){if(!menu||menu->pendingDismiss||menu->captured)return;if(action=="close")close(true);else if(action=="save")save();else if(action=="delete"||action=="cancelDelete"){menu->input.deleting=action=="delete";menu->scene.syncContent(mod::prepareCalendarMenu(menu->input),++menu->revision,time,false,options.reduceMotion);}else if(action=="confirmDelete"&&menu->eventID&&!state.busy()){const auto tag=menu->generation;std::weak_ptr<Impl>weak=shared_from_this();state.remove(*menu->eventID,[weak,tag](bool removed){auto i=weak.lock();if(!i||!i->alive)return;i->dirty=true;if(removed&&i->menu&&i->menu->generation==tag)i->close(true);});if(alive)content();}}
    void perform(std::string_view action){if(action=="new"){if(state.loaded()&&!state.busy())show(nullptr);}else if(action=="reminders"){state.refreshReminders();if(alive)content();}else if(action.starts_with("event:")){for(const auto&e:state.events())if(e.id==action.substr(6)){show(&e);break;}}else if(view.perform(action,today))content();}
    void feedback(std::optional<P>q){if(!pose||!active)return;canvas.setFeedback(menu?std::nullopt:q,pressed,time,options.reduceMotion);if(menu)menu->scene.setFeedback(q?std::optional<P>{{q->x-30,q->y-77}}:std::nullopt,pressed,time,options.reduceMotion);}
    void poseMenu(Menu&m){if(!pose)return;const double alpha=options.reduceMotion?1:m.closing?1-core::CubicTiming{.25,.1,.25,1}.value(std::clamp((time-m.closed)/.14,0.,1.)):core::CubicTiming{.25,.1,.25,1}.value(std::clamp((time-m.opened)/.16,0.,1.));const auto world=pose->contentWorld*M::translation(30,77);m.scene.updatePose({world,float(alpha)*pose->opacity,time,std::span(&pose->hostClip,1),pose->shutter});if(!m.closing&&!m.captured){const auto camera=gpu::layerViewportProjection(metrics.pixelWidth,metrics.pixelHeight)*M::scale(metrics.scale,metrics.scale);for(unsigned n=0;n<3;++n)m.fields[n]->updatePose({world*M::translation(fieldRects[n].x,fieldRects[n].y),camera,metrics.pixelWidth,metrics.pixelHeight,float(alpha)*pose->opacity,true,ownerFocused&&input&&m.focused==n,std::span(&pose->hostClip,1),pose->shutter});}}
    void deactivate(){input=false;pressed=dragging=false;close(false);state.setActive(false);}
};
CalendarPreview::CalendarPreview(HWND h,mod::CalendarState&s,gpu::CalendarCivilContext&c,gpu::LayerRasterizer&r,CalendarPreviewOptions o,ITfThreadMgr*m,TfClientId id):impl_(std::make_shared<Impl>(h,s,c,r,std::move(o),m,id)){}
CalendarPreview::~CalendarPreview(){auto i=impl_;i->alive=false;if(i->menu)for(auto&f:i->menu->fields)f->stopInput();}
void CalendarPreview::resize(const app::ClientMetrics&m){need(m.pixelWidth&&m.pixelHeight&&std::isfinite(m.scale)&&m.scale>0,"Invalid Calendar client metrics");impl_->metrics=m;}
void CalendarPreview::setLanguage(core::Language l,double t){auto i=impl_;const Impl::Event event(*i,t);auto labels=strings(l);const bool localeChanged=i->civil.setDisplayLocale(locale(l));if(!localeChanged&&i->options.strings==labels&&i->fontRevision==i->raster.fontRevision())return;i->options.strings=std::move(labels);i->dirty=true;if(i->menu&&!i->menu->pendingDismiss&&!i->menu->captured){i->menu->input.strings=i->options.strings;i->menu->scene.syncContent(mod::prepareCalendarMenu(i->menu->input),++i->menu->revision,i->time,false,i->options.reduceMotion);const std::array<std::string,3>hints{i->options.strings.title,i->options.strings.date,i->options.strings.details};for(unsigned n=0;n<3;++n)i->menu->fields[n]->setAppearance(i->options.appearance,hints[n]);}if(i->pose)i->content();}
void CalendarPreview::setAppearance(mod::CalendarAppearance a,double t){auto i=impl_;const Impl::Event event(*i,t);if(i->options.appearance==a&&i->fontRevision==i->raster.fontRevision())return;i->options.appearance=a;i->dirty=true;if(i->menu&&!i->menu->pendingDismiss&&!i->menu->captured){i->menu->input.appearance=a;i->menu->scene.syncContent(mod::prepareCalendarMenu(i->menu->input),++i->menu->revision,i->time,false,i->options.reduceMotion);const std::array<std::string,3>hints{i->options.strings.title,i->options.strings.date,i->options.strings.details};for(unsigned n=0;n<3;++n)i->menu->fields[n]->setAppearance(a,hints[n]);}if(i->pose)i->content();}
void CalendarPreview::setReduceMotion(bool b,double t){auto i=impl_;const Impl::Event event(*i,t);i->options.reduceMotion=b;}
void CalendarPreview::systemChanged(double t){auto i=impl_;const Impl::Event event(*i,t);i->civil.refreshSystemContext();i->today=i->state.today();i->state.refreshForSystemChange();if(!i->alive)return;i->dirty=true;if(i->pose)i->content();}
void CalendarPreview::setOverlayVisible(bool b,double t){auto i=impl_;const Impl::Event event(*i,t);if(i->overlay==b)return;i->overlay=b;if(!b&&i->active){i->active=false;i->deactivate();}}
void CalendarPreview::update(const M&center,const core::source::DesktopChromeSettings&settings,const core::ModulePresentationSample&sample,float opacity,double t){auto i=impl_;const Impl::Event event(*i,t);const auto*shown=sample.current.module==core::Module::calendar?&sample.current:sample.incoming&&sample.incoming->module==core::Module::calendar?&*sample.incoming:nullptr;const bool active=i->overlay&&shown&&sample.requested==core::Module::calendar;
 if(active!=i->active){i->active=active;if(active){i->today=i->state.today();i->state.setActive(true);if(!i->alive)return;i->dirty=true;}else{i->deactivate();if(!i->alive)return;}}i->input=active&&sample.acceptsModuleInput;if(!i->input){i->pressed=i->dragging=false;if(i->menu)for(auto&f:i->menu->fields)f->editor().pointerUp();}
 if(!shown){i->pose=nullptr;i->registration.update({});return;}i->content();i->surface.update(center,settings,*shown,opacity);i->pose=&i->surface.pose();const auto&p=*i->pose;const auto camera=gpu::layerViewportProjection(i->metrics.pixelWidth,i->metrics.pixelHeight)*M::scale(i->metrics.scale,i->metrics.scale);i->projection=core::Projection::viewport(camera*p.contentWorld,i->metrics.pixelWidth,i->metrics.pixelHeight);i->seen=true;i->canvas.updatePose({p.contentWorld,p.opacity,i->time,std::span(&p.hostClip,1),p.shutter});if(i->menu)i->poseMenu(*i->menu);if(i->closing){i->poseMenu(*i->closing);if(i->options.reduceMotion||i->time>=i->closing->closed+.16)i->dispose(std::move(i->closing));}i->feedback(i->point?i->local(*i->point):std::nullopt);i->registration.update(p.registration);
}
bool CalendarPreview::requiresFrames(double t)const{const auto&i=*impl_;t=std::max(t,i.time);if(!i.pose)return false;return i.canvas.requiresFrames(t)||(i.menu&&((!i.options.reduceMotion&&t<i.menu->opened+.16)||i.menu->scene.requiresFrames(t)))||bool(i.closing);}
bool CalendarPreview::covers(P p)const{const auto q=impl_->local(p);return q&&(impl_->menu||inside({0,0,400,440},*q));}
bool CalendarPreview::capturesPointer()const noexcept{return bool(impl_->menu)||impl_->dragging;}
bool CalendarPreview::pointer(const app::PointerEvent&e,double t){auto i=impl_;const Impl::Event event(*i,t);i->point=P{e.x,e.y};const auto q=i->local(*i->point);
 if(e.kind==app::PointerKind::captureLost||(e.kind==app::PointerKind::up&&e.button==app::PointerButton::left)){const bool was=i->pressed||i->dragging;i->pressed=i->dragging=false;if(i->menu)for(auto&f:i->menu->fields)f->editor().pointerUp();i->feedback(q);return was;}
 if(e.kind==app::PointerKind::leave){i->point.reset();i->feedback({});return false;}if(!i->input)return false;if(i->menu&&(i->menu->pendingDismiss||i->menu->captured))return true;
 if(e.kind==app::PointerKind::move){if(i->dragging&&i->menu){auto&field=*i->menu->fields[i->menu->focused];field.editor().pointerDrag({e.x*i->metrics.scale,e.y*i->metrics.scale});field.syncContent();}i->feedback(q);return i->dragging||bool(i->menu)||(q&&inside({0,0,400,440},*q));}
 if((e.kind!=app::PointerKind::down&&e.kind!=app::PointerKind::doubleClick)||e.button!=app::PointerButton::left||!q)return false;
 if(i->menu){i->pressed=true;const P p{q->x-30,q->y-77};if(!inside({0,0,340,310},p)){i->close(true);return true;}for(unsigned n=0;n<3;++n)if(inside(fieldRects[n],p)){if(i->focusField(n,false)){i->poseMenu(*i->menu);const auto result=i->menu->fields[n]->editor().pointerDown({e.x*i->metrics.scale,e.y*i->metrics.scale},(e.modifiers&MK_SHIFT)!=0);i->dragging=result.handled;i->menu->fields[n]->syncContent();}i->feedback(q);return true;}if(const auto action=mod::calendarActionAt(i->menu->scene.artwork().actions,p))i->menuAction(*action);if(i->alive)i->feedback(q);return true;}
 if(!inside({0,0,400,440},*q))return false;i->pressed=true;i->perform(mod::calendarActionAt(i->canvas.artwork().actions,*q).value_or(""));if(i->alive){if(i->menu&&i->pose)i->poseMenu(*i->menu);i->feedback(q);}return true;
}
bool CalendarPreview::wheel(const app::WheelEvent&e,double t){auto i=impl_;const Impl::Event event(*i,t);if(!i->input)return false;const auto q=i->local({e.x,e.y});if(!q)return false;if(!std::isfinite(e.steps)||!e.linesPerStep)return false;const double delta=-e.steps*(e.linesPerStep==UINT32_MAX?86:12.*e.linesPerStep);
 if(i->menu){if(i->menu->pendingDismiss||i->menu->captured)return true;const P p{q->x-30,q->y-77};if(inside(fieldRects[2],p)&&!e.horizontal){auto&field=*i->menu->fields[2];field.editor().scrollBy(delta);field.syncContent();}return true;}if(e.horizontal)return inside({0,0,400,440},*q);const auto old=i->view.revision();const bool used=i->view.scroll(*q,delta,i->eventCount());if(old!=i->view.revision())i->content();return used;
}
bool CalendarPreview::key(const app::KeyEvent&e,double t,std::optional<CalendarKeyModifiers>supplied){auto i=impl_;const Impl::Event event(*i,t);if(!i->input)return false;const auto mods=supplied?*supplied:CalendarKeyModifiers{GetKeyState(VK_CONTROL)<0,GetKeyState(VK_SHIFT)<0,e.alt,GetKeyState(VK_LWIN)<0||GetKeyState(VK_RWIN)<0};const bool modified=mods.control||mods.shift||mods.alt||mods.system;
 if(i->menu){if(i->menu->pendingDismiss||i->menu->captured)return true;auto&field=*i->menu->fields[i->menu->focused];if(e.kind==app::KeyKind::character||e.kind==app::KeyKind::unicodeCharacter){if(mods.control||mods.alt||mods.system)return true;field.editor().character(e.value,e.kind==app::KeyKind::unicodeCharacter);field.normalize(i->options.text);field.syncContent();return true;}if(e.kind!=app::KeyKind::down)return false;if(e.value==VK_ESCAPE){i->close(true);return true;}if(e.value==VK_RETURN&&(mods.control||mods.system)){i->save();return true;}
 if(mods.control&&e.value=='Z'){if(mods.shift)field.editor().redo();else field.editor().undo();}else if(mods.control&&e.value=='Y')field.editor().redo();else if(mods.control&&e.value=='A')field.editor().command(gpu::ProjectedEditorCommand::selectAll);else {std::optional<gpu::ProjectedEditorCommand>command;switch(e.value){case VK_LEFT:command=gpu::ProjectedEditorCommand::left;break;case VK_RIGHT:command=gpu::ProjectedEditorCommand::right;break;case VK_UP:command=gpu::ProjectedEditorCommand::up;break;case VK_DOWN:command=gpu::ProjectedEditorCommand::down;break;case VK_HOME:command=gpu::ProjectedEditorCommand::documentStart;break;case VK_END:command=gpu::ProjectedEditorCommand::documentEnd;break;case VK_BACK:command=gpu::ProjectedEditorCommand::backspace;break;case VK_DELETE:command=gpu::ProjectedEditorCommand::deleteForward;break;default:break;}if(!command)return false;field.editor().command(*command,mods.shift);}field.normalize(i->options.text);field.syncContent();return true;}
 if(e.kind!=app::KeyKind::down||modified)return false;if(e.value==VK_LEFT)i->perform("previousMonth");else if(e.value==VK_RIGHT)i->perform("nextMonth");else return false;return true;
}
bool CalendarPreview::filterKey(const app::NativeMessage&m){auto i=impl_;return i->menu&&!i->menu->pendingDismiss&&!i->menu->captured&&i->input&&i->ownerFocused&&i->menu->fields[i->menu->focused]->editor().filterKeyMessage(m.message,m.wParam,m.lParam);}
bool CalendarPreview::message(const app::NativeMessage&m,double t){auto i=impl_;const Impl::Event event(*i,t);if(m.message!=i->options.textMessage||!i->menu)return false;unsigned n=3;for(unsigned k=0;k<3;++k)if(i->menu->fields[k]->generation()==m.wParam)n=k;if(n==3)return false;auto*menu=i->menu.get();const auto flags=menu->fields[n]->editor().takeChanges(m.wParam);if(!flags)return false;
 if(menu->pendingDismiss){i->close(menu->animateDismiss);return true;}if(menu->pendingFocus){i->focusField(*menu->pendingFocus,menu->pendingSelectAll);if(!i->alive||i->menu.get()!=menu)return true;}if(menu->pendingBlur){focus(false,i->time);if(!i->alive||i->menu.get()!=menu)return true;}menu->fields[n]->normalize(i->options.text);menu->fields[n]->syncContent();if(menu->pendingSave)i->save();return true;
}
void CalendarPreview::focus(bool focused,double t){auto i=impl_;const Impl::Event event(*i,t);i->ownerFocused=focused;if(!i->menu||!i->manager||i->menu->pendingDismiss)return;if(focused){i->focusField(i->menu->focused,false);return;}auto*old=i->menu.get();auto&field=*old->fields[old->focused];const auto committed=field.editor().commitComposition();if(!i->alive||i->menu.get()!=old)return;if(locked(committed)){old->pendingBlur=true;return;}need(SUCCEEDED(committed),"Cannot commit Calendar focus loss");const auto hr=field.editor().focus(false);if(!i->alive||i->menu.get()!=old)return;if(locked(hr)){old->pendingBlur=true;return;}need(SUCCEEDED(hr),"Cannot blur Calendar text field");old->pendingBlur=false;}
bool CalendarPreview::dismissMenu(bool animated,double t){auto i=impl_;const Impl::Event event(*i,t);return i->close(animated);}
bool CalendarPreview::editing()const noexcept{return bool(impl_->menu);}std::optional<mod::CalendarEditorField>CalendarPreview::focusedField()const noexcept{return impl_->menu?std::optional(static_cast<mod::CalendarEditorField>(impl_->menu->focused)):std::nullopt;}const mod::CalendarView&CalendarPreview::view()const noexcept{return impl_->view;}
void CalendarPreview::upload(gpu::Renderer&r){auto i=impl_;need(!i->renderer||i->renderer==&r,"Calendar resources belong to another renderer");i->renderer=&r;if(i->seen){i->canvas.uploadResources(r);i->canvas.uploadAnimations(r);}if(i->closing){i->closing->scene.uploadResources(r);i->closing->scene.uploadAnimations(r);}if(i->menu){i->menu->scene.uploadResources(r);i->menu->scene.uploadAnimations(r);if(!i->menu->captured)for(auto&f:i->menu->fields)f->upload(r);}if(i->registrationRevision!=i->registration.stats().geometryRevision){i->registration.uploadGeometry(r);i->registrationRevision=i->registration.stats().geometryRevision;}}
std::span<const gpu::LayerCompositionEntry>CalendarPreview::entries(){auto i=impl_;i->count=0;if(!i->pose)return {};const auto append=[&](std::span<const gpu::LayerCompositionEntry>v){for(const auto&e:v){need(i->count<i->composed.size(),"Calendar retained draw list exceeded its source budget");i->composed[i->count++]=e;}};append(i->canvas.entries());if(i->closing)append(i->closing->scene.entries());if(i->menu){append(i->menu->scene.entries());if(!i->menu->captured)for(auto&f:i->menu->fields)i->composed[i->count++]=f->entry();}i->composed[i->count++]={&i->geometry,i->registration.draws()};return{i->composed.data(),i->count};}
void CalendarPreview::collected(gpu::Renderer&r){auto i=impl_;i->canvas.collectRetired(r);if(i->menu)i->menu->scene.collectRetired(r);if(i->closing)i->closing->scene.collectRetired(r);for(auto it=i->retired.begin();it!=i->retired.end();){bool okay=(*it)->scene.releaseResources(r);if(okay)for(auto&f:(*it)->fields)okay=f->releaseResources(r)&&okay;if(okay)it=i->retired.erase(it);else ++it;}}
void CalendarPreview::release(gpu::Renderer&r){auto i=impl_;need(i->close(false),"Calendar text lock must finish before shutdown");i->dispose(std::move(i->closing));collected(r);need(i->retired.empty()&&i->canvas.releaseResources(r)&&i->registration.releaseResources(r),"Detach Calendar composition before resource release");i->registrationRevision=0;i->renderer=nullptr;}
}
#endif
