#include "tools/projection_media_binding.hpp"
#ifdef _WIN32
#include "core/data/data_store.hpp"
#include <algorithm>
#include <atomic>
#include <cmath>
#include <stdexcept>
namespace endfield::tools {
namespace {
namespace n=native;namespace m=modules;namespace d=ehud::data;using M=core::Matrix4;
void need(bool b,const char*s){if(!b)throw std::invalid_argument(s);}
std::string identity(){static std::atomic<std::uint64_t>serial{};return "projection.media."+std::to_string(++serial);}
std::string utf8(const std::filesystem::path&p){const auto value=p.u8string();return {reinterpret_cast<const char*>(value.data()),value.size()};}
constexpr std::array<n::Vertex,4>vertices{{{{0,0,0},{0,0}},{{1,0,0},{1,0}},{{1,1,0},{1,1}},{{0,1,0},{0,1}}}};
constexpr std::array<std::uint32_t,6>indices{0,1,2,0,2,3};
}
struct ProjectionMediaBinding::Impl {
    struct Asset {
        std::uint64_t id{};std::string key{identity()};std::shared_ptr<const m::ProjectionMediaReference>reference;n::NotesImageAccess access;
        std::shared_ptr<const n::NotesImageFrame>frame;std::uint64_t frameRevision{},observedFrameRevision{},uploadedRevision{},posterRevision{},posterToken{};HRESULT posterError{S_OK};bool wanted{},failed{},uploaded{},imageSubmitted{},videoSubmitted{},bound{},playing{};
        HRESULT observedError{S_OK};std::optional<std::string>error,publishedError;double seconds{};std::string texture;unsigned width{},height{};core::Rect content;
    };
    struct Import {std::uint64_t token{},serial{};std::vector<ProjectionImportFile>files;std::vector<std::optional<n::NotesImageCompletion>>results;};
    ProjectionPreview&preview;m::ProjectionModel&model;n::NativeMediaRequestBroker&broker;n::NativeMediaRequestBroker::Client client;n::Renderer&renderer;ProjectionMediaBindingOptions options;
    std::vector<std::unique_ptr<Asset>>assets;std::string mesh{identity()+".quad"};bool meshUploaded{},alive{true},visible{},requestsDirty{true};std::uint64_t modelRevision{},importSerial{1};double time{};std::optional<Import>import;
    Impl(ProjectionPreview&p,m::ProjectionModel&m,n::NativeMediaRequestBroker&b,n::NativeMediaRequestBroker::Client c,n::Renderer&r,ProjectionMediaBindingOptions o):preview(p),model(m),broker(b),client(c),renderer(r),options(std::move(o)){need(client&&renderer.stats().initialized&&options.resolve&&options.errorText,"Projection media requires explicit borrowed providers");assets.reserve(32);}
    void clock(double t){need(std::isfinite(t)&&t>=time,"Projection media requires a finite monotonic owner clock");time=t;}
    Asset*find(std::uint64_t id)const{for(const auto&a:assets)if(a->id==id)return a.get();return nullptr;}
    void submit(){if(!requestsDirty)return;std::vector<n::NotesImagePlaybackRequest>images;std::vector<n::NotesVideoRequest>videos;images.reserve(model.media().size());videos.reserve(model.media().size());if(visible)for(const auto&a:assets)if(a->wanted&&!a->failed){const auto kind=a->reference->kind();n::NotesImageRequest image{a->key,utf8(a->access.path),1,768,kind==m::NotesMediaKind::image||kind==m::NotesMediaKind::video,a->access.lease,false,kind==m::NotesMediaKind::video};images.push_back({image,kind==m::NotesMediaKind::video?m::NotesMediaKind::image:kind});if(kind==m::NotesMediaKind::video&&broker.hasVideoPlayback())videos.push_back({a->key,image.path,1,768,a->reference->duration(),a->access.lease,true});}
        broker.setImages(client,1,images,time,!visible);broker.setVideos(client,1,videos,time,!visible);for(auto&a:assets)if(a->wanted&&!a->failed&&visible){a->imageSubmitted=true;a->videoSubmitted=a->reference->kind()==m::NotesMediaKind::video&&broker.hasVideoPlayback();}requestsDirty=false;
    }
    bool cancel(){if(!import)return false;broker.cancelInspections(client,++importSerial);import.reset();return true;}
    bool sync(){const bool show=preview.active();const auto revision=model.mediaRevision();if(show==visible&&revision==modelRevision&&!requestsDirty)return false;const bool visibilityChanged=visible!=show;visible=show;modelRevision=revision;requestsDirty|=visibilityChanged;if(!visible)cancel();std::array<bool,32>previous{};for(std::size_t k=0;k<assets.size();++k){previous[k]=assets[k]->wanted;assets[k]->wanted=false;if(visibilityChanged&&visible){assets[k]->posterRevision=0;assets[k]->posterError=S_OK;}}
        if(visible)for(const auto&item:model.media()){auto*a=find(item.id);if(!a){need(assets.size()<32,"Publish and collect retired Projection media before replacement");auto next=std::make_unique<Asset>();next->id=item.id;next->reference=item.reference;try{next->access=options.resolve(*item.reference);need(d::validWindowsFilePath(utf8(next->access.path)),"Projection media access must be an explicit Windows locator");}catch(...){next->failed=true;next->error=options.errorText(E_ACCESSDENIED);}a=next.get();assets.push_back(std::move(next));preview.setMediaDraw(item.id,{},time);}a->wanted=true;}
        for(std::size_t k=0;k<assets.size();++k)requestsDirty|=previous[k]!=assets[k]->wanted;submit();return true;
    }
    bool inspect(){if(!import)return false;if(!preview.importRequestCurrent(import->token)){cancel();return false;}auto results=broker.drainInspections(client,import->serial);for(auto&result:results)for(std::size_t k=0;k<import->files.size();++k)if(result.key=="import."+std::to_string(import->serial)+"."+std::to_string(k))import->results[k]=std::move(result);if(std::any_of(import->results.begin(),import->results.end(),[](const auto&r){return !r;}))return false;
        auto done=std::move(*import);import.reset();broker.cancelInspections(client,++importSerial);std::vector<std::shared_ptr<const m::ProjectionMediaReference>>references;references.reserve(done.files.size());std::optional<std::string>error;for(std::size_t k=0;k<done.files.size();++k){const auto&result=*done.results[k];try{if(FAILED(result.result)||!result.info)throw std::invalid_argument("Projection media inspection failed");const auto&info=*result.info;const auto kind=info.kind==m::NotesMediaKind::image?"image":info.kind==m::NotesMediaKind::gif?"gif":"video";const auto encoded=d::makeWindowsMediaReference(done.files[k].path,done.files[k].displayName,static_cast<int>(info.pixelWidth),static_cast<int>(info.pixelHeight),kind,info.kind==m::NotesMediaKind::image?std::nullopt:std::optional(info.duration),static_cast<int>(info.frameCount));references.push_back(m::ProjectionMediaReference::fromWindowsReference(encoded,done.files[k].accessLease));}catch(...){error=options.errorText(FAILED(result.result)?result.result:E_INVALIDARG);break;}}
        return error?preview.receiveImportError(done.token,std::move(error),time):preview.receiveImport(done.token,references,time);
    }
    bool refresh(){bool changed=inspect();if(!alive)return changed;sync();for(auto&a:assets){if(!a->wanted||!visible)continue;const auto*item=model.find(a->id);if(!item)continue;bool playing{};double seconds{};std::string_view texture;unsigned width{},height{};const auto kind=a->reference->kind();
            if(const auto*image=broker.findImage(client,a->key)){if(image->frame&&(a->frame!=image->frame||a->observedFrameRevision!=image->frameRevision)){a->frame=image->frame;a->observedFrameRevision=image->frameRevision;++a->frameRevision;}if(kind==m::NotesMediaKind::video&&broker.hasVideoPlayback()){if(FAILED(image->error)){if(a->posterError!=image->error&&broker.setVideoPoster(client,a->key,1,a->posterToken+1,nullptr,image->error)){++a->posterToken;a->posterError=image->error;}}else if(image->frame&&(a->posterRevision!=a->frameRevision||FAILED(a->posterError))){if(broker.setVideoPoster(client,a->key,1,a->posterToken+1,image->frame.get(),S_OK)){++a->posterToken;a->posterRevision=a->frameRevision;a->posterError=S_OK;}}}if(kind==m::NotesMediaKind::gif)playing=image->state==m::NotesMediaState::playing;if(FAILED(image->error)&&a->observedError!=image->error){a->error=options.errorText(image->error);a->observedError=image->error;}}
            if(kind==m::NotesMediaKind::video){if(const auto*video=broker.findVideo(client,a->key)){texture=video->textureID;width=video->width;height=video->height;playing=video->state==m::NotesMediaState::playing;seconds=video->pendingSeek.value_or(video->currentTime);if(FAILED(video->error)&&a->observedError!=video->error){a->error=options.errorText(video->error);a->observedError=video->error;}}else if(!broker.hasVideoPlayback()&&a->observedError!=E_NOTIMPL){a->error=options.errorText(E_NOTIMPL);a->observedError=E_NOTIMPL;}}
            if(texture.empty()&&a->frame){if(!a->uploaded||a->uploadedRevision!=a->frameRevision){renderer.setTexture(a->key,a->frameRevision,{a->frame->width,a->frame->height,a->frame->straightRGBA});a->uploaded=true;a->uploadedRevision=a->frameRevision;changed=true;}texture=a->key;width=a->frame->width;height=a->frame->height;}
            if(a->playing!=playing||a->seconds!=seconds||a->publishedError!=a->error){preview.setMediaPlayback(a->id,playing,seconds,a->error,time);a->playing=playing;a->seconds=seconds;a->publishedError=a->error;changed=true;}
            const auto content=m::projectionMediaGeometry({item->frame.width,item->frame.height},kind).content;if(!a->bound||a->texture!=texture||a->width!=width||a->height!=height||a->content!=content){std::optional<n::DrawObject>draw;if(!texture.empty()&&width&&height){if(!meshUploaded){renderer.setMesh(mesh,1,{vertices,indices});meshUploaded=true;}const auto scale=std::min(content.width/width,content.height/height);const auto w=width*scale,h=height*scale;n::DrawObject value;value.sourceID=a->key+".draw";value.meshID=mesh;value.textureID=texture;value.world=M::translation(content.x+(content.width-w)*.5,content.y+(content.height-h)*.5)*M::scale(w,h);value.masks.push_back({M{},content});draw=std::move(value);}preview.setMediaDraw(a->id,std::move(draw),time);a->bound=true;a->texture=texture;a->width=width;a->height=height;a->content=content;changed=true;}
        }return changed;
    }
};
ProjectionMediaBinding::ProjectionMediaBinding(ProjectionPreview&p,m::ProjectionModel&m,n::NativeMediaRequestBroker&b,n::NativeMediaRequestBroker::Client c,n::Renderer&r,ProjectionMediaBindingOptions o):impl_(std::make_shared<Impl>(p,m,b,c,r,std::move(o))){}ProjectionMediaBinding::~ProjectionMediaBinding(){auto i=impl_;i->alive=false;try{releaseResources(i->time);}catch(...){} }
bool ProjectionMediaBinding::sync(double t){auto i=impl_;i->clock(t);return i->sync();}bool ProjectionMediaBinding::refresh(double t){auto i=impl_;i->clock(t);return i->refresh();}
bool ProjectionMediaBinding::action(const ProjectionPreviewAction&a,double t){auto i=impl_;i->clock(t);if(!i->preview.active()||!i->preview.importRequestCurrent(a.generation))return false;auto*asset=i->find(a.mediaID);if(!asset||!asset->wanted)return false;const auto kind=asset->reference->kind();bool changed{};if(a.kind==ProjectionPreviewAction::Kind::togglePlayback){if(kind==m::NotesMediaKind::gif)changed=i->broker.toggleImage(i->client,asset->key,t);else if(kind==m::NotesMediaKind::video)changed=i->broker.toggleVideo(i->client,asset->key,t);}else if(a.kind==ProjectionPreviewAction::Kind::seek&&kind==m::NotesMediaKind::video)changed=i->broker.seekVideo(i->client,asset->key,a.seconds);if(changed)i->refresh();return changed;}
bool ProjectionMediaBinding::beginImport(std::uint64_t token,std::span<const ProjectionImportFile>files,std::optional<core::Point>point,double t){auto i=impl_;i->clock(t);if(!i->preview.importRequestCurrent(token)||files.empty())return false;if(files.size()>m::ProjectionModel::maximumMedia-i->model.media().size()){i->preview.beginImport(token,files.size(),point,t);return false;}Impl::Import next;next.token=token;next.serial=i->importSerial+1;next.files.assign(files.begin(),files.end());next.results.resize(files.size());std::vector<n::NotesImageRequest>requests;requests.reserve(files.size());for(std::size_t k=0;k<files.size();++k){const auto&file=files[k];need(d::validWindowsFilePath(file.path)&&!file.displayName.empty()&&file.displayName.size()<=4096&&d::Json::validUtf8(file.displayName),"Invalid explicit Projection import locator");requests.push_back({"import."+std::to_string(next.serial)+"."+std::to_string(k),file.path,1,64,false,file.accessLease,true});}if(!i->preview.beginImport(token,files.size(),point,t))return false;try{i->broker.setInspections(i->client,next.serial,requests);}catch(...){i->preview.receiveImportError(token,i->options.errorText(E_FAIL),t);throw;}i->importSerial=next.serial;i->import=std::move(next);return true;}
bool ProjectionMediaBinding::cancelImport(){auto i=impl_;const auto token=i->import?std::optional(i->import->token):std::nullopt;const bool changed=i->cancel();if(token&&i->alive)i->preview.receiveImportError(*token,{},i->time);return changed;}
bool ProjectionMediaBinding::collectRetired(){auto&i=*impl_;bool okay=true;for(auto it=i.assets.begin();it!=i.assets.end();){auto&a=**it;if(a.wanted){++it;continue;}if(a.uploaded&&!i.renderer.removeTexture(a.key)){okay=false;++it;continue;}a.uploaded=false;if(a.imageSubmitted&&!i.broker.retireImage(i.client,a.key)){okay=false;++it;continue;}a.imageSubmitted=false;a.observedFrameRevision=0;a.posterRevision=0;a.posterError=S_OK;if(a.videoSubmitted&&!i.broker.retireVideo(i.client,a.key)){okay=false;++it;continue;}it=i.assets.erase(it);}return okay;}
bool ProjectionMediaBinding::releaseResources(double t){auto i=impl_;i->clock(t);i->cancel();i->visible=false;i->modelRevision=0;i->requestsDirty=true;i->broker.hideImages(i->client,t);i->broker.hideVideos(i->client,t);for(auto&a:i->assets)a->wanted=false;bool okay=collectRetired();if(i->meshUploaded){if(i->renderer.removeMesh(i->mesh))i->meshUploaded=false;else okay=false;}return okay;}
}
#endif
