#include "tools/projection_preview.hpp"
#ifdef _WIN32
#include "native/projection_media_scene.hpp"
#include "core/source_color.hpp"
#include <algorithm>
#include <charconv>
#include <cmath>
#include <deque>
#include <stdexcept>
namespace endfield::tools {
namespace {
namespace n=native;namespace m=modules;using P=core::Point;using R=core::Rect;using M=core::Matrix4;using J=ehud::data::Json;
void need(bool b,const char*s){if(!b)throw std::invalid_argument(s);}
bool inside(R r,P p){return std::isfinite(p.x)&&std::isfinite(p.y)&&p.x>=r.x&&p.y>=r.y&&p.x<r.x+r.width&&p.y<r.y+r.height;}
P local(P p,R r){return {p.x-r.x,p.y-r.y};}
std::optional<std::size_t>index(std::string_view s){std::size_t result{};const auto value=std::from_chars(s.data(),s.data()+s.size(),result);if(value.ec!=std::errc{}||value.ptr!=s.data()+s.size())return {};return result;}
J messageArt(R r,const std::string&s){return J::Object{{"id","projection.message"},{"kind","text"},{"bounds",J::Array{0,0,std::max(1.,r.width),r.height}},{"position",J::Array{0,0}},{"anchorPoint",J::Array{0,0}},{"contentsScale",2},{"text",J::Object{{"string",s},{"fontSize",12},{"font",J::Object{{"familyName",".AppleSystemUIFont"},{"postScriptName",".AppleSystemUIFontDemi"},{"pointSize",12},{"symbolicTraits",2}}},{"foregroundColor",J::Object{{"sRGB",J::Array{1,1,1,1}}}},{"alignment","center"},{"wrapped",false}}}};}
}
struct ProjectionPreview::Impl {
    struct Menu {
        m::ProjectionControls controls;m::ProjectionControlsInput input;std::unique_ptr<n::NativeProjectionControlsScene>scene;
        m::NotesControls common;m::NotesControlsInput commonInput;std::unique_ptr<n::NativeNotesControlsScene>commonScene;std::unique_ptr<n::NativeLayerGroup>group;
        R frame{};M world;std::size_t focused{};double start{},alpha{},y{},scroll{};bool closing{},dead{},uploaded{},dirty{true},wheelDrag{},pressed{};std::optional<std::size_t>slider;std::optional<ProjectionPreviewEvent::Kind>pendingEvent;
        bool isCommon()const{return bool(commonScene);}R bounds()const{return isCommon()?common.bounds():controls.bounds();}
        std::optional<std::string_view>action(P p)const{return isCommon()?common.actionAt(p):controls.actionAt(p);}
    };
    struct Media {std::uint64_t id{};n::ProjectionMediaAppearance appearance;std::unique_ptr<n::NativeProjectionMediaScene>scene;bool dead{};};
    m::ProjectionModel&model;m::ProjectionInteraction&interaction;n::LayerRasterizer&raster;ProjectionPreviewOptions options;
    n::NativeProjectionPlane plane;n::NativeProjectionInk ink;m::ProjectionControls toolbar;std::unique_ptr<n::NativeProjectionControlsScene>toolbarScene;n::LayerScene message;
    app::ClientMetrics metrics{};m::ProjectionWorkspaceGeometry geometry{};M dpi;std::optional<P>pointer;bool alive{true},active{},ready{},toolbarPressed{},messageDirty{true},importing{};double now{},backgroundStart{},backgroundFrom{1},backgroundTarget{1};bool backgroundAnimating{};
    std::uint64_t liveRevision{1},mediaRevision{},preferencesRevision{},generation{1},fontRevision{},messageRevision{1};P importPoint{};std::size_t importCount{};std::string messageText;
    std::vector<std::unique_ptr<Menu>>menus;std::vector<std::unique_ptr<Media>>media;std::vector<n::LayerCompositionEntry>paint;std::deque<ProjectionPreviewAction>actions;std::vector<ProjectionPreviewEvent>events;
    Impl(m::ProjectionModel&model_,m::ProjectionInteraction&interaction_,n::LayerRasterizer&r,ProjectionPreviewOptions o):model(model_),interaction(interaction_),raster(r),options(std::move(o)),plane(r,options.raster),ink(r,options.raster),message(r){menus.reserve(4);media.reserve(32);paint.reserve(100);events.reserve(8);toolbar.update(input(m::ProjectionControlsKind::toolbar));toolbarScene=std::make_unique<n::NativeProjectionControlsScene>(toolbar,raster,options.raster);toolbarScene->syncContent();backgroundFrom=backgroundTarget=model.backgroundEnabled()?1:0;}
    void clock(double t){need(std::isfinite(t)&&t>=now,"Projection requires a finite monotonic owner clock");now=t;}
    m::ProjectionControlsInput input(m::ProjectionControlsKind kind)const{return {kind,options.language,options.accent,model.color(),model.brushWidth(),model.darkness(),model.blur(),model.erasing(),model.backgroundEnabled()};}
    std::string text(const char*en,const char*zh)const{return core::localized(en,zh,options.language);}
    Menu*current()const{for(auto it=menus.rbegin();it!=menus.rend();++it)if(!(*it)->dead&&!(*it)->closing)return it->get();return nullptr;}
    void event(ProjectionPreviewEvent::Kind k,std::optional<m::NotesMediaKind>kind={}){events.push_back({k,kind});}
    void notify(){while(alive&&!events.empty()){const auto e=events.front();events.erase(events.begin());auto callback=options.event;if(callback)callback(e);}}
    void clearMessage(){if(!messageText.empty()){messageText.clear();messageDirty=true;}}
    void error(std::string s){if(messageText!=s){messageText=std::move(s);messageDirty=true;}}
    void action(ProjectionPreviewAction::Kind k,std::string shelf={},std::uint64_t id=0,double seconds=0){if(k==ProjectionPreviewAction::Kind::chooseLocal||k==ProjectionPreviewAction::Kind::useShelf){if(importing)return;++generation;}actions.push_back({k,generation,id,std::move(shelf),seconds});}
    double background()const{if(!backgroundAnimating)return backgroundTarget;const auto p=std::clamp((now-backgroundStart)/.18,0.,1.);return backgroundFrom+(backgroundTarget-backgroundFrom)*p;}
    void refreshPreferences(){if(preferencesRevision!=model.preferencesRevision()){const double target=model.backgroundEnabled()?1:0;if(target!=backgroundTarget){backgroundFrom=target?0:1;backgroundTarget=target;backgroundStart=now;backgroundAnimating=active&&!options.reduceMotion;}preferencesRevision=model.preferencesRevision();}toolbar.update(input(m::ProjectionControlsKind::toolbar));toolbarScene->syncContent();}
    void refresh(Menu&menu){if(menu.isCommon()){menu.common.update(menu.commonInput);const auto images=menu.commonInput.kind==m::NotesControlsKind::color?std::span(&*options.colorWheel,1):std::span<const n::NativeNotesControlsImage>{};menu.commonScene->syncContent(images,1);}else{menu.input=input(menu.input.kind);menu.controls.update(menu.input);menu.scene->syncContent();}menu.dirty=true;}
    void close(bool animated=true){for(auto&menu:menus)if(menu->closing)menu->dead=true;auto*menu=current();if(!menu)return;if(menu->pendingEvent){event(*menu->pendingEvent);menu->pendingEvent.reset();}menu->closing=true;menu->start=now;menu->wheelDrag=menu->pressed=false;menu->slider.reset();menu->dead=!animated||!active||options.reduceMotion;interaction.setMenuOpen(false);}
    void show(std::unique_ptr<Menu>menu){close();menus.erase(std::remove_if(menus.begin(),menus.end(),[](const auto&v){return v->dead&&!v->uploaded;}),menus.end());menu->start=now;menus.push_back(std::move(menu));interaction.setMenuOpen(true);}
    void open(m::ProjectionControlsKind kind){auto menu=std::make_unique<Menu>();menu->input=input(kind);menu->controls.update(menu->input);menu->scene=std::make_unique<n::NativeProjectionControlsScene>(menu->controls,raster,options.raster);menu->scene->syncContent();show(std::move(menu));}
    void open(m::NotesControlsKind kind){need(kind!=m::NotesControlsKind::color||options.colorWheel.has_value(),"Projection color menu requires the original prepared wheel");auto menu=std::make_unique<Menu>();menu->commonInput.kind=kind;menu->commonInput.dark=true;menu->commonInput.strings=options.menuStrings;menu->commonInput.accent=options.accent;menu->commonInput.currentColor=model.color();menu->commonInput.colorWheelSelection=core::source::colorWheelPoint(model.color());if(kind==m::NotesControlsKind::shelfMedia&&options.shelfChoices)menu->commonInput.choices=options.shelfChoices();if(!alive)return;menu->common.update(menu->commonInput);menu->commonScene=std::make_unique<n::NativeNotesControlsScene>(menu->common,raster,options.raster);menu->commonScene->syncContent(kind==m::NotesControlsKind::color?std::span(&*options.colorWheel,1):std::span<const n::NativeNotesControlsImage>{},1);menu->commonScene->updatePose({},1,now);menu->group=std::make_unique<n::NativeLayerGroup>(menu->commonScene->scene(),"projection.menu",options.raster.pixelsPerPoint);show(std::move(menu));}
    void feedback(Menu&menu,std::optional<std::string_view>id,bool pressed){if(menu.isCommon())menu.commonScene->setFeedback(id,pressed,options.reduceMotion,now);else menu.scene->setFeedback(id,pressed,options.reduceMotion,now);}
    void adjust(Menu&menu,std::size_t n,double value){if(n>=menu.controls.sliders().size())return;const auto id=menu.controls.sliders()[n].id;if(id=="brush"){model.setBrushWidth(value);menu.pendingEvent=ProjectionPreviewEvent::Kind::brushChanged;}else{if(id=="blur")model.setBlur(value/100);else model.setDarkness(value/100);menu.pendingEvent=ProjectionPreviewEvent::Kind::backgroundChanged;}refresh(menu);refreshPreferences();}
    void chooseColor(Menu&menu,P p){const P q{(p.x-8)/166,(p.y-8)/166};const auto c=core::source::colorAtWheel(q);model.setColor(c);const auto x=q.x*2-1,y=q.y*2-1,r=std::max(1.,std::hypot(x,y));menu.commonInput.currentColor=c;menu.commonInput.colorWheelSelection={(x/r+1)*.5,(y/r+1)*.5};menu.pendingEvent=ProjectionPreviewEvent::Kind::brushChanged;refresh(menu);refreshPreferences();}
    void clear(){const bool pending=importing||interaction.ownsPointer();++generation;importing=false;interaction.cancelGesture();++liveRevision;clearMessage();const bool changed=model.clearContent();close();if(changed||pending)event(ProjectionPreviewEvent::Kind::cleared);}
    void perform(std::string_view id,Menu*menu){if(menu){if(id=="close"){close();return;}if(id=="confirm"){clear();return;}if(!menu->isCommon()){const bool minus=id.starts_with("minus:");if(minus||id.starts_with("plus:")){const auto n=index(id.substr(minus?6:5));if(n&&*n<menu->controls.sliders().size()){const auto s=menu->controls.sliders()[*n];adjust(*menu,*n,s.value+(minus?-1:1));}}return;}
        if(id=="finder"){close();action(ProjectionPreviewAction::Kind::chooseLocal);return;}if(id=="shelf"){open(m::NotesControlsKind::shelfMedia);return;}if(id=="filter"){menu->commonInput.mediaOnly=!menu->commonInput.mediaOnly;menu->commonInput.firstRow=0;menu->commonInput.selectedID.reset();refresh(*menu);return;}if(id=="use"&&menu->commonInput.selectedID){const auto selected=*menu->commonInput.selectedID;close();action(ProjectionPreviewAction::Kind::useShelf,selected);return;}if(id.starts_with("row:")){const auto row=index(id.substr(4));if(!row)return;std::size_t n{};for(const auto&c:menu->commonInput.choices)if(!menu->commonInput.mediaOnly||c.supported){if(n++==*row&&c.available&&c.supported){menu->commonInput.selectedID=c.id;refresh(*menu);break;}}}return;}
        if(id=="close")action(ProjectionPreviewAction::Kind::returnToHUD);else if(id=="clear")open(m::ProjectionControlsKind::clearConfirmation);else if(id=="brush")open(m::ProjectionControlsKind::brush);else if(id=="appearance")open(m::ProjectionControlsKind::appearance);else if(id=="color")open(m::NotesControlsKind::color);else if(id=="media")open(m::NotesControlsKind::mediaSource);else if(id=="eraser"){model.setErasing(!model.erasing());event(ProjectionPreviewEvent::Kind::brushChanged);}else if(id=="background"){model.setBackgroundEnabled(!model.backgroundEnabled());event(ProjectionPreviewEvent::Kind::backgroundChanged);}refreshPreferences();
    }
    void mediaFeedback(P point,bool pressed){for(auto&v:media)if(!v->dead){const auto*item=model.find(v->id);if(!item)continue;const auto g=m::projectionMediaGeometry({item->frame.width,item->frame.height},item->reference->kind());const auto q=local(point,item->frame);v->scene->setFeedback(inside(g.close,q)?std::optional<std::string_view>("close"):g.moving&&inside(g.play,q)?std::optional<std::string_view>("play"):std::nullopt,pressed,options.reduceMotion,now);}}
    void result(const m::ProjectionInputResult&r){if(r.changed)++liveRevision;if(r.closeMenu)close();if(r.returnToHUD)action(ProjectionPreviewAction::Kind::returnToHUD);if(r.togglePlayback)action(ProjectionPreviewAction::Kind::togglePlayback,{},*r.togglePlayback);if(r.seek)action(ProjectionPreviewAction::Kind::seek,{},r.seek->id,r.seek->seconds);if(r.strokeCompleted)event(ProjectionPreviewEvent::Kind::strokeCompleted);if(r.erased)event(ProjectionPreviewEvent::Kind::erased);if(r.brushChanged)event(ProjectionPreviewEvent::Kind::brushChanged);if(r.mediaRemoved)event(ProjectionPreviewEvent::Kind::mediaRemoved);if(r.drawingLimit)error(text("This drawing has reached the stroke limit.","此画布已达到笔画数量上限。"));}
    Media*find(std::uint64_t id)const{for(const auto&v:media)if(!v->dead&&v->id==id)return v.get();return nullptr;}
    void syncMedia(){for(auto&v:media)if(!v->dead&&!model.find(v->id))v->dead=true;for(const auto&item:model.media()){auto*v=find(item.id);if(!v){auto next=std::make_unique<Media>();next->id=item.id;next->appearance.accent=options.accent;next->scene=std::make_unique<n::NativeProjectionMediaScene>(raster,options.raster);v=next.get();media.push_back(std::move(next));}v->appearance.accent=options.accent;v->scene->sync(item,v->appearance);v->scene->setPose(dpi);v->scene->update(now);}mediaRevision=model.mediaRevision();}
    void update(){if(!ready)return;if(fontRevision!=raster.fontRevision())for(auto&menu:menus)if(!menu->dead)refresh(*menu);refreshPreferences();if(backgroundAnimating&&now>=backgroundStart+.18)backgroundAnimating=false;plane.setBackground(model.darkness(),background());plane.setPose(dpi,1);const auto*visibleMenu=current();const bool cursorShown=active&&pointer&&inside(geometry.bounds,*pointer)&&!inside(geometry.toolbar,*pointer)&&(!visibleMenu||!inside(visibleMenu->frame,*pointer));plane.setCursor(cursorShown?pointer:std::optional<P>{},model.brushWidth(),model.color(),model.erasing());const auto&live=interaction.liveStroke();ink.update(model.drawing().strokes(),model.drawingRevision(),live?&*live:nullptr,liveRevision,{metrics.width,metrics.height},metrics.scale);ink.setPose(dpi,1);syncMedia();
        toolbarScene->updatePose(dpi*M::translation(geometry.toolbar.x,geometry.toolbar.y),1,now);if(messageDirty||fontRevision!=raster.fontRevision()){auto art=messageArt(geometry.message,messageText);if(!message.contentRevision())message.load(art,options.raster);else message.updateLocalContent("projection.message",++messageRevision,art,options.raster);messageDirty=false;}const n::LayerPlacement place{0,dpi*M::translation(geometry.message.x,geometry.message.y),messageText.empty()?0.f:1.f,{}};message.setPlacements(std::span(&place,1));fontRevision=raster.fontRevision();
        for(auto&menu:menus){if(menu->dead)continue;const auto elapsed=std::max(0.,now-menu->start);if(menu->closing&&(options.reduceMotion||elapsed>=.14)){menu->dead=true;continue;}const auto progress=options.reduceMotion?1.:core::CubicTiming{.42,0,.58,1}.value(std::clamp(elapsed/.16,0.,1.));menu->alpha=menu->closing?1-std::clamp(elapsed/.14,0.,1.):progress;menu->y=menu->closing?-5*progress:-5*(1-progress);const auto b=menu->bounds();menu->frame=m::projectionMenuFrame(geometry,{b.width,b.height});menu->world=dpi*M::translation(menu->frame.x,menu->frame.y+menu->y);if(menu->isCommon()){menu->commonScene->updatePose({},1,now);if(menu->uploaded)menu->group->setPose(menu->world,float(menu->alpha));}else menu->scene->updatePose(menu->world,float(menu->alpha),now);}
    }
};
ProjectionPreview::ProjectionPreview(m::ProjectionModel&m,m::ProjectionInteraction&i,n::LayerRasterizer&r,ProjectionPreviewOptions o):impl_(std::make_shared<Impl>(m,i,r,std::move(o))){}ProjectionPreview::~ProjectionPreview(){if(impl_){impl_->alive=false;impl_->interaction.setActive(false);}}
void ProjectionPreview::resize(const app::ClientMetrics&metrics,double safe,double visible){auto p=impl_;need(std::isfinite(metrics.scale)&&metrics.scale>0&&metrics.pixelWidth&&metrics.pixelHeight,"Invalid Projection metrics");auto&i=*p;const auto geometry=m::projectionWorkspaceGeometry({metrics.width,metrics.height},safe,visible);i.plane.resize({metrics.width,metrics.height},metrics.scale);i.metrics=metrics;i.geometry=geometry;i.dpi={};i.dpi.values[0]=i.dpi.values[5]=metrics.scale;i.interaction.resize({metrics.width,metrics.height});for(const auto&item:i.model.media())i.model.setFrame(item.frame,item.id,geometry.bounds);i.ready=true;i.messageDirty=true;++i.liveRevision;i.update();}
void ProjectionPreview::setActive(bool value,double t){auto p=impl_;auto&i=*p;i.clock(t);if(i.active==value)return;i.active=value;i.result(i.interaction.setActive(value));if(!value){++i.generation;i.importing=false;i.actions.clear();i.pointer.reset();i.toolbarPressed=false;i.toolbarScene->setFeedback({},false,true,t);for(auto&v:i.media)if(!v->dead)v->scene->setFeedback({},false,true,t);i.close(false);i.backgroundAnimating=false;++i.liveRevision;}i.update();i.notify();}bool ProjectionPreview::active()const noexcept{return impl_->active;}
void ProjectionPreview::setPreferences(core::Language l,m::NotesColor accent,m::NotesControlsStrings strings,bool reduced,double t){auto p=impl_;auto&i=*p;i.clock(t);i.options.language=l;i.options.accent=accent;i.options.menuStrings=std::move(strings);i.options.reduceMotion=reduced;for(auto&menu:i.menus)if(!menu->dead){if(menu->isCommon()){menu->commonInput.strings=i.options.menuStrings;menu->commonInput.accent=accent;}i.refresh(*menu);}if(reduced)i.backgroundAnimating=false;i.update();}
void ProjectionPreview::update(double t){auto p=impl_;p->clock(t);p->update();}double ProjectionPreview::backgroundOpacity()const{return impl_->background();}
bool ProjectionPreview::requiresFrames(double t)const{const auto&i=*impl_;if(i.backgroundAnimating&&t<i.backgroundStart+.18)return true;if(i.toolbarScene->requiresFrames(t))return true;for(const auto&v:i.media)if(!v->dead&&v->scene->requiresFrames(t))return true;for(const auto&v:i.menus)if(!v->dead&&(t<v->start+(v->closing?.14:.16)||(v->isCommon()?v->commonScene->requiresFrames(t):v->scene->requiresFrames(t))))return true;return false;}
bool ProjectionPreview::pointer(const app::PointerEvent&e,double t){auto keep=impl_;auto&i=*keep;i.clock(t);if(!i.active||!i.ready||!std::isfinite(e.x)||!std::isfinite(e.y))return false;const P point{e.x,e.y};auto*menu=i.current();if(e.kind==app::PointerKind::captureLost){cancelInteraction(t);return true;}if(e.kind==app::PointerKind::leave){i.pointer.reset();i.toolbarScene->setFeedback({},false,i.options.reduceMotion,t);if(menu)i.feedback(*menu,{},false);i.update();return false;}i.pointer=point;
    if(e.kind==app::PointerKind::move){if(menu){const auto q=local(point,menu->frame);if(menu->wheelDrag)i.chooseColor(*menu,q);else if(menu->slider){const auto s=menu->controls.sliders()[*menu->slider];if(const auto value=s.valueAt(q.x))i.adjust(*menu,*menu->slider,*value);}else i.feedback(*menu,inside(menu->bounds(),q)?menu->action(q):std::nullopt,menu->pressed);}else if(i.interaction.ownsPointer())i.result(i.interaction.drag(point));else{i.toolbarScene->setFeedback(inside(i.geometry.toolbar,point)?i.toolbar.actionAt(local(point,i.geometry.toolbar)):std::nullopt,i.toolbarPressed,i.options.reduceMotion,t);for(auto&v:i.media)if(!v->dead){const auto*item=i.model.find(v->id);const auto g=m::projectionMediaGeometry({item->frame.width,item->frame.height},item->reference->kind());const auto q=local(point,item->frame);v->scene->setFeedback(inside(g.close,q)?std::optional<std::string_view>("close"):g.moving&&inside(g.play,q)?std::optional<std::string_view>("play"):std::nullopt,false,i.options.reduceMotion,t);}}i.update();i.notify();return true;}
    if(e.kind==app::PointerKind::up){i.toolbarPressed=false;i.toolbarScene->setFeedback(inside(i.geometry.toolbar,point)?i.toolbar.actionAt(local(point,i.geometry.toolbar)):std::nullopt,false,i.options.reduceMotion,t);if(menu){menu->wheelDrag=menu->pressed=false;menu->slider.reset();const auto q=local(point,menu->frame);i.feedback(*menu,inside(menu->bounds(),q)?menu->action(q):std::nullopt,false);}else{i.mediaFeedback(point,false);i.result(i.interaction.up());}i.update();i.notify();return true;}
    if(e.kind!=app::PointerKind::down&&e.kind!=app::PointerKind::doubleClick)return false;if(e.button==app::PointerButton::right){i.result(i.interaction.rightDown());i.update();i.notify();return true;}if(e.button!=app::PointerButton::left)return false;
    if(menu){const auto q=local(point,menu->frame);if(!inside(menu->bounds(),q)){i.close();i.update();i.notify();return true;}menu->pressed=true;if(menu->isCommon()&&menu->commonInput.kind==m::NotesControlsKind::color&&inside({8,8,166,166},q)){menu->wheelDrag=true;i.chooseColor(*menu,q);}else if(!menu->isCommon()&&(menu->slider=menu->controls.sliderAt(q))){const auto s=menu->controls.sliders()[*menu->slider];if(const auto value=s.valueAt(q.x))i.adjust(*menu,*menu->slider,*value);}else if(const auto action=menu->action(q)){const auto owned=std::string(*action);i.feedback(*menu,owned,true);i.perform(owned,menu);}}
    else if(inside(i.geometry.toolbar,point)){i.toolbarPressed=true;if(const auto action=i.toolbar.actionAt(local(point,i.geometry.toolbar))){const auto owned=std::string(*action);i.toolbarScene->setFeedback(owned,true,i.options.reduceMotion,t);i.perform(owned,nullptr);}}
    else{i.clearMessage();i.mediaFeedback(point,true);i.result(i.interaction.down(point));}i.update();i.notify();return true;
}
bool ProjectionPreview::wheel(const app::WheelEvent&e,double t){auto keep=impl_;auto&i=*keep;i.clock(t);if(!i.active||!std::isfinite(e.steps)||!std::isfinite(e.x)||!std::isfinite(e.y))return false;if(e.horizontal)return true;auto*menu=i.current();if(menu){if(menu->isCommon()&&menu->commonInput.kind==m::NotesControlsKind::shelfMedia&&inside(menu->frame,{e.x,e.y})){auto&v=menu->commonInput;std::size_t count{};for(const auto&c:v.choices)if(!v.mediaOnly||c.supported)++count;menu->scroll-=e.steps*12;const auto rows=static_cast<long long>(menu->scroll/39);menu->scroll-=double(rows)*39;const auto next=std::size_t(std::clamp(static_cast<long long>(v.firstRow)+rows,0LL,static_cast<long long>(std::max<std::size_t>(4,count)-4)));if(next!=v.firstRow){v.firstRow=next;i.refresh(*menu);}}return true;}i.result(i.interaction.wheel(e.steps,false,true));i.update();i.notify();return true;}
bool ProjectionPreview::key(const app::KeyEvent&e,double t){auto p=impl_;auto&i=*p;i.clock(t);if(!i.active||e.kind!=app::KeyKind::down)return false;if(e.value==27){i.result(i.interaction.escape());i.update();i.notify();return true;}auto*menu=i.current();if(!menu)return false;if(menu->isCommon()&&menu->commonInput.kind==m::NotesControlsKind::color&&(e.value>=37&&e.value<=40)){auto q=P{8+menu->commonInput.colorWheelSelection.x*166,8+menu->commonInput.colorWheelSelection.y*166};if(e.value==37)q.x-=4;else if(e.value==39)q.x+=4;else if(e.value==38)q.y-=4;else q.y+=4;i.chooseColor(*menu,q);i.update();return true;}const auto actions=menu->isCommon()?menu->common.actions():menu->controls.actions();std::size_t enabled{};for(const auto&a:actions)enabled+=a.enabled;if(!enabled)return true;if(e.value==40||e.value==39)menu->focused=std::min(enabled-1,menu->focused+1);else if(e.value==38||e.value==37){if(menu->focused)--menu->focused;}else if(e.value==13||e.value==32){std::size_t n{};for(const auto&a:actions)if(a.enabled&&n++==std::min(menu->focused,enabled-1)){const auto id=a.id;i.perform(id,menu);break;}}else return false;i.update();i.notify();return true;}
bool ProjectionPreview::pointerLocked()const noexcept{const auto&i=*impl_;const auto*menu=i.current();return i.interaction.ownsPointer()||(menu&&(menu->wheelDrag||menu->slider));}void ProjectionPreview::cancelInteraction(double t){auto p=impl_;auto&i=*p;i.clock(t);i.interaction.cancelGesture();++i.liveRevision;i.toolbarPressed=false;i.toolbarScene->setFeedback({},false,i.options.reduceMotion,t);if(auto*menu=i.current()){menu->pressed=menu->wheelDrag=false;menu->slider.reset();i.feedback(*menu,{},false);}i.update();}bool ProjectionPreview::menuOpen()const noexcept{return impl_->current()!=nullptr;}
bool ProjectionPreview::importBusy()const noexcept{return impl_->importing;}
std::optional<ProjectionPreviewAction>ProjectionPreview::takeAction(){auto&i=*impl_;if(i.actions.empty())return {};auto action=std::move(i.actions.front());i.actions.pop_front();return action;}bool ProjectionPreview::importRequestCurrent(std::uint64_t n)const noexcept{return impl_->active&&n==impl_->generation;}
std::optional<std::uint64_t>ProjectionPreview::prepareImportRequest(){auto&i=*impl_;if(!i.active||i.importing)return {};return ++i.generation;}
bool ProjectionPreview::beginImport(std::uint64_t n,std::size_t count,std::optional<P>point,double t){auto p=impl_;auto&i=*p;i.clock(t);if(!importRequestCurrent(n)||i.importing||!count)return false;if(count>m::ProjectionModel::maximumMedia-i.model.media().size()){i.error(i.text("Projection supports up to 16 media items.","投影最多可添加 16 个媒体。"));i.update();return false;}const auto destination=point.value_or(P{i.metrics.width*.5,i.metrics.height*.5});if(!std::isfinite(destination.x)||!std::isfinite(destination.y))return false;i.importing=true;i.importCount=count;i.importPoint=destination;i.error(i.text("Loading media…","正在载入媒体…"));i.update();return true;}
bool ProjectionPreview::receiveImport(std::uint64_t n,std::span<const std::shared_ptr<const m::ProjectionMediaReference>>refs,double t){auto p=impl_;auto&i=*p;i.clock(t);if(!importRequestCurrent(n)||!i.importing)return false;need(refs.size()==i.importCount&&std::all_of(refs.begin(),refs.end(),[](const auto&r){return bool(r);}),"Projection import must return every validated reference");need(refs.size()<=m::ProjectionModel::maximumMedia-i.model.media().size(),"Projection import no longer fits the source media limit");for(std::size_t k=0;k<refs.size();++k)if(i.model.addMedia(refs[k],{i.importPoint.x+double(k)*12,i.importPoint.y+double(k)*12},i.geometry.bounds))i.event(ProjectionPreviewEvent::Kind::mediaAdded,refs[k]->kind());i.importing=false;i.clearMessage();i.update();i.notify();return true;}
bool ProjectionPreview::receiveImportError(std::uint64_t n,std::optional<std::string>error,double t){auto p=impl_;auto&i=*p;i.clock(t);if(!importRequestCurrent(n))return false;i.importing=false;if(error)i.error(std::move(*error));else i.clearMessage();i.update();return true;}void ProjectionPreview::showError(std::string error,double t){auto p=impl_;p->clock(t);p->error(std::move(error));p->update();}
bool ProjectionPreview::setMediaDraw(std::uint64_t id,std::optional<n::DrawObject>draw,double t){auto p=impl_;p->clock(t);p->syncMedia();auto*media=p->find(id);if(!media)return false;media->scene->setDraw(std::move(draw));media->scene->update(t);return true;}bool ProjectionPreview::setMediaPlayback(std::uint64_t id,bool playing,double seconds,std::optional<std::string>error,double t){auto p=impl_;p->clock(t);auto*media=p->find(id);if(!media||!std::isfinite(seconds)||seconds<0)return false;media->appearance.playing=playing;media->appearance.seconds=seconds;media->appearance.error=std::move(error);const auto*item=p->model.find(id);media->scene->sync(*item,media->appearance);media->scene->update(t);return true;}
void ProjectionPreview::upload(n::Renderer&r){auto p=impl_;auto&i=*p;need(i.ready,"Resize Projection before upload");i.plane.upload(r);for(auto&v:i.media)if(!v->dead)v->scene->upload(r);i.message.uploadResources(r);i.toolbarScene->upload(r);for(auto&menu:i.menus)if(!menu->dead){if(menu->isCommon()){if(!menu->uploaded||menu->dirty)menu->group->uploadResources(r);else menu->group->updateLocal(r);menu->group->setPose(menu->world,float(menu->alpha));}else menu->scene->upload(r);menu->uploaded=true;menu->dirty=false;}}
std::span<const n::LayerCompositionEntry>ProjectionPreview::entries(){auto&i=*impl_;i.paint.clear();if(!i.ready)return i.paint;i.paint.push_back(i.plane.backgroundEntry());for(const auto&item:i.model.media())if(auto*v=i.find(item.id)){const auto entries=v->scene->entries();i.paint.insert(i.paint.end(),entries.begin(),entries.end());}for(const auto&e:i.ink.entries())i.paint.push_back(e);i.paint.push_back(i.plane.cursorEntry());i.paint.push_back({&i.message,{}});i.paint.push_back(i.toolbarScene->entry());for(auto&menu:i.menus)if(!menu->dead&&menu->uploaded)i.paint.push_back(menu->isCommon()?menu->group->entry():menu->scene->entry());return i.paint;}
void ProjectionPreview::collected(n::Renderer&r){auto&i=*impl_;i.ink.collectRetired(r);i.message.collectRetiredResources(r);for(auto it=i.media.begin();it!=i.media.end();)if((*it)->dead&&(*it)->scene->releaseResources(r))it=i.media.erase(it);else ++it;for(auto it=i.menus.begin();it!=i.menus.end();)if((*it)->dead&&((*it)->isCommon()?(*it)->group->releaseResources(r):(*it)->scene->releaseResources(r)))it=i.menus.erase(it);else ++it;}
void ProjectionPreview::release(n::Renderer&r){auto&i=*impl_;need(i.plane.releaseResources(r),"Projection background remains published");need(i.ink.releaseResources(r),"Projection ink remains published");need(i.message.releaseResources(r)&&i.toolbarScene->releaseResources(r),"Projection controls remain published");for(auto&v:i.media)need(v->scene->releaseResources(r),"Projection media remains published");for(auto&menu:i.menus)need(menu->isCommon()?menu->group->releaseResources(r):menu->scene->releaseResources(r),"Projection menu remains published");i.media.clear();i.menus.clear();}
}
#endif
