import Foundation
import CoreFoundation
// API oracle for the exact Foundation encoding selected by unchanged
// ReaderDocument.swift:59. No files/books/windows/application state are opened.
let encoding = String.Encoding(rawValue: CFStringConvertEncodingToNSStringEncoding(CFStringEncoding(CFStringEncodings.GB_18030_2000.rawValue)))
func scalar(_ bytes: [UInt8]) -> UInt32? {
    guard let s = String(data: Data(bytes), encoding: encoding), s.unicodeScalars.count == 1 else { return nil }
    return s.unicodeScalars.first!.value
}
let output = URL(fileURLWithPath: CommandLine.arguments[1])
var singles: [UInt32] = []
for b in 0...255 { singles.append(scalar([UInt8(b)]) ?? UInt32.max) }
var pairs: [UInt32] = []
for a in 0x81...0xfe { for b in 0x40...0xfe where b != 0x7f { pairs.append(scalar([UInt8(a),UInt8(b)]) ?? UInt32.max) } }
var ranges: [[UInt32]] = []
for a in 0x81...0xfe { for b in 0x30...0x39 { for c in 0x81...0xfe { for d in 0x30...0x39 {
    let index = UInt32((((a-0x81)*10+b-0x30)*126+c-0x81)*10+d-0x30)
    guard let value = scalar([UInt8(a),UInt8(b),UInt8(c),UInt8(d)]) else { continue }
    if let last = ranges.last, last[1] + 1 == index, last[2] + index - last[0] == value { ranges[ranges.count-1][1] = index }
    else { ranges.append([index,index,value]) }
} } } }
var text = "// Generated by reader_gb18030_reference.swift using pinned Mac Foundation.\n// Input: CFStringEncodings.GB_18030_2000, as ReaderDocument.swift:59.\n#pragma once\n#include <array>\n#include <cstdint>\nnamespace endfield::modules::readerGB18030Data {\n"
func array(_ name: String, _ values: [UInt32]) { text += "inline constexpr std::array<std::uint32_t,\(values.count)> \(name){\n"; for i in stride(from: 0,to: values.count,by: 16) { text += values[i..<min(values.count,i+16)].map { String(format:"0x%xu",$0) }.joined(separator:",") + ",\n" };text += "};\n" }
array("singles",singles);array("pairs",pairs)
text += "struct Range {std::uint32_t first,last,scalar;};\ninline constexpr std::array<Range,\(ranges.count)> ranges{{\n"
for r in ranges { text += "{\(r[0])u,\(r[1])u,0x\(String(r[2],radix:16))u},\n" };text += "}};\n}\n"
try text.write(to: output,atomically: true,encoding: .utf8)
print("Foundation GB18030: \(singles.count) single bytes, \(pairs.count) pairs, \(ranges.count) four-byte ranges, \(text.utf8.count) source bytes")
