#include "tools/reader_preview.hpp"
#ifdef _WIN32
#include "native/module_scene.hpp"
#include "native/module_registration.hpp"
#include <windows.h>
#include <algorithm>
#include <cmath>
#include <utility>
namespace endfield::tools {
namespace {namespace gpu=native;namespace mod=modules;using M=core::Matrix4;using P=core::Point;using R=core::Rect;using J=mod::ReaderJson;
void need(bool b,const char*m){if(!b)throw std::invalid_argument(m);}bool inside(R r,P p){return p.x>=r.x&&p.y>=r.y&&p.x<r.x+r.width&&p.y<r.y+r.height;}
J empty(){return J::Object{{"bounds",J::Array{0,0,400,440}},{"position",J::Array{0,0}},{"anchorPoint",J::Array{0,0}},{"children",J::Array{}}};}}
struct ReaderPreview::Impl {
    mod::ReaderState*state;gpu::LayerRasterizer*raster;ReaderPreviewOptions options;mod::ReaderViewport viewport;gpu::NativeReaderScene canvas;gpu::LayerScene geometry;
    std::unique_ptr<gpu::NativeModuleSurface>surface;gpu::NativeModuleRegistration registration{"reader.registration"};
    app::ClientMetrics metrics;core::Projection projection;std::optional<gpu::ModuleSurfacePose>pose;
    std::optional<int>pendingAdvance;bool active{},seen{},overlay{true},input{},pressed{},dirty{true};double time{};unsigned eventDepth{};std::uint64_t stateRevision{};
    struct Menu {std::unique_ptr<gpu::NativeReaderMenu>scene;mod::ReaderMenuInput input;mod::ReaderArtwork artwork;P origin;double start{},closingAt{};bool closing{};std::size_t focusedIndex{};double fontRemainder{};};
    std::unique_ptr<Menu>menu,closing;std::vector<std::unique_ptr<Menu>>retired;
    std::array<gpu::LayerCompositionEntry,4>composed;std::size_t count{};gpu::Renderer*renderer{};std::uint64_t registrationUploadedRevision{};
    mod::ReaderListScroll listScroll;std::optional<ReaderImportAction>action;std::uint64_t importGeneration{};bool importPending{},importVisual{},importApplying{};std::optional<std::string>importError;struct ImportTarget{mod::ReaderReferencePlatform platform;std::string path,title;bool wasCurrent{};};std::optional<ImportTarget>importTarget;
    struct Event {Impl&i;Event(Impl&v,double t):i(v){need(std::isfinite(t),"Reader owner requires finite time");if(!i.eventDepth)i.time=std::max(i.time,t);++i.eventDepth;}~Event(){--i.eventDepth;}};
    Impl(mod::ReaderState&s,gpu::LayerRasterizer&r,ReaderPreviewOptions o):state(&s),raster(&r),options(std::move(o)),canvas(r,options.raster),geometry(r){need(options.newID!=nullptr,"Reader bookmark UUID factory required");geometry.load(empty(),options.raster);surface=std::make_unique<gpu::NativeModuleSurface>(geometry,core::Module::reader);retired.reserve(2);}
    std::optional<P>local(P p)const{return input?projection.unproject({p.x*metrics.scale,p.y*metrics.scale}):std::nullopt;}
    void dispatchNavigation(const mod::ReaderNavigationIntent&n){if(n.step&&viewport.pendingContinuousDirection()==n.step&&viewport.nonPrecisionScrollDuration()>0&&!options.reduceMotion){pendingAdvance=n.step;return;}pendingAdvance.reset();if(n.progress)state->jump(*n.progress);else if(n.step>0)state->next();else state->previous();}
    void reverseWaiting(double delta){if(viewport.waitingScrollOpposes(delta)){const auto position=canvas.scrollPresentation(time);pendingAdvance.reset();viewport.adoptScrollPresentation(position,time);}}
    void navigation(){if(viewport.takeNeighborRequest())state->prepareNeighbors();while(const auto n=viewport.takeNavigation())dispatchNavigation(*n);if(pendingAdvance&&viewport.pendingContinuousDirection()!=*pendingAdvance)pendingAdvance.reset();}
    mod::ReaderCanvasInput canvasInput()const{mod::ReaderCanvasInput i;i.appearance=options.appearance;i.strings=options.strings;if(const auto*b=state->book())i.bookTitle=b->title;i.error=importError?importError:state->error();i.loading=importVisual&&!i.error?true:state->loading();if(!importVisual)if(const auto*p=state->current()){i.hasPage=true;i.illustration=p->illustration;i.next=bool(p->next);i.previous=bool(p->previous);i.progress=p->progress;if(const auto*b=state->book())for(const auto&m:b->bookmarks)if(m.location==p->location)i.bookmarked=true;}return i;}
    void content(){if(!active&&!dirty)return;if(!dirty&&stateRevision==state->revision())return;if(importApplying&&importTarget){const auto*b=state->book();const bool confirmed=b&&b->platform==importTarget->platform&&mod::readerReferencePath(*b)==importTarget->path&&b->title==importTarget->title;if(confirmed&&(state->loading()||(state->current()&&(!importTarget->wasCurrent||!state->hasUnsavedChanges())))){importApplying=false;importVisual=false;importError.reset();importTarget.reset();}}viewport.setPreferences(state->library().preferences);std::optional<mod::ReaderPageAnchor>anchor;if(!importVisual)if(const auto*p=state->current()){const auto*b=state->book();anchor=mod::ReaderPageAnchor{b?b->id:"",p->location,bool(p->next),bool(p->previous),p->illustration,p->progress};anchor->nextReady=!p->next;anchor->previousReady=!p->previous;for(const auto&cached:state->pages()){if(p->next&&cached.location==*p->next)anchor->nextReady=true;if(p->previous&&cached.location==*p->previous)anchor->previousReady=true;}}viewport.setPage(std::move(anchor),time,options.reduceMotion);if(const auto n=viewport.takeNavigation()){dispatchNavigation(*n);if(!pendingAdvance){dirty=true;content();return;}}canvas.syncContent(canvasInput(),importVisual?std::span<const mod::ReaderPage>{}:state->pages(),importVisual?nullptr:state->current(),importVisual?std::optional<mod::ReaderDetail>{}:state->imageDetail(),viewport,time);stateRevision=state->revision();dirty=false;}
    void dispose(std::unique_ptr<Menu>v){if(!v)return;if(!renderer||v->scene->release(*renderer))return;retired.push_back(std::move(v));}
    void close(bool animated=true){dispose(std::move(closing));if(menu){if(animated&&active&&!options.reduceMotion){closing=std::move(menu);closing->closing=true;closing->closingAt=time;}else dispose(std::move(menu));}}
    void deactivate(){pendingAdvance.reset();canvas.retainDepartingArtwork(true);input=false;pressed=false;close(false);viewport.cancelInteraction();viewport.setActive(false,time);state->setActive(false);importPending=false;action.reset();++importGeneration;}
    void feedback(std::optional<P>p){if(!active)return;content();canvas.setFeedback(menu?std::nullopt:p,pressed,options.reduceMotion,time);if(menu)menu->scene->setFeedback(p?std::optional<P>{{p->x-menu->origin.x,p->y-menu->origin.y}}:std::nullopt,pressed,options.reduceMotion,time);}
    void rebuildMenu(){need(bool(menu),"Reader menu missing");menu->artwork=mod::prepareReaderMenu(menu->input);menu->scene->syncContent(menu->artwork);}
    void show(mod::ReaderMenuType kind){close();auto next=std::make_unique<Menu>();next->scene=std::make_unique<gpu::NativeReaderMenu>(*raster,options.raster);next->input.type=kind;next->input.strings=options.strings;next->input.accent=options.appearance.accent;next->input.preferences=state->library().preferences;next->input.selectedFont=next->input.preferences.fontName=="System"?std::string(raster->defaultFontFamily()):next->input.preferences.fontName;
        if(kind==mod::ReaderMenuType::library)for(const auto&b:state->library().books)next->input.choices.push_back({b.id,b.title+" · "+std::to_string(static_cast<int>(b.progress*100))+"%"});
        else if(kind==mod::ReaderMenuType::bookmarks){if(const auto*b=state->book())for(const auto&m:b->bookmarks)next->input.choices.push_back({m.id,std::to_string(static_cast<int>(m.progress*100))+"%"});}
        else if(kind==mod::ReaderMenuType::shelf){if(options.shelfChoices)next->input.choices=options.shelfChoices();}
        else if(kind==mod::ReaderMenuType::font){if(options.fontFamilies)for(auto&name:options.fontFamilies())next->input.choices.push_back({name,name});next->input.selectedFont=state->library().preferences.fontName=="System"?std::string(raster->defaultFontFamily()):state->library().preferences.fontName;}
        next->artwork=mod::prepareReaderMenu(next->input);const auto width=next->artwork.bounds.width;const double x=kind==mod::ReaderMenuType::open?12:kind==mod::ReaderMenuType::library?85:kind==mod::ReaderMenuType::bookmarks?296:158;next->origin=kind==mod::ReaderMenuType::shelf?P{(400-width)/2,46}:P{std::min(std::max(8.,x),392-width),44};if(kind==mod::ReaderMenuType::font){const auto at=std::find_if(next->input.choices.begin(),next->input.choices.end(),[&](const auto&v){return v.title==next->input.selectedFont;});next->input.firstRow=std::min(next->input.choices.size()>7?next->input.choices.size()-7:0,at==next->input.choices.end()?0:static_cast<std::size_t>(at-next->input.choices.begin()));next->artwork=mod::prepareReaderMenu(next->input);}next->start=time;next->scene->syncContent(next->artwork);listScroll=mod::ReaderListScroll{};listScroll.setCount(next->input.choices.size());menu=std::move(next);
    }
    void import(ReaderImportAction::Kind kind,std::string id={}){close();importPending=true;action=ReaderImportAction{kind,std::move(id),++importGeneration};}
    void menuAction(std::string_view id){if(!menu)return;const auto kind=menu->input.type;if(id=="close"){close();return;}if(id=="finder"){import(ReaderImportAction::Kind::chooseLocal);return;}if(id=="shelf"){show(mod::ReaderMenuType::shelf);return;}
        if(kind==mod::ReaderMenuType::library){if(id.starts_with("delete:")){menu->input.deletion=std::string(id.substr(7));listScroll.setDeleteConfirmation(true);rebuildMenu();return;}if(id=="cancelDelete"){menu->input.deletion.reset();listScroll.setDeleteConfirmation(false);rebuildMenu();return;}if(id=="confirmDelete"&&menu->input.deletion){const auto target=*menu->input.deletion;close();state->remove(target);return;}const std::string target(id);close();importVisual=false;importApplying=false;importError.reset();importTarget.reset();state->select(target);dirty=true;}
        else if(kind==mod::ReaderMenuType::bookmarks){if(const auto*b=state->book())for(const auto&m:b->bookmarks)if(m.id==id){const auto location=m.location;close();state->jump(location);break;}}
        else if(kind==mod::ReaderMenuType::shelf)import(ReaderImportAction::Kind::useShelf,std::string(id));
        else if(kind==mod::ReaderMenuType::settings){if(id=="font"){show(mod::ReaderMenuType::font);return;}auto p=mod::changeReaderSetting(state->library().preferences,id);state->setPreferences(p);menu->input.preferences=std::move(p);menu->input.selectedFont=menu->input.preferences.fontName=="System"?std::string(raster->defaultFontFamily()):menu->input.preferences.fontName;rebuildMenu();}
        else if(kind==mod::ReaderMenuType::font){const auto prefix=std::string_view("value:");if(id.starts_with(prefix)){const auto index=static_cast<std::size_t>(std::stoull(std::string(id.substr(prefix.size()))));if(index<menu->input.choices.size()){auto p=state->library().preferences;p.fontName=menu->input.choices[index].title;state->setPreferences(std::move(p));close();}}}
    }
    void perform(std::string_view id){const auto old=viewport.imageView();if(id=="previous")viewport.turnPage(-1);else if(id=="next")viewport.turnPage(1);else if(id=="zoomIn")viewport.zoomBy(1.3,{200,215},time);else if(id=="zoomOut")viewport.zoomBy(1/1.3,{200,215},time);else if(id=="zoomReset")viewport.resetZoom(time);else if(id=="bookmark")state->toggleBookmark(options.newID());else if(id=="open")show(mod::ReaderMenuType::open);else if(id=="library")show(mod::ReaderMenuType::library);else if(id=="bookmarks")show(mod::ReaderMenuType::bookmarks);else if(id=="settings")show(mod::ReaderMenuType::settings);detailChanged(old);}
    void detailChanged(mod::ReaderImageView old){if(old!=viewport.imageView()){state->cancelImageDetail();canvas.syncPages(state->pages(),state->current(),state->imageDetail(),viewport,time);}navigation();content();}
};
ReaderPreview::ReaderPreview(mod::ReaderState&s,gpu::LayerRasterizer&r,ReaderPreviewOptions o):impl_(std::make_unique<Impl>(s,r,std::move(o))){}ReaderPreview::~ReaderPreview()=default;
void ReaderPreview::resize(const app::ClientMetrics&m){need(m.pixelWidth&&m.pixelHeight&&std::isfinite(m.scale)&&m.scale>0,"Invalid Reader client metrics");impl_->metrics=m;}
void ReaderPreview::setAppearance(mod::ReaderAppearance a){auto&i=*impl_;i.options.appearance=a;i.state->setLayout({376,334},a.dark);i.dirty=true;if(i.menu){i.menu->input.accent=a.accent;i.rebuildMenu();}}
void ReaderPreview::setStrings(mod::ReaderStrings s){auto&i=*impl_;i.options.strings=std::move(s);i.dirty=true;if(i.menu){i.menu->input.strings=i.options.strings;i.rebuildMenu();}}
void ReaderPreview::setReduceMotion(bool b)noexcept{impl_->options.reduceMotion=b;}
void ReaderPreview::setOverlayVisible(bool b,double t){auto&i=*impl_;const Impl::Event event(i,t);if(i.overlay==b)return;i.overlay=b;if(!b&&i.active){i.active=false;i.deactivate();}}
void ReaderPreview::update(const M&center,const core::source::DesktopChromeSettings&settings,const core::ModulePresentationSample&sample,float opacity,double t){auto&i=*impl_;const Impl::Event event(i,t);const auto*shown=sample.current.module==core::Module::reader?&sample.current:sample.incoming&&sample.incoming->module==core::Module::reader?&*sample.incoming:nullptr;const bool active=i.overlay&&shown&&sample.requested==core::Module::reader;
    if(active!=i.active){i.active=active;if(active){i.canvas.retainDepartingArtwork(false);i.importVisual=false;i.importApplying=false;i.importError.reset();i.importTarget.reset();i.viewport.setActive(true,i.time);i.state->setLayout({376,334},i.options.appearance.dark);i.state->setActive(true);i.dirty=true;}else i.deactivate();}i.input=active&&sample.acceptsModuleInput;if(!i.input){i.pressed=false;i.viewport.cancelInteraction();}
    if(!shown){i.pose.reset();i.registration.update({});return;}i.content();if(i.pendingAdvance){if(i.viewport.pendingContinuousDirection()!=*i.pendingAdvance)i.pendingAdvance.reset();else if(i.options.reduceMotion||i.canvas.canAdvanceVertical(*i.pendingAdvance,i.time)){const int direction=*i.pendingAdvance;i.pendingAdvance.reset();if(direction>0)i.state->next();else i.state->previous();i.dirty=true;i.content();}}i.surface->update(center,settings,*shown,opacity);i.pose=i.surface->pose();const auto&p=*i.pose;const auto camera=gpu::layerViewportProjection(i.metrics.pixelWidth,i.metrics.pixelHeight)*M::scale(i.metrics.scale,i.metrics.scale);i.projection=core::Projection::viewport(camera*p.contentWorld,i.metrics.pixelWidth,i.metrics.pixelHeight);
    i.seen=true;i.canvas.updatePose(p.contentWorld,p.opacity,i.viewport,i.time,i.options.reduceMotion,std::span(&p.hostClip,1),p.shutter);const auto updateMenu=[&](Impl::Menu&m){const double alpha=i.options.reduceMotion?1:m.closing?1-core::CubicTiming{.25,.1,.25,1}.value(std::clamp((i.time-m.closingAt)/.14,0.,1.)):core::CubicTiming{.25,.1,.25,1}.value(std::clamp((i.time-m.start)/.16,0.,1.));m.scene->updatePose(p.contentWorld*M::translation(m.origin.x,m.origin.y),static_cast<float>(alpha)*p.opacity,i.time,std::span(&p.hostClip,1),p.shutter);};if(i.menu)updateMenu(*i.menu);if(i.closing){updateMenu(*i.closing);if(i.time>=i.closing->closingAt+.14)i.dispose(std::move(i.closing));}i.registration.update(p.registration);
}
bool ReaderPreview::requiresFrames(double t)const{const auto&i=*impl_;t=std::max(t,i.time);return i.pose&&(i.canvas.requiresFrames(t)||i.pendingAdvance||(i.menu&&((!i.options.reduceMotion&&t<i.menu->start+.16)||i.menu->scene->requiresFrames(t)))||bool(i.closing));}
std::optional<double>ReaderPreview::nextWakeTime()const noexcept{return impl_->viewport.nextWakeTime();}
ReaderScrollSnapshot ReaderPreview::scrollSnapshot()const noexcept{const auto&i=*impl_;return {i.canvas.scrollSnapshot(),i.time,i.viewport.scrollOffset(),i.viewport.imageView().zoom,i.viewport.imageView().pan.y,i.viewport.deferredScroll(),i.pendingAdvance.value_or(i.viewport.pendingContinuousDirection()),i.state->revision(),i.state->busy()};}
bool ReaderPreview::deadline(double t){auto&i=*impl_;const Impl::Event event(i,t);bool changed{};if(const auto view=i.viewport.takeDetailRequest(i.time)){i.state->requestImageDetail(*view);changed=true;}if(i.viewport.artworkReleaseDue(i.time)){i.canvas.clearArtwork();changed=true;}return changed;}
bool ReaderPreview::covers(P p)const{const auto q=impl_->local(p);return q&&(impl_->menu||inside({0,0,400,440},*q));}
bool ReaderPreview::pointer(const app::PointerEvent&e,double t){auto&i=*impl_;const Impl::Event event(i,t);const auto q=i.local({e.x,e.y});if(e.kind==app::PointerKind::captureLost||(e.kind==app::PointerKind::up&&e.button==app::PointerButton::left)){const bool was=i.viewport.dragging()||i.pressed;const auto old=i.viewport.imageView();i.viewport.pointerUp(i.time);i.detailChanged(old);i.pressed=false;i.feedback(q);return was;}if(e.kind==app::PointerKind::leave){i.feedback({});return false;}if(!i.input)return false;
    if(e.kind==app::PointerKind::move){const auto old=i.viewport.imageView();if(q&&i.viewport.dragging())i.viewport.pointerDragged(*q,i.time);i.detailChanged(old);i.feedback(q);return i.viewport.dragging()||(q&&inside({0,0,400,440},*q));}
    if((e.kind!=app::PointerKind::down&&e.kind!=app::PointerKind::doubleClick)||e.button!=app::PointerButton::left||!q)return false;if(i.menu){i.pressed=true;const P p{q->x-i.menu->origin.x,q->y-i.menu->origin.y};if(inside(i.menu->artwork.bounds,p)){if(const auto id=mod::readerActionAt(i.menu->artwork.actions,p))i.menuAction(*id);}else i.close();i.feedback(q);return true;}if(!inside({0,0,400,440},*q))return false;i.pressed=true;i.content();if(i.state->current()&&inside(i.viewport.progressRect(),*q))i.viewport.pointerDown(*q);else if(const auto id=mod::readerActionAt(i.canvas.actions(),*q,false))i.perform(*id);else i.viewport.pointerDown(*q);i.feedback(q);return true;
}
bool ReaderPreview::wheel(const app::WheelEvent&e,double t){auto&i=*impl_;const Impl::Event event(i,t);const auto q=i.local({e.x,e.y});if(!q)return false;if(i.viewport.dragging())return true;if(!std::isfinite(e.steps)||!e.linesPerStep)return false;const double travel=e.linesPerStep==UINT32_MAX?334:12.*e.linesPerStep,delta=-e.steps*travel;
    if(i.menu){if(i.menu->input.type==mod::ReaderMenuType::font){i.menu->fontRemainder+=delta;const auto rows=static_cast<long long>(i.menu->fontRemainder/18);if(rows){i.menu->fontRemainder-=static_cast<double>(rows)*18;const auto max=i.menu->input.choices.size()>7?i.menu->input.choices.size()-7:0;const auto next=static_cast<std::size_t>(std::clamp(static_cast<long long>(i.menu->input.firstRow)+rows,0LL,static_cast<long long>(max)));if(next!=i.menu->input.firstRow){i.menu->input.firstRow=next;i.rebuildMenu();}}return true;}if(i.menu->input.type!=mod::ReaderMenuType::settings&&i.menu->input.type!=mod::ReaderMenuType::open&&i.listScroll.scroll(delta)){i.menu->input.firstRow=i.listScroll.offset();i.rebuildMenu();}return true;}const auto old=i.viewport.imageView();if(!e.horizontal)i.reverseWaiting(delta);const bool used=i.viewport.scroll(*q,e.horizontal?-delta:0,e.horizontal?0:delta,i.time,mod::ReaderGesturePhase::none,false,false,(e.modifiers&MK_CONTROL)!=0);i.detailChanged(old);return used;
}
bool ReaderPreview::key(const app::KeyEvent&e,double t){return key(e,e.alt||GetKeyState(VK_SHIFT)<0||GetKeyState(VK_CONTROL)<0||GetKeyState(VK_LWIN)<0||GetKeyState(VK_RWIN)<0,t);}
bool ReaderPreview::key(const app::KeyEvent&e,bool modified,double t){auto&i=*impl_;const Impl::Event event(i,t);if(!i.input||e.kind!=app::KeyKind::down)return false;if(i.menu){if(e.value==VK_ESCAPE){i.close();return true;}const auto&items=i.menu->artwork.actions;std::size_t enabled{};for(const auto&a:items)if(a.enabled)++enabled;if(!enabled)return true;if(e.value==VK_DOWN||e.value==VK_RIGHT)i.menu->focusedIndex=std::min(enabled-1,i.menu->focusedIndex+1);else if(e.value==VK_UP||e.value==VK_LEFT)i.menu->focusedIndex=i.menu->focusedIndex?i.menu->focusedIndex-1:0;else if(e.value==VK_RETURN||e.value==VK_SPACE){const auto selected=std::min(enabled-1,i.menu->focusedIndex);std::size_t n{};for(const auto&a:items)if(a.enabled&&n++==selected){const auto id=a.id;i.menuAction(id);break;}}else return false;return true;}if(modified)return false;const auto old=i.viewport.imageView();if(i.state->library().preferences.vertical()){if(e.value!=VK_SPACE&&e.value!=VK_UP&&e.value!=VK_DOWN)return false;const double delta=e.value==VK_SPACE?334:e.value==VK_UP?-40:40;i.reverseWaiting(delta);i.viewport.scroll({200,215},0,delta,i.time);}else{if(e.value!=VK_LEFT&&e.value!=VK_RIGHT)return false;i.viewport.turnPage(e.value==VK_LEFT?-1:1);}i.detailChanged(old);i.feedback({});return true;}
bool ReaderPreview::capturesPointer()const noexcept{return impl_->viewport.dragging()||bool(impl_->menu);}
bool ReaderPreview::pointerLocked()const noexcept{return capturesPointer();}
void ReaderPreview::cancelInteraction(double t){auto&i=*impl_;const Impl::Event event(i,t);i.viewport.cancelInteraction();i.pressed=false;i.feedback({});}
std::optional<ReaderImportAction>ReaderPreview::takeImportAction(){return std::exchange(impl_->action,{});}bool ReaderPreview::importRequestCurrent(std::uint64_t g)const noexcept{return impl_->active&&impl_->importPending&&g==impl_->importGeneration;}
bool ReaderPreview::beginImport(std::uint64_t g,double t){auto&i=*impl_;const Impl::Event event(i,t);if(!importRequestCurrent(g))return false;i.importVisual=true;i.importError.reset();i.importApplying=false;i.importTarget.reset();i.dirty=true;i.viewport.cancelInteraction();i.state->cancelImageDetail();return true;}
bool ReaderPreview::receiveImportError(std::uint64_t g,std::optional<std::string>error,double t){auto&i=*impl_;const Impl::Event event(i,t);if(!importRequestCurrent(g))return false;if(error)need(error->size()<=4096&&J::validUtf8(*error)&&error->find('\0')==std::string::npos,"Invalid Reader import error");i.importPending=false;i.importApplying=false;i.importTarget.reset();i.importError=std::move(error);i.importVisual=bool(i.importError);i.dirty=true;return true;}
bool ReaderPreview::receiveImport(std::uint64_t g,mod::ReaderBook b,double t){auto&i=*impl_;const Impl::Event event(i,t);if(!importRequestCurrent(g))return false;i.importPending=false;i.importError.reset();i.importVisual=true;i.importApplying=true;i.dirty=true;const auto*old=i.state->book();i.importTarget=Impl::ImportTarget{b.platform,std::string(mod::readerReferencePath(b)),b.title,old&&old->platform==b.platform&&mod::readerReferencePath(*old)==mod::readerReferencePath(b)&&old->title==b.title};const bool changed=i.state->addValidated(std::move(b));if(!changed){i.importApplying=false;i.importVisual=false;i.importTarget.reset();}return changed;}
void ReaderPreview::queueCapacityAvailable(){impl_->state->queueCapacityAvailable();}
void ReaderPreview::upload(gpu::Renderer&r){auto&i=*impl_;need(!i.renderer||i.renderer==&r,"Reader resources belong to another renderer");i.renderer=&r;if(i.seen)i.canvas.upload(r);if(!i.pose)return;if(i.closing)i.closing->scene->upload(r);if(i.menu)i.menu->scene->upload(r);const auto revision=i.registration.stats().geometryRevision;if(i.registrationUploadedRevision!=revision){i.registration.uploadGeometry(r);i.registrationUploadedRevision=revision;}}
std::span<const gpu::LayerCompositionEntry>ReaderPreview::entries(){auto&i=*impl_;i.count=0;if(!i.pose)return {};i.composed[i.count++]=i.canvas.entry();if(i.closing)i.composed[i.count++]=i.closing->scene->entry();if(i.menu)i.composed[i.count++]=i.menu->scene->entry();i.composed[i.count++]={&i.geometry,i.registration.draws()};return {i.composed.data(),i.count};}
void ReaderPreview::collected(gpu::Renderer&r){auto&i=*impl_;for(auto it=i.retired.begin();it!=i.retired.end();)if((*it)->scene->release(r))it=i.retired.erase(it);else ++it;}
void ReaderPreview::release(gpu::Renderer&r){auto&i=*impl_;need(i.canvas.release(r)&&(!i.menu||i.menu->scene->release(r))&&(!i.closing||i.closing->scene->release(r))&&i.registration.releaseResources(r),"Detach Reader entries before release");for(auto&v:i.retired)need(v->scene->release(r),"Detach retiring Reader menu before release");i.retired.clear();i.registrationUploadedRevision=0;i.renderer=nullptr;}
}
#endif
